### ISSUE TITLE
Upgrade JSCoverage to JSCover

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1050]
[JSCoverage](http://siliconforks.com/jscoverage/), which we are using now, was replaced with [JSCover](http://tntim96.github.io/JSCover/).  Let's upgrade at some point.

No rush, but @shunter brought it up so I wanted to make a note.

**Comment by pjcozzi** [comment]
JSCover requires Java so I would avoid it since we just removed the Java dependency for building Cesium.  Istanbul is probably the front runner.  Blanketjs is not as actively developed.

**Comment by mramato** [comment]
I've been meaning to update this issue to mention that `istanbul` has become pretty standard and I've used it in several projects.  Much nicer results than our existing solution.  Ultimately, we probably want to move to a karma/jasmine/istanbul, which will allow for automated testing without having to manually fire up the browser (and is all node based and cross-platform).  I just haven't have a chance to look into what it would take to refactor Cesium to do it (setting up this kind of configuration from scratch is dirt simple).

**Comment by mramato** [comment]
Now part of #3571
