### ISSUE TITLE
Scale labels based on distance

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1075]
CC #93 and #1074

**Comment by pjcozzi** [comment]
For signed distance fields, this is a useful read: http://www.essentialmath.com/blog/?p=111

**Comment by pjcozzi** [comment]
Also see http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/

**Comment by tokyovigilante** [comment]
There's a Metal implementation of SDF here - http://metalbyexample.com/rendering-text-in-metal-with-signed-distance-fields/

**Comment by pjcozzi** [comment]
Cool, thanks @tokyovigilante!

**Comment by bagnell** [comment]
For resources on different font rendering methods, including SDF, see - http://aras-p.info/blog/2017/02/15/Font-Rendering-is-Getting-Interesting/
