### ISSUE TITLE
Improve orientation usability

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1107]
One topic that pops up over and over again on the mailing list is primitive orientatiaon.  It would be very beneficial to add something like `EulerSequence` and `YawPitchRoll` objects to Cesium and have `fromYawPitchRoll` or `fromEulerSequence` functions on `Quaternion` to allow for users to easily construct orientations and pass them to primitives.

We could also allow orientation in CZML files to be specified in these ways.

I'm pretty sure we have C# code that can be ported to Cesium for this.

**Comment by bagnell** [comment]
This was added in 1.6.
