### ISSUE TITLE
Animation widget performance bottlneck

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1148]
Either load simple.czml into Viewer or use the [Sandcastle example](http://localhost:8080/Apps/Sandcastle/gallery/CZML.html) (local link).  Chrome shows laying out the animation widget each frame as 16% of the rendering time.  This is because of the time string on the SVG.  With such a large percentage of time being eaten up per-frame (Chrome timeline shows 3ms) this is a performance killer.

I'm not  sure if it's due to SVG, or if it's simply related to how the SVG is laid out, but this really needs to be fixed.

**Comment by mramato** [comment]
Whatever I thought I saw 20 months ago doesn't appear to be there now, and toggling the animation widget on or off has no affect on the fps.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:54969 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZmSD2-003bdc-L1
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:59:37 -0500
Date: Wed, 14 Oct 2015 12:59:36 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1444852776;
	bh=LMtlYPaSNZE0o0KB5AhjLvEV7nm9LasMFrtTkzep1lg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qsWymwc1oSJxD4tfJuS267ObRKmKhLGiIq7fedvcF9mOnjFH/Q1SDClMSlrHND5ah
	 PcyWmQGamyMoz2gXBJz06bp0Zx2f/Ml19P6cavOXv0VJQQJ5xalILS093GY5zP1fra
	 hxN2WHzNFi3TmuVJFmdxPXEu97QNGSmzcZ+h09ZU=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:54856 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZmSD1-003bbE-Py
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:59:36 -0500
Date: Wed, 14 Oct 2015 12:59:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1444852775;
	bh=mSfvIff8/YEzSWg8S5AUOHkC4eVAkWNuL375+2gQgRM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=U+HPwhdyYOqGpKiy8GDrs5LrzkacrE5ORNknsj/Z1xHkyKZi6RdGOucmU7045Onke
	 KvLUM2oNH+GMjgmKphf5zbHXTs1s9RGRRJxGJLL3vKE3tkR9PKOQgXBZ1dfGaaeMoq
	 PI/tWsvqtFY3bSTgGw7CasAfYUnhK7vvTmJZJAOo=
