### ISSUE TITLE
Pass uniforms to material constructor

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1185]
Low-hanging fruit...

- [X] **Part 1**

Instead of writing

``` javascript
var polygon = new Polygon();
polygon.material = Material.fromType('Color');
polygon.material.uniforms.color = {
  red : 1.0,
  green : 1.0,
  blue : 0.0
  alpha : 1.0
};
primitives.add(polygon);
```

I want to be able to pass my overrides for the default uniform values to `fromType`

``` javascript
var polygon = new Polygon();
polygon.material = Material.fromType('Color', { 
  color : {
    red : 1.0,
    green : 1.0,
    blue : 0.0
    alpha : 1.0
  }
});
primitives.add(polygon);
```

So that I can construct `polygon` in one line without needing an instance:

``` javascript
primitives.add(new Polygon({
  material : Material.fromType('Color', { 
    color : {
      red : 1.0,
      green : 1.0,
      blue : 0.0
      alpha : 1.0
    }
  })
}));
```

- [ ] **Part 2**

(Part of #640).  Replace `Material.fromType` with a new property in the object literal passed to the `Material` constructor.

``` javascript
new Material({
  type : 'Color',
  uniforms : {
    color : {
      red : 1.0,
      green : 1.0,
      blue : 0.0
      alpha : 1.0
     }
  }
});
```

Here `type` is used to indicate a known material type, as opposed to `fabric` which allows the entire Fabric JSON.

Add tests and update the Sandcastle examples.

**Comment by AnandDhoot** [comment]
Hi, 
I would like to take up this issue. I have just downloaded and built the codebase on my machine. 
Request your guidance on how to proceed on my first bug fix!
Thank you

**Comment by pjcozzi** [comment]
Thanks for the interest, @AnandDhoot.  This issue is not very high priority right now.  May I suggest you consider #1670?

**Comment by AnandDhoot** [comment]
Sure! Thanks for your reply.

**Comment by pjcozzi** [comment]
Insufficient priority.
