### ISSUE TITLE
Inconsistent 3D and 2D camera controls

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1200]
Run the [CZML Sandcastle demo](http://cesium.agi.com/Cesium/Apps/Sandcastle/index.html?src=CZML.html), click on the Molniya satellite to follow it.  Note that we use the left mouse button to rotate around it.

Switch to 2D.  The left mouse button no longer rotates; instead we need to use the middle mouse.

I know this is by-design-ish, but the typical user will not figure it out.

CC #453

**Comment by mramato** [comment]
Since we closed #453, I'm closing this as well.  We can revisit the issue if it ever becomes a problem.
