### ISSUE TITLE
Missing Bower package

### ISSUE THREAD

**Issue by sgentile** [AnalyticalGraphicsInc/cesium#1210]
Could a bower package be added to the bower repository ?

Thanks
Steve

**Comment by mramato** [comment]
I took another look at this and it seems the correct way to handle bower in a project like Cesium is to create a bower-specific repository, which makes the entire process trivial.  This is what angular does. I just need to figure out if bower can support both AMD and traditional development in a single package or if we need two repositories (one for AMD and for the combined Cesium).

**Comment by samy100** [comment]
+1

Right now I pull from bower using the repo URL directly and building it myself. Would be nice that cesium has its own --> maintained <-- repository

**Comment by ron212** [comment]
+1

**Comment by pksorensen** [comment]
This comes up as a top result when googling cesium and bower. Would be nice if a conclussion was at the end of this thread. Either with its done or current status :) Just some feedback. Great job on the project.

**Comment by pjcozzi** [comment]
The Cesium team doesn't maintain a bower package, but there are a few unofficial ones:
* https://libraries.io/bower/cesium-bower
* https://libraries.io/bower/cesium
* https://libraries.io/bower/cesium.js
