### ISSUE TITLE
CSS documentation...

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1254]
Users who would like to tweak the styling of our widgets need to override our default CSS properties, for example `cesium-widget-small-icon` controls the default button size for the toolbar buttons.  We have absolutely no documentation for any of it.  I'm not sure if we could generate CSS documentation with our existing tools, or if we just rely on inline comments in the CSS file to inform people about what they can tweak.

**Comment by pjcozzi** [comment]
From three years ago:

> I'm okay with closing this, though I think our overall CSS strategy needs to be reevaluated at some point in the future.

Closing for now.
