### ISSUE TITLE
touchcancel

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1286]
From here: https://plus.google.com/u/0/+RickByers/posts/Ny6ZXuzWdN5
The link deals mostly with scrolling, but it applies to anyone listening to `touchend`.  

There are multiple areas in the code where we listen to `touchend` events, but we never subscribe to `touchcancel`.  This creates some nasty bugs where our `touchend` code never gets called (which I've seen first hand on Android but didn't know what the problem was until I stumbled across this link).  We need to subscribe to both and terminate our touch event accordingly.  

CC @emackey @bagnell

**Comment by twpayne** [comment]
I'm looking at this now.
