### ISSUE TITLE
WebGL warnings in Firefox

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1317]
There are new WebGL warnings in Aurora (Firefox 27)

> Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture, with a minification filter requiring a mipmap, and is not mipmap complete (as defined in section 3.7.10).

I believe this is a Firefox bug ([issue](https://bugzilla.mozilla.org/show_bug.cgi?id=943433)) since we later set the texture filters before rendering.  We can workaround it if need be.

**Comment by mramato** [comment]
Since this is a longstanding Firefox issue, do we just want to close this?  There's noting we can do about it on our end and if anyone searches for the issue in our repository they'll still find it even if it's closed.

**Comment by pjcozzi** [comment]
Sounds good.
