### ISSUE TITLE
Multiple end point URLS for WebMapServiceImageryProvider

### ISSUE THREAD

**Issue by ramotswa** [AnalyticalGraphicsInc/cesium#1327]
Hello,

So I will try and help out on this, because I think I know what I'm doing, and the main learning curve here for me is contributing to your code and using github!

But just a few questions to make sure I'm going down the right path;

There are two things we need to keep in mind here - clearly 'subdomains' (from the Bing layer code), these are actual subdomains with Bing, but I presume we want to give the user something like what openlayers does? eg either a single url string, or an array of urls:

<pre><code>
new Cesium.WebMapServiceImageryProvider({
           url: 'someURL' OR ['URL1','URL2'],
            layers: layerArray,
            parameters: {
                transparent: 'true',
                format: 'image/png'
            },
            proxy: new Cesium.DefaultProxy(proxy)
        })
</code></pre>

Now what I just want confirmation on, is that the browser limitation looks at the proxy too right? - i.e. if I had 2 different urls but they both had to go via the same proxy, that would defeat the point, and the browser will treat both of them as 1 end point. 
So we need to give the user a way of specifying different proxies? So again, something like

<pre><code>
new Cesium.WebMapServiceImageryProvider({
            url: 'someURL' OR ['URL1','URL2'],
            layers: layerArray,
            parameters: {
                transparent: 'true',
                format: 'image/png'
            },
            proxy: new Cesium.DefaultProxy(proxy)
OR
            proxy: [new Cesium.DefaultProxy(proxy), new Cesium.DefaultProxy(proxy2)]
        })
</code></pre>
?

We don't actually need both - I think if you have different proxy urls but the same WMS url endpoint, the browser still treats them as different? 

Thanks.
Toby

**Comment by mramato** [comment]
@kring is this issue still valid given the `subdomains` options that was recently added?

**Comment by kring** [comment]
`WebMapServiceImageryProvider` now supports subdomains so I think that addresses the original problem.  It still could be a useful addition to make the proxy support subdomains, too.  I'm going to close this, and if someone would like to request that feature (subdomains for the proxy) please write a separate issue.
