### ISSUE TITLE
Tweak Bing maps missing tile detection

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#1353]
From the Bing Maps team:

> to solve the problem of detecting missing tiles you mention below, we do have a URL parameter you can add: 
> 
> n=z
> 
> This will produce a zero-length response body for missing tiles instead of serving the no-camera image. This should be a lot easier to detect and would work in cross-domain scenarios.

**Comment by KeyboardSounds** [comment]
While this should work, I couldn't find the `n=z` url parameter documented anywhere [here](https://docs.microsoft.com/en-us/bingmaps/rest-services/)-- do we want to be using an undocumented feature of the API?

**Comment by shunter** [comment]
The quote in this issue was from an email from a member of the Bing Maps team in regards to NORAD Tracks Santa from 2013.  You're right that it's not directly documented, but the new Bing styles use it in their image URL template, and it's alluded to in the sample data for these services:

https://docs.microsoft.com/en-us/bingmaps/articles/geospatial-endpoint-service
