### ISSUE TITLE
Evaluate Jasmine 2.0

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1366]
[Jasmine 2.0](http://jasmine.github.io/2.0/introduction.html) was just released.  We should take a closer look to see how hard upgrading is given all our custom changes.  If it is a ton of work, we can hold off until we decide on Intern, #735

**Comment by pjcozzi** [comment]
@kring any ETA on this?  No rush, I just want to avoid a big merge conflict with #2056 (no action there yet).

**Comment by kring** [comment]
I hope to get back to it really soon, especially since the merge gets more painful every day even in the absence of big changes like #2056.

**Comment by pjcozzi** [comment]
Upgraded in #2495
