### ISSUE TITLE
Inertia bounce interferes with camera flights in 2D

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1401]
1. Start Cesium Viewer
2. Switch to 2D
3. Zoom out with the wheel to get a good camera "bounce" at max distance
4. Quickly enter a location in the Geocoder and fly there

The flight will happen but then you will get sent back to where you started.  I can reproduce this easy enough, but it is timing dependent, so if you have problems let me know.

CC @bagnell

**Comment by mramato** [comment]
I took a quick look at this and while the bug manifests differently, the end result is that bounce inertia will end up interfering with camera flights.  I'm not sure there's an easy to fix this because the `SceenSpaceCameraController`is what knows about inertia while the `Camera` itself and the flights know nothing.  We should probably take a hard look at camera architecture for Cesium 2.0

**Comment by bagnell** [comment]
There's no bounce back animation so I can't reproduce the original issue. Does it happen with inertia as well?

**Comment by hpinkos** [comment]
@mramato I can't reproduce this.  Can this be closed?

**Comment by mramato** [comment]
Looks like we got rid of the inertial bouncing at some point (probably when we added infinite 2D) either way I can no longer reproduce this either.
