### ISSUE TITLE
Allow customization of modules in Cesium.js

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#1494]
Right now, all modules are dumped onto the global Cesium object in the combined file.  This includes internal modules which are undocumented and are not intended for users, as well as useless documentation-only modules like `Packable`, etc.

We should add a way to exclude modules completely from the Cesium object.  This can be as simple as a special comment at the top of the file, which we can look for in `createCesiumJs.js`.

We should also allow the "path" to the module to be customized as well.  This would allow us to split up the "pile of functions" modules, such as `Transforms`, so that we can selectively import just a single function, without impacting the public API.  (In that particular case, we would get rid of the need for every geometry worker to include all the EOP/XYS code).

**Comment by pjcozzi** [comment]
Close as duplicate with #2524?

**Comment by mramato** [comment]
Any changes at this point will be majorly breaking, so I agree we can close and it will be automatically revisited when we implement ES6 modules.
