### ISSUE TITLE
Multi-frustum artifact for Polygons on the surface

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#1506]
Polygons on the surface are tessellated differently than the ellipsoid. To avoid z-fighting artifacts, we write depth for opaque polygons, but do not for the ellipsoid and instead use the depth plane. Clearing depth before rendering the next frustum causes artifacts at the boundaries:
![image](https://f.cloud.github.com/assets/1494815/2263822/67523dc0-9e6a-11e3-99a5-3c98f7c0c057.png)
Everything rendered is correct after the furthest frustum is rendered. When the next frustum is rendered and if the far plane of the frustum intersects the polygon and ellipsoid where the ellipsoid surface is above the polygon, the ellipsoid surface will be rendered to the fragment that has already been writen to by the polygon in the previous frustum.

One solution is to draw each frustum in a separate FBO with color and depth attachments, then resolve the depth in a final pass. We would need depth texture or MRTs support.

**Comment by pjcozzi** [comment]
@bagnell do you think polygons on terrain will fix this?

**Comment by pjcozzi** [comment]
@bagnell is this still an issue with the ground primitive?  If not, close this.
