### ISSUE TITLE
GoogleEarthImageryProvider requestType

### ISSUE THREAD

**Issue by nirko** [AnalyticalGraphicsInc/cesium#1532]
Hi
Currently there is no way to set requestType in GoogleEarthImageryProvider contractor and it's const.
this._requestType = 'ImageryMaps';  line 113.
this cause errors while loading vector data.
when setting it using the provider._requestType = 'VectorMapsRaster'; it works.
Need to add it to the contractor.

**Comment by pjcozzi** [comment]
@nirko would you be able to open a pull request for this? Here's [instructions](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request).

**Comment by pjcozzi** [comment]
Closing, no update in 3 years and potentially OBE by the recent GEE provider.
