### ISSUE TITLE
Abrupt lighting change

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1578]
Open the [corridor Sandcastle example](http://localhost:8080/Apps/Sandcastle/index.html?src=Corridor.html&label=All).  Zoom in and tilt the view.  The green corridor will appear to blink perhaps when it changes frustums?

![image](https://cloud.githubusercontent.com/assets/782098/2538865/6fd1d856-b5c2-11e3-8024-81239c9d1ea6.png)

![image](https://cloud.githubusercontent.com/assets/782098/2538869/75c756e6-b5c2-11e3-93aa-ea5e988ce9fb.png)

Most likely OIT related.  Compare to [b26](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Corridor.html&label=All).

**Comment by WilsonMuktar** [comment]
not fixed ?

**Comment by WilsonMuktar** [comment]
i'm using cesium to generate colored map, look like below : 
![120006000](https://cloud.githubusercontent.com/assets/13670967/9325198/0ac32c16-45c3-11e5-9ad5-efcf0115085d.png)

can anyone help me to be fix it ?
the color didn't fully the same, some of them become more darker.

**Comment by mramato** [comment]
There is no simple solution to this problem at this time (which is why this issue is still open).  We have a longer term roadmap to refactor the lighting system but no ETA as to when it will happen.

**Comment by pjcozzi** [comment]
Closing as duplicate with #1825.
