### ISSUE TITLE
Create sample CZML utilizing all current graphics

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#1649]
As we add more capabilities to the DynamicScene/CZML layer, we should maintain a sample CZML file that demonstrates all primitives, with examples of constant/interval/sampled properties.  It doesn't have to be a realistic example, since it would serve as a catalog of what's possible, and also as a quick visual smoke test.

**Comment by pjcozzi** [comment]
Closing as duplicate with #3027
