### ISSUE TITLE
BillboardCollection test failure on AMD

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1660]
In Chrome and Firefox.

![image](https://cloud.githubusercontent.com/assets/782098/2821308/b6004064-cf04-11e3-8815-b675ed1dc236.png)

**Comment by pjcozzi** [comment]
This is no longer an issue with the latest AMD driver and browsers.  @mramato do you still see this on HD 4000?

**Comment by mramato** [comment]
I don't think so, but I'll confirm when I get home and close if so.

**Comment by mramato** [comment]
I am getting 4 failures on the HD 4000 in Chrome, but I don't get this specific error.
