### ISSUE TITLE
Consistently document properties for ease of use

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1661]
The general pattern we follow in much of our code is that documentation for properties which are read/write start with `Gets or sets` while properties that are readonly start with just `Gets`.  This makes it easy for the user to tell if a value is user-settable or not.  We should update the doc for all properties and public variables to match this pattern.

**Comment by manujain** [comment]
@mramato , if this issue is free, can I work on it? Please guide me to the docs which need changes. Thanks.

**Comment by mramato** [comment]
You are more than welcome to work on this.  I would suggest updating a few files at a time to start, then open a PR to get feedback.  This will be easier than trying to update them all in one pass.  We also just merged a big pull request into master, so I would make sure you are up to date before you start.  Thanks!

**Comment by manujain** [comment]
@mramato , can you give the links of docs which need changes? Thanks!

**Comment by mramato** [comment]
There's no set list, you would need to basically start at the first file and work your way through all of them.  For each documented property, determine if it's readonly or not and update the description accordingly.  Also, for readonly items that don't have it, you would want to add the `@readonly` tag.
