### ISSUE TITLE
Cesium inspector: terrain crashes

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1665]
Run the [Cesium inspector example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html&label=Showcases).
- `Terrain` - `Pick a tile`.  Click on the globe without changing the view.
-  Click `NW` under `Select relative`.
- Check `Show only selected`.

I think we just need to tighten up what the UI allows a bit.  I also ran into exceptions about upsampling.

This is in b27 and master.

![image](https://cloud.githubusercontent.com/assets/782098/2841180/a4d58960-d063-11e3-9aaf-da71b2050d78.png)

**Comment by hpinkos** [comment]
Duplicate #2448
