### ISSUE TITLE
Test failure in Firefox on Mac

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1700]
Is this Mac only?  Can someone confirm?

In stable and aurora:

![image](https://cloud.githubusercontent.com/assets/782098/2965629/4aac319e-dafb-11e3-91a3-9e101986d89e.png)

Perhaps related-ish to #1568

**Comment by mramato** [comment]
While there are quite a few Firefox failures on the Mac mini, I can no longer reproduce this one.
