### ISSUE TITLE
Renderer/VertexArrayFacade sub-commits fails in Firefox

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1755]
`Renderer/VertexArrayFacade sub-commits.` has a bunch of failures in Firefox after upgrading to Nvidia's 337.88 drivers.  Chrome and IE both pass.  Windows 7x64 8800GT.

CC @pjcozzi @bagnell

**Comment by hpinkos** [comment]
Fixed in FF 44.0.
