### ISSUE TITLE
OSM 3d

### ISSUE THREAD

**Issue by vahid-sohrabloo** [AnalyticalGraphicsInc/cesium#1811]
Hi
First Thanks for your awesome map engine.
I have one Suggestion.
You can add OSM 3D  to view map. like this
http://demo.f4map.com/#lat=51.3340872&lon=12.3588510&zoom=16
Document about OSM 3d is here
http://wiki.openstreetmap.org/wiki/3D_Development

**Comment by pjcozzi** [comment]
This is in-progress with 3D Tiles.  Check out NYC: http://cesiumjs.org/NewYork/

Some [notes](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/TileFormats/OpenStreetMap/README.md).

Closing since this is being tracked in the `3d-tiles` repo.
