### ISSUE TITLE
IE 11 fullscreen timeline and animation widget

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1872]
Separating from #1616:

Timeline trackbar and Animation dial do not stay under the mouse when going fullscreen from an iframe.

**Comment by mramato** [comment]
FYI, this is fixed in Edge.  I think IE 11 is just on life support at this point, but I don't know for sure.  At some point we'll have to decide if when to just close IE 11 issues.

**Comment by pjcozzi** [comment]
I am OK with closing this.
