### ISSUE TITLE
Camera exception during morph

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1880]
In b29 and the `camera-terrain` branch.

* Run Viewer.
* Switch to 2D.
* Use the Geocoder to zoom to "Exton."
* Switch to Columbus Viewer.
* Part way through morph:

![image](https://cloud.githubusercontent.com/assets/782098/3459551/c62358f0-020d-11e4-94bf-f0b4bfaf14ed.png)

Not 1.0.

**Comment by pjcozzi** [comment]
Another way to reproduce this from #2825:

> * Run http://localhost:8080/Apps/Sandcastle/index.html?src=Camera.html&label=Showcases
> * Switch to 2D
> * Fly to rectangle
> * Then switch to CV.
>
> I'm pretty sure this is because the morph started before the flight finished.

**Comment by hpinkos** [comment]
Cannot reproduce.  Also, this looks like a duplicate of #1596
