### ISSUE TITLE
Making JSDoc more than just reference documentation.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1884]
Random idea.  JSDoc has built in mechanisms for including additional pages above and beyond the class references.  Tutorials is one of these: http://usejsdoc.org/about-tutorials.html

Should we consider moving our web-site tutorials into the main Cesium code-base and maintaining them there?  They would still be on the website, but be part of the generated documentation instead of as blog posts.

We could also include additional overview and reference documentation, not just tutorials.

Thoughts?

**Comment by hpinkos** [comment]
Yeah, I don't think this is one we'll go forward with.  Thanks @OmarShehata
