### ISSUE TITLE
WebMapServiceImageryProvider incoherence in tile size

### ISSUE THREAD

**Issue by kaktus40** [AnalyticalGraphicsInc/cesium#1886]
Hello,
I found in [WebMapServiceImageryProvider](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/WebMapServiceImageryProvider.js) these oddities:
- _tileWidth and _tileHeight are not use to make WMS request (see lines [144](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/WebMapServiceImageryProvider.js#L144) to [150](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/WebMapServiceImageryProvider.js#L150)). The real tile size must be defined in the WebMapServiceImageryProvider constructor thanks to "options.parameters.width" or "options.parameters.height"
- "options.parameters" isn't well documented. I had to find in source which parameter can be used.
- tileWidth (line [201](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/WebMapServiceImageryProvider.js#L201)) and tileHeight (line [219](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/WebMapServiceImageryProvider.js#L219)) return incoherent informations compared to "options.parameters.width" and "options.parameters.height". These incoherences make Cesium buggy when the tile size is different fram default size ie 256X256 pixels

Good luck

**Comment by pjcozzi** [comment]
@kaktus40 would you be able to open a pull request with fixes for these?

**Comment by kaktus40** [comment]
Hello,
with the refactoring of this class using UrlTemplateImageryProvider, the issue is obsolete. :-)

**Comment by pjcozzi** [comment]
Thanks for the update, @kaktus40!
