### ISSUE TITLE
CZML examples in documentation

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#1941]
Would it make sense to add CZML snippets to each object and complete examples that demonstrate the important features?

**Comment by pjcozzi** [comment]
Do we want to close this given the upcoming CZML examples in #3027?

**Comment by pjcozzi** [comment]
Closing as duplicate with #3027.  Once the examples ship with Cesium 1.15, we will add a link to them from the CZML Guide.
