### ISSUE TITLE
Make Camera scene mode independent.

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#2007]
Make camera properties scene mode independent like `Camera.transform`. 

For example, `camera.transform = Transforms.eastNorthUpToFixedFrame(origin);` works in all scene modes without any projection or swizzling components of the column vectors. This will add a little complexity to the camera properties, but simplify the rest of the API. Then, we can remove any "set cartographic" functions.

CC #1699.

**Comment by pjcozzi** [comment]
@bagnell is this still relevant?
