### ISSUE TITLE
Esri World Imagery rendering problem

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#2023]
Using Firefox 31 I'm seeing the following, which actually has "movement" in the problem areas.

![esriworldimagery_firefox31](https://cloud.githubusercontent.com/assets/4126790/3802067/c3b28c1e-1c0a-11e4-925f-35204335a0c9.png)

**Comment by mramato** [comment]
@GatorScott can you still reproduce this problem?

**Comment by GatorScott** [comment]
I can no longer reproduce this.  Closing.
