### ISSUE TITLE
Use of return value without checking for undefined

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2033]
In [Camera.js#L340](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.0/Source/Scene/Camera.js#L340) (among other places) we call `cartesianToCartographic` and then use the return value, without checking for `undefined`, even though the function is able to return `undefined` intentionally (for example if the input was at the Cartesian origin).

More generally, should we have code analysis tools pick up on this kind of stuff?  I imagine it's harder to get right with JavaScript than other languages, but for cases where the called function contains the actual text `return undefined;` I would think this could be automatically found.

**Comment by mramato** [comment]
@emackey are you okay with just closing this?  While cartesianToCartographic can return undefined, everywhere in our code where we use it should crash if Cartesian3.ZERO is passed in.  If we checked for undefined, we would still end up throwing a DeveloperError or RuntimeErrror.

If you want to keep this open, that's okay with me, but we should decide on what the correct course of action for fixing this would be.

**Comment by emackey** [comment]
I've forgotten what I was doing when I ran into this.  I'll reopen if it comes up again.
