### ISSUE TITLE
Using Material with PolygonOutlineGeometry

### ISSUE THREAD

**Issue by aramk** [AnalyticalGraphicsInc/cesium#2052]
In order to modify the color of polygon outlines, you can use the approach in the sandcastle which uses `PerInstanceColorAppearance` and then use:

```
var geometryAtts = primitive.getGeometryInstanceAttributes(geometry.id);
geometryAtts.color = ColorGeometryInstanceAttribute.toValue(fillColor);
```

The problem is that this needs `Primitive#update()` to be called before use, which I cannot guarantee. Using `Material` works fine for `PolygonGeometry` and you modify the color by setting it on `appearance.material.uniforms.color`. The same does not work for `PolygonOutlineGeometry` and I'm not sure why. Here is my construction code:

```
var outlineGeometry = new GeometryInstance({
  geometry: new PolygonOutlineGeometry({
    polygonHierarchy: polygonHierarchy,
    height: elevation,
    extrudedHeight: elevation + height,
    vertexFormat: VertexFormat.POSITION_AND_ST
  })
});

var outlineAppearance = new EllipsoidSurfaceAppearance({
  material: new Material({
    fabric: {
      type: 'Color',
      uniforms: {
        color: borderColor
      }
    },
    translucent: false
  })
});

var outlinePrimitive = new Primitive({
  geometryInstances: outlineGeometry,
  appearance: outlineAppearance
});
```

I get the following error:

> DeveloperError: Appearance/Geometry mismatch.  The appearance requires vertex shader attribute input 'st', which was not computed as part of the Geometry.  Use the appearance's vertexFormat property when constructing the geometry.

I am setting the correct `VertexFormat`, so I'm not sure why it's failing.

**Comment by pjcozzi** [comment]
Duplicate with #2174.  @aramk please reopen if there is another issue.
