### ISSUE TITLE
Improve ArcGIS server compatibility

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2058]
From the mailing list: https://groups.google.com/d/msg/cesium-dev/R_bw13WjRUQ/xiTRHAnr0xoJ It looks like there are two ways to retrieve imagery from an ArcGIS server and not all servers support both ways.  We should at least have a toggle or option (if not automatic detection) so that we can work on all servers.

**Comment by mramato** [comment]
@kring do you think this is something we'll ever do, or should we just close this?

**Comment by kring** [comment]
Well I've worked with a fair number of ArcGIS servers at this point, and have never seen one that requires `exportImage`.  Maybe it's an old version of ArcGIS or something?  In any case, these days you can just use `UrlTemplateImageryProvider` to access tiles using whatever URL you need, so I'll close this.
