### ISSUE TITLE
Support orthographic frustum in 3D

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2069]
Discussion: https://groups.google.com/forum/#!topic/cesium-dev/lOm1POOLxgs

**Comment by emackey** [comment]
More discussion: https://groups.google.com/forum/#!msg/cesium-dev/_ScHuVx7Zio/cQ3BZccAjMsJ

**Comment by WarpDrive** [comment]
Here's another https://groups.google.com/d/msg/cesium-dev/YkbYA5z2nj4/PZislAkrncgJ
Perhaps instead of (or in addition to) 3 pre-packaged combo buttons, users could select each aspect independently, subsequently letting them have any combination at their disposal.
-shape: ellipsoid or flat
-frustum: perspective or orthographic
-terrain: on or off

**Comment by emackey** [comment]
I really like the idea of disconnecting the ellipsoid-vs-flat selection from the ortho-vs-perspective choice.  The deeper levels of Cesium have this welded together pretty firmly, so it's not an easy fix.

**Comment by WarpDrive** [comment]
Ya I didn't see any easy way to change these aspects around back when I tried adding terrain to 2D mode, but I think it would be a neat feature to have.

So the typical user (not familiar with the jargon) can relate here are some ideas for labeling:
Eye - point eye or flat eye (perspective or orthographic)
Shape - ball or rectangle (ellipsoid or rectangle)
Surface - flat or hilly (terrain off or on)

point eye being perspective where all rays converge to a point
flat eye being orthographic where all rays are parallel to each-other

Just like shape changes has a cool morphing animation, perhaps so too can changes between point eye and flat eye, where opposite sides of the frustum move from being parallel to each-other to becoming angled to each-other, and vice versa.

This wouldn't have to preclude the current 3 pre-packaged options though, it could just be an additional custom option.
