### ISSUE TITLE
Home button does not work as expected when in Columbus view

### ISSUE THREAD

**Issue by github-linoy** [AnalyticalGraphicsInc/cesium#2073]
Environment details : Win 7 64 bit(IE, Chrome and Firefox)

Website URL :http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?source=/Cesium/Apps/SampleData/simple.czml

Steps to reproduce: 
1. Enter the URL: http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?source=/Cesium/Apps/SampleData/simple.czml in browser
2. Click on Columbus view
3. Pan/Zoom the map
4. Then click on Home button

Expected Result: 
Map should be returned to the home position

Actual Result: 
Map does not return to the home position
![home button does not work as expected with columbus view](https://cloud.githubusercontent.com/assets/8424329/3977474/93249f70-2839-11e4-917b-e3d87a4097f1.jpg)

**Comment by pjcozzi** [comment]
This is fixed in master (Cesium 1.11) and perhaps [older versions](https://github.com/AnalyticalGraphicsInc/cesium/pull/2825#issuecomment-116793851).
