### ISSUE TITLE
EPSG:3395 support

### ISSUE THREAD

**Issue by ezze** [AnalyticalGraphicsInc/cesium#2084]
It would be nice to have a support of Mercator projection using ellipsoidal equations ([EPSG:3395](http://epsg.io/3395)). I know it's not so widely used as Mercator projection on sphere ([EPSG:3857](http://epsg.io/3857)) and has more complex calculations but we feel a lack of it. For example, basic [Kosmosnimki](http://kosmosnimki.ru)'s coverages are supported in EPSG:3395 for a long time and we can't use them in Cesium now.

By the way, EPSG:3395 is already [supported](http://leafletjs.com/reference.html#projections-l.projection.mercator) by popular 2D map engine [Leaflet.js](http://leafletjs.com).

**Comment by pjcozzi** [comment]
Thanks again @ezze @zhhwdev.  To keep our GitHub issues manageable, I made a note of this in #3877.
