### ISSUE TITLE
On Mac Book Pro - Application site get crash automatically on firefox ( Version 31.0)  Browser 

### ISSUE THREAD

**Issue by github-satejd** [AnalyticalGraphicsInc/cesium#2091]
Environment : Macbook pro + Firefox browser ( Version 31.0) 
Website URL :

1)http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?source=/Cesium/Apps/SampleData/simple.czml
2)http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?source=/Cesium/Apps/SampleData/Vehicle.czml

Steps to reproduce:
1. Launch the website.on Mac Book Pro ( Firefox Browser Version 31.0) 
2. Use the application site for few minutes 
3. Now observe application site.

Expected Result:
User can use various aspects , operations of the site witout any problem  

Actual Result:
In Reality the application gets crash down automatically in between  forcing the user to close the browser .

Refer Video For Details :
https://docs.google.com/a/afourtech.com/file/d/0B8KM7n8RDSg_TllPd2lCSWpSTE0/edit

**Comment by pjcozzi** [comment]
Is this still an issue in the latest version of FF?
