### ISSUE TITLE
glTF aircraft example different in IE

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2106]
The Cesium Air example has black propellers in Chrome but white propellers in IE.

**IE 11**
![image](https://cloud.githubusercontent.com/assets/1495196/4121101/3c901dcc-32b8-11e4-9d4a-5b2aeb80f1e8.png)

**Chrome**
![image](https://cloud.githubusercontent.com/assets/1495196/4121109/4b150b8c-32b8-11e4-9267-3c163e4fb20a.png)

**Comment by hpinkos** [comment]
fixed
