### ISSUE TITLE
Imagery feature picking only works in 3D

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2115]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Web%20Map%20Service%20(WMS).html&label=Beginner

**Comment by tlpinney** [comment]
This occurs because the pickedPosition is coming back undefined in 2D mode. 

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ImageryLayerCollection.js#L365-L370

It may also be related to the issue #2480

**Comment by mramato** [comment]
This recently came up [on the forum](https://groups.google.com/d/msg/cesium-dev/8o52AWvOh-o/E9q6J0l9T38J)

**Comment by kring** [comment]
I'm happy to look at this if it's specific to imagery layers, but it seems pretty clear it's a general `globe.pick` doesn't work in 2D, as described in #2480, right?

**Comment by hpinkos** [comment]
@kring yeah, I was looking at this a tiny bit earlier today, and `globe.pick` is definitely the problem.  It returns `undefined`.

**Comment by mramato** [comment]
Closing since this is a dupe of #2480
