### ISSUE TITLE
OIT artifacts

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2129]
![image](https://cloud.githubusercontent.com/assets/782098/4273879/d2d3f7dc-3cee-11e4-8d9f-aee25040ce42.png)

Could be an Intel bug: https://code.google.com/p/chromium/issues/detail?id=414280

Could also be our bug: https://twitter.com/pastasfuture/status/511538181691682816

Info on their implementation: http://floored.com/blog/2014/webgl-order-independent-transparency-single-render-target.html

**Comment by gberaudo** [comment]
I have the issue reported by @pjcozzi  and @mramato on my machine when OIT is enabled (Cesium 1.5). It disappears when disabling OIT:
```js
scene._oit.isSupported = function() {
    return false;
};
```
Tested on Ubuntu 14.10:
- Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06). 
- Mesa DRI Intel(R) Haswell Mobile
- GL_VERSION 3.0 Mesa 10.3.2

What is the consequence of disabling OIT?

**Comment by pjcozzi** [comment]
@gberaudo instead of using that workaround, set `orderIndependentTranslucency` to `false` when constructing `Viewer`:  https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/Viewer/Viewer.js#L217

For the consequence, see: http://cesiumjs.org/2014/03/14/Weighted-Blended-Order-Independent-Transparency/

**Comment by gberaudo** [comment]
Thank you @pjcozzi.
Added a comment to the Chrome bug https://code.google.com/p/chromium/issues/detail?id=414280#c9.
