### ISSUE TITLE
Billboard multifrustum clipping

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#2139]
First noticed this with NORAD Tracks Santa, but saw it again today.

Billboards appear to be clipped against the edge of the frustum.

![image](https://cloud.githubusercontent.com/assets/32828/4342160/803f0f10-4041-11e4-8db5-a9347b7c1adc.png)

Sandcastle example:

https://gist.github.com/shunter/ac663bf2b527bac7242b

**Comment by pjcozzi** [comment]
@bagnell will billboards on terrain help here?

**Comment by pjcozzi** [comment]
Duplicate with #4510.  Will add Sandcastle example there.
