### ISSUE TITLE
Double selection?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2176]
With the new [simplestyle example](http://localhost:8080/Apps/Sandcastle/index.html?src=GeoJSON%20simplestyle.html&label=Showcases), I double click on a billboard and get two selection widgets:

![image](https://cloud.githubusercontent.com/assets/782098/4506788/66bf578c-4b06-11e4-97a1-e818f171c520.png)

Clicking on another billboard results in just one:

![image](https://cloud.githubusercontent.com/assets/782098/4506801/86c7f03e-4b06-11e4-9bbb-907747832aa5.png)

**Comment by hpinkos** [comment]
@mramato I can't reproduce this.  Can you check if it's still a problem on linux?

**Comment by pjcozzi** [comment]
I can't reproduce this now in Chrome or Firefox on Mac.
