### ISSUE TITLE
Add "Are you sure?" prompt to Sandcastle navigation

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2178]
This could be a little tricky, but I think we should have some sort of "Are you sure" prompt if you try and refresh or navigate away from a Sandcastle example that has been edited.  While using Sandcastle for debugging code snippets, I constantly accidentally refresh the page (instead of hitting run) and lose my work.  My idea would be to store the complete text of the example (sans whitespace) when it is first loaded and then on navigation, compare the current code to the original code.  If they are different we prompt.  If they are the same we don't.

@emackey Does this sound feasible to you in the current architecture?  Is there something built in to CodeMirror that might help here?

**Comment by adi2412** [comment]
I can work on this. Can anybody give me some pointers to start off?

**Comment by ayk115** [comment]
I have solved this using onbeforeunload javascript event. Pull request on the way. Screenshots attached. 
 
![1](https://cloud.githubusercontent.com/assets/4329000/6561654/f2418fa4-c6b8-11e4-84a9-34c91d9f3ce4.png)
![2](https://cloud.githubusercontent.com/assets/4329000/6561655/f269c5a0-c6b8-11e4-98e1-3f39a434dff2.png)

**Comment by ayk115** [comment]
While researching for this bug, I went through the documentation of codeMirror. I came to know that codeMirror has been upgraded to version 5.0 and Sandcastle is still using version 4.6. So, should we upgrade? I don't know how much they've changed in the latest version, but it might be helpful to have it.

**Comment by pjcozzi** [comment]
I'm not very familiar with CodeMirror, but I think it is worth trying to upgrade (using a new branch off of master).  Please check to see if their license was updated at all to see if our [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) needs to be updated.

**Comment by emackey** [comment]
Fixed by @ayk115.  @mramato can you add him to Contributors.md?
