### ISSUE TITLE
Camera modified after morphComplete event

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2203]
Apparently we fire `Scene.morphComplete` before we are done messing with the camera.  Try this example code, which came from [a question on StackOverflow](http://stackoverflow.com/questions/26396604/setting-camera-position-after-scene-transitions).

```
scene.morphComplete.addEventListener(function (){
    console.log('Morph completed...');
    var west = Cesium.Math.toRadians(10);
    var east = Cesium.Math.toRadians(40);
    var south = Cesium.Math.toRadians(35);
    var north = Cesium.Math.toRadians(45);
    var rectangle = new Cesium.Rectangle(west,south,east,north);    
    window.scene.camera.viewRectangle(rectangle);
    console.log('Camera view rectangle updated...');    
});
```

**Comment by mramato** [comment]
I'm fairly certain both of these problems were fixed a while ago and using the sample code I was unable to cause a crash or unexpected behavior.  Can someone please confirm everything works for them as well and close this issue.  Thanks.

**Comment by bagnell** [comment]
I can confirm everything works.
