### ISSUE TITLE
Incorrect BillboardCollection bounding sphere

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2225]
Looks like an issue with the bounding sphere computation since once the bounding sphere goes out of the viewport, the billboard disappears.

![image](https://cloud.githubusercontent.com/assets/782098/4791221/bbbd9b4a-5dda-11e4-9e44-c00340f7f118.png)

**Comment by hpinkos** [comment]
@pjcozzi this looks fine in master now.  It must have been fixed somewhere along the way.
![image](https://cloud.githubusercontent.com/assets/3451886/8855723/bf60d950-3134-11e5-8a00-b027ba697462.png)
