### ISSUE TITLE
Quaternion interpolation issue

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2233]
@tfili already reported the details to @bagnell

**Comment by mramato** [comment]
Assuming this is still a bug (and any of you remember what the issue is) we should probably put some details here before people forget.  It's already been 4 months.

**Comment by hpinkos** [comment]
I'm closing this because it's been almost a year and this issue has no information in it.
@tfili @bagnell please open a new issue if you know what this was about.
