### ISSUE TITLE
Minor BoxOutlineGeometry cleanup

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2260]
Consider:
```javascript
var geometry = new BoxOutlineGeometry({
  minimumCorner : this._aabb.minimum,
  maximumCorner : this._aabb.maximum
})
```
This could benefit from:
* A `fromAxisAlignedBoundingBox`function.
* Maybe dropping `Corner` from `minimumCorner` and `maximumCorner` for consistency.

The same applies to `BoxGeometry`.

**Comment by abhishekvp** [comment]
Hi @pjcozzi,

I would like to work on this. Could you please explain me, what needs to be done?

Thanks.

**Comment by pjcozzi** [comment]
Thanks for the interest.  This is not priority for us right now.  I suggest building a simple demo app on Cesium.
