### ISSUE TITLE
Considering replacing throttleRequestByServer with RequestsByServer

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2268]
See 847fd9f74015b52f688f189bcfc2dc9e30924c5f

`RequestsByServer` allows checking to see if any requests will be allowed so, for example, we can sort requests before making any.  This is not important to expose now but perhaps will be of interest later.

**Comment by markerikson** [comment]
Would be nice if Cesium exposed the ability for the application to manipulate the throttling behavior (say, by changing the current max requests allowed).  Would be useful for bandwidth-sensitive situations.

**Comment by kring** [comment]
I made a small change in the `nm` branch awhile back to allow this:
https://github.com/AnalyticalGraphicsInc/cesium/commit/e9b0bae375d9db1570e8bc9624707b7aac0a5d30

**Comment by pjcozzi** [comment]
I'm going to replace `RequestsByServer` with a more general, Cesium-wide, scheduler for throttling requests that ensures different parts of Cesium can't starve each other.
