### ISSUE TITLE
Terrain and sky disappear with camera height near zero

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2271]
Discussion, code example, and partial workaround: https://groups.google.com/forum/#!topic/cesium-dev/87rvANHNnjs

Terrain tiles are horizon culled (which also affects [subsurface](https://groups.google.com/forum/#!searchin/cesium-dev/translucent$20terrain/cesium-dev/Z_bX7pr1sRg/JzJuxoxNE_4J)).  The sky command is executed so the shader is most likely returning an alpha of zero.

**Comment by pjcozzi** [comment]
Also reported here: https://groups.google.com/forum/#!topic/cesium-dev/CQ_jovXcXsk

**Comment by WarpDrive** [comment]
Only relatively flat tiles disappear. https://groups.google.com/d/msg/cesium-dev/OON3DghJS-4/csZA-Q6pF5gJ

**Comment by pjcozzi** [comment]
CC #2415

**Comment by pjcozzi** [comment]
It's easy to reproduce this, by zooming to the "Dead Sea" and then zooming in a bit more.

**Comment by pjcozzi** [comment]
@bagnell can you look at this and #2415 in time for 1.14?

**Comment by pjcozzi** [comment]
@bagnell can you please reply to the Cesium forum threads in this issue, and let them know that this fix will be in Cesium 1.14 on October 1?
