### ISSUE TITLE
Exception in CZML Sandcastle example 

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2285]
This might take 2 or 3 times to reproduce.
- Open the CZML Sandcastle example.
- Double click on the AGI billboard.  Zoom in so you can see the buildings on the imagery.
- Switch to 2D.  Zoom in again.
- Switch to Columbus view.

I don't know if the zoom has anything to do with it or if it is just the timing with the CZML file and primitives go in and out of the view frustum.

![image](https://cloud.githubusercontent.com/assets/782098/5054608/dfb2038a-6c24-11e4-8e82-296672f5ab26.png)

**Comment by hpinkos** [comment]
@pjcozzi I tried a few times but I couldn't reproduce this.  But I keep running into #1518 so it's hard to test.

**Comment by pjcozzi** [comment]
I reproduced it first try.

**Comment by pjcozzi** [comment]
I can't reproduce this any more either.
