### ISSUE TITLE
Throw exception if Primitive.modelMatrix changes in 2D or Columbus View

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2287]
Might as well throw if the primitive has more than one instance too.

"If the model matrix is changed after creation, it only affects primitives with one instance and only in 3D mode"

**Comment by manujain** [comment]
Hi
I would like to fix this up. Can you guide how to proceed forward? Thanks!!

**Comment by pjcozzi** [comment]
Hi @manujain.  Thanks for the interest.  Please read [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).  Then check out [Primitive.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Primitive.js).  In the `update` function, you'll want to look at `this.modelMatrix`, `this._modelMatrix`, and `frameState.mode`.

**Comment by manujain** [comment]
@pjcozzi , I think we need to add throw exception statement in "https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Primitive.js#L1214" . Am I right?

**Comment by pjcozzi** [comment]
Yes, in that area of the code, but we only throw if (the matrix changed and (the scene mode is in 2D/CV, or the number of instances is greater than one)).  Please include tests.

**Comment by pjcozzi** [comment]
And update the reference doc.

**Comment by manujain** [comment]
It is "else if" statement of "https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Primitive.js#L1220" - 
else if (this._numberOfInstances > 1 || (frameState.mode === SceneMode.COLUMBUS_VIEW || frameState.mode === SceneMode.SCENE2D)) {
        throw new DeveloperError('If the model matrix is changed after creation, it only affects primitives with one instance and only in 3D mode');
}
I think this would be correct.

**Comment by pjcozzi** [comment]
Have you set up a development environment (see [here](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Contributor%27s-Guide))?  Give it a try, write some tests, and see where it takes you.

**Comment by manujain** [comment]
I am building the environment. Can you assign this issue to me? As soon as I finish building I'll fix this issue. Can you also suggest some other bugs related to the project "Compass / Navigation Widget" og GSoC 2015. Thanks!

**Comment by pjcozzi** [comment]
> Can you assign this issue to me?

Consider it assigned.

> Can you also suggest some other bugs related to the project "Compass / Navigation Widget" og GSoC 2015.

@kring is the best person to help here.

**Comment by manujain** [comment]
@pjcozzi , can you tell how to write tests and update reference doc?

**Comment by pjcozzi** [comment]
For example tests, see [PrimitiveSpec.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Scene/PrimitiveSpec.js).  This is also the file you would add tests to.

The reference doc should be added to [Primitive.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Primitive.js) where you made the code change.  For example, see [Line 707](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Primitive.js#L707).

**Comment by manujain** [comment]
@pjcozzi , two tests are not passing -
updates model matrix for more than one instance in 3D with equal model matrices in 3D only scene
does not transform to world coordinates

**Comment by pjcozzi** [comment]
Do you know how to use the debugger?  Check out https://developer.chrome.com/devtools

**Comment by manujain** [comment]
@pjcozzi , the above two tests are now passing.
Now all the tests are passing. I want to ask that the tests -
https://github.com/manujain/cesium/blob/master/Specs/Scene/PrimitiveSpec.js#L514
https://github.com/manujain/cesium/blob/master/Specs/Scene/PrimitiveSpec.js#L537
https://github.com/manujain/cesium/blob/master/Specs/Scene/PrimitiveSpec.js#L563
 are passing means that update cannot be done in 2D, columbus view. Then how can we write tests to update the matrix in these specific views?
I've updated the reference doc also. After this I'll make a pull request.

**Comment by manujain** [comment]
@pjcozzi , issue solved, can you take a look at it?

**Comment by pjcozzi** [comment]
Thanks!  We will take a look soon; we are at a conference this week.

**Comment by manujain** [comment]
@pjcozzi , can you suggest me some more beginner issues to work on? Thanks!
