### ISSUE TITLE
Frustum-like artifacts when using OIT

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2327]
Load the [GeoJSON example](http://localhost:8080/Apps/Sandcastle/index.html?src=GeoJSON%20and%20TopoJSON.html&label=Showcases) and zoom in with the right mouse button.  On a machine with OIT enabled (and only certain graphics cards, I have an Nvidia 650TI) you will see a large frustum-like artifact as you approach the surface.  Whether it's a frustum problem or not, I don't know.  This issue has been there a long time; but it doesn't look like we ever wrote it up.

![image](https://cloud.githubusercontent.com/assets/1495196/5461223/5dc07de4-8537-11e4-8765-c4680ca4d4a5.png)

**Comment by mramato** [comment]
Me and @bagnell have discovered discovered this is an issue with the weighting function in `czm_alphaWeight`.  He's going to experiment with the different weighting functions and it should hopefully fix this issue.

**Comment by pjcozzi** [comment]
Is this still an issue?

**Comment by mramato** [comment]
This appears to be OBE and was probably fixes a long time ago.
