### ISSUE TITLE
Load CZML/GeoJSON from the clipboard

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2369]
As discussed in #2368, for debugging purposes it would be cool to be able to paste CZML or GeoJSON directly into the Cesium Viewer app and have it load.  This would avoid the annoyance of having to create a separate file to drag and drop for a given GitHub issue.

We could also considering adding such capability to the Cesium Inspector, rather than the Cesium Viewer app.

**Comment by ayk115** [comment]
@mramato I did some work on this issue. Please checkout the pull request.
The issue I face is how do I identify whether the text pasted is CZML or GEOJSON or KML? Once this can be detected, corresponding load functions can be called.

**Comment by GatorScott** [comment]
You need to look at the specifications for each format to determine how to identify them.  KML for instance is an XML document whose root node must be "Document".  Evaluating an XPath expression for the Document node is one way to test for KML.  This concept can be applied to CZML and GeoJSON as well.

**Comment by ayk115** [comment]
@GatorScott I created validator functions for CZML, KML and GEOJSON according to their specifications as you suggested. Please have a look at #2617, and suggest what more is required.
