### ISSUE TITLE
Another polyline precision issue?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2375]
As seen on the [forum](https://groups.google.com/d/msg/cesium-dev/4E1mqHUBP2E/46DdFa5iGCEJ).  Our new duplicate removal changes in 1.5 are causing CZML files that used to work in 1.4 to now crash in 1.5.

@bagnell is this new behavior "correct" or are the tolerances still wrong in some places?  If the behavior is correct, I should probably handle this somewhere in the entity pipeline to avoid throwing the exception; since we have a similar problem for KML.

Here's the CZML snippet that was provided.
```
[
  {
    "id": "document",
    "version": "1.0"
  },
  {
    "polyline": {
      "positions": {
        "cartographicDegrees": [
          -87.719606109668,
          43.759647034233,
          0,
          -87.71960610967,
          43.759647034233,
          0,
          -87.719606109669,
          43.759647034233,
          0
        ]
      }
    }
  }
]
```

Here's the same file, but with values pre-converted to Cartesian.
```
[
  {
    "id": "document",
    "version": "1.0"
  },
  {
    "polyline": {
      "positions": {
        "cartesian": [
			183589.97538701253,
			-4610333.314044575,
			4388842.362350027,
		
			183589.97538685286,
			-4610333.314044581,
			4388842.362350028,
			
			183589.9753869327,
			-4610333.314044578,
			4388842.362350027
        ]
      }
    }
  }
]
```

**Comment by GatorScott** [comment]
A couple of issues are exposed here.

First, removeDuplicates has created the condition (1 point left), so the item should simply not be drawn.

Second, we should probably be as tolerant of "bad" data as possible.  We could emit a GeometryError (or similar) exception in this case and let the application developer decide what to do.  Alternatively, we could silently ignore the item.

**Comment by pjcozzi** [comment]
@GatorScott and I talked a bit offline, and perhaps our exceptions are not, well, exceptional enough in cases like this.  For example, when the user gets data from the server and provides it to Cesium, is it really a `DeveloperError` if the points are too close together, if a polyline has only one point, or if a polygon has only two points.  Certainty in this case where Cesium is the one to strip it down to one point, I don't think we should throw.

**Comment by mramato** [comment]
Fix in above pull.

**Comment by GalacticalManiac** [comment]
@GatorScott @mramato Hey guys;  I wanted to ask will this allow points in the line to be drawn?  We have segments of polylines that are close and we are getting this error.  Example (in web mercator although we are converting to geographic before pushing to cesium): 
Point_0	-998.235016360454	998.688453477717
Point_1	-997.075348391704	998.688453477717	

I really appreciate your assistance.  If not, what can we do to get these rendering?  It is so essential for us...

Thanks!

**Comment by mramato** [comment]
That doesn't look like the same issue as above, and you are also using a polyline volume, which is totally different than regular lines.  Please update to the latest official Cesium version (1.5 as of this writing) and if the problem still persists, post about it on the [forum](https://groups.google.com/forum/#!forum/cesium-dev), preferably with a small complete example to reproduce the issue.  Please don't continue to comment on this issue, as it's closed and most likely unrelated.
