### ISSUE TITLE
2D camera exception

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2401]
From #2381:

> Go the [Viewer](http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html) on the website, zoom in to Exton, middle mouse click to rotate the view until the heading is about west, switch to CV.

**Comment by mramato** [comment]
This appears to be Chrome stable specific (does not happen in Firefox, IE, or in Chrome Canary). Can someone else confirm this?

**Comment by pjcozzi** [comment]
I can't reproduce at all now.

**Comment by mramato** [comment]
I've re-opened this because it manifests in other ways (as described in #2503, switching modes in the the KML bike ride example.)  It still appears to be Chrome only, I'm just not sure if it's a Chrome bug or on our end.

**Comment by hpinkos** [comment]
@mramato can you still reproduce this?  I can't

**Comment by mramato** [comment]
Looks like I can't.
