### ISSUE TITLE
Winding order bug in extruded polygons with holes?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2404]
Are extruded polygons with holes considered opened or closed?  Right now the DataSource layer sets them to closed, (which I assume is correct) but this results in interior walls being culled as in the below image:

![image](https://cloud.githubusercontent.com/assets/1495196/5793579/a3a7622e-9f17-11e4-878c-88a6f668aa31.png)

My assumption is that this a bug in the geometry; specifically I think [this line](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/PolygonGeometry.js#L505) is flipped and should be 
`if (windingOrder === WindingOrder.COUNTER_CLOCKWISE)`

If @pjcozzi or @bagnell can confirm either way, I'll open a fix (either in the Polygon code or the DataSource primitive batching code depending on the answer).

**Comment by pjcozzi** [comment]
@bagnell can you confirm please?  I believe @mramato is right since when ear clipping polygons with holes by finding mutually visible vertices, the winding order needs to be consistent for the newly formed polygon, which would mean CCW outer and CW inner.

**Comment by bagnell** [comment]
I can confirm that it should be `COUNTER_CLOCKWISE`.
