### ISSUE TITLE
Remove deprecated Camera.flyToRectangle and flyTo options

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#2425]
* The `direction` and `up` options to `Camera.flyTo` have been deprecated in Cesium 1.6. They will be removed in Cesium 1.8. Use the `orientation` option.
* `Camera.flyToRectangle` has been deprecated in Cesium 1.6. They will be removed in Cesium 1.8. Use `Camera.flyTo`.

**Comment by pjcozzi** [comment]
Deprecated in #2414
