### ISSUE TITLE
Refactor HTML sanitization strategy

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2430]
When we originally added HTML sanitization to the `InfoBox`, most of the HTML was coming from external data sources like CZML and GeoJSON.  With the elevation of the Entity API as the top level of Cesium, the current strategy is no longer viable.

Sanitization makes the `InfoBox` look broken by default. If a user creates an Entity and sets it description with HTML, there's a good chance they'll be disappointed in what shows up.  Sanitization should probably be opt-in.  I can think of two ways of doing this:

1. Entities could provide a way to be tagged so that the InfoBox knows if they require sanitization.  For example, CzmlDataSource could have an option indicating whether the data is trusted, if the data isn't trusted, it tags the entities it creates as needed sanitization.  The InfoBox itself still does the heavy lifting.

2. We remove sanitization from the InfoBox and promote sanization functionality to a top-level help function.  The out of the box data sources can then sanitize input data themselves if it is needed.  Users would then be responsible for sanitizing their own data.

I vote for option 2, since I think it provides the fexibility we need.  I think we were being too aggressive trying to sanitize everything for the user and people have come away with the wrong impression of InfoBox capabilities.  We are an engine so we should give users the tools they need but not make decisions like this for them.  Thoughts?

**Comment by emackey** [comment]
I'm OK with either one, but I do need InfoBox to have a way to support async descriptions.  Currently I'm using (abusing) the sanitizer to "look up" more info on the selected object, and I have it show the animated-three-bars icon during the lookup.

**Comment by pjcozzi** [comment]
I am, err, clueless about this code, but I agree that 2 sounds good.

**Comment by pjcozzi** [comment]
@mramato is there more to do here after the KML branch is merged?

**Comment by mramato** [comment]
This can be closed.  There's some odds and ends we might clean up later, but that has more to do with the InfoBox and nothing to do with sanitization.
