### ISSUE TITLE
Major regression in Firefox 35

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2431]
There appears to be a major ANGLE related regression in Firefox 35 (obviously Windows only).  This causes all existing versions of Cesium to render a lot of materials incorrectly.

![image](https://cloud.githubusercontent.com/assets/1495196/5947763/a2fddc4c-a70d-11e4-8fff-29d37d4e53f5.png)

This was on the DX 9 back end, not sure about DX 11. Disabling Angle fixes the problem.  I'll look into filing a Firefox bug, but someone should confirm that this isn't some weird bug on our end that Firefox is exposing.

**Comment by mramato** [comment]
Looks like this is a manifestation of [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1124453) which I found via [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1124187).

Setting WebGL context alpha to false affects all framebuffers, which causes anything with alpha to go haywire in Cesium. If I force alpha to true in Context.js, everything works (though I'm not sure of the full ramifications of this change).

**Comment by pjcozzi** [comment]
Chime in on those issues and let them know it affects Cesium.

We could workaround this by setting `alpha` to `true`, but it is a potential performance hit as it can make the browser compositor work harder.

Is this in any version of Chrome?  If not, we could just set `alpha : true` for Firefox as a workaround for a few months.

**Comment by mramato** [comment]
That's what I would do, check for Firefox 35 and force it to true.  We have a similar workaround already in place for Firefox 34, because that broke Cesium as well.

**Comment by pjcozzi** [comment]
OK with me.
