### ISSUE TITLE
Setting the camera's heading doesn't work in the southern hemisphere

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#2434]
Here's a simple Sandcastle example to show the problem:

```
var viewer = new Cesium.Viewer('cesiumContainer');
var toolbar = document.getElementById('toolbar');
var heading = document.createElement('input');
toolbar.appendChild(heading);
heading.addEventListener('focusout', function() {
    viewer.camera.heading = Number.parseFloat(heading.value);
}, false);
```

Enter 0 in the input box and tab out of it, and the camera doesn't move (north is still up, as expected).  Now pan the camera so that it's located anywhere in the southern hemisphere and do the same thing.  The globe flips upside-down so that south is up.

**Comment by kring** [comment]
(I know the `heading` property is deprecated; the behavior is the same with `setView`)

This worked in 1.5 so I'm marking it showstopper.  Also, the heading rotation in master is opposite what it is in 1.5.  pi/2 radians makes "up" point west in 1.5 and east in master.

**Comment by bagnell** [comment]
I followed your instructions and I couldn't reproduce it. Entering 0 in the box and tabbing out of it over the southern hemisphere orients it north.

**Comment by bagnell** [comment]
I decided to try it again and now I can reproduce it. I'm not sure why it didn't happen the first time.
