### ISSUE TITLE
Cesium prevents sliders from working

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#2435]
Try this Sandcastle example:
http://localhost:8080/Apps/Sandcastle/index.html?src=Imagery%20Adjustment.html&label=Showcases

The sliders can't be moved by dragging them.  Clicking works.  This is caused by Cesium canceling the document's mousemove event.  Some discussion here:
https://groups.google.com/d/topic/cesium-dev/Emt-CrGYulY/discussion

**Comment by kring** [comment]
Marked show stopper because it's a regression that breaks people's apps in mysterious ways.

**Comment by emackey** [comment]
git bisect has narrowed this down to #2408, either c5c440c6 or 2315709e.  /cc @bagnell
