### ISSUE TITLE
HomeButtonViewModel uses deprecated camera functionality

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#2437]
The `direction` and `up` parameters to `Camera.flyTo` have been deprecated but they're still used in `HomeButtonViewModel`:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/HomeButton/HomeButtonViewModel.js#L58

**Comment by mramato** [comment]
This is already fixed in the entity-zoom branch. But we can leave this open until its in master.

**Comment by emackey** [comment]
I know we're swamped, but it seems like very bad form to ship a release that prints the deprecation warning for users that click Home.  The average user won't know why they're seeing the message, and it makes many Sandcastle demos appear broken when you look at the console.

**Comment by mramato** [comment]
It's not going to ship, entity-zoom (and related branches) will be going into master tomorrow

**Comment by kring** [comment]
Ok, thanks guys!

**Comment by mramato** [comment]
Fixed in #2315
