### ISSUE TITLE
Add Columbus view support to the Ellipsoid

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#245]
Currently, the ellipsoid only draws in 3D.  It should also draw in Columbus view and 2D.  First, we need to cleanup the Columbus view architecture.

**Comment by mramato** [comment]
Given #3085, should we just close this?  No plans to have the moon in Columbus View mode anytime soon I imagine.

**Comment by pjcozzi** [comment]
Agreed
