### ISSUE TITLE
Camera Heading calculation

### ISSUE THREAD

**Issue by SlySnake** [AnalyticalGraphicsInc/cesium#2451]
Examing the heading get code in camera.js v1.6:

var heading;
if (Math.abs(direction.z) < Math.abs(right.z))
{heading = Math.atan2(direction.y, direction.x) - CesiumMath.PI_OVER_TWO;}
else {heading = Math.atan2(right.y, right.x);}
this._setTransform(oldTransform);
return CesiumMath.TWO_PI - CesiumMath.zeroToTwoPi(heading);

Using right vector to determine heading will fail if you're pitched and rolled. Direction is the only vector whom's heading isn't affected by roll. This code uses right vector when direction z is of greater magnitude than right z, but if you pitch and roll the heading value will be off. For example: if you pitch up >45deg and roll left 90deg the horizontal components of direction and right vectors face in opposite directions rather than 90deg apart.

I've been using atan2 with x and y reversed:
Math.atan2(direction.x,direction.y);
Which yields the same signed heading that Google Earth uses. Which can be easily converted to non-signed:
if(heading<0){heading+=2*Math.PI;}

Pitch +90 and -90 is a conundrum though when trying to calculate heading and roll. Heading should be NA because if you move forward your lon/lat doesn't change and that is sort of the definition of heading: how lon/lat will change when you move forward at that heading.

**Comment by bagnell** [comment]
Thanks again for trying out the new camera code and submitting this. The fix is in master. When the pitch is +/- 90, the heading is the angle from north of the camera's up vector and the roll is 0.0.
