### ISSUE TITLE
Picking precision issue

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2461]
1. Run the [simple-style example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=GeoJSON%20simplestyle.html&label=Showcases)
2. Zoom out so that all of the pins are lumped together.  Try and pick the top of the billboard, it fails to select.
3. If you continue to zoom in a little at a time, eventually you get close enough that the selection works.

You can always select the base of the image, it's only when selecting the top that there is a problem.

**Comment by pjcozzi** [comment]
@bagnell perhaps this is a culling issue with the billboard's bounding sphere that becomes evident because of the pick frustum.

**Comment by hpinkos** [comment]
@mramato was this fixed when we fixed the billboard bounding sphere?  It seems to work okay for me now.

**Comment by mramato** [comment]
Yes, and what a glorious day it was!
