### ISSUE TITLE
Problem with Primitive spec

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2463]
`Scene/Primitive failed geometry rejects promise and throws on next update.` does not run properly when running all unit tests against combined file with debug code removed.  I believe this is a problem with the test and the weird way it's trying to use an asynchronous web worker (I wrote the code and I was iffy about it at the time).

**Comment by mramato** [comment]
This was also discussed in #2495

**Comment by shehzan10** [comment]
As of v1.30, I don't see this failure (although I do see others). I ran the following steps after checking out the 1.30 release.
```
npm install && npm run build
npm run minifyRelease
cd build && npm start
# Open webpage and Run All Tests
```

Tested on Chrome stable (other failures seen) and Chrome Canary (no failures).

Is there anything I'm missing in reproducing this?

**Comment by hpinkos** [comment]
I don't see this one anymore either
