### ISSUE TITLE
LASSO or RUBBERBAND

### ISSUE THREAD

**Issue by kaktus40** [AnalyticalGraphicsInc/cesium#2471]
Hello,
reading the following discussion, do you think it's a good idea to had a tool to draw entities via mouse in Cesium (new branch) or should it be a plug in?

https://groups.google.com/forum/embed/?place=forum/cesium-dev&showsearch=true&showpopout=true&hideforumtitle=true&parenturl=http%3A%2F%2Fcesiumjs.org%2Fforum.html#!searchin/cesium-dev/lasso/cesium-dev/GDQE5HB9Q8k/KgB-AqDV_kMJ

**Comment by kaktus40** [comment]
Well, I'm not popular. I'll make a contribution with a drawHelper for entities but I don't know if this contribution should be a plug in or a real part of Cesium. Also I need your vision !

**Comment by pjcozzi** [comment]
Perhaps start with a plugin and then we can evaluate if it should go into core Cesium.

Please don't worry about the delayed response; the Cesium team is the most busy we have ever been.

**Comment by hpinkos** [comment]
I think this is outside of the scope of what we want to do for Cesium.
@pjcozzi do you think we can close this?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:13786)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZmS9y-003SMW-J7
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:56:27 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kLGSaSQ5p42eMNsP0DpFKBMn5/Q=; b=NcWQaV+GqaSuV4bJ
	8WGBLtzi3KfGzWi/gPnibaaNy+yN5wXbkpBuhrCTp/LgRJLS4MNQ4Phu1VUtERlL
	B+GNYG+2GSdYDf9BhjIfPyBjZzLjrEn0h0gmXN7G8Mim8wfS58eC5yeTCAH3B1AT
	fZndeZ85jwy3DXPoxAHJnXhgtBM=
Received: by filter0457p1mdw1.sendgrid.net with SMTP id filter0457p1mdw1.25366.561EB36743
        2015-10-14 19:56:23.70944485 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id 8DuIoMpOTw-d8w9mewLLFw
	for <greg@biomassiv.es>; Wed, 14 Oct 2015 19:56:23.701 +0000 (UTC)
Date: Wed, 14 Oct 2015 12:56:23 -0700

**Comment by pjcozzi** [comment]
I agree we can close this.  The plugin is welcomed, of course.
