### ISSUE TITLE
Starting in 2D mode breaks 3D mode.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2474]
1. Run the below example.
2. Switch to 3D.
3. Hit the `zoomTo` button
4. Terrain will be majorly busted (even though this is just using the ellipsoid provider).

To me it looks like tiles are being drawn in the wrong order so tiles in the back are overwriting tiles in the front, causing their skirt to show. Toggling different terrain providers after getting in this state does not fix the issue.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', { sceneMode : Cesium.SceneMode.SCENE2D });

var entity = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-110.0, 34.0),
    point : {
        pixelSize : 10
    }
});

Sandcastle.addToolbarButton('zoomTo', function() {
    viewer.zoomTo(entity, new Cesium.HeadingPitchRange(Math.PI / 2, -Math.PI / 4, 4000000));
});
```

![image](https://cloud.githubusercontent.com/assets/1495196/6085007/2893b56e-ae04-11e4-9d11-67020349d81e.png)

**Comment by bagnell** [comment]
I thought this might have been a recent commit where we disabled the depth plane in 2D. After a quick look at the order and render states of the tiles, everything looks good. Though if you replace `RenderState.partialApply` with `RenderState.apply`, everything renders correctly.

**Comment by bagnell** [comment]
This will happen if you start in 3D mode and switch to Columbus view with the changes in #2768. The change should be fine so the globe is probably setting the wrong render state.

**Comment by mramato** [comment]
I can no longer reproduce this, perhaps it was fixed by the other recent render state work.  Can someone confirm and close?

**Comment by pjcozzi** [comment]
I agree, it appears fixed.
