### ISSUE TITLE
inconsistence in documentation about PolylineGlowMaterialProperty

### ISSUE THREAD

**Issue by kaktus40** [AnalyticalGraphicsInc/cesium#2482]
Hello,
in MaterialProperty and even in Visualizing Spatial Data blog, you talk about PolylineGlowMaterialProperty but in Cesium source the real object is [PolylineGlowProperty](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.6/Source/DataSources/PolylineGlowMaterialProperty.js#L32) .

**Comment by mramato** [comment]
Thanks I just opened a PR to fix this.  The actual API has always been `PolylineGlowMaterialProperty` and the var in `PolylineGlowMaterialProperty.js` has been updated to match (as well as the doc).  It's actually the filename that controls how it appears in the public API.

**Comment by pjcozzi** [comment]
Thanks again for the report, @kaktus40.
