### ISSUE TITLE
2015 OSGeo Code Sprint #1

### ISSUE THREAD

**Issue by jawntehrani** [AnalyticalGraphicsInc/cesium#2483]
On the Cesium Up and Running Page, the following phrasing is a bit confusing... 

"While the application is small, it has everything we need to begin a larger one. We’ll break down the four most important lines.

1. The first step is to include Cesium.js in a script tag. This defines the Cesium object, which contains everything we need."

in particular, the "need to begin-include" because it gave me the impression I need to add these pieces. 

Recommend rephrasing to indicate these are the 4 core pieces of a CesiumJS App.

**Comment by jawntehrani** [comment]
In the Visualizing Spatial Data Tutorial:

I recommend flip flopping the following sentences ... 

When fill is set to true, the material property determines what that filling looks like. In our next example, let’s create a translucent blue ellipse. By default, fill is true and outline is false, so we only need to specify material.

and styling the last false consistently with the other properties.

**Comment by jawntehrani** [comment]
Keeping the content intact, consider making the Visualizing Spatial Data tutorial multiple mini tutorials.

**Comment by hpinkos** [comment]
Thank you for the recommendations! I tweaked the wording in the up-and-running page slightly, but I think the wording in the tutorial makes sense the way it is.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:60419 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZmS5O-003HRp-G3
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:51:43 -0500
Date: Wed, 14 Oct 2015 12:51:41 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1444852301;
	bh=ps1e0yymSd1wl1fsvQlwndrcKWOHsFGeGqAVxRf6orQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=obuSaG4AkKe/9FjpT7LahSMjoj/Vllt2hOPCgcO5zE3i7VAwlDH6RKvfytdVK/hsn
	 vQzg+v3+D3K/ZuxoEIaSZ21daoAmlcgufJfGH3pOIFHnK9Dreip+ONkgq3PBXN8uYy
	 8ZxltkF3eVkaTXkYZfP548KFXvw6GPg1epIqrj08=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:63490)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZmS5P-003HSg-Sl
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:51:45 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=WWSwqU8HLGbqggvteBXgm/HbmOE=; b=mO9Rtl5n4Azjwd6L
	SJU3dfLMp/CSn+TMGso9hEwqnuDl+mk6imhkYx22LjwF9B9yiebF2nBOY0K/Iyq7
	f+jvXENJHlsukuVDJ+tYRfiEFRDhh8sx1ioxlQ0bOtQt07dlNOJ451pS0b6Y+6pi
	rPb4sb0snfhE4p7XdxtnufFbkHA=
Received: by filter0857p1mdw1.sendgrid.net with SMTP id filter0857p1mdw1.6868.561EB24D4B
        2015-10-14 19:51:41.754733101 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id Wdwlg_FPScKR9E_kDPAeUw
	for <greg@biomassiv.es>; Wed, 14 Oct 2015 19:51:41.787 +0000 (UTC)
Date: Wed, 14 Oct 2015 12:51:41 -0700
