### ISSUE TITLE
Ability to adjust image material translucency

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2484]
There's currently no way (at least in the Entity API, but it wasn't clear to me on the lower-level material either) to indicate whether an image material is translucent and what the alpha level should be.

[fourm post](https://groups.google.com/d/msg/cesium-dev/ep9gKuIsibg/8P0w59FeUToJ)

**Comment by bagnell** [comment]
You can create a custom material (modified `ImageMaterial`):
```javascript
primitive.material = new Cesium.Material({
        fabric : {
            uniforms : {
                image : '../images/Cesium_Logo_Color.jpg',
                repeat : new Cesium.Cartesian2(1.0, 1.0),
                alpha : 0.5
            },
            components : {
                diffuse : 'texture2D(image, fract(repeat * materialInput.st)).rgb',
                alpha : 'texture2D(image, fract(repeat * materialInput.st)).a * alpha'
            }
        },
        translucent : true
    })
```
You can change the alpha with `primitive.material.uniforms.alpha` and make sure to set `primitive.material.translucent` to `false` if the alpha is ever set to `1.0`.

**Comment by mramato** [comment]
@bagnell Is there a reason we shouldn't just include this as part of the default image material?

**Comment by lilleyse** [comment]
Should this actually be closed? Like how `ImageMaterialProperty` has `transparent`, image-based material's could have something similar.

Brought up here: https://groups.google.com/forum/#!topic/cesium-dev/yleK3tQryyw with this Sandcastle code. It also feels strange that `MaterialAppearance.translucent` doesn't place the primitive in the `TRANSLUCENT` pass but only changes render states.

```
var viewer = new Cesium.Viewer('cesiumContainer', {
        'timeline': false,
        'animation': false,
        'homeButton': false,
        'geocoder': false,
        'fullscreenButton': false,
        'searchButton': false,
        'scene3DOnly': false,
        'orderIndependentTranslucency': false, // this does not appear to make a difference in this case
        'terrainShadows': Cesium.ShadowMode.DISABLED,
        'navigationHelpButton': false,
        'selectionIndicator': false,
        'sceneModePicker': false,
        'infoBox': false,
        'baseLayerPicker': false,
        'shadows': false,
});

viewer.camera.position = new Cesium.Cartesian3(-5077718.912198819, 3502183.4223716888, 1623436.7903385134);
viewer.camera.setView({
            orientation: {
                roll: 0.5073851418388697,
                heading: 2.120649161455434,
                pitch: 0.17861047868488078
            }
            });

function createRect (w, s, e, n, h) {
    return viewer.entities.add({
                 rectangle: {
                     coordinates: Cesium.Rectangle.fromDegrees(w,s,e,n),
                     height: h,
                     material: new Cesium.ImageMaterialProperty({
                         image: '../images/Cesium_Logo_overlay.png',
                         repeat : new Cesium.Cartesian2(1, 1),
                         transparent: true
                     })
                 }
    });
}

function createRectPrimitive (w, s, e, n, h) {
    var rectangleInstance = new Cesium.GeometryInstance({
            geometry : new Cesium.RectangleGeometry({
                rectangle : Cesium.Rectangle.fromDegrees(w,s,e,n),
                height: h,
            })
        });
        var prim = new Cesium.Primitive({
            geometryInstances: rectangleInstance,
            appearance: new Cesium.MaterialAppearance({
                material : Cesium.Material.fromType("Image", {
                    image: '../images/Cesium_Logo_overlay.png',
                    repeat : new Cesium.Cartesian2(1, 1),
                    translucent : true
                    //color: new Cesium.Color(1.0, 1.0, 1.0, 0.99)
                }),
                faceForward : false,
                translucent: true
            })
        });
        viewer.scene.primitives.add(prim);
}

var option1 = 1;
var option2 = 2;
var currentDisplayed = option2;

// option1: create rects as entities (shading/lighting glitch)
if (currentDisplayed === option1) {
    createRect (145.55805556, 14.66000000, 145.64861111, 14.73583333, 9000);
    createRect (145.61083333, 14.70638889, 145.70500000, 14.75007778, 9002);
}

// option2: create rects as primitives (alpha glitch)
else if (currentDisplayed === option2) {
    createRectPrimitive (145.55805556, 14.66000000, 145.64861111, 14.73583333, 9000);
    createRectPrimitive (145.61083333, 14.70638889, 145.70500000, 14.75007778, 9002);
}
```

**Comment by hpinkos** [comment]
@lilleyse both the examples look the same to me.  What is the issue you're seeing? Anything we do at the entity level can be done at the primitive level, entities are built on top of primitivies.

**Comment by lilleyse** [comment]
The entity example has inconsistent lighting when moving the camera which seems to be related to faceForward being on by default and not changeable. I don't know if this type of lighting is expected for faceForward or a separate bug.
<img width="228" alt="dark" src="https://cloud.githubusercontent.com/assets/915398/24357876/1f44fe5c-12cd-11e7-9403-dd199c8fe1f2.PNG">
<img width="194" alt="light" src="https://cloud.githubusercontent.com/assets/915398/24357875/1f43f61a-12cd-11e7-954e-61465f928bfd.png">

The primitive example has incorrect alpha blending where one rect clips the other because the primitives are not placed in the translucent pass. This is because the `MaterialAppearance.translucent` only affects the render state and not the pass, which is determined by the material's translucency, which for image materials is always false unless the color's alpha is < 1. `ImageMaterialProperty` in the entity API has a `transparent` property available that achieves this, but the base `Material` does not.

<img width="286" alt="clipping" src="https://cloud.githubusercontent.com/assets/915398/24357894/2fe2eea4-12cd-11e7-9682-52daff35b229.png">

**Comment by hpinkos** [comment]
I don't see that on my machine.  Either way, that looks like a separate issue than this one, can you open a new issue?
