### ISSUE TITLE
Billboard rotation accuracy issue

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2487]
Paste this into Sandcastle, switch to 2D or CV and then pan/rotate around the map.  The arrow points down by default, so the below should make it always point south.  However, when you pan around the map, the arrow rotates slightly.  It happens in 3D too, but is more noticeable in other modes.  @bagnell thinks it's a precision issue in the shader.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(0, 0, 0),
    billboard : {
        image : 'http://maps.google.com/mapfiles/kml/shapes/arrow.png',
        alignedAxis : Cesium.Cartesian3.UNIT_Z
    }
});
```

**Comment by emackey** [comment]
I'm having an issue with `alignedAxis` that believe this is the same bug (or at least the demo code above shows the same problem I'm seeing), so I'm adding my demo to this issue.  The `alignedAxis` when viewed off-axis doesn't point quite the right way.

Here's my [Many-Aircraft Demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=7a8de5a9878672b703e5260e8aaf6c34).  (It's a cool demo, if we get it working maybe it could be a Sandcastle Showcase demo of `VelocityVectorProperty`).

When viewed top-down, it looks mostly (but not 100%) correct:

![alignedaxistopdown](https://cloud.githubusercontent.com/assets/1235080/24714318/2c13cade-19f6-11e7-8627-ac230b031345.jpg)

But the further off-axis you go, the worse this problem gets:

![alignedaxissideview](https://cloud.githubusercontent.com/assets/1235080/24714350/3c585e5a-19f6-11e7-8585-41ff74200e4c.jpg)

Of course if you make it all the way to 90 degrees off-axis, you get gimbal lock and there's no way it can work.  But the problem gets bad long before you reach that point.  It feels like it's not taking the off-axis-ness (that's a term) into account properly.

**Comment by rahwang** [comment]
Came up in the forum: https://groups.google.com/d/msg/cesium-dev/dPJ-Ug1CM2E/N8RrhKruDQAJ
