### ISSUE TITLE
EllipseGeometry documentation is wrong

### ISSUE THREAD

**Issue by cesium-user2** [AnalyticalGraphicsInc/cesium#2494]
the "rotation" field is documented to be an "angle from north **(clockwise)**" . However it's seems to be **counter-clockwise**.

http://cesiumjs.org/Cesium/Build/Documentation/EllipseGeometry.html?classFilter=elli

In the context of rotation - it's also worth to say that the semi-major field is the value on the x-axis and semi-minor is the y-axis.

**Comment by abhishekvp** [comment]
Also the link to Cesium Sandcastle Ellipse Demo gives "RequestError: Unable to load gallery/Ellipse.html status: 404" in the Console. It should be changed from "http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Ellipse.html" to "http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Circles%20and%20Ellipses.html&label=Geometries"
