### ISSUE TITLE
PolylineGeometry colorsPerVertex seems broken in 1.6+

### ISSUE THREAD

**Issue by chris-cooper** [AnalyticalGraphicsInc/cesium#2516]
This code shows per-vertex colours in Sandcastle in 1.5 but not in 1.6 or master.  Is there an interface change I missed?

    var viewer = new Cesium.Viewer('cesiumContainer');
    var scene = viewer.scene;
    
    var instance = new Cesium.GeometryInstance({
      geometry : new Cesium.PolylineGeometry({
          positions: Cesium.Cartesian3.fromDegreesArray([
        0.0, 0.0,
        5.0, 0.0,
        5.0, 5.0
      ]),
          width: 5.0,
          vertexFormat: Cesium.PolylineColorAppearance.VERTEX_FORMAT,
          colors:[new Cesium.Color(1,0,0), new Cesium.Color(0,1,0), new Cesium.Color(0,0,1)],
          colorsPerVertex: true,
          ellipsoid: Cesium.Ellipsoid.WGS84  // <- required for Cesium 1.5
        }),
      id : 'object returned when this instance is picked and to get/set per-instance attributes'
    });
    scene.primitives.add(new Cesium.Primitive({
      geometryInstances : instance,
      appearance : new Cesium.PolylineColorAppearance({})
    }));

**Comment by mramato** [comment]
This was indeed a bug due to a typo. It will be fixed in 1.7.

**Comment by pjcozzi** [comment]
Fixed in #2529

**Comment by chris-cooper** [comment]
Great, thanks!
