### ISSUE TITLE
Possible to determine status of loading imagery?

### ISSUE THREAD

**Issue by asimps** [AnalyticalGraphicsInc/cesium#2518]
We display cockpit-view animation starting at takeoff.  When a user requests the animation, we want to wait until enough of the runway is rendered before moving the camera. Is there a way to tell how much of the terrain and imagery is loaded - something we can poll, or something that returns a callback?

**Comment by mramato** [comment]
I won't repeat myself from the other issue, but this should be all you need: https://groups.google.com/d/msg/cesium-dev/lz_BvEmWYq0/PTc9-32Oo28J

**Comment by mramato** [comment]
Just to clarify, there's no official support yet, but there's a workaround in that link.
