### ISSUE TITLE
camera.flyToBoundingSphere doesn't respect range when radius is zero

### ISSUE THREAD

**Issue by alexander-entin** [AnalyticalGraphicsInc/cesium#2519]
https://github.com/AnalyticalGraphicsInc/cesium/blob/1.6/Source/Scene/Camera.js#L2490-L2495
I'd say it should be wrapped with
if (!offset.range) { ... }
to only change the range if it wasn't provided

**Comment by pjcozzi** [comment]
Thanks for the report.
