### ISSUE TITLE
Remove samples prior to a certain time (SampledProperty)

### ISSUE THREAD

**Issue by speigg** [AnalyticalGraphicsInc/cesium#2520]
Is there a simple way to prevent sampled data from accumulating indefinitely, such as removing the oldest data?

**Comment by mramato** [comment]
There's no official way to do this yet, but we'll add one sometime soon.  In the meantime here is a code snippet you can use.  Keep in mind this is accessing private functions, so you'll want to stop using this as soon as the real version is available.

```javascript
function removeBeforeDate(property, time) {
    var times = property._times;
    var index = Cesium.binarySearch(times, time, Cesium.JulianDate.compare);
    if(index > 0){
        times.splice(0, index);
        property._values.splice(0, index * property._innerType.packedLength);
        property._updateTableLength = true;
        property._definitionChanged.raiseEvent(property);
    }
}
```

The above will work for `SampledProperty`, but not `SampledPositionProperty`, for positions, you can pass in `positionProperty._property` to the above function instead.

I'll leave this issue open until support is added; but please use [our forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) for any future questions, as we prefer to start all conversations there.  Thanks.

**Comment by speigg** [comment]
Thanks!

**Comment by speigg** [comment]
FYI, I had to add a tilde to make this work:

function removeBeforeDate(property, time) {
    var times = property._times;
    var index = ~Cesium.binarySearch(times, time, Cesium.JulianDate.compare);
    if(index > 0){
        times.splice(0, index);
        property._values.splice(0, index * property._innerType.packedLength);
        property._updateTableLength = true;
        property._definitionChanged.raiseEvent(property);
    }
}

**Comment by speigg** [comment]
Also, it would be nice to have an option for a fixed capacity (any time new samples are added, old ones are removed or overwritten if the capacity is reached)

**Comment by mramato** [comment]
Thanks for the suggestion.  Doing it automatically might be possible, but it could negatively affect performance because of memory churn.  We'll have to experiment with various strategies and see what works.

**Comment by willemvdg** [comment]
To avoid throwing away all samples I used
`if (index > 0 && (index < times.length))`
so there is always 1 sample left, which is good if you use ExtrapolationType.HOLD.

**Comment by shunter** [comment]
Also consider adding CZML capability to specify that an interval of samples should be removed from a particular property.
