### ISSUE TITLE
Cartesian3.prototype.equalsEpsilon doesn't accept absolute epsilon

### ISSUE THREAD

**Issue by alexander-entin** [AnalyticalGraphicsInc/cesium#2532]
Not a big deal, just inconsistency.

Cartesian3.equalsEpsilon(a, b, 0, 1) // checks against absolute epsilon
a.equalsEpsilon(b, 0, 1) // ignores the last parameter and thus checks for exact equality

**Comment by mramato** [comment]
Thanks for the report.  I just opened a PR to fix this.
