### ISSUE TITLE
Handling of zero magnitude cases in Cartesian3.normalize

### ISSUE THREAD

**Issue by SlySnake** [AnalyticalGraphicsInc/cesium#2540]
Zero magnitude causes divide by zero which causes NaN in place of what should be a number. Those NaNs often times cause a crash further down the road and the crash report only traces about 8 functions back. Hunting down the cause can waste alot of time. 

Perhaps have a quick zero magnitude check: if(cartesian.x==0 && cartesian.y==0 && cartesian.z==0)

Some possible actions if true:
console.log("warning: divide by zero");
Or set the result to all zeros instead of all NaNs.
Or set property .valid to false as you can't really turn a zero magnitude vector into unit length.

Perhaps normalize could be renamed to unitize to not be confused with the other definition of normal: a vector perpendicular to a plane.

**Comment by pjcozzi** [comment]
I suggest putting a wrapper around `normalize` in your application as we are unlikely to add a check in the low-level code to keep it lean and performant for the common case.

**Comment by SlySnake** [comment]
I understand about keeping the functions very lean, particularly ones called quite often and shouldn't involve checks for rare cases. Thanks, I'll be sure to instead wrap the check into another function that in turn calls normalize if non-zero.
