### ISSUE TITLE
Entity rectangle with image doesn't show image

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#2561]
The following Sandcastle example attempts to draw a rectangle to display the Cesium logo.  No errors are reported, but the rectangle is white.  I'm using master as of 2015-03-08T17:19Z.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var imageRectangle = viewer.entities.add({
    name : 'Rectangle with image',
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-110.0, 20.0, -80.0, 25.0),
        material : new Cesium.ImageMaterialProperty({
            image : "./images/Cesium_Logo_Color.jpg"})
    }
});

viewer.zoomTo(viewer.entities);

**Comment by bagnell** [comment]
I see a 404 error in the dev tools console when I run this example. Try `'../images/Cesium_Logo_Color.jpg'`.

**Comment by GatorScott** [comment]
Is there some way to push this information to the Sandcastle console?  As a novice Cesium developer, I'm not automatically tuned in to checking the dev console yet.

**Comment by pjcozzi** [comment]
This is really not Cesium's responsibility.  If we were to accept #2564, we would have to do things like that throughout the API.
