### ISSUE TITLE
ICRF not working

### ISSUE THREAD

**Issue by AnneWoepse** [AnalyticalGraphicsInc/cesium#2570]
if you go to sandcastle and click the camera example, and change the camera setting to ICRF, it is currently showing a fixed view.  In an inertial view, the globe would be spinning.

**Comment by pjcozzi** [comment]
Thanks for the report, @AnneWoepse.  This is most likely a regression.  @bagnell can you have a look?

**Comment by pjcozzi** [comment]
This was fixed in #2571 and will be in Cesium 1.8.  Thanks again for the report, @AnneWoepse.
