### ISSUE TITLE
Model translucency issue in 1.7

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2572]
@bagnell I will send you the model.  Can you look at this?  Perhaps this is an OIT change?  However, setting `orderIndependentTranslucency` to `false` did not help.  I tried to briefly tweak the model alpha values, but it also did not help.

1.6:

![image](https://cloud.githubusercontent.com/assets/782098/6583646/ac083604-c722-11e4-854e-aa0db443dc00.png)

1.7:

![image](https://cloud.githubusercontent.com/assets/782098/6583631/934c2e54-c722-11e4-95c5-84f3f6bbfca4.png)

**Comment by bagnell** [comment]
@pjcozzi Does the model create separate commands for back/front faces when blending is enabled? The commands being submitted were only those culling the back faces. If you turn OIT off, this model still doesn't look right.

**Comment by pjcozzi** [comment]
> Does the model create separate commands for back/front faces when blending is enabled?

No.  We could do this, but I think I would want to do it server-side so that the Cesium client truly renders what the model describes, not what we think it should describe.
