### ISSUE TITLE
Model does not render

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2577]
Reported on the [forum](https://groups.google.com/forum/#!topic/cesium-dev/pi20u3DWPTc).

`Geometry1` and `Geometry2` only have `POSITION` attributes (which is legal).  We can this warning:

> [.WebGLRenderingContext]PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty

Not sure if this is a Cesium or converter issue yet.

**Comment by pjcozzi** [comment]
Potential converter issue: https://github.com/KhronosGroup/glTF/issues/369

**Comment by mramato** [comment]
Can this be closed?  It looks like the issue you created above has been closed.
