### ISSUE TITLE
WMS-T (time) support in WebMapServiceImageryProvider

### ISSUE THREAD

**Issue by mcenirm** [AnalyticalGraphicsInc/cesium#2581]
Does WebMapServiceImageryProvider currently support WMS-T (time) functionality, in conjunction with the Timeline widget?

If so, then where is it documented?

If not, then what is a rough outline of the steps to connect WebMapServiceImageryProvider and Timeline?

**Comment by mcenirm** [comment]
An example WMS-T endpoint is `http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0q-t.cgi?` (Historical CONUS NEXRAD Base Reflectivity) from [Iowa Environmental Mesonet](https://mesonet.agron.iastate.edu/ogc/).

```js
var nexrad = new Cesium.WebMapServiceImageryProvider({
    url: "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0q-t.cgi?",
    layers: "nexrad-n0q-wmst",
    parameters: {
        format: 'image/png',
        transparent: 'true',
        time: '2014-04-28T21:00:00Z'
    }
});
```

**Comment by hpinkos** [comment]
Time-dynamic imagery support added in #5575
We should be able to use that to implement WMS-T

**Comment by OmarShehata** [comment]
https://github.com/AnalyticalGraphicsInc/cesium/pull/6348 added support for this so I think we can close this @hpinkos

**Comment by hpinkos** [comment]
Yes, thanks @OmarShehata
