### ISSUE TITLE
Chrome reporting console error on Infobox use

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2582]
See this [forum post](https://groups.google.com/d/msg/cesium-dev/1v33B3zMnfs/rZ3AxF_du6wJ).  I think the solution is to replace about:blank with  a manually created empty page.

**Comment by pjcozzi** [comment]
@mramato are you doing this for 1.8?

**Comment by mramato** [comment]
This error is harmless, so I'm taking off the showstopper, but I still might get to it for 1.8.

**Comment by mramato** [comment]
This appears to be caused by AdBlock.  It's a harmless error but one they have to fix on their end.  They are injecting scripts into sandboxed iFrames, which report the attempt to do so to the console (hence the error).
