### ISSUE TITLE
Support stippled lines

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2584]
I thought we had an issue for this, but I couldn't find one.

We get requests for dashed/dotted lines on the forum all the time, most recently in [this thread](https://groups.google.com/d/msg/cesium-dev/Zkgq8E80v8c/mKR9MH2j4-gJ).  Google Earth also has this ability (though not KML).  I don't know how difficult it would be to create a material that does this, but it's definitely worth doing when we have the time.

**Comment by Deepak-Kumar-D** [comment]
Even i don't find an issue with this one. But yeah we can enhance.

**Comment by pjcozzi** [comment]
Reading:
* [Shader-Based Antialiased, Dashed, Stroked Polylines](http://jcgt.org/published/0002/02/08/)
* [Drawing Lines is Hard](http://mattdesl.svbtle.com/drawing-lines-is-hard) - entertaining but not specifically about styling.

**Comment by prisanto** [comment]
Is there any improvements in this matter? If no one is working on it I would like to give it a try. Can you give some tips about where to start it?

**Comment by pjcozzi** [comment]
@prisanto there's no update here yet.  A good place to start is the paper, "Shader-Based Antialiased, Dashed, Stroked Polylines", linked above.  Let me know what you think about this approach.

**Comment by hpinkos** [comment]
Requested again here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/J_75KkE2mcA

**Comment by pjcozzi** [comment]
Fixed in #5159 by @jasonbeverage.

**Comment by mramato** [comment]
@rahwang you might want to go back to the threads linked in this issue and let them know about the new support that will be in 1.32 on May 1st.

**Comment by hanokhaloni** [comment]
WOOHOO!!!!!
