### ISSUE TITLE
SampledProperty.prototype.getValue returns invalid Cartesian3

### ISSUE THREAD

**Issue by speigg** [AnalyticalGraphicsInc/cesium#2596]
Using a HOLD `backwardExtrapolationType` in an empty sampledProperty causes `getValue` to return an invalid Cartesian3. 

```javascript
var sampledPosition = new Cesium.SampledPositionProperty()
sampledPosition.backwardExtrapolationType = Cesium.ExtrapolationType.HOLD 
var result = sampledPosition.getValue(Cesium.JulianDate.now())
```

I would expect the result to be `undefined`.
Instead, the result is a `Cartesian3` with `{x: undefined, y: undefined, z: undefined}`

When using the default `backwardExtrapolationType` (NONE), the result is `undefined`, as expected.

**Comment by mramato** [comment]
Thanks, nice catch.  I just opened #2605 to address this.  It was a problem with all sampled properties, not just position, thankfully it was an easy fix.
