### ISSUE TITLE
Ability to set home offset

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2599]
We currently expose `Camera.DEFAULT_VIEW_RECTANGLE` and `Camera.DEFAULT_VIEW_FACTOR` but we don't expose anything like `Camera.DEFAULT_OFFSET`, which I imagine would be an HPR.  We should expose such a value and use it in the `HomeButton` widget.

**Comment by hpinkos** [comment]
related: #1798
