### ISSUE TITLE
strange camera behaviour

### ISSUE THREAD

**Issue by kaktus40** [AnalyticalGraphicsInc/cesium#2607]
Hello,
in a sandCastle when you use the  line:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
```
the mouse buttons follow this behaviour:
* middle button tilts the globe
* right button zooms the globe
* left button turns the globe

With the next lines:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var target = new Cesium.Cartesian3(300770.50872389384, 5634912.131394585, 2978152.2865545116);
var offset = new Cesium.Cartesian3(6344.974098678562, -793.3419798081741, 2499.9508860763162);
viewer.camera.lookAt(target, offset);
```
the mouse buttons follow this behaviour:
* the left button tilts the globe
* the middle button does nothing
* the right button zooms the globe

**Comment by WarpDrive** [comment]
When you perform lookAt, camera.transform changes
-instead of left drag spinning around the Earth's transform it spins around the lookAt transform
-instead of right drag zooming in on Earth's transform it zooms on the lookAt transform
-middle mouse button drag basically creates a temporary lookAt, but you already have a lookAt target so it does nothing

**Comment by kaktus40** [comment]
Hello,
I agree with you for the transform, I saw it in the source. In fact my questions are:
* Is it a bug or a feature? :-)
* How can I return to the first behaviour with a lookAt?

**Comment by WarpDrive** [comment]
I believe it's a feature, allowing one to adjust to various angles/ranges to a specified target. You can set it back to Earth transform using camera._setTransform(Cesium.Matrix4.IDENTITY); Or camera.lookAtTransform(Cesium.Matrix4.IDENTITY); if you don't want to use a private method.

**Comment by kaktus40** [comment]
Thanks, it works.
