### ISSUE TITLE
Ability to show/hide layers based on zoom level

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2612]
This is something that has come up several times, most recently in [this post](https://groups.google.com/d/msg/cesium-dev/BP9FaQNFALw/rgDdf_XOYoYJ) on the form.

@kring any reason we can't simply add a somthing like a  `minimumDisplayLevel`/`maximumDisplayLevel` to the `ImageryProvider` interface?  My naive understanding of our imagery code tells me this should be simple.

**Comment by kring** [comment]
I agree, should be straightforward.  Switching between layers at different scales is a really common thing to do, but I've mostly seen people do it on the server side.

**Comment by mramato** [comment]
This is actually already implemented via the ImageryLayer.minimumTerrainLevel/maximumTerrainLevel options

**Comment by riccardolardi** [comment]
Any way to "fade" between imageryLayers depending on zoom?

**Comment by OmarShehata** [comment]
@riccardolardi there's not built-in way but there's a feature request here: https://github.com/CesiumGS/cesium/issues/8140
