### ISSUE TITLE
How do map tiles work?

### ISSUE THREAD

**Issue by trusktr** [AnalyticalGraphicsInc/cesium#2623]
What's the concept behind putting the map tiles onto the globe based on zoom level?

**Comment by kring** [comment]
Cesium's terrain/imagery rendering is described here:
http://cesiumjs.org/presentations/Rendering%20the%20Whole%20Wide%20World%20on%20the%20World%20Wide%20Web.pdf

Please post questions like this to the [forum](http://cesiumjs.org/forum.html) instead of creating GitHub issues.

**Comment by trusktr** [comment]
@kring That's amazing. Thank you!
