### ISSUE TITLE
Globe pickTriangle

### ISSUE THREAD

**Issue by WarpDrive** [AnalyticalGraphicsInc/cesium#2629]
This is in response to this thread https://groups.google.com/d/msg/cesium-dev/Cy0iRA7jG0w/fX04Kc6SwBcJ

I've written a working implementation here https://github.com/WarpDrive/cesium/commit/a4b881fb65d9e48bd1ea23568f80989c267dcc3c

I've tested it locally using this SandCastle example

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var camera = viewer.scene.camera;var scene=viewer.scene;
var CC3 = Cesium.Cartesian3;var pos = new CC3();

Sandcastle.addToolbarButton('cam dir vs surface normal', function() {
    var ray = scene.camera.getPickRay(new Cesium.Cartesian2( viewer.canvas.clientWidth / 2,viewer.canvas.clientHeight / 2));
    pos = scene.globe.pickTriangle(ray, scene, true);

    //get outward facing normal
    var right = new CC3();
    var left = new CC3();
    var normal = new CC3();
    CC3.subtract(pos.v0,pos.v1,left); //v1 to v0
    CC3.subtract(pos.v2,pos.v1,right); //v1 to v2
    CC3.cross(right,left,normal);
    CC3.normalize(normal,normal);
    console.log(CC3.dot(normal,camera.direction));
    //near -1 when looking opposite the normal
    //near 0 when looking obliquely at the normal
});
```

It does tack on properties onto the intersection Cartesian3 object, but that doesn't interfere with using it in the Cartesian3 functions. They can easily be stripped off using the Cartesian3.clone function though.

I believe this will retain backward compatibility. I haven't yet signed the individual contributor licence, otherwise I would of made a pull request instead of an issue. Also perhaps someone else might have a better approach to getting triangle vertices, or perhaps there are unforseen issues with this code.

Perhaps intersection point and normal can be combined into a ray object, and return an object consisting of a ray and the 3 vertices instead? Just returning ray I suppose is an option also, but there may be applications that can make use of the vertices, like placing an overlay just over that triangle, and Kevin's original usage of obtaining the barycenter.

**Comment by WarpDrive** [comment]
Some other possible forms on intersection:
Kevin's original form: one large composite object consisting of 4 Cartesian3 objects followed by tile
```javascript
{
intersection : intersection,
v0 : v0,
v1 : v1,
v2 : v2,
tile:
}
```
Or perhaps an array, consisting of an array of component objects
```javascript
intersection[0]=intersection
intersection[1]=v0
intersection[2]=v1
intersection[3]=v2
intersection[4]=tile
```
tile isn't a Cartesian3, but having the same data type isn't a prerequisite for arrays in JavaScript.

**Comment by kring** [comment]
@WarpDrive thanks for the work on this.

Please feel free to open a pull request.  We won't merge it until you've signed the CLA, but it's much easier to review and comment on a pull request.  Any problem signing the CLA?  You can just email it in.

I don't think it's a good idea to add extra properties to `Cartesian3`, because tacking on extra properties is likely to break optimizations that browsers do on this type.  Instead, define a new type, called `TriangleIntersection` maybe, for holding an intersection point plus three vertices.

**Comment by pjcozzi** [comment]
Thanks for submitting the CLA, @WarpDrive.

**Comment by WarpDrive** [comment]
You're welcome. I'm surprised it was processed so quickly, I look forward to being able to contribute! Before re-coding and making a pull request, I was hoping to get some feedback on the following:

Perhaps a triangle3D object could be created, similar to these object
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Plane.js
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Ray.js

properties being .v0 .v1 .v2 (Cartesian3 verticies)
one method could be .getNormal (assuming counter clockwise verticie order)
perhaps another method could be .getArea
yet another .getBaryCenter
(does the terrain mesh already have pre-calculated normals for the triangles by chance?)

Plane.js could have a function Plane.fromTriangle where it determines the plane that the triangle is in

I was thinking instead of creating an object type such as TriangleIntersection perhaps it could just return a type-less object where the components are immediately split into object types upon being returned? The components being a triangle3D, and a Cartesian3 intersection point. Not a big deal though, either way should work.

IntersectionTests.rayTriangle calls rayTriangle which returns the range, then it scales using this range to find the intersection point. Since range is already calculated why not return that as well? That will save a future subtraction and magnitude calculation down the road if the user wants the range.

One use I was thinking of is movement clipping. An app calculates a movement 'ray segment' where it has a starting position, velocity vector, and time for this frame. Initially it calculates range assuming no collision. Then it creates a ray whom's origin is the same as the projectile and whom's direction is the same as the velocity vector. If the returned range is greater, then no collision occurs. However if the returned range is less, then a collision did occur.

Then it figures how much time it takes till collision at the intersection, then with the remaining time decides how to redirect the velocity vector and perform the second move for that frame, such as how much to direct toward a slide motion, and how much toward a bounce, if any.

Perhaps 'ray segments', or rays with a certain range could be tested as well, not just rays of infinite length.

Picking seems to only work for tiles in the frustum. Perhaps very low LOD tiles could be placed outside of the frustum for collision detection there as well, or fall back to pick ellipsoid at least.

**Comment by kring** [comment]
> Perhaps a triangle3D object could be created, similar to these object

Sounds ok to me.  Probably just call it `Triangle`.

> does the terrain mesh already have pre-calculated normals for the triangles by chance?

No, the mesh (optionally) has a normal at each vertex, which is better for lighting than a normal per triangle.

> I was thinking instead of creating an object type such as TriangleIntersection perhaps it could just return a type-less object where the components are immediately split into object types upon being returned?

Even though I used one in my hacked up version in the `nm` branch, we try to avoid type-less objects in Cesium.  Well-defined types give us a good place to put documentation and potentially aid the browser's ability to generate fast code as well.

I originally suggested `TriangleIntersection`, but something more precise like `RayTriangleIntersection` would be better.

> Since range is already calculated why not return that as well?

Sounds ok to me.

> Picking seems to only work for tiles in the frustum. 

Right, because you're picking from what's drawn on the screen.  I don't think it would be appropriate to use picking for collision detection, except maybe for the camera itself (which we already do), because it's too dependent on things like screen size and resolution, viewer position, and what terrain data the client has gotten around to loading so far.

One last note: I'd encourage you to keep the scope of this under control.  Adding a bunch of extra methods, like `getBaryCenter`, `Plane.fromTriangle`, etc., without a clear and immediate need for them, is probably not a good use of your time and will make it harder to get the pull request merged.

**Comment by WarpDrive** [comment]
Thanks for all of the information and advice. I'll limit the scope by not adding things like triangle area, barycenter, and get plane from triangle. I was thinking of either adding properties to the current Ray object, or introducing a RaySegment object.

RaySegment object (like a Ray, but not of infinite length)

	//properties
	origin
	direction
	range
	destination

	partial data where the rest can be calculated
		-either origin or destination undefined
		-range and direction are undefined

	//methods
	cloneRay (copies origin and direction from a ray)
	calcAll (calc undefined properties, return true if successful)

Triangle object

	//properties
	v0
	v1
	v2
	normal (CCW verticie order)

	//methods
	calcNormal (updates triangle's normal property and returns the normal)

RayTriangleIntersection object

	//properties
	RaySegment
	Triangle

So when one performs globe.pickTriangle you start with a ray (origin and direction) and it returns a RayTriangleIntersection object. If RayTriangleIntersection object is undefined that means there wasn't an intersection. If there was an intersection RayTriangleIntersection contains the Triangle and RaySegment created by cloning the ray and adding range and destination values.

**Comment by kring** [comment]
As a general rule, the result of a method that computes something does not need to indicate the input parameters that went into computing it.  For example, `IntersectionTests.rayTriangle` just returns the intersection point as a `Cartesian3`.  The result does not indicate the ray and triangle that were intersected, nor should it.

Similarly, I don't think the new `RayTriangleIntersection` type needs to include information about the `Ray`.  In fact, it doesn't make sense for it to include the triangle, either, if it represents the intersection between a ray and triangle.  But on further consideration, what we're actually computing isn't the intersection between a ray and triangle, it's the intersection between a ray and triangle mesh.  So in that case, indicating which triangle in the mesh is intersected makes much more sense.  So let's call it `RayMeshIntersection` instead.  And all it needs to include is the triangle that was intersected and the point of intersection.  Even the distance along the ray is unnecessary in my opinion.

One more note:

> calcNormal (updates triangle's normal property and returns the normal)

A method like this could be useful, but it should be called `Triangle.normal` and it should not store the result on the triangle object itself.  This is consistent with, for example, `Cartesian3.magnitude`.

**Comment by WarpDrive** [comment]
I understand not returning what was inputted. So RayMeshIntersection will only include the triangle, the point of intersection, and possibly range.

Range is what is determined by rayTriangle. There may be cases where all the app wants is range. In that case rayTriangle calculates range, then IntersectionTests.rayTriangle calculates intersection point (not used) and throws away range (is used), then the app has to re-calculate range. So I was hoping to include range with RayMeshIntersection, it's only 1 floating point number.

I was considering these 2 wrapper functions calling globe.pickMesh . 
```javascript
globe.pick (ray,scene,result) //backward compatibility
{return globe.pickMesh(ray,scene,false,result);} //returns Cartesian3

globe.pickPointTriangle (ray,scene,result)
{return globe.pickMesh(ray,scene,true,result);}//returns RayMeshIntersection 
```
```javascript
RayMeshIntersection
{
	//properties
	intersection
	range
	triangle
}
Triangle
{
	//properties
	v0
	v1
	v2

	//methods
	normal (returns the normal)
}
```
Thanks for all of your feedback, I do appreciate it!

**Comment by kring** [comment]
> Range is what is determined by rayTriangle ... then IntersectionTests.rayTriangle calculates intersection point

You'll have to refactor `IntersectionsTests` to make the raw range accessible - and be sure to maintain backward compatibility -  but I have no problem with that if you're up for it.

For your proposed `Globe` methods, I'd suggest something more like:

```
var rayMeshIntersectionScratch = new RayMeshIntersection();
Globe.prototype.pick = function(ray, scene, result) {
    var meshIntersection = this.pickTriangle(ray, scene, rayMeshIntersectionScratch);
    if (!defined(meshIntersection)) {
        return undefined;
    }
    return Cartesian3.clone(meshIntersection.intersection, result);
};

Globe.prototype.pickMesh = function(ray, scene, result) {
   // .. do actual picking here, return RayMeshIntersection
};
```

Thanks again for working on this!

**Comment by pjcozzi** [comment]
@WarpDrive please open a pull request if you want to pursue this.
