### ISSUE TITLE
ScreenSpaceEventType.RIGHT_DOUBLE_CLICK does not work

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2631]
As noted in [this forum post](https://groups.google.com/d/msg/cesium-dev/0f_KD1InXyE/pbMuKz2dxxAJ).  We should either fix this or do as we've talked about in the past and deprecate `ScreenSpaceEventHandler` since it adds nothing to the public API (and recommend users just use standard mouse events).

**Comment by emackey** [comment]
I mostly agree, but I should clarify there is one thing that `ScreenSpaceEventHandler` does offer users:  It combines the separate mouse, touch, and pointer events that browsers currently use.  Perhaps this problem will take care of itself when browsers standardize someday, but for now `touch` will continue to be the only solution on iOS, and pointer events on IE, etc.  Using our event API is perhaps less cumbersome than implementing all three standards in user code.  Our own Sandcastle demos would need to deal with this, if `ScreenSpaceEventHandler` became private.

**Comment by mramato** [comment]
@emackey while your point is valid, I would argue that unifying input functionality is outside of the scope of Cesium.  Anyone writing an app should just use [PEP](https://github.com/jquery/PEP) or one of the other polyfills to unify input interaction (though PEP seems to have quickly become the de factor one).  The only reason we can't use a polyfill in Cesium is because we don't want to do anything that modifies the global scope.  We aren't anywhere near experts in web interaction and our users would be better served with a polyfill.

**Comment by emackey** [comment]
We may be straying off topic, but I have to offer a counterpoint here.  Cesium needs *something* internally to be able to offer support for mouse, touch, and pointer events for its own purposes.  If we force Cesium client apps to use anything other than what Cesium itself is using, that is going to lead to inconsistent app behaviors and generally bad UX.  I think we should encourage apps to use the same input system that Cesium itself uses, or allow them to somehow replace all of Cesium's input system.

That said, the current system is very badly organized (my fault for adding features organically to a previously simple design).  Someday I may take a shot at rewriting the input system, unless you think a polyfill could be incorporated into core Cesium to take its place.  I think a newly written system could be more unified, app configurable, with events-per-frame aggregation built in (which is a feature we use and need, that polyfills are unlikely to have).  We should build a roadmap.

This issue though is simple:  `RIGHT_DOUBLE_CLICK` will never work in a browser, and should be removed from the current API.

**Comment by mramato** [comment]
I think there may be a chance we can use PEP in Cesium without polluting the global scope.  Someone should definitely look into that.  It would allow us to code only against PointerEvents and remove all other handling.

**Comment by mramato** [comment]
I've confirmed that we can't use PEP in Cesium proper without modifying external state.  That being said, I think we should still consider using it anyway and changing Cesium to only work against the PointerEvent API.  Our lack of good unified support for touch/pointer/other input is becoming a more common problem on the forum every day.

I still think we should remove `ScreenSpaceEventHandler` from the public API, but we can certinaly provide default implementations for controls that people can wire up to events as they see fit.

**Comment by pjcozzi** [comment]
Not that I would know, but this all sounds OK to me - can we submit a new issue or rename this one?

**Comment by emackey** [comment]
We should still remove RIGHT_DOUBLE_CLICK, regardless of making this private etc.

I'm fine with private APIs and PEP and whatever else.  Here's my main concern:  Cesium's default use of input events is almost overwhelming.  We use all three buttons for drag, we use the primary click, we use modifier keys, and touch, tap, and three forms of two-finger touch, all by default.  I feel we *have* to throw the app devs a bone here.  We can't expect them to just wire up whatever input they feel like, without the slightest integration with the system Cesium already imposes on them.  We need to give them good control over Cesium's mapping of input events to actions, and freedom to add their own custom actions among that mapping, such that the newly added actions "feel" like they integrate smoothly with Cesium's extensive input handling.

**Comment by lilleyse** [comment]
MIDDLE_DOUBLE_CLICK is also not working for me anymore.

**Comment by emackey** [comment]
"Double" clicking is a relic of the desktop icon era, not modern UX for the age of mobile and touch input.

**Comment by pjcozzi** [comment]
If removing it is the right move, let's do it.

**Comment by lilleyse** [comment]
I started to remove these from the `3d-tiles` branch. What would the deprecation timeline look like if this were removed from master?

**Comment by pjcozzi** [comment]
1 release should be OK; I don't think this is widely used.
