### ISSUE TITLE
Lighting regression

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2635]
532aa53c6711e25cd513b21c0aff43b858f6a771 brings back the 2D/CV lighting issue that was fixed in #2515.  The commit before it, f507210c3af52a9a3ca17597e0731c4916964591, does not have the issue.  You can see this easily enough in the [GeoJSON Sandcastle example](http://localhost:8080/Apps/Sandcastle/gallery/GeoJSON%20and%20TopoJSON.html).

I'm marking this a showstopper so that we at least look at it before 1.9.

**Comment by mramato** [comment]
Unfortunately this isn't going to make 1.9, but I'm leaving it as a showstopper so that we don't let it languish and try and fix it for 1.10.

**Comment by mramato** [comment]
Turns out this is OIT only now, since disabling fixes the issue.  It also works on IE (I'm not sure if IE has extensions needed for OIT or not)

**Comment by pjcozzi** [comment]
Will look at post 1.10.

**Comment by mramato** [comment]
Recently came up again [on the forum](https://groups.google.com/d/msg/cesium-dev/OzfwqMLOr60/SNW0D0_HP5MJ)

**Comment by emackey** [comment]
Are there updated steps to reproduce this?  The code sample from #1825 doesn't produce the results shown in the screenshot for me.

**Comment by mramato** [comment]
@emackey just run the GeoJSON Sandcastle example linked to in the description and switch to 2D.  

![image](https://cloud.githubusercontent.com/assets/1495196/8282425/ace3c898-18be-11e5-926e-9fe8135b959d.png)

**Comment by pjcozzi** [comment]
@bagnell thoughts on this? Is this an easy fix for 1.11?
