### ISSUE TITLE
Add credit outside of the render loop

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2641]
`Credit` and `CreditDisplay` were designed for adding attribution based on visibility, e.g., terrain tiles, during the render loop.

We also want apps to be able to add their own persistent credits directly without having to tap into the render loop and private `frameState`

From the Seattle demo.

**Comment by shunter** [comment]
This is what `addDefaultCredit` is for.

**Comment by pjcozzi** [comment]
Ah, yes.  Thanks!
