### ISSUE TITLE
Test Failures report

### ISSUE THREAD

**Issue by theOgrable** [AnalyticalGraphicsInc/cesium#2651]
Hi everybody,

Here is a unit test failure report following a discussion initiated on the Google group forum that you can find [here](https://groups.google.com/forum/#!topic/cesium-dev/00uetXoqtTA)

So I checked your recommandation :

1. Browsers are up-to-date
2. I was sure that my graphic cards were up-to-date trusting that I would have had some notifications if not, but I still double checked, and it appeared it was not. So I updated my NVIDIA card, not my Intel HD Graphics, since I have a manufacturer specific driver installed and Intel tells me it is not recommended to use a generic driver in that case. If you think it's needed, I will update my Intel graphic card as well.
3. I tried to run it with node.js, and there are less errors 1 instead of 11 in firefox, 7 instead of 18 in Chrome.

Here are my specs :
* Windows 7 64 bit
* GPU 1 : Intel(R) HD Graphics 4000, driver version : 8.15.10.2712
* GPU 2 : NVIDIA GeForce GT 640M, driver version : 9.18.13.5012

The result from "Run all tests" (it appears there are no more differences in Firefox or Chrome with "run with Webgl Validation" since I updated my graphic card) are :

<strong>From IIS instance : </strong>
* In Firefox : 11 failures

> Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with 32bit indices
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with VertexNormals
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with WaterMask
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with VertexNormals and WaterMask
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with OctVertexNormals
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with VertexNormals and unknown extensions
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with OctVertexNormals and unknown extensions
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with unknown extension
Renderer/VertexArrayFacade sub-commitsScene/Globe renders terrain with enableLighting

* In Chrome : 18 failures

> Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with 32bit indices
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with VertexNormals
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with WaterMask
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with VertexNormals and WaterMask
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with OctVertexNormals
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with VertexNormals and unknown extensions
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with OctVertexNormals and unknown extensions
Core/CesiumTerrainProvider requestTileGeometry provides QuantizedMeshTerrainData with unknown extension
Scene/Model renders animBoxes without animationScene/Model Animates and renders
Widgets/Geocoder/GeocoderViewModel moves camera when search command invoked
Scene/Globe renders terrain with enableLightingScene/Scene debugShowBoundingVolume draws a bounding sphere
Scene/GeometryRendering WallGeometry 3DScene/GeometryRendering WallGeometry Columbus view
Scene/GeometryRendering WallGeometry pickScene/GeometryRendering WallGeometry async 

* In IE : red page, range from 400 to 900 failures. IE even crashed once. Problem might be due to unit tests script in itself as I have a succession of error :like that before real failures:

> AfterAll TypeError: Impossible d’obtenir la propriété « destroyForSpecs » d’une référence null ou non définie 

<strong>From node.js instance : </strong>
* In Firefox : 1 failure

> Renderer/VertexArrayFacade sub-commits

* In Chrome : 7 failures

> Scene/Model renders animBoxes without animationScene/Model Animates and renders
Scene/GeometryRendering WallGeometry 3DScene/GeometryRendering WallGeometry Columbus view
Scene/GeometryRendering WallGeometry pickScene/GeometryRendering WallGeometry async
Scene/Scene debugShowBoundingVolume draws a bounding sphere

* In IE : no improvements from IIS 

Olivier

**Comment by mramato** [comment]
I would actually recommend you update your Intel driver, but that's up to you.  I have dual set up as well and I always update both drivers.  Assuming your laptop is using nvidia optimus, your browser will use the Intel card for WebGL rendering unless you explicitly configure your browsers to use the Nvidia card (which can be tricky to do).  So updating the driver may make some of these pass (but that's not a definite).

In either case, the IIS failure is a configuration issue (because the MIME type for .terrain files is not provided by default.  This is easily fixed and I'm going to open a PR to do so.  The Chrome failures don't surprise me because I used to have them on older Intel drivers. The Firefox one is almost certainly a bug in the  browser.

While we strive to have all tests pass on all systems, the nature of web browsers, video cards, and the difficulty of testing WebGL code means that we see false failures such as what you're seeing.  They are nothing to worry about and not indicative of a bug in Cesium (at least as far as we can tell so far).  

That being said, thanks for reporting them.

**Comment by theOgrable** [comment]
Well, I tried to update my graphic card following [these instructions](http://www.intel.com/support/graphics/sb/CS-033915.htm), but in the end, it tells me that my driver are up-to-date and do nothing.
I suppose it's in some way due to manufacturer specific driver. I will try Acer support, to see if they can provide any help.

That being said, I noticed something else when running my Cesium IIS instance in Firefox : there is a very high cpu usage. There is the usual 15-20% cpu usage for the process named 'Firefox' (when Cesium is on the focused tab), but there is also a 30-40% cpu usage for the 'System' process (NT kernel & system).
I added MIME type of terrain (application/octet-stream) to IIS just in case, but the problem remains.

I don't notice this behavior in Chrome nor IE.

**Comment by mramato** [comment]
I haven't had much experience with Acer in recent years, but one of the traditional problems with brands like them is that they lock you into specific drivers and stop updating them a long time before the machine has outlived it's usefulness.  Unfortunately, the drivers end up having bugs that never get fixed.

The terrain MIME type is not octet-stream, it's application/vnd.quantized-mesh, see the above pull request for the exact configuration change I made.

The CPU usage is most likely a red herring, One minor possibility is that you end up falling back into software rendering mode in some browsers, which would explain high-CPU usage, but Cesium itself has no direct effect on any of it (being it's just a script in a web page).  http://webglreport.com can sometimes be useful here, indicating what capabilities are being exposed via WebGL (the top section is probably most relevant for you).

Ultimately, none of the failures you are seeing is anything to worry about and are just quirks of your machine.  None of it should translate into bugs when running Cesium applications.

**Comment by emackey** [comment]
We added the MIME type, but ultimately the tests aren't going to pass unless you run them against `node server.js` (from the Cesium root folder), as there is some proxying logic there needed by the tests.

**Comment by mramato** [comment]
@emackey I could be wrong but I don't think that's true.  We never actually use the proxy in the tests, we check that `DefaultProxy` generates specific URLs but that's about it.  I ran the tests in IIS last night and they all passed once I added the MIME type.

**Comment by emackey** [comment]
@mramato oops!  Apparently I didn't `git pull`.  But indeed, I see the tests passing under IIS now.
