### ISSUE TITLE
Cannot remove entity with a path

### ISSUE THREAD

**Issue by chocstarfish** [AnalyticalGraphicsInc/cesium#2656]
In the Interpolation demo (http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Interpolation.html&label=Showcases)

I tried to remove the entity by adding following codes:
```
Sandcastle.addToolbarButton('Delete Entity', function() {
    viewer.entities.removeAll();
});
```
or
```
Sandcastle.addToolbarButton('Delete Entity', function() {
    viewer.entities.remove(entity);
});
```
I got an error from the console as following and the deletion failed:
>Uncaught TypeError: Cannot read property 'removeObject' of undefined (on line 533 of http://cesiumjs.org/Cesium/Source/DataSources/PathVisualizer.js)

**Comment by mramato** [comment]
Thanks for the bug report.  This doesn't happen in Cesium master and after some digging I found it was already fixed (by accident) in #2620.  The fix will be officially available with Cesium 1.9 on May 1st.

The two line change to `Source/DataSources/DataSourceDisplay.js` in that PR is what fixed it, just in case you want to make a temporary change to your local copy.
