### ISSUE TITLE
Missing startposition for ScreenSpaceEventType.PINCH_START event

### ISSUE THREAD

**Issue by jbo023** [AnalyticalGraphicsInc/cesium#2664]
On touch devices(android, ios tablet) I observed some sluggish and unpredictable results during zoom/tilt/rotate with a two finger pinch gesture on this page: https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html.

This only happens if the camera is near the ground. 

After some digging in the code I found the following bug in the pinch event handling methods. 

In the File Scene/CameraEventAggregator.js line 74:

    Cartesian2.clone(event.position, eventStartPosition[key]);

The startposition for a ScreenSpaceEventType.PINCH_START event is set to undefined. The event Object has only the attributes "position1" and "position2". After changing the line to:

    Cartesian2.clone(event.position1, eventStartPosition[key]);

The navigation behavior on touch devices near the ground was much better and worked as expected.

**Comment by WarpDrive** [comment]
Does this also effect the same line at https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/CameraEventAggregator.js#L176

I don't know if this is related or not, but if you press/hold left mouse then press/hold ctrl then let go of left mouse then let go of ctrl it acts as if left mouse is still pressed. Order of pressing is important: it works OK if ctrl was pressed before left mouse is pressed.

**Comment by jbo023** [comment]
Hi, 

this shouldn't effect the line 176: Only two finger touch events do have two positions in the event, see 

https://github.com/AnalyticalGraphicsInc/cesium/blob/fd4112e344bb822eb34aec4eb8643ff95f22f593/Source/Core/ScreenSpaceEventHandler.js#L380-L383
so the CRTL bug should have another cause

**Comment by emackey** [comment]
@WarpDrive that's a separate issue, #2522.
