### ISSUE TITLE
How to get the name of the folder (KML) with Cesium

### ISSUE THREAD

**Issue by espacedev** [AnalyticalGraphicsInc/cesium#2670]
I need to recover all the name of the parent folder and name of the folder child in KML

**Comment by mramato** [comment]
In the future, please use [the forum](http://cesiumjs.org/forum.html) for any questions and comments you might have.  More people will see your post and you will usually get more/better help. We try to only use GitHub issues for actual bugs and features.

That being said, the answer to your question is that you need to get the list of entities after the KML loads and iterate through them looking at their parent properties.  That will allow you to reconstruct the full hierarchy of the original KML document.  If you haven't already down so, I would recommend reading the [Visualizing Spatial Data](http://cesiumjs.org/2015/02/02/Visualizing-Spatial-Data/) tutorial, which doesn't answer your question directly, but does provide a good overview of the basics of the Entity API (which is what KmlDataSource uses).  Please start a forum thread if you still have any questions.
