### ISSUE TITLE
Sandcastle "open in new window" broken for Development demos

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2672]
None of the demos in the new "Development" subfolder work with the "Open in New Window" Sandcastle toolbar button, due to path problems.

**Comment by emackey** [comment]
This fix should get merged before the 1.9 release, so I'm flagging it.

**Comment by mramato** [comment]
Don't worry, I'll merge this later tonight.  But it's not a show stopper because we don't actually ship any of the Development examples.
