### ISSUE TITLE
Ability to use Cesium in Chrome packaged apps

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2677]
From [the forum](https://groups.google.com/d/msg/cesium-dev/DlUgwLL_Xj8/fw0yk-t23MEJ). Currently the Viewer widget can't be used in a Chrome packaged app because Knockout is not CSP compliant.  There are some workaround out there and it might be possible to use them to enable this functionality.  There's also a chance that the type of binding we do with knockout makes this basically impossible.  More research is needed.

**Comment by pjcozzi** [comment]
@mramato is this still of interest?  Are Chrome packaged apps commonly used?

**Comment by mramato** [comment]
It hasn't come up in a long time and I doubt it will.
