### ISSUE TITLE
KML GroundOverlay should apply alpha transparency value from color property

### ISSUE THREAD

**Issue by markerikson** [AnalyticalGraphicsInc/cesium#2688]
Google Earth supports a `<color>` value on a `<GroundOverlay>`.  The RGB values are ignored, and the alpha value is applied to the image  (see http://dagik.org/kml_intro/E/image.html for an example).  It would be nice if Cesium supported that as well.

**Comment by mramato** [comment]
Thanks, unsurprisingly I don't think the spec mentions this.  If this is trivial, I'll get it into 1.10.

**Comment by GatorScott** [comment]
If I change the color to 550000FF I see a red tinted image.  The choice of white is probably giving the impression that it is being ignored since the center of the image is white anyway and blending a transparent white would serve to soften the color even further.

**Comment by markerikson** [comment]
For what it's worth, GE Desktop exposes a "Transparency" slider in the Properties dialog for a GroundOverlay.  I suppose there might be a use case somewhere for actually applying the other color values as well, but alpha is certainly the most obviously useful (and admittedly the only one I care about myself).

**Comment by hpinkos** [comment]
Hello @markerikson 
This issue was fixed in #3766 and will be included in the Cesium 1.20 release.  Thanks!
