### ISSUE TITLE
Billboard/label on terrain flickering

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2691]
As described [here](https://github.com/AnalyticalGraphicsInc/cesium/pull/2653#issuecomment-99255110) and [here](https://github.com/AnalyticalGraphicsInc/cesium/pull/2653#issuecomment-99262447).  @bagnell is right about the root cause.

**Comment by pjcozzi** [comment]
@hpinkos is this OBE with #6621?

**Comment by hpinkos** [comment]
Should be
