### ISSUE TITLE
Doc for getPixelSize contains errors

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#2695]
The help for PerspectiveFrustum.getPixelSize is confusing.  While it does correctly identify the first parameter as being a Cartesian2, the examples indicate a different structure ({integer width, integer height}).

**Comment by emackey** [comment]
The examples also show use of `canvas.clientWidth` and `canvas.clientHeight`, but actual internal use always references the undocumented `context.drawingBufferWidth` and `context.drawingBufferHeight`.  The buffer width & height are available to the user through other means, should we steer users towards that instead?  (Naturally the heights differ when browser zoom is in effect, and on high-DPI mobile displays etc).

**Comment by pjcozzi** [comment]
CC #2267

**Comment by pjcozzi** [comment]
@ggetz can we close this or make any additional tweaks required to close this?

CC #3091

**Comment by ggetz** [comment]
@pjcozzi The documentation currently makes sense for the structure of the parameters. If it is OK that the example uses `canvas.clientWidth` and `canvas.clientHeight`, then we can close it.

**Comment by pjcozzi** [comment]
Can you open a small pull request to use `scene.drawingBufferWidth` and `scene.drawingBufferHeight` instead?

**Comment by ggetz** [comment]
Sure.
