### ISSUE TITLE
Sun bloom rectangle

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2701]
For horizon views when the sun is just rising or setting, it looks like bloom saturates and the scissor rectangle becomes prominent:

![image](https://cloud.githubusercontent.com/assets/782098/7613391/66b07fbc-f95e-11e4-922c-6dd7f7840197.png)

Please close if duplicate.

**Comment by pjcozzi** [comment]
I'm pretty confident that the bloom is over saturating but beware of #1316, which indicates that the scissor rectangle could also be wrong.

**Comment by pjcozzi** [comment]
Potentially related to this (and #1316) is that the sun is too aggressively culled.  In the following view, a slight rotation will make the sun disappear too sun:

![image](https://cloud.githubusercontent.com/assets/782098/7776650/742b4590-008a-11e5-8b9f-e2d89e2728d0.png)

**Comment by pjcozzi** [comment]
Here's another perhaps insightful screenshot of this from the Model Sandcastle example (note the time in the bottom left to reproduce):

![image](https://cloud.githubusercontent.com/assets/782098/8057828/c4e3676e-0e82-11e5-9cb1-87faeb95fe0d.png)

**Comment by hpinkos** [comment]
Appears to be fixed 
![image](https://cloud.githubusercontent.com/assets/3451886/20976974/2d4b1d08-bc72-11e6-8abc-b59774dcb121.png)
