### ISSUE TITLE
Folders and Expansion of KML

### ISSUE THREAD

**Issue by jdkatz** [AnalyticalGraphicsInc/cesium#2707]
Is there any development plans to support parent folders and expansion in KML?

**Comment by mramato** [comment]
Unless you are talking about an interactive user interface, we already support it.  While Cesium's `EntityCollection` is a flat array, each entity has a `parent` property which can be used to visually construct the KML hierarchy.  Toggling the `show` property on an entity also toggles the visibility of child objects, just like KML.  If you are talking about a UI like Google Earth has, it's not on the near term roadmap but someday we'll probably have one.

In the future, please use [the forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) to ask questions and get support.  Your questions will be seen by more people and you'll hear from other users who have solved similar problems.  We try and only open GitHub issues for confirmed bugs or enhancements.  Thanks.
