### ISSUE TITLE
Cartesian type

### ISSUE THREAD

**Issue by icholy** [AnalyticalGraphicsInc/cesium#2728]
I'm a little confused about the `Cartesian` type that gets used.

* [TilingScheme#positionToTileXY](https://github.com/AnalyticalGraphicsInc/cesium/blob/0af79be33aca5a6c004050d20ba1f2be3cd95357/Source/Core/TilingScheme.js#L124) (GeographicTilingScheme, WebMercatorTilingScheme)
* [IntersectionTests#grazingAltitudeLocation](https://github.com/AnalyticalGraphicsInc/cesium/blob/0af79be33aca5a6c004050d20ba1f2be3cd95357/Source/Core/IntersectionTests.js#L582)

AFAIK there is no `Cartesian` interface definition anywhere.

Should they be changed to union types? `{Cartesian2|Cartesian3|Cartesian4}`

**EDIT**: Same thing with `Projection`

**Comment by shunter** [comment]
These are errors in the documentation.  positionToTileXY should be a `Cartesian2`, grazingAltitudeLocation should be a `Cartesian3`.  The doc should be fixed, but in the meantime, check the source code to see what the correct type is.

**Comment by hpinkos** [comment]
and `Projection` should be `MapProjection`

**Comment by icholy** [comment]
Should [this](https://github.com/AnalyticalGraphicsInc/cesium/blob/0af79be33aca5a6c004050d20ba1f2be3cd95357/Source/Scene/Camera.js#L134) be `PerspectiveFrustum`?

**Comment by pjcozzi** [comment]
I think it could also be `OrthographicFrustum`.  @bagnell can you confirm?
