### ISSUE TITLE
Cesium.Cartesian3.fromDegrees(0,0) gives wrong value

### ISSUE THREAD

**Issue by speigg** [AnalyticalGraphicsInc/cesium#2736]
Cesium.Cartesian3.fromDegrees(0,0)
> Cartesian3 {x: 6378137, y: 0, z: 0}

Cesium.Cartesian3.fromDegrees(1,1)
> Cartesian3 {x: 6376200.806232033, y: 111296.99906813345, z: 110568.77482456663}

**Comment by mramato** [comment]
These values are definitely correct.  I assume you you expected the X value to have been unchanged, but the surface of the earth is an ellipsoid, not a sphere, so it will grown and shrink as you move from semiMajor to semiMinor axes.  If you think the bug is something else, please explain what that it.

**Comment by speigg** [comment]
Look at the X value, not the X value. The first example `fromDegrees(0,0)` is incorrect, the second example `fromDegrees(1,1)` is correct

**Comment by mramato** [comment]
`Cartesian3 {x: 6378137, y: 0, z: 0}` is correct, what do you expect it to be?

**Comment by speigg** [comment]
Oh sorry, I was thinking z = up, as in ENU, but that doesn't make sense. Sorry for the bother!

**Comment by speigg** [comment]
Okay, so the problem I'm seeing isn't with `Cesium.Cartesian3.fromDegrees` like I thought it was, but with `Cesium.Transforms.headingPitchRollQuaternion` and `Cesium.Transforms.eastNorthUpToFixedFrame` returning an invalid quaternion/matrix when Cesium.Cartesian3.ZERO is used. 

This time I know what happened:
```javascript
var q = Cesium.Transforms.headingPitchRollQuaternion(Cesium.Cartesian3.ZERO, 0,0,0, undefined)
Cesium.Quaternion.magnitude(q)
> 0.7071067811865476
```

**Comment by speigg** [comment]
The problem is caused by `CesiumMath.sign` being used instead of `CesiumMath.signNotZero` in `Cesium.Transforms.eastNorthUpToFixedFrame`

**Comment by hpinkos** [comment]
`Cartesian3.ZERO` is not the same as `Cartesian3.fromDegrees(0,0)`.  `Cartesian3.ZERO` is the position at the center of the earth.  `Cartesian3.fromDegrees(0,0)` returns the position where latitude and longitude are equal to 0 on the earth surface.

**Comment by speigg** [comment]
Thanks @hpinkos, I understand that, and putting aside how silly it may seem to be passing in Cartesian3.ZERO, it should either fail with an error, or at least return a valid matrix/quaternion :)
