### ISSUE TITLE
Binary glTF size/speed tests

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2743]
To show the benefit of [Binary glTF](https://github.com/KhronosGroup/glTF/blob/new-extensions/extensions/CESIUM_binary_glTF/README.md), let's show the size/speed results for a few types of models:
* Simple node hierarchy, lots of geometry, no textures
* Simple node hierarchy, simple geometry, one big textures
* Simple node hierarchy, simple geometry, lots of simple textures
* A lot of animations, each with a lot of keyframes
* Complex node hierarchy, simple geometry, no textures
* A few "typical" models, perhaps from [here](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Apps/SampleData/models).

Get results for the following
* File size and number of files for COLLADA (raw and gzipped)
* File size and number of files for JSON + binary (raw and gzipped)
   * And Cesium load time
* File size for base64-encoded resources in glTF (raw and gzipped)
   * And Cesium load time
* File size for binary glTF (raw and gzipped)
   * And Cesium load time

@kainino0x fork https://github.com/KhronosGroup/glTF/ and work off the `new-extensions` branch.  Add any test models we created to a subdirectory under [extensions/CESIUM_binary_glTF](https://github.com/KhronosGroup/glTF/blob/new-extensions/extensions/CESIUM_binary_glTF/) and add the results to the `Experimental Results` section of the [README.md](https://github.com/KhronosGroup/glTF/blob/new-extensions/extensions/CESIUM_binary_glTF/README.md) and rename it to `Results`.  Also add your name to the `Contributors` section.

CC #2659

**Comment by kainino0x** [comment]
KhronosGroup/glTF#395

**Comment by pjcozzi** [comment]
Closing.  The PR in the glTF repo replaces this.
