### ISSUE TITLE
Blurry Text Rendering

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#2752]
Glyphs are rendered to a canvas which already has AA. When we render to a framebuffer, we apply FXAA which makes the text blurry.

We can change the pipeline so that text is rendered after FXAA or use multisampled textures when WebGL 2 is supported.

**Comment by bagnell** [comment]
See this forum post: https://groups.google.com/forum/#!msg/cesium-dev/lBAPrC7IaDw/9dcT9FV4d4kJ

**Comment by hpinkos** [comment]
Fixed in #7730

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!msg/cesium-dev/lBAPrC7IaDw/9dcT9FV4d4kJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/2752 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
