### ISSUE TITLE
Default view should look forward and include at least part of the Earth

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2765]
Back in Cesium 1.5, the default view for Molniyas, GEOs, and HEOs always showed the Earth behind the spacecraft.  Here's the default starting view for the Molniya in simple.czml:

![molniya_1 5](https://cloud.githubusercontent.com/assets/1235080/7886431/0ce53a3a-05f8-11e5-8b0e-e25343952668.png)

The yellow line is the future path, so we're looking where we're going, and the Earth remains in view for the entire animation time.

In the current version, things are different:

![molniya_1 6](https://cloud.githubusercontent.com/assets/1235080/7886457/35f8180c-05f8-11e5-85c0-00c15baf2685.png)

Note the yellow line: we're not looking where we're going.  Also we appear to be in the void of outer space with no reference to where the planet is.

LEOs have a similar story, although the Earth is at least visible for them.  Here's the old 1.5 view:

![leo_1 5](https://cloud.githubusercontent.com/assets/1235080/7886523/98b22eb0-05f8-11e5-8908-9e2c7831b5ab.png)

And here's 1.6.  Again you can see the line that represents future travel is almost perpendicular to the look vector, and we can't see where we're headed.

![leo_1 6](https://cloud.githubusercontent.com/assets/1235080/7886540/bcd345f4-05f8-11e5-8b46-4d518c662d49.png)

/cc #2716

**Comment by mramato** [comment]
I think these are just incidental to the default zoom bounding sphere.  I'm not convinced it's a bug.  I'm sure there are plenty of satellite orbits that looked bad in 1.5 and good in 1.6 as well.  Unless there was some special case code for default satellite views that I'm not aware of?

**Comment by emackey** [comment]
No, these views are more generic than you think, because the camera is sitting in a frame that's based on the vehicle velocity.  So in the older version, the camera looked in the direction of travel of all kinds of moving vehicles, and in the new version it gives a bad starting view for them all.  GEOs/HEOs/Molniyas are particularly egregious as the starting view is pointed up near Polaris.

I do love the idea of the zoom level being based on the bounding sphere size.  But the bounding sphere shouldn't dictate direction.  The default angle should be a good one, scaled in magnitude by the size of the bounding sphere, and overridable by the existing CZML property.

In 1.5, this initial direction (and magnitude, unfortunately) came from a line that's still with us in 1.9, namely [EntityView.js#L251](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.9/Source/DataSources/EntityView.js#L251).  This vector is still the default view for anything that lacks a bounding sphere.  But if the bounding sphere is present, it looks like the line is [Camera.js#L2325](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.9/Source/Scene/Camera.js#L2325).  In particular if you modify that Camera.js line to change `-PI_OVER_FOUR` to `-PI_OVER_TWO`, you'll see the default view is mathematically aligned from the center of the object to the center of the Earth.  This isn't pleasing to the eye but it gets the point across that you can "place" the Earth for any object view.

Ideally I'd like to take the direction from the default in EntityView and scale it to the correct magnitude depending on the size of the bounding sphere.

**Comment by mramato** [comment]
The current default view places the camera so that it's oriented north and looking down on the object at 45 degrees angle.  This is the best possible view for non-moving entities close to the earth (which is a majority of what our users are using).

I agree that it is a sub-optimal view for satellites, and probably not great for moving object, but that's why we let entities specify their own default view (a feature that need to be refactored and improved in the near future).

I understand some of your concerns, but I'm probably going to need some visual aids to completely understand what you're asking for.  Let's meet offline in the near future and go over it.
