### ISSUE TITLE
Scene test failure in Chrome with WebGL validation (ANGLE)

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#2771]
![image](https://cloud.githubusercontent.com/assets/1494815/7922034/969ce760-0877-11e5-9f0e-6058ca8c4791.png)

**Comment by mramato** [comment]
I'm actually getting 6 failures in Chrome with validation on (and several failures in Firefox as well).  They almost all have the same error `RuntimeError: WebGL Error:  INVALID_OPERATION: drawElements(4, 6, 5123, 0);`

**Comment by pjcozzi** [comment]
I did not get these when doing the 1.11 release today.

**Comment by bagnell** [comment]
In the console I also see these errors:
`WebGL: INVALID_OPERATION: drawElements: no ELEMENT_ARRAY_BUFFER bound`
`GL ERROR :GL_INVALID_VALUE : glDrawElements: out of memory`

**Comment by bagnell** [comment]
>I'm actually getting 6 failures in Chrome with validation on...

All of the tests pass for me if the `debugShowGlobeDepth` test doesn't run.

**Comment by mramato** [comment]
I'm still getting these failures as of the 1.13 release.

**Comment by pjcozzi** [comment]
Still the same in 1.15.

**Comment by pjcozzi** [comment]
All tests pass on Mac with WebGL validation so this is Windows/ANGLE related.

**Comment by mramato** [comment]
I can confirm that disabling ANGLE on windows makes the errors go away, we should write up an issue for them when we get a chance (after confirming our tests aren't doing anything odd themselves).

**Comment by lilleyse** [comment]
Getting these failures for the 1.16 release as well.

**Comment by mramato** [comment]
I can no longer produce the above failures; but I am seeing a new set of failures related to `Scene/Sun`across all browsers.  It's all the same error across multiple tests:

> Scene/Sun draws in 3D
> DeveloperError: Framebuffer is not complete.  Incomplete attachment: at least one attachment point with a renderbuffer or texture attached has its attached object no longer in existence or has an attached image with a width or height of zero, or the color attachment point has a non-color-renderable image attached, or the depth attachment point has a non-depth-renderable image attached, or the stencil attachment point has a non-stencil-renderable image attached.  Color-renderable formats include GL_RGBA4, GL_RGB5_A1, and GL_RGB565. GL_DEPTH_COMPONENT16 is the only depth-renderable format. GL_STENCIL_INDEX8 is the only stencil-renderable format.

Can someone confirm?  Should we look at this before 1.20?  A `DeveloperError` in our own code seems bad.
