### ISSUE TITLE
Two Line Element (TLE) Datasource

### ISSUE THREAD

**Issue by maikuru** [AnalyticalGraphicsInc/cesium#2772]
New feature

Datasource takes a TLE string and processes against SGP4/SDP4 algorithm or better, if someone has one that can be open sourced.

Possible options:
* Model to assign to the entity created
* expire date to stop using the TLE

**Comment by mramato** [comment]
This is outside the scope of Cesium proper.  If someone wants to provide this capability as a plug-in, we would be happy to list it on the plug-ins page.  See https://github.com/AnalyticalGraphicsInc/cesium-plugins-list for details.
