### ISSUE TITLE
heightReference for Labels and Billboards

### ISSUE THREAD

**Issue by bmckilligan** [AnalyticalGraphicsInc/cesium#2792]
Billboard._updateClamping  is throwing an error for billboards and labels  created in a label or billboard collection when trying to set a heightReference  value other than NONE  

a work around is to set the '_scene' value for the collections

 billboards = scene.primitives.add(new Cesium.BillboardCollection());
 labels = scene.primitives.add(new Cesium.LabelCollection());

//<workaroundCode>
billboards._scene = scene;
labels._scene = scene;
//</workaroundCode>

billboard = billboards.add({ ...   heightReference : Cesium.HeightReference.CLAMP_TO_GROUND });
label = labels.add({  heightReference: Cesium.HeightReference.CLAMP_TO_GROUND });

**Comment by mramato** [comment]
This is not a bug.  As per the documentation, you need to pass an options object to the constructor functions in order to enable heightReference functionality.

```javascript
billboards = scene.primitives.add(new Cesium.BillboardCollection({
    scene : scene
}));
```

**Comment by bmckilligan** [comment]
thanks, sorry I totally missed it, clear as day in the docs:
 http://cesiumjs.org/Cesium/Build/Documentation/BillboardCollection.html

'Must be passed in for billboards that use the height reference property or will be depth tested against the globe.'
