### ISSUE TITLE
cesium viewer not loading in latest dev

### ISSUE THREAD

**Issue by chriswingler** [AnalyticalGraphicsInc/cesium#2793]
latest dev:
![screenshot 2](https://cloud.githubusercontent.com/assets/2586623/8026897/67233c2c-0d50-11e5-8c74-4c8068b159b6.png)

cesium 1.10:
![screenshot 1](https://cloud.githubusercontent.com/assets/2586623/8026898/678c0428-0d50-11e5-8809-9c80226a82bc.png)

errors caught by chrome during page load:

Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/GlobeFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/GlobeFSDepth
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/GlobeFSPole
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/GlobeVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/GlobeVSDepth
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/GlobeVSPole
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SkyAtmosphereFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SkyAtmosphereVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SunFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SunTextureFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SunVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SkyBoxFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/SkyBoxVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/AllMaterialAppearanceFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/AllMaterialAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/BasicMaterialAppearanceFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/BasicMaterialAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/TexturedMaterialAppearanceFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/TexturedMaterialAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/PerInstanceColorAppearanceFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/PerInstanceFlatColorAppearanceFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/PerInstanceColorAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/PerInstanceFlatColorAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/BillboardCollectionFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/BillboardCollectionVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PolylineCommon
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PolylineFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PolylineVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/PolylineColorAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Appearances/PolylineMaterialAppearanceVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PointPrimitiveCollectionFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PointPrimitiveCollectionVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Builtin/CzmBuiltins
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/EllipsoidFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/EllipsoidVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/BumpMapMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/CheckerboardMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/DotMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/GridMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/FadeMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/NormalMapMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/PolylineArrowMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/PolylineGlowMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/PolylineOutlineMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/RimLightingMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/StripeMaterial
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/Materials/Water
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/ViewportQuadVS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PostProcessFilters/FXAA
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PostProcessFilters/PassThrough
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/AdjustTranslucentFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/CompositeOITFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PostProcessFilters/AdditiveBlend
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PostProcessFilters/BrightPass
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/PostProcessFilters/GaussianBlur1D
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/ReprojectWebMercatorFS
http://requirejs.org/docs/errors.html#scripterror
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Script error for: Cesium/Shaders/ReprojectWebMercatorVS
http://requirejs.org/docs/errors.html#scripterror

**Comment by mramato** [comment]
I just verified that Cesium is working fine at head of master.  This looks like you forgot to run the ant build step.  See the [Contributor's Guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Contributor%27s-Guide) for full instructions on on building Cesium.
