### ISSUE TITLE
CesiumViewer app should save more parameters

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2798]
In particular, it should save `sceneMode`, because camera views saved from 2D mode are not particularly appealing when reloaded in the default 3D view.

Also, it should save `lookAt` when `viewer._trackedEntity` changes, and make sure the camera gets restored to tracking and looking correctly on reload.

**Comment by emackey** [comment]
Since we're peeking down a rabbit hole here, I'll add this:  Maybe we should save `clock.currentTime` as well, as restoring a camera view from a different time does not return you to the view you once had.

**Comment by pjcozzi** [comment]
Good ideas here.

We could also turn this off in 2D/CV.

I suggest keeping this a minimal as possible since I imagine we would introduce a JSON format for scene configuration like the current time, widget layout, terrain, etc.

**Comment by mramato** [comment]
This is the kind of rabbit hole I was concerned about when we started to add these features.  The important thing to keep in mind is that the Cesium Viewer is a demo app with no guaranteed backwards compatibility.  That being said, the right thing to do here is to not actually put the raw data in the url but instead have some JSON object that cibtaubs viewer state that we simply and encode into a single URL parameter.  This lets us add more data later without adding more query options or braking existing urls.  If we wanted to get fancy, we could also have a "share" button that generates a shortened url using one of the freely available services.

**Comment by pjcozzi** [comment]
Is this still relevant?

**Comment by mramato** [comment]
I second closing this.  The viewer app is a simple sample application and I don't see a reason to add additional feature to it.
