### ISSUE TITLE
`Matrix4.multiplyByScale` documentation unclear - requires affine matrix

### ISSUE THREAD

**Issue by kainino0x** [AnalyticalGraphicsInc/cesium#2799]
EDIT: The documentation says that the transformation matrix has a bottom row of [0, 0, 0, 1], but isn't clear that this is assumed and required. Proposed edit:

```
     * Multiplies an affine transformation matrix (with a bottom row of <code>[0.0, 0.0, 0.0, 1.0]</code>)
     * by an implicit non-uniform scale matrix.  This is an optimization
     * for <code>Matrix4.multiply(m, Matrix4.fromScale(scale), m);</code>, where
     * <code>m</code> must be an affine matrix, with less allocations and arithmetic operations.
     *
     * @param {Matrix4} matrix The affine matrix on the left-hand side.
```

[Matrix4.js:1750](https://github.com/AnalyticalGraphicsInc/cesium/blob/6dc467a717598a24cf6aa77821975a39e35bd74d/Source/Core/Matrix4.js#L1750)

[Matrix4Spec.js:638](https://github.com/AnalyticalGraphicsInc/cesium/blob/6dc467a717598a24cf6aa77821975a39e35bd74d/Specs/Core/Matrix4Spec.js#L638)

**Comment by kainino0x** [comment]
Actually, it does specify, but unclearly - updated description

**Comment by pjcozzi** [comment]
Do you plan to open a PR with a new description?

**Comment by kainino0x** [comment]
I initially opened an issue since I wasn't clear whether the behavior or the documentation should change. But since I determined it makes more sense to change the documentation, I'll do that.

**Comment by kainino0x** [comment]
Closing in favor of PR #2801.
