### ISSUE TITLE
Tracking objects in 2D seems problematic

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2803]
```
http://localhost:8080/Apps/CesiumViewer/index.html?source=..%2FSampleData%2Fsimple.czml&lookAt=Satellite%2FMolniya_1-92
```

Load the above.  There's a delay while the camera attempts to fly to the dataSource.  When that's done, switch to 2D mode.  The whole screen goes black for me.  If you pan around in the blackness for a while, `scene` will throw `Invalid array length`.

**Comment by mramato** [comment]
This (thankfully) doesn't happen in 1.10, so it's probably related to one of the recent camera changes.

**Comment by pjcozzi** [comment]
@bagnell can you please have a look?

**Comment by emackey** [comment]
Correction, the error thrown happens on zoom, not pan.
