### ISSUE TITLE
Remove bounding volumes' `.intersect` in Cesium 1.13

### ISSUE THREAD

**Issue by kainino0x** [AnalyticalGraphicsInc/cesium#2807]
* `AxisAlignedBoundingBox.intersect`
* `AxisAlignedBoundingBox.prototype.intersect`
* `BoundingSphere.intersect`
* `BoundingSphere.prototype.intersect`

Deprecated in 1.11, PR #2782.

**Comment by pjcozzi** [comment]
@kainino0x can you remove this soon for the upcoming 1.13 release?
