### ISSUE TITLE
Don't mutate objects returned by CallbackProperty

### ISSUE THREAD

**Issue by alexander-entin** [AnalyticalGraphicsInc/cesium#2809]
In some cases setting entity's position like this
`position: new C.CallbackProperty(function() { return that.labelPosition }, false)`
ends with misplaced entity (some other entity position is used).

To overcome, one needs to clone the position before returning:
`position: new C.CallbackProperty(function() { return that.labelPosition.clone() }, false)`

While the workaround is rather simple, it is too easy to forget and spend hours hunting the bug.

**Comment by hpinkos** [comment]
Thanks for reporting this @alexander-entin.  This is related to a bigger problem with ownership management that we are planning to address in the future (most likely for Cesium 2.0)
I'm going to close this issue since it will be addressed then.

**Comment by mramato** [comment]
I missed this when it was first submitted, but the complete answer is that the `CallbackProperty` callback signature is `function(time, result)`.  If the result parameter is provided, it should be mutated by the function.  If result is not specified, a new instance should be returned but that instance is owned by the caller (i.e. Cesium).  It will most likely use that value for the result parameter in the future.

This should be clarified in the CallbackProperty documentation.
