### ISSUE TITLE
Calling scene.drillPick breaks scene.pickPosition

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#2813]
In the picking sandcastle example, replace line 143 (`scene.pick(....)`) with
```
var pickedObject = scene.drillPick(movement.endPosition)[0];
```

The position returned by `scene.pickPosition` is incorrect. (For this demo, the height is negative).
I'm pretty sure it's picking the ellipsoid instead of the model.

**Comment by pjcozzi** [comment]
@hpinkos is this holding you up?  If so, we can look at it after #2810.

You could also take a quick look at `pickPosition` and `pick`; it might not be too hard to figure out.

**Comment by hpinkos** [comment]
@pjcozzi I skimmed through and I couldn't find anything obvious that `drillPick` was doing weird.   I might look into it further tomorrow.

It's not holding me up, but the functionality of what I'm working on will be better once this is fixed.

**Comment by emackey** [comment]
I haven't looked deeply yet, but it's possible this is related to #2790.
