### ISSUE TITLE
Image flips when the geometry coordinate longitude crosses -180/180

### ISSUE THREAD

**Issue by abhishekvp** [AnalyticalGraphicsInc/cesium#2818]
The image flips when the geometry coordinates cross -180/180. I have narrowed it down in a Sandcastle Example, displaying 2 wall geometries with numbered images so it is easier to make out the flipping.

I tried hosting the example on Github, forking the Cesium repository and creating a gh-pages branch, but couldn't. So here's the source code of the example: https://github.com/abhishekvp/cesium/blob/gh-pages/Apps/Sandcastle/gallery/ImageFlip.html

**Comment by hpinkos** [comment]
Order matters for your positions.

For the flipped ones, swap the longitude coordinates

```
positions: Cesium.Cartesian3.fromDegreesArray([ 179.96,-18.99, -170.59, -18.99]),
```

**Comment by pjcozzi** [comment]
Ah, good eye, thanks @hpinkos.

@abhishekvp thanks for narrowing this down.

[Forum discussion](https://groups.google.com/forum/#!topic/cesium-dev/Dp_asXZbZ4E)
