### ISSUE TITLE
what is fromDegrees?

### ISSUE THREAD

**Issue by vinita90** [AnalyticalGraphicsInc/cesium#2820]
whatb is fromDegrees in 

 position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),

i want to put that obstacle at my lat long

**Comment by mramato** [comment]
fromDegrees creates a Cartesian3 instance from the specified longitude and longitude in degrees (as opposed to radians). I would recommend you check out the tutorials, especially the [Visualizing Spatial Data](http://cesiumjs.org/2015/02/02/Visualizing-Spatial-Data/) tutorial.

In the future, please use [the forum](https://groups.google.com/forum/#!forum/cesium-dev) for general Cesium questions and support.
