### ISSUE TITLE
Remove redirect for //cesiumjs.org/stk-terrain/world

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2833]
Deprecated in 1.11, see #2832 for details.

**Comment by pjcozzi** [comment]
Just a reminder that this is labeled for 1.14 on Thursday.

**Comment by pjcozzi** [comment]
The release is today.  What is the plan?

**Comment by mramato** [comment]
It's a 1 line change in the web.config, I just assumed it would be part of the release PR into the website, I'll open a separate PR if you want.

**Comment by pjcozzi** [comment]
One PR is fine.  Up to you.
