### ISSUE TITLE
Zooming out with mouse wheel zooms from scene center, not mouse position

### ISSUE THREAD

**Issue by rutsky** [AnalyticalGraphicsInc/cesium#2834]
In master branch with done #302 mouse now zooms in into mouse position, but zooms out still from scene center, not mouse position.

**Comment by mramato** [comment]
I agree with @rutsky.  whether it's mouse-wheel or righ-click based, the zoom-in/zoom-out behavior should be reversible.  Right now zooming out and in in the same motion creates very awkward behavior. Conceptually, this seems like it should be easy to implement @bagnell any thoughts here?

**Comment by mramato** [comment]
Try this: `Home view -> right-button on California -> zoom out a bunch -> zoom back in (all in one motion)`   You end up in the middle of the Pacific instead of California.

**Comment by pjcozzi** [comment]
Fixed in #2840, right?

**Comment by mramato** [comment]
Yes
