### ISSUE TITLE
Remove smallterrain usage

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2836]
The smallterrain dataset is no longer available after cesiumjs.org and assets.agi.com were split into 2 different servers.  Our tests depend on it in 2 places, see #2835, which fixes the tests temporarily until they can be migrated to use different terrain.

**Comment by pjcozzi** [comment]
What exactly needs to be done here?

**Comment by mramato** [comment]
As discussed in the linked issue, we're just going to move the smallterrain set so it can still be used for testing, I'll open a separate PR with the final urls once everything is migrated to its new home.

**Comment by pjcozzi** [comment]
Is this still a `show stopper` for 1.11?

**Comment by mramato** [comment]
It's a test only change, but it should go into 1.11.  I just opened #2855 for it.  I was previously waiting for the transfer I kicked off yesterday to finish.
