### ISSUE TITLE
Using the STK terrain tiles from a https site fails

### ISSUE THREAD

**Issue by keattang** [AnalyticalGraphicsInc/cesium#2837]
It seems the redirect no longer handles the protocol correctly and causes a mixed content error

**Comment by kring** [comment]
Guys, can you pretty please not take down the terrain server or redirecting server to fix this in the next hour or so? :)

**Comment by mramato** [comment]
Sorry for the delay, this is now fixed.  If you're still having problems, let us know.

**Comment by mramato** [comment]
I forgot to add that the correct url for the terrain is `assets.agi.com/stk-terrain/world`, if you are using the older `cesiumjs.org/stk-terrain/world` url, you should update your code. The redirect that is in place will cause slower overall performance.  It was the redirect that was broken in this case, https over assets.agi.com was unaffected.
