### ISSUE TITLE
Camera inertia takes way too long to finish

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2839]
I noticed both in the camera move events example and via #2838 that the camera inertia takes several seconds to finish after the user lets go of the mouse.  It seems it continues to move a minuscule amount < 1 meter for several seconds.  This greatly decreases the usefulness of the move events because it creates what is perceived as lag.  We should shorten the inertia or have a cut off that once the inertia is less than a certain amount, we just stop.

**Comment by hpinkos** [comment]
related: #2715
