### ISSUE TITLE
Contributor License Agreement links broken

### ISSUE THREAD

**Issue by nmschulte-aviture** [AnalyticalGraphicsInc/cesium#2852]
The links to the individual and corporate CLAs (currently hosted on the AGI/agi.com website) are broken (in CONTRIBUTING.md).

**Comment by mramato** [comment]
Thanks, I'm looking into this.

**Comment by pjcozzi** [comment]
@nmschulte-aviture you are already covered by the Aviture corporate CLA unless you are contributing this as an individual in which case you would want to fill out the individual CLA.

If you need the CLA before the links are fixed, email me (pjcozzi@siggraph) and I can send it to you.

**Comment by nmschulte-aviture** [comment]
@pjcozzi, that's my understanding as well (thanks for confirming!).  I made the issue for the reason that it's broken and making it easy for others to contribute is probably a goal.

**Comment by mramato** [comment]
Thanks again for reporting this.  The issue has been fixed.
