### ISSUE TITLE
Uint32Array undefined error in ie9

### ISSUE THREAD

**Issue by gberaudo** [AnalyticalGraphicsInc/cesium#2857]
Older versions of Cesium used to load the Cesium script without error.

Starting with version 1.10, an error occurs due to the use of the undefined Uint32Array in Scene/Model.js: `var sizeOfUint32 = Uint32Array.BYTES_PER_ELEMENT;`.

Having a code like `Uint32Array = Uint32Array || {};` in application code workarounds the issue.

**Comment by pjcozzi** [comment]
Thanks for the report and workaround, we'll try to get a fix into 1.12.

**Comment by pjcozzi** [comment]
Thanks again @gberaudo.  Fixed in #2858.
