### ISSUE TITLE
Rendering issues during resize

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2880]
Resizing Cesium in 1.10 or later causes different rendering problems in both Chrome and Firefox.  This is easy to see in the Box example.  We should try and fix this for 1.12.

1.9 : http://cesiumjs.org/releases/1.9/Apps/Sandcastle/gallery/Box.html
1.11: http://cesiumjs.org/releases/1.11/Apps/Sandcastle/gallery/Box.html

**Comment by pjcozzi** [comment]
@bagnell can you look at this?  Do you think @kainino0x and I introduced this with the sun/stars fix?
