### ISSUE TITLE
drillPick makes Safari and Chrome crash on iOS

### ISSUE THREAD

**Issue by jimmyangel** [AnalyticalGraphicsInc/cesium#2892]
Hi All:

First, thank you very much for making Cesium available... It is really cool.

I am having some trouble with Cesium on iOS though. The drillPick functionality will make both Chrome and Safari freeze and or crash almost every time I get more than a few features returned by the function. It happens on both an iPhone 6 and an iPad 2 running iOS 8.4.

Here is a reproducer: http://rikitraki.com/test.html

Just touch the yellow blob near Florida and the browser will freeze.

Thank you,

Ricardo

**Comment by pjcozzi** [comment]
Thanks for the report and upcoming Cesium website showcase, @jimmyangel.

If you know something is a bug, please submit an issue like this; if you're not sure, start a thread on the forum, but don't worry about doing both.

When Cesium does a drill pick, it renders the scene once for each object under the mouse cursor.  In this case, there can be a lot of objects so I _think_ it is just taking a long time to render.  Try the new `limit` parameter to [drillPick](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Scene.js#L1912) so only the top n objects are considered.

CC [forum post](https://groups.google.com/forum/#!topic/cesium-dev/_lQaHR32cMQ)

**Comment by mramato** [comment]
As mentioned in the forum post, `limit` seemed to fix the problem.
