### ISSUE TITLE
Incorrect billboard bounding sphere

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#2894]
![image](https://cloud.githubusercontent.com/assets/3451886/8755042/f986f8c4-2c95-11e5-929a-1bd56663ce39.png)

This is why we can only pick a pin by clicking the bottom of it.

The bounding sphere needs to be altered if `verticalOrigin` is `TOP` or `BOTTOM`.  When `horizontalOrigin` is defined the sphere changes, but it needs to for `verticalOrigin` as well.

**Comment by pjcozzi** [comment]
Also see #2225.  There could be more than one problem.  @hpinkos a fix is welcomed if you have time.
