### ISSUE TITLE
Incorrect canvas pixel position when using two maps

### ISSUE THREAD

**Issue by tomermoshe** [AnalyticalGraphicsInc/cesium#2896]
When im using two maps (in two different divs that are in the same hirarchy in the DOM) I get incorrect canvas position (pixel position) using the following code:
```js
var handler = new Cesium.ScreenSpaceEventHandler(scene.canvas)
handler.setInputAction(function(movement){
   movement.endPosition;   //correct positoin only in the second canvas.
})
```
In the first map, `movement.endPosition` is relative to the screen position of the second map's canvas (it can be negative if the cursor is left to the second map's canvas).

**Comment by mramato** [comment]
@bagnell any thoughts here?  Sounds like a similar bug we had where we weren't taking offset within the body into account.

**Comment by hpinkos** [comment]
@tomermoshe I can't reproduce this.  Do you only have the `ScreenSpaceEventHandler` on the second map's canvas or do you have a handler for both?  How are your maps oriented? left and right or top and bottom?
thanks!

**Comment by mramato** [comment]
I'm also unable to reproduce this using the below Sandcastle code.  I'm going to close this for now since we haven't heard anything in a while, but @tomermoshe, if you are still having problems and can provide some runnable code to show the issue we can reopen it.  Thanks.

```html
<style>
    @import url(../templates/bucket.css);
</style>
<div id="cesiumContainer" style="width:50%; height:50%;"></div>
<div id="cesiumContainer2" style="width:50%; height:50%;"></div>
<div id="loadingOverlay"><h1>Loading...</h1></div>
<div id="toolbar"></div>
```

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var viewer2 = new Cesium.Viewer('cesiumContainer2');

var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handler.setInputAction(function(movement){
    console.log('viewer: ' + movement.endPosition);
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);

var handler2 = new Cesium.ScreenSpaceEventHandler(viewer2.scene.canvas);
handler2.setInputAction(function(movement){
    console.log('viewer2: ' + movement.endPosition);
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);
```
