### ISSUE TITLE
Add failIfMajorPerformanceCaveat query parameter for tests

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2906]
So the SwiftShader folks can test with our unit tests.

Note that `failIfMajorPerformanceCaveat` can be passed as part of the `webgl` options to Viewer similar to [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Widgets/Viewer/ViewerSpec.js#L348).

**Comment by emackey** [comment]
Is there ever a reason to run unit tests with `failIfMajorPerformanceCaveat = true` ?

**Comment by mramato** [comment]
Is defaulting to true even a good idea?  When people encounter this problem they simply override it back to false anyway so I'm not really sure we're helping anyone.

**Comment by emackey** [comment]
Good point, maybe using the watchdog timer message thing to warn users of bad performance is better than having it fail like this.

**Comment by pjcozzi** [comment]
For now, we'll set `failIfMajorPerformanceCaveat : false` for the tests.
