### ISSUE TITLE
Culling Volumes?

### ISSUE THREAD

**Issue by chriswingler** [AnalyticalGraphicsInc/cesium#2914]
Hey folks, I've been learning Javascript and Cesium the past month or so and it's great!  I can come up with a ton of questions, but I'll stick to one and ask how culling volumes work.

What I'm trying to do is create a first person view, where if you're moving fast (like riding a dirkbike through national park trails), the terrain and imagery immediately in front of you loads first and doesn't cull within an arbitrary distance that would be appropriate for such a sim.  The goal is to have the terrain immediately in front of you pre-loaded and I'm assuming not culled.

What would be the best way to do this?  I've been suspecting it has something to do with the camera bounding sphere, but documentation is scarce to my knowledge on this.

It seems like I'd need to create a small bounding sphere around the camera inside of another bounding sphere, where the inner one doesn't cull.  Is this correct?  Am I off base here?

Thanks in advance,
Chris

**Comment by pjcozzi** [comment]
@chriswingler please post questions like this on the [Cesium forum](http://cesiumjs.org/forum.html).  It will get a lot more attention since we use GitHub just for issue tracking.

This topic has been discussed a few times before so you might find some info searching on the forum.
