### ISSUE TITLE
Add {reverseZ} to UrlTemplateImageryProvider

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#2917]
Requested in the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/L3VPz8guGbI

**Comment by kaktus40** [comment]
Hello,
I made a pull request : https://github.com/AnalyticalGraphicsInc/cesium/pull/2919

**Comment by pjcozzi** [comment]
Thanks @kaktus40
