### ISSUE TITLE
TileDiscardPolicy.shouldDiscardImage documentation

### ISSUE THREAD

**Issue by slozier** [AnalyticalGraphicsInc/cesium#2930]
The `TileDiscardPolicy.shouldDiscardImage` documentation says that it should accept an `Image|Promise<Image>` and return a `Promise<Boolean>`. This does not appear to be true in the implementations of this interface:

`NeverTileDiscardPolicy.shouldDiscardImage` has the same documentation but the code actually returns a `Boolean`.

`DiscardMissingTileImagePolicy.shouldDiscardImage` accepts an `Image` and returns a `Boolean`.

I tend to think that `DiscardMissingTileImagePolicy` is correct and the documentation of the `TileDiscardPolicy` interface and `NeverTileDiscardPolicy` should be updated...

**Comment by pjcozzi** [comment]
> I tend to think that DiscardMissingTileImagePolicy is correct and the documentation of the TileDiscardPolicy interface and NeverTileDiscardPolicy should be updated...

Agreed, good catch.
