### ISSUE TITLE
Billboards no longer show up in 2D if terrain is enabled

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2951]
[via the forum](https://groups.google.com/d/msg/cesium-dev/LNRMg40XpR8/y7czsP2wDQAJ)

As of 1.12, Billboards no longer show up above the terrain (even satellites) in 2D.  Run the [1.12 CZML example](http://cesiumjs.org/releases/1.12/Apps/Sandcastle/index.html?src=CZML.html&label=DataSources) and switch to 2D and turn on terrain.  This doesn't happen in 1.11.

**Comment by mramato** [comment]
FYI, Points have the same problem.

**Comment by pjcozzi** [comment]
Fixed in #2957.
