### ISSUE TITLE
Make Cesiumjs Webpack and Browserify Friendly and publish on NPM

### ISSUE THREAD

**Issue by mmacaula** [AnalyticalGraphicsInc/cesium#2981]
See: [forum post](http://cesiumjs.org/forum.html#!msg/cesium-dev/fH3oiHZnHgE/31MiuygDCHoJ)

The source code changes are minimal, just remove package.json files in Source/* directories and could be done in a quick PR.  

To become more friendly, it would be nice to publish the compiled workers and source code on npm so that people could npm install it without having to do a special build step.  Ideally they would just:

```
npm install cesiumjs
var viewer = require('cesiumjs/Source/Widgets/Viewer/Viewer');
```
and so on.  The default js file could be the viewer since that is likely how most applications start out, but there's nothing to prevent people from requiring in just what they need.  

Ideally, as mentioned on #1438 , @adius said he'd be willing to give up the cesiumjs name on npm for the official cesium once we're ready.  

Thoughts?

**Comment by mramato** [comment]
We're definitely interested in supporting Webpack and Browserify out of the box.  I was just talking to @kring and @shunter about this last week.  Hopefully one of them can chime in with some additional thoughts since I personally haven't used either yet. (If only there were more hours in the day).

As for publishing things on NPM.  It's definitely in our long-term roadmap but I think there's definitely more work that we need to do under the hood.  We'll also need to make changes to the release process and automate as much as possible in order to make it easy to maintain.

**Comment by mmacaula** [comment]
@mramato I'd be happy to help with the npm publishing, or at least dive into it to make sure I understand what needs to be done.  Am I correct in assuming that most of the current process is in the build.xml file?

**Comment by mramato** [comment]
Yes, and related js files they reference.  In truth we would love to move Cesium to an all node/gulp based build process and remove the need for ant/java completely, but no one has had the time to do it (and there's quite a build involved given both the complex nature of Cesium and things like shaders and web workers).

We also want to make it easy to use Cesium as an NPM module on the server.  One way we plan on accomplishing that is to switch to using ES6 module syntax in Source and then produce UMD modules as output (which is what we would ship).

Anyway, sorry for the brain dump.  Like I said, hopefully Scott or Kevin can chime in with some thoughts.

**Comment by rutsky** [comment]
@mmacaula, you mentioned in the mailing list that you managed to build pure Cesium with minimal changes (removing package.json) with webpack.
How did you handle building `.glsl` into `.js` files?
Did you handle debug macroses, like following?

```
        //>>includeStart('debug', pragmas.debug);
        throw new DeveloperError('Unable to infer material type: ' + value);
        //>>includeEnd('debug');
```

**Comment by mmacaula** [comment]
@rutsky.  I did not handle the debug macros.  I believe the .glsl files are all part of web workers (if I'm not mistaken) and because of that, as long as we use the built versions of those web workers then we do not need to worry about it unless you want webpack to also build those webworkers.  I of course could be mistaken on this and just not exercised the code enough. 

I'm not an expert at webpack but those two items could also be done in a webpack friendly way too.  I can imagine a glsl loader and a plugin that could strip out the macros based on your webpack config file.

**Comment by mramato** [comment]
It has nothing to do with the workers.  The glsl files are never used directly, they are transformed into JavaScript files during the `ant build` process.  If you use a released version of Cesium modules or the combined Cesium.js, then the glsl files are never touched.

While it certainly doesn't have to be in the initial solution, handling debug macros should definitely be a long term goal, since it affects performance.

**Comment by mmacaula** [comment]
I see, thanks @mramato, I must have been mistaken on it only needing the workers built.  I think I misspoke in the forum and used the downloaded version of cesium, which includes all the js files from the .glsl files. 

@mramato, stepping back a bit, can you explain the reasons behind the package.json files in the source directory?  If they are not used, then getting rid of them would allow us to publish steps to working with webpack with pure cesium.  These steps I believe would be something like this:

1.  Clone Cesium repo in your package.json or bower.json or download it
2.  If cloned, run `ant build`
3.  Copy the Workers and Assets directory from Build and make sure they are hosted on your app
4.  set Base url: `buildModuleUrl.setBaseUrl('path/to/Assets/parent/'); `

We could put these steps in the Getting Started Docs, or somewhere else.  Then we could address the build and publishing on npm separately, while only minimally affecting Cesium as is.  Thoughts?

**Comment by bartvde** [comment]
Running into this issue as well with browserify, would be great if this could be handled properly out of the box.

**Comment by mmacaula** [comment]
@mramato, as far as strategy getting this done, would you approve with an approach of a PR that would remove the package.json files from the source directories first, followed by work on updating the build?   I'm still not 100% what purpose those package.json files serve...

**Comment by mmacaula** [comment]
So I was thinking a [tutorial](http://cesiumjs.org/tutorials.html) might be a good next step for those wanting to use cesium in webpack or browserify right away.  Thoughts?  I don't see a defined process for writing one.  How is it done exactly?

**Comment by pjcozzi** [comment]
A tutorial would be awesome.  Email me, pcozzi@agi.com, and I will connect you with our editor.

**Comment by bartvde** [comment]
is there any progress on the tutorial? TIA.

**Comment by mmacaula** [comment]
hey @bartvde, it is still a work in progress (still being reviewed) but you can see it at https://github.com/aviture/cesium-webpack

**Comment by bartvde** [comment]
thanks for pointing me to this @mmacaula

**Comment by andthenwhat** [comment]
has anyone had success with browserify?  My attempts to used browserify.external and browserify.ignore have just produced different versions of failure.  I can post the problems I'm having, but wanted to see if anyone had succeeded before I do.

**Comment by mramato** [comment]
I believe our official `cesium` node module and @mmacaula's excellent blog post/example repository resolves this issue, correct?  @mmacaula is there anything else on the cesium end you feel needs to be done?  Thanks.

**Comment by mmacaula** [comment]
Yes, let's close.  Thanks!

**Comment by bensleveritt** [comment]
It's worth noting that [mmacaula's repo](https://github.com/mmacaula/cesium-webpack) is more up to date (with post 1.6 instructions).

**Comment by mmacaula** [comment]
Nope all done, we can close
