### ISSUE TITLE
Exception in ImageryLayer

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2985]
- Run viewer.
- Switch to 2D.
- Switch to Mapbox Streets.
- Use the geocoder to zoom into "Downingtown, PA"
- Switch to Columbus view, and get the following exception:

![image](https://cloud.githubusercontent.com/assets/782098/9577906/71f3dca6-4fb3-11e5-801d-70f939c64b11.png)

The line is:

``` javascript
maxU = Math.min(1.0, (clippedImageryRectangle.east - terrainRectangle.west) / terrainRectangle.width);
```

Also in Cesium 1.12.

**Comment by kring** [comment]
I followed the instructions above, but I can't reproduce this in this instance of Cesium Viewer:
http://cesiumjs.org/Cesium/Apps/CesiumViewer/index.html

Is it still broken for you?

**Comment by hpinkos** [comment]
This appears to be fixed
