### ISSUE TITLE
Middle mouse look does not stop inertia

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2988]
1. Fling the earth in any direction with the left mouse.
2. While the inertia is still going, hold down the middle mouse to rotate.

The inertia should stop the moment the middle mouse is down (or down and moves) but instead the inertia keeps going while I'm looking around.

**Comment by emackey** [comment]
This is true of any two different types of motions.  For example, you can zoom while pan inertia is going and vice versa.  Sometimes the effect is visually cool, I kind of like it.

**Comment by mramato** [comment]
No one has really complained about this and while I thought it was weird, it hasn't been a usability problem yet, so I'll just close.
