### ISSUE TITLE
Crash on Nexus 7 when modifying Entity

### ISSUE THREAD

**Issue by jasonbeverage** [AnalyticalGraphicsInc/cesium#2995]
I'm experiencing a crash on my Nexus 7 when attempting to modify an Entity's show property.  The same issue occurs when I try to change the position.

I've uploaded a test to demonstate the crash at  https://s3.amazonaws.com/jason.beverage.uploads/cesium-entity-crash/entity.html

That example will toggle an entity's show property every 10 frames.  On every device I've tested it appears to work, but on the Nexus 7 the first time you try to modify the show property you get an exception of 

An error has occurred while rendering.  Rendering has stopped
RangeError: Invalid array length

This is similar to this issue https://github.com/AnalyticalGraphicsInc/cesium/issues/1477 but appears to be somewhat of a catchall.

Another note is that my example is displaying an entity with a billboard and a label.  If I just do one (either a label OR a billboard) and not both, the entity hides correctly on the first toggle of show but never appears again when show is toggled to true.

**Comment by hpinkos** [comment]
@jasonbeverage do you know if this is still a problem?  Thanks!

**Comment by jasonbeverage** [comment]
It's been a long time since I've tested this on a Nexus, I'm not sure.  I want to say that an Android update may have fixed it.  It's not a pressing problem for us at the moment so feel free to close this issue if we were the only ones with the issue.

**Comment by hpinkos** [comment]
Thanks @jasonbeverage, I know we haven't seen any problems like this lately with our android devices.  If you do discover it's still a problem, feel free to reopen the issue.  Thanks again!
