### ISSUE TITLE
3d-tiles branch: tile unloading

### ISSUE THREAD

**Issue by jbo023** [AnalyticalGraphicsInc/cesium#2999]
We created a b3dm dataset for Berlin with 500000 textured buildings. Unfortunately cesium crashes after some time viewing the dataset. After some debugging we found out that cesium never unloads b3dm tiles from the GPU memory. On my machine it crashes after the chrome taskmanager shows 3.6gb GPU memory used. I also couldn’t find any code for unloading tiles. Do you have any internal development for this already?

**Comment by pjcozzi** [comment]
We haven't developed this yet, but, of course, we plan to.  We want to get a bit deeper into the load pipeline and refinement strategies before we do cache management because we need to look at cases like, for example, if we will allow child to be loaded without their parent.

**Comment by jbo023** [comment]
If someone has the same problem, we started with a rudimentary unloading strategy, which basically just unloads b3dm tiles if they are not visible anymore. The Code is not great but makes it possible to visualize 500k textured buildings without filling up memory.

You can find the code in our Cesium Fork. 
https://github.com/virtualcitySYSTEMS/cesium/tree/3d-tiles

**Comment by pjcozzi** [comment]
3D Tiles cache replacement was added in #3808.  Let me know if you have any feedback.
