### ISSUE TITLE
Update README.md screenshots

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3005]
Update [README.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/README.md) screenshots to include all the new [showcases](http://cesiumjs.org/demos.html).

I'll take care of this soon.

**Comment by fantasticole** [comment]
Hi Patrick! I just submitted a PR for this issue. Please let me know if I did anything incorrectly, as this is my first PR!

**Comment by fantasticole** [comment]
Hi Patrick! I just submitted a PR for this issue. Please let me know if I did anything incorrectly, as this is my first PR!
