### ISSUE TITLE
Fabric wiki page has broken link on image

### ISSUE THREAD

**Issue by rutsky** [AnalyticalGraphicsInc/cesium#3008]
On [this](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric) page there is an image with source https://github.com/AnalyticalGraphicsInc/cesium/wiki/materials/Grid.PNG which doesn't exists, but https://github.com/AnalyticalGraphicsInc/cesium/wiki/materials/Grid.png (extension in lowercase) exists.

**Comment by pjcozzi** [comment]
Thanks @rutsky.  This is fixed now.
