### ISSUE TITLE
Camera moveEnd not triggered when globe spun

### ISSUE THREAD

**Issue by adamish** [AnalyticalGraphicsInc/cesium#3012]
in Cesium 1.13 if you move the globe (any Cesium.Viewer instance) using a "flick" gesture, i.e. the mouse is still moving at the point the mouse button is released then viewer.camera.moveEnd is NOT triggered. 

The moveEnd event appears to work correctly when moving the globe normally, e.g. a simple mouse down, move, mouse up. 

Example

    var viewer = new Cesium.Viewer('cesiumContainer');
    viewer.camera.moveEnd.addEventListener(function () {
        console.log("camera move");
    }, this);

**Comment by mramato** [comment]
I can't reproduce what you are seeing.  It takes way too long, but the camera event always fires.  Are you sure you simply aren't running into #2839? (We should fix this sooner rather than later either way).

**Comment by hpinkos** [comment]
Also related: #2715

**Comment by adamish** [comment]
Yes this is a duplicate of 2715, the event is triggered, it just happens 10+ seconds later... Sorry I was being impatient...

**Comment by pjcozzi** [comment]
Thanks @adamish
