### ISSUE TITLE
Credits take up too much canvas real estate

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3013]
For example, here is the default Cesium Viewer at 350x350:

![image](https://cloud.githubusercontent.com/assets/782098/9787990/03905d40-5795-11e5-9bb6-5db3b0915160.png)

The credits take up too much space.  Here is the same view with terrain enabled at 350x350:

![image](https://cloud.githubusercontent.com/assets/782098/9788007/2558b8e6-5795-11e5-9da9-79c663b6eaa8.png)

We have discussed only showing terrain credits for visible tiles.  I fully support this, but we need to do more.

Perhaps we can leave the Cesium logo as a canvas overlay and provide an option to put the other credits on any DOM element (which defaults to the Cesium Viewer canvas)?  We'll need to look at the Terms of Service for the various data providers, but there's a reasonable chance the credits can be put on the main page even if they do not overlay the Cesium Viewer canvas (e.g., for apps that don't run Cesium full-screen because they also have 2D and other views).  Maybe the TOS for some data providers would also allow putting the credits on a separate page or a slide-out like the Cesium mouse/touch help widget.  It would be up to the app to do the right thing.

@kring do you happen to have any time or interest to look into this?

**Comment by kring** [comment]
FWIW Bing Maps does allow attribution on a separate page on mobile devices, at least:
http://www.microsoft.com/maps/mob-brand-guid.aspx
(see the Data Provider Attribution section)

If STK World Terrain allowed the same, that would solve a lot of the problem.
