### ISSUE TITLE
Fabric wiki page has invalid interlinks in Contents

### ISSUE THREAD

**Issue by rutsky** [AnalyticalGraphicsInc/cesium#3015]
E.g. FabricSchema section in Contents links to 
```
https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric#FabricSchema
```
but works 
```
https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric#fabric-schema
```
(notice lowercase and minus as word separator).

Looks like this issue is due to GitHub links validator, that normalizes links.

**Comment by hpinkos** [comment]
fixed
