### ISSUE TITLE
PolygonGeometry documentation links on the Sandcastle demo with Entities, not Primitives

### ISSUE THREAD

**Issue by rutsky** [AnalyticalGraphicsInc/cesium#3028]
Here:
https://github.com/AnalyticalGraphicsInc/cesium/blob/1.13/Source/Core/PolygonGeometry.js#L380

Looks like demo with Primitives API was rewritten using Entites API.

Is there is no Primitives API demo anymore?

**Comment by pjcozzi** [comment]
The Primitive API examples are here: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Apps/Sandcastle/gallery/development

Also see: #3020

**Comment by rutsky** [comment]
Thanks, @pjcozzi!
I opened PR with fix for this issue according to solution proposed in #3020.

**Comment by pjcozzi** [comment]
Closing as duplicate with #3020.
