### ISSUE TITLE
Polyline quality regression in 1.10

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3036]
Compare the 1.9 CZML example with the 1.13 one.

[1.9 CZML Example](http://cesiumjs.org/releases/1.9/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases)
[1.13 CZML Example](http://cesiumjs.org/releases/1.13/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases)

In 1.9, the lines are nice and smooth
![image](https://cloud.githubusercontent.com/assets/1495196/9906163/e7637b7c-5c56-11e5-844a-70e6dee8a377.png)

In 1.10-1.13 they are jagged and ugly
![image](https://cloud.githubusercontent.com/assets/1495196/9906172/f47cc5e8-5c56-11e5-876c-e47046bc8aa5.png)

**Comment by denverpierce** [comment]
This isn't really noticeable on Chrome 46 Beta, win7, and a nvidia quadro card.

1.9
![image](https://cloud.githubusercontent.com/assets/5432027/9922393/8bfd2146-5cad-11e5-81ed-931c1e110b9a.png)

1.13
![image](https://cloud.githubusercontent.com/assets/5432027/9922481/b235dd52-5cae-11e5-8ec1-8f925b04b873.png)

I do notice it on a another desktop though (Win10, Chrome 45, Radeon R9 270x).

**Comment by mramato** [comment]
I see it in both 45 and 47 on my Win 10 laptop (5200M Quadro) and my Win 7 desktop (650ti) both with the latest drivers.  I could depend on the capabilities of the card and which render passes we are taking.

**Comment by hpinkos** [comment]
@mramato is this still a problem?

**Comment by pjcozzi** [comment]
With my Windows NVIDIA GeForce, there are slightly more artifacts in 1.29 than 1.9 likely due to FXAA.

Compare:

http://cesiumjs.org/releases/1.9/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases

http://cesiumjs.org/releases/1.29/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases

I am OK with closing this.

**Comment by mramato** [comment]
Disabling fxaa makes things look even work in my opinion, not better.  But given how long this has been open, I'm okay with closing this.  However when we have time we really need to investigate overall image quality improvements for Cesium.

**Comment by liyunchuan1216** [comment]
this is problem is ok ?
