### ISSUE TITLE
Triangulation error for polygons with holes

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3044]
I couldn't find an open issue for this, but it was reported in the forum by a user using GeoJSON files:

![image](https://cloud.githubusercontent.com/assets/3451886/10030148/2fabb95c-6144-11e5-812d-637ecc4acee1.png)

https://groups.google.com/forum/?hl=en#!topic/cesium-dev/HfwbCQPi7CI

He says the errors are very common with these types of polygons.

**Comment by hpinkos** [comment]
Also reported here:  https://groups.google.com/forum/?hl=en#!topic/cesium-dev/b7nCByVXyKs

[example.geojson](https://github.com/AnalyticalGraphicsInc/cesium/files/56963/example.geojson.txt)

**Comment by mramato** [comment]
Not identical, but related to #2788.

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/SKn6LUR906g

**Comment by hpinkos** [comment]
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/wNDxpEPK6QQ

[sample-geojson.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/163355/sample-geojson.txt)

**Comment by pjcozzi** [comment]
Improved in #3998.

**Comment by bagnell** [comment]
I'm going to close this and open a new issue. The GeoJson files were fixed, but one still has an issue written up in #4000. The KML triangulation still fails because some of the holes share vertices or edges with the outer ring.
