### ISSUE TITLE
Add a 'ConstantColorMaterialProperty' that exposes `ConstantProperty`'s `setValue` setter

### ISSUE THREAD

**Issue by nmschulte** [AnalyticalGraphicsInc/cesium#3060]
I was going to title this issue _Support `setValue` method for `ColorMaterialProperty`_, but then I realized that `ColorMaterialProperty` isn't meant to be constant, though its most common (exemplified) use is.  (On that note, the `ColorMaterialProperty` currently depends on the `ConstantProperty` module but never uses it.)

The `ColorMaterialProperty` doesn't specialize(optimize) for "constant colors," nor do I think it should.  Instead, this could be done by a `ConstantMaterialColorProperty` (that is perhaps encapsulated and then "supported" by the `ColorMaterialProperty`, but that may be the wrong approach), which may improve performance for this common use case.  It's possible the engine is already able to make this optimization internally, but that approach increases the complexity of the `Property` system (and the objects with `Property` members, as noted in the next comment) and the understanding the developer needs in order to use it.

**Comment by nmschulte** [comment]
To this end, it seems a bit strange that `ConstantProperty` has "set semantics," but `Property` does not.  Shouldn't this be defined by `Property` and overridden to e.g. throw a `DeveloperException` in `ConstantProperty`?

Perhaps my question indicates a misunderstanding/confusion on my part: `ConstantProperty` is for a property that is constant with respect to the simulation time; does this mean that if I expect the property can change (via e.g. user input) for the same simulation time, it shouldn't be a `ConstantProperty`?  It looks like there's a level of "smarts" with regard to Entity "members" (`show`, `material`, `heirarchy`; the "properties") that detects when the whole "property definition" (the `Property` object) has changed.  This isn't clearly conveyed in the tutorials, and because those "smarts" deal with the same concern as the whole `Property` heirarchy, it's not clear which way of updating them is proper.

**Comment by nmschulte** [comment]
@pjcozzi if someone could answer the architectural Qs above, I can work toward closing this issue.

**Comment by pjcozzi** [comment]
@nmschulte I am not the right person to answer here. 😄 

Probably @mramato would know.

**Comment by mramato** [comment]
@nmschulte I'm sorry but I'm failing to understand what you're asking here. What are you trying to do that you can't do with the current API or causes the current implementation to otherwise have issues? Maybe provide pseudocode showing the problem?

> The `ColorMaterialProperty` doesn't specialize(optimize) for "constant colors,"

It does. The value of its `isConstant` property changes depending on if the underlying value is constant.

You can also change a `ColorMaterialProperty` to a new color at any time by just setting the `color` property

```js
var foo = ColorMaterialProperty(Color.BLUE); //constant blue (creates a ConstantProperty automatically)
foo.color = new ConstantProperty(Color.YELLOW) // change to constant yellow
foo.color = Color.GREEN; // change to constant green. (creates a ConstantProperty automatically)
```

If you know for certain that color is a Constant already, you can also call set value.

```js
foo.color.setValue(Color.YELLOW); // change to constant yellow
```

**Comment by nmschulte** [comment]
It looks like `ColorMaterialProperty` and the property system has changed a lot since I created this issue.  I'm sure we can close this, but here's my comments:

Is the "definition (of a property)" different than the "property" then?  Just kind of confusing that the definition can be changed (by `setValue`, counterpart of `getValue`) even though the `ConstantProperty` is considered "constant (value").
https://github.com/AnalyticalGraphicsInc/cesium/blob/1.61/Source/DataSources/ConstantProperty.js#L29

On that note I was thinking the code would be clearer if `Property` had a `setValue` (or whatever the proper "abstract" value-setting is), and `ConstantProperty` (or whatever it actually doesn't allow `setValue`).

The used dependency/require I had noted is already cleaned up.
