### ISSUE TITLE
iOS crashes in portrait without a viewport tag.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3066]
As reported in [this forum thread](https://groups.google.com/d/msg/cesium-dev/hr0OOe5lFxs/Wmy6-fmhBwAJ), not having a viewport meta tag seems to cause Cesium to crash on iOS devices.  At first glance it appears that we are attempting to render with a canvas width of 0 (which has bit us in the past) but I need to look further into it to figure out why.

**Comment by hpinkos** [comment]
@lilleyse can you test this on the ipad?

**Comment by pjcozzi** [comment]
@lilleyse can you test this?

**Comment by lilleyse** [comment]
It seems to be fine now, at least for a modified Hello World.
