### ISSUE TITLE
Geometry shows up all white in Firefox

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3068]
Load the attached kmz file into Cesium.  In Chrome everything works as expected, but in Firefox, the geometry is completely white.  I verified that it is not an ANGLE issue and it happens in older versions of Cesium as well so my assumption is that we are encountering a Firefox bug, but either way we should figure out the problem and workaround it (and report a bug to Mozilla if necessary).

[Vorarlberg_Building_Tile_0_11_geometry.kmz.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/12567/Vorarlberg_Building_Tile_0_11_geometry.kmz.txt)

**Comment by mramato** [comment]
Forgot to mention this was found and reported on the forum: [thread](https://groups.google.com/d/msg/cesium-dev/bt68_WXcQIs/IvOKSuddCgAJ)

**Comment by pjcozzi** [comment]
This works on Mac in both master and the `firefox-oit` branch from #4762.  Can someone please test on Windows to see if we can close this?

**Comment by lilleyse** [comment]
This is what I see in Firefox on Windows - looks fine.

![capture](https://cloud.githubusercontent.com/assets/915398/21300475/4acbb1e0-c572-11e6-9349-3c32e938662a.PNG)

**Comment by pjcozzi** [comment]
OK, appears to be fixed.
