### ISSUE TITLE
KML geometry incorrect compared to Google Earth

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3082]
As reported [on the forum](https://groups.google.com/d/msg/cesium-dev/bt68_WXcQIs/KhFCDBCiCgAJ), load the attached KMZ file into Cesium and you'll notice small gaps between the walls and roof.  These gaps do not exist if you load the same file into Google Earth.

[test_geometry.kmz.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/13233/test_geometry.kmz.txt)

**Comment by billyweisberg** [comment]
Matt, I have 153K Kml file that loads fine in Google Earth. In Cesium, one hemisphere loads fine, and the other hemisphere contains a few lines which should be an entire grid, but it appears the processing stops. Strangely, i can't upload the file here, it errors. I can get you the file somehow if you are interested in using it to debug. I wish I had more js skills, I would debug it for you. Thanks
![ge](https://cloud.githubusercontent.com/assets/9979211/10487647/2edba34c-7252-11e5-90c9-3a30f7aaac55.JPG)

![cesium](https://cloud.githubusercontent.com/assets/9979211/10487655/3a5f3b02-7252-11e5-9c99-7ba93e809cce.JPG)

**Comment by mramato** [comment]
Thanks, that is very weird.  You can email me the file directly to
matt.amato@gmail.com

Thanks for the bug report.

**Comment by mramato** [comment]
The bug was fixed in 1.17 and the gaps are gone.  I believe an unrelated fix to the underlying Polygon geometry code fixed this as well.
