### ISSUE TITLE
Proposal to deprecate EllipsoidPrimitive, RectanglePrimitive, and Polygon

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3083]
I propose we deprecate (and remove in 3 releases) `EllipsoidPrimitive`, `RectanglePrimitive`, and `PolygonPrimitive`.  These objects have outlived their usefulness and cause confusion for many users (adding yet a 3rd option in the API).

To jog everyone's memory,

`EllipsoidPrimitive` is the raycasted ellipsoid which only works in 3D and as far as I know no one uses.  The `EllipsoidGeometry` and `EllipsoidGraphics` can handle everything it can do from an end-user's standpoing.

`RectanglePrimitive` and `PolygonPrimitive` both wrap their equivalent geometry.  Thy have been superseded by the Entity API.  And neither have been updated to keep base with underlying geometry features.

Any thoughts or objections?

**Comment by pjcozzi** [comment]
> EllipsoidPrimitive

Let's mark this private since the moon uses it.

> RectanglePrimitive and PolygonPrimitive

OK.
