### ISSUE TITLE
Sandcastle CZML Example Tweaks #2

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#3084]
Sorry I'm late to the party but I have a few comments.  There are a couple of comments about the CZML Content wiki page, while not explicitly a part of the original task, should be cleaned up as well.

* **General**
- [ ] Use a JS pretty printer to produce code that matches the indentation style of the Sandcastle editor.  The examples are currently using 2 space indentation which gets hard to read when a user edits the CZML data and the editor uses 4 spaces for indentation levels.

* **CZML Billboard and Label**
- [ ] Should position the items to be on our building rather than the field across the street.

* **CZML Circles and Ellipses**
- [ ] Use contrasting colors when demonstrating outlines.

* **CZML Model**
- [ ] Would be nice to show how to orient models in typical situations (e.g. static/dynamic, ground/air/ space).

* **CZML Path**
- [ ] Add clock to the document to slow down the animation.
- [ ] Do we need to acknowledge the source of the GPS track data?

* **CZML Point**
- [ ] Need more contrast in colors.

* **CZML Point - Time Dynamic**
- [ ] Need more contrast in colors.
- [ ] Would be a nice place to show time dynamic colors and pixelSize.

* **CZML Polygon - Intervals, Availability**
- [ ] Add clock to the document to speed up the animation.

* **CZML Rectangle**
- [ ] Rectangle is not defined on the CZML Content page of the wiki.
- [ ] Use of height and extrudedHeight should be described on the CZML Content page, especially identifying the reference surface.

**Comment by pjcozzi** [comment]
@tiffanylu @adamdavidcole there is some low-hanging fruit here that would add values to the CZML examples (like the contrast in colors).  Let's evaluate these once we finish the imagery provider update.
