### ISSUE TITLE
Remove support for CESIUM_binary_glTF

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3102]
It will be replaced with KHR_binary_glTF.

CESIUM_binary_glTF was deprecated in #3039.

**Comment by pjcozzi** [comment]
Also remove "glTF 0.8 with CESIUM_binary_glTF" from the online model converter.

**Comment by TomPed** [comment]
Are these changes to be in `Model.js`?

**Comment by pjcozzi** [comment]
Yes

**Comment by pjcozzi** [comment]
Fixed in #3426.

**Comment by mramato** [comment]
> Also remove "glTF 0.8 with CESIUM_binary_glTF" from the online model converter.

Are you going to open a separate issue for this part?

**Comment by pjcozzi** [comment]
Ah, good catch.  No, I'll just re-open this.

@tfili can you do this for the 1.18 release on February 1?

> remove "glTF 0.8 with CESIUM_binary_glTF" from the online model converter.

**Comment by pjcozzi** [comment]
The binary checkbox will be grayed out when glTF 1.0 is not selected since the converter does not output CESIUM_binary_glTF anyway.

**Comment by pjcozzi** [comment]
Updated.
