### ISSUE TITLE
Move general glTF helpers to their own libraries

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3103]
- `gltfDefaults`
- `ModelCommonMaterials`

And publish them on npm so we can use them in gltf-statistics, OBJ2GLTF, etc.

**Comment by pjcozzi** [comment]
Progress in gltf-pipeline here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/272

**Comment by pjcozzi** [comment]
@lilleyse OK to close this?

**Comment by lilleyse** [comment]
Yes, fine to close.
