### ISSUE TITLE
Coerced EXT_texture_filter_anisotropic object causes WebGL error in Texture.js

### ISSUE THREAD

**Issue by gbeatty** [AnalyticalGraphicsInc/cesium#3105]
Changes in SHA: 7c75a1227c23775224a33f234ce65f37728e1ae7 added a !! coersion to the EXT_texture_filter_anisotropic object in `Context`. This causes `gl.texParameteri(target, this._textureFilterAnisotropic.TEXTURE_MAX_ANISOTROPY_EXT, sampler.maximumAnisotropy);` in  `Texture/defineProperties` to return undefined. Sending undefined into `gl.texParameteri()` generates a WebGL: INVALID_ENUM: texParameter: invalid parameter name error.

**Comment by pjcozzi** [comment]
Good eye, thanks @gbeatty.

@bagnell @lilleyse can one of you look at this?

**Comment by mramato** [comment]
I assume this bug in the Picking example is also because of this?  `master` seems to be in pretty bad shape right now.

![image](https://cloud.githubusercontent.com/assets/1495196/10608682/181e8b18-770e-11e5-8f21-7ac71647d271.png)

**Comment by pjcozzi** [comment]
Good eye, thanks again @gbeatty.
