### ISSUE TITLE
Should we still be shipping the built Cesium Viewer?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3127]
We currently ship with a built copy of the `Cesium Viewer` and even mention it as "ready for deployment" on our website's download page.  This is misleading since the Cesium Viewer contains the default Bing key and can't be deployed as-is without violating usage policy.

I'm not even sure how many people actually ever use the built version either (or why you would use it other than for development).  Should we just stop shipping the built version?  It would probably shrink our overall zip file size a bit as well.  If we want to continue to ship the built version, we'll need a way to specify the Bing key via a configuration file that Cesium Viewer looks for.

**Comment by pjcozzi** [comment]
Removing it is OK with me.

**Comment by emackey** [comment]
Sounds good.
