### ISSUE TITLE
3D Tiles Sandcastle example is broken

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3136]
@lilleyse can you please look at this ASAP so we can merge #3131?

Functions such as `hasProperty` and `getPropertyNames` were moved in https://github.com/AnalyticalGraphicsInc/cesium/commit/bab0ba9874efd03aed641d874337d05d19a6dbf7#diff-406122f3413b001f1cbf74187c314641.  However, the [Sandcastle example](https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Apps/Sandcastle/gallery/Cities.html) was not updated so per-building coloring (other than highlighting does not work).

**Comment by mramato** [comment]
Can this be closed?

**Comment by pjcozzi** [comment]
Yes, thanks!
