### ISSUE TITLE
Cesium3DTileSet should expose overall bounding volume

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3138]
I wanted to fly the camera to a `3DTileSet`, but there doesn't seem a way to get it's bounding volume.  I ended up with the below code (not sure if it's correct).  A properly like `tileset.boundingVolume` would probably be ideal.

```javascript
var bb = tileset._root._tileBoundingBox;
var bs = BoundingSphere.fromCornerPoints(bb.northeastCornerCartesian, bb.southwestCornerCartesian);
return camera.flyToBoundingSphere(bs);
```

**Comment by lilleyse** [comment]
@JoshuaStorm Would you like to take a look at this?
