### ISSUE TITLE
1.14 broke the sun on some mobile devices

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3141]
The Sun looks fine on my phone (Android 5.1, latest Chrome) using `1.13`, but `1.14` shows a white block.  I also tried master and get the same thing.  Since this is a regression, I marked it as a showstopper.

![image](https://cloud.githubusercontent.com/assets/1495196/10808501/a16c68bc-7dc2-11e5-8e7a-15be5fe40582.png)

**Comment by mramato** [comment]
Here's the webglreport from my phone, if that helps.  Note atmosphere doesn't work here either, but I doubt it's related.

![image](https://cloud.githubusercontent.com/assets/1495196/10808588/944d5f00-7dc3-11e5-9a28-515ea1fa1262.png)

**Comment by pjcozzi** [comment]
@lilleyse can you take a quick look at this before the 1.15 release to see if it is anything obvious with the renderer refactoring or `WebGLConstants`?

**Comment by lilleyse** [comment]
Yeah I can take a look at this. It works on my phone, so I may need a device to test with.

**Comment by mramato** [comment]
My phone is available whenever you want to have a look.

**Comment by pjcozzi** [comment]
I'm OK shipping 1.15 without this.  We'll leave it labeled next release.  @lilleyse please look at this soon.
