### ISSUE TITLE
Regression layer.json with absolute URLs due to #3133

### ISSUE THREAD

**Issue by gberaudo** [AnalyticalGraphicsInc/cesium#3142]
The layer.json of my Cesium terrain server defines an array of absolute URL
templates in order to allow parallel queries to subdomains.

Before #3133, the URLs were used as-is. Now, they are scrumbled:
- URL to layer.json: https://3d.geo.admin.ch/prefix/layer.json
- URL in layer.json: //terrain3.geo.admin.ch/prefix/{z}/{x}/{y}.terrain?v={version}
- generated terrain URL: https://3d.geo.admin.ch/prefix/prefix/0/1/0.terrain?v=1.0.0

The domain is incorrect and the prefix appears twice.

**Comment by kring** [comment]
This is a pretty serious regression, so I'm marking it showstopper.  I will try to work on it today.

**Comment by mramato** [comment]
Thanks @kring

**Comment by gberaudo** [comment]
Thank you @kring. Let me know if I can do something to help.
