### ISSUE TITLE
Warning in Sandcastle example

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3143]
@ggetz  can you update this before 1.15?  Or is there nothing we can do about this one?

> Scene/HeadingPitchRange is deprecated. Use Core/HeadingPitchRange instead.

http://localhost:8080/Apps/Sandcastle/index.html?src=Interpolation.html&label=All

**Comment by pjcozzi** [comment]
Same issue for this example: http://localhost:8080/Apps/Sandcastle/index.html?src=development/Ground%20Primitive.html&label=Development

**Comment by mramato** [comment]
This is a problem with the Combined Cesium file because the deprecated one overwrites the new one. It's a single fix for all cases at the build level. I'll look at putting a fix in the build process tonight.
