### ISSUE TITLE
COLLADA to bGLTF converter not working on files it worked on before.

### ISSUE THREAD

**Issue by ZacBrownBand** [AnalyticalGraphicsInc/cesium#3156]
I have been using the COLLADA to bGLTF converter for a few weeks as I have been adding to a ever growing library of 3d models. 

I attempted to convert some more models today and received an error. I tried an older file that worked a week ago and received the same error. 

Since its minified the error was not very helpful but here it is: 

TypeError: Cannot read property 'target' of undefined
TypeError: Cannot read property 'target' of undefined
    at Ct (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:443:3613)
    at $t (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:443:15526)
    at _r.update (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:443:26943)
    at a.update (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:457:15103)
    at Tt (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:459:13328)
    at xt (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:459:14030)
    at Mt.render (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:459:20433)
    at A.render (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:464:27833)
    at t (https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js:464:10458)

The model files are proprietary so I cannot link one here.

**Comment by pjcozzi** [comment]
Have you seen https://groups.google.com/forum/#!topic/cesium-dev/8kxfbamMcQ4

What COLLADA to Binary glTF converter are you using?  If you are using colladaToBglTFConverter, I asked them to upgrade: https://groups.google.com/forum/#!searchin/cesium-dev/%22gltf$201.0%22/cesium-dev/Hy7iQ0IK7Ik/FMShsdg3DAAJ

Cesium will have backwards compatibility with CESIUM_binary_glTF until 1.18; however, we need a sample model to test if there is an issue with the backwards compatibility code.  We did not find any issues with the binary glTF models created from the online converter.

**Comment by ZacBrownBand** [comment]
I had not seen that, thanks for directing me there, thats very helpful. 
I am using the colladaToBglTFConverter and using the check box to create the binary. 
So KHR_binary_glTF is replacing bgltf? What is the best resource to convert DAE files into KHR_binary_glTF?

**Comment by pjcozzi** [comment]
> So KHR_binary_glTF is replacing bgltf?

Yes

> What is the best resource to convert DAE files into KHR_binary_glTF?

We are updating the online model converter as part of the Cesium 1.15 release today: http://cesiumjs.org/convertmodel.html

I also suggest asking the colladaToBglTFConverter developers to update their tool.

I also expect more tools to emerge, they will be listed here: https://github.com/KhronosGroup/glTF/blob/master/README.md

**Comment by ZacBrownBand** [comment]
Okay, thank you so much! I will close this issue as it will likely get resolved by the release.
