### ISSUE TITLE
Support for custom CZML properties

### ISSUE THREAD

**Issue by RacingTadpole** [AnalyticalGraphicsInc/cesium#3162]
We want to add custom properties to CZML files. Currently we are doing this with a workaround, by wedging some json into the `description` field. @kring and I spent some time today discussing alternatives, and would like to get your feedback on the scheme we came up with. If you are ok with it, one of us can then submit a pull request.

A few explanatory points -
- We decided against adding custom properties at the root level of the CZML object, since they might conflict with current or future special properties (eg. `point`, `polygon`). So instead we propose they appear under a new `properties` key.
- We want to maintain the basic idea that CZML properties can be time-varying. So that the custom properties do not have to all vary in the same way, we will not define intervals on `properties` directly, but instead on its sub-properties.
- Those sub-properties would be interpreted using a new "generic" type handler (in [`unwrapInterval`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/CzmlDataSource.js#L342-L382)). Properties whose values are arrays or objects would need to put that value on the special key `value`. (Much like the current color handler requires a special key `rgba`.)
- For simplicity, nested properties cannot have different intervals to their parent properties, and so do not need the extra `value` key. This could be allowed in an extension later.

Here's an example:

```
"properties": {
    "short_name": "ABC",
    "changing_name": [
        {
            "interval": "2007-03-02T13:00:00Z/2008-05-11T15:30:00Z"
            "value": "XYZ"
        },
        ...
    ],
    "foobar": {
        "value": {
            "foo": 4,
            "bar": 10
        }
    },
    "an_array": {
        "value": [...]
    },
    "children": {
        "value": {
            "name": "alice",
            "children": [
                {
                    "name": "bob",
                    "children": []
                }
            ]
        }
    }
}
```

What do you think?

**Comment by RacingTadpole** [comment]
As an extension, you could add typed properties, eg.:

    propertyTypes: {
        "bgColor": "Color",
        "center": "Cartesian3"
    },
    properties: {
        "bgColor": {
            "value": {
                "rgba": [...]
            }
        },
        ...
    }

**Comment by kring** [comment]
We'd likely want to put the `propertyTypes` bit in the `document` packet so that all entities from a single CZML have the same "schema" for their custom properties.  Speaking of schema, it could describe more than just the type of the property, if we want.  This is all future work, though.  The initial feature would only support generic properties.

**Comment by RacingTadpole** [comment]
After discussing this further with others, we can extend the above to make it easier to define constant properties (or more generally, properties which all apply over the same interval): if `properties` is an array, then treat it as an array of intervals, and do not allow any sublevels to have their own intervals. Eg.:

    "properties": [
        "interval": "2007-03-02T13:00:00Z/2008-05-11T15:30:00Z"  // optional, default is all time
        "value": {
            "short_name": "ABC",
            "foobar": {
                "foo": 4,
                "bar": 10
            },
            "an_array": [...]
            "children": {
                "name": "alice",
                "children": [
                    {
                        "name": "bob",
                        "children": []
                    }
                ]
            }
        }
    ]

Although it feels a little clumsy to interpret different levels of the `properties` differently depending on whether it's an array or an object, there is a unifying idea here: you can define the interval at either the `properties` level or at the per-property level, and then once you have, you do not need to define intervals at the lower levels.

An alternative would be to allow all levels of `properties` to specify intervals. But this is cumbersome, eg. `children` above would have to be written:

        "children": {
            "value": {
                "name": "alice",
                "children": [
                    {
                        "value": [
                            {
                                "name": "bob",
                                "children": [{"value": [...]}]
                            }
                        ]
                    }
                ]
            }
        }

**Comment by mramato** [comment]
Hey guys, I somehow missed this issue the first time around.  I haven't had a chance to fully review your ideas yet but I'm all on board with making them happen @shunter has actually taken an active role in trying to bring czml-writer back to life and clean things up, so we should all get on the same page and make sure everyone converges on the same spec.

**Comment by RacingTadpole** [comment]
FYI, I have implemented a first pass at this, including specs that mirror the above, at https://github.com/TerriaJS/cesium/compare/terriajs...TerriaJS:terriajs_czml_props

(that comparison shows up some minor extra changes between the terriajs branch and cesium master)

**Comment by RacingTadpole** [comment]
FYI, after further discussion with @kring, we're only going to implement the first spec above. 

The second spec introduces confusion, eg. elsewhere when CZML is presented with `{"value": ...}`, it is smart enough to know that's the same as `[{"value": ...}]`. But these two would be interpreted differently if we allowed the second spec.

**Comment by hpinkos** [comment]
Added in #5105
