### ISSUE TITLE
Incorrect label align

### ISSUE THREAD

**Issue by fredj** [AnalyticalGraphicsInc/cesium#3166]
A label created with the following code:
```javascript
var labels = viewer.scene.primitives.add(new Cesium.LabelCollection({
  scene: viewer.scene
}));
labels.add({
  position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
  text : 'Philadelphia',
  verticalOrigin: Cesium.VerticalOrigin.TOP
});
```
Has an incorrect alignment:
![cesium_label_align](https://cloud.githubusercontent.com/assets/100959/10943481/d19045b6-8314-11e5-9d72-7139c05043df.png)
 
This issue only occurs if  `verticalOrigin` is `Cesium.VerticalOrigin.TOP` or `Cesium.VerticalOrigin.CENTER` and and the scene is passed to the `Cesium.LabelCollection`

**Comment by pjcozzi** [comment]
Good catch!  Thanks for the report.

@bagnell perhaps this broke with billboards/labels on terrain?

This code works:
```javascript
var labels = viewer.scene.primitives.add(new Cesium.LabelCollection({
//  scene: viewer.scene
}));
labels.add({
  position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
  text : 'Philadelphia',
  verticalOrigin: Cesium.VerticalOrigin.TOP
});
```

**Comment by hpinkos** [comment]
Appears to be fixed
