### ISSUE TITLE
Tile selection issues

### ISSUE THREAD

**Issue by slozier** [AnalyticalGraphicsInc/cesium#3170]
There appears to be issues with tile selection. In my sample code below, the lat/lon I selected is in the 032 tile section on Bing maps. The height is below ground for the WGS84 model, but above ground when using a terrain provider.

If I run my sample in the sandcastle, the camera is below ground and a number of "incorrect" tiles are loaded (I can see them being downloaded using dev tools in the browser). For example, the following tile is loaded:
http://ecn.t1.tiles.virtualearth.net/tiles/a31023233033312000303.jpeg?g=4462

There might be two issues here:
* I don't think tiles should be loaded when we are looking at their back face
* Why are the tiles on the opposite side of the globe loading to such resolution? (e.g. 31023233033312000303 instead of just 310)?

```
var widget = new Cesium.CesiumWidget('cesiumContainer');
var target = Cesium.Cartesian3.fromDegrees(-73.870152, 40.778059, -5);
var offset = new Cesium.HeadingPitchRange(0, -1, 1);
widget.camera.lookAt(target, offset);
```

**Comment by pjcozzi** [comment]
Thanks for the report, @slozier.  It's possible that Cesium's screen-space error / bounding volume pixel size computation has an issue with negative heights.  We'll update here when we know.
