### ISSUE TITLE
Polygon rotation 

### ISSUE THREAD

**Issue by lucasvw** [AnalyticalGraphicsInc/cesium#3173]
In continuation of: https://github.com/AnalyticalGraphicsInc/cesium/issues/3172 

I implemented the same principle with PolgyonGeometry. In this case Iam no longer using the rotation property but I compute the coordinates of the corners myself under each rotation.

See for the result: http://youtu.be/SEywSgEa1P8

This following is noticed:

(1) The geometry is now correctly rotated, the geometry is no longer warped, skewed at nonzero rotation as was the case for RectangleRotation.
(2) At some rotations the material is displayed correctly, at others not. Sometimes its black, sometimes the half of the geometry is shown correctly, the other half not (over the diagonal).
When switching to 2D mode: 
(3) At 0 Degrees the geometry is not a square, aspectRatio != 1. 
(4) With nonzero rotation: the geometry gets skewed and warped.

So appaerently: if I use RectangleGeometry then 3D rotation gets warped and skewed. But 2D view rotation works, although the coordinates of the rectangle does not get translated well into 2D mode, leading to a non-square geometry.
if I use PolygonGeometry, then 3D rotation works but 2D rotation gets warped and skewed..

**Comment by hpinkos** [comment]
This is working as designed.   The edges of polygons follow [geodesic](https://en.wikipedia.org/wiki/Geodesic) arcs and Rectangles follow [rhumb lines](https://en.wikipedia.org/wiki/Rhumb_line)

We plan on adding a rhumb line option for polygons.  See #4000
