### ISSUE TITLE
Fog dark

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3178]
I experienced an issue with the fog when testing the 3d Models Sandcastle. This happens when I first orient the camera into the ground (horizon view), and then start zooming out.

![fog-dark](https://cloud.githubusercontent.com/assets/915398/11051751/b5d866aa-871f-11e5-926d-5c4f486d7c76.gif)

**Comment by pjcozzi** [comment]
@bagnell can you look at this before the 1.16 release?  I suspect this is because of the time of day and the view direction, the blend color is dusk/dawn, but it's strange that it changes when zoomed out.

**Comment by pjcozzi** [comment]
@bagnell just a reminder that 1.16 is coming up next week.  No one has reported running into this yet so we can push if it is really hard to fix.

**Comment by bagnell** [comment]
Its either a problem with the atmosphere code or the camera collision with the terrain but I haven't tracked it down. This happens in master too. If you go to the same Sandcastle example in master, keep rotating down and the sky will become super bright.

**Comment by lilleyse** [comment]
In `Camera` changing

```Matrix4.inverse(camera._viewMatrix, camera._invViewMatrix);```

to `inverseTransformation` fixes both fog and shadows. It looks like the camera vectors are a bit wrong, I'll look into this more but at least here is the easy fix.

**Comment by lilleyse** [comment]
Whoops other way around, `inverseTransformation` to `inverse` fixes it.

**Comment by pjcozzi** [comment]
There was a proposed workaround in #3750.
