### ISSUE TITLE
Files missing from built Cesium

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#3194]
If I delete my "Build" folder and run `npm run release`, the `Build/Cesium` and `Build/CesiumUnminified` folders are missing some items.  Try running the "Hello World" app from the main page after building.

* `Assets\IAU2006_XYS` does not have a complete set of JSON files, compared to the source tree
* `Assets\Textures` is missing three subfolders, `maki`, `NaturalEarthII`, and `SkyBox`
* `ThirdParty\Workers` exists but has no files at all, not sure if it should exist or not.  It wasn't there in the ant builds of Cesium.
* `Widgets\Images` is missing, breaking many buttons in Hello World
* `Workers` does not have a complete set of workers.

**Comment by mramato** [comment]
@emackey I can't reproduce this (started from a `git clean -dxf` just to be sure).  What version of NPM and OS are you using?  Can you try blowing away your `node_modules` directory and rerunning `npm install`.

**Comment by emackey** [comment]
Looks like I had an old version of Node.js and npm from 2013.  Cleaning and re-downloading node_modules didn't fix the problem until after I upgraded to the Node.js 4.2.2 release.
