### ISSUE TITLE
Uppercase STYLES parameter overridden by WebMapServiceImageryProvider

### ISSUE THREAD

**Issue by RacingTadpole** [AnalyticalGraphicsInc/cesium#3195]
`WebMapServiceImageryProvider` combines user-provided parameters with its own defaults before then converting them all to lowercase.

As a result, if the user provides parameters that also appear in the defaults, but with different capitalization (in particular, STYLES vs styles), the default winds up overriding the user-provided value.

Raised by @rsignell-usgs here: https://github.com/TerriaJS/terriajs/issues/1055

**Comment by aaditya-thakkar** [comment]
Has this issue been resolved?

**Comment by RacingTadpole** [comment]
Thanks for spurring me on to looking at this. It turns out this is a terria problem after all - sorry! Solved via https://github.com/TerriaJS/terriajs/pull/1228 .
