### ISSUE TITLE
npm run build only creates minifyShaders.state

### ISSUE THREAD

**Issue by fegyi001** [AnalyticalGraphicsInc/cesium#3204]
I tried to build the project with node.js, but when I run "npm run build" only a single file is generated in the Build folder (minifyShaders.state), and its content is simply "false".

What did I do wrong?

**Comment by mramato** [comment]
Hi @fegyi001, I just answered your question [on the forum](https://groups.google.com/d/msg/cesium-dev/VM-UOjpTFRI/M1nqX5TNFAAJ).  In general, the forum gets you a faster answer for questions like this, and that's what we recommend everyone use.  Thanks.
