### ISSUE TITLE
IE 11  GroundPrimitive doesn't work

### ISSUE THREAD

**Issue by oterral** [AnalyticalGraphicsInc/cesium#3214]
Just open the sandcastle example : http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=development/Ground%20Primitive.html&label=Development in IE 11

Polygons are not displayed.

**Comment by mramato** [comment]
This is mentioned in [CHANGES](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#113---2015-09-01), but apparently nowhere else:

> Because of the cutting edge nature of this feature in WebGL, it requires the EXT_frag_depth extension, which is currently only supported in Chrome, Firefox, and Edge. Apple support is expected in iOS 9 and MacOS Safari 9. Android support varies by hardware and IE11 will most likely never support it. You can use webglreport.com to verify support for your hardware. Finally, this feature is currently only supported in Primitives and not yet available via the Entity API.

I will leave this issue open until we properly add the above caveats  to the `GroundPrimitive` documentation.  Sorry I don't have better news for you.

**Comment by oterral** [comment]
Thx to point this out !!!  I've read it before but that I had totally forgotten.
