### ISSUE TITLE
Request to publish releases after 1.10.0.

### ISSUE THREAD

**Issue by d-amit** [AnalyticalGraphicsInc/cesium#3217]
Currently the highest release via npm is 1.10.0.  Can you please publish the rest of the releases?

**Comment by pjcozzi** [comment]
@adius any chance you can update this?

**Comment by d-amit** [comment]
Is there anyway some else can get to publishing these?  I'm on a deadline so if you could publish those I would be very grateful.

**Comment by mramato** [comment]
Sorry @d-amit, the current NPM Cesium libraries are not part of our official release process nor are they officially maintained.  We can't guarantee their correctness or how often they get updated.  Eventually, we will add publishing to NPM as part of our official release process, but we're not there yet.

Personally, I would recommend downloading our official release and using that.

**Comment by mramato** [comment]
@d-amit.  Good news, I just opened #3243 with the idea that we will have an official NPM module sometime very soon. Keep an eye on it.

**Comment by mramato** [comment]
@d-amit Cesium is now officially available on npm as the `cesium` module.  Read all about it here: http://cesiumjs.org/2015/12/14/Cesium-npm/

@adius, I sent you and Joel an email regarding the cesiumjs package you've previously published.  It would be great if you could point users to the officially maintained version now. Thanks.

**Comment by adius** [comment]
Just deprecated cesiumjs with a message redirecting to the new module!

**Comment by mramato** [comment]
Awsome, thanks @adius!
