### ISSUE TITLE
STK World Terrain Server not working

### ISSUE THREAD

**Issue by andyneff** [AnalyticalGraphicsInc/cesium#3221]
As of 12PM GMT time on Nov 18, 2015 the STK World Terrain quick working in Cesium.

![image](https://cloud.githubusercontent.com/assets/7596961/11250266/a96d1d94-8df9-11e5-9f7f-a5f77de7974c.png)

The SSL cert for https://assets.agi.com/ expired. Most modern web browsers will not accept connections to an expired cert (without an exception being added). So now when you try and load the STK World Terrain, you just get a blank globe.

**Comment by andyneff** [comment]
Update: agi support tells me "It should be back up now". Perhaps the bad cert is still cached.

Will wait this out a little.

**Comment by mramato** [comment]
The site is up, but as you pointed out, the SSL cert appears to have
expired.  I contacted the person in charge to get it fixed ASAP.  In the
mean time, using the HTTP version of the terrain server still works fine
(but obviously is not a valid solution for https connections).  Thanks for
the heads up.

**Comment by mramato** [comment]
This is back up, thanks again for the report.
