### ISSUE TITLE
Remove OpenStreetMapImageryProvider

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3222]
Deprecated in #3146.

**Comment by slozier** [comment]
@pjcozzi @lilleyse Any reason why this was merged into the 3d-tiles branch instead of master?

**Comment by mramato** [comment]
This was a mistake, @lilleyse can you cherry-pick the required commits and open a PR into master to fix this.  Thanks.

**Comment by mramato** [comment]
Thanks for catching this @slozier

**Comment by pjcozzi** [comment]
@TomPed want to try this one?  Check out [git cherry-pick](https://git-scm.com/docs/git-cherry-pick).
