### ISSUE TITLE
Deselect Entity

### ISSUE THREAD

**Issue by digitaldavenyc** [AnalyticalGraphicsInc/cesium#3229]
Is there a way to deselect an entity after a user has clicked on it? I have not seen any documentation on this.

**Comment by hpinkos** [comment]
@digitaldavenyc please use our [forum](https://groups.google.com/forum/#!forum/cesium-dev) to ask questions.

To deselect, set `viewer.selectedEntity = undefined`. See the [Viewer.selectedEntity](http://cesiumjs.org/Cesium/Build/Documentation/Viewer.html#selectedEntity) reference documentation.
