### ISSUE TITLE
LICENSE.md cleanup

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3234]
License.md has a list of all third-party software that ships with Cesium, as well as their license, which usually contains a copyright year.  We have updated to newer versions of some of these libraries but usually forget to go back and verify the license text hasn't changed (for example, having the copyright year updated).  We should do a pass on the entire file and verify

1. All included entries are still shipped with Cesium.
2. That Cesium isn't shipping with things not listed in License.md (doubtful).
3. Update the license and copyright year to reflect the version Cesium is using.

**Comment by eputnam** [comment]
I can grab this if it still needs doing.

**Comment by pjcozzi** [comment]
@eputnam go for it!  This was just submitted.  See [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md) for more details on contributing to Cesium in general.  Thanks!

**Comment by eputnam** [comment]
ok great.
