### ISSUE TITLE
Remove TileMapServiceImageryProvider

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3238]
Deprecated in ~~#3150~~ #3460.

**Comment by pjcozzi** [comment]
Relabeling for 1.20, but the exact version will depend on when #3150 is merged.

**Comment by pjcozzi** [comment]
This will be 1.20.

**Comment by pjcozzi** [comment]
Removed in #3460, which replaced #3150.

**Comment by hpinkos** [comment]
Remember to delete `TileMapServiceImageryProviderSpec` as well

**Comment by sanuj** [comment]
@hpinkos Shall I delete `TileMapServiceImageryProviderSpec` and `TileMapServiceImageryProvider` and send a PR?

**Comment by hpinkos** [comment]
@sanuj sure! We'll just leave the PR open until after the March release.

**Comment by sanuj** [comment]
@hpinkos I'll remove it after the March release then other I would have to rebase the branch again.
