### ISSUE TITLE
Most glTF semantics are not covered by tests

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3245]
This is surprising since they should be covered by [Models/Box-Textured-Custom](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Specs/Data/Models/Box-Textured-Custom).

@lilleyse can you look at this?  We would like to donate this model to the glTF repo for testing.

![image](https://cloud.githubusercontent.com/assets/782098/11402231/c8429b2a-9364-11e5-90a1-dab605359f8c.png)

**Comment by lilleyse** [comment]
Yes I can look into this.

**Comment by lilleyse** [comment]
It looks like we handle all the cases for when the semantic is alone, but not the cases where you have a semantic and a referenced node via `getUniformFunctionFromSource`.

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2463-L2472

I can edit the sample model to handle these as well.

**Comment by pjcozzi** [comment]
Good eye, thanks @lilleyse!

**Comment by pjcozzi** [comment]
Fixed in #3257.
