### ISSUE TITLE
CZML Updates

### ISSUE THREAD

**Issue by ZYingithub** [AnalyticalGraphicsInc/cesium#3250]
Dear Ms,
I'm very grateful to your great work filing up CZML materials and I've learnt it  carefully and thankfully.
I 'm a beginer learning Cesium, and I'm very interested in CZML.
I've been learning  CZML by browsing  pages in Github, and I've found it's not so complete in content. 
Many entitiy types are not included,such as "wall","box",valid in CZML but not included in the official 
documentation. What's more, it's a little difficult for me to use property "orientation", I'm quite unfamiliar with “Quaternions”.So I wonder wether  "orientation"could be replaced by "heading,pitch,roll" things?
Now I want to make a request: could you send me some materials about the latest updates of CZML?
I'm looking forward to your reply  and thanks a million.

Best Regards!

**Comment by shunter** [comment]
I have updated the CZML documentation to reflect the current implementation.  

https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Packet

**Comment by hpinkos** [comment]
@shunter it looks like wall and rectangle are missing, would you mind adding those when you get a chance?

**Comment by shunter** [comment]
Wall and Rectangle are now in.  AnalyticalGraphicsInc/czml-writer#113
