### ISSUE TITLE
Camera's flying and rotation in 2D causes crash when switching to 3D in Chrome

### ISSUE THREAD

**Issue by ezze** [AnalyticalGraphicsInc/cesium#3255]
Hi, guys!

During development of an application based on Cesium I detected an unexpected behavior linked with camera interactions in 2D scene mode. I was able to reproduce the problem in Google Chrome with [Camera example in Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Camera.html&label=Showcases):

1. Switch to 2D scene mode.
2. Fly to San Diego.
3. Hold mouse scroll wheel and rotate the camera.
4. Switch back to 3D scene mode => application hangs (seems like an infinite loop).

Sometimes I can reproduce this one even excluding step 3. If I don't use `flyTo` everything works fine.

My setup:
- Ubuntu 14.04 LTS (also tested by co-worker on different machine with Linux Mint);
- GeForce GT630M with proprietary NVIDIA driver version 352.63;
- Chrome flag `ignore-gpu-blacklist` is enabled otherwise WebGL doesn't work;
- Google Chrome Version 44.0.2403.157 (64-bit) (can't update to recent version yet due to [this](https://code.google.com/p/chromium/issues/detail?id=509336) and [this](https://code.google.com/p/chromium/issues/detail?id=530788)).

Everything works in Mozilla Firefox.

Also, when I switch to 2D scene mode, I get the following warning in console per each animation frame (don't know if it's an issue):

> [.WebGLRenderingContext-0x2338a562d180]PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty
> WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by hpinkos** [comment]
Thanks @ezze!  I'm pretty sure the issue you're seeing is related to #1518

**Comment by ezze** [comment]
@hpinkos, thanks for the reply!
Updated to Chrome 47, nothing is changed.
Waiting for some info on this or related issues.

**Comment by hpinkos** [comment]
@ezze I'm going to close this issue because I believe it's the same as #1518.  When we fix that issue someone will double check that the error you're seeing is fixed too.

Thanks!
