### ISSUE TITLE
Inspector - show frustums shader compilation error

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3262]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html&label=Showcases

If you click the 'show frustums' box, the shader fails to compile:

![error](https://cloud.githubusercontent.com/assets/915398/11482716/5de0567a-9772-11e5-8fb5-4c1c5f97ee3d.jpg)

It works fine when you are zoomed in close enough.

**Comment by pjcozzi** [comment]
I believe this is duplicate with #2448.
