### ISSUE TITLE
Quadtree Primitive Sandcastle error

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3263]
Happens after waiting a few seconds.

![image](https://cloud.githubusercontent.com/assets/915398/11482923/8642531a-9773-11e5-834e-ef307e332313.png)

**Comment by pjcozzi** [comment]
Not critical for 1.16 since this is in the Development tab.

@kring do you want to look at this?  Perhaps we changed `RectangleOutlineGeometry` recently.

**Comment by hpinkos** [comment]
Looks like we got rid of this sandcastle example
