### ISSUE TITLE
'All' button missing in Sandcastle

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3266]
Broken in #3232

[This promise](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/CesiumSandcastle.js#L1139) doesn't ever seem to resolve.

@mramato

**Comment by mramato** [comment]
`Hello World` also shows up at the end of the list now, rather than alphabetical.  Also marking as a showstpper.
