### ISSUE TITLE
JSHint problem in Sandcastle

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3267]
Probably also broken in #3232

Running Sandcastle from master, I noticed is it won't give an error if you're trying to use a variable that hasn't been defined yet.  On the website, it will highlight that line as having an error.

ie, the line `var foo = bar` should be highlighted because bar isn't defined.

@mramato

**Comment by mramato** [comment]
Marking this a showstopper.  This was broken with #3210.
