### ISSUE TITLE
Hitting browser refresh in Sandcastle causes Gallery to go blank

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3271]
I personally feel this is a showstopper.

**Comment by hpinkos** [comment]
It's because the query string has `label=undefined`.  It's not being set properly

**Comment by mramato** [comment]
That's always happened in Sandcastle, but it's much worse now because any refresh breaks it.

**Comment by mramato** [comment]
Also, linking like this now break too: http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Models.html&label=Showcases
