### ISSUE TITLE
The wiki page took too long to render invalid

### ISSUE THREAD

**Issue by ZYingithub** [AnalyticalGraphicsInc/cesium#3280]
I cannot open the the CZML Content Page,just reading: wiki page took too long to render.
So , where can I find the content page,please?

**Comment by pjcozzi** [comment]
Link: https://github.com/AnalyticalGraphicsInc/cesium/wiki/CZML-Content

Perhaps this is temporary or GitHub added a timer for how long it takes to render a page.  We'll split it up if needed.

Good catch, thanks for bringing it to our attention.

**Comment by ZYingithub** [comment]
Dear Mr.
Thanks a lot for your reply.
Good day!


ZhangYu
2015.12.03






At 2015-12-03 21:04:28, "Patrick Cozzi" <notifications@github.com> wrote:


Link: https://github.com/AnalyticalGraphicsInc/cesium/wiki/CZML-Content

Perhaps this is temporary or GitHub added a timer for how long it takes to render a page. We'll split it up if needed.

Good catch, thanks for bringing it to our attention.

**Comment by mramato** [comment]
Yeah, that's definitely a very recent development.

**Comment by shunter** [comment]
FYI I have been working on doc improvements in czml-writer and I have updated markdown for the wiki if/when this issue is resolved.  The updated content is not any smaller, though.  (current .md file is 531KB)

**Comment by pjcozzi** [comment]
@shunter it's fine if you are going with the old C# .md generator, but I used this for glTF: https://github.com/AnalyticalGraphicsInc/wetzel

**Comment by mramato** [comment]
The main issue (and I'm not sure if wetzel would improve this yet) is that there is a ton of repeating information in the current generated doc.  We should update whatever doc generator we end up going with to be able to have common types only documented once and then referred to throughout the rest of the document.

**Comment by drakej** [comment]
Is there an alternative source for this data as this situation gets sorted out?

**Comment by hpinkos** [comment]
@drakej here's a link to the raw markdown: https://raw.githubusercontent.com/wiki/AnalyticalGraphicsInc/cesium/CZML-Content.md

**Comment by drakej** [comment]
Thank you!

**Comment by pjcozzi** [comment]
Can we just split this page into two in the short-term?

**Comment by pjcozzi** [comment]
As a temporary workaround, I divided this into two pages: https://github.com/AnalyticalGraphicsInc/cesium/wiki/CZML-Content

**Comment by pjcozzi** [comment]
I suspect we could also move this into the repo since, for example, GitHub renders the long [glTF spec](https://github.com/KhronosGroup/glTF/blob/master/specification/README.md).

**Comment by shunter** [comment]
Updated CZML documentation.

https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Packet
