### ISSUE TITLE
Segment display is not connected

### ISSUE THREAD

**Issue by bicealyh** [AnalyticalGraphicsInc/cesium#3293]
I use the following method to draw polyline volume,but find the segment display is not connected,Why?

       function computeCircle(radius) {
                var positions = [];
                for (var i = 0; i < 360; i++) {
                        var radians = BeyonMap.Math.toRadians(i);
                        positions.push(new BeyonMap.Cartesian2(radius * Math.cos(radians), radius *  Math.sin(radians)));
                }
                return positions;
        }

        var promiseRoad =BeyonMap.GeoJsonDataSource.load('./Test.geojson');
        promiseRoad.then(function(dataSource) {
                var entities = dataSource.entities.values;
                var nowtime = BeyonMap.JulianDate.now();
                for (var i = 0; i < entities.length; i++) {
                        var entity = entities[i];
                        var redLine = viewer.entities.add({
                                polylineVolume : {
                                        positions : entity.polyline.positions.getValue(nowtime),
                                        shape : computeCircle(5.0),
                                        outline : false,
                                        material : BeyonMap.Color.WHITE
                                }
                        });
                }
        }).otherwise(function(error){
                //Display any errrors encountered while loading.
                window.alert(error);
        });

**Comment by bicealyh** [comment]
![test](https://cloud.githubusercontent.com/assets/6030959/11608061/1d323766-9b9a-11e5-9c3a-b912ba293b1a.png)

[Test.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/52852/Test.txt)

**Comment by hpinkos** [comment]
@bicealyh I submitted a fix here #3305 

This will fill in many of the gaps, but there are still some breaks because you data is a bunch of separate polylines.  You'll have to combine positions that are supposed to be connected into a single polyline in order for the `PolylineVolume` to fill in the rest of the gaps and corners.

**Comment by hpinkos** [comment]
@bicealyh This was fixed in #3305.  It will be included in the next release (Cesium 1.17)
