### ISSUE TITLE
Cesium in QlikView (BI)

### ISSUE THREAD

**Issue by seneric** [AnalyticalGraphicsInc/cesium#3304]
I try to integrate Cesium in a QlikView plugin and I had two problems.
- When you are in QlikView plugin resources are accessed through a queryString : 
  http://server/QvAjaxZfc/QvsViewClient.aspx?public=only&name=Extensions/QlikView/Examples/Local/Build/CesiumUnminified/Cesium.js
  In the URI module of Cesium (URI.prototype.resolve) the queryString is deleted so you can't load the resources (images for example).
  My "dirty" modification :
  .....
  if (baseURI.authority && baseURI.path == '') {
  uri.path = '/' + this.path;
  } else {
  //uri.path = baseURI.path.substring(0, baseURI.path.lastIndexOf('/') + 1) + this.path;
  uri.path = baseURI.path + "?" + baseURI.query + this.path;
  }
  uri.removeDotSegments();
  .....
- In the "cesiumWorkerBootstrapper.js" module in the "req.load" function, if isWebWorker the url value is trucated! There is not the ".js" extension at the end. I do not know why ?
  So "importScripts(url)" failed.
  My "dirty" modification :
  .....
  if (url.indexOf(".js") < 0) {
  url+= ".js";
  }
  importScripts(url);
  ....

After that Cesium is OK in QlikView plugins.

**Comment by hpinkos** [comment]
@seneric sorry we never responded to this.  If you're still having problems, please ask them on our [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev)
Thanks!
