### ISSUE TITLE
Development-only examples on cesiumjs.org

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3306]
The current deployed copy of Sandcastle, http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html, is showing the `Development` category and demos. I'm not sure if this has always been the case or something that happened last release, but these demos are not intended for end user consumption and shouldn't be on the website.

FYI, the old release links don't have this problem because they use the zip content and not the `cesiumjs.org` branch.

**Comment by AmayAgrawal** [comment]
So sir we have to just remove the whole thing (i.e. Development category).Can I work on it??

**Comment by pjcozzi** [comment]
I thought there was another issue for this, but I am still in support of including the Development examples, especially now for CI since, for example, we can't test the hosted branch for https://github.com/AnalyticalGraphicsInc/cesium/pull/3819.

**Comment by mramato** [comment]
You can still access those examples, they just aren't in the gallery (we could also change this for CI builds): http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/shadows-commands/Apps/Sandcastle/index.html?src=development/Shadows.html&label=Showcases

I would rather see us "promote" relevant examples (perhaps a `Primitives` label) instead of just exposing all developer examples on the website.  Developer examples are largely unmaintained and anything on the site should be curated enough that it gets tested with each release.

**Comment by pjcozzi** [comment]
All the development examples work AFAIK.  I test them when I do a release.  I'm OK with positioning them however you want, but hiding them is clearly not working for us and users.  Given everything we are working on, what do you realistically want to see happen in the short-term?  Just show them by default for CI?

**Comment by hpinkos** [comment]
There have been multiple people on the forum asking where the development tab went.  It's nice to have it on the website because every now and again I need to link to an example for a question someone has on the forum.

I'm okay with compromising and keeping the less polished examples off of the website.  But I agree with @pjcozzi, I wouldn't say they're unmaintained.  Most of those demos are in good shape and they're useful to people.

**Comment by hpinkos** [comment]
I haven't seen anyone in the forum mention this in a really long time, so I'm going to close this issue
