### ISSUE TITLE
Simplify imagery provide declarations

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3329]
Do they still need to be declared like this:
```javascript
var ArcGisImageServerTerrainProvider = function ArcGisImageServerTerrainProvider(options) {
```
instead of just
```javascript
var ArcGisImageServerTerrainProvider = function(options) {
```

**Comment by mramato** [comment]
Technically, @kring wanted to go the other way where everything in Cesium is just declared as:

```javascript
function ArcGisImageServerTerrainProvider(options) {
```

because it made browsers give better errors but JSDoc didn't support that at the time (but I'm fairly certain they do now).  In either case, we should decide on the preferred way to declare a constructor function in Cesium (which is most likely with `var Foo = function()`) and use it everywhere.

Browser debuggers and JSDoc handle all cases now as far as I know.

**Comment by pjcozzi** [comment]
Given its conciseness, I prefer this too:
```javascript
function ArcGisImageServerTerrainProvider(options) {
```

**Comment by shunter** [comment]
yes.  If `function Foo() {` works with JSDoc now, we should switch everywhere.  The only reason for `var Foo = function() {` was JSDoc.

**Comment by mramato** [comment]
This should be easy with a find/replace regex.  Something like `var\s(.*)\=\s?function\s?(.*)?\{` and then the replace would be `var $1 = function \{`

**Comment by kring** [comment]
I did this because of this:

```
var Foo = function() {};
var foo = new Foo();
expect(foo.constructor.name).toBe('');

var Bar = function Bar() {};
var bar = new Bar();
expect(bar.constructor.name).toBe('Bar');
```

I just verified that this is still true in Chrome.

Obviously if JSDoc now works without the extra assignment, that's the best way to go.

**Comment by kring** [comment]
The also extends to other ways of looking at the constructor function in the Chrome debugger.  For example, in the Chrome debugger:

```
> var x = Foo;
> x
<- function() {}
> var y = Bar;
> y
<- function Bar() {}
```

**Comment by pjcozzi** [comment]
@kring just to confirm, you are OK with this simplifying change even though it hurts that debugging case?

**Comment by kring** [comment]
I'm definitely ol with #3338 because it is the best of both worlds, now that jsdoc supports it.
