### ISSUE TITLE
Put @see after @example

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3331]
A lot of our reference doc has `@see` before `@example` (either because years ago the `@see` tag was generated as part of the example or I just thought it was ):
```javascript
    /**
     * ...
     * @see TerrainProvider
     *
     * @example
     * var terrainProvider = new Cesium.ArcGisImageServerTerrainProvider({
     *   url : '//elevation.arcgisonline.com/ArcGIS/rest/services/WorldElevation/DTMEllipsoidal/ImageServer',
     *   token : 'KED1aF_I4UzXOHy3BnhwyBHU4l5oY6rO6walkmHoYqGp4XyIWUd5YZUC1ZrLAzvV40pR6gBXQayh0eFA8m6vPg..',
     *   proxy : new Cesium.DefaultProxy('/terrain/')
     * });
     * viewer.terrainProvider = terrainProvider;
     */
    var ArcGisImageServerTerrainProvider = function ArcGisImageServerTerrainProvider(options) {
```
`@see` should always come after `@example` like it does in the generated doc:
```javascript
    /**
     * ...
     * @example
     * var terrainProvider = new Cesium.ArcGisImageServerTerrainProvider({
     *   url : '//elevation.arcgisonline.com/ArcGIS/rest/services/WorldElevation/DTMEllipsoidal/ImageServer',
     *   token : 'KED1aF_I4UzXOHy3BnhwyBHU4l5oY6rO6walkmHoYqGp4XyIWUd5YZUC1ZrLAzvV40pR6gBXQayh0eFA8m6vPg..',
     *   proxy : new Cesium.DefaultProxy('/terrain/')
     * });
     * viewer.terrainProvider = terrainProvider;
     *
     * @see TerrainProvider
     */
    var ArcGisImageServerTerrainProvider = function ArcGisImageServerTerrainProvider(options) {
```
```

**Comment by AmayAgrawal** [comment]
I am looking over it and I have found that some files only contain @see while some only contain @example.So we have to check only those files which contains both?? or we have to update those files also which contains only @see or @example.

**Comment by pjcozzi** [comment]
Hi @AmayAgrawal!  Thanks for looking into this.

> So we have to check only those files which contains both??

Exactly.  Just leave the ones that only have `@example` or `@see`, but not both.

**Comment by AmayAgrawal** [comment]
* @see CorridorOutlineGeometry.createGeometry
     *
     * @demo {@link http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Corridor%20Outline.html|Cesium Sandcastle Corridor Outline Demo}
     *
     * @example
     * var corridor = new Cesium.CorridorOutlineGeometry({
     *   positions : Cesium.Cartesian3.fromDegreesArray([-72.0, 40.0, -70.0, 35.0]),
     *   width : 100000
     * });
     */

For this type we have to push both @see as well as @demo at the last??Or not to change this type of file

**Comment by pjcozzi** [comment]
When there is a `@demo` tag, the order can be:
```
@see
@demo
@example
```
