### ISSUE TITLE
Terrain disappears zooming and tilting - Cesium 1.16

### ISSUE THREAD

**Issue by slightGT** [AnalyticalGraphicsInc/cesium#3335]
Dear all,

I would like to highlight a bug with the new versione 1.16 of Cesium.
The terrain disappears at a certain level of zoom and tilting the camera near the terrain generates the same bug.

![bugcesium_compressed](https://cloud.githubusercontent.com/assets/12815732/11739144/7d440bb8-9fe9-11e5-8ddf-5c4e8f05e782.gif)

![bugcesium2_compressed](https://cloud.githubusercontent.com/assets/12815732/11739892/fdb6bfac-9fee-11e5-99ad-ba746d432e9c.gif)

It seems that the issue is raised up only in certain areas, for example in the north east Italy.
To reproduce the bug search the city of "Trento" in the Cesium demo on the front page of the website.

The related post on the forum: http://cesiumjs.org/forum.html#!msg/cesium-dev/2_2zBxN7Dno/qT6Vzep-CQAJ
Best Regards,
Michele

**Comment by mramato** [comment]
Thanks @slightGT This is definitely a bug and I could easily reproduce it after zooming to Trento.

@bagnell this is definitely a recent regression with all of the terrain work you've been doing.  We should probably look into it ASAP.

**Comment by pjcozzi** [comment]
+1

**Comment by pjcozzi** [comment]
@slightGT thanks for the detailed report.  This was fixed in #3365 and will be released in Cesium 1.17 on January 4.
