### ISSUE TITLE
Change extrudeHeight with the time 

### ISSUE THREAD

**Issue by juacarri** [AnalyticalGraphicsInc/cesium#3339]
Hello, I'm trying to change the extrudeHeight with the time, like in the 4D choropleth  demo, but I have no idea... I did this code, but dont do nothing:

var czml = [
  {
    "id" : "document",
    "name" : "CZML Geometries: Circles and Ellipses",
    "version" : "1.0"
  },
{
    "id" : "redRectangle",
    "name" : "extruded red rectangle with black outline",
    "rectangle" : {
      "coordinates" : { "wsenDegrees" : [-120, 40, -110, 50] },
      "height" : 600000,
	  
	  
      "extrudedHeight": {
      "interpolationAlgorithm": "LINEAR",
      "interpolationDegree": 1,
      "interval" : "2012-08-04T16:00:00Z/2012-08-04T17:00:00Z",
      "epoch" : "2012-08-04T16:00:00Z",
      "extrudedHeight": [
        0, -60, 35, 30000
      ]},
	  
	  
    
      "fill" : true,
      "material" : {
        "solidColor" : {
          "color": {
            "rgba" : [255, 0, 0, 100]
          }
        }
      },
      "outline" : true,
      "outlineColor" : {
        "rgba" : [0, 0, 0, 255]
      }
    }
  }
];

Could you help me? Thanks! :)

**Comment by juacarri** [comment]
I resolved it:

      "extrudedHeight": {
			"number":["2012-08-04T16:00:00Z",999999,"2012-08-04T17:00:00Z",5000]},
	  
But where can I get a tutorial or some information about use the time and czml? Do you know how to convert a geojson to czml?

**Comment by juacarri** [comment]
I have another question, in relation with this topic. I want to change the final position of a polyline with the time. Why appear an error following the same structure?

  {
    "id" : "orangeLine",
    "name" : "Orange line with black outline at height and following the surface",
    "polyline" : {
      "positions" : {
        "cartographicDegrees" : [
          -75, 30, 0,
          -75, 30, {"number":["2012-08-04T16:00:00Z",5000,"2012-08-04T17:00:00Z",50000]}
        ]
      },
      "material" : {
        "polylineOutline" : {
          "color" : {
            "rgba" : [255, 165, 0, 255]
          },
          "outlineColor" : {
            "rgba" : [0, 0, 0, 255]
          },
          "outlineWidth" : 2
        }
      },
      "width" : 5
    }
  }

**Comment by pjcozzi** [comment]
Hi @juacarri - try posting your question on the [Cesium forum](http://cesiumjs.org/forum.html). It will get a lot more attention.

See the [guidelines for submitting an issue](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#submitting-an-issue).
