### ISSUE TITLE
Replace @namespace with @exports

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3342]
I believe the best practice is to, for example, replace
```javascript
    /**
     * Object for setting and retrieving the default BingMaps API key.
     *
     * @namespace
     * @alias BingMapsApi
     */
    var BingMapsApi = {
    };
```
with
```javascript
    /**
     * Object for setting and retrieving the default BingMaps API key.
     *
     * @exports BingMapsApi
     */
    var BingMapsApi = {
    };
```
The old doc guide sounds like this is the case:
> Use `@exports moduleName` to document modules, including static classes and standalone functions.

Need to verify it produces the same results.

**Comment by Decatek** [comment]
I just finished working on this issue, I'm going to open a pull request in minutes

**Comment by pjcozzi** [comment]
Wow, thanks @Decatek!  Can you please [submit a CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) if you haven't already?

**Comment by Decatek** [comment]
I sent the CLA to cla@agi.com
Pull request will come soon!

**Comment by pjcozzi** [comment]
Thanks, we received the CLA.
