### ISSUE TITLE
Replace "use strict" with 'use strict'

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3345]
As mentioned here: https://github.com/AnalyticalGraphicsInc/cesium/pull/3312#discussion_r47279560

**Comment by eputnam** [comment]
has this issue been resolved?

**Comment by pjcozzi** [comment]
No, you are welcome to go for it!

**Comment by AmayAgrawal** [comment]
Sir can u please explain what we have to do exactly in this issue
