### ISSUE TITLE
Atmosphere disappears as you look up

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3347]
Reported on the forum https://groups.google.com/forum/?hl=en#!topic/cesium-dev/su5kb_cNN7Y

This seems to have been introduced in 1.16.

* Zoom into the globe and tilt
* Middle mouse drag on the sky to keep tilting up
* The atmosphere flickers then disappears completely when the globe leaves the bottom of the screen

**Comment by pjcozzi** [comment]
This may have changed in 1.16, but I have reproduced this in older versions.

**Comment by lilleyse** [comment]
This is still an issue as of 1.21. @likangning93 would you like to take a look at this? You can use the 3D Models Sandcastle demo as an example of this.
