### ISSUE TITLE
CZML Ellipsoid with time-dependent geometry results in incomplete ellipsoid visualization

### ISSUE THREAD

**Issue by kjartab** [AnalyticalGraphicsInc/cesium#3354]
When adding the following ellispoid using CZML loading it results in an ellipsoid with a hole on the top, removing the time-dependent geometric properties (position or radii) results in a complete ellipsoid. Time-dependent colors on for instance do not seem to cause the same bug. 

Verified to be the case in the Sandcastle app as well.
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML%20Spheres%20and%20Ellipsoids.html 

```javascript
{
    "id" : "redSphere",
    "availability" : "2012-08-04T10:00:00Z/2012-08-04T15:00:00Z",
    "position" : {
        "cartographicDegrees" : [ 15, 67, 1500.0 ]
    },
    "ellipsoid" : {
      "radii" : {
        "epoch" : "2012-08-04T10:00:00Z",
        "cartesian" : [
         0, 30000.0, 30000.0, 30000.0,
         2000, 30000.0, 70000.0, 30000.0
         ]
      },
      "fill" : true,
      "material" : {
        "solidColor" : {
          "color" : {
            "epoch" : "2012-08-04T10:00:00Z",
            "rgba" :  [
            0, 192, 0, 0, 0,
            300, 192, 0, 0, 100,
            600, 192, 0, 0, 253,
            1000, 192, 0, 0, 254,
            1001, 192, 0, 0, 0,
            1100020, 192, 0, 0, 0
            ]
          }
        }
      }
    }
  }
```

**Comment by hpinkos** [comment]
Hello @kjartab 
Thanks for reporting this!  The CZML sample is really helpful.
This is a known issue, first reported here: #3045
I'm going to close this issue because the other one is open so we don't have duplicates, but I'll link that issue to your CZML example =)
