### ISSUE TITLE
README tweaks

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3372]
1. The current README links to the old Getting Started url, it should link to the new one.
2. Should we link to the website downloads page directly from the Getting Started section?
3. Should we mention `npm` in the README Getting Started section? (most modules do so that people know what the official module is)
4. The forum links to google groups, should it link to our site's forum page?

**Comment by AmayAgrawal** [comment]
1. I think that it should link to this url: http://cesiumjs.org/tutorials/cesium-up-and-running/
I also think that 2, 3 and 4 are good points.
But about npm what should we include in it??

**Comment by pjcozzi** [comment]
Updated in #3376.
