### ISSUE TITLE
Proposal for Bathymetric Terrain Tile Type

### ISSUE THREAD

**Issue by bellengj** [AnalyticalGraphicsInc/cesium#3384]
At line 186 of Source/Core/CesiumTerrainProvider.js I would like the following code added to create a surfacemap-1.0 type that would allow for full bathymetric elevations

            } else if (data.format === 'surfacemap-1.0') {
                that._heightmapStructure = {
                        heightScale : 1.0 / 3.0,
                        heightOffset : -12000.0,
                        elementsPerHeight : 1,
                        stride : 1,
                        elementMultiplier : 256.0,
                        isBigEndian : false
                    };
                that._hasWaterMask = true;
                that._requestWaterMask = true;

This would provide a heightmap type format with offset of 12000 meters below zero and a 1/3 scaling factor.

**Comment by abwood** [comment]
This appears to be a modification to the heightmap-1.0 spec, which as you have found does not support bathymetric elevations well.  The successor to heightmap-1.0 is the quantized-mesh 1.0 spec, which already supports bathymetric data as it stands.  

For quantized-mesh tiles, the source elevation data overlapping a terrain tile will be quantized to values between minHeight and maxHeight.  What this means for you is that your data will be more accurately represented using the Cesium-ready quantized-mesh format.

**Comment by bellengj** [comment]
The issue with quantized-mesh format is that only the for cost AGI Terrain software creates this format.  I was able to a self modified the Univ. of Southampton ctb-tile program along with the Southampton terrain server to build a nice bathy globe.

**Comment by markerikson** [comment]
@bellengj : would you be interested in contributing those changes back to cesium-terrain-builder?  I'm sure others would appreciate the improvements as well.

**Comment by pjcozzi** [comment]
@bellengj quantized-mesh is the preferred terrain format because it contains a precise geometric error and requires very little processing to render (if this were 3D models, quantized-mesh is like glTF and height-map-based formats are like COLLADA).

We actually want to discourage use of heightmaps since they are not efficient, which is why, for example, the old heightmap dataset was deprecated.  So introducing another heightmap format is a step in the opposite direction we want to take.

**Comment by bellengj** [comment]
Is there an open source way to create quantized-mesh terrain files for those that can't afford STK Terrain Server?

**Comment by pjcozzi** [comment]
@bellengj the core Cesium team has not developed one, you would have to search around to see if there are others.

Closing given this is not the right technical direction.
