### ISSUE TITLE
Picking unpredictable in 1.17

### ISSUE THREAD

**Issue by chris-cooper** [AnalyticalGraphicsInc/cesium#3386]
I'm finding 'Drill Down Picking' in the 'Picking' Sandcastle example gives flickering results in 1.17 vs 1.16.  I notice another user has [reported something on the mailing list](https://groups.google.com/forum/#!topic/cesium-dev/N-f7uh5e6Zs) which may be related.  Tested on Chrome with Intel graphics running Ubuntu 14.04.

**Comment by chris-cooper** [comment]
I think you can repro what the OP was referring to with the labels example.  A single click brings up the green crosshairs in [1.16](http://cesiumjs.org/releases/1.16/Apps/Sandcastle/index.html?src=Labels.html&label=Showcases) but not in [1.17](http://cesiumjs.org/releases/1.17/Apps/Sandcastle/index.html?src=Labels.html&label=Showcases)

**Comment by pjcozzi** [comment]
@bagnell can you look at the drill picking issue ([Sandcastle example](http://cesiumjs.org/releases/1.17/Apps/Sandcastle/index.html?src=Picking.html&label=Showcases))?  The easiest way to reproduce it is to mouse over the part where all three rectangles overlap.  It seems OK when there is not overlap.

**Comment by emackey** [comment]
This affects selection too:  If you load the [CZML Sandcastle Demo](http://cesiumjs.org/releases/1.17/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases), you can't single-click the entities to select them.

**Comment by ezze** [comment]
I faced the same issue in my project after upgrading to 1.17. I do picking on left mouse click, and it seems that it works only on the second attempt (at least, it never works on the first click).

**Comment by emackey** [comment]
`git bisect` says the first bad commit is 539cf3c94a.

**Comment by pjcozzi** [comment]
@emackey fixed this in #3391. @chris-cooper @ezze thanks again for the report.

**Comment by chris-cooper** [comment]
Thanks team!  :thumbsup:
