### ISSUE TITLE
QuadtreePrimitive Sandcastle example Rectangle exception

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3388]
With master, browse to http://localhost:8080/Apps/Sandcastle/index.html?src=development/QuadtreePrimitive.html&label=Development

Then zoom in, and switch to the console tab:

![image](https://cloud.githubusercontent.com/assets/782098/12150285/ecd110ce-b476-11e5-8885-16b1065fab41.png)

Is this due to recent changes to the `Rectangle` error checking?

**Comment by lilleyse** [comment]
Duplicate of #3263

**Comment by pjcozzi** [comment]
Ah, I searched for "QuadtreePrimitive", not "Quadtree Primitive"
