### ISSUE TITLE
Cracking between 2D tiles

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3393]
@bagnell this is new in 1.17 perhaps due to the quantization.  It happens for ellipsoid and terrain tiles.

* Run Viewer
* Switch to 2D
* Zoom in close to an area, you'll see black cracks

![ok](https://cloud.githubusercontent.com/assets/782098/12154535/1bad9e1e-b48e-11e5-8853-0112d5076f48.gif)

**Comment by kepta** [comment]
@pjcozzi I would love to work on this issue, but I am new to webGL.
Can I work on it?

**Comment by pjcozzi** [comment]
Thanks for the interest in contributing, @kepta!  I don't think this is a good beginner issue.  For ideas, check out: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#getting-started-contributing

**Comment by pjcozzi** [comment]
@bagnell can you still look at this for 1.18 (on Monday)?
