### ISSUE TITLE
Trademark Violation?

### ISSUE THREAD

**Issue by drakej** [AnalyticalGraphicsInc/cesium#3399]
https://itunes.apple.com/us/app/cesium-streamlined-music-player/id924491991?mt=8

Noticed this app using the same name. Just thought I would bring your attention to it.

**Comment by pjcozzi** [comment]
Thanks @drakej.  In the future, feel free to email me directly (pcozzi@agi.com) about things like this so we can keep the GitHub issues focused on code.
