### ISSUE TITLE
Create getExtensionFromUri helper function

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3403]
A few areas of the code get the extension from a uri as follows:

`var ext = ext.substr(filename.lastIndexOf('.') + 1);`

We should add a private helper function instead. 

`KmlDataSource` and `Cesium3DTile` will use the new function.

**Comment by pjcozzi** [comment]
@lilleyse please close this when ready (before or after the PR into `3d-tiles` is OK).
