### ISSUE TITLE
Create tileset with the tiles.json path

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3404]
For #3241 

Currently when you create a `Cesium3DTileset` you pass in a url to the tileset folder. The code assumes the tiles json file is called `tiles.json`, which may not be true in all cases. 

We should support `options.url` to be either a directory of the tileset or a path to the tiles.json file. In either case, `this._url` should stay the directory of the tileset and `this._tilesJson` should stay the path to the tiles.json file.

This will help clean up the tileset tests which can't reuse files due to this limitation.

**Comment by TomPed** [comment]
The url that is passed in to the tileset folder is the `options.url`?

**Comment by lilleyse** [comment]
Yeah `options.url` refers to the url of the tileset, which usually is the directory but in this PR it should also be a path to a `.json` file.
