### ISSUE TITLE
Cesium broken in latest WebGL2 Chrome implementation

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3425]
Chrome Canary recently added a `WebGL 2.0 Prototype` option to chrome://flags and when I tried it out I noticed that Cesium no longer works (if I recall correctly, @bagnell and @lilleyse got it working during our last sprint).  Running Cesium Viewer spits out the following errors:

```
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: 
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
index.html:1 [.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
```

It's possible this is a bug in Chrome's implementation, but we should check it out either way and file a bug with them if it is.

**Comment by pjcozzi** [comment]
Works now in Canary 56.

![image](https://cloud.githubusercontent.com/assets/782098/20005210/42d7b08e-a267-11e6-9e6e-1c086416dbb1.png)

![image](https://cloud.githubusercontent.com/assets/782098/20005248/8b1232c0-a267-11e6-8b7f-a5f5c5ea85a5.png)

Some Cesium features may not work yet, but we'll handle that as part of #797.
