### ISSUE TITLE
Hello World demo app broken

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#3428]
Keep in mind you need to `npm run minify` before testing Hello World.  Also, for debugging, you can edit HelloWorld.html to switch to the `CesiumUnminified` folder (and then `combine` will suffice instead of `minify`, and you can read the source near the exception).

This bug was just introduced yesterday with #3418.  An exception is thrown when creating the default imagery providers.

**Comment by pjcozzi** [comment]
@TomPed can you please look at this soon?

**Comment by TomPed** [comment]
Sure thing, I'll take a look.

**Comment by TomPed** [comment]
@emackey is this the error you are talking about?

![screen shot 2016-01-15 at 11 38 06 am](https://cloud.githubusercontent.com/assets/11602092/12358678/7ddaf664-bb7c-11e5-933b-bc8179bacef1.png)

**Comment by TomPed** [comment]
This is what the code in `buildModuleUrl.js` was before using `getAbsoluteUri`:

```javascript
baseUrl = new Uri(baseUrlString).resolve(new Uri(document.location.href));
```

**Comment by TomPed** [comment]
I've substituted that in and I seem to be getting the error still.
