### ISSUE TITLE
Have the build generate occasional status output

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3430]
Our travis builds occasionally fail because travis thinks the build process is hung but in reality the build steps are taking more than 10 minutes and don't print out information during the process.  We can fix this by updating the gulpfile to set `config.logLevel = 1;` in `requirejsOptimize`.  This will spit out a line for each file as it's working.

@TomPed This should be an easy one for you to work on.

**Comment by mramato** [comment]
The downside is that this clutters up the travis output, but that's how it used to be before the gulp port anyway.

**Comment by mramato** [comment]
Actually, another solution is to prepend `travis_wait` in travis.yml to the npm command, as discussed here: https://docs.travis-ci.com/user/build-timeouts.  This is my preferred solution since it will no longer clutter output.

That being said, some developers have expressed interest in status info being written (as described above).  So if you feels strongly about it one way or the other, here's your change to chime in.

CC @shunter

**Comment by TomPed** [comment]
For the latter option, does the command `install: travis_wait mvn install` need to be ran in addition to adding the prefix `travis_wait` in travis.yml, or is that install a one time thing?

**Comment by mramato** [comment]
No, just add `travis_wait` to the immediately before `npm run`, but after the `-`

**Comment by TomPed** [comment]
Got it.
