### ISSUE TITLE
Remove GroundPrimitive.geometryInstance

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#3431]
Deprecated in #3429.

**Comment by sanuj** [comment]
@pjcozzi I would like to work on this. Shall i replace all `geometryInstance` by `geometryInstances` in the code base in a new branch or is there more to it?

**Comment by pjcozzi** [comment]
@bagnell is the best person to advise.

**Comment by bagnell** [comment]
@sanuj It does not need to be replaced, just removed and only in `GroundPrimitive`. Though you may want to work on something else because it needs to be removed after the 1.19 release. Otherwise, it would sit in a branch until then.

**Comment by sanuj** [comment]
@bagnell I'll remove it after the 1.19 release then.
