### ISSUE TITLE
Refactoring tiles.json to tileset.json

### ISSUE THREAD

**Issue by TomPed** [AnalyticalGraphicsInc/cesium#3437]
I've changed the all of the `tiles.json` files to `tileset.json`. Once I change them I seem to be getting some failed test, any thoughts why this would be happening? This is for `Cesium3DTilesetSpec`.
![screen shot 2016-01-18 at 9 13 42 am](https://cloud.githubusercontent.com/assets/11602092/12393483/f5c70458-bdc3-11e5-8e8e-5e7b4d641358.png)

**Comment by lilleyse** [comment]
I'm not sure if you've checked already, but make sure all occurrences of `tiles.json` are also changed in the code.

**Comment by TomPed** [comment]
Yep, I changed that as well.

**Comment by lilleyse** [comment]
Ok, I think it might be because some `tileset.json` files are referencing `tiles.json` files internally. Make sure to edit the files in the `TilesetOfTilesets` folder.

**Comment by TomPed** [comment]
That worked, thanks.

**Comment by pjcozzi** [comment]
@TomPed did you mean to close this issue?  Was a related pull request merged?

**Comment by TomPed** [comment]
I think I meant to close it :smile:. I have no PR open yet, I just had an issue while working on it. Should I have made the PR first then opened the issue and waited to close once merged?

**Comment by pjcozzi** [comment]
Ah, I see.  A better workflow here is to open the pull request with a tasklist for remaining items and then ask the question in the PR.  For example: https://github.com/AnalyticalGraphicsInc/cesium/pull/3406#issue-126028253
