### ISSUE TITLE
Ability to change atmosphere color

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3439]
This has been asked for a few times, including this [forum post](https://groups.google.com/forum/#!topic/cesium-dev/jGgNInY2Fqo) and this [FOSS4G presentation](https://vimeo.com/106853454).

Good beginner graphics issue.

**Comment by kepta** [comment]
Hi @pjcozzi , can I work on this one?
In this file SkyAtmosphereVS.glsl,
```
const vec3 v3InvWavelength = vec3(
    5.60204474633241,  // Red = 1.0 / Math.pow(0.650, 4.0)
    9.473284437923038, // Green = 1.0 / Math.pow(0.570, 4.0)
    19.643802610477206); // Blue = 1.0 / Math.pow(0.475, 4.0)
```
I think this is what needs to be modified? Any pointers on how to implement?

**Comment by tokyovigilante** [comment]
Some additional realism could be added to the atmosphere when lighting is enabled by fading the brightness or alpha on the night side of the globe.

It might also be cool down the track to combine the existing fog and atmosphere into a unified shader.  The new Google Earth JS app does this, and there is another GLES/Unity example at http://scrawkblog.com/2014/05/19/proland-to-unity-atmosphere/. This might be a bigger effort though. 

There are some additional posts [on that blog](http://scrawkblog.com/category/atmosphere/) regarding varying the Rayleigh scatter value to produce different colors, but I think that's more related to Earth's atmosphere at different times of day.

**Comment by kepta** [comment]
@tokyovigilante Can you help me work on this bug ? :P

**Comment by tokyovigilante** [comment]
Sure, my physics background doesn't cover optics extensively, but we can give it a crack. 

Have a look at [Mie](https://en.wikipedia.org/wiki/Mie_scattering) and [Rayleigh](https://en.wikipedia.org/wiki/Rayleigh_scattering) scattering online.

The atmosphere in Cesium is currently based on [this GPU Gems article](http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter16.html) 

There is a DX9 implementation for the Proland renderer I posted above. I've just found [another OpenGL implementation](https://github.com/korgan00/TFG-Atmospheric-Scattering/blob/master/OGL-SDL_Template/app/shaders/scattering.fs.glsl) which has an impressive [YouTube demo](https://www.youtube.com/watch?v=zV-XPXddpgI) and should be relatively easy to port over to Cesium, however it has a fairly heavy fragment shader so I'm not sure about performance.

What effects are you aiming to implement? I would suggest increased realism during sunrise and sunset and day/night fading when the camera is in space are most useful.

**Comment by kepta** [comment]
First I would like to know, 
Do we need to implement an API to change atmosphere colour?

**Comment by tokyovigilante** [comment]
Again that depends on your goal. If you want a more realistic representation of Earth's atmosphere, you'll need to implement one of the approaches I've mentioned above.

If you want to represent a different atmosphere, then you need to understand that the mixture of gases determine the scattering of sunlight and therefore perceived color, and alter input parameters, which to do effectively you'll again need to understand Rayleigh scattering.

Lastly, if you just want a ground-based view to have a different color, just turn off the atmosphere entirely and use either a static background color or a SkyBox with custom textures to simulate the atmosphere you want.
