### ISSUE TITLE
Strange atmosphere/sun rendering

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3442]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/w3Uht1MILjU

To reproduce:
1. [3D Models](http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Models.html&label=Showcases) demo
2. Select the milk truck
3. Tilt the camera all the way down and rotate it so the sun is in frame
4. Move the camera left and right with the sun in frame.  The atmosphere and sun will get gradually lighter then suddenly darker, etc

**Comment by lilleyse** [comment]
Duplicate of this: https://github.com/AnalyticalGraphicsInc/cesium/issues/3178

**Comment by hpinkos** [comment]
thanks @lilleyse
