### ISSUE TITLE
Strange texture coordinates

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#3447]
I'm seeing a strange issue that I haven't fully tracked down yet.  It appears to be damaged texture coordinates, or incorrect interpolation of some kind.  Here's some code to reproduce in Sandcastle:

```
var extent = Cesium.Rectangle.fromDegrees(85, -5, 90, 5);
Cesium.Camera.DEFAULT_VIEW_RECTANGLE = extent;

var viewer = new Cesium.Viewer('cesiumContainer');
var ellipsoid = viewer.scene.mapProjection.ellipsoid;

var boxAltitude = 1500000;
var boxCenter = 86.4;
var halfLonAngle = 0.5;
var halfLatAngle = 1.5;

var boxPositions = ellipsoid.cartographicArrayToCartesianArray([
    Cesium.Cartographic.fromDegrees(boxCenter - halfLonAngle, halfLatAngle),
    Cesium.Cartographic.fromDegrees(boxCenter - halfLonAngle, -halfLatAngle),
    Cesium.Cartographic.fromDegrees(boxCenter + halfLonAngle, -halfLatAngle),
    Cesium.Cartographic.fromDegrees(boxCenter + halfLonAngle, halfLatAngle)
]);

var material = Cesium.Material.fromType('Checkerboard');

var geoBoxInstance = new Cesium.GeometryInstance({
    geometry : Cesium.PolygonGeometry.fromPositions({
        positions : boxPositions,
        height : boxAltitude
    })
});

viewer.scene.primitives.add(new Cesium.Primitive({
    geometryInstances : [geoBoxInstance],
    appearance : new Cesium.MaterialAppearance({
        material : material
    })
}));
```

The desired result is a box with a proper material applied, in this case the Checkerboard material shows the layout of the texture coordinates.  Here's what my machine produces:

![bustedbox](https://cloud.githubusercontent.com/assets/1235080/12459803/8e2e64d2-bf7e-11e5-9d35-e27300cf72b7.png)

Of course I would expect the checkerboard to be made of rectangles, such as shown in the middle, not with diagonal facets shown at the top and bottom.  The "Grid" material shows the same pattern, which makes me think it's a texture coordinate problem.

I've tested Cesium as far back as version 1.5, and this issue affects every version I've tested.  If it is a Cesium bug, it's been in there forever.  But I've never seen it before last month, and I've got multiple reports of it now.  Possible a driver update has broken something?  Or we just never asked for boxes of this exact size and placement before last month?  Lots of unanswered questions.

**Comment by mramato** [comment]
I can reproduce this.  It seems to be related to height, at 112 there's no problem, at 113 you see one side go incorrect.  The higher you go the more incorrect it gets.  My guess is either there's a precision issue we're not taking into account (so the farther you get from Cartesian3.ZERO the worse it gets), or we simply aren't accounting for height somwhere.


Here's another simplified example via the Entity API.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var height = 113;
var center = 86.4;
var halfLonAngle = 0.5;
var halfLatAngle = 1.5;

viewer.entities.add({
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([center - halfLonAngle, halfLatAngle,
                                                        center - halfLonAngle, -halfLatAngle,
                                                        center + halfLonAngle, -halfLatAngle,
                                                        center + halfLonAngle, halfLatAngle]),
        height : height,
        material : new Cesium.CheckerboardMaterialProperty()
    }
});

viewer.zoomTo(viewer.entities);
```

**Comment by mramato** [comment]
You can also see this in http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Geometry%20and%20Appearances.html&label=Showcases

Just change the first polygon (second item overall) and add `height: 150000,`.  It will produce the following:

![image](https://cloud.githubusercontent.com/assets/1495196/12460889/0d1702ae-bf84-11e5-9cd2-3fd3d9cfdf01.png)

**Comment by emackey** [comment]
Here's some more insight.  Paste the sample from the top of this issue back into Sandcastle, and replace the one line in the middle where `var material` is declared, with the following:

```
var material = new Cesium.Material({
    fabric : {
        components : {
            diffuse : 'vec3(materialInput.st.t)'
        }
    }
});
```

This custom material shows just the vertical texture coordinate `t`, as brightness.  If we also modify `boxAltitude` to be 100 meters, we see the expected vertical gradient: (surrounded by blue ocean in this screenshot)

![goodtexcoord](https://cloud.githubusercontent.com/assets/1235080/12470380/a222d930-bfc1-11e5-99d7-f1ff4d20c889.png)

But to reproduce the bug, we use the original `boxAltitude = 1500000`, and this pattern emerges:

![badtexcoord](https://cloud.githubusercontent.com/assets/1235080/12470385/a8ccc980-bfc1-11e5-8c14-53f822c8e460.png)

The problem only shows up in the vertical `t` channel, not the horizontal `s` channel.

In `PolygonGeometry.js` if you [set a breakpoint here](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.17/Source/Core/PolygonGeometry.js#L245), you can inspect the values of `textureCoordinates`.  The `s` coordinates range from `0` to `1` exactly, but the `t` coordinates are more sloppy, going below `0.0` and above `1.0` along the bottom and top edges.  It seems like the computation of these coordinates is somehow problematic.

**Comment by emackey** [comment]
Thanks @hpinkos!
