### ISSUE TITLE
Remove throttleRequests flag in TerrainProvider and inherited classes

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3448]
`throttleRequests` is now replaced by a `Request` object. For `1.19`, the following code

``` javascript
if (!defined(request) || (request === false)) {
```

can change to

``` javascript
if (!defined(request)) {
```

in `ArcGisImageServerTerrainProvider`, `CesiumTerrainProvider`, and `VRTheWorldTerrainProvider`.

**Comment by AmayAgrawal** [comment]
Can u give one example of what to change exactly

**Comment by pjcozzi** [comment]
Thanks for the interest, @AmayAgrawal, but let's wait until #3476 is merged.

**Comment by pjcozzi** [comment]
@lilleyse reminder to label this once 3D Tiles is merged.
