### ISSUE TITLE
Use frameState.afterRender to fire QuadtreePrimitive.tileLoadProgressEvent

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3450]
In case, for example, someone adds new primitives in the callback.

For example, see https://github.com/AnalyticalGraphicsInc/cesium/blob/7d449906cf65cf06e75d5cde7bf2dd5921bc95dd/Source/Scene/ModelAnimationCollection.js#L387

**Comment by kepta** [comment]
@pjcozzi  Can I take this one?

**Comment by pjcozzi** [comment]
Sure.

The code you'll want to modify is here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/QuadtreePrimitive.js#L458-L465

The example to use is here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/7d449906cf65cf06e75d5cde7bf2dd5921bc95dd/Source/Scene/ModelAnimationCollection.js#L387

Make sure to run all the tests and that they still pass.  See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines

**Comment by kepta** [comment]
I tried changing the code to this,
``` Javascript
  function raiseTileLoadProgressEvent(primitive, frameState) {
        var currentLoadQueueLength = primitive._tileLoadQueue.length;
        if (currentLoadQueueLength !== primitive._lastTileLoadQueueLength) {
          frameState.afterRender.push(function() {
            primitive._tileLoadProgressEvent.raiseEvent(currentLoadQueueLength);
            primitive._lastTileLoadQueueLength = currentLoadQueueLength;
          });
        }
    }
```
However, the test case 
```
Scene/QuadtreePrimitive tileLoadProgressEvent is raised when tile loaded and when new children discovered
TypeError: Cannot read property 'args' of undefined
```
fails, what am I missing ?

**Comment by kepta** [comment]
@pjcozzi a little help here please :)
