### ISSUE TITLE
camera.flyTo not working when in 2D mode and only orientation changes

### ISSUE THREAD

**Issue by Larcius** [AnalyticalGraphicsInc/cesium#3457]
camera.flyTo not working when in 2D mode and destination remains but orientation changes.
I'm quite sure this happens because of line 303-304 in CameraFlightPath:
`var empty = scene.mode === SceneMode.SCENE2D;`
`empty = empty && Cartesian2.equalsEpsilon(camera.position, destination, CesiumMath.EPSILON6);`
`empty = empty && CesiumMath.equalsEpsilon(Math.max(frustum.right - frustum.left, frustum.top - frustum.bottom), destination.z, CesiumMath.EPSILON6);`

**Comment by hpinkos** [comment]
Thanks @Larcius!  That's exactly what's causing the bug.  Are you interested in submitting a bug fix pull request?  We'd be happy to accept it!

Here's a sandcastle example for testing:
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {sceneMode: Cesium.SceneMode.SCENE2D});

Sandcastle.addToolbarButton('Flight1', function() {
    viewer.camera.flyTo({
        destination : Cesium.Cartesian3.fromDegrees(-117, 32, 15000.0),
        orientation: {
            heading: 1
        }
    });
});

Sandcastle.addToolbarButton('Flight2', function() {
    viewer.camera.flyTo({
        destination : Cesium.Cartesian3.fromDegrees(-117, 32, 15000.0),
        orientation: {
            heading: 2
        }
    });
});
```

**Comment by Larcius** [comment]
alright, I'm working on it
