### ISSUE TITLE
Allow Viewer.zoomTo/flyTo to take an ImageryLayer

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3471]
As I mentioned in #3470, now that we have `ImageryLayer.getViewableRectangle`, it should be straightforward to have `Viewer.zoomTo` and `Viewer.flyTo` support `ImageryLayer` instances as a parameter.

**Comment by kepta** [comment]
I want to work on this issue, I speculate that we need to somehow check if zoomTarget is an ImageryLayer right?
