### ISSUE TITLE
Paths to pnts are not anymore relative to tiles.json

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#3483]
With changes of commit c45cc14 point clouds in tiles.json cannot be anymore references relative to tiles.json. Instead paths have to be relative to the directory of current app.

E.g. you have following files:
- cesium/Apps/PointCloud/index.html
- cesium/Apps/PointCloud/data/tiles.json
- cesium/Apps/PointCloud/data/0.pnts

Until revision 04f6b9b you could reference 0.pnts from tiles.json by
`"content":{"url":"1232000.pnts"}`
Since revision c45cc14 you have to write
`"content":{"url":"data/1232000.pnts"}`

because in Cesium3DTileset.js value of this._url is now "data" instead of "data/".

In my opinion old behavior was better, because you could change location of whole data folder without need to adjust tiles.json

**Comment by lilleyse** [comment]
I think the case you mentioned should be fixed in the latest version of 3d-tiles. If it still doesn't work I can look into it more.

**Comment by lilleyse** [comment]
Also `_url` signifies the url that the user gives when creating the dataset, and `_baseUrl` specifies the actual base directory that the tileset.json is contained in (it will have the trailing slash).

**Comment by SunBlack** [comment]
True. I was on latest version and had some trouble with it. Now I stepped all merges into 3dtiles branch  from our last working version into direction of latest version. Now I'm on latest version again and all issues disappeared *confused*
