### ISSUE TITLE
Replace or augment npm strip-comments module

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3485]
We use [strip-comments ](https://www.npmjs.com/package/strip-comments) as part of the build process. Versions `0.4.0` and later no longer work on glsl code (presumably because they switched to using an actual JS parser which obviously can't parse glsl.

We are stuck on `0.3.2` for now and should either find and use a different module, be good Samaritans and support to glsl to `strip-comments`, or simply do something difference for glsl than we do for JS.

**Comment by hpinkos** [comment]
fixed in #4707
