### ISSUE TITLE
Setting CESIUM_BASE_URL without a trailing slash breaks Cesium

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3496]
This took me a while to track down, but apparently if you set `CESIUM_BASE_URL` to a valid value but without a trailing `/` you will no longer get a globe and a bunch of stuff will fail to load.  I assume this can be fixed a the `buildModuleUrl` level.

CC @shunter

**Comment by viraj96** [comment]
Do you want to append / to all places where buildModuleUrl is called.

**Comment by mramato** [comment]
No, `buildModuleUr` needs to be updated to work whether or not a slash present at the end of `CESIUM_BASE_URL`.  You should only have to modify the one file.  The `joinUrls` might be the solution here.
