### ISSUE TITLE
Send 404 error in case of compressed file not exists

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#3508]
Since revision 90fd9f5 you don't get anymore a 404 error in case your browser want to load a tile which not exists. Instead you get always a ERR_CONTENT_DECODING_FAILED (same message occurs in case tile data are not gzip compressed, so you don't see anymore if a tile couldn't be loaded because of tile data are missing or data are not compressed).

I could preorduce this issue with all gzip compressed files (b3dm, pnts, i3dm and cmpt).

**Comment by pjcozzi** [comment]
Thanks we'll look at this as part of #3241.

**Comment by pjcozzi** [comment]
@SunBlack does #3839 work for you?

**Comment by pjcozzi** [comment]
@SunBlack let me know if you run into any issues.

**Comment by SunBlack** [comment]
Well I had now time to test ist. In my opinion removing gzip compression isn't best solution - or isn't there another solution in case file not exists?

**Comment by pjcozzi** [comment]
Tiles can still be served pre-gzipped, we just don't pre-gzip the test data so it is easy for developers to work with.

**Comment by SunBlack** [comment]
My tiles are currently pre-zipped, but because of missing http header not extracted by browser. So maybe an it is possible to add an option to default server implementation, like --port, to enable compression support?

**Comment by pjcozzi** [comment]
That is a good idea that we can consider.  In the meantime, you want to not pre-gzip or add a header like:
```javascript
res.header('Content-Encoding', 'gzip');
```
