### ISSUE TITLE
[Beginner][Bug] BingMapsImageryProvider using incorrect mapStyle (always defaults to AERIAL)

### ISSUE THREAD

**Issue by BGR360** [AnalyticalGraphicsInc/cesium#3514]
I am just beginning to use Cesium for the first time. I tried to create a small script in the HelloWorld.html example app, and it mostly works. However, when I try to change the Imagery from AERIAL to AERIAL_WITH_LABELS, the viewer does not change its imagery style, it keeps the default.

Here is what the documentation says about how to do this:

```javascript
// Instantiating the Viewer with a specific ImageryProvider

var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.ArcGisMapServerImageryProvider({
        url : 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
    }),
    baseLayerPicker : false
});
```

```javascript
// Creating a new BingMapsImageryProvider

var bing = new Cesium.BingMapsImageryProvider({
    url : '//dev.virtualearth.net',
    key : 'get-yours-at-https://www.bingmapsportal.com/',
    mapStyle : Cesium.BingMapsStyle.AERIAL
});
```

Now here's me combining those two methods to create a Viewer with an AERIAL_WITH_LABELS BingMapsImageryProvider:

```javascript
Cesium.BingMapsApi.defaultKey = '<myBingMapsKey>';
var viewer = new Cesium.Viewer('cesiumContainer', {
imageryProvider: new Cesium.BingMapsImageryProvider({
    url: '//dev.virtualearth.net',
    key: Cesium.BingMapsApi.defaultKey,
    mapStyle: Cesium.BingMapsStyle.AERIAL_WITH_LABELS  // This is what's not working
    })
});
```

And I still get a map with the regular aerial imagery, no labels. Is there something I'm doing wrong?

See [this gist](https://gist.github.com/BGR360/dcdf30cf121b614d3b65) for the full HelloWorld.html file. I only modified the code inside the main <script> tag.

More Info:
* OS: OS X El Capitan
* Browser: Google Chrome (latest version, I updated today)
* Cesium version: Latest version (downloaded today) - 1.18

**Comment by shunter** [comment]
`imageryProvider` is only used when `baseLayerPicker` is false, like in your first code snippet. but missing from your final snippet.  

This is mentioned in the doc: http://cesiumjs.org/Cesium/Build/Documentation/Viewer.html and throws an error when using a debug build (recommended when doing development for better error reporting).
