### ISSUE TITLE
Use official NoSleep release when navigator bug is fixed

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3516]
In #3509, I changed our copy of NoSleep.js so that it checks if `navigator` is defined.
I submitted a PR to NoSleep here: https://github.com/richtr/NoSleep.js/pull/13
If/When that gets merged, we should switch back to use the official release

**Comment by yash14123** [comment]
Is it merged already?
I can take this up then . :)

**Comment by hpinkos** [comment]
Nope, no movement on this one yet.

**Comment by pjcozzi** [comment]
The latest version should be fixed now, https://github.com/richtr/NoSleep.js/pull/13
