### ISSUE TITLE
Cardboard VR demo

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#3524]
We need a better VR demo than just the globe. I have an OK one [here](bagnell.github.io/WebVRDemo). It just uses a cut down version of the interpolation Sandcastle example and locks the camera behind the plane. 

Maybe we could create CZML for the moving plane and keep the camera code. I can imagine use cases that people would want the camera code. For example, people could use the code to lock the camera to the cockpit of a plane.

**Comment by mramato** [comment]
@emackey can you get us a fighter jet or similar with a modeled cockpit? We were talking offline and it would be awesome to have the demo be a first-person cockpit view flying around the world, then you would just look out the window.  Should be a trivial amount of code and we can model the flight in STK and export a CZML file.

**Comment by mramato** [comment]
A hot-air balloon would also be cool.

**Comment by emackey** [comment]
![balloonscreenshot](https://cloud.githubusercontent.com/assets/1235080/12895745/ee7f5660-ce6b-11e5-9fba-6a8b5c83456f.jpg)

**Comment by mramato** [comment]
:+1: We can always count on you @emackey!

**Comment by hpinkos** [comment]
@emackey that looks awesome!

**Comment by pjcozzi** [comment]
@emackey absolutely love the new model!

Can you also donate this to the [glTF sample models](https://github.com/KhronosGroup/glTF/blob/master/sampleModels/README.md)?

**Comment by mramato** [comment]
Random idea: In addition to the balloon the webVR user is riding in, have a handful of other balloons dotted around the sky to give a sense of scale and show things in the air, otherwise looking down is the only option.

**Comment by pjcozzi** [comment]
@bagnell you still want to keep this open?
