### ISSUE TITLE
Add length property to Matrix classes to make them fully Array-like

### ISSUE THREAD

**Issue by speigg** [AnalyticalGraphicsInc/cesium#3536]
This allows Matrix objects to be used as arrays in APIs that expect an array-like object. 

For example, adding a length with the value of 16 to the Matrix4 class would allow a TypedArray to be set directly from a Matrix4 instance:

```
var matrix4 = new Cesium.Matrix4();
var typedArray = new Uint32Array(16);
typedArray.set(matrix4);
```

Without a length property, the above silently fails. With a length property, it works as expected. 

Proposal summary, add these properties:

```
Matrix2.prototype.length = 4;
Matrix3.prototype.length = 9;
Matrix4.prototype.length = 16;
```

**Comment by pjcozzi** [comment]
Thanks for the idea, @speigg!

This is OK with me.  Good beginner issue.  Any other thoughts?

**Comment by viraj96** [comment]
So we just need to add length properties to their respective .js files only. Or should we something else.

**Comment by pjcozzi** [comment]
Yes, we would add a length like this: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/AssociativeArray.js#L30-L34

And also add tests: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/TestingGuide/README.md

And update CHANGES.md

**Comment by hpinkos** [comment]
@speigg this was added in #3579 and will be available in the next release
