### ISSUE TITLE
Geocoder doesn't respect minimumZoomDistance

### ISSUE THREAD

**Issue by theplatapi** [AnalyticalGraphicsInc/cesium#3549]
When searching for a location, it will zoom in as far as it needs to without checking the ScreenSpaceCameraController's minimumZoomDistance field. Trying to zoom from there makes it jump to a zoomed out position. Also it takes a lot of scrolling to zoom out after the jump.

Sandcastle example below. Try searching for "Butlers Gorge" for an example.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.scene.screenSpaceCameraController.minimumZoomDistance = 100100;
```

**Comment by hpinkos** [comment]
Thanks @theplatapi!

**Comment by theplatapi** [comment]
I can try fixing it, since I need it this working relatively soon. Should I take the initiative or is someone already making progress on this?

**Comment by mramato** [comment]
@theplatapi No one is actively working on this and we love pull requests, so go for it.  Just be sure to check out [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md) for guidelines for contributing.  You'll need to email us a filled out CLA in order for us to accept the contribution.

Thanks in advance!

**Comment by theplatapi** [comment]
I'll take a look at it and see if I can put something together.
