### ISSUE TITLE
A couple minor edits to the Visualizing-Spatial-Data tutorial

### ISSUE THREAD

**Issue by mjturtora** [AnalyticalGraphicsInc/cesium#3586]
I've been working through the subject tutorial (http://cesiumjs.org/tutorials/Visualizing-Spatial-Data/
) and have had a few problems with the instructions. I've found solutions to a couple of them that could be solved with some simple edits to the doc (and no doubt avoid considerable frustration for newbies).

**Entity description introduction**

The Entity.description code block after this text: 

> Going back to our original example, we only supplied the wyoming entity with a name, which determines the title of the InfoBox, but we can also provide additional data in HTML via the Entity.description property. Let’s add the below block of code to the end of the first example.

Results in an error when copy/pasted into sandcastle because of the lack of continuation lines (everything between the single quotes). I get an error in sandcastle at the line:

`wyoming.description = '`

...because of the lone single quote on that line.  I solved that by adding a backslash continuation character to every line of the description (although this may not be best practice in js, it did the trick).

**collectionChanged Event introduction**

The function onChanged in the code block below this text...

> To see this in action, let’s use the Geometry Showcase example in Sandcastle. Copy and paste the below code near the top, immediately after the viewer is created.

does not print anything in the console. Adding a console.log statement in the for loop as suggested in the below post solves the problem:

`console.log(msg);`

To give credit where credit is due, I found this solution in this forum post:
http://cesiumjs.org/forum.html#!msg/cesium-dev/dawqCDi4Ef0/Xvu555iZJoYJ

Well, that link doesn't seem to work but you can find the post by searching the forum for:
`collectionChanged.addEventListener(onChanged)`
...it's the only thread that comes up.

**Comment by hpinkos** [comment]
Thanks for the feedback @mjturtora!  We'll work on updating that tutorial.

**Comment by yash14123** [comment]
Is it open? 
I would like to work on this,

**Comment by hpinkos** [comment]
Thanks @yash14123, but this something we have to update on our website and only certain people have access to that.
Take a look at some of our [beginner issues](https://github.com/AnalyticalGraphicsInc/cesium/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner) and see if you would like to do any of those =)

**Comment by rahwang** [comment]
Looks like these problems were resolved in the tutorial by @hpinkos 

Should this issue be closed?

**Comment by hpinkos** [comment]
Yep, it looks like these are fixed.  Thanks for looking at it @rahwang!

And thanks for all the suggestions @mjturtora!
