### ISSUE TITLE
Issue and Pull Request templates

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3596]
https://github.com/blog/2111-issue-and-pull-request-templates

Will check this out for making the guidelines more prominent.

**Comment by yash14123** [comment]
I would like to take this up.
Please assign me this.

**Comment by pjcozzi** [comment]
Thanks for the offer, @yash14123, but I plan to do this one to keep our messaging consistent.

**Comment by pjcozzi** [comment]
We're not moving forward with this for now as discussed in #3637.
