### ISSUE TITLE
Weird tile loading for exaggerated terrain introduced in 1.18

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3607]
![image](https://cloud.githubusercontent.com/assets/3451886/13185000/fc5e9242-d70c-11e5-8d95-16352293b94b.png)

If you open the [terrain exaggeration](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain%20Exaggeration.html&label=Showcases) example and zoom in and rotate around you'll see random floating flat tiles.
It seems to be related to them being too close to the camera.  If you zoom out, the tiles become part of the terrain

I'm marking this as next release because it makes exaggerated height unusable.  The demo is really broken.

![image](https://cloud.githubusercontent.com/assets/3451886/13185213/f02ff064-d70d-11e5-8408-19acfaaf1ab8.png)
![image](https://cloud.githubusercontent.com/assets/3451886/13185217/f2b9baae-d70d-11e5-9327-c40dbfb309d0.png)

**Comment by hpinkos** [comment]
related issue reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/tYvyat8e090

**Comment by pjcozzi** [comment]
> I'm marking this as next release because it makes exaggerated height unusable. The demo is really broken.

Agreed.  @bagnell can you please look at this?

**Comment by pierotofy** [comment]
Confirm, I had the same issue.

**Comment by lilleyse** [comment]
All I can say here is the problem was introduced in 50938745833342b208fb0b1c5eec921bc092f607

**Comment by mramato** [comment]
Given the circumstances, I'm okay with pushing this to the next release.  Leave the `next release` tag though so we don't forget.

**Comment by mramato** [comment]
Reported again via #3676

**Comment by pjcozzi** [comment]
@hpinkos can you comment on the forum thread and let them know this will be fixed in 1.20?
