### ISSUE TITLE
3D Tiles Sandcastle example has mouse issues in IE 11

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3614]
Obviously not a big deal until we are ready to bring 3d-tiles into master, but I wanted to submit this before I forget.

The mouse doesn't behave as expected when running the 3D Tiles Sandcastle example in IE11.  Panning and rotation are wildly inaccurate.  Running the demo in Chrome works fine.  It looks like other examples work fine in the 3d-tiles branch, so maybe it's something specific to the new example.

**Comment by bicealyh** [comment]
The master branch also has the same problem.  The mouse wheel does not respond In IE11.

**Comment by mramato** [comment]
@bicealyh you are correct, but the two are unrelated.  This mouse wheel is actually a much bigger issue since it's broken in master.  I submitted #3643 for us to fix this before the next release.  Thanks for the heads up.

**Comment by pjcozzi** [comment]
@TomPed would you like to try this one when you are available?

**Comment by TomPed** [comment]
I'm trying to load the sandcastle example and I am getting an error:
```
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Object doesn't support property or method 'fill'
TypeError: Object doesn't support property or method 'fill'
```

**Comment by TomPed** [comment]
I will try thing on another computer later today on IE 11.

**Comment by TomPed** [comment]
This is the support for the `fill` method for Internet Explorer.

![ieisbad](https://cloud.githubusercontent.com/assets/11602092/15585192/31ff847a-234c-11e6-8ef7-9a64f6627909.JPG)

[`TypedArray.prototype.fill()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill)

**Comment by mramato** [comment]
Up to @lilleyse and @pjcozzi, but if we think this will affect performance, we can write a helper function that calls `fill` if it's defined and falls back to iteration if it's not.

**Comment by pjcozzi** [comment]
@mramato's approach is fine.  Look in the file history; we just added `fill` so we were basically using the fallback beforehand.

**Comment by TomPed** [comment]
> Panning and rotation are wildly inaccurate.

@mramato when you say this, are you referring to the granularity of the panning and rotation, or when you go to pan and rotate, sometimes, no movement occurs. The latter is what I see.

**Comment by mramato** [comment]
@JoshuaStorm can you take a look at this?  Create a new private function in Core called `arrayFill`, which uses the polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill, but instead of patching the prototype, have the function take the array as the first parameter.  You'll also want to clean up the formatting and error checks to match our conventions as well as add specs.

In order to take advantage of fill on browsers that do support it, in `arrayFill` check if `Array.prototype.fill` exists first and if it does just us that instead.  See `getTimestamp` for a simple example of setting this up.

Then you can update `Cesium3DTileBatchTableResource.js` and replace the calls to `fill` with the new function and verify it works in all browsers.

**Comment by JoshuaStorm** [comment]
@mramato I cannot seem to find `Cesium3DTileBatchTableResources.js` in this repo. Am I missing something?

**Comment by mramato** [comment]
This needs to be done in a branch off of `3d-tiles`

**Comment by JoshuaStorm** [comment]
Makes sense, figured I was forgetting something like that.

**Comment by mramato** [comment]
There still seem to be several issues in the IE11 3D Tiles demo, but I'll try and write up more specific issues in place of this current one.
