### ISSUE TITLE
can glow the point like PolylineGlowMaterialProperty, make the point like lightup

### ISSUE THREAD

**Issue by haisapan** [AnalyticalGraphicsInc/cesium#3630]
I need one feature is make the point lightup, like the PolylineGlowMaterialProperty. But I haven't found how to implement it, the PolylineGlowMaterialProperty is only for polyline.

Can I use like this:
pointer.material = new Cesium.PolylineGlowMaterialProperty({
	glowPower : 0.2,
	color : Cesium.Color.BLUE
 });

or use some linear color?

**Comment by hpinkos** [comment]
Hello @haisapan,

This functionality is not available for points.
Please ask questions like this in our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
You will get a better response.

Thank you!
