### ISSUE TITLE
Add option to Cesium3DTileset to set custom appearance

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#3639]
Currently it seems not to be possible to to change appearance of a PointCloud. There exists already a PointAppearance but this will be always set fixed in Points3DTileContent and it is not possible to pass parameter to this appearance. But we need ability to attach other shaders to a PointCloud and to modify point size (PointAppearance provide an option to modify point sze, but I didn't found a way to access PointAppearance from an app)

**Comment by pjcozzi** [comment]
Thanks for the input.  Have you seen the declarative styling work-in-progress for 3D Tiles: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2

What are you going to base point size on?  One of the point's attributes, e.g., temperature, etc.?

Also, have you already built a project on 3D Tiles?  If so, let me know - https://groups.google.com/forum/#!topic/cesium-dev/2NlWw_vqVVs

**Comment by SunBlack** [comment]
Currently we just need point size to increase general appearance. E.g. if you are really far zoomed in you have a point each 20px. If a pixel is just 2px you don't really see them good. Another nice effect of increased pixel size: You can decrease number of necessary loaded points. E.g. if you have a 4K Display you  need 1920*1080 points with a size of 2 pixel to fulfill screen. Each point currently needs 15 Bytes - so you already have to load a ~30 MB (with gzip ~26,5MB) Point cloud to hide terrain beyond it. With a pixel size of 4 Pixels you need only 7,5MB. But indeed to adjust fixed point is just a possibility to increase visual appearance. A better idea is an adaptive point size (see examples of Potree)

@declarative style: Didn't saw it until, but not sure if it makes sense on point clouds. It's a good idea for 3D Models, but with point clouds you have massive data, so you need to calculate all important things in a shader instead of with CPU. So for us it is just important to have ability to use different shaders to render a point cloud in different styles. Just take a look on examples of Potree to see what a user could do.

**Comment by pjcozzi** [comment]
The base implementation of point clouds will have adaptive point size based on distance, and hopefully occlusion culling based on that.

For declarative styles, when used with point clouds, I expect that we will generate GLSL from the AST so everything will be done in a shader, see https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2

>  * [ ] GPU implementation for tile formats that would really benefit, e.g., point clouds

**Comment by pjcozzi** [comment]
Declarative styling is now implemented for point clouds; it is possible to set the point size.
