### ISSUE TITLE
Mouse wheel broken in IE11

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3643]
The mouse wheel works on the website, but is broken in master.  Just run any Cesium demo or Viewer.

**Comment by mramato** [comment]
@bagnell can you take a look at this on Monday?  If not, I can try and figure out what's going on.

**Comment by bicealyh** [comment]
In the 103 line of core/ScreenSpaceEventHandler.js, by increasing the IE11 judgment can solve this problem. For example:

      // detect available wheel event
        var wheelEvent;
        if ('onwheel' in element) {
            // spec event type
            wheelEvent = 'wheel';
        } else if (defined(document.onmousewheel) || (/Trident\/7\./).test(navigator.userAgent)) {	  //IE11
            // legacy event type
            wheelEvent = 'mousewheel';
        } else {
            // older Firefox
            wheelEvent = 'DOMMouseScroll';
        }

**Comment by lilleyse** [comment]
The mouse wheel functionality was broken in https://github.com/AnalyticalGraphicsInc/cesium/commit/a094c4ad00af91c7c11d46779338369cfc2e582d. `document.onmousewheel` is null, so the following code also works.
```javascript
        // detect available wheel event
        var wheelEvent;
        if ('onwheel' in element) {
            // spec event type
            wheelEvent = 'wheel';
        } else if (document.onmousewheel !== undefined) {
            // legacy event type
            wheelEvent = 'mousewheel';
        } else {
            // older Firefox
            wheelEvent = 'DOMMouseScroll';
        }
```
