### ISSUE TITLE
GroundPrimitive and PolygonOutlineGeometry

### ISSUE THREAD

**Issue by gberaudo** [AnalyticalGraphicsInc/cesium#3656]
When using a ground primitive with a polygon outline geometry, Cesium used to skip rendering the primitive. In master it now freezes the globe due to a geometry instance beeing undefined.

The issue only occurs with the new `geometryInstances` property, and not with the deprecated `geometryInstance`. Indeed, with the following sandcastle snippet, the `groundInstances` array
created in `GroundPrimitive.prototype.update` is `[undefined]`.

```

var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;
scene.terrainProvider = new Cesium.CesiumTerrainProvider({
    url: '//assets.agi.com/stk-terrain/world'
});



var positions = [new Cesium.Cartesian3(-2358138.847340281, -3744072.459541374, 4581158.5714175375),
                    new Cesium.Cartesian3(-2357231.4925370603, -3745103.7886602185, 4580702.9757762635),
                    new Cesium.Cartesian3(-2355912.902205431, -3744249.029778454, 4582402.154378103),
                    new Cesium.Cartesian3(-2357208.0209552636, -3743553.4420488174, 4581961.863286629)];
var polygonHierarchy = { positions : positions };

var color = Cesium.Color.RED;

scene.groundPrimitives.add(new Cesium.GroundPrimitive({
    geometryInstances : new Cesium.GeometryInstance({
        geometry : new Cesium.PolygonOutlineGeometry({
            polygonHierarchy : polygonHierarchy
        }),
        attributes: {
            color: Cesium.ColorGeometryInstanceAttribute.fromColor(color)
        },
        id : 'polygon 1'
    })
}));

viewer.camera.lookAt(new Cesium.Cartesian3(-2354331.3069306486, -3742016.2427205616, 4581875.591571755), new Cesium.HeadingPitchRange(Cesium.Math.toRadians(20.0), Cesium.Math.toRadians(-35.0), 10000.0));
viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
```

The simplest solution seems to use `[]` instead of `new Array(length)` and push to make the array grow.
See https://github.com/AnalyticalGraphicsInc/cesium/blob/2cf0e06fb4ea4f9af950895c5628edeae7b872a6/Source/Scene/GroundPrimitive.js#L863. Is it an acceptable fix?

Update: changed `PolygonGeometry` to `PolygonOutlineGeometry`

**Comment by hpinkos** [comment]
Hello @gberaudo,
I'm a little confused about the problem you're seeing.  Did you mean to say polygon outline geometry?  In your example, you're using a `PolygonGeometry`, and `PolygonOutlineGeometry` isn't yet supported by `GroundPrimitive`.

What version of Cesium are you using?  Your example ran fine for me in Sandcastle with Cesium 1.19, which was released yesterday.  If you look at the code, `GroundPrimitive.prototype.update` will `return` if both `geometryInstance` and `geometryInstances` are `undefined`: https://github.com/AnalyticalGraphicsInc/cesium/blob/2cf0e06fb4ea4f9af950895c5628edeae7b872a6/Source/Scene/GroundPrimitive.js#L827

Thanks

**Comment by gberaudo** [comment]
Sorry for the confusion, the sandcastle example should indeed use `PolygonOutlineGeometry`. Updating it. I tested commit 2cf0e06fb4ea4f9af950895c5628edeae7b872a6 from yesterday.

This example is artificial, for simplification. In OL3-Cesium, [the code creating the GroundPrimitive with the geometry instances](https://github.com/openlayers/ol3-cesium/blob/a3e7a3baf9f884550801a9f50995f844d4c4e740/src/featureconverter.js#L130) is generics. It used to "work" in previous versions of Cesium: the unsupported primitives were skipped but other primitives rendered.

@hpinkos, does it clarify?

**Comment by hpinkos** [comment]
Great, thanks @gberaudo.
I put in a fix here #3659

**Comment by hpinkos** [comment]
@gberaudo, We actually decided the best solution was to throw a `DeveloperError` if the `GroundPrimitive` doesn't support the primitive type.  You should be sending your outline geometry types to `new Primitive` instead.
Thanks for bringing this up!

**Comment by gberaudo** [comment]
Thanks @hpinkos for the follow up and advice.
