### ISSUE TITLE
Timeline.zoomTo needle position

### ISSUE THREAD

**Issue by lRawd** [AnalyticalGraphicsInc/cesium#3664]
`var startTime = new Cesium.JulianDate(1721425, 43210);`
`var stopTime = new Cesium.JulianDate(1721426, 11258);`
`viewer.timeline.zoomTo(startTime, stopTime);`

This causes the timeline needle to have an enormous left offset (left: 2.81476e+08px;) and in turn causes rendering issues for other html elements (ex. cesium-viewer-fullscreenContainer).

**Comment by emackey** [comment]
In the future, please use [our forum](https://groups.google.com/forum/#!forum/cesium-dev) for questions.  Thanks!

```
var viewer = new Cesium.Viewer('cesiumContainer');

var startTime = new Cesium.JulianDate(1721425, 43210);
var stopTime = new Cesium.JulianDate(1721426, 11258);
viewer.clock.startTime = startTime;
viewer.clock.stopTime = stopTime;
viewer.clock.currentTime = startTime;
viewer.timeline.updateFromClock();
viewer.timeline.zoomTo(startTime, stopTime);
```

**Comment by lRawd** [comment]
It wasn't really a question. The Timeline documentation doesn't specify that the needle position will be based on the current time, I assumed it was supposed to be the start time passed in. When I saw the large offset and the rendering issues it was causing, it seemed like a bug.

Also, Timeline.updateFromClock isn't listed in the API documentation and is marked as private in the source code.

**Comment by hpinkos** [comment]
Thanks @lRawd 
We have an issue open for refactoring the timeline and improving the documentation here: #754
I'll link your issue so whoever updates the timeline widget makes sure this is addressed.
