### ISSUE TITLE
Tilt map scroll wheel zoom in, sometimes jump

### ISSUE THREAD

**Issue by bicealyh** [AnalyticalGraphicsInc/cesium#3672]
In the eastern hemisphere with terrain data, when  tilt the map， and then  scroll wheel zoom in, it will jump sometimes.

**Comment by hpinkos** [comment]
Hi @bicealyh.  Can you please provide some more details?  I'm not able to reproduce this problem.
Thanks!

**Comment by hpinkos** [comment]
I think this is a duplicate of #3037.  If not, feel free to comment with more information so we can look into this.  Thanks!
