### ISSUE TITLE
Failing tests in 3d-tiles

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3694]
From #3689

`Cesium3DTilesetSpec: handles failed tile requests` is failing, which causes a lot of other tests to fail because it is clogging the `RequestScheduler`. As an aside it would be nice to be able to reset the `RequestScheduler` before every test so this type of thing doesn't happen, but I'm not sure what the best way to do this is.

For the failing test, the request fails (gets a 404 message) but the promise is not rejected. None of the `deferred.reject` lines are called in `loadWithXhr`. This happens now that `server.js` serves all tiles as gzipped. Is some strange interaction going on where the error is thrown in the server code and never reaches `loadWithXhr`?

**Comment by lilleyse** [comment]
Also it works on Firefox and IE.

**Comment by pjcozzi** [comment]
When did this start failing?  Was it a Cesium change or Chrome update?

**Comment by lilleyse** [comment]
It passes in Chrome Canary as well, so this may be caused by a Chrome update.

**Comment by mramato** [comment]
It seems to fail in the last version of Chrome too (48).  So I'm not sure it's a problem that started with 49.  `handles failed tile requests` also passes if run standalone; so my assumption is there is a race condition in our code somewhere, most likely having to do with RequestScheduler.

**Comment by lilleyse** [comment]
It doesn't pass standalone for me with 49.

**Comment by mramato** [comment]
> It doesn't pass standalone for me with 49.

Apparently it doesn't for me either, but it does pass in Chrome 48 standalone (when run via WebStorm with Electron).  But fails in 48 when run altogether.  If you guys really think it's a Chrome bug, then I guess we can ignore it on Chrome until 50 is released, but I'm still suspicious it's a race condition on our end somewhere.

**Comment by lilleyse** [comment]
Just doing a more basic test here. The error is not printed. When I restart the server with gzip off for b3dm, it does print the error.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var url = 'invalid.b3dm';
Cesium.loadArrayBuffer(url).then(function(arrayBuffer) {
    var uint8Array = new Uint8Array(arrayBuffer);
    var magic = Cesium.getMagic(uint8Array);
    console.log(magic);
}).otherwise(function(error) {
    console.log(error);
});
```
