### ISSUE TITLE
Imagery Provider Urls

### ISSUE THREAD

**Issue by TomPed** [AnalyticalGraphicsInc/cesium#3705]
Is there a reason why imagery urls don't specify `http` or `file`:

```javascript
url : '//cesiumjs.org/smallTerrain'
```

vs.

```javascript
url : 'http://cesiumjs.org/smallTerrain'
```

I'm only asking because [Electron](http://electron.atom.io/) has an issue where it can't find the imagery providers unless `http` is specified.

Urls also in the terrain and geocoding cause issues too.

**Comment by TomPed** [comment]
Seems like there is already a issue for this #3650. I'll close this.

**Comment by pjcozzi** [comment]
@TomPed you are welcome to work on #3650.
