### ISSUE TITLE
arcgis layers

### ISSUE THREAD

**Issue by MannusEtten** [AnalyticalGraphicsInc/cesium#3719]
there is support for arcgis layers (ArcGisMapServerImageryProvider)

i can define that it has to use precached tiles but an Esri ArcGIS Mapservice.
How about the Esri ArcGIS ImageServices? Can I use those with the same provider?

**Comment by hpinkos** [comment]
Hello @MannusEtten 

I'm not that familiar with ArcGIS ImageServices.  You can try using `ArcGisMapServerImageryProvider`, and if that doesn't work you might be able to use the [UrlTemplateImageryProvider](http://cesiumjs.org/Cesium/Build/Documentation/UrlTemplateImageryProvider.html).

If you need further help, please use our forum to post a question: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
There might be someone with experience using ImageServices that will see your post there and be able to better help you out.

Best,

Hannah
