### ISSUE TITLE
Clean up procedural GLSL concatenation

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3721]
There's a lot of code like:
```javascript
        var showMain =
            'attribute float show;\n' +
            'void main() \n' +
            '{ \n' +
            '    czm_non_show_main(); \n' +
            '    gl_Position *= show; \n' +
            '}';
```
We could introduce a simple helper to clean up the line breaks and concatenation:
```javascript
        var showMain = ShaderSource.concatenate([
            'attribute float show;',
            'void main()',
            '{',
            '    czm_non_show_main();',
            '    gl_Position *= show;',
            '}']);
```

**Comment by mramato** [comment]
Another option would be to use string literals, which require a trailing slash, but can be edited as a single block and is already what we do for HTML in the widgets:

```javascript
        var showMain = '\
            attribute float show;\
            void main()\
            {\
                czm_non_show_main();\
                gl_Position *= show;\
            }');
```

You can also have WebStorm syntax highlight the entire block if you do it this way:

![image](https://cloud.githubusercontent.com/assets/1495196/13860610/aaa14c0c-ec5f-11e5-9dfa-0bc5adf74db1.png)

I'm fine with whatever you want, I just wanted to mention the third option.

**Comment by pjcozzi** [comment]
That is pretty.  We'll start with that.

**Comment by lasalvavida** [comment]
I'll look to see if it's really an issue, but as per [the google style guide](https://google.github.io/styleguide/javascriptguide.xml?showone=Multiline_string_literals#Multiline_string_literals) 

Do not do this:

var myString = 'A rather long string of English text, an error message \
                actually that just keeps going and going -- an error \
                message to make the Energizer bunny blush (right through \
                those Schwarzenegger shades)! Where was I? Oh yes, \
                you\'ve got an error and all the extraneous whitespace is \
                just gravy.  Have a nice day.';
The whitespace at the beginning of each line can't be safely stripped at compile time; whitespace after the slash will result in tricky errors; and while most script engines support this, it is not part of ECMAScript.

Use string concatenation instead:

var myString = 'A rather long string of English text, an error message ' +
    'actually that just keeps going and going -- an error ' +
    'message to make the Energizer bunny blush (right through ' +
    'those Schwarzenegger shades)! Where was I? Oh yes, ' +
    'you\'ve got an error and all the extraneous whitespace is ' +
    'just gravy.  Have a nice day.';

**Comment by lasalvavida** [comment]
It seems like the preferred way of doing this was added in ECMAScript 6: [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

![multi-line-literal](https://cloud.githubusercontent.com/assets/2489570/13952521/37765888-f00d-11e5-9f3b-1b2e2dda77fd.JPG)

**Comment by mramato** [comment]
@lasalvavida we do not follow the google style guide and that link is incorrect and out of date.  Strings with escaped line endings are officially part of ES5 and we already use them throughout the Cesium code base.  For this use case, the only valid point that doc makes it the whitespace issue, which is easily addressed by left aligning glsl (which I believe we already do for HTML in similar situations):

```javascript
        var showMain = '\
attribute float show;\
void main()\
{\
    czm_non_show_main();\
    gl_Position *= show;\
}');
```

While I agree that template literals are useful, we will not be able to use ES6 in Cesium until all major browsers in use add support.

**Comment by mramato** [comment]
@lasalvavida, one last thing.  When we update the string, also add `//language="glsl"` on the line immediately before it.  This will cause WebStorm to detect that it is glsl and will provide syntax highlighting and code completion support (if the glsl plugin is installed).  Thanks

**Comment by lasalvavida** [comment]
@mramato, there are some places with variables concatenated into the shaders as in:

```javascript
    computeFunctions += functionName + '\n' +
                        '{\n' +
                        '    return czm_translateRelativeToEye(' + name + '3DHigh, ' + name + '3DLow);\n' +
                        '}\n\n';
```

Do you think it would make sense to implement something like [this](http://stackoverflow.com/posts/18234317/revisions)?

```javascript
    computeFunctions += '\
{functionName}\
{\
    return czm_translateRelativeToEye({name}3DHigh, {name}3DLow);\
}'.format({functionName:'foo', name:'bar'});
```

**Comment by mramato** [comment]
Up to @pjcozzi on how he wants to handle these, the simple thing to do would be use string literals and just leave this code largely as-is.

Otherwise, since `.format` is not a method on string, so we would probably use the existing `sprintf` function we have in Cesium that does traditional c-style %s string replacement.

**Comment by lasalvavida** [comment]
@mramato I included a link in my comment to a fairly simple string prototype modification to add the format method. If we were going to do this, you would need named arguments. In my example, 'name' is only used twice, but there are others with many repetitions that would make those sprintf functions look really nasty.

**Comment by mramato** [comment]
One of the fundamental rules of Cesium is that we never modify standard object prototypes or otherwise pollute the global namespace.  As a developer library we have to be very careful not to make decisions for our users or otherwise do things that can potentially conflict with their own code.  So modifying the prototype is not an option.

**Comment by lasalvavida** [comment]
@mramato Is there an appropriate 'utilities' type namespace where we could put it then?

**Comment by mramato** [comment]
Wait and see what @pjcozzi thinks.  Unless this type of thing is all over the place, just keeping it largely as is probably the easier choice, otherwise you would add a helper function on `ShaderSource`.

**Comment by pjcozzi** [comment]
> Up to @pjcozzi on how he wants to handle these, the simple thing to do would be use string literals and just leave this code largely as-is.

Yes, I would keep those cases as is, or they would work with what I originally proposed: https://github.com/AnalyticalGraphicsInc/cesium/issues/3721#issue-141697795

Please keep in mind the overall goal: to make writing inline shaders slightly less cumbersome.  It is minor, but managing the `\n` and `+` now is OK, but could just be a bit easier.  This isn't a huge problem and we don't need to over solve it.

**Comment by lasalvavida** [comment]
@pjcozzi, what about this? 

```javascript
var tempFunction =
//language="glsl"
'\
vec4 __FUNCTION__(){\
    vec4 p;\
    if (czm_morphTime == 1.0)\
    {\
        p = csm_translateRelativeToEye(__NAME__3DHigh, __NAME__3DLow);\
    }\
    else if (csm_morphTime == 0.0)\
    {\
        p = czm_translateRelativeToEye(__NAME__2Dhigh.zxy, __NAME__2DLow.zxy);\
    }\
    else\
    {\
        p = csm_columbusViewMorph(\
            czm_translateRelativeToEye(__NAME__2DHigh.zxy, __NAME__2DLow.zxy),\
            czm_translateRelativeToEye(__NAME__3DHigh, __NAME__3DLow),\
            czm_morphTime);\
    }\
    return p;\
}';
                    tempFunction = tempFunction.replace(
                        /__FUNCTION__/g, 'czm_compute').replace(
                        /__NAME__/g, match[1]
                    );
                    computeFunctions += tempFunction;
```

It doesn't require any crazy modifications and it works perfectly with the WebStorm GLSL extension.

**Comment by pjcozzi** [comment]
I would just leave these cases as is or do what I originally suggested throughout.  The point here is to make GLSL easier to author and read, no need to introduce anything too complex.

Please work with @lilleyse on this. @mramato and I are focused on other things.

**Comment by pjcozzi** [comment]
What's the plan here?  Are we still interested in this?  Do we want to pass?  Or use the original suggestion?

**Comment by lilleyse** [comment]
My take away is that most of the shader code doesn't benefit from the cleanup approaches here because it is often too intertwined with if statements and variables. I think the original suggestion is good for certain cases, but may not be worth the effort. The string literal approach makes the code less readable to me because it is left justified. I think we should pass on this, even though @lasalvavida did a good job in the pull request.

**Comment by pjcozzi** [comment]
OK with me.  @lasalvavida what do you think?

**Comment by lasalvavida** [comment]
I generally advocate for consistency. I don't like that we would have it one way in some places and another in others.

I think that a more template-style approach like the one in my last suggestion is probably the most readable (also the only one that really works with syntax highlighting), but that would be a more significant refactoring.

**Comment by pjcozzi** [comment]
We have bigger fish to fry and this is a minor inconvenience at most so let's pass, and reevaluate later if needed.
