### ISSUE TITLE
Polylines look incorrect when transitioning from 3D to 2D

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3729]
This is an example of what you see if you changing the path widths to 10 in `simple.czml` and transition from 3D to 2D.  You can see the ends of the lines disappear during the transition.  From certain views, there are just pointy sections instead of a large chunk of the line disappearing.

![polylines](https://cloud.githubusercontent.com/assets/3451886/13892520/4e8cc08e-ed2e-11e5-9c22-5db9b29b8562.gif)

**Comment by mramato** [comment]
I just made a comment in the other PR, but I think this might just be a dupe of #1593

**Comment by bagnell** [comment]
I think this was fixed by #3768 like #1593. At least the missing part of the line was. I don't see any of the pointy sections din the description. @hpinkos Can you still reproduce this?

**Comment by hpinkos** [comment]
yep, looks like it's fixed
