### ISSUE TITLE
npm run test doesn't run the tests?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3732]
Perhaps I am just not setup, right?

Following the [guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide#run-all-tests-on-the-command-line-with-karma):
```
$ npm run test

> cesium@1.19.0 test c:\source\cesium
> gulp test

[12:29:18] Using gulpfile c:\source\cesium\gulpfile.js
[12:29:18] Starting 'test'...
21 03 2016 12:29:18.652:INFO [framework.detect-browsers]: Detecting browsers is
disabled. The browsers of the browsers array are used.
21 03 2016 12:29:18.942:INFO [karma]: Karma v0.13.21 server started at http://lo
calhost:9876/
```
If extra setup is needed, we should add it to the testing guide.

`npm run test-all` also appears to just hang.

This works:
```
npm run test -- --browsers Firefox,Chrome
```

**Comment by mramato** [comment]
I apparently broke this with #3658.  Fix is trivial, I'll open a PR shortly.
