### ISSUE TITLE
 Removing Animation Widget?

### ISSUE THREAD

**Issue by tomasregina** [AnalyticalGraphicsInc/cesium#3745]
Hi,
I'm starting using Cesium and I woud like to remove animation widget from my map window. I know I have to use destroy() method, but I'm not sure where should I add it in my code or how should I call it. I attached screenshots how my code looks and how destroy() methods looks :). I know its kinda silly question, but I'm little bit helpless... Thank you very much! 
<img width="744" alt="destroy" src="https://cloud.githubusercontent.com/assets/17382889/13951917/df548464-f033-11e5-8bd3-256314915e02.png">
<img width="746" alt="my_code" src="https://cloud.githubusercontent.com/assets/17382889/13951918/df7da45c-f033-11e5-905e-e0bd4239e670.png">

**Comment by hpinkos** [comment]
Hello @tomasregina 
You can tell the Viewer which widgets to include when you initialize it.  See the reference documentation here: http://cesiumjs.org/Cesium/Build/Documentation/Viewer.html

Also, in the future, please use our [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev) to ask questions.   Thanks!
