### ISSUE TITLE
Large missing section of primitive when switching from 3D to Columbus View

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3748]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/5A1-br_4iu4

The first example is 3D -> CV
![artifact](https://cloud.githubusercontent.com/assets/3451886/13956920/f9fb8938-f020-11e5-891e-9ed7eb1c714a.gif)

The second example is 2D -> 3D -> CV
![artifact2](https://cloud.githubusercontent.com/assets/3451886/13956921/fb4de5ec-f020-11e5-9284-ad1fe0f5673c.gif)

As far as I can tell, this was introduced in 1.17
Run this example, and change the scene mode to 3D and then to CV.  Then tilt the map to see the artifact.
```
var viewer = new Cesium.Viewer('cesiumContainer', {sceneMode: Cesium.SceneMode.SCENE2D});

viewer.entities.add({
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-170.0, -80.0, 170.0, 90.0),
        material : Cesium.Color.YELLOW.withAlpha(0.5),
    }
});
```

**Comment by hpinkos** [comment]
@pjcozzi would you consider this a show stopper?

**Comment by pjcozzi** [comment]
I can confirm this was introduced in 1.17.  It can also be reproduced by running the following example and switching to CV:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-170.0, -80.0, 170.0, 90.0),
        material : Cesium.Color.YELLOW.withAlpha(0.5),
    }
});
```
@bagnell and I are working on too many other pressing things to look at this in detail right now.

**Comment by pjcozzi** [comment]
I think the same problem can be seen with labels in 2D in the Picking Sandcastle example:

![ok](https://cloud.githubusercontent.com/assets/782098/14004676/34a3c714-f132-11e5-86f9-7489acdb01e1.gif)

**Comment by santilland** [comment]
Hi, so i really wanted to have a solution for this so i went hunting a little bit. The issue was introduced in commit #62c63bc058d8014b1498d5c03f211450028b97f2 
I cant quite figure out what happened, because from what i see it is just renaming and separating the updatePrimitives funtion into two functions (updatePrimitives and updateEnvironment).
In any case the clipping issue has to do with the useDepthPlane.
If you remove the if statement in line 1604 of Scene.js (https://github.com/AnalyticalGraphicsInc/cesium/commit/62c63bc058d8014b1498d5c03f211450028b97f2#diff-fb63af82386df4a707d9fcfb196c35fcR1604) everything seems to work as expected.
If scene._depthPlane.update(frameState); is never called it also removes the clipping but i imagine then in 3D the depth plane is not used loosing performance.
Hope this helps getting the solution into the next release :) regards!

**Comment by Lighfer** [comment]
The problem arises again：[sandcastle](https://sandcastle.cesium.com/index.html#c=bZBfa8IwFMW/yqVPFeqtDsb+WGWj+uYmTHAM8hLTq4aliSSp4obffbG1MjYfknBO7vndyxVGOw87SXuyMARNe8jJyarERe3FLBK1zo32XGqyLErgm2kAJ0jTiynosY3MWwfn+eR1cjNm+tgZMM100wBJe+klOeRFEdcQS8JzvVYBUmsAYYwtpOae3AX81lbhyppyTGtL5OJu/66HvQS69/VzVg/h7iQNqwwUK7m6gHKjjMWPyXQ6e8e99Jtntd3wuIe3TeSY1CNHScSiwcloD0Dm/EHRqBEAT7LcGuuhsipGTD2VW3WaOV1W4pM8Cuc6g3My/R3NCrkDWQyvLBaE4s6Fn1Wl1Fx+EYtGWRrq/0WV4WFH69mOrOKHU9mmP5o2JiJmaZDXk94YteT2D/kH)

**Comment by Lighfer** [comment]
> The problem arises again：[sandcastle](https://sandcastle.cesium.com/index.html#c=bZBfa8IwFMW/yqVPFeqtDsb+WGWj+uYmTHAM8hLTq4aliSSp4obffbG1MjYfknBO7vndyxVGOw87SXuyMARNe8jJyarERe3FLBK1zo32XGqyLErgm2kAJ0jTiynosY3MWwfn+eR1cjNm+tgZMM100wBJe+klOeRFEdcQS8JzvVYBUmsAYYwtpOae3AX81lbhyppyTGtL5OJu/66HvQS69/VzVg/h7iQNqwwUK7m6gHKjjMWPyXQ6e8e99Jtntd3wuIe3TeSY1CNHScSiwcloD0Dm/EHRqBEAT7LcGuuhsipGTD2VW3WaOV1W4pM8Cuc6g3My/R3NCrkDWQyvLBaE4s6Fn1Wl1Fx+EYtGWRrq/0WV4WFH69mOrOKHU9mmP5o2JiJmaZDXk94YteT2D/kH)

Based on testing, this issue was reintroduced from 1.80

**Comment by Lighfer** [comment]
I found that the problem was solved by modifying file `ShadowVolumeAppearanceFS` like this

```javascript
// line 79
if (0.0 <= uv.x && uv.x <= 1.0 && 0.0 <= uv.y && uv.y <= 1.0 || logDepthOrDepth != 0.0) {
// change to
if (0.0 <= uv.x && uv.x <= 1.0 && 0.0 <= uv.y && uv.y <= 1.0 || (logDepthOrDepth != 0.0 && czm_sceneMode != czm_sceneMode2D)) {

// line 92
if (uv.x <= 0.0 || 1.0 <= uv.x || uv.y <= 0.0 || 1.0 <= uv.y || logDepthOrDepth == 0.0) {
// chang to
if (uv.x <= 0.0 || 1.0 <= uv.x || uv.y <= 0.0 || 1.0 <= uv.y || (logDepthOrDepth == 0.0 && czm_sceneMode != czm_sceneMode2D)) {
```

@pjcozzi pjcozzi Is this a correct solution?
