### ISSUE TITLE
Freeze RenderState

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#3752]
`RenderState` objects are supposed to be immutable so we can map the minimal amount of GL state changes between draw calls. All `RenderState`s should be frozen as well as all of the object literal properties, except for `_applyFunctions`. We'll need a function that freezes an object and its properties recursively so we can use a pragma to remove it from release builds unless it has a negligible performance impact.

**Comment by ateshuseyin** [comment]
I wrote a freezeRenderState function but I don't know where it should be used. Can you help me?

**Comment by ateshuseyin** [comment]
@bagnell I pushed my code. You can check it from https://github.com/ateshuseyin/cesium/tree/freeze-renderstate

**Comment by pjcozzi** [comment]
Thanks @ateshuseyin!

@bagnell could this be part of your upcoming stencil separation `RenderState` update?  Or is this too big/unrelated?
