### ISSUE TITLE
provider like openlayer3 ol.source.ImageWMS?

### ISSUE THREAD

**Issue by topwood** [AnalyticalGraphicsInc/cesium#3758]
thanks at first,i am new in Cesium.js.
my wms server provide only image wms service,not in tile. when i use openlayers, i find [Single Image WMS](http://openlayers.org/en/v3.14.2/examples/wms-image.html),and i use this successfully. but now i want to use cesium.js. i search all the example in sandcastle and i fail to find what i want..how can i request wms service with image but not tile?

**Comment by hpinkos** [comment]
Hello @topwood 
I'm not sure, but can you use the [SingleTileImageryProvider](http://cesiumjs.org/Cesium/Build/Documentation/SingleTileImageryProvider.html)?

If you have an follow up questions, please post them in our [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev)

**Comment by topwood** [comment]
i have seen the single SingleTileImageryProvider  and it just request the server once, not request another image when the map zoom or move.
the WebMapServiceImageryProvider request tiled image.

what i want is request the view extent as bbox for wms when the map zoom or move just like the openlayers3 demo above,thank you.

**Comment by topwood** [comment]
my problem just like the post [here](https://groups.google.com/forum/#!searchin/cesium-dev/wms$20tile/cesium-dev/PJCxKreB3fo/BQonhaBXYCAJ)

**Comment by samuel-girard** [comment]
Hello @topwood 
Any chance that you found a solution for this?
I encounter the exact same problem, and I couldn't see a way to make it work in Cesium.

Thanks.
