### ISSUE TITLE
Morphing from 3D to 2D hides vector layers partially

### ISSUE THREAD

**Issue by ezze** [AnalyticalGraphicsInc/cesium#3772]
I faced a strange issue I'm able to reproduce in Cesium Viewer:

- load vector data in 3D scene mode (GeoJSON in my case);
- switch from 3D to 2D with morphing;
- you will see something like on pictures below:

When I load vector data in 2D everything works fine.

The problem is reproduced on two diffirent machines with the following characteristics:

1. Ubuntu 14.04 LTS, Google Chrome 49.0.2623.87 (64-bit)/Mozilla Firefox 45.0, NVIDIA GT630M
![geojson-bug](https://cloud.githubusercontent.com/assets/665479/14041020/3738ecc8-f27e-11e5-83f6-7bb9287f753d.png)
![mozilla-vector-bug](https://cloud.githubusercontent.com/assets/665479/14041323/b9682e6e-f280-11e5-8f9c-23082425e419.png)

2. Windows 7, Google Chrome 49.0.2623.87 (64-bit), Intel HD Graphic 4000/NVIDIA NVS 5400M
![2016-03-25](https://cloud.githubusercontent.com/assets/665479/14041169/6eb97c20-f27f-11e5-939d-a1df8bc198f3.png)

It also affects some other vector primitives such as billboard and labels in CZML. Probably, this bug is appeared in recent Cesium version (1.19).

GeoJSON sample is [here](http://geo.gisprom.com:30080/geojson/river/rivers_lo.geojson).

**Comment by hpinkos** [comment]
Thanks for the very detailed write up @ezze!  I believe this is the same issue as #3748 
This has been fixed in master and will be included in the 1.20 release on April 1st
If you still see this issue after upgrading, feel free to re-open this issue
