### ISSUE TITLE
Remove ImageryMaterialProperty.alpha

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3785]
I just noticed this in CHANGES.md:

> Deprecated `ImageryMaterialProperty.alpha`.  It will be removed in 1.21.  Use `ImageryMaterialProperty.color.alpha` instead.

**Comment by emackey** [comment]
Related issue:  AnalyticalGraphicsInc/czml-writer#106

**Comment by pjcozzi** [comment]
@TomPed do you want to do this?
