### ISSUE TITLE
The sun isn't being rendered

### ISSUE THREAD

**Issue by lasalvavida** [AnalyticalGraphicsInc/cesium#3800]
Pretty self explanatory.

**Comment by lasalvavida** [comment]
I've narrowed this down to a change that occurred between March 23rd and 24th

**Comment by lasalvavida** [comment]
This was caused by revision b937a5c7ccfd929a04806a5dfdd12b4dc99ce25d, Infinite horizontal scrolling in 2D; the sun is still rendered in the revision previous revision 68723424b01ba1fa54e10f10f1eeb896575a3228. Working on a fix

**Comment by pjcozzi** [comment]
Thanks for finding and narrowing it down.  @bagnell let's fix this for the next release.

**Comment by lilleyse** [comment]
Fixed in #3801
