### ISSUE TITLE
problems with groundPrimitives in recent chrome

### ISSUE THREAD

**Issue by bmckilligan** [AnalyticalGraphicsInc/cesium#3804]
Just noticed this last week with chrome, it may have started earlier  , pulled the following demo code from issue #3710, things render fine in firefox, 

the rectangle geometry appears to be projecting down towards the center of the earth and is rendering above the ground

Windows 7, chrome 49.0.2623.110 m, 

![capture](https://cloud.githubusercontent.com/assets/8988054/14260070/93772e36-fa5e-11e5-90f6-c0331ef8a989.JPG)

`

```
var viewer = new Cesium.Viewer("cesiumContainer", {
    baseLayerPicker: false,
    terrainProvider: new Cesium.CesiumTerrainProvider({
        url: "//assets.agi.com/stk-terrain/world"
    })
});
```

```
var rect = Cesium.Rectangle.fromDegrees(-85.0, 35.99, -84.99, 36.0);
    viewer.camera.setView({destination: rect});
```

```
Sandcastle.addToolbarButton('Bug', function () {
    viewer.scene.groundPrimitives.add(new Cesium.GroundPrimitive({
        geometryInstances : new Cesium.GeometryInstance({
            geometry : new Cesium.RectangleGeometry({
                rectangle : rect
            }),
            attributes: {
                color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 1.0, 0.0, 0.5))
            }
        }),
        asynchronous : false
    }));
});
```

`

**Comment by hpinkos** [comment]
Hello @bmckilligan.  Have you tried updating to Cesium 1.20?  We fixed a ground primitive issue in that release that sounds a lot like the one you're seeing. (#3706)

**Comment by bmckilligan** [comment]
yes, appears to be in 1.20 also, the screen grab was from sandcastle showing Cesium.VERSION 1.20

**Comment by hpinkos** [comment]
Okay thanks!  And thanks for providing a code sample and all of the details.  That will make it easier for us to look into the problem

**Comment by bmckilligan** [comment]
I noticed it late last week when using cesium 1.19 in Chrome.

just looked at http://googlechromereleases.blogspot.ca/  .  I suspect the culprit is there 
 
Stable Channel Update for Chrome OS
Thursday, March 31, 2016
The Stable channel has been updated to 49.0.2623.111 (Platform version: 7834.66.0/7834.67.0) for all Chrome OS devices. This build contains a number of bug fixes, an update to Adobe Flash Player (21.0.0.197-r1) and security fixes. Systems will be receiving updates over the next several days.

**Comment by bmckilligan** [comment]
any luck on resolving this ?  has a bug been filed with bugs.chromium.org ?

**Comment by bmckilligan** [comment]
any word on this, Its still present in Chrome 50.0.2661.94 m (64-bit) ?
has a  Chromium bug been submitted ?

**Comment by mramato** [comment]
@bmckilligan as far as I know, no bug has been submitted to the Chrome team (not 100% sure if it's a Chrome bug or not yet); I've seen this problem randomly in the past but I can't reproduce it with the code you provided.  Does this happen every time for you?  Can you copy/paste the results of going to http://webglreport.com?  That might help narrow down the issue.

**Comment by bmckilligan** [comment]
I just tried the code in a 32-bit version of chrome and things worked, 

so it looks like it may be a chrome 64-bit issue

**Comment by bmckilligan** [comment]
Platform:	Win32
Browser User Agent:	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc.
Unmasked Renderer:	ANGLE (Intel(R) HD Graphics Family Direct3D9Ex vs_3_0 ps_3_0)
Antialiasing:	Available
ANGLE:	Yes, D3D9
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	253
Max Vertex Texture Image Units:	4
Max Varying Vectors:	9
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range:	[1, 1]
Aliased Point Size Range:	[1, 256]
Fragment Shader
Max Fragment Uniform Vectors:	221
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	1
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	8192
Max Viewport Dimensions:	[8192, 8192]
Textures
Max Texture Size:	8192
Max Cube Map Texture Size:	8192
Max Combined Texture Image Units:	20
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

To see draft extensions in Chrome, browse to about:flags, enable the "Enable WebGL Draft Extensions" option, and relaunch.

**Comment by pjcozzi** [comment]
@bmckilligan this may be fixed in [Cesium 1.29](http://cesiumjs.org/downloads.html) as part of the stencil initialization fix.  Can you please retest?

**Comment by pjcozzi** [comment]
@bmckilligan any update on if this is still an issue for you?  Thanks!

**Comment by bmckilligan** [comment]
Sorry, I missed the message in January, All looks good on Chrome 64-bit
