### ISSUE TITLE
KML - Hotspot don't play well with scale by distance

### ISSUE THREAD

**Issue by theOgrable** [AnalyticalGraphicsInc/cesium#3813]
Hi,

There is a problem when using hotspot with KML : it does not play well with scale by distance. At least when the unit is fraction (untested otherwise).

Here a simple gist for sandcastle that show the problem : 
https://gist.github.com/theOgrable/6883ac6a4e9be381f3dd0f1d1f97b121

We can see that when zooming out the billboard will start flying above its position target. Not what is expected.

The first option show the problem, the second show a simple solution using pixelOffsetScaleByDistance instead of simply pixelOffset.

I think this solution (pixelOffsetScaleByDistance) should be integrated natively during KML processing.

What do you think ?

Olivier

**Comment by hpinkos** [comment]
Thanks for including the code example @theOgrable!  This looks like a bug.  Your solution of using `pixelOffsetScaleByDistance` looks good to me.  Would you be interested in opening a pull request with the fix?   The change would need to be made in [KmlDataSource](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/KmlDataSource.js#L632).

**Comment by theOgrable** [comment]
No problem,

Here it is : https://github.com/AnalyticalGraphicsInc/cesium/pull/3837

Please, let me know if it's ok.

I had some problems to build sand castle and I was a little bit confuse about the different build scenarii. I'll write some comments about this on the forum.

**Comment by hpinkos** [comment]
Fixed in #3837
