### ISSUE TITLE
Source/test WebStorm plugin

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3817]
It would be cool to have a simple WebStorm plugin that provides a hotkey to swap between a source file and its test, e.g., (`/Source/path/file.js <-> /Specs/path/fileSpec.js`).

Good code sprint project.

**Comment by TomPed** [comment]
I've made the plugin [here](https://github.com/AnalyticalGraphicsInc/cesium-webstorm-plugin). Does anyone have any other ideas/requests for the plugin to help with Cesium development?
