### ISSUE TITLE
Failed to load external gltf!

### ISSUE THREAD

**Issue by osh** [AnalyticalGraphicsInc/cesium#3818]
I'm having difficulty loading a gltf model correctly using cesium.
after specifying

...
model : {
 uri : '/models/model.gltf',
minimumPixelSize : 64 
},
...

I get the attached error message.
have tried generating the gltf using the web-convert as well as manually building COLLADA2GLTF and running it locally.   Do you have any suggestions for additional approaches to debugging what could be going wrong here? Thanks!  (gltf file provided for reference, generated using local COLLADA2GLTF binary)

![image](https://cloud.githubusercontent.com/assets/850758/14358328/6ee6afa2-fcba-11e5-8e1a-d136af4086e8.png)

[model.gltf.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/208760/model.gltf.zip)

**Comment by lilleyse** [comment]
The glTF file is referencing some external files which aren't included included in the zip (binary files, images, shaders). Can you send those over as well? Also feel free to send over the dae file.

**Comment by osh** [comment]
please see original DAE, and converted gltf format attached! 
Thanks!

[model_dae_original.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/208855/model_dae_original.zip)
[model_gltf_converted.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/208856/model_gltf_converted.zip)

**Comment by lilleyse** [comment]
I reconverted the dae with Blender and it now loads okay (though it's missing the solar panel texture). I'll try to figure out why the original file doesn't work.
[model.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/208981/model.zip)

**Comment by osh** [comment]
im still getting the same error with the .gltf you posted

**Comment by lilleyse** [comment]
For my testing I placed the model in `Apps/SampleData/models` and modified the `3D Models` Sandcastle example to load the new model in place of Cesium_Air.

`createModel('../../SampleData/models/model.gltf', 5000.0);`

Does that work at all?

**Comment by osh** [comment]
ok actually, updating to latest cesium build 1.20 resolves this :+1: thanks!

**Comment by pjcozzi** [comment]
Can we close this?
