### ISSUE TITLE
Bug - ArcGisMapServerImageryProvider exportImage*

### ISSUE THREAD

**Issue by theOgrable** [AnalyticalGraphicsInc/cesium#3821]
Hi,

I believe there is a bug in the ArcGisMapServerImageryProvider in the image url building.

```
Line 256 :            
url = imageryProvider._url + '/export?';
```

Based on the API documentation (http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Export_Image/02r3000000wm000000/) and my experimentation, it should be 

```
Line 256 :            
url = imageryProvider._url + '/exportImage?';
```

instead.

**Comment by kring** [comment]
ArcGIS Image services use exportImage.  ArcGIS Map services, which is what
this imagery provider claims to access, use export:
http://resources.arcgis.com/en/help/arcgis-rest-api/02r3/02r3000000v7000000.htm

If you're trying to access an ImageServer, you might try using
UrlTemplateImageryProvider.

Kevin

On Fri, Apr 8, 2016 at 7:55 PM, theOgrable <notifications@github.com> wrote:

> Hi,
>
> I believe there is a bug in the ArcGisMapServerImageryProvider in the
> image url building.
>
> Line 256 :
> url = imageryProvider._url + '/export?';
>
> Based on the API documentation (
> http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Export_Image/02r3000000wm000000/)
> and my experimentation, it should be
>
> Line 256 :
> url = imageryProvider._url + '/exportImage?';
>
> instead.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AnalyticalGraphicsInc/cesium/issues/3821>
>



-- 
www.kotachrome.com/kevin
