### ISSUE TITLE
Support for British National Grid (OSGB36)

### ISSUE THREAD

**Issue by kalifa17** [AnalyticalGraphicsInc/cesium#3824]
I am trying to import a 3D model (.gltf) into Cesium which is in OSGB36 projection, however I know that Cesiumjs doesn't support British projection natively.

I've tried changing the origin of the map and reporject the lat and lon based on the x,y,z coordinates cesium's api gives you using entity.position.getValue().

```
var entity = viewer.entities.add({
    // Lon, Lat, Height, Elipsode
    position : Cesium.Cartesian3.fromDegrees(-10.6658787,50.6943631),
    model : {
        uri : '../../static/structures/models/duck/duck.gltf'
    }
});
```

I am looking for which would be the best and quickest way to include this 3d Models, because also would like to use OL3-Cesium to integrate Cesiumjs and Openlayers 3 which only support EPSG:4326 and EPSG:3857 projections and not British.

I would appreciate any advise. Thank you.

**Comment by pjcozzi** [comment]
Thanks again @kalifa17!  To keep our GitHub issues manageable, I made a note of this in #3877.
