### ISSUE TITLE
Add CZML support for polygons with holes

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3826]
Mentioned on the forum: https://groups.google.com/d/msg/cesium-dev/9jzhk3Hv8v0/2MYysnkEAwAJ

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/9jzhk3Hv8v0/2MYysnkEAwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/3826 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
