### ISSUE TITLE
Show Cesium3DTileset wire frame

### ISSUE THREAD

**Issue by e-andersson** [AnalyticalGraphicsInc/cesium#3830]
We sometimes want to show the wire frame (with no texture) for a 3D tileset (ideally on top of the original model/textures). Is that a feature that will/could be added?

**Comment by pjcozzi** [comment]
Yes, this would be a welcomed contribution.  To get started, see `Cesium3DTileset.debugColorizeTiles` and `Model.debugWireframe`.

**Comment by e-andersson** [comment]
Having the model wireframe show seems relatively straightforward, but it I haven't found any way of showing the wireframe and the textured model at the same time (except perhaps for loading the tiles twice, once with `debugWireframe` and once normally).

Is there something I have overlooked, or does Cesium not currently support this unless modifying model shader code?

**Comment by pjcozzi** [comment]
> Is there something I have overlooked, or does Cesium not currently support this unless modifying model shader code?

Right, Cesium doesn't currently support this.

This could be of interest to you: https://github.com/virtualglobebook/OpenGlobe/tree/master/Source/Scene/Renderables/Wireframe (it uses a geometry shader so it would need to be adapted for WebGL).

**Comment by e-andersson** [comment]
Thanks, will keep that in mind. (I'll probably not be able to dig into this problem soon though -- perhaps a bit later.)

**Comment by lilleyse** [comment]
@austinEng for this one it's fine to just draw the wireframe itself, not both the solid and wireframe at the same time.

**Comment by pjcozzi** [comment]
Fixed in #4844

**Comment by wyq521** [comment]
Does cesium support to show the wireframe and the textured model at the same time now?
