### ISSUE TITLE
Hosted Sandcastle for master branch does not run

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3838]
Visit http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/Sandcastle/index.html

![image](https://cloud.githubusercontent.com/assets/782098/14500366/c497977c-016f-11e6-8df9-ea69b900c821.png)

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/TUegXPEvF5M

**Comment by ggetz** [comment]
On the google group someone says: 
>It's a typo error.
>SandCastle is looking for TextArea.js when the file is named Textarea.js.
>Not sure which one is wrong between the code or the file name...
