### ISSUE TITLE
Bug in logo style guide

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3847]
I just noticed that the logo style guide at the bottom of https://github.com/AnalyticalGraphicsInc/cesium/wiki/Cesium-Logos has a bad RGB value for Cesium's blue color, instead of 108, 103, 223, it should be 108, 173, 223 (verified with a dropper, 103 makes it purple).  I'm not sure if any of the other categories/values are right/wrong but we should verify them.

**Comment by hpinkos** [comment]
Fixed
