### ISSUE TITLE
mistake on the website

### ISSUE THREAD

**Issue by OljaKli** [AnalyticalGraphicsInc/cesium#3849]
Mistake [here](https://cesiumjs.org/tutorials/3D-Models-Tutorial) in **Animations** part:

```javascript
Cesium.when(mode.readyPromise).then(function(model) 
```
Correct variant:
```javascript
Cesium.when(model.readyPromise).then(function(model) 
```

**Comment by hpinkos** [comment]
Thanks! I made that fix, it should be updated on the website soon.
