### ISSUE TITLE
Texture coordinates incorrect for rotated ellipse with rotated texture

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3851]
The texture coordinate is wrong for one of the outer vertices when a `rotation` and a `stRotation` are used.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

scene.primitives.add(new Cesium.Primitive({
    geometryInstances : [new Cesium.GeometryInstance({
        geometry : new Cesium.EllipseGeometry({
            center : Cesium.Cartesian3.fromDegrees(1.52278, 45.00838),
            semiMajorAxis: 5000, 
            semiMinorAxis: 5000, 
            rotation : Cesium.Math.toRadians(-168), 
            stRotation : Cesium.Math.toRadians(168), 
            granularity: Cesium.Math.toRadians(10),
            vertexFormat : Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT
        }),
        attributes: {
            color: Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.RED)
        }
    })],
    appearance : new Cesium.DebugAppearance({
        attributeName: 'st'
    })
}));

scene.camera.setView({
    destination: Cesium.Rectangle.fromDegrees(1.4, 44.9, 1.6, 45.1)
});
```

**Comment by mramato** [comment]
Could this be the same root cause (or at least same logic bug) that causes #3172?

**Comment by hpinkos** [comment]
Not exactly.  It's probably more related to #2737,  but I think the solution for the rectangle rotation will be way different.

**Comment by bagnell** [comment]
I couldn't reproduce this in 1.26.

**Comment by hpinkos** [comment]
Yep, this appears to be fixed.

This is what it looked like in 1.20
![image](https://cloud.githubusercontent.com/assets/3451886/19491127/c837d0d6-953f-11e6-891f-3d139338c1b0.png)
And this is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/3451886/19491140/d9012afc-953f-11e6-999e-bcffeff55515.png)
