### ISSUE TITLE
FlyTo with rectangle does not work as expected in 1.19

### ISSUE THREAD

**Issue by Aviv-Galmidi** [AnalyticalGraphicsInc/cesium#3859]
I am trying to update to 1.19 but when I use the function camera.flyTo with a rectangle the camera flies to the wrong location.
I did not have that problem in 1.18.

I reverted cesium back to 1.18 and put a breakpoint right before I call this function, I coppied the rectangle I send there and used it hardcoded in 1.19. Once again it took me to the wrong location.

When using a cartasian3 point the flyTo works perfect, it only occours when using a rectangle.

**Comment by hpinkos** [comment]
Hello @Aviv-Galmidi,
We did fix an issue where the camera flew to the wrong location in 2D, and that will be included in the upcoming 1.21 release on May 2.
Can you give a code example for your case to make sure your issue is fixed as well?
Thanks!
