### ISSUE TITLE
How can i use the faunction "Cesium.CzmlDataSource.processMaterialPacketData(object, propertyName, packetData, interval, sourceUri, entityCollection)"?

### ISSUE THREAD

**Issue by wangyipeng** [AnalyticalGraphicsInc/cesium#3864]
I use the code exmple: [(http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML%20Point%20-%20Time%20Dynamic.html&label=CZML)]
I want change the point's color to red,and I use the method:Cesium.CzmlDataSource.processMaterialPacketData(object, propertyName, packetData, interval, sourceUri, entityCollection).
after i change the code ,the point's color is change to white,i dont know hao to do with the problem...
`var czml = [
  {
    "id" : "document",
    "name" : "CZML Point - Time Dynamic",
    "version" : "1.0"
  }, {
    "id" : "point",
    "availability" :"2012-08-04T16:00:00Z/2012-08-04T16:05:00Z",
    "position" : {
      "epoch" : "2012-08-04T16:00:00Z",
      "cartographicDegrees" : [
        0,   -70, 20, 150000,
        100, -80, 44, 150000,
        200, -90, 18, 150000,
        300, -98, 52, 150000
      ]
    },
    "point" : {
      "color" : {
        "rgba" : [255, 0, 0, 255]
      },
      "outlineColor" : {
        "rgba" : [200, 0, 20, 20]
      },
      "pixelSize" : 15
    }
  }
];

var viewer = new Cesium.Viewer('cesiumContainer');
var haha=new Cesium.CzmlDataSource();
var data=haha.load(czml);                                                              
var entities=haha.entities;
var entitypoint=entities.getById("point");

var timeInterval = new Cesium.TimeInterval({
    start : Cesium.JulianDate.fromIso8601('2012-08-04T16:00:00Z'),
    stop : Cesium.JulianDate.fromIso8601('2012-08-04T16:05:00Z'),
    isStartTimeIncluded : true,
    isStopTimeIncluded : false,

});

Cesium.CzmlDataSource.processMaterialPacketData(entitypoint.point,"color", { "rgba" : [255, 0, 0, 255]} , timeInterval, czml, entities);

viewer.dataSources.add(data);
`

**Comment by hpinkos** [comment]
Hello @wangyipeng,
We use our GitHub issues to track bugs and features for Cesium.  For questions, please post in the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
More people see the forum, so you are more likely to get help from someone who has done the same thing in their own application.
Thanks!

**Comment by wangyipeng** [comment]
hello @hpinkos 
thank you ,I have solved the problem.
