### ISSUE TITLE
Default CV view is now straight down like 2D

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3878]
For example, just switch to CV in Viewer: http://cesiumjs.org/releases/1.20/Apps/CesiumViewer/index.html

Was this change intention?

**Comment by hpinkos** [comment]
Brought up on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Gn4jOl0wQmk

I think this slipped through when we changed the scene mode transitions.  It should be changed back to be tilted after the transition.

**Comment by lilleyse** [comment]
@JoshuaStorm Here's another one you can work on next.

**Comment by hpinkos** [comment]
Mentioned on the forum again here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/q2OO2oUzdgQ

**Comment by ggetz** [comment]
Taking a look at this now.
