### ISSUE TITLE
convertLongitudeRange producing unexpected result

### ISSUE THREAD

**Issue by rowanwins** [AnalyticalGraphicsInc/cesium#3882]
So I'm trying to convert my radian value into a longitude value between -180 and 180, 

The docs provide a simple example 
````
var longitude = Cesium.Math.convertLongitudeRange(Cesium.Math.toRadians(270.0));
````
However that results in  `-1.5707963267948966` rather than `-90`

Any tips?
Thanks in advance,
Rowan

**Comment by lasalvavida** [comment]
Hi @rowanwins!

The answer is being returned to you in radians. -90 degrees is -pi/2 radians, or -1.570...

**Comment by rowanwins** [comment]
Thanks @lasalvavida , rookie mistake, that's what happens when you try and do this stuff too late in the day!
