### ISSUE TITLE
SVG billboard doesn't draw in Firefox

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3886]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/eiFCPPlR19c

``` Javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var svg ='data:image/svg+xml,' +
           '<svg width="100%" height="100%" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg">';
svg += '<circle cx="24" cy="24" r="10" style="fill:#ff141e;stroke-width:2px;stroke:#ececec;" />';
svg += '</svg>';

var image = new Image();
image.src = svg;

viewer.entities.add({
   position : Cesium.Cartesian3.fromDegrees(-85, 40),
   billboard :{
       image : image
   }
});
```

**Comment by mramato** [comment]
This is almost certainly a problem in the SVG itself (or a bug in Firefox, but doubtful).  I'll see if I can dig up the forum conversation where I've discussed this in the past.

**Comment by mramato** [comment]
See #2907, which shows that svg billboard render in firefox just fine.  So this is most likely a problem with the svg or a bug in Firefox.

Keep in mind that IE will not load this either for security reasons they mark SVGs (at least hard coded ones) as tainted canvases that can't be used in WebGL.

@emackey might have some thoughts on why Firefox is barfing on the image; but otherwise I would file a bug with them.

**Comment by emackey** [comment]
This does appear to be a Firefox issue, because creating an SVG img tag in this fashion does not work in Firefox even on a page without Cesium.js.

Looks like the workaround for Firefox is to base-64 encode it, and wait for the onload event.

```
var viewer = new Cesium.Viewer('cesiumContainer');

var svg = '<svg width="48" height="48" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg">';
svg += '<circle cx="24" cy="24" r="10" style="fill:#ff141e;stroke-width:2px;stroke:#ececec;" />';
svg += '</svg>';

svg = 'data:image/svg+xml;base64,' + window.btoa(svg);

var image = new Image();

image.onload = function() {
    viewer.entities.add({
       position : Cesium.Cartesian3.fromDegrees(-85, 40),
       billboard :{
           image : image
       }
    });
};

image.src = svg;
```

**Comment by emackey** [comment]
Also the `width="100%"` and likewise the height is not valid in SVG, I changed this to `width="48px"`.

**Comment by mramato** [comment]
Thanks @emackey!

**Comment by jorpiell** [comment]
Thanks @emackey
