### ISSUE TITLE
Missing tiles when morphing from 2D to 3D in Linux Chrome

### ISSUE THREAD

**Issue by cfairchi** [AnalyticalGraphicsInc/cesium#3889]
Using Linux chrome, if you toggle from 3D to 2D, then toggle back to 3D tiles are missing for most if not all of the globe.  Zooming to different zoom level show tiles for for different zoom, but the only way to get all tiles back at all zoom levels is to refresh the browser.  

![missingtiles](https://cloud.githubusercontent.com/assets/984128/14942934/2f07b570-0f89-11e6-9535-348c40fafb2c.png)

**Comment by cfairchi** [comment]
different zoom level

![missintiles2](https://cloud.githubusercontent.com/assets/984128/14942943/630d9a56-0f89-11e6-9594-2b42de79959a.png)

**Comment by hpinkos** [comment]
Hello @cfairchi,  what version of chrome are you using?  And what version of Cesium?  Thanks!

**Comment by mramato** [comment]
I can reproduce this on Linux using Chrome 50.0.2661.86 (64-bit)

I'm also getting the following output in the console:
```
149 /Cesium/Apps/CesiumViewer/index.html:1 [.CommandBufferContext]PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty
107 /Cesium/Apps/CesiumViewer/index.html?view=0%2C0%2C31890685%2C360%2C-90%2C0:1 [.CommandBufferContext]PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty
/Cesium/Apps/CesiumViewer/index.html?view=0%2C0%2C31890685%2C360%2C-90%2C0:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

@bagnell I'll bring my laptop in for you to have a look.

**Comment by cfairchi** [comment]
I have seen it in both Red Hat Linux 7.2 Chrome 47.0.2526.111, and in Linux Mint 17.3 Chrome 49.0.2623.112 (64 bit).  I have seen it in Cesium 1.10, 1.17 and 1.20.  It seems to be less severe in Cesium 1.10.  I get the same output in the console that Matt gets (Attribute 0 warning).  It almost looks like the tiles are rendering on the wrong side of the globe because I can see tiles rendering near the edge of the globe, then disappear as I rotate the globe.

**Comment by pjcozzi** [comment]
@bagnell is it realistic to look at this for 1.23?

I'm pretty sure this is an OS/browser/driver issue, but we can probably work around it by ensuring that attribute 0 is always in use.
