### ISSUE TITLE
2D infinite scrolling broken in IE

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3893]
reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/bUa1zY8RyKM

I'm going to mark this as next release because scrolling across the IDL doesn't work at all on Internet Explorer

![2d-ie](https://cloud.githubusercontent.com/assets/3451886/14988553/553402c2-1122-11e6-9d45-34e563100517.gif)

**Comment by hpinkos** [comment]
Just to note, a few users have said that they would appreciate a toggle to go back to the old 2D behavior.

Another thing the user said was that he can't zoom out all the way to see both poles of the 2D map on a 16:9 screen, so we might want to think about that at some point too.

**Comment by mramato** [comment]
Broken in Edge as well.
