### ISSUE TITLE
Enable rotation for 2D

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3897]
Several users on the forum have asked if it is possible to revert to the old 2D scene mode behavior because they want to be able to rotate the 2D map.

https://groups.google.com/forum/?hl=en#!topic/cesium-dev/CPnsBqMzUVo
https://groups.google.com/d/msg/cesium-dev/bUa1zY8RyKM/GBspqvCPAAAJ

**Comment by tianhai82** [comment]
I hope there will be a mean to enable 2d map rotation. Please consider adding it back.

**Comment by pjcozzi** [comment]
Given the navigation use case of orienting the map with the driving direction up, I have to agree that this is a valuable option.

**Comment by hpinkos** [comment]
@tianhai82 an option was added for the old 2D map behavior in #3990 and will be available in Cesium 1.23 coming out on July 1st
