### ISSUE TITLE
ImageMaterialProperty not rendering in Chrome with AMD graphics card

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3906]
Can someone with an AMD graphics card see if they can reproduce this?  Seen in Chrome 50.

Reported on the forum: https://groups.google.com/d/msg/cesium-dev/AMf11Gr9RFI/FoyNr6PGBgAJ

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var url ="../images/Cesium_Logo_overlay.png"
var redRectangle = viewer.entities.add({
    name : 'Red translucent rectangle with outline',
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-110.0, 20.0, -80.0, 25.0),
        material :  new Cesium.ImageMaterialProperty({image:url}),
        outline : true,
        outlineColor : Cesium.Color.RED
    }
});

viewer.zoomTo(viewer.entities);
```

**Comment by lilleyse** [comment]
I'm noticing the same problem with Chrome 50, among other issues.

**Comment by lilleyse** [comment]
However my drivers are also pretty behind: 15.201 from September because that seems to be the version that Bootcamp for Windows 8.1 caps at. Maybe someone with the newest drivers can test too.

**Comment by mramato** [comment]
If that happens with the official bootcamp drivers, we should probably look into it.  Any console output?

**Comment by denverpierce** [comment]
Chrome Version 50.0.2661.94 m (64-bit), Catalyst 16.4.2 I have the same issue, but creating a ImageMaterialProperty like that sets transparent: false by default. Creating the material with transparent:true and it shows up as intended.

No console errors. Same thing happens in Edge.

**Comment by lilleyse** [comment]
No console output for me either.

**Comment by lilleyse** [comment]
This is working for me now with the latest Chrome update, as well as a lot of other demos that used to be broken.

**Comment by hpinkos** [comment]
@lilleyse can this be closed?
