### ISSUE TITLE
VR renders the same image for both eyes

### ISSUE THREAD

**Issue by jmgomezpoveda** [AnalyticalGraphicsInc/cesium#3909]
When enabling the VR mode (useWebVR / vrButton), two images are rendered side by side.

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Cardboard.html&label=

I would expect these images to be slightly different, simulating the position of the eyes to create the 3D effect. However, the images I see are exactly the same (subtracting them in GIMP gives a completely black image).

![vr](https://cloud.githubusercontent.com/assets/3722516/15168217/644d2288-1727-11e6-95c9-17e2d5fb2377.png)
![vr2](https://cloud.githubusercontent.com/assets/3722516/15168256/c26e027e-1727-11e6-8e24-fa51f0499728.png)

Tested with Firefox and Chromium.

**Comment by mramato** [comment]
@bagnell we should probably look at this for the next release.

**Comment by mramato** [comment]
Thanks for the report @jmgomezpoveda!

**Comment by pjcozzi** [comment]
@bagnell can you look at this in time for the release next week?

**Comment by pjcozzi** [comment]
@bagnell are you able to look at this for the 1.23 release tomorrow?

**Comment by bagnell** [comment]
The images are different for objects close to the camera so you wouldn't see anything different in those two example screen shots. I'll push out the default near plane and add parameters to make it adjustable. It won't make the 1.22 release, but will make the 1.23.

**Comment by bagnell** [comment]
Here's an example with the camera close to the basket of a hot air balloon. The rendering for each eye:
![vr0](https://cloud.githubusercontent.com/assets/1494815/15945692/af7a104e-2e61-11e6-9470-f9ea3bb37227.png)
![vr1](https://cloud.githubusercontent.com/assets/1494815/15945695/b2e4fbb8-2e61-11e6-8b69-f53310eaa633.png)
And here's the diff (the pixels different are pink):
![vrdiff](https://cloud.githubusercontent.com/assets/1494815/15945716/cd19c608-2e61-11e6-85bd-ef07764a2194.png)

**Comment by pjcozzi** [comment]
@bagnell this is labeled 1.23, but do we really need to do anything for this release?

**Comment by pjcozzi** [comment]
OK to close this?

**Comment by bagnell** [comment]
No, it doesn't render the same for both eyes when you have things close to the viewer, so I want to add options to push that distance out.

**Comment by pjcozzi** [comment]
@jmgomezpoveda thanks again for submitting this issue.  This was fixed in #5917.  Please let us know if you build something cool with Cesium and VR.
