### ISSUE TITLE
render a 2.5D raster overlaping terrain

### ISSUE THREAD

**Issue by seifer08ms** [AnalyticalGraphicsInc/cesium#3914]
Hi, guys!
We want to render a 2.5D raster overlaping a terrain layer. For example, a 2.5D raster layer of temperature has higher altitude where the temperature is higher than other regions. I couldn't found somethins about raster 2.5D render . Is it possible to implement it ?

**Comment by hpinkos** [comment]
@seifer08ms sorry we didn't answer this.  We don't have anything like this currently built into Cesium.
If you have further questions, please ask them on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
thanks!
