### ISSUE TITLE
Billboard.prototype.computeScreenSpacePosition returning wrong y position

### ISSUE THREAD

**Issue by e-andersson** [AnalyticalGraphicsInc/cesium#3920]
The behavior of computeScreenSpacePosition seems to have changed recently (there seem to be a few new commits changing Billboard.js). It looks like the y screen coordinate is the inverse of what it used to be. According to the API docs, the y coordinate increases from top to bottom.

The attached Billboards sandcastle example prints the screen positions and the computed screen positions of the clicked billboard.

Am I possibly missing something here?
[sandcastle_compute_screenposition.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/266055/sandcastle_compute_screenposition.txt)

**Comment by pjcozzi** [comment]
@bagnell any idea here?  Is this related to https://github.com/AnalyticalGraphicsInc/cesium/commit/651a8b26816ba5c947bd01e49eb01b8c2b97d889#diff-97a34c40d0a290b6fab62f87f92bcc6f or https://github.com/AnalyticalGraphicsInc/cesium/commit/dae0242025e29ba99e4517992357cca64224d4f4#diff-97a34c40d0a290b6fab62f87f92bcc6f?

**Comment by emackey** [comment]
Git bisect says this went bad in 651a8b26816ba5.

**Comment by mramato** [comment]
Given this has been brought up several times this month, we should probably try to get to this before the next release.

**Comment by emackey** [comment]
Here's some test code.  A small `div` should float in the middle of the Cesium logo, and not go to the top of the screen when the logo is at the bottom of the screen and vice-versa.

```
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

var billboards = scene.primitives.add(new Cesium.BillboardCollection());
var b = billboards.add({
    image : '../images/Cesium_Logo_overlay.png',
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883)
});

var floater = document.createElement('div');
floater.innerHTML = 'Test';
floater.style.cssText = 'position:absolute;border: 1px solid #aaa;background:black';
document.body.appendChild(floater);

var scratchPos = new Cesium.Cartesian2();
viewer.clock.onTick.addEventListener(function(clock) {
    var pos = b.computeScreenSpacePosition(scene, scratchPos);
    if (pos) {
        floater.style.display = 'block';
        floater.style.top = pos.y + 'px';
        floater.style.left = pos.x + 'px';
    } else {
        floater.style.display = 'none';
    }
});
```

**Comment by mramato** [comment]
So is this just a one-character change to negate y?

**Comment by emackey** [comment]
It's basically `height - y`, yes.  We should probably check that the solution works when the canvas has a different number of CSS pixels from canvas pixels, unless we're explicitly giving the answer in canvas pixels with CSS-oriented coordinates.  Also, several other classes besides `Billboard` offer a `computeScreenSpacePosition`, they should be tested too.

**Comment by pjcozzi** [comment]
@bagnell can you look at this in time for the release next week?
