### ISSUE TITLE
Billboards on terrain don't all update when terrain is turned off

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#3921]
To reproduce
* Load the `development/BillboardsClampToGround` Sandcastle example
* Zoom in to the area with the billboards
* In the layer picker select `STK World Terrain Meshes` (Terrain is on but isn't selected which should probably be fixed for the example as well)
* Again in the layer picker select `WGS84 Ellipsoid`

You'll notice not all billboards were put on the ellipsoid.

![image](https://cloud.githubusercontent.com/assets/1652382/15305089/010f88e8-1b8f-11e6-998c-2c8f7462c47d.png)

**Comment by pjcozzi** [comment]
I suspect this is an easy fix.  @tfili can you give it a shot?

**Comment by tfili** [comment]
@pjcozzi Sure. Looking at it now.

It looks like it happens when the updateHeight callbacks are still being fired and we change the terrain again.
