### ISSUE TITLE
Offline Guide Out of Date

### ISSUE THREAD

**Issue by TomPed** [AnalyticalGraphicsInc/cesium#3930]
The [Offline Guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Offline-Guide) is out of date in the [example section](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Offline-Guide#example).
 
The example is:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
  imageryProvider : new Cesium.TileMapServiceImageryProvider({
    url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
  }),
  baseLayerPicker : false,
  geocoder : false
});
```
and it should be updated to be:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
  imageryProvider : Cesium.createTileMapServiceImageryProvider({
    url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
  }),
  baseLayerPicker : false,
  geocoder : false
});
```

`new Cesium.TileMapServiceImageryProvider` `->` `Cesium.createTileMapServiceImageryProvider`

**Comment by pjcozzi** [comment]
Good catch, thanks @TomPed!

https://github.com/AnalyticalGraphicsInc/cesium/wiki/Offline-Guide/_compare/c43bb59756e7d6f130e7342cb187e31c998d6202...967df6a9c6880b20f2fb5a2074f722c8c7bfd38c
