### ISSUE TITLE
"RangeError: Invalid array length" when rotating camera down from sky-facing startup

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#3961]
- pan up so the view is entirely sky/space
- reload the page to restart Cesium
- pan down
  <img width="965" alt="crash snip" src="https://cloud.githubusercontent.com/assets/5395255/15579561/21c33b1a-2333-11e6-9033-b3f7bafa267a.PNG">

**Comment by likangning93** [comment]
You might have to pan all the way up before reloading and then navigate a little bit after panning down to reproduce this.

**Comment by pjcozzi** [comment]
Link: https://cesiumjs.org/NewYork

**Comment by pjcozzi** [comment]
Could be duplicate with #2317.

**Comment by mramato** [comment]
@likangning93 can you still reproduce this?  I fixed a camera issue in #5440 that led to NaNs which may have accidentally fixed this.

**Comment by likangning93** [comment]
It's been a while, so I'm not sure if I followed my own instructions exactly, but it seems like I can't reproduce this anymore.

**Comment by programmer101010** [comment]
This is still an issue in Cesium 1.42.  It requires rapidly moving the camera up and down for a view near the ground as well as a view pointing toward the horizon.  This is using Chrome 67 on Windows.  In some cases, the window becomes unresponsive without an error message.  This is difficult to reproduce but is still present.
