### ISSUE TITLE
VR The World terrain provider broken in 1.18

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3964]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/jwEW4MudJ28

The terrain is stair stepped when using the `VRTheWorldTerrainProvider`

Half dome in 1.18
![image](https://cloud.githubusercontent.com/assets/3451886/15583667/c25c9e20-2344-11e6-915b-fc48bbb1452c.png)

Half Dome in 1.17
![image](https://cloud.githubusercontent.com/assets/3451886/15583655/b3727042-2344-11e6-93f9-6c911f211d5f.png)

Also, the Sandcastle terrain example is broken for VR-The World because they don't have https.
Change the URL to `url : 'http://www.vr-theworld.com/vr-theworld/tiles1.0.0/73/'`

**Comment by pjcozzi** [comment]
@bagnell can you take a quick look at this for the next release?

**Comment by jo-chemla** [comment]
Seems like VR-theWorld terrain provider does not work anymore, am I wrong ? See sandbox here for reference: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain.html&label=Showcases

**Comment by hpinkos** [comment]
Hi @jo-chemla, it's working for me.  Do you see any errors in the console?

**Comment by jo-chemla** [comment]
Hi @hpinkos , thanks for the quick reply. I cannot see the terrain when choosing VRTheWorldTerrainProvider in the first input dialog, the error being: 

loadWithXhr.js:194 Mixed Content: The page at 'https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain.html&label=Showcases' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.vr-theworld.com/vr-theworld/tiles1.0.0/73/'. This request has been blocked; the content must be served over HTTPS.loadWithXhr
XMLHttpRequest cannot load http://www.vr-theworld.com/vr-theworld/tiles1.0.0/73/. Failed to start loading.
 An error occurred in "VRTheWorldTerrainProvider": Request has failed.

**Comment by hpinkos** [comment]
Ah, this is because you're on our https site and www.vr-theworld.com doesn't have an https sever.  The http requests are blocked from https servers for security reasons.  It works fine if you go to this link: http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain.html&label=Showcases

I've written up an issue here for us to update the Sandcastle example: #4594

**Comment by jo-chemla** [comment]
Alright, thanks a lot for the hint! All the best,
