### ISSUE TITLE
Entity disappears applying Alpha

### ISSUE THREAD

**Issue by juacarri** [AnalyticalGraphicsInc/cesium#3968]
Hello, I'm trying to apply an Alpha value to the colour of my polygons following this code:

			var color = colorHash[name];
			if (!color) {
				color = Cesium.Color.fromRandom({Alpha: 1.0});
				colorHash[name] = color;
			}
The problem is that the polygons dissapear if I use this code, and they appear if I delete the Alpha. You can see all the code in my web ( http://social4d.com/ ) and actually I uploaded the version without the Alpha in the polygons, but I want to fix this bug. Is it a problem of my code?

**Comment by lasalvavida** [comment]
@juacarri I put together a little sandcastle [demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=96cf45f347aa6ae133338402b7bd6ed8) for you showing setting a random color on an entity.

As best I can tell it's probably a bug in your code.

**Comment by lasalvavida** [comment]
Also, `Alpha` should be lowercase: `alpha`.

**Comment by juacarri** [comment]
@lasalvavida I tried the demo and I can't see the objects with my browser (Chrome) it happens the same that occur in my code. 

Ok, I tried with other browser (IE) and it works completely the both projects, sandcastle and my code.

**Comment by mramato** [comment]
Closing, since this appears to be a browser issue.  Please re-open with more details if you are still having issue.
