### ISSUE TITLE
Cesium exception on startup on Windows/NVIDIA

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3981]
Is anyone else getting this in master when just opening Cesium Viewer?

![image](https://cloud.githubusercontent.com/assets/782098/15682379/61cad1d6-272b-11e6-8857-71cb29e90b41.png)

Looks like a uniform was optimized out.  Perhaps incorrectly?

Chrome 51 and Firefox 46.

**Comment by pjcozzi** [comment]
Just a build issue that @lilleyse pointed out.

I needed to rebuild when switching to `master`.

**Comment by hpinkos** [comment]
I saw that after I pulled down master, but it went away after I did `npm run build`
