### ISSUE TITLE
request tiles out of range

### ISSUE THREAD

**Issue by cuizx** [AnalyticalGraphicsInc/cesium#3999]
When using GoogleImageryProvider, the request format is somthing like http://..../?x=X&y=Y&z=Z. if the option maxiumLevel is set, e.g.  z=6. the x or y should lie within(0,63), however when continuously zooming in at any point, x or y may exceed 63, while z keep unchanged, which causes an error.

**Comment by cuizx** [comment]
now, it's correct.

**Comment by pjcozzi** [comment]
@cuizx did you mean to re-open this?
