### ISSUE TITLE
Add option to use rhumb lines for geometry

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4000]
Once #3998 gets merged, [example.geojson.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/298108/example.geojson.txt) loads nicely in Cesium but exposes an existing bug we never noticed.  Check out these two screenshots, one from geojson.io and one from Cesium:

geojson.io

![image](https://cloud.githubusercontent.com/assets/1495196/15787704/b980d386-2991-11e6-8ad6-be3fc507e8e6.png)

Cesium

![image](https://cloud.githubusercontent.com/assets/1495196/15787714/c280420a-2991-11e6-83a4-964fa184b1e7.png)

As you can see, Polygons (and other surface geometry) are currently connected with geodesics.  While GeoJSON doesn't specify what the correct behavior is, most users seem to expect rhumb.  We should add an option to all surface geometry to allow for either behavior and then hook up `GeoJsonDataSource` to use it.

**Comment by mramato** [comment]
The next version of the [GeoJSON spec](https://tools.ietf.org/html/draft-ietf-geojson-03) is in its final draft stages (and actually has been approved already I believe).  I haven't read the whole thing yet, but it now explicitly defines hows to connect points to form geometry (and as suspected, Cesium is currently doing the wrong thing).

**Comment by mramato** [comment]
Maybe I missed a conversation somewhere, but it would be nice if this happened long before the mythical 2.0 release we want to do.  We need to make sure we conform to the latest GeoJSON spec.

**Comment by pjcozzi** [comment]
I expect it will happen sooner since we likely need it for 3D Tiles.  Not sure why this is labeled 2.0.

**Comment by hpinkos** [comment]
Sorry, I just labeled it 2.0 because we have a bunch of other geometry issues labeled 2.0

**Comment by alberto-acevedo** [comment]
+1

**Comment by wallw-bits** [comment]
While users may expect lat/lon boxes to be interpolated as rhumb lines, that is probably not true of other shapes. An option in the API would be nice, but the shortest distance between two points is always the geodesic. The 2D map library used by geojson.io is simply rendering a straight line in cartesian space between the 5 points in each box, which is taking advantage of the fact that a Mercator projection is being used (rhumb lines are straight lines in Mercator projections).

If an addition to the API is made, I would highly suggest taking a look at Karney's algorithms as implemented in [GeographicLib](https://geographiclib.sourceforge.io/). His algorithm for geodesics is faster than Vincenty's method and does not have the same issues with antipodal points. There is an ellipsoidal rhumb line algorithm as well.

Our application does its own GeoJSON parsing via another library and detects lat/lon rectangles. We then use `Cesium.RectangleGeometry`, which renders the rectangles as you expect.

**Comment by ggetz** [comment]
Came up on the forum again: https://groups.google.com/forum/#!topic/cesium-dev/_T3vRx1D858

**Comment by mccoy1** [comment]
+1

**Comment by zbennett10** [comment]
+1

**Comment by hpinkos** [comment]
Added in #7492

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/_T3vRx1D858

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4000 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
