### ISSUE TITLE
Documentation contains broken links to private members

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4001]
For example, [ShadowMap](http://cesiumjs.org/Cesium/Build/Documentation/ShadowMap.html) contains a link to Context

Clicking this goes to an 'access denied' page.

**Comment by lilleyse** [comment]
Ah I forgot about that. One solution is to pass `Scene` to `ShadowMap` instead of `Context`. The other is to initialize values on the first frame of the update loop with the frame states's context.

**Comment by hpinkos** [comment]
@lilleyse there aren't any changes you should have to make to your code.  jsDoc should know not to make a link for something that's not there.

**Comment by pjcozzi** [comment]
Duplicate with #4010.
