### ISSUE TITLE
Mapbox Classic will be deprecated

### ISSUE THREAD

**Issue by rominavarela** [AnalyticalGraphicsInc/cesium#4015]
Hi, I have a project using "classic" Mapbox imagery layers, which will be deprecated,
¿Is there any plans to migrate to the new Mapbox?

**Comment by pjcozzi** [comment]
Thanks for the report.  Do you have a link with more info on the deprecation?

**Comment by rominavarela** [comment]
I asked to mapbox support and they told me they will keep such "classic" version "for the forseeable future". I still think cesium should migrate to the new style, which announcement is in https://www.mapbox.com/blog/mapbox-studio-tiles-static/

**Comment by hpinkos** [comment]
Here's the API for getting raster tiles from a style:
https://www.mapbox.com/api-documentation/#retrieve-raster-tiles-from-styles

The URI should look like this:
`https://api.mapbox.com/styles/v1/{username}/{style_id}/tiles/{tileSize}?/{z}/{x}/{y}?access_token={access_token}`

**Comment by sekitaka** [comment]
Hi.
I'm using Cesium.UrlTemplateImageryProvider like following code.

    var MAPBOX_ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN'; 
    var MAPBOX_STYLE_ID = 'YOUR_STYLE_ID'; 
    var MAPBOX_USERNAME = 'YOUR_USERNAME';

    var viewer = new Cesium.Viewer('cesiumContainer');
    var layers = viewer.imageryLayers;
    
    // Mapbox api url
    var url = 'https://api.mapbox.com/styles/v1/' + MAPBOX_USERNAME + '/' + MAPBOX_STYLE_ID + '/tiles/256/{z}/{x}/{y}?access_token=' + MAPBOX_ACCESS_TOKEN;
    
    var customImageryProvider = new Cesium.UrlTemplateImageryProvider({
      url : url
    });
    layers.addImageryProvider(customImageryProvider);

It works for me.

**Comment by bampakoa** [comment]
@hpinkos do you refer to the additional options that should be passed to MapboxImageryProvider, right?

**Comment by pjcozzi** [comment]
Thanks again for the issue, @rominavarela!  Would you like to make the update to Cesium?  For info on contributing, see [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request).  Thanks!

**Comment by bampakoa** [comment]
Is this still valid?

**Comment by hpinkos** [comment]
@bampakoa we haven't made any changes here.  I believe this is something we still want to do, but Mapbox hasn't removed support for the old API for fetching tiles so it hasn't been a priority for us to update to use styles instead.

**Comment by bampakoa** [comment]
@hpinkos I would be happy to help on that if that's ok. Maybe submit a proposal PR for an additional imagery provider?

**Comment by hpinkos** [comment]
Yes, thanks @bampakoa!
