### ISSUE TITLE
Add Cesium version to Sandcastle title bar

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4019]
While we have the `Cesium.VERSION` constant for programmatic access, it would be useful to have Sandcastle have the version in it's title bar as well.  This way if you have a branch or website build open, it's easy to know exactly what version that is.

**Comment by andyfry01** [comment]
@tnewell5 and I are working on this one, we're thinking about adding the version number to the Sandcastle title bar in the following way: 

- Include Cesium.js as a script tag in [/Apps/Sandcastle/index.html](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/index.html)

- Use Dojo templating to include the version number in cesiumTitle div on [line 39](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/index.html#L39)

Are we on the right track with this one? Thank you!

**Comment by emackey** [comment]
Fixed in #4889
