### ISSUE TITLE
How Cesium deal with imagery service of WebMercator Projection?

### ISSUE THREAD

**Issue by lp249839965** [AnalyticalGraphicsInc/cesium#4025]
dear Cesium group:
     I have two question these days and i'm not able to solve it
question 1：
I have found that the VRtheWorldTerrain and STK Terrain both have a different projection from the BingMaps ,ArcGISserver Imagery。How Cesium deal with that,I have read the source code of 1.18，but I have no idea？
question 2:
ArcGisMapServerImageryProvider and BingMaps both have Web Mercator projection，the latitude range from [-85.05，+85.05]. so how cesium deal with the missing latitude？
I am a student interested with virtual earth and I hope you will teach me how to solve these question, Thank you!

**Comment by pjcozzi** [comment]
@lp249839965 See this presentation: [Rendering the Whole Wide World on the World Wide Web](http://cesiumjs.org/publications.html#rendering-the-whole-wide-world).

In the future, please post questions like this on the [Cesium forum](http://cesiumjs.org/forum.html).
