### ISSUE TITLE
TerrainPush Problem

### ISSUE THREAD

**Issue by fxkulou** [AnalyticalGraphicsInc/cesium#4031]
I hava found a TerrainPush js in github,but it is just support cesium 1.2.I think the TerrainPush is a very useful tool to show the pipeline underground。so I want to know ,is there any other methods to show the pipelines underground?

**Comment by pjcozzi** [comment]
@fxkulou the Cesium geometries like polylines should work with negative heights.

In the future, please post general questions to the [Cesium forum](http://cesiumjs.org/forum.html) and use GitHub issues for bugs, features, etc.  For more info, see [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).

**Comment by fxkulou** [comment]
OK,thanks. @pjcozzi
