### ISSUE TITLE
Can't set box's material property to PolylineOutlineMaterialProperty

### ISSUE THREAD

**Issue by superliwei** [AnalyticalGraphicsInc/cesium#4036]
I try to set a box's material property to PolylineOutlineMaterialProperty ,but it goes wrong,here is my code:

```
var entity = viewer.entities.add({
	box:{
			dimensions:new Cesium.Cartesian3(400000,400000,400000),
			material : Cesium.Color.RED.withAlpha(0.5),
			outline : true,
			outlineColor : Cesium.Color.BLACK
		},
		position:Cesium.Cartesian3.fromDegrees(25,44)
});
var materialProperty = new Cesium.PolylineOutlineMaterialProperty();
entity.box.material = materialProperty;
```

other MaterialProperty like `ColorMaterialProperty,CompositeMaterialProperty,GridMaterialProperty,ImageMaterialProperty,PolylineGlowMaterialProperty,StripeMaterialProperty` works fine.

**Comment by hpinkos** [comment]
Hello @superliwei 

PolylineOutlineMaterialProperty only works for polylines, not for other types like boxes.
In the future, please ask questions on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use github issues for bug and feature tracking
