### ISSUE TITLE
Is there any way to hide part of a model?

### ISSUE THREAD

**Issue by Cyperwu** [AnalyticalGraphicsInc/cesium#4037]
Hey, guys
I've been looking for a way to make a profile of a model so that i can directly look insied it and didn't get any progress.would you give me some hints? ; )

Thanks,C

**Comment by pjcozzi** [comment]
Hi @Cyperwu - please ask questions like this on the [Cesium forum](http://cesiumjs.org/forum.html); we only use GitHub issues for bugs and features.  For more info, see [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).  Thanks!
