### ISSUE TITLE
JulianDate issues parsing some dates...

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#405]
I'm not sure why, but the date `11/17/2039 12:00:00 AM UTC` produces a `JulianDate` that is off by one day (November 16 instead of 17).  The problem appears to be in `computeJulianDateComponents` and is most likely a rounding error.  I was able to fix the error (by re-porting some Components code) but that caused other tests to start failing (seemingly due to a rounding error in the other direction).  The below test should pass, but doesn't.

```
it('Construct problem dates', function() {
        var expectedDate = new JulianDate(2466109, 43235.0, TimeStandard.TAI);
        var date = JulianDate.fromDate(new Date('11/17/2039 12:00:00 AM UTC'));
        expect(date).toEqual(expectedDate);
    });
```

**Comment by pjcozzi** [comment]
Fixed in #2949
