### ISSUE TITLE
Being able to zoom in and out through mouse double click events?

### ISSUE THREAD

**Issue by jhu** [AnalyticalGraphicsInc/cesium#4052]
Hello,

Users of Google Earth can zoom in to and out of the globe incrementally by double-clicking on right and left mouse buttons. OpenLayers 2/3 provides the ability to zoom in via double-clicking left mouse button. Will there is a plan on including this feature or similar into the Cesium codebase? Is there a way of doing it with existing codebase?

Thanks

**Comment by hpinkos** [comment]
Hello @jhu 

You can use [ScreenSpaceCameraController.zoomEventTypes](http://cesiumjs.org/Cesium/Build/Documentation/ScreenSpaceCameraController.html#zoomEventTypes) to add more event types that zoom.

If you have further questions, please ask them in our [Forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev).  We use GitHub issues to track bugs and features.  Thanks!
