### ISSUE TITLE
Setting viewer.trackedEntity fails when assigned in onFulfilled callback

### ISSUE THREAD

**Issue by racarate** [AnalyticalGraphicsInc/cesium#4053]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML%20Path.html&label=

I added these lines to the end of the gliding example on Sandcastle:

```
var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
handler.setInputAction(function(movement) {
    if (viewer.trackedEntity === null) {
        viewer.flyTo(path).then(function() { viewer.trackedEntity = path; });               
    } else {
        viewer.trackedEntity = null;
    }
}, Cesium.CameraEventType.LEFT_DRAG);
```

The entity was saved off as a global variable called path:

```
viewer.dataSources.add(Cesium.CzmlDataSource.load(czml)).then(function(ds) {
    path = ds.entities.getById('path');
    viewer.trackedEntity = ds.entities.getById('path');
});
```

Unfortunately, the assignment to viewer.trackedEntity doesn't seem to work when it happens within the onFulfilled callback of the promise's then function.  The camera comes to a halt at some past position of the glider.

The expected behavior is for the camera to track the moving glider, which is what occurs when the assignment to viewer.TrackedEntity is done without using a promise, like this:

```
var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
handler.setInputAction(function(movement) {
    if (viewer.trackedEntity === null) {
        viewer.trackedEntity = path;               
    } else {
        viewer.trackedEntity = null;
    }
}, Cesium.CameraEventType.LEFT_DRAG);
```

**Comment by hpinkos** [comment]
Hello @racarate,

The problem is camera.flyTo doesn't return a promise, it takes a callback function to options.compelte
http://cesiumjs.org/Cesium/Build/Documentation/Camera.html?#flyTo

If you have further questions, please as them on our fourm: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

We use GitHub for tracking bugs and new features we want to add.

Thanks!
