### ISSUE TITLE
Update Cesium repo's README.md to include latest showcases

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4054]
@slchow how do you suggest we handle this?  Do you just want to update README.md once a month timed with the release?

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/README.md

http://cesiumjs.org/demos.html

**Comment by slchow** [comment]
Oh, that's a good suggestion! I'll start doing it monthly.

**Comment by pjcozzi** [comment]
OK, we'll close this issue after the 1.23 release this week.

**Comment by pjcozzi** [comment]
Fixed in #4078.
