### ISSUE TITLE
GeoJSON simplestyle Sandcastle example zooms to the wrong location

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4061]
@bagnell can you take a quick look and see if this is realistic to fix for 1.23 on Friday?

Compare

http://localhost:8080/Apps/Sandcastle/index.html?src=GeoJSON%20simplestyle.html&label=All

to

http://cesiumjs.org/releases/1.22.1/Apps/Sandcastle/index.html?src=GeoJSON%20simplestyle.html&label=Showcases

**Comment by bagnell** [comment]
Zooming to billboard's bounding sphere in 2D when it is clamped to the ground is broken.

@tfili Can you take a look?

**Comment by pjcozzi** [comment]
Just a reminder that this is needed for the release tomorrow.
