### ISSUE TITLE
CesiumTerrainProvider issue with non-earth ellipsoid

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4069]
Reported on the fourm: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/GefAAXtkiZI

Tiles go missing as you get close to the ellipsoid
![image](https://cloud.githubusercontent.com/assets/3451886/16492114/9d2aeed8-3eae-11e6-8b1c-b412874a246d.png)

```
var ellipsoid = new Cesium.Ellipsoid(3376200.0, 3376200.0, 3396190.0);
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: new Cesium.CesiumTerrainProvider({
        url : 'https://assets.agi.com/stk-terrain/world',
        ellipsoid: ellipsoid
    }),
    imageryProvider:  new Cesium.ArcGisMapServerImageryProvider({
        url : 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
    }),
    baseLayerPicker: false,
    mapProjection: new Cesium.WebMercatorProjection(ellipsoid)

});
```

**Comment by emackey** [comment]
@abwood correct me if I'm wrong here.

I believe it is not valid to use pre-processed terrain data, such as `https://assets.agi.com/stk-terrain/world`, on any ellipsoid other than the one it was processed for (WGS84 in this case).  The quantized mesh tiles all have precomputed bounding boxes that are only valid for the original ellipsoid.

**Comment by pjcozzi** [comment]
@emackey you are correct.  I think they are generating their own terrain so you might want to chime in on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/GefAAXtkiZI

**Comment by emackey** [comment]
Moved to https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/25

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/GefAAXtkiZI

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4069 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
