### ISSUE TITLE
working with ray object:Uncaught TypeError: Cannot read property 'x' of undefinedo.multiplyComponents @ Cesium.js:423

### ISSUE THREAD

**Issue by am2222** [AnalyticalGraphicsInc/cesium#4073]
Hi,
I am going to create a circle and in each degree I create a ray and find the intersection of that ray with surrounding objects, 
well, I come up with this code
` 
    var viewer = new Cesium.Viewer('cesiumContainer');
    var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
    handler.setInputAction(function(click) {

            var cartographicPosition = Cesium.Ellipsoid.WGS84.cartesianToCartographic(position);
         

        var x=Cesium.Math.toDegrees(cartographicPosition.latitude);
        var y=Cesium.Math.toDegrees(cartographicPosition.longitude);
       // alert(x);//35
      //  alert(y);//-101
        var radius=0.01;
        var segmants=360;
        var seg=Math.PI*2/segmants;
        var origin=  new Cesium.Cartesian3(x, y, 0);
        var shape = [];
        for (i = 0; i <= segmants; i++) {
            var teta=seg*i;
            var a =x+Math.cos(teta)*radius;
            var b =y+Math.sin(teta)*radius;
            shape.push(a);
            shape.push(b);
            var origin=  new Cesium.Cartesian3(x, y, 0);
            var direction=  new Cesium.Cartesian3(a, b, 0);
            alert(direction.toString());
            alert(origin.toString());
            var ray=new Cesium.Ray(origin, direction);
            alert(ray.toString());
           var intersection = Cesium.IntersectionTests.rayEllipsoid(ray, blueEllipse);
            alert(intersection.toString());
            if(intersection!=undefined){
                  var point = Cesium.Ray.getPoint(ray, intersection.start);
                  alert(point.toString());

            }

           // shape.push(point.x);
           /// alert(point.x.toString());
           // shape.push(point.y);

        }
        shape.push(shape[0]);
        shape.push(shape[1]);
        alert(shape);
        var resultPolygon = viewer.entities.add({
            name : 'result',
            polygon : {
                hierarchy : Cesium.Cartesian3.fromDegreesArray(shape),
                material : Cesium.Color.YELLOW
            }
        });

        viewer.zoomTo(resultPolygon.position);
    }, Cesium.ScreenSpaceEventType.LEFT_CLICK);
    var blueEllipse = viewer.entities.add({
        position: Cesium.Cartesian3.fromDegrees(-101.2660238862044, 35.334352672773285,0.01),
        name : 'Blue translucent, rotated, and extruded ellipse with outline',
        ellipse : {
            semiMinorAxis : 150000.0,
            semiMajorAxis : 300000.0,
            extrudedHeight : 200000.0,
            rotation : Cesium.Math.toRadians(45),
            material : Cesium.Color.BLUE.withAlpha(0.5),
            outline : true
        }
    });`

when I click a loaction a ray must be created and the intersection must be find but this comes up with this error 
`Cesium.js:423 Uncaught TypeError: Cannot read property 'x' of undefinedo.multiplyComponents @ Cesium.js:423f.rayEllipsoid @ Cesium.js:425(anonymous function) @ HelloWorld.html:68v @ Cesium.js:435n @ Cesium.js:435`

where is my mistake?can you please help me find the solution?
thanks

**Comment by shunter** [comment]
`rayEllipsoid` takes an `Ellipsoid`.  `blueEllipse` is an `Entity`.  Please consult the documentation for issues like this:  http://cesiumjs.org/Cesium/Build/Documentation/IntersectionTests.html

In the future, please ask questions like this on the [Cesium forum](http://cesiumjs.org/forum.html); we only use GitHub issues for bugs and features.
