### ISSUE TITLE
Camera flight issues

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4075]
The below Sandcastle example is a simple save/restore camera view that exposes two issues in Cesium.

1. Flights that start far away from their destination and end up on the ground will cause the camera to collide with terrain while it is in flight. This causes the camera to end up wherever the terrain was loaded when it collided and not the end destination.

2. I think the minimum distance is being taken into account differently during camera flights than it does during camera motion. This means if you move the camera close to the ground with a horizon view, save the settings, and then do a flight; you end up in a difference location.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/world',
    requestWaterMask : true,
    requestVertexNormals : true
});
viewer.terrainProvider = cesiumTerrainProviderMeshes;

var view;
var camera = viewer.scene.camera;

Sandcastle.addToolbarButton('Store View', function(){
    view = {
        destination : Cesium.Cartesian3.clone(camera.positionWC),
        orientation : {
            heading: camera.heading,
            pitch: camera.pitch,
            roll: camera.roll
        }
    };
});

Sandcastle.addToolbarButton('Load View', function(){
    camera.flyTo(view);
});
```

Using the above code, fly to San Francisco and create a horizon view right up against the ground.  Storing and loading the view won't match.

Stored view
![image](https://cloud.githubusercontent.com/assets/1495196/16503183/e3bf874c-3edf-11e6-80bf-25ddb7634cd4.png)

Result after flight
![image](https://cloud.githubusercontent.com/assets/1495196/16503190/eadc7094-3edf-11e6-87e7-e3d6df721ed1.png)

**Comment by pjcozzi** [comment]
@mramato thanks for narrowing this down.

@bagnell can you take a look soon since this is affecting demos.  Perhaps it is as simple as disabling collision detection and minimum distance during flights?
