### ISSUE TITLE
Black Marble texture does not wrap around the earth completely

### ISSUE THREAD

**Issue by andriivarhanov** [AnalyticalGraphicsInc/cesium#4079]
It cat be seen here http://cesiumjs.org/releases/1.23/Apps/CesiumViewer/index.html

Screenshot for reference
![image](https://cloud.githubusercontent.com/assets/5204821/16535493/61c803a6-3ff0-11e6-946f-75714d427cef.png)

Please advise on if there any turnaround exist

**Comment by hpinkos** [comment]
Thanks @andreyvarganov! I'm not sure if this is a problem with the imagery or a problem with how we add it to he globe.  It looks like it's been this way for a while though.

@mramato do you know what the problem might be?

**Comment by mramato** [comment]
This appears to be a problem with the data itself and has been there for at least a year (I tried 1.10 and it had the same issue).  I have a different version of the tiled imagery and it works fine. So this is a problem with sample data on the website and not Cesium itself.

The sample Black Marble is out of date for other reasons as well, we will probably take care of this as part of a larger data migration when all hosted sample data gets reorganized as part of our cesiumjs.com work.

**Comment by hpinkos** [comment]
Closing this because iit is an issue with the data, not a problem with Cesium
