### ISSUE TITLE
KML billboard alignment problem introduced in 1.23

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4082]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/U6Q74ewtnQM
See the forum post for the example kmz file

In 1.22, the billboard is aligned center to it stays in line with the polyline
![1 22](https://cloud.githubusercontent.com/assets/3451886/16585462/ff0285ec-428e-11e6-8302-d78ed552142c.gif)

In 1.23, it doesn't match up anymore
![1 23](https://cloud.githubusercontent.com/assets/3451886/16585463/0231d4a2-428f-11e6-98d7-0af92fd1ada6.gif)

**Comment by hpinkos** [comment]
@tfili do you think this is related to height reference changes you added?

**Comment by tfili** [comment]
@hpinkos It could be. I'll look into it.
