### ISSUE TITLE
Scene.pickPosition support for 2D and CV

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4084]
Requested on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/IKB3Owx1f58

Right now the pick position Sandcastle example doesn't to anything in CV and it throws a DeveloperError in 2D

**Comment by pjcozzi** [comment]
CC #4572

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/d/msg/cesium-dev/zkb3kXLOQfQ/6tNIVx5bAwAJ
