### ISSUE TITLE
Chrome dev tools loading incorrect source map (unminified build)

### ISSUE THREAD

**Issue by slozier** [AnalyticalGraphicsInc/cesium#4094]
The earcut library has a source mapping url in the comments
```
//# sourceMappingURL=data:application/json;charset=utf-8;base64,...
```
When loading the unminified build in the Chrome dev tools it tries to be smart and picks this up as the source mapping for Cesium.js (which obviously it isn't).

**Comment by laurensdijkstra** [comment]
Yes I also experience this problem. Is it a bug or a possible configuration issue on my side?

**Comment by mramato** [comment]
I just opened #4169 to fix this issue, if you have a chance to try it out and report back, that would be great.  Thanks.

**Comment by slozier** [comment]
@mramato :+1:

**Comment by laurensdijkstra** [comment]
Works for me! Clicking on a line number in an exception now gets me to the line in the Cesium.js file like it should. Breakpoints also work again.
