### ISSUE TITLE
Enable Greenkeeper for Cesium

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#4102]
[Greenkeeper](https://greenkeeper.io/) is awesome,  It automatically runs your tests against new dependencies released on npm and opens a pull request when:
* The new version _isn't_ included in your version range in package.json, so you won't get it automatically, or
* You will get the new version automatically because it's in your version range, but it breaks your build or tests.

We should enable it in Cesium.  It takes about 30 seconds and the only reason I haven't done it already is because you need to have admin access to the rep to do it.  Here's the super simple procedure:
https://greenkeeper.io/#getting-started

Here's an example of the sort of pull request it will open:
https://github.com/NICTA/nationalmap/pull/283

**Comment by pjcozzi** [comment]
Sounds good, thanks for sharing.

@mramato do you want to look at this as part of the Node Guide?

**Comment by mramato** [comment]
I looked at this at one point and at the time we were doing a good job of upgrading our dependencies regularly. However, since that's not true lately, I'm willing to give it a shot.  Worst case we can disable it later on.

Silly question for @pjcozzi, but does this have CLA implications since a bot would be opening a PR?  I assume not since AGI is "in control" of the bot.

**Comment by pjcozzi** [comment]
> does this have CLA implications since a bot would be opening a PR?

No concern.

**Comment by kring** [comment]
> I looked at this at one point and at the time we were doing a good job of upgrading our dependencies regularly.

Well, that's not really the point of Greenkeeper anyway.  Staying up to date is easy in a sense.  Just use super-loose version specifications (such as `*`) and you'll always be up to date!

Where Greenkeeper shines is in detecting incompatibilities with new versions in a controlled fashion.  Let me tell you a story.

TerriaJS supports IE9, and we run the automated tests (stop laughing @pjcozzi, we have a decent test suite now!) on it on every commit using Sauce Labs.  Recently, the tests started failing on IE9.  But it wasn't just a normal failure, it was more like they wouldn't even start.  The weird thing is that when we built and ran the tests locally, they passed, even on IE9.  Many hours of debugging later, we finally figured out that socket.io, which is used by Karma, released a new minor version that accidentally broke compatibility with IE9.

So we spent several hours doing difficult debugging.  Here's what happened to a project that had the same problem but that was using Greenkeeper:
https://github.com/testem/testem/pull/907

Sweet!  That was the first time I heard of Greenkeeper, and it made me a believer.

> does this have CLA implications since a bot would be opening a PR?

We had the same question, and even though it seemed a bit pedantic we decided to email the Greenkeeper folks.  Their response:

> if an email is good enough for you, I can hereby verify that Greenkeeper PRs are in the LICENSE of the project, and whatever else your CLA needs ;)
> 
> If you need us to submit a CLA somewhere as the Greenkeeper Account, we can do that too :)

We decided that was good enough and didn't take them up on formally signing the CLA.

**Comment by mramato** [comment]
OK, I turned it on so we'll see how it goes.  We definitely can't merge it's "update all" PR because some of our packages need to stay on older versions, but I guess we'll get other packages one-at a time?

**Comment by kring** [comment]
Edit the PR to revert packages that need to stay at their current versions, then merge it.  I'm not sure if it will be smart enough to open a failing PR for upgrading each of the remaining dependencies (that'd be nice), but it will definitely do that for future versions.  i.e. if you need to stay on version 1.0.2 because 1.0.3 introduced a bug, and then 1.0.4 comes out, Greenkeeper will automatically try it and let you know whether 1.0.4 is still broken or if it fixed the problem (assuming your tests fail when there's a problem, of course).

**Comment by mramato** [comment]
All dependencies that we can upgrade) have been updated to their latest version and Greenkeeper seems to be working as expected.
