### ISSUE TITLE
Remove MapQuest-OpenStreetMap from Imagery Picker

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4109]
Good beginner issue, anyone want to try this for the next release?

See https://mapzen.com/blog/closing-mapquest-open/

![image](https://cloud.githubusercontent.com/assets/782098/16789049/0844a114-4878-11e6-80c1-34847fbeb586.png)

**Comment by andyfry01** [comment]
Hey Patrick, 

I'd like to help you out with this. I'm a first time contributor to the project and new to open source, is there anything in particular that I should know before starting work on this? 

Thanks,
Andy

**Comment by hpinkos** [comment]
Hi @andyfry01!  Thanks for looking into this.  The MapQuest imagery provider is added to the base layer picker in [createDefaultImageryProviderViewModels](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/BaseLayerPicker/createDefaultImageryProviderViewModels.js) 

You'd just have to go in and erase the code that adds it to the `providerViewModels` array

**Comment by andyfry01** [comment]
Great, thanks Hannah! I was actually poking around in there already, I should have the pull request finished pretty soon.

**Comment by pjcozzi** [comment]
Leave labeled `next release`, but push for 1.24.

**Comment by mramato** [comment]
@andyfry01, this was fixed in #4159 so that it can go out with today's release.  We're always excited to have new contributors, so hopefully you can find some other pull requests to open.  Thanks. in advance.
