### ISSUE TITLE
Tutorial for Geometry and Appearances has a bad link

### ISSUE THREAD

**Issue by thinkpadder1** [AnalyticalGraphicsInc/cesium#4117]
[Link to tutorial](http://cesiumjs.org/tutorials/Geometry-and-Appearances/)

Part in question:
> Appearances also define the full [render state](http://cesiumjs.org/Cesium/Build/Documentation/RenderState.html), which controls the GPU’s state when the primitive is drawn. 

The link leads to:
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C0AEA9E050CF9290</RequestId>
<HostId>
+E/U9AcdwLfrjK3Xja06PWieibs4wJLF/bdfMNbgXnu9RAw5MziWyYPBEpMBN5hoCYse6P5dj6c=
</HostId>
</Error>`

**Comment by hpinkos** [comment]
Thanks @thinkpadder1!  It looks like we forgot to remove this link when render state was made private.

I've updated the page, it should be updated on the website soon.
