### ISSUE TITLE
GLTF model cache

### ISSUE THREAD

**Issue by kartblanch** [AnalyticalGraphicsInc/cesium#4119]
Hello!

I had a problem ... there gltf model and I need to use it many hundreds of times. As it is possible to cache, to use gltf once? Thanks.

**Comment by lilleyse** [comment]
Yes this is possible, glTF models are automatically cached so it is no problem loading the same model hundreds of times.

In the future, you can post questions like this to our forum https://cesiumjs.org/forum.html since we use github issues mainly for bug reports.
