### ISSUE TITLE
How to push ground?

### ISSUE THREAD

**Issue by outlier888** [AnalyticalGraphicsInc/cesium#4129]
I see globe.depthTestAgainstTerrain  , can it work like [cesium-groundpush-plugin](https://github.com/NICTA/cesium-groundpush-plugin) ?

**Comment by hpinkos** [comment]
Hello @outlier888 
Cesium does not currently have this support.
In the future, please ask questions on [our forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev).  We use GitHub for bug tracking and planning new features.
Thanks!

**Comment by outlier888** [comment]
I‘m sorry for this , @hpinkos , but we can't use google in mainland China , someone used issues like blogs [lifesinger/blog](https://github.com/lifesinger/blog/issues)
Thanks for you answer !

**Comment by hpinkos** [comment]
Thanks @outlier888!  Sorry, I wasn't aware of the restricted access there.
Cesium would like to support behavior similar to what the ground push plugin does in the future, but we're really focused on implementing the 3D tiles specification at the moment. I'm not sure how long it will be before we are able to add it.

**Comment by outlier888** [comment]
Maybe @hpinkos can tell me to upgrade cesium-groundpush-plugin . It version too old support only Cesium1.2 ,  GlobeSurfaceShaderSet.prototype.getShaderProgram part have too much changes, I can't understand the principle, you can simply tell me what's going on , or how to understand?

**Comment by happytoTom** [comment]
@outlier888 Have you solved the problem, please?

**Comment by ggetz** [comment]
@happytoTom @outlier888 While we don't support all the features of the groundpush-plugin, we just implemented [clipping planes on terrain](https://github.com/AnalyticalGraphicsInc/cesium/pull/5996) which would allow you to cut away a rectangle of terrain.
