### ISSUE TITLE
why  so many shadow on scene？

### ISSUE THREAD

**Issue by w67735287** [AnalyticalGraphicsInc/cesium#4140]
I am Transformation data from max file
when I start， there are so many scene shadow repeat on the picture 
 
![qq 20160721183346](https://cloud.githubusercontent.com/assets/20577014/17019963/a5d22b54-4f71-11e6-8dc6-2cb5e4c14b5e.jpg)

is there any problem on data or program?
thanks!!!

**Comment by hpinkos** [comment]
Hello,

Please use our forum to ask questions like this: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub issues for bug tracking and feature planning.

Thanks!
