### ISSUE TITLE
Instanced models are not being cached correctly between different ModelInstanceCollections

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4144]
If multiple i3dm tiles are loaded, they all use the same Model cache key which is causing tiles not to render.

**Comment by lilleyse** [comment]
Quick update: I'm only seeing the wrong behavior for certain models. This leads me to believe it's not related to the cache key but instead something with the shader transformations.

**Comment by pjcozzi** [comment]
I don't know what it could be with the shader; only the program should be cached, not the uniforms (which is where I expect the culprit would be).

**Comment by lilleyse** [comment]
This was a problem in the instanced model conversion step, not in Cesium.
