### ISSUE TITLE
3D Tiles cache not cleaning up fully

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4147]
@lilleyse can you please look at this after SIGGRAPH?

@arneschilling @clausnagel have the full details and a potential fix:

https://github.com/virtualcitySYSTEMS/cesium/commits/release-v3.2 (see ceb77bc and 2c6c919).

**Comment by pjcozzi** [comment]
@lilleyse can you please evaluate this?

**Comment by lilleyse** [comment]
After some thorough testing our cache system seems to be working properly. The only discrepancy was the `numberReady` statistic included empty tiles which made it seem like tiles were not being unloaded properly. This is fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/4278.
