### ISSUE TITLE
Question regarding gltf modelmaterial lighting + clamping gltf model to terrain

### ISSUE THREAD

**Issue by lyaunzbe** [AnalyticalGraphicsInc/cesium#4149]
Hello!

I am using the OBJ2GLTF converter (https://github.com/AnalyticalGraphicsInc/OBJ2GLTF) to load in a gltf model and view it in cesium alongside terrain. Two issues I am running into:

(1) The position/normal based lighting on the model is too dark when I tilt my camera view. Is their any way to disable the material's position based lighting entirely? I know I can do this in the gltf  glsl fragment shader (and have successfully done so) but it would be far more convenient to do it from cesium itself in JS.

(2) I've been loading my model in like so:

```
var center = Cesium.Cartesian3.fromDegrees(-1.3619113125000002,51.84183939351851, 0);
var heading = 0.0;
var pitch = 0.0;
var roll = -Cesium.Math.PI_OVER_TWO;
var modelMatrix = Cesium.Transforms.headingPitchRollToFixedFrame(center, heading, pitch, roll);

var model = scene.primitives.add(Cesium.Model.fromGltf({
    url : 'palace.gltf',
    modelMatrix : modelMatrix,
    scale : 1.0,
    castShadows: false,
    receiveShadows: false,
}));
```

The issue I've been noticing is that unless I adjust the Z/height of my `center` to be above the z of the terrain at that lat/lng, rotating the camera view makes it look like the 3D model is moving.  If I give the `center` a height that is large enough, the 3d model does stay fixed in place, as it should. In general, are there any utility functions that can help me with 'clamping' my 3d model to the terrain appropriately? Should I simply be getting the highest Z of the terrain in a certain bounding box and use that as my center Z?

Let me know if you need any additional resources from me. Really appreciate any help/guidance! Thanks!

**Comment by lyaunzbe** [comment]
regarding (2)

I've also tried using the heightReference on my model like so:
```
var center = Cesium.Cartesian3.fromDegrees(-1.3619113125000002,51.84183939351851);
var heading = 0.0;
var pitch = 0.0;
var roll = -Cesium.Math.PI_OVER_TWO;
var transform = Cesium.Transforms.headingPitchRollToFixedFrame(center, heading, pitch, roll);
var model = scene.primitives.add(Cesium.Model.fromGltf({
    url : 'palace.gltf',
    modelMatrix : transform,
    scale : 1.0,
    castShadows: false,
    receiveShadows: false,
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
    scene: scene
}));
```
However this does not fix the issue, though perhaps I'm not using heightReference correctly (documentation on it is fairly sparse).

Here's a gif to better explain the unwanted behavior Im talking about:
![d5mcwkuwcd](https://cloud.githubusercontent.com/assets/28675/17121720/7a25bb76-528a-11e6-8aca-9a09a624ada1.gif)

**Comment by lilleyse** [comment]
> (1) The position/normal based lighting on the model is too dark when I tilt my camera view. Is their any way to disable the material's position based lighting entirely? I know I can do this in the gltf glsl fragment shader (and have successfully done so) but it would be far more convenient to do it from cesium itself in JS.

In the meantime, I added a `--cesium` flag for obj2gltf, which will use the sun as the light source. It could be possible to edit the shader on load time, but there are many edge cases in determining whether the model is using position based lighting, and then editing the shader in the right place. Hopefully the flag is helpful though.

> (2)

Yeah `heightReference` is a pretty new feature. Maybe @tfili will have a better idea. 

> The issue I've been noticing is that unless I adjust the Z/height of my center to be above the z of the terrain at that lat/lng, rotating the camera view makes it look like the 3D model is moving. If I give the center a height that is large enough, the 3d model does stay fixed in place, as it should.

I'm not sure why this would be happening. I did a quick test and didn't notice that.

**Comment by lyaunzbe** [comment]
> In the meantime, I added a --cesium flag for obj2gltf, which will use the sun as the light source. It could be possible to edit the shader on load time, but there are many edge cases in determining whether the model is using position based lighting, and then editing the shader in the right place. Hopefully the flag is helpful though.

Thank you @lilleyse! Will try out the flag and let you know how it goes!

> I'm not sure why this would be happening. I did a quick test and didn't notice that.

Did you use the sandcastle to test? If so, can I trouble you to send me the code you used for testing? That way I can try to recreate what's happening with my model using your code potentially.

Huge thanks again, everyone on the cesium/agi team always respond so fast and are super helpful 😄

**Comment by lilleyse** [comment]
Sorry for the delay...

Here's the Sancastle code I've tried (the camera controls are a little touchy):

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/world',
    requestWaterMask : true,
    requestVertexNormals : true
});
viewer.terrainProvider = cesiumTerrainProviderMeshes;

// Place height at 100, but will be clamped to ground
var center = Cesium.Cartesian3.fromDegrees(-1.3619113125000002,51.84183939351851, 100);
var heading = 0.0;
var pitch = 0.0;
var roll = 0.0;
var transform = Cesium.Transforms.headingPitchRollToFixedFrame(center, heading, pitch, roll);
var model = scene.primitives.add(Cesium.Model.fromGltf({
    url : '../../SampleData/models/CesiumGround/Cesium_Ground.gltf',
    modelMatrix : transform,
    scale : 1.0,
    castShadows: false,
    receiveShadows: false,
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
    scene: scene
}));

model.readyPromise.then(function(model) {
    // Play and loop all animations at half-speed
    model.activeAnimations.addAll({
        speedup : 0.5,
        loop : Cesium.ModelAnimationLoop.REPEAT
    });

    var camera = viewer.camera;

    // Zoom to model
    var controller = scene.screenSpaceCameraController;
    var r = 2.0 * Math.max(model.boundingSphere.radius, camera.frustum.near);
    controller.minimumZoomDistance = r * 0.5;

    var center = Cesium.Matrix4.multiplyByPoint(model.modelMatrix, model.boundingSphere.center, new Cesium.Cartesian3());
    var heading = Cesium.Math.toRadians(230.0);
    var pitch = Cesium.Math.toRadians(-20.0);
    camera.lookAt(center, new Cesium.HeadingPitchRange(heading, pitch, r * 2.0));
}).otherwise(function(error){
    window.alert(error);
});
```

It's a bit hard to tell by your gif, but is your model flat or does it conform to the terrain? If it's flat, I could see this being a problem since the model's position is clamped to the ground but the geometry isn't warped to fit it, which could explain why most of it appears under the ground.

**Comment by lyaunzbe** [comment]
@lilleyse  No worries!

It's definitely not flat, my model is of the palace you see in the sat. imagery. I'm thinking that because using the center is not perfectly accurate at georeferencing the model, parts of it are perhaps intersecting with the terrain. Could that cause this? I have attached the GLTF model of the palace for you to try yourself (note that the texture for the model is packed into the gltf file). Thanks, really appreciate it!

GLTF model of [blenheim palace](http://d.pr/f/12wvB)

**Comment by lilleyse** [comment]
I've been trying without `heightReference` and using a height of 200. With `viewer.scene.globe.depthTestAgainstTerrain = true;` it looks like the lat/long is slightly off compared to the imagery. Maybe just tweaking the values a bit with help.

![capture](https://cloud.githubusercontent.com/assets/915398/17302709/7c62a050-57eb-11e6-99e3-19fc262fd69f.JPG)

**Comment by tfili** [comment]
@lyaunzbe The issue is that all your Z values are negative, so the building is rendered under the terrain. The origin of the model's reference frame is placed at the specified Lat/Lon at the height of the terrain. Since all your Z values are negative, you'll need to use a `heightReference` of `RELATIVE_TO_GROUND` and specify the offset of where the actual bottom of the building is.

**Comment by lyaunzbe** [comment]
@lilleyse I've moved it by hand to be more or less in position with the following coordinates 
```new Cesium.Cartesian3(3947846.3182381927,-93801.72103658345``` however it still does not work with ```heightReference: Cesium.HeightReference.CLAMP_TO_GROUND```. I'm thinking of a work around and would it be possible for me to somehow see if the bounding box of the model primitive intersects with the terrain so I could measure the difference and just set the height manually using that?

**Comment by lyaunzbe** [comment]
@tfili ahh. do you mean the actual mesh vertices/geometry have negative values? I will try using relative_to_ground, but where do I apply this 'offset'?  Or does this just mean setting the height of the center?

**Comment by lyaunzbe** [comment]
Also, is there no simple way to create a bounding box around a primitive/model that takes the object's height into account?

**Comment by pjcozzi** [comment]
Can this discuss move to the [Cesium forum](http://cesiumjs.org/forum.html) or is there there a bug?

**Comment by lyaunzbe** [comment]
Yep, sorry about that, closing the issue
