### ISSUE TITLE
WMTS layer rendered in wrong location/scale

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#4154]
The following images show right (QGIS) and wrong (Cesium head).  Server is private.  Capabilities document is attached also.

[C0007424-00_wmts-getcapabilities.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/387049/C0007424-00_wmts-getcapabilities.zip)

![wmts_visibility_qgis](https://cloud.githubusercontent.com/assets/4126790/17190537/445c08b6-5414-11e6-9c67-b4276cca0db7.png)
![wmts_visibility_cesium](https://cloud.githubusercontent.com/assets/4126790/17190545/475cd4e6-5414-11e6-99d8-cc4d4bfeabe8.png)

**Comment by pjcozzi** [comment]
@GatorScott is this or #4158 urgent?

**Comment by GatorScott** [comment]
This turns out to be user error.  I failed to set the tiling scheme to Geographic rather than the default WebMercator.
