### ISSUE TITLE
CZML Polygon - Intervals, Availability sandcastle example broken in 1.23

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4160]
The "Dynamic Polygon with Intervals" shows up in [1.22.1](http://cesiumjs.org/releases/1.22.1/Apps/Sandcastle/index.html?src=CZML%20Polygon%20-%20Intervals,%20Availability.html&label=CZML) but not in [1.23](http://cesiumjs.org/releases/1.23/Apps/Sandcastle/index.html?src=CZML%20Polygon%20-%20Intervals,%20Availability.html&label=CZML)

@shunter is this related to CZML changes you recently made?

**Comment by shunter** [comment]
Not that I can tell.  Stepping through in the debugger, the entity properties appear to be evaluating to the correct values, and the options passed to PolygonGeometry look correct to me.  The code changed significantly between the two versions as a result of #3903, though, so I would look there first.

**Comment by hpinkos** [comment]
Thanks for taking a look @shunter!
@tfili, could you maybe look into this?

**Comment by lilleyse** [comment]
The demo is still broken in master.

**Comment by mramato** [comment]
Should be fixed in linked PR.
