### ISSUE TITLE
Use some sort of LOD for glTF Models

### ISSUE THREAD

**Issue by laurensdijkstra** [AnalyticalGraphicsInc/cesium#4197]
When spawning lots of glTF Models, performance is affected badly. This will be probably alleviated by the Model instancing features that are planned. But it might be desirable use some sort LOD method for glTF Models. I do not have enough insight in the LOD methods the glTF format provides, but I have read that glTF does support some sort of LODing. 

Maybe users should just switch Models manually based on the distance to the Camera. What are your thoughts on this matter?

**Comment by likangning93** [comment]
You might be interested in 3D Tiles: https://github.com/AnalyticalGraphicsInc/3d-tiles

A single 3D tile can be a model with a bounding box and an "error" value indicating how different the tile's model is from a more detailed version. Nesting a bunch of tiles with different LODs of the same model can get you something very much like a hierarchical LOD, and Cesium will automatically render different LODs when the camera is at different distances.

One other detail that I think isn't in the spec yet, there's also a [branch](https://github.com/AnalyticalGraphicsInc/cesium/tree/3d-tiles-transform) in Cesium for 3D Tile hierarchies with a transformation at the top so you can more easily place a tileset somewhere on the globe.

**Comment by hpinkos** [comment]
@laurensdijkstra I'm going to close this issue since it is something we are already working on in the 3D Tiles branch.

If you have any questions about 3D tiles or want to know more information, check out this forum post: https://groups.google.com/d/msg/cesium-dev/tCCooBxpZFU/7hxT_E4pGgAJ

Thanks!

**Comment by pjcozzi** [comment]
@laurensdijkstra for an example of the LOD approach you suggested with 3D Tiles, see https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/tree/master/tilesets/TilesetWithDiscreteLOD

**Comment by laurensdijkstra** [comment]
@likangning93  @hpinkos @pjcozzi Thanks for the suggestion!
