### ISSUE TITLE
The intro https://cesiumjs.org/tutorials/cesium-up-and-running/ does seem to show the outline

### ISSUE THREAD

**Issue by CMCDragonkai** [AnalyticalGraphicsInc/cesium#4198]
Following the intro https://cesiumjs.org/tutorials/cesium-up-and-running/ doesn't appear to show the outline of the polygon? I downloaded the zip file, extacted it, ran `npm install` then `node server.js`, and navigated to the hello world example. But no outline at all? What's happening here?

**Comment by hpinkos** [comment]
Hello @CMCDragonkai 
Please use our forum to ask questions like this: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub for tracking bugs and new features.

Sorry, I'm not sure what you're asking. There aren't any polygons in that tutorial.
However, if you are trying to draw a polygon with an outline, set the property `height: 0`.  Polygons default to draw on terrain, and we don't have support for outlines on terrain.  Setting the height forces it to draw on the ellipsoid where we do have outline support.

If you have a follow up question, please use the forum.  Thank you!
