### ISSUE TITLE
billboard and label still scale by distance after set scaleByDistance to undefined

### ISSUE THREAD

**Issue by yqrashawn** [AnalyticalGraphicsInc/cesium#4203]
```javascript
            img.onload = () => {
                const board = billboard.add({
                    position: options.modelMatrix,
                    id: options.id,
                    show: true,
                    pixelOffset: Cesium.Cartesian2.ZERO,
                    eyeOffset: Cesium.Cartesian3.ZERO,
                    scaleByDistance: undefined,
                    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
                    pixelOffsetScaleByDistance: undefined,
                    image: img,
                    scale: 0.06,
                });
                const poi = new POI(board, options);
                if (callback) {
                    callback(poi);
                }
            };

```
And the img billboard still scale when I scroll the camera far and become bigger than the CesiumMilkTruck. So is this a bug or it's not suppose to be like that?

**Comment by hpinkos** [comment]
Thanks @yqrashawn!  Can you please update your code example so it runs in [Sandcastle](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html)?  That'll make it easier for us to reproduce the issue.

**Comment by yqrashawn** [comment]
![1](https://i.imgur.com/mKTSQfd.png)  ![2](https://i.imgur.com/bF8Ei5t.png) It still scale, bigger than earth in the end. I just want it to be the same like models.

**Comment by hpinkos** [comment]
I think you're misunderstanding what the scaleByDistance property is used for.  When it is defined it makes the billboard a bit smaller when you zoom out and a bit bigger when you zoom in.

I think you are looking for the [sizeInMeters](http://cesiumjs.org/Cesium/Build/Documentation/Billboard.html) property.  This will keep the billboard a fixed size.

In the future, please use our [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev) if you have questions.  We use GitHub exclusively for bug tracking and feature planning.

**Comment by yqrashawn** [comment]
@hpinkos Really thanks!
