### ISSUE TITLE
Cesium render error on valid KML.

### ISSUE THREAD

**Issue by dwhipps** [AnalyticalGraphicsInc/cesium#4204]
I have validated the KML (http://tinyurl.com/gvvjlab) and opened it in Google Earth and it seems to be well formed (I think), but Cesium complains about a rectangle crossing the pole:

"_DeveloperError: Rotated rectangle is invalid.  It crosses over either the north or south pole._"

**SANDCASTLE**:
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=ecd9c57033801798f9bc1ac4a1120981

Here's a direct link to my file: ([Land Surface Temp KML File](http://earthdata.layeredearth.com/Layers/Earth/Climate Change/Global Warming/land surface temperature - January - 2014.kmz))

**Comment by hpinkos** [comment]
Hi @dwhipps 
What version of Cesium are you using?  I added your KMZ file to our current master and it had no problem

**Comment by dwhipps** [comment]
Locally I'm using the latest release (1.24?), but if you click that Sandcastle link above, you'll see the bug there too, so whatever version is running on Sandcastle exhibits the issue.

**Comment by hpinkos** [comment]
Ah, thanks @dwhipps!  I didn't see the problem when I added the KML to another application, but I did when I added it to Sandcastle.  It seems there was a floating point error that happened intermittently when rotation was explicitly set to `0`. 

I submitted a fix in this PR #4206

**Comment by dwhipps** [comment]
Great. Thanks!
