### ISSUE TITLE
Use Cesium sun as lightsource for material

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4207]
From https://github.com/AnalyticalGraphicsInc/collada2gltf-web-service/issues/2 by @laurensdijkstra:

> When converting Collada models to glTF via the web service you provide and then displaying the model in Cesium makes the model unaffected by the lighting direction of the sun. I saw that the obj2gltf library added a --cesium flag to address this issue. Would it be possible for the web service to provide a similar feature?

**Comment by OmarShehata** [comment]
This already works for glTF 2. Should we close @pjcozzi ?

**Comment by pjcozzi** [comment]
Up to @lilleyse

**Comment by lilleyse** [comment]
Yeah fine to close.
