### ISSUE TITLE
1.24 can not add break point

### ISSUE THREAD

**Issue by lp249839965** [AnalyticalGraphicsInc/cesium#4221]
use chrome,1.24 unminfied cesium.js
when i add break point at any line in the file of cesium.js,it will directly jump to the end line of earcut.js。
![image](https://cloud.githubusercontent.com/assets/16017103/17842082/aee6a528-6851-11e6-875a-613ef36099cd.png)

**Comment by hpinkos** [comment]
Hello,  
I think this issue has been fixed in this PR: #4097
It will be available in the next release.  If you're still seeing problems then, feel free to re-open the issue.

Thanks!
