### ISSUE TITLE
Polygon outlineWidth property is ignored

### ISSUE THREAD

**Issue by pierotofy** [AnalyticalGraphicsInc/cesium#4223]
While running this code:

```
Cesium.Math.setRandomNumberSeed(1234);

var viewer = new Cesium.Viewer('cesiumContainer', { infoBox : false });
var entities = viewer.entities;
var positions = Cesium.Cartesian3.fromDegreesArray([
            -107.0, 31.0,
            -107.0, 39.0,
            -97.0, 39.0,
            -97.0, 31.0
        ]);

entities.add({
    polygon : {
        height: 0,
        hierarchy : new Cesium.PolygonHierarchy(positions),
        material : Cesium.Color.BLUE,
        outline: true,
        outlineColor: Cesium.Color.RED,
        outlineWidth: 50
    }
});


viewer.zoomTo(viewer.entities);
```

Note the outlineWidth set to 50, which should draw a fairly thick outline.

But the outline is fairly thin, and doesn't change if you modify the value to something else, say 1, or 200.

![image](https://cloud.githubusercontent.com/assets/1951843/17859860/e8aa7f1a-6850-11e6-912d-da4612d73916.png)

**Comment by hpinkos** [comment]
Hello @pierotofy,
Sorry, but line width is something that is dependent on the browser's WebGL implementation, so it's a little beyond our control.  
I believe a wider line is currently only supported on Safari?  I'm not quite sure.

**Comment by pierotofy** [comment]
Should this be mentioned somewhere in the docs?

**Comment by mramato** [comment]
See this post: http://stackoverflow.com/a/25405483/3191039  It's a limitation of the WebGL implementations on Windows (but is completely in spec).  It works on standard OpenGL implementations (which means phones, Linux, Mac, and etc.)

The maximum value on the current system is documented and exposed via `scene.maximumAliasedLineWidth` and this limitations is also mentioned in our [Visualizing Spatial Data](http://cesiumjs.org/tutorials/Visualizing-Spatial-Data/) tutorial.

**Comment by pierotofy** [comment]
Ok! Thanks to both for the info!
