### ISSUE TITLE
Multiple meshes - No indices

### ISSUE THREAD

**Issue by konashredbiker** [AnalyticalGraphicsInc/cesium#4237]
Storing multiple meshes in one glTF without indices and loading it in Cesium results in an error. Only the first mesh shows up. While debugging Cesium, I can see that multiple meshes are loaded and this error message occurs while rendering:

[.CommandBufferContext]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 1

When debugging Cesium in Context.js line 934 [context._gl.drawArrays(primitiveType, offset, count);] a different offset is used than defined in the glTF file.
In the example ([testMulti.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/439284/testMulti.zip)) three Cubes are saved, but when loading the file only the first one is rendered.

I already posted an issue in the glTF repo (https://github.com/KhronosGroup/glTF/issues/694), but it seems that the model or the glTF spec is not the problem.

**Comment by pjcozzi** [comment]
Thanks for the detailed report, @konashredbiker.

@lasalvavida can you please look at this _after_ the glTF 1.0.1 updates?

**Comment by konashredbiker** [comment]
Could this be labeled as "bug bash" so someone can take a look at this issue?

**Comment by hpinkos** [comment]
Hi @konashredbiker,  we've labeled this issue for the bug bash.  It might be a little larger scope than we can get to during the event, but this will at least put it on our radar to look into it soon if we can't get to it then.  Thanks!
