### ISSUE TITLE
Map projection broken with non-earth ellipsoid

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4244]
![mapprojection](https://cloud.githubusercontent.com/assets/3451886/18056170/cfde3bec-6dd8-11e6-9d6b-ef71483fb9f0.gif)

It looks like the globe and atmosphere is the correct size, but the imagery is at WGS84

``` javascript
var ellipsoid = Cesium.Ellipsoid.MOON;
var viewer = new Cesium.Viewer('cesiumContainer', {
    mapProjection: new Cesium.GeographicProjection(ellipsoid)
});
```

Setting just the globe ellipsoid and letting the map projection use the default has better results...
``` javascript
var ellipsoid = Cesium.Ellipsoid.MOON;
var viewer = new Cesium.Viewer('cesiumContainer', {
    globe: new Cesium.Globe(ellipsoid)
});
```

**Comment by emackey** [comment]
Is this a dupe of #4245?  The examples here are using Bing imagery constructed on the WGS84 ellipsoid, so they are not going to work correctly.
