### ISSUE TITLE
ArcGIS MapServer demo not loading layer

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4252]
http://localhost:8080/Apps/Sandcastle/index.html?src=ArcGIS%20MapServer.html&label=Beginner

I'm getting 404's.

![captur2e](https://cloud.githubusercontent.com/assets/915398/18075605/4bb1ec12-6e44-11e6-88e4-13c767acdbce.PNG)

**Comment by pjcozzi** [comment]
@kring is this temporary or should we update the URL?

**Comment by pjcozzi** [comment]
Nice to have for 1.25, but not required.
