### ISSUE TITLE
"Floating" CorridorGeometry on mobile 

### ISSUE THREAD

**Issue by turban** [AnalyticalGraphicsInc/cesium#4261]
I'm trying to clamp CorridorGeometry to the terrain. It works fine on desktop, but the CorridorGeometry "floats" on mobile (tested on Android/Chrome and iPhone/Safari). Is this a known issue with touch devices? 

![corridor](https://cloud.githubusercontent.com/assets/548708/18105628/63325f9a-6f00-11e6-9274-4c8d768bb9a9.gif)

Desktop: 
![screen shot 2016-08-30 at 22 29 05](https://cloud.githubusercontent.com/assets/548708/18105833/3fc09e4a-6f01-11e6-99a6-354f3c46fb05.png)

```
viewer.entities.add({
  name: 'Track',
  corridor: {
    positions: Cartesian3.fromDegreesArray(coords),
    width: 20.0,
    material: Color.ORANGE.withAlpha(0.9),
  },
});
```

Version: 1.24

**Comment by hpinkos** [comment]
Hello @turban.  Thanks for including the GIF!

It looks like the corridor is rendering under the terrain.  My guess is device doesn't have support for ground primitives.

From CHANGES.md:

> Because of the cutting edge nature of this feature in WebGL, it requires the [EXT_frag_depth](https://www.khronos.org/registry/webgl/extensions/EXT_frag_depth/) extension, which is currently only supported in Chrome, Firefox, and Edge.  Apple support is expected in iOS 9 and MacOS Safari 9. Android support varies by hardware and IE11 will most likely never support it. You can use [webglreport.com](http://webglreport.com) to verify support for your hardware.

I'm going to close this issue for now.
If you can see in WebGL report that `EXT_frag_depth` is supported on your device, let us know and we'll look into it further.  If it's not supported, there's unfortunately not much we can do as a workaround.

Thanks!

**Comment by hpinkos** [comment]
Oh also, for development purposes, you can check the 
[GroundPrimitive.isSupported](http://cesiumjs.org/Cesium/Build/Documentation/GroundPrimitive.html#.isSupported) to see if ground primitives are supported.  If not, you could turn off terrain to avoid having the geometry render under the terrain.

**Comment by turban** [comment]
Thanks @hpinkos, GroundPrimitive.isSupported was useful to target those devices.
