### ISSUE TITLE
HeightmapTerrainData test failures in built release

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4272]
These tests fail when running all tests in built release mode. However they work when run individually. I'm seeing this in all browsers.

![captur3e](https://cloud.githubusercontent.com/assets/915398/18171441/01316ed6-7030-11e6-8816-a861ca93c498.JPG)

**Comment by pjcozzi** [comment]
@lilleyse do you still get these test failures?

I do not.

**Comment by lilleyse** [comment]
I'm no longer seeing these.
