### ISSUE TITLE
how to render a flooding scenario with cesium

### ISSUE THREAD

**Issue by shengzheng1981** [AnalyticalGraphicsInc/cesium#4283]
Hi,everyone
I'm working to render a flooding scenario with cesium.I have the scenario’s flooding result about flooding area and the depth grid(10m*10m) . how to render?any suggestion will be appreciated!

**Comment by hpinkos** [comment]
Hello @shengzheng1981 

Please ask questions like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for bug tracking and new features planning

Thanks!
