### ISSUE TITLE
Other map projections (spatial references)

### ISSUE THREAD

**Issue by wussup** [AnalyticalGraphicsInc/cesium#4291]
Hello, how I can use Cesium with other than EPSG:3857 and EPSG:4326 projections?

**Comment by pjcozzi** [comment]
For 2D map projects, try implementing the [MapProjection](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/MapProjection.js) interface.  For an example, see [WebMercatorProjection](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/WebMercatorProjection.js).

In the future, please ask general questions on the [Cesium forum](http://cesiumjs.org/forum.html) and use GitHub issues for bug reports and specific feature requests.
