### ISSUE TITLE
Cesium 1.25 Build Bug

### ISSUE THREAD

**Issue by zwzhlj100000** [AnalyticalGraphicsInc/cesium#4312]
Cesium 1.25 Build Bug: 

Win 10,X64,
i run command npm run release,and get the follow error:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! cesium@1.25.0 release: `gulp release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cesium@1.25.0 release script 'gulp release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cesium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cesium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cesium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Uninpho\Product\Cesium\3DTiles\V1.25\cesium-3d-tiles\npm-debug.log

C:\Uninpho\Product\Cesium\3DTiles\V1.25\cesium-3d-tiles\npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'release' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle cesium@1.25.0~prerelease: cesium@1.25.0
6 silly lifecycle cesium@1.25.0~prerelease: no script for prerelease, continuing
7 info lifecycle cesium@1.25.0~release: cesium@1.25.0
8 verbose lifecycle cesium@1.25.0~release: unsafe-perm in lifecycle true
9 verbose lifecycle cesium@1.25.0~release: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Uninpho\Product\Cesium\3DTiles\V1.25\cesium-3d-tiles\node_modules\.bin
10 verbose lifecycle cesium@1.25.0~release: CWD: C:\Uninpho\Product\Cesium\3DTiles\V1.25\cesium-3d-tiles
11 silly lifecycle cesium@1.25.0~release: Args: [ '/d /s /c', 'gulp release' ]
12 silly lifecycle cesium@1.25.0~release: Returned: code: 1  signal: null
13 info lifecycle cesium@1.25.0~release: Failed to exec release script
14 verbose stack Error: cesium@1.25.0 release: `gulp release`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid cesium@1.25.0
16 verbose cwd C:\Uninpho\Product\Cesium\3DTiles\V1.25\cesium-3d-tiles
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error cesium@1.25.0 release: `gulp release`
22 error Exit status 1
23 error Failed at the cesium@1.25.0 release script 'gulp release'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cesium package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp release
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cesium
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cesium
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hpinkos** [comment]
Hello @zwzhlj100000 

Make sure you run `npm install`.  See instructions in the [Getting Started Tutorial](http://cesiumjs.org/tutorials/cesium-up-and-running/)

In the future, if you have any questions please post on the Ceisum Forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
