### ISSUE TITLE
3DTiles spamming console.log with thousands of messages.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4313]
#4228 added a message about using the old 3DTiles b3dm format, but it's using `console.log` and spamming the output with thousands of messages when working with most existing 3DTiles sets.  It should use `oneTimeWarning` or `depracationWarning` instead.

**Comment by pjcozzi** [comment]
Agreed, this is commented out in the `3d-tiles-temp` branch, but do not use that branch right now as it is experimental.

**Comment by lilleyse** [comment]
@JudyWeng let's do this one next. Use a `deprecationWarning`, for example like https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L883

For testing you can follow the same steps as here: https://github.com/AnalyticalGraphicsInc/cesium/issues/3892#issuecomment-248639720
