### ISSUE TITLE
Show license at top of repo

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4322]
For the Cesium repo and all AGI repos, e.g., like this:

![image](https://cloud.githubusercontent.com/assets/782098/18553340/14f999ee-7b2e-11e6-9176-24f89a366c17.png)

https://github.com/Kupoman/BlenderRealtimeEngineAddon

I have not looked into if this is a admin checkbox, LICENSE.md parsing, etc.

**Comment by shunter** [comment]
https://help.github.com/articles/adding-a-license-to-a-repository/

LICENSE.md doesn't exactly match the standard Apache license, so it doesn't get detected.

**Comment by shunter** [comment]
Thinking about this more, Cesium is not exactly licensed under Apache.  Given the included third-party code, the combined work is Apache plus MIT plus BSD plus whatever else.  I suggest closing this.  The auto-detect is for simple projects, which Cesium is far from.

**Comment by mramato** [comment]
@shunter I'm pretty sure your reasoning would eliminate 90% of GitHub projects, since most depend on other libraries with various compatible licenses; but I'll let @pjcozzi and our legal counsel sort this out.

**Comment by pjcozzi** [comment]
The Cesium code that we develop is Apache 2.0.  Third-parties are as licensed by their developers (and, of course, compatible with Apache 2.0).  I don't see this "Apache 2.0" icon as any different than what we advertise on the Cesium website, in talks, etc.

**Comment by pjcozzi** [comment]
This would be cool, but passing for now as mentioned in https://github.com/AnalyticalGraphicsInc/cesium/pull/4330#issuecomment-255449370

**Comment by pjcozzi** [comment]
When using the template license, GitHub will now also show a summary of the terms of the license:

![image](https://cloud.githubusercontent.com/assets/782098/24452126/c00bad26-144f-11e7-8c92-00dc229a43c4.png)

https://github.com/blog/2335-open-source-license-descriptions-and-metadata

I think we could do this by
* Renaming our current LICENSE.md to LICENSE-WITH-THIRDPARTIES.md
* Using the Apache 2.0 template for LICENSE.md

Give me a few weeks to look at this.  If it pans out, we could do it for all repos.

**Comment by pjcozzi** [comment]
Also, probably remove the Apache 2.0 badge from README.md
