### ISSUE TITLE
JSDoc footer is enormous

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4335]
While testing #4302, I discovered that (even in master) the JSDoc footer on each object's page is almost 2000 pixels tall.  This means that every page can scroll way past its content and there's just a tone of blank space.  Obviously not a deal breaker and low priority, but it would be nice to fix.

**Comment by emackey** [comment]
This is done deliberately so that anchor links near the bottom of the page can be scrolled to.  I'd like to keep this.

**Comment by mramato** [comment]
OK, that makes sense I guess.  Didn't realize it was intentional.

**Comment by mramato** [comment]
Thanks, I had inspected the element, but obviously the comment gets removed during the build.
