### ISSUE TITLE
3D Tiles - ModelInstanceCollection has no ShadowMode option to conserve performance.

### ISSUE THREAD

**Issue by HeercoGrond** [AnalyticalGraphicsInc/cesium#4340]
Hi,

Currently I'm using openstreetmaps to load forestdata to use for rendering trees in cesium using the ModelInstanceCollection of the 3D Tiles branch. The problem is that the ModelInstanceCollection has no options for setting the ShadowMode of the models contained within. Some of the objects in our scene require the shadows, and the trees are more there for cosmetic value so disabling shadows in the general sense of Cesium is not an option for us. Adding a shadowmode option to the ModelInstanceCollection might help in regards to usage and performance. It seems checked off in #3241 but isn't implemented. I tested it by adding it in our local branch and it seems to work well (only really tested with the ShadowMode.ENABLED and ShadowMode.DISABLED). 

Kind regards,

Heerco

**Comment by lilleyse** [comment]
Thanks for submitting this, adding a `shadows` property to `ModelInstanceCollection` and the 3D Tiles Contents would be very useful. This will be a good starter issue for @JudyWeng or @sumitshyamsukha.

**Comment by HeercoGrond** [comment]
The implementation for this looks to be very easy, mostly adding another parameter called shadows, adding this._shadows below the variables that get passed onto the model and adding it to the createModel function's parameters for the model. This seems to do the trick.

**Comment by lilleyse** [comment]
Fixed in #4341
