### ISSUE TITLE
Add shadows property to Cesium3DTileset

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4344]
For #3241 

Similar to https://github.com/AnalyticalGraphicsInc/cesium/pull/4341, we should support a shadows property inside `Cesium3DTileset`, `Batched3DModel3DTileContent`, and `Instanced3DModel3DTileContent`. `PointCloud3DTileContent` is more involved so that should be held off for now.

@sumitshyamsukha Let's work on this one tomorrow.

**Comment by pjcozzi** [comment]
This is for per-feature shadows, right?  Although I was the one who suggested this, I would hold off until we have enough interest since this comes with a high memory overhead.  I would not use this as a beginner 3D Tiles issue.  Please check the roadmap for others and let me know if you need input.

**Comment by lilleyse** [comment]
No this is for the entire tileset.

**Comment by pjcozzi** [comment]
Ah, +1 from me.

**Comment by lilleyse** [comment]
@sumitshyamsukha https://github.com/AnalyticalGraphicsInc/cesium/pull/4348 is merged so you should be able to finish your PR when you pull the latest `3d-tiles` changes. One more thing to address is being able to set the shadows dynamically rather than just at creation time. To do that, in `Batched3DModel3DTileContent.update` you can set the model's shadows to equal the tileset's shadows. In `Instanced3DModel3DTileContent.update` you can set the `ModelInstanceCollection`'s shadows to the tileset's shadows.

**Comment by rammy4real** [comment]
hello lilleyse . good day. hope you are doing great sir. i would love to contribute to this. just to let you that i am a starterwith the following knowledge level
html: intermediate
css:intermediate
javascript: basic/beginner
java: basic/beginner
really do love to be part of your team. I promise to give my best and my all .
thank you sir.
rammy4real@gmail.com

**Comment by pjcozzi** [comment]
@lilleyse OK to close this given #4386?

@rammy4real thanks for your interest in contributing to Cesium.  A great place to start is the [Contributor's Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).

**Comment by lilleyse** [comment]
> @lilleyse OK to close this given #4386?

Yup, closed.
