### ISSUE TITLE
Lots of missing pragmas for DeveloperError

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4349]
1. Edit `gulpfile.js` and change the `combine` step so that `removePragmas` is true.
2. Run the combine step and then search the resulting `Build/CesiumUnminified/Cesium.js` file for `new DeveloperError`.

There will be a ton of occurrences in the code when there should be none.  This also affects performance due to additional if checks in hot code.  Any place it appears means that it's missing the proper pragma notation as discussed in the Coding Guide: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#throwing-exceptions

It should be easy to detect this as part of the build process in the future, once the initial problems are fixed.

**Comment by pvskarthikeya** [comment]
Hey! Is this still open. Can I work on it?

**Comment by mramato** [comment]
Of course!  In order for us to review and accept a pull request, you'll need to email us a CLA as described here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md

That document also contains links to other relevant information you'll need (such as the Coding Guide) in order to make your PR a successful one.

Thanks in advance.

**Comment by erikmaarten** [comment]
@mramato There's a destroyObject function that replaces an object's methods with a throwOnDestroyed method that simply throws a DeveloperError when invoked. What should the behavior of this be in production code? Not sure if this DeveloperError should be handled like all the other ones.

**Comment by erikmaarten** [comment]
Also, what about "interface specifications", like in `Source/Core/TilingScheme.js`, which should not be used at all, are they actually included in the output bundle when building for production?

**Comment by mramato** [comment]
> Not sure if this DeveloperError should be handled like all the other ones.

@pjcozzi or @shunter can second this, but perhaps it should either be a `RuntimeError` instead or a no-op (don't replace the functions at all).  I think I would prefer either of those to leaving an un-pragma'd `DeveloperError`

> Also, what about "interface specifications", like in Source/Core/TilingScheme.js, which should not be used at all, are they actually included in the output bundle when building for production?

Same opinion here as above, these make more sense as `RuntimeError` or being pragma'd out.

Let's go with pragma-ing both cases for now and if anyone has any objections, it's easy enough to change if there are any objections.

**Comment by pjcozzi** [comment]
> Let's go with pragma-ing both cases for now and if anyone has any objections, it's easy enough to change if there are any objections.

+1

**Comment by erikmaarten** [comment]
@mramato Can you close this? (I didn't use the "Fixes #..." reference in the PR before it was merged...)
