### ISSUE TITLE
outlineWidth

### ISSUE THREAD

**Issue by cfickler** [AnalyticalGraphicsInc/cesium#4352]
Guys, it looks like outlineWidth has no affect. I especially need this on a polygonGraphic. Can you please investigate? 

var outlineOnly = viewer.entities.add({
    name : 'Yellow box outline',
    position: Cesium.Cartesian3.fromDegrees(-100.0, 40.0, 300000.0),
    box : {
        dimensions : new Cesium.Cartesian3(400000.0, 300000.0, 500000.0),
        fill : false,
        outline : true,
        outlineColor : Cesium.Color.YELLOW,
        outlineWidth : 3.0
    }
});

**Comment by hpinkos** [comment]
outlineWidth isn't supported on all platforms.  See the answer to this forum post for more information: https://groups.google.com/forum/?hl=en#!searchin/cesium-dev/outlineWidth%7Csort:relevance/cesium-dev/guxo6vcVkhc/5tHeE5Va2DwJ

In the future, please use the forum for asking questions like this.  We use GitHub issues for bug and feature tracking.  Thanks!
