### ISSUE TITLE
[tutorial] Outline not shown in 1st example of Visualizing Spatial Data Tutorial

### ISSUE THREAD

**Issue by jnachtigall** [AnalyticalGraphicsInc/cesium#4356]
Following the Tutorial at https://cesiumjs.org/tutorials/Visualizing-Spatial-Data/ with 

```
var viewer = new Cesium.Viewer('cesiumContainer');

var wyoming = viewer.entities.add({
  name : 'Wyoming',
  polygon : {
    hierarchy : Cesium.Cartesian3.fromDegreesArray([
                              -109.080842,45.002073,
                              -105.91517,45.002073,
                              -104.058488,44.996596,
                              -104.053011,43.002989,
                              -104.053011,41.003906,
                              -105.728954,40.998429,
                              -107.919731,41.003906,
                              -109.04798,40.998429,
                              -111.047063,40.998429,
                              -111.047063,42.000709,
                              -111.047063,44.476286,
                              -111.05254,45.002073]),
    material : Cesium.Color.RED.withAlpha(0.5),
    outline : true,
    outlineColor : Cesium.Color.BLACK
  }
});

viewer.zoomTo(wyoming);
```

Other than in the screenshot at https://cesiumjs.org/images/2015/02-02/OurFirstEntity.jpg there is no outline. Also in the console I see the message:

> Entity geometry outlines are unsupported on terrain. Outlines will be disabled. To enable outlines, disable geometry terrain clamping by explicitly setting height to 0.

At first, I thought I did something wrong. But I guess there's been some internal Cesium change. I suggest updating the tutorial.

**Comment by hpinkos** [comment]
Thanks @jnachtigall!  Yes, it looks like we forgot to update the code example

**Comment by mrajcok** [comment]
In case it is not clear what to do based on the console message, add a height property to the polygon to see the outline:

```
polygon : {
    hierarchy : Cesium.Cartesian3.fromDegreesArray([...]),
    material : Cesium.Color.RED.withAlpha(0.5),
    outline : true,
    outlineColor : Cesium.Color.BLACK,
    height: 0    // <<----  and don't miss the comma on the previous line
  }
```

And I prefer flying to zooming:  `viewer.flyTo(wyoming);`

**Comment by hpinkos** [comment]
Thanks @jnachtigall, @mrajcok!  We updated the example to include `height: 0`.  This update will be deployed to the website shortly.
