### ISSUE TITLE
[tutorial] Broken link in https://cesiumjs.org/tutorials/Imagery-Layers-Tutorial/

### ISSUE THREAD

**Issue by jnachtigall** [AnalyticalGraphicsInc/cesium#4358]
Hope this is the right repo for this issue, but there's now github source mentioned for the tutorial pages.

https://cesiumjs.org/tutorials/Imagery-Layers-Tutorial/

> Cesium includes a "simple proxy" written in Java for development purposes.

links to https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Tools/proxy which is 404

**Comment by rammy4real** [comment]
hello jnachtigall . good day. hope you are doing great sir. i would love to contribute to this. just to let you that i am a starterwith the following knowledge level
     html: intermediate
     css:intermediate
     javascript: basic/beginner
     java: basic/beginner
 really do love to be part of your team. I promise to give my best and my all .
thank you sir.
rammy4real@gmail.com

**Comment by Swapnull** [comment]
I think the link just needs changing to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/DefaultProxy.js , but that site is not in this repo.

**Comment by mramato** [comment]
Thanks guys, we'll definitely clean this up as part of our bug bash next week.

**Comment by emackey** [comment]
This will be fixed with the next deploy.
