### ISSUE TITLE
[3D Tiles] ModelInstanceCollection has no scaling parameters. 

### ISSUE THREAD

**Issue by HeercoGrond** [AnalyticalGraphicsInc/cesium#4365]
While using ModelInstanceCollection, I came upon the issue that ModelInstanceCollection has no option to insert the desired scale into the model pre-creation as an uniform scale for all the models. For my usecase, we're having trees that are currently towering above our primitive buildings, so we need to be able to adjust them. I've made a fix based purely on the scale property of the model, not yet including maximumScale or minimumPixelSize, that I will create a pull request for soon and reference in this post.

**Comment by HeercoGrond** [comment]
Pull request is made: #4366. Tested it locally, works fine (even without defining the property of scale in the creation of the modelinstancecollection.)

**Comment by lilleyse** [comment]
I'm not sure if this property is needed since the scale can be part of the modelMatrix of each instance. I also think maximumScale and minimumPixelSize are probably too specific to be needed by most people using ModelInstanceCollection.

**Comment by pjcozzi** [comment]
> I'm not sure if this property is needed since the scale can be part of the modelMatrix of each instance.

I generally would agree here, but `scale` is part of `Model` for end-user simplicity.

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L311

However, given that `ModelInstanceCollection` is an internal API, we don't have to overbuild it.

**Comment by HeercoGrond** [comment]
Yeah, adding the scale to the ModelMatrix manually is also a solution. I might look into making a calculation that rather than add a scale onto the createmodel method, adds a scale directly to the modelmatrix for end-user simplicity.

**Comment by pjcozzi** [comment]
> adds a scale directly to the modelmatrix for end-user simplicity.

I'm not sure if I was clear, but `ModelInstanceCollection` end users are really just other parts of the Cesium API (since it is not part of the public API) so I would not add features to it that are not used by other parts of Cesium.  If `ModelInstanceCollection` becomes part of the public API, we may add things like this.
