### ISSUE TITLE
Remove deprecated visualizer scene constructor parameter

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#4385]
Remove `BillboardVisualizer`, `LabelVisualizer` and `PointVisualizer` `scene` constructor argument.

**Comment by pjcozzi** [comment]
Labeled `remove in 1.2.7`; I don't think this will impact many users.

**Comment by erikmaarten** [comment]
Pull request merged, I think this can be closed.

**Comment by mramato** [comment]
Thanks.  As an FYI, if you put "Fixes #XXXX" in your PR descriptions, then issues will automatically close when they get merged.

**Comment by erikmaarten** [comment]
@mramato Thanks Matt, I had a vague feeling I was missing something that could make it automatic... That's exactly what I need :smile:
