### ISSUE TITLE
Wrong camera position in the Ground Clamping example.

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#4397]
Open the Ground Clamping Sandcastle example. Switch to 2D or Columbus view and select either the point or billboard from the drop down. The camera reference frame is wrong.

**Comment by hpinkos** [comment]
Related #5042

**Comment by hpinkos** [comment]
Actually, this is definitely a the same problem as #5042
Closing as a duplicate
