### ISSUE TITLE
3D Tiles: loadProgress event incorrect

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4400]
We have sample code that looks like the following.

``` javascript
 city.loadProgress.addEventListener(function(numberOfPendingRequests, numberProcessing) {
     if ((numberOfPendingRequests === 0) && (numberProcessing === 0)) {
         console.log('Stopped loading');
         return;
     }

     console.log('Loading: requests: ' + numberOfPendingRequests + ', processing: ' + numberProcessing);
 });
```

The problem is, Cesium3DTileset doesn't take pending requests into account, i.e. it schedules something with the RequestScheduler, but the request hasn't happened yet.  This means the above code ends up printing "Stopped loading" while tiles are actually still being loaded.

**Comment by mramato** [comment]
@lilleyse I'm seeing problems with 3D tilesets claiming to be complete when they are not.  I assume the traversal changes may have something to do with it but I'm not sure.  All I know is that `numberOfPendingRequests` is 0, and `numberProcessing` is 0, but the scene is not complete.

**Comment by lilleyse** [comment]
Is the problem with the `allTilesLoaded` event or the `tilesetLoaded` property, or both? It is possible something has changes due to the traversal. Is `numberOfAttemptedRequests` also 0?

**Comment by mramato** [comment]
I'll debug further and let you know.  Right now I'm not using the events because I just need to know "is everything done for the previously rendered frame", so I'm just checking `numberOfPendingRequests` and `numberProcessing` directly.

**Comment by mramato** [comment]
Looks like `numberOfAttemptedRequests` is 0 as well, but I'm starting to think this is a false alarm and it could be a problem with the tileset I'm using.  The pop-in I'm seeing could be a bad boundingsphere or something.

While I have you here, what exactly is `numberOfAttemptedRequests`?

Is there a reason we are using an `allTilesLoaded` event instead of just setting a boolean flag?  For every use case I've encountered, the event isn't the right abstraction and I'd much rather just check a flag because I'm usually trying to answer "is every tileset loaded this frame" not "tell me whenever this particular tileset is complete"  In order to do what I want to do via the event, I would need to subscribe to every tileset rather than just iterate them when needed.

**Comment by mramato** [comment]
Spoke offline with @lilleyse we think it's bad geometric error with the tileset I'm using.

We'll keep the `allTilesLoaded` event for now, but what we really need is a interface level property for all Primitives that indicate if they are complete or not.  This would be the first stepping stone to being able to avoid rendering every frame if there's no work to be done.

I'm going to close this for now and keep an eye out for it in other places.

**Comment by lilleyse** [comment]
By the way, `tilesLoaded` is a boolean flag you can use.

**Comment by mramato** [comment]
Awesome, I must have missed when that got added.
