### ISSUE TITLE
Add support for NetworkLinkControl updates

### ISSUE THREAD

**Issue by wulfgarpro** [AnalyticalGraphicsInc/cesium#4404]
I'm porting an application from GE to Cesium; it relies on [NetworkLinkControl](https://developers.google.com/kml/documentation/kmlreference#networklinkcontrol) updates heavily, and I think this would be a useful feature for most people.  Is there any roadmap for such a feature?

**Comment by hpinkos** [comment]
Hello @wulfgarpro,  we do have a note to add this in our KML roadmap issue.  I'm not sure when we'll be able to get to it though.
I'm going to close this issue and make a comment on #873 so we can keep track of how many people have asked for this.  Thanks!
