### ISSUE TITLE
Invalid array length error

### ISSUE THREAD

**Issue by lucasvw** [AnalyticalGraphicsInc/cesium#4407]
Hi all,

Just found a quite nasty bug. reproducable with the following sandcastle code:

```
var viewer = new Cesium.Viewer('cesiumContainer');

var scene = viewer.scene;

var camera = scene.camera;

camera.setView({
    "destination": {
        "x": 3787532.157385739,
        "y": 902939.3512136568,
        "z": 5037430.268736357
    },
    "orientation": {
        "heading": 6.274672120105068,
        "pitch": -0.8980206372523926,
        "roll": 0
    }
});
```

If this code is run on a mobile device and the very first move is a zoom pinch, then Cesium crashes because of an invalid array length. I debugged a little and saw it has something to do with invalid (NaN) values in directionWC and positionWC of the camera.

Interestingly enough this only happens when the **first** move is a zoom pinch.. first moving and then zoom pinching is no problem.

**Comment by hpinkos** [comment]
Thanks @lucasvw, I think you're running into #4177
We're going to try to look into it during our bug bash in two weeks.
I'm going to close this issue since it's a duplicate
