### ISSUE TITLE
Label/Billboard show/hide bug

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4408]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/u75ie_3xwy0

1. Load the example and zoom in to see the labels
2. Hit hide - This works correctly
3. Hit show - Only the labels come back, the billboards don't
4. Now neither the show or hide button have any effect

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas
};
var kml = '../../SampleData/kml/facilities/facilities.kml';
var kmlds;

viewer.dataSources.add(Cesium.KmlDataSource.load(kml, options))
.then(function(ds) {
    kmlds = ds;
});

Sandcastle.addToolbarButton('Hide', function() {
    kmlds.show = false;
});
Sandcastle.addToolbarButton('Show', function() {
    kmlds.show = true;
});
```

**Comment by hpinkos** [comment]
Creating the entities from the Entity API causes the same problem: 

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var label = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    point: {
        pixelSize: 5,
        outlineColor: Cesium.Color.BLACK,
        outlineWidth: 1
    },
     label: {
        text: 'Label',
        font: '20pt Verdana',
        pixelOffset: new Cesium.Cartesian2(0, -30),
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM,
    }
});

var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handler.setInputAction(function() {
    label.show = label.show ? false : true;
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/L5-UMH051RY

I labeled this for next release since it's effecting a number of users

**Comment by lilleyse** [comment]
And here: https://groups.google.com/forum/#!topic/cesium-dev/FAXHuSIBJv4

**Comment by tfili** [comment]
@bagnell It looks like this is caused by clustering. I can only reproduce this with the KML example. Another thing I noticed is that when it worked before clustering turning on the entities was pretty quick, now its really slow (even when clustering isn't enabled).

**Comment by bagnell** [comment]
@tfili I tracked down the `show` problem, but the performance problem has to do with height referenced billboards and labels.

**Comment by mramato** [comment]
KML is defaulting to terrain clamping for billboards even though it shouldn't, which is why performance there is slow there, #4459 should fix the default behavior, but it will still be slow when clamping is on.

**Comment by Kulvinderjatt** [comment]
var viewer = new Cesium.Viewer('cesiumContainer');

var label = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    point: {
        pixelSize: 5,
        outlineColor: Cesium.Color.BLACK,
        outlineWidth: 1
    },
     label: {
        text: 'Label',
        font: '20pt Verdana',
        pixelOffset: new Cesium.Cartesian2(0, -30),
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM,
    }
});

var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handler.setInputAction(function() {
    label.show = label.show ? false : true;
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);


This works like a charm. Thanks alot!
