### ISSUE TITLE
Unable to re-add datasource

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4409]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Yo_dyrt43B8

1. Click `add` to add the datasource
2. Click `remove` to remove it
3. Click `add` to add it again.  The app crashes with `cannot set property 'id' of undefined`

`DatasourceCollection.remove` has `destroy=false` by default, so I couldn't find any reason why you shouldn't be able to do this

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas
};
var kml = '../../SampleData/kml/facilities/facilities.kml';
var ds;

ds = new Cesium.KmlDataSource(options);
ds.load(kml, options).then(function() {
    console.log('loaded' + ds.entities.values.length + ' entities');
});

Sandcastle.addToolbarButton('add', function() {
    viewer.dataSources.add(ds);
});
Sandcastle.addToolbarButton('remove', function() {
    viewer.dataSources.remove(ds);
});
```

**Comment by twpayne** [comment]
I'm looking at this now.

**Comment by mramato** [comment]
Copied from the closed PR.

I think the issue here is that the destroy method on BillboardVisualizer, LabelVisualizer, and PointVisualizer needs to iterate over the entityCollection.values array and call removeLabel/removePoint/removeBillboard for each depending on the visualizer.
