### ISSUE TITLE
Support for dynamic billboards

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4413]
Currently, when you change the `billboard.image` property, it adds a new image to the texture atlas.  However, this can cause problems if you have a billboard that changes frequently because the texture atlas runs out of space and causes errors.  It would be nice to have the ability to overwrite part of the texture atlas for a billboard that you know is going to be changing frequently.

I couldn't find an issue that exactly matches this, but it's been requested on the forum multiple times:
https://groups.google.com/d/msg/cesium-dev/jFsmh7LOiTs/MCJfLJlEZZgJ
https://groups.google.com/d/msg/cesium-dev/cF9Vt28Wk-4/nJ68p3YONKcJ
https://groups.google.com/d/msg/cesium-dev/tuQyixSKJuA/3-jsFmIABwAJ
https://groups.google.com/d/msg/cesium-dev/Sd4x1YmneCs/nfMsP3eaAwAJ
https://groups.google.com/d/msg/cesium-dev/JzpfPUvBdEA/8adq-uKfb7sJ

**Comment by hpinkos** [comment]
Related: #2319

**Comment by mramato** [comment]
This is exactly the same as the issue you linked to.  I recommend closing this and just adding the form links to #2319.
