### ISSUE TITLE
KML clustering  crash

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4414]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/p1Mv6vpvvnY

If you use this kml file in the Sandcastle clustering example, it crashes.  The KML has two placemarks in it

[placenames_capital.kml.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/516479/placenames_capital.kml.txt)

**Comment by pjcozzi** [comment]
@bagnell can you please look at this for 1.27 perhaps even at the bug bash?

**Comment by mramato** [comment]
The fix here appears to be to add `defined(entityCluster._labelCollection) && ` to line 148 of EntityCluster.js, doing so appears to make everything work as expected.  I tried (and failed) to create a unit test for this, so perhaps @bagnell can do it when he gets back on Monday.
