### ISSUE TITLE
Kml file loading regression: works in 1.25, not 1.26 "Cannot read property 'center' of undefined"

### ISSUE THREAD

**Issue by vrittis** [AnalyticalGraphicsInc/cesium#4431]
The attached kml file loads correctly in 1.25, but fails with the following error message in 1.26:

> An error occurred while rendering. Rendering has stopped.
> TypeError: Cannot read property 'center' of undefined
> TypeError: Cannot read property 'center' of undefined
>     at updateBatchTableBoundingSpheres (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:93495:40)
>     at Primitive.update (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:93890:13)
>     at GroundPrimitive.update (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:98060:25)
>     at PrimitiveCollection.update (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:157993:27)
>     at updatePrimitives (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166211:33)
>     at executeCommandsInViewport (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166122:9)
>     at updateAndExecuteCommands (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:165990:17)
>     at render (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166420:9)
>     at Scene.render (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166458:13)
>     at CesiumWidget.render (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:175280:25)

I wasn't able to determine if it was a problem with the quantity of geometries in the file or the mix between polygon and multigeometries. I stripped down the kml file for the issue, the polygons are much more complex usually. However the error happens even with four points polygons. There are 3423 placemarks in the file. 

[Fail1.26.kml.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/529713/Fail1.26.kml.zip)

**Comment by pjcozzi** [comment]
@bagnell can you look at this at the bug bash?

**Comment by tfili** [comment]
@bagnell The document for #4041 is also showing this issue.

**Comment by mramato** [comment]
@bagnell it looks like loading this file in master causes lots of undefined bounding spheres, while everything works as expected in 1.25.  I'm assuming this is batch-table related.

**Comment by mramato** [comment]
@bagnell let's discuss this and #4414 when you get in today.  This one in particular is a geometry-wide regression and not just KML.
