### ISSUE TITLE
Drastic performance decrease when animating colors of polygons via SampledProperty + Polygon losing transparency

### ISSUE THREAD

**Issue by thinkpadder1** [AnalyticalGraphicsInc/cesium#4433]
Please [see this gist/sandcastle for a code example.](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=8faa5262fc15a96cdcbc641e4ee5548d)

**Instructions**:

- Play it back manually with your mouse (the full length of the timeline bar) back and forth a few times (5x each way).
- Notice how the polygon has lost its transparency.
- Zoom in so that the polygon fully fits in your screen.
- Try panning the screen.
- Notice the drop in performance.

**Edit**: Updated the gist with FPS counter + auto zoom to polygon.

**Comment by mramato** [comment]
Thanks @thinkpadder1 the loss of transparency is definitely a bug in the ground primitive geometry batching and I've marked this for the bug bash so we fix it.

The performance decrease is actually a result of how ground primitives work and is GPU fill-rate limited, i.e. the more pixels of a ground polygon are on the screen, the more graphics card resources get used per frame.  If you aren't using terrain, you can set `height:0` and performance will be way better (and this works around the other bug as well).  The downside is the polygon will no longer conforms to terrain.  We certainly hope to improve performance here in the future, but there's no bug or other trivial change, it's a research problem.

**Comment by mramato** [comment]
Turns out this bug was nastier than I thought and did affect performance.  The reason it was turning opaque is because we were adding a new primitive every time without removing the old one.  I just submitted #4457 with the fix.
