### ISSUE TITLE
Create glTF at runtime

### ISSUE THREAD

**Issue by tomeof** [AnalyticalGraphicsInc/cesium#4439]
Hello,

Could you please provide an example of loading glTF files in the viewer at runtime? I have a glTF file in memory as string. Should i convert it to JSON object?

Greetings

**Comment by hpinkos** [comment]
Hello,  Please see this forum post:  https://groups.google.com/forum/?hl=en#!topic/cesium-dev/qnuG2pAjVCQ

In the future, please use the forum for asking questions like this.  We use GitHub for bug and new feature tracking.  Thanks!

**Comment by tomeof** [comment]
Sure, thanks.
