### ISSUE TITLE
MacOS when scrollwheel zooming while hovering on billboard

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4440]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/QJz-ipNQpYU

The use reports seeing an `Invalid array length` error when using the mouse scroll wheel to zoom while the mouse is hovering over a billboard.

> this crash only appears to happen when my mouse is over the billboard when the page loads, and I zoom without the mouse moving from where it was before the page loads, and only on OS X.

**Comment by hpinkos** [comment]
Can someone with a mac see if they can reproduce this?  I couldn't on my windows machine

**Comment by smills2929** [comment]
Can confirm that I get the same error on Firefox 48.0.2.

RangeError: invalid array length updateFrustums@http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1183:9 createPotentiallyVisibleSet@http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1408:13 executeCommandsInViewport@http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2101:9 updateAndExecuteCommands@http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1968:17 render@http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2398:9 Scene.prototype.render@http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2436:13 CesiumWidget.prototype.render@http://cesiumjs.org/Cesium/Source/Widgets/CesiumWidget/CesiumWidget.js:683:13 render@http://cesiumjs.org/Cesium/Source/Widgets/CesiumWidget/CesiumWidget.js:72:25

**Comment by smills2929** [comment]
A bit more information. I just had another go of re-creating the crash with a different Windows machine and had no luck.

I tried a few other OS X machines (Sierra and El Capitan) and they all appeared to have the issue.

To reliably recreate the issue:

1. Load http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases
2. Place the mouse in the Cesium window around the center (roughly) while it is still Loading and don't move it.
3. Scroll in quickly as soon as 'Loading' has disappeared without moving the mouse. Scrolling in slowly doesn't appear to cause the crash. It also doesn't crash if you wait a second or two before scrolling, or you move the mouse.

**Comment by hpinkos** [comment]
Great, thanks for all of the information @smills2929!  That will be really helpful when we go to look into this

**Comment by smills2929** [comment]
I can confirm that it does not require a billboard to be in the scene or to be the subject of the zoom. It also appears to be the exact same issue as this:
https://github.com/AnalyticalGraphicsInc/cesium/issues/4177

It has the same error, and occurs only if you zoom while the viewer is still finishing initialising without panning.

**Comment by pjcozzi** [comment]
@hpinkos close as duplicate with #4177?
