### ISSUE TITLE
Artifact in rectangle

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4441]
Reported on the forum https://groups.google.com/forum/?hl=en#!topic/cesium-dev/V6TF-vnPoBk

When you tilt the globe a certain amount, there's a visible seam in the rectangle

![rect-seam](https://cloud.githubusercontent.com/assets/3451886/19485097/fe4a9ee6-9527-11e6-8d5f-4cb9fbfdcbd7.gif)

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var material = new Cesium.Material({
    fabric: {
        type: 'Image',
        uniforms: {
            image: '../images/earthspec1k.jpg',
            alpha: 0.6
        },
        components: {
            diffuse: 'texture2D(image, materialInput.st).rgb',
            alpha: 'texture2D(image, materialInput.st).a * alpha'
        }
    }
});
var geoInstatnce = new Cesium.GeometryInstance({
    geometry: new Cesium.RectangleGeometry({
        rectangle: Cesium.Rectangle.clone(Cesium.Rectangle.MAX_VALUE),
        height: 0
    })
});
var primitive = new Cesium.Primitive({
    geometryInstances: geoInstatnce,
    appearance: new Cesium.MaterialAppearance({
        material: material,
        faceForward: true,
        translucent: true,
        flat: true
    })
});

viewer.scene.primitives.add(primitive);

```

**Comment by pjcozzi** [comment]
CC #4510

**Comment by hpinkos** [comment]
Can no longer reproduce

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/V6TF-vnPoBk

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4441 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
