### ISSUE TITLE
Cesium failing to render on latest version of chrome

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4442]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/OASbgZGgw8E
@shunter and @dwhipps both reported cesium crashes with the latest chrome update, Version 54.0.2840.59
This seems like it might be a chrome bug, but I figured we should have an issue to track it as well

Info from @dwhipps:

1) I incorrectly reported that I was on macOS Sierra 10.11. I AM on Sierra, but it is, of course 10.12.

2) WebGLReport passes on WebGL1, but fails on WebGL2. Here’s my report:

Platform:   MacIntel
Browser User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
Context Name:   webgl
GL Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:   WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit
Renderer:   WebKit WebGL
Unmasked Vendor:    ATI Technologies Inc.
Unmasked Renderer:  AMD Radeon HD 6770M OpenGL Engine
Antialiasing:   Available
ANGLE:  No
Major Performance Caveat:   No

3) I’m on a Late 2011 MacBook Pro with “dual” video cards, one of which is the Intel 3000, but it typically switches over to my AMD Radeon 6770 for OpenGL. (See above.) I can (and have) “forced” it to use the Radeon, and don’t see any difference.

I’m still experiencing this issue both locally (while developing my own app) as well as with the Cesium homepage and the Sandbox.

I’ve discovered that if I put a breakpoint immediately after creating my “Viewer” and allow it to break briefly, then continue, rendering seems to work out fine. I’d like to reproduce that in the Sandbox, but I can’t figure out how/where to break in there.

Is this some kind of a race? I can debug inside Cesium, but it’d be nice to have a hint where to start. Where’s the render loop begin?

**Comment by dwhipps** [comment]
This seems to affect Safari as well, but not FireFox.

**Comment by pjcozzi** [comment]
Is this still a problem in Chrome 55?

**Comment by mramato** [comment]
As reported by @shunter in the linked forum post:

> I looked into this again after I found that it was still broken on my 9800GT. This is the culprit:
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=656989
> 
> Note that my issue is specific to Windows.  It appears the fix will go into Chrome 55.  In the comments, the suggested workaround is to add:
> 
> --disable_chromium_framebuffer_multisample
> 
> to the Chrome command line, which fixes WebGL for me.

So this should be fixed and even if it isn't, is definitely a Chrome bug and not Cesium.

**Comment by hijazikaram** [comment]
For some reason, cesium stopped working on chrome
