### ISSUE TITLE
Sandcastle "All" gallery does not have tooltips

### ISSUE THREAD

**Issue by twpayne** [AnalyticalGraphicsInc/cesium#4454]
In Sandcastle:
- Select the "Gallery / Showcases" tab at the bottom
- Hover over any thumbnail
- Observe that a tooltip is displayed
- Select the "Gallery / All" tab
- Hover over any thumbnail
- Observe that no tooltip is displayed

Tooltips should be shown in the "All" gallery.

**Comment by tekhaus** [comment]
Simple 1 line fix in CesiumSandcastle.js, works fine on local build (after updating package.json to use electron@1.4.10 since they pulled 1.4.9). Any other scripts I should run before submitting a PR?

**Comment by tekhaus** [comment]
Travis CI failed since it expects electron 1.4.9 (which should be rolled back to 1.4.8 or updated to 1.4.10)

**Comment by hpinkos** [comment]
Fixed in #4702
