### ISSUE TITLE
AGI CesiumSensor plugin not working well with Cesium 1.26

### ISSUE THREAD

**Issue by Calvinv99** [AnalyticalGraphicsInc/cesium#4466]
Hi
The CesiumSensor plugin does not work well with Cesium 1.26. It displayed a blue screen with an error log 'cannot read property 'entities' of undefined' at the console.  Cesium 1.25 has no error with it.

Regards
Calvin Chua

**Comment by mramato** [comment]
@Calvinv99, the Cesium sensors plugin was discontinued a couple of years ago and has not worked with Cesium for some time.  Some users in the community have forked the project to continue to update it, but I'm not sure of the details.  If you search our forum, or start a new topic, I'm sure you'll get a fairly quick response from them: https://groups.google.com/forum/#!forum/cesium-dev
