### ISSUE TITLE
Fix typo "funciton" in EllipsoidGeodesic

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4480]
@leesafini

Let's start off simple just to get you familiar with the pull request workflow.

In https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/EllipsoidGeodesic.js  the word `funciton` is misspelled twice.

@sumitshyamsukha and @JudyWeng can help out if you have questions opening a PR.

**Comment by ceyyarbrough** [comment]
Committed change to master branch for typo fix.

**Comment by leesafini** [comment]
Done! See pull request #4504

**Comment by fredj** [comment]
fixed with #4504 , this issue can be closed
