### ISSUE TITLE
Fix typo in Build Guide

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4481]
@Dylan-Brown

In the [Build Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide) change `to take affect` to `to take effect`.

@sumitshyamsukha and @JudyWeng can help with opening a pull request.

**Comment by Dylan-Brown** [comment]
So, I made the relevant change in the documentation. However, I can't commit to the project. Should I fork and make a pull request?

**Comment by lilleyse** [comment]
Yes you'll need to make a fork.

**Comment by Dylan-Brown** [comment]
Pull request here: https://github.com/AnalyticalGraphicsInc/cesium/pull/4486
