### ISSUE TITLE
GroundPrimitive bounding volume doesn't take curvature of the earth into consideration

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4483]
For example, the bounding box for this rectangle is too short:

![image](https://cloud.githubusercontent.com/assets/3451886/19575543/015ff958-96dd-11e6-96bb-5ac7ed58bfbe.png)

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var primitive = viewer.scene.primitives.add(new Cesium.GroundPrimitive({
    geometryInstances : [new Cesium.GeometryInstance({
        geometry : new Cesium.RectangleGeometry({
            rectangle : Cesium.Rectangle.fromDegrees(-110.0, 20.0, -80.0, 25.0),
            vertexFormat : Cesium.PerInstanceColorAppearance.VERTEX_FORMAT
        }),
        attributes: {
            color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 0.0, 0.0, 0.5))
        }
    })],
    appearance : new Cesium.PerInstanceColorAppearance({
        closed : true
    })
}));
primitive.debugShowBoundingVolume = true;
```

**Comment by pjcozzi** [comment]
@hpinkos is this still the case with #4751?

**Comment by hpinkos** [comment]
@pjcozzi yep, it'll still be a problem after #4751 gets merged

**Comment by pjcozzi** [comment]
Even for small ground primitives the bounding volume is not tall enough:

![image](https://cloud.githubusercontent.com/assets/782098/21643442/3e64f02e-d256-11e6-9d03-2b7fa3e948cb.png)

For example, try the red rectangle ground primitive in http://localhost:8080/Apps/Sandcastle/index.html?src=development/Ground%20Primitive.html&label=Development

This is likely more apparent now that `debugShowShadowVolume` shows the actual volume used for rendering.
