### ISSUE TITLE
Navigation widget

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#450]
From our Santa experience:

Cleanup the navigation widget and make it reusable like the timeline, etc.

The UI could use some redesign since this was designed for 5-10 year-olds ([discussion](https://groups.google.com/forum/#!searchin/cesium-dev/navigation/cesium-dev/50GI5fX1ODk/xZn7zD6e4e8J)).  In particular, the rotate and orient north buttons could be bigger, and all the separate buttons could be better integrated and have more compelling visuals.  Perhaps we can take some lessons from the [playback widget](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Playback-Details)?

**Comment by pjcozzi** [comment]
Potential [GSoC 2015 project](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Google-Summer-of-Code-Ideas-2015#navigation).

**Comment by Larcius** [comment]
How about this?
https://github.com/Larcius/cesium-navigation

Based on alberto-acevedo cesium-navigation (which was based on terriaJS) I added 2D and Columbus support and changed it to a viewer mixin.

**Comment by Larcius** [comment]
Examples are available at
http://larcius.github.io/cesium-navigation/

**Comment by hpinkos** [comment]
Thanks for sharing @Larcius!  The zoom in/out behavior is a little wonky in 2D and  Columbus View, but it's a good start!

**Comment by pjcozzi** [comment]
@Larcius could you open a pull request in the [cesium-plugins-list](https://github.com/AnalyticalGraphicsInc/cesium-plugins-list) repo for cesium-navigation and we'll close this?

**Comment by Larcius** [comment]
The plugin "Cesium Navigation" is already listed. This plugin refers to @alberto-acevedo repository but all my changes were pulled there.
Meanwhile the wonky zooming as pointed out by @hpinkos was fixed.

**Comment by pjcozzi** [comment]
Sounds good.

**Comment by hpinkos** [comment]
@pjcozzi I don't think we should close this.  At some point we should have a navigation widget included in our library.  I noticed in usability testing that it's the first thing people go for if they're not necessarily familiar with Cesium's mouse controls, and it would be especially useful for tilting since not all mouses have a middle button.

**Comment by pjcozzi** [comment]
OK, when ready, open an issue with concrete info; this issue just says "navigation widget."
