### ISSUE TITLE
(1.26.0 RangeError: invalid array length) when bringing in large GeoJSON datasources

### ISSUE THREAD

**Issue by ukitake** [AnalyticalGraphicsInc/cesium#4502]
Cesium Version: 1.26.0

When bringing in the attached GeoJSON as a GeoJSONDataSource to the Cesium Viewer I get RangeError: invalid array length.  The same geojson works fine when we bring it into version 1.25.0.  It also seems to be a Chrome specific problem as it worked fine on Firefox.  I only tried with Chrome Version 53.0.2785.143 (64-bit) and Firefox version 49.0.1.

[geojson-bug-1.26.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/544996/geojson-bug-1.26.txt)

**Comment by hpinkos** [comment]
Hello @ukitake,

The attached geoJson file worked fine for me in the current master.  Try clearing your cache/cookies.  That can sometime cause weird side effects when switching between version of Cesium.
I'm going to close this issue for now.  It's possible that we fixed some error between 1.26 and now, so feel free to re-open this issue if it's still not working when the 1.27 release comes out on November 1st.  Thanks!
