### ISSUE TITLE
Remove separate heading, pitch, roll value support in 1.30

### ISSUE THREAD

**Issue by twpayne** [AnalyticalGraphicsInc/cesium#4506]
Consequent to #4498, support for separate heading, pitch, and roll values in `Transforms.headingPitchRollToFixedFrame` and `Transforms.headingPitchRollQuaternion` should be removed in version 1.30.

**Comment by twpayne** [comment]
Please can someone with commit access to this repo add a "remove in 1.30" label to this bug.

**Comment by pjcozzi** [comment]
Will label now.

**Comment by hpinkos** [comment]
@twpayne @pjcozzi done
