### ISSUE TITLE
Model bounding sphere should scale with model scale

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4508]
From #4038

The model bounding sphere needs to scale with the model scale in the function noted in #4038 as well as other functions in `Model`

(Be sure that the scale doesn't get applied more than once)

**Comment by shehzan10** [comment]
Reviewed this with @pjcozzi.
The scale is being correctly applied in the [`boundingSphere` getter function](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L778).
The proposed change is applying the scale again and this results in incorrect behavior.

**Comment by pjcozzi** [comment]
Agreed, this breaks `minimumPixelSize`.  Thanks for investigating @shehzan10!
