### ISSUE TITLE
Setting globe TerrainProvider doesn't set underlying surface property?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4509]
@kring or @bagnell you are probably best qualified to answer this.

I was investigating why changing the terrain provider doesn't seem to update terrain clamping.  I noticed in https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Globe.js#L94, we construct the default `QuadtreePrimitive` using the default `terrainProvider` instance.  However, in the set method for `terrainProvder` (https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Globe.js#L252) we don't appear to update the `_surface` instance.

Is this a bug? 

I don't think it fixes the issue I was investigating, but it looked off enough to open an issue.

**Comment by kring** [comment]
@mramato the terrain provider is passed through to the `GlobeSurfaceTileProvider` on render:
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Globe.js#L494

I don't know of any particular reason for this offhand.  It might just be left over from when we didn't use JavaScript properties.  In any case, I'm pretty sure this isn't a bug, so I'm closing it.
