### ISSUE TITLE
PointPrimitive flickering and disappearing in Safari

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4519]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/kfr5KohKPvQ

Can someone with a mac/ipad/iphone test this out? https://storm.pps.eosdis.nasa.gov/storm/cesium/EVMini.html

The user reports all of the point primitives flicker then disappear in safari running on iPhone 6

**Comment by pjcozzi** [comment]
It works OK on Safari 9, OS X El Captain, Intel.

**Comment by lilleyse** [comment]
Confirmed that it flickers and disappears in iOS 10 on an iPad Pro.

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/gDODtmR4w5E

Safari 10.0.1 on macOS Sierra

**Comment by pjcozzi** [comment]
Perhaps now duplicate with #4712?

**Comment by pjcozzi** [comment]
Likely duplicate with #4712.
