### ISSUE TITLE
about PR 4498

### ISSUE THREAD

**Issue by kaktus40** [AnalyticalGraphicsInc/cesium#4527]
Hello,
for @twpayne , @pjcozzi  , @hpinkos : about  ``aircraftHeadingPitchRoll*``, I just need an explanation why it was removed. Is it a forbidden area like determining polygon area or is it a feature for cesium pro only?!? I just need explanation to adjust my next PR.
Thanks

**Comment by twpayne** [comment]
*Please not that I'm not a representative of Cesium*

I suggest we continue the discussion in #4498 rather than opening a new issue that duplicates the discussion in an existing one.
