### ISSUE TITLE
Run WebStorm JSDoc inspection and fix all errors

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4530]
Webstorm has an inspection titled `JSDoc comment matches function signature` which actually shows a lot of incorrect documentation throughout our codebase (115 warnings, though I'm sure some our false positives).  We should run this inspection and bring the result down to 0 (or some reasonable number if false positives are high).

To execute this, select `Code -> Run Inspection by Name` and then type JSDoc and it will show up.

**Comment by pjcozzi** [comment]
If we plan to automate this, that can be a separate issue or part of #652

**Comment by mramato** [comment]
> If we plan to automate this, that can be a separate issue or part of #652

Unfortunately this would be hard to automate (as it relies on webstorm), however when we finally switch to eslint, they have plugins for it.
