### ISSUE TITLE
entity.show error

### ISSUE THREAD

**Issue by jeffwhitty** [AnalyticalGraphicsInc/cesium#4540]
I just upgraded my project from the august release to the October release (we want clustering!), and had a few breaks, two of which I can't fix (I'll seperate them into two issues)

I have custom filtering on my entities. There's 20,000 entities, approximately half are billboard and half are just point. They represent one of about 20 'type' of underlying object. I have a list of all the types on my screen and I can click it to hide that type;
`for each entity in the viewer.entities collection;
if(entity.DisplayType == 'Type1'){
  entity.show = false;
}
`
I then do the reverse to unhide them
`
if(entity.DisplayType == 'Type1'){
  entity.show = true;
}
`
Prior to upgrading cesium this worked flawlessly. Entities disappeared, entities came back. Now they all disappear, but only entities with "point" come back - the ones that are billboards don't render. I have debugged to confirm that the entity.show property is changing from false to true for the missing billboards. I can confirm there are ZERO billboards that came back from thousands expected, so it's not a sometimes thing, it's every time. I rechecked the code on my UAT instance which is still the August release (since I'm still attempting to integrate the new version in DEV) and it works as expected.

**Comment by lilleyse** [comment]
This is fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/4460 and will be in the next release. In the meantime you can use master to confirm.
