### ISSUE TITLE
PolylineGraphics material colour withAlpha broken in latest version

### ISSUE THREAD

**Issue by jeffwhitty** [AnalyticalGraphicsInc/cesium#4541]
I have just upgraded my project from the August release to the October release and in my integration testing I hit something that has broken. 

I have a function that draws a half dozen polylines between various points. The points are all represented by their own entity as well, but I don't think that's relevant. This function broke and started throwing an error 

> TypeError: Cannot read property 'center' of undefined

 (which I later tracked down to actually being from my code that shows the mouse co-ordinate on mouse move - the error presented is not related to my line drawing function).

The first few lines draw fine, the last two both cause the error. I isolated them and confirmed that without these two lines everything works, and also that either of them alone will cause the failure.

I then tried a million things, because the lines are essentially a copy/paste of the previous line with a different colour and positions. I should mention each line is only one segment, two positions.

The offending line came down to the colour! This is broken;
`
var line = viewer.entities.getOrCreateEntity("line6");
line.name = "Line 6";
line.position = line6position; //<-- NOTE: line6position is the correct type and location
line.polyline = new Cesium.PolylineGraphics({
  positions: [startEntity.position._value, line6position],
  width: 2,
  _**material: Cesium.Color.WHITE.withAlpha(.4)**_
});
`
but this works;
`
var line = viewer.entities.getOrCreateEntity("line6");
line.name = "Line 6";
line.position = line6position; //<-- NOTE: line6position is the correct type and location
line.polyline = new Cesium.PolylineGraphics({
  positions: [startEntity.position._value, line6position],
  width: 2,
  _**material: Cesium.Color.WHITE**_
});
`

**Comment by hpinkos** [comment]
Hello @jeffwhitty 
I believe this issue was fixed in this PR #4532

The fix will be included in the 1.27 release coming out on November 1st.  If you are still seeing this problem with the new release, feel free to reopen this issue.  Thanks!
