### ISSUE TITLE
Scene Render Crashes with Large 3D Tiles

### ISSUE THREAD

**Issue by KermMartian** [AnalyticalGraphicsInc/cesium#4549]
I'm trying to debug an unusual Cesium crash with 3D Tiles. A hierarchy of Composite-packed models is being loaded (although the same issue occurred with un-composited b3dm models). The top-level tile and model loads fine; after zooming, Cesium starts to load the child models. After a predictable amount of time, which appears from the Network debugging tab in Chrome to correspond to all child Composite tiles being loaded, Cesium crashes with the following error, context, and call stack.

Error (in cesium/Source/Renderer/Texture.js):

```
        if (width <= 0) {
            throw new DeveloperError('Width must be greater than zero.');
        }
```

Call stack:

```
Texture
createTexture
updateFramebuffers
GlobeDepth.update
updateAndClearFramebuffers
executeCommandsInViewport
updateAndExecuteCommands
render
```

The context (that is, scene._context) passed all the way down to Texture() from updateAndClearFramebuffer has width (drawingBufferWidth) and height (drawingBufferHeight) 0. Therefore, as far as I can tell, the models themselves are not the problem. How can I proceed in debugging this issue, as I suspect Cesium itself, not my models, are at fault? Thanks in advance, and my apologies if it turns out to be a spurious issue.

**Comment by lilleyse** [comment]
How large is the tileset? This sounds like an out of memory issue.

**Comment by KermMartian** [comment]
The top-level tile is a ~50MB cmpt, and the children sum to about ~200MB, so that could definitely be the case; I'll reduce the detail in the tiles and try again. To keep this as a potentially useful issue, is there possibly a cleaner way to handle this, for example to provide a callback to allow the application to catch when loading a tile is going to cause this to occur, or is there no good way to do so?

**Comment by lilleyse** [comment]
The memory situation should have been improved now that [skipping lods](https://github.com/AnalyticalGraphicsInc/cesium/pull/5128) and [unloading based on memory usage](https://github.com/AnalyticalGraphicsInc/cesium/pull/5245) are in.

I'm going to close for now, but feel free to comment if there are still issues.

**Comment by jkumar80** [comment]
Hi,

I am facing same error. Is there any solution for this?, kindly let me know. 

Best Regards,
K.Jayakumar

**Comment by lilleyse** [comment]
@jkumar80 some things to try are

* Lower [maximumMemoryUsage](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#maximumMemoryUsage), maybe to 256 or 128.
* Raise [maximumScreenSpaceError](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#maximumScreenSpaceError), maybe to 32.

However if the tileset isn't well optimized it may still run into out of memory problems.

**Comment by jkumar80** [comment]
Thanks Iilleyse for your reply. Please let me know how to optimize the tile set?

**Comment by itsegg** [comment]
Hi,
I set maximumMemoryUsage = 512MB,But the browser memory uses 2G,And it will not fall.
My 3dtile has 100G size.

**Comment by mramato** [comment]
@itsegg Cesium's current strategy is to always load the amount of data required for the current scene and screen space error.  maximumMemoryUsage is just the size of the frame-to-frame cache.  We realize this is not ideal and plan on changing it, please follow #6226 for details.

In the meantime, your best solution is to raise maximumScreenSpace error for your tilesets.

**Comment by itsegg** [comment]
Thanks for your reply.

**Comment by itsegg** [comment]
@mramato 
Hi mramato,
I found a place in Cesium that caused the memory to keep increasing,
When tile.unloadTile (), _request also occupies memory.
After this modification, the memory of my browser stabilized at about 1.5G.
My Cesium version is 1.69
![image](https://user-images.githubusercontent.com/23716608/82994589-fc4efd00-a034-11ea-9f10-719cae4bc8e4.png)

**Comment by lilleyse** [comment]
@itsegg that looks suspiciously similar to https://github.com/CesiumGS/cesium/issues/8843

**Comment by heylying** [comment]
@mramato Hi! I try to load a large 3D tiles model more than 200GB and Cesium(version 1.71) crashes now. It is still out of memory. Now Is all I can do now is still raise maximumScreenSpace error?
