### ISSUE TITLE
isArray not used in UrlTemplateImageryProvider

### ISSUE THREAD

**Issue by fredj** [AnalyticalGraphicsInc/cesium#4554]
`Array.isArray` is [used](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.26/Source/Scene/UrlTemplateImageryProvider.js#L551) instead of the [isArray](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.26/Source/Core/isArray.js) module.

**Comment by fredj** [comment]
`Array.isArray` is also used in `WebMapTileServiceImageryProvider`

**Comment by fredj** [comment]
The native `Array.isArray` function is [widely supported](http://kangax.github.io/compat-table/es5/#test-Array_methods_Array.isArray), would you consider dropping `isArray`and always use the native function?

**Comment by mramato** [comment]
The main reason we still have the `isArray` helper is to allow Cesium to still be included on sites that need to support older browsers (mainly IE8).  Obviously Cesium won't work on these browsers, but trying to use a method like `isArray` would cause JS parsing itself to fail in certain cases, breaking the entire page.  This would make it impossible for apps built with Cesium to gracefully degrade on old browsers.

We could only use the `isArray` helper function is global initialization code and `Array.isArray` everywhere else, but it's just easier to always use the helper function instead.

That all being said, we can certainly change our policy at some point in the future, but making Cesium fundamentally incompatible with IE8 is something that would need to be discussed with the community first.

**Comment by fredj** [comment]
@mramato thanks for the answer; I will change `UrlTemplateImageryProvider` and `WebMapTileServiceImageryProvider` to use `isArray` instead of `Array.isArray`
