### ISSUE TITLE
Add cos to styling language

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4555]
For https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2

@Dylan-Brown like the [abs](https://github.com/AnalyticalGraphicsInc/cesium/pull/4545) function write a `cos` function for the styling language. Like `Math.cos` and glsl's `cos` it takes radians.

As part of the PR 
* [ ] Update `Expression.js` - Javascript and GLSL interpreters.
* [ ] Add tests to `ExpressionSpec.js`
* [ ] Add a style to `3D Tiles Point Cloud Styling.html` that uses the `cos` function to help visualize that things work.

After this we'll go quickly through the other trig functions.

**Comment by pjcozzi** [comment]
CC #3241

**Comment by lilleyse** [comment]
Completed in #4578
