### ISSUE TITLE
Add sqrt to styling language

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4556]
For https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2

@leesafini  like the [abs](https://github.com/AnalyticalGraphicsInc/cesium/pull/4545) function write a `sqrt` function for the styling language.

As part of the PR 
* [ ] Update `Expression.js` - Javascript and GLSL interpreters.
* [ ] Add tests to `ExpressionSpec.js`
* [ ] Add a style to `3D Tiles Point Cloud Styling.html` that uses the `sqrt` function to help visualize that things work.

After this we'll go quickly through the other simple math functions.

**Comment by pjcozzi** [comment]
CC #3241

**Comment by pjcozzi** [comment]
Added in #4606 thanks to @leesafini!
