### ISSUE TITLE
Android: FLOATING POINT TEXTURE EXTENSION IS REQUIRED BUT NOT SUPPORTED.

### ISSUE THREAD

**Issue by wkoeter** [AnalyticalGraphicsInc/cesium#4563]
It appears that loading data gives the following error:

RUNTIMEERROR: THE FLOATING POINT TEXTURE EXTENSION IS REQUIRED BUT NOT SUPPORTED.

I have a Samsung Galaxy S7. I've tried multiple browsers aswell but it keeps failing. The same javascript has no errors on pc browser.

**Comment by hpinkos** [comment]
Hello @wkoeter,
It looks like your phone might not have support for one of the WebGL extneions we use.  Go to http://webglreport.com/ and see if `OES_texture_float` is in the list of supported extensions.

**Comment by wkoeter** [comment]
Thanks for the fast reply. Indeed my Galaxy S7 seems to not support that extension. Is there a work around you might recommend? Or is it a dead end regarding my phone? Thanks in advance.

**Comment by mramato** [comment]
Currently, it's a dead end, but this was a recent change in Cesium and it's extremely unfortunate that the S7 does not support this extension.  I think we need to revisit this requirement since the S7 is such a popular phone.

I assume you tried Chrome?

CC @bagnell @pjcozzi

**Comment by wkoeter** [comment]
@mramato 

Okey that is unfortunate indeed. 
Yes i've tried Chrome, Chrome Beta, Opera and Firefox.

**Comment by pjcozzi** [comment]
IIRC this is a very widely supported extension (not sure why the S7 would not have it) and there were no good alternatives to not using it.  We could consider a sub-optimal fallback if there's enough users expected to not have support for this for quite some time to come.

**Comment by mramato** [comment]
> IIRC this is a very widely supported extension

According to https://community.arm.com/thread/9251, no Mali gpus support `OES_texture_float`, considering how popular Malu chipset is, I'm not sure we can claim it's widely supported enough to allow Cesium to be broken on it.  The Samsung Galaxy line alone (all of which are Mali I believe) is about 20% of the mobile market.  What's particularly bad is that this was a breaking change in a recent version of Cesium, so it used to work fine.  I understand there are some major technical hurdles here, but this is a huge reduction in Cesium device compatibility.

**Comment by malaretv** [comment]
We've been looking into building on top of Cesium's VR capabilities (which is already limited to android devices) and this issue is really biting us since we invested in Samsung Galaxy + [Gear](http://www.samsung.com/global/galaxy/gear-vr/) setup for testing purposes

**Comment by mramato** [comment]
> (which is already limited to android devices)

What makes you say this?  We've had Cesium running on Occulus devices in the past and there's no reason it can't work with other set ups as well (Vive, iphone, etc..).  I'll admit that it might need some work to update to the latest WebVR spec and definitely needs more testing, but the landscape isn't as bleak as you're painting it.  We would be happy to look at pull requests to improve Cesium's current implementation.

That all being said, I'm firmly in the "Has to work on Galaxy" camp, and VR compatibility is an unrelated issue I'd be happy to discuss on the forum (where more people can chime in what their thoughts).

**Comment by malaretv** [comment]
@mramato should've kept it at +1 for Galaxy support :+1: My misspoken bleakness comes from ignorance as i'm just getting my feet wet with VR support. Will be in touch in the forums

**Comment by hpinkos** [comment]
Reported on the forum: https://groups.google.com/d/msg/cesium-dev/Lsj-KsgR__U/3YYz5s4mAQAJ

**Comment by pjcozzi** [comment]
@bagnell and I discussed offline about adding an ugly but isolated ubyte RGBA fallback.  I marked this as `next release` since we may be able to get this to this in time.

There should also be a Chrome issue that @mramato may have the link too.

**Comment by pjcozzi** [comment]
There's a workaround for this in #4700.  We would appreciate if anyone is able to test the branch in that pull request and leave your feedback here.  If all goes well, we plan to ship this in Cesium 1.28 tomorrow.
