### ISSUE TITLE
Camera test failures in Edge 

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4565]
Most of the `CameraEventAggregator` and `ScreenSpaceCameraController` tests fail in Microsoft Edge.  We should investigate why (most likely bad tests) and get them to pass.

**Comment by HeercoGrond** [comment]
Is there any update to this? Right now, our functionality in Edge is broken because of it.

**Comment by pjcozzi** [comment]
No update, but we would welcome a pull request if you are able to look into this.  For info on the tests, see the [Testing Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/TestingGuide/README.md).

**Comment by HeercoGrond** [comment]
Sure thing - I'll have a crack at it.

**Comment by pjcozzi** [comment]
Thanks @HeercoGrond!  It is much appreciated.

**Comment by HeercoGrond** [comment]
Looking at the failures and the experiences we're having in Edge so far, it seems something with mouse-input registering goes terrible wrong. In our 'home' screen, for example, we can't click on things when the page is first loaded and only works when reloaded. All the values from ScreenSpaceCameraController for example are mostly the same when a simulated mouse movement is made.

I hope this information clarifies the issue somewhat, but I'll be looking into it some more when I get the time.

**Comment by shehzan10** [comment]
As of 1.30 release, I'm not seeing any of the Camera tests failin in Edge (v38.14393.0.0 with MS EdgeHTML v14.14393).

That said, I am seeing 2 errors in `Renderer/CubeMap draws with a cube map with premultiplied alpha` and `Renderer/Texture renders with premultiplied alpha` but nothing in the tests noted in this issue.

**Comment by shehzan10** [comment]
With regards to `CameraEventAggregator` and `ScreenSpaceCameraController`, these were only intermittent in the browser so could barely get any information out.

So I added #4993 which allowed running these tests from command line. Now the errors are consistent.

All the failures seem to stem from:
```
Edge 14.14393.0 (Windows 10 0.0.0) ERROR
  InvalidPointerId
  at Source/Core/ScreenSpaceEventHandler.js:602
```

**Comment by hpinkos** [comment]
I don't see these test failures either.  @mramato do you still see them?

**Comment by mramato** [comment]
Nope, looks good.
