### ISSUE TITLE
Disable scene mode picker in Atmosphere demo

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4568]
Since there's no atmosphere in 2D and Columbus View, we should disable the scene mode picker in the atmosphere demo

http://localhost:8080/Apps/Sandcastle/index.html?src=Atmosphere Color.html&label=All

**Comment by abhishekvp** [comment]
Hey @mramato , the commit for this issue seems to have been clubbed with the pull request I sent earlier for #4587 . I am sorry for this mix up. How do I fix this? From next time, I will remember to create a new branch before committing.

**Comment by hpinkos** [comment]
@abhishekvp you don't need to modify your pull request, it's okay that it fixes two issues since they're both small fixes to Sandcastle examples

**Comment by fredj** [comment]
fixed with #4591

**Comment by hpinkos** [comment]
thanks @fredj
