### ISSUE TITLE
Multiple problems with Pick position demo in Sandcastle

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4572]
The `Pick position` part of the overall picking example (http://localhost:8080/Apps/Sandcastle/index.html?src=Picking.html&label=All) has several problems.

1. Switching to 2D just causes a bunch of errors to the console because 2D isn't supported.  We should probably more gracefully handle this case in the demo.
2. CV silently fails.  Is pick position supposed to be supported for CV?

**Comment by pjcozzi** [comment]
#4892 patched the Sandcastle example.  #4084 is still open to fix the actual bug, now labeled `priority`.
