### ISSUE TITLE
Sandcastle terrain example clean up

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4575]
1. `Toggle lighting` should be a checkbox, not a button.
2. `Sample Everest Terrain` should update the camera to Everest as well.  Right now it appears to do nothing if you aren't already looking at Everest.

**Comment by abhishekvp** [comment]
Hey @mramato , this is my first pull request to Cesium. I have sent the completed CLA to the specified email address. Please let me know if there is anything else to do for fixing this issue.

Thanks.
