### ISSUE TITLE
3D Tiles - TileOrientedBoundingBox debug volume should be 2x2x2

### ISSUE THREAD

**Issue by sdgrimm** [AnalyticalGraphicsInc/cesium#4581]
I am using OrientedBoundingBox to create 3D Tiles point cloud tilesets with oriented bounding box volumes.  It works perfectly.  However, when Cesium3DTileset#debugShowBoundingVolume is enabled, the BoxOutlineGeometry is incorrect.  The cube being created is 1x1x1, but I believe it should be 2x2x2 to match OrientedBoundingBox.  See (https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/TileOrientedBoundingBox.js#L123).

**Comment by pjcozzi** [comment]
Thanks for the report, @sdgrimm.  I added this issue to the roadmap, #3241.

A pull request into the `3d-tiles` branch with a fix is also very welcome.  See [Getting Started Contributing](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#getting-started-contributing) if you have time to investigate.

**Comment by pjcozzi** [comment]
Thanks again for the report, @sdgrimm!  This was fixed in #4845 and is now in the 3D Tiles branch.
