### ISSUE TITLE
Update Cesium logo

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4582]
We've been using a new logo with a border around the Cesium icon which can be found on our logos page: https://github.com/AnalyticalGraphicsInc/cesium/wiki/Cesium-Logos

We should update the Cesium credit in the footer and the favicon to use this new logo

**Comment by emackey** [comment]
The thought of a `beginner` submitting something for this was enough to scare me into doing it myself.
