### ISSUE TITLE
HeightmapTessellator relativetoCenter issue

### ISSUE THREAD

**Issue by pasu** [AnalyticalGraphicsInc/cesium#4602]
hi, I think  this is a writing mistake here:
in HeightmapTessellator.computeVertices function:
var center = options.relativetoCenter; 
relativetoCenter -> relativeToCenter

**Comment by hpinkos** [comment]
Thanks @pasu! I've fixed the documentation

**Comment by lilleyse** [comment]
There's also a typo in the code.
`var center = options.relativetoCenter;`

**Comment by hpinkos** [comment]
Good catch @lilleyse!  I just saw that options.relativeToCenter was correct the first time it was called.

I'll fix this

**Comment by pasu** [comment]
:)
