### ISSUE TITLE
3D Tiles - trigonometric functions

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4603]
For https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2 and #3241 

@Dylan-Brown as with https://github.com/AnalyticalGraphicsInc/cesium/issues/4555 lets finish up the rest of the trigonometric functions.

Add support for:
- [x] radians(x) - convert value to radians
- [x] degrees(x) - convert value to degrees
- [x] sin(x)
- [x] tan(x)
- [x] asin(x)
- [x] acos(x)
- [x] atan(x)

Also add these functions to the 3D Tiles spec in a single PR.

In `3D Tiles Point Cloud Styling` Sandcastle, it's fine if you create 1 or 2 styles that call all of the trigonometric functions, including the `cos` one. The styles can just be called `trigonometric functions`.

Leaving `atan2` out of this PR since it takes two arguments.

**Comment by pjcozzi** [comment]
@lilleyse for this and #4604, I think you should consider a data-driven approach to avoid the duplication for the simple cases (more complicated functions can just have custom code and not be in the object property).  Can you please evaluate this approach and advise @Dylan-Brown and @leesafini?

**Comment by Dylan-Brown** [comment]
How would I write an example into the 3D Tiles Point Cloud Styling for the conversion functions (radians, degrees) in a way that makes sense?

**Comment by pjcozzi** [comment]
> How would I write an example into the 3D Tiles Point Cloud Styling for the conversion functions (radians, degrees) in a way that makes sense?

For a simple example, just combine them with a trig function, e.g.,
```
sin(radians(some_value_in_degrees))
degrees(sin(some_value_in_radians))
```
Then scale and bias this value to compute the color or create a color ramp.

**Comment by pjcozzi** [comment]
Sorry, this is wrong, of course:
```
degrees(sin(some_value_in_radians))
```
It should be `asin`.

**Comment by lilleyse** [comment]
> @lilleyse for this and #4604, I think you should consider a data-driven approach to avoid the duplication for the simple cases (more complicated functions can just have custom code and not be in the object property). Can you please evaluate this approach and advise @Dylan-Brown and @leesafini?

Here's a possible data-driven approach. Most of the `abs` areas can be replaced with code like:

```javascript
var unaryFunctions = {
    abs : Math.abs,
    sqrt : Math.sqrt,
    cos : Math.cos
};
```

```javascript
} else if (defined(unaryFunctions[call])) {
    //>>includeStart('debug', pragmas.debug);
    if (args.length < 1 || args.length > 1) {
        throw new DeveloperError('Error: ' + call + ' requires exactly one argument.');
    }
    //>>includeEnd('debug');
    val = createRuntimeAst(expression, args[0]);
    return new Node(ExpressionNodeType.UNARY, call, val);
}
```

```javascript
} else if (defined(unaryFunctions[node._value])) {
    node.evaluate = getEvaluateUnaryFunction(node._value);
}
```

```javascript
function getEvaluateUnaryFunction(call) {
    var evaluate = unaryFunctions[call];
    return function(feature) {
        return evaluate(this._left.evaluate(feature));
    }
}
```

GLSL section - works as long as the function names are valid GLSL functions, which I believe is true for all the built-ins we are adding.
```javascript
} else if (defined(unaryFunctions[value])) {
    return value + '(' + left + ')';
}
```

**Comment by pjcozzi** [comment]
Yes, exactly.  That is beautiful!

**Comment by Dylan-Brown** [comment]
Relevant changes made

**Comment by pjcozzi** [comment]
@lilleyse is the above tasklist up-to-date?  Can we close this?

**Comment by lilleyse** [comment]
Checked all the boxes, just forgot to close.
