### ISSUE TITLE
3D Tiles - sign, floor, ceil, round, etc for styling language

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4604]
For https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2 and #3241

@leesafini After #4556 is done let's add these functions to the styling language in a single PR:

- [ ] sign(x)
- [ ] floor(x)
- [ ] ceil(x)
- [ ] round(x)
- [ ] exp(x)
- [ ] log(x)
- [ ] exp2(x)
- [ ] log2(x)
- [ ] fract(x) - glsl has a built-in function for this, but JavaScript Math does not - you'll need to come up with a good command for doing this in JS

Also add these functions to the 3D Tiles spec in a single PR.

In the `3D Tiles Point Cloud Styling` Sandcastle feel free to use multiple functions in the same style. For example floor, ceil, and round could all go together, exp, log, exp2, log2 could also go together.

**Comment by Dylan-Brown** [comment]
@lilleyse Is this issue finished?

**Comment by lilleyse** [comment]
Yup it is, thanks for checking.
