### ISSUE TITLE
EllipsoidTerrainProvider with WebMercatorTilingScheme

### ISSUE THREAD

**Issue by pasu** [AnalyticalGraphicsInc/cesium#4610]
Hi, I think in some situations, especially when we needn't terrain data and mostly the imageryProvider is WebMercatorTilingScheme mode
, it is better to set EllipsoidTerrainProvider tilingScheme as WebMercatorTilingScheme because of high performance and high texture quality.
So, how about it:
`ImageryLayer.prototype._reprojectTexture = function(frameState, imagery,terrainTilingScheme)`

we add the terrainTilingScheme as a parameter, then we can judge whether to reprojectTexture:

`var bBothWebMercatorTilingScheme = (this._imageryProvider.tilingScheme instanceof WebMercatorTilingScheme) &&
            (terrainTilingScheme instanceof WebMercatorTilingScheme);`

of couse, I think it is ok that ignoring this situation that EllipsoidTerrainProvider is WebMercatorTilingScheme while imageryProvider is GeographicTilingScheme.

here is my example for this test:
https://github.com/pasu/ExamplesforCesium/blob/master/globeTerrain.html

![1](https://cloud.githubusercontent.com/assets/2180609/20027658/58bbec74-a354-11e6-91c0-9c77dd58bc65.png)

**Comment by pasu** [comment]
I hope somebody can give me a response,
Maybe my idea is not suitable or this situation is rare, so I can get it.
thanks @hpinkos  :)

**Comment by hpinkos** [comment]
Sorry I missed this @pasu
This isn't an area of the code I'm very familiar with, @pjcozzi @kring do you have some feedback?

**Comment by pjcozzi** [comment]
@kring is the best person to advise here.  There was this recent change: #4339.

**Comment by pasu** [comment]
@pjcozzi I got it from the latest version, it is a smart and general solution for this issue. The comparison and analysis are clear.So happy for this improvement:)
