### ISSUE TITLE
Cesium TIFF to PNG Proxy

### ISSUE THREAD

**Issue by elfayoumi** [AnalyticalGraphicsInc/cesium#4627]
Hello
I am trying to consume an esri DEM image service using Cesium, I read that I need a TIFF to PNG proxy, and found the code here under tools, but I am not sure how to use it?
Is there any doc, is it just a jar file, you run as a service?
Would you please explain how to use it?

Regards
Ibrahim

**Comment by hpinkos** [comment]
Hello Ibrahim,

Cesium don't have support for TIFFs and I don't think we have a proxy for doing this.

Please ask question like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub issues for bug tracking and planning new features.  Plus, more people will see your question and hopefully be able to help.

-Hannah
