### ISSUE TITLE
Option to hide errors when using sampleTerrain and it throws 404.

### ISSUE THREAD

**Issue by HeercoGrond** [AnalyticalGraphicsInc/cesium#4634]
Hello there,

For our application we're working on a worldwide scale and use the sampleTerrain functionality quite a lot. Now this works great, however, I've written a method that verifies what the 'highest' LOD for a certain area is and it works pretty well, but throws a massive amount of errors from Cesium itself in low LOD areas. For example, in Mirny Mine the highest LOD for terrain is 9. Since the method starts at 15 and returns the first " possible" option, it throws 6 404 errors. Is there a way to hide these?

**Comment by HeercoGrond** [comment]
`var promise = new Promise(function(resolve, reject){ 
        testTerrain();

        function testTerrain(){
            Cesium.sampleTerrain(terrainProvider, currentPos, testCarto).then(function(result){
                if(result[0].height !== undefined){;
                    correctZoomLevel = currentPos;
                    resolve(correctZoomLevel);
                } else {
                    currentPos--;
                    testTerrain();
                }
            });
        }
    });
    `

I added the relevant code for reference.

**Comment by hpinkos** [comment]
Hello @HeercoGrond,
Please ask questions like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub issues for bug reports and planning new features.  Plus, there's a greater likelihood that someone will see your question and be able to help.
Thanks!
