### ISSUE TITLE
3D Tiles - binary functions

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4643]
@leesafini Similar to the work that @Dylan-Brown is doing for the unary functions, we want a data-driven approach for the following binary functions to avoid a lot of duplicate code:

* atan2
* pow
* min
* max

https://github.com/AnalyticalGraphicsInc/cesium/issues/4603#issuecomment-258867315

You'll need to make a few modifications so it supports sending in two values instead of one. These are some examples:

```javascript
left = createRuntimeAst(expression, args[0]);
right = createRuntimeAst(expression, args[1]);
return new Node(ExpressionNodeType.BINARY, call, left, right);
```
```javascript
return evaluate(this._left.evaluate(feature), this._right.evaluate(feature));
```

**Comment by leesafini** [comment]
This is mostly done, but I'm struggling with how to come up with a meaningful demo in the Point Cloud Styling. Is there any value that is meaningfully comparable for each point (for min, max)? Completely at a loss for atan2 and pow.

**Comment by lilleyse** [comment]
For min and max you can reference the point's position in some way. This could create a gradient effect where the core of the point cloud is solid, the outer edges are solid, but the middle area (between the min and max values) is a gradient.

For atan2 you can add it to one of the styles in https://github.com/AnalyticalGraphicsInc/cesium/pull/4628, once that is in.

For pow something simple like temperature^3 is ok, like the sqrt one.

**Comment by leesafini** [comment]
Now having issues in the point cloud demo using atan2:
`RuntimeError: Vertex shader failed to compile.  Compile log: ERROR: 0:8: 'atan2' : no matching overloaded function found`

I understand what it's saying but not why it's saying it. It's doing this no matter what arguments I use. I don't get, if min, max, and pow are all working and set up the same way, why atan2 wouldn't work as well.

**Comment by lilleyse** [comment]
In GLSL `atan2` is just called `atan`. I had left a small note here: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2.

**Comment by leesafini** [comment]
Aha, okay, that makes sense. I've updated it so that calling atan2 runs Math.atan, but I'm still getting this exception. Should I be doing something differently? I can't change it entirely to atan because of the checks for the number of arguments in ExpressionSpec.

**Comment by lilleyse** [comment]
Where it builds the shader you will need to add a special case for `atan2`. Right near this section.

```javascript
} else if (defined(unaryFunctions[value])) {
    return value + '(' + left + ')';
```

**Comment by leesafini** [comment]
I already have a case for all of the binary functions.

`else if (defined(binaryFunctions[value])) {
                    return value + '(' + left + ', ' + right + ')';`

I should be treating `atan2` differently than even these?

**Comment by lilleyse** [comment]
> I should be treating atan2 differently than even these?

Yup

**Comment by leesafini** [comment]
Really confused by this. Should it not be called `atan2` at all, and just be `atan` with two arguments? Meaning it would be treated as a unary function until it sees that it has two arguments? Or would it still be called `atan2`, defined as a binary function, but treated differently once it's encountered?

**Comment by lilleyse** [comment]
Yes the second case. It only is treated differently in the glsl section. Right above the code for checking the binary functions it should check if the name is atan2, and if so build the shader using    atan. Sorry I think I was misleading when I referenced the unaryfunctions area.

**Comment by leesafini** [comment]
Got it, thanks!
