### ISSUE TITLE
Calling makeStyleDirty has no effect

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#4646]
I have multiple tilesets in a app with same style. To not store a reference to each tileset but still be able to modify the style, I have stored a reference to this generic style, so I can change properties there and it effects all tilesets. But I'm not apply to see my changes.

A simple demo to demonstrate this issue:
```
var tileset = new Cesium3DTileset({url : 'data'});
tileset.style = new Cesium3DTileStyle({
	"pointSize" : 2
});

viewer.scene.primitives.add(tileset);

window.setTimeout(
	// This does not work
	function() {
		tileset.style.pointSize = new Expression("10");
		tileset.makeStyleDirty();
		console.log("10");
	}
, 2500);
	
window.setTimeout(
	// This works
	function() {
		tileset.style =  new Cesium3DTileStyle({
			"pointSize" : 5
		});
		console.log("5");
	}
, 5000);
```

**Comment by pjcozzi** [comment]
@SunBlack thanks for the report, @lilleyse fixed this in #4655.
