### ISSUE TITLE
Why use multi-frustum to solve the depth buffer problem when logarithmic depth buffer method works fine?

### ISSUE THREAD

**Issue by PlutoniumHeart** [AnalyticalGraphicsInc/cesium#4653]
Hi,

I am not sure what I am missing, but as far as I know logarithmic depth buffer method is effective with very large view distance (S_min = 3.75m with Far plane = 10000000m, constant C=1, at distance = 1000000000m, change to C can easily get S_min to come down to less than 1 meter), and it only requires modification to the VS (if the depth buffer need to be correctly interpolated also small modification to FS, but it can be optimized out [1]). I understand there is a small (not sure if noticeable) performance drawback, is this the main reason multi-frustum method is used?

As far as performance, doesn't multi-frustum method has a higher impact? And the multi-frustum method also introduced some hard to workaround problems like the artifact with transparent objects. 

So may I ask why is multi-frustum method still preferred in cesium? 

Thanks!

[1] http://outerra.blogspot.com/2012/11/maximizing-depth-buffer-range-and.html

**Comment by hpinkos** [comment]
Hello @PlutoniumHeart, here is information from a course Patrick did at SIGGRAPH a few years ago: https://cesiumjs.org/massiveworlds/index.html#UsingMultipleFrustumsforMassiveWorlds
The first part of the course is all about using multiple frustums.

If you have follow up questions, please post on our forum: https://groups.google.com/forum/#!forum/cesium-dev
The forum is a better platform for questions and discussions like this.  We use GitHub issues exclusively for tracking bugs and planning new features.

Thanks!

**Comment by emackey** [comment]
@pjcozzi @bagnell Have we ever looked into logarithmic depth?  There's a [demo](https://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html).  The dynamic range looks plenty large enough, but I can't tell at a glance if it supports having the camera at Earth/Moon distances while looking at <1 meter objects.

**Comment by pjcozzi** [comment]
yes, @emackey, it has lots of issues like requiring depth writes in fragment shaders and still not providing enough depth range.  See the SIGGRAPH course or the chapter in the virtual globe book.

**Comment by PlutoniumHeart** [comment]
@hpinkos Sorry for posting the question here, but before I did, I already went through the slides, it didn't talk much about why choosing multi-frustum over logarithmic. 
@emackey logarithmic depth definitely works for <1 meter objects, while looking at 300000 km meter objects at the same time. 
@pjcozzi I am not sure what kind of depth range is enough, but with a 32bit depth buffer, S_min is quite reasonable at the scale of the earth, you can even place the camera at one edge of the solar system and it still provides ~40 meter resolution at the other edge of the solar system. Can you explain a little bit more about the requirements?

**Comment by pjcozzi** [comment]
@PlutoniumHeart Cesium needs to be able to handle satellites in High-Earth Orbit down to bolts on a car.

Try this demo and switch between the different z-buffer options to see how log-z and reverse 32-bit floating-point break down: https://github.com/virtualglobebook/OpenGlobe/tree/master/Source/Examples/Chapter06/DepthBufferPrecision

You are, of course, encouraged to experiment with different options in Cesium and see what you come up with.  We would love only require a single frustum.
