### ISSUE TITLE
Polygons Don't Have Outline Even When Terrain Server Isn't Present

### ISSUE THREAD

**Issue by billwritescode** [AnalyticalGraphicsInc/cesium#4659]
When no terrain server is present, polygons still don't have an outline. There is a log in the console saying:
> Entity geometry outlines are unsupported on terrain. Outlines will be disabled. To enable outlines, disable geometry terrain clamping by explicitly setting height to 0.

But there is no terrain because there is no terrain server.

When there is no terrain present, the polygon is being clamped to the ellipsoid. In this case, the user experience is confusing because you would expect to see your outlines. I would think the desired behavior for this case is equivalent to the case where the user explicitly sets height to 0.

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polygon.html&label=Geometries

![no-terrain-no-outlines](https://cloud.githubusercontent.com/assets/10883162/20366141/cd584250-ac17-11e6-9203-c1c516cfc299.PNG)

**Comment by hpinkos** [comment]
Thanks @billwritescode,  you're right, from an API perspective this could be improved.  

It works this way because of what is going on behind the scenes.  A `GroundPrimitive` is used when height reference is clamp to ground, and a `Primitive` is used when the polygon has a defined height.

**Comment by billwritescode** [comment]
Thanks @hpinkos! I suspect that cesium internally is treating the ellipsoid as the terrain to clamp to in this case.

**Comment by pjcozzi** [comment]
In the shorter-term, should we update this Sandcastle example so it doesn't generate the console warning?

**Comment by hpinkos** [comment]
I think we already updated all of the examples so they don't have a console warning

**Comment by pjcozzi** [comment]
I just tested the Polygon Sandcastle example in master and received the above console warning.

**Comment by hpinkos** [comment]
duplicate #6694
