### ISSUE TITLE
ScreenSpaceCameraController.minimumZoomDistance default is incorrect

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#4660]
If you look at the code you'll see the actual default and the default in the doc are different. We should make them match.

I'm not sure what the correct value is. I've noticed that the value of `1.0` causes issues when you can zoom through terrain if you are zooming in to a mountain.

```javascript
        /**
         * The minimum magnitude, in meters, of the camera position when zooming. Defaults to 20.0.
         * @type {Number}
         * @default 20.0
         */
        this.minimumZoomDistance = 1.0;
```

**Comment by pjcozzi** [comment]
@bagnell do you know which is correct?

**Comment by bagnell** [comment]
`1.0` is correct. It used to be `20.0` to prevent the camera from clipping terrain in certain situations.

**Comment by mramato** [comment]
Unfortunately, @tfili found this because the camera is clipping terrain in certain situations 😈
