### ISSUE TITLE
The Case of the Misrendering Polygons

### ISSUE THREAD

**Issue by billwritescode** [AnalyticalGraphicsInc/cesium#4661]
Polygons sometimes misrender when terrain is on. 

I'm not exactly sure what's causing this issue. I made sure to put the polygons over the ocean as an attempt to minimize the disruption caused by terrain data. It would seem strange to have disruptive terrain data over the ocean! I would be very impressed if waves were being taken into account :).

The sandcastle is here:

http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=93fb9028cb5f69539e2a761cff0da02f

First, go to that sandcastle in your browser. Then, if all three triangles appear, try zooming in and out a bit or panning the map. If the issue still isn't appearing, try playing with the size of the viewport. I've included two screenshots here. The difference between the two screenshots is the width of the viewport.

![broken-polygons](https://cloud.githubusercontent.com/assets/10883162/20367664/7896b4ac-ac1e-11e6-804f-c77e12714ba4.PNG)
![broken-polys-biggercapture](https://cloud.githubusercontent.com/assets/10883162/20367666/79e75a82-ac1e-11e6-9223-84f5319fa0d7.PNG)

Perhaps this is related: https://github.com/AnalyticalGraphicsInc/cesium/issues/4161

For the sake of completeness, the above screenshots were taken with a slightly different sandcastle that had some extra stuff in it. That sandcastle is here: 
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=aa76c839e7ee9172563e1c0fa7bde6f4

**Comment by hpinkos** [comment]
Thanks @billwritescode, this does look like the same problem as #4161 
I'm going to close this issue and add a comment to that one
