### ISSUE TITLE
Cesium License

### ISSUE THREAD

**Issue by pasu** [AnalyticalGraphicsInc/cesium#4666]
There is an issue I am confused about. It is about Cesium license(Apache 2.0).

My team is developing a production which is based on Cesium. We add some new features, modify a few source files and obfuscate Cesium.js.
But for some reasons, this production is not an open source project.

In this production package, we contain Cesium's original files including CHANGES,README,LICENSE, and we provide a list to mark these files we modified.	
Meanwhile we also build a web application based on our production.
	
Here is the link of our production: http://www.supermapol.com/webgl/downloads.html
and our web application: http://www.supermapol.com/earth/
and there are two pics as the attachments you can see them.
	
Honestly We do not want to hide the fact that our production is based on Cesium, and what we did is for protecting our source files.

I want to make sure whether this situation is legal and I really want to get your suggestions.
	
Thanks for your reply.
![1webgl](https://cloud.githubusercontent.com/assets/2180609/20421053/924dc230-ad9c-11e6-9c56-e95006e720ad.png)
![2se](https://cloud.githubusercontent.com/assets/2180609/20421054/92542580-ad9c-11e6-836b-3e65794664ee.jpg)

**Comment by pasu** [comment]
I know it is very unsuitable to talk about this issue here.  And I also send an email to <todd@agi.com>

I think I follow the requires of the license, but I am not quiet sure. I need to get your suggestions.
So, I will focus on this issue and clear the inappropriate content as quickly as possible.

Thanks and hope for your help.
@mramato

**Comment by pjcozzi** [comment]
Todd is in touch with @pasu.

For everyone's benefit: the Apache 2.0 license does not require tracking or making available modifications to Cesium.  Pull requests are always welcome, of course.  For more on contributing, see [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).

**Comment by pasu** [comment]
OK, I get it, Thanks.
Personally,  It is my honor to make contributions. Actually nowadays, I am writing some articles about Cesium in my blog. I hope more Chinese can feel the beauty of Cesium. And I always recommend others to read your books. Thanks for sharing. @pjcozzi
