### ISSUE TITLE
about cesium copyright 

### ISSUE THREAD

**Issue by aninggo** [AnalyticalGraphicsInc/cesium#4672]
[supermap inc](http://www.supermapol.com/earth/)
China's supermap company use your opensource project declare their own intellectual property and does not meet the apache 2.0 license.
![snip20161122_1](https://cloud.githubusercontent.com/assets/112144/20509503/1b390c8a-b0a4-11e6-9160-d39ec19f8159.png)

**Comment by maming** [comment]
bad company

**Comment by erikmaarten** [comment]
Thanks @aninggo for reporting. A Supermap representative has already contacted us about licensing (#4666) so we're in touch with them about how to handle this.
