### ISSUE TITLE
Scroll wheel zoom goes through the earth

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4680]
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/xeRAg8lObUg

> If you go to this sandcastle:
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Geometry%20and%20Appearances.html&label=Showcases
>
>Make the camera perpendicular to the earth then zoom in quickly as far/fast as you can using the mouse wheel with the mouse over a 3D shape, you'll zoom through the earth about 10-20% of the time.
>
>NOTE: It doesn't seem to happen nearly as often if the camera is on an angle, or if the mouse isn't over a shape.
>
>It only seems to happen for me on Mac OS X and Ubuntu. It does not happen on Windows. I am able to reliably re-create the issue using OS X Sierra and Chrome 55

**Comment by smills2929** [comment]
I've noticed that the viewer.scene.screenSpaceCameraController.minimumZoomDistance keeps being set to 0, regardless of what I set it to. 

From a quick search of the Cesium source it seems that controller.minimumZoomDistance is being set in multiple places around the application every frame. How can I stop this being set to 0?

**Comment by pjcozzi** [comment]
CC #2968 and #3037

**Comment by hpinkos** [comment]
Closing as duplicate of #4855
