### ISSUE TITLE
3D Tiles - memory management

### ISSUE THREAD

**Issue by iWun** [AnalyticalGraphicsInc/cesium#4683]
Hello everybody，
  I have tried to convert some **texture models** into b3dm according to official documentation, and have successfully loaded into Cesium. When I zoom out, some distant models disappear (I guess it was cut off), but why the memory does not change.
  I think since the model has been cut off, the memory should be reduced. is it a [bug](https://github.com/AnalyticalGraphicsInc/cesium/issues/4645)?
  Anyone can help me? thanks.

**Comment by lilleyse** [comment]
Tiles that are out of view may still be cached and stay in memory. By default the maximum number of cached tiles is 256. What happens when you construct `Cesium3DTileset` with `maximumNumberOfLoadedTiles : 0` ?

**Comment by iWun** [comment]
It works. Thanks a lot.
