### ISSUE TITLE
Alpha not working for certain colors in Firefox 50

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4687]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/lmPHhYxMd7c

In the example below, the wall should be transparent gray but shows up solid in Firefox.  `Red.withAlpha(0.5)` works fine.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var entities = viewer.entities;

var cartesianPositions = Cesium.Cartesian3.fromDegreesArrayHeights( [-71.4178416666667, 43.5730416666667, 50000, -72.3041944444444, 43.6261111111111, 50000] );

entities.add( {
    wall: {
        positions: cartesianPositions,
        material: new Cesium.Color.GRAY.withAlpha(0.5)
    }
});

viewer.zoomTo(viewer.entities);
```

The `GREEN.withAlpha(0.5)` in this example is also not working: http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Rectangle.html&label=Geometries

**Comment by hpinkos** [comment]
@pjcozzi should this be labeled next release?

**Comment by lilleyse** [comment]
Also here: https://github.com/AnalyticalGraphicsInc/cesium/issues/4658

**Comment by hpinkos** [comment]
@lilleyse Thanks, I missed that issue.  Should we close this as a duplicate or is it a different issue?

**Comment by lilleyse** [comment]
It's the same issue, we either one can be closed.
