### ISSUE TITLE
Tile Seams Don't Load Correctly

### ISSUE THREAD

**Issue by esparano** [AnalyticalGraphicsInc/cesium#4698]
If you zoom in to longitude -110, latitude 45 in Cesium Sandbox v1.27, then rotate the camera near the "seam" between two tiles, one of the tiles will not load at specific angles and you will see the black skybox through the Earth.

**Comment by hpinkos** [comment]
Thanks @esparano, but this is an artifact in the Bing Maps imagery, not a problem with Cesium.  Other imagery sources do not have noticeable seams here.

**Comment by mramato** [comment]
I can reproduce the problem with all imagery providers, this is definitely a cracking bug.  However, we already have it documented in #3710.  @bagnell it would be nice to look into the cracking sometime soon.

**Comment by mramato** [comment]
Also, thanks @esparano!
