### ISSUE TITLE
PointPrimitives not rendering in Safari

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4712]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/YziA_6iXFeo

This user says that points don't render in Safari and see's this error: drawarrays: attempt to access out of bounds

> I am currently seeing this on OSX:Sierra 10.12.1
> Nvidia GT 750M 2048MB / Intel Iris Pro 1536MB
> And Safari 10.0.1

Can someone with a mac see if they can reproduce this problem?
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Points.html&label=Showcases

**Comment by pjcozzi** [comment]
It could be OS X Sierra / Safari 10.  This works OK for me with:

> OS X 10.11, El Captain
Intel GPU
Safari 9.0.3

I do not think this would be NVIDIA.

**Comment by movestill** [comment]
Just came across this bug, today. On my same system using Chrome, I don't have a problem.

OS X 10.11, El Capitan
AMD Radeon R9 M370X 2048MB / Intel Iris Pro
Safari 10.0.1

**Comment by pjcozzi** [comment]
Forum posts from #4519:

* https://groups.google.com/forum/?hl=en#!topic/cesium-dev/kfr5KohKPvQ
* https://groups.google.com/forum/?hl=en#!topic/cesium-dev/gDODtmR4w5E

**Comment by briegn1** [comment]
I just updated all of my code to 1.30, and I no longer have this issue in Safari on iPhone 6. Whether the fix was inadvertently done in one of the CesiumJS updates or was part of one of the Apple updates, I don't know, but lots of pointPrimitives are rendering now seamlessly.

**Comment by hpinkos** [comment]
Thanks for the update @briegn1!

**Comment by pjcozzi** [comment]
@movestill would you be able to retest as well so we know if we can close this?

**Comment by movestill** [comment]
Looks good! Still running El Capitan but now using Safari 10.0.3.

**Comment by axman6** [comment]
Does someone have a service running somewhere which uses this version? Happy to test it on Sierra if someone has a link quickly available.

**Comment by pjcozzi** [comment]
@movestill thanks for verifying.

@axman6 try the different dropdown options in this example: http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=development/PointPrimitives.html&label=Development.

**Comment by axman6** [comment]
Looks like it's working for me in Safari 10.0.3 on macOS 10.12.3, nice work whoever fixed this =)

**Comment by pjcozzi** [comment]
@axman6 thanks for looking.  Probably the Safari update fixed this.
