### ISSUE TITLE
Many billboards, few BillboardCollections enhancement

### ISSUE THREAD

**Issue by jeffwhitty** [AnalyticalGraphicsInc/cesium#4719]
My apologies for submitting this as an issue when it really belongs in a discussion forum, but I have no means of posting in the forum at the moment (yay for enterprise security nazis!)

I am displaying about 40,000 positions on my globe. The vast majority are represented by a billboard (specifically a coloured arrow indicating the position type, heading, and rough velocity). Some are simply coloured circles (points).

My performance is pretty ordinary. If I turn all of the billboard off and change them to points the performance is quite good, so I've narrowed down that it is the billboards that are the issue as opposed to the number of positions. I am only using six images for the billboards and they're super tiny, and the colour is set in the code (the image is white).

Reading would suggest that if I made one billboard collection and jammed all the billboards onto it that my problem would be vastly improved, however I desire the functionality of working with the viewer.entities collection (the entities have extended properties, labels, description panel).

Is there any easy way I can instruct all of my billboards to share a collection? Would jamming my images into a texture atlas help? I've seen things light flightradar24x7 that have heaps of billboards out there, how have they made that performant?

My thoughts without knowing much about how Cesium is put together is to have a parameter to allow me to specify the billboardcollection when I create the billboard on the entity - ideas?

**Comment by hpinkos** [comment]
Hello @jeffwhitty, points are optimized for performance to that's why you're seeing better performance with that than with billboards.
For billboard entities, the billboards share a collection behind the scenes, so there's nothing else you can do to improve performance that I can think of, sorry

**Comment by pjcozzi** [comment]
@jeffwhitty this post is for point, but the same ideas apply: try using `scaleByDistance`/`translucencyByDistance` to have fewer total pixels: https://cesiumjs.org/2016/03/02/Performance-Tips-for-Points/

**Comment by jeffwhitty** [comment]
Thanks @pjcozzi but we're actually using scale to convey additional information already.

Would I correctly assume that the pointgraphics simply draws a circlegeometry? In which case could I possibly override that to draw a polygon geometry (in my case, define a triangle)? I'm happy to give it a go myself, but I can't see where this happens.

**Comment by hpinkos** [comment]
@jeffwhitty `PointGraphics` uses a `PointPrimitiveCollection` to add points to the scene.  It is very different from a `CircleGeometry`, which is a geometry type for drawing an ellipse on the globe surface.
The `PointPrimitiveCollection` was specifically designed to draw many circular points very efficiently so there isn't any way to customize the shape.  You would need to make changes to the shaders and possibly a few other places in the code in order to make it to draw triangles instead.  You can see the code involved with creating the point primitive collection in this pull request: https://github.com/AnalyticalGraphicsInc/cesium/pull/2632/files

**Comment by emackey** [comment]
@jeffwhitty @hpinkos actually I've always had dreams of customizing the shape of PointPrimitive to be more flexible than just circles, but it's tricky to figure out what the API would be that would be flexible enough to allow users to supply custom shapes somehow.

The shape itself comes straight from the [fragment shader here](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.28/Source/Shaders/PointPrimitiveCollectionFS.glsl), and as you can see the shader is quite short.  It computes the current fragment's distance from the center of the pointprimitive, and uses that length to determine if the fragment is in the center part, the outline part, or outside of the round dot (in the corners of the rectangular region being considered).  Drawing a triangle isn't too hard, the code would consider separately the horizontal and vertical distances of the fragment from the bottom-center or top-center of the space and make a decision along the lines of "horizontal distance * 2 < vertical distance" or similar, to see if a given fragment is inside the triangle.

**Comment by jeffwhitty** [comment]
Thanks @emackey, I especially like the way you left that hanging for me to investigate myself :)

I'll have a play with it, and if I have any luck I'll drop it this way so someone who knows what they're doing can review it and consider it for inclusion later.

**Comment by jeffwhitty** [comment]
Wow, that was a helluva crash course in webGL. So I've had some success in that I can modify the appearance of the point directly, changing its basic geometric appearance based on a formula. As you're aware though it's all or nothing, I can change the appearance for all points the same, so my circles all became squares, or triangles. 

I'm not skilled enough in this area to solve the API problem of how to let the developer specify their own geometry, but I'm hoping it might be 'simple' enough to pass a few properties from the point? In my case I've created a few extra properties (entity.addProperty()) that would allow me to code some logic into the shader, for example I have Speed and Heading. Depending on speed, I draw slightly different shapes easily enough. Based on heading though, I want to rotate the point (with the billboards there is a rotation property).

So, any idea how I can quickly/easily access the properties of the point in the Fragment Shader and where I would jam in a rotation property on the point (which would far simplify my maths in that respect)? I'm going to continue investigating to see if I can copy rotation from the billboards somehow.

**Comment by emackey** [comment]
Unfortunately it's not quick or easy, as the parameters have to be passed through "vertex attributes" (possibly compressed vertex attributes) and get passed through (or decompressed by) the vertex shader.  This is because space is quite constrained getting per-vertex data from JavaScript onto the graphics card and down the pipeline to the fragment shader.

Before you start chasing all that, have you tried just creating your own BillboardCollection, and managing your own billboards directly, without touching the Entity layer?  That might be a lot easier, and give more performance than you're seeing now.

**Comment by jeffwhitty** [comment]
I did try the single billboardcollection but that's going to involve refitting a heap of stuff to do the management features which are built in to the Entity layer. It also means when my data changes between being a point and being a Billboard there's checking and so forth, not to mention the messing about for billboards that move over time with the animation...

What if I were to 'clone' the PointPrimitive and make a "TrianglePointPrimitive" that always rendered the triangle and rotated it? Then instead of entity.point I could use entity.triangle and set the same properties? This would give the developer the opportunity to select a predefined shape, not their own geometry I realise. Again I realise it's not quite that simple. For the moment I guess I'll take a less elegant approach and reduce the number of entities I'm showing by default with some filters.
