### ISSUE TITLE
Billboard Put Holes in Polygons

### ISSUE THREAD

**Issue by billwritescode** [AnalyticalGraphicsInc/cesium#4720]
Billboards seem to put putting holes in polygons. I made sure to show the code in the screenshots in order to easily view what is clamped to ground and what is not. The billboard is putting holes in the polygon in many cases. I would expect that the billboard never puts holes in polygons.

http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=0f4feb87ebd2f9b360608cd3889e1e81

![billboards-put-holes-in-features](https://cloud.githubusercontent.com/assets/10883162/20936729/a5b411d0-bbb1-11e6-973f-ff53f14f08c7.gif)

![bb-clamp](https://cloud.githubusercontent.com/assets/10883162/20936770/dac2dd16-bbb1-11e6-9959-32d2bae983f5.PNG)

![bb-poly-clamp](https://cloud.githubusercontent.com/assets/10883162/20936847/35dd7198-bbb2-11e6-9ad2-8df8e06e0ed4.PNG)

**Comment by hpinkos** [comment]
Thanks @billwritescode.  This is actually a known issue, we have a bug report open here: #2130 
I'm going to close this issue since it's a duplicate and link the other issue to this one.
