### ISSUE TITLE
Evaluate why WalkingLady glTF model does not load in Cesium

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4722]
Is this an issue in Cesium or the sample model? https://github.com/KhronosGroup/glTF-Sample-Models/pull/12

@lasalvavida can you please look at this after the 1.1 updates?  Or anyone else in the meantime...

**Comment by pjcozzi** [comment]
Could be the same issue three.js had, https://github.com/mrdoob/three.js/pull/10319.

**Comment by denverpierce** [comment]
Looks exactly the same as the three.js bug (stuff of nightmares).

![ss](https://cloud.githubusercontent.com/assets/5432027/21319968/f5dcf492-c5d4-11e6-8e90-832893d31ea0.gif)

**Comment by pjcozzi** [comment]
@denverpierce thanks for looking into it.  Any chance you have the bandwidth to try out the same type of fix used in three?

**Comment by denverpierce** [comment]
Yeah, if it's a straightforward one liner like three.js I should be able to take a look at it.

**Comment by pjcozzi** [comment]
That would be great, thanks!

**Comment by denverpierce** [comment]
I crunched on this a bit but couldn't make any progress.  Is the [gltf spec](https://github.com/KhronosGroup/glTF/tree/master/specification/1.0) the best resource to look at for this issue?

**Comment by pjcozzi** [comment]
Thanks for investigating, @denverpierce!  I suspect the fix to three.js, https://github.com/mrdoob/three.js/pull/10319, would be the best place to look, perhaps followed by the [reference card](https://github.com/KhronosGroup/glTF#overview), and then the spec.

**Comment by javagl** [comment]
Change `if (defined(` to `if (!defined(` at https://github.com/AnalyticalGraphicsInc/cesium/blob/389cb1d3664536c53755b62a297bd96400abaff8/Source/ThirdParty/gltfDefaults.js#L404

**Comment by pjcozzi** [comment]
@cx20 the fix for this will be in Cesium 1.29, which will be released on Monday.  Can you please update [gltf-test](https://github.com/cx20/gltf-test)?

**Comment by cx20** [comment]
I will update it as new version is released :)

**Comment by cx20** [comment]
I confirmed that WalkingLady glTF model is displayed in Cesium.js 1.29.
https://github.com/cx20/gltf-test

![image](https://cloud.githubusercontent.com/assets/1833979/21591345/8bd4fd92-d146-11e6-82e0-84cba103c400.png)

**Comment by pjcozzi** [comment]
Great, thanks for the quick response, @cx20!

**Comment by denverpierce** [comment]
Thanks to @javagl for the fix!
