### ISSUE TITLE
ScreenSpaceEventHandler and ScreenSpaceCameraController test broken with Chrome 55

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4740]
Chrome 55 added support for PointerEvent, which is awesome; but it looks like it broke a bunch of our tests which were relying on the ability to create `PointerEvent` instances via `document.createEvent`.  I'm pretty sure `new PointerEvent` is the proper syntax, but not positive.

Here's one example of the failing tests (they all have the same root cause): 

http://localhost:8080/Specs/SpecRunner.html?spec=Core%2FScreenSpaceEventHandler%20handles%20mouse%20down%20LEFT_DOWN%20action

@emackey any thoughts here?

**Comment by emackey** [comment]
Looks like [MDN shows createEvent as obsolete](https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent).  I'll take a look.
