### ISSUE TITLE
Mapbox access token invalid

### ISSUE THREAD

**Issue by erikmaarten** [AnalyticalGraphicsInc/cesium#4748]
It was reported on the forum that the default Mapbox imagery (streets or satellite) doesn't load. 

When selecting either of the providers, network requests error out with "{"message":"Not Authorized - Invalid Token"}", so it's probably time to renew the default token included in Cesium.

**Comment by hpinkos** [comment]
Thanks @erikmaarten, this was just fixed in #4741
However, people should be setting their own tokens.  They're only allowed to use ours in development, not in production.
