### ISSUE TITLE
Zooming bug with Cesium and the latest Chromium 55 engine

### ISSUE THREAD

**Issue by keikland** [AnalyticalGraphicsInc/cesium#4767]
After auto-updating my installations of Chrome and Opera to their latest versions, Cesium (latest) has problems both with tiles near the poles and when zooming into a balloon.  (Machine is 64-bit Win10, Dell XPS 8700, i7 Haswell, Sapphire RX480 graphics card) 

For example, check the Cesium Camera Sandcastle example (//cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases).  Zoom in towards AGI.  All of a sudden to position moves in to a very detailed zoom at some other location far, far away.  I can reproduce the effect with several apps.   No error messages are written to the console.

I installed previous versions of both Chrome and Opera, and they work fine, without the problem, as do Edge and Firefox. Reinstalling latest versions of Chrome and Opera (after complete uninstall) again reintroduces the problem, again for those two browsers only.  They of course share the Chromium 55 engine.  The problem could be triggered with the help of the AMD Radeon driver, but that driver is otherwise very stable.  If there is anything Cesium does to provoke the error it would be nice if it could be bypassed.

(In the testing process, I also found that latest Firefox ignore the alpha setting for polylines, rendering them in solid color.  The other browsers are fine.)

Kjell

**Comment by jdkatz** [comment]
Same issue mouse here: Chrome latest version (issue appeared around release Dec. 19), AMD Firepro V4900. Logged related rendering issue at https://bugs.chromium.org/p/chromium/issues/detail?id=678407. IE11 works.

**Comment by lilleyse** [comment]
I'm noticing this as well.

**Comment by emackey** [comment]
@lilleyse is this a dup of #4855?

**Comment by lilleyse** [comment]
Yes
