### ISSUE TITLE
I'm using the 3d Model code sample in sandcastle but it not run correctly

### ISSUE THREAD

**Issue by sabahMotamedi** [AnalyticalGraphicsInc/cesium#4780]
Hello,
Please  help me,

I'm using the 3d Model code sample in sandcastle but it not run correctly. I runs but don't search for 3d models.

It run but don't searching  for 3d models.

In this line there is error(line 40):      var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);

Error description:

Uncaught TypeError: Cesium.HeadingPitchRoll is not a constructor
    at createModel (3D%20Models2.html:40)
    at Object.onselect (3D%20Models2.html:64)
    at HTMLSelectElement.menu.onchange (Sandcastle-header.js:57)

I attached image from error message,

This code is code from 3d model in sandcastle:

<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="utf-8">
  
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
  <title>3d models</title>
  <script type="text/javascript" src="../Sandcastle-header.js"></script>
  <script src="../Build/Cesium/Cesium.js"></script>
  <style>
    @import url(../templates/bucket.css);
    @import url(../Build/Cesium/Widgets/widgets.css);
        html, body, #cesiumContainer {
          width: 100%; height: 100%; margin: 0; padding: 0; overflow: hidden;
      
</style>
  
</head>
<body>
<div id="cesiumContainer" class="fullSize"></div>
<div id="loadingOverlay"><h1>Loading...</h1></div>
<div id="toolbar"></div> 
  <script>
var viewer = new Cesium.Viewer('cesiumContainer', {
    infoBox : false,
    selectionIndicator : false,
    shadows : true
});

function createModel(url, height) {
    viewer.entities.removeAll();

    var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, height);
    var heading = Cesium.Math.toRadians(135);
    var pitch = 0;
    var roll = 0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            uri : url,
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });
    viewer.trackedEntity = entity;
}

var options = [{
    text : 'Aircraft',
    onselect : function() {
        createModel('../../SampleData/models/CesiumAir/Cesium_Air.glb', 5000.0);
    }
}, {
    text : 'Ground vehicle',
    onselect : function() {
        createModel('../../SampleData/models/CesiumGround/Cesium_Ground.glb', 0);
    }
}, {
    text : 'Hot Air Balloon',
    onselect : function() {
        createModel('../../SampleData/models/CesiumBalloon/CesiumBalloon.glb', 1000.0);
    }
}, {
    text : 'Milk truck',
    onselect : function() {
        createModel('../../SampleData/models/CesiumMilkTruck/CesiumMilkTruck-kmc.glb', 0);
    }
}, {
    text : 'Skinned character',
    onselect : function() {
        createModel('../../SampleData/models/CesiumMan/Cesium_Man.glb', 0);
    }
}];

Sandcastle.addToolbarMenu(options);

  </script>
 
</body>
</html>

Image from error message:

![untitled](https://cloud.githubusercontent.com/assets/20692137/21463606/7898ae32-c920-11e6-9dc0-8433789b86f3.png)

**Comment by pjcozzi** [comment]
@sabahMotamedi someone will answer your [same question on the Cesium forum](https://groups.google.com/forum/#!topic/cesium-dev/WSrlBHNLAjM).

In the future, please use the Cesium forum for questions like this and use GitHub issues to report bugs and fixes requests.  A lot more devs are watching the forum than the issues.  Thanks!
