### ISSUE TITLE
Model disappeared when there is czml packet delay 

### ISSUE THREAD

**Issue by gaolizhou** [AnalyticalGraphicsInc/cesium#4788]
Below is copied from https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Structure#availability

> Availability
In addition to the id property, CZML packets have one additional special property: availability.
{
    "id": "PredatorUAV",
    "availability": "2012-04-30T12:00:00Z/14:00:00Z",
    // ...
}
The availability property indicates when data for an object is available. If data for an object is known to be available at the current animation time, but the client does not yet have that data (presumably because it will arrive in a later packet), the client could pause with a message like "Buffering..." while it waits to receive the data. The property can be a single string specifying a single interval, or an array of strings representing intervals.
A later Cesium packet can update this availability if it changes or is found to be incorrect. For example, an SGP4 propagator may report availability for all time, but then later the propagator throws an exception and the availability needs to be adjusted. If this optional property is not present, the object is assumed to be available for all time. Availability is scoped to a particular CZML stream, so two different streams can list different availability for a single object. Within a single stream, the last availability stated for an object is the one in effect and any availabilities in previous packets are ignored. If an object is available at a time, the client expects the object to have at least one property, and it expects all properties that it needs to be defined at that time. If the object doesn't have any properties, or a needed property is defined but not at the animation time, the client could pause animation and wait for more data.

But, It seems the modes will disappear when there is czml packet delay. I didn't see the buffering...

**Comment by hpinkos** [comment]
@gaolizhou from the documentation you posted, it sounds like the "Buffering..." message is a suggestion for how you could handle this case client side.  It is not something that is built into the Cesium `CzmlDataSource`.

In the future, if you have questions like this please ask them on our [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev).  It is viewed by a lot more people so there is a greater chance someone can help answer your question.
