### ISSUE TITLE
Dynamic geometry sandcastle example

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4791]
This is something that comes up on the forum a lot, and I think it would be beneficial to have a sandcastle example to show how to use a `CallbackProperty` to make entity geometry draw synchronously instead of asynchronously.

Here are some forum posts with code examples for ideas:
https://groups.google.com/d/msg/cesium-dev/jjVOcPFx89Q/p-mDuTXnAgAJ
https://groups.google.com/d/msg/cesium-dev/nypZFdPLjhs/rRH_NdUvhVIJ

**Comment by mramato** [comment]
I think #5301 covers this well enough.
