### ISSUE TITLE
Syntax error in master according to Eclipse

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#4796]
Eclipse Luna (configured as per the official Cesium Contributor's Guide) shows a red syntax error in master on [Check.js#L91](https://github.com/AnalyticalGraphicsInc/cesium/blob/34f3f11da51b1f2f122dcd1ef19b1171b5bb6f2b/Source/Core/Check.js#L91) saying:

> Syntax error on token "function", Identifier expected

This error is repeated several more times in `CheckSpec.js`.

**Comment by pjcozzi** [comment]
This passes JSHint, but I think we should still rename it; I have used `func` [elsewhere](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/RenderState.js#L126) to avoid this.

@erikmaarten can you please update?
