### ISSUE TITLE
Throughout rename "binormal" to "bitangent"

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4822]
It's the more correct term, and will match glTF PBR.

See https://github.com/KhronosGroup/glTF/issues/812#issuecomment-271037920

**Comment by javagl** [comment]
Done. 

Renaming "binormal" to "bitangent" may be a bit more effort, though ;-)

**Comment by pjcozzi** [comment]
https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/207 can be done after this.
