### ISSUE TITLE
Unignored .idea files

### ISSUE THREAD

**Issue by shehzan10** [AnalyticalGraphicsInc/cesium#4833]
With a clean webstorm install, I am seeing some `.idea` files in unstaged changes.
Here is a sample log:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .idea/cesium.iml
	modified:   .idea/jsLibraryMappings.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.idea/libraries/
```

Do you want me to change the [.gitignore](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/.gitignore#L25) to ignore the entire `.idea` directory?

**Comment by mramato** [comment]
What version of WebStorm are you running?  If you are on the latest, `2016.3.2`, then there shouldn't  be any files checked out.  I just tried this myself and could not reproduce the problem.

**Comment by shehzan10** [comment]
I had version `2016.1.3`. Updated to the latest version and a clean clone. Those files no longer seem to appear.

**Comment by pjcozzi** [comment]
Thanks, I also needed to update.
