### ISSUE TITLE
3D Tiles Inspector

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4846]
This will allow us to remove a lot of prototype and duplicate code in Sandcastle examples, and will allow users to embed the inspector in their apps for easily debugging and profiling.

The UI design is open-ended; feel free to make it much better than the collection of buttons in the Sandcastle examples.

Phase one is to just replace the debugging functionality already in the Sandcastle examples; we can do more pull requests as new features are needed.  Do not worry about the current style options in the Sandcastle examples for the first pull request.

* [x] Features based on the debug options in the Sandcastle example: http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles.html&label=Showcases
   * [x] **Show stats** and **Show pick stats**.  These could be shown in the inspector UI instead of the console.  Keep the separation of the inspector and the 3D Tiles rendering clean; the inspector would just pull the fields from `Cesium3DTileset`.
   * [x] **Freeze frame**
   * [x] **Colorize**
   * [x] **Show bounding volumes**, **Show contents**, and **Show request volume**
   * [x] **Change SSE** - have a slider and be able to set an explicit value
   * [x] **Enable Dynamic SSE**
      * [x] **Change density and factor** - similiar to SSE above
   * [x] **Trim tiles cache**
   * [x] **Enable picking**
* [x] New features
   * [x] Be able to pragmatically pass a tileset to the inspector
   * [x] Be able to click on a tileset (when the inspector is open) to inspect it
   * [x] **Performance Display** - just like the Cesium Inspector (for convenience)
   * [x] **Show Wireframe**
   * [ ] ~~**Ignore batch table** - should force a tileset reload~~
   * [ ] ~~Show the url of a clicked tile~~
* [x] Remove similar code in the 3D Tiles Sandcastle examples (in the `3d-tiles` branch and branches off of `3d-tiles`) and instead add the 3D Tiles Inspector.

---

For @austinEng when ready.

**Comment by austinEng** [comment]
> Show stats and Show pick stats. These could be shown in the inspector UI instead of the console.

Does this mean to entirely remove console logging or to just show the information in the inspector as well? Logging of the stats is implemented within `Cesium3DTileset` and removing it would involve disabling the debug flags for statistics. We can still pull the statistics from the tileset as you said, but would doing so without debug flags be inconsistent?

**Comment by pjcozzi** [comment]
I _think_ we can just remove `debugShowStatistics` and `debugShowPickStatistics`, expose a `@private` getter for `_statistics`, and then basically move the [showStats](https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/Cesium3DTileset.js#L1543) logic to the inspector.

See how it feels.
