### ISSUE TITLE
3D Tiles Styling - add vector support to the built-in functions

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4865]
Now that vector types are supported in the styling language (https://github.com/AnalyticalGraphicsInc/cesium/pull/4759) the built-in functions should support the `vec2`, `vec3`, and `vec4` types in addition to supporting numbers as they currently do.

Unary functions can accept either a number, `vec2`, `vec3`, or `vec4`. If the type is a vector, the function should be applied to every component of the vector and return the resulting vector. This rule applies to the other functions as well.

* [x] radians
* [x] degrees
* [x] cos
* [x] sin
* [x] tan
* [x] asin
* [x] acos
* [x] atan
* [x] sqrt
* [x] abs
* [x] sign
* [x] floor
* [x] ceil
* [x] round
* [x] exp
* [x] log
* [x] exp2
* [x] log2
* [x] fract

The function signatures for all these look like:
`fract(vecx x)`
`fract(float x)`

For `atan` and `pow`, both arguments must be the same type.

* [x] atan2
* [x] pow

`atan2(float x, float y)`
`atan2(vecx x, vecx y)`

`pow(float x, float y)`
`pow(vecx x, vecx y)`

For `min` and `max`, the second argument may be a number. Otherwise the types should match.

* [x] min
* [x] max

`min(float x, float y)`
`min(vecx x, vecx y)`
`min(vecx x, float y)`

`max(float x, float y)`
`max(vecx x, vecx y)`
`max(vecx x, float y)`

Example: `min(vec4(1.0), vec4(2.0))` and `min(vec4(1.0), 2.0)` are both valid, but `min(vec4(1.0), vec3(1.0))` is not

Similar rules for `mix` and `clamp`:

* [x] mix

`mix(float x, float y, float a)`
`mix(vecx x, vecx y, vecx a)`
`mix(vecx x, vecx y, float a)`

* [x] clamp

`clamp(float x, float minVal, float maxVal)`
`clamp(vecx x, vecx minVal, vecx maxVal)`
`clamp(vecx x, float minVal, float maxVal)`

Below are functions that haven't been added to the styling language yet.

* [x] length

`length(vecx x)`
`length(float x)`

* [x] distance

`distance(vecx x, vecx y)`
`distance(float x, float y)`

* [x] dot

`dot(vecx x, vecx y)`
`dot(float x, float y)`

* [x] normalize

`normalize(vecx x)`
`normalize(float x)` -- always return 1.0

* [x] cross - this is a special case, ONLY `vec3` is supported. Throw a `DeveloperError` otherwise.

`cross(vec3 x, vec3 y)`

As usual, this is a good reference: http://www.shaderific.com/glsl-functions/

I'll open a PR for one of these. And then possibly @Dylan-Brown or others can finish it off.

**Comment by pjcozzi** [comment]
Please link to this from #3241 (and link future short-term 3D Tiles issues) so we can track our progress.

**Comment by lilleyse** [comment]
Unary functions PR here: https://github.com/AnalyticalGraphicsInc/cesium/pull/4867

**Comment by glee2244** [comment]
Hi, I'm working on adding the length and distance functions but couldn't find anything in CesiumMath that support either of those two functions. Are there any other functions in the repo that could possibly help me?

**Comment by lilleyse** [comment]
Look into `Cartesian3.length` and `Cartesian3.distance`.

**Comment by lilleyse** [comment]
@glee2244, @Jane-Of-Art, @Dylan-Brown 

Just a heads up that `length` is being implemented here: https://github.com/AnalyticalGraphicsInc/cesium/pull/5149

**Comment by lilleyse** [comment]
Finished. Thanks @Jane-Of-Art and @glee2244 for the work here!
