### ISSUE TITLE
Calling drillPick() on a 3d-tiles point cloud without a limit hangs browser

### ISSUE THREAD

**Issue by denverpierce** [AnalyticalGraphicsInc/cesium#4895]
scene.pick works fine, but calling scene.drillPick without the optional limit parameter locks the tab.

Load this and click the cloud:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    scene3DOnly : true
});

var scene = viewer.scene;
var url = '../../../Specs/Data/Cesium3DTiles/PointCloud/PointCloudWithPerPointProperties/';

var tileset = scene.primitives.add(new Cesium.Cesium3DTileset({
    url : url
}));

tileset.readyPromise.then(function(tileset) {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0, -2.0, 0));
});

viewer.screenSpaceEventHandler.setInputAction(function (loc) {
	var picks = viewer.scene.drillPick(loc.position);
	if (Cesium.defined(picks)) {
		console.log(picks.length);
	}
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

**Comment by pjcozzi** [comment]
@denverpierce thanks for the report, I added this to #3241.

If you have any time to narrow this down, the likely suspect is [this loop](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Scene.js#L2737).

**Comment by lilleyse** [comment]
The problem here is that `PointCloud3DTileContent` does not have a `show` property. @denverpierce if you haven't already started investigating I'm happy to work on this.

**Comment by denverpierce** [comment]
I'm full up this week, it's all you.
