### ISSUE TITLE
Enable glitchy ground primitives on IE 11

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4899]
I was talking with @bagnell on Friday and learned that we could actually enable ground primitives on machines without `frag_depth` but it would lead to artifacts when inside of the shadow volume.  I  had no idea this was an option and personally feel like it's a much better solution than having ground primitives not work at all.

Can we open a PR with making this behavior the default and ask our users to experiment with it and let us know what they think?  For many cases where you are nowhere near the shadow volume, this solution is ideal.

**Comment by pjcozzi** [comment]
+1 from me.  @bagnell can you please do this?
