### ISSUE TITLE
Add model to Sandcastle ground clamping demo

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4901]
Models also support a height reference.  
We should add an example for using `heightReference: Cesium.HeightReference.CLAMP_TO_GROUND` to this sandcastle demo: http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Ground%20Clamping.html&label=Showcases

**Comment by likangning93** [comment]
Taking this for the bug bash, speak now or forever hold your peace...
