### ISSUE TITLE
Improve Sandcastle load time

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4906]
By using the built Cesium.js for the deployed version.

See https://github.com/AnalyticalGraphicsInc/cesium/pull/4889#discussion_r96953182

**Comment by emackey** [comment]
In the interest of avoiding thrashing, it's worth noting that we went the other direction (from pre-built to separate requires) back in #2164.  We did this so users didn't need to run `combine` before running Sandcastle.  Maybe we could look for the built version for speed, and fall back on the requires for convenience?  That seems like a lot of dependency logic to inject just to get a version number and autocomplete working.

**Comment by emackey** [comment]
+1 for improving load times though!

**Comment by pjcozzi** [comment]
@emackey I'm suggesting that we basically just have this optimization for the released version.  I'm open to other variations, but do not want to require building often.

**Comment by emackey** [comment]
Ah, release Sandcastle should use a built copy of Cesium, yes.
