### ISSUE TITLE
Remove MIDDLE_DOUBLE_CLICK and RIGHT_DOUBLE_CLICK events

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4911]
Deprecation PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/4910

**Comment by smills2929** [comment]
Is the LEFT_DOUBLE_CLICK event being removed?

**Comment by mramato** [comment]
I don't think it makes sense to remove `LEFT_DOUBLE_CLICK`. it's used internally and is pretty standard.  @emackey exactly what were you thinking here?

**Comment by lilleyse** [comment]
I left a note about that here: https://github.com/AnalyticalGraphicsInc/cesium/pull/4910#discussion_r97451075

It'll probably be best just to deprecate right and middle.

**Comment by emackey** [comment]
Yes, deprecate only right and middle.  Keep left, but remember that there should always be a touch-friendly alternative to double-left-click.  For example, for `trackedEntity`, you can double-left-click the entity, or you can touch the entity and then touch the camera button on the InfoBox.
