### ISSUE TITLE
Unicode variation selectors (U-FE00 to U-FE0F) in Label text freeze Cesium

### ISSUE THREAD

**Issue by xtassin** [AnalyticalGraphicsInc/cesium#4918]
Using a unicode character and a variation selector (U-FE00 to U-FE0F) as label's text gets Cesium in an infinite loop (CPU maxed and frozen browser)

I could reproduce this in FireFox and Chrome but not IE or MS Edge (do not appear to support variation selectors)

This character: `☠` (\u2620) will work fine
It's variation: `☠️` (\u2620\ufe0f) will crash Cesium

Firebug pointed me to mesureText.js (line 173) that looks like a good candidate for the buggy loop.

Here is the stack trace:

measureText@https://cesiumjs.org/Cesium/Source/ThirdParty/measureText.js:173:19
writeTextToCanvas@https://cesiumjs.org/Cesium/Source/Core/writeTextToCanvas.js:89:25
createGlyphCanvas@https://cesiumjs.org/Cesium/Source/Scene/LabelCollection.js:99:15
rebindAllGlyphs@https://cesiumjs.org/Cesium/Source/Scene/LabelCollection.js:202:29
LabelCollection.prototype.update@https://cesiumjs.org/Cesium/Source/Scene/LabelCollection.js:778:16
EntityCluster.prototype.update@https://cesiumjs.org/Cesium/Source/DataSources/EntityCluster.js:727:12
PrimitiveCollection.prototype.update@https://cesiumjs.org/Cesium/Source/Scene/PrimitiveCollection.js:366:12
updatePrimitives@https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2196:8
executeCommandsInViewport@https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2106:8
updateAndExecuteCommands@https://cesiumjs.org/Cesium/Source/Scene/Scene.js:1974:16
render@https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2404:8
Scene.prototype.render@https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2442:12
CesiumWidget.prototype.render@https://cesiumjs.org/Cesium/Source/Widgets/CesiumWidget/CesiumWidget.js:687:12
render@https://cesiumjs.org/Cesium/Source/Widgets/CesiumWidget/CesiumWidget.js:72:24

**Comment by hpinkos** [comment]
Related: #378

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/UgdiI_MNbTQ

**Comment by ggetz** [comment]
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/sfE8_8dUfXI

**Comment by glathoud** [comment]
Same issue with the soft hyphen U+00AD ([sandcastle example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=1Vhbbxo5FP4rVl4YJGIIhKS5ahOSqFFpUpV0V9WyqszMAawYe+TxkNCK/7BS1YeV9vK8+4f4O3s8w2UYJly6qdT1Cx77+Pic852b6TNN+hweQJMTIuGB1CDgYY/+GK05OTf6rClpGJegc/mjpmzKdihdw5UkzPPqrAXCyZNPTUlwNJj0XBYYAdQDVzANzoTInrUk8X0UpOGGQ0Bx3xmftsNXAY+YH06EqTFtcMZkhba16l1ARwMEzvZ+le7s7e7s7e0XSOWAHlTLduQLM17C3ouMEuztMPBocDX3pssFazYfzy48EH6Xs9yMbhhPh1bq4ZzSAZgrNMhSncc036nKE20L8zRtlNjSlHf9R/ISRB8MdxepuBA1JZROSGs/aePV+/P6u8sUuQqNQNfJPHFeP6u9yqb/iXumi/Tl1HZgBgJmfCLHatg1enVdr384u7n4cPvurn59c7kmlG+08kFbVFYBOqOcworRE2E6wOj5xhjjvGQHLX0t2tkGiaexFjRiRwOXoY1PSJmWjrK2u+rhnLn3Ha1C6SGd0SEsmFa122iz88EFDwyTLiy1bpo4aWDeYx0YZ6drO3cmu9EOVVIoZsWYXD27aY3Qe+7ws6OFEdJSTHuLwHyL66KwsJDN7IesE8n8Bpi+YrqBNEw7O7QK6E1VWioQO0feJVrNYhpb/jD+nd8epsif8MOkL0ahSlBto3z0jkhkLjsza+UyRJimpBKmpIDJYDsAzdtZpCm3PIzcMoOuqzT/aAuauNW8wxMwvEzt0Nrlzd3l2wwePn8EcRs57bypp0iWnZI18Hbso13gna7JL+fU2BjDSgrDFEaJgJ+EzHAudALtYtzkKC1G30GxzVwubKR30MYLId3GVLJmQM+TPn8ZrNCD3QLZLdG9/Q3S4Q3a873S92n3MRo9S4QuSHewEQA7EwBeWABK+ewU+6yqv9illQOEvkL3qxuofmYEQ89+Hs2rCc33l2meqrbzDr683s7TzirV/6OV2jwfl5+M5aXty1ubWO5UHdorG9IE6cQrk10UmpS1BCSoLsBAfNG4xpNi8VaKAeoCXoB5nLTAyoBJHVVkhpgu4BJmTmkTO+Z4u8B8X2AbafnQ7w3C12gkfPo4o19Hn0dfRn/lD23fK1SzKUf/jH4f/Tn6bfSZOIEJPZQWd0d/4+qX0R/LHgoJ66Nmd0qJFtOvQYbOz2MxpkHpebGEE/dRMgCBNsfN7G5m9uA6mi0mLuwiesIiuPDqQtGGBZISoIHg2RK79v3Tt8+q61MPoCdv96dN9SYyJJv2NSRZ7Nwz5RkX9NhnWgPijaN3bckWe95Vwj3V+GbKd4XZ5j9Ily7fq2TLruHZSEYvhq8XbaEyrAR1sTwsdbNYtAeOb0ptGWwbtS0wxeGG7ITY+2zifXM5dw33y0i8VtBf4qKWOKXB+l/WSyadMjX0VB/ORJwIbFe3Vdg6jh7Hp/GJH3jPV9qQUAsHGzwDPV8wzKLFVujeg6FuEAXDcXFy6NjjfcK9k+ZW6k+f5hbBGhIEuNMOhWjwj9DcOj0uIv3cMfsMw7x/2wct2MCSdHdO6/EipfS4iJ+Lp0ycHxMc/wU)).

**Comment by glathoud** [comment]
#378 is pretty old now... Until it gets solved, would it be thinkable to filter out the most problematic Unicode codepoints before rendering, e.g. U+FE00 to U-FE0F, and U+00AD ?

**Comment by mramato** [comment]
Can confirm that this is fixed in master (and in today's 1.63 release I'm publishing now).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/UgdiI_MNbTQ
https://groups.google.com/forum/#!topic/cesium-dev/sfE8_8dUfXI

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4918 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
