### ISSUE TITLE
SceneModePicker and PerformanceWatchdog test failures in master

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4923]
These tests fail when you run all `Widgets` specs but do not fail when run independently
http://localhost:8080/Specs/SpecRunner.html?spec=Widgets 

![image](https://cloud.githubusercontent.com/assets/3451886/22306165/2b82332e-e30c-11e6-9d54-0f70905efd2f.png)

**Comment by pjcozzi** [comment]
These are fixed / worked around in #4827.  Also, see https://github.com/AnalyticalGraphicsInc/cesium/pull/4827#discussion_r95155845
