### ISSUE TITLE
Problems with label backgrounds

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4927]
#4886 appears to cause problems for labels with backgrounds: 

Run http://localhost:8080/Apps/Sandcastle/index.html?src=Ground%20Clamping.html&label=Showcases

The label text should be opaque and the background translucent, but there's an issue that makes the font appear as if it's behind it's background (not always).  @bagnell thinks this is a draw order issue.

![label](https://cloud.githubusercontent.com/assets/1495196/22350206/e1cccb7e-e3e0-11e6-9e62-0e26e1d9a7bc.gif)

CC @emackey

**Comment by pjcozzi** [comment]
Perhaps the background is not getting the new `blendOption` set correctly?

Otherwise, are we sure the background billboard collection is always added before the label billboard collection?

Otherwise, is `>=` depth test not set?

**Comment by emackey** [comment]
Does this only happen when clamped to ground?  `>=` depth is set, and the `=` part is being relied upon, but I think the clamping might make the Z value a bit noisy.

**Comment by emackey** [comment]
Possibly related to #4736, clamped billboards can shake.

**Comment by bagnell** [comment]
The problem seems to be sampling the texture. The default used by the texture atlas is linear. For smaller sized fonts, all of the sampled texels have an alpha < 1. You can test this by changing the label collection to use `BlendOption.OPAQUE` and no text will be drawn.

**Comment by pjcozzi** [comment]
If we need a workaround for this, we can also force `BlendOption.TRANSLUCENT` when a background is used.  In practice, it will likely often be OK-ish more so then when there is no background.
