### ISSUE TITLE
Test Failure: Core/writeTextToCanvas

### ISSUE THREAD

**Issue by shehzan10** [AnalyticalGraphicsInc/cesium#4928]
Test commands:
```
npm run test -- --exclude WebGL --suppressPassed # I used Chrome
npm run test -- --browsers Electron --exclude WebGL --suppressPassed
```

Failure log:
```
TOTAL: 1 FAILED, 5298 SUCCESS

1) allows the text to be either stroked or filled
     Core/writeTextToCanvas
     Expected 2 to equal 1.
    at Specs/Core/writeTextToCanvasSpec.js:86:46
    at Object.<anonymous> (Specs/customizeJasmine.js:75:30)
     Expected 4 to equal 3.
    at Specs/Core/writeTextToCanvasSpec.js:96:46
    at Object.<anonymous> (Specs/customizeJasmine.js:75:30)
```

This command is similar to the one that is run on Travis. However the failure doesn't show up there. I have seen it on OS X and Windows.

This failure only shows up with the `--exclude WebGL` flag.

**Comment by pjcozzi** [comment]
Worked around in https://github.com/AnalyticalGraphicsInc/cesium/pull/4827, but I don't know if there is a legit root cause.

**Comment by pjcozzi** [comment]
Passes now via #4827, am open to a more precise workaround or fix if appropriate.
