### ISSUE TITLE
Camera.flyHome in 2D uses Rectangle.MAX_VALUE instead of Camera.DEFAULT_VIEW_RECTANGLE

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4933]
Brought up on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/elr1j2jHlbg

Should we change the home button to use the `Camera.DEFAULT_VIEW_RECTANGLE` in 2D and Columbus View?

**Comment by pjcozzi** [comment]
OK with me.

**Comment by PratyushTalreja** [comment]
I have made required changes to the file.

**Comment by pjcozzi** [comment]
@PratyushTalreja did you open a pull request for this?  Perhaps I missed it?

**Comment by omh1280** [comment]
@rms13  Try to see what is failing in the tests. I'd recommend looking at #4971, making the same changes to master that @PratyushTalreja did, and fixing the tests.
