### ISSUE TITLE
Rendering problem with transparent video

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4935]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/BHXRoSzPHnk

The transparent parts of the video don't clear when the video loops

![transparent-video](https://cloud.githubusercontent.com/assets/3451886/22467941/8cbc94e0-e794-11e6-8e59-ab40cb9e61f6.gif)

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {showRenderLoopErrors : false});

var videoElement = document.createElement('video');
videoElement.style.display = 'none';
videoElement.setAttribute('autoplay', '');
videoElement.setAttribute('loop', '');
videoElement.setAttribute('crossorigin', '');
videoElement.setAttribute('controls', '');
var src = document.createElement('source');
src.setAttribute('src', 'https://examples.phaser.io/assets/video/alpha-webm.webm');
src.setAttribute('type', 'video/webm');
videoElement.appendChild(src);
document.body.appendChild(videoElement);

var sphere = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-79, 39, 1000),
    ellipsoid : {
        radii : new Cesium.Cartesian3(1000, 1000, 1000),
        material : new Cesium.ImageMaterialProperty({
            image: videoElement,
            transparent: true
        })
    }
});

viewer.trackedEntity = sphere;
```

**Comment by mramato** [comment]
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Material.js#L698 is where we copy the frame from the video into the texture.  I imagine `copyFrom` drawn on top of the old texture without clearing it, leaving any underlying parts intact.

This isn't my area of expertise, but I assume we either have an option or it would be easy to add an option to have the transparent pixels overwrite any data that may exist.

@bagnell @lilleyse any ideas?

**Comment by spereirag** [comment]
Changing [line 454](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Texture.js#L454) from:

```gl.texSubImage2D(target, 0, xOffset, yOffset, this._pixelFormat, this._pixelDatatype, source);```

to:
```gl.texImage2D(target, 0, this._pixelFormat, this._pixelFormat, this._pixelDatatype, source);```

seems to fix the problem. We don't know how this affects the rest of the code, though.

**Comment by pjcozzi** [comment]
@spereirag have you tried this on multiple browsers?  This is could be a WebGL implementation bug.  In both `texImage2D ` and `texSubImage2D `, the last argument is `TexImageSource`, which is:
```
typedef (ImageBitmap or
         ImageData or
         HTMLImageElement or
         HTMLCanvasElement or
         HTMLVideoElement) TexImageSource;
```
I'm not aware of any differences with alpha when calling one function vs the other.

The other thing it could be is if the internal format / pixel format / pixel datatype changed from when `texImage2D` was first called in the `Texture` construction function at the top of that file.

**Comment by dwastberg** [comment]
I just stumbled across this particular bug in my own code.  As of 1.49 I can confirm that transparent video textures work fine in Firefox, but this bug is still there in Chrome (Windows in both cases).  Any further ideas on if it is fixable on the Cesium side of things or is it a Chrome bug?  Otherwise I can take another look at texImage2D vs  texSubImage2D as mentioned above.

**Comment by hpinkos** [comment]
![transparent-video](https://user-images.githubusercontent.com/3451886/65267251-a196f600-dae2-11e9-9257-378ac6599221.gif)

Appears to be fixed

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/BHXRoSzPHnk

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4935 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
