### ISSUE TITLE
Add depthTestAgainstTerrain to ground clamping sandcastle demo

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4945]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/68jiQll7WJc

http://cesiumjs.org/Cesium/Apps/Sandcastle/gallery/Ground%20Clamping.html

needs to have `viewer.scene.globe.depthTestAgainstTerrain = true;` so the billboard/label don't show up through the mountain.

**Comment by PrasannaNatarajan** [comment]
#4963
