### ISSUE TITLE
Positive time offset doesn't work at stop time

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#4949]
In [EntityView.js#L57](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.30/Source/DataSources/EntityView.js#L57), a small positive time offset of 0.001 seconds is used to get a tiny position delta, used to approximate a velocity near that moment in time.  The time offset does not work for the last 0.001 seconds of playback in the scene, if the objects don't have position data available past the stop time.  This can cause the camera to flip over, for example if it is tracking a GEO satellite and the user moves the timeline to the stop time.

One fix could be to test if the 0.001 offset failed, and attempt a -0.001 offset instead, negating the resulting vector.  I don't think this would be much of a performance hit because it would be a code path only used when the current position is available but a small positive delta position failed.  Can anyone think of other downsides to this possible fix?

**Comment by mramato** [comment]
> Can anyone think of other downsides to this possible fix?

I thought we were actually already doing this (I'm pretty sure we do it elsewhere when we use finite differencing).  So good with me.
