### ISSUE TITLE
Polyline entities with arrow material property don't update color correctly

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4951]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/B7ePBv4XXac

The polylines start out as blue, and they should change to red when you click the 'Change color to red' button.  However, one polyline changes to red and the other changes to purple.  This doesn't happen when using a `ColorMaterialProperty`, so there's something weird going on with the `PolylineArrowMaterialProperty`

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var entities = viewer.entities;	

var line1 = entities.add({
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights([0, 0, 36000000, 38.8, 0.8, 40022479]),
        width : 10,
        followSurface : false,
        material : new Cesium.PolylineArrowMaterialProperty(Cesium.Color.BLUE)
    }
});

var line2 = entities.add({
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights([0, 0, 36000000, 36.5, -1.16, 42047591]),
        width : 10,
        followSurface : false,
        material : new Cesium.PolylineArrowMaterialProperty(Cesium.Color.BLUE)
    }
});	

viewer.zoomTo(line2, new Cesium.HeadingPitchRange(0, Cesium.Math.toRadians(-120)));

Sandcastle.addToolbarButton('Change color to red', function() {
    line1.polyline.material = new Cesium.PolylineArrowMaterialProperty(Cesium.Color.RED);
    line2.polyline.material = new Cesium.PolylineArrowMaterialProperty(Cesium.Color.RED);
});
```

**Comment by denverpierce** [comment]
Using material.property.color.setValue() works as intended.
```

Sandcastle.addToolbarButton('Change color to red', function() {
    line1.polyline.material.color.setValue(Cesium.Color.RED);
    line2.polyline.material.color.setValue(Cesium.Color.RED);
});
```

**Comment by hpinkos** [comment]
Thanks @denverpierce!  That's a good workaround until we fix this

**Comment by shortwavedave** [comment]
I ran into this problem today

**Comment by hpinkos** [comment]
Fixed

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/B7ePBv4XXac

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4951 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
