### ISSUE TITLE
Failed to obtain terrain tile error when using ArcGisImageServerTerrainProvider

### ISSUE THREAD

**Issue by psanyal** [AnalyticalGraphicsInc/cesium#4954]
Hello,

The following sample throws an error as mentioned below:

https://github.com/AnalyticalGraphicsInc/cesium/blob/52066e974c34cefab627c8769dc340a429f0aeda/Source/Core/ArcGisImageServerTerrainProvider.js

An error occurred in "ArcGisImageServerTerrainProvider": Failed to obtain terrain tile X: 1 Y: 0 Level: 0.

Sample services:
https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer
https://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer

Thanks

**Comment by hpinkos** [comment]
Hello @psanyal,
Please see the response to this forum post: https://groups.google.com/d/msg/cesium-dev/zhJgvO4U3Vk/A3yvKnQRMA8J
