### ISSUE TITLE
Deprecate the ArgGisImageServerTerrainProvider?

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4955]
We occasionally get questions about how to use the `ArgGisImageServerTerrainProvider`, and I always refer them to this forum post from @kring: https://groups.google.com/forum/#!msg/cesium-dev/zhJgvO4U3Vk/A3yvKnQRMA8J 

>We probably should have removed ArcGisImageServerTerrainProvider prior to the 1.0 release, because it is unfortunately nearly impossible to actually use.  The problem is that ArcGIS image servers can return height data in a number of ways, but none of them really work for our purposes.  If the heightmap is returned as a floating point TIFF, web browsers (and therefore Cesium) are unable to decode it.  If the heightmap is returned as a PNG or JPG, the heights are discretized to a value from 0-255, creating a lousy terrain representation.
>
>The workaround that ArcGisImageServerTerrainProvider expects (and this is not well documented) is the use of a special proxy.  The proxy requests heightmap images from ArcGIS as TIFF files, and then re-encodes them as PNG files to serve to the browser and Cesium.  Rather than a simple grayscale PNG like the one ArcGIS produces itself, the transcoding proxy uses the red, green, and blue channels to effectively represent a 24-bit integer.  This gives us much more height precision than we get from the standard ArcGIS PNGs.

Should we deprecate this terrain provider since it's really difficult to actually use in Cesium?

**Comment by pjcozzi** [comment]
+1.

If someone is using this, please let us know.

**Comment by pjcozzi** [comment]
CC #4954

**Comment by kring** [comment]
👍

**Comment by hanokhaloni** [comment]
any plans to interacting with ArcGIS to get terrain data?

**Comment by pjcozzi** [comment]
@hanokhaloni no, but it would be great if Esri wants to contribute that.

**Comment by mortac8** [comment]
I just saw this.  We were using the ArcGisImageServerTerrainProvider to stream local terrain when offline.  So there is no way forward since this class has been removed?

**Comment by hpinkos** [comment]
@mortac8 we decided to end official support for this because it only worked for a very particular server configuration.  However, if you include the class in your own project I believe it should still work.  You can find the file here: https://github.com/AnalyticalGraphicsInc/cesium/blob/ed034dbe51a9bf1560fb5f40418c47c1d2fc479d/Source/Core/ArcGisImageServerTerrainProvider.js

You can build a custom version of Cesium by following the instructions in our [Build Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide)

Or if you want to use the official Cesium release, you could modify the file and include it in your project separately.  You can remove the AMD define function and add `Cesium.` before all the Cesium function and class names 
(ie `new GeographicTilingScheme(...)` -> `new Cesium.GeographicTilingScheme(...)`, `CesumMath.toDegrees(...)` -> `Cesium.Math.toDegrees(...)`, etc)
