### ISSUE TITLE
Clamping Model to ground causes issues with Ellipsoids

### ISSUE THREAD

**Issue by Zizekftw** [AnalyticalGraphicsInc/cesium#4965]
Project Background: Application we are developing is consuming real-time data and passing cartographic data into Cesium. We're using SampledPositionProperty to make use of interpolation and are setting the timestamp to now() + 5 seconds (to ensure we always have enough data for accurate interpolation paths. To make the code more straight forward, we are passing in the cartographic data into Cesium (including altitude). Due to some slight issues with our external program we were using to generate paths, the altitudes were being miscalculated. We worked around this by using HeightReference.CLAMP_TO_GROUND for our entities with 3D models associated to them.

Problem: When HeightReference.CLAMP_TO_GROUND is being used for entities that have an altitude assigned to them, any ellipsoid being drawn around the object is it the Cartesian3 height reference instead of the height the entity is being rendered at. Sounds like an edge case, but I would assume the same height value used for drawing would be used across all attributes of an entity. This also causes the trackedEntity marker to be placed in-between the model and the displayed ellipsoid.

```
    var viewer = new Cesium.Viewer('cesiumContainer', {
        infoBox : true,
        selectionIndicator : true,
        shadows : true
    });

    function createModel(url, height) {
        viewer.entities.removeAll();

    var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, height);
    var heading = Cesium.Math.toRadians(135);
    var pitch = 0;
    var roll = 0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            uri : url,
            minimumPixelSize : 128,
            heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
            maximumScale : 20000
        },
        ellipsoid : {
            radii : new Cesium.Cartesian3(20, 20, 20),
            material : Cesium.Color.BLACK,
            outline : true,
            outlineColor : Cesium.Color.BLACK
        },

    });
    viewer.trackedEntity = entity;
}

var options = [{
    text : 'Ground vehicle',
    onselect : function() {
        createModel('../../SampleData/models/CesiumGround/Cesium_Ground.glb', 100);
    }
}];

Sandcastle.addToolbarMenu(options);
```
![example1](https://cloud.githubusercontent.com/assets/3292560/22748328/b0e12e26-edf7-11e6-8aff-53e9f7bde1ac.PNG)

**Comment by hpinkos** [comment]
Hello @Zizekftw,

Some primitive types like the Ellipsoid do not have support for ground clamping.  If you need this behavior, I would recommend using a glTF model of an ellipsoid instead.

In the future, please post things like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
Thanks!
