### ISSUE TITLE
Remove ArcGisImageServerTerrainProvider

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#4985]
Deprecation PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/4981
Details: https://github.com/AnalyticalGraphicsInc/cesium/issues/4955

There are also a couple `@see ArcGisImageServerTerrainProvider` in the doc that should be removed as well.

**Comment by hanokhaloni** [comment]
There is also a comment in doc you need to remove.
Also - Can you provide more information about this change?

**Comment by pjcozzi** [comment]
@hanokhaloni see http://gis.stackexchange.com/questions/228806/cesiumjs-1-32-and-arcgis-10-2-arcgisimageserverterrainprovider-is-being-deprec
