### ISSUE TITLE
Instanced3DModel3DTileContent does not load batch IDs

### ISSUE THREAD

**Issue by pmconne** [AnalyticalGraphicsInc/cesium#4987]
It needs to look for BATCH_ID in featureTable.json, not on the featureTable itself.
Apologies for poor formatting - I'm new here.

`-            if (defined(featureTable.BATCH_ID)) {`
`-                var componentType = defaultValue(featureTable.BATCH_ID.componentType, ComponentDatatype.UNSIGNED_SHORT);`
`+            if (defined(featureTable.json.BATCH_ID)) {`
`+                var componentType = defaultValue(featureTable.json.BATCH_ID.componentType, ComponentDatatype.UNSIGNED_SHORT);`
`                batchId = featureTable.getProperty('BATCH_ID', i, componentType);`

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/5001
