### ISSUE TITLE
Add number of points/features stats to 3D Tiles Inspector

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5003]
@austinEng can you please do this after #4978 and the related blog post?

For point clouds (pnts), we'd like the inspector to report the total number of points downloaded and the number currently rendered.

For 3D models (b3dm, i3dm), we'd like to report the same for number of features, e.g., number of buildings.

Please test with composite tiles as well.

Later, we'll add support for vctr; in the meantime, please display a warning if a tileset has a vector tile.

CC @austinEng

**Comment by pjcozzi** [comment]
downloaded === in memory, not those that were unloaded from the cache.

CC #3241

**Comment by austinEng** [comment]
Do we want to differentiate between the types of features? i.e. If there are different types of content (models and points). Should the inspector report the feature counts separately?

**Comment by pjcozzi** [comment]
Yes, features (from b3dm and i3dm) should be a separate count from points (pnts)
