### ISSUE TITLE
Make max/min speed selectable through jog wheel configurable

### ISSUE THREAD

**Issue by krheinwald** [AnalyticalGraphicsInc/cesium#5009]
Please add member/method to Cesium.Animation to make the upper and lower bounds of the jog wheel configurable.

604800x is a bit too much when dealing with a timeframe of 10mins ;)

**Comment by mramato** [comment]
You can already do this via the [setShuttleRingTicks](https://cesiumjs.org/Cesium/Build/Documentation/AnimationViewModel.html#setShuttleRingTicks) method.

Here's a Sandcastle example of using it: http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=6cbfde5cbd3f9acc83486a7ab2161764
