### ISSUE TITLE
3D Tiles Inspector: report geometric error for each tile

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5016]
@austinEng can you look at this before we start the skipping LODs optimization?

Use `LabelCollection` to display the geometric error for each tile.  Perhaps draw at the approximate corner of the tile's bounding box/region/sphere.

This will be useful for us to evaluate tilesets, e.g., sometimes the geometric error is just wrong or increases too incrementally from parent to child tile.

CC #3241

**Comment by hpinkos** [comment]
Fixed in #5017
