### ISSUE TITLE
GroundPrimitive support for other materials

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5025]
I swear we had an issue open for this already but I couldn't find it.

From the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/x3sYLgIr8Mc

**Comment by jimmyangel** [comment]
Oh, please, please @hpinkos add support for this soon! I noticed this problem with a kml data source that has a GroundOverlay element and the image would just not clamp to the ground. I thought I was doing something wrong but then I ran across [this](https://groups.google.com/forum/#!topic/cesium-dev/x3sYLgIr8Mc) thread  in the forum.

Any estimates on when do you guys plan to support images clamped to ground?

**Comment by hpinkos** [comment]
Hi @jimmyangel.  Based on the amount of effort that needs to be done to implement this, I don't think it's high enough priority for us to justify the time right now.  Our current focus is on finishing 3D tiles.  However, if a number of other users are asking for this we will look into it sooner.

**Comment by jimmyangel** [comment]
@hpinkos oh, bummer. In the mean time, can you suggest any kind of workaround for this issue?

I would say this is pretty critical for people coming from Google Earth to Cesium. Probably a show stopper for them.

**Comment by pjcozzi** [comment]
I labeled this `priority` as we do agree it is important and it may get done as part of the vector tile work for 3D Tiles, but it would be hard to break stride at the momentum to focus on just this.

**Comment by slandersson** [comment]
I would love to see groundprimitive walls and polylines!

**Comment by pjcozzi** [comment]
There's a start to this in the [ground-primitive-tex-coords](https://github.com/AnalyticalGraphicsInc/cesium/compare/ground-primitive-tex-coords) branch.

**Comment by ggetz** [comment]
Requested on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Axk7LMMOD8Q

**Comment by ggetz** [comment]
Requested again on the forum: https://groups.google.com/forum/#!topic/cesium-dev/TyFcn8m1Hb0

**Comment by ggetz** [comment]
Request on the forum: https://groups.google.com/forum/#!topic/cesium-dev/BsNCUQzpxCE

**Comment by jburr-nc** [comment]
We would **_love_** to see this one get fixed -- specifically ground overlays in the KML datasource.

**Comment by ggetz** [comment]
@jburr-nc We have some initial work by @likangning93 being done in this branch: https://github.com/likangning93/cesium/tree/worldFromTerrainDepth

We'll ping this issue when we have some more progress.

**Comment by likangning93** [comment]
Coming soon to a Cesium near you:

![comingsoon](https://user-images.githubusercontent.com/5395255/37490860-5052ad12-2872-11e8-88df-2871ec04ed29.JPG)
