### ISSUE TITLE
3D Tiles Inspector: report per-tile number of commnads/features/points/etc

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5029]
@austinEng after skipping LODs or when you need a break can you add label visualization that displays per tile:
* Number of commands (including derived commands for translucent styling if possible)
* Number of features (hide if zero)
* Number of points (hide if zero)
* Number of triangles (hide if zero)

Probably use one `LabelCollection` for all debugging labels and create new lines in the strings, but do whatever you think.

Let's start with these, phase two could include:
* Size of tile in MB
* Number of external references
* Size of textures
* Number of instances
* etc

This is a lot of data so we would probably add pickable point primitives for each tile (could even color code them based on heuristics on if the tile is "optimized" or not) that bring up the tile's details.

Similar to #5017

**Comment by hpinkos** [comment]
Fixed in #5188
