### ISSUE TITLE
3D Tiles Inspector: add commas to numbers

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5030]
To make them a bit easier to read, for example:

![image](https://cloud.githubusercontent.com/assets/782098/23260214/bb64715c-f99e-11e6-8153-746d82692753.png)

@austinEng 

CC #3241

**Comment by mramato** [comment]
Don't just add commas manually, call [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString).  Commas and decimal points are reversed in many languages and this will use the correct one depending on the users system.
