### ISSUE TITLE
package.json 'main'

### ISSUE THREAD

**Issue by EvaldasVasiliauskas** [AnalyticalGraphicsInc/cesium#5048]
Im developint Angular2 + Webpack2 solution with Cesium. Everything works great, but only if I add
`"main": "Build/Cesium/Cesium.js",`
to Cesium npm package.json. so that angular knows cesium package main script to run.

Could you please add this line to package.json by default?

**Comment by hpinkos** [comment]
Thanks for the suggestion @EvaldasVasiliauskas!

@mramato what do you think of this?

**Comment by EvaldasVasiliauskas** [comment]
Any news on this?

**Comment by mramato** [comment]
See #5418 for additional discussion on this, but here's my take

> I don't think we can take this change as-is. Since Cesium is also available for use from within Node, having it reference Build/Cesium/Cesium.js (which is not a node module) instead of index.js will break all Node usage. If you set main to index.js does it that work for you? (I doubt it unless Angular is doing some magic under the hood).
> 
> While I'm not very familiar with Angular2 and Webpack (particular when being used together), I have to believe there is a different approach that could work better here. For example, why not use the individual Cesium modules instead of simply referencing the legacy combined file? It would produce smaller final output as well. I'm pretty sure that's what our other webpack users are doing.
> 
> We hope to have official reference Hello World examples for Cesium and all of the popular frameworks in the future that will provide guidance on decisions like this, but we just haven't had the bandwidth to spare lately. We also plan on moving Cesium to ES6 modules, which should further improve integration.
> 
> We're certainly open to solutions that make Cesium more out-of-the-box friendly with other systems, so if you have other potential solutions, please let us know. I just don't think we can take this one because of Node compatibility.

**Comment by fredj** [comment]
`"main"` and `"module"` are now set in `package.json` (see 16695223ce097120476991d4e79db64ba4c01152).

Does it fixes this issue?

**Comment by mramato** [comment]
Yes, thanks for the heads up @fredj.
