### ISSUE TITLE
Cesium Inspector - Picking tile bug

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5055]
When picking a tile and then clicking select relative NW, NE, SW, or SE I get an error

`Uncaught TypeError: Cannot read property 'minimumHeight' of undefined (on line 896 of http://localhost:8081/Source/Widgets/CesiumInspector/CesiumInspectorViewModel.js)`

**Comment by hpinkos** [comment]
See discussion in #2448

@pjcozzi said fixing this is 'is insufficient priority for the amount of work'

We should probably remove those buttons though if it doesn't work

**Comment by pjcozzi** [comment]
@kring what do you want to do here?

**Comment by kring** [comment]
I just opened a PR to fix it.
