### ISSUE TITLE
See the geometry under a surface

### ISSUE THREAD

**Issue by kartblanch** [AnalyticalGraphicsInc/cesium#5073]
Hello!
I would like to learn how I can display the primitive (3D model) under terrain.
All my results are ambiguous ... hard to understand whether the model above or below ground. As an example, you can see in the screenshot:
https://hostingkartinok.com/show-image.php?id=86f03fdf4b0f371244c8a95f49de6cea
Case 1: A simple model is on negative height.
Case 2: Use `scene.globe.depthTestAgainstTerrain = false`
Case 3: Use `scene.globe._surface.tileProvider._debug.wireframe = true`
Case 4: Added GridImageryProvider.
```
var gp = new Cesium.GridImageryProvider ({
         cells: 4
         glowWidth: 6
         backgroundColor: Cesium.Color.AZURE,
         color: Cesium.Color.BLACK
     });
scene.imageryLayers.addImageryProvider (gp);
```
I would like to know your ideas as you might correctly display model under the ground.

Regards, Anton.

**Comment by hpinkos** [comment]
Hello @kartblanch,

Cesium does not currently have great support for underground primitives.  However, it is one of the most frequently requested features and we would like to look into it sometime after we finish implementing the 3D Tiles specification.  
For now, turning off `depthTestAgainstTerrain` is your best bet until we have official support.

In the future, please post things like this to our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
Thanks!
