### ISSUE TITLE
GroundPrimitive doesn't render in 2D

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5075]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/DgkAt_g283E

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Ground%20Clamping.html&label=All

If you switch to 2D, the polygon, corridor and rectangle ground primitives don't render

**Comment by pjcozzi** [comment]
@hpinkos do you know if this broke recently?  If so, please label this `next release`.

**Comment by hpinkos** [comment]
@pjcozzi Works in 1.29, broken in 1.30.  I added the `next release` label
