### ISSUE TITLE
Two-pass labels intersect the depth buffer differently

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5083]
Noticed in #5066:

Here's an example of labels sticking into mountains.  I know the text looks crowded and bad, but there are not supposed to be any holes in the glyphs.  The holes appear to be the opaque pass finding different depths to intersect than the translucent pass.

Cesium 1.28 needs to be manually set to "Natural Earth II" base map, but then it works, and it looks fine:

* [Cesium 1.28 large label demo](http://cesiumjs.org/releases/1.28/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=b3026fe9bc53ad4c3717360d436158ea)

Cesium 1.30 exhibits the label depth strangeness:

* [Cesium 1.30 large label demo](http://cesiumjs.org/releases/1.30/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=b3026fe9bc53ad4c3717360d436158ea)

![bigbadlabels](https://cloud.githubusercontent.com/assets/1235080/23529354/49b18464-ff6b-11e6-8679-26c2c661b880.gif)

**Comment by emackey** [comment]
I did `git bisect` this, and indeed it was introduced with #4886.  This is not a surprise, since that is the change that separated these labels into two passes, and clearly the two passes have different ideas about where that mountain is.

**Comment by mramato** [comment]
I labeled this a priority and next release.  It's a pretty bad regression for anyone clamping labels to terrain.

**Comment by emackey** [comment]
@mramato Here's a workaround to get the old behavior, for now:

```
                showBackground : true,
                backgroundColor : Cesium.Color.TRANSPARENT
```

**Comment by bagnell** [comment]
>The holes appear to be the opaque pass finding different depths to intersect than the translucent pass.

This is exactly what is happening. During the opaque pass, we overlap the frustums by a small percentage. During the translucent pass, there is no overlap leading to slightly different depths to the opaque pass.

Removing the overlap from the opaque pass fixes the problem, but it should cause tearing of opaque geometry on frustum boundaries. I need to test more.
