### ISSUE TITLE
pinBuilder puts low-alpha values inside the pin

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5097]
Noticed in #5066.

Our pinBuilder helper produces pins that can have low-alpha "fringes" on the interior of the pin.  For example, here's the Maki shopping cart on a pin, shown alongside a greyscale version of its alpha map:

![testmakiicon](https://cloud.githubusercontent.com/assets/1235080/23860978/fac92466-07de-11e7-9c25-c256d87f6cf9.png)  ![testmakiicon_alpha](https://cloud.githubusercontent.com/assets/1235080/23860991/00da934e-07df-11e7-9395-baceac4db9d5.png)

Here's a question mark on a pin, alongside its alpha map:

![testquestionicon](https://cloud.githubusercontent.com/assets/1235080/23861009/10c75a30-07df-11e7-81cc-2c4675e18c7a.png)  ![testquestionicon_alpha](https://cloud.githubusercontent.com/assets/1235080/23861015/17105234-07df-11e7-87cf-a3343d643d89.png)

In the alpha map images above, the white pin body should NOT have any black pixels floating around in it.  Both of them do, although the shopping cart one is much more subtle, the question mark one is more obvious.

I've tested as far back as Cesium 1.20 and the pinBuilder appears to have this problem even back then.  It wasn't much of an issue until now, with the billboard blending fixes coming in, the low alpha values are actually leaking other billboards through them.

The inset image written onto the pin should of course use the alpha values for proper blending, but it should use those values to blend against the pin's background color, not against a transparent background.  The resulting pixels should always have exactly the pin background's opacity.

**Comment by emackey** [comment]
Reproduce steps:

1. Load Sandcastle Hello World and add these lines:

```
var pinBuilder = new Cesium.PinBuilder();
window.foo = pinBuilder.fromText('?', Cesium.Color.STEELBLUE, 48).toDataURL();
```

2. Click "open in new window" (on Sandcastle toolbar) and wait for the globe to appear.
3. Hit F12 and on the JS console type:  `copy(foo)`.  This will return `undefined`.
4. Open a new tab and hit "Paste & Go".
5. Right-click on the image and hit "Save image as...".
6. Examine the image in a paint program (I've been using Gimp) that can inspect the alpha channel.

**Comment by mramato** [comment]
@emackey this is probably a one line change in PinBuilder's `drawIcon` function.  I assume we are putting the canvas in an incorrect compositing mode or something.  Might be a super easy fix if you want to take a look.
