### ISSUE TITLE
JQMIGRATE: jQuery.fn.bind() is deprecated

### ISSUE THREAD

**Issue by krheinwald** [AnalyticalGraphicsInc/cesium#5113]
When using the logging debug version of jQuery.migrate, the above warning is produced when a Viewer is instantiated.

**Comment by hpinkos** [comment]
@krheinwald we don't include jquery in Cesium.  In the future, please post things like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
Thanks!
