### ISSUE TITLE
Add link to gltf-vscode to VSCode Guide

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5137]
* [gltf-vscode](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode)
* [VSCode Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/VSCodeGuide)

**Comment by ryki2658** [comment]
I think I can handle this one.
