### ISSUE TITLE
Auto connect 3D Tiles Inspector to tileset

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5139]
@austinEng @lilleyse what do you think?

Often we have one tileset loaded and then we bring up the inspector, but then have to pick on the tileset before we can inspect it.

Can we add a flag like `inspectFirstAvailableTileset` (better name?) that when `true` loops through `scene.primitives` and sets the inspector to the first `Cesium3DTileset` instance it finds?

Probably default to `false`.

CC #3241

**Comment by pjcozzi** [comment]
Does anyone have bandwidth to look at this?  It has bitten me a few times.

**Comment by hpinkos** [comment]
@pjcozzi how about if no tileset is selected, you select the first tileset you hover over?

Is there a reason to have a flag for this?  I feel like it would always be helpful to auto-select the first tileset you come into contact with.

**Comment by pjcozzi** [comment]
> @pjcozzi how about if no tileset is selected, you select the first tileset you hover over?

Sounds good.

> Is there a reason to have a flag for this? I feel like it would always be helpful to auto-select the first tileset you come into contact with.

Maybe not.  I suppose if the inspector's tileset is `undefined`, then take the tileset on hover.
