### ISSUE TITLE
documentation is not built

### ISSUE THREAD

**Issue by freder** [AnalyticalGraphicsInc/cesium#5141]
I just noticed that the documentation fails to build for me. (`3d-tiles` branch, macOS)

```
node_modules/.bin/jsdoc  --configure Tools/jsdoc/conf.json
There are no input files to process.
[...]
```

it only works when I remove [`excludePattern`](https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Tools/jsdoc/conf.json#L9) from `conf.json`.

**Comment by mramato** [comment]
To build the documentation, you need to run `npm run generateDocumentation` as detailed in our doc guide: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/DocumentationGuide#building-the-doc

**Comment by freder** [comment]
I had tried `npm run release` before, but it failed — so does `npm run generateDocumentation`.
