### ISSUE TITLE
PolylineGeometryUpdater crashes when there is no globe

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#5146]
Forum post:

https://groups.google.com/d/msg/cesium-dev/UboMKwwn8Xk/noMUrTS7CQAJ

This line crashes if there is no globe:
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/PolylineGeometryUpdater.js#L519

This assignment should be delayed until `update` and only done if `followSurface` is true.  Otherwise `generateCartesianArcOptions` is unused.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/5413
