### ISSUE TITLE
Options to turn off normal shading for point clouds

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5152]
@Dylan-Brown, @glee2244 this will be a good thing to work on after #4759 

For point clouds with normals (like `Specs\Data\Cesium3DTiles\PointCloud\PointCloudNormals`), shading is automatically applied in the shader here: https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/PointCloud3DTileContent.js#L1005-L1010

Instead of shading always being applied, it should be controlled with a boolean, since some may want to apply their own shading with the styling language, or just not at all.

Shading on:
<img width="167" alt="shading" src="https://cloud.githubusercontent.com/assets/915398/24364938/497c451c-12e2-11e7-8ec0-d1db892cb534.PNG">

Shading off:
<img width="177" alt="unshaded" src="https://cloud.githubusercontent.com/assets/915398/24364937/4959c7f8-12e2-11e7-9a54-c2171c8afbda.png">

Look at how `backFaceCulling` is handled, a `normalShading` flag will act very similarly.

This was requested on the forum a little while back: https://groups.google.com/forum/#!msg/cesium-dev/GgfuEFgHw-g/0T3Ypsz7BAAJ

Afterwards we can look at how `backFaceCulling` and `normalShading` can be easily toggled from a tileset.

**Comment by glee2244** [comment]
@lilleyse Hi Sean, just a couple clarifying questions:

1. Looking at how backFaceCulling is handled - is there a significance in having backFaceCulling and _backFaceCulling (https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/PointCloud3DTileContent.js#L119) ?  If there is, is this something that needs to be also done with normalShading?

2. Is all of the code below the line you specified responsible for adding shading (https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/PointCloud3DTileContent.js#L1087)? I ask because I'm still slightly confused as to what lines of code will need to be encapsulated in a if (normalShading) block.

3. How can I test my implementation of the normalShading flag?

**Comment by lilleyse** [comment]
Sorry @glee2244, I missed this comment. @AnimatedRNG will finish this up now.

1. Having both allows us to check if the value has changed since the last frame. It is basically the same as having a dirty flag, but slightly less code. `normalShading` will act similarly.
2. I updated the link in the top post. Everything in that `hasNormals` block applies the shading. The new code should be just `hasNormals && normalShading`.
3. To visually test, switch to the `Point Cloud Normals` tileset in the `3D Tiles` sandcastle demo. Add a Sandcastle button that toggles `tileset._root.content.normalShading`. For testing in the Spec file you can render once with `normalShading` on, once with `normalShading` off, and compare the pixel colors.

**Comment by pjcozzi** [comment]
Fixed in #5433.

**Comment by lilleyse** [comment]
The option exists at the `PointCloud.js` level, which is private, but not the tileset level. So reopened this.

**Comment by lilleyse** [comment]
The options were added to `PointCloudShading` which is accessible from the tileset level in https://github.com/AnalyticalGraphicsInc/cesium/pull/7399.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!msg/cesium-dev/GgfuEFgHw-g/0T3Ypsz7BAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/5152 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
