### ISSUE TITLE
Support add/remove of an instance from ModelInstanceCollection

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5155]
Requested on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/aYbtOBbZ6CQ

Adding or removing instances from a collection without having to rebuild the entire collection.

**Comment by mramato** [comment]
`ModelInstanceCollection` is private and not part of the public API.  It's also not even in master yet and is only part of the `3d-tiles`.  Users should not be creating or using this object directly.

**Comment by lilleyse** [comment]
I'll leave this in the back of my head though, it may not be too hard to support.
