### ISSUE TITLE
Per-tile memory usage statistics

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5156]
For #3241 

@rahwang 

It would be nice to extend the per-tile debug labels to show more than just geometric error. There are other statistics that would be useful to show, like
* number of commands
* texture memory usage
* vertex memory usage

In the Cesium 3D Tiles Inspector, there could be a sub-section of `Display` called `Tile Info` that has checkboxes for each of these properties, which appear together in a label for each tile.

The label style can take inspiration from the picking demo. Sometimes it's nice to see all the tiles labelled at once, but also the idea of showing an info box on hover seems pretty cool to have, and less clutter. Both these options can be supported in the inspector.

<img width="630" alt="better-labels" src="https://cloud.githubusercontent.com/assets/915398/24371112/d0c508c8-12f7-11e7-8ae5-bd4e98316143.png">

Current version, just geometric error:
<img width="412" alt="geometric-error" src="https://cloud.githubusercontent.com/assets/915398/24371132/e1ac9976-12f7-11e7-9bf2-2e18af75b1a3.PNG">

**Comment by rahwang** [comment]
Thanks for all your help with this, @lilleyse !

**Comment by pjcozzi** [comment]
Fixed in #5188
