### ISSUE TITLE
Throw debugging errors in the 3D Tiles Sandcastle demos

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5158]
For development/debugging purposes it would be helpful to see when errors occur when loading `tileset.json` or individual tiles while in the Sandcastle demos, as the current behavior just leaves an empty globe / empty tile space.

Checking for `tileset.json` errors is pretty easy, but checking for tile errors is more difficult as the `readyPromise` is not easily accessible from the outside. Would it be worth supporting a debugging event in `Cesium3DTileset` like `tileFailed` to look for these types of errors in the Sandcastle demos?

This will help save a lot of time when debugging invalid tiles.

**Comment by lilleyse** [comment]
Example case where this would help: https://github.com/AnalyticalGraphicsInc/cesium/issues/5158

**Comment by mramato** [comment]
I think a `tileFailed` event makes a lot of sense, do terrain and imagery already do something similar?  We should make sure we have a holistic approach so that the architecture/API makes sense from the outside.

**Comment by lilleyse** [comment]
> do terrain and imagery already do something similar

I think so, `TileProviderError.handleError` does something like this.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6088
