### ISSUE TITLE
Dome Geometry

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5167]
Requested on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/lvoe4Kp8X8g

Several users have asked for a geometry type that is a partial sphere

**Comment by shunter** [comment]
FYI sensor domes are already available as part of Cesium Pro.

**Comment by mramato** [comment]
This is no different than an ellipsoid with depth testing turned on.  If someone literally once a half-sphere, we already have an issue for that (#4754) (any subset of a sphere is a sector.)

**Comment by hpinkos** [comment]
@mramato In the forum it sounded like they do want half a sphere.  The sector would be a subset of a cylinder, so this is different

**Comment by srtrotter** [comment]
Hello, I left a comment in the forum, but thought I'd jump over here after Hannah pointed me to it. I am really after a sector, not a half-sphere. I want to define a min/max az/el to draw only a portion of a sphere, which may or may not be half.

**Comment by srtrotter** [comment]
Hello, I was asking about this in the forum, and thought I'd jump over here after Hannah pointed me to it. What I need is to be able to draw a sector of a sphere, given a min/max az/el, which may or may not be a half sphere.

Thanks,
Steven

**Comment by mramato** [comment]
Thanks @srtrotter that's a reasonable request.  I could see it either being options to the `Ellipsoid` geometry or a new geometry outright.

**Comment by srtrotter** [comment]
That would be great. Any idea which release this might get in?

**Comment by mramato** [comment]
We're swamped with 3D Tiles and related work, so I can't say when this would be added.  However if anyone would like to contribute this new geometry (or update EllipsoidGeometry to handle it) we would be happy to look at a pull request.

**Comment by rahwang** [comment]
Mentioned in the forum again: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/5aAeg9Ahj_E

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/lvoe4Kp8X8g
https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/5aAeg9Ahj_E

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/5167 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
