### ISSUE TITLE
latest version of GeoJsonDataSource throw exceptions

### ISSUE THREAD

**Issue by Mofangbao** [AnalyticalGraphicsInc/cesium#5180]
Hi,thanks for the perfect project first!
I'm using the latest version 1.3.2,when i try to show the geojson file below ,exceptions occured,but version 1.1.6 can load the file correctly.

GeoJSON file link:

http://7xp128.dl1.z0.glb.clouddn.com/110m-land.json

code modified from Sandcastle:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    sceneMode : Cesium.SceneMode.SCENE2D,
    timeline : false,
    animation : false
});

var dataSource = Cesium.GeoJsonDataSource.load('../../SampleData/110m-land.json');
viewer.dataSources.add(dataSource);
viewer.zoomTo(dataSource);
```

Is this a bug? Thanks a lot!

**Comment by mramato** [comment]
Thanks @Mofangbao!  At first glance this does seem to be a bug.

@bagnell this is a splitting problem when processing for two.  For example, this crashes:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.dataSources.add(Cesium.GeoJsonDataSource.load('http://7xp128.dl1.z0.glb.clouddn.com/110m-land.json'));
```

But this doesn't

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {scene3DOnly: true});
viewer.dataSources.add(Cesium.GeoJsonDataSource.load('http://7xp128.dl1.z0.glb.clouddn.com/110m-land.json'));
```

I also attached the linked geojson just in case the url stops working at any point: [110m-land.json.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/893416/110m-land.json.txt)

**Comment by Mofangbao** [comment]
@mramato Thank you for so much concern.

**Comment by hpinkos** [comment]
The attached GeoJSON renders without crashing
