### ISSUE TITLE
Overlapping billboards blended incorrectly

### ISSUE THREAD

**Issue by schmidtk** [AnalyticalGraphicsInc/cesium#5185]
The icon blending issues fixed in #5066 can still be reproduced with a lot of overlapping icons.

Take the following Sandcastle snippet:

```
var viewer = new Cesium.Viewer('cesiumContainer');

var altitude = 75000;
var count = 5000;
var opacity = 1.0;
var degrees = 1;

for (var i = 0; i < count; i++) {
    viewer.entities.add({
        position : Cesium.Cartesian3.fromDegrees(Math.random() * degrees, Math.random() * degrees),
        billboard :{
            image : 'http://maps.google.com/mapfiles/kml/shapes/parks.png',
            scale : 0.5,
            color : new Cesium.Color(1.0, 1.0, 1.0, opacity)
        }
    });
}

viewer.camera.flyTo({
    destination : Cesium.Cartesian3.fromDegrees(degrees / 2, degrees / 2, altitude)
});
```

At the provided altitude, icon borders bleed into other icons:
![screen shot 2017-04-05 at 2 42 52 pm](https://cloud.githubusercontent.com/assets/5685437/24726162/9951e0b4-1a0e-11e7-9e5c-cc68333ed68f.png)

If you zoom out, the icon borders no longer overlap.

**Comment by pjcozzi** [comment]
@schmidtk thanks for the report and code example.

@emackey any ideas?

**Comment by emackey** [comment]
This is a somewhat fleeting glimpse of the bug, only viewable from very few angles and distances.  It looks like it starts to happen right along a frustum boundary.

@bagnell as a test, I tried setting `OPAQUE_FRUSTUM_NEAR_OFFSET` (in `Scene.js`) to exactly 1.0, and sure enough, this reproduce case goes away.  I believe that means this is actually a lingering effect of #5083, where the edges of the trees are not quite at the same depth as the interior of each tree.  The teeny depth offset is enough, from this particular view angle & distance, to cause the bad edge behavior against other trees.

@bagnell could we use the same frustum for both opaque & translucent, with a slight overlap, but just use a clipping plane (or non-1.0 depth clear value) to prevent overlap in the translucent pass?

**Comment by ZacLiveEarth** [comment]
We are affected by this bug as well. It seems that there are also times when a billboard can be between frustums and only render it's 'outline', where the 'outline' is just pixels that have non-zero and non-one alpha in the texture. At a glance, it seems that the billboard has disappeared.

**Comment by ZacLiveEarth** [comment]
Here are some images of a billboard moving away from the camera along the terrain and through the frustum boundaries.

![billboardclose](https://user-images.githubusercontent.com/15931232/36693998-877e44c2-1b02-11e8-8f85-bf6c8a8478b9.PNG)

![billboardmid](https://user-images.githubusercontent.com/15931232/36694027-a504fcd4-1b02-11e8-8743-6b61eecb0e09.PNG)

![billboardhalfmid](https://user-images.githubusercontent.com/15931232/36694034-a8eabb68-1b02-11e8-8bcd-7a5bec49fdaa.PNG)
![billboardfar](https://user-images.githubusercontent.com/15931232/36694037-ade00c54-1b02-11e8-9b56-ca01fbfd4eac.PNG)

**Comment by hpinkos** [comment]
Thanks for the extra details @ZacLiveEarth!  Could you attach that icon to this issue so we can use it for testing?

**Comment by ZacLiveEarth** [comment]
Pretty much any png with anti-aliased edges will do. The tree icon above, for example, should work just fine.

**Comment by hpinkos** [comment]
@ZacLiveEarth Gotcha, thanks =)

**Comment by hpinkos** [comment]
Appears fixed 
![image](https://user-images.githubusercontent.com/3451886/65268144-89c07180-dae4-11e9-845d-af9367e9011b.png)

**Comment by schmidtk** [comment]
@hpinkos Confirmed, thank you!
