### ISSUE TITLE
Z Ordering

### ISSUE THREAD

**Issue by noacohen** [AnalyticalGraphicsInc/cesium#5187]
hi, is there a way to visually line up a billboard or other elements in front of all the other elements? (common z indexing)

i tried to play with eye offset but sometimes it acts weird (i guess it needs a formula for different zoom scales) and polylines doesnt even have that property...

I also tried to play with positions altitudes but if i increase one point alt by 5 meters for example, 
it gets higher but its still not higher than other points with base altitude which is higher (cuz of terrain differneces)...

any solution?

**Comment by hpinkos** [comment]
Hello @noacohen,

Sorry, we currently don't have good z-ordering support.  We have an issue written up here to look into improving this: #4108 

I'm going to close this issue as a duplicate. Thanks!
