### ISSUE TITLE
Wrong formula in Matrix3.fromHeadingPitchRoll()

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5195]
Reported by @zimengyang in [this comment](https://github.com/AnalyticalGraphicsInc/agi-cesium-arcade-game/issues/26#issuecomment-293062816)

> I double checked Cesium's implementation in Matrix3.fromHeadingPitchRoll(), there is a bug here:
Cesium/Core/Matrix3.js, line 321, formula here is incorrect,
>
>The correct formula is:
>var m12 = -sinPhi * cosPsi + cosPhi * sinTheta * sinPsi;
>
>Instead of
>var m12 = -sinTheta * cosPhi + cosPhi * sinTheta * sinPsi;

**Comment by pjcozzi** [comment]
@rahwang could you open a pull request with the fix?

**Comment by rahwang** [comment]
@pjcozzi yep! On it!
