### ISSUE TITLE
Camera goes under terrain

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5199]
Reported in the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/gqaHh1IaTQM

Looks like the camera goes under the terrain when the tiles are not fully loaded.

**Comment by hpinkos** [comment]
![fly-under-terrain](https://cloud.githubusercontent.com/assets/3451886/24922283/cbb359e6-1ebb-11e7-8c1a-6a9ad3a1ca2a.gif)

**Comment by mramato** [comment]
This is by design, camera flights disable collision with the terrain until all of the terrain in the area has finished loading, otherwise it's impossible to have the camera fly anywhere close to the ground.  See #4105
