### ISSUE TITLE
change default screen control crash

### ISSUE THREAD

**Issue by swhkyo** [AnalyticalGraphicsInc/cesium#5219]
Hi, I want change the default control in the pad so I add the following code in my project:

viewer.scene.screenSpaceCameraController.rotateEventTypes = [
    Cesium.CameraEventType.MIDDLE_DRAG,
    Cesium.CameraEventType.PINCH, // something worng in this line
    {
      eventType: Cesium.CameraEventType.LEFT_DRAG,
      modifier: Cesium.KeyboardEventModifier.SHIFT
    }
  ];

when I using 2 fingers to move the camera, the web will crash.

**Comment by pjcozzi** [comment]
@swhkyo could you please post a question to the [Cesium forum](http://cesiumjs.org/forum.html)?  You'll get a better response there; we use this GitHub repo for feature requests and bugs.
