### ISSUE TITLE
Problem filling long area on the ground

### ISSUE THREAD

**Issue by Ismir11** [AnalyticalGraphicsInc/cesium#5223]
We’re consistently seeing issues with the way that Cesium is deciding to fill some of our long pushbroom footprints. I’ve attached an example czml file that demonstrates the issue.

[BadFootprint.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/944978/BadFootprint.zip)

**Comment by pjcozzi** [comment]
Thanks @Ismir11.  I consolidated this with #4871.
