### ISSUE TITLE
Wrong on hover description for Custom Geocoder sandcastle example

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5227]
<img width="320" alt="screen shot 2017-04-21 at 3 06 16 pm" src="https://cloud.githubusercontent.com/assets/1758825/25292475/4eafb2d2-26a4-11e7-9118-7555f951d0e5.png">

**Comment by rahwang** [comment]
Interpolation is wrong too.

**Comment by hpinkos** [comment]
Thanks @rahwang!  You can fix this by editing the text under the 'Info' button in Sandcastle and saving the example 

![image](https://cloud.githubusercontent.com/assets/3451886/25340177/ed914f16-28d2-11e7-9a41-cef873b9f513.png)
