### ISSUE TITLE
Minor Tutorial Issues

### ISSUE THREAD

**Issue by TanYongTai** [AnalyticalGraphicsInc/cesium#5229]
https://cesiumjs.org/tutorials/Imagery-Layers-Tutorial/
Should change "new Cesium.TileMapServiceImageryProvider" to "new Cesium.createTileMapServiceImageryProvider"

https://cesiumjs.org/tutorials/Camera-Tutorial/
Should change "orentation" to "orientation"

**Comment by hpinkos** [comment]
Thanks @TanYongTai!

@rahwang can you fix this?

**Comment by morrme** [comment]
Can I help with this?

**Comment by hpinkos** [comment]
Thanks for volunteering @morrme.  The code for this tutorial is in a different repo though, so someone from our team will have to take care of it.  Check out the beginner label to see if there are any other issues you would be interested in fixing: https://github.com/AnalyticalGraphicsInc/cesium/labels/beginner
Thanks!

**Comment by emackey** [comment]
[Meta comment: I think we shouldn't use the `beginner` label for issues that require access to private repos, nor for issues that involve coordinating with AGI legal on licensing issues, AGI marketing on logo usage, etc., even if those tasks don't require coding skill.]

**Comment by pjcozzi** [comment]
@emackey I thought about that but then I can't find them when looking for onramping issues.  I'll use another approach if this comes up often enough.

**Comment by emackey** [comment]
OK.  I took the tag off but feel free to add it back.  Or maybe `onramping` is a better tag here than `beginner`?

**Comment by hanbollar** [comment]
@hpinkos - just fixed this, so it can be closed when you're ready

**Comment by ggetz** [comment]
Fixed and deployed to cesiumjs.org
