### ISSUE TITLE
Display text blur

### ISSUE THREAD

**Issue by mumu1** [AnalyticalGraphicsInc/cesium#5235]
Drawing text blur on cesium 3D sphere
![blur](https://cloud.githubusercontent.com/assets/23307078/25375357/06107926-29d3-11e7-83fc-7f87306e82da.jpg)
Original canvas draw text fine,image like below:
![https://cloud.githubusercontent.com/assets/23307078/25375385/16e52b20-29d3-11e7-8b86-1711c77b4524.png]()
![original](https://cloud.githubusercontent.com/assets/23307078/25375385/16e52b20-29d3-11e7-8b86-1711c77b4524.png)

**Comment by mumu1** [comment]
![blur](https://cloud.githubusercontent.com/assets/23307078/25375357/06107926-29d3-11e7-83fc-7f87306e82da.jpg)

**Comment by mumu1** [comment]
![original](https://cloud.githubusercontent.com/assets/23307078/25375385/16e52b20-29d3-11e7-8b86-1711c77b4524.png)

**Comment by hpinkos** [comment]
Thanks @mumu1, this is a known issue.  See #2752 for some more details

**Comment by mramato** [comment]
In the mean time, you can set `viewer.scene.fxaa = false;` for much crisper text and imagery rendering and the cost of sharper lines.
