### ISSUE TITLE
Add Skip LOD options to 3D Tiles Inspector

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5239]
@rahwang do you want to do this?

@austinEng can explain the parameters added in #5128.

**Comment by rahwang** [comment]
Sure thing! I'll add it to my list.

**Comment by austinEng** [comment]
- Checkbox to toggle `tileset.skipLODs`
- #5254 is going to add a value called `baseScreenSpaceError` which should be modifiable like `maximumScreenSpaceError`
- Slider for `tileset.skipSSEFactor`. Probably range from 1 to 50
- Slider for `tileset.skipLevels`. Probably range from 0 to a small number.
- Checkboxes for `tileset.immediatelyLoadDesiredLOD` and `tileset.loadSiblings`
- Debug display for `tile._selectionDepth`. It would be nice if tiles could be colored by this value, similar to the way debugColorize works. It may also be helpful to have it displayed as a label
- It would be good to add something to show `tile._screenSpaceError`

**Comment by pjcozzi** [comment]
Fixed in #5405
