### ISSUE TITLE
KMZ uncompression in FF52+

### ISSUE THREAD

**Issue by jburr-nc** [AnalyticalGraphicsInc/cesium#5240]
Our users are reporting that as soon as they upgrade to FF52, KMLs take forever to load -- to the point where it's unusable.  We are using the Cesium.KmlDataSource.load() function.  When they roll back to FF51 (with no code changes on our end), everything works perfectly again.

I can now re-produce this issue fairly consistently.  It seems to happen when they upload a KMZ archive instead of a KML file.  I can't supply a sample for you, but I can say the uncompressed KML files can sometimes be upwards of 20MB+ in size.

The KMZ may sit there 20+ minutes trying to load.
If I manually extract the KML before uploading, the same data takes 5-10 seconds to load.
This happens even when there are no other files or images in the KMZ except for the doc.kml file.

Sorry I couldn't post on the dev forum first -- I can't access it here.  But feel free to close if you can't reproduce or if you think there's something else happening on our end.

**Comment by mramato** [comment]
Thanks for the bug report @jburr-nc.  It went to test this but it looks like FF53 just landed and I'm not seeing any performance issues with it (unzipping the kmz takes no longer than usual).  Maybe it was an FF bug that they already fixed.

I was testing on Windows 10.  What OS are your users on?  What are you using to generate the kmz files?  Perhaps it's something specific to the way they are being compressed?

It's going to be hard to track this down without being able to reproduce it, if you can provide a sample kmz that causes the problem for you (even if it's totally made up data), then we can look further into it.

**Comment by jburr-nc** [comment]
Thanks for looking into this @mramato.  I'll see if I can create a sample to easily reproduce this.  Closing until I have more info for you.
