### ISSUE TITLE
Proper STK Terrain Server API not being used

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#5257]
References to AGI's hosted STK Terrain Server are not valid for out-of-the-box private deployments (local rewrite rule).  Please update the examples to use "https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles".

**Comment by pjcozzi** [comment]
@rahwang could you please make this change?

**Comment by rahwang** [comment]
Sure thing, @pjcozzi !

**Comment by mramato** [comment]
There are also a slew of places in cesium's code base where we do this, might as well be consistent.  Just search for `assets.agi.com/stk-terrain` and you'll find them all (since they are not all `world` specific).
