### ISSUE TITLE
Clean up CZML geometry examples

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5266]
A bunch of our CZML Sandcastle examples trigger the "outlines not supported for Ground primitives" warnings in the console.  This is confusing for new users.  We should either remove the outlines from these examples (since they don't show up anyway) or explicitly set the height to 0 so that ground primitives aren't used and the outline is shown.

@rahwang this might be a good low-hanging issue to work on.

**Comment by mramato** [comment]
This is true of our regular Geometry examples too, (i.e. Corridor).

**Comment by rahwang** [comment]
Thanks for pointing this out, @mramato !
