### ISSUE TITLE
HPR example hard to read

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5267]
http://localhost:8080/Apps/Sandcastle/index.html?src=HeadingPitchRoll.html&label=All

Needs a background like our other examples.

![image](https://cloud.githubusercontent.com/assets/1495196/25593128/5c3f893a-2e89-11e7-927d-b45becca3cc8.png)

**Comment by mramato** [comment]
Same thing for http://localhost:8080/Apps/Sandcastle/index.html?src=LocalToFixedFrame.html&label=All

**Comment by emackey** [comment]
For whoever does this, I recommend `background: rgba(42, 42, 42, 0.8);`  I think there are existing demos with this or very similar backgrounds.

**Comment by JamieDawson** [comment]
Thanks for the suggestion @emackey , i'll take a look at it and see what I can do.

**Comment by rahwang** [comment]
I volunteer as tribute!
