### ISSUE TITLE
Picking in Clustering sandcastle demo doesn't do anything

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5286]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clustering.html&label=Showcases

I noticed [this block of code](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/gallery/Clustering.html#L151-L162) in the Clustering sandcastle example:

```
    var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
    handler.setInputAction(function(movement) {
        var pickedLabel = viewer.scene.pick(movement.position);
        if (Cesium.defined(pickedLabel)) {
            var ids = pickedLabel.id;
            if (Cesium.isArray(ids)) {
                for (var i = 0; i < ids.length; ++i) {
                    ids[i].label.fillColor = Cesium.Color.RED;
                }
            }
        }
    }, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

But no matter what you click on, `pickedLabel.id` is always `undefined`.

@bagnell what was this meant to do?

**Comment by bagnell** [comment]
`pickedLabel.id` should be an array of the entities in the cluster.

**Comment by rahwang** [comment]
Mentioned on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/APtarX9ga64

**Comment by hpinkos** [comment]
Pretty sure this is what we want to do:
- [ ] Add an id to the default entity cluster label in [`EntityCluster`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/EntityCluster.js#L141)
- [ ] Add an id to the custom style billboard in the Sandcastle example
