### ISSUE TITLE
1.33.0 release and webpack glsl loader

### ISSUE THREAD

**Issue by lyssdod** [AnalyticalGraphicsInc/cesium#5291]
Hi,

I'm happily using webpack with cesium and everything works nice. However, after recent update to fresh 1.33.0 release webpack gives me warnings:

```
WARNING in ./~/cesium/Source/ThirdParty/Shaders/FXAA3_11.glsl
Module parse failed: 
$/work/frontend/node_modules/cesium/Source/ThirdParty/Shaders/FXAA3_11.glsl Unexpected character '#' (87:0)
You may need an appropriate loader to handle this file type.
| 
| 
| #if (FXAA_QUALITY_PRESET == 10)
|     #define FXAA_QUALITY_PS 3
|     #define FXAA_QUALITY_P0 1.5
 @ ./~/cesium/Source/ThirdParty ^.\/.*$
 @ ./~/cesium/Source/ThirdParty/pako_inflate.js
 @ ./~/cesium/Source/Core/GoogleEarthEnterpriseMetadata.js
 @ ./~/cesium/Source/Core ^.\/.*$
 @ ./~/cesium/Source/Core/buildModuleUrl.js
 @ ./app/index.js
```

Adding glsl loaders to webpack didn't solve this issue. Anyway, everything works nice expect this issue keeps me worried a bit :) 

My webpack config is:

```javascript
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
//var WebpackBundleSizeAnalyzerPlugin = require('webpack-bundle-size-analyzer').WebpackBundleSizeAnalyzerPlugin;
var webpack = require('webpack');

var ExtractTextPlugin = require("extract-text-webpack-plugin");
var OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
var LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

var path = require('path');

var config = {
    node: {
        fs: 'empty' /* workaround for cesium 1.33 */
    },
    entry: {
        //abc: path.join(__dirname, 'app', 'loader.js'),
        main: path.join(__dirname, 'app', 'index.js')
    },
    output: {
        path: path.join(__dirname, 'public'),
        filename: '[name]-[hash].js',
        sourcePrefix: '',
        publicPath: '/'
    },

    module : {
        /* cesium quirks */
        unknownContextCritical: false,
        unknownContextRegExp: /^.\/.*$/,
        /* ^^^^^ https://github.com/AnalyticalGraphicsInc/cesium/issues/4876 */
        rules : [ {
            test: /\.(js)$/,
            exclude: /node_modules/,
            use: {
                loader: 'babel-loader',
                query: {
                    presets: [
                        ['es2015', { 'modules': false }],
                        ['react']],
                    plugins: ['lodash']
                    
                }
        } }, {
            /* concat css */
            test: /\.css$/,
            use: ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })
        }, {
            /* use these with care */
            test: /\.(png|gif|jpg|jpeg)$/,
            loader: 'file-loader'
        },
        /*{ test: /\.png$/, use: "url-loader?limit=100000" },
        { test: /\.jpg$/, use: "file-loader" },*/
        /* webfonts */
        { test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/, use: 'url-loader?limit=10000&mimetype=application/font-woff' },
        { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, use: 'url-loader?limit=10000&mimetype=application/octet-stream' },
        { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, use: 'file-loader' },
        { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, use: 'url-loader?limit=10000&mimetype=image/svg+xml' }
        ]
    },
    devServer : {
        historyApiFallback: true,
        contentBase: './public'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin("common.js"),
        new HtmlWebpackPlugin({
            minChunks: Infinity,
            chunksSortMode: function (a, b) {  //alphabetical order
                if (a.names[0] > b.names[0]) {
                    return 1;
                }
                if (a.names[0] < b.names[0]) {
                    return -1;
                }
                return 0;
            },
            template: 'app/index.html',
            inject: true 
        }),
        new webpack.ProvidePlugin({
            Promise: 'es6-promise-promise'
        }),
        new webpack.DefinePlugin({
          'process.env': {
            'NODE_ENV': JSON.stringify('"production"')
          }
        }),
        new ExtractTextPlugin("styles.css"),
        new LodashModuleReplacementPlugin()
    ]
}

if (process.env.NODE_ENV === 'production') {
    config.plugins.push(
        /* pass NODE_ENV down to to-be-compiled code */
        new webpack.DefinePlugin({
            'process.env' : {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
            }
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new OptimizeCssAssetsPlugin({
            cssProcessorOptions: {
                safe: true, /* preserve z-indexes */
        }}),
        new webpack.optimize.UglifyJsPlugin()
    );
}

module.exports = config;
```

**Comment by mramato** [comment]
@lyssdod, thanks for reporting your issue, but in the future please use the forum for questions like this.  It will be seen by more people and get a faster response: https://groups.google.com/forum/?fromgroups#!forum/cesium-dev

To answer your question, the `glsl` files are not needed at all when using a Cesium release, they are compiled into JavaScript at build time.  You should just configure your build system to ignore them or ignore the warning you are seeing.

**Comment by thw0rted** [comment]
FWIW I added

        { test: /\.glsl$/, use: 'file-loader' },

to my `module.rules` and it got rid of the warning.  Maybe webpack integration docs need an update since there have been a lot of changes since [the last one](http://cesiumjs.org/2016/01/26/Cesium-and-Webpack/)?  I've had a tough time getting things running, but I'm a webpack newbie...

**Comment by lyssdod** [comment]
Thank you guys!

**Comment by pjcozzi** [comment]
@mramato are there any docs we should update with https://github.com/AnalyticalGraphicsInc/cesium/issues/5291#issuecomment-302057468?

**Comment by mramato** [comment]
I don't think so, we don't really have any "how to use Cesium with webpack" doc and we also never added specific doc for our modules other than the fact they are AMD.

**Comment by thw0rted** [comment]
Of course you're right, the "docs" I linked to are a guest blog post -- hardly canonical.  Still, the experience of using Cesium via Webpack could be simpler.  If I want to use jQuery, I just 1) `npm install --save jquery`, then 2) `import $ from 'jquery'`; there is no step 3.  Even if you fix #4876, I'm still stuck copying a bunch of assets to be served directly (or in the case of Webpack, using the `copy-webpack-plugin`).  Is one-line integration on the roadmap at some point?

**Comment by pjcozzi** [comment]
@thw0rted sorry for the slow response.  Yes, we want to have super simple integration with webpack in the future.

In the short-term, would you like to write a short guest post on the Cesium blog with the latest info on using Cesium and webpack together with the latest info?

**Comment by thw0rted** [comment]
I will keep it in mind -- I have a deadline next week so I'm unlikely to have the time to blog before then, but maybe after?  That said, I'm not convinced I'm using this properly.  My current Webpack config "works" but takes a relatively long time (20+ seconds) to build and results in one 10+MB JS file.

I think I have some reading to do!

**Comment by pjcozzi** [comment]
Sounds good, @thw0rted, keep us posted!

**Comment by markerikson** [comment]
For reference, I did write a blog post that demonstrates configuring Webpack to load Cesium, and also how to use Webpack's "DLL" feature to pre-build a Cesium bundle that doesn't have to be rebuilt whenever the app is edited: [Declaratively Rendering Earth in 3D, Part 1: Building a Cesium + React App with Webpack](http://blog.isquaredsoftware.com/2017/03/declarative-earth-part-1-cesium-webpack/).
