### ISSUE TITLE
Labels should render above Polygons and Polylines regardless of order added

### ISSUE THREAD

**Issue by jktaylor** [AnalyticalGraphicsInc/cesium#53]
No matter what altitude I put my label at, it always gets rendered beneath a polygon or polyline when the primitive is added after the labelcollection.  To see what I mean, try In the Sandbox to paste the label code example into the polygon example and move the label's position so it intersects with the polygon. 

I can use sendtoback in compositeprimitive to keep the ordering correct, but I was just thinking that maybe this should be done always in the compositeprimitive class without my intervention.

**Comment by drakej** [comment]
This would be nice although any form of draw ordering control is welcome.

**Comment by hpinkos** [comment]
duplicate of #4108
