### ISSUE TITLE
Label offset problem

### ISSUE THREAD

**Issue by moonvoid** [AnalyticalGraphicsInc/cesium#5302]
1.In the case of loading terrain,the Polyline object is offset
2.In the case of loading terrain,change label width and height，the label object is offset
![1](https://cloud.githubusercontent.com/assets/16361207/25880868/74fa6c44-356c-11e7-9ef8-2a6af814f643.jpg)
![2](https://cloud.githubusercontent.com/assets/16361207/25880878/7ca4c638-356c-11e7-98b7-2490501561c5.jpg)
![3](https://cloud.githubusercontent.com/assets/16361207/25880886/873e9268-356c-11e7-9961-e2d608e1287a.jpg)

**Comment by hpinkos** [comment]
Hello @moonvoid, can you please post a minimal [Sandcastle Example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) that reproduces this problem?
