### ISSUE TITLE
billboard height with sizeInMeters and VerticalOrigin.BOTTOM

### ISSUE THREAD

**Issue by YousefED** [AnalyticalGraphicsInc/cesium#5303]
Steps to reproduce:
1. http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Billboards.html&label=Showcases
2. add `verticalOrigin: Cesium.VerticalOrigin.BOTTOM` to the `sizeInMeters` example
3. Zoom in / out

Observed behaviour: when zooming out, the billboard seems to change it's height-position relative to the surface.

Expected behaviour: the bottom of the billboard stays "clamped" to the original position.

Let me know if you need more info!

**Comment by hpinkos** [comment]
Thanks for reporting this @YousefED!  You can see the billboard is creeping upwards as I zoom out:

![billboard-meters](https://cloud.githubusercontent.com/assets/3451886/25911133/b7e7fbd4-3580-11e7-8ccf-070922471dce.gif)
 
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var entity = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    billboard : {
        image : '../images/Cesium_Logo_overlay.png',
        sizeInMeters : true,
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM
    }
});

viewer.zoomTo(entity);
```

**Comment by YousefED** [comment]
Thanks for adding. Offtopic: What tool do you use for your video snippets?

**Comment by hpinkos** [comment]
We use [LICEcap](https://licecap.en.softonic.com/) to capture animated GIFs.  Definitely comes in handy
