### ISSUE TITLE
Clarify difference between GoogleEarthImageryProvider and GoogleEarthEnterpriseImageryProvider

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5310]
From @thw0rted in #5189

> The thread here was very helpful in understanding the difference between the GE provider and the GEE provider, but this clarification is sorely lacking in the documentation. Since both providers actually talk to GEE (and not the public GE server), maybe in a future release it would be helpful to merge the two and provide a 2D/3D mode switch? That would clarify the intent.

**Comment by mramato** [comment]
Thanks for the reminder, I meant to mention this in the original PR.  I think a rename of the original class to mention `Maps` (i.e. `GoogleEarthEnterpriseMapsProvider`) and `@link` in the jsDoc for both that clearly explain the differences should be a good, low-impact way of handling this.

**Comment by lilleyse** [comment]
Fixed in #5399
