### ISSUE TITLE
Render Error Switching from Columbus View to 3D view

### ISSUE THREAD

**Issue by cfairchi** [AnalyticalGraphicsInc/cesium#5311]
Cesium 1.33, open sandcastle hello world (Chrome 51.0.2704.84), go to Columbus view, then go back to 3D view and I get a rendering error.
TypeError: Cannot read property 'clone' of undefined

**Comment by hpinkos** [comment]
Thanks for reporting this @cfairchi!  I was able to reproduce this first try.

@bagnell can you look into this?

**Comment by pjcozzi** [comment]
@cfairchi this was fixed in #5312.  It will be in Cesium 1.34 in June.
