### ISSUE TITLE
Should CompositeEntityCollection maintain the entity.values order of it's collections?

### ISSUE THREAD

**Issue by denverpierce** [AnalyticalGraphicsInc/cesium#5313]
Psuedo:
```
var a = new EntityCollection([1,2,3]);
var b = new EntityCollection([4,5,6]);

var composite = new CompositeEntityCollection().addCollection(a);
composite.addCollection(b);

composite.entities.values = 6,5,4,3,2,1;
```

Is it intended to reverse the order of the entities in the collection (as compared to `EntityCollection`), or should it just not be considered to be in the same order as the source collections?

**Comment by shunter** [comment]
I suspect it's a quirk of the implementation.  In general, I think we usually consider entity collections as being unordered, with intended access being through id lookups (`getById`).

**Comment by denverpierce** [comment]
Ok, it was a little confusing when using it in a loop that needed to maintain the processed order, but it's an understandable behavior.
