### ISSUE TITLE
Add basePath option to Cesium.Model.fromGltf

### ISSUE THREAD

**Issue by HowardWolosky** [AnalyticalGraphicsInc/cesium#5320]
Right now, there are two ways of loading glTF content:

`Cesium.Model.fromGltf` and `new Cesium.Model`.  When using `new Cesium.Model`, you can specify a `basePath` (although it doesn't currently work (see Issue #5319)).  Unfortunately, you can't specify a `basePath` when using `Cesium.Model.fromGltf`.  This means it's not possible to use that API to load local files that leverage relative paths for their binary content.

This is to track the request to add the ability to specify a `basePath` for `fromGltf` as well.

**Comment by pjcozzi** [comment]
This should be a small tweak.

@rahwang do you want to make this change?  @lilleyse can advise.  Just be careful that this probably needs to be part of the key for the cache.

**Comment by pjcozzi** [comment]
Thanks again for the input, @HowardWolosky.

Added in #5403 by @moneimne
