### ISSUE TITLE
3D Tiles scaling does not scale geometric error

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5330]
When setting a scale transform on the root tile in order to scale a 3D Tileset, bad things happen.  The tileset may draw, but at the wrong resolution and it may also disappear completely when it should take up the whole screen.  @likangning93 thinks the problem is that Cesium is not taking the scale transform into account when computing the final client geometric error, leading to incorrect tile selection.

**Comment by lilleyse** [comment]
If we decide to address this in Cesium, we should also update the spec:

From `tile.schema.json`
> A floating-point 4x4 affine transformation matrix, stored in column-major order, that transforms the tile's content, i.e., its features and content.boundingVolume, and boundingVolume and viewerRequestVolume from the tile's local coordinate system to the parent tile's coordinate system, or tileset's coordinate system in the case of the root tile.  **transform does not apply to geometricError** nor does it apply any volume property when the volume is a region, which is defined in EPSG:4326 coordinates.

**Comment by pjcozzi** [comment]
I probably wrote that part of the spec, but it is not going to work.  Two options:

* Explicitly disallow scale as part of the spec.  It will make the client a bit easier to implement if they actually follow the spec.  Cesium could still expose its own scale/transform.
* Allow scale in the spec - including the GE - and fix Cesium, which I do not think will be hard unless I am missing something.

I would go with 2.
