### ISSUE TITLE
Labels/Billboards behind the camera appear in the wrong position when minimumDisableDepthTestDistance is Infinity

### ISSUE THREAD

**Issue by denverpierce** [AnalyticalGraphicsInc/cesium#5331]
[Gist](https://gist.github.com/denverpierce/2e501f3090cb830efb1bee5c89e70288)

This happens when `scene.minimumDisableDepthTestDistance` is set to `Number.POSITIVE_INFINITY`, when viewing Labels/Billboard/Points at angles low to the Horizon and reasonably close to the entities.

Entities behind the camera will render in the wrong position.
![s](https://cloud.githubusercontent.com/assets/5432027/26130794/0bae8802-3a5c-11e7-812e-0f0d059579f1.gif)

**Comment by pjcozzi** [comment]
Thanks for the report, @denverpierce!

@bagnell is this an easy fix?  Perhaps you could guide @rahwang?

**Comment by oterral** [comment]
I'm interested to fix this if someone can give me guidance

**Comment by oterral** [comment]
It happens not only with INFINITY value, but whatever the value I put .

**Comment by hpinkos** [comment]
Thanks for volunteering @oterral!  @bagnell do you have any suggestions here?

**Comment by rahwang** [comment]
Does anyone have any ideas about what this might be? I'd really like to get this fixed soon, since it pops up in my workshop app. @bagnell , any clue? I'd be happy to work on this.

**Comment by pjcozzi** [comment]
@rahwang do you want to experiment with the shader?  See this part: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/BillboardCollectionVS.glsl#L259-L276

**Comment by hpinkos** [comment]
@denverpierce @oterral this issue was fixed in #5737 and will be included in the 1.37 release available on September 1st.  Thanks!

**Comment by denverpierce** [comment]
Did you mean #5735?

**Comment by hpinkos** [comment]
uh, yes!  Thanks @denverpierce =)

**Comment by oterral** [comment]
good thx for the fix !!!!

**Comment by thw0rted** [comment]
I don't know if this was missing before, but right now `disableDepthTestDistance` is missing from the constructor options [in the docs](https://cesiumjs.org/Cesium/Build/Documentation/BillboardGraphics.html).

**Comment by hpinkos** [comment]
Thanks @thw0rted!  I submitted a PR to update the doc #5918
