### ISSUE TITLE
Cesium3DTilesInspector: tiles don't un-select on mouse out

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5332]
![3dtiles-inspector](https://cloud.githubusercontent.com/assets/3451886/26157651/c3380b3e-3ae7-11e7-8037-9b46d8fd89fe.gif)

http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles.html&label=Showcases

The `Cesium3DTilesInspector` no longer returns feature that have been hovered over to their original color

There's also really bad flickering on mouse move for the tilesets that have been hovered over.  Not sure whether that is related.

@lilleyse @rahwang would one of you be able to look into this?

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/5321

**Comment by lilleyse** [comment]
Flickering is related to https://github.com/AnalyticalGraphicsInc/cesium/issues/5307
