### ISSUE TITLE
BingMap

### ISSUE THREAD

**Issue by ailmee** [AnalyticalGraphicsInc/cesium#5340]
Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by ailmee** [comment]
Why can't BingMap load it out?

**Comment by pjcozzi** [comment]
Perhaps the Bing key expired?  Check the console:

> This application is using Cesium's default Bing Maps key.  Please create a new key for the application as soon as possible and prior to deployment by visiting https://www.bingmapsportal.com/, and provide your key to Cesium by setting the Cesium.BingMapsApi.defaultKey property before constructing the CesiumWidget or any other object that uses the Bing Maps API.

In the future, please post questions to the [Cesium forum](http://cesiumjs.org/forum.html).  You'll get a faster response; the GitHub issues are only used for bugs and features.
