### ISSUE TITLE
Remove 3D Tiles deprecation warnings

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5363]
[Batched3DModel3DTileContent](https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/Batched3DModel3DTileContent.js) has special handling for legacy b3dm headers. This should be removed once we're pretty sure most tilesets have upgraded.

**Comment by pjcozzi** [comment]
Labeled with the new `category - 3d tiles` label.  Please use this moving forward on all 3D Tiles issues.  I haven't yet went back through them.

**Comment by lilleyse** [comment]
Also at the same time remove support for the non-underscored `BATCHID` semantic.

**Comment by lilleyse** [comment]
And drop support for lowercase 'add' and 'refine'.

**Comment by lilleyse** [comment]
And turn the geometric error check back into a `RuntimeError` : https://github.com/AnalyticalGraphicsInc/cesium/pull/5574

**Comment by mramato** [comment]
And remove the workaround added in #6125

**Comment by lilleyse** [comment]
Remove workaround that allows loading unaligned glb's. The alignment rules are much more solid in the 1.0 spec.

When fixing, look for `The embedded glb is not aligned to a 4-byte boundary`

**Comment by lilleyse** [comment]
Throw an error if a tile's content is glTF 1.0.

**Comment by lilleyse** [comment]
Does anyone have thoughts on when to start removing the workarounds for these deprecated 3D Tiles syntax/features?

I was thinking the best time would be
* After the [1.0](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0) branch of the spec is merged into `master`
* Finish the `upgrade` command in [3d-tiles-tools](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/issues/145) so that people can upgrade their old tilesets
* Ideally, finish the [3D Tiles validator](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/validator), if there is time.

Thoughts @pjcozzi, @mramato, @ggetz ?

**Comment by mramato** [comment]
I'm all for removing as many workarounds/non-spec compliant behavior as possible.

> Throw an error if a tile's content is glTF 1.0.

Except this one, is there a reason to do this?  It will break almost every tileset we currently have.  What is the burden on just supporting gltf 1.0 forever?  I thought we automatically updated models to 2.0 anyway so I would think the burden is small. (but I could be wrong)

**Comment by lilleyse** [comment]
There isn't any burden in supporting gltf 1.0, but it's technically not valid to be in 3D Tiles 1.0 and I wasn't sure how hard-line we wanted to be.

We have another large breaking change where `tile.content.url` is now `tile.content.uri` https://github.com/AnalyticalGraphicsInc/cesium/pull/6744. If the goal is to not break most existing tilesets then we should also keep the workaround that can load either variant.

With a few exceptions, a lot of the workarounds are actually pretty simple with little code burden. We could just keep most of them around forever if we wanted.

**Comment by ggetz** [comment]
> After the 1.0 branch of the spec is merged into master

When is the plan to do this? I was under the impression that master was the "working" branch and "1.0" is basically the tagged release version for the community standard.

**Comment by mramato** [comment]
> With a few exceptions, a lot of the workarounds are actually pretty simple with little code burden. We could just keep most of them around forever if we wanted.

In that case, my vote would be that anything that's less than a few lines and doesn't affect performance should stick around forever and just log warnings.  We should also make sure there is a clear comment stating that it is there for backwards compatibility reasons.  More complicated workarounds (like #6125) should definitely get removed.  Ultimately, my thinking is that we shouldn't shift the burden to our users (by making them update all of their tilesets) unless there is a good reason to.

But this is just my opinion and I'm sure others may feel differently.

**Comment by lilleyse** [comment]
I'm on board with that. And https://github.com/AnalyticalGraphicsInc/cesium/pull/6125 is a perfect example of one of the exceptions that should be removed.

**Comment by ggetz** [comment]
We added a depreaction warning for `content.url` instead of `content.uri`: https://github.com/AnalyticalGraphicsInc/cesium/pull/6744#issuecomment-402761331

**Comment by lilleyse** [comment]
Given the `content.url` deprecation warning, this is also a good excuse to update all the hosted tilesets to 3D Tiles 1.0, glTF 2.0, and Draco for https://github.com/AnalyticalGraphicsInc/cesium/issues/6487.

Currently working on an `upgrade` command in [3d-tiles-tools](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/2.0-tools) that will help upgrading some of these. It will also fix the "The embedded glb is not aligned to a 4-byte boundary." warning in the power plant model.

**Comment by ggetz** [comment]
Added a deprecation warning fro the Batch Table Hierarchy in https://github.com/AnalyticalGraphicsInc/cesium/pull/6780

**Comment by lilleyse** [comment]
Closing - we're keeping most workarounds for backwards compatibility so no action needed here.
