### ISSUE TITLE
Investigate eslint auto-fix

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5370]
eslint has the ability to automatically fix problems.  At the very least we should add a manual gulp task for fixing problems.  If it's foolproof and fast, we can even consider it happening automatically at commit time.

**Comment by ateshuseyin** [comment]
I am playing with pre-commit now. It is very irritating to wait a while for each commit for me. We can consider push time. If I will have time I will evaluate [pre-push](https://www.npmjs.com/package/pre-push).

There is a risk to use `eslint --fix` for es5 project. If one of es6 specific rule is active (eg. [prefer-spread](http://eslint.org/docs/rules/prefer-spread)), eslint change your code with es6 equivalent.

**Comment by mramato** [comment]
We don't have any es6 rules active, so I don't think `eslint --fix` will be a problem, plus if we have a rule active, we would want it to change the code everywhere.

Can you experiment with enabling [caching](http://eslint.org/docs/user-guide/command-line-interface) to see how much that speeds up the pre-commit hook (I imagine it would be a big help).  I agree that pre-commit might be a little aggressive, we may even decide pre-push is too.  Is it just the run-time that you are irritated by?

**Comment by ateshuseyin** [comment]
My pre-push idea is failed. `eslint --fix` causes some unstaged changes which blocks push. I added a new gulp task (eslint-fix) but I will replace it with eslint cli according to #5449 .

I am still unsettled about pre-commit. After evaluting eslint cli with --cache I will decide.

**Comment by mramato** [comment]
Thanks for looking into this @ateshuseyin.  After some unrelated changes, running with `--fix` is as easy as running `npm run eslint --fix`.  I think running fix automatically is really worth it (since it can't fix everything) and most of the time devs will just manually fix one or two issues.

I think where `--fix` comes in very useful is in adding new rules, which is a rare occurrence.

Long story short, I'm closing this issue.  Thanks again @ateshuseyin.
