### ISSUE TITLE
Breaking Change Log for 3D-Tiles Format Spec

### ISSUE THREAD

**Issue by KermMartian** [AnalyticalGraphicsInc/cesium#5375]
A log of breaking changes to the b3dm/i3dm/cmpt/etc version 1 format as those specs are developed, or breaking changes to their implementation in 3d-tiles, would be greatly appreciated. For example, AnalyticalGraphicsInc/3d-tiles@e6caa00 and its implementation in 2175467. Unfortunately, by the time we upgraded to a commit beyond that one, the deprecation warning for the 24-byte b3dm header seems to have already been removed. Thanks in advance!

**Comment by lilleyse** [comment]
The deprecation warning for both legacy b3dm headers should still be logged here https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/Batched3DModel3DTileContent.js#L261-L285, if it isn't could you send over a sample .b3dm?

The good news is we don't expect the headers to change any more before version 1, and afterwards any breaking changes will be documented.

**Comment by KermMartian** [comment]
The relevant bytes that those lines check are the empty JSON array 7b 7d 20 20 ("  {}"), ie, 0x20207d7b, which is less than 0x22000000 as noted in the source. /After/ those bytes come the glTF magic ("glTF"). I'm not sure why we have spaces before the empty JSON array, but that seems to be perfectly valid JSON regardless. This is probably such a corner case as to not be worth investigating on your end, although we'll strip the extra whitespace on our end.

**Comment by pjcozzi** [comment]
Closing as no action here.

@KermMartian please keep an eye on the [3d-tiles repo](https://github.com/AnalyticalGraphicsInc/3d-tiles) as we are about to put the finishing polish on the spec and would value your input.
