### ISSUE TITLE
support gzipped data file on 3d-tiles branch?

### ISSUE THREAD

**Issue by xuezhaokun** [AnalyticalGraphicsInc/cesium#5410]
Hi,
I just noticed you are now supporting to serve gzipped data file on the 3d-tiles-samples server, and I tried it out and found it is a really cool fix. I am wondering if it is an easy fix for your 3d-tile branch here to support gzipped data file as well. Thanks!

**Comment by lilleyse** [comment]
I should have started the conversation here instead of `3d-tiles-samples`. See @mramato's comment: https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/pull/11

>
> I'm not sure why we would add support for it in Cesium, since we don't include any gzipped tilesets or data, right?
>
>It sounds like they are using the NYC sample data we have up on cesiumjs.org, in my opinion we should change that sample to not include gzipped data.
>
>That being said, if we just want to make our users happy and avoid any potential headaches, I'm not again adding it "just because", but I do have some minor performance concerns, since it means every files gets read twice.
>
>Perhaps we can punt for now and revisit when we handle the http2 PR. The server is long overdue for an update either way.
