### ISSUE TITLE
"Any" type in JSDoc

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5411]
There are places in the code where we use  `{Object}` to indicate "This can be anything" when in reality the correct type is `{*}`.  We should do a review of the doc and fix these.

**Comment by hanbollar** [comment]
@mramato does this include changing items from `{Object[]}` to `{*[]}` ?

**Comment by hpinkos** [comment]
@hanbollar you'll have to take a look at what the parameter is.  If the function expect is something like `[{property: 1}, {property: 2}, {property: 3}]` it should stay `{Object[]}`.  However, if it's something that can be an array of anything (string, number, boolean, etc) then it would be `{*[]}`

Same goes for `{Object}`.  Don't just replace all `{Object}` with `{*}`, you'll have to look to see what the function is expecting.
