### ISSUE TITLE
glTF 3d model texture is not showing in mobile chrome browser

### ISSUE THREAD

**Issue by kladess** [AnalyticalGraphicsInc/cesium#5416]
https://geoint.iptime.org:8442/rabbit/

Hi, my 3d model was made  by 3d scanner s/w and converted to glTF format by obj2gltf.

this model was showing collectly with texture in desktop browsers but mobile browser was not them.

**Comment by lilleyse** [comment]
The texture on this model is pretty large, 8192 x 4096 pixels. On http://webglreport.com/ check for `Max Texture Size`. It's possible the mobile device has a limit of 4096 or smaller. To fix this try scaling down the texture.
