### ISSUE TITLE
Whether I can load a tile map based on a custom resolution

### ISSUE THREAD

**Issue by LiuYP208** [AnalyticalGraphicsInc/cesium#5429]
In the project, I have a product layer, which is based on  a resolution like [0.625, 0.3125, 0.15625, 0.078125, 0.0390625, 0.01953125, 0.009765625, 0.0048828125, 0.00244140625]，not the default resolution（[0.70312500000000,...]）。I want to load it in the 3D mode.
I tried to  load it by createTileMapServiceImageryProvider  and change the “units-per-pixel” Property in the  file:“ tilemapresource.xml，but it seems didn't work。
so I want to know whether I can load it？if I can ,what should I do？

**Comment by hpinkos** [comment]
Hello @LiuYP208,  Please ask questions like this on [our forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev).  We use GitHub exclusively for bug tracking and planning new features.  The forum reaches many more people, so it is more likely that someone will see your question and be able to help.   Thanks!

**Comment by LiuYP208** [comment]
SORRY THAT BECAUSE OF INTERNET REASON ,IT'S VERY HARD FOR ME  TO CONNECT  TO THE GOOGLE NET......

**Comment by mramato** [comment]
@LiuYP208 I totally understand that parts of the world do not have access to Google services.  To answer your question, what you are describing is actually a custom tiling scheme and very non-standard.  If you would like to view your map data in Cesium, you would have to implement your own `TilingScheme` class (see https://cesiumjs.org/Cesium/Build/Documentation/TilingScheme.html) and then pass your class as an option to `createTileMapServiceImageryProvider`  see (https://cesiumjs.org/Cesium/Build/Documentation/createTileMapServiceImageryProvider.html?classFilter=TileM#createTileMapServiceImageryProvider)

I'm sorry that we don't have any good code examples on exactly how to do this; but hopefully the documentation will be enough.

**Comment by LiuYP208** [comment]
Thank you very  much for both understand and Technical support!! I will try  to write code according to the documentation you provided!
