### ISSUE TITLE
Cesium tests broken in Chrome

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5430]
Chrome  59 deleted `initDeviceOrientationEvent` because they are non standard and have newer equivalents.  We need to update `DomEventSimulator` to account for this.

> Remove non-standard DeviceOrientation Event initialization functions
> 
> For some time now there's been a general trend in browser APIs away from initialization functions and toward object constructors. The most recent version of the DeviceOrientation Event Specification follows this trend by requiring constructors for both DeviceOrientationEvent and DeviceMotionEvent.
> 
> Since Chrome is enabling these constructors by default in Chrome 59 the legacy initialization fuctions, initDeviceMotionEvent() and initDeviceOrientationEvent() are also removed. Edge has deprecated the initialization functions and Firefox has already shipped the constructors.

See https://developers.google.com/web/updates/2017/04/chrome-59-deprecations for full details.

**Comment by pjcozzi** [comment]
Any takers for the code sprint next week?
