### ISSUE TITLE
Plane not normalized bug

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5439]
This simple follow-camera example worked in previous releases, but is now broken. The problem seems to be that CullingVolume is passed unnormalized planes at some point. @mramato 

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=1c5e7894a4da621935504540bb8aef40

**Comment by mramato** [comment]
This exception is because of #5304.  The code in the Sandcastle example is most likely not the culprit, it looks like `CullingVolume.prototype.computeVisibility` is using an unnormalized plane, but I need to trace exactly where it's coming from.

**Comment by mramato** [comment]
Talked to @bagnell, we figured out the problem.  I'll have a PR open later tonight.
