### ISSUE TITLE
3D Tiles - Trailing spaces after featureTableJSON in .pnts file

### ISSUE THREAD

**Issue by waldanbridger** [AnalyticalGraphicsInc/cesium#5444]
A point cloud is displayed only if there are some spaces after closing bracket of featureTableJSON string.
Tested on the 'cube' point cloud from the 3d-tiles-samples/TilesetWithExpiration repo. It works only if there are exactly 3 spaces after JSON.

**Comment by lilleyse** [comment]
The spaces there are added for padding purposes. More details here: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/FeatureTable#implementation-notes

We also plan on clarifying this better in the spec.
