### ISSUE TITLE
More eslint improvements

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5449]
@omh1280 here's some low hanging fruit after you are done with #5431

* Enable --cache argument for all eslint usage: http://eslint.org/blog/2015/09/eslint-v1.4.0-released
* Remove `/*global define*/` from all Cesium source files, as it will no longer be needed.
* Make `defineSuite` a global in Cesium tests and remove `/*global defineSuite*/` from all specs.
* Expand coding guide to discuss `eslint-config-cesium` and preference for single like rule disabling.

**Comment by omh1280** [comment]
- [ ] remove `.jshintrc` files, and other associated jshint functions (in `gulpfile.js` for example)

**Comment by omh1280** [comment]
https://github.com/adametry/gulp-eslint/issues/132

**Comment by mramato** [comment]
@omh1280 I know we talked a little bit about that link offline, but always provide some contents to posts like that so other developers (or ourselves in the future) have the required context for it.  Cesium is developed out in the open.

Also, I think the easy solution in this case is to run eslint via a child process instead of through gulp, then we can use the cache argument.  Look at `generateDocumentation` in the gulpfile for an example.

**Comment by omh1280** [comment]
@mramato Is it time to remove `/*global define*/`s and `/*global defineSuite*/`s?

**Comment by mramato** [comment]
Go for it.  Now that 3d-tiles is in master, it shouldn't conflict with other branches
