### ISSUE TITLE
Polyline dashes don't play nice with CallbackProperty

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5450]
When using `CallbackProperty`, the polyline dashes are always shown horizontally, even if the line is mostly vertical in screen space.

Here's a [demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=5f1f68fe618ae46774a52c02b7819833).  Try moving the camera around to see how the dashes behave at different orientations.  The light blue line behaves the usual way, with the dashes facing the most prominent direction of the line.  But the yellow line always cuts the dashes horizontally, regardless of the screen-space direction of the line.

/cc @AnneWoepse

```
var viewer = new Cesium.Viewer('cesiumContainer');

var redLine = viewer.entities.add({
    name : 'Yellow dashed line',
    polyline : {
        positions : new Cesium.CallbackProperty(() => {
        return Cesium.Cartesian3.fromDegreesArrayHeights([-95, 50, 250000,
                                                        -95, 30, 250000]);
        }, false),
        width : 8,
        material : new Cesium.PolylineDashMaterialProperty({
            color: Cesium.Color.YELLOW
        })
    }
});

var blueLine = viewer.entities.add({
    name : 'Blue dashed line',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights([-98, 50, 250000,
                                                        -98, 30, 250000]),
        width : 8,
        material : new Cesium.PolylineDashMaterialProperty({
            color: Cesium.Color.LIGHTSKYBLUE
        })
    }
});


viewer.zoomTo(viewer.entities);
```

![polylinedashproblem2](https://user-images.githubusercontent.com/1235080/26983509-07335ed6-4d0a-11e7-9a6b-5bb7b3c44f75.gif)

**Comment by hpinkos** [comment]
Could no longer reproduce
