### ISSUE TITLE
Update feature demos and demos in README.md to match cesiumjs.org demos

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5468]
Update

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/README.md#featured-demos

to match

http://cesiumjs.org/demos.html

CC @slchow

**Comment by slchow** [comment]
Also need to remove ".html" from all addresses so links work.

**Comment by pjcozzi** [comment]
Fixed in #5834.
