### ISSUE TITLE
Picking and drill-picking don't work after rotating the globe

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5478]
If you spin the globe to the opposite side (Australia, for example) and then come back to the US, picking and drill-picking stop working correctly.

Picking:

![pickingproblem](https://user-images.githubusercontent.com/1235080/27202271-ee5f96f6-51ee-11e7-88fe-25041568d0b1.gif)

And also, drill-picking:

![drillpickproblem](https://user-images.githubusercontent.com/1235080/27202280-f91b2312-51ee-11e7-80b9-65f7b6dec80b.gif)

/cc @AnneWoepse

**Comment by emackey** [comment]
At least one team internally considers this high-priority.

**Comment by mramato** [comment]
This probably has the same root cause as #5402

**Comment by emackey** [comment]
`git bisect` says the first bad commit is a9a275f8e6286ae509633d00cc622d195ad4e29b.

**Comment by emackey** [comment]
Turns out there was nothing magical about Australia that would cause Cesium to freak out just by looking at it.  I was debugging this problem in the summer, in the US, during the daytime, so, viewing Australia caused the Sun to become visible in the frame behind the Earth.  The picking framebuffer got reassigned to the sun bloom post-process effect when this happened, and picking broke.
