### ISSUE TITLE
Multliple `for` loops and block scoping

### ISSUE THREAD

**Issue by omh1280** [AnalyticalGraphicsInc/cesium#5491]
I am in the process of enabling proposed ESLint rules (#5456). [`block-scoped-var`](http://eslint.org/docs/rules/block-scoped-var) has 160 errors, the large majority of which look like:

```
  258:14  error  'i' used outside of binding context  block-scoped-var
  258:21  error  'i' used outside of binding context  block-scoped-var
  258:39  error  'i' used outside of binding context  block-scoped-var
  259:29  error  'i' used outside of binding context  block-scoped-var
```

These come from functions like https://github.com/omh1280/cesium/blob/master/Source/Core/Tipsify.js#L125, which contain multiple `for` loops and re-use the variable `i` or `j`. 

Which of these solutions makes the most sense to have as a standard?
- Always use unique loop indexes within a function (`i`, `j`, `k`,...)
- Declare the index at the function-level scope prior to its first use. (E.g. saying `var i` right before a `for` loop)
- Something else?

I'll make a PR with the changes as soon as we agree on a standard. Thanks!

**Comment by pjcozzi** [comment]
Either is OK with me, but separate variables is probably more textbook as it reduces the "span" of a variable, at least in block-scoped languages.
