### ISSUE TITLE
3D Tiles - Targeted Sancastle demos

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5506]
https://github.com/AnalyticalGraphicsInc/cesium/pull/5308#issuecomment-303176700

>For discoverability, let's create the following Sandcastle examples:
>
>3D Tiles - Photogrammetry
>3D Tiles - CAD
>With an indoor and outdoor example
>3D Tiles - Point Clouds
>These can be pretty simple examples with data from cesium.com, and will supplement the other examples.
>

* [ ] Targeted Sandcastle demos
* [ ] Improve or remove existing dev Sandcastle demos: https://github.com/AnalyticalGraphicsInc/cesium/pull/5308#issuecomment-305783824

**Comment by lilleyse** [comment]
Also include a city/pickable buildings type demo.

**Comment by mramato** [comment]
> Also include a city/pickable buildings type demo.

We could use the NYC data for this, I also think it's important to show off this type of dataset because of styling.

**Comment by pjcozzi** [comment]
The current "3D Tiles Batch Table Hierarchy" Sandcastle example reports:

> This tile uses a lowercase refine "add". Instead use "ADD".

**Comment by pjcozzi** [comment]
Same comment for other 3D Tiles Sandcastle examples.

**Comment by pjcozzi** [comment]
Also at least some of the 3D Tiles Sandcastle examples should be labeled "Showcases" so they show up in the default tab.
