### ISSUE TITLE
3D Tiles - Cleanup traversal code

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5507]
Cleanup the traversal code based on comments in #5308. This will include work to make Cesium3DTile and similar files as small as possible.

https://github.com/AnalyticalGraphicsInc/cesium/pull/5308#pullrequestreview-39712440
https://github.com/AnalyticalGraphicsInc/cesium/pull/5308#discussion_r117968456

**Comment by lilleyse** [comment]
As part of this, also improve doc and prototype function checking for private functions and private classes.

**Comment by pjcozzi** [comment]
@lilleyse have recent refactors fixed this?

**Comment by lilleyse** [comment]
For the most part they have. `Cesium3DTile` still has a lot of properties but there isn't really any action to take now.
