### ISSUE TITLE
Forum check when an issue is closed

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5516]
Somewhat related to #5489, it would be handy for a bot to check issues when they are closed to scan the comments and extract all the unique links to Cesium forum, and then comment @mentioning the user who closed the issue asking if they remembered to update the forum threads.  The bot could even suggested the text like:

> Issue xyz was just merged and will ship in ("the next version of Cesium next month" / "precise Cesium version and release date if you are an overachiever").  Thanks to [name of person who opened PR]!

Maybe also do this for PRs, but it would be less commonly useful.

CC @omh1280 @mramato

**Comment by omh1280** [comment]
Can I expand this to simply check for certain keywords (like "forum")? A quick search shows only ~5 issues in the past year which link to the cesium forum. And issues like #5451 link neither to the cesium forum nor the google group.

**Comment by hpinkos** [comment]
I always linked directly to the google group

**Comment by omh1280** [comment]
On second thought, I could just start with searching for the cesium forum and the google group. If that's not enough, we can expand the search.

**Comment by omh1280** [comment]
@pjcozzi [GitHub Webhooks](https://developer.github.com/webhooks/) require a public server to contact when events occur. I have no problem setting up a server in Node, but how should I make it publicly accessible to Github?

(We can use secrets to prevent malicious requests to the server)

**Comment by pjcozzi** [comment]
I dunno.

@mramato?

**Comment by omh1280** [comment]
I've found https://www.heroku.com/, and have successfully implemented GitHub webhooks with a test repo https://github.com/omh1280/forum-reminder/issues/2.

**Comment by mramato** [comment]
@omh1280 it's not a question of what or how we would deploy.  It's a question of running and maintaining (and paying) for a server just so we can use git hooks and what that means in the context of any other infrastructure we need to maintain as part of the project.  @pjcozzi let's talk offline when you're back in the office.

**Comment by pjcozzi** [comment]
Send me an email to start the conversation so I don't stall you guys.

**Comment by pjcozzi** [comment]
Fixed by https://github.com/AnalyticalGraphicsInc/cesium-concierge
