### ISSUE TITLE
WebGL error displaying bounding volumes when using regions

### ISSUE THREAD

**Issue by Prior99** [AnalyticalGraphicsInc/cesium#5519]
**Problem:**

I am trying to debug a `tileset.json` I generated. I am using regions instead of spheres or boxes and it works fine, but when I try to enable displaying of bounding boxes I am getting the following error:

```
[.Offscreen-For-WebGL-0x30d53fdee00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 4
WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Example region:**

The `tileset.json` is very big (>10MB), but a n example region looks like this:

```
{
    "region": [-1.680111719624372, 0.53360849538126576, -1.680111352014404, 0.53360812210272279, 0, 1000]
}
```
Could this be a bug with cesium or did I do something wrong with my `tileset.json`?

Please let me know if you need any additional information from me.

**Information about my system:**

```
$ chromium --version
Chromium 59.0.3071.86
$ uname -a
Linux auenland 4.11.4-1-ARCH #1 SMP PREEMPT Fri Jun 9 07:46:48 CEST 2017 x86_64 GNU/Linux
$ lspci -v | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X] (prog-if 00 [VGA controller])
```

**Comment by lilleyse** [comment]
With region being [west, south, east, north, minHeight, maxHeight], your south is greater than your north. After flipping the two the region is drawn correctly (though very small).

<img width="362" alt="small-region" src="https://user-images.githubusercontent.com/915398/27395022-4ff86852-567c-11e7-9b6c-b0b78011d0a2.PNG">

**Comment by Prior99** [comment]
Thank you. That fixed it.
