### ISSUE TITLE
Sandcastle doesn't work in Firefox 54?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5521]
Maybe I'm doing something wrong.

Using Firefox 54 with a clear cache on Windows/NVIDIA, and the latest Cesium master or 1.34 release, I get the following:

![image](https://user-images.githubusercontent.com/782098/27408095-1b69542a-56a9-11e7-91f1-56dd4d584aeb.png)

Perhaps a new Firefox issue?

Sandcastle works in Chrome and Cesium Viewer works in Firefox.

**Comment by mramato** [comment]
Works fine for me.

**Comment by GatorScott** [comment]
I just upgraded and see this in the console:
`An error occurred in "BingMapsImageryProvider": An error occurred while accessing https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?incl=ImageryProviders&key=AsarFiDvISunWhi137V7l5Bu80baB73npU98oTyjqKOb7NbrkiuBPZfDxgXTrGtQ.`

**Comment by GatorScott** [comment]
and this in the Developer console:
![image](https://user-images.githubusercontent.com/4126790/27408708-fc079896-56ab-11e7-8f60-ae27e5acd2e7.png)

**Comment by GatorScott** [comment]
On Windows with ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)

**Comment by GatorScott** [comment]
And on Windows with ANGLE (NVIDIA Quadro M1000M Direct3D11 vs_5_0 ps_5_0)

**Comment by lilleyse** [comment]
I see the same thing as @GatorScott.

**Comment by burn123** [comment]
This seems to still be a problem in 1.36. I see this message in the Sandcastle in the dev tools console

![image](https://user-images.githubusercontent.com/2721458/28494786-7cc89d46-6f06-11e7-8cd8-2b823a5059b6.png)

**Comment by mramato** [comment]
Are you guys using 32 or 64 bit?  This continues to work for me without any problems.  54.0.1, 64-bit, Windows 10, Nvidia 650ti

**Comment by GatorScott** [comment]
No change for me on Win32 ANGLE (NVIDIA Quadro M1000M Direct3D11 vs_5_0 ps_5_0).  Result is no globe.

**Comment by GatorScott** [comment]
Turns out that Firefox doesn't like Microsoft's certificate.  Adding an exception to trust Bing Maps makes the globe visible.  The other TypeErrors and Error remain.

**Comment by pjcozzi** [comment]
Works OK on Mac Firefox on my home network.

**Comment by burn123** [comment]
I'm using 32-bit, 54.0.1, Windows 10, Nvidia 980M. I thought I was on 64 bit, but I guess not
