### ISSUE TITLE
Model textures broken in master

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5528]
Notice anything strange about this model 😄 

![image](https://user-images.githubusercontent.com/1495196/27458874-3ef00562-5779-11e7-9f24-37fa24fdde5a.png)

If not, look at the propellers.  Most likely caused by unexpected changes from 3d-tiles.

Someone should look at this ASAP.

**Comment by emackey** [comment]
3D Tiles maybe not to blame...??

`git bisect` claims the first bad commit is 2981035fedf90f8.

**Comment by pjcozzi** [comment]
Thanks for tracking this down @emackey!
