### ISSUE TITLE
Canvas blink when adding a label after loading the imagery

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5537]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/y4EPthqm_d8

"When setting a tileLoadProgressEvent and adding a label once all the imagery tiles are loaded, the canvas "blinks" (turns black for a moment)"

Code example:
 http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=cf1d71eefb161f3f3546ad4e3d488423

Apparently this began with 1.33

@bagnell @emackey

**Comment by mramato** [comment]
We should at least figure out what's causing this.  I think @bagnell looked into it and said he thought it was a driver bug, but if it only started with 1.33, it's probably not.

**Comment by emackey** [comment]
This didn't start with 1.33.  On my machine I can reproduce as far back as Cesium 1.15 (I stopped there only because I didn't want to get ant builds going again).

Maybe this wasn't noticed before, or possibly it was introduced by a driver or browser upgrade.

**Comment by mramato** [comment]
That certainly lends credence to the idea that this is a driver bug (it happens in multiple browsers so I don't think that's it).

**Comment by emackey** [comment]
Yeah.  I haven't manually updated my drivers in quite a while.  Maybe an auto-update pushed something there.

**Comment by pjcozzi** [comment]
Removed `priority - next release` label; there's not enough bandwidth to look at this for the 1.35 release and it does not seem prominent enough.

**Comment by pjcozzi** [comment]
Also happens with "Sample Evert Terrain at Level 9" in the [Terrain Sandcastle example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain.html&label=Showcases).

I get this on Windows/NVIDIA and Mac/Intel - and Chrome and IE.  Other than Cesium, I don't know what the common thread would be, it is not the driver, browser, ANGLE, etc.  But we would have noticed this since Cesium 1.15...

**Comment by emackey** [comment]
I messed this one up.  I had clicked the link and was loading Sandcastle off cesiumjs.org, not my local build.  Ouch.  Running a new bisect now...

**Comment by emackey** [comment]
OK.  Now that I'm actually testing the code I'm building, it's easier to track down.  Amazing.

So, git bisect reports to me a commit that seems very familiar.  It's the same scissor test change that caused two other bugs recently.  a9a275f8e6286a

**Comment by pjcozzi** [comment]
@emackey nice detective work.

@bagnell perhaps this is low-hanging fruit with inconsistent render state / framebuffer for a frame?
