### ISSUE TITLE
PolylineCollection limited to 16384

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5538]
Reported on the forum: https://groups.google.com/d/msg/cesium-dev/exLJc20nQpI/6S_Kxs6pBQAJ

When adding large numbers of elements to a polyline collection, only the first 16384 show up.

Here's an example (should make a full circle): 
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=758939a9dea1f6f5bf4d14617d55fe6a

**Comment by fcayre** [comment]
I tried to debug that one unsuccessfully until now. However I noticed:
* this error in the console when the number of polylines is 20000 for instance: "bound vertex attribute buffers do not have sufficient size for given indices from the bound element array"; this error does not show up for a lower number of polylines (2000 for instance); so the vertex indices and position buffers do not match
* when using an even greater number of polylines (100 000 for instance), only the last polylines do not show up, as if only the last polylines' bucket (as they are named in the code) was not displayed but hte others were.

I would greatly appreciate an idea to debug that, specific tools or debug options you might suggest, ...

**Comment by fcayre** [comment]
OK we finally spotted an offset in the polyline indices buckets, a pull request should be submitted soon.

**Comment by hpinkos** [comment]
Appears to be fixed 

![image](https://user-images.githubusercontent.com/3451886/65269063-6d253900-dae6-11e9-89cf-4a763509c213.png)

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/exLJc20nQpI/6S_Kxs6pBQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/5538 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
