### ISSUE TITLE
Create `Check.typeOf.number.equals`

### ISSUE THREAD

**Issue by omh1280** [AnalyticalGraphicsInc/cesium#5554]
As we move away from throwing `DeveloperError`s in favor of `Check` (#4794), there are cases where two numbers are compared for equality: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/CatmullRomSpline.js#L161, https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/LinearSpline.js#L65

Please add a function, `Check.typeOf.number.equals`, which takes two names and two values, checks if the values are numbers, and checks if they are equal. If not, throw a `DeveloperError` with  a description similar to:

`'times.length must be equal to points.length.'`

/cc @Rudraksha20

**Comment by hpinkos** [comment]
Added in #5555
