### ISSUE TITLE
viewer.flyTo on billboards breaks zoom limits

### ISSUE THREAD

**Issue by burn123** [AnalyticalGraphicsInc/cesium#5573]
I feel like this may have been mentioned before, but the `flyTo` method doesn't respect the zoom limits. For my case particularly it is zooming in way closer than the desired max zoom for billboards, but I'm guessing it isn't limited to that.

In addition, if you fly to a billboard, it seems to break the max zoom, because after that, you can zoom to any zoom level in both 2D and 3D, and it won't restrict you. It doesn't break the min zoom, so you can't zoom out infinitely, but you can seemingly zoom in infinitely

**Comment by pjcozzi** [comment]
Thanks for the report, @burn123.  Do you have a minimal code example to reproduce this?

**Comment by burn123** [comment]
[Here is a basic example. ](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=ed3234a33a2205870d2de08d3ef6403b)
In our app, it was on a marker/billboard, so it allowed us to then be able to zoom to any zoom level. In the example, it seems that it then changes how zoomed in you can be to wherever it flew

**Comment by pjcozzi** [comment]
Thanks for the prompt response!

**Comment by burn123** [comment]
I realized that the code example I gave didn't actually contain the code that shows it is broken.
[This is an updated example.](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=5877523ea1ccd20f90efa0519ab14a36) Sorry it is on MOUSE_MOVE, for some reason the click handler wouldn't fire.

**Comment by burn123** [comment]
I traced the issue some, and I realized that part of the problem, specifically why the minimum zoom is broken, is [this line of Viewer.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/Viewer/Viewer.js#L1918):

    controller.minimumZoomDistance = Math.min(controller.minimumZoomDistance, boundingSphere.radius * 0.5);

I'm not sure why the minimum zoom would be updated programmatically, because this should be something left up to the user in my opinion. Also, `maximumZoomDistance` is never updated in this way, which makes me think that this was some code that was useful at one point, but no longer is, and wasn't removed properly.
