### ISSUE TITLE
A corridor clamped to ground with same coordinate triggers a Developer error

### ISSUE THREAD

**Issue by oterral** [AnalyticalGraphicsInc/cesium#5580]
Trying to display this KML file a developer error appears:

KML:
```
<?xml version="1.0"?>
<kml xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Document>
    <name>Thomas Ulrich</name>
    <description>Exported(UTC) 20170703 12:20:03; 20170703-20170703</description>
    <Style id="LSgrounded1">
      <LineStyle>
        <color>FFC005FE</color>
        <colorMode>normal</colorMode>
        <width>1</width>
      </LineStyle>
    </Style>
    <Placemark id="PM_ground_P1_1_184_816558135">
      <name>06:21:39 - 06:26:38</name>
      <styleUrl>LSgrounded1</styleUrl>
      <LineString>
        <tessellate>1</tessellate>
        <altitudeMode>clampToGround</altitudeMode>
        <coordinates>6.181617,46.583332,1120 6.181617,46.583332,1121 6.181633,46.583332,1121</coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>
```

Error:
```
normalized result is not a number
Error
    at new DeveloperError (createGeometry.js:91)
    at Function.Cartesian3.normalize (createGeometry.js:1760)
    at Object.CorridorGeometryLibrary.computePositions (createCorridorGeometry.js:23739)
    at computePositionsExtruded (createCorridorGeometry.js:26422)
    at Function.CorridorGeometry.createGeometry (createCorridorGeometry.js:26838)
    at createCorridorGeometry (createCorridorGeometry.js:26911)
    at createGeometry (createGeometry.js:19650)
    at createGeometry.js:19537
```

Problem comes from the 2nd coordinate which is the same coordinates as the first but we a different z .
If I set the altitudeMode to absolute it works. But when set to clamp to ground.

Same positions are supposed to be removed [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/7213d4d25e02deab085448250c5dca966f1dbfcc/Source/Core/CorridorGeometry.js#L968) but when clamped to ground the position become the same  [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/7213d4d25e02deab085448250c5dca966f1dbfcc/Source/Core/CorridorGeometryLibrary.js#L170) then it results a division by zero error [there](https://github.com/AnalyticalGraphicsInc/cesium/blob/7213d4d25e02deab085448250c5dca966f1dbfcc/Source/Core/CorridorGeometryLibrary.js#L190)

**Comment by hpinkos** [comment]
Thanks for reporting this @oterral

**Comment by hpinkos** [comment]
No longer crashes
