### ISSUE TITLE
OrthographicFrustum missing from documentation

### ISSUE THREAD

**Issue by slozier** [AnalyticalGraphicsInc/cesium#5586]
OrthographicFrustum is missing from the documentation. I see that `@alias OrthographicFrustum` got changed (#5021) to `@alias OrthographicOffCenterFrustum` so the documentation got merged with OrthographicOffCenterFrustum. Was this on purpose? This creates duplicate near/far entries in the [OrthographicOffCenterFrustum documentation](https://cesiumjs.org/Cesium/Build/Documentation/OrthographicOffCenterFrustum.html#far).

Also the example code in OrthographicFrustum.js got changed to use OrthographicOffCenterFrustum instead of OrthographicFrustum.

**Comment by mramato** [comment]
Thanks for the report, this is definitely a doc bug.  We're happy to take a PR to fix this.
