### ISSUE TITLE
Node 1.35 package broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5588]
I'm not sure what happened, but the Node package for 1.35 is broken, it looks like it's missing some files and has extra files that shouldn't be included.

It's possible something in our build steps changed and this is my fault, but we should fix it either way.  I'll get on it and we'll publish a 1.35.1

**Comment by pjcozzi** [comment]
Good eye, thanks!

**Comment by mramato** [comment]
Well, not so much my eye as much as all of our other projects starting to fail on travis 😉 

I __think__ what happened is that `npm publish` was ran from the unpacked zip file and not the git source tree.  Since the unpacked zipfile does not have the `.npmignore` or `index.js` files, this means the wrong fileset was published.

In reality, we should probably make it so that we can run npm publish from the zipfile since that is the canonical source of the release.

**Comment by mramato** [comment]
I unpublished `1.35.0` and published an npm-only 1.35.1 release.  I'll open a separate PR to make the change I describe above, but we're good to go for now.

**Comment by pjcozzi** [comment]
Yes, it's possible I ran `npm publish` from the unzipped directory.
