### ISSUE TITLE
Dynamic changing of volume extruded height does not work anymore

### ISSUE THREAD

**Issue by YvesE** [AnalyticalGraphicsInc/cesium#5590]
Changing volume extruded height was working on CesiumJS version 1.22.1 and no more with version 1.34 nor 1.35.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var dataSource;

viewer.dataSources.removeAll();
//Seed the random number generator for repeatable results.
Cesium.Math.setRandomNumberSeed(0);

dataSource = new Cesium.GeoJsonDataSource();
var promise = dataSource.load('../../SampleData/ne_10m_us_states.topojson');
promise.then(function(dataSource) {
    viewer.dataSources.add(dataSource);
    //Get the array of entities
    var entities = dataSource.entities.values;

    var colorHash = {};
    for (var i = 0; i < entities.length; i++) {
        //For each entity, create a random color based on the state name.
        //Some states have multiple entities, so we store the color in a
        //hash so that we use the same color for the entire state.
        var entity = entities[i];
        var name = entity.name;
        var color = colorHash[name];
        if (!color) {
            color = Cesium.Color.fromRandom({
                alpha : 1.0
            });
            colorHash[name] = color;
        }

        //Set the polygon material to our random color.
        entity.polygon.material = color;
        
        //Remove the outlines.
        //entity.polygon.outline = false;
        
        //Extrude the polygon based on the state's population.  Each entity
        //stores the properties for the GeoJSON feature it was created from
        //Since the population is a huge number, we divide by 50.
        entity.polygon.extrudedHeight = entity.properties.Population / 50.0;
    }
}).otherwise(function(error){
    //Display any errrors encountered while loading.
    window.alert(error);
});

Sandcastle.addToolbarButton('Toggle volume', function() {
//Get the array of entities
var entities = dataSource.entities.values;

    dataSource.entities.suspendEvents();
    for (var i = 0; i < entities.length; i++) {
        var entity = entities[i];
        //entity.polygon.height = 0;
        if (entity.polygon.extrudedHeight === undefined) {
            entity.polygon.extrudedHeight = entity.properties.Population / 50.0;
        } else {
            entity.polygon.extrudedHeight = undefined;
        }
    }
    dataSource.entities.resumeEvents();
    //dataSource.changedEvent.raiseEvent();
    //dataSource.entities.collectionChanged.raiseEvent(dataSource.entities, null, null, dataSource.entities.values);
});
```

**Comment by hpinkos** [comment]
Hello @YvesE, this example still works for me.  Did you try clearing your cache/cookies? Sometimes that causes weird side effects when switching between versions of Cesium.  Otherwise, what browser and OS are you using?

**Comment by YvesE** [comment]
Hi, I try cleaning cache and cookies but same results.
I am running Windows 7 Enterprise and Firefox ESR 45.7.0. Unfortunately, I cannot upgrade it because it is the company settings.
Regards

De : Hannah [mailto:notifications@github.com]
Envoyé : jeudi 6 juillet 2017 14:23
À : AnalyticalGraphicsInc/cesium
Cc : ERNOTTE Yves; Mention
Objet : Re: [AnalyticalGraphicsInc/cesium] Dynamic changing of volume extruded height does not work anymore (#5590)


Hello @YvesE<https://github.com/yvese>, this example still works for me. Did you try clearing your cache/cookies? Sometimes that causes weird side effects when switching between versions of Cesium. Otherwise, what browser and OS are you using?

**Comment by hpinkos** [comment]
Thanks @YvesE, I just re-ran the example on Windows 7 in Firefox and it worked the same in 1.35 as it does in 1.22.  Here's a link to the example I was testing with: http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=cde1b3afdad8a86a80c0ad82bc7a37c2

What happens when you click the 'Toggle volume' button?

**Comment by YvesE** [comment]
Thanks Hannah. Your example is also running on my side. But when I add the Sandcastle.reset function as in my example, it does not work. Sandcastle.reset function without viewer.dataSources.removeAll(); works.

In fact, I was trying to show a problem in a more complex code not using Sandcastle. You have demonstrate that Cesium works as expected, so I shall investigate more on my side.
Thanks again for your help.

De : Hannah [mailto:notifications@github.com]
Envoyé : jeudi 6 juillet 2017 15:09
À : AnalyticalGraphicsInc/cesium
Cc : ERNOTTE Yves; Mention
Objet : Re: [AnalyticalGraphicsInc/cesium] Dynamic changing of volume extruded height does not work anymore (#5590)


Thanks @YvesE<https://github.com/yvese>, I just re-ran the example on Windows 7 in Firefox and it worked the same in 1.35 as it does in 1.22. Here's a link to the example I was testing with: http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=cde1b3afdad8a86a80c0ad82bc7a37c2

What happens when you click the 'Toggle volume' button?

**Comment by hpinkos** [comment]
No problem!  If you need help, feel free to ask questions on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
