### ISSUE TITLE
Duplicate debug properties in Cesium3DTileset

### ISSUE THREAD

**Issue by slozier** [AnalyticalGraphicsInc/cesium#5594]
The debug properties appear to be duplicated in Cesium3DTileset.js. I would have submitted a PR however the comments for the properties are slightly different so I'm not sure which version is the latest one.

**Comment by lilleyse** [comment]
I just noticed this earlier today and fixed it here: https://github.com/AnalyticalGraphicsInc/cesium/pull/5592

**Comment by hanbollar** [comment]
@lilleyse is this issue okay with being closed?

**Comment by lilleyse** [comment]
Yes
