### ISSUE TITLE
Fix for Point Cloud show style

### ISSUE THREAD

**Issue by sir-chaos** [AnalyticalGraphicsInc/cesium#5598]
In PointCloud3DTileContent.js, in line executing when a "show" style parameter is defined to hide points with show == false, there might be incorrect nullification of gl_Position, which in fact does not remove the point. I suggest it was meant to nullify gl_PointSize instead (which effectively hides the point).
Link to the line in code (just change the variable):
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/PointCloud3DTileContent.js#L1025
(actual for commit 337ad9d)

**Comment by lilleyse** [comment]
Setting `gl_Position *= 0.0` should discard the point properly. The resulting NDC position will be outside the [1, 1, 1] to [-1, -1, -1] NDC-space cube and the GPU will cull the point. Whether its bad for the NDC position to be [infinity, infinity, infinity] is a different question, but we use this trick throughout the code base, though I suppose it's less relevant for points.

For clarity sake I would be ok with changing it to `gl_PointSize = 0`. Feel free to open a PR.

Semi related post here: https://stackoverflow.com/a/33970293

**Comment by sir-chaos** [comment]
Thank you for your response!
I will revisit this issue with a PR shortly, but anyway I must point out that for some reason in my case the present code leads to a single ugly point in the center of the screen instead of discard (obviously at [0,0,x]). I think this is subject to some investigation and would appreciate if someone could verify that.

**Comment by lilleyse** [comment]
Ok that's interesting, I don't see that but it is worth the fix.

Do you also see a stray point when show is false for non point-cloud tilesets? Like for this example: http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=e79e2d6547c4c5a017372e8a91776769

**Comment by sir-chaos** [comment]
Non point-cloud tilesets seem OK. For sand castle the issue reproduced, try inserting 
`    tileset.style = new Cesium.Cesium3DTileStyle({show: "${POSITION}.x > 10.0"})`
line somewhere (The point might be tricky to see but it is definitely there)

**Comment by lilleyse** [comment]
I've tried a similar setup here and don't see a point: http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=2fdd2a88b3bce29db2f51515c08a5d79

This inconsistency is probably explained by hardware or driver differences.

**Comment by sir-chaos** [comment]
In the last example the point is very distinct for me.
Created pull request https://github.com/AnalyticalGraphicsInc/cesium/pull/5599

**Comment by hpinkos** [comment]
Fixed in #5599
