### ISSUE TITLE
Support different heightReferences per entity in KmlDataSource

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5600]
Came up in the forum today: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/8RrBo6eVaSg

Would be nice to support ground clamping for some but not all entities in a KML data source. Currently it seems to be all or nothing.

It seems misleading that we just set polygon.height to 0 when ground clamping option is false for the data source: https://github.com/rahwang/cesium/blob/master/Source/DataSources/KmlDataSource.js#L1231

It shouldn't be too difficult to set a specified height here instead?

**Comment by mramato** [comment]
I'm not sure what's being asked.  KML specifies on a per-feature basis whether the item is clamped to ground or not.  If `clampToGround: true` is specified when loading the KML, we only clamp items that should actually be clamped (not everything).  There are some items Cesium can't clamp do to lack of Cesium features (GroundOverlays with textures for example), these will automatically get clamping as soon as `GroundPrimitive` supports it.

Unless I'm missing something, we should just close this.

**Comment by pjcozzi** [comment]
Agreed.

@rahwang please update the forum.
