### ISSUE TITLE
Documentation generation broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5604]
1. Blow away node_modules and run npm install
2. Run `npm run generateDocumentation`
3. See a litany of errors.

It looks like the latest jsDoc update has breaking changes (or our customizations to it are now leading to breaking changes.

This causes ALL branches to fail, so we should look into fixing this ASAP

**Comment by pjcozzi** [comment]
@ggetz can you please look at this?

@mramato when exactly did this happen?

**Comment by mramato** [comment]
Already fixed with #5605 (@ggetz please test and review).

> when exactly did this happen?

Within the last 24 hours, they release both 3.5.0 and 3.5.1 in that span.

**Comment by pjcozzi** [comment]
Gotcha, thanks!
