### ISSUE TITLE
Cannot read property 'setColor' of undefined

### ISSUE THREAD

**Issue by Kelien** [AnalyticalGraphicsInc/cesium#5607]
When I use  `this._viewer.scene.primitives.add(cesium3DTileset)` , at the time of the mouse on the tileset, using `this._viewer.scene.primitives.remove(cesium3DTileset),`  there will be an error

I use the  `viewer.extend(Cesium.viewerCesium3DTilesInspectorMixin);` in the main function

`Uncaught TypeError: 
    Cannot read property 'setColor' of undefined

    at Cesium3DTileFeature.set (Cesium3DTileFeature.js:91)
    at Cesium3DTilesInspectorViewModel.set (Cesium3DTilesInspectorViewModel.js:979)
    at Cesium3DTilesInspectorViewModel.js:342
    at handleMouseMove (ScreenSpaceEventHandler.js:252)
    at handlePointerMove (ScreenSpaceEventHandler.js:644)
    at HTMLCanvasElement.listener (ScreenSpaceEventHandler.js:67)`

The Cesium3DTileFeature this._content.batchTable is undefined

**Comment by hpinkos** [comment]
Thanks for reporting this @Kelien!  I'm having a little trouble reproducing it though.  Could you please put together a short [Sandcastle example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Inspector.html&label=3D%20Tiles) to reproduce the error?

**Comment by Kelien** [comment]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Inspector.html&label=3D%20Tiles

JS 
var btn = document.getElementById("removeTiles");
btn.onclick=function(){
   viewer.scene.primitives.remove(tileset);
};


html
<button id="removeTiles" style="position:absolute;z-index:1000;top:30px;left:40px;">remove tiles</button>


![qq 20170714091914](https://user-images.githubusercontent.com/15319956/28194243-9635bcc4-6875-11e7-9743-6d7f85a9f9ca.png)


console
Uncaught TypeError: Cannot read property 'setColor' of undefined (on line 91 of http://cesiumjs.org/Cesium/Source/Scene/Cesium3DTileFeature.js)
Uncaught TypeError: Cannot read property 'setColor' of undefined (on line 91 of http://cesiumjs.org/Cesium/Source/Scene/Cesium3DTileFeature.js)
Uncaught TypeError: Cannot read property 'setColor' of undefined (on line 91 of http://cesiumjs.org/Cesium/Source/Scene/Cesium3DTileFeature.js)
Uncaught TypeError: Cannot read property 'setColor' of undefined (on line 91 of http://cesiumjs.org/Cesium/Source/Scene/Cesium3DTileFeature.js)

**Comment by hpinkos** [comment]
Thanks @Kelien, I submitted a fix for this here: #5630

**Comment by Kelien** [comment]
the same problem to Cesium3DTileFeature @hpinkos 
```
Cesium3DTileFeature.js:91 Uncaught TypeError: Cannot read property 'setColor' of undefined
    at Cesium3DTileFeature.set (Cesium3DTileFeature.js:91)
    at SelectTileset.restoreFeatureColor (SelectTileset.js:29)
    at SelectTileset.js:36
    at handleMouseDown (ScreenSpaceEventHandler.js:166)
    at handlePointerDown (ScreenSpaceEventHandler.js:608)
    at HTMLCanvasElement.listener (ScreenSpaceEventHandler.js:67)
```

**Comment by hpinkos** [comment]
Thanks @Kelien, that should be fixed as well.  Feel free to re-open this issue if you're still seeing problem after the next release comes out.

**Comment by Kelien** [comment]
OK，thanks your reply：）

**Comment by KlienCy** [comment]
@hpinkos 
cesium version 1.36
I did not use  `viewer.extend(Cesium.viewerCesium3DTilesInspectorMixin)`
but used ` viewer.scene.pick(position);`
Is still the problem
`Cesium3DTileFeature.js:91 Uncaught TypeError: Cannot read property 'setColor' of undefined`
