### ISSUE TITLE
there is an error when gulp build the source code,though it doesn't matter

### ISSUE THREAD

**Issue by kesai** [AnalyticalGraphicsInc/cesium#5619]
![1](https://user-images.githubusercontent.com/5986940/28105837-e62593f2-6713-11e7-978e-9702831a19c4.jpg)

**Comment by hpinkos** [comment]
Hello @kesai, I believe we fixed this a few days ago in this pull request: #5605 
Feel free to re-open this if you are still experiencing a problem after you pull down master.  Thanks!
