### ISSUE TITLE
drillPick doesn't play well with pickPosition on 3D tilesets

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5622]
In the following code example, I keep getting negative heights when picking tileset features.  It doesn't happen all of the time, but if you move the camera around a little bit it happens within a few clicks.  This does not seem to happen when i use `scene.pick` instead of `pickPosition`.   Also, when the camera is more tilted showing the horizon, sometimes picking stops working entirely.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

viewer.scene.camera.setView({
    destination: Cesium.Cartesian3.fromDegrees(-74.01881302800248, 40.69114333714821, 753),
    orientation: new Cesium.HeadingPitchRoll.fromDegrees(21.27879878293835, -21.34390550872461, 0.0716951918898415),
    endTransform: Cesium.Matrix4.IDENTITY
});

var tileset = scene.primitives.add(new Cesium.Cesium3DTileset({
    url: 'https://beta.cesium.com/api/assets/1461?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkYWJmM2MzNS02OWM5LTQ3OWItYjEyYS0xZmNlODM5ZDNkMTYiLCJpZCI6NDQsImFzc2V0cyI6WzE0NjFdLCJpYXQiOjE0OTkyNjQ3NDN9.vuR75SqPDKcggvUrG_vpx0Av02jdiAxnnB1fNf-9f7s'
}));

var handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(click) {
    var pickedObjects = scene.drillPick(click.position, 10);
    for (var i = 0; i < pickedObjects.length; i++) {
        var pickedObject = pickedObjects[i];
        if (Cesium.defined(pickedObject)) {
            var position = scene.pickPosition(click.position);
            if (Cesium.defined(position)) {
                var cart = Cesium.Ellipsoid.WGS84.cartesianToCartographic(position);
                console.log('Mouse: ' + Cesium.Math.toDegrees(cart.longitude) + ', ' + Cesium.Math.toDegrees(cart.latitude) + ', ' + cart.height);
            }
        }
    }
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

**Comment by hpinkos** [comment]
@lilleyse or @bagnell, do you have any time to look at this?

**Comment by lilleyse** [comment]
This might be the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/4368. Is it definitely just tilesets having this problem?

**Comment by hpinkos** [comment]
Not 100% sure, but I've only been able to reproduce it with tilesets

**Comment by hpinkos** [comment]
@bagnell  to clarify my use case, I have a polyline that follows around the mouse pointer, but I want to click a building in a 3D tileset.  Sometimes using `scene.pick` picks the polyline instead of the building, which is why I want to use `drillpick` to test if one of the things I clicked was a building before calling `pickPosition`.

**Comment by bagnell** [comment]
The problem here is that `pickPosition` uses the depth buffer from the last render. The way `drillPick` works is that it renders, removes what was picked, renders, etc. At the end, there is nothing in the depth buffer for `pickPosition` to find because it was all removed in the `drillPick` renders. The negative heights are from the depth plane that we render so primitives behind the globe are hidden. If you had `depthTestAgainstTerrain` you would get the height from the ellipsoid or from terrain.

A workaround would be to explicitly call `render` after `drillPick`.

**Comment by hpinkos** [comment]
Is there a reason `drillPick` doesn't put everything back after it's finished?

**Comment by emackey** [comment]
We wouldn't want `drillPick` to always re-render the scene if it wasn't going to be needed.  Maybe there could be a flag indicating the depth buffer is dirty after `drillPick`, and in need of re-rendering before other operations that reuse it?

**Comment by bagnell** [comment]
@emackey is right, we could track if it is dirty and re-render before other operations but that is still probably not what you want.

If you render after a `drillPick`, the `pickPosition` will always return the position of the closest thing. You want the position under the mouse of everything returned by `drillPick` right? We could add a function like `drillPick` that returns every object under the mouse along with the position.

**Comment by hpinkos** [comment]
Thanks for the input @bagnell, @emackey!  Calling `scene.render` fixes the problem, and it sounds like we're not going to make any changes in Cesium with regards to this, so I'm going to close this issue.

**Comment by fnicollet** [comment]
Just found this issue after getting stuck for a few hours. Calling viewer.scene.render() after "drillPick" does the trick, but it's just impossible to guess.
If that helps anyone, here is a sandcastle example of the issue:

[Sandcastle reprod](https://sandcastle.cesium.com/#c=lVZtc+I2EP4rKv2AmRIbYwiQSzJNk7TJTEgyB3edm9LpCHvBmsiSR5JJ0pv89678FiBcQvmAbWnf9Oyzu1pRRVYMHkGREyLgkZyDZlnifs3XnGaYf55LYSgToJpt8n0mCP4MKIVL90quWATqqFIMFVADf0rFo2kh4rRm4qX1aSZmovDk6hAEuEsu5+BGkJp4CtqcLVFWm1IJozEqg1zL88gEDDExECaYYZSTkCagaB45MZJwKR8INWRMRUyNodYVHqyUvpcan9LaLIM8p8rgGxWBu1AyuYClAtDOwaDndvzh0A863WGn0+0N26TXcQ9Hvt8LgmDg94Zdv00G/cAeZ83DnWKACJVO1mC8AhoxsbxnJow/S8433HV9tzsYDkbDwbA7CoZBv00OcC3oBaNOv98ZDrq9Q3TXcTsD/3DU90cY2mjY8/u593UoCzhcDcbmzSlTFCGqTORRHW1j0S5E5GvgRzsOU0qBiKaKCr2QKqkTPaZGsaeee31xeTu9nn57TTLikmm4UIzzexY+ICILyjWUkEnxZW3zPKZiCZGVyURofTrQKuPfMvLT+jcae8m9TaiIQqoNB5dG0VQulxx+y4xBQ7MGapCoNkE1eQTOZ432hun27pDaZNYwUvI5VbNGq+ThjaRRTsTbb+dknjFus6uJYRwQ/OKA5ccmEYpHcDEtNp3vJFO8xvJais+gZaZCyBlyplHmOnL6g57fIi9v8p0qlmCuVqDtoZ3SY6uqlqvp+IbIFShOnwkmjehYPmKgZIG1mSkgAvmCpyaJRCCsYBG5Bg55DqZ4bsPSu9LECYlkmCXIirK8LznYL6cZsVVzLbqw6hMuTVNkzXmMCDk/MGv1frDlhpxqfWujPCHNOQ0fIiXT5jsK2jwjAyKm0yLgppACPlZIX1tDk8615JnZQ2sukV+J1el8LMxhYfYT/auZSiawsR7ACtHVzb//x0GQBzbDqNBLn/Y4AmK6VDLDHEkuVQ4zx7XmZp/GPiUmKQ3h0kZ0hbXG7TqSU6SZOSsKtqpcZNTYEmqMjHIS/LMcaVUDgy2Is1HCVZnbnwLkpfhULLwUD8vIFOUg+r2grcYoN8qgLu3am4ukq1pcqzSHBWH7gMItnHI4LWYNlVdrg9AFov3aIWp5DUBiY1J95HlLZuJsjtROvDNB+bNhIeV/KJrGLNTXIvSKEekxrTPQXv+w2/05f0cNG9JB0O33RsHI71TmN85QhOXYYF/aVT+YbAE/fU7BHd99mVz+M777evnaZ6XAUlzlvbqGfq2XkrdpsFphNf62AbVwV/C9i2mezDLYCBZY8pFTW23Vzt5LrRWXywLHzclcreatsB7Va/ZLY3v3gjmXBbM/1qpLu+poFHHW2I/sTLwCtowNOSC7oHGfyS+kWdTex37KrrDT0NN+hgw8GXsxQ3W0NGusA+rGRahHuI7WdmyVAzRv+zb3W1Qot6BiV1n6m0Ntsrs/ONWlxEJnk7VtZbuB7GLx/rXQaDeOc1BPC7x+ZUkqlbED1nFdz0CCPEDmePMMmwmOMJ0HdexVSsc4xQiLThDCzdsuYpcPItxZZJxP2L8wa5weeyi/ocZlfssrE2NFYv/0plh0XffYw8+3WvXlot77Dw)

Click on "use drillPick as well" to see the height of the "pickPosition" change (it gives the height of the ellipsoid instead). 
In the code you can uncomment the "viewer.scene.render()" line to "fix the issue. Still, that's probably not good to call render() on each mouseMove() for instance, so a fix would be nice :)
