### ISSUE TITLE
Pilot GitHub releases for Cesium 1.36

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5629]
For the 1.36 release, let's pilot using the GitHub release feature by uploading the zip and including the CHANGES.md section here:

https://github.com/AnalyticalGraphicsInc/cesium/releases/new

The Cesium website download page could then link to this zip and we will be able to get GitHub release download stats from http://www.somsubhra.com/github-release-stats, which we currently can't get with just tags.

If this goes well, let's
* [x] Update the [Release Guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Release-Guide)
* [x] Put all the past release up there (ordered correctly) so all the zips are in a central location

@tfili has done this before for [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/releases), please chime in with any advice.

**Comment by tfili** [comment]
It's pretty self explanatory. From what I remember it was pretty simple.

**Comment by ggetz** [comment]
+1 This would free up some space in the website repo and speed up the deploy process

**Comment by hpinkos** [comment]
Done https://github.com/AnalyticalGraphicsInc/cesium/releases

**Comment by pjcozzi** [comment]
Very cool!!!
