### ISSUE TITLE
cross color

### ISSUE THREAD

**Issue by KillDragon** [AnalyticalGraphicsInc/cesium#5636]
Render building  by floor in  version 1.35  causes cross color. How it can be fixed.
Thanks in advance.
 

![d](https://user-images.githubusercontent.com/15921876/28254795-c86e9fa2-6ae2-11e7-8f34-13f66a3c6488.jpg)

**Comment by hpinkos** [comment]
Hello @KillDragon,  There currently isn't a way to avoid this kind of z-fighting.  You can try offsetting the surfaces so they're not occupying the same space, or making them slightly transparent.  See the discussion in #4878.  In the future, please ask questions like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev  
Thanks!

**Comment by mramato** [comment]
Adding very slight translucency (0.99) may also fix your issue.

**Comment by KillDragon** [comment]
Thanks for your reply

**Comment by ggetz** [comment]
Hi @KillDragon, you can asks questions in the [Cesium Forum](http://cesiumjs.org/forum.html) to get a response. We use GitHub just for issue tracking.
