### ISSUE TITLE
Occluded Region of Sensors is Broken

### ISSUE THREAD

**Issue by esparano** [AnalyticalGraphicsInc/cesium#5637]
At certain angles, the occluded region of conical sensors looks mostly fine:
![7-17-2017 11-16-18 am](https://user-images.githubusercontent.com/3947139/28275836-ac2022cc-6b04-11e7-8142-bc4270d7ee85.jpg)

However, when viewing the occluded region from the side, the front face of the red occluded region only seems to render where there is another piece of the sensor behind it.  
![7-17-2017 11-16-44 am](https://user-images.githubusercontent.com/3947139/28275931-ecf78cae-6b04-11e7-8420-e724322b2019.jpg)

**Comment by hpinkos** [comment]
Thanks @esparano!  Since sensors are not part of open source Cesium, I opened an issue in our Cesium Pro repository for someone to look into this.

**Comment by pjcozzi** [comment]
@esparano can you please send me your email so we can keep you posted on progress here: email me at pcozzi@agi.com
