### ISSUE TITLE
Polygon entities are missing outlines

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#5642]
See [Sandcastle demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polygon.html) - the blue polygon has outline enabled, but no outline is visible, even if you increase `outlineWidth`.

**Comment by hpinkos** [comment]
Thanks @SunBlack!  We just had a small typo in the word 'height'
I submitted a fix here: #5643
