### ISSUE TITLE
New label appears at position of old label

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5647]
1. Click the `Destroy` button to remove the first label
1. Click the `Label 2` button to add a new label
1.  Zoom in towards the middle of the globe.  Eventually the new label will appear around the spot the old label was, even though the new label has no position

This is specific to labels, it does not happen with billboards.  It also only happens when using the `CLAMP_TO_GROUND` height reference

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

var labelCollection = scene.primitives.add(new Cesium.LabelCollection({
    scene: scene
}));

var label = labelCollection.add({
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
    text: 'label 1',
    position:  new Cesium.Cartesian3(-748060.358557192, -4909764.442609902, 3988488.2144659692)
});

Sandcastle.addToolbarButton('Destroy', function() {
    labelCollection.remove(label);
});

Sandcastle.addToolbarButton('Label 2', function() {
    labelCollection.add({
        heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
        text: 'label 2'
    });
});
```

**Comment by mramato** [comment]
This sounds similar to a billboard bug I fixed in #5339.  My guess is that label caching isn't clearing the clamped state.
