### ISSUE TITLE
Make ClassificationPrimitive highlight translucent geometry

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5659]
From https://github.com/AnalyticalGraphicsInc/cesium/pull/5625#issuecomment-316515271

> Of course the primitive can be translucent, but does it highlight translucent geometry? No.Neither will GroundPrimitives. Our translucent pass doesn't write depth.

At first the main use case is photogrammetry models, but I can see this being used for BIM and other models with translucent geometry so let's see how much interest there is.

**Comment by hpinkos** [comment]
duplicate #7753
