### ISSUE TITLE
Enable Camera URL Hashing property on Viewer

### ISSUE THREAD

**Issue by burn123** [AnalyticalGraphicsInc/cesium#5669]
I know in the `Apps/CesiumViewer/CesiumViewer.js` there is code to update the URL with the position of the camera, but it would be nice if this could be a property of the viewer.

**Comment by hpinkos** [comment]
Thanks for the suggestion @burn123!  I initially added that functionality at the `Viewer` level, but we decided we didn't want to add that kind of specific behavior since almost all Cesium apps use the `Viewer`. 
 We wanted to keep it pretty generic.  Users are welcome to copy the code from `CesiumViewer` to add this behavior to their own applications.

**Comment by burn123** [comment]
I know you could just copy the code over, but it seems like there is actually a lot of code that you would have to copy over. Because you need `queryToObject` and `objectToQuery`, then those rely on `decodeURIComponent` and `encodeURIComponent`, and so it ends up being a lot of code for a relatively simple task, which is why it might be good to have a viewer option

**Comment by hpinkos** [comment]
`queryToObject` and `objectToQuery` are both included as part of Cesium, so you can do `var query = Cesium.objectToQuery({...});` if you're using the built version of Cesium.  `decodeURIComponent` and `encodeURIComponent` are both standard global functions that are available in all web browsers.

**Comment by burn123** [comment]
Yeah I just realized that right after I posted :P Thanks!

**Comment by ateshuseyin** [comment]
No need to copy whole cesium viewer. Getting and seting camera position and orientation (see camera changed event) is ok for this feature.

**Comment by emackey** [comment]
The viewer widget is not in control of the host app's URL.  A single app with a single URL could have multiple viewer widgets with different camera positions.  This feature can't go in the viewer widget, sorry.
