### ISSUE TITLE
How support multiple viewport at the same time show?

### ISSUE THREAD

**Issue by yoyomule** [AnalyticalGraphicsInc/cesium#5675]
Hello, cesium support multiple viewport at the same time show? Similar to the threejs multi-viewport function(https://threejs.org/examples/webgl_multiple_views.html).

**Comment by ggetz** [comment]
Thanks @yoyomule, we're already tracking multiple viewports in a previous issue, #5214. We're going to close your issue now to keep the discussion in one place. If you have any further input on the main issue, #5214, please post it there.

**Comment by hoEc** [comment]
Is cesium now having this similar api?

**Comment by hpinkos** [comment]
@hoEc see this example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Multiple%20Synced%20Views.html
