### ISSUE TITLE
Sandcastle demos of specific particle system effects

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5679]
It would be nice to have template code for making smoke, fire, spark effects, etc to help people get started with particle systems.

**Comment by rahwang** [comment]
@jasonbeverage , father of Cesium particle systems has expressed interest? Are you still interested in doing part of this?

**Comment by jasonbeverage** [comment]
Jason Beverage, father of particle systems, first of his name :)  I'm interested for sure.  I'm going to be working on some demos over the next couple of weeks for foss4g, so if you want to wait and see if anything interesting drops out of those demos that could be cool.

**Comment by pjcozzi** [comment]
@ggetz OK to close?
