### ISSUE TITLE
2D flyTo cuts off with multiple billboards

### ISSUE THREAD

**Issue by rahwang** [AnalyticalGraphicsInc/cesium#5686]
Reported on the forum here: https://groups.google.com/forum/?hl=en#!searchin/cesium-dev/wrong$20viewpoint%7Csort:date/cesium-dev/MSPOj17Iqcg/dtbDsrUdBgAJ

In 2D mode, when using flyTo with an EntityCollection, the resulting view cuts off some of the entities.

To reproduce, use this sandcastle:
https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=be6da7fd622f888782c829d0dd13b273

1. Select "Add multiple billboards" and in 3D view the flyTo animation works to show all billboards (though the bottom one is cut off)
2. Rerun example and select "2D" map
3. Now select "Add multiple billboards" and the camera zooms past all of the billboards, leaving none of them visible

**Comment by hpinkos** [comment]
Duplicate #2473
