### ISSUE TITLE
Clamp 2D map view to map edges?

### ISSUE THREAD

**Issue by pizza2code** [AnalyticalGraphicsInc/cesium#5689]
Is it possible to clamp the 2D map view to the map edges, such that a user can't scroll beyond the north & south poles?  Letting up to half of the screen be black non-map seems of marginal utility.
(Sorry I can't post in the Google forum at the moment, don't have access to my 2FA.)

**Comment by ggetz** [comment]
Hi @pizza2code, we have an issue open for camera boundaries in #4802, please add any comments you may have to that issue. Thanks!
