### ISSUE TITLE
Mixing morph targets in materials crashes for glTF 2.0 models

### ISSUE THREAD

**Issue by moneimne** [AnalyticalGraphicsInc/cesium#5695]
When there are two primitives, one with morph targets and one without, that reference the same material, we add morph target calculations to both. This shouldn't happen and morph targets should be addressed on a per-primitive basis.

**Comment by pjcozzi** [comment]
@moneimne please look at this after SIGGRAPH.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6421
