### ISSUE TITLE
Model shadows broken in IE

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5697]
Shadows no longer cast properly onto models in IE

Chrome:
![image](https://user-images.githubusercontent.com/3451886/28791742-608d1e80-75fb-11e7-809f-9f4fd839abd3.png)

IE:
![image](https://user-images.githubusercontent.com/3451886/28791568-e4d8836a-75fa-11e7-9ec4-226be8c79652.png)

I didn't test to see which release this was broken in, I just noticed that this worked when shadows were introduced in 1.22 and it doesn't work now.  For the hot air balloon model, sometimes the shadow pops in but it goes away as soon as I move the camera.

**Comment by lilleyse** [comment]
This might have started working again since this issue was opened.

This demo works for me in IE:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/gallery/Shadows.html

**Comment by hpinkos** [comment]
Yep, looks good
