### ISSUE TITLE
'Request Volumes' in 3D Tiles Inspector doesn't seem to do anything

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5701]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Inspector.html&label=All

I don't see anything change when I check and uncheck the `Request Volumes` checkbox on the 3D tiles inspector.

@lilleyse what is the behavior supposed to be?

**Comment by pjcozzi** [comment]
Most likely the tileset/tile does not have a request volume: https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/README.md#viewer-request-volume

It should be OK to close this.
