### ISSUE TITLE
3D tiles interactivity sandcastle example throws developer error

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5703]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Interactivity.html&label=All

This is easiest to reproduce in Firefox.  Sometimes `pickPosition` returns `undefined`, and the annotation part of the example throws a `DeveloperError` when we call ` Cesium.Cartographic.fromCartesian`.  We need to check if `cartesian` is defined before continuing

**Comment by klim705** [comment]
This was fixed in #5759.

**Comment by pjcozzi** [comment]
Good eye, thanks @klim705!
