### ISSUE TITLE
SST Timezone

### ISSUE THREAD

**Issue by AbdullahIngramMicro** [AnalyticalGraphicsInc/cesium#5709]
Hi Everyone, I want to construct the SST timing.... So iinput the code in the sandcastle...
var datetime = new Cesium.JulianDate();
var result = '';
datetime = Cesium.JulianDate.addHours(datetime, 8);
console.log(datetime);
It gave me errors as it states that result is required and what is result is for???
Can you please explain to me(steps by steps) on how to construct the Singapore Timezone(No fractional timezone)???

Best Regards,
abdullah

**Comment by ggetz** [comment]
Hi @AbdullahIngramMicro, same message as the other issue you opened- Cesium is a large project, so we use GitHub exclusively for bug tracking and feature requests. Please ask questions on the [Forum](http://cesiumjs.org/forum.html). Thanks!
