### ISSUE TITLE
1.35version resolution Bug

### ISSUE THREAD

**Issue by fuxinruming** [AnalyticalGraphicsInc/cesium#5711]
Hello, I'm using the latest version 1.35 to build a simple earth error(fragment shader failed to compiled.) on the 7680*3240 resolution screen, and 1.34 of the 3dtiles branch versions do not have this problem. Will it be fixed in the next release? Thanks.in addition，when I load the 3dtiles at 7680*3240 resolution when the camera height decreases after a few seconds, this error will appear--Failed to execute"shaderSource" on "WebGlRenderContext":paraneter 1 is not of type 'webGlShader'.

**Comment by ggetz** [comment]
Hi @fuxinruming, Cesium is a large project, so we use GitHub exclusively for bug tracking and feature requests. Please ask questions on the [Forum](http://cesiumjs.org/forum.html). Thanks!

**Comment by ggetz** [comment]
I believe this should be reopend. @hpinkos 

From the forum: https://groups.google.com/forum/#!topic/cesium-dev/Bq1e6N8WGWU

```
<!DOCTYPE html> 
<html> 
        <head> 
                <meta charset="utf-8" /> 
                <title>加载3D影像</title> 
                <script type="text/javascript" src="Build/Cesium/Cesium.js" ></script> 
                <script type="text/javascript" src="ThirdParty/jquery-2.1.0.js" ></script> 
                <link rel="stylesheet" href="Build/Cesium/Widgets/widgets.css" /> 
<style>#cesiumContainer{width:100%;height:100%;}</style> 
        </head> 
        <body> 
                <div id="cesiumContainer"></div> 
        </body> 
        <script> 
                //球构建 
                var viewer = new Cesium.Viewer('cesiumContainer'); 
                  

        </script> 
</html> 
```
> only this code,There is no problem with 1920 * 1080 and 3840 * 2160 resolutions,but crashes at 7680 * 3240 resolution, and crashes by clicking on F5.

**Comment by mramato** [comment]
If the only difference is resolution, than this is almost certainly not a bug in Cesium but more likely a limitation of the video card or other hardware Cesium is running on.

**Comment by mramato** [comment]
There are many reasons it might have worked for you before but doesn't now.  I don't think anything changed in Cesium itself.  For example, I can't run Hello World at that resolution in 1.34 or 1.36 on my 650ti.  The resolution is not the only issue.  What is the value of window.devicePixelRatio?  What OS?  What video card?  Do you have the latest drivers?  The DPI settings of the host OS might even come into play.

Running non-trvial WebGL content at 7680x3240 requires pretty good hardware, this is why almost all browsers will provide a devicePixelRatio value that ends up rendering content at a lower resolution and scaling.  It's entirely possible that this used to be set on that machine and no longer is.

If you're looking for a quick fix, try setting `viewer.resolutionScale` to `0.5`, which will force the content to be rendered at half resolution and scale up, regardless of devicePixelRatio.

**Comment by mramato** [comment]
Just to close the "is this a bug?" aspect of this, I can successfully run Cesium at 7680*3240 on my laptop with a GTX 1050.  @fuxinruming let's move this conversation to the forum where others may be able to provide some additional advice: https://groups.google.com/forum/#!topic/cesium-dev/Bq1e6N8WGWU
