### ISSUE TITLE
Issues and bug in SST time

### ISSUE THREAD

**Issue by AbdullahIngramMicro** [AnalyticalGraphicsInc/cesium#5716]
var viewer = new Cesium.Viewer('cesiumContainer');
//SST timezone
var TZcode = 'SST';
//Construct a new Date
var UTCoffset = new Date();
//Return the timezone difference between UTC and Local Time:
UTCoffset = -UTCoffset.getTimezoneOffset();
//Construct a Julian Date
var UTCscratch = new Cesium.JulianDate();

// Date formatting to a global form
function localeDateTimeFormatter(datetime, viewModel, ignoredate) {
if(UTCoffset) datetime = Cesium.JulianDate.addMinutes(datetime, UTCoffset, UTCscratch);
var gregorianDT = Cesium.JulianDate.toGregorianDate(datetime), objDT;
if(ignoredate)
objDT = '';
else {
objDT = new Date(gregorianDT.year, gregorianDT.month-1, gregorianDT.day);
objDT = gregorianDT.day + ' ' + objDT.toLocaleString("en-us", { month: "short" }) + ' ' + gregorianDT.year;
if(viewModel || gregorianDT.hour+gregorianDT.minute === 0)
return objDT;
objDT += ' ';
}
return objDT + Cesium.sprintf("%02d:%02d "+TZcode, gregorianDT.hour, gregorianDT.minute);
}
I want to construct the SST time in sandcastle but however there are bugs and issues...

**Comment by ggetz** [comment]
Hi @AbdullahIngramMicro, please post your questions to the [Cesium Forum](http://cesiumjs.org/forum.html), thanks!
