### ISSUE TITLE
Bad artifacts in 3D Tiles BIM example

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5722]
Load the 3D Tiles BIM example and zoom and pan so that the tileset is near or over the horizong, you'll see alls kinds of artifacts flashing on and off:

![image](https://user-images.githubusercontent.com/1495196/28928893-7c725f78-783c-11e7-9f13-3926c10c003d.png)

![artifactts](https://user-images.githubusercontent.com/1495196/28928949-a72a5f90-783c-11e7-8f52-cc332ee726ab.gif)

CC @lilleyse

**Comment by likangning93** [comment]
I know that `gltf-pipeline` used to have an issue with special characters causing binary gltf to be wrong and have weird byte offset errors that caused similar artifacts, I wonder if it's the same thing here.

**Comment by pjcozzi** [comment]
I suspect this tileset was not created with `gltf-pipeline` (not to say it is not the same issue) and has **custom shaders** that may be moving the vertex to a crazy position.

@lilleyse can you confirm that there are custom shaders in this tileset?
