### ISSUE TITLE
Reversed camera tilt, part 2

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5733]
The "reverse tilt" was first reported in #1970, and fixed in #2006, with one caveat:

> There is still an issue in certain situations with tilting after using a shift-left drag to look. That will have to be fixed post-1.0.

I couldn't find an open issue for this, but shift-left-drag certainly causes problems.  In the animation below, I shift-drag the globe to the left, and then hold the middle-mouse and drag the mouse up and down.  The globe tilts left-and-right while the mouse goes up-and-down.

Then, I shift-drag the globe such that the center of the globe is above the center of the screen, the middle tilt-drag will be completely upside-down.

![cameratiltreversed](https://user-images.githubusercontent.com/1235080/29087704-c16992d4-7c44-11e7-8ea1-d47d628fe120.gif)

**Comment by hpinkos** [comment]
@emackey we have issue #2877 open, I added a comment to also see the details in this issue
