### ISSUE TITLE
Incorrect blending with globe off and black background

### ISSUE THREAD

**Issue by pmconne** [AnalyticalGraphicsInc/cesium#5734]
Opaque green cylinder (0,255,0,255), translucent red cylinder (255,0,0,127).
With globe off and black background, blending looks quite wrong:
![image](https://user-images.githubusercontent.com/22944042/29088156-4b6d57bc-7c46-11e7-892a-a1daf96f6f42.png)

Possibly related to [5731](https://github.com/AnalyticalGraphicsInc/cesium/issues/5731)?
Either way, this data set is attached [5731](https://github.com/AnalyticalGraphicsInc/cesium/issues/5731#issuecomment-321041644)

**Comment by hpinkos** [comment]
Thanks @pmconne!  I think this might also be related to #4170, but I'm not sure.
@bagnell @lilleyse what do you think?

**Comment by pmconne** [comment]
Thanks @hpinkos - just to clarify, this is with OIT enabled.

**Comment by lilleyse** [comment]
This is what I see, not as drastic. I'm not sure what would explain the difference...
![alpha](https://user-images.githubusercontent.com/915398/29098521-d34c62dc-7c6d-11e7-975e-a4d5742950fd.png)

Here is the Sandcastle code I'm using:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    globe : false,
    skyBox : false
});

var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url: '../../SampleData/test/Translucent/Model_1c.json'
}));

tileset.readyPromise.then(function() {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0.0, -0.5, boundingSphere.radius / 4.0));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
}).otherwise(function(error) {
    throw(error);
});
```

**Comment by bagnell** [comment]
I see the same as @lilleyse, which looks correct to me.
