### ISSUE TITLE
Windows Authentication Basemap Issue

### ISSUE THREAD

**Issue by cfickler** [AnalyticalGraphicsInc/cesium#5739]
When locking down ArcGIS map services using Windows Authentication Cesium fails to authenticate correctly and all the tile requests receive a 401 error.

It turns out the reason is simple, the TrustedServers.contains method fails to correctly compare the provided url with the list of TrustedServers. The getAuthority call in the contains method strips out the scheme, in our case 'https://' and hence the compare fails.

To get around the issue I added the scheme back into the getAuthority return string as shown below. My only issue is I am unclear if that should be the intent of the method. Making the change resolved the bug.

 function getAuthority(url) {
        var uri = new Uri(url);
        uri.normalize();

        // Removes username:password@ so we just have host[:port]
        var authority = uri.getAuthority();
        if (!defined(authority)) {
            return undefined; // Relative URL
        }

        if (authority.indexOf('@') !== -1) {
            var parts = authority.split('@');
            authority = parts[1];
        }

        // If the port is missing add one based on the scheme
        if (authority.indexOf(':') === -1) {
            var scheme = uri.getScheme();
            if (!defined(scheme)) {
                scheme = window.location.protocol;
                scheme = scheme.substring(0, scheme.length-1);
            }
            if (scheme === 'http') {
                **authority = scheme.concat("://", authority, ':80');**
            } else if (scheme === 'https') {
            	**authority = scheme.concat("://", authority, ':443');**
            } else {
                return undefined;
            }
        }

        return authority;
    }

I guess the only other way would be to get the authority from the provided url which might be the correct way to do it, but I admit I haven't looked to see how many changes that would involve.

Your thoughts are appreciated

Cheers

**Comment by mramato** [comment]
Thanks for the report @cfickler!  @tfili can you take a look at this?

**Comment by tfili** [comment]
What does you `add` call look like? My guess is that you passing a full url to the `add` function instead of just the host name and port.

`add` requires a hostname and a port. If you pass a full URL this will cause `contains` to fail.

`contains` requires a URL where we will automatically add a port if the scheme is `http` or `https`.

If you look at the following Sandcastle example, you can see how it works
```
Cesium.TrustedServers.add('test.com', 80);

if (Cesium.TrustedServers.contains('http://test.com/image.jpeg')) {
    console.log('Found'); // Should see this
} else {
    console.log('Not Found');
}

if (Cesium.TrustedServers.contains('https://test.com/image.jpeg')) {
    console.log('Found');
} else {
    console.log('Not Found'); // Should see this
}

// Fails because full URL is passed to add
Cesium.TrustedServers.add('https://test.com', 8080);
if (Cesium.TrustedServers.contains('http://test.com:8080/image.jpeg')) {
    console.log('Found'); 
} else {
    console.log('Not Found'); // Will see this because of incorrect call to add
}

```

**Comment by cfickler** [comment]
apologies!!!  I haven't looked at the help example close enough!!!
