### ISSUE TITLE
Label text isn't pixel-aligned (even without FXAA)

### ISSUE THREAD

**Issue by pizza2code** [AnalyticalGraphicsInc/cesium#5746]
I set the font size to 12px in the labels Sandcastle and disabled FXAA.  The text degrades in quality significantly depending on the sub-pixel location of the text.

Poor:
![image](https://user-images.githubusercontent.com/15824044/29285085-320faedc-80fb-11e7-8eb6-73b52c0e856b.png)
Nearly ideal:
![image](https://user-images.githubusercontent.com/15824044/29285095-3728e816-80fb-11e7-9e6e-212de7c1fe66.png)

**Comment by emackey** [comment]
Related:  https://github.com/AnalyticalGraphicsInc/cesium/issues/4235#issuecomment-242516462

**Comment by hpinkos** [comment]
Improved with sdf labels
![image](https://user-images.githubusercontent.com/3451886/65270953-394c1280-daea-11e9-9da4-bcc0d743a294.png)
