### ISSUE TITLE
Broken link in contributor guide

### ISSUE THREAD

**Issue by YonatanKra** [AnalyticalGraphicsInc/cesium#5763]
The link: http://cesiumjs.org/2013/10/08/GitHub-Pull-Request-Workflows/ is broken.
It shows in this section: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines

**Comment by ggetz** [comment]
I've updated a redirect rule so this will redirect to the correct blog location. Make sure you clear your cache or open in an incognito window to see the change.

**Comment by pjcozzi** [comment]
Thanks for the report @YonatanKra!

@ggetz is the best practice for us to update all of our links and not rely on the redirects?  If so, please only a `doc` issue for it.  Perhaps @slchow could help.

**Comment by ggetz** [comment]
Opened #5775
