### ISSUE TITLE
3D Tiles selection bug?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5766]
Check out the NYC Sandcastle examples: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Picking.html&label=3D%20Tiles

If you just sit there and let everything load, some of the tiles that should be visible never get loaded even though they are definitely within the SSE (verified by waiting for the network tab to stop loading tiles).  If you move the camera around, these buildings get loaded pretty quickly, and if you go back to the home view, they stay loaded.  So I'm not sure where the bug is,, but it seems like a pretty significant one.

Initial view; 
![image](https://user-images.githubusercontent.com/1495196/29594033-27c27518-877c-11e7-8e99-aace0d7b8464.png)

After moving the camera around and back to the initial view:

![image](https://user-images.githubusercontent.com/1495196/29594037-3f2f2228-877c-11e7-8aab-ae1aa5121ea9.png)

CC @lilleyse @pjcozzi

**Comment by lilleyse** [comment]
Seems to be a problem with `skipLevelOfDetail`. I'll investigate.

**Comment by pjcozzi** [comment]
Good catch, thanks @mramato!

@lilleyse if it's realistic, looks like an important fix for the next release.

Maybe this is a simple additive vs. replacement issue?

**Comment by SunBlack** [comment]
We can confirm since issue with point clouds (additive). Issue exist since #5254
