### ISSUE TITLE
Geojson memory leak

### ISSUE THREAD

**Issue by AnotherFoxGuy** [AnalyticalGraphicsInc/cesium#5774]
I'm using [Mapzen vector tiles](https://mapzen.com/projects/vector-tiles/) to get Geojson data and load it using ```Cesium.GeoJsonDataSource().load()```
After browsing the map a while, Cesium starts using more and more ram and crashes after reaching ~3GB RAM

Made a sandcastle demo to show the Geojson memory leak: https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=6079abc25a6ff992220adc40da0284b3

**Comment by ggetz** [comment]
Thanks for the report @AnotherFoxGuy, and thanks for the Sandcastle demo! 

We'll try to take a look at this soon. If you're able and have time to debug the problem yourself, we'd be happy to accept any contributions.

**Comment by hpinkos** [comment]
I'm closing this as a duplicate of #5662
