### ISSUE TITLE
Remove pipeline extras for glTF

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5776]
This change was made to fix a caching bug: https://github.com/AnalyticalGraphicsInc/cesium/pull/5728

But as a result, `extras: {_pipeline: {....}}` is added everywhere in the `Model.glTF` object.  This has to significantly bloat the size of the gltF in memory.

**Comment by pjcozzi** [comment]
@lilleyse is this still an issue in the latest gltf-pipeline?

**Comment by lilleyse** [comment]
Now extras are only added to buffers, images, and shaders, so it has improved. Still it would be better to remove them completely. @ggetz can you look at this as part of Cesium's gltf-pipeline upgrade?
