### ISSUE TITLE
glTF lighting change in 1.36

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5787]
The CesiumMilkTruck-kmc model is completely black when not lit by the sun in 1.36.  This was not the case in 1.36.  Was this change intentional? @lilleyse 

1.35:
![image](https://user-images.githubusercontent.com/3451886/29791024-92900d92-8c09-11e7-8171-517e07626479.png)

1.36:
![image](https://user-images.githubusercontent.com/3451886/29791030-96bfb016-8c09-11e7-9ca3-f7936b60b457.png)

Load this example and move the timeline so it's night.
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, 0);
var heading = Cesium.Math.toRadians(135);
var pitch = 0;
var roll = 0;
var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

var entity = viewer.entities.add({
    position : position,
    orientation : orientation,
    model : {
        uri : '../../SampleData/models/CesiumMilkTruck/CesiumMilkTruck-kmc.glb',
        minimumPixelSize : 128,
        maximumScale : 20000
    }
});
viewer.trackedEntity = entity;
```

**Comment by lilleyse** [comment]
Should be better now - fixed here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/313
![dark](https://user-images.githubusercontent.com/915398/29848852-31a999ce-8cf1-11e7-9859-e1b6252e957a.PNG)

**Comment by pjcozzi** [comment]
OK to close?

**Comment by lilleyse** [comment]
Yeah
