### ISSUE TITLE
Source links in documentation are broken

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#5792]
Reported by @gberaudo in #5791.

All of the source links (the small hyperlinks in the right margin of each sub-header) are broken.  For example:  https://cesiumjs.org/Cesium/Build/Documentation/EntityCollection.html#getById

The link's target looks like this:

https://github.com/AnalyticalGraphicsInc/cesium/blob/1.36.0-13623056/Source/DataSources/EntityCollection.js#L388

The problem here is `1.36.0-13623056` is being used in the path, which does not match the GitHub tag name of `1.36`.  This URL is constructed here: 
 https://github.com/AnalyticalGraphicsInc/cesium/blob/1.36/Tools/jsdoc/cesium_template/publish.js#L308

The `CESIUM_VERSION` appears to be assigned here: 
 https://github.com/AnalyticalGraphicsInc/cesium/blob/1.36/gulpfile.js#L203

/cc @mramato Are you aware of recent build changes that might have altered this value?

**Comment by mramato** [comment]
Our website is also showing the wrong version in Sandcastle, @ggetz can you take a quick look to see if it's something obvious that changed in the build process.

**Comment by mramato** [comment]
Actually, this is most likely specific to how the version of Cesium on the website gets updated and not anything to do with Cesium's build itself.  Which means @ggetz is even more of the right person to check this out.

**Comment by emackey** [comment]
Agreed.  It doesn't seem to affect the "archived" version, such as:

https://cesiumjs.org/releases/1.36/Build/Documentation/EntityCollection.html  -- works fine

It also doesn't affect local developer builds.  It seems to be only the main hosted version that's incorrect.

**Comment by emackey** [comment]
Downgraded from "next release" since the release itself doesn't seem to be broken.

**Comment by ggetz** [comment]
To clarify, using  the [cesiumjs.org](https://github.com/AnalyticalGraphicsInc/cesium/tree/cesiumjs.org) branch and running `npm run release` will be the version we want hosted, right?

**Comment by mramato** [comment]
Yes.

**Comment by ggetz** [comment]
Alright, this is fixed on the site now, and I'm working on fixing this as part of the automated website build process.

**Comment by emackey** [comment]
OK to close?

**Comment by ggetz** [comment]
Yes please, thanks @emackey!
