### ISSUE TITLE
Allow polylines to connect points with Rhumb lines

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#5795]
```
var viewer = new Cesium.Viewer("cesiumContainer" );


viewer.entities.add({
    polyline: {
        positions: Cesium.Cartesian3.fromDegreesArray([-120, 20, 120, 20])
    }
});
```

Turn on 2D mode and the line will appear warped, even though it's connecting two points of a constant latitude, because the polyline is connecting the two points with a great arc.

The `followSurface` property only allows the two points to be connected with a great arc or linearly (which clips through the globe):
https://cesiumjs.org/Cesium/Build/Documentation/PolylineGraphics.html?classFilter=polyline#followSurface

**Comment by hpinkos** [comment]
Duplicate #4000

**Comment by ggetz** [comment]
Thanks @hpinkos!
