### ISSUE TITLE
Video not playing in Sandcastle demo

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5805]
In the Video Sandcastle demo all I see is this:
<img width="394" alt="video" src="https://user-images.githubusercontent.com/915398/29984287-b2e53812-8f27-11e7-8a9b-162536f11b87.PNG">

I checked that the video paths still works. Does anyone have an idea? I have it labelled for next release.

**Comment by hpinkos** [comment]
Is it an http/https issue?

**Comment by hpinkos** [comment]
Yeah, change the links to point to `https://cesiumjs.org/...`

**Comment by ggetz** [comment]
May be an issue with the settings on on the file since moving to S3, I'll take a look.

**Comment by ggetz** [comment]
Yeah I think @hpinkos id right

**Comment by shunter** [comment]
Looks like the content-types are wrong for the files, which is probably breaking the video tag.

`curl -LkD - 'https://cesiumjs.org/videos/Sandcastle/big-buck-bunny_trailer.webm' -o /dev/null`

```
Content-Type: binary/octet-stream
Content-Length: 2165175
Connection: keep-alive
x-amz-id-2: W1FqjsPv2+ivVM18BuKQLEWxtbkc2TME7siFUzzeH4OoDyuiZ3pUJarnldX3wsKSF/el9YQtix0=
x-amz-request-id: AE92FFB5A8405135
Date: Wed, 23 Aug 2017 18:02:38 GMT
Last-Modified: Fri, 11 Aug 2017 14:20:33 GMT
ETag: "9b962361f255c3a3c3059e30adde6627"
Server: AmazonS3
Age: 144
X-Cache: Hit from cloudfront
Via: 1.1 8ed48260ebc584eec98d6931248a313e.cloudfront.net (CloudFront)
X-Amz-Cf-Id: rMgbR1KzWucdeWgaeN3H6M9C27cMEgDpdXlHJBqUojIGE9pBOgQu3A==
```

**Comment by ggetz** [comment]
All the content-types are correct in s3 except for the `webm` file, which I just updated.

**Comment by lilleyse** [comment]
Those changes helped.

A different problem now - the video stays stuck on a middle frame. Works in Firefox but not Chrome. Can someone test if this also happens for them?

<img width="344" alt="video2" src="https://user-images.githubusercontent.com/915398/29985418-f4a2251c-8f2c-11e7-860e-6f361ff6212a.PNG">

**Comment by hpinkos** [comment]
It works fine for me

**Comment by lilleyse** [comment]
Hm, it could just be me then. I'll reopen if I see that problem anywhere else.
