### ISSUE TITLE
Default icon is displayed when icon tag is empty

### ISSUE THREAD

**Issue by josh-bernstein** [AnalyticalGraphicsInc/cesium#5819]
I found a bug when I loaded a KML file containing the following
`<IconStyle>
<Icon></Icon>
    </IconStyle>`

No icon is specified, and if I import that KML into Google Earth, the placemark icon is not shown.  However, when I import the KML into an app using Cesium, a yellow placemark icon is shown.

**Comment by hpinkos** [comment]
Thanks for reporting this @josh-bernstein!

**Comment by josh-bernstein** [comment]
@hpinkos My pleasure!  I have a branch with a fix that I would like to push up, but I'm having GitHub difficultiies atm

**Comment by hpinkos** [comment]
Great, thanks @josh-bernstein!  We're always happy to review pull requests.  We have some details for opening a pull request in our contributing documentation here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request

Hope you're able to figure out your GitHub issues without too much trouble.  I'm not sure if this would help, but we have instructions for getting started and building the code base here: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide#build-guide
