### ISSUE TITLE
Update deprecated HeadingPitchRoll related functions

### ISSUE THREAD

**Issue by kaktus40** [AnalyticalGraphicsInc/cesium#5822]
- Update `HeadingPitchRoll.fromQuaternion` with the content of `HeadingPitchRoll.fromDirectQuaternion` and remove `HeadingPitchRoll.fromDirectQuaternion`
 - Update `Matrix3.fromHeadingPitchRoll` with the content of `Matrix3.fromDirectHeadingPitchRoll` and remove `Matrix3.fromDirectHeadingPitchRoll`
 - Update `Quaternion.fromHeadingPitchRoll` with the content of `Quaternion.fromDirectHeadingPitchRoll` and remove `Quaternion.fromDirectHeadingPitchRoll`
 - Update `Transforms.headingPitchRollToFixedFrame` with the content of `Transforms.directHeadingPitchRollToFixedFrame` and remove `Transforms.directHeadingPitchRollToFixedFrame`
 - Update `Transforms.headingPitchRollQuaternion` with the content of `Transforms.directHeadingPitchRollQuaternion` and remove `Transforms.directHeadingPitchRollQuaternion`

**Comment by kaktus40** [comment]
It's for version 1.43 (I don't know how to add label)

**Comment by pjcozzi** [comment]
Deprecated in #5809.
