### ISSUE TITLE
viewer.entities.remove(entity)后再创建模型导致浏览器内存一直增长

### ISSUE THREAD

**Issue by githubhanjunjun** [AnalyticalGraphicsInc/cesium#5823]
Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by githubhanjunjun** [comment]
创建了大量模型，用for循环调用viewer.entities.remove(entity)删除所有模型后，再创建模型导致浏览器内存一直增长

**Comment by ggetz** [comment]
Hi @githubhanjunjun, from translating your comment, it looks like you have a question about a large number of entities. Try asking over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
