### ISSUE TITLE
CORS issues when using cesiumjs.org

### ISSUE THREAD

**Issue by awst-baum** [AnalyticalGraphicsInc/cesium#5826]
I'm including cesium from cesiumjs.org in a JSF page with JavaScript like so:

	<script src="https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js" />

This used to work fine in the past - but recently the Rectangles my JavaScript code adds aren't shown on the globe any more and I get these errors in the Firefox console:

	Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cesiumjs.org/Cesium/Build/Cesium/Assets/approximateTerrainHeights.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).  (unknown)
	Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cesiumjs.org/Cesium/Build/Cesium/Assets/IAU2006_XYS/IAU2006_XYS_15.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

If I add cesium to the webserver (application server) that hosts the JSF page, the error vanishes and my Rectangles are shown just fine.

Does this mean that cesium is no longer meant to be used in cross-origin scripting?

**Comment by emackey** [comment]
@ggetz @mramato I'm seeing lack of CORS on cesiumjs.org too.  Can this be fixed?

**Comment by mramato** [comment]
Thanks @awst-baum for raising the issue.

@emackey It definitely is something that can be/sould be fixed, but I'm not directly involved in the running of the website itself anymore so we'll have to wait for @ggetz to respond.

**Comment by ggetz** [comment]
@awst-baum I've allowed all Origin headers on cesiumjs.org, that should fix the error. Make sure you clear your cache, and let me know if you're still seeing issues. Thanks!

**Comment by awst-baum** [comment]
Thanks a lot, working perfectly now!

**Comment by TietoaPetter** [comment]
I'm still geting a CORS denied on this resource: https://cesiumjs.org/releases/1.62/Build/Cesium/Assets/Textures/maki/.png
