### ISSUE TITLE
An error occurred while rendering

### ISSUE THREAD

**Issue by uekeueke** [AnalyticalGraphicsInc/cesium#5841]
Sometimes loading my cesium project the rendering stops on init and the console shows this message
this happens a lot in firefox 55.0.2 (64-bit),
and sometimes in chrome 59.0.3071.104 (Build oficial) (64 bits)...

> An error occurred while rendering.  Rendering has stopped.
> undefined
> TypeError: d is undefined
> O.unpackCombineGeometryParameters@http://127.0.0.1:40373/3d/vendor/Cesium/Workers/combineGeometry.js:62:6670
> r@http://127.0.0.1:40373/3d/vendor/Cesium/Workers/combineGeometry.js:62:8582
> n/<@http://127.0.0.1:40373/3d/vendor/Cesium/Workers/combineGeometry.js:62:8089

My projects loads 4 geojsons of 400kn each one, not so much?

How to debug it?

**Comment by ggetz** [comment]
Hi there @uekeueke, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

To debug, try your browse's dev tools. (In Chrome hit ctr+shift+i)
