### ISSUE TITLE
From 1.37, GLTF shader paths are relative, even when starting with a slash

### ISSUE THREAD

**Issue by xtassin** [AnalyticalGraphicsInc/cesium#5844]
Hi,

I used to specify custom shaders in my GLTF files in this manner:

`"uri": "/shaders/mappedReflectiveFS.glsl"`

This should load the file from the root of the web host (http://domain.com/shaders/mappedReflectiveFS.glsl)

Instead, and starting with Cesium 1.37, the shaders are loaded relative to the GLTF's directory even if the uri starts with a slash.

Regards,

Xavier.

**Comment by mramato** [comment]
Thanks for the report @xtassin, this definitely sounds like a clear cut bug.  @lilleyse or @emackey any ideas?

**Comment by emackey** [comment]
Definitely sounds like a bug.  There's been some discussion of root-relative paths on the official glTF repo lately, but nothing that should prevent this from working.

**Comment by xtassin** [comment]
Sorry to bump this but can we expect a fix in upcoming releases or is this something I should be looking into myself?

Thanks.

**Comment by mramato** [comment]
@xtassin we would love to get this fix in, but no one has had a chance to look at it yet.  It should be pretty straight forward so I think it would make a great first pull request if you have the time or desire to tackle it yourself.

If not, thanks for bringing it to our attention anyway and I marked this a priority so we don't forget about it.

**Comment by emackey** [comment]
Actually I recently opened a PR to add `file` support to `joinUrls` in #5989, and while I was in there I noticed that joinUrls always concats them, taking care to get the slashes right, but not cancelling out any base path if the 2nd URL is a root-relative URL.  It looked like intended behavior, as `..` is not supported there, and the unit tests very specifically test for that behavior.  Maybe it used to be different?  Or maybe glTF in Cesium didn't used to depend on this?

If someone has time to run `git bisect` on this, to nail down exactly what changed to cause the break, that would be a great for understanding this.  I'm a little swamped with non-glTF stuff at the moment sadly.

**Comment by xtassin** [comment]
All usage of uri.resolve have been replaced by joinUrls in model.js (and possibly in other places) during "Misc changes and helpers from 3d-tiles #5249"

The fix could be to handle root relative url in joinUrls but I am not sure of your view on that.

**Comment by lilleyse** [comment]
I checked that this has since been fixed after the resource loading overhaul. Paths starting with a slash should now point to the server root directory.
