### ISSUE TITLE
Nearest-neighbor image resampling for ImageryLayer

### ISSUE THREAD

**Issue by forman** [AnalyticalGraphicsInc/cesium#5846]
We develop an application that uses Cesium to display climate data imagery. Many users (usually Earth scientists) would like to see the original grid cell extends in the images. Cesium seems to use (linearily) interpolated textures by default. Is there any possibility to set an `ImageryLayer` to a nearest-neighbor image resampling so actual grid cells would be displayed as squares? Even a global Cesium (or WebGL) setting would help.

To get an idea, here is a screenshot of the application showing monthly cloud averages in 0.5 degree grid cells. The interpolation applied makes it impossible to distinguish the original grid cells:

![image](https://user-images.githubusercontent.com/206773/30906005-c462c97a-a376-11e7-89b4-7ba305b48201.png)

**Comment by ggetz** [comment]
Hi there @forman. Please ask your question over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

**Comment by ggetz** [comment]
@lilleyse confirmed that there's not a way to do this is Cesium currently. The imagery layer has the linear interpolation hard-coded, so we'll leave this open.

**Comment by mramato** [comment]
I think we had a thread about this at one point on the forum and it's come up before.  @bagnell isn't modifying this just a one line change?  Might be a good workaround or easy enough for someone to open a PR to handle.

**Comment by forman** [comment]
Hi @ggetz, sorry for spaming your issue tracker and thanks for the info! Maybe @lilleyse could point me to the code location so we may fork & fix.

**Comment by forman** [comment]
@mramato we're happy to do so

**Comment by bagnell** [comment]
You can add [Sampler](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Sampler.js)s to the textures here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ImageryLayer.js#L743

Set the minification and magnification filters to `NEAREST`. If the textures need reprojection, you can modify the samplers here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ImageryLayer.js#L796

**Comment by mramato** [comment]
Thanks @bagnell!  Looking forward to a pull request @forman!  Let us know if you run into any roadblocks.

**Comment by forman** [comment]
@bagnell thanks, I hope to find some time next week

**Comment by forman** [comment]
Closing this as the feature is already included since v1.39, 2017-11-01.
