### ISSUE TITLE
Remove deprecation warnings for HeadingPitchRoll function in 1.40

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#5862]
Remove deprecation warnings for  `HeadingPitchRoll.fromQuaternion`, `Matrix3.fromHeadingPitchRoll`, `Quaternion.fromHeadingPitchRoll`, `Transforms.headingPitchRollToFixedFrame`, and `Transforms.headingPitchRollQuaternion` in the 1.40 release.

See https://github.com/AnalyticalGraphicsInc/cesium/pull/5848

**Comment by hpinkos** [comment]
This change was reverted, so this is no longer needed
