### ISSUE TITLE
Camera moveForward/moveBackward broken in 2D view

### ISSUE THREAD

**Issue by thw0rted** [AnalyticalGraphicsInc/cesium#5884]
Go to the [Sandcastle demo for Camera control](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Camera%20Tutorial.html&label=Showcases), switch to 2D, and try the W/S keys.  The camera moves toward or away from the map in 3D and Columbus, but does not move in 2D.

**Comment by thw0rted** [comment]
I just noticed that `ScreenSpaceCameraController` uses `Camera.zoomIn` instead of `moveForward`.  This works fine.

**Comment by ggetz** [comment]
@thw0rted OK to close?

**Comment by thw0rted** [comment]
Well, at least somebody should update the demo to pick the function based on the mode, but also I don't think that `moveForward` should have no effect at all in 2D mode.

**Comment by pjcozzi** [comment]
@thw0rted if you have the time, it would be great for you to open a small pull request to update the Sandcastle example, thanks!

**Comment by thw0rted** [comment]
It would be simple enough to update the example, but I do think that `moveForward` should be fixed to move toward the map in 2D mode (which would make the Sandcastle update unnecessary).
