### ISSUE TITLE
PolylineGraphics.depthFailMaterial doc error?

### ISSUE THREAD

**Issue by denverpierce** [AnalyticalGraphicsInc/cesium#5886]
Should `depthFailMaterial `appear in the docs for `PolylineGraphic`s, or what that an intentional omission?

https://github.com/AnalyticalGraphicsInc/cesium/blob/1.38/Source/DataSources/PolylineGraphics.js#L104

**Comment by ggetz** [comment]
Looks like it's just missing the `* @memberof PolylineGraphics.prototype` line, I don't think it is intentional.
