### ISSUE TITLE
Camera sinks under terrain

### ISSUE THREAD

**Issue by andrzejfigula** [AnalyticalGraphicsInc/cesium#5888]
Hi guys, 
just found that while terrain data is loading / worker is processing, it is possible to place and control camera under terrain.
(Attached GIF)

Scenario is:
1. Happens for both, WGS84 Ellipsoid and STK Terrain.
2. Move the camera (ctrl+mouse controls), after moving, quickly move it again below the ground level.

Notice that this might depend on how quickly data will load / be shown on screen. It seems to happen only when not all terrain data is already loaded. 

I found that this was introduced between 1.37 and 1.38, as 1.37 works fine.

Some details:

Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
macOS Sierra 10.12.6 (16G29)
NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB
(I think it uses GeForce while in WebGL)

![nimbus-record-video-2017-10-08-00-42-53_1](https://user-images.githubusercontent.com/10167071/31312742-50861098-abc3-11e7-830c-f28d6f8b61f9.gif)

Best regards, and many thanks for making this amazing software!
Let me know if you need any further information.
Andrzej

**Comment by ggetz** [comment]
Hey @andrzejfigula, thanks for bringing up. We've already been tracking it in a previous issue, #5837. We're going to close your issue now to keep the discussion in one place. If you have any further input on the main issue, #5837, please post it there.
