### ISSUE TITLE
Cesium controls on Cesium homepage demo are covered by close button container

### ISSUE THREAD

**Issue by andrzejfigula** [AnalyticalGraphicsInc/cesium#5889]
Hi guys,
One minor CSS issue on homepage, it seems like Close Demo button has width set to 100%, it overlaps the Cesium controls, and makes them inaccessible. 

<img width="1350" alt="screen shot 2017-10-08 at 01 40 12" src="https://user-images.githubusercontent.com/10167071/31312939-28ed95f4-abca-11e7-855f-4bff57071281.png">

Regards,
Andrzej

**Comment by ggetz** [comment]
Hi @andrzejfigula, thanks for the report! I'm going to open this issue in the website repo so we can close it here.

**Comment by ggetz** [comment]
@andrzejfigula This should be fixed now, just make sure clear your cache or open in an incognito window.

**Comment by andrzejfigula** [comment]
@ggetz Works fine now! 👍
