### ISSUE TITLE
Removing polylines in a loop doesn't remove polylines with non-color materials

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#5893]
Go to the [polylines sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Polyline.html&label=All).

Add the following:
```
Sandcastle.addToolbarButton('Remove polylines', function() {
    for (var i = 0; i < viewer.entities.values.length; ++i) {
        viewer.entities.remove(viewer.entities.values[i]);
    }
});
```

The first time that button is pressed, the polylines that are a material other than the default color are not removed. Pressing the button additional times removes one additional polyline each time.

**Comment by hpinkos** [comment]
There are some issues with your logic here.  Using a for loop isn't a good way to do this because `i` is incrementing but `viewer.entites.values.length` is decrementing each time you remove an entity.

This example works fine:
``` javascript
Sandcastle.addToolbarButton('Remove polylines', function() {
    while (viewer.entities.values.length > 0) {
        viewer.entities.remove(viewer.entities.values[0]);
    }
});
```

**Comment by ggetz** [comment]
Thanks @hpinkos. Is there a particular reason this happens only with the polylines with non-color materials?

**Comment by hpinkos** [comment]
It's just a coincidence.  Those indexes were the ones skipped over based on how your for loop was working.
If you use the code snippet I wrote above and there are still polylines that don't get removed, feel free to re-open the issue.  All the polylines were removed correctly for me.
