### ISSUE TITLE
where to find the source code of the  Cesium Documentation

### ISSUE THREAD

**Issue by riddle911** [AnalyticalGraphicsInc/cesium#5894]
Hi there, I want make the Documentation offline to read.
I noticed the wiki is built by JSdoc. But I didn't find the source code of the documentation.
Can you guys help me.

**Comment by ggetz** [comment]
Hi @riddle911, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

If you run `npm run generateDocumentation`, it will be output to the `Build/Documentation` directory. See the Cesium [Build Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md).

**Comment by shunter** [comment]
Also the documentation is available in the official release zip files in the `Build/Documentation` directory.
