### ISSUE TITLE
Ellipsoid isn't properly occluded if it intersects with another ellipsoid

### ISSUE THREAD

**Issue by coreylowman** [AnalyticalGraphicsInc/cesium#5895]
See this showcase:

https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=49dd70ab630f3893dda1a8cf9fa23f99

The ellipsoid is centered at the surface of the earth so half of it should not be visible, but the whole ellipsoid is still visible.

If you change the angle that you view the ellipsoid at, it will become partially occluded.

Any ideas what could be causing this issue?

**Comment by hpinkos** [comment]
Hello @coreylowman 
To enable clipping against the ellipsoid, add this line: `viewer.scene.globe.depthTestAgainstTerrain = true;`

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for issue tracking and feature planning

**Comment by coreylowman** [comment]
@hpinkos Sorry about that! Thanks for the solution. I'll post future questions there instead.
