### ISSUE TITLE
Rename "beginner" label to "good first issue?"

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5902]
Across all of our repos for better discoverability.

![image](https://user-images.githubusercontent.com/782098/31464069-3d3028b6-ae9e-11e7-8b4c-42ee856ac3a9.png)

**Comment by techboy14** [comment]
alright

**Comment by ggetz** [comment]
Updated

**Comment by pjcozzi** [comment]
Did you already rename all our docs in all our repos?

**Comment by pjcozzi** [comment]
already -> also

**Comment by ggetz** [comment]
Yep, updated repos that had a beginner tag that wasn't `good first issue` or `help wanted`

**Comment by pjcozzi** [comment]
Great, but I meant the contributing guide, onramping material, etc.

**Comment by ggetz** [comment]
Updated in all our guides mentioning it :+1:
