### ISSUE TITLE
The overlapping geometry show mix color if two geometries intersect 

### ISSUE THREAD

**Issue by heavis** [AnalyticalGraphicsInc/cesium#5903]
Two intersected geometries show on map,  set color to 'YELLOW' and 'BLUE'. The overlapping part showing color neither YELLOW nor BLUE. But I hope the overlapping part show the top YELLOW color.   similar geometries can be shown normally by Openlayers.

**Comment by ggetz** [comment]
Hi @heavis, thanks for the bug report. Could you maybe put together an example using [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases) to show when this occurs?

**Comment by hpinkos** [comment]
@heavis Cesium uses order independent translucency by default, so colors that are translucent will be blended.  You can try disabling this to see if it gives you the effect you want.  Here is an example:
```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    orderIndependentTranslucency: false
});
var entities = viewer.entities;

entities.add({
    polygon: {
		hierarchy: new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray([
                -58.0, 10.0,
                -50.0, 27.0,
                -50.0, 32.0,
                -58.0, 30.0
            ])),
		material : Cesium.Color.fromRandom({alpha : 0.8}),
		height: 0
    }
});

entities.add({
    polygon: {
		hierarchy: new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray([
                -59.0, 10.0,
                -51.0, 18.0,
                -51.0, 40.0,
                -59.0, 41.0
            ])),
		material : Cesium.Color.fromRandom({alpha : 0.8}),
		height: 0
    }
});

viewer.zoomTo(viewer.entities);
```

Cesium unfortunately does not have support for z-ordering so there isn't a way to specify which geometry renders on top of the other.  We have an issue written up here to add that feature: #4108

In the future, please report things like this on our forum and someone will be able to help: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
Thanks!

**Comment by mramato** [comment]
@hpinkos is only half right.  The Entity API does not support z-ordering, but [GroundPrimitive](https://cesiumjs.org/Cesium/Build/Documentation/GroundPrimitive.html) does.  Disabling IOT will have no affect here if the goal is to have one opaque geoemtry render completely on top of another opaque geometry.

This probably is much harder in 3D than 2D (where you can literally just draw on top of the lower one).  If you are not using terrain, you can set a small height offset to achieve the desired effect in some cases as well (but this won't work with terrain).
