### ISSUE TITLE
camera.constrainedAxis not work?

### ISSUE THREAD

**Issue by wangtun** [AnalyticalGraphicsInc/cesium#5911]
I have set the camera.constrainedAxis as Cesium.Cartesian3.UNIT_Z, but when I rotate the global, I can rotate it any axis. How can I fixed the camera axis  when I rotate the global? thanks

**Comment by ggetz** [comment]
Hey @wangtun, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
