### ISSUE TITLE
Firefox WebGL warnings in console

### ISSUE THREAD

**Issue by thw0rted** [AnalyticalGraphicsInc/cesium#5912]
When I load [the basic viewer](https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?stats=true) in Firefox (56.0, 64-bit, Ubuntu 16.04), I see repeated errors in the console:

> Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

When I try to work with [billboards](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Billboards.html&label=Showcases), I also see

> Error: WebGL warning: texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.

and

> Error: WebGL warning: texSubImage2D: This operation requires zeroing texture data. This is slow.

In my (much more complex) application, I get tons of these warnings, until Firefox just gives up and stops warning.  I don't know if this is actually having a performance impact; Chromium does do a few FPS better than Firefox but that could be for other reasons.

(I have seen #1317 but if you click through to the Bugzilla link, they think that issue has been fixed, and would only account for one of the 3 warning types.)

**Comment by hpinkos** [comment]
Thanks @thw0rted!  I see this on my windows machine as well. 

@lilleyse do you know what this might be from?

**Comment by pjcozzi** [comment]
Good catch, thanks @thw0rted!

I suspect a new version WebGL 1.0.x version make these deprecations:

> Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

The other errors are like due to not calling `texImage2D ` before `texSubImage2D` - which Cesium _should_ do everywhere.

@bagnell do you want to look at this since @lilleyse has his hands full with your PRs. :)
