### ISSUE TITLE
Billboard image glitch on filled area

### ISSUE THREAD

**Issue by Levente0xFFFF** [AnalyticalGraphicsInc/cesium#5916]
Hello,
I use Cesium 1.38.
Let the code and the pictures speak:

![whole](https://user-images.githubusercontent.com/32195238/31763175-c7bab8d2-b4bd-11e7-8326-c47be81c5dbe.PNG)
![notwhole](https://user-images.githubusercontent.com/32195238/31763178-cd4f4114-b4bd-11e7-8684-ca71920beb39.PNG)

On the first picture I have NaturalEarth layer and the circles are full.
On the second picture I have NaturalEarth layer too, but its alpha is 0.0.
In case the first picture, only the country borders are visible (white), the "fill" is transparent.
For the second I set the fill to cornflowerblue.
The circles which have a number inside them are billboard images.

```
        private drawCountryBorders(stroke: Cesium.Color, fill: Cesium.Color) {
            if (this._countryBorders) {
                this._cesiumViewer.dataSources.remove(this._countryBorders, true);
            }

            var promise: any;
            promise = Cesium.GeoJsonDataSource.load('../Scripts/ne_110m_admin_0_countries.topojson', {
                stroke: stroke,
                fill: fill,
                strokeWidth: 5, // Windows can only draw 1 wide lines: https://stackoverflow.com/questions/25394677/how-do-you-change-the-width-on-an-ellipseoutlinegeometry-in-cesium-map/25405483#25405483
                markerSymbol: '?'
            });

            promise.then((dataSource) => {
                this._countryBorders = dataSource;
                this._cesiumViewer.dataSources.add(this._countryBorders);
            });
        }

        public switchToNaturalStyle() {
            this._isNaturalStyleActive = true;
            var viewer = this._cesiumViewer;
            viewer.scene.globe.baseColor = Cesium.Color.TRANSPARENT;
            viewer.scene.globe.imageryLayers.get(0).alpha = 1.0;
            viewer.scene.globe.enableLighting = true;
            viewer.scene.skyBox.show = true;
            viewer.scene.skyAtmosphere.show = true;
            viewer.scene.sun.show = true;
            viewer.scene.moon.show = true;
            this.drawCountryBorders(Cesium.Color.WHITE, Cesium.Color.TRANSPARENT);
        }

        public switchToClassicStyle() {
            this._isNaturalStyleActive = false;
            var viewer = this._cesiumViewer;
            viewer.scene.globe.imageryLayers.get(0).alpha = 0.0;
            viewer.scene.globe.enableLighting = false;
            viewer.scene.globe.baseColor = Cesium.Color.ALICEBLUE;
            viewer.scene.backgroundColor = Cesium.Color.WHITESMOKE;
            viewer.scene.skyBox.show = false;
            viewer.scene.skyAtmosphere = new Cesium.SkyAtmosphere();
            viewer.scene.skyAtmosphere.show = false;
            viewer.scene.sun.show = false;
            viewer.scene.moon.show = false;
            this.drawCountryBorders(Cesium.Color.WHITE, Cesium.Color.CORNFLOWERBLUE);
        }
```
If I load a .geojson instead of topojson, I have the same issue.

If I zoom more, or the angle is less, I can see the circles as full circles in the second case too, but in the first case even if the circles are far away or not perpendicular to the camera, the circles are fully visible.

Any ideas to fix this?

Regards,
Levente

**Comment by ggetz** [comment]
Hi @Levente0xFFFF, please ask questions like this over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

**Comment by Levente0xFFFF** [comment]
OK, give me your phone number so I can create a google account after you sent me the activation code...

**Comment by Levente0xFFFF** [comment]
Nice, so since google doesn't call back my desk phone, for me, it would be only possible to ask my question about Cesium if I go and by a new phone number. Hail Google!

**Comment by hpinkos** [comment]
Sorry about your technical troubles @Levente0xFFFF 
For your billboards, try using the [disableDepthDistance](https://cesiumjs.org/Cesium/Build/Documentation/Billboard.html?classFilter=bill#disableDepthTestDistance) property to keep them from going under the terrain

**Comment by Levente0xFFFF** [comment]
Wonderfully solved the issue!
**Thank you very much!** <3
