### ISSUE TITLE
WebGL rendering issue when minimizing and maximizing Chrome Version 62.0.3202.62 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by jschwepp** [AnalyticalGraphicsInc/cesium#5920]
When minimizing and maximizing the browser window WebGL crashes.

![chrome_2017-10-20_15-11-43](https://user-images.githubusercontent.com/32968215/31840381-cd39b842-b5aa-11e7-99db-94324f702f9f.png)
![chrome_2017-10-20_15-12-23](https://user-images.githubusercontent.com/32968215/31840383-d034b24a-b5aa-11e7-8569-3a1a0e4af244.png)

**Comment by hpinkos** [comment]
Hi @jschwepp.  I just updated Chrome and was unable to reproduce this.
What OS are you using?
Try clearing your cache/cookies to see if that fixed the problem.  Thanks!

**Comment by jschwepp** [comment]
This is on Windows 10 Enterprise version 1607 OS Build 14393.1715.  Already tried clearing cache and cookies.  Happening to multiple users.  Though, they do share the same laptop model which is a Lenovo P50.  I will test on a different computer when I have the chance.

**Comment by hpinkos** [comment]
Do you know what graphics card is on that laptop?

**Comment by hpinkos** [comment]
@jschwepp also, please go to http://webglreport.com/ from that laptop and let us know what you see on that page.  Thanks!

**Comment by jschwepp** [comment]
Video card is a Nvidia Quadro M2000M.  Users were having no problems with Cesium before the latest Chrome update.  

![image](https://user-images.githubusercontent.com/32968215/31841283-7af48fd6-b5ae-11e7-85e5-ceb914f73c50.png)
![image](https://user-images.githubusercontent.com/32968215/31841286-7f03923e-b5ae-11e7-9fc5-ac1542990e30.png)

**Comment by hpinkos** [comment]
@pjcozzi @bagnell any ideas here?

**Comment by mramato** [comment]
This is most likely a cut-and-dry missing check for `0` width or height in `GlobeDepth.update`

**Comment by mramato** [comment]
I randomly ran into this today, but can't consistently reproduce it.  Marking it for next release (I'll take a look before the end of the week).

**Comment by Doomelf** [comment]
@jschwepp I found a workaround on the internet that works. Go to Settings -> Advanced Settings and disable "Use hardware acceleration when available".

If this is not enough to fix the issue go to your Internet Settings -> Advanced -> Accelerated Graphics section and check "Use software rendering instead of GPU rendering".

**Comment by mramato** [comment]
@Doomelf, disabling hardware acceleration is definitely not a recommended solution for this.  It will ruin Cesium performance (and performance on many other websites as well).  It does help narrow this down to a possible driver bug.

@jschwepp can you find out the nvidia driver version and date that you are using?  It looks like the latest for that card is fairly recent.  If you go to chrome://gpu/ and search for `Driver vendor` you should find the relevant info.

Quadro cards actually have two drivers available (users choose which one they want):

"Enterprise" driver
http://www.nvidia.com/download/driverResults.aspx/125782/en-us

"New feature" driver
http://www.nvidia.com/download/driverResults.aspx/123914/en-us

I recommend the second one for Cesium.

**Comment by mramato** [comment]
I took another look at this and can't reproduce it on Windows (have seen it once on a questionable Linux driver).  I'll keep an eye out while we do release testing, but I don't think it needs to hold anything up.

**Comment by KlienCy** [comment]
I have the same problem.
-----------------------------
cesium : 1.39
WIN10 
chrome  62.0.3202.75（64）
video card : HD Graphics 630

**Comment by jschwepp** [comment]
It looks like this was due to a bug in Chrome.  As of 62.0.3202.94 (Official Build) (64-bit),  I am no longer seeing this problem.

This is the particular commit that addressed the issue:
https://chromium.googlesource.com/chromium/src/+/6c8832c6e3861b4070f864d923c2880e4d65d7c8

**Comment by hpinkos** [comment]
Thanks for the update @jschwepp!  Glad the problem is fixed
