### ISSUE TITLE
Test Failure: Scene/Expression throws if regex constructor has invalid pattern

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5927]
Windows 10 in Chrome 62.0

![image](https://user-images.githubusercontent.com/3451886/31905107-11f36ec2-b7fb-11e7-9d1f-9f1fa99ffe2b.png)

**Comment by mramato** [comment]
@ggetz, I think you're most familiar with this code?  Do you think you'll have time to take a look before the next release?  At least to make sure this isn't a bigger issue in styling.

**Comment by ggetz** [comment]
@mramato Sure, I'll take a look shortly.
