### ISSUE TITLE
pick   3dtile is wrong

### ISSUE THREAD

**Issue by gomap** [AnalyticalGraphicsInc/cesium#5929]
when i click  mouse  on 3dtile ,then code  dose not run  alert ,but feature  is not   undefined:

 var feature = viewer.scene.pick(click.position);
  if (feature instanceof Cesium.Cesium3DTileFeature) {
            alert("test")
  }

**Comment by lilleyse** [comment]
This seems to work on the [3D Tiles Feature Picking demo](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=3D%20Tiles%20Feature%20Picking.html&label=Showcases).

What does `console.log(feature)` say the feature is? Does your tileset contain features?

**Comment by gomap** [comment]
add  code   console.log(feature)   show these  messages :
{content: b, primitive: U}
content
:
b {_tileset: U, _tile: M, _url: "http://192.168.14.180/hf/Tile_+034_+015_+000_L18_000.b3dm?v=0.0", _model: xe, _batchTable: R, …}
primitive
:
U {_url: "http://192.168.14.180/hf", _basePath: "http://192.168.14.180/hf/?v=0.0", _tilesetUrl: "http://192.168.14.180/hf/tileset.json", _root: M, _asset: {…}, …}
__proto__
:
Object

**Comment by gomap** [comment]
sorry,i found the reason. the old  formate  of b3dm   is right . the new formate of my data may be not right ,but i can load them on view .

**Comment by lilleyse** [comment]
Ok I'll close this issue then. If you need help in the future head over to the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev.
