### ISSUE TITLE
Can I use the canvas as a layer to draw on earth?

### ISSUE THREAD

**Issue by tomhaitao** [AnalyticalGraphicsInc/cesium#5936]
Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by ggetz** [comment]
Hi @tomhaitao, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
