### ISSUE TITLE
How to highlight or locate the model.Node 

### ISSUE THREAD

**Issue by 9lovingly** [AnalyticalGraphicsInc/cesium#5941]
I met with the trouble about it.When I get the node objects by the way of "getNode()",at the same time I want to locate or highlight it to show where it is in the whole models.However I couldn't found any properties like color or x,y,z(lon lat height) just matrix.Therefore I hope some can give me some suggestion.
     node = model.getNode(id);
function createModel(id, url, height, lon, lat) {
    var scene = viewer.scene;
    var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(Cesium.Cartesian3.fromDegrees(lon, lat, height));
    var model = scene.primitives.add(Cesium.Model.fromGltf({
        id: id,
        name: id,
        color: Cesium.Color.fromAlpha(Cesium.Color.WHITE, parseFloat(1)),//viewModel.color viewModel.alpha
        url: url,
        modelMatrix: modelMatrix,
        allowPicking: true
    }));
    return model;
}

Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by lilleyse** [comment]
Changing the color of a single node in a model isn't possible right now. Depending on what your model is, it might make sense to convert it to [3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles) where individual features can be colored.

I'll close for now, but if you have more questions feel free to ask them on the [forum](http://cesiumjs.org/forum.html).

**Comment by 9lovingly** [comment]
Thanks Sir.by the way,what kind of tools do you use to convert it to 3D Tiles?

**Comment by ggetz** [comment]
Hi @9lovingly, please ask questions over on the forum. There's a [thread that discusses this question already](https://groups.google.com/forum/#!searchin/cesium-dev/convert$203d$20tiles%7Csort:date/cesium-dev/xLkYIuku9hA/L893wEmsDgAJ). Thanks!

**Comment by ViachaslauBohdan** [comment]
@lilleyse @ggetz is it possible now to change the color of a single node? If yes, how to achieve this?
