### ISSUE TITLE
npm  install err with sha1

### ISSUE THREAD

**Issue by Lx15** [AnalyticalGraphicsInc/cesium#5950]
Now , I am using the Cesium with 1.38. I run `npm install` after I downloaded the cesium zip . But I meet an err and i can't fix it . 
the version of node is V8.4.0 ,and npm is  5.3.0
the err is followed:
![err sreenshot](https://user-images.githubusercontent.com/14272220/32258381-2e47b91a-bef5-11e7-9d09-945d3872853f.png)
the err is happened when it extract clone@1.0.2

![err](https://user-images.githubusercontent.com/14272220/32258630-90c0a8f8-bef6-11e7-9ca4-5d465f6edb13.png)

**Comment by ggetz** [comment]
Hi @Lx15 ! Please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

[Building Cesium requires Node 6+.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md#build-the-code) Try [update Node.js](http://nodejs.org/).

**Comment by Lx15** [comment]
ok ... i'm sorry . and i solved this question by install sha module  by hands before run npm install.
