### ISSUE TITLE
Run buildApps during Travis build

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#5953]
It would be nice if Travis could run `buildApps` so Sandcastle links from branches would load laster. How much would this impact build time?

**Comment by ggetz** [comment]
This wouldn't be much longer, `buildApps` only takes a few seconds.

**Comment by mramato** [comment]
buildApps takes longer than a few seconds. (Sandcastle is fast, Viewer is slow).  I'm okay with building them but we need to make sure they do not end up in the deploy zip or npm package.

**Comment by mramato** [comment]
We specifically stopped building them because of time and deployment reasons, but that was when our build process only took a couple of minutes anyway.  We do a lot more these days so the overhead isn't a big deal.
