### ISSUE TITLE
RequestScheduler starves imagery requests for 3D Tiles

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5954]
The NYC demo loads all 3D Tiles tiles before loading any imagery.  This is really noticeable on slow connections or slower browsers (Firefox and Chrome throttles show the issue).

http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Picking.html&label=All

Our theory is that since the camera starts at the location of the tileset, the position of the root imagery tile is so far away that it loads it last in the queue.  We think something similar would happen with a large 3D tileset or terrain as well.

This makes some demos look really bad during load, but I'm not sure what the level of effort (or priority) for fixing this should be compared to other efforts.

CC @pjcozzi @lilleyse

**Comment by lilleyse** [comment]
Two ideas for fixing this:

* Create priority buckets based on request type (imagery, terrain, 3D Tiles)
* Prioritize by distance from bounding sphere rather than distance from the tile's center.

**Comment by hpinkos** [comment]
Not sure if it's related, but the same thing seems to happen to terrain.  Setting `RequestScheduler.throttleRequests = false;` fixes the issue

**Comment by mramato** [comment]
@hpinkos I would be really surprised if it weren't the same exact problem.

**Comment by lilleyse** [comment]
I think this might only be a problem in unbuilt versions of Cesium. Compare [built](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Styling.html&label=3D%20Tiles) with [unbuilt](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Styling.html&label=3D%20Tiles).

On the unbuilt version I see the imagery start to load in only after all the .js files have been loaded. Is imagery waiting on a web worker or something?

**Comment by lilleyse** [comment]
Though the priority ordering could still be better and I have a possible fix coming.

**Comment by mramato** [comment]
Terrain/Imagery is definitely waiting on a worker, but keep in mind that Chrome will only load so many files at a time, so the fact that JS files are being loaded is starving other requests too.  So I definitely expect performance to be worse with the unbuilt version.  This is one of the reasons we should always do profile/performance testing against the built version of Cesium; it's a huge difference.

**Comment by lilleyse** [comment]
Hm so I guess the problem is that 3D Tiles requests are fighting with JS requests, which means it takes longer for imagery to begin. Is that something that we can fix?

**Comment by mramato** [comment]
> Hm so I guess the problem is that 3D Tiles requests are fighting with JS requests, which means it takes longer for imagery to begin. Is that something that we can fix?

Not really (in code anyway). HTTP/2 fixes it because browsers will no longer limit to 6 requests at once.

**Comment by mramato** [comment]
This was pre-streaming overhaul and I would consider it OBE.
