### ISSUE TITLE
3D Tileset inspector "Show Picked Only" shows under the inspector

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5956]
If you look closely at the below image, you'll see the tile stats are showing under the inspector, rather than the location of the picked tile.

![image](https://user-images.githubusercontent.com/1495196/32292372-5c4d0556-bf16-11e7-9da7-8ed2a4268465.png)

This is only happens when "Show Picked Only" is selected.  I would expect the data to show up at the pick location instead.

http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Inspector.html&label=All

**Comment by lilleyse** [comment]
It shows up at the pick location for me. Hm..

**Comment by mramato** [comment]
I'm having trouble reproducing this as well (though clearly it happened since you can see it in the screenshot).  I'll close this and re-open if I can figure out how to easily reproduce.
