### ISSUE TITLE
Fullscreen fails in Angular (not your problem?)

### ISSUE THREAD

**Issue by CHBaker** [AnalyticalGraphicsInc/cesium#5970]
The full screen button inside cesium just paints the background of my page black,
and puts my page into full screen while the cesium container remains the same size.

Now I'm using the 'Angular-Cesium' npm package, so this might not be an issue with cesium.js, it could even be an Angular issue, just thought I'd ask.

my css:

```
#cesiumContainer {
    width: 100%;
    height: 720px;
    margin: 0; padding: 0;
    overflow: hidden;
}

.map-container {
    height: 720px;
    box-shadow: 4px 4px 7px #d2d2d2;
}
```

and my css settings:
`encapsulation: ViewEncapsulation.None`

**Comment by ggetz** [comment]
We do not officially support the `Angular-Cesium` package. 
 
You'll probably have more luck asking questions like this over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
