### ISSUE TITLE
cesium can add Local coordinate system？

### ISSUE THREAD

**Issue by duoduohappy** [AnalyticalGraphicsInc/cesium#5979]
cesium can add Local coordinate system？

**Comment by hpinkos** [comment]
Hello @duoduohappy,  sorry but we only support WGS84.  You will have to use another tool to convert your data to that coordinate system to use your data in Cesium.
In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for bug tracking and planning new features

**Comment by JimmingSong** [comment]
> Hello @duoduohappy, sorry but we only support WGS84. You will have to use another tool to convert your data to that coordinate system to use your data in Cesium.
> In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
> We use GitHub exclusively for bug tracking and planning new features

This axis has no arrow prompts
