### ISSUE TITLE
Incorrect documentation or implementation of cartesianToCartographic().height

### ISSUE THREAD

**Issue by keikland** [AnalyticalGraphicsInc/cesium#5987]
Hi,
I get current elevation with 
var elevation = Cesium.Ellipsoid.WGS84.cartesianToCartographic(viewer.camera.position).height;

In the docs, at https://cesiumjs.org/Cesium/Build/Documentation/Cartographic.html, it states for this property: 

height : Number Core/Cartographic.js 50
The height, in meters, above the ellipsoid.
Default Value:  0.0

It seems that the returned height is in fact in cm.  This is convenient for setting  a new position, which requires cm, but is obviously inconsistent with the documentation.   Just discovered this, and have not tried other eIlipsoids, so the issue could be isolated to WGS84.

Kjell

**Comment by ggetz** [comment]
Thanks @keikland ! 

All of our measurements are done in meters, the intended behavior would be the height to be specified in meters.

Do you have an example using sandcastle or code snippet, and your result vs the expected value perhaps? This would help us track things down.

**Comment by mramato** [comment]
@keikland the confusion here is probably the result of `viewer.camera.position` not being what you expect, that value is in the current reference frame of the camera and not necessarily in WGS84.  If you want to reliably get the camera is WGS84, use [viewer.camera.positionWC](https://cesiumjs.org/Cesium/Build/Documentation/Camera.html#positionWC) and your code will work in all cases.  However, in your exact use case you can just use [viewer.camera.positionCartographic.height](https://cesiumjs.org/Cesium/Build/Documentation/Camera.html#positionCartographic) to retrieve the height directly without having to call `cartesianToCartographic` yourself.

If you still believe this is a bug, please re-open the issue with a reproducible test case.  Thanks.

**Comment by keikland** [comment]
@mramato, thanks for getting back quickly, and the ***** help .  I did further testing yesterday and found inconsistencies in my own comment, with widely varying heights.  Use of the relevant and correct reference frame certainly explains the results, and the fix will definitely help.  In my case the logic is necessary to automatically save and restore view after restart, which otherwise already works nice for the position alone.  I'll try the height again now.

Kjell
