### ISSUE TITLE
Why cant my tiles been shown on cesium

### ISSUE THREAD

**Issue by wsf1990** [AnalyticalGraphicsInc/cesium#6000]
I create a viewer and add a layer which is provided by myself(the map server is akka).but I cant seen these map tiles and I can show cesium had load these tiles at console.The code like this:

```
var viewer = new Cesium.Viewer("cesiumContainer");
var layers = viewer.scene.imageryLayers;
var through = layers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({
    url : 'http://my_ip:8777/modis/ndvi/{z}/{x}/{y}.png',
    format: "image/png"
}));
through.alpha = 0.5;
```
And if I change the url to other map such as blackmarble, which will be load correctly(this correctly just means I can show the tiles but the position because the y which must be changed to reverseY).Dose any body konws why my map cant be load on the cesium?Thanks!

**Comment by hpinkos** [comment]
Hi @wsf1990,  please ask your question on the [cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).  That has much higher traffic so it is more likely that someone who has experienced a similar problem will be able to help you.  Thanks!

**Comment by wsf1990** [comment]
gotcha!thanks!
