### ISSUE TITLE
Billboard Images with transparent pixels have black borders

### ISSUE THREAD

**Issue by dominicrico** [AnalyticalGraphicsInc/cesium#6006]
Hey,

if my Billboard image has transparency in there it will be sometimes (and only in FireFox) shown with a black (flickering) border. Any ideas how to prevent this?

<img width="224" alt="bildschirmfoto 2017-11-28 um 11 54 03" src="https://user-images.githubusercontent.com/6437833/33316478-58fa6294-d434-11e7-99ad-db2da5bc659a.png">

CesiumJS version is 1.39.0 and 1.23.0 both have those borders.

**Comment by hpinkos** [comment]
Thanks @dominicrico!  This is a known issue: #4525
I'm closing this as a duplicate

**Comment by dominicrico** [comment]
@hpinkos sorry, didn't saw the issue.
