### ISSUE TITLE
Remove deprecated Credit parameters

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6014]
From #6005

Remove the `text`, `imageUrl` and `link` parameters in `Credit`

**Comment by Jahrkor** [comment]
is there a way to contribute with this project?

**Comment by hpinkos** [comment]
Hi @Jahrkor!  Thanks for your interest in contributing!
Yes, there are lots of ways to contribute. See our [contributing documentation](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md)
[Beginner](https://github.com/AnalyticalGraphicsInc/cesium/labels/beginner) issues are always a great place to start.

If you want to take a stab at this issue, we want to remove the deprecated parameters from [`Credit` ](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Credit.js#L33) before the next release on January 2nd.  We want to remove the `imageUrl` and `link` parameters and keep the `options` parameter instead.
