### ISSUE TITLE
Tooltip and entities clipped near 180 degrees longitude

### ISSUE THREAD

**Issue by mspencev** [AnalyticalGraphicsInc/cesium#6020]
In 2d mode one can observe the tooltip being clipped as you put your mouse just to the west of  180 degrees longitude in the demo linked below.  First pan the map to the left some so 180 is not right on the edge of the view.  My experience has been that entities get clipped too.

[https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Picking.html&label=Showcases](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Picking.html&label=Showcases)

**Comment by hpinkos** [comment]
Hi @mspencev, this is a known issue, see #3960
I'm going to close this issue as a duplicate but I'll make a comment that you reported this too so we can notify you when it's fixed. Thanks!
