### ISSUE TITLE
Globe Materials not compatible with enableLighting = false

### ISSUE THREAD

**Issue by YousefED** [AnalyticalGraphicsInc/cesium#6042]
Closely related to https://github.com/AnalyticalGraphicsInc/cesium/issues/6039, but use-case is different nevertheless so decided to open a separate issue (cc @lilleyse as he might be working on this already).

Steps to reproduce:
- https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Globe%20Materials.html&label=Showcases
- set ```viewer.scene.globe.enableLighting = true;``` on line 7

Result: shader compilation fails

Desired result: not have any time-of-day lighting effects, but still be able to use a globe material for slopes / heights.

**Comment by hpinkos** [comment]
Thanks @YousefED!  I thought we fixed this before we merged in globe materials, but we must have missed something.

@lilleyse @jasonbeverage I marked this as 'next release'.  If we have time, we should try to address this for 1.41

**Comment by lilleyse** [comment]
I plan on tackling this along with #6039

**Comment by pjcozzi** [comment]
Thanks again for the report @YousefED!  This is fixed in #6063.

For line 7, I think you mean set it to `false`, not `true`.  Let me know if I am mistaken.

Also, since globe materials are a new features, please post some screenshots if you are able to share your work; we would love to see it. 😄

**Comment by YousefED** [comment]
@pjcozzi correct.

I'm not using globe materials directly, but experimenting with code based on it to generate snow :):

![image](https://user-images.githubusercontent.com/368857/34201400-a4f9c2f6-e574-11e7-88d8-30526ac1e434.png)

**Comment by jasonbeverage** [comment]
That looks great!   We have a pretty nice "splatting" layer in osgEarth
that we could probably port to Cesium using globe materials.   Basically
you feed in a land use raster to the GPU and figure out what texture to
repeat based on the land use code (grass, rock, same, etc), the normal and
elevation.

Here's a screenshot of what it looks like in osgEarth

https://pbs.twimg.com/media/B1SsPThIIAAjIdD.jpg

**Comment by pjcozzi** [comment]
@YousefED very nice!!!  Also, check out some Cesium snow work my students did this past semester: https://github.com/HuYuxin/CIS565FinalProjectCesiumSnow/blob/master/CIS565FinalProjectREADME.md

@jasonbeverage contributions welcome, as always! 😄

**Comment by YousefED** [comment]
@pjcozzi awesome!! Are there more projects online? I missed the livestream (time difference)!

**Comment by pjcozzi** [comment]
Yes, they are all here: https://cis565-fall-2017.github.io/studentwork.html

**Comment by mogmog** [comment]
are there any code samples out there to do this kind of snowy rocky texture? That screenshot of @YousefED  looks amazing!
