### ISSUE TITLE
Multiple URL's  WebMapServiceImageryProvider

### ISSUE THREAD

**Issue by CHBaker** [AnalyticalGraphicsInc/cesium#6054]
Hello,

I have only found a few old posts of this question, and no solutions. So I apologize if this has been resolved already.

I have two sets of imagery data, and I'm trying to use the `addImageryProvider()` method, but it doesn't seem to be working.

I added one set of tiles directly to the instance of the `Cesuim.Viewer` `imageryProvider` options, and I got a blue globe from that. so it appears to be a step closer.

how can I add both sets directly to the view instance? for example:

```

imageryProvider: Cesium.createTileMapServiceImageryProvider({
    url: ['url1', 'url2']
    layers: ['layer1', 'places1']
    ...
)}

```

As of right now, I cannot get anything to load with my current code:
```
this.viewer = new Cesium.Viewer('cesiumContainer2',
      baseLayerPicker: false,
      geocoder: false,
      animation: false,
      fullscreenButton: false,
      vrButton: false,
      homeButton: true,
      infoBox: false,
      sceneModePicker: true,
      selectionIndicator: false,
      timeline: false,
      navigationHelpButton: true,
      navigationInstructionsInitiallyVisible: true

      // affects how multiple objects appear when on top of each other
      // orderIndependentTranslucency: false
    });

    const layers = this.viewer.scene.globe.imageryLayers;
    const imagery = new Cesium.WebMapServiceImageryProvider({
      url: 'http://reference2:15001/geowebcache/service/wms',
      layers: 'imagery',
      minimumLevel: 1,
      maximumLevel: 19,
      tileWidth: 512,
      tilesHeight: 512
    });

    layers.addImageryProvider(imagery);

    const places = new Cesium.WebMapServiceImageryProvider({
      url: 'http://reference2:15001/geowebcache/service/wms',
      layers: 'places',
      minimumLevel: 1,
      maximumLevel: 19,
      tileWidth: 512,
      tileHeight: 512
    });

    layers.addImageryProvider(places);
```

When I add the var imagery settings directly to the instance like this, i get a blue globe:

```
imageryProvider: Cesium.createTileMapServiceImageryProvider({
      url: 'http://reference2:15001/geowebcache/service/wms',
      layers: 'imagery',
      minimumLevel: 1,
      maximumLevel: 19,
      tileWidth: 512,
      tilesHeight: 512
}),
...
```

**Comment by hpinkos** [comment]
You might find this tutorial helpful: https://cesiumjs.org/tutorials/Imagery-Layers-Tutorial/
I don't see any problems with your code.  The only other problem I can think of is that there may be a CORS issue.  Make sure your imagery server has CORS enabled. https://enable-cors.org/

If you're still having trouble please ask questions like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
More people see posts there so it is more likely someone will be able to help.  We use GitHub exclusively for bug tracking and planning new features.

**Comment by CHBaker** [comment]
CORS issue, thanks @hpinkos
