### ISSUE TITLE
Some tiles disappear after switching to and from 2d mode

### ISSUE THREAD

**Issue by Vineg** [AnalyticalGraphicsInc/cesium#6056]
We have a 3dTiles model which gets corrupted after switching to 2d mode and then back to 3d. Some DrawCommands seem to have wrong BoundingSphere center and not being rendered.
Can you take a look at https://github.com/AnalyticalGraphicsInc/cesium/blame/b0939bf96697ec8c51cc32b8b96c5ed79b94a71a/Source/Scene/Model.js#L3798
It seems that when we switch back to 3d, model._rtcCenter not gets switched back to _rtcCenter3D

**Comment by pjcozzi** [comment]
Thanks for the report @Vineg.  This is a duplicate with #5955.  I'll add your note there.  Keep an eye on it.
