### ISSUE TITLE
Locations far away from equator looks stretched in 2d mode

### ISSUE THREAD

**Issue by Vineg** [AnalyticalGraphicsInc/cesium#6057]
I propose using classic Mercator projection instead of Miller to avoid stretching
![stretched](https://user-images.githubusercontent.com/1757455/34038743-7180d718-e19e-11e7-83bc-eafbbe9674d0.png)

**Comment by mramato** [comment]
@Vineg in the future, please ask questions like this on [our forum](https://cesiumjs.org/forum/) first.  It will usually get a faster reply and we also try to reserve GitHub issues for confirmed bugs and feature requests.

As for your request, Cesium supports Geographic (default) and WebMercator  projections.  To use WebMercator, simply pass it into the Viewer or Widget constructor:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer',
                               { mapProjection : new Cesium.WebMercatorProjection() });
```

#3877 already covers the feature request to add additional projection types, but this gets fairly complicated on anything other than an empty map so it will most likely be some time before we get to it.
