### ISSUE TITLE
Change color button doesn't work in Globe Materials Sandcastle example

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6058]
http://localhost:8080/Apps/Sandcastle/index.html?src=Globe%20Materials.html&label=All

Clicking on it doesn't bring up anything in Chrome or Firefox.

If this is a trivial fix, can we fix it for 1.41?

**Comment by lilleyse** [comment]
I can look at this one as well before the release.

**Comment by bagnell** [comment]
This works for me. It only changes the color of the contour lines. Is it supposed to change any other color?

**Comment by hpinkos** [comment]
Yeah it's only supposed to change the contour color. If the UI isn't obvious maybe disable or hide the button when contour is disabled

**Comment by pjcozzi** [comment]
Yes, disable or rename to make it explicit.
