### ISSUE TITLE
How to realize snow\rainning particle effect?

### ISSUE THREAD

**Issue by 9lovingly** [AnalyticalGraphicsInc/cesium#6072]
Recently I'd like to add some snow or rainning effect on my 3D system using cesium.However I just found the example of fireworks.Anyone can help me?Thanks!

Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by hpinkos** [comment]
Hello @9lovingly, please ask questions like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for bug tracking and planning new features
