### ISSUE TITLE
3D Models Sandcastle - shader linker error in IE

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6077]
This is blocking the 1.41 release; this works in 1.40.

http://localhost:8080/Apps/Sandcastle/index.html?src=3D Models.html&label=All

![image](https://user-images.githubusercontent.com/782098/34486398-ceff4a70-ef9d-11e7-8ef5-16e8fe47f5fd.png)

Works in other browsers.

@ggetz @lilleyse?

**Comment by lilleyse** [comment]
The demo works for me in IE. Version 11.64.16299.0.

**Comment by ggetz** [comment]
I also cannot duplicate in IE 11.0

**Comment by pjcozzi** [comment]
Thanks for looking.

This is IE 11.0.96 on Windows 7 with auto updates.  I will check NVIDIA drivers.

**Comment by pjcozzi** [comment]
Updated to 386.01 driver for NVIDIA Quadro K2100m - linking still fails - this is likely the IE version.

We could still ship 1.41, but I don't know how widely used this version of IE is.  What is new with the **generated** glTF shaders between 1.40 and 1.41?  Is something from clipping planes included even when that are not enabled?  Did gltf-pipeline change how shaders are generated from PBR materials?

**Comment by pjcozzi** [comment]
Discussed offline with @lilleyse.  Will just disable the clipping plane code when generating shaders for 3D Models and the Globe, and comment in the Sandcastle example and reference doc that clipping planes are not currently supported in IE.

CC @ggetz

**Comment by ggetz** [comment]
Updated in #6079
