### ISSUE TITLE
Annotate doesn't work in IE in 3D Tiles Interactivity Sandcastle example

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6078]
http://localhost:8080/Apps/Sandcastle/index.html?src=3D Tiles Interactivity.html&label=All

The annotation does not appear.  I don't think this requires any WebGL extensions that would not be supported in IE.  It works in the other browsers.

The other right click actions - "Print metadata" and "Zoom to feature" - work in IE.

**Comment by lilleyse** [comment]
Annotation is the only one that uses `pickPosition` and IE doesn't support depth textures, so I think this is somewhat expected.

**Comment by pjcozzi** [comment]
OK, labeling this as `beginner` and `doc` - a comment in the Sandcastle example would be fine.
