### ISSUE TITLE
There is a bug in Lon/Lat graticule plug-in  in 2D mode

### ISSUE THREAD

**Issue by 834897006** [AnalyticalGraphicsInc/cesium#6100]
This page's plugin only supports 3D mode（https://github.com/leforthomas/cesium-addons），In 2D mode, the latitude and longitude lines of the central area will disappear

**Comment by hpinkos** [comment]
@834897006 sorry, but that plug-in is not developed or maintained by the Cesium team.  I would recommend filing an issue in that repository if there is a bug.

Thanks!
