### ISSUE TITLE
 Add billboard crash with  globe :false option

### ISSUE THREAD

**Issue by zwzhlj100000** [AnalyticalGraphicsInc/cesium#6109]
Add billboard crash without globe. 

var viewer = new Cesium.Viewer('cesiumContainer',{globe:false});
viewer.entities.add({
        position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
        billboard :{
            image : '../images/Cesium_Logo_overlay.png'
        }
    });

**Comment by ggetz** [comment]
Thanks for the report @zwzhlj100000, addressed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6110
