### ISSUE TITLE
how to define  the cutting clippingPlanes ?

### ISSUE THREAD

**Issue by c-y-q** [AnalyticalGraphicsInc/cesium#6117]
as shown in the figure,The tangent is a quadrilateral ,what should I do to change it to a triangle or any other figure?  Is it the following code content?

code:  
 var clippingPlanes = [
        new Cesium.Plane(new Cesium.Cartesian3(0.0, 0.0, 1), 150.0)
    ];

    tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
        url : url,
        clippingPlanes : new Cesium.ClippingPlaneCollection({
            planes : clippingPlanes,
            edgeWidth : viewModel.edgeStylingEnabled ? 1.0 : 0.0
        })
    }));
-----------------------------------------------------------
I don't know how to make the data in cartesian3 ,can you give some good advice?
![ploynoe](https://user-images.githubusercontent.com/24750024/34932279-37b24fda-fa0d-11e7-91f9-abfbab32ca90.png)

**Comment by ggetz** [comment]
Hi @c-y-q , please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. 

The `Cartesian3` in the previous code snippet is used to define the direction of the plane, and should be normalized. Take a look at the [`Plane`](https://cesiumjs.org/Cesium/Build/Documentation/Plane.html?classFilter=plane) documentation.

The "quadrilateral" is a PlanePrimitive, and is just used to represent the clipping plane location. You don't need to use it.
