### ISSUE TITLE
Remove deprecated properties from the adding of the Resource class

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#6119]
Remove functions:
- [ ] `loadImage`
- [ ] `loadArrayBuffer`
- [ ] `loadblob`
- [ ] `loadImageViaBlob`
- [ ] `loadJson`
- [ ] `loadJsonp`
- [ ] `loadText`
- [ ] `loadWithXhr`
- [ ] `loadXML`

Removed deprecation of parameters:
- [ ] `loadCRN`
- [ ] `loadKTX`
- [ ] `ArcGisMapServerImageryProvider`
- [ ] `BingMapsImageryProvider`
- [ ] `GoogleEarthEnterpriseMapsProvider`
- [ ] `GoogleEarthEnterpriseImageryProvider`
- [ ] `MapboxImageryProvider`
- [ ] `SingleTileImageryProvider`
- [ ] `UrlTemplateImageryProvider`
- [ ] `WebMapServiceImageryProvider`
- [ ] `WebMapTileServiceImageryProvider`
- [ ] `createOpenStreetMapImageryProvider`
- [ ] `createTileMapServiceImageryProvider`
- [ ] `ImageryProvider`
- [ ] `CesiumTerrainProvider`
- [ ] `GoogleEarthEnterpriseTerrainProvider`
- [ ] `GoogleEarthEnterpriseMetadata`
- [ ] `Model`
- [ ] `Cesium3DTileset`
- [ ] `CzmlDataSource`
- [ ] `KmlDataSource`

`Resource` class cleanup
- [ ] `loadImage` method - `allowCrossOrigin` parameter.
- [ ] `createIfNeeded` method can probably have the options parameter removed. It was there to more easily handle URL strings with a bunch of options specified to the parent classes instead of the to the `Resource`. Removing all these deprecated properties should remove the need for it.
- [ ] Move all the specs for the `load*` functions to the specs for the `Resource` class.

**Comment by thw0rted** [comment]
@tfili you closed this but createOpenStreetMapImageryProvider still takes a `string` for the URL, meaning you can't load it through a proxy.  I can open a separate issue if you like.

**Comment by tfili** [comment]
@thw0rted Just looking at it quickly, I think it should work if you pass a `Resource` instance in as the url. It should just be a documentation tweak, if you want to write up an issue or open a PR.

**Comment by thw0rted** [comment]
Looks like somebody beat you to it in #8079.  Maybe @ProjectBarks would like to update the docs to match the fixes he made?  I'll drop a comment there.
