### ISSUE TITLE
Inconsistent naming between BingMapsApi and MapboxApi when defining the key

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#6130]
Currently you have:
```
BingMapsApi.defaultKey
MapboxApi.defaultAccessToken
```
Imho both should have same name (`defaultKey` or `defaultAccessToken`)

**Comment by ggetz** [comment]
I believe the naming in based on the provider's terminology:

Mapbox Access Tokens: https://www.mapbox.com/help/how-access-tokens-work/
Bing Key: https://msdn.microsoft.com/en-us/library/ff428642.aspx

**Comment by mramato** [comment]
I agree with @ggetz.

**Comment by hpinkos** [comment]
Yes, @ggetz is correct.  Thanks for keeping an eye out though, @SunBlack!
