### ISSUE TITLE
is there any method to clip more than one model by ClippingPlaneCollection

### ISSUE THREAD

**Issue by wlhm1984** [AnalyticalGraphicsInc/cesium#6135]
i try to use ClippingPlaneCollection clip some bad tiles on 3dtiles, but plane can not set size ,is there any methods？thanks

**Comment by hpinkos** [comment]
Hello @wlhm1984.  Sorry, I'm not quite sure what you're asking.  Each 3D tileset can have a clipping plane collection which clips all features on the side of the plane where the normal is pointing for that tileset.

Please ask you question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

We use GitHub exclusively for tracking bugs and planning new features.  The forum has higher traffic so it is more likely that someone can help answer your question. Thanks!
