### ISSUE TITLE
3D Tiles Point Cloud Classification demo broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6142]
Looks like this hasn't shipped yet, but it doesn't work in master: http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Point%20Cloud%20Classification.html&label=Showcases

You get `Invalid tile content`

The url in the comment to https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/vector-tiles/TileFormats/Geometry is also 404.

@bagnell any ideas?

**Comment by mramato** [comment]
It's also possible that this could be a data issue.  I don't think ion is set up to support geom tiles, so the data may not have the proper headers.  @bagnell is `geom` a new payload type?

**Comment by lilleyse** [comment]
Yes `geom` is new. Also `vctr` is new if that's not yet handled.

I didn't notice that when we merged the vector tiles spec it went into the `3d-tiles-next` branch. I opened a PR to merge it into master, if that's what we want. https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/279

**Comment by lilleyse** [comment]
The demos used to work, so I think this is a data issue.

**Comment by mramato** [comment]
OK, I'll take a stab at addressing this on my end then.

**Comment by mramato** [comment]
This is fixed on the server side, if you're having problems; clear your cache.

@lilleyse thanks for fixing the links.
