### ISSUE TITLE
Support KHR_technique_webgl extension for glTF

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6149]
@ggetz @lilleyse for after Draco, #5120

Please track and participate as needed in the spec discussion here: https://github.com/KhronosGroup/glTF/issues/1217

Update both Cesium and gltf-pipeline.

**Comment by pjcozzi** [comment]
@ggetz OK to close this?

**Comment by OmarShehata** [comment]
@ggetz it looks like the extension was renamed from `KHR_technique_webgl` to `KHR_techniques_webgl` at some point, (it doesn't have the `s` [in 1.49](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.49/Source/Scene/ModelUtility.js#L145)) but I don't see a breaking change announcement for it in changes.md. 

This is breaking some people's tilesets (see [forum thread](https://groups.google.com/d/msg/cesium-dev/NYH3XKk-cF0/oYc31ieJBAAJ)). Should we just check for both or should we have had a deprecation period? I'm not sure what all went into this rename so apologies if I'm missing some context here.

**Comment by ggetz** [comment]
The extension name itself changed after he initial draft. They should update their tilesets since it's no longer valid. I think checking ad throwing a `oneTimeWarning` which we eventually remove would work. @lilleyse sound good?

**Comment by OmarShehata** [comment]
I just spoke with @lilleyse offline, and it sounds like even though it was in 1.49, it was never officially supported, and that it's not just a naming change, that the old tilesets wouldn't really work out of the box, so it shouldn't be something we can support. 

Perhaps the best course of action here is to update those old tilesets with [obj2gltf](https://github.com/AnalyticalGraphicsInc/obj2gltf) ? (Assuming the source obj still exists).
