### ISSUE TITLE
Spruce up CHANGES.md

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6162]
Some of the Cesium releases are getting big enough to justify a bit more organization and style in CHANGES.md.

For example, I like the emojis, sections, and new identifier highlighting in turf: https://github.com/Turfjs/turf/blob/master/CHANGELOG.md

No need to update previous releases, just pilot this on a new one.

**Comment by ggetz** [comment]
Updated in 1.42: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md

**Comment by pjcozzi** [comment]
Looks good, but I would still keep breaking changes and deprecation together, perhaps both right under highlights.
