### ISSUE TITLE
Exception when calling TimeInterval.fromIso8601

### ISSUE THREAD

**Issue by tamarmot** [AnalyticalGraphicsInc/cesium#6164]
Sample date string: "2020-08-29T00:00:00+00:00"
I can call:
JulianDate.fromIso8601 with success
When I try to call 
Cesium.TimeInterval.fromIso8601({iso8601:"2020-08-29T00:00:00+00:00"});
I get an exception: Invalid ISO 8601 date.

**Comment by shunter** [comment]
Time intervals contain two ISO dates separated by slash:

https://en.wikipedia.org/wiki/ISO_8601#Time_intervals

Arguably the error message could be better.

**Comment by hpinkos** [comment]
Let's add a link to https://en.wikipedia.org/wiki/ISO_8601#Time_intervals in the doc for `TimeInterval.fromIso8601`, and throw a `DeveloperError` if `options.iso8601` does not contain a `'/'`.

**Comment by tamarmot** [comment]
Thanks, that's helpful.
