### ISSUE TITLE
Imagery Layers Manipulation Sandcastle example doesn't load

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6168]
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Imagery%20Layers%20Manipulation.html&label=undefined

![image](https://user-images.githubusercontent.com/782098/35485077-fb0595c2-0427-11e8-89f5-704dfad8c663.png)

**Comment by ggetz** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6112
