### ISSUE TITLE
Convert DAE to GLTF 2.0 for Cesium with COLLADA2GLTF 2.0 Branch

### ISSUE THREAD

**Issue by KermMartian** [AnalyticalGraphicsInc/cesium#6173]
Due to a requirement to switch to using GLTF 2.0 models for other parts of our software, we gave KhronosGroup/COLLADA2GLTF/, branch 2.0 a try to convert DAE to GLB for CesiumJS (and our own Geopipe/gltf2glb to pack the resulting GLBs into B3DMs, then CMPTs, but that another discussion). https://gltf-viewer.donmccurdy.com/ is able to load the resulting GLBs, modulo warnings that we haven't made image dimensions powers of 2 yet, but Cesium appears unable to load either the GLBs or CMPTs made from these GLBs. We specified the -b (binary) and -e (embed) flags to COLLADA2GLTF. I know that in the past we had to use the "KHR_binary_glTF" extension on our buffers in GLTF 1.0 GLBs; I'm hoping no such specific changes are necessary now. Thanks in advance for any help you may be able to offer, and I'm happy to provide sample files and a MWE as necessary.

**Comment by pjcozzi** [comment]
@KermMartian sample models and anything you can do to narrow down the issue, including checking the models with the [glTF validator](https://github.com/KhronosGroup/glTF-Validator), would be appreciated.

The list of working / not working glTF sample models may also provide some insights: https://github.com/cx20/gltf-test/

**Comment by KermMartian** [comment]
This turned out to be a two-part problem. Part 1 was that we weren't on the tip of the master branch of Cesium. Part 2 is a direct result of what turns out to already be known as KhronosGroup/COLLADA2GLTF/issues/123 ; feel free to either close this if appropriate, or I can close it once we submit a PR that resolves that COLLADA2GLTF problem.

**Comment by pjcozzi** [comment]
Thanks for looking into this @KermMartian!  We'll close this one and look forward to your COLLADA2GLTF pull request.
