### ISSUE TITLE
Is there any documents to guide to new learner?

### ISSUE THREAD

**Issue by xuetao72** [AnalyticalGraphicsInc/cesium#6174]
Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by conradlempert** [comment]
nice issue bro

**Comment by hpinkos** [comment]
@xuetao72 check out our getting started tutorial: https://cesiumjs.org/tutorials/cesium-up-and-running/

And if you have any questions, please post on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for planning new features and tracking bugs. Thanks!

**Comment by xuetao72** [comment]
@hpinkos @conradlempert thanks!
