### ISSUE TITLE
ArcGisMapServerImageryProvider-A tile that cannot access the proxy address.

### ISSUE THREAD

**Issue by Moonkan** [AnalyticalGraphicsInc/cesium#6186]
ArcGisMapServerImageryProvider
When I use the Intranet to access the external network address of the agent, the map will not come out, but I can access the pictures alone according to the tile website. Please help me.

this.viewer.imageryLayers.addImageryProvider(new Cesium.ArcGisMapServerImageryProvider({
            //url: "//222.247.40.204:6080/arcgis/rest/services/yingxiang/MapServer",//Original network address

            url: "192.168.1.20:999/arcgis/rest/services/yingxiang/MapServer",//Internal network proxy address.

            rectangle: rectangle,
            enablePickFeatures:false
        }))

**Comment by SelimAbidin** [comment]
I checked the map service with version 1.42.
The error says
"Tile spatial reference WKID 4490 is not supported."

**Comment by Moonkan** [comment]
but,I add the WKID  4490 in cesium, The outside net succeeds, but the inside net agent this outside net can not succeed.

**Comment by SelimAbidin** [comment]
I just noticed your intranet port is different than the public one. Can it be CORS problem? 
Is it possible to share more detail such as Developer console Network data?

**Comment by hpinkos** [comment]
I'm not sure what the problem is @Moonkan.  Please ask your question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev 
Many more people see questions on the forum so it is more likely that someone will be able to help.

We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
