### ISSUE TITLE
Imagery stops loading when changing terrain in request render mode

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6193]
![image](https://user-images.githubusercontent.com/3451886/35931626-24e50570-0c03-11e8-8d58-af35bbe084de.png)

Easiest way to reproduce
- Zoom in close to the ground and hit the `Disable terrain` button until the imagery stops loading in  (usually 2-5 clicks)
- Hit the `Enable terrain` button
- Now the imagery never loads in, even after the camera moves

I wasn't able to reproduce this when `requestRenderMode: false`, so it seems to be related to those changes.
It seems like it might be related to changing the terrain before all imagery tiles are loaded, but I'm not sure.

``` js
var viewer = new Cesium.Viewer('cesiumContainer', {
    requestRenderMode : true,
    animation: false,
    timeline: false
});

var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles',
    requestWaterMask : true,
    requestVertexNormals : true
});
viewer.terrainProvider = cesiumTerrainProviderMeshes;

Sandcastle.addToolbarButton('Enable terrain', function() {
    viewer.terrainProvider = new Cesium.CesiumTerrainProvider({
        url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles',
        requestWaterMask : true,
        requestVertexNormals : true
    });
    viewer.scene.requestRender();
});

Sandcastle.addToolbarButton('Disable terrain', function() {
    viewer.terrainProvider = new Cesium.EllipsoidTerrainProvider();
    viewer.scene.requestRender();
});
```

**Comment by hpinkos** [comment]
@ggetz any ideas here?  Let me know if you have trouble reproducing it

**Comment by ggetz** [comment]
@hpinkos I can reproduce, but I need to take a closer look to see what's causing this.

**Comment by hpinkos** [comment]
@ggetz while it's not as bad, I'm definitely still seeing problems with this.  Please look into it further for next release.  Thanks!

**Comment by mramato** [comment]
@hpinkos can you list steps to still reproduce this.  I know we fixed the initial issue, but we should really fix this completely as reliability is really important when using requestRender.

**Comment by hpinkos** [comment]
@mramato I'll have to trace what's going on in composer to figure out a way to reliably reproduce it.  It's really easy to reproduce in that application but difficult to reproduce with the sandcastle example I put together.

**Comment by lilleyse** [comment]
This likely won't make it into 1.44 but I've leave the next release label.

**Comment by mramato** [comment]
@hpinkos, @ggetz is this still planned for May 1st?  If not, we really need to fix it for June 1st.

**Comment by hpinkos** [comment]
Sorry, didn't have time to look into it this month

**Comment by ggetz** [comment]
I think this will need to be bumped to next month, I need the steps to reproduce this.

**Comment by ggetz** [comment]
@hpinkos Could you take a look at providing steps to reproduce?

**Comment by hpinkos** [comment]
@ggetz yes, this is next on my list as soon as I wrap up the few features I'm working on

**Comment by hpinkos** [comment]
Probably not going to have a chance to look at this for the July release, but I'll have a reproducible example ASAP so we can fix this for the August release

**Comment by hpinkos** [comment]
Well, I actually can't reproduce this anymore.  @mramato reopen this if you still see it
