### ISSUE TITLE
CZML Image Material Broken?

### ISSUE THREAD

**Issue by weatherdrew** [AnalyticalGraphicsInc/cesium#6199]
Greetings Cesium Folks!

As of CesiumJS 1.42, I am seeing some strange behavior with previously working Image Material rendered via CZML. I have also noticed this is occurring in the Cesium Sandcastle example below:

[Sandcastle with missing Cesium logo](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=CZML%20Rectangle.html&label=CZML)

The polygon renders correctly and the default white texture appears. However, previous versions would asynchronously load the referenced "uri" element and overlay the image. This seems to have stopped with 1.42 based on my tests (1.41 behavior not apparent).

Here is my CZML for reference, which I believe is correct and has not changed between the previous releases of Cesium since Fall 2017:

`[{"id":"document","version":"1.0"}, {"name":"data-Base_Reflectivity_L2","position":{"cartographicDegrees":[-86.5625,36.2472229004,1.0]},"ellipse":{"semiMinorAxis":299875.0,"semiMajorAxis":299875.0,"height":10.0,"outline":true,"material":{"image":{"transparent":true,"image":{"uri":"http://data.horizonwx.com/kohx/Base_Reflectivity_L2/1508163444.png"}}}}}]`

I've attached screen grabs from my development environment and the sandcastle.

If I'm missing something, or if there is now a new syntax to follow for overlaying materials on polygons in CZML I'm happy to adjust. 

Thanks!

![screen shot 2018-02-08 at 17 22 56](https://user-images.githubusercontent.com/31680472/36003744-edb9d6fa-0cf4-11e8-8570-eeb131f3c556.png)

![screen shot 2018-02-08 at 17 23 21](https://user-images.githubusercontent.com/31680472/36003748-f0add820-0cf4-11e8-943f-fe08c0913284.png)

**Comment by hpinkos** [comment]
Thanks for reporting this @weatherdrew.  I can reproduce this bug.  I've marked this `next release` since it's a regression.

@tfili is this related to your `Resource` changes?  Image materials work through the entity API but not through this CZML example

**Comment by weatherdrew** [comment]
No problem @hpinkos - glad to help, and I appreciate the great work you guys are doing!

**Comment by tfili** [comment]
@hpinkos Yep. I'm looking at it now.
