### ISSUE TITLE
ImageryLayerCollection move proposal

### ISSUE THREAD

**Issue by jeanpul** [AnalyticalGraphicsInc/cesium#6200]
Hi,

This is my first submission so first at all I want to thanks the devs for this great tool !

Cesium: 1.42.1

I do not want to create a pull request because I think is too short. In one of my project I needed
to reorder the Layer in the ImageryLayerCollection but I did not find any move(src, dst) method so here is the code I use :

```
Cesium.ImageryLayerCollection.prototype.move = function (layer, toIndex) {    

  var index = this._layers.indexOf(layer);
  if (index == -1 || index == toIndex || toIndex <0 || toIndex > (this._layers.length - 1)) {
    return;
  }

  this._layers.splice(index, 1);
  this._layers.splice(toIndex, 0, layer);

  this._update();

  this.layerMoved.raiseEvent(layer, toIndex, index);  
};

```
It would be great if this could be in some future release.

Regards

**Comment by ggetz** [comment]
Hi @jeanpul, welcome!

Gnerally, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively.

While there is indeed no `move` function, we have [`raise`/`lower`](https://cesiumjs.org/Cesium/Build/Documentation/ImageryLayerCollection.html#lower) methods in `ImageryLayerCollection`. If move is a function you'd like to see, please [contribute](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md) and open a PR with your changes! This isn't too short at all.
