### ISSUE TITLE
Specs have deprecation warnings

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6202]
The specs use things like `loadWithXhr` and `loadImage` all over the place so now there are a bunch of deprecation warnings.

Marking this 'next release' because it should have been addressed in #6138

@tfili please take a look at this when you get a chance

**Comment by tfili** [comment]
I was told to leave the tests for the deprecated functions. There is an issue (#6119) to move all the `load*` tests into the `Resource` tests when they are removed. I should at least remove their usage in other tests.

**Comment by hpinkos** [comment]
> I should at least remove their usage in other tests.

Thanks, yeah I agree.

**Comment by mramato** [comment]
There's no reason for this to be next release, it can just be done when the deprecated functions are removed.  This is standard practice for us, it just so happens that there are a lot of deprecating functions this time around.

**Comment by hpinkos** [comment]
I don't know, every time I've deprecated something I've had to remove use of the deprecated function from the specs.

**Comment by mramato** [comment]
Yes, we try and remove usage in tests outside of the tests for the deprecated functionality itself, but we don't always catch them all.  It's harmless for now and like I said will just come out when we actually remove the deprecated functionality.  `priority - next release` should be reserved for things that actually impact the next release, this doesn't.
