### ISSUE TITLE
Resource instance fetch() throws when called with no arguments

### ISSUE THREAD

**Issue by thw0rted** [AnalyticalGraphicsInc/cesium#6206]
Run [this Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=a8f1a5f7f1bfa865caca6768606dae9c), check the (actual, browser) console.  You will see

> Cannot add property method, object is not extensible

Somebody, somewhere, is freezing the return value from `defaultClone` before `options.method` is assigned [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.42/Source/Core/Resource.js#L1107), only in the case where `options` is undefined.  As you can see in the example, passing an empty object works around this.  The cheap fix would be to change L1106 to `options = defaultClone(options || {}, defaultValue.EMPTY_OBJECT);` but it would probably be more helpful in the long run to ensure that defaultClone can never return a frozen object.

Also, in filing this issue, I discovered that your sample data for the "GeoJSON and TopoJSON" Sandcastle demo is missing -- just open that page and try to click any button, you should get a 404.

**Comment by hpinkos** [comment]
Thanks @thw0rted!  I've submitted a PR to fix this here: https://github.com/AnalyticalGraphicsInc/cesium/pull/6210
