### ISSUE TITLE
Dynamically loading GeoJSON data

### ISSUE THREAD

**Issue by Yakitrak** [AnalyticalGraphicsInc/cesium#6207]
I am loading GEOJSON data from a server using a get request. It will currently load it for the whole globe, which is fine for smaller datasets but it crashes for larger datasets. Is it possible to load data for the tiles currently on screen only? So as the user moves the map around, more data for the layer is loaded dynamically?

**Comment by hpinkos** [comment]
Hello @Yakitrak,
As far as I know, GeoJSON does not have this capability.  If you have large datasets, I would recommend converting your data to 3D tiles: https://github.com/AnalyticalGraphicsInc/3d-tiles
3D tiles was specifically designed for dynamically loading data based on what is on screen.

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
