### ISSUE TITLE
PointGraphics heightReference crash

### ISSUE THREAD

**Issue by jmack2424** [AnalyticalGraphicsInc/cesium#6213]
When attempting to clamp a Cesium.CustomDataSource entity to ground:
{
      id: id,
      name: name,
      position: cartesian,
      description: desciption,
      point: {
        pixelSize: 6,
        color: color,
        outlineColor: Cesium.Color.WHITE,
        outlineWidth: 2,
        heightReference: 1,
      },
      label: {
        text: name,
        horizontalOrigin : Cesium.HorizontalOrigin.CENTER,
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM,
        font: '12pt roboto',
        style: Cesium.LabelStyle.FILL_AND_OUTLINE,
        outlineWidth: 4,
        pixelOffset: new Cesium.Cartesian2(0, -9),
        disableDepthTestDistance: Number.POSITIVE_INFINITY,
        heightReference: 1,
      }

Including the "heightReference" on the point crashes Cesium. Binding to GeoJsonDataSource or CzmlDataSource works, but there is no way to clamp the custom PointGraphics object to the terrain without crashing Cesium.

Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Cesium 1.37

**Comment by hpinkos** [comment]
@jmack2424 can you please paste a complete code example that reproduces the crash in Sandcastle? https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/

Thanks

**Comment by jmack2424** [comment]
Hannah, we found our issue, and forcing it to work in the Sandcastle helped us to find it. =)

Our custom data points were being serialized, which broke on the load call, because the Cesium references in the custom object could not be resolved.

**Comment by hpinkos** [comment]
Thanks @jmack2424, glad you were able to figure it out =)
