### ISSUE TITLE
Cesium3DTileset immediatelyLoadDesiredLevelOfDetail test failure

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6221]
I haven't been able to reproduce this locally, but this test is intermittently failing in travis

```
1) immediatelyLoadDesiredLevelOfDetail
     Scene/Cesium3DTileset
     Expected 2 to be 1.
    at Specs/Scene/Cesium3DTilesetSpec.js:2669:70
    at i.then (Build/Cesium/Cesium.js:471:19284)
    at Build/Cesium/Cesium.js:471:19841
    at m (Build/Cesium/Cesium.js:471:21223)
```

https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/341544905
https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/341516554

**Comment by hpinkos** [comment]
@lilleyse any ideas here?

**Comment by hpinkos** [comment]
Nope, guess that didn't fix it.  https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/344548142

**Comment by hpinkos** [comment]
Ignored this test in #6255 until we figure out what the problem is

**Comment by lilleyse** [comment]
I added the test back in for https://github.com/AnalyticalGraphicsInc/cesium/pull/6390. Hopefully it consistently passes once that PR is in.

**Comment by lilleyse** [comment]
I haven't seen this test fail since #6390. It should be fine to close this now.
