### ISSUE TITLE
CESIUM_BASE_URL ignored in 1.42

### ISSUE THREAD

**Issue by mreilaender** [AnalyticalGraphicsInc/cesium#6225]
Setting the `CESIUM_BASE_URL` like below breaks Cesium (**v1.42**). It seems to be completely ignored as the console errors show (see picture).

In **v1.41** everything works correctly.

```javascript
window['CESIUM_BASE_URL'] = './path/to/somewhere';
```

![image](https://user-images.githubusercontent.com/6803839/36264977-7769c526-126e-11e8-8b4a-116073a625f6.png)

**Comment by hpinkos** [comment]
@tfili another one related to your Resource changes?

**Comment by tfili** [comment]
If you change it to `window['CESIUM_BASE_URL'] = './path/to/somewhere/';` (with the trailing slash) it should work in 1.42. I fix this in #6231, so it should make it in the next release.

**Comment by mreilaender** [comment]
Adding the trailing slash doesn't work ... Still the same errors

**Comment by tfili** [comment]
I was able to reproduce the problem without the slash and adding the slash fixes it. All my fix does is guarantee the slash is there.

If that doesn't fix the problem, you may want to try master to make sure it actually addresses your issue.

**Comment by mark-lassche** [comment]
For what it's worth we're running into the same issue. Adding trailing slash did not fix the problem, downgrading to 1.43 did resolve the issue for us.

**Comment by hpinkos** [comment]
@mark-lassche there's a new issue for this open here: #6411
We should have it fixed again for the 1.45 release
