### ISSUE TITLE
makeZipFile fails all the time on CI

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6230]
I've seen this error happen fairly frequently:

```
[16:21:43] 'combine' errored after 59 s
[16:21:43] Error: Command failed: npm run requirejs
```

Is there anything we can do about it?

https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/342414434

**Comment by mramato** [comment]
The problem is almost certainly that requirejs is running out of memory on travis' anemic servers.  We've always skirted the limits, but it's possible that Cesium's code base has grown enough that it's hitting it again.  To fix it, we can try changing `  - npm run makeZipFile -- --concurrency 2` to `  - npm run makeZipFile -- --concurrency 1` in the travis.yml.

**Comment by shunter** [comment]
I've seen this too on our offline build farm on a system with 16GB RAM.  Unless there's some other memory limit in node I'm not aware of.

```
16:06:10,642 INFO  - [16:06:10] Error: Command failed: npm run requirejs -- --eyJ3cmFwIjp0cnVlLCJ1c2VTdHJpY3QiOnRydWUsIm9wdGltaXplQ3NzIjoic3RhbmRhcmQiLCJwcmFnbWFzIjp7ImRlYnVnIjp0cnVlfSwiY3NzSW4iOiJTb3VyY2UvV2lkZ2V0cy9BbmltYXRpb24vQW5pbWF0aW9uLmNzcyIsIm91dCI6IkJ1aWxkXFxDZXNpdW1cXFdpZGdldHNcXEFuaW1hdGlvblxcQW5pbWF0aW9uLmNzcyJ9 --silent
16:06:10,642 INFO  -
16:06:10,642 INFO  - npm ERR! Windows_NT 10.0.16299
16:06:10,642 INFO  - npm ERR! argv "C:\\BuildToolsQB\\windows\\node\\7.7.3-x64\\node.exe" "C:\\BuildToolsQB\\windows\\node\\7.7.3-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "requirejs" "--" "--eyJ3cmFwIjp0cnVlLCJ1c2VTdHJpY3QiOnRydWUsIm9wdGltaXplQ3NzIjoic3RhbmRhcmQiLCJwcmFnbWFzIjp7ImRlYnVnIjp0cnVlfSwiY3NzSW4iOiJTb3VyY2UvV2lkZ2V0cy9BbmltYXRpb24vQW5pbWF0aW9uLmNzcyIsIm91dCI6IkJ1aWxkXFxDZXNpdW1cXFdpZGdldHNcXEFuaW1hdGlvblxcQW5pbWF0aW9uLmNzcyJ9" "--silent"
16:06:10,642 INFO  - npm ERR! node v7.7.3
16:06:10,642 INFO  - npm ERR! npm v4.1.2
16:06:10,642 INFO  - npm ERR! code ELIFECYCLE
```

The base64 decodes to:
```
"{"wrap":true,"useStrict":true,"optimizeCss":"standard","pragmas":{"debug":true},"cssIn":"Source/Widgets/Animation/Animation.css","out":"Build\\Cesium\\Widgets\\Animation\\Animation.css"}"
```

so it's while minifying the CSS.

**Comment by hpinkos** [comment]
@mramato setting `--concurrency 1` did not fix the error 

https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/344911937?utm_source=github_status&utm_medium=notification

**Comment by mramato** [comment]
This could be a two fold problem, in addition to concurrency, I think we also run the debug/release builds at the same time.  I'll look into it.

**Comment by hpinkos** [comment]
I've been seeing this all the time lately

**Comment by hpinkos** [comment]
https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/395137713
