### ISSUE TITLE
Overlapping holes in polygons cause artifacts

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#6238]
![image](https://user-images.githubusercontent.com/4439461/36443514-f990bae2-1646-11e8-91e9-d5d8b62bcf11.png)

Brought up on the forum here: https://groups.google.com/forum/#!topic/cesium-dev/yCvREpm4rXE

It was brought up that polygons can't have overlapping holes by design and the overlaps should be removed as a workaround, however, this is not clear in the docs.

**Comment by hpinkos** [comment]
duplicate #1209

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/yCvREpm4rXE

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/6238 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
