### ISSUE TITLE
Consider changing documentation fonts

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6254]
Most of the fonts in our generated documentation make it easy to confuse uppercase `I` and lowercase `l`.  We should consider switching to one with a more distinct character set.

![image](https://user-images.githubusercontent.com/1495196/36554713-07413896-17ce-11e8-8acd-a2303b74aeba.png)

**Comment by hpinkos** [comment]
> one with a more distinct character set

I'm not opposed to switching to a serif font for the class name.  I wouldn't change the entire page to that though.  It's easier to read sans-serif fonts.

**Comment by ggetz** [comment]
Maybe monospace instead of introducing a serif?
