### ISSUE TITLE
Visited Credits links are unreadable in the attribution pop-up

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6262]
![image](https://user-images.githubusercontent.com/1495196/36564506-8c2081d0-17eb-11e8-86d9-99236ce304f0.png)

@hpinkos do we just want them to stay white?

**Comment by hpinkos** [comment]
@mramato yes, I think white is the right option.  You can add something to the `appendCSS` function in `CreditDisplay`
