### ISSUE TITLE
Remove `@returns {undefined}` from code

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6265]
Here's an easy issue for a new contributor.  We have `returns {undefined}` littered throughout our JSDoc.  There's no reason for them and they should simply be removed.

**Comment by durgeshra** [comment]
HI! I would like to work on it. however, I did not find such statement in the jsdoc folder. Am I looking at the wrong place or what? Thank you!

**Comment by hpinkos** [comment]
Hi @durgeshra!  We want to remove this from the documentation comments throughout the `Source` folder.  Thanks!

**Comment by durgeshra** [comment]
I guess you mean @returns {anything can be here} or specifically @returns {undefined}?

**Comment by durgeshra** [comment]
Do I have to remove only returns{undefined} or the entire statement that goes along with it in the comment?

**Comment by mramato** [comment]
@durgeshra the entire block.  For example:

```
*  @param {Number} foo A variable
*
*  @returns {undefined} blah blah blah blah
*              blah blah blah blah blah blah
*
*  @example
```

Becomes

```
*  @param {Number} foo A variable
*
*  @example
```

**Comment by hanbollar** [comment]
@mramato @hpinkos It seems this issue has been completed? or is there other items left to do?

**Comment by hpinkos** [comment]
Yes, thanks @hanbollar, it looks like @gabriel-macario removed them all in his PR
