### ISSUE TITLE
3DTileset tile selection bug?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6270]
@lilleyse and @bagnell is this a bug, or am I just misunderstanding expected behavior?

1. Run any 3D Tileset Inspector demo: http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Inspector.html&label=Showcases
2. Turn on statistics
2. Hit the home button
3. The root tile is still selected for rendering even though you are zoomed all of the way out, why?

**Comment by lilleyse** [comment]
Apparently the tileset has a geometric error of `36757007.226` which is extremely big. Definitely a data problem.

**Comment by lilleyse** [comment]
The root's geometric error is `739.9` which is much more reasonable.
