### ISSUE TITLE
Zoom When Model Load Failure

### ISSUE THREAD

**Issue by jpthompson212** [AnalyticalGraphicsInc/cesium#6272]
When loading a CZML file and the model fails to load it causes the camera to never zoom to the entity.  This is most likely because there is no detection of the model load failure.  

Ideally, the model load failure would be detected and then the camera would zoom to the entity anyways.

**Comment by mramato** [comment]
Thanks @jpthompson212!  This issue has been around forever but mostly off our radar.  Pretty sure it's a simple fix in ModelVisualizer.js.  Basically, we need to update `onModelError` to record that the model failed in the `modelHash` and check if the modelData fail flag is set in `getBoundingSphere` and return failed there if so.

Another good beginner issue.  We'd be happy to take a PR if you want to take a crack at this. 😄

**Comment by srwiseman** [comment]
Hey guys,

Do you mind if I take a crack at this one?

**Comment by jpthompson212** [comment]
Hey @srwiseman,

Of course not!

**Comment by srwiseman** [comment]
Awesome. @jpthompson212 Can you post some quick reproduction steps, so that I know I'm seeing the exact same thing?

**Comment by hpinkos** [comment]
Hi @srwiseman!  Thanks for volunteering!

To get started, see our [contributor documentation](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors).  The [Build Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide) will give you instructions for checking out the code base and building the project.

As @mramato said above, you'll most likely have to make changes to `ModelVisualizer.js`

Here is an example to reproduce the issue:

```js
var czml = [{
    "id" : "document",
    "name" : "box",
    "version" : "1.0"
}, {
    "id" : "shape1",
    "name" : "Blue box",
    "position" : {
        "cartographicDegrees" : [-114.0, 40.0, 300000.0]
    },
    "box" : {
        "dimensions" : {
            "cartesian": [400000.0, 300000.0, 500000.0]
        },
        "material" : {
            "solidColor" : {
                "color" : {
                    "rgba" : [0, 0, 255, 255]
                }
            }
        }
    }
}, {
    "id" : "aircraft model",
    "name" : "Cesium Air",
    "position" : {
        "cartographicDegrees" : [-77, 37, 10000]
    },
    "model": {
        "gltf" : "invalid/model/path.glb",
        "scale" : 2.0,
        "minimumPixelSize": 128
    }
}];

var viewer = new Cesium.Viewer('cesiumContainer');
var dataSourcePromise = Cesium.CzmlDataSource.load(czml);
viewer.dataSources.add(dataSourcePromise);
viewer.zoomTo(dataSourcePromise);
``` 

Let us know if you have any questions!  Looking forward to your pull request =)

**Comment by srwiseman** [comment]
Awesome!  Thanks!

**Comment by srwiseman** [comment]
Ok, I've fixed this by adding a fail flag to the modelData, then adding a check for the failure condition in getBoundingSphere. I'll prepare the PR soon! :)
