### ISSUE TITLE
Impossible to credit some sources properly in Cesium.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6280]
Currently, all credits get mashed together into a single list, but this makes it hard to properly credit some sources.  For example, [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)  requires a link to the CC 4.0 license, but there's no way via credits to indicate which data this license applies to without repeating information across Credits.

For example let's say I have a data source `Foo Imagery`, that requires attribution to both Bar.inc and CC 4.0.  I also need to link to both.  Right now I would be forced to write

* [Foo Imagery (includes part of data X and Y) provided by Bar.inc](https://cesium.com)
* [Foo Imagery licensed under CC 4.0](https://creativecommons.org/licenses/by/4.0/)

This can get pretty crowded when you have multiple data sources and many attributions are much more elaborate.  I would much rather write:

* Foo Imagery (includes part of data X and Y) provided by [Bar.inc](https://cesium.com) and licensed under [CC 4.0](https://creativecommons.org/licenses/by/4.0/)

The best idea I have for fixing this is allowing HTML credits instead of just `text`.  OpenLayers does this already, but all credits are manually added by the user.  Since we support server-side credits, we probably need to sanitize the credit using https://www.npmjs.com/package/xss or similar.

**Comment by hpinkos** [comment]
Other libraries like leaflet and openlayers have HTML credits.  I think that's the way to go

**Comment by kring** [comment]
I believe this was fixed in #6331.

**Comment by hpinkos** [comment]
Yes, thanks @kring
