### ISSUE TITLE
Bing Maps imagery doesn't show up in Firefox

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6288]
Only tested on Mac so far.

http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/CesiumViewer/index.html

> Loading failed for the <script> with source “https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?jsonp=loadJsonp161644&incl=ImageryProviders&key=Ar9n20kTp-N8tEg3Dpx-Pgocmx3W0-GUnD_Bgt3h8g6pSeDL8yxByTVGHyMyjI2p”.
index.html:1
An error occurred in "BingMapsImageryProvider": An error occurred while accessing https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?jsonp=loadJsonp161644&incl=ImageryProviders&key=Ar9n20kTp-N8tEg3Dpx-Pgocmx3W0-GUnD_Bgt3h8g6pSeDL8yxByTVGHyMyjI2p.

![image](https://user-images.githubusercontent.com/782098/36808664-bb16b7aa-1c93-11e8-8e94-8de9c0e32e1f.png)

Warnings are tracked in #5912

**Comment by mramato** [comment]
Works for me (Windows 10, FF 58.0.2)

**Comment by shunter** [comment]
If you're seeing this on the AGI network, this is probably due to Firefox not using the system certificate store, so it doesn't trust our corporate SSL gateway.

**Comment by hpinkos** [comment]
Works for me

**Comment by pjcozzi** [comment]
@shunter is probably right, closing, thanks all!
