### ISSUE TITLE
DataSources/CzmlDataSource checks validation document fails in FF, IE, Edge

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6294]
`DataSources/CzmlDataSource checks validation document`
`
Expected Cartesian3({ x: -0.0639954754237593, y: -0.6595436486193664, z: -0.7489370832661051 }) to equal Cartesian3({ x: -0.06399547542375929, y: -0.6595436486193663, z: -0.748937083266105 }).
`

This has been failing since the 1.38 release

Also see discussion in https://github.com/AnalyticalGraphicsInc/cesium/issues/2860#issuecomment-369658876

**Comment by shunter** [comment]
Debugged this - the discrepancies are because the Cartesian3 is client-side normalized by the CZML loading code but the expected value is not (because it's already known to be magnitude 1 by construction).

I'll add an epsilon to the generated assertions.
