### ISSUE TITLE
Exclude modules from source only used in workers

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#6298]
If a module only used in a web worker should it be exclude it from `sourceFiles` when building in order to not have the module downloaded if it's not being used.

We need to formalize the rules and update the coding guide

CC https://github.com/AnalyticalGraphicsInc/cesium/pull/6191#discussion_r171706541

**Comment by mramato** [comment]
@bagnell says we can exclude Crunch as well, does anyone else know of any libraries that are only used in workers?
