### ISSUE TITLE
Clock.shouldAnimate default value

### ISSUE THREAD

**Issue by xuncanzhe** [AnalyticalGraphicsInc/cesium#6300]
My application abnormal after update cesium version. Eventually I found it in Clock.shouldAnimate, which was the default `true` in previous releases(1.36), but `false` in the new release(1.42). But it does not seem to be updated in the API documentation.

**Comment by hpinkos** [comment]
Hi @xuncanzhe, sorry this change caught you off guard.  We did make note of it in the `Breaking Changes` section of `CHANGES.md` for the 1.42 release: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#breaking-changes-mega-1

You can set it back to `true` by passing in `shouldAnimate: true` as an option to `Viewer`

I couldn't find anywhere any errors in the documentation where it says `shouldAnimate` defaults to `true`, but if you see any please let us know so we can update it.  Thanks!

**Comment by xuncanzhe** [comment]
HI, https://cesiumjs.org/Cesium/Build/Documentation/Clock.html?classFilter=cloc . and the same situation in source code Comments.

**Comment by xuncanzhe** [comment]
@hpinkos

**Comment by hpinkos** [comment]
Ah, thanks @xuncanzhe!  I looked at the doc for the params at the top of the file, but I forgot to look at the doc for the property.

I've updated that in https://github.com/AnalyticalGraphicsInc/cesium/commit/7a86dcf871bf994b50da6decb42adcf6d8f0a6b8 and the doc will be fixed in the Cesium 1.44
