### ISSUE TITLE
Remove `Plane` with `ClippingPlaneCollection` and `ClippingPlaneCollection.isSupported` deprecation notices

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6317]
`ClippingPlaneCollection` currently can ingest `Plane` objects, but we're getting rid of that functionality in 1.45.
Also, clipping planes are now supported in Internet Explorer, so `ClippingPlaneCollection.isSupported` should also be removed in 1.45.

**Comment by hanbollar** [comment]
@likangning93 @ggetz are we still doing this for 1.45?

**Comment by hanbollar** [comment]
k. ggetz says it's a go - i'll start working on this.
