### ISSUE TITLE
About  `CESIUM_BASE_URL` and result of `cesiumScriptRegex.exec`

### ISSUE THREAD

**Issue by luogeng2017** [AnalyticalGraphicsInc/cesium#6319]
i use thy way of npm i cesium to build my demo.then, use webpack to pack my code up.
but when i debugged ,thw code var result = cesiumScriptRegex.exec(src); get a result=null.
Have you any way likes npm i cesium .thanks

**Comment by hpinkos** [comment]
Hello @luogeng2017, please see this tutorial for webpack instructions: https://cesiumjs.org/tutorials/cesium-and-webpack/

In the future, please ask questions like this on the Cesium forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for planning new features and tracking bugs.  Thanks!

**Comment by nmccready** [comment]
The documentation for Cesium and Webpack appears to be broken around 1.47, 1.48 . Whenever the iframe implementation was enforced as the dom container for the map.

**Comment by hpinkos** [comment]
@ggetz can you look into this?

**Comment by nmccready** [comment]
Heads up I figured it out.

`CESIUM_BASE_URL : JSON.stringify('')`
now needs to be
`CESIUM_BASE_URL : JSON.stringify('../')`

**Comment by hpinkos** [comment]
Thanks for the info @nmccready!  I created this issue so we can update the example and tutorial: https://github.com/AnalyticalGraphicsInc/cesium-webpack-example/issues/11
