### ISSUE TITLE
cesium default navigation suggestion

### ISSUE THREAD

**Issue by mclkyo** [AnalyticalGraphicsInc/cesium#6321]
on pc,cesium's default navigation is Right click + drag, or Mouse wheel scroll，but i think in most 3d enginee, right click is rorate view,so i suggest that cesium can give a way to custom the navigation key, or change right click to rotate view

**Comment by hpinkos** [comment]
Hi @mclkyo. Thanks for the suggestion, but I think we're pretty happy with the default behavior.
However, if you wanted to change it for your own application, you can do so fairly easily using the [ScreenSpaceCameraController](https://cesiumjs.org/Cesium/Build/Documentation/ScreenSpaceCameraController.html) 

You can do something like this:

```js
viewer.scene.screenSpaceCameraControler.tiltEventTypes = [CameraEventType.RIGHT_DRAG]
```

In the future, please open these kinds of discussions on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
