### ISSUE TITLE
glTF 2.0 animations don't play

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#6322]
Still investigating this, but I'm having trouble getting any glTF 2.0 animation to play in master.  Even the "animated triangle" official sample model won't budge.

The animation code is being exercised, particularly in `ModelAnimationCollection` it is running every frame and calculating a `localAnimationTime` and such.  Just visually, nothing appears to move on the screen.

**Comment by lilleyse** [comment]
It seems to work for me in the 3D Models sandcastle demo.

Are you passing in `shouldAnimate : true` to the viewer?

**Comment by emackey** [comment]
The 3D Models demo uses glTF 1.0 models.  Did you try this with glTF 2.0?  Which model?

**Comment by emackey** [comment]
Scratch that.  It's working now in Sandcastle, for certain models.
