### ISSUE TITLE
Tests that need to load data don't work in karma

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6339]
Doing this in the Jasmine HtmlReporter works:

```js
var path = './Data/Cesium3DTiles/Tilesets/TilesetOfTilesets';
var tileset = new Cesium3DTileset({
    url : path
});
```

However, to get this to load when running tests in karma the path needs to look like this
```js
var path = './base/Specs/Data/Cesium3DTiles/Tilesets/TilesetOfTilesets/';
```

Running `npm run test` locally fails tests all over the place because of this.  I have no idea why they pass on travis.

See `zoomTo zooms to Cesium3DTileset with default offset when offset not defined` in `ViewerSpec` for an example

cc @mramato

**Comment by mramato** [comment]
@hpinkos this is OBE, right?  I think we tracked this down as a conflict with other servers running on the same machine.

**Comment by hpinkos** [comment]
Yeah, I don't remember what this ended up being about but it's fine now
