### ISSUE TITLE
Volume rendering Demo

### ISSUE THREAD

**Issue by Ants-double** [AnalyticalGraphicsInc/cesium#6345]
Now ,I want to develop a program that can show the volume rendering . i.e.  the clouds in the air. .
I have  RAW data ,i have no idea. Thank you help me?

**Comment by hpinkos** [comment]
@Ants-double if you're interested in cloud rendering, see the discussion in this issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/5962

For all other questions, please post on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
