### ISSUE TITLE
EllipseGeometry rectangles not getting computed correctly

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6347]
[Link for Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dVVNb+IwEP0rFheCxBo49MLSalmWpajdtirVnpAqkwzg1rEj24HSVf/7jkNinJRyCvabN28+vWOa7DjsQZNLImFPJmB4ntK/xVnUjou/EyUt4xJ0u/N9KXdoA+JB85RbvgM8WecytlxJkrJXmArBMwNRDNKC7pB/S0nwd/RC8RCtwFANqdrBWIjIcToEX5OodJ/AGt0lUeCm45kCNoNOgGYVpmKt2ZXsH0tZCinkFxpnoFKw+oCxh8FP67dR4PcYFBmWH93TjYGU/+FS6fEbNwi46Lsf7Tch7MVDBv3PGK0sK1KJDHQQXOxAW3j7rXTKLF5WdQpO6cP9Yv40v797Ht/9el48lXG7BJwi59JYJmOol7sKdV7eViFvqgQNmykrlfEEr9pq9QKxJRpsrrFsZL8FSewWg/Tu8Dvj8SteMpkQq5Da9gxYkoH+5lHMWs1XuQXTPqs+3gJy6JViOvnDsACcCYykjKI6oWut0qdDBlF7Ehi061zHgBRPFrlesxjGWQZMOxmDenKmXwLDzkgrOcOzKj+FE7Qouvuqn1mSRIEUb9IsUFU411ZVNssSMS/XV/Fs0JXCepY2GkA+YnWZ3IhAqZ9jpzBIg2Sp89OeOTtikdqI3A1L99jakHSLDoA3q/ME20F7buzrLfDN1pI9t1uicitwCbTD4fDYYbgMisFUSidcogPzuVmpN+zWrYKilRmeKKE0nT1Op3fUyRiLbMuiPr3oNExLqUPSb1yUuvEGI4Qu6fUqbJobS1ZAXNuvlfZInIaEm0yww1mmQlJT4c/b8eTmBP8I+qvYdK522nm9xmyL5npfxK48iww7YLrD4pSgqNaGMUMW4xhDIorq5zLL7bhY+VG1+yO3eFPkOm18N7AM95PhTJ46J8YO0Yy6beAnyxvTTBnu6Lr1kdgItQLquzd8MryL2gNRe4k84vQWfHS/yoVbHPRxPrt+ep7czic3x3ko1bwr3CwqagzBEdLqtkbGHgRcHb384GmmtCW5FhGlPQsplhiF9FY5rgdLY1MYjnqV0SjhO9yol8tW49ldtkgsmDF4s86FWPB3WLauRj3E18yEYjgDm3t8K1wzIWQ7uLo9HlJKRz38+9nKKiVWTAeM/wE). Right click on the globe to place an ellipse with its computed `Rectangle` drawn around it.

Inigo Quilez has a more accurate version here: http://www.iquilezles.org/www/articles/ellipses/ellipses.htm

but my implementation of it has accuracy problems for large areas since it's wrapping the ellipse around the planet, and also has very high false-negative coverage at the poles (again specifically for large area ellipses):

![iqbig](https://user-images.githubusercontent.com/5395255/37607345-272a801e-2b6e-11e8-8262-5c05449a2120.JPG)

![iqpole](https://user-images.githubusercontent.com/5395255/37607351-2abcc3f4-2b6e-11e8-8a9b-95ed2aa476bb.JPG)

For anyone interested, we're thinking about using rectangular bounds around ellipses, polygons, and rectangles to help with batching `GroundPrimitives`, but for that we need at least conservative rectangular bounds. Taking the AABB of the ellipse's entire oriented bounding box seems to get better results, although there's still problems at the poles. But is this too loose for Cesium's other use cases on ellipse rectangles?

![obb](https://user-images.githubusercontent.com/5395255/37607579-c56a28f6-2b6e-11e8-9f2f-e8be522591c3.JPG)

We could also possibly use iq's algorithm for small areas and the OBB algorithm for big ones?

**Comment by hpinkos** [comment]
@likangning93 we know the positions used to draw the ellipse, so we should be able to find a bounding rectangle fairly easily.  To me, it looks like our [EllipseGeometry computeRectangle](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/EllipseGeometry.js#L662) function is not applying the rotation correctly.

Look at [EllipseGeometryLibrary.computeEllipsePositions](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/EllipseGeometryLibrary.js#L100)
At the very worst, we can get the edge positions used for the `EllipseOutlineGeometry` and call `Rectangle.fromCartesianArray` to get the bounding rectangle.  But I'm sure we can figure out how to get the north/south/east/west most point in the ellipse without having to compute all of them.

**Comment by likangning93** [comment]
> it looks like our EllipseGeometry computeRectangle function is not applying the rotation correctly.

Sort of... in more detail, the current `computeRectangle` function builds the rectangle extents just by transforming the axes of the the ellipse. This just doesn't account for curvature, hence the current accuracy problem:

![img_20180320_103554739](https://user-images.githubusercontent.com/5395255/37661313-e3f7b042-2c2a-11e8-867d-50d9b8223288.jpg)

IQ's algorithm accounts for the curvature and works fine for bounding rectangles in cartesian space, I'm just having trouble getting to ellipsoid space. `EllipseGeometryLibrary.computeEllipsePositions` might be helpful though, I'll take a look.

**Comment by likangning93** [comment]
I tried computing the thetas for where the ellipses "touch" the bounding box and then generating the projected points for those, but it looks like the projection can make those thetas basically "wrong" at the poles. I think we're just going to have to cycle over all the generated points, unfortunately.

**Comment by hpinkos** [comment]
@likangning93 you can call `EllipseGeometryLibrary.computeEllipsePositions` from the `computeRectangle` function.  It's unfortunate to have to compute it twice but that's what we ended up having to do for corridors.  In the grand scheme of things it's not that expensive to just compute the outer ring.
