### ISSUE TITLE
about Imagery Layers

### ISSUE THREAD

**Issue by zebrainncu** [AnalyticalGraphicsInc/cesium#6356]
Hi 
I use refence  Apps\Sandcastle\gallery\Web Map Tile Service with Time.html
I want to add a WMTS imagery layer in cesium
but it doesn't work. Some message as below
An error occurred in "y": Failed to obtain image tile X: 214 Y: 110 Level: 8.

![image 1](https://user-images.githubusercontent.com/16786888/37694387-c6d0d69c-2d01-11e8-9bdf-26f28bd0cf50.png)

=================
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>NCU-</title>
    <meta charset="utf-8" />
    <script src="../Build/Cesium/Cesium.js"></script>
    <style>
        /*@import url(../Apps/Sandcastle/templates/bucket.css);*/
        @import url(../Build/Cesium/Widgets/widgets.css);
    html,
    body,
    .map {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
    }
    </style>
</head>
<body>    
    
    <div id="map" class="map"></div>
    <script type="text/javascript">
        'use strict';
        var viewer = new Cesium.Viewer('map', {
            shouldAnimate : true,
            baseLayerPicker : false,
        });

        function dataCallback(interval, index) {
            var time;
            if (index === 0) { // leading
                time = Cesium.JulianDate.toIso8601(interval.stop);
            } else {
                time = Cesium.JulianDate.toIso8601(interval.start);
            }

            return {
                Time: time
            };
        }
        // Add a WMTS imagery layer
        var provider = new Cesium.WebMapTileServiceImageryProvider({
            // url : 'https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/AMSR2_Snow_Water_Equivalent/default/{Time}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png',

            url :'http://140.115.110.11/SP/SP2014NC_3857/{z}/{x}/{y}.png',//Failed to obtain image tile
            // url :'//140.115.110.11/SP/SP2014NC_3857/{z}/{x}/{y}.png',//Failed to obtain image tile
        });
        var imageryLayers = viewer.imageryLayers;
        imageryLayers.addImageryProvider(provider);
        provider.readyPromise
            .then(function() {
                viewer.timeline.zoomTo(start, end);
                var clock = viewer.clock;
            });

        var Options = {
            destination : Cesium.Cartesian3.fromDegrees(121.1, 23.800321, 500000.0),
            duration: 5,
            orientation: {
                heading : Cesium.Math.toRadians(0),
                pitch : Cesium.Math.toRadians(-90),
                roll : 0.0
            }
        };
        viewer.camera.flyTo(Options);

    </script>
</body>

</html>

Can you help me?
Thanks

**Comment by hpinkos** [comment]
@zebrainncu try taking a look at our [Imagery Layers Tutorial](https://cesiumjs.org/tutorials/Imagery-Layers-Tutorial/) to see if that helps.

Otherwise, can you please ask your question on the forum? https://groups.google.com/forum/?hl=en#!forum/cesium-dev
A lot more people see forum posts so it is more likely that someone will be able to help.
We use GitHub exclusively for tracking bugs and planning new features.
Thanks!
