### ISSUE TITLE
Clarify documentation for 3D Tiles styling

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6358]
With the addition of vector tiles we added a lot of new styling properties to `Cesium3DTileStyle` but most of those are only applicable to vector tile point features. This could be clarified better in the documentation. Besides `color` and `show` which are used by all formats, each property should have a note about which tile formats they are applicable to.

vctr point feature properties: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/3d-tiles-next/Styling#vector-data

`pointSize` is used by both vctr point features and pnts.

**Comment by hanbollar** [comment]
@lilleyse I'll work on this update

just as a clarification regarding the documentation in the link you provided
- all properties are available in point formats but only show and color are available for polygon/polyline formats, yes?
- and all you want as a change is that each property now has a note stating that they're specifically only for point formats except for show and color, correct?

**Comment by lilleyse** [comment]
Yeah exactly.

The doc for `verticalOrigin`, for example, might look like:

```
        /**
         * Gets or sets the {@link StyleExpression} object used to evaluate the style's <code>verticalOrigin</code> property. Alternatively a string or object defining a number style can be used.
         * The getter will return the internal {@link Expression} or {@link ConditionsExpression}, which may differ from the value provided to the setter.
         * <p>
         * The expression must return a <code>VerticalOrigin</code>.
         * </p>
         * <p>
         * This expression is only applicable to point features in a Vector tile.
         * </p>
         ....

```
