### ISSUE TITLE
Firefox 59.0 on macOS ctrl+touchpad rotation not working

### ISSUE THREAD

**Issue by andrzejfigula** [AnalyticalGraphicsInc/cesium#6372]
Latest Firefox broke navigation control (ctrl + touchpad to rotate) for macbook.
This was only checked with touchpad, not sure if affects other pointing devices.

Environment:
- macOS (Sierra) on MacBook Pro (Retina, 15-inch, Mid 2014)
- Firefox 59.0.2 (64-bit)
- Cesium 1.43 (Cesium home page and my application)

Issue:
I'm always using touchpad to rotate (**ctrl + touch**), it was always possible on FF until last update.
(Chrome and Safari works fine). 

Tested on Cesium home page and with Cesium 1.43

Looking at FF release notes:
https://www.mozilla.org/en-US/firefox/59.0/releasenotes/

I found this:
"Added support for W3C specs for pointer events and improved platform integration with added device support for mouse, pen, and touch screen pointer input"

Just guessing this might be the reason.

**Comment by hpinkos** [comment]
Thanks for reporting this @andrzejfigula!
@ggetz can you confirm this bug on your mac?

**Comment by jimmyangel** [comment]
I can confirm this issue as well on Firefox 59.0.2 MacOS 10.13.4, Cesium 1.44. Control-drag not working work with a trackpad nor a mouse either.

**Comment by hpinkos** [comment]
Thanks @jimmyangel.  Can someone with a mac confirm this bug?  @shehzan10 @tfili @shunter?

**Comment by shrichards** [comment]
I'm also seeing this on my MacBook Pro (exact same specs as @andrzejfigula) with Cesium 1.44 & FireFox v60.0b13 beta.

With a mouse hooked up, ctrl-leftclick-drag also doesn't work.  However, ctrl-*rightclick*-drag does rotate.

**Comment by hpinkos** [comment]
Thanks @shrichards, we'll try to look into this soon

**Comment by DronePhil** [comment]
@hpinkos any updates here? At DroneDeploy we are starting to see customer complaints about this issue. Though we can fix it by rewriting the camera controls ourselves, we'd prefer not to.

**Comment by mramato** [comment]
I believe Firefox has several bugs in the PointerEvents implementation, we've encountered this before in our own unit tests.  I think the best solution here is to disable PointerEvents completely in FireFox until those issues get fixed.

I'll push a branch with this change and if folks can confirm that it fixes the issue, we'll merge for the next release.

**Comment by mramato** [comment]
Since I can't reproduce this, can anyone with this issue try http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/dont-point/ (That has both the Viewer sample app and Sandcastle) and report whether it fixes the issue?

If so, I think we can squeeze this into the next release (tomorrow!) but we need to know if it works ASAP.

**Comment by ggetz** [comment]
Can't duplicate on my machine, can @likangning93 or someone else with macOS?

**Comment by mramato** [comment]
@ggetz do you mean you can't reproduce this in master either?

**Comment by ggetz** [comment]
@mramato Yes, I can't reproduce this in master.

**Comment by mramato** [comment]
@andrzejfigula, @DronePhil, @shrichards @jimmyangel Can any of you still reproduce this, either in master at http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/ or on the branch I linked to above (http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/dont-point/)

**Comment by likangning93** [comment]
Just tested on Firefox 61.0.2 x64 on macOS 10.11.6, ctrl + trackpad worked for the `dont-point` branch but not in `master`

**Comment by mramato** [comment]
Wrote up #7003 to revisit this issue once Firefox improves their implementation (or we find out it was something we are doing on our end)
