### ISSUE TITLE
Error in StaticGeometryPerMaterialBatch

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6378]
``` js
if (this.depthFailMaterialProperty instanceof MaterialProperty) {
    this.depthFailMaterial = MaterialProperty.getValue(time, this.depthFailMaterialProperty, this.depthFailMaterial);
    translucent = this.depthFailMaterial.isTranslucent();
...
```

[This if block](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/StaticGeometryPerMaterialBatch.js#L147-L149) is wrong.  `MaterialProperty` is an interface, so `this.depthFailMaterialProperty` will never be an instance of `MaterialProperty`.
What should this actually be?  I couldn't figure it out.

cc @bagnell @mramato

**Comment by mramato** [comment]
That whole block is a mess.  Fairly certain this check us unnecessary and it should just always execute the true block.  If `depthFailMaterialProperty` is defined, thenit is guaranteed to be a MaterialProperty implementing class.
