### ISSUE TITLE
Flag new/updated Sandcastle examples

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6384]
Right now, users have to look at CHANGES.md or I guess the file timestamps to see what new examples are in a release.

It would be cool if there was a Sandcastle tab (or other type of sorting / highlighting) where it is easy to discover the new / significantly updated examples.

Could maybe even automate it as part of the build.

Folks were asking for the same thing for three.js at GTC

**Comment by mramato** [comment]
For automation, this should be easy by having `createGalleryList` look at new files since the previous release git tag.

**Comment by emackey** [comment]
This is a great idea.  Probably shouldn't use file timestamps for this though.  Git log can identify what's changed lately in a particular branch, or we could manually flag some each release.

**Comment by emackey** [comment]
For example, if a developer has been working on a branch that has changed demos, and then swaps back to master to build a release, the datestamps on those files will get touched to "now" as the demos are reset back to their old master state.  They would be incorrectly flagged as new.

Likewise, on a fresh clone, everything is new.

**Comment by mramato** [comment]
Just do: `git diff --name-only --diff-filter=A 1.43 HEAD Apps/Sandcastle/gallery/*.html` and you're done.

**Comment by emackey** [comment]
@mramato That's perfect.

**Comment by mramato** [comment]
PR incoming.
