### ISSUE TITLE
512px Tile Support Broke

### ISSUE THREAD

**Issue by NaderCHASER** [AnalyticalGraphicsInc/cesium#6395]
[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVDva8IwEP1XQr9UQZJWGWxaZSADBzrFH9uXwojtrQ1Lk5KkdVX835e2DtQdhPDe3XvHu5IqVDI4gEJjJOCApqBZkeH3huu4UQOnUhjKBCi3OwpFKEqrYvmtYqf4FrKcUwOvGU1AVSslSxZbl1MokK1C8SFyU2NyPSTEMA7K8zHlnGkpUllowJHMmgaZrdfr6fJttyHbl8Xqs78gfc9/9AYDj9jP1hV+anBOORgD5HQ8k1Nl388Z5yJxe+3y2vWDxSYdoge/f0XOgCWpadhQnC/5mvRYRyAAszbNnFagNKZxfB+P5d2R03MCbSoOk9b5mWW5VKbO3MGYmMtlNNkX0TcYHGldrwrInyiIWYlYPA6du5OHDoo41dp2vgrON+wIoTMJiJ2/kXFJYyaSZQmK06oeSf3JvCUxxgGx8L/KSMn3VF05/gI)

Screenshot:
![screen shot 2018-03-30 at 1 29 03 pm](https://user-images.githubusercontent.com/913068/38150903-5cabd4fa-341e-11e8-8fe6-d8cdca9f6664.jpg)

Fixed by offsetting `{z}` tag replacement + 1.

Varying tile sizes used to work just fine. I don't know when this broke or which commit is to blame.

**Comment by hpinkos** [comment]
Thanks @NaderCHASER, what's the last release you know this worked in?

**Comment by NaderCHASER** [comment]
It's been over a year @hpinkos. I found an `ol-cesium` issue from May 11, 2017 which reports this exact problem (but proposes - 1 level offset).

https://github.com/openlayers/ol-cesium/issues/457

I'll likely end up with a PR to fix this as I'm migrating from 256px tiles to 512px tiles. No guarantee you all won't beat me, though.

**Comment by hpinkos** [comment]
Gotcha.  Yeah if you have time to look into it that would be greatly appreciated @NaderCHASER!  I'm not sure we'll be able to very soon.

**Comment by pjcozzi** [comment]
@NaderCHASER +1 if you are able to submit a PR.  Also, we would be very interested to hear how 512px tiles perform in Cesium!

**Comment by NaderCHASER** [comment]
256px Tiles
--
154 network requests
Load Time: ~8.2s

512px Tiles
--
46 network requests
512px Tiles -  ~3.6s

Even with HTTP(S)/2's multiplexing, my 512px tiles were served and viewable over twice as fast as with 256px tiles.

I needed to confirm that my custom tiler wasn't responsible for the 256px vs. 512px tile bug in Cesium. I did this through a JSFiddle running Leaflet, which displayed my 512px tiles properly.

Currently, I'm using the basic fix of offsetting the zoom +1. This week I'll have more time to dig into Git blame and find the cause of this issue and hopefully get a PR submitted.

Sorry for the delay.

**Comment by hpinkos** [comment]
Wow, that's very promising @NaderCHASER!  Looking forward to your PR 😄

**Comment by NaderCHASER** [comment]
I've determined that the issues were with the calculations being performed by an open source tiler, not Cesium. Please accept my apologies for the false alarm. The other tiler has been corrected and Cesium is displaying beautiful 512px tiles with much improved performance.
