### ISSUE TITLE
Cleanup renderer object creation

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#640]
Some objects use a create function like `context.createRenderState`; others have an explicit cache like `context.getShaderCache().getShaderProgram`; and others are just allocated with `new` like `DrawCommand`.

Likewise, some things need `destroy`, others need `release`, and others do not require anything.

As we add more caching (CC #638), we'll be able to converge.  Details TBA.

**Comment by pjcozzi** [comment]
Temporarily removed the Material texture cache: #2850

**Comment by pjcozzi** [comment]
@lilleyse, let's do a pull request for each bullet:

* `createRenderbuffer` / `createFramebuffer`
* `createVertexArray` / `createVertexArrayFromGeometry`
* `createRenderState`
* `createTexture2D` / `createTexture2DFromFramebuffer` / `createCubeMap`
* `createShaderProgram` / `replaceShaderProgram`
* `createSampler`
* `createVertexBuffer` / `createIndexBuffer`

**Comment by pjcozzi** [comment]
@lilleyse here's a few ideas for `createRenderState`:

* Remove `context.createRenderState`, of course.
* Change the `RenderState` constructor function to take `options`, which will have two properties: `context` and `renderState`.  However, users will not call this directly, instead...
* Add `RenderState.fromCache` (which is a static function, not on the prototype), which takes the same `options` and is basically the implementation of `context.createRenderState`.  Make sure to move the actual cache from Context.js:
```javascript
var nextRenderStateId = 0;
var renderStateCache = {};
```
* I'm not 100% convinced that this actually works with multiple WebGL contexts, but I didn't look closely and I am not aware of any bugs.  Think it through, and if there are issues, we can simply move the caches to be per context.

**Comment by pjcozzi** [comment]
@lilleyse `createCubeMap` should be straightforward, do it before 2D textures.  Just move the implementation into the `CubeMap` constructor function, and then update everything.  There will only be a few places; cube maps are just used for stars and in the tests.

**Comment by pjcozzi** [comment]
@lilleyse `createTexture2D` / `createTexture2DFromFramebuffer` will also be pretty straightforward.  The only thing of note is to move `createTexture2DFromFramebuffer` to a static function, `Texture.fromFramebuffer`.

**Comment by pjcozzi** [comment]
@lilleyse for `createShaderProgram` / `replaceShaderProgram`, replace them with new `ShaderProgram.fromCache` and `ShaderProgram.replaceCache` static functions.

We'll talk in person about `createSampler`, `createVertexBuffer`, and `createIndexBuffer`.  Basically, we'll create a new `Sampler` class, and then we need to think about buffers in context with WebGL 2 uniform buffers and transform feedback.

**Comment by lilleyse** [comment]
It seems safe to move the cache to RenderState since RenderState doesn't seem to store any GL resources. Are there any examples with multiple contexts that I could test with?

**Comment by pjcozzi** [comment]
Here's a good start (which clearly works so we are probably OK and I'm sure I thought about this at some point): http://analyticalgraphicsinc.github.io/cesium-google-earth-examples/demos/multiple/

Code: https://github.com/AnalyticalGraphicsInc/cesium-google-earth-examples/tree/master/demos/multiple

**Comment by lilleyse** [comment]
After looking closer, it does initialize its viewport width and height with the context drawing buffer's width and height. This may be a problem in some cases.

**Comment by pjcozzi** [comment]
@lilleyse open future pull requests into the [renderer-refactor](https://github.com/AnalyticalGraphicsInc/cesium/tree/renderer-refactor) branch.

**Comment by pjcozzi** [comment]
@lilleyse for buffers, also check out the code from our book:

* https://github.com/virtualglobebook/OpenGlobe/tree/master/Source/Renderer/GL3x/Buffers
* https://github.com/virtualglobebook/OpenGlobe/tree/master/Source/Renderer/Buffers

I'm not at all advocating for the same approach, but taking a brief look should help identify strengths and weaknesses.
