### ISSUE TITLE
glTF 2.0 models appear dark

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6412]
Compared to other glTF viewers out there our models usually appear darker. We should experiment with either:

* Increase the sun/environment lighting brightness
    * Make it configurable?
* Tweak the PBR shader. I believe https://github.com/KhronosGroup/glTF-WebGL-PBR performs all lighting in linear space and outputs in sRGB space, whereas we do everything in sRGB space.

**Comment by pjcozzi** [comment]
I also think IBL will help here.

Cesium does look much darker, so I am keen on a quick workaround in the meantime.

For example, compare Cesium to the other engines here: https://github.com/KhronosGroup/glTF-Sample-Models/pull/154#issuecomment-373727889

Perhaps @emackey has a few minutes to spare to work on this? 😄

**Comment by cx20** [comment]
I tried displaying [Polly.gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) in the following version. It seems that it is dark when it is the latest version (v1.44).

[Cesium.js v1.43 + Polly.gltf result:](http://jsdo.it/cx20/u7sb)
![image](https://user-images.githubusercontent.com/1833979/38253746-6ce5879a-3792-11e8-8654-e0b5a01d1798.png)

[Cesium.js v1.44 + Polly.gltf result:](http://jsdo.it/cx20/K4NH)
![image](https://user-images.githubusercontent.com/1833979/38253769-803d7dc0-3792-11e8-8d98-832b24646223.png)

**Comment by pjcozzi** [comment]
@lilleyse @cx20 perhaps related to #3737 as well?

**Comment by emackey** [comment]
The Polly model there (the dog alone) isn't just dark, it's pitch black, even the emissive green lights on the dog have gone out.

`git bisect` blames my tangent vector fix, 2990c509df29b.  It's possible that tangent vectors and skinned animations aren't compatible in Cesium's current implementation, newly broken by adding support for tangent vectors.  I'll dig into this.

Other (non-skinned) models look the same as they have before, so I think the Polly/skinned model bug is separate from the general lighting concerns.

**Comment by emackey** [comment]
Turns out, Polly actually has a material (named "Head" at index 0) that is used for the eyes, which supply tangents, and the rest of the head, which does not supply tangents.  As such, a single shader must handle both cases, or we need to move to per-primitive materials.  Or, we use the supplied tangents only when ALL of the affected meshes supply tangents, and ignore supplied tangents otherwise.  That last option is the least destructive change, I'll try it first.

**Comment by JackD83** [comment]
It seems that this bug has returned between 1.96 and 1.97 till the current 1.101. I have multiple 3DTiles sets that are now completely black.  

Polly now looks like this:
![Polly 1 101](https://user-images.githubusercontent.com/15889805/214239289-f1797d12-87f1-4f5d-9a41-1d8ea83da673.png)

**Comment by cx20** [comment]
@JackD83 Perhaps the reason why it looks dark is that the time of the area displayed by `Cesium.js` was night.
Below is an online demo using Cesium.js.
https://cx20.github.io/gltf-test/examples/cesium/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/dd7a3dbd8f43a79d572e7c45f4215f770bb92a37/polly/project_polly.gltf

![image](https://user-images.githubusercontent.com/1833979/214287834-3638f566-73f5-4fb2-8fa9-64ac5bee4f0c.png)

BTW, I think the antenna-like things coming out of Polly's ears are artifacts.

**Comment by ggetz** [comment]
@JackD83 Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

**Comment by JackD83** [comment]
> @JackD83 Perhaps the reason why it looks dark is that the time of the area displayed by `Cesium.js` was night. 

You where right (and I feel stupid) . That means polly is fine and its only my own gltf models that are black. I dug a little deeper and the models in question where converted from gltf 1.0 to 2.0 using a custom script. The script set the single texture as emissiveTexture:

`"emissiveTexture": {
        "index": 0,       
        "texCoord": 0
      }`

This worked up to Cesium 1.96 and results now in a black model. 

Using
` "baseColorTexture":{
          "index": 0,
          "texCoord": 0
        },`

inside pbrMetallicRoughness is working. 

emissiveTexture probably was wrong from the beginning, but should work nonetheless. The windows gltf viewer and others have no problem with it. We have large datasets and I would rather not have them repacked and redistributed. 

You can find a sandcastle with the models [here](https://sandcastle.cesium.com/#c=tVRda9swFP0rwk8OeLKTbjDcNKwrgw1atrVlL/MYinVTi8iSkeS4H+S/78qy0yTLyx5mYmyde++55344pVbWkY2ADgy5IAo6cgVWtDX90WNxEZX9+Uorx4QCU0QJeSkUIUKt9Ef9mJMVkxYSD1mQUDqh1RfFRcmcNgfWinHd2Zw4046IbiW/VKJmDnb4dnJeqEKtWtVzkdIAmm80Bxm3RiakAvFQuUmQEbRTUE44AZYaqPUGLqWMA03ZV9hoK3qygxqvmHH4xtRZ/OZ9lmUJ8b/JOSGe2d8hugLGhXrA4CHwhrmKOn2LMFM2np6988lG90a4skLnbA8zWsojqGqOWv45pPnmw2/RPx7yJoEx6Un2E2kjsG42FDaw3BuUtNKmtrQ6IvzeYiONQvfYk5BdW5JwREX+JTRuTNJ39gn5jzvNOI9fQqBiNc7PD+eQNz/OsKc43z8M5toPOScDK0FGEWjJiITntvffhl4Mupxh5Rr4p1Fu0I0e29c10I1PZtH600cOeRw8upwUUafNGtuFGz6IVWGhcYnHXYwnr+L293LEUGBUOdfYPE27rqNcPEhHOaT4WKXXs9nv6WyWzXDX3mbUY7tk/spoNh5CabtKSXJC79LoNaj/Jzfw/5NMnM+vfnvumOIls06C35N7reWSmRtQbTzMwEdGSTS37knCYuT7IOpGG+dnHlOaOqgbiaptumxxuI6W1o4p5+l+6JyLDRH84sT/FSklsxYtq1bKO/EMRbSYp+j/V6jU/ffydQNGsifvVk0X1wGklM5TPJ6OdKHAI+Y/)
