### ISSUE TITLE
Implementation of `ScreenSpaceCameraController` does not follow documentated specification

### ISSUE THREAD

**Issue by crubier** [AnalyticalGraphicsInc/cesium#6414]
The actual behaviour of `ScreenSpaceCameraController` does not fit what is said in the documentation. 

This table summarizes the discrepancies (in red):

https://docs.google.com/spreadsheets/d/1OzlwQqFJkqIsK44NLkyFCYyDyM62EvHrvFqPZvDB5Ag/edit?usp=sharing

<img width="708" alt="screen shot 2018-04-03 at 10 21 41" src="https://user-images.githubusercontent.com/2954572/38240930-d37f16ca-3728-11e8-8c57-8792909b8cba.png">

**Comment by hpinkos** [comment]
@crubier Thanks for taking the time to summarize this!  Could you open a pull request with the documentation changes?  Note that we refer to 'tilt' as the middle mouse action where you're changing the camera pitch to get a horizon view, so I think the documentation for tilt is correct.  I think the rotation documentation is just out of date and wasn't updated the last time we made changes to the screen space camera controller.

**Comment by hpinkos** [comment]
Thanks again @crubier!  We updated the documentation in #6489
