### ISSUE TITLE
CI whitelist for publishing branches to S3

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6423]
Branches in this repo are published to S3 so we can run the tests, Sandcastle, etc.

It would be great if we could whitelist frequent contributors who work on forks so that we have easy access to the built branches on S3.

**Comment by ggetz** [comment]
If the contributor sets up credential for their fork, it can also be deployed: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md#configure-s3-credentials
