### ISSUE TITLE
Sandcastle debugging

### ISSUE THREAD

**Issue by hanbollar** [AnalyticalGraphicsInc/cesium#6425]
is there currently a way to debug the Sandcastle example itself? if not - could we implement this feature - because currently you can use the developer tools to debug specific functions in the cesium files; however, I'm not sure you can actually step through any of the example itself.

**Comment by shunter** [comment]
You can put `debugger;` statements in the example itself which act as a breakpoint.  After it hits the breakpoint then you can step through like normal.  Otherwise there's not really a good way to set breakpoints because the "source file" is a temporary string injected into the bucket dynamically.

**Comment by emackey** [comment]
Yes to `debugger` statements in Sandcastle.  The other method I normally use, in combination with that, is the "open in new window" button at the top, then you can debug your demo directly as a top-level frame, without the sandbox iframe getting in the way.  You don't need "Run (F8)" to make that work.
