### ISSUE TITLE
Clipping Plane doesn't work as expected

### ISSUE THREAD

**Issue by SelimAbidin** [AnalyticalGraphicsInc/cesium#6431]
![gif](https://user-images.githubusercontent.com/1409316/38454962-a99339b4-3a79-11e8-98b4-a8e0603184bd.gif)

The gif is recorded with Cesium 1.43, so it uses same clipping collection on globe and 3dtileset. It works on ground perfectly but on tileset.

[Here Version 1.44 Sandcastle Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=jVVdb9owFP0rFi9NpMwkhfI1ila1lca0btXKWk1jDya5gFXHjmwH1lX8910TsvBVtDwEbN9z7vG59s1YLpgmCw5L0OSSSFiSazA8T+njes47i9fDayUt4xL0mf9+LMdymsvYciWJUCwZcQEGrJdr4ZPXsST4OFpbzCNvkYCaGCTQTPOUW74AQ1mSeFs5i5/GTUn4SpCSrHzfpXSsG0aqgSUv91ql3AC1c5BelWzgJJSAUophaSbgEWK7u8trpi3+Y7LhRUEYhP4OsFAdsxQ0o0Kp5yvrlRImKpcJl7OHbA4aKO7Mgg7e4G7TVivsNFqNqNGKOo1mOyDvOlFEu61Wt3sRRZ2oc9ENWp0ujaKLsH3e7IatZrvpNn5KzEgzaaZKp94m5R2zmv9u0uHN7ZfRcPTDP+JErJmN5/eCSdj1Yj3lHYinsVA4XznoBySkoTsH27yx4FmGfqxZUFgMVd3RGyz4pt6vFc49mTLcnaQeOe3sHmotv0f2yNyT8BSkQUaD68fKce51wzAg+PKDQ3jKMBtnAsElUAml6dPH4eiWLrmdX4lszryQdo7BS2HbNh8JU7kVfB1odX4iYJ37qJRdyKoaroobWk0IvBVldZBAQHFzd+/BdvWqoINiuWXTIz8PBb9F9v8Has+FX3tjSGbwxBM775GIhnuLqUpAFKe/d3gSaazSLLdwV0WVsj7lAjXdYNGpVEvP949kXbt+ugar7cZRr+/0u5lQE5Swrcqg+5rP5ray+h+6vAYHgCM1LJOufKqwDeol9kPPA62V9jedsFQY44VQArBzzDYBJdSRrNzLXeMJT79jz70sdztU8hsYlWt0cYoN98qgtmHiNTqNtjto2/2/wPq1oNY39kXAoMjwgaeZ0tb1co/SugWsO/pt6pM8fnYbNcYx9eslqJ/wBeHJ5bi29/EZ19AEZgyuTHMhHvgfGNcG/TrG78CcKDTq6wK0YC8uZB4NPheTlNJ+HYeHKKuUmDC9xfgX)

**Comment by ggetz** [comment]
Hi @SelimAbidin, you shouldn't need to specify the additional `modelMatrix: clippingPlaneTrace.computeModelMatrix(Cesium.JulianDate.now())` for the `ClippingPlaneCollection` you apply to the tileset since they are in the same coordinate system. If you remove that line, it works as expected.

**Comment by hpinkos** [comment]
@SelimAbidin in the future, if you have problems like this please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
The forum has much higher traffic so it is more likely that someone will be able to help.  Our team answers questions on the forums well.  We try to use GitHub exclusively for tracking bugs and planning new features.  Thanks!
