### ISSUE TITLE
How to get the height of 3dtiles

### ISSUE THREAD

**Issue by githubhanjunjun** [AnalyticalGraphicsInc/cesium#6438]
I want to do a point to point general view analysis, my idea is, straight line interpolation, the height of the interpolation point and the 3dtiles height of the point coordinates, if higher than the height of 3dtiles is to be viewed. But I don't know how to get the height of 3dtiles of a coordinate point. I hope I can get the answer, thank you.

**Comment by pjcozzi** [comment]
@githubhanjunjun this is part of #6080 as @lilleyse mentioned so closing as a duplicate.  Keep an issue on that issue.
