### ISSUE TITLE
Overlapping polygons rendering incorrectly with clampToGround

### ISSUE THREAD

**Issue by jimmyangel** [AnalyticalGraphicsInc/cesium#6448]
Dear Colleagues,

I would like to report what I believe is a bug rendering overlapping polygons loaded with GeoJsonDataSource using the clampToGround option set to true ([posted](https://groups.google.com/forum/#!topic/cesium-dev/6oVV6Wq6x8k) in the forum as well).

Here is a Sandcastle reproducer:

```
var viewer = new Cesium.Viewer('cesiumContainer');
 
Sandcastle.addDefaultToolbarButton('Eagle Creek Fire', function() {

    var TestDataSource = new Cesium.GeoJsonDataSource("EagleCreek");   
    viewer.dataSources.add(TestDataSource);
    TestDataSource.load('https://stable-data.oregonhowl.org/test/test4.json', {clampToGround: true});

});

//Reset the scene

Sandcastle.reset = function() {
    viewer.dataSources.removeAll();
    viewer.scene.camera.flyTo({
        destination : Cesium.Cartesian3.fromDegrees(-121.66810, 45.03687, 92812),
        maximumHeight : 14000,
        orientation : {
            heading :0.0325,
            pitch : -1.052,
            roll : 0.0}
    });
};
```
Here is what you see:

![screen shot 2018-04-14 at 2 28 56 pm](https://user-images.githubusercontent.com/6842945/38772614-36efb03c-3ff0-11e8-8578-b5d4eaaf5ad4.png)

If you change clampToGround to false then you will see this, which looks correct:

![screen shot 2018-04-14 at 2 31 03 pm](https://user-images.githubusercontent.com/6842945/38772626-7f4c240a-3ff0-11e8-9f95-16e33feae572.png)

This is only happening with "large" GeoJSON (or TopoJSON) files -- i.e., many (>20) relatively complex polygons (> 2000 coords each) which have a lot of overlapped areas. I have another, larger example if you want to see it.

I looked at the GeoJSON file and there does not seem to be anything wrong with it. I can see it fine with both mapshaper and geojson.io.

Also, if I render each individual feature (Polygon or MultiPolygon) separately by using non-overlapping Entity availability settings, then  each shape will be rendered correctly. You can see this in the current version of my application using the same data set (in topojson) [here](https://oregonhowl.org/?view=rcwildfires&fId=2017-Eagle_Creek). As you move through the timeline, each feature is displayed separately. And it works fine.

Please let me know if there is anything I can do to help you guys figure this out.

Thank you,

Ricardo

**Comment by ggetz** [comment]
Thanks for the thorough report @jimmyangel. Related discussion on the forum here: https://groups.google.com/forum/#!topic/cesium-dev/6oVV6Wq6x8k

**Comment by hpinkos** [comment]
This appears to be fixed

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/6oVV6Wq6x8k

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/6448 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
