### ISSUE TITLE
Model clipped inappropriately

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#6451]
While experimenting with lighting options for a glTF model provided in https://github.com/KhronosGroup/COLLADA2GLTF/issues/172, I discovered the model sometimes disappears from view while moving the camera.  This didn't start happening until I merged master into my branch, bringing in logDepth along with it.

Git bisect isolates a specific commit from LogDepth where the problem is introduced:  0d90d985b0179003b2

The original model from that issue has some un-related validation errors, here's a cleaned-up copy of the model:

[Collada2gltf_issue172.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/1916877/Collada2gltf_issue172.zip)

And the reproduce code:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    infoBox : false,
    selectionIndicator : false,
    shadows : false,
});

function createModel(url) {
    viewer.entities.removeAll();

    var position = Cesium.Cartesian3.fromDegrees(-123.074085, 44.050050, 10);
    
    var heading = Cesium.Math.toRadians(-20);
    var pitch = 0;
    var roll = 0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            scale: 10,
            uri : url,
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });
    viewer.trackedEntity = entity;
}

createModel('../../SampleData/models/emackey/Collada2gltf_issue172.gltf');
```

Here's the bad behavior:

![logdepthclipissue](https://user-images.githubusercontent.com/1235080/38830262-b3dfe680-4189-11e8-8949-c67cdfad90c0.gif)

**Comment by emackey** [comment]
Note that this bug is "not yet released", since it was introduced with LogDepth #5851 last week.

**Comment by mramato** [comment]
I tagged this for next release since it's a bad regression.  CC @bagnell @lilleyse
