### ISSUE TITLE
Necessary import?

### ISSUE THREAD

**Issue by puckey** [AnalyticalGraphicsInc/cesium#6456]
I noticed [Source/Scene/Globe.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Globe.js) is importing Material.js but isn't using it in the code aside from referring to it in the doc comments. This is causing lots of code to be included in my builds unnecessarily...

Would a pull request removing this import be welcome?

**Comment by hpinkos** [comment]
Thanks @puckey, yes it looks like that can be removed.  Feel free to open a PR removing that and any other unnecessary requires.  We usually go through maybe once a year and clean that up, but it's been a little while
