### ISSUE TITLE
Problem occurs when viewer.trackedEntity is set 'null' and when i use viewer.flyTo(zoomTo)

### ISSUE THREAD

**Issue by medusaless** [AnalyticalGraphicsInc/cesium#6458]
If I set viewer.trackedEntity = null， error occurs when i use viewer.flyTo or viewer.zoomTo
If if set viewer.trackedEntity = undefined， the error doesn`t happen

**Comment by hpinkos** [comment]
Hello @medusaless.  This is expected behavior.  When using the Cesium library, you should always use `undefined` instead of `null`.   Thanks!
