### ISSUE TITLE
shadow volumes broken in master at near distances

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6461]
Shadow volumes (underpinnings of all the polygon/corridor stuff that's clamped to ground) seem to be broken at distances close to the camera. It *kind of* looks like the camera's near plane is causing problems here. Steps to reproduce:
1) launch the `Ground Clamping` Sandcastle in `master`
2) select `Draw Rectangle`
3) go to a corner and zoom in to a view something like this:

![bug](https://user-images.githubusercontent.com/5395255/38942299-6efc9bc0-42fc-11e8-99bb-3c5436b29fed.JPG)

@bagnell do you think this might be related to changes in https://github.com/AnalyticalGraphicsInc/cesium/pull/5851?

**Comment by hpinkos** [comment]
For reference, here's what the problem looks like

![ground](https://user-images.githubusercontent.com/3451886/38942717-879f28fe-42fd-11e8-8518-67790c7d9510.gif)

@bagnell we should fix this before the next release

**Comment by likangning93** [comment]
Setting `viewer.scene.logarithmicDepthBuffer = false;` gets rid of the problem, so more evidence to this being a log depth thing.

**Comment by likangning93** [comment]
@bagnell I think this is related to this comment: https://github.com/AnalyticalGraphicsInc/cesium/pull/5851/files#r172639411

Forcing `DISABLE_GL_POSITION_LOG_DEPTH` [hereabouts](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ClassificationPrimitive.js#L532) seems to help for me. I'll investigate a bit more and open a PR, but I'm... not super confident heheh.
