### ISSUE TITLE
About Cesium3DTileset  modelMatrix

### ISSUE THREAD

**Issue by 9lovingly** [AnalyticalGraphicsInc/cesium#6466]
I set the modelMatrix to the Cesium3DTileset,but there is no change to the location:
rtcCenter = new Cesium.Cartesian3.fromDegrees(-75.6164030283303,40.06352846008451)
posMat = Cesium.Transforms.eastNorthUpToFixedFrame(rtcCenter);
//m= Cesium.Matrix4.fromTranslation(posMat);
var tileset22 = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    id:'house11',
	url:'Data/BatchedmaoLOD1',//Batchedsurface BatchedmaoLOD1 Batchedmfactory1 BatchedmaoLOD3 Batchedmfactory1 gming  Data/Cesium3DTiles/Tilesets/CityModel00  GJD_CLB_B  xjp tile sinp sss aia aia new flout DA_WISE_GML BatchedT2 
	//loadSiblings:true,
	//dynamicScreenSpaceError:true,
	debugShowBoundingVolume:true
	modelMatrix:posMat
	}));

Another Question is why the default location is in U.S.A NewYork nearby if I didn't set the modelMatrix?

Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by hpinkos** [comment]
Hello @9lovingly, when we position a tileset we typically have to set the tileset root transform to the identity matrix.
```js
    tileset._root.transform = Cesium.Matrix4.IDENTITY;
    tileset.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(position);
``` 

In the future, if you have questions like this please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
