### ISSUE TITLE
Encountered a problem when interactive drawing polygon when terrain is added

### ISSUE THREAD

**Issue by medusaless** [AnalyticalGraphicsInc/cesium#6469]
When terrain is added, If I dynamicly draw polygon and set the polygon`s hierarchy to a callbackproperty which returns an array containing the polygon`s vertex cartesain3. A point is added to the callbackproperty when leftclick event is fired. A point is first poped then added when mousemove event is fired. But if i click on the same location or move very slowly after I left click on map, error occurs when dynamicly drawing.

When I dont add terrain,the code works fine.

Do you know why?

**Comment by hpinkos** [comment]
Hi @medusaless, sorry I'm not exactly sure what the error is.
Can you please post on the forum? https://groups.google.com/forum/?hl=en#!forum/cesium-dev 
Someone will be able to help you there.  We use GitHub exclusively for tracking bugs and planning new features.
When you post on the forum, please include a [Sandcaslte Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) that reproduces the problem.  That'll make it easier for people to help you debug the problem.

Thanks!

**Comment by medusaless** [comment]
Thank you for your help. Can you give me your email or something like that? I want to ask you more questions about cesium.

**Comment by hpinkos** [comment]
@medusaless The Cesium team monitors the forum so that's the best place to ask questions about Cesium

**Comment by medusaless** [comment]
I have some problems creating new google account, because I am in China.
I have already pasted my code link below. 

[](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=xVdtc+I2EP4raj5czA1j2n7pDIRMMxy9Y0oumYTmPpTOnbAXrEFIHkmG0h7/vSvZBvkFmrl+aN4meHef3X32RfJc9N7OxVtCZgkoIBR/zU6SjYxBEyNJRHmUcWrwcQKEw9KQiLNoTVZKZiImqWTCEIewgIhmGhVBKcoEYWLJMxCRBULbXLPEY1KE1spZTpbOIWGaXM/GT093k4/XXYIwUhEZRZnSwUQgCMo1M5mzRktCHPCWwQ7UF106flRyy2JQRCcy4zHGRUagWbYJIwXUfJKKx7NcNeh0Qodz+uPHMp5OH58fJu8wGGbITqq1JksmoBlN19nugMQSk6RxXAbTcVkWaTrpF0PWQu7ILtkXKVLFNJK0S0CcyNMWBWJrjj+9ubDfW6qKdMmQCNiVib24Z8F15D6O0AtigLruDEqrR8n3KylmoA2aLjMRORKDHK3rcu6Qv10aLrfw6Cf/Z+CJHEHDnKevX081c96OWrGiOyZWL6AM/In5Dcnvfwya8iKysTDM7FEJuwosyXGh61kw/S63GWPnYRaUaziPOLLVhrqip469yBc0WmPDpBhk3bmnuWAiHm9BmMAyesiL4VEapkoaafappaUgMZJCG5VFRqq+T3/eKsSDLC2O7qSY4qCN7Jx9oCLmrgxnJC62wAo7gwbME1slZ3AaootA9xIn+15uoYFTl1RhakBgEz5BeB38jLMJ4jmlEYw9pcBrRawXtnIzOh801GAmIs3Mnevv4Axp3XNuZ1jCcDr+ZfZ5NJ2Mfv0WXw1iLzt7mrz/8B+81em/7Oz+4bfn8ef7h5dx6etQtGOTo8B5rzSnXST5Gi/KvwLz3p0Dj/ZpbhGmEtei3YmnZdHIrLYbwjTTSeCgfVW2JEGrOgexMgkZDsmP5M0b8t356a/Ef2nyvV4c1aTBaV024OyXApMp0ZrYoKp98Kajm6+l6pQcI8TlXyQStEbcabE5t/5wC4EXyKFaec9TWblG0aFczh5L+cIOanykOVS/jaeEgaIqSvZ9cuyRppbMDMcN3Hdht8g3mJVilPcrJZNcqvtCcqybLww/fZjMxuGOmeSOpwkNvg9/6nRq+AePpXM9Wz+vcm5qusXGcjIGrpxBrugPXjl6jZXxf83exYzbz9Nzh7PXdKcdU99WLXmyZdCA61SbKZ+3ZkefjvfXEwb240XOXrOE2rfM65bcgQCy+a9ubl/tRaZBZ/Dt4VRrViPt1F+VC2Odb5Fx7mFqnLooIUHDxt2TKGZ/vEL2mwNvgRXdl2U8XgY2uE1sUR9xbp7o/rS9Bk2MSiMUCDoCAeGKywWEKWIE6KTb1GiDW+AorAdteeArwyR/Z+i/LooiDxvAmHOWasnii6nUfXvNXxxEzo03e6hhV6V3By2u/TjvV92rG232HG5z/Z/ZJpXKkEzxIAx7BjapffvTvUUWrcGEkXYXsJteaXQTsy1h8XB+VXv5mF/hmyLVGiVLbIdn9hfMr25veqhfMeOSxtiWD1tQnO6tSvLD7TR/GIbhTQ8/Nq2MlHgeKg/xHw)

**Comment by medusaless** [comment]
I have some problems creating new account in Google right now.

I have already pasted my code below.

Please have a look.

[https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=xVdtc+I2EP4raj5czA1j2n7pDIRMMxy9Y0oumYTmPpTOnbAXrEFIHkmG0h7/vSvZBvkFmrl+aN4meHef3X32RfJc9N7OxVtCZgkoIBR/zU6SjYxBEyNJRHmUcWrwcQKEw9KQiLNoTVZKZiImqWTCEIewgIhmGhVBKcoEYWLJMxCRBULbXLPEY1KE1spZTpbOIWGaXM/GT093k4/XXYIwUhEZRZnSwUQgCMo1M5mzRktCHPCWwQ7UF106flRyy2JQRCcy4zHGRUagWbYJIwXUfJKKx7NcNeh0Qodz+uPHMp5OH58fJu8wGGbITqq1JksmoBlN19nugMQSk6RxXAbTcVkWaTrpF0PWQu7ILtkXKVLFNJK0S0CcyNMWBWJrjj+9ubDfW6qKdMmQCNiVib24Z8F15D6O0AtigLruDEqrR8n3KylmoA2aLjMRORKDHK3rcu6Qv10aLrfw6Cf/Z+CJHEHDnKevX081c96OWrGiOyZWL6AM/In5Dcnvfwya8iKysTDM7FEJuwosyXGh61kw/S63GWPnYRaUaziPOLLVhrqip469yBc0WmPDpBhk3bmnuWAiHm9BmMAyesiL4VEapkoaafappaUgMZJCG5VFRqq+T3/eKsSDLC2O7qSY4qCN7Jx9oCLmrgxnJC62wAo7gwbME1slZ3AaootA9xIn+15uoYFTl1RhakBgEz5BeB38jLMJ4jmlEYw9pcBrRawXtnIzOh801GAmIs3Mnevv4Axp3XNuZ1jCcDr+ZfZ5NJ2Mfv0WXw1iLzt7mrz/8B+81em/7Oz+4bfn8ef7h5dx6etQtGOTo8B5rzSnXST5Gi/KvwLz3p0Dj/ZpbhGmEtei3YmnZdHIrLYbwjTTSeCgfVW2JEGrOgexMgkZDsmP5M0b8t356a/Ef2nyvV4c1aTBaV024OyXApMp0ZrYoKp98Kajm6+l6pQcI8TlXyQStEbcabE5t/5wC4EXyKFaec9TWblG0aFczh5L+cIOanykOVS/jaeEgaIqSvZ9cuyRppbMDMcN3Hdht8g3mJVilPcrJZNcqvtCcqybLww/fZjMxuGOmeSOpwkNvg9/6nRq+AePpXM9Wz+vcm5qusXGcjIGrpxBrugPXjl6jZXxf83exYzbz9Nzh7PXdKcdU99WLXmyZdCA61SbKZ+3ZkefjvfXEwb240XOXrOE2rfM65bcgQCy+a9ubl/tRaZBZ/Dt4VRrViPt1F+VC2Odb5Fx7mFqnLooIUHDxt2TKGZ/vEL2mwNvgRXdl2U8XgY2uE1sUR9xbp7o/rS9Bk2MSiMUCDoCAeGKywWEKWIE6KTb1GiDW+AorAdteeArwyR/Z+i/LooiDxvAmHOWasnii6nUfXvNXxxEzo03e6hhV6V3By2u/TjvV92rG232HG5z/Z/ZJpXKkEzxIAx7BjapffvTvUUWrcGEkXYXsJteaXQTsy1h8XB+VXv5mF/hmyLVGiVLbIdn9hfMr25veqhfMeOSxtiWD1tQnO6tSvLD7TR/GIbhTQ8/Nq2MlHgeKg/xHw](url)

**Comment by hpinkos** [comment]
@medusaless sorry you can't access the forum.  I don't have time to debug your application, but from a breif look I noticed two things:

- There might be a problem with how you're adding and removing points from the polygon on mouse move. 
- Sometimes `pick` and `pickEllipsoid` return `undefined`.  You should be checking if the result is defined before adding it to your polygon positions
