### ISSUE TITLE
Imagery Layers Split sandcastle example throws error when loaded

### ISSUE THREAD

**Issue by hanbollar** [AnalyticalGraphicsInc/cesium#6471]
[Imagery Layers Split](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers%20Split.html&label=Beginner)

i was going through some sandcastle examples and when i got to the Imagery Layers Split one it threw the following error when it first loaded:
Uncaught ReferenceError: require is not defined (on line 8)

when i reloaded the page through directly clicking the link it worked fine though so I'm not entirely sure what happened...

**Comment by hpinkos** [comment]
@hanbollar I couldn't reproduce this locally.  Did you run `npm run build` before running sandcastle?

**Comment by hpinkos** [comment]
Oh, nevermind.  I think you linked the wrong example.  There seems to be a problem with this one: 
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers%20Texture%20Filters.html&label=Beginner

**Comment by hpinkos** [comment]
@hanbollar you can fix this by replacing `require.toUrl('Assets/Textures/NaturalEarthII')` with  `Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')`

Can you open a pull request please?  Thanks for finding this error!

**Comment by hanbollar** [comment]
@hpinkos i didnt run it locally - i was running it directly on chrome...

**Comment by hpinkos** [comment]
Thanks!  Yeah it looks like it only causes a problem on the built version of Sandcastle, so it's good you were going through the website and stumbled across it =)
