### ISSUE TITLE
Draco compressed glTF skinning model is not displayed

### ISSUE THREAD

**Issue by cx20** [AnalyticalGraphicsInc/cesium#6480]
I tried to display several Draco format files with Cesium.js.
However, the Draco format glTF skinning model does not appear to be displayed.

|model        | glTF          |glTF-Draco|
|:-----------|:------------|:------------|
|[Duck](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck)|:white_check_mark: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=Duck&scale=1&type=glTF)|:white_check_mark: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-Draco)|
|[CesiumMilkTruck](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMilkTruck)|:white_check_mark: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF)|:white_check_mark: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF-Draco)|
|[RiggedSimple](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedSimple)|:white_check_mark: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=RiggedSimple&scale=0.2&type=glTF)|:x: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=RiggedSimple&scale=0.2&type=glTF-Draco)|
|[CesiumMan](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan)|:white_check_mark: [Sample](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=sampleModels&model=CesiumMan&scale=1&type=glTF)|:x: [Sample](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=CesiumMan&scale=1&type=glTF-Draco)|

Because it can be displayed in Three.js and Babylon.js, I think that it is not a model problem but a problem of Cesium.js.

**Comment by lilleyse** [comment]
Fixed in #6420
