### ISSUE TITLE
Add changing data to the description of entity

### ISSUE THREAD

**Issue by Tarlan0001** [AnalyticalGraphicsInc/cesium#6481]
I have created an entity, initialized its positions with an array of lat/long. That's to say, the position of an entity is changed with time.

Now, I would like to add the current position to the description of an entity, which is shown when the entity is selected.

How to add the dynamic data to the description? How to change the data with time?

**Comment by hpinkos** [comment]
Hi @Tarlan0001, a `entity.description` is a `Property` like all of the other entity attributes, so you can use a [CallbackProperty](https://cesiumjs.org/Cesium/Build/Documentation/CallbackProperty.html) or [TimeIntervalCollectionProperty](https://cesiumjs.org/Cesium/Build/Documentation/TimeIntervalCollectionProperty.html) to make it dynamic.

In the future, if you have questions like this please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
