### ISSUE TITLE
Add RTC_CENTER support for b3dm

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6488]
`RTC_CENTER` will soon be a part of the `b3dm` format and we should add support for it in Cesium.

Likely [CESIUM_RTC](https://github.com/KhronosGroup/glTF/tree/master/extensions/1.0/Vendor/CESIUM_RTC) and `RTC_CENTER` will share the same implementation.

Will need to think about how this interacts with [relocating a tileset](https://github.com/AnalyticalGraphicsInc/cesium/issues/6394)

See https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/263 and https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301

**Comment by pjcozzi** [comment]
@lilleyse is this finished?

**Comment by lilleyse** [comment]
No, most of the 3D Tiles 1.0 changes have not been implemented in Cesium yet, besides https://github.com/AnalyticalGraphicsInc/cesium/pull/6678.

Now that the 1.0 edits have been stable for a while I'll open a task list issue for all the items that need to get into Cesium.
