### ISSUE TITLE
Add extensions and extras to 3D Tiles

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6490]
https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/8 adds extras and extensions properties to the top-level `tileset.json`, individual tiles, feature table, batch table, and other misc json objects. How do we want to expose this from the API?

To start, we should atleast add an `extras` getter/setter to `Cesium3DTileset` and `Cesium3DTile`.

**Comment by pjcozzi** [comment]
As discussed offline, let's push this until after spec work unless it is critical to getting the spec right...which I don't think it is in this case given this is just following glTF's lead.

**Comment by lilleyse** [comment]
I agree, the implementation can wait.

**Comment by apopiak** [comment]
I would be interested in using extensions. As extras seem to be equally powerful that would be my fallback, but not optimal for building something well-defined.
Use-case: including (just bare-bones) images in 3D-tiles data that are loaded based on the HLOD.

**Comment by lilleyse** [comment]
@apopiak you can start using them now. The extras/extensions API looks like:

[tile.extras](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTile.html?classFilter=cesium3dtile#extras)
[tileset.extras](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#extras)
[tileset.hasExtension](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#hasExtension)

There isn't a great way to get extension data from the API since it usually needs to be implemented internally. But for your use case you could start by storing image uris in each tile's `extras` and then listening to the [tileset.tileLoad](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#tileLoad) and [tileset.tileVisible](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#tileVisible) events where your app would handle the logic for loading and displaying the images.

**Comment by apopiak** [comment]
Ok, cool, thanks for the info!
Will use extras then.
