### ISSUE TITLE
 'scene.pickPositionSupported' is not supported in IE11

### ISSUE THREAD

**Issue by liubgithub** [AnalyticalGraphicsInc/cesium#6495]
Hi, I enjoyed cesium very well, but I am not clear why 'scene.pickPositionSupported' is not supported in IE11. It means that I can't interact with anything in the scene when my program running in IE11. Are there any way I can solve this problem? Expecting your reply, thank you very much!

**Comment by hpinkos** [comment]
Hello @liubgithub.  Unfortunately IE11 does not support the WebGL features we need for `pickPosition` to work.  However, most other Cesium features should work fine in IE11.  `pickPosition` is just used for depth picking, which would be for something like getting the position of when you click on a model or 3D tiles building.  You can test our demo application on https://cesiumjs.org/.  Click 'tap to interact' to confirm that Cesium works in IE11 on your computer.

In the future, please ask questions on the forum if you can: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.
