### ISSUE TITLE
Add support for KHR_materials_unlit

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6507]
The [KHR_materials_unlit](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit) extension defines an unlit shading model that is suitable for photogrammetry and other models that shouldn't be lit in a PBR way.

When using this extension normals do not have to be generated. CC https://github.com/AnalyticalGraphicsInc/cesium/issues/6506

This would replace the stopgap solution in https://github.com/AnalyticalGraphicsInc/cesium/pull/6501

**Comment by OmarShehata** [comment]
I think we can close this now @lilleyse !
