### ISSUE TITLE
Sandcastle "back" button broken

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#6509]
Visit any Sandcastle page:  https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/

Click on one of the gallery icons below.  Note the top URL bar updates, and the new gallery item is loaded into the editor.

Now, click the back button.  The Top URL goes back to the previous Sandcastle Demo URL, but the editor does not respond to the change.  It used to, not sure when.  I could bisect this if that's really needed (but it would take longer than normal since Sandcastle itself is part of my normal bisection workflow).

**Comment by shunter** [comment]
Likely I broke this in #6342.  I looked at it briefly and popstate is firing but the state is null.  I see that there's code that calls replaceState with `null`.  Probably at the time I was not aware the app was actually using state for anything.
