### ISSUE TITLE
CylinderGeometry Documentation Clarification

### ISSUE THREAD

**Issue by hanbollar** [AnalyticalGraphicsInc/cesium#6511]
in the constructor it has the following exceptions 

```
@exception {DeveloperError} options.topRadius must be greater than 0.
 @exception {DeveloperError} options.bottomRadius must be greater than 0.
 @exception {DeveloperError} bottomRadius and topRadius cannot both equal 0.
```

however, based on the first and second exceptions here, there should be no case where the third exception will exist.

**Comment by hpinkos** [comment]
@hanbollar these 3 lines of documentation can be removed, they weren't updated when we changed the code
