### ISSUE TITLE
CESIUM FOR GIS DATA ANALYTICAL/MATH OPERATIONS ON 3D

### ISSUE THREAD

**Issue by AkshayGore** [AnalyticalGraphicsInc/cesium#6517]
HI,
HOW TO PERFORM ANALYTICS ON GIS DATA USING CESIUM APART FROM VISUALIZATION?
IS THERE ANY APPLICATION DEVELOP OR WEBSITE ONLINE THAT DO ANALYTICS.
THANKS
AKSHAY GORE

**Comment by hpinkos** [comment]
Hi @AkshayGore, analytics is something we plan to make available as part of the [Cesium ion](http://cesium.com) platform but they are not available at this time.

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features
