### ISSUE TITLE
How to zoom in when I click one of model part of 3D tiles

### ISSUE THREAD

**Issue by 9lovingly** [AnalyticalGraphicsInc/cesium#6518]
When I click one of model part of 3D tiles like air-condition or chair of my model(3D tiles),I'd like to zoom it in.Is there any method to support it.Anyone can help me?Thanks a lot!

Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by hpinkos** [comment]
Hello @9lovingly,  this is not something supported automatically, but you should be able to implement it using [scene.pickPosition](https://cesiumjs.org/Cesium/Build/Documentation/Scene.html#pickPosition) to get the position on the 3D tile you clicked on, and [camera.flyTo](https://cesiumjs.org/Cesium/Build/Documentation/Camera.html#flyTo) to zoom the camera to that position.

If possible, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features. Thanks!
