### ISSUE TITLE
Particle system demo does not play well with timeline

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6521]
http://localhost:8080/Apps/Sandcastle/index.html?src=Particle%20System%20Tails.html&label=New%20in%201.44

1. The demo animates whether the clock is running or not.
2. Jumping around in the timeline seems to completely break the effect.

**Comment by hpinkos** [comment]
@mramato this is a new demo, should we fix it before the release tomorrow?  @hanbollar @ggetz

**Comment by ggetz** [comment]
The fix for this would be to factor in the delta time that is passed as the second parameter to the update function, but it would take a little bit of fiddling to make it look nice for all time multipliers. 

@hanbollar would you be interested in providing a fix?

**Comment by hanbollar** [comment]
@ggetz @mramato @hpinkos I can take a look at this and try to fix the visual

**Comment by hpinkos** [comment]
THanks @hanbollar!

**Comment by hanbollar** [comment]
@ggetz @mramato @hpinkos - added sort of a hacky fix - lmk if this is ok for a sandcastle example - i explain my reasoning in the pull request
