### ISSUE TITLE
Entities store primitives data even when removed 

### ISSUE THREAD

**Issue by EdenEdk** [AnalyticalGraphicsInc/cesium#6534]
I am using cesium 1.34 in my project (abit problematic to updrage to the lastest)
My main goal is to draw a large amount of comoplex entities which contains: 
point
polygon
label
billboard
and stores an object which i get when pressing (pick..)

I display a max of 20,000 of these complex entities which change and update same time, but i create more and more as time pass while deleting old.
some time ago i used primitives in order to do this, but after some nasty memory and performance issues i consult with some cesium users in your google groups and they all told me, use entities for complex drawing with suspend/resume events
so i did..

after switching i did saw a differnce in performance and memory but i noticed that after i load alot of data my system becomes slow and memory hungry..
i spanshot before the data loading and after the data loading without using cesium, garbage collected and cleaned everything and the MB difference was minor, something like 10 MB.
but when using cesium and deleting the data the MB difference was alot, something like 100MB per 5000 entities.
I started looking up inside and found some wierd stuff..

So i created this:
![default](https://user-images.githubusercontent.com/15359272/39482060-4047f9d0-4d76-11e8-8db8-137e3f22f23c.PNG)

a simple entities usage which create 64,800 entities, paint them and position them in a different position on the globe..
after 5 seconds (basicially after cesium finish drawing this)
i delete them all and print hte viewer to the console, i print it just so i can stop in the debug and watch the viewer and this is what i found:

![default](https://user-images.githubusercontent.com/15359272/39482450-c2199774-4d77-11e8-9040-bc6e03f787a4.PNG)

while the entities collectiong appear empty..
the PointPrimite collectiong hold on to the data
BUT!!!
not all the data, this data:

![undefined](https://user-images.githubusercontent.com/15359272/39482482-e0dafdc4-4d77-11e8-8ab6-c9cf0e48befe.PNG)

and the same thing happens in my app, but for all collections:
labels
billboards
points
and so on..
that means that apperantly even after I remove the entities there is alot of data kept in the memory
COLLECTIONS_AMOUNT * ENTITIES_CREATED

**Comment by hpinkos** [comment]
Hi @EdenEdk!  Thanks for taking the time to investigate this.
However, Cesium is designed to only remove things from the `PointPrimitiveCollection` when it needs to, so logging a `scene.primitives` immediately after calling `viewer.entities.removeAll` doesn't give an accurate picture of how Cesium works.  They are likely removed from the collection on the next render instead.  This type of management prevents constantly resizing the array of primitives when things are added and removed which would be even worse for performance.

I do believe that you are running into this bug though: #3018
I'll make a comment in that issue so we can notify you when that has been fixed.

I would also highly recommend upgrading to a more recent version of Cesium.  We are constantly making performance improvements so it's possible that using the latest version will help solve some of the issues you're seeing as well.

**Comment by EdenEdk** [comment]
Ok i got you but, if cesium remove only from the pointPrimitive collection, it aggregate the other collections(labels, billboard, etc) when i create a new entity..
And then the collections wont clean

**Comment by hpinkos** [comment]
I'm not sure I know what you mean by "it aggregates the other collections when I create a new entity"
The entity layer creates PointPrimitiveCollections, LabelCollections and BillboardCollections under the hood but it is optimized in a way that it shares these collections between entities so we are not creating and adding primitives unnecessarily

**Comment by EdenEdk** [comment]
Ummm so if i inderstood correctly, 
Even tho these collections (labels, billboard etc) hold on to previous data of entities who were removed, cesium will take care to delete them on the other render cycle?
I mean, i the second picture i uploaded we can see point which has fields but are undefined, cesium will delete those points after a short time if i wont add entities?

**Comment by EdenEdk** [comment]
Btw i took a look in #3018
Its not my case, because i iterate on certain entities when i remove them (not in the code i shared, in my app)
And i use removeById

**Comment by hpinkos** [comment]
> Ummm so if i inderstood correctly,
Even tho these collections (labels, billboard etc) hold on to previous data of entities who were removed, cesium will take care to delete them on the other render cycle?
I mean, i the second picture i uploaded we can see point which has fields but are undefined, cesium will delete those points after a short time if i wont add entities?

Yes, that should be the case
