### ISSUE TITLE
Cesium completely broken in Edge

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6535]
```
RuntimeError: Program failed to link.  Link log: Varying variable with name "v_logZ" is used in fragment shader, but doesn't exist in vertex shader
```

@lilleyse is investigating, but @bagnell if you're out there we need you.

**Comment by likangning93** [comment]
Adding a `czm_vertexLogDepth();` at the end of `EllipsoidVS.glsl` seems to fix the problem, but the mystery then is why this works in Chrome...

**Comment by bagnell** [comment]
Fragment shaders that include that GLSL file don't use that varying when computing the depth in the fragment shader. The shader compilers in other browsers were removing it but Edge wasn't.

**Comment by oterral** [comment]
Hi @bagnell @lilleyse, We have still this bug in 1.46 and 1.45 . When we try to display `.vctr` 3d tiles.

 Here is an example : 
https://codepen.io/anon/pen/RJrxYM?editors=0010

Our tilset contains only points.

**Comment by hpinkos** [comment]
Hi @oterral, I opened #6654 so we can track the problem there instead of on this closed issue.  Thanks!
