### ISSUE TITLE
Parent terrains broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6537]
Me and @tfili ran into an issue where if a child terrain only has a single root tile `0/0/0` (i.e. half the earth), `TileAvailability` assumes it also has `0/1/0` (which is actually located in the parent terrain).

This is a showstopper for this release since we depend on this feature in ion.  @tfili will follow up with a fix ASAP.

**Comment by hpinkos** [comment]
Fixed in #6538
