### ISSUE TITLE
Firefox has ~48 camera-related test failures

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6539]
Cesium itself still works, so this seems to be a test-only problem with how we are doing epsilons.  @bagnell  says something like has happened before when Firefox released a new version.  Our 1.44 tests fails now as well.

No need to hold up the release, but definitely look at for 1.46

**Comment by bagnell** [comment]
I'm seeing those failures as far back as 1.39 (didn't test further).

**Comment by bagnell** [comment]
Having `FeatureDetection.supportsPointerEvents` return `false` fixes most of the tests. It seems like the `pointerdown` event isn't fired.

**Comment by mramato** [comment]
It's possible that the regression confirmed in this bug is the cause: https://bugzilla.mozilla.org/show_bug.cgi?id=1463354 

Basically the broke some part of pointerevents in FF 60.  One solution is to not use PointerEvents on Firefox until it's fixed (basically change the `FeatureDetection.supportsPointerEvents` check to return false for Firefox.

Or we can just wait it out.

**Comment by hpinkos** [comment]
Closing this issue.  We disabled pointerevents in #6999 and that fixed the tests.  Once we revert that change (#7003)  we can double check to make sure tests are passing as expected.
