### ISSUE TITLE
Log a warning message for eye dome lighting in IE/Edge

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6543]
Eye dome lighting for point clouds doesn't work in IE/Edge due to lack of EXT_frag_depth, OES_texture_float, and WEBGL_draw_buffers extensions in WebGL 1.0.

Currently it just silently bypasses that code, but it should log an error.

**Comment by mramato** [comment]
We need to add a `isDomeLightingSupported` flag and use it in the Sandcastle example so users understand they need to check for it and what the best practices are.  Simply logging to the console will go unnoticed for most users.

**Comment by bagnell** [comment]
Edge has all of those extensions (also EXT_color_buffer_float which is required). If you open the eye dome lighting example in Edge it logs framebuffer incomplete errors.

I've run into this before with OIT where all of the extensions are supported but the framebuffer is incomplete. In the `isSupported` function, make sure all of the extensions are supported and create the framebuffer. Then return true if the `framebuffer.status === WebGLConstants.FRAMEBUFFER_COMPLETE`.
