### ISSUE TITLE
currentTime not correct when accessed through onTick

### ISSUE THREAD

**Issue by adday** [AnalyticalGraphicsInc/cesium#6550]
I have embedded Cesium into a GUI and am attempting to override the timeline controls in my GUI. I need to get the currentTime reported back to my GUI from Cesium and I am using the onTick() to trigger the sending of the current time. Inside of the onTick EventListener, I am accessing clock.currentTime and returning this as the currentTime being displayed in the viewer.

The issue is that this time is not logical. It only advances fractions of a second for a visualization that is lasting many seconds. For example, my streaming data that is correctly displayed has a time delta of 25 seconds, and all of the data is properly displayed. However the time delta on the clock.currentTime that is returned to my application is only ~6 seconds. 

I am not sure if I am doing something wrong by accessing the clock.currentTime inside of onTick in hopes of getting the current Timeline time, or if there is something I am misunderstanding in the way that the clock is reporting the time.

Thanks for any help!

**Comment by hpinkos** [comment]
Hi @adday, it's hard for me to say what is going on without looking at your code.

You might need to get the current time from `viewer.clockViewModel.currentTime` instead
It might be helpful if you look at the code for our [Timeline Demo](https://cesiumjs.org/Cesium/Apps/TimelineDemo/): https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/TimelineDemo/TimelineDemo.js

If these don't solve your problem, please ask on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features
