### ISSUE TITLE
clampToGround  KmlDataSource

### ISSUE THREAD

**Issue by pengbao4386** [AnalyticalGraphicsInc/cesium#6551]
When the KML data is loaded, the clampToGround is set to true. But the line data can't be clamped to the ground。the clampToGround is not work?
var kmlDataSource = new Cesium.KmlDataSource();
     var promise = kmlDataSource.load('../Apps/SampleData/kml/road.kmz',
     {
         camera: viewer.scene.camera,
         canvas: viewer.scene.canvas,
         clampToGround:true
     });
    viewer.dataSources.add(promise);

**Comment by ggetz** [comment]
Hi @pengbao4386 

Cesium currently doesn't support polylines clamped to terrain, but we are in the process of working on them, see https://github.com/AnalyticalGraphicsInc/cesium/issues/2172.

Generally, please ask questions like this over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
