### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6553]
When loading arbitrary data in Cesium, it often ends up being night-time at the data location so nothing is lit and the entire scene is washed out.  In these cases I don't care about the time and having to turn on and fiddle with the timeline is a pain.  I just want to be able to see the details of stuff on the screen.

I've seen other apps offer a "Flashlight" button that puts a light source at the camera location pointing in the camera direction (or in all directions).  One hack I thought of was putting the Sun at the camera location, but that proved tricky because the implementation is not very monkey-patchable.

While I know arbitrary light sources are on the long term roadmap, what's the simplest thing (even if it's a temporary workaround done at the app level) that we can do in the meantime?

CC @lilleyse @bagnell

**Comment by mramato** [comment]
Also CCing @emackey because this sounds like the type of problem I might be able to [nerd snipe](https://xkcd.com/356/) him on

**Comment by mramato** [comment]
Awesome @emackey!  That seems like a great workaround.

**Comment by OmarShehata** [comment]
Requested [on the forum](https://groups.google.com/d/msg/cesium-dev/BgRKJ8N6aDI/-avmESUeCgAJ).

**Comment by lilleyse** [comment]
This type of effect is now possible in https://github.com/AnalyticalGraphicsInc/cesium/pull/8493.

```js
viewer.scene.light = new Cesium.DirectionalLight({
    direction : new Cesium.Cartesian3(1, 0, 0)
});

viewer.scene.preRender.addEventListener(function(scene, time) {
    viewer.scene.light.direction = Cesium.Cartesian3.clone(scene.camera.directionWC, viewer.scene.light.direction);
});
```

[Sandcastle](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/light-direction/Apps/Sandcastle/index.html#c=fVPbjtowEP0VixeClDrh0t12y6K2sKoqIbUq0vYlL8YeYFTHRrYToNX+eye3AotUyw+ZmTPj43PiUjhWIhzAsUdm4MDm4LHI+XOdi/qyDufWBIEGXD9mfzLDaKHZ2M/2yB7YRmgPcZP1oEEGtOarUShFsO41YCeUPXjKBleck7bQ6pPBXARoS5l5GXzITGZKYggmYDgRw4Yqr2MEz4VSUUtobz1WJ1N/e4e5cIG+hBnzjbP5ArYOwEdvhqMxT+8nk7vh+5hNJjx9m47v07uYpTwdtJRyq0DTqHZ4tQqHlOhzntBeiXyvYSGCSGqoT744Wxj1DDuUGq4jvtXrfnyelCNdtci/4xH0Cn9XVx6O3l0CxLECrKTQVXGU0mqqL60urRDBCfkL1FOnTyNUo1uD8BIMcI3bXbh2eIGusUroZVXtdFRd/uESfdYyGpJQtAdnhy5P2jv4AUZRTN48lURoiT5QxUWbwtSDoxoZs4A5DDqFb+nyf0yI+K2lUlsDzSguRQ5OnBt+zuP/Dqx41+R7cW/qw0nDrGHxEfO9dYG81hG5HIBcpn/SJ+uCdA5cel+1TZOuaaqwZKges96rl5L1mNTCe6psCl3bnPVm04TwV23aCoVm+60Ep8WpguyGs2WT5JxPEwpvu4K1ei3cxcS/)

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/BgRKJ8N6aDI/-avmESUeCgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/6553 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
