### ISSUE TITLE
Classification type ignored when depthTestAgainstTerrain is true

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6568]
The classification type is `CESIUM_3D_TILE`. When `globe.depthTestAgainstTerrain` is true the polygon classifies both the tileset and terrain, as in the second image.

<img width="458" alt="no-depth-test" src="https://user-images.githubusercontent.com/915398/39706743-5991a544-51e0-11e8-8eed-11f492ae8980.PNG">
<img width="493" alt="depth-test" src="https://user-images.githubusercontent.com/915398/39706744-5a63e176-51e0-11e8-99c6-09e1d8989617.PNG">

[Sandcastle demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=bVRtb9owEP4rFl9INGryCklLq1FAKlK7VZBNmsZUmcQQa46NbIeOVf3vu5BAoZ2/OOd7nufOd+dsiUJbRp+pQtdI0Gc0opqVBf6+P7Pa6d4cSWEIE1S17auFWIgtsAzjVFNzTqs3f5zUTusFlYpfHrxTKWZUy1KlFK+ULIYaMNPM8iO/Z6PXSrvOBeuUCoo3ihXMsC3VmGSZ1USsU2gMrCjJdo8gxjTFJqfCWpUiNUwKy35ZCASrynYpS5ExsZ5vcqooJH3gnzuuGkadRUoKqgiurNszmHXO6pyW4A4SAs8jM2k+I2JNLQc7HXTh4LDzLg2sAFpq9AmFDoBs+7/huZS/hyZRROiVVIXVxHkgRrE/AZ6OJ1+SafKjIr++tYdChcwOLtqI7W3WVLIpzEby3VoKdImag2rlDIKqNN/B8cm1Hmvs3cF7SGNElIEvIvx9S2dwI0h0qBTZWT8vXOy7ceD3Yq/f993A8bwOcnAvjiKn54W+EzvVDtXZA/04DOPI8ZzAc/tHYOyG/ajfd70weAP6ruc5cRj7vQOwD2F8L4idqHcUDPww8rzACcLAiY64vhv3wjDsxXH0y7Y7b1cviKGKEY6OEzuSXCo8m4zxMzP5kG9yAu0MT0kpJ1qzFUtJNXTJbkNP6B98eDSZT789PPnjp2R6P6llXo+dmxORpUQbTqs+JXK95vS2NAamuT2mG5MjKLZBZA2vEXZIV8FXu4NWhGuYw+PspzlNf9PMPnT27F2tuVxSnFV6CcgNa7WkFoORacj1QLU6rYE2O05vaqXPrNhIZaqHbWHcNbTYcKib7i5LIBmcal3dZdA9kAYZ2yKWXS9a734mi1ZdPPCsSs7n7C9dtG4GXcCf0bjcv6ivW6o42VWQ3L25rw8xxoMumB9ZRkq+JOpE8R8)

@bagnell could you check this out?

**Comment by bagnell** [comment]
This has always been a problem. The stencil shadow volumes use whatever is in the depth buffer so if terrain and 3D Tiles have been drawn with depth rites enabled, then the classification is applied to them. One solution would be to drawn terrain after 3D Tiles, but we would have the opposite problem.

**Comment by lilleyse** [comment]
Ah, alright. Thanks @mramato
