### ISSUE TITLE
Option to disable group display in BaseLayerPicker

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#6571]
In Cesium 1.45 the layout of BaseLayerPicker was changed. Now the enduser see always a group "Cesium Ion" and "Other" - but the user has no idea where the difference is. For me this groups are just interesting as dev. So it would be nice to have an option to disable this and get layout like before Cesium 1.45.

**Comment by mramato** [comment]
@SunBlack I wrote up #6572 to address this (sorry I originally thought this was a forum post and ended up writing up a duplicate issue).

As a reminder, the initial list in the base layer picker is provided for demo/development purposes.  You should always be providing a custom list of layers for your own apps, and you can simply leave off the category option on those layers.

**Comment by mramato** [comment]
@SunBlack this was fixed in #6574 and will be in 1.46 release on June 1st.
