### ISSUE TITLE
Clipping Planes sandcastle examples show errors in IE

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6575]
... but the demos don't actually crash? This seems to be limited to demos that involve `Model.js`, so instanced and b3dm tilesets as well as 3D models.

https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=3D%20Tiles%20Clipping%20Planes.html

**Comment by likangning93** [comment]
In Sandcastle:
```
[Cesium WebGL] Shader program link log: Internal linking error

RuntimeError: Program failed to link.  Link log: Internal linking error

Error
   at RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:42:13)
   at createAndLinkProgram (http://localhost:8080/Source/Renderer/ShaderProgram.js:257:13)
   at initialize (http://localhost:8080/Source/Renderer/ShaderProgram.js:451:9)
   at ShaderProgram.prototype._bind (http://localhost:8080/Source/Renderer/ShaderProgram.js:468:9)
   at beginDraw (http://localhost:8080/Source/Renderer/Context.js:939:9)
   at Context.prototype.draw (http://localhost:8080/Source/Renderer/Context.js:1002:9)
   at DrawCommand.prototype.execute (http://localhost:8080/Source/Renderer/DrawCommand.js:502:9)
   at executeCommand (http://localhost:8080/Source/Scene/Scene.js:2075:13)
   at executeCommands (http://localhost:8080/Source/Scene/Scene.js:2403:17)
   at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2762:9) (on line 257 of http://localhost:8080/Source/Renderer/ShaderProgram.js)
```
Funny thing, running this in a separate tab once triggered Windows to ask if I'd like to use the Visual Studio debugger... that "internal linking error" thing also suggests to me that something deeeeep in the browser is dying...

**Comment by likangning93** [comment]
> limited to demos that involve Model.js

Another observation, removing the `discard` [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/getClippingFunction.js#L95) gets rid of the problem, but... I mean... that defeats the purpose.

I panicked for a second and thought maybe `discard` just doesn't work in IE anymore but terrain and pnts don't have a problem, so it's probably something in the model shader.

**Comment by likangning93** [comment]
Tried to git bisect, it looks like this emerged in 1635c92da2fec454e440baf45973c749e2b22ffe when `master` with texture clipping planes (and IE clipping planes for the first time) got merged into log depth.

**Comment by flyingsnowers** [comment]
> I think I have a fix, but a few more observations:
> 
> * removing the `gl_FragColor` write for the clipping plane edge style prevents the error for regular 3D models but not for all 3D Tilesets
> * removing modifications for log depth on picking shaders seems to fix everything. Again, this is IE so log depth isn't supported anyway.
> 
> I wonder if we're actually looking at multiple quirks in IE's webgl implementation... I know that we've run into weird `discard` problems before on DirectX-based webgl, like calling `discard` from inside a loop. In this case maybe it's just the sheer amount of indirection, even though a lot of that indirection in this case isn't actually doing anything.



> I think I have a fix, but a few more observations:
> 
> * removing the `gl_FragColor` write for the clipping plane edge style prevents the error for regular 3D models but not for all 3D Tilesets
> * removing modifications for log depth on picking shaders seems to fix everything. Again, this is IE so log depth isn't supported anyway.
> 
> I wonder if we're actually looking at multiple quirks in IE's webgl implementation... I know that we've run into weird `discard` problems before on DirectX-based webgl, like calling `discard` from inside a loop. In this case maybe it's just the sheer amount of indirection, even though a lot of that indirection in this case isn't actually doing anything.

may i ask  how to fix this problem？

**Comment by OmarShehata** [comment]
@flyingsnowers this should be fixed now. Are you running into any errors? I was able to run the [clipping planes code example](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=3D%20Tiles%20Clipping%20Planes.html) in IE 11 with no WebGL errors.
