### ISSUE TITLE
Camera below the terrain surface

### ISSUE THREAD

**Issue by fgamezc** [AnalyticalGraphicsInc/cesium#6581]
When rotating with the middle button, the camera can be moved below the terrain surface. It seems that the position of the camera is only adjusted after it finishes loading the terrain.

Cesium 1.45
Web browser: Chrome 66.0.3359.139

![bug_cesium](https://user-images.githubusercontent.com/39163913/39877501-628cd04a-5476-11e8-8c0f-507f6b19c019.jpg)

**Comment by hpinkos** [comment]
Thanks @fgamezc, this is a known issue.  I've added a comment to #5837 so we can notify you when the issue is fixed.  Thanks!
