### ISSUE TITLE
Scene/ShadowMap point light shadows test failure

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6582]
Does anyone else see this test fail when running the tests locally?  I get this in Chrome on Windows 10:

Expected [ 255, 255, 255, 255 ] not to equal [ 255, 255, 255, 255 ].
    at http://localhost:8080/Specs/Scene/ShadowMapSpec.js:733:34

cc @lilleyse

**Comment by mramato** [comment]
Pretty sure I have
