### ISSUE TITLE
Scene/Scene debugShowGlobeDepth test failure

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6583]
Does anyone else see this test fail when running the tests locally? I get this in Chrome on Windows 10:

Expected to render [0,0,0,255], but actually rendered [255,255,255,255].
  at http://localhost:8080/Specs/Scene/SceneSpec.js:350:23

cc @lilleyse

**Comment by likangning93** [comment]
I have this too. Chrome on Windows 10 on Nvidia.

**Comment by likangning93** [comment]
Also Chrome on Windows 10 on Intel

**Comment by hpinkos** [comment]
This seems to be fixed
