### ISSUE TITLE
Cesium treats +X as glTF forward vector, 2.0 spec says it's +Z.

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#6591]
Not sure how I didn't notice this before, but `VelocityOrientationProperty` apparently places the `+X` vector as the forward vector, while glTF 2.0 settled some time ago on the `+Z` vector being forward.

This means that all glTF 2.0 models used with `VelocityOrientationProperty` will fly or drive sideways.

**Comment by emackey** [comment]
Also this repo contains an out-dated `GroundVehiclePBR`, that I am in the process of updating, that was using the old +X convention.

**Comment by emackey** [comment]
New vehicle added in #6592.  Note that if you use the corrected model with `VelocityOrientationProperty`, you will now see truck driving sideways.

**Comment by emackey** [comment]
Expanding the scope:  It's not just `VelocityOrientationProperty`, it's everything that deals with orientation.  For example, headings are all 90 degrees off for glTF 2.0 files.

One option here could be to add a `frontAxis` setting similar to [the existing `upAxis` setting](https://github.com/AnalyticalGraphicsInc/cesium/blob/dbc671006507a78ceade01e9f3943a550e217862/Source/Scene/Model.js#L4435-L4439).  The default would have to auto-detect glTF 1.0 (`+X` front) vs glTF 2.0 (`+Z` front) and assign itself accordingly.

**Comment by mramato** [comment]
As you already noted, the scope here goes far beyond models.  I think this is a massive breaking change for Cesium if we were to make it.  I'm not sure changing all of Cesium because of glTF 2.0 is the way to go.  It might be better for the Model primitive to have special logic for handling gltf models so that glTF "just works" with Cesium's existing convention.

**Comment by emackey** [comment]
>  It might be better for the Model primitive to have special logic

Yes, and I suspect the existing `upAxis` setting is an example of such logic.  Perhaps all that's needed is a new `forwardAxis` setting in Model.js.  Would need to be careful that this didn't mess up 3D tiles somehow.

**Comment by hpinkos** [comment]
Is that all related to this? #3256

The East/North/Up transform we default to everywhere makes `heading: 0` east instead of north.

**Comment by emackey** [comment]
@hpinkos I was noticing that in my testing of headings just now.  `heading: 0` appears to place glTF's +X axis to the East, and +Z to the South.  glTF 2.0 models drive South with heading `0`.

**Comment by hpinkos** [comment]
@emackey yeah, I've been trying to argue for years that `heading: 0` should be north because that seems to be a more common standard.  But I lost that argument and we decided just to document it and add the fixed frame generator to `Transforms`.

**Comment by emackey** [comment]
@hpinkos OK.  I think that's an unrelated issue.  The proposed fix here would just make glTF 1.0 and 2.0 agree on East.

**Comment by hpinkos** [comment]
Gotcha 👍

**Comment by lilleyse** [comment]
Fixed in #6632
