### ISSUE TITLE
splitchunks in webpack 4

### ISSUE THREAD

**Issue by fnoop** [AnalyticalGraphicsInc/cesium#6610]
In the cesium and webpack tutorial (https://cesiumjs.org/tutorials/cesium-and-webpack/), there is a section about code splitting which uses webpack.optimize.CommonsChunkPlugin.
However, in the new webpack 4 this has been deprecated, so you get this error:
``` ERROR  Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.```

I can't seem to work out the correct syntax for using splitChunks with cesium, it would be very helpful to add this to the tutorial.

**Comment by ggetz** [comment]
Thanks @fnoop! I'm closing this in favor of https://github.com/AnalyticalGraphicsInc/cesium-webpack-example/issues/7,
