### ISSUE TITLE
Missing tiles in VR mode (regression w.r.t. Cesium 1.44)

### ISSUE THREAD

**Issue by glathoud** [AnalyticalGraphicsInc/cesium#6612]
Hello, sometimes in VR mode some tiles are not displayed. From what I could see, the issue happens with Cesium 1.45 but not with Cesium 1.44.

To reproduce the issue:
 * open the Sandcastle example "Ground Clamping"
 * add the line `vrButton: true` to the Viewer config
 * re-run the example, click on the VR button and move the camera around (see the screenshots below).

I also tried `scene.logarithmicDepthBuffer = false` but that did not change the behaviour.

Below, you can see the code, and screenshots taken with Cesium v1.44 and v1.45 at similar positions.
If I can do anything to further help, please let me know.

### Screenshots

Code with `vrButton: true`:
![code_cesium145](https://user-images.githubusercontent.com/2437470/40373398-19b6101e-5de7-11e8-8a9b-967b72d5e85c.png)

----

Position 1, Cesium 1.44:
![position1_cesium144](https://user-images.githubusercontent.com/2437470/40373399-19d23a0a-5de7-11e8-8439-03ea86b46e35.png)
...vs Cesium 1.45:
![position1_cesium145](https://user-images.githubusercontent.com/2437470/40373400-19ea41c2-5de7-11e8-8a1b-7d312dfda6e7.png)

----

Position 2, Cesium 1.44:
![position2_cesium144](https://user-images.githubusercontent.com/2437470/40373401-1a06623a-5de7-11e8-83d6-233d7b116cd0.png)
...vs Cesium 1.45:
![position2_cesium145](https://user-images.githubusercontent.com/2437470/40373402-1a1f9656-5de7-11e8-91bd-a1459211d126.png)

**Comment by glathoud** [comment]
Here is an [example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=7Vnrb9u2Fv9XePvFMubSkixZUvrAdRK3C+Y84HgtiqYIaIu2eSeLBknl0SH/+w5FyZFlOV2xpXcfZiSwJZ0XD8/jd6gbItANo7dUoDcopbfoiEqWrfCH/J7VmuWXRzxVhKVUtDro96sUwUdRIeDWheA3LKbioGScCUoU/chFEk8MidU2HB10Iw4zpXh6gJTI6FX60H51lRrtWM5oSvEi4VOKY7pWywmVarAAfqkKQWCh5gOeq7TbRYKuBY+zGUVMyowiniKCHDe07xzb9ZAES2iKYnrDZjRnWCq1lgfd7oKpZTbFM77qDlKS3Cs2I8l7QdZLNpMn6axrFt3Nxcpuv++4YCY4akZWVBAwo7DZXD+uoVwf1tenPKaJVrIiaYzJHBw2vKOzTFFM4nh4Q1M1YlLBqoUFtl+XzEg7ZZ6lM8XgovLAape+Z3Nk7VfJ5Iex/tUGyoJBfyRVE7aiPFMWWvEbes1UBzm2becKNcVDQWy+NiYUxI/q9ccsHa+5ZDnRVvAcEaHgF0l71ksHB0EQeaHtB24QRpEddF66NvYcJ4hc2wHful7UiQIcBqEXeo4X9G077JU2VXTFTNDZk8psbDu5tiCKen7oR67TsbFr58qcKIhCOww8MMDGUWD02VE/DKOwX/HBg46vS9i0GZEqyXfrmM5JlqgJ58mUiFOaZtbnwhndbvmNJhzNErJaozVnqZKICzRlSTLlRMRS+x+pJUVLyhZLNaZzKmgKwas4OhoNTi+uJ+fX78fnv54da8bxcDSYnHwYPt7dVqfonUIHqHUsyC260PrQLYQ1GpEpTVodQ8RTSRPwGRCWu7m9izqo6WM8Q0jCblKpl2xVyPRns9MHu47Hc8FXx3QBCSdhx10XO5EfdpDXhx+O3+7URWlzD1BNQ77VPIHFP6rQl/jyl0+Ho1+HnV3yNbujySX7SoHFsRsIINoTqFtHTWI/DUej84/7mT6yGBx6gHoNJPVN3Ij+efsBrm3ttqSHmuREb16zY8r9PtIBRmMdNQvBszRuNVg357l/W463VkiSVL6UVLB5629cSJMoLthX3SiSc8EWrBIpP9ee4NHw3aRBwg0VeS2u83/Yuo8PB5fD0clZU0DMId8aN/twNDj6pYFBLvntIZn9ZpyJTGdqoJtuaErx1RKkb1kOlNP8z8ZB+0kRF5BfLF3UhJTp5Fo6dZokxEySaUKPy/Z4DP2DmF07y1ZTyOCL88uTvGycnL07OTuZfNJ1KYYaIfPaYwIMXAsJCyHC52Ubr8Xl42XeoisFwxQKJWAtNB7qenEP9YNWqmcFIVRK1GFZCP/htWlTsJvTkK3IQru7hXE3/y27czJjCbgBL/7eDHuOLak0qyMuBIu5kB1wX3K/gP1A0POQ7rEkXSRUQkNJEjSlpqlBzSGZ4iuSZ2Jyr0EIhNQ9IoLmaQcEeQciUMRTHZeqqOYgdaN1SSRKeeET3ecgRkQWA6+5hTeUZ+eT4QG6pErpTCkYoOrZxqwiFYxtQIGfaI/lUp8j9GaF7OZwKQNTfisyB5CF99bnXQn6U0RtGbNe5wkyQDyaDL6eIuoVRLs0X5rqzm3RCV1Ai7ipzUJUQIMhSb3qvh8Ph2dYh8UgWS8JADS//Z1x/ZXz1YRbtP3NEnNhwvh5CkwuunmTlwzQqZgt75sf1+Pg8x6g7AJidXohDr2g59luCBv5shd4nh242PMj33PgCvYNqBw/xH7geE7g9wK/vWertz77lQZuz8Fe5IIou2/3jFbfsXs4CMN+33ad0M/V2oHtAm72g6Dv9nt/Va0fOSDNdl3b93rlWmEUwLYbBQDNfbNWF1yBHSAJQjDpLy/VDkG+Hfk+rKBvlIIpPQyqbS8MndLDUd/BYb/nggPcqP1lV+vDd2SBBq8/KgkmcJEJqKffmw16pvxPYbZpIlhm6zUXSp4W65JzLoZFlpyn5XRfnd/b7XoG3LI05reYJADhrFY5yBddqnSYzJtIygGsGpVgP2SbWjKJ1glRoHfVqk6E+iMoLDSt3HzYcty/yf1vcj9TclfAnzHlesQX/Nok+//WiyYUCDhFSjYH7KRDZXK/rgDBo51neDIcjwcnZ00DixpzRbbRLiToEis+JjF4Q1reM9aXcQkPn6PNbrDnvsMBLmBugo2o4KmNQbtA36Acu2NAj51fNUbZvsI9Hh7/qLqdH939w2ejlbaxeWsywYrEgL9LgOQwpRJFujlLmSanJC0TBn7iRTJ95hOJFUvZKltdVE+J3LAxAO404SVMNuYoyX7Ogdj4B+kzpkrz0MOXntTNFJUfgQOHVOWo832Tc0LTBQh4k5/wvqp3RhjPhBrlJ6nNJSTs4wh6RrR1DptHXRp/gy+M+l4UtHd0Qh/fy+YGOApD129gKw4ojM8uNt56gz5/qZgGCAFZmpzBE/sVfL0uXPAK/fQT24EluUE76wCQsrbMCjsbH3VAWBdZhUNfIqddRyJa2P6DcL4wbxasRMsCL9TZm1eI15lcWqXY9j6cUyi6XdLUKn7LXFABtU65VMdUEQYBVEK12qubzh4L2p3H+DIyZaMf+Xyuz7Z1qGG7tramfSlk4af2J+90hu4z+4KL8f+nN4WyVzvpWTPr23WxRH55Fv4pbFeC4yRha8lZjD++vww9PKvscT7GT/imwpqxvnTeHnwz50nCby8zMSd5uZsDIKZ7aMtJ3N/zvNLJKmF4Uazz3Bxsl3geAmANsPze+n0/8Go8kD8fD87eD5+Aa7UTdPfbpPsPbZtZH/Z5My+c7yDeT3+IKwAi/J/90ABfa9mxXVQ3hZWIRZ62zZC6Z9tBAJDHDmGGCKNeCODZ7/c8jeydntOLAEnD6AB4PnR8FwOY9n2YLJx+vbxtykOzHhDpweDh2VHYD0K/7wJcg76De17xwg5gO0wQMDxE0JJsmFrsoN9z+u5OFa6+k8UJ578NlGUW2SmM+DMsEwENSQ+c1mNnEOzOwyfHw7PJyeTTVimuArsvHdTSgM+8kJUt4/bKi0RBjSM2b1Yf23a9YAmq37oOksTSUh7g/0XnxWup7hP61nD8l630pAzIK7EAcym60pMyjCTTDJCIwjMpNevrbsn0OmY3iMVvrl7U3ulfvTDTCTyZZ0kOlK5evH3dBfottoQT/dbi/IaKhNxrkqXzdmRuYoxfd+Fyl0uZd6ZAbuyuPCk6FE2zir5tmoo/99JA9QX4P9IdAizZS2aq8K6w8vsP) for a 1280x1024 screen device. Just click on the VR button and shortly after the camera will be moved to a problematic (position,direction) pair. Problem reproduced with a chromium browser under Lubuntu.

**Comment by glathoud** [comment]
Using that example the issue seems to appear in the `master` branch at the log depth merge 50b1d5d890dafb9fbe962fff227c1e4345ccbffe, and not on the previous commit 603640c627706735d391486bd7c3b24877d77cf2

However in my tests, setting `viewer.scene.logarithmicDepthBuffer = false;` did not change the result.

**Comment by glathoud** [comment]
Here is a possible [fix](https://github.com/glathoud/cesium/commit/e85a779ff083f481aae74740295fb89a645b3b0f) that makes the `aspectRatio` in `configureCameraFrustum` depend on `useWebVR`. In my tests it worked.

**Comment by glathoud** [comment]
Hello, it would be cool if someone could have a short look on the two small commits below and say whether they are worth submitting a PR.

 * https://github.com/glathoud/cesium/commit/e85a779ff083f481aae74740295fb89a645b3b0f
 * https://github.com/glathoud/cesium/commit/e47a7d5d57c78012f0607d12a95671ac5efa9ffb

**Comment by hpinkos** [comment]
Hi @glathoud!  I'm not super familiar with this area of the code, but your fix make sense to me.  It would be great if you can open a PR with that fix!  Thanks!

**Comment by glathoud** [comment]
@hpinkos thanks for looking at the code. I just created the PR.
