### ISSUE TITLE
New in 1.XX Sandcastle button has duplicate examples

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6613]
I think since I made two commits on the `Z-Indexing Geometry` Sandcastle demo it's showing up under the `New in 1.45` tab twice.

Also, some of the development sandcastle examples are showing up under that tab.  We probably don't want that.

Labeling this 'next release' because we won't want this deployed to the website

**Comment by mramato** [comment]
At first glance, this looks like a Sandcastle client issue, since the file is only showing up once in `gallery-index`.
