### ISSUE TITLE
Whether Cesium3DTileStyle supports image attribute to 3dtiles

### ISSUE THREAD

**Issue by leation** [AnalyticalGraphicsInc/cesium#6618]
Whether Cesium3DTileStyle supports image attribute to 3dtiles?When I try these code below,it seems not work,and the breakpoint can not Jump into the "evaluate" function,is there somebody tell me?
style.image = {
    evaluate : function(frameState, feature) {
        return '/url/to/image';
    }
};

**Comment by lilleyse** [comment]
Just to be sure, does your tileset contain [vector data](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/3d-tiles-next/TileFormats/VectorData)? The image attribute is only supported for vector data.

**Comment by leation** [comment]
thank you very mush！
