### ISSUE TITLE
glTF 2.0 models dark on Samsung S8

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6622]
glTF 2.0 models are rendered dark on the Samsung S8. My first guess is this is a shader precision issue that causes the PBR shader to break. Does anyone have this phone or a similar Android phone? Try this link:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/gallery/Physically-Based%20Materials.html

Screenshots are from a PC (correct) and a Samsung S8. Both are at the same time.

![pc](https://user-images.githubusercontent.com/915398/40460866-cf27ec66-5ed6-11e8-91b1-3d922fe8a4f3.jpg)
![s8](https://user-images.githubusercontent.com/915398/40460942-0f6f4bf2-5ed7-11e8-9318-fc25f5a48383.jpg)

Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/qYjFtc3Ktg8

PS: reminder to also look at https://github.com/AnalyticalGraphicsInc/cesium/issues/6334

**Comment by shehzan10** [comment]
Here are the screen shots from an S9. Tried to. Match the time on the darker one. 
![screenshot_20180523-230407_chrome](https://user-images.githubusercontent.com/2288659/40462404-d8f45304-5edd-11e8-97a9-877bb92188a6.jpg)

![screenshot_20180523-230428_chrome](https://user-images.githubusercontent.com/2288659/40462411-df47646c-5edd-11e8-920c-75d43b8ff468.jpg)

**Comment by alx696** [comment]
@lilleyse Same b3dm model:

Ubuntu Chrome 71:
![PC](https://github.com/alx696/share/raw/master/image/3DTiles%E5%9C%A8%E7%94%B5%E8%84%91%E4%B8%8A%E6%95%88%E6%9E%9C.png)

Samsung S8 Chrome 70:
![Android](https://github.com/alx696/share/raw/master/image/3DTiles%E5%9C%A8Android%E4%B8%8A%E6%95%88%E6%9E%9C.jpg)

I have disable shadows: `new Cesium.Cesium3DTileset({ shadows: Cesium.ShadowMode.DISABLED })`. Looks very dark ! `shadows` option not work.

**Comment by likangning93** [comment]
Hi @alx696, I realized that the Galaxy S8 can have one of two different chipsets with different GPUs, do you know if your unit is Qualcomm or Exynos?

We might also be able to figure this out if you post the output from visiting http://webglreport.com/ on your device.

**Comment by alx696** [comment]
@likangning93 Mode: `SM-9500`

* CPU: Qualcomm Snapdragon 835 MSM8998 (10nm)
* GPU: Qualcomm Adreno 540
> https://www.phonemore.com/samsung-galaxy-s8-sm-g9500/specs/3233

I have made a simple model, But same problem. See #7403

**Comment by alx696** [comment]
@likangning93 WebGL Report:

![a](https://github.com/alx696/share/raw/master/image/%E4%B8%89%E6%98%9FSM-9500%E7%9A%84WebGL%E6%8A%A5%E5%91%8A1.jpg)
![b](https://github.com/alx696/share/raw/master/image/%E4%B8%89%E6%98%9FSM-9500%E7%9A%84WebGL%E6%8A%A5%E5%91%8A2.jpg)
![c](https://github.com/alx696/share/raw/master/image/%E4%B8%89%E6%98%9FSM-9500%E7%9A%84WebGL%E6%8A%A5%E5%91%8A3.jpg)
![d](https://github.com/alx696/share/raw/master/image/%E4%B8%89%E6%98%9FSM-9500%E7%9A%84WebGL%E6%8A%A5%E5%91%8A4.jpg)
![e](https://github.com/alx696/share/raw/master/image/%E4%B8%89%E6%98%9FSM-9500%E7%9A%84WebGL%E6%8A%A5%E5%91%8A5.jpg)

**Comment by OmarShehata** [comment]
This should be fixed with https://github.com/AnalyticalGraphicsInc/cesium/pull/7944, and will be out with CesiumJS 1.59 coming out next week.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/qYjFtc3Ktg8

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/6622 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
