### ISSUE TITLE
How to avoid passing underneath globe

### ISSUE THREAD

**Issue by safa833** [AnalyticalGraphicsInc/cesium#6623]
![1](https://user-images.githubusercontent.com/10292075/40472688-d95503ce-5f42-11e8-938a-eb011693f694.png)

Anybody know solution ?

**Comment by gberaudo** [comment]
Yes, see https://github.com/AnalyticalGraphicsInc/cesium/pull/6012.

**Comment by safa833** [comment]
@gberaudo , This is a good solution but The problem is continuing

**Comment by gberaudo** [comment]
@safa833, have you used `scene.camera.enableTerrainAdjustmentWhenLoading = true`?
You can do it just after creating Cesium.

**Comment by safa833** [comment]
@gberaudo, Yes, I have. but Camera comes up surface after passing underneath it for a while

**Comment by hpinkos** [comment]
Hi @safa833, I'm going to close this issue as a duplicate of #5837.  I'll make a comment in that issue so we can notify you when we have a fix
