### ISSUE TITLE
Use createImageBitmap for image decoding when available

### ISSUE THREAD

**Issue by puckey** [AnalyticalGraphicsInc/cesium#6624]
While profiling in Chrome, I noticed quite a few ms being spent in decoding satellite images on the main thread. Using ImageBitmap this decoding could be offloaded to the background. ImageBitmap is currently supported by Firefox, Chrome & Opera.

https://developers.google.com/web/updates/2016/03/createimagebitmap-in-chrome-50
> "The problem with decoding images is that it can be CPU intensive, and that can sometimes mean jank or checkerboarding. As of Chrome 50 (and in Firefox 42+) you now have another option: createImageBitmap(). It allows you to decode an image in the background, and get access to a new ImageBitmap primitive, which you can draw into a canvas in the same way you would an <img> element, another canvas, or a video."

**Comment by pjcozzi** [comment]
Resources from #5963 

* https://github.com/mrdoob/three.js/pull/12456
* https://twitter.com/donrmccurdy/status/925800420101931008
* https://twitter.com/superhoge/status/1052609244824887296

**Comment by mramato** [comment]
Implemented in #7579
