### ISSUE TITLE
Polygons render colours incorrectly

### ISSUE THREAD

**Issue by AndreasSvendby** [AnalyticalGraphicsInc/cesium#6630]
I've added GeoJSON and set the colours of the different shapes by fetching the entities from the datasource and set the colours. When I set the same colour on a polygon and a polyline, the polygon doesn't get the correct color.

In the following image I've set both entities to have the colour Cesium.Color.PALETURQUOISE

![image](https://user-images.githubusercontent.com/2139271/40536003-10e5d0b6-600b-11e8-8c70-efca33535d09.png)

**Comment by GatorScott** [comment]
I noticed that this happens only in 2D and Columbus modes.  The polygon is not affected by sun in 3D.

`var viewer = new Cesium.Viewer('cesiumContainer', {
    sceneMode: Cesium.SceneMode.SCENE2D,
    enableLighting: true
});

var geoJsonData = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [-95, 35],
                    [-125, 35]
                ]
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [-115.0, 37.0],
                        [-115.0, 32.0],
                        [-107.0, 33.0],
                        [-102.0, 31.0],
                        [-102.0, 35.0]
                    ]
                ]
            }
        }
    ]
};
var promise = viewer.dataSources.add(Cesium.GeoJsonDataSource.load(geoJsonData, {
    stroke: Cesium.Color.PALETURQUOISE,
    fill: Cesium.Color.PALETURQUOISE,
    strokeWidth: 5
}));
promise.then(function(dataSource) {
    viewer.dataSources.add(dataSource);
    
    // Get the array of entities
    var entities = dataSource.entities.values;
    
    for (var i = 0; i < entities.length; i++) {
        var entity = entities[i];
        if (entity.polygon) {
            entity.polygon.outline = false;
        }
    }
});

viewer.zoomTo(viewer.entities);
`

**Comment by hpinkos** [comment]
Hi @AndreasSvendby, this is a known issue: #5730
I'll make a comment in that issue so we can give you an update when we have one.  Thanks!
