### ISSUE TITLE
Content underneath a classification primitive not pickable when allowPicking is false

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6633]
@bagnell do you know if this is expected issue with classification primitives or just a bug?

![picking](https://user-images.githubusercontent.com/915398/40588839-cf16165c-61b1-11e8-8ef2-cf9388d77f18.gif)

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=vVlrc+I2F/4rar5gpkRczD2XKQu0YV4ImQ1tZ6fp7AhbgLrC8tgyhLeT/94jyza2Y7Jk0mlmdhOkc9O5POdIVKtogHy2dTlFNt0KJFbIHKEF49RHK0pk4FHkMusbc9Zoz+QGbcSOeog4NvIpp5ZES7ohOya8J6daRZ8Cxm1FaxNJkCUCT1L/oKTefxmiuUudkdpwhScJ76ONlG6/Wt3v93XsHCy8FruqzySt2oJJWWUOk4xItqN+1bQvl5Fw7JI1fXJ2xEM7Rvdgzg1y6B4Nqc+CLf4tXDNKVvhxKBxJmEO9UgX9/eQg+JHU82DpwRM7ZlOvHzNaHhyY/i48bi80iVF+cl7KV08OaAulYt+iDsVrLpYU29SVmwX15WANtL6MmMAa6QU05AKXPFKJ5IYifRiOLLKlHgktR1IgLsQ3RCSaEWdDpCSOPlhE/SDAHUwomZGRQ6Jcyohj4pUntiO69ij1jctOE9fq3W7drDW6tVqj2a2gZg23e/V60zTNTr3ZbdQrqNMy1XFSGuYeo+ChSEnKjXeUKGc/MGltPgvOM+oaddzodDu9bqfb6Jlds1VBl7BmNs1erdWqdTuNZhvU1XCtU2/3WvUemNbrNuutUHvaldod2KdSxc2IQmSDV5kTWtXP+6KiScTR8H7BYSIq6tgLjzj+SnjbJNAzIj323MST0fh+MVl8SYIM4ZoKYofxUgkbZ5yPpKoIKrXrog9Zf+lf5mihN42/UeDxROVEOJ+pD/Vg0dCRAx9oJrbRbPfMMnp55RbXY1sWZj4mtm1EGhMr7xazKVKVyMkBwdmQvxF7VXdxzTrgVgQh3YrAp4pQW66W5xHbDbKFFWzBYVHmjzlVn4ySzXallEVWXEKYuFDB9nADXjFSohRt6iO2OPH9e2XBDSotifXN9oRbyhH58sChhpjvamNKjnBoMZF7rIISWfqCB/IE5VJIKbaKrlZMwOlKnt7+o+QK5gA+XNIdeMIv/fkdwyA2yutA1HSfT5gE5197IgC/CS680CUc1kpxLCeOSk5dgWQpAg0XVuB5YAI/RDhL7Ti2OpLJ6k0Ma9F2H4EquoJ42cdKWUMx8VB/P5OzaiUEuXON2bD1hsO/V/akN/5dkwYOVLFkEtrI8i/VcfYbZm2gG3EO3YjbUPwrcZbnwkpR1EvxjKLMy3pzrBVlCluvGUnt6TCSROiBci72qtjC3ohTlQxY6Ty6xKJjlU530DW5WofKd9xADizlZmMVOOEfIGGmqnUGUowt/KeKsRy7UsVmldK6Jz5yPQqdN/Czcakob4vQFcmqlsFWyIgOFYXDSPHhSHQ50al+CggAEHQip/cyEb16kx84k3yIKF+Ub6NjPsC4AQdVEUgyTG2pOKlRhNo/J3KymAmbieMwAFXcMcpXx/P/kHNARmL26GehVUzsURDgFBxnkA1ZqK6CfBFCNmKy5CdAroAWTNesb2pfcqERpJgygcEYwQlkuQ+4rNrjHVXhQJeoyFX4gH5EJY1lxbIjBC1kfs4yxx0HyDNuxmsqYfpyqQd1VVIUpbdCpAheR+ZtocxORL68Pomkz3Kona1qHXauUhG7i1M2rKE4emBZGCxHSEQ4NEz7CDD4aHw2Q3+4uTkSxfX1nfLKHyyVZGmMhGhCCmb16cqsnC7MckpYAWdqzAxVfBlPp/Pfj358qcT7jzlsWxxcimfzXx/HX2fz38YnwRJgTvsjbDDqFqGqYEslCW8MMD0rn6su9Ek8Yw3OkLbWtwg80zVfjK7rLLq+Ze90/PPi63A6Gf4vM3+9F7WnUBFDngafc1E7To13QfarfMokVH43CWyycQqp85z/DUy7H8PodG4c3X8OLj/q6+u5JX607rWfbnIVm7Ewb8AJV+dL/mgn2dHQyvw0oxpHFEoUBvkUCCn7ivp82soCZDkJIpUTuVR+f9tHlPv0O3YUItzbFrwUojmkauE4fSYYTiezcSYwcANMMiceKinAB3NVQh+rISK6f18nzI6kOGp5KVnFdCkL1KCgrrPqhnINdzoU3stuni70y8gl0yh7yTXN08XtdRXIbpP2HVVtfjbOLpxlxrUkS05PGQBJQQIuF4pGWSGXwj7cltCPx7w4+QOiPeDY3H6a3F9X4fe1tBXrW34G0lJZjSrAYMOhQcI7lY3mk8UCTUbnagzpv05GH1T7OP/183D8Dr2a4eOKp8JZMxnY9FzFPGb4qGK4ir5Lb0T/QbV6Rj5X6Sak/qDK+PUwGs+NMefM9QWzy+eaEUm4+5A1VV188FtVY4gF35n6slOUHtn0g8dD/IiVHwFy2/qNK3Xl/iW7H78KrqmASdE7TBxfEgdABGWeDn7JbRupvhKzZjm0j2nMmGYIhwuq3oKyLMf3V6Numma7beJe0+y0W41ux6ygy2a71TR7DWw2OvVO12zWK6hZNzu9rok73W63B2vtciWrx6dbNmOO8AbPTJ2pXqvVcK2IiPyVIzrSvKSlEik9tgzA0j7KH0o/uaRbW95xg5g7fKrULzKZVvh5PMLq24ABdzfEqOFWuZwyJOrBsT1EPY88RN8h9NGKQMtXL64qW3KJoF8O2YpZ4QuUSq9UF361hz/NF3dXF5WL6/Bqeqv1/cS26vsF9fxqYFyVdAu3ZvBEdRlA6Uhs+b5SfV2NmcLeyOykLyVfGTxdJB1rFXD+yP5PkyaZZosaaHS7VCSb+m3UeTHG11X4+JpLCsGXxEtJ/Ac)

**Comment by pjcozzi** [comment]
@bagnell?

**Comment by bagnell** [comment]
This is expected behavior. Should you be able to pick through classifications? That would be an easy change.

**Comment by lilleyse** [comment]
Normally no, but since `allowPicking` is false I would expect it to pick through?

**Comment by bagnell** [comment]
It works the same as if there was a translucent primitive in front of the buildings that had `allowPicking` set to false. Would you expect to pick through the primitive to the building? I would understand if classification should be different though.

**Comment by lilleyse** [comment]
Alright, it sounds like this is expected behavior then. `drillPick` is an alternative when wanting to pick through.
