### ISSUE TITLE
Terrain doesn't work if level 0 is missing

### ISSUE THREAD

**Issue by coolwanglu** [AnalyticalGraphicsInc/cesium#6635]
For example, the swisstopo data does not have any data until level 0
https://3d.geo.admin.ch/1.0.0/ch.swisstopo.terrain.3d/default/20160115/4326/layer.json

This issue affect 1.45, but not 1.43.

The cause is probably [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/213777c2bf8640dc2a4120d96797813da03ff0a1/Source/Core/TileAvailability.js#L61), which assumes that level 0 is available.

**Comment by oterral** [comment]
@coolwanglu  We fixed that . I've updated the file now you have all the levels, it should work.

**Comment by coolwanglu** [comment]
Thanks, @oterral , it works!
Not sure whether level 0 is required to exist in the spec, but I'm closing this issue for now.
