### ISSUE TITLE
rotationMatrixFromPositionVelocity not normalized cross product leads to rendering artefacts

### ISSUE THREAD

**Issue by xtassin** [AnalyticalGraphicsInc/cesium#6640]
Method  Cesium.Transforms.rotationMatrixFromPositionVelocity does not normalize the result of several cross product operations.

This leads to rendering artefacts similar to some observed in a different scenario (#3178) when a VelocityOrientationProperty is being used to generate a camera lookAt transform.

**Comment by hpinkos** [comment]
Thanks @xtassin, could you open a pull request with the fix? That would help us get this fix in faster.
