### ISSUE TITLE
Vector tiles broken in Edge

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6654]
Reported by @oterral in #6535

>Hi @bagnell @lilleyse, We have still this bug in 1.46 and 1.45 . When we try to display `.vctr` 3d tiles.
>
>Here is an example : 
>https://codepen.io/anon/pen/RJrxYM?editors=0010
>
>Our tilset contains only points.

**Comment by hpinkos** [comment]
Hi @oterral,  I wasn't able to reproduce the problem because I couldn't load the tileset in the example you posted.  It looks like your tile server isn't configured for CORS

You can learn how to enable CORS here: https://enable-cors.org/

Or @tfili @bagnell do we have a vector tileset we can use to reproduce this locally?

**Comment by mramato** [comment]
@hpinkos there's already a Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Terrain%20Classification.html

I'm not on Windows right now, so I can't test Edge.

**Comment by hpinkos** [comment]
@mramato that one works fine.  It might be related to points, I think that tileset only has polygons

**Comment by oterral** [comment]
Sorry, wmts and terrain services were blocked. Here is an updated codepen with working urls.
https://codepen.io/oterral/pen/xzVXqr?editors=0010

**Comment by hpinkos** [comment]
Thanks for fixing that example @oterral!  However, it runs fine for me in Edge.  
I'm on Windows 10, Edge 42.17134
Have you tried clearing your cookies/cache?  Sometimes that can have weird side effects when switching between versions on CesiumJS.

**Comment by oterral** [comment]
You're right works since Edge 42 . it fails on edge 41 and edge 36.

Do you have an idea why ? 

Feel free to close if support of old edge is not a priority for Cesiumjs

**Comment by hpinkos** [comment]
Ah okay.  Yeah, maybe Microsoft fixed something in their WebGL implementation or added support for an extension.  I took a quick look at their [changelog](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/) and couldn't find anything WebGL specific, but it does look like 17134 was a decent sized release.

I'm going to close this, I don't think we'll have a chance to go back and figure out what was wrong in the older versions of Edge.  Thanks for the update @oterral!
