### ISSUE TITLE
Vertical Polygon Drawing: How to do it?

### ISSUE THREAD

**Issue by silky** [AnalyticalGraphicsInc/cesium#6662]
Consider:

![image](https://user-images.githubusercontent.com/129525/41017747-a83bef1c-6999-11e8-974e-452d741cf919.png)

Generated from the following code in the [Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polygon.html):

```
var viewer = new Cesium.Viewer('cesiumContainer');

var redPolygon = viewer.entities.add({
    name : 'Red polygon vertically',
    polygon : {
        perPositionHeight: true,        
        hierarchy : Cesium.Cartesian3.fromDegreesArrayHeights([111.0, 33, 140000.0,   // 1
                                                               111.0, 33, 100000.0,   // 2
                                                               116.0, 33, 100000.0,   // 3
                                                               116.0, 33, 140000.0,   // 4
                                                               114.0, 33, 180000.0]), // 5
        material : Cesium.Color.RED.withAlpha(0.6)
    }
});

var bluePolygon = viewer.entities.add({
    name : 'Blue polygon on surface',
    polygon : {
        perPositionHeight: true,        
        hierarchy : Cesium.Cartesian3.fromDegreesArrayHeights([111.0, 35, 100000.0,   // 1
                                                               111.0, 33, 100000.0,   // 2
                                                               116.0, 33, 100000.0,   // 3
                                                               116.0, 35, 100000.0,   // 4
                                                               114.0, 38, 100000.0]), // 5
        material : Cesium.Color.BLUE.withAlpha(0.6)
    }
});

viewer.zoomTo(viewer.entities);
```

The vertical (red) polygon is not drawn correctly (it's missing the bottom part of the house-like shape). I've projected it in blue below to show how it should look. In general this makes vertical polygon drawing problematic.

Another example (without code to reproduce) to show the kind of problems we get:

![image](https://user-images.githubusercontent.com/129525/41017889-7dae33da-699a-11e8-878d-1085cde5dc01.png)

I believe this is related to https://github.com/AnalyticalGraphicsInc/cesium/issues/2897

I'm not sure what the current status on fixing this kind of issue is though.

Anyone have any thoughts?

At the moment I feel like I could potentially solve it by computing my own triangulation and adding those geomerties to a mesh; but in my particular case not all the polygons are going to be convex, so it'll be a bit involved to do the work.

Appreciate any advice!

**Comment by hpinkos** [comment]
Hi @silky!  Our polygons are designed to curve to the ellipsoid surface and therefore they cannot take any arbitrary points and draw a polygon in space.  We do have an issue open for this: #3349 

I have an incomplete branch that supports the kind of thing you're trying to do here: https://github.com/AnalyticalGraphicsInc/cesium/tree/space-polygon 

I'm going to close this as a duplicate, but I'll make a comment in #3349 so we can notify you when we have a chance to add this feature

**Comment by silky** [comment]
interesting, thanks @hpinkos

**Comment by mihaiMoise** [comment]
Thank you @silky for the Sandcastle! With your help, I finally found out how to draw an inclined Polygon!

**Comment by OmarShehata** [comment]
If you haven't found it, it's the new [CoplanarPolygonGeometry](https://cesium.com/docs/cesiumjs-ref-doc/CoplanarPolygonGeometry.html?classFilter=CoPlan) that allows you to do this.
