### ISSUE TITLE
outlineWidth not work when add a polygon

### ISSUE THREAD

**Issue by whlysu** [AnalyticalGraphicsInc/cesium#6667]
viewer.entities.add({
                    name: 'Wyoming',
                    polygon: {                     
                        hierarchy: Cesium.Cartesian3.fromDegreesArray([
                        -95.0, 33.0,
                        -89.0, 33.0,
                        -89.0, 37.0,
                        -95.0, 37.0
                    ]),                       
                        height: 0,                     
                        material: Cesium.Color.LIGHTSKYBLUE .withAlpha(0.2),                       
                        outline: true,
                        outlineColor: Cesium.Color.LIGHTSKYBLUE,
                        outlineWidth:20,
                        width: 10,
                    }
                }
The outline width cant't change by outlineWidth or width。how to change?
use 1.46

**Comment by maxdow** [comment]
If you are on windows, It could be related to the WebGL implementation and not CesiumJS.
Take a look at this answer from stackoverflow
https://stackoverflow.com/questions/25394677/how-do-you-change-the-width-on-an-ellipseoutlinegeometry-in-cesium-map/25405483#25405483

**Comment by hpinkos** [comment]
Thanks for linking to that answer @maxdow!  Yes @whlysu, unfortunately this is something that is limited based on the device you are using.  Windows currently only supports an outlineWidth of 1.

**Comment by emackey** [comment]
@whlysu Since you're outlining a polygon, you can use a Cesium Polyline to trace around the edge.  Polylines are things that look like lines but are drawn with polygons, supporting any width.

**Comment by whlysu** [comment]
Thank you all @maxdow @hpinkos  @emackey ,I used the @emackey  proposal to solve the problem
