### ISSUE TITLE
please tell me what's wrong with this?

### ISSUE THREAD

**Issue by fengzhongye** [AnalyticalGraphicsInc/cesium#6675]
<img width="1216" alt="screen shot 2018-06-10 at 8 30 22 am" src="https://user-images.githubusercontent.com/4496435/41197216-9455c4ae-6c88-11e8-9735-f724d05c0321.png">

**Comment by lilleyse** [comment]
Hey @fengzhongye, can you provide a code sample?

**Comment by hpinkos** [comment]
@fengzhongye Please ask your question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
