### ISSUE TITLE
About 1.46 ,RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:64: 'undefined' : undeclared identifier

### ISSUE THREAD

**Issue by 9lovingly** [AnalyticalGraphicsInc/cesium#6676]
When I load the 3D tiles Data,and then the error:
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:64: 'undefined' : undeclared identifier
ERROR: 0:64: 'texture2D' : no matching overloaded function found
ERROR: 0:64: 'SRGBtoLINEAR4' : no matching overloaded function found
ERROR: 0:64: '=' : dimension mismatch
ERROR: 0:64: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'

**Comment by lilleyse** [comment]
Thanks @9lovingly for the bug report.

The error is coming from `processPbrMetallicRoughness`. I believe the problem is the material has a base color texture but the primitive doesn't have texture coordinates. Would you be able to upload the model so we can confirm?

A line in the glTF spec says:
> Mesh must have corresponding texture coordinate attributes for the material to be applicable to it.

So it's possible it isn't a valid glTF model. Can you see if your model produces validation errors here: http://github.khronos.org/glTF-Validator/?

**Comment by 9lovingly** [comment]
@lilleyse ，hi. Actually my model is not gltf and it's 3dtiles.It's large so I couldn't upload it.And  the website:http://github.khronos.org/glTF-Validator/,just support gltf and glb. However，the problem still didn't solve.

**Comment by lilleyse** [comment]
@9lovingly if you upload a single b3dm tile here we can check it out.

glTF is embedded in the b3dm and can be extracted using the [`b3dmToGlb`](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/tools#b3dmtoglb) tool.

**Comment by dev-oups** [comment]
Hi all,
I have the same problem with several 3D Tiles data sets converted from CityGML.
Could anyone get a look at this?
Thanks

[buggy.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3956315/buggy.zip)

```
An error occurred while rendering. Rendering has stopped.
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:111: 'undefined' : undeclared identifier
ERROR: 0:111: 'texture2D' : no matching overloaded function found
ERROR: 0:111: 'tile_diffuse_final' : no matching overloaded function found
ERROR: 0:111: 'SRGBtoLINEAR4' : no matching overloaded function found
ERROR: 0:111: '=' : dimension mismatch
ERROR: 0:111: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'

RuntimeError@http://127.0.0.1:3615/scripts.js:23:40446
createAndLinkProgram@http://127.0.0.1:3615/scripts.js:23:924186
initialize$1@http://127.0.0.1:3615/scripts.js:23:926921
get@http://127.0.0.1:3615/scripts.js:23:923054
getAttributeLocations@http://127.0.0.1:3615/scripts.js:23:1761663
createVertexArrays/</<@http://127.0.0.1:3615/scripts.js:23:1764278
ForEach.meshPrimitive@http://127.0.0.1:3615/scripts.js:23:1613782
createVertexArrays/<@http://127.0.0.1:3615/scripts.js:23:1764210
ForEach.object@http://127.0.0.1:3615/scripts.js:23:1611153
ForEach.topLevel@http://127.0.0.1:3615/scripts.js:23:1611298
ForEach.mesh@http://127.0.0.1:3615/scripts.js:23:1613650
createVertexArrays@http://127.0.0.1:3615/scripts.js:23:1764181
createResources@http://127.0.0.1:3615/scripts.js:23:1777827
Model.prototype.update@http://127.0.0.1:3615/scripts.js:23:1794542
Batched3DModel3DTileContent.prototype.update@http://127.0.0.1:3615/scripts.js:23:2217361
Cesium3DTile.prototype.process@http://127.0.0.1:3615/scripts.js:23:2445037
processTiles@http://127.0.0.1:3615/scripts.js:23:2480247
Cesium3DTileset.prototype.prePassesUpdate@http://127.0.0.1:3615/scripts.js:23:2480515
PrimitiveCollection.prototype.prePassesUpdate@http://127.0.0.1:3615/scripts.js:23:1509150
prePassesUpdate@http://127.0.0.1:3615/scripts.js:23:3017943
tryAndCatchError@http://127.0.0.1:3615/scripts.js:23:3022620
Scene.prototype.render@http://127.0.0.1:3615/scripts.js:23:3024129
CesiumWidget.prototype.render@http://127.0.0.1:3615/scripts.js:23:3267523
e@http://127.0.0.1:3615/scripts.js:23:3247839
invokeTask@http://127.0.0.1:3615/polyfills.js:3626:31
runTask@http://127.0.0.1:3615/polyfills.js:3403:47
invokeTask@http://127.0.0.1:3615/polyfills.js:3700:34
ZoneTask/this.invoke@http://127.0.0.1:3615/polyfills.js:3689:48
timer@http://127.0.0.1:3615/polyfills.js:5885:29
```

**Comment by OmarShehata** [comment]
@dev-oups how are your 3D Tiles created?

**Comment by dev-oups** [comment]
@OmarShehata converted from CityGML with FME and the Cesium 3D Tiles writer.
