### ISSUE TITLE
different behavior minified vs unminified, normalized result is not a number

### ISSUE THREAD

**Issue by eatapl** [AnalyticalGraphicsInc/cesium#6688]
When digging into "normalized result is not a number" exceptions (see #4863, #4801, etc.) I observe  different behavior between the minified and unminified versions where minified does not throw the exception and unminified does.

Example code taken from #4863 using Chrome 6x on Win 10 x64 w/ Cesium 1.44, 1.45, & 1.46:

`var viewer = new Cesium.Viewer('cesiumContainer');

var hierarchy = [ -180,90,-180,50,180,50,180,90];

viewer.entities.add({
    polygon: {
        hierarchy: new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray(hierarchy)),
        outline: true,
        outlineColor: Cesium.Color.YELLOW,
        fill: true,
        //fill: false,
        material: Cesium.Color.RED,
        outlineWidth: 10
    }
})`

**Comment by shunter** [comment]
This is by design.  The unminified build has additional runtime checks which can impact performance.  As a result the recommendation has always been to develop and test applications locally with the unminified version, and deploy the minified version.
