### ISSUE TITLE
Billboard depth testing performance improvements

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6699]
Leftover from #6621 

Right now we're doing the depth testing checks in the fragment shader.  We can move most of this to the vertex shader (when texture reading in the vertex shader is supported), but the math will be slightly different for computing the screen coordinates.

See this comment: https://github.com/AnalyticalGraphicsInc/cesium/pull/6621#discussion_r195212797

**Comment by pjcozzi** [comment]
Let's please do this for the upcoming release as it will be a significant performance win for a large number of billboards, which is a common case.

**Comment by hpinkos** [comment]
@bagnell I'm really stuck on this one.  I'm not sure how to get the coordinates for the depth texture lookups, and I'm not sure what I should be comparing the result of that lookup to.
