### ISSUE TITLE
Switch datasources to use polylines on terrain

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6700]
At least `KMLDataSource` is using corridors for polylines clamped to terrain, but now we can use polylines when available.

What other datasources can be updated?

**Comment by mramato** [comment]
These should be be trivial changes, so it would be nice to have them in the next release.

**Comment by likangning93** [comment]
Does this include adding `clampToGround` to Czml polylines?

**Comment by mramato** [comment]
> Does this include adding clampToGround to Czml polylines?

Yes, does the entity API default to true or false?

**Comment by likangning93** [comment]
It defaults to false. I'm not sure about what else needs to be edited though in terms of CZML documentation/wiki stuff.

**Comment by mramato** [comment]
@likangning93 the czml-writer repository is where all of that stuff gets handled.  CzmlDataSource itself will likely be a one line change.  You can work with @shunter to get the property added to the spec.

Glad to hear it defaults to false, since that makes it a non-breaking change.
