### ISSUE TITLE
Collada. Double sided texture do not work on server

### ISSUE THREAD

**Issue by alextym** [AnalyticalGraphicsInc/cesium#6703]
I create dae file to export to cesium. My surface has texture only on back (one side of surface). I want it has face and back texture. In collada spec 1.5 (page 26) i see that we should apply semantic attribute with double sided:
I use 
 ```
<newparam>
          <semantic>DOUBLE_SIDED</semantic>
 </newparam>
```
inside library_effects>profile_COMMON
Is problem in my code or on the server? Thanks for any help.

**Comment by hpinkos** [comment]
Hello @alextym, Cesium doesn't support COLLADA directly, you'll have to convert it to glTF first.  We have a hosted converter here: http://52.4.31.236/convertmodel.html

If you have any follow up questions, please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by alextym** [comment]
Hello @hpinkos, thank you.
