### ISSUE TITLE
Stringifying Iso8601.MAXIMUM_VALUE results in an invalid ISO 8601 date

### ISSUE THREAD

**Issue by kripod** [AnalyticalGraphicsInc/cesium#6718]
Calling `Cesium.Iso8601.MAXIMUM_VALUE.toString()` or `Cesium.JulianDate.toIso8601(Cesium.Iso8601.MAXIMUM_VALUE)` results in an invalid ISO 8601 date: `10000-01-01T00:00:00Z`. The correct result would be `9999-12-31T24:00:00Z`.

**Comment by shunter** [comment]
`9999-12-31T24:00:00Z` and `10000-01-01T00:00:00Z` actually are the same instant, that is, they are equal, so both are correct representations.

The inconsistency though is that 

`Cesium.JulianDate.fromIso8601(Cesium.Iso8601.MAXIMUM_VALUE.toString())`

throws an exception.  We can change the formatting code to special case that specific instant and produce the `24:00:00` string.
