### ISSUE TITLE
Does the Cesium.Polyline class have this attribute of disableDepthTestDistance?

### ISSUE THREAD

**Issue by dminor112** [AnalyticalGraphicsInc/cesium#6728]
I found that when i want to keep a billboard always visiable, i can set the billboard option disableDepthTestDistance = Number.POSITIVE_INFINITY. but i does not work with a polyline. Is any way i can do to keep a polyline always visiable?

**Comment by hpinkos** [comment]
Hello @dminor112, polyline does not have a `disableDepthTestDistance` property.  However, you can set at `depthFailMaterial`.  The polyline will draw with that material when it is behind or under terrain.  If you set it to the same color as the `material` it will effectively be the same as having the polyline always visible.
In the future, if you have questions please ask on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by dminor112** [comment]
ok, thank you!
And I still have some problem, is  depthFailMaterial supported with chrome? There is no effect with the demo : https://github.com/AnalyticalGraphicsInc/cesium/issues/5333
![image](https://user-images.githubusercontent.com/7435641/41889125-6c271e50-793b-11e8-8f2c-89fa2bd7ea18.png)

**Comment by hpinkos** [comment]
@dminor112 that issue is open because `depthFailMaterial` doesn't currently work with dynamic polylines.  However, it works with static ones.  See the `Sample line positions and draw with depth test disabled` part of this demo: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Ground%20Clamping.html&label=All

**Comment by hpinkos** [comment]
@dminor112 yes, we do want to add this.  We have an issue open here: #5333
