### ISSUE TITLE
Materials for Ground Primitives don't work for small areas on newer mobile devices

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6739]
[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVRRT9swEP4rXl+aiMqF19GioYwNtLIhivZUCRnnkno4vsh2igD1v+8SN21I6cRcqa3v7vvuu8tdVsKylYInsGzKDDyxBJyqCv67sUVD2VwTNF4oA3YYny7MijBOggGCBCxvruRi2xPCMMsceIo75scn5CdrAIDxyitwXKRp9BqAFqQXJtfAPrPXHZdEtKkywoMjx0bfbRvLM4vFV8gtgIsoy4g1XyFx+xuPdnQFEVklNHENOR+rQuTgxoH2foY53ieo0fI/ZT4MqPXCrJu6g/QXxOIOo14hcaiOal4Kk+p+P+eSBJp5KSRcrAhzGYKipnFcCkI2FBswJ9FXpqz8ufQKTZRVJvwpcAUF4eO2Q/1+WqhDzrWO4s3zUBnbpCkwBfZpOt2JIus1Gfn1r9uby6uf3+Nu43fAUsnHG3SqljCvyhKth/RNbCOFipeCXE4Js5sNKQqwouG40FqVDlW6rYOXG9rQvy5dnX4jNIWMpi+NtuzxXvKuAMytKJdKsm2lScfaTEzSMnU4T99n1MLviK6FX3KP7cB1s3EKVL5K4SARmg8SockPMkk0DmnuNeZRzXjEhvQ5qmW+m/jwvvXPgf3bF/DhfSR9o1rYiAWl7VbWLT16Zzf75/93tX/W++Z1v02dmPV24zu9+9fCr0eHNvzuuQQ+u/h2d5/MrpIf8elgNJg4/6zhLLB/UUW9SKyyOqLiPBSlrps6fqjkI3guXZNjMm5Bk1StmEqni0HvrbwYMKmFc+TJKq3n6gUWg7PJmOLfwDQKenD5rxVYLZ7rkOXJ2SwYOeeTMV33UR5RPwjbYfwL)

Increasing `offset` to larger than `1.0` switches to spherical coordinates, which mostly works other than some depth precision issues.

Related: https://github.com/AnalyticalGraphicsInc/cesium/issues/6735

[EDIT] for anyone new to this issue, Cesium uses the materials-on-GroundPrimitives codepath when available for batching colored `GroundPrimitives`, which is why on some newer mobile platforms `corridors` on terrain won't work bu on earlier mobile platforms without depth texture support they will work.

**Comment by likangning93** [comment]
I think it's a batch table problem.

Here's a [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1VhtT+NGEP4rLh8Ou2cc4PhQ8XIqCtwRFQ50pIeqckKLPUm2rL3Weu0QTvnvnV2/7To2peqnRojE8/LM7MzseGcLIpyCwhKEc+IksHTGkNE8Dr5pmrsd6scxTyShCYht3/lxnzj4oTGZg1jdCF7QCLUPa81QAJEwpQyuSHoLoqAhTGxht8JQn1ywVvcxpyy64lHO4HfB3O3TLAOZjabwLHMB2egLwW/CzomQi8lk2yth1vi99o7ukwIXk4WQAK6lXFSgH5FVMpcLKuFuQRh8hVCSZM7gRtCYSlq0QqJm3dFILhBqN9jFz54WmOVJKClPHBJFmxhuiJ7xuSDpgoaeClXpoQVrB7oBsXQDxpM5lXkEzk7HId+xBYl8m1wD+P6NgF0578hcDpFS0MdcQobrqdZyuyARX37jLI/hNE2BCJKEEMxB3jCSEFHlccy5iGiCVXLagLiNLd/5c9d3yr89/bf73S/TGswZf4QAGKNpxmlUk2OSYmn9BToztpsZz+XiDjL5cDH5fIGutn4HNi8oCMtVFWyqXl7fDWkia0MRSCaXRES2Tk3dEE84VvOmfENuFFqVAoSEZxVuELc8FyEWVbultgsIP2yuXFHdbUyrzflz9zvScGMrVpe3Z/A6rP3vjuJ5R8gbtl2Grsc0MoYsK1a/YcV5za4R+cZkTbOtNVTTUEN8zYaZrsZIQ7SttGTTTEu17RiWmjrQJpyUZ1TV9oezCzpfdLwalL3ky0HRGeNEOo9EhotJtGEea2xFk7kC3HeKB5pgwWWgNjGcP0tIZNaNTKtwgApLTJaWfl1MJ7ZXDje3E+Mbx/Vsxg/7Uf2bs4ebasmYkfAlfogglYsxI3H6iQgN7ypyzCNg6r3W9oqvoLpdAVN+vgLnZ60d8jjFCNWYrreZHb0NrTofc5HoV6htqQ9fYlPMkAwW07V3l28XvecFz6uXo83FtxVpeaHsIDUmDI22Bfu+6/AQohY7J0OIzTYbAOyDVDp35a7pou+8wa2yXhVIWYAIwyCZy4VbA3s9Wo3R0YmhO+xkGcnSy25U3+6l1uy62UD3+dnaHZ2Y6v2etturbEEHTQx8Zyfi0njsuOz1GTf3YQ3YOFQhGs9vg+xpGSX2vrsX7DojIx34jtcUY91dzPW29fqbCTKPUWz4Bfg/6l9lzTA+P1Nt61ror2rH5UlKwidNcWV5eNo/0y1Gn4Q0ozpU+aoRfsLA6NMVtguMqBJU5+AUIxu8LPtTpZYCK+NQVtle0gQPc7o5tbzM7Vjxu557g9sir4BTFbAzmkl1OHSNYPuO7YjqeapSLNrSwwbUm9LgedB0MWC6TaD/30yvhnrKgRNyxkW9r3LfKXw1UOii74sVnTku8p3jEwzYu3f4D3+pDYK/K3qhfhcVHaeMTZDqvVgmqjSv3eixt3aAZeD8cN6Eoheh3a/XMLiQ9eAWfm0Ks4ejdrAyJsY58BikWE2SMo8Zzo+GzucO21Q11W2txpNavaumPu0Id9j+tsXWnm8TjDnp0HhohSwN0kxNtntXWH+CEtZOVV3/ekaCwx5ix7veTnrYS/ZNl+vBuxpjyjEsrbOVBTgdu6+lWSmu64F7QZKIdS8gbkMBkNxi/4PzAl25KIXc0lRIUDNTKJVykIGcJHhwO9UHO7ee092YF6CW4tUXFxu+ClAy/+huvTmrkROPeM5PJ+3oq6hXSAyurr/eXEy+fG4M2oopDZ/qs+VtnqrWDJElW7/l1FSO4CRpbzNCEoMgGuO8HoKbFQb1yb+dgE3zlaMRzGgCkdugexvGTQfqa4F2yB+blwUzweNxjWRgHm0ivuHCpKO1NiquKjisGn+oQqarFILL80/Th/HlZPyb11zo0ARtEXbZ3ICcODu/7AZ7Rza7vvfQFz5aud/loTicwRwdytyuOb9rwdN3VVZGGedPp9KE1nH88C+BfXMHtSju3m7Zro2vQSemaj6Z4VHfbXuPoM8HweTs/Mt0Mv1DKW75W8eZXDH4WCbmVxqrSla3eW4QjCTEqRpxstFjHj6BDMJMb9bjUa10HNHCodHJ/VbnhvF+ywkZyTLkzHLGbukL3G99PB6hvKWG73V8Lc+vscUxslIii72PlyUxCILjET5uaknO2SMRBuLf) that replicates a stripped down version of the shader that just computes texture coordinates.

Here's the same [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1VhtT+NGEP4rLh8Ou2cc4PhQ8XIqCtwRFQ50pIeqckKLPUm2rL3Weu0QTvnvnV2/7To2peqnRojE8/LM7MzseGcLIpyCwhKEc+IksHTGkNE8Dr5pmrsd6scxTyShCYht3/lxnzj4oTGZg1jdCF7QCLUPa81QAJEwpQyuSHoLoqAhTGxht8JQn1ywVvcxpyy64lHO4HfB3O3TLAOZjabwLHMB2egLwW/CzomQi8lk2yth1vi99o7ukwIXk4WQAK6lXFSgH5FVMpcLKuFuQRh8hVCSZM7gRtCYSlq0QqJm3dFILhBqN9jFz54WmOVJKClPHBJFmxhuiJ7xuSDpgoaeClXpoQVrB7oBsXQDxpM5lXkEzk7HId+xBYl8m1wD+P6NgF0578hcDpFS0MdcQobrqdZyuyARX37jLI/hNE2BCJKEEMxB3jCSEFHlccy5iGiCVXLagLiNLd/5c9d3yr89/bf73S/TGswZf4QAGKNpxmlUk2OSYmn9BToztpsZz+XiDjL5cDH5fIGutn4HNi8oCMtVFWyqXl7fDWkia0MRSCaXRES2Tk3dEE84VvOmfENuFFqVAoSEZxVuELc8FyEWVbultgsIP2yuXFHdbUyrzflz9zvScGMrVpe3Z/A6rP3vjuJ5R8gbtl2Grsc0MoYsK1a/YcV5za4R+cZkTbOtNVTTUEN8zYaZrsZIQ7SttGTTTEu17RiWmjrQJpyUZ1TV9oezCzpfdLwalL3ky0HRGeNEOo9EhotJtGEea2xFk7kC3HeKB5pgwWWgNjGcP0tIZNaNTKtwgApLTJaWfl1MJ7ZXDje3E+Mbx/Vsxg/7Uf2bs4ebasmYkfAlfogglYsxI3H6iQgN7ypyzCNg6r3W9oqvoLpdAVN+vgLnZ60d8jjFCNWYrreZHb0NrTofc5HoV6htqQ9fYlPMkAwW07V3l28XvecFz6uXo83FtxVpeaHsIDUmDI22Bfu+6/AQohY7J0OIzTYbAOyDVDp35a7pou+8wa2yXhVIWYAIwyCZy4VbA3s9Wo3R0YmhO+xkGcnSy25U3+6l1uy62UD3+dnaHZ2Y6v2etturbEEHTQx8Zyfi0njsuOz1GTf3YQ3YOFQhGs9vg+xpGSX2vrsX7DojIx34jtcUY91dzPW29fqbCTKPUWz4Bfg/6l9lzTA+P1Nt61ror2rH5UlKwidNcWV5eNo/0y1Gn4Q0ozpU+aoRfsLA6NMVtguMqBJU5+AUIxu8LPtTpZYCK+NQVtle0gQPc7o5tbzM7Vjxu557g9sir4BTFbAzmkl1OHSNYPuO7YjqeapSLNrSwwbUm9LgedB0MWC6TaD/30yvhnrKgRNyxkW9r3LfKXw1UOii74sVnTku8p3jEwzYu3f4D3+pDYK/K3qhfhcVHaeMTZDqvVgmqjSv3eixt3aAZeD8cN6Eoheh3a/XMLiQ9eAWfm0Ks4ejdrAyJsY58BikWE2SMo8Zzo+GzucO21Q11W2txpNavaumPu0Id9j+tsXWnm8TjDnp0HhohSwN0kxNtntXWH+CEtZOVV3/ekaCwx5ix7veTnrYS/ZNl+vBuxpjyjEsrbOVBTgdu6+lWSmu64F7QZKIdS8gbkMBkNxi/4PzAl25KIXc0lRIUDNTKJVykIGcJHhwO9UHO7ee092YF6CW4tUXFxu+ClAy/+huvTmrkROPeM5PJ+3oq6hXSAyurr/eXEy+fG4M2oopDZ/qs+VtnqrWDJElW7/l1FSO4CRpbzNCEoMgGuO8HoKbFQb1yb+dgE3zlaMRzGgCkdugexvGTQfqa4F2yB+blwUzweNxjWRgHm0ivuHCpKO1NiquKjisGn+oQqarFILL80/Th/HlZPyb11zo0ARtEXbZ3ICcODu/7AZ7Rza7vvfQFz5aud/loTicwRwdytyuOb9rwdN3VVZGGedPp9KE1nH88C+BfXMHtSju3m7Zro2vQSemaj6Z4VHfbXuPoM8HweTs/Mt0Mv1DKW75W8eZXDH4WCbmVxqrSla3eW4QjCTEqRpxstFjHj6BDMJMb9bjUa10HNHCodHJ/VbnhvF+ywkZyTLkzHLGbukL3G99PB6hvKWG73V8Lc+vscUxslIii72PlyUxCILjET5uaknO2SMRBuLf), but with all batch table reads replaced with hardcoded values.

The former computes texture coordinates very incorrectly on iPad.

**Comment by likangning93** [comment]
At @bagnell's suggestion, tried disabling floating point textures in the batch table which results in the same thing happening on Desktop. So I think we can chalk this one up to the iPad's lack of support for float textures... looks like that's going to have to be an additional requirement. I'll open a PR soon.

**Comment by likangning93** [comment]
Maybe the iPad is actually doing the same packing thing under the hood, which might also explain the depth texture problems... that is very bad.

Regardless, I'll open a PR soon adding a check for float texture support.

**Comment by likangning93** [comment]
BTW on Desktop, using our float packing code, the diff actually doesn't seem to be *as bad.*

**Comment by likangning93** [comment]
^
![notasbad](https://user-images.githubusercontent.com/5395255/41999633-2557e210-7a2c-11e8-94cf-1f569ce7ee75.JPG)

**Comment by likangning93** [comment]
^ that was on Windows Nvidia, it's less on Linux/Intel which is interesting.
Maybe instead of requiring float textures we can come up with something more clever to reduce the range of the floats getting packed.

![screenshot_2018-06-27_19-36-57](https://user-images.githubusercontent.com/5395255/42005288-902618f4-7a41-11e8-8f8b-dedc98293f30.png)

**Comment by likangning93** [comment]
So I tried:
* [logarithms](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xVhtT+Q2EP4rLh9K0stlgbtKFbCnooU7VoU7dGyLqlIhk8zuuufEkeNkWar97x07cd5zpe2HrhBJxvPyeOwZzzinkuQMNiDJlMSwITNIWRb5vxiasx+Yz5mIFWUxyH2P/HkfE/yxiK5Abm+kyFmI0sdWMpBAFSwYh2ua3ILMWQDzNrNT6tC/TPJa9jFjPLwWYcbhZ8md/bM0BZVOFvCkMgnp5CPFJ+UXVKr1fL7vFmp2+Ny5J/dxjpNJA4gB51JMyjefOFQMbtZMwd2acvgMgaLxisONZBFTLK+ZpB26Y6Fao6oS3DVVa1+JzzRkNE6dA/9718gsszhQTMQkhCXHqTtUSte6aSkkcbRWhooOTvBxSnDc5xCv1Bq/X72qeI1bl0TL/8Z+J9MpSvgHrWH9C3AxWJxpwJa0q1+tMDFwU7aKS30u+a6gcbE6cswbfUztoFtqQ0271qRoGPZ95QS4AmIlabJmgQFYSLfc195QlZKWLIKJV0xlIZDXHcd7pM1I1cv4KoWvXqiwy1esqp0OVUqyx0xBWu+E2zUNxeYXwbMIzpIEqKRxAP4K1A2nMZXlfp0JIUMW45Y4q5Q4lS2P/HbgkeLv0Pwd/O4V29dfcfEIPnDOklSw0JIjmmAI/QFmZdowU5Gp9R2k6uFy/uESoda4/faYn1NebZ626NWnuzFJHOoJAk3VhsqwLWOpPfZYYNT2+StyJVCI2Ghqo7f7tD+KCLuDFkqXXpls+zAHqeBJLy7IW5HJALdwHVj7FWZkDN6QRKRMr8Ob80u2Wp/sk1cv4b0Sm1HWJRdUkUeqgvU8LLgafIhwy+KVVnhE8gcWI9wU9IaDiycFsUo7ihsCb1Fgg04y3F9nMw5t8DU4C3wsLpxYfC0x+tv6bBZbkip/ScBwiMnyZNdnLcdMolrqHJWIjXPkY1Do7LTExNSW2fX8oh1sQZmPfBBTaUhzOBW7/+R6tbC/bX09jxpvmsf4JBEejo7b5h2AsOIPN+VOwBgInqOHEBK1nnEaJe+pNF53NDkSIXB9BNfh/hl0wsphIS62gG7SbIGIEtw4Vqdj8XbMGqdUgTITMjanfdvSkH6FeS3VzmgNVt7TLGa3Lugjh4d2oDrlPnYbLh0VwNit+V3Xf9o+n/TdZ+ZhYrc1D60VqRHlCHvEVBXxtRnM+x2fjJk0bBf0H5q0yefvLQ7Z1NJ3Ra7smn/9AtxFcGolRW5ANUXF4VjF7oBUZXQybciOgyzWokDZXZeXozSSXZiV6iGctd3JtCk+jLTOfLosxCxX+cAjr0OhGp8dyO6Q8WaKtAorQKXGxvfLVA5k80L3kXPoH5BJYzmwVDCUxrz7aap1ri0lXUXINnqy/U9Hy7/KocWewRr2XKfOT9I8ypDM4oQGXwzFUUUNdnRu4tIUVGagrM08nYzfo2NMkYYJBz2qGXXbkKBn/efN8FLpqcC2UduVtjcsxprQJMh6LHU6Vrwucnc0LLJScaIdds5SpWtMp+Fsj7SB6Kypd0qLttFH6uCS+k+jpvMR0/UCev/N9HYsp7zF7oYLaeMq80ju6SLCbPohX+lKA8fJ6RQd9u23+A/fdIDge0nP9Xte0gdLg/JsLhaqMG9gDNjbEeApkD/Ji7SYSRj4dg6jE9mNhvDXmtZ2j1X3Z42WcQUiAiW387hYxxTb7YbMh86w0+k2rXhbqkJixbtiRcVlO8Hj+r3NtnO9NqHRbh03PhqtblOCVs1XGx52tyAZ5XVz1sU3UOsfDxA76AYz6fEg2WtCtvcUZR9SdHOJXa3Uxybb+doya8GdvZ9Y0zjk3fua20ACxLeY/+AiRyiXBZNTmAooSqZaSynsp6DmMRaPZ6a4dGy770QiBz2V6tahh1WC5vlbuDY4y84Vy0zyzbTuoDX1Gon+9afPN5fzjx96tyClYRZ8sfXtbZbo1Axh70pEu0U396icxvXlT0AjkNTouLC9dDVD3zZldRPYNF8CxZaRxRA6lXa3Z7wJwN4u1HcFs+adw1KKaGY1NXSe9DW+4N6lI7Xr3QfpyxxvbIcstgn4VxfvFw+zq/nsJ7e6/2Ix2qL8qrpImZLXPxz4hyftYXt9Ypo8IzwMecwP57BCQKnTNed1LZi7qfaKciG+nKmmauPHN/9QsdeMoFqLc/j9Af5Msu69jaJZ6GZpiU2BUychyZ7e+vPzi4+L+eLXwsN73t5pqrYc3hVr9COL9KbW96CO708URInuJtLJYxZ8AeUHqYnb04kVOg1ZTlg4vd/r3M3e75GA0zTFkWXG+S17hvu9d6cT5G+J4RGPJ/TqE2Y7TreaZX347qog+r5/OsHPvpQSgj9S2dD4Fw)
* [square roots](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xVhtb9s2EP4rWj408qLITl+AIYmLBY7bGEuaIPEaDM0Q0NJZ5kKJGkXJcQr/9x0pUW+WW3f7MMOwpeO9PLzjHXnMiLAyCksQ1tCKYGmNIKFp6H7WNHvf068jHklCIxD7jvX1IbLwQ0MSgFjdCJ5RH6WPjaQngEiYUgZXJL4DkVEPJk1mu9ChPqlglewspcy/4n7K4HfB7P2zJAGZ9KfwLFMBSf8TwX/CxkTIxWSy38vVrPF/3Tt5iDKcTOJBBDiXfFKufsWhfHC5oBLuF4TBLXiSRAGDG0FDKmlWMQkzdE99uUBVBbgrIheu5LfEpyRK7IE7GAze9bTYPI08SXlk+TBnOHubCNEznppzYdlKMUVdgxP8O7Vw3GUQBXKB7wcHJa/64NgX+ifyaoMJDSI7J/Wsnwva30La+onMEjOokGhvoDMamIjvb87W9tCHPBAkXlBPm8+lGw5oLolSSUPWZTwKqEx9sA5brnOsJiORu/GVCg92VNjmy4NipkOkFHSWSkiqWN4tiM+XnzlLQziLYyCCRB64AcgbRiIiihU34lz4NMKInpVK7NKWY30ZOFb+PdLfwZ9OvgDdgPEZuMAYjRNOfUMOSYxJ8BfoyDRhJjyVi3tI5OPF5OMFQq1wu80xNyMshZMu0cvr+22SOLQhCCSRSyL8poyhbrBHHPNuk78klwK5iEmGJnqzTjdHEWF70EBp00uTTR9mICQ8q+CCuOOp8HAJV4m1X2JGRu+NFfOEqji8Ob+gweJk3zrYhfeSL7eyzhkn0poR6S0mfs5V40OEKxoFSuFrK3ukEcJNQC04GD9LiGTSUlwTeIsCS3SS5v42m3Zoja/OqaZCo9yH+iXD3G9qUz8CcPVHeuZ25j5j3cl/dTHCx56DhJUmryrySpNfNPmlIr9gaWqaWG/gwhSxQtxh7F6TswNbwB5vimDgMvRewkcfYrkYMRLGH4jQE7cVOeQ+MLWPVRl3C6pmZDDl4xUgQsXm8TDG2BmdtkHbMqu9Va7VEReR3jKblrr0SywtiXJ4Y9A2UVAsesFMyYzBYzNX7GIp9dCz3xXA9Kn4ez33efVysuk+PQ+dPo15KK1IDQlD2FtMlUlXmcHS2/LJNpOabUx+0KTJ/+9b7LKppO/zctU2f7gD7jyblZI8PVFNvmfbRnGvQ6o02h/WZLeDzGORo2zHZXeUWrINs1TdhbOy2x/WxbuRVsVHna2w0JQ+cKxDn8vaawtyr8t4vUoZhSWgQmPtfTeVHQU11/3aPnIHVr8WDtytNaU2780i1dha5oIEIbJt3Vz+p+r+r2povmYYD85V6bwW+q9IyTSKifekKbbMj0Gvz3Ve6jONHiiOR44qxh/QMfqchAUHPaoY1dk7Rs+6L8vuUKmpwKp2vCpsL2mExzJdIKuxxG5ZcdrIe1vTIi0Ux8ph5zSR6phn15ztWE0gqmqqldKgLdXJuzOk7vNW09kW01UAnf9merWtpry1PM64MHmV4q6MR1N3oBd9l6/o3FLtjHU6RIe9eoU/+KQSBJ8Leqaes4LeeWYo9uY8ULl5DaPD3toCloD11dpJi56Ehm/msHUi660p/K3Or9nmVC1SrScLgIcgxWoS5XFMsGetyXxsDddF6+JNqRKJEW+L5Ucx04wdV89NtnXPaRJqHc9x7aViakiQsv9pwsMGEwQlrOqP2vg6jtvHHcQWus5KetxJduqQTbNftAJ5QxWbaCUu9rn2t8KsBNemyV+QyGftS487TwBEd1j/YJwhlIucyc5NeQQlE6WlEHYTkJMID49n+nBpm47bDnkGaiplW7+BVYDi+S5ck5xF84jHTOunYdXEKuoVEt2r69ubi8mnj417hEowpt6TOd/epbEqzeA3eM0up/prVE6i6gbFIyEIonWMTTtbztA1fVHVh9XNF0Cxa6MR+HapvbdhvA7ANPhVuz6qt/1zwcOR0VTTebKpcYerj5bUurbiqvsUZ9sKma5icC/HH6aPo8vJ6LdeeYlEI7RF2GV5lzG0Dn8ZuEcnzWFzgzFUtU0Ld0Pe5odzCBBQYrfNOW0L+nqoGVHG+dOZrKvWfnzzg4qdegZVWuyjd3m5rv1tBTFVPdIcewG7qj2CPr91J+fjT9PJ9I/csXvO3mkiVwze56H5lYZqLas7RNt1+xLCWDURSX+Wek8gXS/R6XraN0KnPs0s6g8f9lr3mg97lsdIkuDIPGXsjr7Aw9770z7yN8RwZ8eNObjGIsfISrEsjt5f5kTXdU/7+LopJTlnMyJqGv8B)
* [inverses](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xVjrb9s2EP9XuHxopEWRnT6AIbaLBU7aGEuaIPEaDE0RMNLZ5kKJAkXJcQr/7ztSb1lu3e3DjCCSyHv87sEjjymVJGWwBElGJIQlGUPMksD9bMasfc98jkWoKAtB7jvk231I8McCOge5upYiZT5yHxecngSqYMo4XNLoFmTKPJg0ia1chv4lkle8jwnj/qXwEw5/Sm7tn8QxqLg3hWeVSIh7nyg+KT+jUi0mk307E7PG59oe3IcpGhN7EALakhnlmk+cyiaXC6bgbkE53ICnaDjncC1ZwBRLKyJZTN0xXy1QVA7ukqqFq8QN9RkNY6vv9vv9d7ZhmyWhp5gIiQ8zjtZbVEq78NRMSGJpwQxl9Qf4GBKcdzmEc7XA74ODklb/cO4L+4q0R26f9PLPQW4qWtpQSH1/0xTLQweJuaTRgnlGdsbdsK4Z71JIg9flIpwzlfhADlt+cUiTkKrd6EqBBzsKbNNlHi/MoUpJ9pgoiKtA3S6oL5afBU8COIkioJKGHrhzUNechlTm6TQWQvosxHCdlEKsUpdDvvQdkv0dmb/+VyfLLnfOxSO4wDmLYsH8YjigEWb432Ai04QZi0Qt7iBWD+eTj+cItcLtNufclPIEBl2sF1d32zhxaoMRaKyWVPpNnmJ0gzwUuKg26cvhkiFjKTK9id4ebJtFhO3JAkp7vFTZ9GEKUsGzDi7IW5FID1O4WjX7JWYk9N6QSMRMx+HN6TmbLwb75GAX2gux3Eo644Iq8kiVt5j4GVWNDhGuWDjXAl+T9IGFCDcGnXBw9qwgVHFLcI3hLTIs0UmG+vtkxqE1ujqlNoWFmQ/NR4prvylN/5OA2R8ay62sxKTus0OK11X1+mK3wKw3dGL6kwC3BstuUnbonfOH69zRmGLeS/DgQ6QWY06D6AOVxihLDwfCB643oGo13YCuBylMxdkKyK+G2xNBhHEpZFq2veESkzraE2UejoUMzV7X1NQlX2HZiLUzG5NW4WFNYpJhSh85PDTXgZWniW075IcMuDQqett2n1cvg033GTvM0mjYoaXiaEA5wt6iqlxQlRosqy2fbFNpyM7oT6os1vaPNXbp1Nx3WSlqqz/cAXe2UrWQbOmhmGyztQrBdgdXqbQ3qvFuB5nFIkPZjsvuKA1nG2Ypugtnpbc3qrN3I60Kiz4UYREpfeCQQ1+o2mcLst2lvF6BCoEloFxi7Xs3kR3FMpP9Oi9QVTiK4lSze7NINbaNmaTzAMm2bhz/U+X+VzU0yxku5qe6dF5J88iXZBJG1HsyI5bKjjivT826NOcVM5EffRxdjD+gY8wZCAsOelQT6kNzhJ51X5bdodKmwKp2dMp1L1mIRy5TIKu52GppcdrI7a3LIskFR9phpyxW+ghn1ZztkCYQXTV1pjTGljZWqM6Qus9bVadbVFcBdP6b6tW2mvKWeIILWayrxCEpHjvdvkn6Ll+xGdF9CBmO0GGvXuG/YdY24Hs+nur3NB/vPA/ke3MWqEy9gdGhb02Ax0C+kZ2kGCMM/MKGrYasty7h77VszRaman9qzdQcRABKriZhFscYm80az8fWdJ21zt7kKpEU7G227JhVNFrH1XuTbG07zYFaN3Nc+6iIGhy07G2a8LBRBckor3qfNr6Oo/Rxx2ALXWclPe4cduqQiy49P+ZnzVJURCt2sYe1vhdmzbguuvMFDX3evq249SRAeIv1D85ShHKeEVmZKo8iZ6yl5MxuDGoS4uHxxBwuraKbtgKRgjal7Mc3sErQND+EWyzOvDHEYyb5ZVQ1qHr0Egfdy6ub6/PJp4+NC4CKMWLeU3G+vU0iXZrBb9AWu5zunVE4DaurD48GIKmRcVa0qqWFbtHzVD1WXX0OFDsyFoJvldLtDeV1AEXzXrXi43pLP5MiGBeSajIHmxJ3uNZoca1rGVfdlTjbMmS6isC9OPswfRhfTMZ/2OXtDwtRF+UX5T3FiBz+1nePBs3p4nZipGubYe6GvM0PpzBHQLHVVue0NdjmYqsRUS7E04mqizZ+fPOTgp36CqqkWEfvsnJde2wFMdU90gx7AauqPZI9v3Unp2efppPpX5lj95y9YaxWHN5nofmdBTqX9eWf5bo9BUGkm4i495h4T6BcLzbLddgrmIY+SwnzR/d7rQvJ+z3icRrHODNLOL9lL3C/937YQ/oGG+7suDHPr7DIcbrSJIuj9xfZoOu6wx5+bnIpIfgjlTWJ/wA)

All of these seem plausible on desktop but don't produce useable results on the iPad, so we might have to scrap the range reduction idea.

**Comment by likangning93** [comment]
A good thing to have might be minimal proof of the iPad's float texture misbehavior, it'll at least help if we try to report this problem to Apple.

**Comment by likangning93** [comment]
I think I have to put this aside for a couple days at least, here's a few more notes for picking this back up:

**last resort**
* spherical texture coordinates work fine, they just won't look good for small areas
* we can add a fallback for this if nothing else works

**Two more ideas to try**
* alternate packing method - go so far as to encode each float into many integer groups of sigfigs
  * `-6123456.789` -> uint8: `[-61, 23, 45, 67, 89]`.
  * inefficient, also encode/decode possibly expensive which is probably why this isn't widely used for packing textures and stuff, but we'll be doing reads/decodes in the VS from batch table
  * probably lots of other caveats on why you wouldn't want to do this for generic floats, but for us we know that they're distances in meters, >= Earth max radius, and only need accuracy to 2, maybe 3 decimal places
  * this is also just a fallback, Apple may yet fix this too

* tweak `Cartesian4.packFloat` and `czm_unpackFloat` specifically for iOS
  * observe that there's a "bias" in here
  * these functions already behave differently on Intel/Linux and Nvidia/Windows
  * maybe we can tune for iOS

**Comment by likangning93** [comment]
Pointed out by @mramato: https://www.khronos.org/webgl/public-mailing-list/public_webgl/1703/msg00036.php

It's nice to not be alone

**Comment by likangning93** [comment]
A lot of users have been running into this and #6735 lately, because Cesium currently uses materials for GroundPrimitives to batch corridors when it detects the required extensions and many users consider corridors to be a legacy "fallback" for polylines on terrain.

For now we should disable both polylines on terrain and materials-on-GroundPrimitives on mobile, this way any legacy fallbacks will still work.

**Comment by Spec1alFx** [comment]
I'm one of this users;
just one detail: I found that clamped to ground polygons (corridors, rectangles and so on) are not displayed on modern devices BUT are working on my old Galaxy Note 3.

Question: polylines on terrain are a very useful (and wanted) feature and are working on mobile (although with some graphical glitches when camera is too near or too far). For my use cases it would be better to be free to choose between polylines on terrain and corridors than disable the first ones at all.

Thank you!
