### ISSUE TITLE
Scene mode button disappears

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#6747]
![scene_mode_button_disappears](https://user-images.githubusercontent.com/1494815/42000949-6774ae9a-7a30-11e8-87af-755955bd22f9.gif)

**Comment by hpinkos** [comment]
This seems to be a chrome issue, this button hasn't changed in forever.  And it works fine in firefox.

@emackey any ideas?

**Comment by hpinkos** [comment]
I haven't seen this in a while
