### ISSUE TITLE
GroundPolylinePrimitive doesn't render on 3d tiles

### ISSUE THREAD

**Issue by chris-cooper** [AnalyticalGraphicsInc/cesium#6748]
It's great to see the progress on ground polylines @likangning93!  Are there plans for them to render on 3d tiles, like `GroundPrimitive` with `classificationType` set to `BOTH`?

**Comment by likangning93** [comment]
We're planning on adding support: https://github.com/AnalyticalGraphicsInc/cesium/issues/6636.

Polylines on terrain depend on the depth buffer, as do materials on ground primitives.
The depth buffer doesn't include information for 3D Tiles yet, which is the main reason this doesn't work right now.

Another problem is that the current implementation won't allow users to, say, draw a square on a vertical wall or only on the bottom side of a highway overpass, but maybe that's not something that comes up much.

**Comment by chris-cooper** [comment]
Thanks for the info @likangning93 ! Yes those uses cases are less common for our applications too.
