### ISSUE TITLE
How does the 3D earth disappear

### ISSUE THREAD

**Issue by m7567** [AnalyticalGraphicsInc/cesium#6749]
Hi,

In my project , the background 3D earth is not always there, sometimes it is disappeared. How to fix this?

**Comment by ggetz** [comment]
Hi, @m7567, we'll need some more context here. Please ask the question over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev) and include screenshots and/or a code snippet showing the problem using [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases).

There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
