### ISSUE TITLE
Cesium.ScreenSpaceEventType.LEFT_CLICK problem

### ISSUE THREAD

**Issue by safa833** [AnalyticalGraphicsInc/cesium#6750]
var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
    handler.setInputAction(function(movement) {
      var cartesian = viewer.scene.pickPosition(movement.endPosition);
      console.log(cartesian);
    }, Cesium.ScreenSpaceEventType.LEFT_CLICK);

I want to get cartesian coordinate in the above code but It shows "Uncaught TypeError: Cannot read property 'toString' of undefined". In contrast,  No problem in MOUSE_MOVE

**Comment by hpinkos** [comment]
Hello @safa833, use `movement.position` when using `LEFT_CLICK`.

If you have any follow up questions, please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
