### ISSUE TITLE
modelMatrix breaks height and extrude

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#6758]
This bug came out of this [forum thread](https://groups.google.com/forum/?place=forum%2Fcesium-dev&showsearch=true&hideforumtitle=true&fragments=true&parenturl=https%3A%2F%2Fcesiumjs.org%2Fforum%2F&theme=default#!topic/cesium-dev/Pczi40rEgQw).

[Here is a sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=nVRdT9swFP0rVl9wpMhN6RBbV9CgowNpDAQdm7ROk0luW2uOHdlOaYb473PsOP0A9rCqD7m+91yfc+zrJVVoyeABFDpCAh7QCDQrc3Ln1vBe6sKRFIYyAWovej8VS4vRKQiwEI8lLrQpn5SKzZmw2abZiCpjv6jok5mS+UeYKwCNe0mfHB4eHB7EPdJP9t+9Dc0LyYTRFv9jg9G6CU5iZP8oieKpQFu/l+sP/gfQr0HRTyfK08plBvySGsVWa20+fkPykhtW8Oq0migqNKeGSYH9dk2pS8ykyjUBqs0XqcziazGRY7aCbKxoDtg7F2j+S33yQlHDBUdTEbWHYcKukF23vtay7BrmYLzbSM4a26NH3/cZjhSlXuBXZbsivOFR7BvGr8iIoprjU6A5B5mDUdX2NbyWvJpL8alJ4oZb4ZfPGSiq0kU1eAHTJvEzJcG6JVg2q7HNUIMGLR7UhdCGihRGkkt1UhRAVR2Su7Obydn3X+Orm8uTSdNkAWy+MAOUkKTXLMHKqDKD7NylbOd+YpWuj4Q17be1BpFh8yC2dWbQfjb7UGN9vi+tozb3GK52WpNey3EadnufBKQbSFeCN+vJt/OLyVnkWz615N2Yk0KxnBm2BE1oluFN60Nml3vYtyYa1AcRrb1o+xhfPQb8uJ5id7a8tLxqn2eUa2hIRzXrtee6WIDacfxUliJjYn7rcs3wxagH++4l8k9baudSUVJHO/W+ZV3aiTtDbSoOx37zDywv7HSjUnFMSNdAXtgHAXT3vkx/gyGp1jVs2A2gYcaWiGVH087OgzvtoJRTrW1mVnJ+y/7AtHM87Nr6LRiXtGZ2Za80p1Vdsugdf/aLhJBh14bPUUZKfk/VRse/) for putting a polygon (approximately) on the surface with an extrude of 30. This is done without a model matrix, by manually transforming the points before passing them to the geometry.

This is correct, and looks like this:

![correct polygon](https://i.imgur.com/kbDZa5j.png)

[Here is the same example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVRtT9swEP4rUb/gSJHb0iG2rqBBRwfSGAg6NmmdJpNcG2uOHdlOaYf473P8kqYFJq3qh5zvnrvnufN5SWS0pPAAMjqKODxEY1C0KvCdPUN7qTXHgmtCOci9+P2MLw1GpcDBQBwWW9O4nFNIuqDceH2yMZHafBE+wHMpio+wkAAK9XsDfHh4cHiQ9PGgt//ubUheCsq1MvgfLUabJKiXROYf9XCvHyczHm39XoYcBMz/AAY1KP5pdTlmhciAXRIt6Wojz9lvcFExTUu2Pl1PJeGKEU0FR66cD7WOuZCFwkCU/iKkzr+WUzGhK8gmkhSAXPMCzX81oPdCkOeC4hmPm3noUBWy66a1tSxzhhho1/BIzH3n40eX9xkOl5XK0auybRBq9ShxCZNXZMRxzfEp0FyAKEDL9fZNvBZsvRD8k3ciz610x+cUJJFpvh6+gGmcyOvy/VqCobCaGGFER8MGBPKCK014CmPBhDwpSyCyNvHd2c307PuvydXN5cnUJ8mBLnI9tLfQH8FKyyqD7Ny6TOZBz8jbzIH69NsCg7JQPChs2jFsPn2dVoeHbcO7iTbGfWW6bKCP4bqntaaNWitxt/RJQNo9tSGoHY+/nV9Mz2KX8qnRZrcfl5IWVNMlKEyyDLXHETy70kLdmmhoThDRdD/aHu2rU0KPm822N5dVhlc9hjlhCjzpuGa9GYkqc5A7AzkVFc8oX9xan1/IJOrDvn2g3IuXml2VBNfWTrxLWYd2ks5I6TWDY1f8Ay1Ks/FRJRnCuKuhKM0jAap7X6W/QeNUqRo26gbQKKPLiGZHs87OOzzrRCkjShnPvGLslv6BWed41DXxWzAmSM3sytx4RtZ1SN4//uwOMcajrjGfo7QQ7J7IVsa/), except I pass the pre-transformed points and the modelMatrix instead.

The result is incorrect:

![sailboat](https://i.imgur.com/NIqZPTT.png)

As exciting as it is to think about using the earth as a giant sailboat, I think this is a bug. The expected behavior is that both of these examples would produce the same result. The specific case in the thread was to use the modelMatrix to create many geometry instances, all using the same geometry, and shifted around via a modelMatrix.

**Comment by hpinkos** [comment]
@OmarShehata polygons are not meant to be used in that way, so this is expected behavior.  When the polygon is created, the positions passed in are projected onto the ellipsoid surface.  If you remove the model matrix from the second example, you'll see the polygon draws like this:

![image](https://user-images.githubusercontent.com/3451886/42172872-5a04fd82-7deb-11e8-8eeb-5b7ae491a25a.png)

**Comment by OmarShehata** [comment]
So then, what is the correct/recommended way of constructing an extruded polygon as seen in the first image?

**Comment by hpinkos** [comment]
@OmarShehata probably with the method used in the first example
