### ISSUE TITLE
I can't open "3d Tiles Feature Picking" sandcalsle in IE 11, Edge

### ISSUE THREAD

**Issue by kladess** [AnalyticalGraphicsInc/cesium#6759]
I can't open "[3d Tiles Feature Picking](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Feature%20Picking.html)" sandcalsle in IE 11, Edge (42.17134.1.0) but FireFox and Chrome was opened.

sandcastle's console log was printed: 
> Object expected (on line 3601 of https://cesiumjs.org/Cesium/Build/CesiumUnminified/Workers/decodeDraco.js)

**Comment by mramato** [comment]
Thanks for reporting @kladess.

@ggetz this appears to happen in master as well (at least the deployed version): http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Picking.html

Perhaps it a built Sandcastle/deployment issue?  Either way, I'm tagging this so it gets fixed before today's release.

**Comment by ggetz** [comment]
It looks like the `decodeDraco` worker is running into an issue with requiring the draco module, only in the built version, in IE.

IE doesn't support wasm, so it's falling back to the JS module.

**Comment by mramato** [comment]
Are we failing to copy something to the expected directory?  Or perhaps it's a module path issue similar to the buildModuleUrl fixes we just did for approximateTerrainHeights?

**Comment by mramato** [comment]
Perhaps we need to wrap the three paths at https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/DracoLoader.js#L34 in `buildModuleUrl`?

**Comment by ggetz** [comment]
It doesn't look like anything is failing to copy, it's still failing locally.

We're already wrapping it in `buildModuleUrl` here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/TaskProcessor.js#L181

I'm checking if changes need to be made after the adjustments we made for approximateTerrainHeights
