### ISSUE TITLE
JSDoc: Support natural syntax for function declaration

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#676]
JSDoc currently requires us to use syntax like this to declare a constructor:

```javascript
var Foo = function(args) {
};
```

But this syntax makes `constructor.name` blank, and gives us a less useful call stack.  We'd like to modify JSDoc to work with this syntax as well:

```javascript
function Foo(args) {
}
```

**Comment by mramato** [comment]
@shunter and @kring, I just verified that JSDoc supports this syntax by changing `Cartesian3` and building the doc, everything worked as expected.  We can definitely close this issue, but the main question is whether we want to update all existing source files to use it?

**Comment by mramato** [comment]
I'm going to close this and I'll just open a PR for the sweeping change if we decide we want to do it (it's a simple regex find and replace)
