### ISSUE TITLE
Starburst Sandcastle example looks odd in 2D/CV

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6764]
![starburst_cv](https://user-images.githubusercontent.com/5395255/42184728-83008ab6-7e14-11e8-8b82-836113a25b06.JPG)

At least as far back as 1.46: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Star%20Burst.html

**Comment by hpinkos** [comment]
duplicate #4877
