### ISSUE TITLE
can't handle dblclick on touch devices

### ISSUE THREAD

**Issue by Joyzen** [AnalyticalGraphicsInc/cesium#6771]
i can't catch double click event if i click screen twice through finger.

**Comment by hpinkos** [comment]
Hmm, I thought this used to work but I can't double click on a touch screen either.  @emackey this should be handled by the `ScreenSpaceEventHandler`, right?

**Comment by emackey** [comment]
No, double click is a desktop only UX pattern.  There's no such event as
double-touch, and mobile users typically don't try that gesture as it's not
hooked up to any OS level event.  In the case of desktop, the OS itself is
in charge of configuring the acceptable click delay, so Cesium doesn't know
the allowed time difference there and just watches for dblclick events
directly.

Sorry!
