### ISSUE TITLE
VideoSynchronizer tests failing on travis

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6772]
These tests seem to be failing in all branches.  They did pass when I ran it locally.

```
  Core/VideoSynchronizer
    ✗ Syncs time when looping
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
	    at <Jasmine>
    ✗ Syncs time when not looping
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
	    at <Jasmine>
```

https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/399783058

Possibly related? #6765

**Comment by hpinkos** [comment]
@mramato any ideas?  Should we just `xit` these tests for now?

**Comment by mramato** [comment]
Feel free to temporarily xit these, but we should look into it before the next release.

Chrome recently decided to break the web for auto-playing content (I expect other browsers do not have this problem).
