### ISSUE TITLE
Add HeightReference to more geometry types

### ISSUE THREAD

**Issue by z3214965** [AnalyticalGraphicsInc/cesium#6777]
BoxGraphics、CylinderGraphics、BoxGraphics not heightReference property，I want the position height is the height above the terrain，What should I do？

**Comment by hpinkos** [comment]
Hi @z3214965, for the first round we only added `HeightReference` to `CorridorGraphics`, `EllipseGraphics`, `PolygonGraphics` and `RectangleGraphics`.  However, we should be able to expand this to include the other geometry types in the future.

I'm not sure how soon I would be able to add this feature, but if anyone has time to open a pull request I'd be happy to review it!
