### ISSUE TITLE
Moving the camera eventually crashes (if you're unlucky).

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#6783]
Brought up in this [forum thread](https://groups.google.com/forum/?place=forum%2Fcesium-dev&showsearch=true&hideforumtitle=true&fragments=true&parenturl=https%3A%2F%2Fcesiumjs.org%2Fforum%2F%23!msg%2Fcesium-dev%2Fq1VNQE3qhd0%2F3mT5jr-rBwAJ&theme=default#!topic/cesium-dev/LSPZK_AlqyU).

Try holding ctrl and rotating with left mouse click in this [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVLBTuMwFPwVKxdSKXIaoNK2hApRDhyQOID2UnNw7dfUwrEj2wm0KP+OnTRLsuRie+bNjN9zGmoQO5US3aLtF1HIfyQSnEQrv3LN6hKUI1EyUA0YK7Tq+QzPSURU69lf2mwkqrQ8Fr3oXDfgVjjvZv9jepZR43RhaHUQ7AEKA9DVbS+XeL5YJuj6Gl9lf/wmWyRoAi4vx+ByMcBXE3hA5wF9+0lvk589fDpTc+CPIIqDW6HFvOda3/XbDVGNH18j4AOMH6CCD7QBK+oS/+2w+IJ1x41WjgoF5uJsPerVvh/v9ecK7am0MEoupN7BFG5n58TKh52DNv7tHqijL7o2DLDUlMfhPUNphd0BVLyvFQtTRrGZoS/E/Ly1DKVFANqZ9+xui/k/H4sp53HV5fXcSevyVQcoSqLcuqOEdX+rO1FW2jhUGxljnDooK0kd2HRXs3dwmFkbfPJ0EOVcNEjwW//C0+mQCDFJrfXMvpbyRZyAROs89fUTWWhSqOLZ/4uSHkPJIVs/9SDGOE/98bfKaS131IwcvwE). If you get the camera in just the right position (the origin), you'll get:

```
An error occurred while rendering.  Rendering has stopped.
undefined
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:540:19)
    at Function.Cartesian3.normalize (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:8132:19)
    at rotateVertical (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:186217:28)
    at Camera.rotateUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:186208:9)
    at rotate3D (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:231295:20)
    at tilt3DOnEllipsoid (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:231534:9)
    at tilt3D (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:231476:13)
    at reactToInput (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:230287:21)
    at update3D (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:231807:9)
    at ScreenSpaceCameraController.update (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:231840:13)
```

You can see a [video here](https://gfycat.com/ThatDelectableAgouti) (I'm just moving my mouse in clockwise in circles and holding ctrl).

Just putting the camera at the origin will also trigger this:

```
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.camera.setView({
    destination : new Cesium.Cartesian3(),
});
```

**Comment by mmacros** [comment]
Also if you move the camera fast, looking underground and above ground, the renderer crash, showing the following error.



![captura](https://user-images.githubusercontent.com/1498693/43137040-ff3f2a2a-8f20-11e8-808f-0815ab8d625e.PNG)

**Comment by OmarShehata** [comment]
Came up on the forum [here](https://groups.google.com/d/msg/cesium-dev/ku9822o-t8I/iEqGNEPdBgAJ).

**Comment by esparano** [comment]
I've been seeing this problem for about 2 years now, actually. I can reproduce it pretty reliably. Here's the updated line numbers for developers:

![image](https://user-images.githubusercontent.com/3947139/49883164-19bbe700-fe00-11e8-8567-75f89ad572ed.png)

**Comment by just-a-user-or-something** [comment]
I am seeing the same stack as @esparano:

Developer Error: normalized result is not a number
normalize
rotateVertical
rotateUp
rotate3D
tilt3DOnEllipsoid
tilt3D
reactToInput
update3D

**Comment by hpinkos** [comment]
Also reported by @mholthausen in #7858

**Comment by OmarShehata** [comment]
Reported on the [forum today](https://groups.google.com/d/msg/cesium-dev/c6-oUcHFUik/yBSWhdmFAgAJ) as well.

**Comment by OmarShehata** [comment]
From the forum posted mentioned above:

> Hi Omar,
I found another commercial website, John Wayne airport, using Cesium and had similar runtime error. You don't have to do any out of ordinary. You can just keep zooming with the mouse wheel until the camera passes the ground then try to look up to the sky from that position, the app crashed.
http://jwaflighttrackviewer.airportnetwork.com/
I think this issue needs to be elevated to be fixed ASAP.
Thanks for your wonderful contribution to the Cesium community!
Hoaininh

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/ku9822o-t8I/iEqGNEPdBgAJ
https://groups.google.com/d/msg/cesium-dev/c6-oUcHFUik/yBSWhdmFAgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/6783 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
