### ISSUE TITLE
Model bounding sphere wrong after forward axis conversion change

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6784]
Compare "Milk Truck" ( a 1.0 model) and "Draco Compressed Model" (a 2.0 model) in the 3D Models sandcastle. [1.47](http://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Models.html) vs [1.46](http://cesiumjs.org/releases/1.46/Apps/Sandcastle/index.html?src=3D%20Models.html)

In 1.47 the pivot point is slightly off.

Removing these lines fixes it, but I haven't looked around enough to know why. Similarly placing them above the other axis conversions works. @emackey would you be able to check this out?

```
if (model._forwardAxis === Axis.Z) {
    // glTF 2.0 has a Z-forward convention that must be adapted here to X-forward.
    BoundingSphere.transformWithoutScale(boundingSphere, Axis.Z_UP_TO_X_UP, boundingSphere);
}
```

Noticed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6559

**Comment by emackey** [comment]
The transform is needed, but was being applied in the wrong order.  PR incoming.

**Comment by emackey** [comment]
This sample file can be used for testing:  [OffsetCube.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2194062/OffsetCube.zip)

It is a cube that is offset from the origin by different amounts on all 3 axes.  It won't be shown in the center of the view if you just comment out the Z-forward transform.  The transform has to be applied in the correct order to center the cube properly.
