### ISSUE TITLE
Cartesian3 use teme or ecef or other

### ISSUE THREAD

**Issue by Carolineliu** [AnalyticalGraphicsInc/cesium#6785]
Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by ggetz** [comment]
Hi @Carolineliu. Yes, `Cartesian3` objects without any transforms applied use ECEF. 

Generally, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
