### ISSUE TITLE
Do you have other controllers besides ScreenSpaceCameraController?

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#6786]
When dragging the map, I want the map to rotate around the mouse point. And when zooming the map, I want the map to zoom around the mouse point.

**Comment by ggetz** [comment]
Hi @hieeyh,

You can modify the events that trigger specific functionality in the [`ScreenSpaceCameraController`](https://cesiumjs.org/Cesium/Build/Documentation/ScreenSpaceCameraController.html) itself, or you could add event listeners to the events in the [`ScreenSpaceEventHandler`](https://cesiumjs.org/Cesium/Build/Documentation/ScreenSpaceEventHandler.html) class and then [move the Camera](https://cesiumjs.org/tutorials/Camera-Tutorial/) accordingly.

Also, we prefer you ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
