### ISSUE TITLE
Turning on point cloud attenuation blows up safari 11.1.1

### ISSUE THREAD

**Issue by euwest** [AnalyticalGraphicsInc/cesium#6792]
Looks like adding `tileset.pointCloudShading.attenuation = true` results in:
>DeveloperError: The color texture pixel datatype is FLOAT and the WebGL implementation does not support the EXT_color_buffer_float or WEBGL_color_buffer_float extensions. See Context.colorBufferFloat. ([source?](https://github.com/AnalyticalGraphicsInc/cesium/blob/dbc671006507a78ceade01e9f3943a550e217862/Source/Renderer/Framebuffer.js#L171))

system specs:
![screen shot 2018-07-10 at 4 42 45 pm](https://user-images.githubusercontent.com/6263840/42543357-6268acaa-8460-11e8-880b-ad851dd2a0a1.png)
![screen shot 2018-07-10 at 4 43 02 pm](https://user-images.githubusercontent.com/6263840/42543358-6280a06c-8460-11e8-8d46-6827fee06c61.png)

Easily duplicated in [sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=XZLNjtMwFIVfxcpmEhScQkGgNlMBZcFISFTTEatsXPu2sXDujfyTKoP67jhNMlC8sexzPt3jkxQF29EZLNsZgZ4pcPqErCEFhrWWOq1AsUPPvgB6Az3b985D4yrshGWdhgG9Zwhnto1oaPjP6116J6/HLaEXGsHeZesKR8prAw78LTZuy69Po5j+rpDF1ZJGvzUU1L4WSuNpxSZlWMJ7wCC8JlwxbwPko3aZ9mDNah7wQPgIjoKVwI+Wms8ujnlQ6fLj8kNW4WXMN2XjFoTqd9GmHXBfA6bHgHIYlE6WbA4ylsCdBATeWt1orztwXCj14l3fWJ+JmieaxfzfGr7B9ZU77WX9KPAE6YK/z9nrBX+bz8XxAwUcXPu2BgvcRiQ49oq944tsGHXJOMXM9hzD/80N1pJ9SS0JHRnghk6Tsp5KSPKkdL43sBmdn3TTkvVDmSnnRfz6rREeXHEI8ldMI50bsLKYoVLpjml1XyX//QNVwqQRzkXlGIzZ62eokk1ZRP8NZuhawo8OrBH9YKnfbL6Pl5zzsojHmfoD), which appears to be using 1.47. I've also tried 1.46.1 and had the same issue.

![screen shot 2018-07-10 at 4 30 37 pm](https://user-images.githubusercontent.com/6263840/42543042-cd22c62c-845e-11e8-8418-1865e71e9b6c.png)

**Comment by hpinkos** [comment]
@likangning93 any ideas here?  Is this something that's not supported and we need a flag for or is this a bug?

**Comment by likangning93** [comment]
I'll take a deeper look soon. It's definitely weird that this is happening when applying point cloud attenuation on a non-point-cloud tileset though.

**Comment by likangning93** [comment]
From a quick look though, this might just be an extension that we need to check for.
