### ISSUE TITLE
Fail tests gracefully if browser zoom is not 100%

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#681]
Since tests in the WebGL category generally render to a 1x1 canvas, if the tests are ran with the browser zoom less than 100%, the WebGL tests can fail because the canvas can be scaled to 0x0.

It is reasonable to just provide a precise error message that the tests require 100% zoom.  This work was started in the [testcanvas branch](https://github.com/AnalyticalGraphicsInc/cesium/compare/master...testcanvas).  The remaining work is for `beforeEach` (part of the Jasmine test framework) to propagate the error.  Alternatively, this check could be placed elsewhere.

This issue is completely separate from being able to scale the Cesium widget canvas for performance improvements.

**Comment by mramato** [comment]
I recommend we just close this. It's really low priority and (as far as I know) has had zero affect on our development..

**Comment by pjcozzi** [comment]
Agreed, the tests still fail, but this hasn't caused a problem in practice in years.
