### ISSUE TITLE
pickPosition broken when point cloud tileset added to scene

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6814]
This works in 1.47 but is broken in master.  @lilleyse @ggetz 

`pickPosition` randomly returns `undefined` if this point cloud is added to the scene.  I set `show: false` for the point cloud in this example because chappes grinds performance to a hault, but the issue happens either way.  It does not happen when there is no tileset in the scene.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var position;

var moveHandler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
moveHandler.setInputAction(function(movement) {
    if (position) {
        var p = viewer.scene.pickPosition(movement.endPosition);
        if(Cesium.defined(p)) {
            position = p;
        }
    }
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);


function getPosition(time, result) {	
	return position;    
}

var tileset = new Cesium.Cesium3DTileset({ url: Cesium.IonResource.fromAssetId(3838), show: false});
tileset.readyPromise.then(function() {
    position = tileset.boundingSphere.center.clone();
    viewer.entities.add({
        position:new Cesium.CallbackProperty(getPosition,false),
        billboard:{
            image:"../images/Cesium_Logo_overlay.png"
        }
    });

});
viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset);
```

**Comment by hpinkos** [comment]
@lilleyse we want to fix this before the release goes out.  What's the plan?

**Comment by lilleyse** [comment]
I'm hoping to look into this sometime this week.

**Comment by mramato** [comment]
Just a reminder that the release is this Wednesday.  We should really try and get all showstopper issues addressed by the end of today.

**Comment by lilleyse** [comment]
This might be a situation where we have to pick which bug is most tolerable:

* Don't render the depth plane before 3D Tiles: tileset may show on opposite side of globe like [this](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVJda9wwEPwri1/ig6vsayiExjka0kIDhYb06JMh6OS1vVTWGkm2uYT898p2fL1L9aCvnZndHSlJ4Lb0aMHXCE6hQdAsCwcN9whKNmgleAZuW3bkA4YKBC6h0rxHAbtAa5mMdzCQ1uBqHoKW5a6qRW56aaEnHEKCGzA4wB066hrxe7qLL9R0vGPjJRm0F6vrmeNJo0N/TpqXy6+7ORi/QGf15yV6z+YRHXdWoSgtN7cuYO6L+PLq6uMKXiflKauY2hStpYY89eiELIr4LeMJ7Jm52fESWJ9W8h1lQaZ6IK/qR2kqjFORruHDZpw/hf1q1MnNG1fYgD88hKLIoQhOm7jsjPLE5pgXXnIDYSyUpwq5QW9JfbOWR/s26TJEej2DBzIFDyLgd9Qgd/6f7lHwTNQyh1kFv9GEzfRyv+gZZ/mj7uvYRTr2MPkWraPM+YPG7Rz+Qk3L1o/2x0IkHptWS48u2XfqT0ijnBtpWbKQsoJ6oOImj949eB6B0tK5ECk7rcdS8mibJQF/Rhv/ZDD8Z49Wy8MIqTfbH/OlECJLwvF/lmfWe2lPFP8C)
* Render the depth plane before 3D Tiles
    * Don't apply an offset to the depth plane: get classification artifacts.
    * Apply offset to the depth plane: picking the depth plane produces bad results - this issue


https://github.com/AnalyticalGraphicsInc/cesium/pull/6779 is easy to revert - I just want to know what people think about https://github.com/AnalyticalGraphicsInc/cesium/issues/6814#issuecomment-409059691.

Classification bug:

 ![classification-bug](https://user-images.githubusercontent.com/915398/43431016-e34e78fc-9439-11e8-9353-7e495f5a1f92.gif)

**Comment by hpinkos** [comment]
@lilleyse I don't understand why we have to choose one or the other if both worked in 1.36

**Comment by lilleyse** [comment]
1.36 was right before classification primitives were added. Going back to the 1.36 behavior results in the artifact above.

**Comment by lilleyse** [comment]
In that situation the depth plane is rendered after 3D Tiles to get around those 2 other bugs, but still before the opaque/translucent pass that all other primitives use.
