### ISSUE TITLE
Clamp to ground stops working with a large number of entities

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6818]
![image](https://user-images.githubusercontent.com/3451886/42952203-f5159fcc-8b45-11e8-8208-469b462bb295.png)

This happens after toggling terrain off.  The ground clamping is not updated for the new terrain provider.

[Sandcastle Example](http://localhost:8080/Apps/Sandcastle/index.html#c=7VZbU+M2FP4rGl4IxSh2Yjt2yDKlQLudYQsD6fZhs7Oj2CeJqGJlJDk0y/Df98iX2Akw5aGP9Ysv+r5zvnOTvGaKJKB5vhyDUoxnt0queQqKfCAXxXeaKGAG/pJKpBWmc3Q6ydbIBCH4SkueviRn8FgbuHoDVZgpDa05PO7TPhffOoelvAuZGeSCOnTI0yQjeE2Zhmu2AXXLk7+RPSQzJjQ45arZkzR8Pc5J9lxEUzijOoEM6FzIKdAUVmYxBm3O54jXpiKiSKNyKKTfsyxNmDYCKEvTsZRiytQnyPLOl6daxT8GXR/W5KuMTQWkh5VImWkQkFjILM8SwyUmt47PXju6zIssvxrSaUl/xtC2udrXccn1fyrkrU5oafl69HbOfsmNQY+Hv4oNGUvMkuGGg8Zav1RTKUnYEhSjM7EZy05LaIoV4xmzHAym1U8XTBl8Ylm/4/tu7Loejfo9z/U9Lw4cEvQ9143pwPMGcej74cAhfhDGUexTXOl5vcHADY6cxpFUHLAnK0ctBfZaAEt5Nh+SPvXi/iAKB72+F8XoytkFrrhJFkNy4tJ+2I+CKPDDXuR6bhzuAZUUYkhC2ot6cRx5A8+NYheVN6jnFiPNVa0soG5VBFuA53dU4R4MsdP33lKUTVEVRIOx3P9LUvX9fubtdidkNucmTwEnJ6RR4IZegGEhO+h51d4qMIwK4gc0ilFFEMVx7EdRWEFSEIbhuksxc4XxukQEi1pUbtPhDnloCoasR6wGkhoNx5Whnwg/bWDA3obVzy24lrlZWHwtu4E/tGCZVG/CWlYbAmsOoqZb6EzJ5SXMFYDu2Hic0v9Ry9P0ncRCUZuY/CvRpuYVYvpO4lZqQ11JzW3dNJr4whwydUjikPRrAyonDapptEPbnrCVFJv5q03PcSZVstjg0tbJXhsv8XhXnAmE1PKlkKpQfof7hFx2nphYLRgCvOcjZ3+s+Hxhzw0f2/DVtTuYgYIsgcbBx90Fend1fT7+/fPVt/HNt9/ubv7843LPEh5fCtsl/Vh7e+lsF/IOpxfX559uG487U9ueW/vW7ZLyPwizlW3qfGtiFswQpoBoPO1OppsTe8c5lIp0bGG5Hc9TvI1IYO/Hx9tZ3GIeSsxDhXloYey1N8qtE/XAORhpsxFwVn77mS9X2JQkV6JDadfAcoVzBro7zfEHydBEa0sfdWvSKOVrwtMPk4O9n6zJAUkE0xpXZrkQ9/w7TA7ORl3E79CELPbUmzUowTYWsvDOrsuPlNJRF19fskx53LQs/gA)

**Comment by hpinkos** [comment]
Alright, it looks like this is an existing problem with our clamp to ground logic.  Billboards do the same thing.

![image](https://user-images.githubusercontent.com/3451886/42958957-27585646-8b55-11e8-9411-d0298c1b6066.png)

**Comment by hpinkos** [comment]
More issues: 

![image](https://user-images.githubusercontent.com/3451886/42968254-c7432080-8b70-11e8-9866-d24581a8c982.png)

This seems to only happen the first time the example is loaded.

**Comment by mramato** [comment]
> This seems to only happen the first time the example is loaded.

A race condition because the terrain isn't cached?  Might happen every time if you disable caching in the debugger.

**Comment by mramato** [comment]
So one weird thing I noticed here is that even if Cesium loads X levels of terrain tiles (and the terrain is done loading) we still trigger updates for every tile rather than just the ones at the most highest loaded layer.  I don't think this has anything to do with the terrain engine and is specific to the terrain clamping sync code.  This is why it takes several "passes" until the polygons are correct.  We could probably speed this up tremendously by skipping items in the queue that are out of date.

**Comment by hpinkos** [comment]
Actually, maybe I was on a different branch.  I tried again like 50 times in master but doesn't reproduce that error anymore with my fix.  I'll close and reopen it if I see it pop up again.

**Comment by mramato** [comment]
I think you're right because I couldn't reproduce it either. :crossed_fingers:

**Comment by bmckilligan** [comment]
For what its worth 

I have been experiencing a lot of issues with terrain and clamp to ground, much of it is hardware related.

I am working on an older Thinkpad T520 running Windows 10 64-bit which has an Intel HD Graphics 3000 and an NVIDIA Quadro NVS 4200M

The Geometry Height Reference example doesn't work in Chrome or FireFox by default, using the Intel GPU

The polygons in the example initially render above the terrain but after render passes as terrain tiles are loaded, the polygons disappear under the terrain.

I can configure Firefox to run using the NVidia GPU, and the height reference example works.

I have also been experiencing with the Chrome Intel combo a lot of issues with billboards rendering under terrain after terrain updates.  Especially if there are more then a few thousand entities loaded with billboards and labels, in that instance I am looking at switching to points.

I've tried to put together a sandcastle example but it seams to be hit and miss when trying on different hardware, I'm in Vancouver and am going to try and attend the BOF at SIGGRAPH 2018 and can show things there

**Comment by hpinkos** [comment]
@bmckilligan the logic that updates billboard clamp to ground and geometry clamp to ground is the same, so it makes sense that you see problems with both.  Also, based on the notion that I'm pretty sure this is a race condition, it also makes sense that you run into this frequently on your older less-perfomant computer.

Thanks for the extra input!  I hope to get this figured out for the September release.  I won't be at SIGGRAPH personally, but a lot of the team will be =)

**Comment by icemagno** [comment]
Can you share the code to create this nice effect?

**Comment by calogeromauceri** [comment]
I am experiencing this issues very often, mostly when the tiles are not cached and retrieving them require more time
