### ISSUE TITLE
How the billboard rotation can not be affected by the map rotation?

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#6825]
When I create a billboard, and then rotate the map from a touch screen, the billboard rotation is not steady, it always head to up screen.What I need is that when I rotates the map, the billboard heading will not change.
I have used allignedAxis property, but it cant achieve the effect I want.

**Comment by hpinkos** [comment]
Hello @hieeyh, we do not currently have support for billboard heading.  See this issue: #6165

In the meantime, using `alignedAxis: Cesium.Cartesian3.UNIT_Z` is your best option.
