### ISSUE TITLE
Geocoder is not working if I provide true value explicitly

### ISSUE THREAD

**Issue by SurajitChowbey** [AnalyticalGraphicsInc/cesium#6826]
Geocoder is not working if I provide true value explicitly.

Please take a look on the following code:

Not working example:
`var viewer = new Cesium.Viewer('cesiumContainer',{
    geocoder: true,
});`

Working example:
`var viewer = new Cesium.Viewer('cesiumContainer',{
    /*geocoder: true,*/
});`

**Comment by hpinkos** [comment]
Thanks for reporting this @SurajitChowbey!  We currently expect either a `GeocoderService` or `false` for the `geocoder` property, which is confusing.  We either need to update the documentation to reflect this, or use a separate property to set a custom geocoder service.

@mramato do you have an opinion here?  I feel like overloading the `geocoder` argument in this way was the wrong decision and we should have `options.geocoder` be a boolean and add `options.geocoderServices`.

**Comment by OmarShehata** [comment]
A better solution is to remove `geocoder` and just have `geocoderServices`. If it's defined then the feature is enabled, just like with `imageryProvider` and `terrainProvider`.

**Comment by mramato** [comment]
> @mramato do you have an opinion here? I feel like overloading the geocoder argument in this way was the wrong decision and we should have options.geocoder be a boolean and add options.geocoderServices.

I believe this mirrors similar SDKs at the time it was written, but it was so long ago I don't remember for sure.  I would recommend just handling the case where the value is `true` and call it a day.  This has never been a problem before and it would create an immense amount of churn to change because all of the Viewer options follow this paradigm.

**Comment by mramato** [comment]
> A better solution is to remove geocoder and just have geocoderServices. If it's defined then the feature is enabled, just like with imageryProvider and terrainProvider.

The geocoder is enabled by default, so it already works like `imageryProvider` and `terrianProvider`.  There's technically no bug here, it's documented behavior, but it's an easy usability improvement to make `true` work for all of the widgets.

**Comment by emackey** [comment]
In retrospect we probably should have used `null` instead of `false` back in the day, then people wouldn't have thought to switch it to true, they would understand to supply an instance.

**Comment by hpinkos** [comment]
Thanks @SurajitChowbey!  This was fixed and will be included in the Cesium 1.48 release available August 1st

**Comment by SurajitChowbey** [comment]
Welcome
