### ISSUE TITLE
entity.show not getting applied after setting entity.position

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6830]
[Sandcastle link](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dVPbjtowEP0Vi5dNJGqCwkJoAXVFqboqUqsS9SlSZZwBrHXsyHaC2Gr/vZM4sCxt/ZB4LufMzMmkZobUAo5gyJwoOJIlWFEV9GfrC+54ay61ckwoMHfhh0zViLEcFCDEY2lrYqh9073UW6A5lO6QgnUPe8Ral4IxeEGQM1WT7JkQ4W6rL5lxem9YeRA8eDek8XA6TuJJEo+TYRxFkz6J6HiaJJM4ju+no9HkfjTqkzii0bk/JBXu9NpgawuwlOV58DtTBE+pLfq0Iu//VZc63ZgYYCrwTYZ9DwQpRWm1yBHZcTXHsFwIdN0M0jLEQUwjbLF7nJmaUzCkFkxetaGlNvTH6pNPesnUS+j18sM8a12kOrgZLbxIemAql7eabrgBUJuScVjViPnik84snCG04+jw1IJ7VGXlHngjU7CrlL8UuoYCKcLz9F5tag/6iEV3TNrm+15FLlLP/ebQUvCn753zwndJCzv0UahcH5s+UlGArtxrD+G18m/rd+vVStcnwyhqtwKv/1EiPZVA16vP6a/l+nH5tUnu9Xsz604SFp7noyhKbRypjAwoHTgoSomfzQ62FX8CR7ltpZsNzqBZLmoi8nnWu/mDsh7hklmLkV0l5UY8Q9ZbzAaY/wYmNW6T2n+rwUh2alIOw8XaOymlswGaf6Oc1nLLzBXjHw)

```js
handler.setInputAction(function(movement) {
    entity.show = false;
    entity.position = scene.pickPosition(movement.position);
    window.setTimeout(function() {
        entity.show = true;
    }, 1000);
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

Setting the show to false seems to have no effect:

![show](https://user-images.githubusercontent.com/915398/43112281-4b0ed486-8ec3-11e8-8371-64243ce97a8f.gif)

With the position line removed, there is a 1 second blink as expected.
![show1](https://user-images.githubusercontent.com/915398/43112301-6b07e476-8ec3-11e8-9d07-770fdfe5c143.gif)

**Comment by hpinkos** [comment]
@lilleyse as a workaround, use `entity.ellipsoid.show` instead of `entity.show`
