### ISSUE TITLE
Every 3D Tiles Sandcastle example warns of deprecation

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6832]
Every 3D Tiles Sandcastle example warns of deprecation.  This switches the focus to the console and makes Sandcastle hard to browse.  It will also be really confusing to our end users.

@ggetz @lilleyse what are the plans to address this before the next release?

**Comment by lilleyse** [comment]
This is part of https://github.com/AnalyticalGraphicsInc/cesium/issues/6697 and will be fixed before the release.

**Comment by tfili** [comment]
@lilleyse Is this still going to be fixed by tomorrow?
