### ISSUE TITLE
Cesium render loop crashes when double clicking access line on a zoomed-to object

### ISSUE THREAD

**Issue by MattPetry** [AnalyticalGraphicsInc/cesium#6848]
The attached czml document demonstrates this behavior. Steps to reproduce:

1. Load the czml
2. Double click ISS to zoom to it
3. Double click the access line between ISS and the ground station
4. Cesium shows an error message

I've seen this in versions 1.44 and 1.47

[accessLine.czml.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/2233375/accessLine.czml.txt)

**Comment by mramato** [comment]
Thanks @MattPetry!

This looks like a clear cut bug to me on line 2022 of Viewer.js
```js
camera.viewBoundingSphere(boundingSphere, viewer._zoomOptions.offset);
```
`viewer._zoomOptions` should just be the locally scoped `zoomOptions` (which is always defined, while the former is not).

If someone wants to confirm this and open a PR, that would be great.  Thanks.
