### ISSUE TITLE
Tile debug bounding volumes clipped when EDL is enabled

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6850]
The failing commit is https://github.com/AnalyticalGraphicsInc/cesium/commit/97074e5c968de24a6a1cce57ef010c2188d34af4 part of the EDL updates in https://github.com/AnalyticalGraphicsInc/cesium/pull/6801.

Not critical for the release but it would be good to fix since it's a regression since 1.47.

`1.47`

![before](https://user-images.githubusercontent.com/915398/43295882-f9519728-9115-11e8-9cb6-89516346edba.PNG)

`master`

![after](https://user-images.githubusercontent.com/915398/43295883-f95e7150-9115-11e8-83d2-883b405abdbe.PNG)

**Comment by hpinkos** [comment]
@lilleyse I disagree. If we broke something between releases we should absolutely fix it before the next release goes out.  It's possible this broke other things too.  For example, this is probably all outlines, not just the debug boxes.

**Comment by hpinkos** [comment]
Yep, marking this `next release`

![image](https://user-images.githubusercontent.com/3451886/43326907-ff577698-9187-11e8-811a-6f49242c2b28.png)

**Comment by hpinkos** [comment]
@likangning93 make sure you take a look at this
