### ISSUE TITLE
Module not found: Can't resolve '../ThirdParty/pako_inflate' in 'E:\react\react-cesium-demo\node_modules\cesium\Build\CesiumUnminified\Workers'

### ISSUE THREAD

**Issue by iamgithubym** [AnalyticalGraphicsInc/cesium#6851]
![image](https://user-images.githubusercontent.com/16376755/43297613-fae352c4-9184-11e8-898e-ab6d08e46dc4.png)
![image](https://user-images.githubusercontent.com/16376755/43297632-0d2383dc-9185-11e8-9d8b-59b91c2b42a2.png)
please what can i do?

**Comment by hpinkos** [comment]
@iamgithubym Our team doesn't officially support the react-cesium-demo.  If you make a comment in https://github.com/markerikson/cesium-react-webpack-demo @markerikson should be able to help you.  Thanks!
