### ISSUE TITLE
Remove tile uri backslash workaround

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6868]
Revert the changes in https://github.com/AnalyticalGraphicsInc/cesium/pull/6125, which added a workaround for tiles with incorrect backslashes before their uri.

**Comment by OmarShehata** [comment]
We're completely removing this right @lilleyse ? No need to keep any warnings or anything?

**Comment by lilleyse** [comment]
Yeah go ahead and remove, this workaround was added to fix a very specific set of incorrect tilesets generated by us. Doesn't need to go through the usual deprecation.
