### ISSUE TITLE
On the cutting function of Cesium 3dtiles

### ISSUE THREAD

**Issue by miniergouzi** [AnalyticalGraphicsInc/cesium#6884]
The respected Cesium team:

I haven't found a suitable solution to whether Cesium technology supports the cutting function of the 3D tiles model. I look up the case of the official network and do not find valuable examples. The 3D tiles Clipping Planes instance is included.

**Comment by hpinkos** [comment]
Hi @miniergouzi, I'm not really sure what functionality you're looking for if it's not clipping planes.  A clipping plane will draw the 3D tileset on one side of the plane and not on the other, which results in cutting the tileset.  https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Clipping%20Planes.html

If you're able to, please ask your question on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
