### ISSUE TITLE
Can somebody give an example pertaining to QuantizedMeshTerrainData on Sandcastle ?

### ISSUE THREAD

**Issue by safa833** [AnalyticalGraphicsInc/cesium#6885]
Can somebody give an example pertaining to  QuantizedMeshTerrainData use on Sandcastle ?

> var data = new Cesium.QuantizedMeshTerrainData({
    minimumHeight : -100,
    maximumHeight : 2101,
    quantizedVertices : new Uint16Array([// order is SW NW SE NE
                                         // longitude
                                         0, 0, 32767, 32767,
                                         // latitude
                                         0, 32767, 0, 32767,
                                         // heights
                                         16384, 0, 32767, 16384]),
    indices : new Uint16Array([0, 3, 1,
                               0, 2, 3]),
    boundingSphere : new Cesium.BoundingSphere(new Cesium.Cartesian3(1.0, 2.0, 3.0), 10000),
    orientedBoundingBox : new Cesium.OrientedBoundingBox(new Cesium.Cartesian3(1.0, 2.0, 3.0), Cesium.Matrix3.fromRotationX(Cesium.Math.PI, new Cesium.Matrix3())),
    horizonOcclusionPoint : new Cesium.Cartesian3(3.0, 2.0, 1.0),
    westIndices : [0, 1],
    southIndices : [0, 1],
    eastIndices : [2, 3],
    northIndices : [1, 3],
    westSkirtHeight : 1.0,
    southSkirtHeight : 1.0,
    eastSkirtHeight : 1.0,
    northSkirtHeight : 1.0
});

How the code need to implement on Sandcastle ?

**Comment by hpinkos** [comment]
@safa833 `QuantizedMeshTerrainData` is a class used to render terrain that is in the Quantized Mesh format.  You shouldn't need to use this class directly.  Instead, you can use a [`CesiumTerrainProvider`](https://cesiumjs.org/Cesium/Build/Documentation/CesiumTerrainProvider.html) to add your quantized mesh terrain to the globe.

You can learn more about the quantized mesh format here: https://cesiumjs.org/data-and-assets/terrain/formats/quantized-mesh-1.0/

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features. Thanks!

**Comment by safa833** [comment]
@hpinkos I know I don't need to use it directly but I should use it for a specific issue so, Can you give an example on Sandcastle ?

**Comment by mramato** [comment]
@safa833, what are you actually trying to do with Cesium?
