### ISSUE TITLE
Cesium no longer adds a default material for gltf 2.0 as needed

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#6891]
See attached. This is a gltf 2.0 containing a `primitive` that doesn't have an assigned material.
Cesium 1.47 handled this [according to spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#default-material) and assigned a default material, but 1.48 crashes instead.

[CUBE.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2266741/CUBE.zip)

**Comment by likangning93** [comment]
Git bisect points to 7e122685048b2c562322517627d2680b46c90165

**Comment by lilleyse** [comment]
Yeah this is my fault...

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/ThirdParty/GltfPipeline/addDefaults.js#L512-L515

I added that to stop it from generating 1.0 shaders for glTF 2.0 models but forgot that 2.0 primitives need default materials too. I'll open a fix.

**Comment by lilleyse** [comment]
Reopened until https://github.com/AnalyticalGraphicsInc/cesium/pull/6805 is merged
