### ISSUE TITLE
Alternatives to cesium-terrain-builder?

### ISSUE THREAD

**Issue by mrgloom** [AnalyticalGraphicsInc/cesium#6905]
As I can see Integer overflow problem is still preserves in `cesium-terrain-builder` https://github.com/geo-data/cesium-terrain-builder/issues/28  for large projects and  `cesium-terrain-builder` is not actively supported, so my question is what other alternatives exist that are compatible with `cesium`?

**Comment by hpinkos** [comment]
Hello @mrgloom,

Yes, we have a terrain processor as part of Cesium ion!  We support many different types of terrain data formats such as .dem, .asc and .tif.

You can sign up for a free account at https://cesium.com/

We have a getting started tutorial here which walks you through how to upload terrain and imagery and use them in CesiumJS applications: https://cesium.com/docs/tutorials/getting-started/

And we have a GitHub set up specifically for answering questions and giving feedback related our ion platform: https://github.com/AnalyticalGraphicsInc/cesium-ion-community

`cesium-terrain-builder` is not developed or maintained by the Cesium team.  Our terrain processor produces quantized mesh terrain tiles which can be used with a `CesiumTerrainProvider`.  Quantized mesh is an open data format that is designed for fast and efficient streaming on the web and results in better performance in CesiumJS applications than other terrain data formats like heightmaps.

I'm going to close this issue, but let me know if you have any more questions =)

**Comment by mrgloom** [comment]
It looks like some external cloud based service, is there any alternatives to work offline?

**Comment by icemagno** [comment]
Seems like Cesium wants to start to sell everything. This is the end of all tools that starts to be too good to be free.

Sometimes, like in my case, WE SIMPLY CAN'T USE A CLOUD.  I'll start to find another one realy free to use before I find my project broke.
