### ISSUE TITLE
Browser hangs when picking GroundPolylineGeometry is picked with drill pick

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#6907]
Submitted on the forum: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=dVRrT9swFP0rVr8slYqTNqUPVtAqYIwNUbSy7QNFk5vcpgbHjmynVTbx33edkL4Gqaok9jnn+txHfJ+cg+F5SqvbLx4nYAk3xPCUC6aJVTXiJ4c16BaZ53Ymfd+BrOZpCjGJ1VpSQq5L5lNuLGFkXUktFGosgYQXJBFqDh8rrkUOGCIVUmQk8hhKFJM8ZZYr2SL4kIAuiAEBUblUMpmMiUKofg1gWiiiKzWnChk4hCzl7JLr+Chj2hYl+ZtU0bPKLRF8rpku6EyuWK1ETomE9Vv58D5E5du5kpZxCfpDE21U3ARUClYX19JYJiPYV7k62PX+ziTBq2aRkz20VrmM75QoBEapuTXHXZky3OXCILE+KLrDJyZDutAqvYBEA5ix1qzwHrZMdx2122067B4HQb8/7PS77Xa3RcIe7fR74aDXHwwG3XY3bL1FCoaDMAi64bDTG/aQFNCgPxwch71eux92j7tbzmNzRwAza5d41g4NqsWXepdZbB5sJXBWdhxGSmA5t+7c62EWxzW3dFxCvF08nXwf315dNl9DzuRLVa+qztREIIEmVbKxgzGjKzCUxbH3bjE2uMMK1mdyNh4OFx9rs1kGTJftsVfwWr089XgD8jZJEkKt73j0zGVygtOWg/Oybb6UZZcrkPYLToXAkdjrvWmEjSCnGYtgF+TtZSFiKGQqxQM1asBeyyy343L8vEUuq4dUrSBFXNPVDX82woZUAihojZX4Op3cUoMVkglfFFt0GcS6v+/fK5JpcMHIkiFOJlj41MGIG083uwvlzLsdlyFHc44zTAbEk/kTfhMM+t0zE2suhEvXJiitB8YFf2m9l5r7IgN6c/n5/vePO4dstBojYwsBZ1UdPvE0U9qSXAuPUt9CmgmGrevPczyOpZEpUzjya9Io5ivC49NZ4+DLMWuQSDBjcGeRCzHlf2DWOBv5iN+jCcVi9D5ZgRascJBl++ymWqSUjnx8/Z9llRJzpncU/wE

The following sandcastle examples hangs when the polyline is picked:

```js
var widget = new Cesium.CesiumWidget('cesiumContainer');

var geometryInstance = new Cesium.GeometryInstance({
    geometry : new Cesium.GroundPolylineGeometry({
        positions : Cesium.Cartesian3.fromDegreesArray([
            -111.94500779274114, 36.27638678884143,
            -111.90983004392696, 30.07985366173454
        ]),
        width : 2.0
    }),
    attributes : {
        color : Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.ORANGE)
    }
});

widget.scene.groundPrimitives.add(new Cesium.GroundPolylinePrimitive({
    geometryInstances : [geometryInstance],
    appearance : new Cesium.PolylineColorAppearance(),
    allowPicking: true
}));

var mapEventHandler = new Cesium.ScreenSpaceEventHandler(widget.scene.canvas);

mapEventHandler.setInputAction(function(movement) {

	console.error(JSON.stringify(movement));
	
	//To prevent hanging comment out the following line
	var pickedObjects = widget.scene.drillPick(movement.position);
}, Cesium.ScreenSpaceEventType.LEFT_UP);
```

@likangning93 any ideas?

**Comment by hpinkos** [comment]
@OmarShehata @ggetz can you find the forum post this was reported in?  Can you tell them it's been fixed please?

**Comment by ggetz** [comment]
Whoops, sorry forgot the forum link. I'll let him know.
