### ISSUE TITLE
Support glTF spec gloss extension

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#6921]
Support the [KHR_materials_pbrSpecularGlossiness]( https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md) extension.

https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/331 has a lot of good notes.

**Comment by OmarShehata** [comment]
We can also close this @lilleyse.
