### ISSUE TITLE
Broken link in CesiumTerrainProvider doc

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#6923]
1. Go to https://cesiumjs.org/Cesium/Build/Documentation/CesiumTerrainProvider.html
2. Read "The format is described on the [Cesium wiki](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Cesium-Terrain-Server)."
3. Be curious and click on the link in the sentence.
4. Behold the redirect to https://github.com/AnalyticalGraphicsInc/cesium/wiki

**Comment by hpinkos** [comment]
Probably should be updated for https://cesiumjs.org/data-and-assets/terrain/formats/

**Comment by hpinkos** [comment]
Fixed in #6938
