### ISSUE TITLE
CallbackProperty callback not firing on clamped polylines using ColorMaterialProperty

### ISSUE THREAD

**Issue by impactblue573** [AnalyticalGraphicsInc/cesium#6925]
Clamped to ground Polylines which use a ColorMaterialProperty based material do not update each frame.

[Sandcastle Example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=xVZrT9swFP0rVr80lYoLDDapDzRUqoG0qmgt8GGdJpPcUg/HjhynKEz977tOnDZpKXuwsUitEvvc4+Nzrx8LpsmCwwNo0iMSHkgfYp6E9Dpr8+p+9tlX0jAuQdcbnalcYMxcLUAPpOEmxZapnCXSN1xJErJ76Cuh9KVWEWiTepChGuT7VBJ8NJhEy/JYfSbELfPvVxEFmWd4CE2MiBNhVgT24TPieEmv1yurqcDsUwxiNdGb84vJgPpCSfAcbWcNXxIQMTxL8Glwtjt8/eommWMcZNkkM4b8NmRZ8YwZw/z5s65Zz/0yANO102o3YP5FIyVSgcmjITOgORPVTGcMQ9e1YqqMtUvxKDGW+PU1X7puJ2BLfSmDmYB2VUdz3a1yhhsemHmb7Lue5WrG2RwEC6P0ACXkK4VmIjnElAVBMZZkIZA2qfctGALyEVnJDTdz8qTBdTdSMVEMLYmOVMytzzE2rxaJNvjG5Bs60yo8gzsNEJ9qzVLv89674yZ5e9ysFu7vPHsHhxnFl0aJ5MG6ghLKxKuEtLcWRgmVWTZRH7RKZIBQoxNw1qKxjU7V2sM/tfYndfAPTD5+ucnHr23yTCiWLb5f8PhK+v+tgI9e7u3R3/B27d5TG7PbDSzg6V3Q1fQaUI3Ps+GykyfkUalworyN9DSqB+ucyUDAUCUx/i3AgwUCK3ttxP17CEa338A362zHPuA+avvyEOQPLl16muRw3/6K3dceq2WWymFaOmSRvQyjPCjOuK0TtBolEyE6a5eLCs3ntnEFGftYIHIcMR8GVvh5DvIq8/IZEmRWOQ4ag7mQUWJO8yvEhm3NXeyTNAI6HF2NB1+Ho+tBo1Nr1rqxSQWc5Hrf8zBS2pBEC4/SloEwElhKces2QScM9eNMRrdVBHUDviA86E1rG5eoac0u3TjGnhn6MeaPMK2ddFuIr4RhoQRc3o3QQMFSC5kfnHzMGyml3RZ+bkcZpfA2pUuMPwA)

![cesiumclamphoverbug](https://user-images.githubusercontent.com/536744/44185711-795afc00-a158-11e8-96a1-8771317c7c2a.gif)

The issue seems to be caused by [`StaticGroundPolylinePerMaterialBatch.js`](https://github.com/AnalyticalGraphicsInc/cesium/blob/f6fa481ce1b1a133a0cb305a78b5ca768c277f2a/Source/DataSources/StaticGroundPolylinePerMaterialBatch.js#L181) not updating the material property when using [`ColorMaterialProperty.js`](https://github.com/AnalyticalGraphicsInc/cesium/blob/f6fa481ce1b1a133a0cb305a78b5ca768c277f2a/Source/DataSources/StaticGroundPolylinePerMaterialBatch.js#L35).

Using a different material property such as `PolylineOutlineMaterialProperty.js` works fine.

**Comment by hpinkos** [comment]
Thanks for reporting this @impactblue573!  And thanks for the great code example =)

I've opened a pull request to fix the issue here: #6927 
This should be merged in time for the September 1.49 release

**Comment by impactblue573** [comment]
@hpinkos Thanks for getting the fix in so swiftly, much appreciated!!
