### ISSUE TITLE
requestRenderMode Does not Function in Cesium version 1.47

### ISSUE THREAD

**Issue by stephenHartzell** [AnalyticalGraphicsInc/cesium#6926]
I am trying to use the `requestRenderMode : true` feature as described in https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/ . However, setting this option does not seem to change the viewer at least in version 1.47. In the profiler, I still see `requestAnimationFrame` called at 60Hz even when nothing is changing in the viewer. In the example straight from the blog post or something as simple HelloWorld with

```
var viewer = new Cesium.Viewer('cesiumContainer', {
          requestRenderMode : true,
          maximumRenderTimeChange : Infinity
      });
```

The viewer still renders every ~16ms (60Hz).

**Comment by hpinkos** [comment]
@stephenHartzell I couldn't reproduce this.  This is the sample code I used:

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
      requestRenderMode : true,
      maximumRenderTimeChange : Infinity
  });
viewer.scene.debugShowFramesPerSecond = true;
```

What OS and browser are you using?

**Comment by stephenHartzell** [comment]
I am using Windows 10 and Chrome 68.0.3440.106. I tried the code you provided and put it in the Hello World example. The debugShowFramesPerSecond shows zero, but that's not what I see in the chrome profiler.

![cesiumfps](https://user-images.githubusercontent.com/8050752/44220958-0d739600-a14e-11e8-9002-ec3601cf6653.png)

**Comment by ggetz** [comment]
The FPS says N/A because the viewer is not actually rendering any new frames. The simulation time is continuing to advance though, and the viewer is performing some checks to see if the scene has been updated and requires a new frame to be rendered. Are you seeing poor performance at all?

**Comment by hpinkos** [comment]
@stephenHartzell yes, the render loop in `CesiumWidget` is still running, but when it calls `scene.render` the scene will only render a new frame if there are changes to the globe that require a new frame to be rendered (for example, if the user has zoomed in).  If the render loop completely stopped, we'd have no way of detecting new input or changes to the scene.
