### ISSUE TITLE
ModelAnimationCache Memory use bug with DataURIs

### ISSUE THREAD

**Issue by mksquires** [AnalyticalGraphicsInc/cesium#6928]
The ModelAnimationCache currently uses model.cacheKey and uriKey in tandem as part of the key for models in the cache. When embedding a reasonably sized model in czml this results in the model's data being used as the cache key. In doing this memory can become rapidly exhausted. Please see the czml file in the following gist: https://gist.github.com/mksquires/0662e8cd7475c98fe63175ffd047a8ee for a demonstration of this issue.

**Comment by hpinkos** [comment]
Thanks for reporting this @mksquires!  Do you have time to open a pull request to address this bug?  If not, we'll try to look into it soon

**Comment by mksquires** [comment]
Hey Hannah,

Yeah I can probably get a pull request to you guys in the next week or so if that works. Let me know!

Cheers,

Michael


On Aug 16, 2018, at 1:36 PM, Hannah <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting this @mksquires<https://github.com/mksquires>! Do you have time to open a pull request to address this bug? If not, we'll try to look into it soon

**Comment by hpinkos** [comment]
Perfect, thanks!  Let us know if you have any questions =)
