### ISSUE TITLE
Evaluate webP for smaller images

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6935]
Useful for 3D Tiles, imagery providers, and other heavy textures?  How fast is decode?  How will it fit with Khronos CTTF (compressed textures)?

> WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.

https://developers.google.com/speed/webp/

**Comment by OmarShehata** [comment]
I think we can close this now.

**Comment by mramato** [comment]
It will automatically close when your PR goes into Cesium (we don't usually close issues until the PR is merged)

**Comment by OmarShehata** [comment]
Support for this is released so we can close now. https://github.com/AnalyticalGraphicsInc/cesium/pull/7486
