### ISSUE TITLE
Built CesiumViewer broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6941]
Not sure when, but worked as of last release.  It seems relative path related (maybe something in buildModuleUri?) did anything change here recently?

CC @ggetz

**Comment by ggetz** [comment]
Built Viewer is working as of the last commit: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Build/Apps/CesiumViewer/index.html

**Comment by mramato** [comment]
Weird, I thought I saw the problem on multiple branches, but maybe it's only broken in one branch.  I'm checking master locally now. Could also be something changed in an npm dependency.

**Comment by mramato** [comment]
OK, I'm just a moron and didn't run `buildApps` first, a long time ago that wasn't always required but I guess it is now.  Sorry for the noise.
