### ISSUE TITLE
StrokeWidth doesn't work for GeoJsonDataSource

### ISSUE THREAD

**Issue by lydart** [AnalyticalGraphicsInc/cesium#6942]
Step to reproduce:
1. go to https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=GeoJSON%20and%20TopoJSON.html&label=DataSources
2. For Basic styling, edit strokeWidth to 30 
4. Run

Expected - Line width should be wider
Actual - Line width didn't change

**Comment by mramato** [comment]
@lydart this is a limitation of Windows browsers (it works on Linux, Android, iOS, and Mac), see https://stackoverflow.com/a/25405483/3191039 for full details.  Basically the maximum limit is whatever `viewer.scene.maximumAliasedLineWidth` reports.

The good news is that we have an alternate implementation that would allow this, but no exact ETA on when it will be in.  Keep your eye on #6694.
