### ISSUE TITLE
Ability to select terrain in georeferncing tool

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6945]
Right now it always defaults to world terrain, but once #3462 is in we should probably allow terrain to be selected and whatever terrain is selected is automatically associated with that asset for preview (or future georeference tweaks).

**Comment by GatorScott** [comment]
Two things.  First, can someone with permission fix the spelling of "georeferencing"?  Second, what georeferencing tool?  I could not find an open issue mentioning georeferencing or georeference.

**Comment by mramato** [comment]
Whoops, wrong repository.
