### ISSUE TITLE
Rectangle no longer renders across IDL

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6951]
This works in 1.45 but not in 1.46

```js
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    rectangle: {
        coordinates: Cesium.Rectangle.fromDegrees(176.0, 30.0, -176.0, 40.0),
        material: Cesium.Color.RED,
        classificationType : Cesium.ClassificationType.TERRAIN
    }
});

viewer.zoomTo(viewer.entities);

```

**Comment by hpinkos** [comment]
@likangning93 it looks like this was broken with your materials for ground primitives changes.  Can you look into this soon?

**Comment by mramato** [comment]
It would be good to update one of our Sandcastle examples (rectangle entities?) so that the geometry just happens to span the IDL.  This way when someone does release testing they should at least notice it.

**Comment by hpinkos** [comment]
I also thought we had a render test for this but maybe not

**Comment by likangning93** [comment]
Digging in a bit:
* it's other primitives too
* definitely related to the materials code since it works with other classification types
* works for tiny areas in 3D b/c bounding planes instead of spherical extents
* CV and 2D broken b/c the primitive gets split and the bounds don't apply anymore... so that's pretty annoying :(

**Comment by ggetz** [comment]
@likangning93 Is 2D/Columbus view going to make it into this release? It should be merged today if so.

**Comment by hpinkos** [comment]
@ggetz #6967 fixed 3D.  2D/CV is still broken.  I"m going to leave this issue marked `next-release` but I don't think we'll have a fix for 2D/CV in by today

**Comment by likangning93** [comment]
@ggetz @hpinkos actually, PR for this should be open soon. Sorry for the radio silence!

**Comment by bagnell** [comment]
Reopened because there is still an issue in 3D/CV. The volumes need to be closed.

**Comment by hpinkos** [comment]
@bagnell is that different than #4746?

**Comment by bagnell** [comment]
Nope. Thanks, I'll close this.
