### ISSUE TITLE
Runtime matrix inversion error causes rendering to stop

### ISSUE THREAD

**Issue by mksquires** [AnalyticalGraphicsInc/cesium#6954]
In the master branch (currently 9287c3c) there appears to be an issue where transformation matrix inversion causes the rendering system to stop. This issue may be demonstrated via the following CZML file in the gist, https://gist.github.com/mksquires/cff0be46da9525f5fc0179becc430a62.

**Comment by mramato** [comment]
Thanks @mksquires  @bagnell said he already had a fix for this so hopefully he'll open a PR soon.

**Comment by mksquires** [comment]
Sounds good! If he can't get to it let me know and I can fix it.

**Comment by mksquires** [comment]
To add some information regarding this issue:
- the render failure occurs only when animations are active
- the render failure is due to the animation system creating transformation matrices for certain nodes with scale factors near zero. The matrix inversion code determines that this matrix is singular and throws.
I do have code to fix this issue and will open a PR soon.

**Comment by hpinkos** [comment]
Thanks @mksquires!  Sorry for the delay on this.  Opening a PR is usually the best way to get a fix through quickly if you have a solution ready to go.

**Comment by mksquires** [comment]
Thanks @hpinkos!
