### ISSUE TITLE
Ion defaultAccessToken warning

### ISSUE THREAD

**Issue by alextym** [AnalyticalGraphicsInc/cesium#6961]
Hi, everyone!
With cesiumjs 1.48 i have a warning when want to use terrainProvider with imageryProvider and geocoder (Bing Maps key):
**This application is using Cesium's default ion access token. Please assign Cesium.Ion.defaultAccessToken with an access token from your ion account before making any Cesium API calls.**

My code is:
`Cesium.Ion.defaultAccessToken = " TOKEN FROM ION HERE";

    var viewer = new Cesium.Viewer('cesiumContainer', {
        imageryProvider: new Cesium.BingMapsImageryProvider({
                    url : 'https://dev.virtualearth.net',
                    key: '<KEY>',
                    mapStyle: Cesium.BingMapsStyle.AERIAL  

                }),
        baseLayerPicker : false,
        geocoder : [
            new Cesium.CartographicGeocoderService(),
            new Cesium.BingMapsGeocoderService({key:'<KEY>'})

                ],
        terrainProvider: Cesium.createWorldTerrain({
            requestWaterMask: true,
            requestVertexNormals: true
                })
    });`
How can i avoid this warning? If I use terrainProvider i can only use IonImageryProvider and IonGeocoderService instead of geocoder and imageryProvider (with BingMap key) in my program?
Thanks.

**Comment by mramato** [comment]
@alextym, sorry to hear you are having a problem.  Unfortunately, your code is working for me locally without any issues. (obviously I replaced the token and key strings with my own values).

How are you including Cesium in your application?  Are you using the version from NPM or the release zip?  Does this happen in all browsers?

**Comment by alextym** [comment]
@mramato, i use cesium 1.48 release zip.  I create another ion token and it is valid for my program(warning dissapear). Don't know why previous token was't right (i checked and it was like in cesium ion). Sorry about previous question.
 I have another question.  Warning still appears when i want to change terrainProvider (for example terrainProvider from EllipsoidTerrainProvider  to Cesium World Terrain)
I have two checkbox WGS84 Ellipsoid and Cesium World Terrain
Code: 
`
if (document.getElementById("EllipsoidTerrainProvider").checked) {
        viewer.terrainProvider = new Cesium.EllipsoidTerrainProvider();
        }
if (document.getElementById("CWT").checked) {
        viewer.terrainProvider = Cesium.createWorldTerrain(
{
    requestWaterMask: true,
    requestVertexNormals: true
});   
       }
`
What can be wrong in my code? Thanks for advice.
