### ISSUE TITLE
Loading fractional times from CZML seems to break the animation widget

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#6970]
The times shown below were written from STK Components' CZML writer.

```
var czml = [{
    "id" : "document",
    "version" : "1.0",
    "clock" : {
      "interval" : "2018-08-28T18:49:58.402156399999512Z/2018-08-29T18:49:58.402156399999512Z",
      "multiplier" : 30,
      "range" : "LOOP_STOP"
    }
}];

var viewer = new Cesium.Viewer('cesiumContainer');
viewer.dataSources.add(Cesium.CzmlDataSource.load(czml));

viewer.clock.shouldAnimate = false;
```

![bustedanimwidget](https://user-images.githubusercontent.com/1235080/44744692-b49fe800-aad3-11e8-8e41-c937b556096c.png)

**Comment by shunter** [comment]
Your CZML snippet does not specify `currentTime`.  If not specified, `currentTime` defaults to `ISO8601.MINIMUM_VALUE` which is year zero as you see.
