### ISSUE TITLE
Scene pickPosition Result Wrong with Viewer Option baseLayerPicker false

### ISSUE THREAD

**Issue by mlptownsend** [AnalyticalGraphicsInc/cesium#6990]
Cesium version 1.48, Win 10 Professional, Intel HD Graphics 520 driver v23.20.16.5018. Reproduces locally on Chrome 68.0.3440.106, Firefox Quantum 61.0.2, Edge. IE not supported (Picking from the depth buffer is not supported. Check pickPositionSupported.) Also reproduced on a different computer using Firefox 61.0.2. 

Cesium 1.47 and 1.44 also appear to be affected.

Problem:
When initializing the Viewer, providing false for baseLayerPicker can cause Scene.pickPosition to return an incorrect value for the provided screen x & y coordinates. If true is provided or not specified, Scene.pickPosition correctly returns the position.

My guess is that it's somehow height related, since CLAMP_TO_GROUND is also specified.

Sandcastle examples:
An entity is created and its position is updated via a mouse move event handler.
Expected behavior: [baseLayerPicker true](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=jVTfb9owEP5XPF4apMi02xulaIyidhoMBJS+REImOYo1Y2e2E8Ym/vedk5gmrJtmv9j347vz3XfOmSY5hwNockckHMgQDM/2dFXIgqu4uA6VtIxL0Fch+RVJgmvDDIzZEfSMx99Ad8mWCQOhU5UGGr5nYOwcZAJ6ohLoEqszCEutBa0RcaZVzlFPuj5wrIFZeFZaJMvSJmhH8tS+jWSOue6YTMRlsgt0ArlIWQyjHKR9LI0C78TNVKJHkWElQituj02YUSELqgemikvbretnTvKgWbrjsXFmkfU7VkLp8xuG7kbno/uwbpPyHyAW/CcW4ua6oVGZFVjd4Rsgn8aD4Ze3jJ95Yndd8r6h2wF/2WHJt6BBxnDGemzK6XA8mMzWy+n6YT59+nr/CnFqh/71hluuZKMASANjmbSzSondS0Fjyeo2TFs8MfkhuA5xt333qs5RA/azTDM7iB1EsM1keYC2p5brz8ERwMfBNpUcpSYGCTRFynldABQZ5m8ukIPg26CBgNgVLd0qm0/9G11KKyYyuPC5ffVAvHeORecc/aryKhA5GMqSJCjh6+4FRElCNwM1zak8ngggN+vgGPG/AmrYqxz+HdMT/zJoVe56aRtTWwzQKfzbmC2PKdDJ9GkxWk+mq1H7thW2esYeBfRL5I98nyptSaZFQGnHwj4VONyms8nwz7A0NsZF6HW8Uy/hOeHJXdS6+HeiFokFMwY120wUUxS1+r0O2jfchGIJly/THLRgR2eyu+mPSyGltNfB659eVimxYbqG+Bs)
Broken: [baseLayerPicker false](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=jVTfb9owEP5XPF4apMi02xulaIyidhoMBJS+REImOYo1Y2e2E8Ym/vedk5gmrJtmv9j347vz3XfOmSY5hwNockckHMgQDM/2dFXIgqu4uA6VtIxL0Fch+RVJgmvDDIzZEfSMx99Ad8mWCQOhU5UGGr5nYOwcZAJ6ohLoEqszCEutBa0RcaZVzlFPuj5wrIFZeFZaJMvSJmhH8tS+jWSOue6YTMRlsgt0ArlIWQyjHKR9LI0C78TNVKJHkWElQituj02YUSELqgemikvbretnTvKgWbrjsXFmkfU7VkLp8xuG7kbno/uwbpPyHyAW/CcW4ua6oVGZFVjd4Rsgn8aD4Ze3jJ95Yndd8r6h2wF/2WHJt6BBxnDGemzK6XA8mMzWy+n6YT59+nr/CnFqh/71hluuZKMASANjmbSzSondS0Fjyeo2TFs8MfkhuA5xt333qs5RA/azTDM7iB1EsM1keYC2p5brz8ERwMfBNpUcpSYGCTRFynldABQZ5m8ukIPg26CBgNgVLd0qm0/9G11KKyYyuPC5ffVAvHeORecc/aryKhA5GMqSJCjh6+4FRElCNwM1zak8ngggN+vgGPG/AmrYqxz+HdMT/zJoVe56aRtTWwzQKfzbmC2PKdDJ9GkxWk+mq1H7thW2esYeBfRL5I98nyptSaZFQGnHwj4VONyms8nwz7A0NsZF6HW8Uy/hOeHJXdS6+HeiFokFMwY120wUUxS1+r0O2jfchGIJly/THLRgR2eyu+mPSyGltNfB659eVimxYbqG+Bs)
Broken: [Drawing on Terrain sample with baseLayerPicker false](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=tVdtcxo3EP4rGn/hmKECJ3FfYuKpg2nMFMeMIfG0ccYWdwunqZBuJB2Ydvzfu7o3TkBwPJ3yxT7ti57dfXYlLZkmSw4r0OQdkbAiPTA8XdDP2VrQCLPPnpKWcQm60SLknztJ8GdAQGi5kgMZ8ZBZpclbMmPCQCtX4HKm3qvHrdUpMzBka9AjHv4F2hda0Br3GWm15BE4hwWcUAOzcKu0iCa5TtC8k0/N0zuZo6c50FsezcFSg/ogxwkLob8EaS+ZjAQqaVioJQxkktrzDHtQ+B9vGUzWCdBh/7fJ/cX1p/fD/n1vOOj97rabpTKzJDmkkeLSBisHbKQMd5JmmaEl5jZxckxtgRJdow4YyqIoKNTcLylsMWLPV6uu4jy9JTUr9wuVULVE9dwnvb0cTPotXzHhjyDG/G9A5ZMtWQx8HtsbmIEGGULl7dJfp73h+dXofnJ9/+Hm+tPHi42Tp/zfrCDuHw021TLHjEsodsmINFtxOb9SEWBKGgIZ1ain1MnHMUsgKPNxwSzz8mmcuNiEz0jguXxXOm3Ws5SZPF+CPMdi7RzsprleJIPiOsDWrmoo2CKZqA9apTJCdatT2KO24pGNUfzaFz3VEltmtFgDbJb9gTvscyX/U+xovzfymINmOozXzwa+wJ7QnIm39WGSkfKqkGBzJ6DtOthlLF1xG5+LJGZBh/7UbH53Vgq6leQo6MaQVUvICJW1qcFEfPl6uiMsVmZCMYspHRWkdWtxPjj82TjeP12CchIxNDUOYWFNDdj6zCn5HoCzrurVbpNbICnW96HwZEKQQBMclOU8eMBW1UgAaSywiKhZpRuyBdYoU+4LwROjePRAjCI2ZrbaYAUE5yOuAQ4OrXGAF3NlFYMkC5UaTADBGanLWUw3vQdM27hEsiHVLso8MFpSpSwW7v/g+XjABhCCTDFqGcEMGy9y3FapzqBgnIZIZQs8iHku1BTopvuLghS2gee86TWC097hAxUg59iArn86zW3ie3zAcOsD39/p1Dfc3SdJTXzYJhuPa8kWPBxVY8ZjXY8JMWWY5LJ/qrEZNPf1bNETO2C2Nn5q5SfwgSAQx2Yyb4Os29U69KU5eDa56BuhPntcV+f0S7tvD508Avh0cuXC2rygGUBG++Les23Nb/MwKasOczF+ZiIFz/h5Wqok+E7yfsPv0/cW5+r607h/f3X9ue/McRLcgONU1tX5IYWjittG3vAFyQhWkOR3tkyxXM4MaO3igLNqwSUSKOdolbXDIW9IvaNXqmyfmzmYLWYc1q35LjW3J0s1/U53YB+W+sfa00s5v52202fLeDP4cOk1mWsElZTj6kvl+NFdVRsXrsRDxG4axV0B9bJ3g3sVlKA8ku/BVIq+cX3cEHDf7qP8WvN/AChvXDUMX7OkjLEKITNWgLtoTZTCwa2vQKZBkaqiB/5UaoFnObEKmU4YjkDibkDu8MveW2bzuslPd6HUX+e2ujnhnMT/mHxNZ1otLmCOFTPBD8evXtFXnZOfW+TNj/T4l5OTFjnudDq002z5B0ppHpxk4hbx/zbrz6s6gIlm0syUXpRI8G6n+eMbOrjof5wMJn84w6PWUdfYtYCzPD2/8kWitCWpFgGlbQuLRGCWTXua4kPQ0tBkaem2S6NuxJeER+/ujrYeoXdH7n5tDEpmqcjeNHdHZ9026ntm2GURlusabw+CrZ1KfHw2zBcppd02fu5a2bxcqJ7j7lo2FVDt6F61IyZBVAq50lRFa29Bn/mDtWujsyHMLHrC0yGreRQRRhAdEhbRoLxm3/Yd7Pd3455nG4fGYkmzEucT8rBP/KyBxi8Xp0tFkZJ/AQ)

Screenshot. Mouse was moved across the Great Lakes.
![cesiumscenepickposition](https://user-images.githubusercontent.com/38544371/44936606-06967700-ad3b-11e8-889f-ab9042996379.png)

**Comment by hpinkos** [comment]
Hello @mlptownsend, thanks for submitting this issue!  The problem is actually that `BaseLayerPickerViewModel` is secretly setting `scene.globe.depthTestAgainstTerrain = true;` if you pass in a terrain provider to `Viewer`.  You can set `viewer.scene.globe.depthTestAgainstTerrain = true;` yourself to fix the problem.

I'm going to open up an issue to discuss whether `BaseLayerPicker` should be setting `depthTestAgainstTerrain`.  I don't think that it should.

And we have an issue open here about using `pickPosition` without `depthTestAgainstTerrain` https://github.com/AnalyticalGraphicsInc/cesium/issues/4368

**Comment by mlptownsend** [comment]
Thanks for the quick response!
