### ISSUE TITLE
Multi-line labels have extra vertical spacing with some characters

### ISSUE THREAD

**Issue by schmidtk** [AnalyticalGraphicsInc/cesium#6997]
The `measureText` call calculates odd heights/descents for some characters. On macOS/Chrome the letter `M` is measured taller than it should be. From inspection, it looks like the canvas has extra empty space at the top. This results in multi-line labels having unnecessary spacing between lines.

![screen shot 2018-09-03 at 11 47 24 am](https://user-images.githubusercontent.com/5685437/44997954-27dfa900-af6f-11e8-8706-3d5e0cad7265.png)

On Linux/Chrome I was seeing similar behavior but with `4` having a height of 17 (most characters were 11) and `N` having a descent of 2.5 (most characters were 0.5). The end result in `repositionAllGlyphs` was a much larger max line height (19.5) than expected and very spread out label lines.

Use this gist to reproduce:
https://gist.github.com/schmidtk/77c64471dc9e7170b18a344c238c4700

**Comment by schmidtk** [comment]
I did look at that a bit, and I believe this is a separate issue with the same library. It happens with native browser fonts and doesn't seem to be related to font loading.

**Comment by hpinkos** [comment]
This appears to be fixed

![image](https://user-images.githubusercontent.com/3451886/65275367-854f8500-daf3-11e9-8015-ba7f62738b19.png)

**Comment by schmidtk** [comment]
@hpinkos Confirmed in our app as well, thank you!
