### ISSUE TITLE
sampleTerrainMostDetailed does not work for EllipsoidTerrainProvider

### ISSUE THREAD

**Issue by floonone** [AnalyticalGraphicsInc/cesium#7002]
Following the recommendation to display polylines at height over terrain, I've been using the function `sampleTerrainMostDetailed` to compute the heights. However, I've found out that calling this function with an `EllipsoidTerrainProvider` fails.

While this bug it can be avoided by calling directly to `sampleTerrain` with a level, it's a bit unconvenient when switching between different terrain providers, since avoiding having to set the maximum tile level for each one.

The sandcastle example for [terrain sampling](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain.html) shows this bug, just select the `EllipsoidTerrainProvider` and click the "Sample Most Detailed Everest Terrain" button, which silently fails. The rest of the features work as expected.

Searching for past issues, I found this comment (https://github.com/AnalyticalGraphicsInc/cesium/issues/4368#issuecomment-407089658), saying that `sampleTerrainMostDetailed` does not work since the terrain provider used doesn't support `availability`, which is needed by the function. This is also the case for EllipsoidTerrainProvider.

**Comment by hpinkos** [comment]
Hello @floonone, I just fixed this issue in #6824.  It will be included in the 1.49 release which will be published later today.  Thanks!

**Comment by mramato** [comment]
@floonone I believe your code should just check if `terrainProvider.availability` is defined before calling `sampleTerrainMostDetailed` and then you can handle it

**Comment by hpinkos** [comment]
Ah yeah, `sampleTerrainMostDetailed` requires the `availability` property or it throws a `DeveloperError`.  Also, if you know that you are using an `EllipsoidTerrainProvider`, the height on the globe will always be zero.

**Comment by floonone** [comment]
@mramato that's fair I guess, I had already found a workaround, and you're right, performing the check, and knowing the EllipsoidTerrainProvider will always provide zero height, this problem can be avoided. The intention after this issue was more about having a consistent behaviour with `sampleTerrain`, which doesn't throw an error, and allows for a more transparent integration, since it removes the need for the check.

I think I'm fine with the solution provided. Thank you both for your time and your work with Cesium!
