### ISSUE TITLE
Uncaught TypeError: Cesium.loadJson is not a function

### ISSUE THREAD

**Issue by vaishakha** [AnalyticalGraphicsInc/cesium#7008]
I'm getting an error like this
Uncaught TypeError: Cesium.loadJsonP is not a function

For Cesium.loadJsonP also giving the same error

Need help. Is Cesium.loadJson() deprecated?
I tested this function in [https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/)  but not working

Version: Cesium-1.48

**Comment by mramato** [comment]
@vaishakha loadJsonP was deprecated 6 months ago in Ceisum 1.42 and removed 2 months ago in Cesium 1.44.  (See [CHANGES](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#144---2018-04-02)) 

Short version, use [Cesium.Resource.fetchJsonp](https://cesiumjs.org/Cesium/Build/Documentation/Resource.html#.fetchJsonp)
