### ISSUE TITLE
load gltf file and select components

### ISSUE THREAD

**Issue by m7567** [AnalyticalGraphicsInc/cesium#7009]
Hi,

I have an Autodesk Revit model with a lot of componets in it. First I convert it to IFC file and then convert to gltf file, then I load this model to Cesium platform. In Cesium, I want to select just one single component and show it's information . Only select the wall but not the whole building. However, in Cesium I can only select the whole model but not just one singe component of the model. 

I am wondering what can I do to solve this. Maybe improve in the way I convert my Revit model to gltf file?

Does someone familiar with this? thanks

![image](https://user-images.githubusercontent.com/40194025/45147737-37bdee00-b1f8-11e8-9c15-e582fc20ecb2.png)

**Comment by hpinkos** [comment]
Hi @m7567,  Cesium doesn't currently have the ability to select individual nodes of glTF models.  We have an issue open here to add this ability: #2387

I'm going to close this issue as a duplicate, but I'll add a comment to #2387 so we can notify you when we have a chance to add support for this.  Thanks!

**Comment by darshangajjar003** [comment]
> Hi @m7567, i'm sorry to bother you after the issue is closed. I was trying to show the Autodesk Revit model in browser too. But I failed to extract the building information such as structural information from gltf file(e.g.I searched the whole files for reinforcing bar information but find nothing).
> 
> In the picture that you posted, the building information was listed in the table at the right side of page. I'm very interested in how that could be done, so may I ask you some questions? I would be very grateful if you can help.
> 
> 1. I'm confused that if the building infomation was included in ifc file and gltf file. Do I need to change the IFC export options in Revit to include the building information or you have anthod way to export and load the building information.
> 2. which tool or method you used to convert the ifc file to gltf file. In my way, I used the [IfcConvert](http://ifcopenshell.org/ifcconvert.html). the convert path was : rvt file -> ifc -> dae -> gltf
> 
> By the way, I used the threejs to load gltf model file and also encountered the same problem as you, that is I can't select the component of the model. Finally I fixed this problem by manually modified the gltf file. I'm glad to offer help if you need.
> Thanks!

If it is possible in three js after modify gltf file then may be It should also work in Cesium JS.
Have you tried that?

**Comment by thxiami** [comment]
@darshangajjar003 Sorry, I haven't tried it yet. But as long as the modified gltf file is still in the standard format, it will also work in CesiumJS.
