### ISSUE TITLE
Translucent rectangles very slow when switching to 2D

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#7018]
Rendering several stacked translucent rectangles seems to severely decrease scene performance, but only when switching to 2D from other scene modes - starting the scene in 2D doesn't seem to have the same performance drop.

I'm not seeing the same performance drop in `1.49` as in `master` (42 -> 30 FPS vs. 42 -> 14 FPS), so this seems like a recent regression as opposed to a bug we never found before.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.scene.debugShowFramesPerSecond = true;

// Tropics of Cancer and Capricorn
var coffeeBeltRectangle = Cesium.Rectangle.fromDegrees(-180, -23.43687, 180, 23.43687);

// Add rectangles to show bounds
var rectangles = [];

for (var i = 0; i < 10; i++) {
    rectangles.push(viewer.entities.add({
        rectangle : {
            coordinates : coffeeBeltRectangle,
            material : Cesium.Color.RED.withAlpha(0.1),
            height : i * 5000.0
        }
    }));
}

Sandcastle.addToolbarButton('Show/Hide Rectangles', function() {
    var rectanglesLength = rectangles.length;
    for (var i = 0; i < rectanglesLength; i++) {
        var rectangleEntity = rectangles[i];
        rectangleEntity.show = !rectangleEntity.show;
    }
});
```

**Comment by hpinkos** [comment]
Related? #5026

**Comment by lilleyse** [comment]
git bisect points to https://github.com/AnalyticalGraphicsInc/cesium/pull/6957/commits/4633ea6b10132066e222a73a1e6a3fd639c8071e. I'll look into this.
