### ISSUE TITLE
ContextCapture 3dtiles failed to display

### ISSUE THREAD

**Issue by veolata** [AnalyticalGraphicsInc/cesium#7020]
I have a tileset generate from context capture (2G in size). Using the apps from bentley, the tileset can be displayed. But when I try to use the tilest as an datasource to code something, it seems not work.

I check the js code Bentley written, it's compressed. It seems did some transform and other modification of the model. But It is not clear, any resource to directly show how to display my tileset directly generate from contextcapture?

btw, Why context capture has not document it clearly? or publish the code clearly???

**Comment by hpinkos** [comment]
Hello @veolata,  Context Capture should export 3D Tiles tilesets that are compatible with CesiumJS.  However, you wouldn't use a datasource to load them.  Here is an example of how to add a tileset:

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var tileset = new Cesium.Cesium3DTileset({
    url: '/path/to/tileset'
});

viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset);
```

If it is not in the correct location on the globe you may need to set `tileset.modelMatrix`.  

Although Bentley supports CesiumJS development, the Cesium team does not work on Context Capture.  If you are having further issues, I would contact Bentley support to see if they are able to help you.  Thanks!

**Comment by likangning93** [comment]
Hi @veolata,

If you have Cesium running on localhost, you should be able to load 3D Tilesets off disk.
Here's a snippet of Sandcastle code for loading one of the sample tilesets that we ship with Cesium:
```js
var viewer = new Cesium.Viewer('cesiumContainer');

var tileset = new Cesium.Cesium3DTileset({
    url: '../../../../Apps/SampleData/Cesium3DTiles/Tilesets/Tileset/tileset.json'
});

viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset);
```

Just make sure you know where the `tileset.json` file is for the whole tileset - I'm not sure, but Context Capture may produce several `tileset.json` files for various parts of the tileset that are linked together using a single `tileset.json`.

If the tileset shows floating in space, but then the camera goes back out to the surface of the Earth, then the tileset might not be positioned correctly on the planet - it may be loading at the center of the Earth.
You can double-check this by setting `viewer.scene.globe.show = false`, which will prevent the globe from hiding your tileset. You can use the `Cesium3DTileset`'s [`modelMatrix`](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html#modelMatrix) to reposition the tileset on the surface of the Earth instead.

In the future, we also recommend using our forum for questions on how to do something, especially when external products like Context Capture are involved: https://groups.google.com/forum/#!forum/cesium-dev

Someone on the forum may already have worked through this problem, or may have the same question with other helpful observations. We prefer using github issues exclusively for tracking bugs and planned features.

**Comment by veolata** [comment]
@hpinkos, Thanks for reply! I am not try to solve the height issue. I did reset the model matrix. But seems only the b3dm files were not downloaded. Other json files in tree are downloaded.  Really cant figure it, please help~

**Comment by veolata** [comment]
Hi @likangning93


Thanks for your reply, I post the issue in Google Group. Sean checks the tileset and has post two issues #7035 and #7036 to report bugs.
Really good works on cesium, wish you guys all the best  


--

祝好


达理
13813873798

At 2018-09-10 22:55:59, "likangning93" <notifications@github.com> wrote:


Hi @veolata,

If you have Cesium running on localhost, you should be able to load 3D Tilesets off disk.
Here's a snippet of Sandcastle code for loading one of the sample tilesets that we ship with Cesium:

var viewer =newCesium.Viewer('cesiumContainer');

var tileset =newCesium.Cesium3DTileset({
    url:'../../../../Apps/SampleData/Cesium3DTiles/Tilesets/Tileset/tileset.json'
});

viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset);

Just make sure you know where the tileset.json file is for the whole tileset - I'm not sure, but Context Capture may produce several tileset.json files for various parts of the tileset that are linked together using a single tileset.json.

If the tileset shows floating in space, but then the camera goes back out to the surface of the Earth, then the tileset might not be positioned correctly on the planet - it may be loading at the center of the Earth.
You can double-check this by setting viewer.scene.globe.show = false, which will prevent the globe from hiding your tileset. You can use the Cesium3DTileset's modelMatrix to reposition the tileset on the surface of the Earth instead.

In the future, we also recommend using our forum for questions on how to do something, especially when external products like Context Capture are involved: https://groups.google.com/forum/#!forum/cesium-dev

Someone on the forum may already have worked through this problem, or may have the same question with other helpful observations. We prefer using github issues exclusively for tracking bugs and planned features.
