### ISSUE TITLE
Entity show not getting applied immediately

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7024]
Setting `entity.show` does not seem to get applied immediately.

![pickbug](https://user-images.githubusercontent.com/915398/45324847-520c0a80-b51d-11e8-92c8-e04082a2c2d0.gif)

```
blueEllipsoid.show = false;
var picked = viewer.scene.pick(movement.position);
// entity gets picked
```

[Sandcastle demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVTRbtowFP0VixeCxBxY+9QCWsvoioY0qbA9IU3GuYBVx45sJxWd+Pddx4RAaKVq0vyQxNf3nOt7fJyCGVIIeAFDhkTBCxmDFXlKf5WxqM3L6Vgrx4QC0+7cLlWBGMtBAUIClpZTXAqLK5nDREqRWS2SOgmUE06ApSxJoj9LRXAolgK5Ie17hBCoMO1uWM20RYRWN9W2xsw4/GLqiq6NTr/CxgDY6FO/f017XXLd88+rnh+01zmwHGmx0KGsH4YlQmDopOuaPvp8IOmS+qtJ7EfKHBjBJKn3qKU29H72cxKy9ku17wRtgg6vWqcLHTVUCSnrXHHfMTG5ulsj9ROoBA+CMylXjD93qg68zqxOeKhwQ1JRRJ3TbiuCyNepguWxUVTZBRZqINUFTArc1ExYh6smeqNKxbE/vC948IQ/RLL3PccxWWyFJUJxbQxwJ3ckM0I5S9wWXeEF2gVnbZlKZNOrc44mUPOM8bDzx5BUCcwZQkt5D2hqwU1Vlru7oNNRMN97igRH4c6MTO1Wv3h9mbRwW59CJvgzJI27QH30SEgrI1fCca2slkCl3kQBX6rRfa+lxS4DOps8LH6PZ9Px9+CVWrkL3XIUeo0XNvkfTTes+bbf/lWZ99UpDfcBmZ6m3x7PdGp1WwPrdhJGgeSLSDNtHMmNjCiNHaSZxFts41WOtRzltnTLIK5Ag0QURCTDZavxO1y2CJfMWlxZ51LOxSssW6NBjPlnMKnxX6M2Pwowku18yrY/moUgpXQQ4/QS5bTGK2tOGP8C)

Ran into this bug while working on https://github.com/AnalyticalGraphicsInc/cesium/pull/6934 where `sampleHeight` needs the ability to hide certain entities or primitives immediately before getting the height.

**Comment by lilleyse** [comment]
[Primitive API demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dVRRT9swEP4rUV9wpM6FwVMpaKVLN7QyEBS0h0jITa6tNceObCdQJv77LnYMaQt5aH2++z7fd2dfzXRUc3gCHZ1FEp6iCRheFfTB7ZGDzJkTJS3jEvRBfJrKGjEmAwkI8VjqTHR5p2Y559t8E6Ytrpg8Jl8Pm48e9qP31XG7CvSlMtxyJa9lIgQvjeI58u1x0aVWxXdYaQBDvhx5rpMOT6FyEFfMav78jvf2CS0qYXkpNhebuWbSCNacSFIZ4deGOsdS6cJQYMb+Vtqu78u5mvJnyKeaFUA+SDXue5KP9bsk3Y+rE32J+93INjsSpzKogED8A1QBVm+2a5vsusk/f34NeOjzFNNnNhqG8BvQl9JYJjOYKKH0uCyB6cakD8ntPPnzOL2+vRrPWxG+mUP/n8rXvaQC2XZSIZfgDTmtgoThvqz2xG7Thl2r9TOLxqLCeqK7pW2+rFHzrtOJ201jHLDu6rgQ0o2nF7P7JPacrx21C1FB9yq6C09LzQtsfg2GsjwnHfk3wbOrOyRiugUIm0HgW0cwqEv6aedIpwzWXeYKE2yavmTCBF5XJKEM5OiwuoJWZ9wIjd+e75rJXOwOhLsMH5m8K1kGSY3UP30QaQdAxhBqGo4WTQ3YS1lWdpy5Z7WspF8UqoYCCeLQuq3SUrNWT3iyS/u0vcbNQODZX8h3Bg5tdt8IaXiJcYvLlDRKABVqRTy+8bz2P5M035RAZ8l0/jiZXU5+xae9fm9k7EbAuSf8xosSJ0BUaUEoHVgoShwaYAaLCtktzYyrwGgQQKOc1xHPz9LezhxNe9gIZgx6lpUQd/wF0t75aIDxWzCh8NXJ1TW+ZME2Tcj66HzmNymlowGa+yirlFgw3WH8Dw)

The primitive gets hidden and does not get picked, which is the correct behavior.

In the entity api `show = false` is only reflected the next frame and is not updated during the pick pass.

**Comment by hpinkos** [comment]
For performance, the entity primitives don't get updated until the next clock tick.  I don't think this is something we'll change.  In your demo, if you add the line `viewer._dataSourceDisplay.update(viewer.clock.currentTime);` after `entity.show = false` it won't pick the entity.  

@mramato can chime in, but I think we should close this issue as a `won't fix`.

**Comment by mramato** [comment]
I mostly agree with @hpinkos here, there are plenty of things things in Cesium that don't get updated until a full frame is rendered and you can fall into a lot of issues if you call pick immediately after changing things.  I would recommend scheduling a postRender callback to actually perform the pick.

That being said, drillPick works fine with entities because it just iterates all primitives and turns them off as it goes (setting the value back to the original value after it's done).  I'm not sure what sampleHeight is doing, but is there a reason for it to work at the entity level instead of the primitive level?

One possible way to make entities be reflected immediately in pick (without giving scene knowledge of Entities) would be to have entities actually update in `preRender` instead of clock tick.  Does scene.pick trigger preRender events?

**Comment by lilleyse** [comment]
Ok, as long as this is expected behavior I'm fine with a workaround. Using a callback won't work with the current design but drill pick should, I was thinking about using it internally in some way.

For a little more background `sampleHeight` accepts a list of objects that will be excluded from picking, the usual case being to exclude the object that you are trying to position, otherwise it samples height on itself. The object could be a primitive or entity. Adding a `drillSampleHeight` (not final name) that returns an array of heights and picked objects might be an option too.

`pick` doesn't call `preRender` functions right now, I'd have to think more about that. I'm ok with closing this for now as `won't fix`.
