### ISSUE TITLE
Cannot replace the parent level tiles with the children level tiles

### ISSUE THREAD

**Issue by a0026** [AnalyticalGraphicsInc/cesium#7026]
When I use the multi-level tiles . I found that the parent and the children disappear and appear at the same time. ps:  I have the "REPLACE" on the root's refine field.

**Comment by ggetz** [comment]
Hi @a0026, would it be possible to provide your tileset, or an example tileset which duplicates this issue?

**Comment by OmarShehata** [comment]
Should this be closed as a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/7007 @ggetz ?

**Comment by a0026** [comment]
> Hi @a0026, would it be possible to provide your tileset, or an example tileset which duplicates this issue?

The same as #7007, thanks.

**Comment by ggetz** [comment]
Thanks! Closing as a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/7007
