### ISSUE TITLE
想要读取mongodb数据库存储的terrain数据

### ISSUE THREAD

**Issue by WHUWWX** [AnalyticalGraphicsInc/cesium#7027]
很感谢这个js库，功能很强大，我自己写了一个MongoTerrainProvider，想要读取后台tomcat服务器提供的terrain数据服务，但是调用的时候只读取0/1/0层数据，服务器返回成功，能调用createHightmapdata函数，想问问是什么原因造成的，我的MogoTerrainProvider中没有获取promise，使用的是xmlhttprequest发送的请求

**Comment by ggetz** [comment]
Hi @WHUWWX, 

It looks like your asking about creating your own terrain provider. Please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. 

Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
