### ISSUE TITLE
3D Tiles Inspector looks funny in master

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#7028]
![3d-tiles-inspector-bug](https://user-images.githubusercontent.com/5395255/45363781-60eacf80-b5a6-11e8-86ba-2b4696a08bd0.JPG)

Seems to have happened after the 1.49 release.

**Comment by hpinkos** [comment]
It's from #6996
The tileset inspector must be using the same css class names as the cesium inspector.  I'll fix this in a sec
