### ISSUE TITLE
Possible new issue template improvements

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7040]
@emackey brought up VS Code's way of doing it and it's pretty nice, especially since it will help direct people to the forum:

https://github.com/Microsoft/vscode/issues/new/choose

Implementation here:

https://github.com/Microsoft/vscode/tree/master/.github/ISSUE_TEMPLATE

**Comment by pjcozzi** [comment]
Oh that is awesome.

**Comment by pjcozzi** [comment]
@OmarShehata perhaps a good one for you once the glTF extensions and clipping planes converge?

**Comment by OmarShehata** [comment]
That's really cool! @pjcozzi  Yeah I can propose something and see what people think.
