### ISSUE TITLE
Memory leak in Firefox when using transparent video textures

### ISSUE THREAD

**Issue by dwastberg** [AnalyticalGraphicsInc/cesium#7054]
I've been investigating #4935 and seem to have found a memory leak in Firefox (62.0), so far only tested on Windows 7. After just letting the test case from that issue[0] run for 5-10 minutes, Firefox is using over 8 GB of Memory.  This does not happen in Chrome or in the standard Video showcase in Sandcastle.  I'm not sure if this is a pure Firefox bug or if there is something that can be done on the Cesium side of things.  

[0] https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=88a3a9c6af80ecc95e1b66e32bbf4478

**Comment by hpinkos** [comment]
@mramato @lilleyse any ideas on this one?

**Comment by mramato** [comment]
At first glance, this looks like a straight-up Firefox memory leak and should probably be reported to their issue tracker.  Chrome had a similar issue that was fixed a while ago: https://bugs.chromium.org/p/chromium/issues/detail?id=634012

**Comment by dwastberg** [comment]
So far I've only been able to trigger this on my windows 7 machine at work, but not my windows 10 laptop at home.  However, at the same time, the video isn't transparent in Firefox on my Windows 10 laptop, like it is on my Windows 7 machine (same version of FF).  Perhaps a driver issue?   I'll try to isolate the problem a bit further and report it to the Firefox developers

**Comment by hpinkos** [comment]
@dwastberg Thanks for the update!  I'm going to close this issue since it seems like it's a firefox issue.  Feel free to reopen if it turns out to be something on our end.

**Comment by dwastberg** [comment]
Just a quick update that this has been verified as a Firefox bug (Bug 1493080) and has been reported fixed in Firefox 64.

**Comment by mramato** [comment]
Awesome, thanks for the update @dwastberg!
