### ISSUE TITLE
Point Cloud Sandcastle Example Loads Point Clouds Under the Terrain

### ISSUE THREAD

**Issue by bbehling-trimble** [AnalyticalGraphicsInc/cesium#7063]
Using this example

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Point%20Cloud.html

If a terrain is added, the 3D Tile Point cloud is not clamped to the terrain. 

Is there a setting we need to configure to clamp point clouds to terrain models, or is this a known issue?

Note, using the NYC 3D building models (b3dm) with terrain works fine.

**Comment by hpinkos** [comment]
Hello @bbehling-trimble,  3D Tiles is not terrain aware, so setting the height to match terrain either has to be baked in to the tileset during processing, or can be adjusted using the `modelMatrix` at runtime.

You can see this example for adjusting the tileset height using a `modelMatrix`: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Adjust%20Height.html&label=3D%20Tiles

If you are using [Cesium ion](https://cesium.com/ion) on cesium.com, we recently added a tileset location tool that lets you move the 3D tiles tileset and save the new location so it is set correctly when you stream your tileset from ion to your CesiumJS applications.  To open the tool, select the asset you wish to adjust from the list of assets, then click the `Adjust Tileset Location` button above the preview window on the right side of the screen.

![image](https://user-images.githubusercontent.com/3451886/45963712-ca7ccc00-bff1-11e8-9aa1-8c91b0836d7f.png)

**Comment by bbehling-trimble** [comment]
Hi @hpinkos 

I tried the example you sent. I tried loading the church 3D TileSet with terrain

var tileset = new Cesium.Cesium3DTileset({ url: Cesium.IonResource.fromAssetId(5714) });

Trying different height values, including 5000, the 3d Tileset is still rendered below the terrain.

Do you why this is still happening when setting the Tile Set's Model Matrix property?

**Comment by hpinkos** [comment]
Hi @bbehling-trimble,  

Sorry, I forgot that particular sample church tileset was generated before we made some updates to our point cloud tiling pipeline and cannot be positioned using the model matrix method.  However, this method will work for all point cloud tilesets generated with the current version of our ion point cloud tiler.  I'll make a note to update our sample point cloud model.

**Comment by hpinkos** [comment]
@bbehling-trimble I'm sorry, I was mistaken.  I had written my sample code incorrectly.  You can see an example of how to change the church point cloud height using a `modelMatrix` in [this Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVVNb9s4EP0rhPdgeSHTTupgC8cNtu0WaIFtWiTunnyhpLFMhCKFIenYXeS/71ASbckteloBQTRfbx7fDOW9QLaX8AzI3jANz+w9WOkr/k/jS8Z5Y7432gmpAceT243e6LaC2xw08FKZDHgBtdutwbq3JWVatwZEeiFUhx7aqq7XZ1OAosC/G83o2YEsd27J5hv90uR1FJ60yZ+Md9yhyJ+SU+XkBOaMUZkIzAuT+wq04yW4DwrC67vjpyIZdykN70tcUdfq+E7qQurSnvHTiNtrJBVYcEOJ2n+v/lq3waQ7jke1jCmfjH4AazzmwLdoqreWEonWzR9Xi0na5lfiICtfPeYIoB9rkcMHRINsya7m1wvSpKXRUeAIojh+JSxpgbsd6GTrde6k0UmXMonCDqZUo6ykk3uwXBTFKfd2kPrdmGptYjDtn/Yj9SWdvkqX7x6ELiGZ83nKpnN+k0Z9eGZ8o+ZjvQMEjlTiLfudXfP5JLR6mXBDnPGZyJ95QzjviXVutDUKuDJlF7k9iXA5QZr2l8wC7kWmoD/BcbtU4wm3PrM5yqzXr41NhvtHs733VUY734U7ZeSWJdLei/voP9WFB8F51F3qS6DYqEkrkwt0pkRR72RO2HFnet5mI4KDQuI0vUsNaXgO8DQnQrYet7QlQ9AG41UD+UCqC22TPgNSU5fS+QJSNvQL17lpnP0uZrttN/5/bTLUtrlaSDAhweifNqP5hfvvkpZQGo8/WM5zfjKJ4FHPKmzEZ+FQHs4NWnvRHGV9ZpD02PTWbpSOVtYdFdy10H/KqjbowlVPOJ85qGqqATvLfP5ELXNrI4vf4jeqtzQZfc5KDGNeMiwzkSyuUxb/5vx1rA1PTZeVlmHJFvWh584MFoDT9oL1gy8XbaWuves33wM6mQs1FUqWeskqWRQKfuw4daZesutB1xjKjHOm6kep7WoWJVoVcs9k8WYzuvj12IxYroS1FNl6pR7ld9iM7lYzyh+UKdN8a74QVyWOIWV3dfd36+Scr2Zk/ljVHZnSW04hcvexWbiY3LhbSdyxBirC8CkjXpXUZE2v5nQNgikOZEbLOqiDSa+FcGKa0W8G2XuhPCy7nU5ZY36rKYOc46bL+Exm0NXBwQVcEoCsm1/hNgiR/38).

Hope this helps!

**Comment by bbehling-trimble** [comment]
@hpinkos What was changed from the previous example? Other loading a new tile set, it looks to be the same code.

**Comment by hpinkos** [comment]
@bbehling-trimble yes, it is using the same method to reposition the tileset as the first Sandcastle demo I linked you too

**Comment by bbehling-trimble** [comment]
@hpinkos Do you re-run the church tileset through the new CLI?

**Comment by hpinkos** [comment]
@bbehling-trimble no, that is using the same church tileset.

Here's an example for positioning it direction on terrain without using the slider.  The height of the terrain at that location is approximately 413 meters.

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: Cesium.createWorldTerrain()
});

viewer.scene.globe.depthTestAgainstTerrain = true;


var tileset = new Cesium.Cesium3DTileset({
    url: Cesium.IonResource.fromAssetId(5714),
    maximumScreenSpaceError : 1024
});

tileset.readyPromise.then(function(tileset) {
    var cartographic = Cesium.Cartographic.fromCartesian(tileset.boundingSphere.center);
    var surface = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, 0.0);
    var offset = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, 413.0);
    var translation = Cesium.Cartesian3.subtract(offset, surface, new Cesium.Cartesian3());
    tileset.modelMatrix = Cesium.Matrix4.fromTranslation(translation);
    
    viewer.scene.primitives.add(tileset);
    viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0.0, -0.5, tileset.boundingSphere.radius * 2.0));
}).otherwise(function(error) {
    console.log(error);
});
```
