### ISSUE TITLE
How to locate the 3Dtileset node

### ISSUE THREAD

**Issue by 9lovingly** [AnalyticalGraphicsInc/cesium#7067]
Is there any method to support to loacte the 3Dtileset node by its ID?Thanks !

Thanks for contributing to the Cesium Community!

If you have a question, please search the forum:

http://cesiumjs.org/forum.html

and start a new forum thread, if needed, instead of creating this issue.

Otherwise, we look forward to your bug report or feature request in this issue.

---

Delete this message before clicking Submit.

**Comment by hpinkos** [comment]
@9lovingly no, I don't believe we have a function for selecting a tile by ID.  You would need to traverse the tile hierarchy.

If you're able to, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.
