### ISSUE TITLE
Unit tests take an unacceptable amount of time

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7068]
For years, Cesium unit tests took about ~45 seconds to run.  Within the last 2 months, they have gotten much slower and additionally some testing modes (like WebGL Invalidation) are now basically useless.

I just tried to run the unit tests locally under Chrome and they took 229.713 seconds (and that's using the webGL stub which is the fastest way to test).

So what's changed and how can we fix this?

**Comment by mramato** [comment]
It appears that GroundPrimitive tests, especially texture-related ground primitives may be the main culprit here.  @likangning93 do you know off hand if these are known slow tests?

**Comment by hpinkos** [comment]
Duplicate #6570
