### ISSUE TITLE
Point Cloud Attenuation test failures

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7070]
I'm seeing the following test failures when running the unit tests.  May be Linux only.  Happens in both Chrome and Firefox.

CC @lilleyse 

```
1) modulates attenuation using the baseResolution parameter
     Scene/PointCloud3DTileContent                                              
     Expected 2 to equal 20.
    at <Jasmine>                                                                
    at Specs/Scene/PointCloud3DTileContentSpec.js:574:36                        
    at compare (Specs/addDefaultMatchers.js:274:29)                             
    at <Jasmine>                                                                
    at Specs/Scene/PointCloud3DTileContentSpec.js:573:27

2) modulates attenuation using the geometricErrorScale parameter
     Scene/PointCloud3DTileContent
     Expected 2 to equal 20.
    at <Jasmine>
    at Specs/Scene/PointCloud3DTileContentSpec.js:587:36
    at compare (Specs/addDefaultMatchers.js:274:29)
    at <Jasmine>
    at Specs/Scene/PointCloud3DTileContentSpec.js:586:27
```

### WebGL Report

Platform:	Linux x86_64
Browser User Agent:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Intel Open Source Technology Center
Unmasked Renderer:	Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)
Antialiasing:	Available
ANGLE:	No
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	4096
Max Vertex Texture Image Units:	32
Max Varying Vectors:	32
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range:	[1, 7.375]
Aliased Point Size Range:	[1, 255]
Fragment Shader
Max Fragment Uniform Vectors:	4096
Max Texture Image Units:	32
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	16384
Max Viewport Dimensions:	[16384, 16384]
Textures
Max Texture Size:	16384
Max Cube Map Texture Size:	16384
Max Combined Texture Image Units:	192
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

**Comment by hpinkos** [comment]
I see the same model test failure on my machine (Windows 10).  Who can look at this before the release?  @likangning93? @ggetz?

**Comment by hpinkos** [comment]
I'm going to open a separate issue for the model test failure since I'm seeing it too and mark in 'next-release'

**Comment by pjcozzi** [comment]
Perhaps @loshjawrence could look at the point cloud tests to keep folks on the critical path elsewhere focused?
