### ISSUE TITLE
glTF 2.0 Model Test Failure

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7073]
Both @mramato and I are seeing this test failure.  Can someone please look at this before the release on Monday? @lilleyse @likangning93 @ggetz @OmarShehata 

```
loads a glTF 2.0 model
     Scene/Model
     Expected to render [169,3,3,255], but actually rendered [170,6,6,255].
    at <Jasmine>
    at Specs/Scene/ModelSpec.js:948:27
    at Promise.then (Source/ThirdParty/when.js:196:34)
    at Source/ThirdParty/when.js:297:13
    at processQueue (Source/ThirdParty/when.js:647:4)
```

**Comment by pjcozzi** [comment]
@OmarShehata could you please take a first look?  Potentially a trivial change to adjust the test if we deem nothing broke.

**Comment by likangning93** [comment]
Wonder if this is related to https://github.com/AnalyticalGraphicsInc/cesium/pull/6877

**Comment by lilleyse** [comment]
Yeah I think it's just a matter of the test being too strict, since the rendered color may vary between systems. Usually checking that the color is within some loose range is good enough.
