### ISSUE TITLE
Travis builds failing but no errors

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7076]
It looks like some builds fail but there's no error reported in any of the steps.  This could be a travis issue but has been going on for some time. CC @lilleyse since he noticed it as well.

Example: https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/433554471?utm_source=github_status&utm_medium=notification

I also notice that the log is not properly folding makeZipFile step, which would be related.  We could try removing all folds temporarily in a branch to see if the problem goes away.

**Comment by hpinkos** [comment]
Yep, noticed this as well.  Between this and #6230 I feel like travis is failing more often than it's passing

**Comment by mramato** [comment]
#6230 is probably a bizarre race condition in our build process so at least it's fixable on our end.

**Comment by hpinkos** [comment]
This is failing most of my branches 😖

**Comment by mramato** [comment]
FYI, I emailed travis support to see if they have any ideas.

**Comment by mramato** [comment]
@hpinkos do you have any more recent links to logs showing this happening?

**Comment by hpinkos** [comment]
Yeah I just saw this again yesterday.  I'll try to find which branch, I don't remember off the top of my head

**Comment by hpinkos** [comment]
https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/446199002

**Comment by hpinkos** [comment]
@mramato https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/446758609

**Comment by mramato** [comment]
Thanks, I replied to Travis support with the new info.
