### ISSUE TITLE
Draco Compressed Model doesn't work in Edge.

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7079]
localhost:8080/Apps/Sandcastle/index.html?src=3D%20Models.html

The Draco Compressed Model doesn't work in Edge.  The model doesn't appear in the scene, and I see this message in the console: `WEBGL11025: INVALID_VALUE: drawElements: Negative count or offset.`

Surprisingly it works in IE.  And also Firefox and Chrome.

This works in 1.49, so this is a recent regression and needs to be fixed before the release on Monday.

@lilleyse @OmarShehata @ggetz

**Comment by hpinkos** [comment]
The NYC 3D tileset doesn't work in Edge either.  It's the same error in the console so I'm assuming it's the same problem.

**Comment by OmarShehata** [comment]
I've tracked it down to this commit which removes adding a default value for `byteOffset`:

https://github.com/AnalyticalGraphicsInc/gltf-pipeline/commit/9e228c9d71e2cf652bb5a51f84ee3455cea349b6#diff-0235c130212493cbf91de44aaf8c8906

This is what causes the division in `Model.js:2910` to be `NaN`. @lilleyse is there not supposed to be a default byteOffset in this case? Should Model.js check if `byteOffset` is defined, not just if `ix` (the accessor) is defined?
