### ISSUE TITLE
Drill picking completely broken

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7081]
This happens in master but not in 1.49 so it needs to be fixed before the release on Monday

This drill picking example causes the browser to hang.

http://localhost:8080/Apps/Sandcastle/index.html?src=Picking.html&label=All

@lilleyse @bagnell

**Comment by lilleyse** [comment]
This is related to https://github.com/AnalyticalGraphicsInc/cesium/pull/7069. I'm looking into it.

**Comment by mramato** [comment]
Spoke with @lilleyse offline, my preference is to revert #7069 and revisit it in the context of #6934 (since it's such a small change anyway).
