### ISSUE TITLE
3d Tile mixed refinement not completing, causing face culling

### ISSUE THREAD

**Issue by Stuv42** [AnalyticalGraphicsInc/cesium#7084]
I'm trying out the current master, was previously working well on 1.48 and below. With skip lods turned on I'm finding the parent tile is never disabled even once loading completes. This normally has the culling effect only while loading as detailed in https://github.com/AnalyticalGraphicsInc/cesium/issues/6415 since the parent and child tiles are mixed. 

This is a view from inside an object after tiles are done loading. Everything in the distance on the left half being culled because it intersects with the parent tile (the right side of the object is outside this parent tile and shows through correctly)
![cesium_view](https://user-images.githubusercontent.com/11517757/46138276-0fb52e00-c27e-11e8-8400-d3055d593c25.jpg)

Freezing the render to get a top view with bounding boxes on, shows the parent tile in yellow indicating its still refining:
![cesiumyellowbounding](https://user-images.githubusercontent.com/11517757/46138529-af72bc00-c27e-11e8-8db4-23d10621856e.jpg)

This is how it should look, with the red parent tile gone and not causing culling. Interestingly moving the camera around very slightly can get the correct result depending on the direction. 
![cesium_goodview](https://user-images.githubusercontent.com/11517757/46138799-7555ea00-c27f-11e8-8649-bc86ec57bdf0.jpg)

**Comment by mramato** [comment]
Thanks for the report @Stuv42 

@lilleyse any ideas here?  Does anyone else know the tile refinement code as well as you that could look at this while you're finishing up the sample PR?  This sounds like a regression that we would need to fix before the next release.  I'll tag it, but feel free to remove the label once triaged.

**Comment by lilleyse** [comment]
There's one commit I'd want to try reverting: https://github.com/AnalyticalGraphicsInc/cesium/pull/6390/commits/4fc6f7e9652a1535cd37ca4ef1e5014da2495bcc

I haven't been able to trigger this problem in other tilesets yet. @Stuv42 is there a chance you could send over the tileset for testing? My email is sean@cesium.com if you don't want to share it publicly.

**Comment by lilleyse** [comment]
Thanks for sending over the tileset @Stuv42. I opened a fix here: #7099.

**Comment by Stuv42** [comment]
Thanks for the update @lilleyse, it seems to have fixed the issue in 99% of cases. I've found it was still occurring in the spot above and taking a closer look its because some json files have no content, but have children. This is happens here due to small floating artifacts in quadrants that don't have a model at medium detail, but still require a json file for that quadrant since zooming further will bring their children into view.

![floating](https://user-images.githubusercontent.com/11517757/46454779-80a69980-c7da-11e8-99cc-d730e33b6f67.jpg)
Example from our data set of floating polygons

![lods](https://user-images.githubusercontent.com/11517757/46454734-39200d80-c7da-11e8-84cf-2379ea185e04.jpg)
The topleft of lod 2 only has a json with no model, but its children can have models as shown in lod 3

**Comment by lilleyse** [comment]
I see why that would be happening. Technically the behavior right now is expected, the external tileset root (empty) meets the screen space error and doesn't traverse to its children, but since it's empty it selects back up. I'll have to recheck what the old traversal did, but to avoid those sorts of issues I'm starting to think empty tiles should always traverse even if they meet screen space error.

Was that section part of the tileset you originally sent over? If not could you send those tiles over too?

I think the fix would be:

```js
    function canTraverse(tileset, tile) {
        if (tile.children.length === 0) {
            return false;
        }
        if (tile.hasTilesetContent) {
            // Traverse external tileset to visit its root tile
            // Don't traverse if the subtree is expired because it will be destroyed
            return !tile.contentExpired;
        }
        return tile._screenSpaceError > tileset._maximumScreenSpaceError;
    }
```

to

```js
    function canTraverse(tileset, tile) {
        if (tile.children.length === 0) {
            return false;
        }
        if (tile.hasEmptyContent) {
            return true;
        }
        if (tile.hasTilesetContent) {
            // Traverse external tileset to visit its root tile
            // Don't traverse if the subtree is expired because it will be destroyed
            return !tile.contentExpired;
        }
        return tile._screenSpaceError > tileset._maximumScreenSpaceError;
    }
```
