### ISSUE TITLE
Create a trackedTileset property?

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7086]
This [just came up on the forum](https://groups.google.com/d/msg/cesium-dev/uc1SoWvzBks/gMEGPsScCwAJ). You can currently set the trackedEntity to a tileset, and the camera will zoom to it but won't stay there. 

It sounds like it would be a pretty useful thing to have to be able to track tilesets in the same way as entities. I think it would only need a small tweak to `EntityView.js`. The question is, what would be the cleanest way to do it? Renaming `trackedEntity` to something more general?

**Comment by hpinkos** [comment]
From an API standpoint, I've been wondering if there is confusion between using `scene.primitives.add` to add 3D tiles and `viewer.entites.add` to add pretty much everything else.  I would if it would make sense to add 3D tiles to the Entity API.  @mramato what are your thoughts on this?

**Comment by pjcozzi** [comment]
Please discuss with me before moving forward with it...and I also would not consider this a priority now.

**Comment by OmarShehata** [comment]
This is related, slightly different, but potentially more useful: being able to zoomTo or flyTo features in 3D Tiles. Use case is described [in this forum thread]():

>  Consider the following workflow:
> 1. Instantiate a 3D tiles tileset, each model of which is batched and contains per-feature information
> 2. Manually pan and zoom around the scene to a particular part of the tileset
> 3. Click on a feature in a model in the tileset. The click is caught via:
    let new_feature = this.viewer.scene.drillPick(movement.endPosition, 1 /* number of items max */);
> 4. Attempt to zoom to that feature. Options considered include this.viewer.zoomTo(new_feature.primitive);, but this zooms to the entire tileset or model.

**Comment by OmarShehata** [comment]
You can now add 3D Tiles through the entity API as of https://github.com/AnalyticalGraphicsInc/cesium/pull/8580! So you can now do:

```
var viewer = new Cesium.Viewer('cesiumContainer');
var tilesetEntity = viewer.entities.add({
    tileset: {
        uri: Cesium.IonResource.fromAssetId(5741)
    }
});
viewer.flyTo(tilesetEntity);
```

Which solves the flyTo and tracking issue presented here.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/uc1SoWvzBks/gMEGPsScCwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7086 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
