### ISSUE TITLE
"npm run build" prints error in console for forks of Cesium

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7090]
I see this printed out to the console when I run `npm run build` in a fork of Cesium because it doesn't have our tags.  My first immediate reaction was "oh no, why did the build fail?".  Is there anything we can do to avoid having "fatal" printed out to the console?  Can we check if the tag exists before making the diff call?  Otherwise, maybe we should print out a message saying to ignore that failure, the build is fine.

```
fatal: ambiguous argument '1.48': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Failed to retrieve list of new Sandcastle demos from Git.
```

**Comment by zbennett10** [comment]
Just did a clean fork and build and couldn't reproduce this.

**Comment by hpinkos** [comment]
Hmm, thanks @zbennett10!  The build still succeeds even when this error prints out so it doesn't effect anything.  I just think it's a little confusing to see that in the console.  I'll have to double check to see if it still happens for me.

**Comment by emackey** [comment]
I think a new clean fork includes new tags.  This problem likely affects forks only after they get old enough to be missing a couple release tags.

**Comment by mramato** [comment]
We should fix this, or at least print a more useful informational messege so users don't think it's an error.
