### ISSUE TITLE
Can we use Vector tiles with Cesium Map?

### ISSUE THREAD

**Issue by munna** [AnalyticalGraphicsInc/cesium#7096]
I want to use **Vector Tile** with Cesium Map. If not, is there anyway to render 3D on cesium map using GeoServer . 

Loading hug amount of json/topojson is crashing cesium map .

**Comment by hpinkos** [comment]
Hello @munna, Cesium suppports an experimental 3D tiles vector format.  You can find more information about that here: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/3d-tiles-next/TileFormats/VectorData

If you have follow up questions about this, please ask on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!f

**Comment by hpinkos** [comment]
@munna I don't think there are any tools that are publicly available, but you can send an email to tim@cesium.com to ask about the beta version of our vector tiler.
