### ISSUE TITLE
Sandcastle ClampToTerrain sample fails to load CesiumWorldTerrain in Google Chrome Canary

### ISSUE THREAD

**Issue by cherukumilli** [AnalyticalGraphicsInc/cesium#7109]
Steps to recreate the problem:
1. Open Google Chrome Canary
2. Open Chrome Developer tools
3. Browse to the ClampToTerrian Sandcastle sample: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clamp%20to%20Terrain.html

You will see that the CesiumWorldTerrain is not loaded.

Also in the developer tools console, you will see the following errors:
`OPTIONS https://assets.cesium.com/1/layer.json 401 (InvalidCredentials)`

`Access to XMLHttpRequest at 'https://assets.cesium.com/1/layer.json' from origin 'https://cesiumjs.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

I wonder if this has anything to do with the site isolation by default feature in Chrome 70+.

Please see the screenshot for the same:
![screen shot 2018-10-02 at 7 56 16 am](https://user-images.githubusercontent.com/5217007/46350204-be0ff900-c619-11e8-8bfa-5ce333cef47c.png)

**Comment by cherukumilli** [comment]
The ClampToTerrain sample loads successfully in Chrome 69 **but not in Chrome Canary (Version 71.0.3568.0)**. 
I am encountering the same problem when I load my app in Chrome Canary.

**Comment by mramato** [comment]
> 1. Open Google Chrome Canary

Thanks for the report, this is a known regression in Google Chrome Canary and they have a bug on their end about it here: https://bugs.chromium.org/p/chromium/issues/detail?id=889004

I'll leave this open for now in case others in the community run into the same issue.

**Comment by cherukumilli** [comment]
@mramato 
I see you guys posted some more questions to google about the chromium bug.
Looks like Chrome 70 will land today or tomorrow as per https://techcrunch.com/2018/10/08/chrome-hundreds-of-sites-to-break/

is there a work around other than disabling the terrain provider for now?

**Comment by mramato** [comment]
@cherukumilli Thank for the heads up, the issue I linked to is marked as `ReleaseBlock-Stable`, so Chrome 70 can't go out until it's addressed one way or another.

That being said, we have a separate change that is being deployed to production later today, so that will mitigate the issue whether they decide to do anything about it on their end.  I'll bump/close this issue once that is in place.

**Comment by mramato** [comment]
While Chrome 70 stable did indeed come out today, it does not have the regression which was causing terrain not to load.

At the same time, the change I mentioned above is now live on our servers anyway, so everything is working as expected in Canary, even with the change.

@cherukumilli I'm going to close this, but please let me know if you are still having issues.  Thanks.

**Comment by cherukumilli** [comment]
@mramato 
Chrome 70 started rolling out today. I just checked my browser version and I got upgraded to chrome 70. Everything is working fine though. Looks like your production push fixed the problem on my side. :)
