### ISSUE TITLE
scene.clampToHeight breaks pickPosition

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#7111]
Clamping an entity position breaks `pickPosition`.

@lilleyse Any ideas?

[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=nVdtc+I2EP4rvnzBtJww73BJrs0Ld8lMcskEN51O6XQUW4AaWfJIMkmuw3/vyrKNbeCuLZMJRrv77K722ZW8xtJZU/JCpHPqcPLiXBBFkwg9pmtuI0h/XgiuMeVENlrO33PuwEcTKWHpXoo1DcH6Q24ZSII1+VVIFvpWx23O+aZ5POdrcKYCwgn4sk5R+jMTBUwEz1tR+hNEVki4pvot04yFopoK4z0mslgOscYzkciAgCCiyvjJorr4GrHLQoyYwKHbQKhd/J3FsWrPcBQzYvTaFwyeffFZioSHKADzRpqCjW3rSSEchu6O5ybSK8LdRcIDE2hJoZnvoM0IQtzKULpGAXRJ9PnbNcRo47+l7NmXSfCcBmGs61sAOBYQ5ZLjbNft3mjKiCIa1NItR7GkEaitswQsaIkA9qt36Vs7NwvafBLJimpfC/5AlA1+AamfKVCGuIfeqN+0Jhv4zuLICosjIjECRcOyHDkkSlOOTeQfKoFgqeEJ857b6XaGfa+HxuP+YDAedseDlvO+P+oNe4MR6k96vUGnN4G1vjfudCcTNOoMhpPxpD9ptqwPISls0q6PK4JDypf3VAerB8GY20fd8aTb7YwAaeyNx94QPHmoP5pMvJHX6Y8GXhf+Ws4QdUeT0XjSGY3G/V6v08tdER76EnO1EDLaNsct1pK+9tH15fSLf+3/VpSILhzXFiawxLsidLnSsySOBeQfFqzJ6ogoh+phlpbnBthMQlPH6Rryu6FKA5J0lYa9M/gbhzDohgwiEFwJZppg6Tb8FVXOkxQvCpo4FEQ5XGhHWb9OJRiUkm9jws157aQu3CK6tGeRWomEhWecRjAJgHFaJiSjraGiePqLBFr5YvoasCQ0Gr9b7v6RaWUUFUo/wD4CZXZSKxqrcJ2j5/QH1HqPmK56xCwhro0zSKQEUJ9GJG+rbWOiEtCeyri5uLWTT461KbbLxLXCPGREptWewXOAlYYiQGa+EOwJy/NEa0iocU9hCuboMHB3UzVwDD8RNs1HSNZZxfgwLV3al1QZWFhaSrd5JV5gdYGBHK1d0TkOnpfp/AMlU8OazgJOBZA0Ov341YkEFyrGAWnUtFbQdF/N+cHuJF1Svm2Gq5oE3Uw/+TXrNdSNBru2j5V15N/d1wxj+krY3WJhZt7+edJ1OzArvObWblOqm31st51bkUDrCAjEgZHuLJl4Io4WjiIkXQgATywljlc0KMpmrbOSV0/WGRyQhM/MVqWUvrJKefdjIIvKGZQBmFF5zeNEn1kiFIyIIKwIMFJmVNtgYep2v6VwWuTjutaB0zhX2U6lSECfvjs93WYBq7ewiG7vHu6vrr98btbZtTWOgdF5KLsTrVJucw3IC1SLqwJTpA6cL9JsVvIrx5FFHZIF3GJCt3DR3BtFOZKitKdlAuWr6ZlXMKqEe3wYlQm+pBrmxAzOAr7cAsPhsEJaXJIlMES5Ze+oMIKLhfgE3A7d7jedwCH3n31kNv/SxcqeULmDCpSVVXH2I5XmWHniFjt5/H2z9Bmlw6xy1nzfRpNXuBHt1zafxo25KDScHx23YX7CQ616TaQYDYj7ftQEYWM+Tzzv3APFb4DO5/wG6zpupWD/E/aM1WHLRaqBRo1/VRS7U+SNZMP09MDlzEMeTFPz7/0eKjg/VCbJ6b5JMruYfpl2L52fnA4awNDuIK95mDj1AXeg8Jvq0qYy7auT7l0FcmcyHKRcPlrrx0jr0Mj332IzN3+ZTf+8vXucNvOb+lHr6ETpN0Y+WoSfaZTewuDC7cIriibwdgI3KtV+gjcBuAMGKj0pTtq50UlI1w4NT+dHtfe2+ZG5yikFkkXC2Ix+JfOjjydt0K+YmfciYModnHYMvxmVVefjjV1ECJ204eeulbYXmBLiPw)

**Comment by hpinkos** [comment]
Related? https://github.com/AnalyticalGraphicsInc/cesium/issues/7092#issuecomment-426105750
