### ISSUE TITLE
Clamped polyline flickers when updating property

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7119]
This [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1Vbbbts4EP0VwS91gCxN3S3XCRZx0kUAtwGaYF/qoqApSiZKiQZJOXWC/vsOdbNct4BR7EtpwwZneIbDM2co7Yhy6EshnCvn06p0YLw2f3asRjxdjWbwn0paFaw0q9Hl0F2SgjULltKw4gfvjinNZdkscBFejRrv93bV62ADQ1TOjAsRjsI+Dc1bqblpA1osJcrIXJHthtNblivGtHV9ApcfoCkOw9CLmzFtIvguSnwcB/2IrB07nyEncK+5EGtJVNrtwAuSt5kgNKlnerJgmlfFl6XM5RcJZxRkj7Zl3uygKRE1wutnN/tbrg0pKevCloyod0Q9gpeoJuUQQx7Iv3R8XA87c21e9vNLvryf8+X9Hl+Bd2DJjfzAjdox/bNZ8n/Okv87LIGUkqQnZqCqqddb4z+DLmjRE8Le75eSEkvHPbWUHPNW7MWJ92z6rMQgE+8cas5nZiOfLdioitm5koZ02fzloyDBUTgNsZ9Mp1GYHHHp/m9c2kCCrJno4BmcayGFVJ1B5WvShAGcF4aHn46KTNrLtb4o8dY4y4rylDgLWWopmHMjRdoceCMVf4G1RDwonvP2cl3cfXi6+9gWhH9j4iHLNDPDmgCLpPQGSXQ7a7MXbX3f3S+XTRDDvrXp+N4MY/gi/MFxsB/MgngWJihJ7g4VuCH0a65kVabDWqx766+5aL4tDy2XJ6LM5O5HJfamrRR7wcu+cp0c9Tl6jKeeH7sBTlzsRlBZ6OPATzD23CRMojiqkxvotp7Eseu5fpSEgZt4HSr2I1BaEoInHgi8IIYpTnphQDH5MRv0fJl0Unvmqdn0twEVpNg+yX9O6B+2hvO9ffJ+frsqV+UOHvo7zp6Zgsd+yZ6dpsfQv7Vt/IbW04WVGVCr3lzUqCaExSpGoV1yEOZVB/3YmVCmZNESPQa6cM1QWFNnf32Em3B1sHpDRKGuiqBM7J/kePD+kTJteFk3tDM77Nqe5aI/i32BeTSKkeL4PAuw3xJDHmWlKBtbQLtj2ls1Imk6PkRookLz3JdQux0R46wqqU1hfPE62AltlQS0rqEXb21pXNwebXQ5mtdtdd2k+jcvtlIZp1JiDBcbvCltBShDT9YV/coMolpb4HzSgeYp3zk8vYLyHpdiNXKg4FqDJ6uEeOQvoPzr+QTWH8GEJCkv84fmvrRLNu71sjEihOYTmJ6ijJRibS+83vcf) continually processes the same CZML packet. Since the polyline already exists, it shouldn't be flickering.

In fact, this is fixed by setting `clampToGround` to false in the CZML. It seems like just supplying this property forces the ground polyline to be recreated? 

This [came up on the forum](https://groups.google.com/forum/#!topic/cesium-dev/Y0YHGBWMgds).

**Comment by hpinkos** [comment]
This is working as expected.  A new polyline is being created each time `czml.process` is being called.  It's just not noticable without `clampToGround` because non-clamped polyllines are so much faster to draw.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/Y0YHGBWMgds

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7119 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
