### ISSUE TITLE
iOS - Local nodejs-cordova - memory leak 

### ISSUE THREAD

**Issue by andreddosantos** [AnalyticalGraphicsInc/cesium#7127]
Hello guys,

I'm using a nodejs-cordova plugin "https://github.com/janeasystems/nodejs-mobile-cordova" to load the tilesets on cesium when offline, the code for my server.js is this one "https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/blob/master/server.js".

My tileset has about 300mb and it is loaded with the example also provided in "AnalyticalGraphicsInc/3d-tiles-samples"
```
    const viewer = new Cesium.Viewer(this.el.nativeElement, {
      scene3DOnly: true,
      selectionIndicator: false,
      animation: false,
      timeline: false,

      baseLayerPicker: false,
      fullscreenButton: false,
      vrButton: false
    });

    const tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({ url: 'http://localhost:3000/tileset.json' }));

    viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0, -0.5, 0));
```

After scrolling for a bit in my iOS mobile (iPhone 8), in the Xcode console i start having warnings like this:

> CDVNodeJS onMemoryWarning

and if  i continue scrolling the app crashes:

> 2018-10-09 20:55:18.480827+0100 [4400:272850] [default] LaunchServices: disconnect event (invalidation) received for service com.apple.lsd.mapdb
> 2018-10-09 20:55:18.502101+0100 [4400:277831] [ProcessSuspension]  0x1d406f740 - ProcessAssertion() Unable to acquire assertion for process with PID 0
> 2018-10-09 20:55:19.167674+0100 [4400:271020] -[CDVNodeJS onReset]

Besides this i keep having this error: "DeveloperError: normalized result is not a number".

The cesium version I'm using is the 1.50.

Regards 
André

**Comment by lilleyse** [comment]
3D Tiles uses a pretty large tile cache by default. You may want to set [maximumMemoryUsage](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#maximumMemoryUsage) to something lower, like 128.

Also increasing [maximumScreenSpaceError](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#maximumScreenSpaceError) will load less tiles overall, but draw less detailed tiles. The default is 16, but you could try something between 20 and 30.

**Comment by andreddosantos** [comment]
This definitely solved my memory issue!

"DeveloperError" - with less frequency but sill shows up.

Thank you very much

**Comment by andreddosantos** [comment]
Hello @lilleyse,

Everything was perfect until i've loaded on the ios a 7gb tileset file. Now it just crashes again.

> [ProcessSuspension]  0x281315440 - ProcessAssertion() Unable to acquire assertion for process with PID 0

It seems like memory issues again. I've been playing around with the variables above but nothing solves it.

**Comment by lilleyse** [comment]
You could try adding the 3D Tiles Inspector to see how much memory the tileset is using. It shows up at the bottom of Logging->Statistics. [Example code here.](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Inspector.html&label=All)

What values are you using for `maximumMemoryUsage` and `maximumScreenSpaceError`?
