### ISSUE TITLE
Bing Maps imagerySets AerialWithLabels and Road are deprecated

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#7128]
Making a note of this since I happened to stumble across this.

https://msdn.microsoft.com/en-us/library/ff701716.aspx

> AerialWithLabels (Deprecated): Aerial imagery with a road overlay, using the legacy static tile service. This service is deprecated and current data will not be refreshed. New applications should instead use AerialWithLabelsOnDemand.

> Road (Deprecated): Roads without additional imagery, using the legacy static tile service. This service is deprecated and current data will not be refreshed. New applications should instead use RoadOnDemand. 

I quickly tested locally and simply changing the `imagerySet` string (which is taken from the values of the `BingMapsStyle` enum) works correctly.  I have not done any side-by-side comparisons.

**Comment by OmarShehata** [comment]
Is this why click "Bing Maps Road" in this Sandcastle is failing to load? @mramato 

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers%20Manipulation.html

**Comment by mramato** [comment]
@OmarShehata no, that's a separate issue, please submit a bug.

**Comment by zdefne-usgs** [comment]
@mramato and @OmarShehata 

> Is this why click "Bing Maps Road" in this Sandcastle is failing to load? @mramato
> 
> https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers%20Manipulation.html

I might be having a similar issue. Bing Aerial displays with a cesium key but Bing Aerial wihth Labels On Demand and Road On Demand don't. Was there any further discussion on this? I couldn't find anything more. Maybe you can point me in the right direction? Thanks!

**Comment by mramato** [comment]
There's actually a bug in that demo.  Cesium does not ship with a Bing key so you can't use Bing directly, it has to be via the ion asset identifier. If you have your own Bing key, everything works fine.  If you load Bing via ion, it also works fine.

I was about to write up an issue, but it turns out we have one #7524, I'll bump it and hopefully someone will get to it.
