### ISSUE TITLE
If depth detection is turned on, (viewer.scene.globe.depthTestAgainstTerrain = true). Then (classificationType = Cesium.ClassificationType.CESIUM_3D_TILE) is invalid, is there a way to solve it?

### ISSUE THREAD

**Issue by GoodLuckIce** [AnalyticalGraphicsInc/cesium#7138]
If depth detection is turned on, (viewer.scene.globe.depthTestAgainstTerrain = true). Then (classificationType = Cesium.ClassificationType.CESIUM_3D_TILE) is invalid, is there a way to solve it?
![image](https://user-images.githubusercontent.com/9364696/46790720-2a090480-cd72-11e8-9b0b-93e10fa77f08.png)

**Comment by lilleyse** [comment]
Thanks for the report @GoodLuckIce. This is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/6568 which we hope to fix as part of the effort to enable terrain by default.
