### ISSUE TITLE
Ground Polyline Primitive has gaps around IDL and Prime Meridian

### ISSUE THREAD

**Issue by shehzan10** [AnalyticalGraphicsInc/cesium#7144]
Sandcastle example: [Drawing on Terrain](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=tVdtb9s2EP4rRL5YBjzZaZe9NG6w1PEaY3ZjxG6DrSkSRjpbRGlSICk73pD/vqMoyaLtOg2G+Usi3gvvnnvuSC6pIksGK1DkLRGwIj3QLFuEn/K1oBHlnz0pDGUCVKNFyD+3guBPA4fIMCkGImYRNVKRN2RGuYaWU2BiJt/Jx61VA0qhq7GSSxaDtSl2jBRQAzdS8XjqdILmrXhqnt4KF2AIjwZEHBT6btF9DIROMRipRuyRCWtSGbkEblg8BxNq3ATEJKUR9JcgzCUVMUclBQu5hIFIM3Oe51RuMtkymK5TCIf936d3F1cf3w37d73hoPeH3XCWidySuDzGkgkTrGw2Y6mZlTRL5JaIeWrlCHmZmjCoAzqkcRwUavaXFrYIk+erVVexnt6QmpX9RZLLGro9+xneXA6m/ZavmLJH4BP2N6DyyZYsATZPzDXMQIGIoPJ26a+HveH5aHw3vbp7f3318cPFxsmT+zevov1HgcmUcDHjEootGLGiKybmIxkDQtLgyLRGHVIrnyQ0haDE44Ia6uGprbjYhM1I4Ll8Wzpt1lHKTZ4vgcOYr62DXZjrRdIorgfY2lWNOF2kU/leyUzEqG5UBnvUViw2CYpf+6KnGrAlosUaYIftT9zGPpfiP+WO9nszTxgoqqJk/WziC+wJxSh/Ux8yOSlHhQQnQgrKrINdxoYrZpJzniY06IQ/N5vfjUpBt5IcBd0osmoJOaHyNtUIxOcvpzvCYmXGJTUI6bggrV1L3ODwZ+Zk/3QJyklE0VTbCAvrUIOpz5yS7wFY66pe7Ta5AZJhfe8LTzoCAWHKoq/lPLjHVlVIAKEN0JjIWaUb0QXWKFfuc85SLVl8T7QkJqGm2mAFBOcjrgEODqVwlhZzZZWAIAuZaQSA4IxU5QAPN70HVJmkjGRDqt0oXWJhSZWyWLj/vefjHhuAc/KAWYsYZth4seW2zFQeCuapiZCmiAdjnnP5AOGm+4uCFLaB57zpNYLV3uFDyEHMsQFt/3Sa28T3+IDp1ge+v9Opb7i7T5rp5LBNPh7Xgi5YNK7GjMe6HuX8gSLIZf9UYzNo7uvZoid2gtna+Knlju0DSWAcm8m8HWTdrtahL8XgWXDRN4b67HFdndMv7b49dPII4NPJlgtr84JmwBvNvrz3bFvz2zxMyqrDbI6fKM/AM36eljINvpO83/D79L3FGV19nPTvRlef+tYcJ8E1WE7lXe0OKRxVzDRcwxckI1hB4u5suWK5nBuEtYsDzqoFE0ggx9EKtcMpb0i9o1eqbJ+bLpgtZhzWrfkuNbcnSzX9TnfCPiz1j7Wnl3J+G7bTZ8t4PXh/6TWZbQSZluPqc+X40V5VGxe2xEOMXTeKuwLq5e8J+1oog/JIviemUvSN6+OGgPt2H7trzf8RQHnjqsXwJQdlglWIqDYc7EVrKiUObjUCkQUFVEUP/CXlAs9yYiQynVAcgcTegOzhl7/D9OZ14053LuXXc1PdnHBO4n9UvA5nSi4uYI4V08EPx69eha86J7+0yI8/hce/npy0yHGn0wk7zZZ/oJTmwUkubhH/b7P2JvMCmCoq9EyqRRkJ3u0Ue/wxHFz0P0wH0z+t4VHrqKvNmsOZg+c3tkilMiRTPAjDtoFFyhFl3X7Ioq/4Zot0Dku3XRp1Y7YkLH57e7T1OL09svdrrVEyy3j+prk9Ouu2Ud8zwy6LsVxXeHvgdG1VkuOzoVsMw7Dbxs9dK+PKheou7q6hDxyqHe1rd0wF8ErBKT3IeO0tqDN/sHZNfDaEmUFPeDrkNY9jQglGh4TFaFBes2/7Dvb7u7bPs41DbbCkeYndhDzsEz9rQeOXzdNCUUDyLw)

Browser: Tested Chrome and Firefox, but appears to be all.

Operating System: Tested Windows, but I assume it's all.

There are gaps when drawing on terrain with `GroundPolylinePrimitive` along IDL and Prime meridian.

The gaps always happen on the other side of the line, ie. if you start from west of PM towards east, then the gap is on east of PM and vice versa.

Sample images:
Gap along prime meridian:
![image](https://user-images.githubusercontent.com/2288659/46877815-b584a300-ce0f-11e8-9aaa-f8c34a363c1d.png)

Gap along prime meridian (with terrain tiles boudaries):
![image](https://user-images.githubusercontent.com/2288659/46877818-b9b0c080-ce0f-11e8-836a-bb0be5903349.png)

Gap along IDL:
![image](https://user-images.githubusercontent.com/2288659/46877823-bd444780-ce0f-11e8-8e61-2704d1229319.png)

Gap along IDL (with terrain tiles boudaries):
![image](https://user-images.githubusercontent.com/2288659/46877827-c0d7ce80-ce0f-11e8-8dee-360ff06b8cb6.png)

**Comment by hpinkos** [comment]
CC @likangning93

**Comment by wangtengwei0707** [comment]
this bug have been solved?

**Comment by wangtengwei0707** [comment]
@likangning93   i find this bug in cesium1.55

**Comment by wangtengwei0707** [comment]
@shehzan10  hey,bro,have you solved this bug?

**Comment by hpinkos** [comment]
I no longer see this issue
