### ISSUE TITLE
Help! How to change direction of a gtlf model dynamically with js?

### ISSUE THREAD

**Issue by addriumruss** [AnalyticalGraphicsInc/cesium#7147]
Hi, 
can anyone help guiding me how to change the direction dynamically in js? 
here is my code and it doesn't wok:

/******   this is the drone definition, run once  **********/
// Load a drone flight path from a CZML file
    var dronePromise = Cesium.CzmlDataSource.load('./SampleData/sampleFlight_nj.czml');
    // Save a new drone model entity
    dronePromise.then(function(dataSource) {
        viewer.dataSources.add(dataSource);

        // Get the entity using the id defined in the CZML data
        var drone = dataSource.entities.getById('Aircraft/Aircraft1');
        // Attach a 3D model
            drone.model = {
                uri: './SampleData/models/CesiumDrone.gltf',
                minimumPixelSize: minDroneSize,
                maximumScale: 300,
                silhouetteColor: Cesium.Color.GREEN,
                silhouetteSize: 1,
                asynchronous: true,
                allowPicking: true
            };
       
        var startLgt = globalStatusList[0][idx].longitude; //start location
        var startLat = globalStatusList[0][idx].latitude; //start location
        drone.position = Cesium.Cartesian3.fromDegrees(startLgt, startLat, 50);
        // Add computed orientation based on sampled positions
        drone.orientation = new Cesium.VelocityOrientationProperty(drone.position);

        drone.viewFrom = new Cesium.Cartesian3(0, 0, 0);
});

/******   this is the location update, run periodically  **********/
status={ new location };
drone.position = Cesium.Cartesian3.fromDegrees(status.longitude, status.latitude, currentHeight);
drone.orientation = new  Cesium.VelocityOrientationProperty(drone.position);

var heading = getTrueHeading(32.0872995538, 118.8189582497, 32.0983180084, 118.8429116101);
        var pitch = Cesium.Math.toRadians(0.0); //getPitch(status.utmX, status.utmY, status.utmZ);
        var roll = Cesium.Math.toRadians(0.0);
        var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
        var orientation = new Cesium.Quaternion();
        Cesium.Quaternion.fromHeadingPitchRoll(hpr, orientation);
        drone.orientation = orientation;
        console.log("heading="+heading+", orientation="+JSON.stringify(orientation));

In the location updatings, I need to change the heading of the drone, and above code doesn't work!

**Comment by hpinkos** [comment]
Hello @addriumruss,  these Sandcastle examples may help:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Interpolation.html&label=All
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Models.html&label=All

If you are still having trouble, please ask your question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev 

We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
