### ISSUE TITLE
I want to use: (shape file, GeoJSON) as a pipeline import (as shown below), is there any way to achieve it?

### ISSUE THREAD

**Issue by GoodLuckIce** [AnalyticalGraphicsInc/cesium#7150]
I want to use: (shape file, GeoJSON) as a pipeline import (as shown below), is there any way to achieve it?

![vqp87 4l2j xghh 5ded v](https://user-images.githubusercontent.com/9364696/46991705-9d779100-d139-11e8-89c7-77d74a7c0f75.png)
![image](https://user-images.githubusercontent.com/9364696/46992246-b5e8ab00-d13b-11e8-834a-1158e49d2461.png)

**Comment by hpinkos** [comment]
Hello @GoodLuckIce.  Cesium has GeoJSON support, see this example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=GeoJSON%20and%20TopoJSON.html&label=DataSources
I would recommend converting your shapefiles to GeoJSON. 

Please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by GoodLuckIce** [comment]
Ok, understand, I will remember, thank you very much.
