### ISSUE TITLE
Doesn't seem to support gl_VertexID.

### ISSUE THREAD

**Issue by herewaitting** [AnalyticalGraphicsInc/cesium#7151]
:exclamation: Please use the [forum](https://groups.google.com/forum/#!forum/cesium-dev) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

If my shader is used in gl_VertexID, the program will report it wrong, say it undeclared identifier

**Comment by hpinkos** [comment]
@herewaitting in the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
