### ISSUE TITLE
Geocoder relies on pragma error

### ISSUE THREAD

**Issue by pkuwwt** [AnalyticalGraphicsInc/cesium#7158]
The Geocoder.flyToDestionation accept either a coordinate or a rect region.

However, it distinguishes between them by a DevelopError from the pragma in Cartesian3.normalize.

So if you remove all the pragma block in code, then there will be a problem. Geocoder will use the wrongly normalized coordinate other than another option: rect.

I noticed that the official build just removes the pragma comment other than the whole code block.

So I guess the DevelopError statement should be moved out of the pragma block to avoid misunderstanding.

**Comment by hpinkos** [comment]
Hi @pkuwwt, I believe we just fixed this today: https://github.com/AnalyticalGraphicsInc/cesium/pull/7154

The fix will be included in the 1.51 release available on November 1st.  If this is a different issue, let me know and I can reopen this issue.  Thanks!
