### ISSUE TITLE
The Pointcloud data cannot display

### ISSUE THREAD

**Issue by RemoteSensingFrank** [AnalyticalGraphicsInc/cesium#7161]
Hello，in my work I want to publish the data by IIS and using cesium to display the data and I published two types of data which are pointCloudBatched.pnts and pointClassify/content.geom in sample data. The former can be displayed and the latter cannot and here is my code:
// An example showing a point cloud tileset classified by a Geometry tileset.
var viewer = new Cesium.Viewer('cesiumContainer');

// Geometry Tiles are experimental and the format is subject to change in the future.
// For more details, see:
//    https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/3d-tiles-next/TileFormats/Geometry
var classificationTileset = new Cesium.Cesium3DTileset({
    url: 'http://localhost/fileshare/pointCloud/PointCloudBatched/tileset.json',
    classificationType: Cesium.ClassificationType.CESIUM_3D_TILE
});
viewer.scene.primitives.add(classificationTileset);

classificationTileset.style = new Cesium.Cesium3DTileStyle({
    color : {
        conditions : [
            ["${id} === 'roof1'", "color('#004FFF', 0.5)"],
            ["${id} === 'towerBottom1'", "color('#33BB66', 0.5)"],
            ["${id} === 'towerTop1'", "color('#0099AA', 0.5)"],
            ["${id} === 'roof2'", "color('#004FFF', 0.5)"],
            ["${id} === 'tower3'", "color('#FF8833', 0.5)"],
            ["${id} === 'tower4'", "color('#FFAA22', 0.5)"],
            ['true', "color('#FFFF00', 0.5)"]
        ]
    }
});

classificationTileset.readyPromise.then(function() {
    console.log('Loaded tileset');
    var bounding = classificationTileset._root._boundingVolume;
    var center = bounding.boundingSphere.center;
    var cart = Cesium.Ellipsoid.WGS84.cartesianToCartographic(center);

    var dest = Cesium.Cartesian3.fromDegrees(
            cart.longitude * (180 / Math.PI),
            cart.latitude * (180 / Math.PI),
            bounding._boundingSphere.radius * 1.0);

    viewer.camera.setView({ destination: dest });
});

**Comment by lilleyse** [comment]
Did you mean to use the geometry tileset url instead of the PointCloudBatched url? Only geometry tiles and vector tiles can be used to classify other tilesets.

If you have more questions, please start a discussion on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev. If there is a bug we can reopen this issue later. Thanks!
