### ISSUE TITLE
"3dtile model adjust angle for tileset" how to do it

### ISSUE THREAD

**Issue by binfenshijie** [AnalyticalGraphicsInc/cesium#7166]
var m = tileset_test.modelMatrix;
    var m1 = Cesium.Matrix3.fromRotationY(Cesium.Math.toRadians(RotateY));
    Cesium.Matrix4.multiplyByMatrix3(m,m1,m);
    tileset_test.modelMatrix = m;
example:
http://cesium.xin/wordpress/archives/106
but now it do not work for 1.4 or heigher
now how to do it 
thanks

**Comment by hpinkos** [comment]
Hello @binfenshijie, yes you should be able to set the tileset modelMatrix to place the tileset

```js
var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url: 'tileset/url'
}));

tileset.readyPromise.then(function(tileset) {
    tileset.modelMatrix = // compute model matrix
}).otherwise(function(error) {
    console.log(error);
});
```

We have a tileset position tool for positioning tilesets tiled on Cesium ion.  Find out more at https://www.cesium.com
Alternatively we have the same tool available for purchase as part of the Cesium ion SDK.  Send an email to tim@cesium.com for details.

**Comment by lilleyse** [comment]
Given that this sounds like a regression, this might be related to https://github.com/AnalyticalGraphicsInc/cesium/pull/6755#issuecomment-425454485 and 
https://github.com/AnalyticalGraphicsInc/cesium/issues/7036.

**Comment by binfenshijie** [comment]
> Given that this sounds like a regression, this might be related to [#6755 (comment)](https://github.com/AnalyticalGraphicsInc/cesium/pull/6755#issuecomment-425454485) and
> #7036.

yes, same question....

but i really can not understand the English better....
and i want to know how to change my code for example ：
------
    var m = tileset_test.modelMatrix;
    var m1 = Cesium.Matrix3.fromRotationX(Cesium.Math.toRadians(RotateX));
    Cesium.Matrix4.multiplyByMatrix3(m,m1,m);
     tileset_test.modelMatrix = m;
-------
you can give some code for me????

**Comment by binfenshijie** [comment]
any one can help????@lilleyse

**Comment by lilleyse** [comment]
@binfenshijie sorry we don't have a fix for this yet. The only workaround at the moment involves modifying the Cesium source code. The code change is described here: https://github.com/AnalyticalGraphicsInc/cesium/pull/6755#issuecomment-425454485.

**Comment by binfenshijie** [comment]
> @binfenshijie sorry we don't have a fix for this yet. The only workaround at the moment involves modifying the Cesium source code. The code change is described here: [#6755 (comment)](https://github.com/AnalyticalGraphicsInc/cesium/pull/6755#issuecomment-425454485).

get it
