### ISSUE TITLE
GroundPolygons not visible on iOS when too small

### ISSUE THREAD

**Issue by xtassin** [AnalyticalGraphicsInc/cesium#7169]
Polygons entities are not visible on iOS (iPad2 + Safari) when smaller than a certain threshold (around 1 deg of lat/lon)

```
var viewer = new Cesium.Viewer('cesiumContainer');

var visiblePolygon = [1.0, 45.0,
                      1.0, 43.0,
                      3.0, 43.0,
                      3.0, 45.0];

var invisiblePolygon = [1, 44.0,
                        1, 43.0,
                        2, 43.0,
                        2, 44.0];

viewer.entities.add({
    polygon : {
        hierarchy: new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray(invisiblePolygon)),
        material: new Cesium.Color(1.0, 0.0, 0.0, 1.0)
    }
});


viewer.zoomTo(viewer.entities);
```

**Comment by likangning93** [comment]
Hi @xtassin, this is the same problem as https://github.com/AnalyticalGraphicsInc/cesium/issues/6739, so I'm going to close this as duplicate. Thanks for the heads up though, more reasons to take another look at this soon.

The gist is that floating point textures on iOS devices behave differently than on desktop, although behavior also varies between Nvidia and Intel. In the worst case we can detect iOS and shut off the ground polygon optimizations that depend on floating point textures, but hopefully something can still be done.
