### ISSUE TITLE
Full of stripes when I open the shadow feature on mobile devices

### ISSUE THREAD

**Issue by a0026** [AnalyticalGraphicsInc/cesium#7178]
When I use the shadow feature on mobile devices, I found that there are many shadows on surface of the model. I think there may be some bugs.

**Comment by lilleyse** [comment]
Hi @a0026, we actually had a very similar issue opened yesterday: https://github.com/AnalyticalGraphicsInc/cesium/issues/7176

I'm going to close this and link to it from that issue.
