### ISSUE TITLE
Upgrade jasmine once karma-jasmine bug is fixed

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7195]
https://github.com/jasmine/jasmine/issues/1617

I reverted to jasmine 3.2.0 in https://github.com/AnalyticalGraphicsInc/cesium/pull/7194
Once the above issue is fixed we should go back to using the latest version of jasmine with the caret in package.json

**Comment by mramato** [comment]
Looks like they released karma-jasmine 2.0 which should fix this.
