### ISSUE TITLE
An error occurred in "w": An error occurred while accessing http://****/tilesets/nj40/layer.json

### ISSUE THREAD

**Issue by addriumruss** [AnalyticalGraphicsInc/cesium#7199]
always got this error.

**Comment by hpinkos** [comment]
@addriumruss can you create a reproducible code example in [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/)?

**Comment by addriumruss** [comment]
@hpinkos Thanks for response~ Sorry I cann't use sandcastle because of no good network, cann't access sandcastle free as will.  
finally it turns out that my .terrain data files are not that right.  
I got a ctb-tile tools on windowss and reproduced the terrain files, these files have twice more size than those on linux.  and they worked.   
I still don't know why.
