### ISSUE TITLE
Viewer.scene.clampToHeight return value problem

### ISSUE THREAD

**Issue by herewaitting** [AnalyticalGraphicsInc/cesium#7200]
When I want to get the height of the model attached to the tilted photographic model with the following code, only the height returned by the first model is correct, and the rest is - 9000.

for(var i=0;i<len;i++){
		Luce_obj[items[i].Id] = {};
		var pos = [items[i].Longitude,items[i].Latitude,lidi_height+10-(luce_varH[items[i].Id]||0.1)];
		var position = Cesium.Cartesian3.fromDegrees(pos[0],pos[1],pos[2]);
		var posmatrix = Cesium.Transforms.headingPitchRollToFixedFrame(position, hpRoll, Cesium.Ellipsoid.WGS84, fixedFrameTransform);
		Luce_obj[items[i].Id].luce = viewer.scene.primitives.add(Cesium.Model.fromGltf({
			url : 'simiandeng/lucedu.gltf',
			id: 'luce&' + (items[i].Id?items[i].Id:''),
			modelMatrix : posmatrix,
			scale:8
		}));
		qjpoint.position = position;
		var clampTo3dTilePos = viewer.scene.clampToHeight(position,[qjpoint]);
		if(clampTo3dTilePos){
			console.log(Cesium.Cartographic.fromCartesian(clampTo3dTilePos).height);
			var matrix = Cesium.Transforms.headingPitchRollToFixedFrame(clampTo3dTilePos, hpRoll, Cesium.Ellipsoid.WGS84, fixedFrameTransform);
			Luce_obj[items[i].Id].luce.modelMatrix = matrix;
		}
}

**Comment by hpinkos** [comment]
@herewaitting please see this code example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Clamp%20to%203D%20Tiles.html&label=New%20in%201.50

If you have any follow up questions, please make a post in the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
The forum is monitored by the Cesium team and is also more visible to members of the community so it is more likely that someone has encountered a similar problem and can help.
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
