### ISSUE TITLE
Polyline option to make loop

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#7202]
Because PolygonGraphics' outlineWidth doesn't work for values other than 1, it would be nice if PolylineGraphics could have the option of changing the line strip into a line loop with a nice mitered corner.  Mentioned on the [forum](https://groups.google.com/forum/#!msg/cesium-dev/wECK0_q6ZPA/VfYj79LkAQAJ).

**Comment by hpinkos** [comment]
First we'd need to add `loop` support to `PolylineGeometry`.  Both `PoylineCollection` and `GroundPolylineGeometry` have support so that's the one that needs to be updated

**Comment by mramato** [comment]
We also plan on removing the outlineWidth limitation as part of our terrain efforts (but allowing geometry outlines to use the material system).  Not sure if that changes anything.

**Comment by GatorScott** [comment]
I don't think removing the outlineWidth limitation helps because the higher level concept is a line not a polygon.  The polygon was just a potential workaround.

**Comment by hpinkos** [comment]
duplicate  #5644

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!msg/cesium-dev/wECK0_q6ZPA/VfYj79LkAQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7202 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
