### ISSUE TITLE
Set Classification Type on GeoJSON Entities

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7208]
Currently, there's no way to set the `classificationType` on entities created from GeoJSONs. The reason you'd want this is if you're using GeoJSONs to classify your 3D Tiles.

For example, this example uses the experimental 3D Tiles Vector format:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Terrain%20Classification.html&label=All

But since no tools exist that can output this, you can't actually do something like this in your own applications in CesiumJS. But you can totally do it if expose an option on [GeoJSONDataSource](https://cesiumjs.org/Cesium/Build/Documentation/GeoJsonDataSource.html) to set the classification type.

**Comment by hpinkos** [comment]
@OmarShehata I don't think this is something we would add to the `GeoJsonDataSource`.  Instead, the user can set the `classificationType` attribute on the entities after they are created, similarly to the `Custom Styling` part of this sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=GeoJSON%20and%20TopoJSON.html&label=DataSources

You would just need to set `entity.polygon.classificationType = Cesium.ClassificationType.CESIUM_3D_TILE`

If that's not a solution that works for your use case, let me know and we can reopen this issue.

**Comment by OmarShehata** [comment]
I can see that it's possible that way. I think it's just easier for the user to have this abstraction, since I can imagine it'd be a common use case to use vector data to mark tilesets like this. 

For example, if my GeoJSON contains more than just polygons, would I have to figure out what the type of each entity is, so I can say `entity.polygon.classificationType` vs `entity.rectangle.classificationType`  etc ? In my case, I grabbed the GeoJSON of road data from the Australian government, and I knew I wanted to use it to classify my photogrammetry, but I didn't know what all the feature types in the GeoJSON were.

**Comment by mramato** [comment]
I understand what you are going for, but I don't think extending the GeoJsonDataSource to handle Cesium specific features are the way to go, as @hpinkos mentioned, that's what the Entity API is for.

GeoJson only has points/lines/polygons, and (unless I'm wrong) points and polylines aren't eligible for classification, so having a rectangle is impossible.

**Comment by hpinkos** [comment]
yep, @mramato is right.  `GeoJsonDataSource` will only make `entity.billboard`, `entity.polyline` and `entity.polygon`.

**Comment by OmarShehata** [comment]
That's fine then! That means there's only one type to worry about (polygons). I think I saw some confusion on the forum about the difference between datasources and entities (the users weren't aware that a datasource created entities) but it sounds like I can fix that by explaining in the doc/tutorials. That Sandcastle is definitely a good resource.

**Comment by OmarShehata** [comment]
I just realized this was already suggested by @lilleyse , in this issue which is still open: https://github.com/AnalyticalGraphicsInc/cesium/issues/6634

**Comment by Tonynovtop** [comment]
I tried,but it didn't work @hpinkos, can you help me check it.the code is here:
var tileset = new Cesium.Cesium3DTileset({
        url: '../../../data/20181102/tileset.json',
        maximumScreenSpaceError: 2,
        maximumNumberOfLoadedTiles: 1000
    });
    viewer.scene.primitives.add(tileset);
var buildingsPromise = Cesium.GeoJsonDataSource.load('../../../data/test.json');
        buildingsPromise.then(function (dataSource) {
        viewer.dataSources.add(dataSource);
        var buildings = dataSource.entities;

        var buildingsEntities = dataSource.entities.values;
        for (var i = 0;i < buildingsEntities.length;i++) {
            var entity = buildingsEntities[i];

            if(Cesium.defined(entity.polygon)) {
                entity.name = entity.properties.Id;
                entity.polygon.material = Cesium.Color.fromRandom({
                    red : 0.2,
                    minimumGreen : 0.5,
                    maximumBlue : 0.5,
                    alpha : 0.6
                });
                entity.polygon.outline = false;
                entity.polygon.classificationType = Cesium.ClassificationType.CESIUM_3D_TILE
            };
        }
    });
