### ISSUE TITLE
when Removing a PostProcessStage from PostProcessStageCollection,it reports an error.

### ISSUE THREAD

**Issue by Joyzen** [AnalyticalGraphicsInc/cesium#7210]
![image](https://user-images.githubusercontent.com/18508793/47769762-fdfcf580-dd17-11e8-8042-8c77b8197b2e.png)

**Comment by lilleyse** [comment]
Thanks for the bug report @Joyzen. It's really easy to trigger this bug - [Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=hZBNS8NAEIb/ypJLEigbPJsWseApYLHiKZfpZtoubnbLzCQliv/dTWJF68E9LMw787zz0QOp3uIZSS2Vx7NaI9uu1S+TlqVmCtfBC1iPlOa3ta99HymHnh8cEEZwdtBs0KM+BZYNhUjyVuCArKFpsi/fzVWysjsCGrQhBMHq4jnlsnzutgXfGGBxODo9h+B2QPedSPBZ+oRt6DFdqH3njdgo5eq99iq+f6aiicy+9xibfYxfskhKlsHhava5s+0pkKiOXKZ1IdieXByWi11nXlG0YR6xsrhAZWN7ZZtlnVydr06UccAcM/vOua19wzpZlUWs/4W5AI31h8ceycEwlhxvVtUsaq3LIoZ/KZkv88PxEw).

@bagnell This seems like a pretty quick thing to fix. Could you look at it?
