### ISSUE TITLE
DebugModelMatrixPrimitive does not show correctly when placed on earth center

### ISSUE THREAD

**Issue by FlorianFehring** [AnalyticalGraphicsInc/cesium#7211]
For debugging of placeing entities i want to see the three axis from globe. But when placeing the DebugModelMatrixPrimitive on earth's center only one axis is shown up.

Code:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var position = {
    x:0,
    y:0,
    z:0
};
var hprRollZero = new Cesium.HeadingPitchRoll();
var modelMatrix = Cesium.Transforms.headingPitchRollToFixedFrame(position, hprRollZero, Cesium.Ellipsoid.WGS84);
viewer.scene.primitives.add(new Cesium.DebugModelMatrixPrimitive({
                modelMatrix: modelMatrix,
                length: 30000000.0,
                width: 5.0
}));
```

[Sandcastle demo](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=bVLBTuMwEP0VK5ekUuRkBSut0lAhsQscQIsWBBLKxY2HxtqJJ7KdtAXx7zgpgZQyp/HMe2/m2e6EYZ2CNRh2wjSs2RlY1db8fqhFYTkcz0g7oTSYcDYvdOc5DVnlFGnPeik087HJ0niXbT+y5ywt9KunlKQtIXCkVRR6bjYITauj4Digasw/QnwEQ/ubXYKQSq9ulCurHhGNDK/WgXGDk3fsnRHaPpGprZ9RCjw3ooY7OlcbkEN+Ad6UcOSdSlrrMGYhCOuG7dgkev2aJOC1cEZtvp1QfVlsOufDXjw1Fo8qfxBVY0lJ/nBx++v4YPrwGNyWflveGFV7qQ4sF1JGk5v5Dct2df255c2IjF729fqYuMmmh/gQiqBXrsrYUboLnn4DWivZY37ydL/3OpvNgzjIrdsiLHa9U1U3ZBxrDUacJw7qBoUDmyzb8j84XlrbX0GejKRcqo4peVIEX/5jEbAShbW+89Qi3qpnKIJFnnj8Hg1peJu//oOg2PaQ6sfialfknOeJPx6yHBEuhZkovgE)

Tested with:
Cesium 1.50
Firefox 63 / Chrome 69

Workaround:
When moveing the x axis a little bit (for example use 0.1 instead of 0) all three axis are displayed.

**Comment by hpinkos** [comment]
@FlorianFehring This isn't working because the transform you're passing in isn't valid.  Heading/Pitch/Roll can't be used at the center of the earth because the concept of north and east doesn't exist at the origin.

Instead, your `modelMatrix` should be `Cesium.Matrix4.IDENTITY`
