### ISSUE TITLE
Polyline spanning half the ellipsoid crashes

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7214]
Brought up [on the forum](https://groups.google.com/d/msg/cesium-dev/Y-NPOSmP4UE/LUSYX5WgBgAJ). 

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var purpleArrow = viewer.entities.add({
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights([0, 0, 0,
                                                               180, 0, 0]),
        width : 10,
        followSurface : true
    }
});

viewer.zoomTo(viewer.entities);
```

**Comment by hpinkos** [comment]
It shouldn't crash when it's set to 180.  That's a different issue though.

There are two possible geodesic lines that could connect the two points.  Cesium always chooses the shorter one because if you're drawing a line between two points, chances are you don't want it to wrap the long way around the globe.  The user can tell the line to wrap the other way by adding a point halfway ( (90, 0) for example).

**Comment by OmarShehata** [comment]
That does make sense @hpinkos . So if someone really wanted a line to cover 270 degrees of the globe, is the best way to do that right now to create 2 lines?

**Comment by hpinkos** [comment]
@OmarShehata they don't have to create 2 lines, but they have to define more positions in the polyline.

Like this: 

```js
viewer.entities.add({
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights([0, 0, 0,
                                                               170, 0, 0,
                                                               -100, 0, 0]),
        width : 10,
        followSurface : true
    }
});
```

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/Y-NPOSmP4UE/LUSYX5WgBgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7214 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
