### ISSUE TITLE
All mouse click events treated as left click, right click, and middle click

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7215]
[Local example](http://localhost:8080/Apps/Sandcastle/index.html#c=rZLRS8MwEMb/ldCXdTBSfLYbSjddsSK44VNBsvS2hV0vJUkzpvi/G1tFnQgKy1Pu8v2+7+DihWFewR4MGzOCPcvAqrbmD10vHsiuzDQ5oQjMYHheUkk+UFtBFR5jC2kAaNEICTMP5Oa9KO4juBQBtb3HO88tuJya1l1KpzTF65b6S6091MFiyJ5LYuFITVYjcNSbeICwdkyikrtupJfRbxMsDw3wYna1fMyKPLs5RbZRm+0/wu/z6/kJ02tVBfrv8bf5dFrMPvOjUZRad0CY9OYXqm60caw1GHOeOKgbFA5ssmrlDhyXtltYmnxAaaU8U9W4jI4+RxmFqYS14WXdIi7UE5TRJE2C/huGWlSKNnceDIrDm2R7Nin6Juc8TUL5k3Ja40qYL46v).

This bug seems to have been introduced in https://github.com/AnalyticalGraphicsInc/cesium/pull/7137.

Could someone who's familiar with the click events look into this ASAP?

**Comment by mramato** [comment]
It might be easier to revert the change in the short term (since it's fairly isolated).
