### ISSUE TITLE
CZML Z Index example not ordering correctly in IE

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7225]
IE
<img width="369" alt="wrong" src="https://user-images.githubusercontent.com/915398/47878847-9ae19080-ddf5-11e8-9c85-cb0e37090f14.PNG">

Chrome
<img width="303" alt="right" src="https://user-images.githubusercontent.com/915398/47878848-9ae19080-ddf5-11e8-8a04-ce0450f6211e.PNG">

**Comment by hpinkos** [comment]
This is because IE doesn't support ground primitive materials.  There's not a bug report for this because IE will never support depth textures so it's not something we're going to fix.

**Comment by mramato** [comment]
Do we have a one-time-warning for this at least?  Sounds like we should.
