### ISSUE TITLE
PrimitiveCollection.Remove() takes longer on Linux than on Windows

### ISSUE THREAD

**Issue by abhimonk** [AnalyticalGraphicsInc/cesium#7230]
I create a primitive that is composed of tens of thousands of Geometry Instances. Removing this primitive using the "remove()" function seems to take significantly longer on Linux compared to Windows. 

On Windows, using Chrome browser: ~12 ms 
On Linux, using Chromium browser: ~4500 ms 

[Here is a sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=zVntb9s2E/9XCAND5caR4rjbh7wUc11nDZY2QexsbW1jYCTaZiOLAkUl8Yr87zu+iKbe0uXLnkdI25B3v7vj3fF4ZNE95mjKKU5WMfmNsA0RfItO0TJPQkFZ4j1u/36PBe4hmkQ0JFn3+zxB5pPYlGVUMmYACjnBglwVM2ecbT5/+VqI6B6XkVgITm9zQSQ0IQ9oRDKab/zCiqGle9/RDiq/Qik6ehZYw8kvZJuUJSQR0iaxTQkIMQJGVZL//vLm3cW495yY7IpwqxFkDZq473GcwzqPHHeVmZ66u/FT9xioZWfdshz8n6wm6ZpwUnbYuxLNcygjzMF9ENyBd+Af9Myfbq8Pfx2jsobVLvgNPvW+l+3dBe/I+b26dJMzR8UvVXrK6QbccU+m4Gwbhit31p9enw8//XYxnlTBZZccVV3U7k+xpplfyr5i7c6s6x4FMEtwuc1UjbW0LBdQItRgtRhbXJlSXk2xUyu77w8SCsa9SG48VAmeDDcnIufJlbN7ZdTPYobFL2+GnOOtwvoxSVZijV6jgbt/Cyl3gDuozC8ZR54kUkWEf06QIwom9vZqJpWA3zTwmwHO6MJiv7Vg5VdZ0uxuAXKMgNm3xXEz6m5vr4HyVNme5aHWVFXoiHn6FxGy9bExRnSJFGF2UCwenZ6eIsgDsqQJiRq9oA06ftb2FwTf0f2C+O9C35IX1fAe/Di8CvvSfPp/zAk9fNJbOAg+jC+uxtfo7ObTaHp++WmCzi6v0fvhdCiJI5UuiOMkYhsEp6gyfJ7YfFoR8REn2z/U4eIl+Ub/1kObPBY0jSnh1jHS8eYU0tHWYbagIrpNu9cy1X2tRYIzgZtCluw0o59Q/6DIAeMr4yMNApJyibuca5LKNUda3XApCHfXpYD/7ZJ+0uMXrkOG5XJ5mZD/qfUvtnyJ5aFBcezVbU05i/JQgNh+k2V9ZVmhs2ZWgX4NPm20yDAUJgVBiOMwj7E8oOcdqJ1rxjLYDPOOY28SQnr0dkluZO2WkXRRgLzdGFhfu2S0j3i3Wygtx3ACh2/RGavddcUotHslp2iF57Y1kHG8Aa7+LzaaGuUW0JaI7hjr7ivp2aWmRTW6tATaOXZffmj8efjx6mKMJtPh9XSCPoyvx0hRgmCeSONC1Yz9SSNwRbknHDkU75XmG7FEYDiX+CvVbEkBWUgS2cW4gnw1WXCQOKZpxmjUyOWvYnZLfMuka6bEbVhE4o8YWrVHQBqr9PiNbyrQ9t32JqHg6s0EMol4TrPVCphCqc0g5eS9p17+DUwxSbmZT3AmPjEu1jfplJ3RRxKdcbwhnjXZD6EBZyuO0zUNp8y24x5qPnccNSMH6S+hU3hPVpxAIu5DVYU+Hr2RnXy323TbaL8BIAOVn7wIuKzGH15Z5s+Gt4VVB0WHBbLxlvDLpUnkU1n/D9QRoIK2Oxkkxcx+Vm1u5RhzpJTOMoP5ojEtZ0UJDBYUqK87TbYyl3kLTrfTr1cBB1NsaAkyl1wAzT730Jce+trUXGjxmcCJVjBbNDRPmy10hZIo4wU/zTznRswxCgKxJijMOYfrqBXfjDEXljIkgx3OlkiYZRYOqEvIKpYEwYSCKkRwuHbgmb4dZySSYgfN8oLggaAHGseIQuRkoyMY6gcDZQkYl9G/ifx93ingHb9uEQTERkcWRc1adK0B1NIfX05cGe3dpBQ/gOpMtfdgkZyknGTyCQA9wC51PAArw3CDY4lflxMEZ2ADecSbNCY9I3ZDoKgA7JVCqfUPeGQFNoixwZSJYpY9yxb2nWaWoT3Ur4wPFzKXmmzSOQeLasiLVO9n6TqW8+eMCoKpdAz8YHQYgQ/gDETe4HEAJeVBXWpVpnD2IHn0PgGpXxtFUaHT45bYlIDiKs3YYIFwZrecp4Rm+a3WV5LcbRDd5Eyz45rL8sxogpvKzPodBoteI6HfRgD3L3o/UNFvU9FvU9F/qYrDNhWHbSoOqyrqGpqqnb3C2LelojihPKPJynkNgzuO3bxNgv4k5vYMSZliVS52dVRmZrkEZUzuwRBD38jiGlUquqdRjuN427yzjJWNT2EF1Wu5ctrF6sfJ6uOqp5KtJ6t7v3e46LZEy+1xjtxRC7/znnXUdhnWriz7giXxFq1hN/W1q9qRiuy8lcKo6hL7Dqo6FsVSeo5UE+0a5AeLXPv6yut1e+VRhQgndrdZ2FPD5b3bkKA2hfw0z9beLvLd+huKbJ2RyWf7jgdOUX2vTGa3Nmam59nat8xyLtnp0hP1quJOGUprotuU4WybhGvOEpZnR3CfiTPipAVOoTHiKoFL7+NXhBeSVSSGlq/2UL6ELhjAguek2mAK1STnoTwgjO7SW6sZKH+Dx4ZR5LgLjnjV22se3eZbaubjKPIcn3WPjdulENjLLNkPYxreIXIvtYMwTjZMil27MZG1BEaSA+YFhUND4DuSoNstdBMaMu9IuDrsoPywGCyq3ECg2U4mKQ7JWCr7AEJjwn04Es+TNBdD/b8j9r7IkguyFCNpnSflbwBTvur3IQNSwtXxBbr8hD14RZrVHKGNrPrCyjp8RpZZjx+zlQeM+6C5IMEVsFckw6SyQPXWfjE+m/41ujgf/d497vQ6J5nYxuStBv9KoaXjAuU89nw/EAT6F3k7D27z8A48FmaqHz4JCtAJFFlEo9N5p3JFBN+HMc4yoCzzOJ5AozfvvD0JgL8EixmWj96X94THeCtZ1v23F3rS9/2TAIZ1lGAshk7AkfgP) that reproduces the issue. 
The sandcastle example constructs a primitive using tens of thousands of triangles, and has an "onclick" listener that removes the primitive when you click anywhere on the map, and prints the time taken by "remove()" to the console.

Try the above in Chrome on Windows, and compare it to Chromium on Linux.

Someone on the google group pointed me to [this issue](https://github.com/AnalyticalGraphicsInc/cesium/issues/3018)

Is this the same issue? Are there any workarounds that don't involve modifying the Cesium source code?

**Comment by hpinkos** [comment]
@abhimonk yes, I believe this is the same root problem as #3018 because both `PrimitiveCollection` and `PointPrimitiveCollection` use pickIds in a similar way.  There is a workaround proposed here: https://github.com/AnalyticalGraphicsInc/cesium/issues/3018#issuecomment-144071807

I'm going to close this as a duplicate but will add a comment to #3018 that you are experiencing the same problem.  Thanks for including the code example!
