### ISSUE TITLE
autonomous driving demo

### ISSUE THREAD

**Issue by tropicalpb** [AnalyticalGraphicsInc/cesium#7242]
Hi, the demo at https://cesium.com/blog/2018/04/03/cesium-for-autonomous-driving-simulation/ looks great.  We have a similar need, it would be great if someone can point me to the steps on how to create a similar demo using Cesium.

Thanks

**Comment by hpinkos** [comment]
Hi @tropicalpb, the features seen in that demo are available for purchase as part of the Cesium ion SDK.  Please send an email to tim@cesium.com if you are interested in purchasing that package.

Thanks!
