### ISSUE TITLE
polygon outlineWidth doesn't work

### ISSUE THREAD

**Issue by avetisyanIncorporation** [AnalyticalGraphicsInc/cesium#7265]
Sandcastle example: 
```
Cesium.Math.setRandomNumberSeed(1234);

var viewer = new Cesium.Viewer('cesiumContainer', { infoBox : false });
var entities = viewer.entities;
entities.add({
    polygon : {
        hierarchy : new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray([-107.0, 27.0,
                                                                                    -107.0, 22.0,
                                                                                    -102.0, 23.0,
                                                                                    -97.0, 21.0,
                                                                                    -97.0, 25.0])),
        outline : true,
        outlineColor : Cesium.Color.BLACK,
        outlineWidth : 13,
        material : Cesium.Color.YELLOW
    }
});
```

Browser: Google Chrome version 70.0.3538.102 

Operating System: windows 10

![image](https://user-images.githubusercontent.com/29467133/48554428-6a1e5280-e8ef-11e8-9a86-93e1a0505344.png)

**Comment by hpinkos** [comment]
Hello @avetisyanIncorporation,

See this post: http://stackoverflow.com/a/25405483/3191039  This is a limitation of the WebGL implementations on Windows (but is completely in spec).  It works on standard OpenGL implementations (which means phones, Linux, Mac, and etc.)

The maximum value on the current system is documented and exposed via `scene.maximumAliasedLineWidth` and this limitations is also mentioned in our [Visualizing Spatial Data](http://cesiumjs.org/tutorials/Visualizing-Spatial-Data/) tutorial.
 
However, we have plans to improve this, along with supporting polygon outlines on terrain coming up soon.
