### ISSUE TITLE
Add "backFaceCulling" option to Globe

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7266]
This came up on Stackoverflow:

https://stackoverflow.com/questions/53277048/how-do-i-clip-an-entity-or-geometry-against-underside-of-terrain

It seems to be a common scenario to isolate a piece of terrain like that (common enough that we have a [Sandcastle for it](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Terrain%20Clipping%20Planes.html)). But one issue is that since backfaces are culled, you can see through the terrain, and that looks ugly.  

![Terrain with backface culling on](https://i.stack.imgur.com/bdug4.png)

If you disable backface culling, it looks great:

![terrain-no-culling](https://user-images.githubusercontent.com/1711126/48560500-ee56e280-e8bb-11e8-8744-21871aa629bf.gif)

I did this by manually editing the source here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/GlobeSurfaceTileProvider.js#L436-L458

It would be nice if this was an option. I think it could be part of the effort to give users more control over blend mode settings https://github.com/AnalyticalGraphicsInc/cesium/issues/7203. This particular case could easily be just a boolean you can set on the globe.

**Comment by IanLilleyT** [comment]
Added `backFaceCulling` option to `Globe` in https://github.com/AnalyticalGraphicsInc/cesium/pull/8470. 

`globe.backFaceCulling = false` fixes this issue.
