### ISSUE TITLE
poliline sometimes is blocked by the cloud points

### ISSUE THREAD

**Issue by dminor112** [AnalyticalGraphicsInc/cesium#7281]
I draw a poline on the cloud points tileset. All of the points of the polyline is higher than the cloud points. Sometimes the polyline was hidden by the cloudpoints at the angle that is not expected.
Nromal: 
![image](https://user-images.githubusercontent.com/7435641/48892653-85520a80-ee79-11e8-978f-20df073be27c.png)

Was Hidden:
![image](https://user-images.githubusercontent.com/7435641/48892877-fdb8cb80-ee79-11e8-83bd-a25e6e8205f9.png)

**Comment by GatorScott** [comment]
There are no intermediate points shown along that particular line segment.  This would result in a straight line that could pass through the canopy if there is a slight hill between those two points.  Can you make a Sandcastle example that duplicates the problem?

Scott

**Comment by hpinkos** [comment]
@dminor112 you can try using a `depthFailMaterial` so the line doesn't look like it's going behind the point cloud

```js
            viewer.entities.add({
                polyline : {
                    positions : ...,
                    material : Cesium.Color.YELLOW,
                    depthFailMaterial : Cesium.Color.YELLOW
                }
            });
```

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features. Thanks!
