### ISSUE TITLE
polygon above a 3DTile model  in 2d view

### ISSUE THREAD

**Issue by laonon** [AnalyticalGraphicsInc/cesium#7284]
In 2d mode, I added a 3DTile model and then added a polygon entity. However, this polygon is under the model. I want to implement this polygon above the model.

// the code

```
let viewer = (this.viewer = new Cesium.Viewer('model-layer', {
    infoBox: false,
    selectionIndicator: false,
    infoBox: false,
    animation: false,
    fullscreenButton: false,
    sceneModePicker: false,
    timeline: false,
    navigationHelpButton: false,
    homeButton: false,
    geocoder: false,
    navigationInstructionsInitiallyVisible: false,
    skyBox: false,
    skyAtmosphere: false,
    selectedImageryProviderViewModel: undefined,
    selectedTerrainProviderViewModel: undefined,
    globe: false,
    shadows: false
}))

tileset = viewer.scene.primitives.add(
    new Cesium.Cesium3DTileset({
        url: uri,
        show: false
    })
)

viewer.entities.add({
    polygon: {
        hierarchy: positions,
        material: new Cesium.Color(1.0, 0.83, 0.12, 0.4),
        // zIndex: 10,
        outline: false,
        height: 0
    }
})

```

**Comment by hpinkos** [comment]
@laonon you'll need to set the height of the polygon to be above the tileset.  Or you can set `height: undefined` and try setting the [classifictiaonType](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Classification%20Types.html&label=3D%20Tiles) so the polygon colors the tileset.

Please ask any follow up questions on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by laonon** [comment]
@hpinkos  Thanks for your reply, but the part of polygon beyond tileset cannot be colored, I guess only two polygons can be drawn overlapping
