### ISSUE TITLE
Post Processing Selected only works for models?

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7288]
For the post processing example:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Per-Feature%20Post%20Processing.html

If you replace the model:

```
model : {
        uri : url
    }
```

with:

```
box : {
        dimensions : new Cesium.Cartesian3(400000.0, 300000.0, 500000.0),
        material : Cesium.Color.BLUE
    }
```

The color-on-mouse-over no longer works. The docs are a bit vague on what it applies to, since it only says that this allows you to select the "features", which at first made me think of 3D Tiles features. 

Is this expected to work? If not, maybe needs a better doc explanation.

[Came up on the forum](https://groups.google.com/d/msg/cesium-dev/n3ErwO3DDPo/Q3B1l8MkAAAJ).

@bagnell

**Comment by OmarShehata** [comment]
I think the answer is yes, it doesn't work for entities yet, because there's currently no API for getting the underlying primitive from an entity. There's a feature request for it here: https://github.com/AnalyticalGraphicsInc/cesium/issues/6705

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/n3ErwO3DDPo/Q3B1l8MkAAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7288 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
