### ISSUE TITLE
IonImageryProvider not working with puppeteer + headless chrome

### ISSUE THREAD

**Issue by sids4ru** [AnalyticalGraphicsInc/cesium#7292]
**Issue:**
If we are running puppeteer with headed chrome, everything is fine. 
However for headless I am not able to render with IonImageryProvider 
I tried alternate providers like MapboxImageryProvider and it works perfectly well

I am trying to render a scene to a video
Using Cesium 50 

**Sample Code**
`const puppeteer = require('puppeteer');
var page;
var browser;
var blob;

async function run() {
  browser = await puppeteer.launch({
  headless: false,
  ignoreDefaultArgs: true,
  args:['--no-sandbox', 
	'--disable-setuid-sandbox', 
	'--remote-debugging-port=9222',
	'--headless',
    '--hide-scrollbars',
    '--mute-audio',
	"--proxy-server='direct://'",
	"--proxy-bypass-list=*",
	"--disable-gpu",
	"--deterministic-fetch"
	]
});
  page = await browser.newPage();
  await page.goto('https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/');
}
run();`

**Hard coded Fix**
Setting preferBlob to false in  Resource.js has fixed this issue

**Error Logs:**
`an error occurred in "IonImageryProvider": Failed to obtain image tile X: 3 Y: 5 Level: 3.
Cesium.js:37792 An error occurred in "IonImageryProvider": Failed to obtain image tile X: 3 Y: 7 Level: 3.
blob:http://localhost:8080/ac24bc30-78d4-46d0-a134-249056283634:1 GET blob:http://localhost:8080/ac24bc30-78d4-46d0-a134-249056283634 net::ERR_UNKNOWN_URL_SCHEME
Image (async)
Resource._Implementations.createImage @ Cesium.js:6316
request.requestFunction @ Cesium.js:5461
RequestScheduler.request @ Cesium.js:4209
fetchImage @ Cesium.js:5466
(anonymous) @ Cesium.js:5425
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1264
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1265
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1265
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
(anonymous) @ Cesium.js:4059
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1264
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
xhr.onload @ Cesium.js:6450
load (async)
Resource._Implementations.loadWithXhr @ Cesium.js:6419
request.requestFunction @ Cesium.js:5794
startRequest @ Cesium.js:4085
RequestScheduler.update @ Cesium.js:4161
Scene.render @ Cesium.js:240484
CesiumWidget.render @ Cesium.js:251309
render @ Cesium.js:250690
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
Cesium.js:37792 An error occurred in "IonImageryProvider": Failed to obtain image tile X: 2 Y: 7 Level: 3.
blob:http://localhost:8080/05535948-ba03-4401-9b68-01d85c035bcb:1 GET blob:http://localhost:8080/05535948-ba03-4401-9b68-01d85c035bcb net::ERR_UNKNOWN_URL_SCHEME
Image (async)
Resource._Implementations.createImage @ Cesium.js:6316
request.requestFunction @ Cesium.js:5461
RequestScheduler.request @ Cesium.js:4209
fetchImage @ Cesium.js:5466
(anonymous) @ Cesium.js:5425
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1264
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1265
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1265
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
(anonymous) @ Cesium.js:4059
(anonymous) @ Cesium.js:1163
(anonymous) @ Cesium.js:1264
processQueue @ Cesium.js:1614
_resolve @ Cesium.js:1300
promiseResolve @ Cesium.js:1326
xhr.onload @ Cesium.js:6450
load (async)
Resource._Implementations.loadWithXhr @ Cesium.js:6419
request.requestFunction @ Cesium.js:5794
startRequest @ Cesium.js:4085
RequestScheduler.update @ Cesium.js:4161
Scene.render @ Cesium.js:240484
CesiumWidget.render @ Cesium.js:251309
render @ Cesium.js:250690
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:83147
render @ Cesium.js:250691
blob:http://localhost:8080/7da491b4-db70-4d04-88eb-d2ddf2d95a6f:1 GET blob:http://localhost:8080/7da491b4-db70-4d04-88eb-d2ddf2d95a6f net::ERR_UNKNOWN_URL_SCHEME`

**Comment by shunter** [comment]
This appears to be a bug in puppeteer:

https://github.com/GoogleChrome/puppeteer/issues/3463

**Comment by hpinkos** [comment]
Thanks @shunter!  @sids4ru i'm going to close this issue since it seems to be a bug in puppeteer.  I would recommend giving a 👍 or posting a comment in the issue @shunter linked to above.

**Comment by OmarShehata** [comment]
As a workaround, you can disable CesiumJS from using blob URLs. It's a bit of hack since `IonImageryProvider` doesn't expose that as an option, see:

https://groups.google.com/d/msg/cesium-dev/nKlceXLF-Js/4YiR_bAnAAAJ
