### ISSUE TITLE
Sandcastle example for model with spinning wheels

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#7295]
Example showing a moving glTF vehicle model where the wheels are spinning at a realistic rate given the vehicle's velocity.

CC @chris-cooper @impactblue573

**Comment by OmarShehata** [comment]
I think this Sandcastle is a good start:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Multi-part%20CZML.html

It already has a vehicle with wheels spinning, depending on the simulation time. I think it shouldn't be too hard to figure out the correct rate to play the animation.

**Comment by pjcozzi** [comment]
Yes, perfect!

**Comment by OmarShehata** [comment]
@lilleyse I've managed to correctly compute the correct rotation speed given the wheel's circumference and the vehicle's speed, however it doesn't look like there's a way to set the rotation speed of an animation from the Entity API, correct me if I'm wrong.

I think this will be a good opportunity to expose that, to make manipulations like this possible.

**Comment by OmarShehata** [comment]
This is done with https://github.com/AnalyticalGraphicsInc/cesium/pull/7361. @mramato can you close?
