### ISSUE TITLE
Investigate intern (possible Jasmine replacement)

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#735]
I know we've done a lot of customization of Jasmine in Cesium, but I'm not sure how tied we are to it.  I stumpled upon [intern](https://github.com/theintern/intern) and it looks pretty promising (particularly because it natively supports AMD, coverage, and promises.)  Has anyone looked at this before?  It's also has CI integration and node support, which could help us with automating branches.

CC @kristiancalhoun @pjcozzi @shunter

**Comment by pjcozzi** [comment]
I did not evaluate it, but [tape](https://github.com/substack/tape) is another one to consider.

**Comment by kring** [comment]
I haven't used tape, but I know some folks who have and like it a lot.  It does require you to declare how many assertions your test is going to do at the top of your test, with a line like: `t.plan(2)`.  It looks like you can alternatively skip the `t.plan` and call `t.end` when you're done, but effectively, that's treating every test like it's async when only maybe 10% of our tests are.

**Comment by pjcozzi** [comment]
Also just came across [mocha](https://github.com/mochajs/mocha) but did not evaluate it.

**Comment by mramato** [comment]
I'm going to close this since we have no plans to move to a different framework any time soon.  The landscape is constantly changing so if we do decide to replace it, it's unlikely any information in this issue will be of much help.  Jasmine is still really popular and personally I think it's a solid choice (though our use of it could possibly be improved).
