### ISSUE TITLE
Polyline flickering artifacts depending on platform

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7360]
Broken out from https://github.com/AnalyticalGraphicsInc/cesium/issues/6741

https://github.com/AnalyticalGraphicsInc/cesium/pull/6955 mostly fixed poyline flickering but I still see it on my AMD machine, not Nvidia.

[Sandcastle demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVFdT8IwFP0rzV42EuwYxI/gJCIagzHxYcQH05fSXaSha0k/IMP4371jiKhNH3o/zuk59264JRsJW7DkhmjYkgk4GSr6us8lsdiHE6M9lxps3CUfTBM8bmmCKsdaVtwDGZIFVw6Y/uxcM810S0lL7nlhgkUWyssyOZBPdpW6P5aoMrxMYkrT4x2v1y4teLVW0PSlTjZPKhAXdzrUL0Eni6CFl0YnP5909uJafQcF3nKxgvJBe+lrtPjTTKHJSVT2Dv6unqKEAq0oJT2kj2Cghixu3ZzwCWXEiopgLcJnsgLkPLh6CkpyjXqBLqypps5cXfSyJO73sv5Zb3CWnc+y3rB/ORz035D4oPM4MqajbpQ7XysYtaVbdG2sJ8GqBIfiAYeA7C6dB/TkqXCugebpNygv5YbI8oZFf9bGIiIUdw4ri6BUIXfAolGeYv8vWLMJqd9fNmAVr5uWZTZ6bpOU0jzF8D/KG6Pm3J4wMv0F)

![capture](https://user-images.githubusercontent.com/32828/41997432-fc9c952e-7a25-11e8-88b7-6c17782c02e6.gif)

**Comment by hpinkos** [comment]
duplicate #7374
