### ISSUE TITLE
Translucent geometry not rendering as well as it used to?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7364]
Somewhere between 1.50 and 1.51 translucent geometry started rendering differently

1.50
https://cesiumjs.org/releases/1.50/Apps/Sandcastle/?src=CZML%20Custom%20Properties.html

![image](https://user-images.githubusercontent.com/1495196/49393760-2c4b6780-f700-11e8-8e4f-4138662cd727.png)

1.51 and 1.52
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=CZML%20Custom%20Properties.html&label=All

![image](https://user-images.githubusercontent.com/1495196/49393790-3a00ed00-f700-11e8-97a8-a9d8ac7be872.png)

**Comment by mramato** [comment]
@hpinkos @bagnell @lilleyse any ideas here?  I haven't bisected yet...

**Comment by mramato** [comment]
This might be specific to this example.  For example: http://localhost:8080/Apps/Sandcastle/index.html?src=CZML%20Rectangle.html&label=All seems to work (look at PA)

**Comment by hpinkos** [comment]
Got it, one sec

**Comment by WangXiaoLun** [comment]
but it's still abnormal in version1.52

**Comment by hpinkos** [comment]
@WangXiaoLun can you post what you're seeing?  It looks correct to me: 

![image](https://user-images.githubusercontent.com/3451886/49449119-32951e80-f7a8-11e8-8706-d3e4be901f5b.png)

Note that we recently made some changes that might make it look slightly different than before, but you can still see the changes in lighting for the different faces of the geometry.
