### ISSUE TITLE
Sample Height from 3D Tiles broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7368]
CC @lilleyse 

http://localhost:8080/Apps/Sandcastle/index.html?src=Sample%20Height%20from%203D%20Tiles.html&label=All

Maybe be the same root cause as #7365?

**Comment by lilleyse** [comment]
I think it is the same cause because it fails when constructing the polyline from the sampled points.

**Comment by mramato** [comment]
@lilleyse so who do you think should be looking into this?  @hpinkos probably knows most about the geometry stuff.

**Comment by mramato** [comment]
The positions all end up NaN in the geometry, so something is seriously getting screwy.
