### ISSUE TITLE
Scene.highDynamicRange gets something wrong...

### ISSUE THREAD

**Issue by vtxf** [AnalyticalGraphicsInc/cesium#7380]
**Scene.highDynamicRange** gets something wrong...
@bagnell @lilleyse 

run [local example](http://localhost:8080/Apps/Sandcastle/index.html#c=tVNba9swFP4rml9sQya73fqSumFdEvqwsYFb9mQoinxii8qSkWSHdPS/99jObQ6UMjYZjKzvcnS+g1tmSCtgA4bcEAUbMgcrmor+6s8Cn/efc60cEwqMH15nqns2QuV6Qw/SYdODLVoWBkDNtxJZJzAF5YQTYCnL8+B3pgguxSogU+LfdRLC95qNcCVZScafiG4cHoI/GQS1tmii1XR/1zkzDndMfaJro6sFdNVt8PEijmk8IZ/792XcLRqHO5dDoSnZXaRbElSBdacoGuiTI+Z0nbJcNBbhy3N4pZ3T1VuMijkwgklyvLmW2tC7dLn8QbuGb2VdsiCmV+GJbNc+qpxp4BzoTcaei9v022NvPPBfMvUSHsZjIMeRwvsGk0JOuP6r/K/+V/7/Kvp0uRjnc89Uzpl1ErowHrSWK2a+NlhBBX4pinKxxWQET5kqMBOybhTv4iBBuO9kF6rloICOJRj6hzcJ18dRDbRnrasHHYxG1VG8iZdYt5UwGwp/EVWtjSONkQGlkYOqlti5jVYNfwJHue1lSbQXJbloichvMm/0o2ce4ZJZi8i6kfJePEPmzZII+X/IpMbUVfGzBSPZtqOUF7PvwyGlNInw81zlhlRPHF8B), and click the button, then zoom out, will got this result(1.52):

![image](https://user-images.githubusercontent.com/13550568/49440037-9433a800-f7fd-11e8-8575-39e89754db23.png)

what the expected behavior is 
![image](https://user-images.githubusercontent.com/13550568/49440095-b9c0b180-f7fd-11e8-9cde-11f58e33fedb.png)

the local example is modified from the [Sandcastle example](http://localhost:8080/Apps/Sandcastle/index.html?src=Cylinders%20and%20Cones.html&label=Geometries)  

Browser: chrome

Operating System: windows 10

**Comment by mramato** [comment]
Thanks @vtxf this looks like a clear cut bug when toggling the setting on/off.  @bagnell?

**Comment by hpinkos** [comment]
@bagnell this is still a problem

**Comment by tfili** [comment]
Is this getting looked at today for the release @bagnell ?
