### ISSUE TITLE
Contrast / saturation adjustments causes render issues on Linux since Cesium 1.52

### ISSUE THREAD

**Issue by ulrichson** [AnalyticalGraphicsInc/cesium#7382]
Since Cesium 1.52 tweaking the contrast adjustment (any value != 1) will cause rendering issues on Linux:

![cesium-1 52-linux](https://user-images.githubusercontent.com/449600/49448714-c0d5c880-f7d9-11e8-835d-a9a891f15b9c.png)

Parts appear black, similar result when saturation is adjusted to a higher value. The previous Cesium version with adjusted contrast / saturation worked fine on my machine.

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Imagery%20Adjustment.html

Browser: Chrome 70 / Firefox 63

Operating System: Ubuntu 18.04.1 LTS

Graphics: GeForce GTX 1060 3GB with NVIDIA driver 390.77

**Comment by mramato** [comment]
Thanks for writing up an issue @ulrichson.

This has actually been a problem on the Windows side for a long time.  I'm under the impression that it was an Nvidia driver bug.  On my Linux machine (Ubuntu 18.04.1 LTS) the issue only appears when running under my GTX 1050 and does not happen when using the Intel GPU.  It's definitely possible that it's an issue in an nvidia-only share path in our code.  (Happens on my Windows 650ti every time).

Maybe someone can finally track it down.

**Comment by ulrichson** [comment]
@mramato thanks for the update!

I found out that the issue appears when `Scene.highDynamicRange = true` (as it was introduced in 1.52). When I disable it the adjustments work as in < 1.52.

**Comment by mramato** [comment]
Thanks for the extra info @ulrichson.

@bagnell any idea where the problem might be?

**Comment by mramato** [comment]
@ulrichson thanks again for reporting this, it will ship with the next release (on Jan 2nd).

**Comment by thw0rted** [comment]
Could this fix have caused #7707 ?
