### ISSUE TITLE
Model fails to load if some primitives are Draco encoded and others are not

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7383]
I can't share the data publicly, but I have a glTF that contains two primitives, one with triangles and the other with lines, and only the triangles are Draco encoded. The code assumes that if the extension is present then all primitives are Draco encoded, which causes a failure when processing the lines.

**Comment by lilleyse** [comment]
This happened with another model that had both lines and triangles.

**Comment by mramato** [comment]
@lilleyse @ggetz Any guess on how easy this will be to fix?  Seems like it's starting to pop up more often.

**Comment by ggetz** [comment]
We check each primitive for the extension before attempting to decode: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/DracoLoader.js#L180

Then throughout we check if there's decoded data associated with the primitive, and use that: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2549

This would be a matter of making sure the resources for the primitives without the extension are loaded and used properly.

**Comment by lilleyse** [comment]
Also came up in https://github.com/AnalyticalGraphicsInc/cesium/issues/7495.

**Comment by OmarShehata** [comment]
There's a sample glTF in that issue above ^ so it should make it easier to confirm that this works when we have a fix.
