### ISSUE TITLE
Sandcastle example for HDR

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#7389]
HDR was merged in #7017 and shipped in Cesium 1.52 but does not have a Sandcastle example.  (@bagnell @lilleyse please don't merge features like this without at least discussing if there should be a Sandcastle example).

Let's add one.  Perhaps there is a good night time example showing the contrast?  @ggetz any ideas?

**Comment by ggetz** [comment]
https://user-images.githubusercontent.com/915398/42740436-70bad4ae-8875-11e8-90a8-033847208e58.jpg

**Comment by mramato** [comment]
OBE, we have a demo.
