### ISSUE TITLE
[.WebGL-000002170E547790]GL ERROR :GL_INVALID_OPERATION 

### ISSUE THREAD

**Issue by qqnzhyxxx** [AnalyticalGraphicsInc/cesium#7390]
When using lensFlare in project, the Browser （ Chrome 70.0）will report this Error:
[.WebGL-000002170E547790]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

**Comment by hpinkos** [comment]
duplicate #7366
