### ISSUE TITLE
Matrix4.getRotation returns rotation with scale

### ISSUE THREAD

**Issue by Vineg** [AnalyticalGraphicsInc/cesium#7398]
It seems to be misleading, since there is at least one place in codebase where Matrix4.getRotation is used as rotation-only. For example it leads to dim lighting of scaled point clouds, since normals are scaled as well. I think this place requires carefull review of existing usages and maybe change the name or normalize result by scale.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.clock.currentTime = new Cesium.JulianDate(2457522.154792);

var tileset = new Cesium.Cesium3DTileset({
    url: '../../SampleData/Cesium3DTiles/PointCloud/PointCloudNormals/tileset.json'
});
viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0.0, -1.0, 50.0));
var style = {};
style.pointSize = Cesium.defaultValue(style.pointSize, 5.0);
tileset.style = new Cesium.Cesium3DTileStyle(style);
Cesium.Matrix4.setScale(tileset.modelMatrix, new Cesium.Cartesian3(3,3,3), tileset.modelMatrix);
```
![image](https://user-images.githubusercontent.com/1757455/49725087-f2d4a800-fc7b-11e8-88b7-dcbba4a73fe7.png)

**Comment by Vineg** [comment]
this is what expected
![image](https://user-images.githubusercontent.com/1757455/49725990-054fe100-fc7e-11e8-9625-694f9f719c30.png)

**Comment by hpinkos** [comment]
Thanks for opening up the issue @Vineg!  This seems like a clear cut bug.

@lilleyse can you look into this?

**Comment by lilleyse** [comment]
I've been confused by this in the past too. It seems like `Matrix4.getRotation` has always just returned the upper left 3x3 matrix, which may include scale.

Should `Matrix4.getRotation` be deprecated in favor of `Matrix4.getMatrix3` or `Matrix3.fromMatrix4`?

**Comment by Vineg** [comment]
`Matrix4.getMatrix3` seems nice
