### ISSUE TITLE
Error Creating Cesium 3D Tile Asset

### ISSUE THREAD

**Issue by bbehling-trimble** [AnalyticalGraphicsInc/cesium#7402]
Hello.

I'm trying to create a Cesium ION asset using the FME Cesium ION Connector. When I go to my assets, this error is displayed: 

"We're having trouble with your data. To help fix it, please open an issue in our Github repository.

If you don't have a GitHub account, email Sean at sean.lilley@cesium.com with the asset ID: 12136."

Any idea what the issue is?

**Comment by bbehling-trimble** [comment]
I've also created a GML file and tried to create 3D tiles directly from the ION Asset page. Same error:

"We're having trouble with your data. To help fix it, please open an issue in our Github repository.

If you don't have a GitHub account, email Sean at sean.lilley@cesium.com with the asset ID: 12138."

The GML can be viewed in QGIS. Its attached. (rename to .gml)
[land_xml.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/2665557/land_xml.txt)

**Comment by lilleyse** [comment]
Hi @bbehling-trimble, I think it may be lack of `LineStringSegment` support. If you don't mind I moved this to the [cesium-ion-community](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues) repo.

https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/70
