### ISSUE TITLE
glTF 2.0 model lose light on Andoird

### ISSUE THREAD

**Issue by alx696** [AnalyticalGraphicsInc/cesium#7403]
* Ubuntu 18.04 Chrome 71.0.3578.80
* Android 8.0 Chrome 70.0.3538.80 Samsung S8
* Cesium 1.52

Problem:
1. Aplha lost;
2. **Model dark** on Android;
3. Below is whiter than above;
4. White Color yellowing(1.43 right, 1.45 little yellowing, 1.52 much yellowing).

Blender file:
https://github.com/alx696/share/raw/master/gltf/box.zip

glTF2.0 file:
https://github.com/alx696/share/raw/master/gltf/box.gltf

> Disable shadows of gltf not work:
```
      let model = viewer.scene.primitives.add(Cesium.Model.fromGltf({
        url: `gltf/box.gltf`,
        modelMatrix: transforms,
        shadows: Cesium.ShadowMode.DISABLED,
        minimumPixelSize: 128,
        maximumScale: 20000
      }));
```
Android WebGL Report: https://github.com/AnalyticalGraphicsInc/cesium/issues/6622#issuecomment-446261050

Model render:
![Model render](https://github.com/alx696/share/raw/master/gltf/box.png)

Ubuntu 18.04 Chrome 71.0.3578.80:
![Ubuntu 18.04 Chrome 71.0.3578.80](https://github.com/alx696/share/raw/master/image/gltf-box%E7%94%B5%E8%84%91%E4%B8%8A%E6%95%88%E6%9E%9C.png)

Android 8.0 Chrome 70.0.3538.80 Samsung S8:
![Android 8.0 Chrome 70.0.3538.80 Samsung S8](https://github.com/alx696/share/raw/master/image/gltf-box%E6%89%8B%E6%9C%BA%E4%B8%8A%E6%95%88%E6%9E%9C.jpg)

> Just now, i found a old phone(GPU Mali-T720). The model show well. But new phones are dark.
![old](https://github.com/alx696/share/raw/master/image/20181212_112514.jpg)

Old Phone WebGL Report:
* WebGL1: https://github.com/alx696/share/blob/master/image/20181212_112615.jpg
* WebGL2: https://github.com/alx696/share/blob/master/image/20181212_112632.jpg

**Comment by alx696** [comment]
Other phone same problem:
> Phone Info: https://www.gsmarena.com/xiaomi_mi_4c-7512.php

https://github.com/alx696/share/raw/master/image/gltf-box%E6%89%8B%E6%9C%BA%E4%B8%8A%E6%95%88%E6%9E%9C-%E5%B0%8F%E7%B1%B3.png

**Comment by likangning93** [comment]
I'm actually able to get the same effect on Adreno 308:

![screenshot_20181211-160617](https://user-images.githubusercontent.com/5395255/49830313-cd6c9a80-fd5e-11e8-8db3-47d58fcf22fb.png)

@alx696  thanks for the model, for anyone else testing here's the scene on [cesiumjs](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZZBNT8MwDIb/StTLOqkk+xKC0U1IgxsSSJM49eK2XheRjylJuw60/467bmKAT/FrP/YbN+BYI3GPji2YwT1boZe15u8nLR4Up3RlTQBp0A2GD5nJTE/w4KD4wPLZBBkOxJ9l7HKJnkNZxl+ZYRQ760mzhs0vG1bgAr3ATPnGWf2ElUP08c14Mk3YbJawyWiY9LC2JSoiz7O6qJ0kYbANYefnQjjY80qGbZ3XHl1BdskEL6wWoNrb+1vht+BQaPABnahU2Ijctrx7DJKfqVoaqWv9JltUa/mJtGI8ubtugLZrWBeguuJkRNFXj5k5dseJkij14aBw2euPUu+sC2RYxZyLgHqngD4u8ppuRx6977BUXKC0lA2T5SKL/tw+i1ihwHuqbGp18pdFy1RQ/y9MWSilqV4bdAoOXct2vHzpRc55Kij9TwVrVQ7uauI3).

**Comment by alx696** [comment]
Cesium 1.43 looks better, But still dark on no sun area:

![1](https://github.com/alx696/share/raw/master/image/glTF%E5%A4%AA%E9%98%B3%E5%85%89%E9%98%B4%E5%BD%B13-%E6%89%8B%E6%9C%BA.jpg)

PC: 
https://github.com/alx696/share/blob/master/image/glTF%E5%A4%AA%E9%98%B3%E5%85%89%E9%98%B4%E5%BD%B11-%E7%94%B5%E8%84%91.png

Android:
https://github.com/alx696/share/blob/master/image/glTF%E5%A4%AA%E9%98%B3%E5%85%89%E9%98%B4%E5%BD%B11-%E6%89%8B%E6%9C%BA.jpg

**Comment by OmarShehata** [comment]
This should be fixed with https://github.com/AnalyticalGraphicsInc/cesium/pull/7944, and will be out with CesiumJS 1.59 coming out next week.
