### ISSUE TITLE
Can't run tests in Chrome 71

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7405]
![image](https://user-images.githubusercontent.com/3451886/49820231-537be780-fd45-11e8-8d42-b3bf1283053b.png)

Windows 10
Version 71.0.3578.80 (Official Build) (64-bit)

Marking this `next release` because we need to be able to run all tests in the browser in order to do the release.

**Comment by OmarShehata** [comment]
I just noticed this by running the Materials Sandcastle example:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Materials.html&label=All

Which crashes after 1-2 seconds.

**Comment by hpinkos** [comment]
@OmarShehata can you open a new issue for that?  It's probably related, but maybe not.

**Comment by mramato** [comment]
1. I can run the tests to completion on Linux (Intel chipset)
2. The materials example does indeed crash for me in Sandcastle.

@hpinkos can you hardcode the HDR default to false and try again?  That would tell us really quick if HDR is the culprit.

**Comment by mramato** [comment]
Is anyone else having problems with the tests CC @lilleyse @bagnell @likangning93 we need to get to the bottom of this ASAP

**Comment by hpinkos** [comment]
Hmm, I just ran all the tests again both with and without hdr enabled and they both passed.  I guess I'll close this for now?

**Comment by mramato** [comment]
Sounds good.  Materials issue is still a real problem but hopefully that's an easy fix.

**Comment by hpinkos** [comment]
Yeah, I see that crash too
