### ISSUE TITLE
Cesium color Change between 1.51 and 1.52

### ISSUE THREAD

**Issue by AtofStryker** [AnalyticalGraphicsInc/cesium#7417]
Hey Cesium Team,

Does anyone know why the background shade on the globe has changed between these two versions? I am using openstreetmaps as my imagery provider.

here is a picture of the content. cesium 1.52 on the left and 1.51 on the right
![image](https://user-images.githubusercontent.com/3980464/50030669-85e64880-ffc2-11e8-82cd-f364d33027bf.png)

 I can provide more code if needed.

**Comment by hpinkos** [comment]
Hello @AtofStryker!  Yes, we added HDR support in 1.52 which is probably why the map looks like it's colored differently.

You should be able to get the old behavior by adding the line `viewer.scene.highDynamicRange = false;`

I'm going to close this issue, but if that doesn't work for you, let me know!

**Comment by AtofStryker** [comment]
@hpinkos Thanks! Ill give it a try and will let you know if I have issues.

**Comment by mramato** [comment]
This definitely looks like a bug, @hpinkos.  All billboards shouln't suddenly be the same color.

**Comment by mramato** [comment]
@AtofStryker were you explicitly asking about the background share or the billboards in the foreground as well?  I might have misread it and @hpinkos might have been right to close this.

**Comment by AtofStryker** [comment]
@mramato the question only pertains to the color hue. I changed the color of the billboards. No worries! @hpinkos was right to close the issue

**Comment by mramato** [comment]
Thanks (and sorry for the confusion on my part)
