### ISSUE TITLE
add ArcGisMapServerImageryProvider error

### ISSUE THREAD

**Issue by chaomashi** [AnalyticalGraphicsInc/cesium#7435]
i  add a  layer to map, error message
a mistake occurred in "ArcGisMapServerImageryProvider": Tile spatial reference WKID 4490 is not supported.
so how to set 4490 Coordinate System in cesium

**Comment by hpinkos** [comment]
Hello @chaomashi,  Cesium does not support that tiling scheme.   The `ArcGisMapServerImageryProvider` supports WKID 102100, 102113, and 4326.  You may need to configure your map server to use one of these tiling schemes instead.

If you have any follow up questions, please ask on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by mramato** [comment]
This may be something we can support once #7438 is implemented, I'll add a note there
