### ISSUE TITLE
Double click not working on mobile

### ISSUE THREAD

**Issue by andreddosantos** [AnalyticalGraphicsInc/cesium#7440]
Hello guys,

I'm using Cesium 1.51 on a hybrid mobile app with angular and i'm not being able to trigger the left_double_click event.

```javascript
    handler.setInputAction(click => {
      console.log("double click");
    }, Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
```

Best regards 
André Lopes Santos

**Comment by OmarShehata** [comment]
I don't think mobile browsers support a "double touch" event, see the discussion here:

https://github.com/AnalyticalGraphicsInc/cesium/issues/6771#issuecomment-402911921

**Comment by hpinkos** [comment]
Hi @andreddosantos, yes unfortunately double-click isn't a behavior supported by touch devices.  Cesium doesn't have any special logic for recognizing a double click, it just listens for a dblclick event to be fired from the browser.  And the browser on a mobile device won't fire a dblclick event.
