### ISSUE TITLE
could you add more style expression functions, such as Array.indexOf()

### ISSUE THREAD

**Issue by hanaimin** [AnalyticalGraphicsInc/cesium#7445]
could you add more style expression Array functions?

I my case, there is a Array typed field in batch table. If the array contains some value, the tile feature should be styled.  The condition may be like this: [id1,id2,id3,id4,id5,id6,id7].indexOf(idx);
But cesium expression functions no support Array.indexOf().

I try to use regExp instead. The expression is like this "regExp("regstr").test(String(${__ids}))", the result is not good enough because of poor performance and sometimes incorrect matched.
so, could you add more style expression functions, such as Array.indexOf()

**Comment by lilleyse** [comment]
I followed up in https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/365 from a 3D Tiles spec point of view, but in Cesium you don't necessarily need to use the styling language to color features. It's possible to use plain JavaScript. See the second example here: https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileStyle.html?classFilter=Cesium3dtilestyle#color.

You could try something like:

```js
style.color = {
    evaluateColor : function(feature, result) {
        var values = feature.getProperty('id');
        if (values.indexOf('idx') !== -1) {
            return Cesium.Color.clone(Cesium.Color.YELLOW, result);
        } else {
            return Cesium.Color.clone(Cesium.Color.WHITE, result);
        }
    }
};
```

**Comment by hanaimin** [comment]
@lilleyse thanks, it's a solution.
