### ISSUE TITLE
Control camera home angles?

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7450]
You can currently override where the camera goes when clicking on the home button by editing [Camera#.DEFAULT_VIEW_RECTANGLE](https://cesiumjs.org/Cesium/Build/Documentation/Camera.html?classFilter=Camera#.DEFAULT_VIEW_RECTANGLE). 

However, I don't see an easy way to set a particular pitch/heading/roll offset for that. This was brought up in [this forum thread](https://groups.google.com/d/msg/cesium-dev/q1LGWUQqHRk/bCq-ow7MCQAJ). I wonder if at that point it'd be easier just to give the user a callback they can define to run whatever custom camera/fly code they want for the home view? Or maybe in those cases the right thing to do is for the user to just make their own button?

**Comment by hpinkos** [comment]
duplicate #6134

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/q1LGWUQqHRk/bCq-ow7MCQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7450 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
