### ISSUE TITLE
Shared Sandcastle demos no longer load

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7466]
![screen](https://user-images.githubusercontent.com/915398/50730570-3c4ed080-111e-11e9-9b84-3d908142beb7.PNG)

http://localhost:8080/Apps/Sandcastle/index.html#c=ZYw7C8IwFIX/SsjSCpLgbFoEV8FBcMqStlcN3iYlr1J/vWlF8HG28/hOUo4kDSM4UhEDI9mD17Fn5yUri3axe2uC0gZcsdpKQ9dU+DAh1NKQrJ3uB+sCiQ5LxniAfkAVwPMmtncIrPV+xgR/Q6LTieiukvTnXlLSovI+N5eIeNIPkLQWPO+/MLSq0+Z6TOBQTfPktqkPr5AxJni2/1SwFhvlPh6f

git bisect points to https://github.com/AnalyticalGraphicsInc/cesium/pull/7250/commits/bbc7df6eb08d6f586067762aebfc68481b70bd87

**Comment by OmarShehata** [comment]
Wow, that's pretty bad! Not sure how I missed that. Fortunately it's an easy fix. I'll open a PR soon, for now you can change this line:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/CesiumSandcastle.js#L745

with:

```
var data = decodeBase64Data(base64String, pako);
```

And then change this line:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/Sandcastle-helpers.js#L20

to:

```
window.decodeBase64Data = function(base64String, pako) {
```
