### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by secretxu** [AnalyticalGraphicsInc/cesium#7467]
![image](https://user-images.githubusercontent.com/8953164/50732098-95fedb80-11ae-11e9-8417-82509f1f19b6.png)

it should be (x,y,z,w).

**Comment by hpinkos** [comment]
Thanks @secretxu! Would you be interested in opening a pull request to fix this? You can find instructions here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request
