### ISSUE TITLE
Cesium crashes in old versions of Chrome and Firefox

### ISSUE THREAD

**Issue by dennisadams** [AnalyticalGraphicsInc/cesium#7472]
Cesium crashes in browsers with old versions of ANGLE when using D3D9, since Cesium 1.50.

<img width="960" alt="atmospherecolor issue pic" src="https://user-images.githubusercontent.com/29460712/50836578-33e6d780-1362-11e9-88fa-f4193ca66cc4.PNG">

This happens to me on Windows 10 x64, with Chrome 59 after disabling D3D11.

GL_RENDERER: ANGLE (NVIDIA GeForce 940MX Direct3D9Ex vs_3_0 ps_3_0)

GL_VERSION: OpenGL ES 2.0 (ANGLE 2.1.0.a9042d3c1952)

It's caused by an old ANGLE bug triggered by this [line](https://github.com/AnalyticalGraphicsInc/cesium/blob/84ca98d95308e1875ddb580125e9ec8fa7cdc2c2/Source/Shaders/GroundAtmosphere.glsl#L97) in GroundAtmosphere.glsl:
```
float fLightAngle = useSunLighting ? dot(czm_sunDirectionWC, v3Pos) / length(v3Pos) : 1.0;
```
which was added in Cesium 1.50.
On my machine, the above line is translated to the HLSL code: (with my comments)
```
{
bool s6 = _webgl_38a54cf7838b624e; // _webgl_38a54cf7838b624e is useSunLighting
if (s6)
{
(s3 = (dot(_webgl_fa5fcdcb25e91339, _webgl_fa0dc18b0c5cfc1c) / length(_webgl_fa0dc18b0c5cfc1c)));
}
else
{
if ((!s6))
{
(s3 = 1.0);
}
else
{
return (webgl_cd16f13802bc8948)0; // webgl_cd16f13802bc8948 is the AtmosphereColor constructor, notice it's missing a "_" prefix
}
```
The last else section isn't even needed but seems to be a workaround to an HLSL error, see this [ANGLE commit](https://chromium.googlesource.com/angle/angle/+/b6c94e1bb81a3edf885b6831bbd9056693e50828%5E%21/) for more details. This workaround appends a dummy return value, whose type is taken from the current function's return type.
But due to a [bug in ANGLE](https://bugs.chromium.org/p/angleproject/issues/detail?id=2061), if the current function's return type is a custom struct (like AtmosphereColor in our case) then the constructor of the dummy value isn't prefixed with a "_", and so it causes an undefined identifier error and a program linking failure. This bug was fixed, but it still affects old versions of Chrome and Firefox.

This seems to be the same issue mentioned in the forum: [https://groups.google.com/forum/#!topic/cesium-dev/okbIEFu5Hcw](https://groups.google.com/forum/#!topic/cesium-dev/okbIEFu5Hcw), regarding Firefox.

On my machine I can simply use a newer version of Chrome and that will solve the problem, but I've encountered it also on other standalone devices with old chrome versions.

Two possible simple workarounds that have worked for me are:
1. Make the `computeGroundAtmosphereFromSpace` function a void type with an `AtmosphereColor` out argument.
2. Instead of using a ternary operator, use `mix()`.

I'll be glad to open a pull request.

**Comment by hpinkos** [comment]
Thanks for reporting this @dennisadams!  Just to clarify, Cesium 1.49 works on these browsers but 1.50 does not?

@bagnell @lilleyse please advise

**Comment by dennisadams** [comment]
@hpinkos that's right. The mentioned line triggering the ANGLE bug was part of #6877 and was introduced in Cesium 1.50.

**Comment by hodbauer** [comment]
This issue happend to my customer too.
He have for some reasons old version of chrome.
The solution that we use to solve it is:
```js
var globe = new Cesium.Globe();
globe.showGroundAtmosphere = false;
var viewer = new Cesium.Viewer('cesiumContainer', { globe: globe });
```
I know that it's less beautiful, but it works.

**Comment by tfili** [comment]
@dennisadams @hodbauer I think I have a fix for this (https://github.com/AnalyticalGraphicsInc/cesium/pull/7857). Could you give the `angle-ternary-bug` branch (https://github.com/AnalyticalGraphicsInc/cesium/tree/angle-ternary-bug) a try and see it fixes it for you?

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/okbIEFu5Hcw](https

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7472 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
