### ISSUE TITLE
globe.cartographicLimitRectangle can't be unset

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7477]
If you try setting `globe.cartographicLimitRectangle` to `undefined` after it has previously been set, it will crash.

<img width="486" alt="crash" src="https://user-images.githubusercontent.com/915398/51002621-da1d1380-1501-11e9-8f26-1bbb1f0a4541.PNG">

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=jVDBTsMwDP2VqJd20kjZed2E2HUSEkWccvESb7NIkypxOg3Ev5O1GmJwIQdHfn7Pz/YAQQyEJwxiJRyexAYjpU6+jlhV6jHdeMdADkM5Wyo3ZM3B+h1myaSVUaNDOYKZMP5SQ2B/CNAfSW+pI35GzZCLeGv1DVd3C3k/F1O8houhci04oyGyRQnGvHhvdxAeE7N3Vdke/amci31ymikDM/GhnMjvH3MkZ3CfNzPZ5nO2LOZFE/lscT11eKCu94FFCraSsmbseguMsd4l/YYsdYyXAZv6KmoMDYLMShW/LqcKoS3EmCv7ZG1L76iKdVNn/o3MejDkDk8DBgvnC+W4WG8nUErZ1Dn9q+LpIj86fgE)

@likangning93 any ideas?

**Comment by likangning93** [comment]
The shipped Sandcastle demo treats the "deactivation" case as `Rectangle.MAX_VALUE`, which is default.
Under-the-hood `GlobeSurfaceTileProvider` always checks tiles against the limiter rectangle but only modifies shaders for terrain tiles that intersect, so the default of `Rectangle.MAX_VALUE` shouldn't cause any shader modification.

I think it's the right level of abstraction to modify the setter in `Globe.js` so setting `undefined` percolates a `Rectangle.MAX_VALUE` down.

**Comment by lilleyse** [comment]
That approach makes sense. Also `cartographicLimitRectangle` seems to be missing documentation - https://github.com/AnalyticalGraphicsInc/cesium/pull/6987#issuecomment-438227934. It would be good to fix that too.
