### ISSUE TITLE
ClampToTerrain Sandcastle example crashing in MacOS

### ISSUE THREAD

**Issue by malaretv** [AnalyticalGraphicsInc/cesium#7480]
Sandcastle example: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clamp%20to%20Terrain.html

Browser:
Chrome 71.0.3578.98 (Official Build) (64-bit)
Firefox 64.0.2 (64-bit)

Operating System:
MacOS 10.12.6
MacBook Pro (Retina, 15-inch, Late 2013)
NVIDIA GeForce GT 750M

Issue: I've been getting error reports from some users running OS X where our application would crash when loading entities. I asked them to try the above sandcastle link which also seems to trigger the crash. The browser or the whole system will hang for them so it's difficult to get any debugging info. Notably, however, it seems to work just fine in Safari.

**Comment by hpinkos** [comment]
@malaretv What's the error you're seeing?  Can you also copy/paste the results from http://webglreport.com/?  That will help us track down the issue.

Can anyone with with a mac confirm this? @lilleyse @ggetz?

**Comment by malaretv** [comment]
Thanks @hpinkos. I'm getting these reports from a couple users second-hand. They say there is no error but the browser and sometimes the whole system just hangs. I'll double-check with them if they can grab anything from the console output that may help.

Here's the output from webglreport they sent me previously
```
Platform:     MacIntel
Browser User Agent:     Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 Firefox/64.0
Context Name:     webgl2
GL Version:     WebGL 2.0
Shading Language Version:     WebGL GLSL ES 3.00
Vendor:     Mozilla
Renderer:     Mozilla
Unmasked Vendor:     NVIDIA Corporation
Unmasked Renderer:     NVIDIA GeForce GT 750M OpenGL Engine
Antialiasing:     Available
ANGLE:     No
Major Performance Caveat:     No
```

**Comment by malaretv** [comment]
One of the users experiencing the issue upgraded their OS and the problem has gone away. Probably just some weird bug with that OS + hardware combination. Closing this issue

**Comment by mramato** [comment]
Thanks for the update @malaretv.  The fact that the entire system was hanging does indeed point to a larger problem than anything Cesium could be doing directly.  Glad to hear an update fixed it.
