### ISSUE TITLE
IBL Example crashes on IE11

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7485]
* Open in IE11: http://localhost:8080/Apps/Sandcastle/index.html?src=Image-Based%20Lighting.html
* Observe crash

I can't seem to find a way to turn off IBL (it's crashing a test model for me in an example where I don't care about IBL). @bagnell

**Comment by hpinkos** [comment]
Marking this `next release`.  
How did this get merged without IE11 working?  That's why we added those checkboxes to concierge.

**Comment by ggetz** [comment]
@bagnell Reminder that this needs to be looked at soon. The release is on Friday.
