### ISSUE TITLE
Explicit Rendering Delays 3D Tiles Loading

### ISSUE THREAD

**Issue by KermMartian** [AnalyticalGraphicsInc/cesium#7489]
**Summary:** When [explicit rendering](https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/) is enabled, 3D tiles are not loaded (or refined/anti-refined) until the scene is jiggled, panned, or zoomed (i.e., the render loop is forcibly executed).

**Steps to Reproduce:**
1. Instantiate Cesium Viewer with `requestRenderMode : true` and `maximumRenderTimeChange: 20.`
2. Add your favorite tileset: `this.viewer.scene.primitives.add(new Cesium.Cesium3DTileset({...}));`
3. Wait. Then wait some more. Keep waiting. Realize nothing is happening, jiggle the scene around for a few seconds, and voila, models.

Thanks in advance for any help (or suggestions, if this is something known and/or fixable on my end). Please let me know if there are any further details I can provide.

**Comment by mramato** [comment]
Thanks for reporting @KermMartian, this is unfortunately a known issue and something we need to address.  Keep your eye on #6898 (I'm closing this since it's the same problem).
