### ISSUE TITLE
generateDocumentation in watch mode

### ISSUE THREAD

**Issue by bampakoa** [AnalyticalGraphicsInc/cesium#7500]
Hey all,

I have noticed that the gulp task `generateDocumetation` runs one time only. It would be great, especially for those that create documetation, to keep it running, watching files and executing as soon as there is a change. What are your thoughts on this?

**Comment by hpinkos** [comment]
Good idea @bampakoa!  We probably don't have time to look into this very soon, but pull requests are welcome =)
