### ISSUE TITLE
Cesium label RTL bug

### ISSUE THREAD

**Issue by ArielLichter** [AnalyticalGraphicsInc/cesium#7501]
Hi,
There is a bug with RTL in cesium label,
Below there is a reproduce in Sandcastle.
We can see that the single quote mark should be before space and not after.

Sandcastle example: 
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVDLbsIwEPwVyxeCRB1RCogSUCU4IlVqq558cZIFVnVsZG9CacU/tP05fqdOAlIfc/LOzszuulKOVQh7cGzGDOzZAjyWhXhuuKiTNeXCGlJowHW6U2mkOYtWKgUtwKhUwwNutvRkV7CmJRBkhNaESHIlBEs7IkgJCcELlefRuzQsYGc9NuLby+yFchReygzE2tliCRsH4KOr8VD0Rzf90WjcY4OJmAyva3R7bY6ulwkh59gaBK8UGMlPH6fPDjt9Sd42j9Icu1Pe44mng4Z5y95hsbOOWOl0JERMUOy0CpvEaZm9AInM+/r8JL6YkhwrhvlM8j/fJDnLtPI+dNal1o/4BpLPkzjof9m0VTmazX0FTqtDLdn256uWFEIkcSj/u8hanSr3I/Eb

Browser:
Chrome 71.0.3578.98

Operating System:
Windows 7

Thanks!

**Comment by OmKoren** [comment]
Thanks Ariel.
This is related to: https://github.com/AnalyticalGraphicsInc/cesium/pull/5771
As @hodbauer did most of the work there, I bet he'll fix it soon.

**Comment by hpinkos** [comment]
Thanks @ArielLichter, @OmKoren!  The fix in #7517 has been merged and will be included in the 1.55 release available March 1st.
