### ISSUE TITLE
Remove deprecated option followSurface in 1.57

### ISSUE THREAD

**Issue by shehzan10** [AnalyticalGraphicsInc/cesium#7504]
From CHANGES.md:

> * `PolylineGeometry.followSurface` has been superceded by `PolylineGeometry.lineType`. The previous definition will no longer work in 1.57. Replace `followSurface: false` with `lineType: Cesium.LineType.STRAIGHT` and `followSurface: true` with `lineType: Cesium.LineType.GEODESIC`. [#7492](https://github.com/AnalyticalGraphicsInc/cesium/pull/7492)
> * `SimplePolylineGeometry.followSurface` has been superceded by `SimplePolylineGeometry.lineType`. The previous definition will no longer work in 1.57. Replace `followSurface: false` with `lineType: Cesium.LineType.STRAIGHT` and `followSurface: true` with `lineType: Cesium.LineType.GEODESIC`. [#7492](https://github.com/AnalyticalGraphicsInc/cesium/pull/7492)

**Comment by shehzan10** [comment]
Ensure that CZML can continue to use `followSurface` and it maps to `arcType`. https://github.com/AnalyticalGraphicsInc/cesium/pull/7582#discussion_r258695385

**Comment by tfili** [comment]
@shehzan10 Can you remove the deprecated options for the next release?

**Comment by tfili** [comment]
Fixed in #7799
