### ISSUE TITLE
Built Sandcastle shouldn't require individual Cesium classes

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7523]
Trying to deploy the built version of Sandcastle is a nightmare because it depends on resources that aren't copied over to the built folder, like some things in `Apps/Sandcastle` and `Source/defined` and `Source/Resource`:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/CesiumSandcastle.js#L54-L55

**Comment by mramato** [comment]
It was never meant to be deployed without the rest of Cesium, "built" just refers to the fact that it is using the built version of Cesium for the Sandcastle examples themselves.

That being said, if `defined` and `Resource` are the only two things stopping us from making it truly standalone, they could probably be removed completely and replaced with standard browser functions (in Sandcastle proper).
