### ISSUE TITLE
ellipse color alpha is change when intersection

### ISSUE THREAD

**Issue by amirlic** [AnalyticalGraphicsInc/cesium#7526]
in this code the final alpha is 1 but i need this stay 0.5 and will be transperent.

var viewer = new Cesium.Viewer('cesiumContainer');
var color = new Cesium.ColorGeometryInstanceAttribute(0.0, 1.0, 1.0, 0.5);

var ellipseInstance = new Cesium.GeometryInstance({
    geometry : new Cesium.EllipseGeometry({
        center : Cesium.Cartesian3.fromDegrees(-105.0, 40.0),
        semiMinorAxis : 300000.0,
        semiMajorAxis : 400000.0
    }),
    id : 'ellipse',
    attributes : {
        color : color
    }
});
var ellipseInstance2 = new Cesium.GeometryInstance({
    geometry : new Cesium.EllipseGeometry({
        center : Cesium.Cartesian3.fromDegrees(-105.0, 40.0),
        semiMinorAxis : 300000.0,
        semiMajorAxis : 400000.0
    }),
    id : 'ellipse',
    attributes : {
        color : color
    }
});
var ellipseInstance3 = new Cesium.GeometryInstance({
    geometry : new Cesium.EllipseGeometry({
        center : Cesium.Cartesian3.fromDegrees(-105.0, 40.0),
        semiMinorAxis : 300000.0,
        semiMajorAxis : 400000.0
    }),
    id : 'ellipse',
    attributes : {
        color : color
    }
});
viewer.scene.primitives.add(new Cesium.GroundPrimitive({
  geometryInstances : [ellipseInstance,ellipseInstance2,ellipseInstance3],
}));

viewer.zoomTo(viewer.entities);

**Comment by hpinkos** [comment]
Sorry no one responded to this @amirlic.  This is working as expected.  When transparent object overlap, the intersections are less transparent.

![image](https://user-images.githubusercontent.com/3451886/65278149-75d33a80-daf9-11e9-9eb8-bf62f6f0530b.png)

I don't believe we have a way to set the colors to keep the same transparency values at intersections.
