### ISSUE TITLE
Moving Entities causes them to disappear

### ISSUE THREAD

**Issue by BenHall-1** [AnalyticalGraphicsInc/cesium#7529]
Browser: Chrome 64-Bit 71.0.3578.98
Operating System: Windows 10

When we go to move an entity using tween, it makes it disappear for some reason

`var entity = viewer.entities.add({
name : 'images/Thonker.glb',
    position : position,
    orientation : orientation,
    model : {
        uri : 'images/Thonker.glb',
        minimumPixelSize : 128,
        maximumScale : 20000
    }
});`

`function run(i) {
    // animate 
    var tween = tween || scene.tweens.add({ 
        update: update,
        startObject: { 
            x: list[i], 
            y: list[i + 1]
        }, 
        stopObject: { 
            x: list[i + 3], 
            y: list[i + 4]
        }, 
        duration: 1.0, 
        easingFunction: Cesium.EasingFunction.LINEAR_NONE  
    });
    tween = undefined;
    current += 3;
    if(current >= list.length) {
        clearInterval(interval);
    }
}`

**Comment by hpinkos** [comment]
@BenHall-1 I'm not quite sure what you're trying to achieve.  However, entities have built in time-dynamic support so you don't need to use a tween to move it.  Take a look at this interpolation example:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Interpolation.html

If you have any follow up questions, please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
