### ISSUE TITLE
Un-pin version changes for eslint

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#7536]
Once https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/113 is fixed, undo pinned version changes in `package.json` from https://github.com/AnalyticalGraphicsInc/cesium/pull/7535.

**Comment by mramato** [comment]
Looks like this is fixed, in addition to unpinning, we should bump both eslint and eslint-plugin-html in package.json to their latest versions to make sure there's no mismatch.

**Comment by hpinkos** [comment]
👍 thanks @mramato
