### ISSUE TITLE
Unable to remove Fog/Atmosphere

### ISSUE THREAD

**Issue by Jetroid** [AnalyticalGraphicsInc/cesium#7540]
Sandcastle example: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Sky%2520Atmosphere.html Can easily be seen here. Clicking the 'Fog' toggle does nothing.

Browser: Google Chrome 69.0.3497.100

Operating System: Arch Linux 4.20.3-arch1-1-ARCH

I'm upgrading my version from 1.44 to 1.54. 

By default, Cesium has [a glow and fog that I don't want](https://i.imgur.com/8dofIEf.png). 

In 1.44, I did this:
```
var viewer = new Cesium.Viewer('cesiumContainer', {
  skyAtmosphere: false,
});
```
and [both the 'glow' around the planet, and the blue fog/atmosphere go away](https://i.imgur.com/iydsY8V.png). In 1.54, the glow correctly goes away, but I [still see the blue fog/atmosphere](https://i.imgur.com/gC4eqsw.png). 

I've checked CHANGES.md for any changes relating to this since then, and I see that some atmosphere related things were added in 1.50 and 1.51, but nothing listed as breaking. 

The fact that an official demo (see Sandcaste link) has a checkbox that (I believe) should remove this effect, but that the button in fact does nothing, implies to me that this is a bug.

**Comment by lilleyse** [comment]
The new atmosphere is called ground atmosphere and was added in 1.50 and has its own Sandcastle demo: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Ground%20Atmosphere.html.

You can disable all atmosphere effects with:

```js
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

scene.skyAtmosphere.show = false;
scene.fog.enabled = false;
scene.globe.showGroundAtmosphere = false;
```
