### ISSUE TITLE
Allow custom BlendingState on EllipseGraphics

### ISSUE THREAD

**Issue by nitzanmo** [AnalyticalGraphicsInc/cesium#7541]
Hi,
I'm currently working on an application which should draw multiple ellipses one on on top of the other, each with its own outline.

However, when ellipses collide, the collided section's translucency (alpha levels) increase until the terrain is hidden.

Screenshot:
![unnamed 1](https://user-images.githubusercontent.com/16973137/52280531-ccbe4200-2964-11e9-882d-f86901adf5ad.jpg)

I have found a solution to this problem (And am aware that the solution is already implemented with other geometric shapes, e.g rectangle and circle), but it required:
1. Creating a custom blending mode: 
```
 CUSTOM_BLEND: freezeObject({
            enabled : true,
            equationRgb : BlendEquation.**MAX**,
            equationAlpha : BlendEquation.ADD,
            functionSourceRgb : BlendFunction.SOURCE_ALPHA,
            functionSourceAlpha : BlendFunction.SOURCE_ALPHA,
            functionDestinationRgb : BlendFunction.ONE_MINUS_SOURCE_ALPHA,
            functionDestinationAlpha : BlendFunction.ONE_MINUS_SOURCE_ALPHA
        }),
```
2. Returning the custom blending mode when translucency is true, instead of the hardcoded ALPHA_BLEND.
(Code section: )
```

    /**
     * Creates a render state.  This is not the final render state instance; instead,
     * it can contain a subset of render state properties identical to the render state
     * created in the context.
     *
     * @returns {Object} The render state.
     */
    Appearance.prototype.getRenderState = function() {
        var translucent = this.isTranslucent();
        var rs = clone(this.renderState, false);
        if (translucent) {
            rs.depthMask = false;
            rs.blending = BlendingState.**CUSTOM_BLEND**;
        } else {
            rs.depthMask = true;
        }
        return rs;
    };

```

After the change : 

![unnamed](https://user-images.githubusercontent.com/16973137/52280508-bfa15300-2964-11e9-9bf9-e17b59b0743c.jpg)

An option to pass a custom blending state would be a better solution to the problem.

However, this is not the optimal solution since it fixates the alpha levels of the collided section.

**Comment by OmarShehata** [comment]
Thanks for explaining your use case here @nitzanmo ! I'm closing this so we can keep discussion in the issue here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7203

And we have a link to this issue from the other one further elaborating your use case.
