### ISSUE TITLE
Camera considers North America to be home in 2D

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium#7546]
Cesium's camera considers "home" in `SceneMode.SCENE2D` to be `Camera.DEFAULT_VIEW_RECTANGLE`, which roughly covers North America.

@bagnell thinks this should be `Rectangle.MAX_VALUE` to better correspond with Columbus View, which considers a view over the entire map to be "home."

**Comment by hpinkos** [comment]
This is working as expected.  We can revisit later if we decide to make a change to the "home" behavior
