### ISSUE TITLE
GroundPolylinePrimitive has incorrect height with custom ellipsoid

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7552]
This is part of several issues that came up when clamping to terrain with custom terrain and a custom ellipsoid on the forum: https://groups.google.com/d/msg/cesium-dev/LxJDKmIDu8I/S-j10RcLFQAJ

This Sandcastle code will create a polyline somewhere on the earth using a smaller ellipsoid (to represent the moon):

```
var ellipsoid = new Cesium.Ellipsoid(1737400,1737400,1737400);

Cesium.Ellipsoid.WGS84 = ellipsoid;
var mapProjection = new Cesium.GeographicProjection(ellipsoid);

var globe = new Cesium.Globe(ellipsoid);
globe.showGroundAtmosphere = false;

var viewer = new Cesium.Viewer('cesiumContainer', {
    mapProjection: mapProjection,
    globe: globe
});

viewer.entities.add({
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArray([
        -12.86401, -42.43998,
        -9.47402, -44.37729
        ], ellipsoid),
        //clampToGround : true,
        width : 5,
        material : new Cesium.PolylineOutlineMaterialProperty({
            color : Cesium.Color.ORANGE,
            outlineWidth : 2,
            outlineColor : Cesium.Color.BLACK
        })
    }
});

viewer.zoomTo(viewer.entities);
```

[Live link](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=bVLLctowFP0VDZuYGUfm4ZZHCFNKMyySlkySaRZ1F8K+gFpZ1yPJMKTDv0fGBj8ab6R77jnnPuQdUwSE4IlGHpFbImFP5qB5GtO7M+x0B/2B3+m4jbN9E8hANtn0dfE89K3VxdbSdrZMzJJHhX8gNBxlvdQCcKNYsuVhyXAu+rxOZrERuIKGNIPq3BOL6i3uFwpTGc1MjDrZgsqkayY0XAx3HPag6o4/T5hzFZ7COUrDuAR15ZJ/gST2qw0yroduTjm1MM6PQB6LCU7GFKThhoOmLIqcwjJBcRC2Chmfi+So5pmptnDR3JwpY29M9ulaYfwNNgpAz5RiB+dXqbzu9ujws9/puuTa71G/PxoN3Up6RH37gr0s69P+YNAblcnfbvl07YrI80LB4uQF863anoxKoULY88hsLfypgsXMgOJMWLiy4sdi3GVqsuN7QbJrTECZg1PZQfaFKFBVdpCFdPk0+7G4c+tMzA1fi056H6fnH/l9fZjN70v6sZ3fj83ne0OMX9BpPGb7puW2JtocBExz4RceJ6gMSZVwKPUMxImwc2pvlYZ/wdBQ68x34p1Fk4jvCI9ug1bjzwtaxG5ea5tZp0I88zcIWtOJZ/k1mUAWcblZ7kAJdsgo2+70IQcppRPPhv+rDKJYMVVxfAc).

Everything looks fine, but then uncomment `//clampToGround: true` and you'll see that the polyline disappears into space. If you apply the following monkey patch to turn on debug bounding volumes for the GroundPolylinePrimitive (or just set it to true when running this locally in `GroundPolylinePrimitive.js`. 

```
setTimeout(function(){
    viewer.scene.groundPrimitives._primitives[0]._primitives[0]._collections[0]._primitives[0].debugShowBoundingVolume = true
}, 1000);
```

You can see that the bounding volume is way high, I'm guessing hardcoded to the Earth's ellipsoid height?

![zoom-out](https://user-images.githubusercontent.com/1711126/52484678-f1910000-2b84-11e9-8174-42df052fccb1.png)

My best guess is that this is because `GroundPolylinePrimitive` uses the `ApproximateTerrainHeights` which is all the Earth's terrain heights?

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/GroundPolylinePrimitive.js#L359-L368

Maybe we should allow overriding a min/max terrain height when creating polylines on non-earth ellipsoids? There's a similar problem that can be seen for the shadow volumes for groundprimitives that I can open a separate issue for.

**Comment by malaretv** [comment]
Hey @OmarShehata thanks for all your help on this issue!

After playing around with `ApproximateTerrainHeights` for a bit, it seems that the issue was actually in the `GroundPolylineGeometry` constructor not accepting an ellipsoid option to override the WGS84 default.  

Re: the initial lunar example posted in the forums: While the above pull request means the line is now drawn near the surface, it tends to be hidden beneath terrain when moving the camera from anything but a straight top-down view. Initial experiments with a custom `approximateTerrainHeights.json` file and modifying the default min / max in `ApproximateTerrainHeights` have definitely been promising but not perfect! Will open another issue with some examples when I have some time.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/LxJDKmIDu8I/S-j10RcLFQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7552 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by hpinkos** [comment]
Thanks for reporting this @malaretv!  A fix was added in #7566 and will be included in the CesiumJS 1.55 release available March 1st

**Comment by OmarShehata** [comment]
@malaretv just followed up, same forum thread. [Here's a Sandcastle with a polyline on a lunar crater](https://cesiumjs.org/releases/1.56/Apps/Sandcastle/index.html#c=xVdtc9o4EP4rmnwBekRg3qFp50hKU6YkZApppnPcZIQtsC6y5ZFkKO3kv9/KMhgDTb705pjMON59drXS7j4rr4hElHMWKcE89A6FdI2uqGJxgAdbcdFp19uNarV88Cy9nYWz8BCNH64nnQa42rkF2AqWCUh0J8U/1NVMhPmlrqlYShL5zM0QxZ29Xce4WHIxpwemRpTHJiisfLG+liIOvb4OhIp8Ko3pgnBF36JKBZy4VCkiN2ghJNKMU4W0QMYOsRCFIjynRGo/28jWtUcj7U+p0v0lYaHSUyol/APetYxpul1thbChFfOozEdtH9M8pPhzFiL4xZL3UMHXOlK9SmVhAsPE1UuiKXZFUEk9V3gcEvm45J5TrRbK1nYXa28/7OfsCEWkFcSSLpXLSS//mnpMttyzj1R0sLXeoSCFqadNdvQ9e/JlE4dRQgI+ARbFYZaH+2FqSLkNYRh6zCVayMza6OdE0RHZUHnH3Cd6oNQsoJyFNC9dUuEK7xDLwoW4FN/zQuXSkN4A+JR3ErKA2MNKxFYKJ7w74BWj68N0f01kxYKbvF6JUMNpUVkoJ+kwybFWOFkbL8QS05DMOfV2FWudw+JLKjfJ5k0aU7OcGKC5d0w8b2gFu0rbi+2Bzm9INKFyxVx6iMsqEu2V5JrOoVIwl8LFRMWYenFlW4DchgZoU56Pa+I+mtIhfAuIiCQB1RaU+k/yJkmoQElDDQrTSOVMCR0Kx268JlurROGyYLXPu7RD0pcT16cBpP4kt0z3IMWfJ1sFPZcyf/SBedrvoaZT2xN+omzp60RqGst21iysvHkzC+8Eg+j/QCMypxx9pETHQDpDpWKqDMgpoTmD/iOhhyJm6h6JBRyZQS8FCphSECGaU58BIu0qtPZpiBTZoB9CBEYPMuNBxBotpAgQmYsVVGKtlCCMWguBXC4UTYBzASwWJbGZV7seMEnEIQ98gzymSBQB2c3CeslsUiMXciQJBKldH3libVwiLsQTIgqxhV0X/Gp4wBZcCeQkkYrlgrh2Ucgj0xu0go5Rvtn+m8quzBMdo0lpbmssEorZxtpyJJAv/EfCOjarfaBLSakqnjsOrjnNehmdN+q41m12yiiMOS9nWdzm0G45V2Wu4ED22RrmFU8+f7sc3Q/26i1i3ymfsB8UoE51TwFnbsjl6pSbb4PRaPxwDE7KCMD1PZWfVNEXugBqDF2aufqUV+CrUf/m7nE6frz+Mr6//ZAvepvJfBvR70mfTDeuLwq5FkrOouA0Ig3VFKpzRSVbFH5DUPsuhGQ/DL/xsWRLqMTMx4EGjwYfp3uWKyo1kP2R3decHF/2J4PR8HY/WTAh+cmEXI76V5/3gGa0XxL3aZlcC45ZZr7Tbd3tj2wjKjplZP+quF06aXoHNW2aNG+8reVaEcq1sW9ZqZj2A67/sL1VfGBKE3v+t3Ewh365G0+G0+HXwePw9uPwdjj9ZsanJ8kabiw+TcsADg36BJIM/ZhSR1otuwtASlMjKMojdnL+u84HYjJ9ADwTKSA3DhesLbcBqcNcYyJWtlsVoiqiLiMceCkhPhOUOc80roTAIBojIsmBv8osu6YWfJPEkWuYTGv5R6FXGKgPkW+Kfx17OHdquNNqVB1DTTXcqHe7nfIJWBc34PpcM6gGrrfbte4x6O8TdLb/czkJoqm4/kUlb3/rlHqaJ3SBSRwcdL5S79JDGlvuuklBcCOIoBE3xRMn90teHX/p314PyqctDsix9jLs1/19bPZcysues9e0D9JhzTdL+BI5OaYnvog5TE5q2iwyxZa0gjJX1qzq18TMnTnMYfMZQAnM5BDq1g5TlcxppAIAIRUJnTTC/zRd93vAbPpkC/gMopKuvzmt/j1dknVLHTv1VrNhB3m13Wl2yi/Ba7jbaTdqtrla7U6t+QrcabU6LQvvdKvOa97hi7bupLeKVqv7svfj2E+j/y6dqM+Xm/GgxO8HeM203+eRT4pV3Hy1uNMqMFfBqSge1ETp7Vn57ELpDafvreWfLIiE1OaOX8QYPi7hWgjBqMo8hs8fjV2VfKBcVLZGFx5bIea9m50dfM7MzgwtKQWaBVzIzPVpdvb+AubbKmfGBTETcgwTH74WDMR33o+sEGN8UYHXYyu40vI5XFEzj/8C).

Notice that tilting the camera causes the polyline to get occluded/culled somehow? @likangning93 is this a separate issue, do you think?

**Comment by likangning93** [comment]
This is an `approximateTerrainHeights` thing. We can probably add an override so volumes for things on terrain will always use an override min/max instead of sampling from `approximateTerrainHeights.json`.
