### ISSUE TITLE
Model Silhouette is not the expected color

### ISSUE THREAD

**Issue by coldsnap2** [AnalyticalGraphicsInc/cesium#7558]
Sandcastle example: [Here](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1Vh7b9s2EP8qRPaHZMCW7TzazrGzJekrQLN2TVpsSIqClmibCEUKFJXYG/LddyT1pO286hSY0SIiebz73fFe5DWW6JqSGyLRCHFyg45JSrM4+GrmfC80w2PBFaacSK+N/r3kCH6UT8SRmKMBmmCWkradTQkjoaKCn/CIhlgJ6RLMcCRuUphVMqsmRcaiQ05jrEi+dMlvW/uX/JJfA0LCFVULM5xk3AhAU6KOBRPyiBEenYqI+GFj2CqQSqIyyQvFmnsumnsCJb4kCZHHOCV+6xsIvF0p04r6A8ekjTBLZrgUptGaRTBnXeJFuWNZxhqQwUSK+FBzt+LaKMEyJW+ZwMq3UlsFwm4Xnc+IOUmtBwMT4vAqRQomU6WtKiZIZBLFlFOEk4Tp0wGVAmvgauOo0MRqMUDeWyFJqqaSEO61a2v6EC+aq8j7QGOi/74rJo5YZib+JoyJG7uEF963nJPRAxj1g16dd3kiGsB7Op0x+K+8lSQWR40IeZ9JwnBo5J7SeSms2ncYi4wr2NgL9tYsvuF4zEjk+i9l4KxEKXJ8h30cqo1YquJ5uGSzau2M/qNtth30wDP2c9eA8L0mUhlvqE46JvGYADbKlUBXXIRXIlNIjFMir7XqKfhG7o/FamDcyi95tAoJR5RHDntgqidefzxFkBRiCOFUO6Ge+3ICf7BCIWYMTcCKVOV+qIRgY6yDJxJhpjcFEHNv7P6jxUnkezmJp2W78LRjLzQWyqdpBbNd8LV43V0g4WOpdX2XZ3zCawVpNk5DScfEt/YuEoIPGfMrhnMr41//bLYKYs0kKJJBmTqKLe3KVoGN5jwVQEA/FqfZv2GcFbo8+5Q8no6zGbiPBlwm1yo9jFbUARfoal3rPJoTtW2OEVakhxHyXXaj0epiE5ye/LUR41kEGzjvei4c1cvLBs7ayYE/htZNu/fEk5MrN6LF4Y/H2B1arMJ+vLG4a9aHTSlhas3D3KbsoEJJoBsxuPxMArYZ0UW76p9M3xkYiRRKkCSxuAbbM98yKtJAIlJqGFaxhqWCL8x3TOP0muhKm/qd/vZO0Hu5u/ui/2sb7e4Gvb3ezsvei1LyfsV0RrCuHBXPU6xm0K99hmnMU7+/s1cnT6gKZ0Dcq81JwZgzNUuc3vq9FfNJb/8M9H4ut205tg2TuiAhKRgEN/U9lwAJimecBjOH4Z8Z2FhyfZ6FndoaRmVCe6LAzLU3jiK/dvIcGlZoJ/RJVZOl7QflZ221DnZQH9VojCfBak2S/mWSLgkz5NC0xln8ic4Jyxuc/vYrlwjPNdEZNBWmA+rBzyEpWtr1Nc4tyasY1HvT5eKzqmKY68haVmUvWguk9XXH5bPckD4kp6xPlWvZ54ZfCbJJ1apY3OZ5oPRm626mjSTRm8ILy/vdbXHjE4l2mRTWLnInUWSujeQdUhlKPCkvA0BlLp26US+yWCN71VOOFwTd8t9hkqTdMxwnjLzGCneNV6ZdG18gJv/6Dp/BlI2hI98Dnwp6tex2W96HC3jvJJxShL6SGQ0ZeTaQVkwupTnKsd4N871QCPRCR9CCC8Gf2Zi5lOYox9m/36anlF2hc5mFV8+MUwsyctxx5yoOH2TXsyvKObSFxzMMPq70i8nzIsaFVb/D5yqI30zSP8M8CnGqwD0gxZ/b69Ap4ZmfR1prJdl0yshRphSA9c7s043XLqI4f8tpVwqFM6Lj2q3mxaMPNNqWYL983dlqbw1TtWDkwO74ncaJgKsqFAEfdFcE1AazpN0xnAJRQZimhXK/FJfFmhHHkFemJhgGSE7H2N/dhqKf/+8Fr+pXggQ0hKo5QLvJvDY9FjIisiOhpGZpffHWEUt5Avfl+vUE7tgUyk8HMzrlAyhbUcTIssSOEgkUqIbUYmkswNhxfdUVa6o9aWg9EVx1bkw7MwD8LKq2DruFdYcRvUY0Gl1uOW96l1soZDhNYWWSMVNgL7cOhl2gb2yDnK8hfgQ1GV5okln/4IOdDIJg2IXh8q4cNpBbTEOlu9ODoRqLaFHOSZiIShhWQ9hiXxJMzRp2VQTsgbLaU1kAdhtiQ9WcHuZxF0HsdMaUa1C5zw/clyRwbd2+uvPGHJbNQU3CnWgq0I+F46B4inBTylcIb9b2ofVgtUgIgIB2cgqa6mYLRpCS9Teew3fffKeKJHahD6M6/Byt6Zhy7F8SIIA5z4jwytNfLVonTy0BPA9Ge3ewbzB6oDUazEw0QONpbTtY++r3G/I8nc+n+gnuVrsinf9sg7rYVtu2Dd2TxrxWl00YfxnKY4SuP6g7ov6s7CnvD/0nBZv7SFuGnbPwvwlAp5V/vlB0BD0lKA90mdmcgXqPtZAW/zMMlFfTe+3TtfUQ/pryqAu3raT/AQ)

Browser: Chrome

Operating System: macOS

Note that when Forestgreen is selected for the model and the silhouette, the colors look fairly different - the silhouette is much lighter. When Lime is selected for both, they look about the same. This appears to be due to the fact that Lime is a more saturated color (#228B22 vs #00FF00). This lightening effect holds true in general, not just for these colors. It is not clear from looking at the API why this would be the case.

**Comment by lilleyse** [comment]
https://github.com/AnalyticalGraphicsInc/cesium/pull/7563 should fix it.

When the color blend mode is Replace the colors should now be identical. It also looks better for the highlight and mix modes.

**Comment by coldsnap2** [comment]
Tested out the fix - looks good. Thanks.
