### ISSUE TITLE
Vertical Exaggeration of 3D Tile objects

### ISSUE THREAD

**Issue by mholthausen** [AnalyticalGraphicsInc/cesium#7562]
Is it currently possible to implement an **exaggeration for 3D objects** (loaded from 3D Tiles) that can be changed while the application is running?
_Specific case_: geological subsurface layers are loaded into CesiumJS via 3D Tiles and the user should be able to define a value of vertical exaggeration for the loaded 3D objects (and ideally the terrain surrounding the objects). If not, is this functionality intended for future releases?
This request could possibly extend #4342

**Comment by hpinkos** [comment]
Hello @mholthausen, you should be able to do this by setting a scale on the tileset transform.  See this example: [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=fVTbbtswDP0VIXuwMzhK0qXbkKbB2m7ACqwXtNme8iLbjCNElgxJzqVD/n2Ub7XTbUYCS+Th4SFFecs02XLYgSaXRMKO3IDheUp/FTbfi4rtjZKWcQnaC8jvpST4mDWL1c6QKbE6h6U89i+WcilLLmoikEAToUKgMWR2vQBjrxLkMHYBWuMC87nIMqpScadiEOioc0RMwJSMkb2AVdo2UkUblVtqNYs2fhPYb7isUiJkrqRYRXkK0tIE7DcBbnl9uI19r4J4LuiUl2WZOFxzGXOZmFf+oOZtJeICDNhu78rXh6+L0ulX1eRaTGvIrZJPYFSuI6ArrdIrg0CU9XH0adJvmlmxUw0sPjwijBugdg3SX+UyslxJv4L065Z1+p9pnnLLt2Aoi+MGe9GBviiVLlTtDNqFfMe82IJHbqP1E5MJ+CM6CshgRM+DunQaqrxo1HO2Bg1UY0huyHtyRkd9l+rYpwo16x2Kf9WNM6B0ozpS0igBVKik8lw0TTg9HDzIh9CA3rJQQPtwvGJcvD41eWgizcNWusLV78wVntl9noY45KWz6gpfEZ+be3ZfmZsg92iwuZYV8ujUuUVzTEoVMynNSukU+Svpd8xqvp9QxDw7Tv/vAZ3W3zBtccXkB38cEPyVaoJ/JGv1qxf0ZsYeBMxLdV94milt3fj5lA4tpJlgyD0M82iDRJExde3v6nvTKjnEK5Zod8ZTopOQ+ZOzgNT/Ef1cx7onwynDSZiSSbZvmUOlY9CDcjLazuNJWi6z3LaTb0FbjoUPmOCJnJKUx7GAtxkHVmVTctbJWrtCZa1K215MOxvWLZrFfEt4fLnsnXzqlj0SCWYMela5EM/8BZa9+WyI+E6YUMUleUCtgh0cZD2e/yiNlNLZELdvo6qSEV5qcp55MR01trCWHbGHDDBGuyuIslIucTeiY7dme1yP8V7ixljIGk/MLBuE+BFDy5aJHD+kxQwFpNj9zBCANq9I4b0K6aS0sLeOGIvH3fl/aAuCWvsf)

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by mholthausen** [comment]
Thank you. Just thought, this would be a feature which isn't implemented yet.
