### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jkumar80** [AnalyticalGraphicsInc/cesium#7565]
Hi,

When tried to execute helloworld page I got the following error: 
**Failed to load resource: net::ERR_FILE_NOT_FOUND (cesium.js)** it is searching in source directory, but file is not available.

Kindly help me to resolve this issue.

Regards,
K.Jayakumar

**Comment by OmarShehata** [comment]
For general questions like this, that are not bugs or feature requests etc. please post on the forum:

https://groups.google.com/forum/#!forum/cesium-dev

I'd be happy to take a look at it there!
