### ISSUE TITLE
Cesium3DTileStyle.style is not reactive

### ISSUE THREAD

**Issue by bkuster** [AnalyticalGraphicsInc/cesium#7567]
### The Issue
If a `Cesium3DTileStyle` is created, its options are used to populate the **readonly** `style`  property, which is described by the docs as follows:
> Gets the object defining the style using the 3D Tiles Styling language.

This is **not** the case, since `style.style` is _only evaluated at style creation_. Thus the following fails, making cloning & persisting of styles tedious:
```javascript
var style = new Cesium3DTileStyle({ show: true });
style.color = "rgb(125, 125, 125)";
var clone = new Cesium3DTileStyle(style.style);
expect(clone.color).to.equal(style.color);
// fails: expected undefined to equal "rgba(125, 125, 125)"
```

### Proposed Solution
When setting an expression on the style, the `getExpression` function not only receives `this.style` and `value` but also `key`. The key is then set on `this.style` to reflect the current value. You can see an implementation of this solution [here](
https://github.com/virtualcitySYSTEMS/cesium/blob/1812550214b41f76eb6812c82e36efc0868a40ca/Source/Scene/Cesium3DTileStyle.js#L162), I would gladly open a PR for this.

**Comment by hpinkos** [comment]
@bkuster I can't see any reason for not updating `_style` as the properties change.  Please open that PR and we'd be happy to review it =)  Thanks!
