### ISSUE TITLE
czml path Color 

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7569]
czml path Color 
在czml中，卫星轨道线段，要实现下面的效果，有什么好的方法
![default](https://user-images.githubusercontent.com/33933148/52683804-fe479680-2f7e-11e9-981f-cd4753b62aec.png)

**Comment by hpinkos** [comment]
duplicate #4393

**Comment by GatorScott** [comment]
To use the API that is available today you will have to create entities that represent

1.  the entire orbit, ib which you should place any potentially common graphics elements like LabelGraphics or PointGraphics.
2. the segments of the orbit that you want to highlight with the necessary PathGraphics properties.

Note that you can share the orbit data with each entity via referencing.

I've attached an example CZML file with truncated ephemeris data to give you an idea what it could look like.

Scott

[AccessIntervals_TruncatedOrbit.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/2873001/AccessIntervals_TruncatedOrbit.txt)
