### ISSUE TITLE
PostProcessStagelibrary test failure

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7578]
```
Scene/PostProcessStageLibrary night vision
Expected 0 to be greater than 0.
    at http://localhost:8080/Specs/Scene/PostProcessStageLibrarySpec.js:221:41
```

This test passes individually, but fails when all the `PostProcessStageLibrary` specs run.  Something is not being reset correctly.

http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FPostProcessStageLibrary

**Comment by hpinkos** [comment]
@bagnell @lilleyse can someone look into this soon?

**Comment by OmarShehata** [comment]
@bagnell looks like this is happening because `scene.postProcessStages.removeAll();` won't remove things from `_activeStages` until another update is called. So adding `scene.renderForSpecs();` at the end of the `afterEach` fixes this.

I'm not sure why it's only an issue in Firefox though.
