### ISSUE TITLE
Distance display conditions

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#758]
I would like to be able to make primitives turn on and off based on distance from the camera.  I imagine that in 3D and Columbus view this would be straight line distance.  But in 2D it  would translate to just difference in height.

For batch primitives, such as BillboardCollection, I would like each item to turn on and off individual instead of distance to the entire batch.

**Comment by pjcozzi** [comment]
The `display-condition` branch is now part of the [gfx](https://github.com/AnalyticalGraphicsInc/cesium/compare/gfx) branch, which has a few other odds and ends I am working on.  The display condition is really just d6041573a4966facba23b1eea389358ed3b018e9.

**Comment by mramato** [comment]
Should we just close this since it will be superseded by the 3D Tiles work?

**Comment by pjcozzi** [comment]
3D Tiles works for the massive dataset use case.  This is for the individual primitive/entity.  Won't we need it for KML?

**Comment by mramato** [comment]
Good point, we can leave it open.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:38384 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZmS5m-003IdM-Kq
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:52:07 -0500
Date: Wed, 14 Oct 2015 12:52:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1444852326;
	bh=AFxoeHVjPHKLuF/D0JEbIMGXWP6C2+oftTV+6wRId30=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=L08tBCl6CxwmYDuO+UJRlCWP7Ku7K0P3Gers1aHVno8fp792WiHOw/Z2dRPPVNPtI
	 hbGyptknsBRfHtyxxm+2CjJL8EGkV5fboMGy58DJvMC9I04dvaeFgLQMFwyzL0B3sL
	 +jC4/CQ3rpvfGuvYpepXMax6ngr57YDklEVS5O9s=

**Comment by pjcozzi** [comment]
See #3835 for the start of a `DistanceDisplayCondition` in 3D models.

**Comment by pjcozzi** [comment]
OK to close this?
