### ISSUE TITLE
CTL + Mouse Scroll

### ISSUE THREAD

**Issue by muazzamazaz** [AnalyticalGraphicsInc/cesium#7587]
Kekboard control plus mouse scroll not working at all. What could be issue?

**Comment by hpinkos** [comment]
Hello @muazzamazaz, control + mouse scroll isn't a defined behavior for navigating in CesiumJS.  What behavior were you expecting to see?

**Comment by muazzamazaz** [comment]
How to achieve it





Sent from OPPO Mail
On Hannah <notifications@github.com>, Feb 21, 2019 7:42 PM wrote:

Hello @muazzamazaz<https://github.com/muazzamazaz>, control + mouse scroll isn't a defined behavior for navigating in CesiumJS. What behavior were you expecting to see?

**Comment by hpinkos** [comment]
Take a look at `viewer.scene.screenSpaceCameraController`  https://cesiumjs.org/Cesium/Build/Documentation/ScreenSpaceCameraController.html

If you have any follow up questions, please ask on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
