### ISSUE TITLE
Does Cesium support multi textures in glTF?

### ISSUE THREAD

**Issue by rlaehgns5399** [AnalyticalGraphicsInc/cesium#7598]
I am not familiar with English, so I ask for an understanding.
 
As they said in a [link](https://github.com/KhronosGroup/glTF/issues/1360),

> As for `TEXCOORD_10`, I guess we have to allow it, else we end up permanently limiting the number of texcoord maps. It's easy enough for a "simple" reader that only supports single-digits here to mark the multi-digit ones as invalid, particularly if leading zeros are forbidden.

Does Cesium support multi textures in glTF 2.0? Can I use `TEXCOORD_11`?

Reason why I am asking this question is because 'glTF Validator' does not support 'TEXCOORD_10', and it says error. but the link insists it should be allowed.

**Comment by emackey** [comment]
Hi, unfortunately at this time Cesium only supports `TEXCOORD_0`.  At some point it would be great if Cesium supported a second, `TEXCOORD_1` UV map in glTF (contributions welcome!).  But supporting more than 9 in a single material seems quite unlikely, even if the spec allows it.

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features. Thanks!
