### ISSUE TITLE
Cesium二维地图绘制经度[0,360]的矩形

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7601]
var viewer = new Cesium.Viewer('cesiumContainer');
    var entity = viewer.entities.add({
        rectangle: {
            coordinates: Cesium.Rectangle.fromDegrees(0, -90,360, 90),
            material: Cesium.Color.RED.withAlpha(0.5)
        }
    });
上述代码可以在三维地球中绘制出来，但是在二维地图中只绘制出[0 ,180]之间的，请问有什么解决方法吗

**Comment by OmarShehata** [comment]
I actually couldn't get this to render in 3D, but in any case, I think you need to split it into two pieces:

```
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.entities.add({
    rectangle: {
        coordinates: Cesium.Rectangle.fromDegrees(-179.99, -90,0, 90),
        material: Cesium.Color.RED.withAlpha(0.5)
    }
});

viewer.entities.add({
    rectangle: {
        coordinates: Cesium.Rectangle.fromDegrees(0, -90, 179.99, 90),
        material: Cesium.Color.RED.withAlpha(0.5)
    }
});
```

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tZFBT4NAEIX/yoZLIaEDPRhDpY2m9WZiUhNPXLYwpRuHXTK70FTT/y4U0apXndu8fe/tt9lWsmgVHpDFQmg8iBVa1VTwfNb8SX5eV0Y7qTTyJLjJ9OAH1E45hRZkUfhvmRbdMOZO6pJwLj6UfnJjuFBaOrTz8YLN6IQdm2qNJSNafzq7TiBJQjFN4jAORRIH4VdP1TWwkvRZsjJkGDb3azgot7+jei/9GK6CIXLK9Knn/VfieGAVI/ifEHuhl1p3JFwO+q2qasNONEw+QOSwqqlni7ZN/oIOcmv7WBqNobRQrVDFIvN+fGDmiZyktd3JriF6Uq+Yecs06vzfYmRk9/7ysUUmeewt+9nyYRABII269XfKGUNbyReN7w).

**Comment by GatorScott** [comment]
This works too and matches what the documentation for Rectangle says about the value limits.  Only drawback is a rendering artifact at the anti-meridian.

`var viewer = new Cesium.Viewer('cesiumContainer');
var entity = viewer.entities.add({
    rectangle: {
        coordinates: Cesium.Rectangle.fromDegrees(-180, -90, 180, 90),
        material: Cesium.Color.RED.withAlpha(0.5)
    }
});
`

![image](https://user-images.githubusercontent.com/4126790/53572293-efddab00-3b38-11e9-8d74-e29d56d1a103.png)
