### ISSUE TITLE
ArcGIS Map Server Sandcastle example not working

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7606]
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=ArcGIS%20MapServer.html&label=All

I'm seeing all kinds of failed requests when I zoom in, and the feature picking is no longer working

@kring It looks like the imagery is coming from  https://nationalmap.gov.au/proxy/http://services.ga.gov.au/site_3/rest/services/Electricity_Infrastructure/MapServer

Is that still valid?  Should we delete this example or do you have another sample MapServer we can point to?

**Comment by kring** [comment]
I believe the URL changed to http://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer, but that isn't working either at the moment. It may just be a temporary problem, I'll get back to you. There are plenty of other ArcGIS servers we can use if necessary.

**Comment by kring** [comment]
The server is working again, sorry about that.
