### ISSUE TITLE
GroundPolylinePrimitive Not Always Culled (renders through globe)

### ISSUE THREAD

**Issue by timoto** [AnalyticalGraphicsInc/cesium#7618]
Using Cesium 1.51

GroundPolylinePrimitive is not always culled as expected and renders through globe.

This example has a single GroundPolylinePrimitive that is clamped to terrain elevation tiles and wraps around the globe: https://dev.globaltimoto.com/

![path-not-culled](https://user-images.githubusercontent.com/1268358/53689721-57406880-3d8e-11e9-90ef-475bab1eced4.gif)

**Comment by hpinkos** [comment]
Thanks for opening this bug report @timoto!  Could you put together a small [Sandcastle Code Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) to reproduce the error?  That would be helpful for us.

This might be related to #4746

**Comment by timoto** [comment]
Hello @hpinkos 

Here is a [sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=7Z1bb1xHkue/CuEX24BYykvkze02tm0PZgaYRQ/Gg13srvahLJVlblOkUKTk0Q76u0/8IyJPkXXOIQ/Joi62+CAofxV5PXmJvMbb9fbo7cnmt8326M9HZ5vfjn7YXJy8ebX6H8K++vK5OH84P7tcn5xttl8+OfrPZ2dH/Hfyav1ys333r9vztycvNttvrnp+vt2sLzd/fb05++lyu9lc/vf163++Lv6VhYK/N9vTb46+/PXy8vXFN0+fXlyuX23Oji9PTjcXq/Xq4uJ09cv64vL03epsc/n0Nw53+/z89Hz79MsnuyB+Yel/+I/LzdnFyfkZB/b/Xr+8+jOn58XJJXNOyJGEfPTzu6Nv10e/bje//PnZF4h7iHr1/PzVsy+++0kcRz9yjl6efft0/d2TozdnnPKxN8ntydsN+3t1fnaxOt++fHp68pwTs7l4+vO7p3HlOLwffjj6/n8d8f8R1urox/XlejIR51xqF1Jqr9avERb7vVaSD0nL8cX6WnJ++ouk5kstqr9/bWV2efJqc8qf+5ujX9anFxuj6zP+5pdSwFfxz+uLzb+s3222/3ry/G+oCFd/vOCoN/HHv56dvvvm6HL7pvOXm/Pn5y9G0pvTzXPE8M9nL06ery/P934/Ofvl/Pvz/9jz9Ld3U+wvl6/OL17/utnu5eLX81eb799cXu5n45c3p6cXXHybs6lfz9ZvT15K5v9pc/p6SoLr5ZabyK49XGsL//N8e/ri31Xkq6+fnf396z89O3t2pi1vJaW0+nn9/G8vt+f8ZX9ABb/eHgV9dRRSenLlH3+EcK6Fonn46fX6+eYHrsHbNdru9vz0lCVenfAnfPPqf5+fv/rxhGv72fMNx+Kdc/uhvDw9/5nD+vX8t3+UFO1Kkz1ItjX93Huc4ttfML4WgHUPUjEuBtnX68tfv0d46+3JBn7+z7FbeZ+eJL9KqebwZN/tV9H5AHcj5yLc3gRaKK1MguxSUxCjZ0AUY1QQHDFIzWf14qvzT8IqJu+qhcGiIxBXLZWq6Wix5CfE6UJsKaxc8SUeBCTOewhJQCucMFrVWmIGiLmoM0RzcvoW/T4CVK56yKGaM5L+nr2C3IImKdaepGygdFANtH1wu8Rn8NggNMoKUrLa5aOC3JpIxCYf2zufaO7L3Ql4bsCViAOLq9gqN8QxmU68N/eeaybAWDqZj3Qsc51wY3aOIojLLnPvErivKNztcNzNhcqEhVMskhpqFAykYMAlJb4WIzl2UkeElIRSLZwcrwfcqoIaWuiecg8mzAYzSt8tgLzTXiOFpqkbk+k8pR51+0w+YlIfQFqkgfi5Kjcm5HsV82EUjoqEZk3CYxTmSpcx+kqlq0GCIfZeleSmJBaphcllTQwPX9L4ki9Zwy3Vq4jPPs+QFhtpuFSkyZKrQWVYJaAZEksIFnlSXz5GJcFryETZJ8uD02ZC3ZenaGkuoaeHx1JPK9Zt2Htyq1oS8jVFiFWOBBK0N2DC6owH4caqwJMTT65SyzNk5OkQgAeSptFUSy1ULZXgsv8M/ujAhyyV1zXuGuZJ6cR85agytdVmhDq4g8gHAvspcwRFARmE8O+ZTOU9d5E0DR6lY3qUyuyqs97OtxmRkHJWknyeqe8Bqi5CyRbKAuA1IifzNEmLM9IcmUxVT60lGxWat5jzZI54iszTTJ7ExlXKiae1IJwDL6Q4JBfz6twE1DDtpsZjv/hITkNNSJsSDh4kep55MImse9MM4YGumS+enkhMMvmVqHyelfFdhtoMCVwvhSREKjLOMkGFZz7TJTEiQSYHTEpGyWpcocfVQz4EyaZ/E8+/a4UiNSYF8xievjHh0Rc6R0XFZGWL/AoFFp+EuKpcO/yTWFbQxxIIayVVQHOshEAkuKakRFb+J8nI0x6glWO1KQjh1IlIa1lBgR61ROQ6yFN+pkLJLVtyCdrhJCkhuWAJ9rkTLRnuq6xkqAyZyp0kI6EDMuAGT5acxlVJEpjUTynF8pCqkcw1SQhP7ZSkns+BQIOWomhVo5LPLIQrpBaOfQOyXNaWyUjupAjwUKQBZF0HhCJZtn2Ly0hY5cKT3Sexsq7OKVVSuIcHKZgfBGjHWIMCqb6XVrLEcK0UCe5SRAB9VcAUoGqoXFIKsjdSva+o9q2hL+HGF7H+NAYFHWuUSm/9HJNIWYj3zpNM5zk48VW5vYc7EM6sEqi3t8oI4GmNtsGKjnGflLmAQ1aREusM8K5HXWdDGZGGhgTC9X4acES1x5RnSMOIpDkgmiJTvRpxyhOIJwyc2uvzEKG9Pg0jAxkJvst0Qn6+1w+9j6/aN1OyvjmqzAShSuKLa5v6Qpq1j68+V4srDKPZ0MenLmMjlYukMn4ugVPBjAeq/WEgOFdtWNJBcTzkHI74FIyYm9Qp6+0Ccu6kJ6Z0GR01mdRqgbguM4B8T7BoTB8Th1UzJpyxmA9KuOH5TizfPiYriVp6Faj7VeAw5JF0jEclU7lY8E0xals45UlblYpegmjFqgu3wbYKPMRwuacVJfQNe4DdvkjHkNCHxSVuHjtI3LkgPO6EnLpr9hKBD80iSJy4URLKKsXK1ZaBq5FHRB6gknT3idXsnKdBKFCyExa2eaDKPOBixOSMcnJqZpATawYCHHRgBqGymi8gsq7HwGNcAGA1vwBEH7JKBAmUg2gqwfNrkXAFnQAAZikA0pEB8EgPwAO/SLAuQ2kMWDVMWfsAHkd4qvXeQM5DZQnJQHdncWOFXNqoL01BVMB/9bFAkU1HmVpkTUfyTSVi4Z4BIFjnEUsLsoNYNaVY9k+TwPVhgLWuD+SOvfUucE+V/aOAFq8BHb9Q0GnsHCXy+s/4cL5/uMnQbwc8u60KeA6wCGRWHYp+6iKfegRScjr68MwrNQGmMjGQKsgzr2bJcJNVcA+w2l0Jo3RY+QgtgHV3nguhe5Hd3UozaOSNAfcjClh/mpa4HYzCuB20IYy8DFDwClLDbIqLV/p5BvxJgnm5HkQKKhD9XBR3dN+1aGKRTg+7sJgdjdw+ZZ0A4BhDWgyogzgpUSpGHo/NiaQSwcn8AFsItAyMwiiYSDNorPen3x3Yyy0+ZLAPyWrLUkAdaIXFWoZU2Cwf+yBgP5Z71KDAf5L7BA3sIG5fOwhT4J61+lZgzpAnf89ZJSJrPFqFRRfFV45psuUUbp/ihWfa7SMGHqthmJ5CLS9ydmoK6KJAZK3WS3lUrwXkgmafQeqAFOgCBQMqc172gK0rkKtNwoiJpHYQyZKWAN9BfnIM/a7lgkUkVndZY58k2WHNGoTT2Jb6Ipd5pAXxUM8XkqnYXcsaO08Nlsb+XglPEDSFpfG3myb3CjnLuRkhST4XKyVBFi15pkxaYE1XWXmOWPMM8GSJ8RpKaai4EfOizBUEpKI+CMGBGiVYHtW5UzECJUuI77549FcSkxJUdCE4eTQdV+NJXydVs4mtG81VWJirCT+16cIwF5+mL9Wiy8s87SwWbm5WoDuRYiKVOgmdxE6s/mPmp0TXgRGwX05u++J5xXNcLELTyoWIFjFNsPgoxPnWSbxOyCWTwTLTIpK4e8LXS6zT1zwVU1qF3FAJeK6dGw8nRuphCPKQ8Gl4iJiWSZlMxrUOmgHuWIXIvFBIpklPMSdUHWQTzWuGyNo/k+yzV4LTJULQaZmvqKTyPEQIpppCUvdVUXdAqIvkpiCiMoGE7ikUDbhAn1Di6mfy0ZMFFYrrJVGvzMtJxglKIZi/zpA2AG0CWXapJJgS708mKua9SMjRugw5ej4JnDYKjtvPgOjMT9Fm40qLIuK4HxMZx1NMaY9OZtjHxD1cRDC0ag0nCo5x/qvx+AbC3UxTgs1vIUgMg4iVewFYoOZuGjuhkiVPpEMC9j/lSwUovB8WBANJhqZWUpGCYr3fpxkZ/sJZiZMBuOFIrICEDT2Q0JqUJRepeRrLRNLqGihRl0kqE5vqaq2ohMOu6xJ3814765hVQ72dEGsSLcn4hy0UGclqCKgvWM/BmvBxYdUpY/sUOkDkD36MPebKVSCyeh5l9FWZ0mWSEC60qgTrjEqSAqlS056CV1KrkZHMOPIao5LAcdEhSZNFr4iTI15FeC5YRMRhKiuEWuxEyks2iAGiC0WB41mFkChZ4Ak7N04ByasfwlILiE+aTRwSl1CTCPA4jrrouRkjSUKIDGi5iC4CEKHOTZbURNldj2Y/1iaKDsvLmQQlGi0IF0ldOe9J8ptSY/0PMqwEJRCSc91CgpYjl6wWG8s0yU+g1hrC4YbJU77osECKJlCx4AclD0dOcS4epOCgEEjG5i5IjZwMIfwhpkkohJ7f4UQAPgCTiu1VIdjlXUqWhDOWuR/hnqYpyVC4DxjyPYlMzECIJD2Y+CQjqBtKSEls8gV5zoCjJ22FGUZVEnBwAwQHgY4b+qIkMlw10OqYBAwWTLKXDqfxACUHN5hknOA69m7lImYv8FYx6hxj699BVQxcudC5TYEWeHIhgLB0eYyjZ1g+fxIyx4p1/WOfuDOGFo/TOlxHEVvhBGAvKzgcTnDziLBfwajheJkRZEXJDnlFKIDrQtgP6ygpwv0oQ9wIFGG8VZTMY9klAaeIgGTSI4dOcABEEM82Le01SRoq6wLVpGq2tEs/ZlJpT2oKZU0ET/Z66FSzEhoKK1YTCtlC5w5EI0QvawjXzYC0+xeEnVZBQ0EELGkb2hV867mm2fwcEg3lnF0ID0Qx2/fHiRBGmTvV6qQkPOuWyRByq0iK8LoUOgnUXcIqmG9cqnQFsIzD4VBFPE+sIoPBzEhoRqwNcCWTcCp3AIZkmQCH+bjvTYsRJ5ObvJwC5IYae/AVETIi7IPsS/VENOw7AjlsMmvwgXsCQeTiwRH2RPXAIiV0YZouHP5GurAgc+wjd4Y4hsZlGljPJUWuFUWYV4O4UrXgKRKmzx6XNrFUC5S0rwGi2hTJEomiqCRK9QbBFpuiLhO08yEsrhvyLhsiCzw7S0KqA8oWVKaQ7oK4sDRZPGWvgipPzaUzSFqThWi/YmSmhmDSr0g+9LUyZrVxGu2FRQ9BGUcf9du7koKfRrfXb/pY0EQje2SE1lmrth6u6nfoIWRWBcJtrPZ2XqwhVp+7UKxdajGZCOieKMswYzkutQ1S3qTCByfaRpp1Tcn/PlDULKaEVT8gcnqalnVK92AUcOoWqNYZtKx6EA4zOPGYksvlY0FoFOi8pFH4jxrhayecTEaphvIZXUXvu2fBVWq5pkHNf+ToUD38AYtvX5n9hFrhZ/Q4aFKhwDUZGdzioF/GaNpR7JVpAo2rLs/g7GIVXmRR5EppmogWk6EUDeEWtNbVoMpXy8NM7zO5kXxUSt9CUqO3KVZMh45rNCXfR1zVcTVDLjzxf/w0KpiVRrmKmquthIyJL3jkhAEFW9jBMTdS5MuAcjWpNCBKhkLqSG9xMxqELDqSPQpFIVjobfDnTMrXIVXke4RpDuHIUuu5KR0F31FaXAqHIRnnm6K8AVFDqu3gKDmnj8BQ6zVhCdKU9oT6SSKXFZp85FK8rX9No5oNpY6CfgZGFDpyyVDZBR86GqT0ejI8xsFjj5GGlOrN56vlHsroS9wDhOuENLO54W2LRybJ+WjI5/eCqOm1+9z0k0wjLhU/rilDQe3KLo7RIBXHYS3zeCMafb54Q+DxjvGNpcLQtPPd0K29BJpCb0J+RKYBuRKD9gaR2vtBu/6n+QEpoZ6q5orJeBpkfBfy82gX3zL0vjJ9I7p36j8K9AEzJE9GSDUp1k4qbrmghjvKqi3E/goMFpTKR42oJG34JVLedTXJpGq9CxqXBFA0ZHt+jEong5C+vQKUR/5sNxQX+rUTztF2Aanhap+sbtlg1Ly5UywzJNak4z4OkOnAwFqJBo1z8Ro0tlcZBOdIg8a2veTXkS6gDQgXtYKlKNfS5A2zgp1tRT4nef+rBHdlbJoozv5pWrwLCtQ0LKc7e4pqR2lA7b5oCH6IsXYp1wY0xDj4G6cqj1Eax1cXodhRuyHCPVKC6dSt9S9RdGQv3vUvQfhRdYlexhMoYsNaaiPlG1JQS0dDudQ0Qnv+sKcvYbu826x/JEKUh7zVNGizsauubW683IH42MTjUL12uhSGrrlZ19zKPFoUnT6IxygPeUthP7djMgqo1GpoNz5Zuik+jFS/ICO4O6DI3w1NldKgDPmb0Mif74FHugGF7jF/KsQ76oqfbanNoD2yqxR983gS3dC6hmLslSLR+2+BfygyfPpw6KA/gW9IQz9nUzwqNmyXrgQvQQsH5CVEjrsAEZ56nkMkL7fBo4++D9GqJOSce5p41LN1gti1GSqm84RC7d7pzLi8oo/M1oKHPPZRHpC+hwyUBqnUUTYkC4kaVuxIH59lVMKAoiFbwULwzRDFIfgBDVKVRmG5IakD8j1dZSBdqOSREO3yQ6MI2xDUgFLPT6JRrmmXhk7KkPbaUU+DPACkQcVRdnZSdSjAXYRhL4eljgrG53Ehp3GJdmRNAsUweMwL+/mr1SN9ANWrlK7C2EGIpWgq8GGiHD4IKtjy0mkc17B+xPVx0fQcII8mULtpDw3Ij1Ech9XGkwe/j5Ib5kv5hv4r3BBUuCFZuzTQePYX7jiNuw2pytoVpjyLxkuRuKId+rJfklMwOEkuFbXZzs4sCldRWAWY7sAZcFknXUbkXoGtG8vDRlOo4gKV7jDwAFb1DkSt+uRfDng+ZI6EZCTGj4Bk2XkOuD5tt29uJnZrpKHnxtstWMs2UkdkT2ZJevB4nUSFlwYXeaoyF5an0Krc1jBS70GqBdP0LgPeAkgmgmWo2ncsQHD3GCThcoASvUnBJHQS/GKCJT2LPZIRqp3UWZkxiX4/Fz0u3Fm2fGUjxXzl2sPJVqjyuj1ea/Q970tIixaObP3tkTpHchvSk3ouyEq+zpIrH3AIJ/bvFXree756eq6QOh/OoUjPaJsDqdew5OdJDzemA5MD5bO4gdAceYRSvqFp9yLMvfJYocpR0Wky1YvcTIoYY9LeSAw5KWnFiLeukHztxLo5CtFIv7i3k4m1h9P2Se2+KPTYe1yxx167L+u+Y9OAc6a75HO/Qebcmx/dgZTeOeK16zt84iH2+DBy1y+6lIwHhnuSJR36J0gWleGnmK9hSM5zvUZy1vU1WZle0r72W+mE2/oUImctP1tfQNRbvqRNSL/FvYBEeyqaI4ppAZn8dtcVQL0U/cFJCkZM9R6TW8u8l1bGLelppXavbO5HcIBT38TOqWnXcBvA9DXoGn1zyW5h3xqR+srdV1JCzfZDUypz5HpcIqMLOld9jUmzuMgemSA7r9HwUsgk8KnoooS8eicvO+GFNGzzpv4UVvO6Y+1za/2FI92axRywP8SlZ7SMeEmNVAAeM2U78ECEZ4c83wxP2gqvc4dJgFccYFcuZfMCkPfBNQlPUBZwYFUeypoJ4wAgdtAWe4F5KQHp/iCau8y4x5Gamw7kht0WAfX+4LZMjDJF+4l4aC4fpUrcFeBMBmozdxuYYU6B4rwCPHMxCbJYLWMgJspWwcvz017f4t93elaYo7jxSsBt0g9x3hjT1bpdnAI8xKaghPYHBLnBVhF3wHi7/n4gliD2QgkLC1o5sN0v9an0bkq9FBevN64CCyomkfckrnsZx1JwE1mAawaaRFvxetlSkJsFuhwki7VO9vye8HKR3ENin47HPxzUKnhHIxUVwKV08cFZ2xd4DDdWpuHmGfbIPUrxJEguaJJlKWQSwIgH3i4opCNi8lou2T7gEnB7LCNwj1jukY7bveBBfs2+dZB4xEDaQGoLC3nJZ8gaawjmrt6SkQyIwVxIxDmJewCyaGuZk9hP1557QfnB4qaUX/6wYPiOaRKMuq5YYeEbPQL5Nte5vR/g0n4XejMYJX0KwMKqgDwjUZtKwDzxY2XOwxYFAFkVbMFLVgj2lZaCa0HgWSHt2fNO7f8Yvspn8F4AnqwFwCv1nzyQRprkJaH7ArxcowXk7w0OkY4bgZdmXKHSl4I9ZWj4rqiKj6OpH9x9W/r2f/dYlYNbLAXCrpSY6eEREpbPxuIPde9F97G5g8OsAsWFd6zvF14yd1vibl6LB2fx7upckJdgeSmT3wImxOCW811j923fbsG3vlNZPKrbrWqEZXKxSVVuLb498ZEz5RhhJItncrXdw31z6Lc5q1rbIlxhhZvUtBZuqcOJRcwsVntuy8iCGn2nFr4o+Ls1kAN3QHetpPKyagaPadp9S3xRzJxxow1hifsAHdrHVr7z6Y0wPC2dDsVQYQAryuMuGbYl8QbyrW6eHCa4YUqJ8Dt2yfF7FFMMuAoWTD4siS8FHA5HePKi7sgdsytNwhfTwqvYqhi6S4QzZuomcwdxO+m0CUZvWY/IHo9G51UUs1EL3BwvnLDULT/jsAp+xmO6+NlJdBCPU+5xcDK+Sxcx4YzicrnECeetSd3zDYMNEnapE25Yg06SNV26ueKWKV4WozySVeen5EuTjiZ6XWrfd4/iv2vyrzs5WHxGnr21SWeVr0zYSBJ3ifa7N7c6s4q7Zj/D6rr8nEy8qjvXa/I9tlSvO4M6Y1Y3WWTRfo8WerLQYlmSlWvOq8VQYIoHUVZuPPVuzgqzGLCyJCaqGrtDipir5oyHR2915kzqhlEeCQwGmfCo/PVfy5R0CGiF4s5tyn1X+agln3GfoMkDl1m/a1U3Og1UMZ/EIKgavZRHQ+kQbofOjVbOY6UQbhwagHnu/nNSJ/omWAdtMGCEp3hHrqo2uPGQf2oHcDfuj2G7qkUpGZhGhbMS1UVutGGElqoEhmKH04vdU4wZsPvUYJH0Hm4kNkl4sK9z+MxfyY2WBQP8DINeapBXnqDGKhaOBrhV4dqtC6VM6gRpsOgKHY/Ewio7MXw5DHc5TPz6R3ZyATsXdTMGLUEPzTi0bJ7Hs4LlJwA+lpdAUkbRLvByexgToIkewSCiPwPAdWQAsZCLJ4I9nrPHe+lFr8IuACHJlgo3Hr2awtqHh44fUip2Ib3ZGni2K6cl1GJ7by6LTFaLYE56TyGpNbmlhBlGkms32enTLDLnmCFjX5/JLYRng3JMRIfsD54e1o2NxKz3u/YJ1+wacEIB9j7xir8Qn4xkrfyFsAkHgIt6IoLDOAByI+yeQN7/l4idJQXWbITIGaRDxbMPHik7nw6I2Gm/Vsww52LE/55IwFkZqWKhy7jYSdqXiVb/xZietojuK3UZX/Z80a4d/T5Iz3ovnmqVBWOUgNzLovSyKFamZKPl1VL2+4099pg6aL3Ys30+2IpREjsJ9FGSK11JOFgDzVS0H2RthITwIO/kK7QMCytMUsajwse4der1RRtKsPZ0TDAim+QUZYJBaiFZ717HINuuJHNqMuKSkdSJj0qSvjwUebYkNsFiwPqkEo0qBnvNx1c81scERlJoj3h9dsW30CR2PMgovoLHhOYY1/di9vcnPotdJSYx+hnCuroTG1g4v5beN4nytcTeYdBiLjjpBlLltUIcdZXjTUmeropLCU9Nk5h5q3hQVt9dLEGB3SunJlYrQLIeycXJvGokGaBwHeCksIYSNNxqdiIrltqWJo9yyNEsj3kF0ZtI1SuvnIGmiUnZQJO08CwvKSiS3MzqsD1Z4NRmKy6MBs02zk8RSNaqjZVAsb6aVwVvmAoRQ1OZ1X2nT8LtAZi4KHqamuf/XlWoiveV5OohjjFDSRdLqMeYljd9hqZVMccCY9145mqflGkSSe3ncHsvYtZlEpWkChtMjkjFcV5vx+NBIHuXaAL50IqaNeDZAT0MlVL70yiVoFgmueRj76bJDW68fxyqXgduOvXNYpnVd4TvNidld6whRXNI7zh5uQzhzWOgQQr3nhhlZxZ8mg7UjJq3lNaS0RYz6pe9a1ZhqtfC6i9JIErfE1t6BLh5YXHWndgoGS2NpDAiCkp7aQ0h0ggNQq17i/WmwLs/Gnu8kqoBhcEjjYKvZYziXEFPorb72r20Wt4vwF2doBu87bLTfdF+TeoWsK75i9fDji7vV62r0ZUuFfaiC62N/cWr/vAuV8YHDHIZuQlx8iotkyT9PVDDvUtBpRJN+WtyswQfkBE6RTXO40T5NIZFNJ6zJWnn/L+SUURAJIcugWBZWklTgA2ZwD1uQIOWEEn9ZLFyLn5gxPoTQ1M5voXAxLsYYGKS5ODv/ZGGTkPwsmIoKQ27lOZDI56aO0tHg6Fdr3LyNirkPK6STaMUo6ganBlWW8XiPcvJ/RpULnlYXkmuHWHVk7XOzNoKFFGsKYmBKGVoCcI8Xu3g/+GhRlRprGgnvH4jjGCAy2CsHC0saetsguwwLKNSCnRJRiXhhsMHQHUlxXwcsC/COsMUwOGkKAQKV7oTC1AZLLQQLcaPiMESOGzZcydFOOMdcZoRat+xmGmE8UvLWbGcUROUYRKBPXq8E+GThsXzu2SBQffT8MXQmDC5IXkQiBGrJzpbRnC5ukeOeyqAVV7zFMgjoElOwkbyDCEgT6JinIXZu55L1gpxg0ChPKWjENvPCr2lE5JRIezLdljr9FfomdxHYiXuavHiSBgepceX4a6jhM/w8JAn4jh1Beij3J78aKG8cK8QCykPhLHJKOer9PkY+XAOYgpSgB1nuZQJU4nRY59+GhaYE5dn0mFYVsxbKZOnRARSG6AsNphk6AxLfcZS/QwfCF0QbbrCmK7vBT8BuU/1plpxpxlqnYUuwnoNe288q/aYej0cUtBnfxBRSjiIPwux/DQkyfdkii1DZRj7VFBulQiU23wC5VF+hb6Y7yadsQq6LlgiaqzE3dJ8afCsI6tnnv3jnSPKsESMUyaANQYMcQpTLR3iAewOBxYU6RVpZXhf7wboUzQYHTfpubhrS2TzEE8VbwMKDGKEFJCnRakqhFlwYdpLKBPTxQqbphyCZQezQZ2wCvQp1B5P6GHi9FyXxGOKCvPOe09RxFdWlgbfPPky32J7V/OTYJdeIE9FLfLkfM95yMkkrbYB6jAA1guz1lxMLsdgZUlZt9DkPbHi9fuQp9r1aZc07mlJ1lpMP/cwM/uxoInaAAU+k+UA73Dz9wZsahw+iIIm2Uq441usABI5TNYBc+pzEZ4SFBVMzqoNhy3tai4abn/mGa9785cVKAbChZFUEDBWbaNBDlx9R3mtR2AsqEDEU5jitFFHTkbBi/DTUJYVcbQOvSHXcuybSR4zjtdLdqBFWmNtveup3GAs7Qslb4C9uaIR3tJVjOHiiLBa33sQ+RhL2Q2jiPTjCulR4bIx7P3BUIoOtY3TG+/ou7LyLw+otpULhNrzCcH3+tkfBn2NHWJbSqHmSGCMAyzDN8L4ZTDH3YeLj1KVEsxdOHlNF8t4Htft7wZzIdkVEoPlmNRMw+kkaednpcSdH/Z27yA52XfeILkcTob5gIhYU2nVGLar7xx3qQOMXTK7nXftO98nVLPcArEMcQgYUjKYcHb9k2B3KJw71KrP8EPBh3Uci6r6/IDRx3QnFg770GAs1d3I8Jl9ZlMsRlnzFYgT5PWusMl6uMIkQRbW9Fuvq5G0An9IeJAW/Yl0RykO434exv1J+LElPtUqk28ZLXmGEh4Mp3rIR8pQzD5ZGSeHIz7vFXqKXd1LmXw4RO3m8hqKs7lB4fKuD03yWP8sdC0Nvn2tB9KyP2GYUusFknCqETDIKpFAKj484sQylgFiZfMOk8C8cklWpZHK4lKdZX9oRfBhLfjwfd9deslYqA/sPFecXWPMeFuvNdsUi05Wtqd8T7OJqjkZTcFC/VALA6U0Dz/kmho3ApKO0VqBrcpPwvdZOWnojMMudroiOWgA+/DDLoAtTvwfZKP/mPAyUE5ZTz2V5mGA6hhrQ7n6opsCxOUox9/naI7VTkhhLSLNsOmY5Ii4J6OwNFJvobFDXLWVqCjo+TREFsTyLYmZ22hHEXGq7D6yJRTZd4uoSjnHm+hEuHM0UnJJc9FyDd6KtiYxVSUnGJOzYnw4TXo+Ekfc8eMkmU7RFI24CyJGooJcS/ZZaQw12G5TDbJBMk+nQ3iPNNaVvDqKg+dN7MTj1IZT27K4WCILylTloLkcfSfuFbSq4OIACZKd6ePicWJKjkE1bOOhGilrA8KpfFrxYBZs1wCvtreVx34qHjuXd6KL3LBu6PaPW4YlZtw6KGipOElfq9z6lgPqzTuZbDk5xQiPbZU4ZzjDG+WGbHqSKzbzcAAX9+hxfu04phX3c3KHCee0ojcNoQW5kIQLlWpvFc82ZjxvLnuUzcuT7NmJcT+fcETAi0GXzFM9nDwGS2LDSFgtHRmJeI7JSEfInISllnDBvKf87Oz//unZ2bOzt+vt0ebs8uTy3dGfj96ebH7bbFfiPtlcrNYvXnx19J/Pzo747/X56bvTk7PNNx0ovGDJ87OLb45+2FycvHm1+mG9veT/rc/i6pft+asfNy+3m83FX7bb9buvjl6vL3/9/vzN2Yv1loM/+vrJLqTfTl5c/vrNUbqCnp+uX73+9/N/3MLHN0eX2zebK7++Wl9utifr013M56fn29W//cOPKvP3Z2d/P/r6T188+eLbi8t3p5vvFP+3k1evz7eXR2+2p1+tVk8vN69en3JIF09/fvP8b5vL1fOLi6+5YL592j19++Lk7dHJiz8/++K5xPPD+dnlmsth++wLpPDign/55c3p6U8n/3/z7Ivvvn3K8te8nZ6vX5ycvfzr2832dP0OIr/67/5F4Wq1+vYpO8e+Ls/PT39eb6+E+F8).

**Comment by hpinkos** [comment]
Thanks @timoto!  I'm not sure how soon we'll be able to look into this, but we'll give you an update when we have one.  Or if you have time to look into a fix, we're more than happy to review a pull request =)

**Comment by timoto** [comment]
@hpinkos Thank you for giving this your attention.

I’m sorry but I don’t have the resources to develop a fix myself.

**Comment by likangning93** [comment]
Line segments on terrain work by drawing a volume into an onscreen polygon, then computing positions on terrain within that onscreen polygon and checking them against a set of 3 planes that slice through the terrain, one for the line width and one for each of the ends. Maybe this culling problem is happening because we aren't bounding the top/bottom of this check, so in some cases the planes slice all the way from one side of the planet to the other.

We could confirm by poking around in [`PolylineShadowVolumeFS.glsl`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/PolylineShadowVolumeFS.glsl).

Maybe we can fix this by checking if the position-on-terrain is very far away from one of the volume's positions.

**Comment by hpinkos** [comment]
I'm no longer able to reproduce this.  @timoto if you still see this problem please feel free to re-open this issue.  Thanks!
