### ISSUE TITLE
Having issue when clicking 2d mode

### ISSUE THREAD

**Issue by hijazikaram** [AnalyticalGraphicsInc/cesium#7619]
Have a globe. Im trying to add in the 2d functionality so i can switch back from 3d to 2d etc.
```
const destination = new Cesium.Cartesian3(
                cameraState.x,
                cameraState.y,
                cameraState.z
            );
            this.globeDispatcher.setCameraTransition(true);
            this.map.camera.cancelFlight();
            this.map.camera.flyTo({
                destination: destination,
                orientation: {
                    heading: cameraState.heading,
                    pitch: cameraState.pitch,
                    roll: cameraState.roll
                },
                pitchAdjustHeight: this.globeConfig.flyToPitchAdjustHeight, // Point Towards the Earth during flight
                duration: this.globeConfig.flyToDuration,
                complete: () => this.globeDispatcher.setCameraTransition(false)
            });
```
When I load the page everything works correctly but as soon as i click 2d mode, the globe keeps on transitioning. 
Creating a Sandcastle example (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) that reproduces the issue helps us a lot in tracking down bugs. Paste the link you get from the "Share" button in Sandcastle below.

Sandcastle example: 

Browser: Google Chrome

Operating System:

![image](https://user-images.githubusercontent.com/9812037/53739703-68f24080-3e60-11e9-9e7d-d59c83be8fbd.png)

**Comment by hpinkos** [comment]
Hi @hijazikaram, I'm sorry but I don't understand your question.  I would recommend posting on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
A lot of community members use the forum and it's more likely that someone has encountered a similar problem and may be able to help.  Members of our team monitor the forum as well to make sure questions get addressed.  We use GitHub exclusively for tracking bugs and planning new features.
Thanks!
