### ISSUE TITLE
Move clampToHeightMostDetailed promise to end of frame

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7621]
The `clampToHeightMostDetailed` promise seems to resolve mid-frame. This causes an issue where if you have a `viewer.flyTo` in that promise, the app will crash, since `GeometryVisualizer.update` wasn't called yet.

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xVZbb9s2FP4rnF8soyqtm3Vp3GBpkqIBckNirCjmPSgSHROjSYGknbpD/vsORcuWbWVon8YHyyK/c75z+UhqlUu0ouSFSPQRcfKCzomiywX+o55z+kX9ei64ziknsu+if6YcwdBESpi6l2JFS7D+0FgWkuSafBWSlROLcQZT/jo4mfIVkKmCcAJclhTXr7BkFzVlRBENy/U8riRdUE1XROG8LB3L3IrSPsKLibVzNrGZsZRsG9KV4A9EiaUsCJ5JsThTAL4qndhLooE1eYXnoI7DMhf5gsgcA85UonFcEqUpzzUV/MNeHLnU8C/noeMHfhz5PgbXaZJkQRy56H2UhHHoh9iH2WSUhi6KvNQPRxke+cFoFPtJEA1cyyEkJVDtI44vJC8pf76nupg/CMacCAdhlgUj3wtHcRrGKRB5OMp8P8jCNIxSLwAyF8U4SLI0yoIs8NJ0FG+ZCC8nMudqJuRi17+bXEv6PcJXF5e3k6vJt03vpvwx52WRK82IacZECPaUy09LrQV3+o/5omIEzQl9nmsFMpkteWFycAaNYlQN+WIRjvG5cdxADxGNIZ0h57dNWxhAJsJCHpdVJaDw5RZpRiG4EhAjE89OfzKnCj1J8aJAoqUgCnGhkbKGaM/bjVD6goDMGSlx30RW68IEaP5s9AqtAUGCHiVZiBU5gz7YJGoMSLhopODvb6gDiYSZh704DIMozEZbhUQ49aMoyaKwkUjk4yxJkywJwKgJao8n+G+eADQW+WHop3HaSDFIAuwFmedlIAxLFHkJzsIoMOR+cpCSWHKzJ0Ovi19t+M9gr6+dGtvECcJCjgFTwHgn8BhbZyfo3Tu61zWDErOZ3fwUDZH1hN4jv/FWN3fL+if9C5BHSWNGZOXsmuC2CuVuGNw36jU4anqH6Noy2fGoAdZzwp2t6msbUp7vAO1sf6EwXdozZ+EBxIxKKGqPjSN2qJZ7bEAYo5UStITd3+HPDAmHDkVvHXYehqI2PwO328UCrgNJc7Y7Ys4FExI/XF4cG7zuT722m79ty0/WpM5r2oNg9b1gawYX2LR3EGS1WeiuQFNRhTpq2pFuLovJuiK7TM/sBL69u73swL/QUs8BHXSstcrWKn6TyN1Sm8fNBgTXcEWkXjtvtLEwFT9swLfL6+u7rx096OpkSSo9/wyyv/kf4zoQR0sabZ0ciWTG1hPhHCrmmehPa/gK6LcF0t8dAvUNNeU9tzdWes3IqZ3/nS7qywM+MByMh5rAnQXZquHTsvibaFwoZSzHw8ZoXNIVaPHjtHfwMTXtGVEpBSuzJWOP9Afo83Q8BPyeGRP1zX+3IpLlawOZ+6fXdhJjPB7C67GVthd0y+O/)

[Forum thread](https://groups.google.com/d/msg/cesium-dev/ClAfoaW9DxM/IYzYIOzvAgAJ)

Click "sampleHeights", and then wait, observe the crash when the promise resolves. You can see that this is indeed the issue by wrapping the `viewer.flyTo` call in a `setTimeout(function(){ ... }, 100)`. 

@lilleyse

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/ClAfoaW9DxM/IYzYIOzvAgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7621 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
