### ISSUE TITLE
BlendFunction.js has a mistake

### ISSUE THREAD

**Issue by vtxf** [AnalyticalGraphicsInc/cesium#7622]
Source\Scene\BlendFunction.js

![image](https://user-images.githubusercontent.com/13550568/53776869-75df6480-3f32-11e9-8926-449f53614277.png)

**Comment by lilleyse** [comment]
Thanks for pointing this out @vtxf. Opened a fix here: https://github.com/AnalyticalGraphicsInc/cesium/pull/7624.
