### ISSUE TITLE
How to set entity not to be picked up by mouse

### ISSUE THREAD

**Issue by githubhanjunjun** [AnalyticalGraphicsInc/cesium#7623]
:exclamation: Please use the [forum](https://groups.google.com/forum/#!forum/cesium-dev) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

**Comment by hpinkos** [comment]
Hello @githubhanjunjun, CesiumJS doesn't have this feature.  We have this issue open: #1592
