### ISSUE TITLE
pickPosition question

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#7628]
When use pickPosition, if it picks a primitive but not 3d tile, the position's altitude is very big. How can I pick the position only with 3d tile ?

**Comment by hpinkos** [comment]
@hieeyh pickPosition shouuld work with 3D tiles.  See this example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Interactivity.html

If you have any follow up questions, please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
