### ISSUE TITLE
Remove deprecation warning for fetchImage in 1.57

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7630]
The createImageBitmap PR #7579 changed the parameters for `Resource.fetchImage` and added a deprecation warning:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Resource.js#L900

Which should be removed in 1.57.

Can we add the deprecation label? @hpinkos 

It also looks like `Resource.addQueryParameters` deprecation warning was supposed to be removed in 1.45:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Resource.js#L612

**Comment by lilleyse** [comment]
I changed the title and description to 1.57 and since the PR that deprecated the behavior was merged this month and needs at least one month of being deprecated.

Though I opened https://github.com/AnalyticalGraphicsInc/cesium/pull/7695 to remove `addQueryParameters` and `addTemplateValues`.

**Comment by tfili** [comment]
@OmarShehata Can you remove the deprecation warning for the next release?

**Comment by tfili** [comment]
Fixed in #7799
