### ISSUE TITLE
3D Tiles Rotation problem

### ISSUE THREAD

**Issue by ailsa-lisa** [AnalyticalGraphicsInc/cesium#7633]
```javascript
var m = tileset.modelMatrix;
var m1 = Cesium.Matrix3.fromRotationX(Cesium.Math.toRadians(30));
Cesium.Matrix4.multiplyByMatrix3(m, m1, m);
tileset.modelMatrix = m;

```
The model rotated and flew out.

**Comment by hpinkos** [comment]
Hello @ailsa-lisa, please ask your question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features. Thanks!
