### ISSUE TITLE
maybe pickPosition's  bug

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#7634]
When use pickPosition, if it picks a primitive but not 3d tile, the position's altitude is very very high, and its not the real altitude of the picked primitive. Maybe you can easily recurrent this bug.

**Comment by ysp** [comment]
you may pick the billbord at the same time, the billbord has set disableDepthTestDistance option.
[https://github.com/AnalyticalGraphicsInc/cesium/issues/7602](url)
