### ISSUE TITLE
Too many imagery layers render black on iOS

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7640]
[Sandcastle](https://www.google.com/url?q=https%3A%2F%2Fcesiumjs.org%2FCesium%2FBuild%2FApps%2FSandcastle%2F%23c%3DzVrrctu6EX4VNCcTSROJlOJcZdmtYmd81HHixHJOJo0zHoiEJUQgwQCgLCXj1%2BiD9Hefpk%2FSXZAUL6JvOTnt0UwcCtjrh8UuuNCCKrLg7IIpskNCdkH2mOZx4Pxmx5oNz37dk6GhPGSq0SbfT0MCnwnV7JCumHrLvTlw98k5FZqdhpet7dNwAWJ5QKdMrSyRBumJGqc0DKQJMU6%2Blj4TQJhqEAljn3z63K7oLI3GkR2DoTAWIh305UVYM6yZYJ5hfs0U12M7SSeCZdPncegZLsOmtaWVWYYfxUysQmJmXDu5XQ4PfbY8Os8YdndIdzthukz1KMo125DdJpazpKKElGP5UrnbOdEaOCfDYSdBrpYmh2WnMJog%2Fek1NTMnoMtmN7WGdEiv9bkgKI58ahJXD7k2zaIhF8AiLxzNzAkPmIxNc%2B0heFVrZ71duCbbABfpdVsV7IS8qFmXm7GzfLfD7gpUeNiszjiChVMzQ5AyvB5W8Kp3sLo8%2F29UPRoe1wblaAPWNOrzWbK7EeAg7rB2nW4lDjYMefCgODSoLuYa9kwxJJ005xQyRBGIfNgmnDTHzUPpzQFSxyjqzfP1bVmizHbIGSYFVzfX1rsu2VMMlo1QISALMKs6y1lmRo1NDYQtaRAJBusIZDqOIqmMsxZxMmO6zEkVCxsGgAGxK6Ij5nEqHEJGpqFJJLXmkJ6IkWRGF4wEsTAcxctztCFYC2YhpjGfgBky9FibfIm1IYLPmbVVwh%2BVqmyTSWwIN5AymUbdAZ2jZG8GnodoHvNojJk9lY0OJ%2Fpysz25AIEomoWGK0amQk4Am9BHj4iM6NeYpX5T33%2BZrcdRZMMjjwj8NF7ycEpe00iTIVPgf6NdJoghLs6hHPmtbTQI1XqxAuRMAcu7KzuW1K%2BqKpREJES6URKNb5VccB%2FSyvcyhzVQCYj%2BxsyYSPdd12cLZ8GVialgVEE6CZmpKsJPQKOxWQnWr6q0o87x0XC%2FzHTZyvbyzX4OlXcwGpMPUgmfjI1izFi3r%2FEYWbgGojFTsL53d1wDH4cjhEOVN%2BVahgJWzfFk4CbWuIpps6ZyrW1niW1noNZdq278uN9HEQsTkXXepp56di%2BXSKve3kElcL%2BLwTPys3TfjLQ0XLBeRzvBV88PLcQ4ot2e03W6rtSB%2BzswHBsasJD80U5oq6ZjDXeoo7Vwzqk2YoUbxr0ABcqTQiq3bvOcA9erpYGUBQ6A0C%2FRtI4MDPW56dtFIlYTmaxI6uA%2BODMN2zbBKLK3R15%2BJFsAINmnhiJdycEy3Xjo%2FA6E31CohFSQV5gfyGhEmkJ6VLSuhfsEzE%2B3COyfW%2BOdypjEXPhQ8GLB3ivRbAw1VDrtnrAlmAKRk5pkLRqNGq0fd%2B79%2BGBMxjPqQ0U6ZoKzcwLVlpIPr0%2FGrWvyzwc2AffQy7u6aEMKIgrLAWRVJ6RoFxX4PJULN8lHlfSDZiZWJkYehWKVpyAXra2LKJG%2BLDTq%2BOsYNGZzZIAqRqGC10azVAEUbyCyhx%2F3S8Rqw9nYEDCKL8fMjPYLUruPngdBfZVZ8iAODtmCiT7pvbhyk1ifHDJ2yAGDbTflEJBkHAMYq9pIr56MsC5DcPAE%2BvSoAEQpL0wN17PXFejRmwNySCdM6LtXZ0J%2BYn2esxWyDcUsln9%2FOvo4%2BTCdvH3y5tno8fBg1v2y%2F%2FWR2gvl0%2Fk4eP1kad794%2Fn0G3930Rl2OtOLrfcH887i3SszDK4r%2FeSK2j98dTwaHp59GJ38enY4fPnqcEyqS1CRCok%2FX5TbYl3OKMSC%2BUekoIbjuDawtZt0GM4AAIxl5Sbizw7lVJ7tYbZv3OBo13lUSEW3cnMM2Ior3CvEVEKGLv6IY0VH8HgM8e9EYe0uVth3sCatl%2F84G3LOlQz22RSKjm52er0nDryebz3Hv51e9xk8v3CePWndLhrutPGOebQ3g%2F2gCeb3a3C6RSjcdhsqHnlWpz3CjL8KlPorvEdAaDhUz5Z%2F5f5O72n3xdOtpw%2BWO9%2BXlw9WO99Xlw%2B%2B7Xz%2FdvnArCK2gyDfZXP8ECBmtgqYUas%2FESxbzwCUn4AKPv4wMnvJi5j%2BM4XL1vPnvcfdnxUuxb%2B3xedA8eteLXF6432jjWrbSVv1rgkOYSB7Uiqfw9GHXbcaSFqgvNGMy1JzpObwF8JRup31bDI568YJdmmKDTAOZ0FcBnleZSE7OzuksX7Xb5Q6RyJta5VbQ1Nmmt36Dl%2B581tuwl0SOFuwOvEFnEYFTc2qd3knqtC7dhAJFAL%2FbVc72E4U61nektxAtX6Za7FtEyqiGW0TPZMXm0BvoATSq6t8hT%2BJG1Y6SEmBSM%2BXv1ERs2aques8KfOgKVew4FSbGBWzMssmWvV9urTn%2B6lhdTfapIES8X9kbXzehHOjwVrEKISjcNYxrGs0prZsdH91JCBvYa%2F8isZw5h0c5eF1By9EbBs204b9SxiyNwSk0%2BGl8N4QaaNlM9h5qxB61ulStxLm6prLp6HrwvHStyf0%2FObFSDuwf%2FQa9gMLMIunjT7yfpT0ND1s%2FqFDHLuY6JSRUkwoBpkvvRiZ0LBXCf%2FL1chvNlKSBqquLimNIrFCW%2BCopfMWbDuT26pt2IKGowm%2Bt2GXs8jVKG3zRsvR8UR7ik9Y3jdf78FiMzepGQSKSQhntwwKX8mog130Ql8xvUOSysljiILkRSI06Vnn1z7VELsiWOpipYvxMci5t8nDh%2BUw4fZFOhO4cYO1cWXxiX9ulQTYmrJpPN8uk0ygYs8LY5frmKtBoO4SparjcwGdNFUUSGz2KFBkCahIYseyGlK%2BKGMBHLebBeJKEd3IhnlItEsbdAMZvA%2BrZvIs1RVszufWlhesrduRl0mc32vfG9juwG5C%2Bjce4IUBnnya8GJhWBAJLNLuJPbmzDie1pk9v2QbsbC6E0iXUyWhhPaJmk5o8%2FGjNsn%2BdZ3nxUoZ4Zt6OO2Tx9GyMDyBgwFTHUV9Huvi5GVFLQ%2Bj2JRSGFMGOwYdKvg07JOA%2B7DDNjV2jIz65FFJazY1kcbIoDhbVWuDHYpJUTOUiVBjA6WfPCJkH8vnAjtu62s%2FJwdIHmvCYPE6kGRuUOjE0c06t7ai5VVqQxmym3TY1HOjls7t1QzcLLwGPl8QOByf3qtc8Z%2FeI56gWsPMeSzEmH9jp%2Fd2By7Ql9iEpLhGR8mbLZLMeruHyaDjOAMXvm5ypS4COYxaP3cHZiL9FYFNQTsTqASoWELC8Wb9rGd0L90PA1joIh3Ef598hx3VJ%2FcjvDoz%2BT0oHB7vI23b%2FhYgJyhcimYkgEymIdHi7w6SeLYvCKBnxrz5RC4Bm5J6HGawuXDvW5CAsyynnEcHOqJhSYRhS9MnybFuwe3tXp%2F8JbN1M6Nbe1tWF8rakG%2FJSxrWUm8S2ibSHjJ1TpofV9eTJ9bg5KgFJuOJLqcvVd%2FESDtSBOVGjErIK6zHAHvAQ%2FjWxSe6hKcePGnDIhx0ur3KwqRmpYdT%2B%2B29zbrYT0XxjfKCb9o0mMSQesLMjORbYWskm6azHi%2BFBRwM54XLb7yozxBKfsWRBuZ9%2B6sBvFnCi%2FmNhcru5ZtrOrD6P%2F%2F818BN1O7%2BD%2B1OfkFxa7sPE%2FKS3f%2BusxseFaYC1yYBnLE5AUeS1PFf&sa=D&sntz=1&usg=AFQjCNG7-qvJWbrELwYHydloooqpxJ_0vw).

Check the "Tile Coordintes" layer. On a 3rd Generation iPad Pro, iOS 12.1.4 you'll see this imagery layer rendering parts of it as black:

![black](https://user-images.githubusercontent.com/1711126/54226712-bd3a9780-44d4-11e9-84af-efd776315775.png)

If you move the imagery layer down (click the down array in the UI) eventually it renders normally again (but then a different layer is black?)

[Forum thread](https://groups.google.com/d/msg/cesium-dev/jQXp6ho71-s/BmIqKyO3AQAJ)

**Comment by gastonmz** [comment]
I have a couple of samples more from an iPhone X and an iPad Air 2.

Both devices with iOS 12.1.4 and url was opened using Safari.

![IMG_8030](https://user-images.githubusercontent.com/505283/54230212-bb78d000-44e4-11e9-82d2-ca243459af8a.PNG)
![IMG_8029](https://user-images.githubusercontent.com/505283/54230223-c2074780-44e4-11e9-97f0-00d3f7fbae47.PNG)
![IMG_2258](https://user-images.githubusercontent.com/505283/54230460-38a44500-44e5-11e9-8d4a-bbb87519c7d4.jpg)
![IMG_2257](https://user-images.githubusercontent.com/505283/54230462-38a44500-44e5-11e9-8bdf-8398b2653964.jpg)

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/jQXp6ho71-s/BmIqKyO3AQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7640 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
