### ISSUE TITLE
Why my alpha doesn't work?

### ISSUE THREAD

**Issue by herewaitting** [AnalyticalGraphicsInc/cesium#7643]
I created a command myself. The alpha value in its element shader is ineffective. The effect is as follows. Why?
![QQ图片20190313175134](https://user-images.githubusercontent.com/22114883/54269735-e0d70e00-45b8-11e9-841b-e32f635df465.jpg)

**Comment by herewaitting** [comment]
Additionally, I draw the frame cache with postProcessStages
![QQ图片20190313183036](https://user-images.githubusercontent.com/22114883/54272221-2ba75480-45be-11e9-86ba-014c90d21401.png)

**Comment by hpinkos** [comment]
Hello @herewaitting, sorry we missed your question.  If you are still having trouble, please ask on our forum and we'll be happy to help: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
