### ISSUE TITLE
Overlapping Imagery Layers Produce Black Tile Artifacts on Chrome and Firefox

### ISSUE THREAD

**Issue by justin-lau** [AnalyticalGraphicsInc/cesium#7649]
When certain number of imagery layers overlaps (I used 15 in this demo). [See it on sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=jVPfb9owEP5XLF4IAxxgYnQloLGuUpEyrSrd+hIJOcklWHXsyDZBrOJ/3yUhQMvL/OL47vvuvvuRgmlScNiBJjMiYUfuwPBtRv9UNqcdVc87JS3jEnS7R94CSfDwjKWg949aFTxG9m3DjDQwCy9Ki3hZY5wjpTzG7gWcwUslL5Gr0ksX90/Lhb9+WT4/rP3F93t/VfMPnV79ETIDPtuDfuTRa5U7YcJAIA+daSADWWBRovQbLKqujpoIJNCj6opspjUyFCx6/cl0iMJmRx5lcaOpqdC56A7K/uh9I8wYsMv4lny+GY5QbK3lIjplIt8wzDGg4ytfqHm6sRJMqXlEBxUgUZo4pUZesqZ4eWQ4xrvb7TSDKN0qSTB3hamNrkt+y0hlGUhL7AZIooRQOy5TInCOxCrC8lzsj8weYTKucKngNtoQbkiqJDTBTvFH5BPhxxz/1akVphTwzAVcNey8FFstcIZtSt1qPsatyWtfpWqtCtCYiuYybffOHA2RZWXs8zI9NSaaaJX9gFQDGKc/GdMB6Z8qHd3gs3t69r9M3ru/0sn45O80m1cO89Dqtbxqgee1+RvPcqVtqd9B8RayXODuGzfc4l5aGhlT8jy3IXkxLwiPZ0Hrw38VtEgkcIHQk2yFWPG/ELTmnov4dzShWIwd/VX3pIRshnO/NlJKPRef1yyrlAiZvoj4Dw).

![image](https://user-images.githubusercontent.com/2094881/54352148-eea99380-468b-11e9-84c2-b0d3c09ac985.png)

When an offset is applied to the layers, stopping them from overlapping, it renders correctly:
![image](https://user-images.githubusercontent.com/2094881/54352226-1ef13200-468c-11e9-8a0e-7dadfda3c9d7.png)

Tested on the following browsers
  - Chrome v72.0.3626.121 (64-bit) -> **Reproducible**
  - Firefox v65.0.1 (64-bit) -> **Reproducible**
  - Safari v12.0.3 (14606.4.5) -> _Not Reproducible_

Operating System: macOS Mojave 10.14.3
Tested and yield same result on multiple generation of iMacs, Macbook Air, and Macbook Pro.

**Comment by hpinkos** [comment]
Thanks for including the code example @justin-lau, I was able to reproduce this as well.

**Comment by likangning93** [comment]
wonder if this is related to https://github.com/AnalyticalGraphicsInc/cesium/issues/7640

**Comment by shunter** [comment]
It's been a long time since I looked at any of the related code but this feels like it could be a result of exceeding the number of texture units, since we bind all overlapping imagery tiles for a terrain tile as separate textures.  The iPad probably has a lower limit than a desktop card, so encounters the issue earlier.  If my hypothesis holds, in the picture for this issue, it's not that they're overlapping, but rather in the second picture where it draws correctly, several of the images have been moved from the tile for eastern US to the western US tile, putting the eastern tile below the limit.

**Comment by likangning93** [comment]
> feels like it could be a result of exceeding the number of texture units

I think Cesium is supposed to get around this by breaking the imagery layers across more draw calls as necessary, but maybe something is going wrong with that.

More data:
* unable to reproduce on Chrome 72 in Windows 10, GT750M via ANGLE, even with 128 iterations. http://webglreport.com/ indicates a limit of 16 texture image units in the fragment shader.
* able to reproduce on Chrome 72 in Linux, Intel Bay Trail via Mesa DRI, with as few as 13 iterations (+ base imagery + black marble, so 15 layers that I'm aware of). Curiously, webglreport also indicates a limit of 16 texture image units in the fragment shader for this potato's-impression-of-a-gpu (said with endearment, not frustration)

**Comment by gastonmz** [comment]
> wonder if this is related to #7640

yeah... seems to be the same issue

**Comment by likangning93** [comment]
> feels like it could be a result of exceeding the number of texture units

> I think Cesium is supposed to get around this by breaking the imagery layers across more draw calls as necessary, but maybe something is going wrong with that.

Spitballing, maybe some commit added a batch table to globe tiles but didn't update `GlobeSurfaceTileProvider` to take this into account when figuring how many textures can be used in a draw call, and maybe some platforms (Nvidia + ANGLE?) are underreporting the number of texture units.
See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/GlobeSurfaceTileProvider.js#L1555

**Comment by likangning93** [comment]
Able to confirm on Windows 10 + Intel (HD 4000) as well.

A little more narrowing down seems to point at https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/GlobeFS.glsl#L106, having the function return something like `texture2D(textureToSample, textureCoordinates) + previousColor` instead of what it's actually doing seems to work as expected. I'll keep digging.

**Comment by likangning93** [comment]
Incidentally, can't reproduce on Windows 10 + HD 4000 in IE11.

@justin-lau I'm testing a fix [here](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fixManyImageryLayersIntel/Apps/Sandcastle/index.html#c=jVPfb9owEP5XLF4IAxxgYnQloLGuUpEyrSrd+hIJOcklWHXsyDZBrOJ/3yUhQMvL/OL47vvuvvuRgmlScNiBJjMiYUfuwPBtRv9UNqcdVc87JS3jEnS7R94CSfDwjKWg949aFTxG9m3DjDQwCy9Ki3hZY5wjpTzG7gWcwUslL5Gr0ksX90/Lhb9+WT4/rP3F93t/VfMPnV79ETIDPtuDfuTRa5U7YcJAIA+daSADWWBRovQbLKqujpoIJNCj6opspjUyFCx6/cl0iMJmRx5lcaOpqdC56A7K/uh9I8wYsMv4lny+GY5QbK3lIjplIt8wzDGg4ytfqHm6sRJMqXlEBxUgUZo4pUZesqZ4eWQ4xrvb7TSDKN0qSTB3hamNrkt+y0hlGUhL7AZIooRQOy5TInCOxCrC8lzsj8weYTKucKngNtoQbkiqJDTBTvFH5BPhxxz/1akVphTwzAVcNey8FFstcIZtSt1qPsatyWtfpWqtCtCYiuYybffOHA2RZWXs8zI9NSaaaJX9gFQDGKc/GdMB6Z8qHd3gs3t69r9M3ru/0sn45O80m1cO89Dqtbxqgee1+RvPcqVtqd9B8RayXODuGzfc4l5aGhlT8jy3IXkxLwiPZ0Hrw38VtEgkcIHQk2yFWPG/ELTmnov4dzShWIwd/VX3pIRshnO/NlJKPRef1yyrlAiZvoj4Dw).

**Comment by justin-lau** [comment]
> Incidentally, can't reproduce on Windows 10 + HD 4000 in IE11.
> 
> @justin-lau I'm testing a fix [here](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fixManyImageryLayersIntel/Apps/Build/Sandcastle/index.html#c=jVPfb9owEP5XLF4IAxxgYnQloLGuUpEyrSrd+hIJOcklWHXsyDZBrOJ/3yUhQMvL/OL47vvuvvuRgmlScNiBJjMiYUfuwPBtRv9UNqcdVc87JS3jEnS7R94CSfDwjKWg949aFTxG9m3DjDQwCy9Ki3hZY5wjpTzG7gWcwUslL5Gr0ksX90/Lhb9+WT4/rP3F93t/VfMPnV79ETIDPtuDfuTRa5U7YcJAIA+daSADWWBRovQbLKqujpoIJNCj6opspjUyFCx6/cl0iMJmRx5lcaOpqdC56A7K/uh9I8wYsMv4lny+GY5QbK3lIjplIt8wzDGg4ytfqHm6sRJMqXlEBxUgUZo4pUZesqZ4eWQ4xrvb7TSDKN0qSTB3hamNrkt+y0hlGUhL7AZIooRQOy5TInCOxCrC8lzsj8weYTKucKngNtoQbkiqJDTBTvFH5BPhxxz/1akVphTwzAVcNey8FFstcIZtSt1qPsatyWtfpWqtCtCYiuYybffOHA2RZWXs8zI9NSaaaJX9gFQDGKc/GdMB6Z8qHd3gs3t69r9M3ru/0sn45O80m1cO89Dqtbxqgee1+RvPcqVtqd9B8RayXODuGzfc4l5aGhlT8jy3IXkxLwiPZ0Hrw38VtEgkcIHQk2yFWPG/ELTmnov4dzShWIwd/VX3pIRshnO/NlJKPRef1yyrlAiZvoj4Dw).

Thanks, @likangning93! Great investigation and fix!
