### ISSUE TITLE
load kml 如何直接加载文件内容，不用地址

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7653]
viewer.dataSources.add(Cesium.KmlDataSource.load(url, options));

如果我不使用’url‘加载数据 ，而是加载 它的文件内容，请问可以加载吗？

**Comment by hpinkos** [comment]
yes, you can find examples for how to do this in our spec: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/DataSources/KmlDataSourceSpec.js#L380-L387
