### ISSUE TITLE
Terrain overshadows 3D Tiles model

### ISSUE THREAD

**Issue by ladislavhorky** [AnalyticalGraphicsInc/cesium#7656]
Hello,

parts of my 3D Tiles city model gets overshadowed by terrain when displayed with it. Is there a way to ensure the model is always visible over the terrain?

[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVNNb9swDP0rgi9xBlvqEAwY0rQY0AIdhg0r2mC7+KJIbKxGljxKdpAW+++lv9K0O88HGxb5yMfHp1Yiaw3sAdkFc7BnVxBMU/Ff/Vk6U/3vlXdRGgc4y54Lx+hB+NNAiHfgNOAPr4EtWcQGsiEcAZEAt+hbQwnLqaxCkBF+e7R6PaSk88L9nZ8XrnAtcYnGQoD4lszwWVyvh2A6cmjQLlmRlDHWYSmE0o5XYP3eceUrsdB9LTEciQ04GXeH3EmdP5onQN+IsRl/DN4VyZHHdExc9YFGqEwAHktw6UPjVDTepWPKnBGVQT4eFDjgNZrKRNNC4FLrY975wFgIZr3fMRkZ1ZuGPZZ48r5a+wmUnUrwlbgYt701UZV30m0hzc/4ImP0/pxNhfjGN65Lu69LQOBImCawD+yMf5p3HMYBx5o34L/R5NcyynvfoAJuvdTpQHWgO5vERbnnWxPLZtMEQEV+ABd7nS01CVa2pcfdQWxkjBZy/5AvdI69O4hPHqJUuyC2ZV7LLS2lltTOBtpGRS4y/QZmGXtt/b8bK/R1DXpsXLjn06mVlVW99jfYyTka+zSesUriDvCefEThs07YdwbRR1F7j0zYcdGv0cEmJ9nDlpIsWYV4sHA5YL+YqvYYO8unnIsIVW3pIgWxadSOFq9C6JArMYFW2rTM6IsieXeDi4TReCFQ5KGxthuhSC5XgvLfwDorkIA/W0ArD11K+fHy+3DIOV8J+v0XFb23G4knFV8A)
Browser: Chromium 72.0
Operating System: Ubuntu 16.04

Thanks,
Ladislav

**Comment by hpinkos** [comment]
Hello @ladislavhorky, you can use a `modelMatrix` transform to adjust the height of the tileset to line it up with terrain.  See this example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Adjust%20Height.html&label=3D%20Tiles

In the future, if you have questions like this, please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
