### ISSUE TITLE
cannot toggle show of CzmlDataSource

### ISSUE THREAD

**Issue by CHBaker** [AnalyticalGraphicsInc/cesium#7658]
Sandcastle example: 
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=jVNNb9swDP0rgi9xgEx2VqTAMjdYlhx2GLCDh558YWW6ESZLgT4cpEP/+yg7Sd02AyrYsESRj4+PdAeWdRIPaNkd03hgG3QytPy+t6UT0R83RnuQGu1kxv5WmtFyOxNUvdayBY9sybwNWOnn6ddKV7oEXQtwXiGHut5iA0H538aoB7Dfg/dGp5OS4pSSHh2BNkELL8k8PeN3RMxZ8ZrV5qlVW/BQmmAFpifXE53DkjWgHA7GnkncnOD6enh9CXaRWUoZuDJQpxPOs8uz3u9dVkK7VxizZU7GLReUfTIdKhxhCmjRAm/U8YdpMc2jw1Ud3ghwjzspFF6v/jrdqzJ8oIBTqv9V4ARqPNfh0Mfmj8Wt0XmpIVJcsksvwFLvJOgb3ljTbvHRIrr003x+yxefZ+xmwXP6fFnkeT6dvYAZK5GmaQAbJYlrh1BL/bhkty/251E/38tqkfjSkHxIQout6XCtVNqD0ZvMksL5o8LVEPSNOm2sZ8GqlHT0SBLSnLrsIYg/6LlwLoYW2TmoqGXHZH1XJW/+lCphQoFzdNMEpUr5hFWyKjLyfxUWm0cl/+rQKjhGl9189XMwcs6LjI7vo/wwSiPESv8D

Browser:
Fire Fox

Operating System:
Windows 10

Bug:
I cannot toggle show of CzmlDataSource, in the example above I set `show: false` before adding it to the dataSources, but it is still visible. More so, when I log the object the property is set to `show: true`

**Comment by hpinkos** [comment]
Hello,  `show` is not a parameter of `CzmlDataSource`.   See the reference documentation: https://cesiumjs.org/Cesium/Build/Documentation/CzmlDataSource.html

Instead, you can set it after you initialize the object: 
```js
var src = new Cesium.CzmlDataSource();
src.show = false;
```

**Comment by CHBaker** [comment]
It is a property though? https://cesiumjs.org/Cesium/Build/Documentation/CzmlDataSource.html#show

**Comment by hpinkos** [comment]
yes, it is a property that has a getter and setter, but it is not configurable by passing something into the constructor

**Comment by CHBaker** [comment]
Thanks, sorry for the misconception
