### ISSUE TITLE
clamptoground area and length

### ISSUE THREAD

**Issue by zhouwenhui008** [AnalyticalGraphicsInc/cesium#7660]
Can I calculate clamptoground area and length of polygons and polylines on the 3d tiles?

**Comment by hpinkos** [comment]
Hello @zhouwenhui008, CesiumJS does not include methods for computing area and length, so you would need to implement ways to calculate this.

We offer a commercial product that includes widgets for doing analysis, including area and distance measurements.  See [Cesium ion SDK](https://cesium.com/ion-sdk/)
