### ISSUE TITLE
Issue with Earth Orientation Parameters

### ISSUE THREAD

**Issue by EstesJL** [AnalyticalGraphicsInc/cesium#7662]
Hello,

Having an issue getting CZML to display properly. The STK scenario of the Apollo 11 scenario shows the rocket launching from the pad at Kennedy. However, the CZML shows the same rocket launching from the middle of the ocean off the coast of Florida.

We're determined the issue is probably with the way the Earth is oriented vs. STK. We created an EOP.json file to correct the discrepancy, but when loaded in the same way as the docs (https://cesiumjs.org/releases/b30/Build/Documentation/EarthOrientationParameters.html), there doesn't appear to be any effect.

No errors are thrown, and the file appears to be accepted. Any idea what might be going on?

**Comment by hpinkos** [comment]
@shunter?

**Comment by emackey** [comment]
I'm in touch with @EstesJL offline.
