### ISSUE TITLE
How is the orientation of the FrustumGeometry different from that of the viewer.camera?

### ISSUE THREAD

**Issue by zhishiqu** [AnalyticalGraphicsInc/cesium#7664]
Hello,
    I have a Cartesian3 (4368392.400488, 615948.622292, 4592230.377595) and an oritation Matrix3(-0.214407,  -0.911161,  0.351874,  -0.624334,  0.404895,   0.668032,  -0.751157, -0.076456,  -0.655682) represent the camera position and view direction respectively.
    Firstly, I draw a frustum represents the camera in the sky using the following code. The result is right, i.e., the camera position and direction is coincide with the terrain modle (please see the code below).
`var rotation = new Cesium.Matrix3(-0.214407,  -0.911161,  0.351874,  -0.624334,  0.404895,   0.668032,  -0.751157, -0.076456,  -0.655682)
	rotation = Cesium.Matrix3.transpose(rotation, new Cesium.Matrix3);
	var orientation = Cesium.Quaternion.fromRotationMatrix(rotation);
	var frustum = new Cesium.PerspectiveFrustum({
		fov: 2*Math.atan(6.17/(2*4.05096043224506)),
		aspectRatio: 4000 / 3000,
		near: 1.0,
		far: 50.0
	});
	var frustumPrimitive = scene.primitives.add(new Cesium.Primitive({
		geometryInstances: new Cesium.GeometryInstance({
			geometry: new Cesium.FrustumGeometry({
				frustum: frustum,
				origin: new Cesium.Cartesian3(4368392.400488, 615948.622292, 4592230.377595),
				orientation: orientation,
				vertexFormat: Cesium.VertexFormat.POSITION_ONLY
			}),
			attributes: {
				color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 1.0, 1.0, 0.1))
			},
			id: url,
		}),
		appearance: new Cesium.PerInstanceColorAppearance({
			closed: true,
			flat: true
		})
	}));`
However, when I use the same Cartesian3 and Matrix3 to set a camera view with the following code, the result is wrong. I first calculate the Quaternion from the Matrix3. Then the Heading/Pitch/Roll is obtained from the Quaternion. Finally the Heading/Pitch/Roll is used into the setView function. 
    Could you help me to find if there is any thing wrong in my code?
`var rotation = new Cesium.Matrix3(-0.214407,  -0.911161,  0.351874,  -0.624334,  0.404895,   0.668032,  -0.751157, -0.076456,  -0.655682)
	rotation = Cesium.Matrix3.transpose(data.origin, new Cesium.Matrix3);
	var orientation = Cesium.Quaternion.fromRotationMatrix(rotation);
					
	var hpr = Cesium.HeadingPitchRoll.fromQuaternion(orientation, new Cesium.HeadingPitchRoll());//四元数转roll、pitch、heading
	console.log('roll:',hpr.roll,'\npitch:',hpr.pitch,'\nheading:',hpr.heading)
	console.log('roll:',Cesium.Math.toDegrees(hpr.roll),'\npitch:',Cesium.Math.toDegrees(hpr.pitch),'\nheading:',Cesium.Math.toDegrees(hpr.heading))
	viewer.camera.frustum.fov = 2*Math.atan(6.17/(2*4.05096043224506))
	viewer.camera.frustum.aspectRatio = 4000 / 3000;
	
	viewer.camera.setView({
		destination: new Cesium.Cartesian3(4368392.400488, 615948.622292, 4592230.377595),
		orientation: {
			roll: hpr.roll,
			pitch: hpr.pitch,
			heading: hpr.heading,
		},
	});`

Yours sincerely,

    Lei Wang

**Comment by hpinkos** [comment]
Hello, sorry we missed your question.  If you are still having trouble, please post on our forum and we'll be happy to help: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
