### ISSUE TITLE
Cesium Inspector Undefined min/max in 1.55

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7672]
Go to:

https://cesiumjs.org/releases/1.55/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html

Click "Terrain > pick tile", notice the min/max is undefined.

Go to:

https://cesiumjs.org/releases/1.54/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html

Repeat the above, notice the min/max works. Is this a bug in terrain, or does the inspector just need to be updated to account for @kring 's changes?

**Comment by dennisadams** [comment]
The inspector just needs to be updated. As part of the terrain overhaul (#7061) the `minimumHeight` and `maximumHeight` properties have moved from the `QuadtreeTile`'s `data` to `data.tileBoundingRegion`.
To fix it simply add `tileBoundingRegion` in the missing places:

https://github.com/AnalyticalGraphicsInc/cesium/blob/10588c0e707334a0166078db7927caeaa098e6d5/Source/Widgets/CesiumInspector/CesiumInspectorViewModel.js#L887

Another place where it needs to be added is in `Globe.prototype.getHeight`:

https://github.com/AnalyticalGraphicsInc/cesium/blob/8cb03492558b6a19330ceef0eba801cdcf8c450d/Source/Scene/Globe.js#L678


These are the places I found that haven't been updated, there might be some more.

**Comment by OmarShehata** [comment]
@dennisadams thanks for looking into this! If you have a chance to, it would be awesome to open a PR with this! And then even if there are other places the reviewer might recommend where to look or double check that this is all.
