### ISSUE TITLE
Cesium still cannot work when using webgl 2.0 in Chrome ??

### ISSUE THREAD

**Issue by jackforest2014** [AnalyticalGraphicsInc/cesium#7674]
Sandcastle example: 

Browser: Chrome latest

Operating System:  Mac OS

![image](https://user-images.githubusercontent.com/7624696/54878710-4c4b9600-4e6b-11e9-81d8-08f19b875d69.png)

And nothing is rendered.

**Comment by hpinkos** [comment]
Cesium does not officially support WebGL 2 at this time.  We would like to fully support WebGL2 soon, but I'm not sure when we'll be able to make it a priority.  In the meantime, we would be happy to review a pull request to get WebGL 2 working again if you have some time to look into it!  Thanks
