### ISSUE TITLE
czml   ellipsoid Can't load image

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7676]
@hpinkos ,使用下面的czml ，无法在ellipsoid上添加material图片
var czml = [{
    "id" : "document",
    "name" : "CZML Path",
    "version" : "1.0",
    "clock": {
        "interval": "2012-08-04T10:00:00Z/2012-08-04T15:00:00Z",
        "currentTime": "2012-08-04T10:00:00Z",
        "multiplier": 10
    }
}, {
    "id" : "path",
    "name" : "path with GPS flight data",
    "description" : "<p>Hang gliding flight log data from Daniel H. Friedman.<br>Icon created by Larisa Skosyrska from the Noun Project</p>",
    "availability" : "2012-08-04T10:00:00Z/2012-08-04T15:00:00Z",
    "path" : {
        "material" : {
            "polylineOutline" : {
                "color" : {
                    "rgba" : [255, 0, 255, 255]
                }              
            }
        },
        "width" : 8,
        "leadTime" : 10,
        "trailTime" : 1000,
        "resolution" : 5
    },
    "ellipsoid" : {
        "radii" : {
            "cartesian" : [30.0, 30.0, 30.0]
        },
        "fill" : true,
     
        "material" :{
            "image":{"image":{"uri":"../../cesium_credit.png"}},
        },
      
    },
    "position" : {
        "epoch" : "2012-08-04T10:00:00Z",
        "cartographicDegrees" : [
            0,-122.93797,39.50935,1776,
            10,-122.93822,39.50918,1773,
            20,-122.9385,39.50883,1772,
            30,-122.93855,39.50842,1770,
            40,-122.93868,39.50792,1770,
            50,-122.93877,39.50743,1767,
            60,-122.93862,39.50697,1771,
            70,-122.93828,39.50648,1765,
            80,-122.93818,39.50608,1770,
            90,-122.93783,39.5057,1754,
            100,-122.93777,39.50513,1732         
        ]
    }
}];

var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider : Cesium.createWorldTerrain(),
    baseLayerPicker : false,
    shouldAnimate : true
});

viewer.dataSources.add(Cesium.CzmlDataSource.load(czml)).then(function(ds) {
    viewer.trackedEntity = ds.entities.getById('path');
});

///////////////////////////////////////////////
  其中的：
    "ellipsoid" : {
        "radii" : {
            "cartesian" : [30.0, 30.0, 30.0]
        },
        "fill" : true,
     
        "material" :{
            "image":{"image":{"uri":"../../cesium_credit.png"}},
        },
      
    },
ellipsoid ->material 无效，请问有什么方法可以有效
![捕获](https://user-images.githubusercontent.com/33933148/54904278-0ea54680-4f19-11e9-86a6-2b3541dd6375.JPG)

**Comment by OmarShehata** [comment]
I think you're just incorrectly setting up the image in the CZML (and I think that URL to the image doesn't work).

This is how you can add an image as a material to an ellipsoid in CZML:

```
"material" : {
            "image" : {
                "image" : { "uri" : "../images/Cesium_Logo_Color.jpg" }
            }
        }
```

Here's a full [Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1VVdb9owFP0rFi9lEjOh0E1qKZpEp70wbRrTHkZQZeJLuKtjR7YDgon/PicOECBsk9ZNWoSInXPP/fC5ul4yTaJNIsg9mXwPJXFP2EAeNsitW3AVZQlIGzZaO0yyBEp0+PX9iLwDlYDVCOaWjNMFaDCESU7eCoGpUchNhbwEbVDJkt+hQdgI5bZFziPPRAZ7F/XhcxMCNTapMmh3YUrXHomYtirWLF1g9ACxBjCF0eRlp9OjQYv0gvy/G+QPDaaeu917rkQ7da0ZRzz9fIgKBplPaHJdem+Rw+okYjWq9zFHIQq61RkcIQmzoJGJ+tiYsBjqoDPY7TKN5dlS2i4g0x66zLPkcaRi9ThUQmn6LY2d1fbYXWVbLrcXlNXAfZ/Uq/oJODEFTlZoF2QmWPREVGYFSvhTkYPX/0rk7pm0f1FkowTyQpzLSkc/g8vq4hkrW/TmpkWC4tcJqvnWyH2q/lHee93qiirBi4n7jOY+pWCf0PS3W23tpFSrX4yRvdy+3zzn2Rou+D+mypwJA8+tXKWXdg3l3heTMQIj+OiqKo7ZH+F179jEumFwYtJ9dWiC6V0oQ7l0d9oSYQXa3WoSVsTPMPql+Na8iortUEnLXBH66sWd53Bm2Vhl2mWhVYIGHL2kDt0V+bCHqVCMN/Nrs6AWbumBbSjjvHnmrWK7USr5rOpN8moarUbf2LWAQSjfYJIqbUmmRdONZQtJKtw0MO1ZFj2BpZExOa3f3hH6HJcE+b1rkeNC3XFFghnjkHkmxBg3Tt5Bv+3sj2h5dSjjD+62Fmydmyw6g5H/SCntt932nGWVEjOmKx5D+QM). 

I used the [CZML Rectangle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=CZML%20Rectangle.html) Sandcastle as a reference since it has an example of adding an image material.

**Comment by Orcallxl** [comment]
I encountered this issue too. Image material doesn't work when position is time-dynamic:
`var czml = [{
    "id" : "document",
    "name" : "CZML Geometries: Spheres and Ellipsoids",
    "version" : "1.0"
}, {
    "id" : "blueEllipsoid",
    "name" : "blue ellipsoid",
    "position" : {
        "cartographicDegrees": ["2021-07-10T14:15:57Z", -114.0, 40.0, 300000.0,
                            "2021-07-10T14:15:57Z", -115.0, 40.0, 300000.0,
                            "2021-07-10T14:16:57Z", -116.0, 40.0, 300000.0,
                            "2021-07-10T14:17:57Z", -117.0, 40.0, 300000.0,
                            "2021-07-10T14:18:57Z", -118.0, 40.0, 300000.0,
                            "2021-07-10T14:19:57Z", -119.0, 40.0, 300000.0,
                            "2021-07-10T14:20:57Z", -120.0, 40.0, 300000.0,
                            "2021-07-10T14:21:57Z", -121.0, 40.0, 300000.0,
                            "2021-07-10T14:22:57Z", -122.0, 40.0, 300000.0,
                            "2021-07-10T14:23:57Z", -123.0, 40.0, 300000.0,
                            "2021-07-10T14:24:57Z", -124.0, 40.0, 300000.0
                        ]
    },
    "ellipsoid" : {
        "radii" : {
            "cartesian" : [200000.0, 200000.0, 200000.0]
        },
        "fill" : true,
        "material" : {
            "image" : {
                "image" : { "uri" : "../images/Cesium_Logo_Color.jpg" }
            }
        }
    }
}, {
    "id" : "redSphere",
    "name" : "Red sphere with black outline",
    "position" : {
        "cartographicDegrees" : [-107.0, 40.0, 300000.0]
    },
    "ellipsoid" : {
        "radii" : {
            "cartesian" : [300000.0, 300000.0, 300000.0]
        },
        "fill" : true,
        "material" : {
            "solidColor" : {
                "color" : {
                    "rgba" : [255, 0, 0, 100]
                }
            }
        },
        "outline" : true,
        "outlineColor" : {
            "rgbaf" : [0, 0, 0, 1]
        }
    }
}, {
    "id" : "yellowEllipsoid",
    "name" : "ellipsoid with yellow outline",
    "position" : {
        "cartographicDegrees" : [-100.0, 40.0, 300000.0]
    },
    "ellipsoid" : {
        "radii" : {
            "cartesian" : [200000.0, 200000.0, 300000.0]
        },
        "fill" : false,
        "outline" : true,
        "outlineColor" : {
            "rgba" : [255, 255, 0, 255]
        },
        "slicePartitions" : 24,
        "stackPartitions" : 36
    }
}];

var viewer = new Cesium.Viewer('cesiumContainer');
var dataSourcePromise = Cesium.CzmlDataSource.load(czml);
viewer.dataSources.add(dataSourcePromise);
viewer.zoomTo(dataSourcePromise);

   `
This Javascript code is from the Scandcastl example and I just made the Position time-dynamic. Its Image Material doesn't work.
@OmarShehata Please help to check.
