### ISSUE TITLE
No imagery on cesiumjs.org home page and Sandcastle

### ISSUE THREAD

**Issue by alexander-entin** [AnalyticalGraphicsInc/cesium#7679]
"Tap to interact" on https://cesiumjs.org/ shows black space.
The same for all Sandcastle examples.

Is there something wrong with Bing keys?
Have their rules changed (if I'm not mistaken, my key used to work from localhost but it doesn't ATM)?

Browser: Chrome 72
Operating System: Win 10

(Also, why is https://cesium.com access from Ukraine blocked?
"The Amazon CloudFront distribution is configured to block access from your country")

**Comment by alexander-entin** [comment]
Here is what I see in the console in Sadcastle

Access to XMLHttpRequest at 'https://api.cesium.com/v1/assets/3845/endpoint?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlMWQ3ZWJlYy01ZDM1LTQ2NTctODVhMS04MjQ2MGNjOTBkNjUiLCJpZCI6MjU5LCJzY29wZXMiOlsiYXNyIiwiZ2MiXSwiaWF0IjoxNTUzMTk2Njk4fQ.l8g-x32loizk5_OA1P8D1zOUq6Fkngh4Fu345EDD07o' from origin 'https://cesiumjs.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by alexander-entin** [comment]
Also, is that correct that Cesium.js depends on cesium.com?
Can I continue using (new versions of) Cesium.js w/o cesium.com account?

**Comment by hpinkos** [comment]
Hello @alexander-entin, yes unfortunately access to Cesium ion is not currently available in Ukraine.  You can see an explanation [here](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/31#issuecomment-420769860).  I made a comment in that issue that you've also experienced that problem so we can notify you if and when it gets resolved.  Thank you

**Comment by mramato** [comment]
> Also, is that correct that Cesium.js depends on cesium.com?

This is incorrect. You can use CesiumJS without cesium.com, it just so happens that the default imagery and terrain layers are hosted by Cesium ion on cesium.com.  Cesium can talk to many different servers/standards/formats and can even be used in a closed environment completely offline.
