### ISSUE TITLE
about property model.specularEnvironmentMaps

### ISSUE THREAD

**Issue by vtxf** [AnalyticalGraphicsInc/cesium#7684]
```_shouldUpdateSpecularMapAtlas``` would be always false, if ```specularEnvironmentMaps``` is set twice with the same value. @bagnell 

![image](https://user-images.githubusercontent.com/13550568/55141294-12350980-5175-11e9-9f76-0fea785474f1.png)

**Comment by hpinkos** [comment]
@vtxf Is there a bug this is causing?  If `specularEnvironmentMaps` is set to the same value twice, I don't think we would need to update the specular map atlas.

**Comment by vtxf** [comment]
Of course.
 ```specularEnvironmentMaps ``` maybe undefined or other value before, 
then the property is set to a different new value twice, it would not update with new value.

**Comment by hpinkos** [comment]
Oooh, if it's set to the same value twice in one frame, before the atlas has been updated.  That makes sense.  Thanks for the extra explanation @vtxf, I'll submit a fix for this
