### ISSUE TITLE
Entity images cut when too many billboards as label used 

### ISSUE THREAD

**Issue by ihsanergun** [AnalyticalGraphicsInc/cesium#7703]
![symbols](https://user-images.githubusercontent.com/49189724/55392972-9a802980-553c-11e9-8a59-c177d6c53dbf.png)
I use billboards to show some data of my entities. When I have a large number of entities (2000+), symbols of entities are getting cut (right side).
 

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVVNc9owEP0rGi42hcjOB5nUOEynaTrtTNIeMm0vXGRbGDWyxEiygXb4711JJphAmtYHo4+3b3ffk0xDFGoYXVKFrpGgS3RDNasr/N2thUHupjdSGMIEVUF/PBUNxFBhmFl/rkhJITBXlBh6266VoUVNxUwqFFrwCiDxGH5SdBbHdjQY9NHvqUDwkKLwgS5q4wJrkRsmRXdvC/dvy8qJAd57YuZYEVHICkBv0PlljE7Q6VU87iCB6hAJGEC+3QJ3cN8bRLQp7bOQmrmSkq1CN0QZGBFxjmdKVh9oqSjVIVQ1tAn7w11wxjjPJFEFSjqU9mFOwKQr53AfMaesnJsEjeLd+sYPN05lV7VzCzsWRjUG3UJP2W+78w49NOUdySjfVXkg+YGVWxWsMqz12x4UV2y45Xc7WKscdoO5MQudRJE/PD81lqqMvGzR+5rxop18ExUTbMZoEf1gRUmNjhyrjr6QhpXEFvSJ8kV0L2sN7E0ZtOkUNbUSPusLLRz2uvOze4gAcvsXwxP0uuFogGIcj1yWdnzU/gQdsz9BmdXE6/lU7D5w0zG/leCo6Z12Dq09lqbrLuj7YBQTJbrezx6ksIVWFRf6etqz7oK5y+USL8+dtfZSRwCZ9tCSFWYOIFiCmT+8MD2NR9PeJECD58SK5uYp6HQ/aGRn2qw5hckMRExUmZHwbARK714xvuqPtVHykZ44osSGRfvJgtTQlUErywq7a1chDCwrjDNO8kcoEGRJEATabws28iNb0SI868NCkEaW4VXWi2Os9hQ5Vin+gdUzWz0nwe6Ge3/s7SqIIYk7ORYzAFvGGdH08mJoc2RGkvDJyf74fy8vhL54x3rDXur8mHjEO1YtpDKoVjzEGFqpFiAcXN+szh+pwbnWNgX00galBWsQK0CbZ/8rIFrOibbHa1Zz/sB+URAujQC/F8YlKaCtrw1VnKwtZH46ufOLGOM0gulhlJGSZ0R1GP8A

Browser: Google Chrome Version 73.0.3683.86 (Offizieller Build) (64-Bit)

Operating System: Win 10

**Comment by OmarShehata** [comment]
Thank you for putting together a Sandcastle!

I'm unable to reproduce this even after cranking the number of entities up to 6000.

![icons](https://user-images.githubusercontent.com/1711126/55655204-8862ed00-57c1-11e9-9dea-85047c52810c.png)

Does this happen on any other computers/devices you have?

**Comment by ihsanergun** [comment]
Hi Omar,

Yes, I tried it on Windows and Linux (also different browsers). Well, your images look better tham mines but they do not seem to be shown fully, do they? And you have also a line under some entities...

**Comment by GatorScott** [comment]
I see the lines quite easily on Windows 10, Chrome 73.0.3683.103 and 74.0.3729.108, Quadro M1000M 389.08.  I modified the example to show 900/>900 entities with SVG image (no entities with mouse image).  Here's what I see on the GPU.  The low spots in the "Dedicated GPU Memory" graph are when there are 900 entities.  Anything greater than 900 results in the higher level.

![image](https://user-images.githubusercontent.com/4126790/56657422-fafb1600-6665-11e9-8a4c-0e048041af80.png)

**Comment by hpinkos** [comment]
duplicate #4525
