### ISSUE TITLE
Suspent bug when adding more than one entity's dynamic position from CZML entities?

### ISSUE THREAD

**Issue by findlaywjl** [AnalyticalGraphicsInc/cesium#7704]
I add satellite orbit from a czml file, and add cylinder under each satellite using the entity's position CallbackProperty. But when there is more than one satellite in czml file, the function only render the last satellite's cylinder in czml file, please help...
cesium 1.51 ,chrome 70

	function func7() {

	var dataSource = new Cesium.CzmlDataSource();
        viewer.dataSources.add(dataSource);
        dataSource.process('./SampleData/satellite1.czml').then(function() {

            console.log(dataSource.entities.values.length);

            var saEntity;
            var nowPos = [];

            for(var i=0;i<dataSource.entities.values.length;i++){
                saEntity = dataSource.entities.values[i];
                var isConstant = false;
                var tmp = i;

                viewer.entities.add({
                    id: tmp,
                    name: tmp,
                    position : new Cesium.CallbackProperty(function(time) {
                        nowPos[i] = Cesium.Ellipsoid.WGS84.cartesianToCartographic(saEntity.position.getValue(time));
                        console.log(tmp + ":" + time);
                        //if(i==0){  console.log(tmp + ":"+ time + "pos:" + nowPos[i]); }
                        return Cesium.Cartesian3.fromDegrees(Cesium.Math.toDegrees(nowPos[i].longitude),Cesium.Math.toDegrees(nowPos[i].latitude),0,Cesium.Ellipsoid.WGS84);
                    }, isConstant),
                    cylinder: {
                        length: new Cesium.CallbackProperty(function(time) {
                            nowPos[i] = Cesium.Ellipsoid.WGS84.cartesianToCartographic(saEntity.position.getValue(time));
                            //if(i==0){  console.log(tmp + ":"+ time + "pos:" + nowPos[i]); }
                            return nowPos[i].height;
                            }, isConstant),
                        topRadius: 0.0,
                        bottomRadius: 300000.0,
                        material: Cesium.Color.RED.withAlpha(0.2),
                    }
                });
            }
        });
    }

:exclamation: Please use the [forum](https://groups.google.com/forum/#!forum/cesium-dev) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

**Comment by shunter** [comment]
This is a general JavaScript coding error, and not a problem with Cesium.  In your code, all of the `CallbackProperty` instances refer to the same `saEntity` variable.  See this for more information on how to fix your code:  
https://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example
