### ISSUE TITLE
Sandcastle in old builds is broken after move to Ion

### ISSUE THREAD

**Issue by thw0rted** [AnalyticalGraphicsInc/cesium#7706]
Previous builds of Sandcastle are available under e.g. `https://cesiumjs.org/releases/1.51/Apps/Sandcastle/index.html` and can be useful for regression testing when looking for bugs.  By default, these point to [this map endpoint](https://api.cesium.com/v1/assets/2/endpoint?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3OTM1ODdhMS1hOTliLTRkZDYtYmI4Ny0wYmM0MzI2ZDU4NTAiLCJpZCI6MjU5LCJzY29wZXMiOlsiYXNyIiwiZ2MiXSwiaWF0IjoxNTQxMDk4NzIxfQ.AqAyuEacuEItRBMDBPpwmhJXEjyZB0b69L3ixapXcF0), which has been disabled under the new licensing model.  It's still possible to switch to other baselayer providers using the picker widget, but it'd be nice to update the hosted builds to either default to a supported provider, or use a newer trial access key for Ion services.

**Comment by mramato** [comment]
This had nothing to do with ion, we have been rotating the demo keys even in the Bing-only days (we just had to get more diligent about it because they were being abused). We rotate the key every month but we only revoke keys after 2 months to provide everyone with a little leeway.

That being said, I agree it's annoying when old builds don't work, but I'm not sure how to fix it in a way that doesn't allow for abuse.

**Comment by OmarShehata** [comment]
My go to is to do my testing in the "offline" Sandcastle. So I think @thw0rted 's suggestion:

> it'd be nice to update the hosted builds to either default to a supported provider

Would be to default to Natural Earth imagery for these builds. I don't know if that means we'd have custom old versions, or monkey patch that in, or what the easiest way to do this logistically would be.

**Comment by thw0rted** [comment]
Right, the demo keys.  Is it possible rig up Sandcastle to load the demo key dynamically (from an absolute path) or to go back into the prior-release builds and hand-jam an updated key directly into the sources?

**Comment by hpinkos** [comment]
Yeah, I usually use the BaseLayerPicker to switch the imagery layer.  Or if you're testing something specific, you can set the imagery provider in your test code.  The hosted versions are the official releases.  I don't think we want to go back and change the releases so it defaults to use natural earth or a newer API key.

**Comment by thw0rted** [comment]
I mean, I understand that they're the official releases, but circumstances in the outside world have changed and they don't work as published anymore.  I'm not saying to rewrite source control or anything drastic like that, but maybe it would be possible to do a one time hand-edit job just to keep them usable in the ecosystem as it exists today?
