### ISSUE TITLE
Change what counts as a Bing Imagery session

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7729]
Some ion users may see a high number of Bing Imagery sessions despite not using Bing as their base layer. This can happen even if:

* An imagery layer is added on top of Bing. Bing tiles are still requested just not visible underneath the new layer: https://github.com/AnalyticalGraphicsInc/cesium/issues/7728
* The default imagery layer (Bing) is removed and another imagery layer is added.

```js
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.imageryLayers.removeAll(false);
viewer.imageryLayers.addImageryProvider(Cesium.createTileMapServiceImageryProvider({
    url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
}));
```

Viewer still creates a `BingMapsImageryProvider` under the hood which is enough to start the session. Is it possible to start the session only when the first tile is requested, or add a delay of some kind?

For anyone running into this problem, the best way to bypass Bing entirely is to pass the imagery provider to the viewer directly:

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : Cesium.createTileMapServiceImageryProvider({
        url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
    })
});
```

**Comment by hpinkos** [comment]
Fixed in #7848
