### ISSUE TITLE
Front-end box/button to upload satellite image

### ISSUE THREAD

**Issue by yyzhang0605** [AnalyticalGraphicsInc/cesium#7739]
Hi all, is there any possibility to upload satellite image, say raster tiff image, via folder browse then button click or drop/drag? I have researched it for few days but still no progress. Anyone here can help me or just give me some hint? Thank you very much

**Comment by hpinkos** [comment]
Hello @yyzhang0605, the open source CesiumJS library doesn't have direct support for tiffs.  However, you can create a Cesium ion account and upload tiffs there to tile them into formats that are compatible with visualizing in CesiumJS apps.  You can learn more at https://cesium.com/cesium-ion/
