### ISSUE TITLE
use CallbackProperty return a polygon,doesn't clamp to ground

### ISSUE THREAD

**Issue by eqmaster** [AnalyticalGraphicsInc/cesium#7740]
i load points by Cesium.GeoJsonDataSource.load,without options or with "clampToGround: true":
`Cesium.GeoJsonDataSource.load(geojsonString,{clampToGround: true})`
the geojson contians one point feature.
I need draw a polygon from the point,and need the polygon clamp to ground,but it it doesn't work. 
code:
viewer.dataSources.removeAll();  
var geojsonStr = "\  
{ \  
    'type': 'FeatureCollection', \  
    'features': [{ \  
        'type': 'Feature', \  
        'geometry': { \  
            'coordinates': [111,30], \  
            'type': 'Point' \  
        }, \  
        'properties': { \  
            'ID': '1', \  
        } \  
    }] \  
} \  
";  
var geojson = eval('('+geojsonStr+')');  
Cesium.GeoJsonDataSource.load(geojson,{  
                clampToGround: true  
            }).then(function(dataSource){  
    viewer.dataSources.add(dataSource);  
    var entities = dataSource.entities.values;  
    let _entity = entities[0];  
    viewer.zoomTo(dataSource);  
    _entity.polygon = {  
        hierarchy : new Cesium.CallbackProperty(function(a,b){  
            let cartographicPosition = Cesium.Cartographic.fromCartesian(_entity.position.getValue(Cesium.JulianDate.now()));  
            let latitude = Cesium.Math.toDegrees(cartographicPosition.latitude);  
            let longitude = Cesium.Math.toDegrees(cartographicPosition.longitude);  
            let _a = [  
                longitude,latitude,  
                longitude*=1.0005,latitude*=1.002,  
                longitude*=0.9995,latitude*=0.997,  
                longitude,latitude  
            ];  
            return Cesium.Cartesian3.fromDegreesArray(_a);  
        }, false),  
    height : 0,  
    **heightReference:Cesium.HeightReference.CLAMP_TO_GROUND,**  
    material : Cesium.Color.GREEN.withAlpha(0.5),  
    outline : true,  
    outlineColor : Cesium.Color.BLACK  
};  
});

**Comment by hpinkos** [comment]
Hello @eqmaster,  the `heightReference` property of polygons is meant for clamping extruded polygons to the globe surface: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Geometry%20Height%20Reference.html&label=Geometries

For your case, remove the `height` property and the `heightReference` property and the polygon should conform to the surface. 

```js
_entity.polygon = {
hierarchy : new Cesium.CallbackProperty(function(a,b){
let cartographicPosition = Cesium.Cartographic.fromCartesian(_entity.position.getValue(Cesium.JulianDate.now()));
let latitude = Cesium.Math.toDegrees(cartographicPosition.latitude);
let longitude = Cesium.Math.toDegrees(cartographicPosition.longitude);
let _a = [
longitude,latitude,
longitude*=1.0005,latitude*=1.002,
longitude*=0.9995,latitude*=0.997,
longitude,latitude
];
return Cesium.Cartesian3.fromDegreesArray(_a);
}, false),
material : Cesium.Color.GREEN.withAlpha(0.5),
outline : true,
outlineColor : Cesium.Color.BLACK
};
```

**Comment by eqmaster** [comment]
> Hello @eqmaster, the `heightReference` property of polygons is meant for clamping extruded polygons to the globe surface: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Geometry%20Height%20Reference.html&label=Geometries
> 
> For your case, remove the `height` property and the `heightReference` property and the polygon should conform to the surface.
> 
> ```js
> _entity.polygon = {
> hierarchy : new Cesium.CallbackProperty(function(a,b){
> let cartographicPosition = Cesium.Cartographic.fromCartesian(_entity.position.getValue(Cesium.JulianDate.now()));
> let latitude = Cesium.Math.toDegrees(cartographicPosition.latitude);
> let longitude = Cesium.Math.toDegrees(cartographicPosition.longitude);
> let _a = [
> longitude,latitude,
> longitude*=1.0005,latitude*=1.002,
> longitude*=0.9995,latitude*=0.997,
> longitude,latitude
> ];
> return Cesium.Cartesian3.fromDegreesArray(_a);
> }, false),
> material : Cesium.Color.GREEN.withAlpha(0.5),
> outline : true,
> outlineColor : Cesium.Color.BLACK
> };
> ```
thank you very much.
