### ISSUE TITLE
The camera rotates below the ground

### ISSUE THREAD

**Issue by ZhangGuangXin** [AnalyticalGraphicsInc/cesium#7741]
In cesium version 1.56.1,   camera. Lookat() function is used to rotate the camera around a target, but the camera rotates down to the ground.  I didn't use terrain, I used 3d tiles data.

Excese me, How to solve this problem?

![image](https://user-images.githubusercontent.com/8392363/56021766-d5543f80-5d3c-11e9-960d-cd572d824b2d.png)

**Comment by shortwavedave** [comment]
I think I have a similar issue - I registered it with the angular-cesium repo (https://github.com/articodeltd/angular-cesium/issues/262), but they think this is a cesium issue.

Intended outcome:

Draw corridors with terrain enabled

Actual outcome:

The corridors are misaligned and change with the view, the georeference of the corridor appears incorrect relative to the aerial image. If I disable terrain, then it works fine.

How to reproduce the issue:

create a map with terrain provider by cesium ion, e.g.:

```
export class MapLayerComponent {
  sceneMode = SceneMode.SCENE3D;
  MapLayerProviderOptions = MapLayerProviderOptions;
  arcGisMapServerProvider = MapLayerProviderOptions.ArcGisMapServer;
  @ViewChild(AcLayerComponent) layer: AcLayerComponent;

  constructor(private viewerConf: ViewerConfiguration, public appSettingsService: AppSettingsService) {
    viewerConf.viewerOptions = {
      selectionIndicator: false,
      timeline: false,
      infoBox: false,
      fullscreenButton: false,
      animation: false,
      shouldAnimate: false,
      homeButton: false,
      geocoder: true,
      navigationHelpButton: false,
      navigationInstructionsInitiallyVisible: false,
      baseLayerPicker: false,
    };

    viewerConf.viewerModifier = (viewer: any) => {
      viewer.screenSpaceEventHandler.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
      viewer.imageryProvider = new Cesium.createWorldImagery({
        style : Cesium.IonWorldImageryStyle.AERIAL_WITH_LABELS
      });
      viewer.terrainProvider = new Cesium.CesiumTerrainProvider({
        url: Cesium.IonResource.fromAssetId(1),
      });
      this.appSettingsService.showRoadsLayer = true;
    };
  }
} 

```
Create a corridor, e.g.:

```
  <ac-corridor-desc props="{
    name: entity.name,
    positions: entity.positions,
    width : 10,
    extrudedHeight : 100,
    height : 400,
    material : Cesium.Color.BLUE.withAlpha(0.1),
    outline : true,
  }">
  </ac-corridor-desc>
```

**Comment by OmarShehata** [comment]
Thanks for bringing this up - I believe this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/5837.

For @shortwavedave , it's hard to tell without seeing it, but I think this is an issue of depth testing against terrain being turned off. Please try turning it on with:

```
viewer.scene.globe.depthTestAgainstTerrain = true;
```

If that doesn't fix it, please open a new issue with a [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) code example of the issue.
