### ISSUE TITLE
czml   orientation.unitQuaternion 四元数 设置方向不起作用？

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7742]
Czml orientation.unitQuaternion setting direction does not work, how can I solve it?
This is my czml file：
[test.czml.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/3072530/test.czml.txt)

**Comment by GatorScott** [comment]
The first problem I see is that the epoch specified for the orientation does not match the epoch for the position.  Second, I'm not sure the impact when you have one point per day.

Please ask questions like this on the [forum](https://groups.google.com/forum/#!forum/cesium-dev).  Github is used to reports bugs and to make feature requests.
