### ISSUE TITLE
Mouse sticking

### ISSUE THREAD

**Issue by loshjawrence** [AnalyticalGraphicsInc/cesium#7747]
@bagnell @emackey  Not sure if the source of the mouse sticking issue is already known but you can reproduce it by clicking and dragging and keep dragging until the mouse goes off screen. When you move the mouse back on screen it still thinks it's pressed. It's not a full screen issue because of this, so it only happens in sandcastles. Could try triggering all mouse release events when the mouse goes off screen to fix these.

**Comment by hpinkos** [comment]
Duplicated #1855
