### ISSUE TITLE
How to Set Lines Not Obscured by Models

### ISSUE THREAD

**Issue by githubhanjunjun** [AnalyticalGraphicsInc/cesium#7748]
Not the desired result：
![image](https://user-images.githubusercontent.com/27795864/56177221-70486480-6030-11e9-89f7-81f30b4f9c63.png)

The result I want：
![image](https://user-images.githubusercontent.com/27795864/56177165-468f3d80-6030-11e9-9c7c-d041e713dca1.png)

**Comment by hpinkos** [comment]
Hello @githubhanjunjun, you can try setting a `depthFailMaterial` on the polyline:
```js
viewer.entities.add({
    polyline : {
        positions : ...,
        width : 5,
        material : Cesium.Color.WHITE,
        depthFailMaterial : Cesium.Color.WHITE
    }
}); 
```

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by githubhanjunjun** [comment]
Thank you very much for your reply, but I tried this method and did not achieve the desired results.
code:
![image](https://user-images.githubusercontent.com/27795864/56253316-6e44db00-60ee-11e9-84f0-1ac11784df93.png)
result:
![image](https://user-images.githubusercontent.com/27795864/56253342-87e62280-60ee-11e9-9bf6-6e41b04bf8d6.png)

**Comment by hpinkos** [comment]
Oh sorry, I forgot we had this limitation on dynamic polyline entities: #5333
