### ISSUE TITLE
the way don't need to differentiate 2d and 3d to draw polygons clamp to ground.

### ISSUE THREAD

**Issue by RenZachary** [AnalyticalGraphicsInc/cesium#7749]
In the issue https://github.com/AnalyticalGraphicsInc/cesium/issues/7740,the polygon clamp to groud when i remove the height and heightReference settings.

But when i set scenemode = Cesium.SceneMode.SCENE2D,the polygon can't be seen ,and the CallbackProperty is called.

I set height and heightReference both by use CallbackProperty to differentiate  the 2d and 3d.

Is any other easy way which don't need to differentiate 2d and 3d and the polygon clamp to ground?

the code:
```js
if(viewer.scene.mode === Cesium.SceneMode.SCENE2D){
                    _entity.polygon.height = 0.0;
                    _entity.polygon.heightReference = Cesium.HeightReference.RELATIVE_TO_GROUND;
                    _entity.polygon.extrudedHeight = 0.0;
                    _entity.polygon.extrudedHeightReference = Cesium.HeightReference.CLAMP_TO_GROUND;
                }else{
                    _entity.polygon.heightReference = Cesium.HeightReference.NONE;
                    _entity.polygon.extrudedHeightReference = Cesium.HeightReference.NONE;
                }
```

**Comment by hpinkos** [comment]
@RenZachary can you give me a code example to reproduce this issue?  This polygon renders fine in both 3D and 2D:

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var redPolygon = viewer.entities.add({
    name : 'Red polygon on surface',
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-115.0, 37.0,
                                                        -115.0, 32.0,
                                                        -107.0, 33.0,
                                                        -102.0, 31.0,
                                                        -102.0, 35.0]),
        material : Cesium.Color.RED
    }
});

viewer.zoomTo(viewer.entities);
```

**Comment by RenZachary** [comment]
> @RenZachary can you give me a code example to reproduce this issue? This polygon renders fine in both 3D and 2D:
> 
> ```js
> var viewer = new Cesium.Viewer('cesiumContainer');
> 
> var redPolygon = viewer.entities.add({
>     name : 'Red polygon on surface',
>     polygon : {
>         hierarchy : Cesium.Cartesian3.fromDegreesArray([-115.0, 37.0,
>                                                         -115.0, 32.0,
>                                                         -107.0, 33.0,
>                                                         -102.0, 31.0,
>                                                         -102.0, 35.0]),
>         material : Cesium.Color.RED
>     }
> });
> 
> viewer.zoomTo(viewer.entities);
> ```

in the link you given me:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Geometry%20Height%20Reference.html&label=Geometries
I replace the javascript ;
## Now the code
```javascript
var cesiumTerrainProvider = Cesium.createWorldTerrain();
var ellipsoidTerrainProvider = new Cesium.EllipsoidTerrainProvider();

var viewer = new Cesium.Viewer('cesiumContainer', {
    baseLayerPicker: false,
    terrainProvider: cesiumTerrainProvider,
    //when i set sceneMode: Cesium.SceneMode.SCENE3D,is OK
    sceneMode: Cesium.SceneMode.SCENE2D
});
viewer.dataSources.removeAll();
var geojsonStr = "\
{ \
    'type': 'FeatureCollection', \
    'features': [{ \
        'type': 'Feature', \
        'geometry': { \
            'coordinates': [111,30], \
            'type': 'Point' \
        }, \
        'properties': { \
        'ID': '1', \
        } \
    }] \
}";
var geojson = eval('(' + geojsonStr + ')');
Cesium.GeoJsonDataSource.load(geojson, {
    clampToGround: true
}).then(function(dataSource) {
    viewer.dataSources.add(dataSource);
    var entities = dataSource.entities.values;
    let _entity = entities[0];
    viewer.zoomTo(dataSource);
    _entity.polygon = {
        hierarchy: new Cesium.CallbackProperty(function(a, b) {
            let cartographicPosition = Cesium.Cartographic.fromCartesian(_entity.position.getValue(Cesium.JulianDate.now()));
            let latitude = Cesium.Math.toDegrees(cartographicPosition.latitude);
            let longitude = Cesium.Math.toDegrees(cartographicPosition.longitude);
            let _a = [longitude, latitude, longitude *= 1.0005, latitude *= 1.002, longitude *= 0.9995, latitude *= 0.997, longitude, latitude];
            return Cesium.Cartesian3.fromDegreesArray(_a);
        },
        false),
        //if i want see the polygon in 2d,i should set height and heightReference:
        //height : 0,
        //heightReference:Cesium.HeightReference.CLAMP_TO_GROUND,
        material: Cesium.Color.GREEN.withAlpha(0.5),
        outline: true,
        outlineColor: Cesium.Color.BLACK
    };
});
```

**Comment by hpinkos** [comment]
I just ran your code example and the polygon displayed in 2D for me:

![image](https://user-images.githubusercontent.com/3451886/56294994-0b594100-60fa-11e9-9400-6f3beecd87b6.png)

Are you using the latest version of Cesium?  What browser and OS are you using?

**Comment by RenZachary** [comment]
In another pc which the configuration is slightly better,it works. thank you!

My local cesium verision is 1.55,chrome version 70.0.3538 x64;

The os is a cloud operating system ,win 7 x64 ,memory size:8G, total available graphics memory : 16M.:astonished:

### In cesium 1.56.1:
![image](https://user-images.githubusercontent.com/3363381/56329656-0f976400-61b7-11e9-8197-ec0b8e83f3b0.png)
### in cesium 1.55:
![image](https://user-images.githubusercontent.com/3363381/56329598-da8b1180-61b6-11e9-8f1c-0e6d75a621ab.png)


when i set
```javascript
viewer.scene.debugShowFramesPerSecond=true;
```
the FramesPerSecond is 1 or 2 fps.:astonished:

Now I will upgrade my computer hardware.

**Comment by hpinkos** [comment]
@RenZachary yeah, this sounds like more of a hardware or graphic card support problem than a bug in Cesium.  If you see this issue on other devices, feel free to re-open this issue.  Best of luck!
