### ISSUE TITLE
About Video Material

### ISSUE THREAD

**Issue by wwaccount** [AnalyticalGraphicsInc/cesium#7752]
I want to clamp a video material to the terrain with slightly modifying the sandcastle example.As a result, the video material turns to be fragmented.
    Is there a solution that can help me to clamp the video to the terrian or change the video transparency as a substitution?
    It will be so grateful!!!!

**Comment by hpinkos** [comment]
@wwaccount this example works for me: [Cesium Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVRNj9s2EP0rhHtYG/BS35bkdYykiz0ESJrCWbQo6iCgJa7FhuKoJGVXCfa/dyTasXaDXAKEB4GceTNv3nCoA9PkIPiRa/KCKH4kt9yItqZ/DLbpVTEcb0FZJhTXV3PyZasILlPBccNVyfUbgOZOa9CGLMkDk4bPv0JaWb5SomaWo8/q9uyyXGtM+LuGg8AUyzNtoTli/wQty3sHmc626nF2s1VbdRhqLTncSV5zZbHiEoq239I9tyfrr93rcnplMVZivZdIdAnbYYyTS4ez4IayspyeRDUguz0orPVk6FcluGa6qLqnZoc3mANUr/zvUfdumba4YyqaXodRkgVRRrM4jWI/zII5uY7SOPbTkMZJnsQBnuYkRlSQZDRJgzhIkyhNZvOnZE/W98nSMAponIeYwl/4kWNLAj+iaZYtFn4YZMlA56d+SPM0SdNFuIh+lC7JA8zih6GfxNFZWxjn1A/zNM3ixGkLUToNEJJmWMoPS/MzzOvnSYIVLxwZlhBRpPTjLAvOncwXAc0WUYiCw3z24cL2OGLux1ILJvHyxmM1QhSSGSMeRMH6W77vmn6Mz7V946P3d5vNq9e/jRIYuwE7AC6Bb5mtqIUNK1GYmcbJzOEfL4PuJvQzQH0PUze4s5vJfLIytpN87fAvRd2AtqTVckqpZ3ndSFRkvF1bfOKWFsa4dD34l9ODGE/weXqXhO0MyNbym4tzB9ZCvSRp0vw3Mmuxr+yS+CPTUZS2WpIo9J8gK+6gQXaxo8SVd9aA+1IciChfbCfPfjPbiWs9eh5aKd+Lz3w7Wa88xK/HYRKwiWr/7sC1ZF0PqYL1G2eklK48PH4bZQHkjulRRvQOE3Dyu1ZhETX2pLfglrUWsL+dO0n857ldocEYwLYIdTKgCA3SDKfTVa0MtLrgxOgCzZW1jVl6nhP9j6Gg997Ab7z3TJUFM1Zybyf21/1V4kep7uOpKnrkuxppLA4c5hrCPGf7CWR1Ez/nGkw/gwoOz6n+bUXxyYqafyX8C/nITsPR4CiXwA1RYIlpm+El2IqTVQElXw/xK2/YE+7eNe2Hb3Bgsv8B)

If your video is transparent, you might be running into this bug: #4935

If you have any follow up questions, please ask on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
