### ISSUE TITLE
Add option to control event.preventDefault

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7757]
Cesium mouse click handlers will prevent the event from propagating by default:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/ScreenSpaceEventHandler.js#L171-L176

This is a problem if you don't want to handle all mouse interaction yourself, such as when you have any UI elements in your application.

[Forum post](https://groups.google.com/d/msg/cesium-dev/TwrIqRi8ZUk/XVVqb3QpCAAJ)

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dZFtT8IwEMe/SrM3jIR0Mb6TSSSIDwmKCQRfOGNKd0Bjd136METjd7fdJgrGvrrr/f+/u14rpkklYAuanBOELRmBEa6gi/ou7vA6HSm0TCDoTrefYYaVd20Y5vLYNuMaAGcl4zCuAO1NI4r3ZUCgnHmACaSWQQ3YWyydHXIrFMYrh01QqAoKj+mSjwyJP6FxoZyBB2VEkPj2LXvEtPURw1PKpULYm2nZakPHAOEKjZJApVrHB7Ag+Oz995b5rgQ6GV/NXy6nj/c/i1Bl8Bo/yVM7pYU3S85IZyg012xlOzX2qHitlcOcLGAjuIQgea6RM78Tzoz1A7I8nysll0zfAbq4bdTtR70oNXYnYdAgL0RRKm2J0zKmNLFQlJL5ZSRLx1/BUm7qbafJtynNRUVEfp5FR/+bRYRLZoyvrJyUM/EOWTRIE68/sEnFcoHraQVasl2QbE4Gk+aSUpomPv3rss1jfhG/AA)

Notice the dropdown doesn't work unless you remove the event handler, or comment out the `event.preventDefault` in ScreenSpaceEventHandler.js.

I think a minimal non breaking fix would be to just add an option to decide whether to call `event.preventDefault` when adding this event handler.

**Comment by mramato** [comment]
I haven't looked closely at this, but this feels more like a bug in how Sandcastle is creating the widgets and less like something we need to change in Cesium.  I'm not sure simple exposing the ability to avoid preventDefault is the best call here.

CC @emackey any thoughts there?

**Comment by hpinkos** [comment]
Related #3947

Also, we've had this discussion before.  See https://github.com/AnalyticalGraphicsInc/cesium/issues/4126#issuecomment-233334890

**Comment by OmarShehata** [comment]
I think this is particular case is false alarm, actually. Notice that the user is passing `Cesium.Scene.canvas` to the event handler constructor. This is undefined, so it adds the event listener to the `document`, not the canvas. That's why it captures clicks on HTML elements outside the canvas. If you swap that with `viewer.scene.canvas` it works fine. 

I think given that not calling `preventDefault` on canvas clicks will cause:

> ... the credit text and/or widgets would get the blue selection highlight every time you pan the globe.

https://github.com/AnalyticalGraphicsInc/cesium/issues/4126#issuecomment-278386527 

then it makes sense to keep this behavior, and the application developer can control the focus behavior as Ed suggests there. 

If you really do want to have greater control over what to do with the mouse event, you can always add your own event listener to the canvas directly since Cesium does expose the canvas to you.

We can close this.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/TwrIqRi8ZUk/XVVqb3QpCAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7757 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by cmcleese** [comment]
Is there a proper way to release the default mouse events from Cesium?
See Ex:
https://codesandbox.io/s/test-quasar-cesium-vue3-edjxls?file=/src/index.template.html
