### ISSUE TITLE
Why does increasing multiplier lead to faster stripe motion in conicSensor of stripesensor

### ISSUE THREAD

**Issue by ccmostmosthandsome** [AnalyticalGraphicsInc/cesium#7760]
First of all, I apologize for my poor English;
here my discovery:
After i load the czml with ConicSensor, the ConicSensor is ok at multiplier is 1;
when i try to increase multiplier, the ConicSensor motion fast at once.But i use stk for simulation, i increase or reduce the multiplier, the conicSensor motion not influenced. I see the czml,i thick i find the value influence this at conicSensor -> lateralSurfaceMaterial ->stripe ->offset->Number ,but i change this value is not achieve my wanted.
do you have a solution?

**Comment by hpinkos** [comment]
@ccmostmosthandsome `ConicSensor` is not part of the CesiumJS library.  If you have purchased a license for the Cesium ion SDK, please get in touch with our sales team and they will direct your question to someone who can help.  Thanks!
