### ISSUE TITLE
Globe size in portrait orientation

### ISSUE THREAD

**Issue by ptz-nerf** [AnalyticalGraphicsInc/cesium#7762]
Sandcastle example:  -

Browser: Chrome

Operating System: Windows 10

The size of the globe does not adjust to the screen size correctly. In some situations part of the globe falls behind the screen, this is especially noticeable in portrait orientation on mobile devices. How to fix this?
For example: https://i.imgur.com/OjpwlyD.jpg

**Comment by hpinkos** [comment]
@ptz-nerf I'm sorry, I'm having trouble loading the imgur link you attached.  Can you add the screenshot directly to this github issue instead?  Thanks!

**Comment by ptz-nerf** [comment]
Sure, this is a demo from the cesiumjs.org main page.
![image](https://user-images.githubusercontent.com/4808076/56429491-bb31d880-62cb-11e9-90d6-4a1d64533269.png)

**Comment by hpinkos** [comment]
Thanks @ptz-nerf 

To fix this, you can change the value of `Cesium.Camera.DEFAULT_VIEW_FACTOR`.  The default is 0.5, you can try setting it to a larger value, like `Cesium.Camera.DEFAULT_VIEW_FACTOR = 1.0;`.  Make sure you set this before creating the viewer.

In the future, please use the forum for questions like this: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
Thanks!

**Comment by ptz-nerf** [comment]
Thank you for pointing out!
`Cesium.Camera.DEFAULT_VIEW_RECTANGLE` fits better in this situation.
