### ISSUE TITLE
如何更改模型中心点位置？

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7764]
如何动态更改模型的中心点位置（X,Y,Z）
实现效果：当模型旋转时，围绕着不同的中心点位置旋转
![捕获1](https://user-images.githubusercontent.com/33933148/56492696-2d4e2b80-651f-11e9-9dc7-b199695d597e.PNG)

![捕获](https://user-images.githubusercontent.com/33933148/56492892-bf563400-651f-11e9-8f14-3bd0b03eaae7.PNG)

**Comment by emackey** [comment]
Cross-posted to KhronosGroup/glTF-Tutorials#26

**Comment by hpinkos** [comment]
Hello @HuZhuangQiang, the selection indicator centers around the `position` of the entity.  There isn't currently a way to customize this.  If you have a glTF model, you would need to re-position your model so the origin is at the location you wish the selection indicator to appear.

**Comment by HuZhuangQiang** [comment]
@hpinkos,必须重新转换成不同中心点的gltf 格式的多个模型吗？
