### ISSUE TITLE
measure line

### ISSUE THREAD

**Issue by developernavy** [AnalyticalGraphicsInc/cesium#7770]
The measured solid line is covered by 3DTile. Here is the code

 measureLength(){
    this.cancelVoid();
    //展示全局提示小窗口
    const mesID = this.message.info('当前功能：测量距离', { nzDuration: 0 }).messageId;
    var pointArr=new Array();
    var heightArr=new Array();
    var pointIndex=0;
    var alldistance:number=0;
    var viewer=this.cesiumService.getViewer();
    var scene=this.cesiumService.getScene();
    var isclick=false;
    this.height=0;
    this.length=0;
    this.allHeight=0;
    this.allLength=0;
    //显示距离dom
    this.isMeasure=true;
    viewer.scene.globe.depthTestAgainstTerrain = false;
    this.polylineCollection = scene.primitives.add(new Cesium.PolylineCollection())
    scene.primitives.raiseToTop(this.polylineCollection);
    var handler = this.cesiumService.getHandler();
    //var handler=new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
    //单击事件，画线测距离
    handler.setInputAction(click=> {

      //隐藏选中的框
      var selectionDivs= document.getElementsByClassName("cesium-selection-wrapper");
      // console.log(selectionDivs);
      // selectionDivs[0].classList.remove("cesium-selection-wrapper-visible");
      selectionDivs[0].setAttribute('style','visibility:hidden');

      //var clickX=click.position.x;//屏幕坐标
      //var clickY=click.position.y;
      isclick=true;
      var feature = scene.pick(click.position);
      if (!Cesium.defined(feature)) {
        // console.log("未选中3dtiles");
        return;
      }
      var cartesian;
      var height;
      if (scene.pickPositionSupported) {
        //cartesian = scene.pickPosition(click.position);
        cartesian = scene.pickPosition(click.position);
        if (Cesium.defined(cartesian)) {
          var cartographic = Cesium.Cartographic.fromCartesian(cartesian);
          height = cartographic.height;
        }
      }
      //初始点击位置画一个点
      if(pointIndex==0) {
        viewer.entities.add({
          name: 'FirstPoint',
          position: cartesian,
          point: {
            color: Cesium.Color.YELLOW,
            pixelSize: 5
          }
        });
      }
      //var cartesian = viewer.scene.globe.pick(viewer.camera.getPickRay(click.position),viewer.scene);//转换成世界坐标

      pointArr[pointIndex]=cartesian;
      heightArr[pointIndex]=height;
      //console.log(pointArr);
      //画已经点下的线
      if(pointIndex>0){
        //新建线元素
        var line= this.polylineCollection.add(
          {
            positions :[pointArr[pointIndex-1],pointArr[pointIndex]]
          }
        );
        //改变线的颜色，改成红色
        line.material.uniforms.color =new Cesium.Color(1,0,0,1);
        line.width=4;
        scene.primitives.raiseToTop(line);

        var tempLength=Cesium.Cartesian3.distance(pointArr[pointIndex-1],pointArr[pointIndex]);
        this.length=tempLength.toFixed(2);
        this.allLength+=Number(tempLength.toFixed(2));
        this.allLength=Number(this.allLength.toFixed(2));
        // var a=heightArr[pointIndex];
        //var b=heightArr[pointIndex-1];
        this.height=heightArr[pointIndex].toFixed(2)-heightArr[pointIndex-1].toFixed(2);
        this.height=Number(this.height.toFixed(2));
        //this.height=a.toFixed(2)-b.toFixed(2);
        this.allHeight+=Number(this.height.toFixed(2));
        this.allHeight=Number(this.allHeight.toFixed(2));
        // console.log(typeof (this.height));
        //this.height=(this.height).toFixed(2);
        //this.allHeight+=tempHeight.toFixed(2);
        //entity.label.text=alldistance.toString();
      }
      pointIndex++;
      //entity.position = cartesian;
      // entity.label.show = true;
      //viewer.zoomTo(viewer.entities);

    },Cesium.ScreenSpaceEventType.LEFT_CLICK);

    //先新建一个移动的线
    var moveLine=this.polylineCollection.add();
    // moveLine.material=Cesium.Material.fromType('Color');
    moveLine.material.uniforms.color=new Cesium.Color(0,0,1,1);
    moveLine.width=4;

    //移动事件，即时画直线
    handler.setInputAction(movement=>{
      if(isclick==false){
        return;
      }
      var feature = viewer.scene.pick(movement.endPosition);
      if (!Cesium.defined(feature)) {
        // console.log("未选中3dtiles");
        return;
      }
      var cartesian;
      var height;
      if (scene.pickPositionSupported) {
        cartesian = scene.pickPosition(movement.endPosition);
        if (Cesium.defined(cartesian)) {
          var cartographic = Cesium.Cartographic.fromCartesian(cartesian);
          height = cartographic.height;
          // console.log(height);
        }
      }
      scene.primitives.raiseToTop(moveLine);
      scene.primitives.raiseToTop(this.polylineCollection);
      var tempLength=Cesium.Cartesian3.distance(pointArr[pointIndex-1],cartesian);
      this.length=tempLength.toFixed(2);
      //this.height=cartesian-heightArr[pointIndex-1];
      var temp=heightArr[pointIndex-1];
      var tempHeight=height.toFixed(2)-temp.toFixed(2);
      this.height=Number(tempHeight.toFixed(2));
      moveLine.positions=[pointArr[pointIndex-1],cartesian];
    },Cesium.ScreenSpaceEventType.MOUSE_MOVE);

    //双击事件，首先画线测量距离，然后结束事件
    handler.setInputAction(click=>{
      //隐藏选中的框
      var selectionDivs= document.getElementsByClassName("cesium-selection-wrapper");
      //  console.log(selectionDivs);
      // selectionDivs[0].classList.remove("cesium-selection-wrapper-visible");
      selectionDivs[0].setAttribute('style','visibility:hidden');

      //var clickX=click.position.x;//屏幕坐标
      //var clickY=click.position.y;
      isclick=true;
      var feature = scene.pick(click.position);
      if (!Cesium.defined(feature)) {
        // console.log("未选中3dtiles");
        return;
      }
      var cartesian;
      var height;
      if (scene.pickPositionSupported) {
        //cartesian = scene.pickPosition(click.position);
        cartesian = scene.pickPosition(click.position);
        if (Cesium.defined(cartesian)) {
          var cartographic = Cesium.Cartographic.fromCartesian(cartesian);
          height = cartographic.height;
        }
      }

      pointArr[pointIndex]=cartesian;
      heightArr[pointIndex]=height;
      //console.log(pointArr);
      //画已经点下的线
      if(pointIndex>0){
        //新建线元素
        var line= this.polylineCollection.add(
          {
            positions :[pointArr[pointIndex-1],pointArr[pointIndex]]
          }
        );
        //改变线的颜色，改成红色
        line.material.uniforms.color =new Cesium.Color(1,0,0,1);
        line.width=4;

        var tempLength=Cesium.Cartesian3.distance(pointArr[pointIndex-1],pointArr[pointIndex]);
        this.length=tempLength.toFixed(2);
        this.allLength+=Number(tempLength.toFixed(2));
        this.allLength=Number(this.allLength.toFixed(2));
        // var a=heightArr[pointIndex];
        //var b=heightArr[pointIndex-1];
        this.height=heightArr[pointIndex].toFixed(2)-heightArr[pointIndex-1].toFixed(2);
        this.height=Number(this.height.toFixed(2));
        //this.height=a.toFixed(2)-b.toFixed(2);
        this.allHeight+=Number(this.height.toFixed(2));
        this.allHeight=Number(this.allHeight.toFixed(2));

      }
      pointIndex++;

      /////以下为cancelvoid方法，删除其中删除所有线段的部分。
      this.cesiumService.sendMessage(null);//关闭建筑物显示div
      //
      /*
      if(this.polylineCollection!=null)
        this.polylineCollection.removeAll();//删除所有线段
        */
      var handler=this.cesiumService.getHandler();
      var viewer=this.cesiumService.getViewer();
      this.cesiumService.resetHandler();
      viewer.scene.screenSpaceCameraController.enableRotate = true;//允许鼠标单击移动
      //  viewer.entities.removeAll();
      //  this.isMeasure=false;
      this.isAutoRotate=false;
      //ng-zerro的提示框
      this.notification.blank( '提示：', '测量结束',{nzDuration: 1000});
      this.message.remove();
    },Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK );
    //按下esc时监听，取消测量
    document.addEventListener("keydown",e=>{
      //console.log(e);
      if(e.key=="Escape"){
        this.cancelVoid();
        // handler.destroy();
        // viewer.entities.removeAll();
        // this.isMeasure=false;
        // scene.primitives.remove(linePrimitive);//清除上一次画的图形
      }
    },false);
  }

**Comment by OmarShehata** [comment]
@developernavy you can use the [classificationType](https://cesiumjs.org/Cesium/Build/Documentation/PolylineGraphics.html?classFilter=PolylineGr#classificationType) option to control whether the line is clamped to terrain, to 3D Tiles, or to both. 

If this doesn't help, can you put a code example in [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/), then click the "Share" button in the top and copy/paste that link here so I can run it? Adding screenshots of what you see vs what you expect would help determine if there is a bug or not.
