### ISSUE TITLE
如何获取Entity  modelMatrix ,并且重置modelMatrix

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7771]
通过 viewer.entities.add（）添加的entity ,如何获取 它的modelMatrix,并且重置modelMatrix。

**Comment by HuZhuangQiang** [comment]
@OmarShehata ,如果使用下面方式加载 ，如何使用 viewer.trackedEntity = entity;绑定模型
var model = scene.primitives.add(Cesium.Model.fromGltf({
  id:"entity",
    url : '../../../../Apps/SampleData/models/GroundVehicle/GroundVehicle.glb',
    modelMatrix : modelMatrix,
    scale : 200.0
}));

**Comment by hpinkos** [comment]
@HuZhuangQiang Entities do not have a `modelMatrix` property.  Instead, use the `position` and `orientation` properties: https://cesiumjs.org/Cesium/Build/Documentation/Entity.html#orientation
