### ISSUE TITLE
gltf  怎么保留透明材质？

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7772]
gltf  怎么保留透明材质？
   使用collada2gltf .exe  转换后，gltf 文件如何保留透明材质，如同obj2gltf   中的
   --checkTransparency选项，collada2gltf有什么方法可以保留透明部分

![捕获](https://user-images.githubusercontent.com/33933148/56654961-09781a80-66c4-11e9-8c1f-75f962409bf6.PNG)

**Comment by OmarShehata** [comment]
@HuZhuangQiang the `blendMode` on the material in the glTF needs to be set. See: https://docs.blender.org/manual/en/dev/addons/io_gltf2.html#blend-modes

This might be a better question to ask on the `COLLADA2GLTF` project or in the glTF forum: https://community.khronos.org/c/gltf-general
