### ISSUE TITLE
Polyline on Terrain in IE causes renderer to crash

### ISSUE THREAD

**Issue by carsnwd** [AnalyticalGraphicsInc/cesium#7775]
[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1Vdtb+I4EP4rvn5puGZdaLu6Cmh1bNvrId0WRNGuTstqZZKBWBfsyHag3Kr/fcdJDEmAtqe7L5cPJfE88+qx5+mSKbLksAJFroiAFbkBzdMF/ZStecdB9nkjhWFcgDr2yfeJIPgYUAqXhkoueQiq7RQDBczAZ6nicJxDvMZEPDc6EzERS/SmAxCAznKvNPtEYfZLQ5im88dIrn5TbAF6COoRAilCxBuVwsaIgsAwMY+hh+5QWDgfuWU6U3JxC3MFoL3Llk/OLn1yee6T86aNJIvDQPLI/4at9kdmImrkiIWcCe01abOVh12WazAjJkK5eEgXUxsehF7r/JccOEtFYLgUZA5mKDW379pruJpZtwFTRs4VSyIe6KLmPazT2jvLQnO4p1pcKnP6AcwKQHiV/OkKtPGrNaHAtCnbW/8De1qmJqobFFKZyFmcSUU8a5aj2WYHf7qkZX9PTjbZOs8mVaJnzbwYwbuyaNj/Nvh0N/o2/jzwyQGBC8U+T+TkimSAQGpv47BBft5scwm93qA1dudr6MqGfeEIOvuKmTy9DCEnpGVh6wL2bNvDviiwDl1SN6iJb0ycZx1btF7eDxWrNttn1/1zJVMRDmW8jvFQDhVfYKctoVOW3kileChVWbpP+x7kAoxa94XGzcbjjkF/+brX1EEoNv6efjhrNmsdYQGJOxYIrJ6SolKvhEeTVEde6aaqI7xS+80LGWmX77b7vR7KevbZBtrevvtVzIqHJkL5BW1uBc+NEooZo/g0xU1GWM1DIGMs2+bmvLGf9Wx6Tj/rjwzilfF0MOo93N/RFTdRL04i5rVos9EoRVP0X6Na34N7+h/Ut27731S29R6vYb9eN4WjaLxOoFw8t0Y/9sd3o7vb/8WGZEf6wHGuDuT7/SBX2/nO2Wy/dpKKomictgi247VYYUkCTFlMdV+dpSzP3gZUmu8Hrp69mbw9g4O9Ws1gxmLtUghipjWf8YDZ5qq1yo6MYsOMev2HTR45GZlXA9WUhaF3YLManTdo7RQm9/aIgzDAcY20BbFjKeMpUx9SY6TwjnEE2NGZFA418ibNpzzmZo1kzBGOLcc4EB/NinRFfnpJ3tkU4C0hBUU2bwxpJ/laSPvlnQp35AIlLHZDY0soanN0y/xoxv3sX7xJmniXOPpXmBooDshtC2ulLv0dcBaL+ZCbIBrJOK7YvXjvk3dn9mYizmSJzdIAuatilipaGu0aPESWxkXmql3PpGhbuY2mvSfCAgUiHOPJ0zh0F+0SPVL86YL2b+8exv3xn1ndjvyjrjbrGK5zzV/5IkEaR1IVe5SeGlgkMbJ1fTpNg7/A0EBnRKN76pS6IV8SHl5Njmr/CEyO8jOGklkax5YzTY6uu6eIr6jFMivjYAkqZmsLiVrXf+SLlNLuKX7uapm84UoWfwA)

The sandcastle from the Polyline on Terrain blog post here: https://cesium.com/blog/2018/07/23/polylines-on-terrain/

Browser: IE11

Operating System: Windows

It appears that it does not work on IE causing the renderer to crash.

```
An error occurred while rendering. Rendering has stopped.
TypeError: Unable to get property '_target' of undefined or null reference
TypeError: Unable to get property '_target' of undefined or null reference
   at UniformSampler.prototype.set (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:94053:9)
   at ShaderProgram.prototype._setUniforms (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:95370:13)
   at continueDraw (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:171970:9)
   at Context.prototype.draw (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:172007:9)
   at DrawCommand.prototype.execute (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:91119:9)
   at executeCommand (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239186:13)
   at executeCommands (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239427:17)
   at executeCommandsInViewport (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239963:9)
   at updateAndExecuteCommands (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239756:13)
   at render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:240396:9)
```

If there is anything to quick fix it, to at least get it running on IE that be great help to me 👍 . I'm looking into this for some of our code now and can update if I figure out anything in particular that causes it so IE at least doesn't crash the renderer.

Thanks!

**Comment by carsnwd** [comment]
#7103 

I believe it is related to this issue or the same issue?

**Comment by carsnwd** [comment]
Apologies, I cannot seem to consistently reproduce it on a sandcastle now.

**Comment by carsnwd** [comment]
Ah I believe it is just with the primitives API is the issue.

**Comment by carsnwd** [comment]
I see, I believe the issue is that due to limitations of WebGL on IE the polylines on terrain can't be supported?

**Comment by hpinkos** [comment]
@carsnwd, yes, IE does not support polylines on terrain.  You can check `Cesium.GroundPolylinePrimitive.isSupported` to determine if polylines on terrain are supported for the browser in which your app is running.

In the future, please ask questions like this on the forum:https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
