### ISSUE TITLE
scene _mode changes in the middle of flight

### ISSUE THREAD

**Issue by loshjawrence** [AnalyticalGraphicsInc/cesium#7781]
In trying to understand why the homemodelviewbutton specs breaks in preload-flights branch, it seems that _mode changes in the middle of the flight so it calls a setView for 3D mode on a 2D destination, and you get a normalized result not a number. The setView is at the end of the flyTo camera function where it sets the final destination view for the preloadFlight camera.

The spec that fails is `morphs to columbus view`. 

Test branch: preload-flights.

**Comment by loshjawrence** [comment]
Sean moved to cesium repo https://github.com/AnalyticalGraphicsInc/cesium/issues/7781

**Comment by hpinkos** [comment]
duplicate #4570
