### ISSUE TITLE
Polyline incorrectly depth testing with ellipsoid 

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7783]
This came up [on the forum here](https://groups.google.com/d/msg/cesium-dev/55A-G1MH9Ds/oSNeATwBDQAJ). 

In [this Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVJNb9swDP0rgi+1kYx2tvWSOEG7NNhhHRqg3YBh3kGxmUSYLBmUbCMb8t9L56vOpovI9/j0KEqNJNEobJHEVBhsxRydqkv4fsDCm/yQzq3xUhmkm2iSmcwcFeByNAgbbVcIBVZ++4LO32+40vkXJOJg6qnGg0Y0bFVZp7yyxrHbz1+Mry2JsGMUI8mEt1R85H0wUJH4yypeFxFUtduGpw7nkjxH0nyANdnyATeE6MJ3oySBRAyEGorRLSRR1/G+1zQaz6ehA1kU4cVB7zTfT4zPnle+DF/i4RvfqsJvmRuxYQ8upUdSUjPTG+jyZPFZ2/brqWJJtkLyu7Bn2q3cah7L+Cyddyk8LBbL5y8/Pj1+Wwyvy/kB2qXtnnAsEnh/+8buo2PM999Hk2AYpM7vNM6O6J0qK0te1KRDgNhjWWnuzMWrOv+NHnLnuuGl8VmUFqoRqphmwT/fIgtErqVzzKxrrZ/VH8yCWRpz/ZVMW1kos3lqkLTcdSXb0ezxCAJAGnP6v8pbq1eSeie+Ag) this polyline seems to be incorrectly depth testing with the ellipsoid.

Here's what it looks like zoomed out:

![poly1](https://user-images.githubusercontent.com/1711126/56813056-35051d00-680a-11e9-8ffd-af35934bf4ea.png)

If you zoom in a bit:

![poly2](https://user-images.githubusercontent.com/1711126/56813066-3a626780-680a-11e9-97c4-c9d496df36ae.png)

But if you tilt the camera it looks fine:

![poly3](https://user-images.githubusercontent.com/1711126/56813083-41897580-680a-11e9-866d-1a3258f9c1d6.png)

There are lots of workarounds to this:

* Set `clampToGround: true`
* Adding a height of at least 1000 to the polyline points
* Turning off `viewer.scene.globe.depthTestAgainstTerrain`

@likangning93 mentioned it would be good to open an issue to investigate this since it's unclear that it's depth testing against here (this is just on the ellipsoid, on terrain). Gary, can you add the appropriate labels?

**Comment by wallw-bits** [comment]
[This forum post](https://groups.google.com/forum/#!topic/cesium-dev/UvLaAr8VnRA) may be related, but in that case neither zooming/rotating the camera, setting heights on the points, nor toggling `scene.globe.depthTestAgainstTerrain` seems to help.

**Comment by OmarShehata** [comment]
@wallw-bits this may be a different issue, since the Sandcastle above is fixed when `clampToGround: true`, which uses a `GroundPolylinePrimitive` under the hood.

In [your Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=fZTRbtowFIZfJeKmicScOLHjmNFqiFZdpUqt1GrVNHbhJgasGRvZDhWbePc5QLpAYeaC2Of/fh/bR2fFTLAS/I2b4DJQ/C0YcyvqBfi2XQsvyu10rJVjQnFz0Q/+TFTgh+PG+KVHo1ei4mbQgqXhzPEXbWT1vJOE0URtos8T1fz2qluja1U9armW3vbRiIVwYsWBUP6fSfGb7+GvXMzmzoYRcHOuwmmtSie092zz2CUPbMkVB7OdbWtnAauqsHOqM9uGe69mMLtW5dxopWs7CKZMWt7vRJdLzgxTJR90b6t1HGupzehdE0YddMb1gjuzvlPWNUF74HB7FO2m1KUPoYPjtBbHaDOW2orm3uz7O42Zcf6LqQxMjV5c85nh3I78pa/DHx8NmvEJwgykBCeQYooSWmDcD7IEJBhjlBSIwIxQkvfP0QkFRZKlEOYE0QIiD+cgQxghmEIKUZoW51kMSEoSRCHNcEZyvzNKAYYpxoQWWZGT/7AJICT1O3seUm/j2QL4FGiRe7siJQiegykCOM1yf6zCp+m1/QAj4M9Ac0IgyVGGaP6R/RmdMIzjmS+LWjIjnH9ISk9omCmf10v+/kyj3Rzc3jxc3zzdjU8gb6Jy80GADiOb4wyYc0a81q4pvBMVUjale1Bd22I+rstR67Ktmq0k7OrB95v7+4eX6CiZf9PNPrSJmpbg+0Kv3xtat5b8ahf4IhZLbVxQGxkCEDu+WErfUWz8Wpe/uAOltQ05jFtoWIlVIKrLSe+oWU16QSmZtT4yraV88l1l0rsaxl5/gEnNKqFmDytuJFs3kjm8ut8tAgCGsZ9+pJzW8pWZjuNf) the issue occurs when using the GroundPolylinePrimitive. It seems like there are these large gaps that don't depend on the camera direction, that occur in specific parts in the terrain:

![bad_castle](https://user-images.githubusercontent.com/1711126/57334194-0d0c9800-70ed-11e9-8687-b600d9b8432f.png)

If you lower the granularity to 99, it fixes these gaps:

![fine_castle](https://user-images.githubusercontent.com/1711126/57334234-2d3c5700-70ed-11e9-90bb-1d0cadb72286.png)

**Comment by hpinkos** [comment]
This is working as expected.  When a polyline is not clamped to ground, the segments between the positions are drawn as straight lines, and they do sink slightly into the ellipsoid surface.  Instead, use clamped polylines.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/55A-G1MH9Ds/oSNeATwBDQAJ
https://groups.google.com/forum/#!topic/cesium-dev/UvLaAr8VnRA

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7783 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
