### ISSUE TITLE
3D Tiles loading infinite loop

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7786]
The AWS Lumberyard Bistro tilesets will constantly load and unload tiles in an infinite loop with a status view from inside the Bistro:

![Peek 2019-04-26 21-06](https://user-images.githubusercontent.com/1495196/56842766-4892a100-6867-11e9-8b6d-0d965ca79db6.gif)

CC @lilleyse @loshjawrence

**Comment by pjcozzi** [comment]
Good catch!!! 👀

**Comment by loshjawrence** [comment]
D'oh, I'll get on it.

**Comment by mramato** [comment]
FYI, this may only happen when `requestRenderMode` is enabled, or at least it's much easier to reproduce with it on.

**Comment by loshjawrence** [comment]
There's a simple fix of putting the cache calls back to where they were (need to understand why it works and integrate into the pass-invariant code style that we have now). There also seems to be interactions with between requestRenderMode and motion based request culling (time gating, cull requests while moving), which will either involve disabling these features when this mode is on or having latch-like logic to make sure it gets everything.
