### ISSUE TITLE
How to get location information of Cesium3DTileFeature

### ISSUE THREAD

**Issue by xiaobaogeit** [AnalyticalGraphicsInc/cesium#7788]
I can't access Google, so I'm going to ask questions here.Sorry for the inconvenience.

**Comment by xiaobaogeit** [comment]
This object does not have any location information

**Comment by OmarShehata** [comment]
CesiumJS doesn't store the feature positions once loaded into the viewer. For tilesets that do need per-feature position info, you could use a property stored in the batch table. This is how the "zoom to feature" works here:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Interactivity.html

Here's the relevant code snippet:

```
// feature is a Cesium3DTileFeature
var longitude = Cesium.Math.toRadians(feature.getProperty('longitude'));
var latitude = Cesium.Math.toRadians(feature.getProperty('latitude'));
var height = feature.getProperty('height');
```

**Comment by digiiitalmb** [comment]
how can I get origin position of the tileset?

**Comment by jougisljs** [comment]
let entity = viewer.entities.add({
        position:features['02fcf87d7e0a9c73d5cb511f8bae4ba4'].tileset.boundingSphere.center,
        billboard: {
            image:'./location.png',
            horizontalOrigin:Cesium.HorizontalOrigin.CENTER,
            verticalOrigin:Cesium.VerticalOrigin.BOTTOM
        }
    })
    features['02fcf87d7e0a9c73d5cb511f8bae4ba4'].color = Cesium.Color.RED;
    viewer.zoomTo(entity);
