### ISSUE TITLE
how can i get more ion resources

### ISSUE THREAD

**Issue by AJJackGIS** [AnalyticalGraphicsInc/cesium#7794]
how can i get more ion resources, the default access token has only few resources, i'm learning examples from Sandcastle APP, but the majority i can't get the whole page

**Comment by OmarShehata** [comment]
@AJJackGIS , what kind of resources are you looking for? We are actively working on adding more datasets available through the ion asset depot, but I'm curious to know if there's a specific type of data you're hoping to see more of.

**Comment by OmarShehata** [comment]
I'm going to close this issue but feel free to post a follow up question on the ion-community repo (https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues) or on the forum (https://groups.google.com/forum/#!forum/cesium-dev)!

**Comment by AJJackGIS** [comment]
we are working on 3dtiles application, recently i was learning 3d tiles demos in the Sandcastle Gallery , for example , 3D Tiles feature picking, 3D Tiles photogrammetry classification and so on, how can i get this kind of resources. thanks!!
