### ISSUE TITLE
glTF 2.0 'OPAQUE' mode broken

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#7795]
When `alphaBlend` mode is set to `OPAQUE`, glTF 2.0 specifies that source alpha values will be _ignored_, not pre-multiplied.  There is a test model to check this: [AlphaBlendModeTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest).

This was broken recently.  I ran `git bisect` on this, and I'm sorry @OmarShehata, it narrowed this down to one of your image handling commits here:  b772d527599c78796 (part of #7579).

**Comment by emackey** [comment]
Here's a screenshot of the model just prior to the problem, in parent commit 96cbc181262b0cacb:

![AlphaBlendCorrect](https://user-images.githubusercontent.com/1235080/56979899-e7115180-6b48-11e9-8c60-2d75860a59be.png)

And here's what happened in b772d527599c787968ba:

![AlphaBlendPreMultiplied](https://user-images.githubusercontent.com/1235080/56979903-eaa4d880-6b48-11e9-89d4-c7ad805e272d.png)

Typically this means that the alpha values are being pre-multiplied, when they should be ignored.

**Comment by emackey** [comment]
It looks like the strength of the blending has noticeably changed in the `Blend` test here too, on that same commit.  I don't know if that's as well defined in glTF, but most viewers treat the alpha channel closer to what's shown in the first screenshot.

**Comment by OmarShehata** [comment]
Thanks for tracking this down @emackey ! Looks like this is indeed an ImageBitmap issue. One of the major issues with implementing it was that an ImageBitmap cannot be flipped during texture upload. It looks like premultiplied alpha is another setting that would need to be done passed on image decode to get ImageBitmap to work correctly.

Here's [my local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=vVRNb9swDP0rQi5xAVd2mrTd2rRYv4YNWLGuCXZZdlAsJhYmS4Ykp8mG/PdRcj5ctxiwSwUfJOqRfHwivWCGLAQ8gSEXRMETuQErqoJ+D7aom4XjjVaOCQWmG5M/E0VwCTXT13pJzsiMSQtxbbUgIXNCq8+Ki4w5bdqAnHH9ZNHqTLU36kryKyUK5mBzNVHrg/OJmqhZpUJEkhnA63vNQUaVkTHJQcxzd7BlVJdBQTnhBFhqoNALuJIyqgMFDJZbaitCwIttsTfMONwx1aczo4tbmBsAGx32jvo0PR0MTnrvYzIY0PQ47Z+mJ7vM5/ugOTAu1Hwf8565nDr9iGambNTrHzfhpXBZjuC0YTNaypYpL1vP8qlO8+DdHxEfbfLGdcQ4BGkm0kagIOx5vWODlGbaFJbmrYDfKtTYKIRHW51iT+O5hEHjFQZsa844jzbP4ZdihX9P/1p7407/s922cdskfNY8NTCF7wG8bWTyqzLiRbIAF9hZVfEgliBH4rdn1Dt61waxpQeNMiY94CjFtUes6+16J21dtzMs+wX8bitHrQti1l6toH/puVu8+7Fh62DpMEF3LscfuxsSiAiD44dl0+7RQbO8Zu93KU3wG7GilHDLHEuCHja5kmXOriUo7oFjsC7xSV6x07l0M5zlYyySptuikPR6N99NmuRaKGZWb8L2sM71Ounpf3C+K6bAOfC3Yb3N9g+xey+I/wxDNWKKZ8w6CX58xlrLKTP3oKpo0zzepRN3htatJFzW7h9EUWrjfLdHSNQBEkX2NplW2JGOZja4DZOt05CLBRH8YtJp/dInHZJJZi3ezCoZBmTSuRwmiH/mJnX4U3xdgJFs5SF57/JLbaSUDhM8vvRydTmNiH8B). This expects the `AlphaBlendModeTest` folder from the glTF sample models repo to be copied to `Apps/SampleData/models/`. 

Changing Resource.js:1894 to:

```
Resource.createImageBitmapFromBlob = function(blob, flipY) {
        return createImageBitmap(blob, {
            imageOrientation: flipY ? 'flipY' : 'none',
            premultiplyAlpha: 'none'
        });
    };
```

Fixes the issue. This potentially impacts imagery as well.

**Comment by OmarShehata** [comment]
@lilleyse I can't seem to find any logic when loading a glTF to set premultiplyAlpha. It seems to just always be false? Or to be based just on the given pixel format.

**Comment by emackey** [comment]
I think "always false" might be correct, particularly if the BLEND side of the test model continues to work.
