### ISSUE TITLE
Lighting issues with glTF rendering

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7800]
Check out the `Milk Truck` and `Draco Compressed Model` options in our 3D Models demo: 

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Models.html

The Milk Truck seems overly dark no matter what time of day it is, this is the brightest I could get it, but maybe this is correct?

![image](https://user-images.githubusercontent.com/1495196/57018008-9e60a380-6bef-11e9-9e77-217d19216fee.png)

Meanwhile, the Draco compressed version of the same model is super washed out:

![image](https://user-images.githubusercontent.com/1495196/57018037-b9331800-6bef-11e9-9baa-54dea87f22fb.png)

I also just noticed the "fuzzy" Cesium logo on the hood.

Why do these two models look so different?

@lilleyse or @likangning93 any thoughts here?

**Comment by lilleyse** [comment]
The first is glTF 1, so we can't really do much about the lighting except to upgrade our sample models to glTF 2, and the second is glTF 2 / PBR and IBL seems too strong.

**Comment by mramato** [comment]
I actually just wrote up #7802 before you made this comment.  We need to put our best foot forward and to me that means glTF 2.0.

**Comment by lilleyse** [comment]
Opened https://github.com/AnalyticalGraphicsInc/cesium/issues/7803 for making the lighting look better.

**Comment by mramato** [comment]
This has 2 more specific issues to deal with the problem described above.
