### ISSUE TITLE
Upgrade all SampleData models to gltf 2.0

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7802]
Looks like there are several glTF 1.0 models still being shipped with Cesium, since almost no one else supports glTF 1.0, we should make sure everything we ship uses 2.0.  We probably also want to revisit how many different versins of some models we have and perhaps more cleanly label some of the files/folders.

Might be a good idea to make everything glb as well.  This is sample data, not test data so we should treat it like we were shipping production-ready models.

**Comment by lilleyse** [comment]
@sanjeetsuhag for testing...

* Verify that all Sandcastle examples that use these models still look correct after the models are switched over to glTF 2.0. This includes the Shadows demo in the Development folder.
* Verify that all sample models, including ones that are already 2.0, pass the [glTF validator](https://github.khronos.org/glTF-Validator/).
* Make sure that unit tests pass. You can either run `npm run test` or go to `http://localhost:8080/` and click `Run all tests`

**Comment by lilleyse** [comment]
Also...

* Remove `CesiumMilkTruck-kmc.glb`. Any Sandcastle examples that use that can use the regular glTF 2.0 `CesiumMilkTruck.
