### ISSUE TITLE
Problems are displayed when part of the model is above ground and part is underground

### ISSUE THREAD

**Issue by xiaobaogeit** [AnalyticalGraphicsInc/cesium#7813]
When one part of the model is above ground and the other part is underground, pulling a long distance will cause the underground part to surface above the ground。

viewer.scene.globe.depthTestAgainstTerrain = true;
Can solve the problem of floating up, and then use the base profile to see the underground, but this is not a good underground mode, is there a good underground mode API?

**Comment by OmarShehata** [comment]
Underground rendering is certainly a feature we'd like to add support for but haven't gotten to yet. There's an issue here https://github.com/AnalyticalGraphicsInc/cesium/issues/5665 discussing it. Feel free to add your thoughts there. It would be great if you can include a screenshot or a Sandcastle of what you're seeing to make sure this is a use case that's covered when we implement this feature.
