### ISSUE TITLE
Error loading ImageBitmap for Cesium3DTileset

### ISSUE THREAD

**Issue by xiaobaogeit** [AnalyticalGraphicsInc/cesium#7814]
No problem at 1.55;

Error Message:
 A 3D tile failed to load: http://../**.b3dm
Cesium.js:507 Error: Failed to load image: id: 3419, bufferView: 18
The ImageBitmap could not be allocated.

Sandcastle example: 
var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(Cesium.Cartesian3.fromDegrees(longitude, latitude, height));
var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
	    url : 'http://..../tileset.json',
            modelMatrix: modelMatrix
        }));
Browser: Google Chrome 版本 74.0.3729.131（正式版本） （32 位）
Cesium:1.57  
Operating System: win10

**Comment by OmarShehata** [comment]
Thanks for reporting this @xiaobaogeit ! Are you able to share your tileset so we can reproduce and fix this issue?

**Comment by xiaobaogeit** [comment]
This [tileset](https://github.com/xiaobaogeit/model/blob/master/tiles.zip) will work fine in the latest version of firefox, but it will be very memory-intensive and will have poor performance.
[Tilset](https://github.com/xiaobaogeit/model/blob/master/tiles.zip) address is as follows:
https://github.com/xiaobaogeit/model/blob/master/tiles.zip

**Comment by OmarShehata** [comment]
@xiaobaogeit I'm not able to replicate a crash a with this tileset on the latest CesiumJS. Are you saying this tileset has poor performance in 1.57 but has good performance in 1.55?

Can you test the crash in Firefox and copy/paste the error you get from there? Or does this only happen in Chrome?

**Comment by xiaobaogeit** [comment]
@OmarShehata 
Operating System: win10 Pro (x64)
1、Firefox latest version of the rendering is no problem, but eat memory.
![Firefox Rendering](https://user-images.githubusercontent.com/19976188/57343273-3a048d80-7175-11e9-8124-2f4830c77a4e.PNG)
![Firefox Performance](https://user-images.githubusercontent.com/19976188/57343355-a2536f00-7175-11e9-8990-9cf19e6bf3bc.png)
2、In version 1.57, Google renders an error and eventually the page crashes.
Error Message:
A 3D tile failed to load: http://../tiles/he_1_0.b3dm
Cesium.js:507 Error: Failed to load image: id: 3319, bufferView: 16
The ImageBitmap could not be allocated.
Browser: Google Chrome 版本 74.0.3729.131（正式版本） （32 位）
3、For version 1.55, after multi-machine test, whether can render out depends on the performance of the computer, but 1.57 are not rendered out.
4、I only tested Google and firefox
