### ISSUE TITLE
Image layer rendering very dark

### ISSUE THREAD

**Issue by JackD83** [AnalyticalGraphicsInc/cesium#7815]
In our app we switch between OpenLayers for 2D rendering and Cesium for the Globe. We noticed some differences in the rendering of image layers. In cesium, image layer appear much darker and with less contrast. 

Its easy to reproduce:
Open the basic sandcastle and go to a city with high res bing imagry. e. g. New York
In another browser window, go to https://www.bing.com/maps and open the same extent on bing maps. Compare them side by side on the same display. 

![cesium_dark](https://user-images.githubusercontent.com/15889805/57225309-45887500-700c-11e9-89f4-18a5c8364563.png)

Cesium 1.57 
Chrome 74.0
Firefox 66.0.4

**Comment by hpinkos** [comment]
@JackD83 try setting `scene.highDynamicRange = false` and let me know if that fixes the issue.  We have a few post process effects enabled by default that are meant to make the globe look nicer, but may be different than what you want for your specific app.

**Comment by JackD83** [comment]
That does indeed fix this error. Thank you! 
I'm not sure if "highDynamicRange" is the right name, maybe postProcessing would be better. The rendered image does not look like HDR

**Comment by hpinkos** [comment]
@JackD83 `highDynamicRange` is the correct name for this.  We have a separate `Scene.postProcessStages` for other post processing effects.  But I'm glad that fixed your issue!
