### ISSUE TITLE
Double-render in Globe.render

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#7816]
`Globe.render` appears to call `surface.render` twice with the same framestate. 
Mentioned this to @bagnell on Friday and he said he wanted to look into it.

https://github.com/AnalyticalGraphicsInc/cesium/blob/a35f0109a5ef126c3dfda66f9f0dc57af3a13d49/Source/Scene/Globe.js#L790-L796

Found via static code analysis.

**Comment by emackey** [comment]
Not high priority, since those two passes are mutually exclusive.  But looks easy to simplify with something along the lines of `if (pass.render || pass.pick)`.
