### ISSUE TITLE
Imagery stops being requested.

### ISSUE THREAD

**Issue by jfrancis537** [AnalyticalGraphicsInc/cesium#7817]
After updating to the latest version of cesium I noticed that imagery will stop loading, http requests for the imagery are no longer going out. 

I did notice that my event handler on my imageryProvider.errorEvent is no longer being called in 1.56.1+ vs 1.55 "throwing" a tile not found error. 

Environment Details:
Our imagery is incomplete, we are missing various sections.
Our environment is offline.

Works Correctly in: Cesium 1.55
Version:  Cesium 1.57 and 1.56.1

**Comment by hpinkos** [comment]
@kring any ideas here?

**Comment by hpinkos** [comment]
@jfrancis537 Do you also see this issue in Sandcastle? https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/
If not, can you please put together a code sample to reproduce this?  Thanks!

**Comment by jfrancis537** [comment]
I can't find a way to reproduce it in Sandcastle because I don't have an imagery set located outside of our closed network, but I think I found the source of the issue / a workaround.

We use a UrlTemplateImageryProvider which makes a call to the server which would look up the image on the filesystem and return it as Content-Type jpeg. 
it looks somewhat like this:
```
let imageryProvider = new Cesium.UrlTemplateImageryProvider({
 url: Cesium.buildModuleUrl("/endpoint/{somecustomtag}"),
 customTags: {
     someCustomTag: function() {
       ...doSomething
    }
 }
});
```

Given that our imagery is incomplete, if the image doesn't exist, we return an HttpResponse with a status code of 204 No content. Once one of those is received in the browser, the imagery stops loading.

However If the status code is changed to 404, the imagery continues to load as expected.

**Comment by jfrancis537** [comment]
It doesn't appear as though the actual content matters. Returning a 200 with a text/plain, still works as expected.

**Comment by kring** [comment]
That's very odd, I can't think of why a 204 would be different from an invalid-image 200. Is there a proper `Access-Control-Allow-Origin: *` header in the response in both cases?

**Comment by jfrancis537** [comment]
Not likely, the web server and imagery server are the same host.

**Comment by OmarShehata** [comment]
@jfrancis537 just to rule out ImageBitmap as the culprit, can you add the snippet in https://github.com/AnalyticalGraphicsInc/cesium/issues/7735 at the top of your code before requesting any imagery and see if the issue still happens?

**Comment by jfrancis537** [comment]
Adding that snippet resolves the issue.

**Comment by OmarShehata** [comment]
@jfrancis537 can you check if this issue is still present with the latest CesiumJS? I made a fix here https://github.com/AnalyticalGraphicsInc/cesium/pull/7914 that might have resolved this.

**Comment by jfrancis537** [comment]
Yep, it fixed it.
