### ISSUE TITLE
About 3dtile rendering mode

### ISSUE THREAD

**Issue by verybigzhouhai** [AnalyticalGraphicsInc/cesium#7820]
Hi，
    Whether cesium 3dtile supports the rendering effect shown in Figure 2, Figure 1 is the original display effect.
![image](https://user-images.githubusercontent.com/37999729/57269011-61e1eb80-70b8-11e9-8b58-dda1f2fdf772.png)
![image](https://user-images.githubusercontent.com/37999729/57269017-65757280-70b8-11e9-9af4-32bda7dcd0c9.png)

thanks！

**Comment by hpinkos** [comment]
Hello @verybigzhouhai, please ask your question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
Someone there should be able to help you.  We use GitHub exclusively for tracking bugs and planning new features.  Thanks!
