### ISSUE TITLE
Something's wrong with imagery or terrain

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7825]
I had just the regular [Hello World Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) up and walked away from my computer for 5 minutes, and when I came back it looked like this.

![wtf](https://user-images.githubusercontent.com/3451886/57384271-49d49f80-717e-11e9-9d06-d89017546982.gif)

**Comment by mramato** [comment]
@hpinkos can you regularly reproduce this?  No one else seems to have ever hit this.

**Comment by hpinkos** [comment]
@mramato I haven't tried to reproduce it
