### ISSUE TITLE
Geometry texture coordinate incorrect in v direction

### ISSUE THREAD

**Issue by HOUWEI** [AnalyticalGraphicsInc/cesium#7828]
This is my code to construct a geometry with textrue
```html
              var mypositions =  Cesium.Cartesian3.fromDegreesArray([60.0, 20.0, 120, 20, 120.0, 40.0, 60, 40]);
              var numPositions = mypositions.length;

              var pos = new Float64Array(numPositions * 3);
              for (var i = 0; i < numPositions; ++i) {
                  pos[i * 3] = mypositions[i].x;
                  pos[i * 3 + 1] = mypositions[i].y;
                  pos[i * 3 + 2] = mypositions[i].z;              
              }

              var uvs = [0, 0, 1, 0, 1, 1, 0, 1];
              var indexs = new Uint16Array([0, 1, 2, 0, 2, 3])

              var geometry = new Cesium.Geometry({
                attributes: {
                    position: new Cesium.GeometryAttribute({
                        componentDatatype: Cesium.ComponentDatatype.DOUBLE,
                        componentsPerAttribute: 3,
                        values: pos
                    }),
                    st: new Cesium.GeometryAttribute({
                      componentDatatype: Cesium.ComponentDatatype.FLOAT,
                      componentsPerAttribute: 2,
                      values: uvs
                    })
                },
                indices : indexs,
                primitiveType: Cesium.PrimitiveType.TRIANGLES,
                boundingSphere: Cesium.BoundingSphere.fromVertices(pos)
            });

            var myInstance = new Cesium.GeometryInstance({
                geometry: geometry,
            });
          
            viewer.scene.primitives.add(new Cesium.Primitive({
                geometryInstances: myInstance,

                appearance: new Cesium.MaterialAppearance({
                    material : new Cesium.Material({
                      fabric : {
                          type : 'Image',
                          uniforms : {
                              image : './Cesium_Logo_Color.jpg'
                          }
                        }
                    })
                })
            }));
```

everything goes well，geometry build right
![image](https://user-images.githubusercontent.com/1874882/57528546-33d50380-7365-11e9-920f-4ae09d38c371.png)

then I change my texture coordinte
```html
var uvs = [0, 0, 2, 0, 2, 2, 0, 2];
```
it shoud be repeate two times in both u and v direction，but texture just repeate two times in u direction
![image](https://user-images.githubusercontent.com/1874882/57528810-e0af8080-7365-11e9-9ed1-69d01aee5d9e.png)

**Comment by hpinkos** [comment]
@HOUWEI texture coordinates should be between 0 and 1.  You're seeing unusual behavior because 2 is outside the expected range. 

In the future, please use the forum for questions like this: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We just GitHub exclusively for tracking bugs and planning features.  Thanks!

**Comment by emackey** [comment]
I'm not so sure about this.  Why wouldn't repeated textures be allowed?  The screenshot looks like it does have a small rendering error, even in the single-tile version.  Notice the bottom-left edge of the "E" has a kink in it, in the first screenshot.  If you draw a diagonal line from the upper-right to lower-left vertex, the texturing is distorted along that line.

There must be a name for this effect, but I can't put my finger on it.  It comes from the fact that rasterized polygons are triangular, while images (and UV space) are inherently rectangular.  Imagine a correctly textured quad, if you were to move any one corner, the entire texture should stretch when pulled by that one corner -- including parts of the texture that were in the other trangle of the quad, the one whose vertices didn't move.  I can't seem to think of the name of this and some quick Googling didn't turn up a relevant link for me.

In any case, the easiest workaround is to add more vertices to the triangle mesh.  Not sure if there's a quick way to do that via the API here, may want to ask on the forum.
