### ISSUE TITLE
xhtml support

### ISSUE THREAD

**Issue by supipd** [AnalyticalGraphicsInc/cesium#7832]
Please consider support for XHTML ... in my opinion auto-html-code-generation  CAN and MUST generate valid (X)HTML code.
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" 
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:svg="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink" 
  xml:lang="en">
<head>
  <meta charset="utf-8"/>
  <script src="https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js"></script>
  <link href="https://cesiumjs.org/releases/1.57/Build/Cesium/Widgets/widgets.css" rel="stylesheet"/>
</head>
<body>
  <div id="cesiumContainer" style="width: 700px; height:400px"></div>
  <script>
    Cesium.Ion.defaultAccessToken = 'XXX...XXX';
    var viewer = new Cesium.Viewer('cesiumContainer');
  </script>
  </body>
</html>

```

Cesium.js:530 Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at new _ (https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:509:27882)
    at new Me (https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:522:5393)
    at new x (https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:530:2562)
    at new te (https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:532:23878)
    at http://localhost/GIS/cesiumFight/firstApp.xhtml:26:18
x @ Cesium.js:530
te @ Cesium.js:532
(anonymous) @ firstApp.xhtml:26

**Comment by OmarShehata** [comment]
Thanks for opening this feature request @supipd. If you're able to dig a little more into what invalid markup is being generated by Cesium this would help determine how much work this would require.

**Comment by supipd** [comment]
Sorry for too late answer.
I tried digging a little deeper and it looks like the problem is in the file 
 ... /cesium/Build/CesiumUnminified/Cesium.js   (in my version on line 30875
 Credit.prototype.element 
After removing DOMPurify.sanitize it seems, that all is working as XHTML.
        /**
         * Gets the credit element
         * @memberof Credit.prototype
         * @type {HTMLElement}
         * @readonly
         */
        element: {
            get: function() {
                if (!defined(this._element)) {
                    var html = this._html;	//DOMPurify.sanitize(this._html);  // <-------------- !!!

                    var div = document.createElement('div');
                    div._creditId = this._id;
                    div.style.display = 'inline';
                    div.innerHTML = html;

                    var links = div.querySelectorAll('a');
                    for (var i = 0; i < links.length; i++) {
                        links[i].setAttribute('target', '_blank');
                    }

                    this._element = div;
                }
                return this._element;
            }
        }

Very interesting situation:
Correct (x)html source code as input to sanitizer ... and output is incorrect ... because DOMpurify uses getting innerHTML from created nodes.

According f.e. https://stackoverflow.com/questions/3047445/innerhtml-doesnt-work-correctly-with-xhtml-in-chrome
.innerHTHML is NON STANDARD and is a bad practice and is browser implementation dependent and should not be used. Especially with XHTML it isn't supported.
