### ISSUE TITLE
Drawing polyline is not smooth

### ISSUE THREAD

**Issue by long3009** [AnalyticalGraphicsInc/cesium#7838]
Dear all
I'm using cesium Sandcastle example to draw line, but polyline is not smooth. I found that Cesium already enable antialias and fxaa.
This is pic to show problem:

![Cesium_antialias](https://user-images.githubusercontent.com/12404368/57691755-3be7b880-766f-11e9-8bf0-f4955ea4eca1.PNG)

How can i fix it.
Thanks

**Comment by OmarShehata** [comment]
I think this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/7783. Check out some of the recommendations there, particular this comment https://github.com/AnalyticalGraphicsInc/cesium/issues/7783#issuecomment-490261591 and the forum post linked in the comment above it.

**Comment by long3009** [comment]
Thank @OmarShehata  for your reply.
Still can't fix this problem. When I rotate camera, these polylines will be artifact and see the bad rendering. Is it the problem of Cesium or Webgl. With OpenGL on desktop, i dont have this problem.
