### ISSUE TITLE
Cesium 1.55 and beyond requests terrain tiles at zoom levels greater than the max zoom level of the TerrainProvider resulting in 404 errors

### ISSUE THREAD

**Issue by abhimonk** [AnalyticalGraphicsInc/cesium#7847]
In Cesium 1.55+, we receive hundreds of console errors stating

"An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile"

These errors always point to terrain tiles with zoom levels outside the max zoom level of our terrain. we're using a CesiumTerrainProvider with a URL for our terrain. [Here's ](https://groups.google.com/forum/#!topic/cesium-dev/UPGExamAoQY)a link to a discussion thread on the cesium forum.

[Here](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=vVTRjuI2FP0Vl46UIJEECJ0ZsgFV2n0cqdXutlIlpJWTXIKFsSPbAWZH8xv9kD7v1/RLeu0QSJhW7FORAPv6+J7j4+u7p4rsGRxAkQURcCDvQbN6F/7uYr6Xu+l7KQxlApQ3fLcSDT40oBQGf1Vyz4rr/c3f5z7Ef1kJQmrFE+JtjKl0EkVbqoyh4QZ4uGZRXEQFNVTLWuUQ2GH0MIsn47h4DKY/rcfBbD2dBPN4Pg/uYTIHun5YFw8PkUdW4tVqO6sDYZhhoENaFJZ3ZSqpMSIFSc4ikRtHVMThWsndBygVgPans3AeP85G5H4cTu7n8xGJx+F4OLJJMsZ5JqkqSOKSrgzb0RIwpxeGkRvrqEn/5UmW8ovcg+L0OaxE6dkNr9YCQqKIfJB1xoHknOVbYjZALrmNJKW0vzZ88plwmVOr3510MBqk2jxzWDb5fma7SipjzfVRiIFdxSkeLsrqfAsmzLW29ljoj0ZKnuG9vzRz+8lovi2VrEWREFVm1J9NR6T9jsPHdq/9VOgoE2VCZtWxE86kwisOFC1YrbuLr1e0TFS16ZKjQ4bllAeUs1IkZMeKgsNbxsDIKiHTHmu7lElj5K67ek1rqHXb9I5tFBV6LRVudENr2R/+uHtaF3d1k1zgaMlME6AaAlmbG4RhXd3mjOPq+F+0Qgq4xVHIg7jNEnw/TRq15ZUWbE9YsVgNrprBaoDFS7XGlXXN+Sf2FVaDZRohvreNS2rv6JfmJVjIZrJ8aoJhGKYRTt/uOh0R4Rh151ymJpPFM7FtIciYsCg8ItB8kxDMDEo7tD1BihfdxWH9J+SF1FhAdxVV2B3wWp7sHrJYLMidxY6IdfECsLMrCDrTMjQsxTJt6tk8V2B5NpBvM3lEb3r0Ngz4uPRGHpxJuLOf5zJzEV1R0Uth4GjwkugORtixNUNDEvJDq5XpT8Ahdz45zb7TO3RcNteb/A7eYzhnvZV0RGRla0ZfoBm+BQfR58XPTrBnFXsomfK6k7qhh8LtaUS6SNeUmx71nMdKLrH+sHsInI3tiB5xNMGRNlDZYDieXF3MSRbl1YaeRP5WIQBjnkvv9S/8raY0q7H1iFZGM+s8jebRBOd4ryxs70/Iuha5tcwfYom2DmHP1+CfCvMO8XD0h8N35LVz/S02p+JjA29xqPrvP/9Ko4Z2+T/q5vLQFsr36H5q4D3d3/5NNw6VbQWRawJ2xfUEG2laxz8) is a sandcastle example demonstrating the issue. Go to the cesium logo billboard to see the terrain. The terrain renders fine, but tiles outside the terrain's max zoom level seem to be requested.

[Here ](https://cesiumjs.org/releases/1.54/Apps/Sandcastle/index.html#c=ZVHBbpwwEP2VERc20mLDst0NG7KqlBwjpVKrnJAigwfWWmMj2xClUf69NjRpk1zsmed5b96MJ2ZgEviEBq5B4RPcoBVjTx5mbBU3c3qjlWNCoYkvriq11BOHxnjwh9GT4J/5y/XrY8nqpVIAo5EHiE/ODfZA6ZkZ5xg5oSStoDmnnDlm9WgaTEJI99s8S3N+mWy+tWmybTdZUuRFkewwK5C1+5bv9zSGSr0Gb+/uUDnhBFrCOA99Kzdo6xGt4PBu0vf2EVM5aY3ub7EziHa12ZIiv9yuYZeSbFcUa8hTkl6sg0gtpKw1MxwOs2jlRM869JoxIXSOLV3kH+90px/1hEayZzKoLg6E17ACAErhVo+1RGikaM7gTgj/tJ2GToczwH/3DFI3LPifJ43WUWnds8Tjovdd9IM2Lix35Y047AfJ/HC0HpszOtJYG9ZT0jdSycUEgl9X0acvriJviVnrX9pRyp/iN1bRsaS+/gNNasaF6u6X+ULJKTveLSAhpKQ+/cpyWsuamf8U/wA)is an example from Cesium 1.54 where the issue does not occur. Make sure to select a non-bing-related basemap for this case, or the globe will not render.

(Note: The terrain used in the above examples is not my terrain data. It just happens to exhibit the same behavior as my terrain data, which I cannot share. The terrain URL above came from this [web app](https://kartta.hel.fi/3d/#/) I ran into online, with which I am not associated).

I'm running into these issues on Windows using google chrome, however I have not tried other browsers or operating systems.

**Comment by OmarShehata** [comment]
The biggest change in 1.55 is @kring 's terrain improvements - do you have any advice here Kevin?

**Comment by kring** [comment]
@abhimonk I just opened #7851 with a fix. With this tileset (and presumably yours as well), the bug is triggered by the lack of a `layer.json` file indicating tile availability. With the PR above, you'll no longer see the requests for missing tiles. However, you will get much better performance if you add a `layer.json`, so do that if you can.

**Comment by abhimonk** [comment]
Hi, thanks for taking a look and fixing the issue. That said, we do have a layer.json file for our specific terrain set. However, our layer.json file only has the following in its contents:
{
  "tilejson": "2.1.0",
  "format": "heightmap-1.0",
  "version": "1.0.0",
  "scheme": "tms",
  "tiles": ["{z}/{x}/{y}.terrain"]
}
How should it be indicating tile availability? Is there a spec for the layer.json file that I could look at?

**Comment by OmarShehata** [comment]
@abhimonk there's an example of one in this thread: https://groups.google.com/d/msg/cesium-dev/MdJKPtvjQFs/dvMTimbCAwAJ

From Kevin's explanation in the same thread, it looks like you're missing an `available` property:

> That means the "available" property of the terrain provider must not be undefined. Otherwise sampleTerrainMostDetailed can't tell which tells exist, so it can't request the most detailed ones in an area. For CesiumTerrainProvider, this means your layer.json must include the "available" property.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/UPGExamAoQY
https://groups.google.com/d/msg/cesium-dev/MdJKPtvjQFs/dvMTimbCAwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7847 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by abhimonk** [comment]
@OmarShehata @kring thanks for the example and for the help!
