### ISSUE TITLE
GroundPolylineGeometry missing/occluded segment

### ISSUE THREAD

**Issue by wallw-bits** [AnalyticalGraphicsInc/cesium#7855]
GroundPolylinePrimitive/Geometry with specific points produces a missing or occluded segment (with or without terrain; also with `GEODESIC` or `RHUMB` arc types). In the following example, changing the second vertex latitude to `48.499` fixes the issue.

Sandcastle example: [Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dZPbjtowEIZfxeJmE4kack4oi4pYRFdCYqVdtapKL0wygFVjI9sBZSvevTaH3XCaiyTjme/3eCbeEIk2FLYg0SPisEUDULRc4R/7Nech37sDwTWhHOSD+3XKp/yYNJKi5MWLYBUzwRdJV1TTDWDKzZsw+g5vIKUBvwNdLLVyXKyXwJ15yXNNBXdc9G/KkbFDCVjlwAEvDrInOYVJUTi12u5s6xy1rBFV8XwpBRel6qA5YQqateh6DUQSnkOnfuaT4kAwIfsfOY5bQxcgVqBl9cyVtkF1pjC6iNZLqtPn0NlxThKXqLW1UNT2zWx6ZAdEavNFeIDnUqyeYCEBVN80vXJ+XwtY++K1I5z4STvMvCyIgiSOmij0ceT5UZRkaZDGSdq8y7ZxkvjtwPJeZmQMm+IwS7M0NnKpn4TePTgLceQHcZbEaRh6JreJohD7npfFSeIlcRiEWXzN/nFvCBKZv1Vr+GhE/+Dj0XDyNHx9HtxAtrTQyw7yzyO7S3WitaSzUtvR3phBbn+Oz/5b73Lq/ZPCfib7FKeej38Nx+PJT/eikE93dwztXHvddvbRaDa6SlcMeofQN7paC6lRKZmDcUvDas2Iqbk1K/O/oHGulMW6rRPULegG0eJx2ri40tMGyhlRykTmJWOv5tZOG71uy+SfYUyQgvLFZAOSkcqmLL3e+LCIMe62jHtNaSHYjMia4n8)

Browser: Chrome 74.0.3729.131 and Firefox 66.0.5

Operating System: OS X 10.14.4

![Screen Shot 2019-05-20 at 4 05 50 PM](https://user-images.githubusercontent.com/7914731/58054866-367be980-7b19-11e9-9b6a-8d0d2236478f.png)

Edit:
This is easily reproducible with lines which are already interpolated along geodesics, but not with the same granularity as Cesium. The items producing this issue in our application are geodesic lines between points with a granularity of 100km.

**Comment by OmarShehata** [comment]
Thanks for following up on this @wallw-bits. I'm surprised shifting the position ever so slightly fixes that gap. 

@likangning93 do you have any advice on where to look here? Lowering the granularity from the default `9999` does help here, but the gap is still large enough to be seen from space at `500`.

**Comment by likangning93** [comment]
@wallw-bits I might not have time to dig deeper into this for a few days, but if it helps, `GroundPolylinePrimitive` has a parameter for visualizing the geometry under-the-hood, `debugShowShadowVolume`. The technique we're using to draw line segments on terrain is actually pretty different from the classic multipass shadow volume technique, but it still involves a piece of geometry that intersects whatever surface the line segment should be clamped to.

With `debugShowShadowVolume` enabled, I'm seeing that a volume exists for the missing segment even though the segment itself fails to draw on terrain:

![fascinating](https://user-images.githubusercontent.com/5395255/58182723-23355f00-7c7c-11e9-983a-77fbacb34161.JPG)

`GroundPolylineGeometry` encodes a description of each volume as a series of planes and attaches this description to each vertex in each volume. It's possible that some of the points/vectors describing these planes for the missing segment have `NaN` components, when I get a chance to debug I might start by trying to filter for these. All of these vectors and points and whatnot eventually get crammed into typed arrays using `Cartesian3.pack`, so I'd start by adding `NaN` checks in there that trigger a `debugger` and then try to trace the computation that went bad from there.

**Comment by wallw-bits** [comment]
I looked into this a bit. I did not see any `NaN` values describing those planes (which I assume to be the `bottomPositionsArray`, `topPositionsArray`, `normalsArray`, etc. in that class). However if I have [`breakMiter()`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/GroundPolylineGeometry.js#L621) always return `false`, that fixes the issue.

**Comment by wallw-bits** [comment]
@likangning93 Further inspection shows that the normal computed at the inbetween point [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/GroundPolylineGeometry.js#L564) and subsequently packed into `normalsArray` is the only normal in the entire array that differs from the others. If you make those three values in `normalsArray` the same as the others, it works.

Therefore I'm fairly sure that the issue lies in `computeVertextMiterNormal()`, but I'm not familiar with the computation. It does not hit the coplanar shortcut or the flip check in that function.

**Comment by likangning93** [comment]
Thanks @wallw-bits! I think I have a hunch as to what's going on:

`GroundPolylineGeometry` miters between polyline segments according to an epsilon check, but it does this by simply computing a normal as the average of the directions from a point to its previous and next points.
This issue reveals that just averaging the directions fails when the points are so far apart that the curvature of the Earth matters - I think the normal is ending up more towards the center of the earth than tangent along the surface of the ellipsoid. I'll try using ellipsoid surface tangents instead and see if that fixes this.
