### ISSUE TITLE
PolygonGraphics.zIndex doesn't work when entity from different GeojsonDatasource

### ISSUE THREAD

**Issue by RenZachary** [AnalyticalGraphicsInc/cesium#7860]
[Demo Link](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=7VZtb9s2EP4rhL9IXgTKbjEUcZxgqdO16TLMQILmQxQEtHS2uVKkQFHKlML/fUe9WVKcYCiGYQPmD7Z19zz3xrujcqZJCCnP4hvQmnG51CrnEWhyShalnIYamIFbpUVUY9zxSSBzZIIQPEkVj56TJTw2Bj68gCrNVIZyDo9D2pdS5jpVeAslDXJBOx75FkiCnxVL4YoVoJc8/Ap6RtZMpOBVStP3NTucZSB3ZS6lKxoxw65VphFKNcQqh3Mh2mQ3oH5Plbw2Ns5gFASB/Ebst3XnmCIBZ0acn7FYmYaFEgJCw5XEeFvQulKmCLzbcw/xO6xSjc5jMLpASJ9YakOldMQlHlNpejqdem8n995zYONlqbg0Tk+/G3hMtEpAG16aHAR7eWGNTAdB7tqn3X35dxeM+rXDwkHOhOu4DjnqFvSIOGOnaod1Jsu6karvPnHQTIfbwoVxfe7WYLjqN8uCCbFi4ddlFXXhtmZc5pHVuOmZ4UeAISHTRm00S7Y8XKqUl7TTveW9lq61iq0AVUy6QJMaTjdgvjCRgVuzPmcCEReYAJXq0R2PbXIvBSCY4SaLYO/0V2a21KgL2GiA1D0UIW1Yr1pWcvM9phvaa7YfGBq9a6Fem4bXcfvDKZnSyWTy417dyKYD3IQeHx8PcFb2roPba+9fiEwDjo/sHl55Vm/Lo6uTPscdULgP7FB2O8/o7MW8ySsuw9WJbXnp+7dbbiCQdQwfQX3GNr9olwuWl0Vu3f3tNgsFi5Mb9VGrTEYzYqOw24maLchON+93VNvT9fZ6Uiq+UV3ASU/f3W4sig4B7UqXWF8cejzbPYA2UprbJk9r/Fpp4loSR/TkBH/mLZ8KkBuzReHRUW/6LP6hRBV2HdTwO9490BITdmZQCaXp7afLmw8dVG0Fh1AUm3JkB0O+bXbHbLhLaurY6xOeLmUEf8zIm4E8RrLmTMwwqs6+q2PZ1bfIf+qCwAF88y+6JP7yBeH77wXu+f+n6++ervdX54tf/pHpmn7XdI280Tw1hYCzSv4TjxOlDcm0cCn1DcSJsP3trzJ8GzQ0TFNLm/sNaR7xnPDoNBgN3iiDkW2PNEXNOhPimj9BMDqb+4jv0Wxjcbn5LQctWGEh2+nZVSWklM59fHzOMkrhm4nuWPwT)
I load polygon from geojsonDatasource and need draw the polygon by order,if the polygon from same geojsonDatasource ,by setting zIndex,it works,otherwise it doesn't work.
## Was it designed like this?

**Comment by OmarShehata** [comment]
I believe this is working as intended. You can sort dataSources by using the [lower](https://cesiumjs.org/Cesium/Build/Documentation/DataSourceCollection.html?classFilter=dataSour#lower) and [raise](https://cesiumjs.org/Cesium/Build/Documentation/DataSourceCollection.html?classFilter=dataSour#raise) functions.

**Comment by RenZachary** [comment]
thank u.
Support for zindex attribute from different geojsondatasource is better.
good luck.
