### ISSUE TITLE
Cesium modifies data in callbackproperty?

### ISSUE THREAD

**Issue by long3009** [AnalyticalGraphicsInc/cesium#7862]
Hi all.
I'm trying to create editable polygon after draw it. I follow drawing example in sandcastle. I log "positionData" and "earthPosition". With draw line: positionData and earthPostion are same, but draw polygon: positionData and earthPosition are different. So I can't get the corect positionData to draw some draggers (for editor purpose).
Please explain why?
This is example link : https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVdtcxo3EP4rqr9wzFCBk7gvMfHUwST21A6MIfG0ccYWdwuniZBuJB2Ydvzfu7o3TkCw0075Yp+0u9qXZx+tFkyTBYclaPKGSFiSHhiezumnbC1ohNlnT0nLuATdaBHy960k+DMgILRcyQsZ8ZBZpclrMmXCQCsX4HKq3qqHjVULWqOpoVYLHoHTKU4MNTALN0qLaJzLBM1b+dg8vpW5gzT35YZHM7DUoDzIUcJC6C9A2nMmI4FCGuZqARcySe1p5l5Q2B9tKIxXCdDL/rvx3dng49vL/l3v8qL3uztumspMk+QuDRWXNlg6x4bKcLfTLJOwwPQlbh+zV3iJplEGDGVRFBRi7pcUuhixZ6tVF3GWXpOalvuFSqhaonruk96cX4z7LV8w4Q8gRvwvQOGjjb0Y+Cy21zAFDTKEytq5v057l6dXw7vx4O799eDjh7O1kcf836wg7h8NNtUy9xmXcNslI9JsyeXsSkWAKWkIBE2jnlK3P4pZAkGZjzNmWZXPUEmjBFChZr7A8TrfxqkX33xKAu/IN+WhzXoWM5WnS5TXQKycge0y1ItocLvuX2tbNBRsnozVe61SGaG41SnsEFvyyMa4/dLfeqwlvgy+WANspt2BO99nSv6n2FF/Z+QxB810GK+eDHyOPaM5E6/rfJKB9qrYweZPQNtVsI1ouuQ2PhVJzIIO/bnZRPvPTkyByBIfBSIZAm8BGeayTjaYi89fjrc2i5WpUMxiVocFrt1anHOLz5Cj3QQUlGTFUNU4DwttasDWaalsiQCcdlUyV9gfiiP6rlYratIkUdqaYQFNM5AlQxaHmRAkNL2y1zupMY65IROtlgajiBQYIpUlhd0K8oZggxb8TBtlcteZ9bPdbpMbICli8b7uBU14+LXktnukHY1glcYCi4iaVrIhmyOeMuG+EDwxikf3xChiY2arA5ZAkOtxDTAerfG+KThyGYMkc5UarBRBvteV32ueAKZtXHqyboBtL/MK0BLWZeB4/r1n4x6bVQgywahlBFPMWOTKpVKduYJx5nnN/UGfZ0JNgK7rWpS10A084371nPQWcKkAOUOycL3eaW42qQdcDLd+efknHfuK2+ckqYn362RUv5JszsNhRYlee/SYEBOGSS57vboCguYufimad8uZjYMfW/k0sScI9GN9y2w6WderUcn35uBZya234E4hdADjeXI+qQaTf8MlG5jzUOJjztUUC/gdHQMy2hX3jmNrdpv7kVu1oYvxExMpeMpPY1clwTMR/g27j88tztXg46h/dzX41HfqSBfX4ICXtX5+6yKfcdvIWaFAIsEKknxIzQTL5UyB1iYlJLQ5l4iyHMhV1vaHvEb+llw1Q20MArkzG8jYL1uzXUpu0k9Fkcdbbu/f9S/px+/F/Gbajp8s4/XF+3OvyVwjqKTktM+V4Qc3mzfOXIkv3XXZKIYflMveQu6lUzrlgXyHT+XWN+blNQB3nT7M57T/w4FyhKz58CVLygirEDJjkc9wchwrheyur0CmQZGqogf+VGqOFz6xCpFOGPIkcSOduyGzN6RZP+fyEUAo9fXUVqMg8iT+x+RLOtVqfgYzrJgJfjx88YK+6Bz90iKvfqKHvx4dtchhp9OhnWbLv3VK9eAo224R/2+z/p6sOzDWTJqp0vPSExxWNX94RS/O+h/GF+M/nOJB66Br7ErASZ6e3/g8m6BSLQJK2xbmicAsm/YkDb/iIzU0WVq67VKpG/EF4dGb24ONh/XtgXswGIM701Rkj7jbg5NuG+U9NeyyCMs1wBFDsJUTiQ9PLvNFSmm3jZ/bWjYvF4rnfnctmwioTnQv9SGTICqBXGiiopW3oE98Yu3a6OQSphYt4e2Q1TyKCCPoHQIWvcH9mn7bN7Db3rV7j64NGoslzUqcM+R+m/hZcxq/XJwuFUVK/gE

**Comment by OmarShehata** [comment]
Hey @long3009 , please use the Cesium forum for general questions like this: 

https://groups.google.com/d/forum/cesium-dev

If you can also include code for adding markers/draggers in those positions in your forum thread, it'll make it easier to see where the discrepancy or issue may be.

**Comment by long3009** [comment]
Thank for your reply. I will post this question to forum.

**Comment by thw0rted** [comment]
In case somebody else comes across this and wonders what's up, trackback to #2809
