### ISSUE TITLE
glTF Animation not playing in Cesium

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7863]
This came up in [this forum post](https://groups.google.com/d/msg/cesium-dev/SRjVP72E6qc/0VeKi-WXBQAJ). The following model is a glTF 2.0 exported from Blender. It has an animation that plays in ThreeJS and Babylon, but not in Cesium. 

~[turbine_model.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3207555/turbine_model.zip)~
^ this file never worked in CesiumJS, the user uploaded a new one here:

[wind_turbine_old.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3249361/wind_turbine_old.zip)

Testing with VSCode, I can see that the Cesium viewer detects an animation, but toggling it on/off doesn't seem to move anything. @lilleyse any idea why? Or advice on debugging it?

**Comment by mramato** [comment]
@OmarShehata put a breakpoint in `ModelAnimationCollection.prototype.update`.  My shot in the dark is that `animateChannels` may be doing some sort of clamping that's causing the animation time to always be 0.

**Comment by emackey** [comment]
@OmarShehata I didn't look at this model, but I know Cesium only supports `LINEAR` animation, `STEP` and `CUBICSPLINE` are both un-implemented.

In Blender, you can work around this by checking a box to always sample animations.

**Comment by OmarShehata** [comment]
So it looks like the first glTF posted by the user never worked in CesiumJS. They posted a new file that used to work, but this glTF does correctly animate in the latest CesiumJS as well. So I'm closing this for now.

My last forum post here has a code example/Glitch app showing this model animating in Cesium: https://groups.google.com/d/msg/cesium-dev/SRjVP72E6qc/FsPYbjQCBgAJ

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/SRjVP72E6qc/0VeKi-WXBQAJ
https://groups.google.com/d/msg/cesium-dev/SRjVP72E6qc/FsPYbjQCBgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7863 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
