### ISSUE TITLE
Hide a HTML Overlay when it's behind the Globe

### ISSUE THREAD

**Issue by asypost** [AnalyticalGraphicsInc/cesium#7866]
Is it possible to make the HTML Overlay hidden when it's behind the globe just like  Billboards。
For now the HTML Overlay is still visible when it's position is behind the globe and the camera  look at the whole globe.

**Comment by OmarShehata** [comment]
For general questions like this, please use the Cesium forum (https://groups.google.com/d/forum/cesium-dev) and I'll be happy to take a look there! 

GitHub issues are more for specific bugs or feature requests. This may already be possible to do, but there's not enough information here to determine that. Please include a bit more context and perhaps a Sandcastle code example when you open your forum thread.
