### ISSUE TITLE
Cannot select entities in 2D when zoomed out

### ISSUE THREAD

**Issue by gcatto** [AnalyticalGraphicsInc/cesium#7868]
Steps to reproduce:

- Navigate to the Billboard Sandcastle app (link below)
- Switch to 2D mode
- Zoom all the way out
- Try to click to select the Cesium logo, but be unable to do so
- Zoom in some
- Try to click to select the Cesium logo again and one will be able to

Edit: if one uses Cesium.MapMode2D.ROTATE instead of Cesium.MapMode2D.INFINITE_SCROLL, the problem does not seem to happen

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1Vp7T9tIEP8qFv/gSOnGefEoUB2PcEQCgkJK1SsV2tiTeHUbO1pvoKHiu9+s7cTvxLTA0UhBznpmdua3M7Ozs9xTod0zeAChHWgOPGjH4LHZhNz4Y/qm6f88dh1JmQNis7J369w6o5ljSuY6GrWsI8b50KXC0ivaz1tHw881dSyTepIDscDkVIAeJwxkKMJgZgKOZJKBR5BKD2Woz9T1mD/Nx4Vax1RIfKJOk4yEOzmBsQDw9A/bbdLe3d7ermotgxjNnZ1mpRrJGS5m1j7GpKsPm9AxoPhNQmr+s1cLZro7d8funXsPgtM5mTrjzYjxKXh8UnY8JeDwQC6tvBLuFIQyayUw+Sz/J0Tar2NU1Wo1zYIRnXH5UZs5+IheYyXlebb7gOKkmEGcPkk0ZT+A90YjhAdpY465NK+hG1XtQ9uoJCdVo0YlKQzmsFJUU0dEkC38UylWy3YFe1TBwHuCjVkM9rPUG3LcuRx0+sWi7tVKm1lBN4lxctQbDHoXSRsD0SlUkUWtUkMZESeuEyNJabrcFTF/UT/Jefeik+T7ctYddJKcwpU06WwXVNrkqnvXu+n07057n/tJGUZ6bsrZGB3i8Afzcj32n06/VwzZA7OkjXx1wyjlaTawsa0WvdFeR14c06ZNnTE8N6wLuWKRjanXD+s5pt5XDPOq1jTURzn2Swd8PoCRfdEsB6GtZDm0F5Atf5PAhQ+0JjEy7wKnPUg6re+i5IFJ+5BPbYpR3GjnJGX2GC1E17kACWJNTs7jePuFe4X8nMoZaOfCvDAjr1zQwNRH150MXD1AIAs3AnCBUcamPMLQW1cbZDmScHO05LPgiHcJK/civhE1GUc1M7yLF2TMRpvvcLMNDc5fjhdVdccgbUynzTapt56pZAzdt1G03qhiLietrZdWNJUxVCI6mp8wT1LHhNW5Ikn7zgu3hNtXcyqIyJJkrXQJVJxScY00VOh10ga1FKrWUM/bqm5qV8pgO6JWWWiTpH9qSZzklII6Hp+Z4JjzV8fa9YvekminiRfxGyr1YINDKOf6t5hB4bs+eO5MmEBGIE27qwDRS0ATB7ukqIT/xjD4HhO1MF8PeCrpxcNK8NBbHHrVZuZpJnc9/CHdZaaIVr+a4WaOKYB6kDikINyBCcrMmO+gTGljtRvUoqkjQGyHOgtq1YPAt7xv9e8kYFm6fUwDVQ2ZVIIVTeRV8fQ5pQJHNbo0bwxyYV1q6tUx9NKxVCKm0rG1xKGaT/f8o1i+nGedw7IinpJDy23vjwPaeFdAF8go1RZQmfJDMq4q6+VdP2f7M6CpsnGYkrfCtkH+HL+S8nPk1yvlne8pvyyn4l8QzyjKU/TRDqxSqGVhwsE1pTyWhLQh5kVLJUNpYx4aYroP/YyFQ5JTj7zjffzBZhKubTpFhXL2b5/qejbswzhQLbaIR+7MsZgz7oOJSzzmoLd2USW1kjvqm3aQwkbMWxTTLeVczd3faQq8KFRbdaxx1kIVj3g15Hf7SHsZK0blDbDb9jNMq/5+sEPP31H2t9S3PHYKOIPsvjF6Td/ztt8Neg1Er26g6zVUmd0oFaX9zslbQLVLgpP5e4GqbqhQ8/+Uz2hfO+fnvS8rziuqDJYgBGXOlXDvmQViL7ZzWcyjQw4nMJX2ADy5cttKE0d7VmqGqHWXnTq2iFmu0DZ1BJDwxRXcGgQ0emr9PdzxgYy5O1TqhfocjpHSkyELilNNt5c/2dYbDVLfbeMitbbwod5+nZZBcELpwwgEBDXNojJMviDH54cXV3eD3t3f/d7ny5OUmPSixWqky9lkiIhc9a67g+5N5657edq97A6+ro2+sEuZQnTpczHXQZAHrsuHVFyAM9O//Vz4yw9VY26qQmeJ2AIA1/GAY1io3tLiuJk4aCYvRmNngtjENmLEFU6Z29HQrqeqllLmGuveaPmmy1sFrKs03yNRkdI6Ft1WrtO2+MqyUO9j/zokV/XS6q64iFmn8crbmGKw2WNcZQzXid8qLw9w/s3DWnyLrh8KNVU+Oglb6LFq/DnemtezL+G2+Y37Ykj9K57hfNGfsMJILw9pujW7Fsxsf7ZQu1Nq/ZZy6d7mOt2yDc5C1cIz728ol20GrlOvqCNY7IL+gfFXHTBzOi3jfjlH1EIVT4Jtxj+H+hsyvvGkpjqbGlYPkyn47bqxUHVPadWz5ck6vfNqlIXS34OCJcYnQC38wXJ2LZo+3NxMOsFjOBnx+Zk7Ad0oqkMFTPA8fsi5HlVFbKTp4Z4d3onrqZKnkrC2sCzKr6LyC6/l/fteRnC5omlEuQcx1PBxo7qx78k5h0/B8F9sMnWF1GaC61jMSJhMORZsXm04M/8FSUzPd5b92oJp32L3GrMObjdS//N0u6G8w/PwzWjGudoVbjc+7deQPsHGXaqq5V7Q4VYkdv3TeTBICNmv4c8slwxKj5jE/wA

Browser: Chrome

Operating System: Win10

**Comment by OmarShehata** [comment]
Thanks for reporting this and for the Sandcastle @gcatto. This is definitely a bug. I'm not sure when we'll have time to look into a fix here, but here are my debugging notes if anyone wants to give it a shot. 

1) The picking of entities happens in the Viewer here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/Viewer/Viewer.js#L112

This is supposed to return the billboard when you click on it, but returns undefined when you're zoomed all the way out.

2) The pick function is in Scene.js here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Scene.js#L3533

This is what's returning undefined. The way this picking works is that Cesium renders the scene to a framebuffer, with a unique color for each object, and then reads back those pixels to figure out what object you clicked on.

3) The reading of the pixels happens in PickFramebuffer.js here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/PickFramebuffer.js#L119

It is specifically this line:

```
var object = context.getObjectByPickColor(colorScratch);
```

In a successful pick, `colorScratch` has a non-zero value. When you zoom all the way out and click on the billboard, you get a color with all zero's. So it's almost as if it's not correctly rendering to the pick framebuffer when you're zoomed all the way out?

@lilleyse do you have any other advice or thoughts to add?

**Comment by lilleyse** [comment]
Opened a fix here https://github.com/AnalyticalGraphicsInc/cesium/issues/7868
