### ISSUE TITLE
CesiumJS 1.57, the HelloWorld is blank, why?

### ISSUE THREAD

**Issue by Hiwen** [AnalyticalGraphicsInc/cesium#7869]
Hello everyone!
I downloaded the CesiumJS 1.57 source code, extracted,  and run the following commands on windows 10(1903):
$ npm install
$ node server.js
Then, I tried the http://localhost:8080/Apps/HelloWorld.html

But it was blank！

Then I tried the 1.40 version as the same way. 
But it worked very well!

 :exclamation:  I don't know why 1.57 didn't work but 1.40 worked well  :exclamation:

I tried this on Chrome 74.0.3729.169. The latest version! And the Node.js was v10.15.3.

I wish someone can help me! Thanks very much.

**Comment by OmarShehata** [comment]
@Hiwen were you getting any errors in the console?

**Comment by mramato** [comment]
Hello World requires the built version of Cesium.  You need to run `npm run minifyRelease` in order for it to work (or to reflect any changes made to the code).

**Comment by mramato** [comment]
See The build guide for other information about building Cesium: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide
