### ISSUE TITLE
Cesium3D Tilesets credits broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7876]
`Cesium3DTileset` credits are not properly showing up in the `Data attribution` panel.  git bisect points to 43c0141a55ee3f00a806fe8697095376e9fa7417 as the first bad commit.

I'm not sure if the problem is where being/end is being called in the linked commit or if the problem is that the credits are in the `postPassesUpdate` function of Cesium3DTileset (and happening outside the begin end.  ideas?

CC @loshjawrence @lilleyse since this was in the streaming PR it would be good if one of you could take a look; but if you absolutely can't I can try to dig in.   We need this fixed ASAP.

**Comment by lilleyse** [comment]
Opened https://github.com/AnalyticalGraphicsInc/cesium/pull/7877

> I'm not sure if the problem is where being/end is being called in the linked commit or if the problem is that the credits are in the postPassesUpdate function of Cesium3DTileset (and happening outside the begin end. ideas?

Yes that was the problem.
