### ISSUE TITLE
Incorrect Output for CesiumMath.Factorial

### ISSUE THREAD

**Issue by rshaikhha** [AnalyticalGraphicsInc/cesium#7888]
There is a bug in CesiumMath file. The function factorial does not produce outputs as supposed to.

Ex:
//Compute 7!, which is equal to 5040
var computedFactorial = Cesium.Math.factorial(7);
returns : 7

The function's output is always equal to the input!

**Comment by tfili** [comment]
Thanks @rshaikhha but this was already fixed with https://github.com/AnalyticalGraphicsInc/cesium/pull/7969.
