### ISSUE TITLE
Cesium crashes when having modelMatrix on polyline primitive

### ISSUE THREAD

**Issue by martinnovak** [AnalyticalGraphicsInc/cesium#7889]
Sandcastle example: 

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=hVVbb+I4FP4rFi+lUmoSEkpIabWdQmeQyrQqbLWrYbRyk0OxamxkO1B2xX8f536Z2V3Eg8/9nO98dvZEoj2FA0h0jTgc0B0oGm/xS6rrnoWpeCe4JpSDPDu/WvF1zENNBUcy5t1z9M+KI/Pr9dACNNIbQJRTTQlDIdmCJGl+pAViQrwjotGc8A3RmvAscG9ayCOehKJp5uuijzsitTkR7uK1FNsJvEkA1b0Yeth2fN9x7b5v233Pt5Bn48uR43iu6w4dz+87FhoO3KThVpVHScHM0yz0BUhE+dsT1eHmWTDWKNd3cH/oD0f+0O+PXN8dWOjC6FzPHdmDge0P+96lKWdje+hcjgbOyLQ28j1nUFTPe0hBxSoEDjgDByvQCdbdHMXkF4HSlKf9BW1krMpNVGMEvxit5gk8WkrC1VrIbVAMPCda0g8PzybTr8vZ8s/M/dTsOBRcabQVEbDMvwKszKjwpoXdUtzTD4jupRmxW7Txb4P83HlmSRqpN7HLA5Vp4Vs1W42zFVe6FzZO9mH+59b/+SIH27lv5vq9VXkPxvdD35tZDXtLAJ5AzoyZ8BDuBBPydrcDIhMRv0yfl9M//rp/fJ7fLq/quUjp1LxvT4IdmblhrUx1WugEcBYb8ujACDHUJpNmxSAXBj8IUINKO71ZGj41tAkjyCuDKEBrwhRUlpPVip0T9d7yOtWYUh/tDcT210N9NhbQ8lhMU64yqI554QON9CZAbi6uDZvEYRHLNQkh78Mq35vbKIIov1rpjrIVBc2NWUWTBllT8VtJgUSBn6cTq6n59PD7FH1vRJlVv6QpM+ATUzl+zk5J28MbjRltX+7wLUehII3ppeb+uWWtNk/Nms5mk7NyNUWiID2V6totDeqCVewrP1QUDGrn3Kg2JBIHVb4Si1Sem2x4MlvcfnowcOVp1JGHGym4iFV9M6f/ePN2BSYKkyjqJmLifUqQTD8mVx2rM1b6yOAmC/+NbndCahRL1sW4p2G7Y4bkqvcah++gcahUkmHcK4LGEd0byK5Xndana9VBISNKGcs6ZmxB/4ZV52bcM/6NMCbSx+zRcIiRY+KycW4eMiXGeNwz4s9RWgj2SmQt4w8
Browser: Chrome

Operating System: OSX

After upgrading Cesium from 1.53 to 1.57, I encountered an error.  When I try to create a polyline primitive with model matrix from point 0,0,0 to 1,0,0 - Cesium works well, but when I try to go to negative with the second point -1,0,0 - Cesium now crashes. I have no idea what is the problem, I tried to debug it a little, but with no luck. But I think it's something with model matrix and that some calculations may not take it into account.

As a workaround, I just don't use model matrix, but I use absolute coordinates instead.

**Comment by hpinkos** [comment]
Hello @martinnovak,  the `followSurface` option for polylines was deprecated.  Use `arcType: Cesium.ArcType.NONE` instead
