### ISSUE TITLE
createImageBitmap Test Failures in Edge

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7894]
```
Core/loadImageFromTypedArray flips image only when flipY is true
Error: createImageBitmap() method does not exist
```

```
Core/loadImageFromTypedArray can load an image when ImageBitmap is not supported
Error: createImageBitmap() method does not exist
```

@OmarShehata Does Edge not support `createImageBitmap`?  Is there a flag or something these tests should be looking for to skip them for Edge?

**Comment by OmarShehata** [comment]
Yeah we must have forgotten to revisit this after refactoring how the check for this works. This should be checking for `Resource.supportsImageBitmapOptions` and then ignoring the test if the browser doesn't support it in the same way ResourceSpec does:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Core/ResourceSpec.js#L1209

I can open a PR to fix this now.
