### ISSUE TITLE
Edge Test Failure - Scene/Model renders with specular environment map

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7896]
localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20renders%20with%20specular%20environment%20map

```
Scene/Model renders with specular environment map
Expected not to render [0,0,0,255], but actually rendered [0,0,0,255].
```

**Comment by OmarShehata** [comment]
No longer failing as of 1.64.

**Comment by wesleyjmartin** [comment]
Fails for me on 1.66, 1.67, and 1.68

**Comment by OmarShehata** [comment]
@wesleyjmartin does it fail in just Edge or all browsers?
