### ISSUE TITLE
Offline guide links to repository that doesn't exist

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7898]
The [offline guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Offline-Guide) says:

> Cesium ships with a low-resolution set of images from Natural Earth II in Assets/Textures/NaturalEarthII, or you can download a higher-resolution tileset from the cesium-assets repository.

However, the repository `cesium-assets` no longer exists. We should either update this link with where a higher resolution version of NaturalEarthII imagery exists, or just delete that reference and link to the Offline Sandcastle instead? Or perhaps remove this page altogether and move it as a tutorial on cesium.com?

This came up [in this forum thread](https://groups.google.com/d/msg/cesium-dev/FgHBostNhao/igUH6aVrBAAJ).

**Comment by hpinkos** [comment]
Removed it

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/FgHBostNhao/igUH6aVrBAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7898 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
