### ISSUE TITLE
Cesium 1.58.0 package on npmjs is missing Build directory

### ISSUE THREAD

**Issue by skaughtx0r** [AnalyticalGraphicsInc/cesium#7901]
I just pulled the latest Cesium version and it appears to be missing the Build directory that was included with previous versions. Was this intentional or a bug?

**Comment by hpinkos** [comment]
Thanks @skaughtx0r, looking into this now

**Comment by hpinkos** [comment]
I just published `1.58.1` on npm, and this includes the `Build` directory.  Thanks again for catching this so quickly @skaughtx0r!
