### ISSUE TITLE
the polyline could be automatically stretched

### ISSUE THREAD

**Issue by venci01** [AnalyticalGraphicsInc/cesium#7902]
Draw a polyline with three points.
The coordinates of the starting point are the same as the coordinates of the ending point.
The polyline could be automatically stretched
![GIF2](https://user-images.githubusercontent.com/24424656/58934150-3415c280-879c-11e9-9a28-06b89f14bd32.gif)

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVVtb9o6FP4rFl+gKtdAy8LLaHVb6NZqKanWrOhqmSo3OYBVx+Y6DpRN/PfZSSAvVLr7cPlQ8OPnnJ7Xx2si0ZrCBiS6QBw2aAwRjUP8lGCNup8cx4IrQjnI+slHj6d8rEBKDT5IsaYByIvM0pdAFMyEZIGbMhq/PI6yj4R/Y4jUTFPkPYle0RApGUPziPEEUsHbVMiQsChjpaRdEoOOOyCKPIpY+lCOfRxHSoSTw22jHm4Ntxh8bhthEgSN/GxIHm+1ViKiigqOiE5iiwzkLgH5QsiAch1/hMQcKQ1FikhF+QKtBOVK8yGFSQiIRMnvd6yABwcbnCa0/5eRzmefi3atfxF+judSJwULCRBdmZAa3z3+V6fTx71B2zrvd8/65k/zvI+t/mDQs3p9a9Dtd63mgWad9zTQ6wy6vW7C67XPrO7A+tA+61nd5p+5+5EWyNQjkGSTJb2hgVoiRl6AeXwuZMPkQ3Ue7Y/6a5SnhhnwhVpq9PT0BP1CeePzFmDgSrOz1hSmZ+9leHD3nf5oFu91LENUsEhQ+gbskf6EIeq0m+U7XzAhh4dqmxP+58a2nVmFuAS6WKqvMAcJ3IeDyW0Zx2P76v7h2XWeP391vk0nuZNdwWFSp6M49bzr4L3a1MFe7ZRWApgLk5q+7vRXb+gW2BoU9YlXq/IoY+M/zUrEium9fo9/bV+Nv7xPn5lmD9FZ5TZSW5YXxjY5PhoIf7qz7eer6eTZ+ebad9Obqt1SbK6J/7qQIubBkSAk1ReS/jQixBxJF5Tn5a9cYPvmk1sxXmsp0ZWqmj6VYHztuK5z//90veIloBF5YTCBlVq6WtsmVEtG4i5XtWRECgK3K60Y25q6e/y/doQbzRmi+t6ivo9kD6Dy1OWKk68UKkbvMxKuXPE5ac2xWGd7P0TdIhgadaeEabwgyw9ZCE46RPcZSb8fK92JbaOyDelqospUzm7v3Or8lMYSHc9lacrfdVjg706yg2nGLtW67M2Ys60rSi9FrVkbJVN/mRr9TcOVkArFkjUwbikIV8xofusl9l9BYT+KjMdRa280Cuga0eDCq1UeWq9mSh9F+mYes0S9vNrlqKX5JTMmiHlGHD3jjGwNZdm5tFMQYzxq6eOxlRKCvRBZ8Pgb

Browser:Google Chrome  71.0.3578.98

Operating System:Windows 10 Home edition

**Comment by likangning93** [comment]
Hi @venci01, thanks for the clear example!

I wasn't able to reproduce this with https://github.com/AnalyticalGraphicsInc/cesium/pull/7885, but could you confirm?

Here's a link: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fixGroundPolylinesCoplanar/Apps/Sandcastle/index.html#c=rVVtb9o6FP4rFl+gKtdAy8LLaHVb6NZqKanWrOhqmSo3OYBVx+Y6DpRN/PfZSSAvVLr7cPlQ8OPnnJ7Xx2si0ZrCBiS6QBw2aAwRjUP8lGCNup8cx4IrQjnI+slHj6d8rEBKDT5IsaYByIvM0pdAFMyEZIGbMhq/PI6yj4R/Y4jUTFPkPYle0RApGUPziPEEUsHbVMiQsChjpaRdEoOOOyCKPIpY+lCOfRxHSoSTw22jHm4Ntxh8bhthEgSN/GxIHm+1ViKiigqOiE5iiwzkLgH5QsiAch1/hMQcKQ1FikhF+QKtBOVK8yGFSQiIRMnvd6yABwcbnCa0/5eRzmefi3atfxF+judSJwULCRBdmZAa3z3+V6fTx71B2zrvd8/65k/zvI+t/mDQs3p9a9Dtd63mgWad9zTQ6wy6vW7C67XPrO7A+tA+61nd5p+5+5EWyNQjkGSTJb2hgVoiRl6AeXwuZMPkQ3Ue7Y/6a5SnhhnwhVpq9PT0BP1CeePzFmDgSrOz1hSmZ+9leHD3nf5oFu91LENUsEhQ+gbskf6EIeq0m+U7XzAhh4dqmxP+58a2nVmFuAS6WKqvMAcJ3IeDyW0Zx2P76v7h2XWeP391vk0nuZNdwWFSp6M49bzr4L3a1MFe7ZRWApgLk5q+7vRXb+gW2BoU9YlXq/IoY+M/zUrEium9fo9/bV+Nv7xPn5lmD9FZ5TZSW5YXxjY5PhoIf7qz7eer6eTZ+ebad9Obqt1SbK6J/7qQIubBkSAk1ReS/jQixBxJF5Tn5a9cYPvmk1sxXmsp0ZWqmj6VYHztuK5z//90veIloBF5YTCBlVq6WtsmVEtG4i5XtWRECgK3K60Y25q6e/y/doQbzRmi+t6ivo9kD6Dy1OWKk68UKkbvMxKuXPE5ac2xWGd7P0TdIhgadaeEabwgyw9ZCE46RPcZSb8fK92JbaOyDelqospUzm7v3Or8lMYSHc9lacrfdVjg706yg2nGLtW67M2Ys60rSi9FrVkbJVN/mRr9TcOVkArFkjUwbikIV8xofusl9l9BYT+KjMdRa280Cuga0eDCq1UeWq9mSh9F+mYes0S9vNrlqKX5JTMmiHlGHD3jjGwNZdm5tFMQYzxq6eOxlRKCvRBZ8Pgb

**Comment by venci01** [comment]
I don't think #7902 is caused by the curvature of the earth.
Coincidence points on the polyline cause this problem.
You can see the pictures below.
[ven.png](https://github.com/venci01/cesium/blob/master/ven.png)
[GIF2.gif](https://github.com/venci01/cesium/blob/master/GIF2.gif)

**Comment by likangning93** [comment]
Hi @venci01, #7885 also includes some behavior changes for co-incident points. I'm no longer able to reproduce the problem using the same Sandcastle code but in the deployed branch, would you mind confirming?

**Comment by venci01** [comment]
@likangning93 哥们你会汉语吧，我英文不好，交流起来太费劲，不介意得话加qq吧（215782823）

**Comment by likangning93** [comment]
Hi @venci01, I'm no longer able to reproduce this in cesium `master`, so I'm going to go ahead and close this.
