### ISSUE TITLE
`camera.computeViewRectangle` returns incorrect values?

### ISSUE THREAD

**Issue by mrlubos** [AnalyticalGraphicsInc/cesium#7913]
Pardon my question, I am not an expert on projections, it's possible this is a feature, not a bug.

I suspect the `camera.computeViewRectangle()` method returns incorrect values for certain magnitude levels. The reason I noticed this is because I attached a listener to the map that is meant to count points inside the visible bounds. As I zoom in, the number decreases, even though I still see all of the points on the map. In other cases, the number stays the same, even though I cannot see the points anymore.

Here is how I obtain my view.

```js
const getView = () => {
    const { ellipsoid } = viewer.scene.globe;
    const rect = camera.computeViewRectangle(ellipsoid, new Rectangle());
    return {
      east: Cesium.Math.toDegrees(rect.east),
      north: Cesium.Math.toDegrees(rect.north),
      south: Cesium.Math.toDegrees(rect.south),
      west: Cesium.Math.toDegrees(rect.west),
    };
};
```

Am I doing something wrong here? I want to know coordinates for the bounding box of currently visible area on canvas.

**Comment by hpinkos** [comment]
Sorry we missed your question.  If you are still having issues, please post on or forum and we'll be happy to help: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

**Comment by mrlubos** [comment]
Hi @hpinkos! Is this not the right place to ask questions? Forum only? Thanks!

**Comment by hpinkos** [comment]
@mrlubos yes, we use GitHub exclusively for tracking bugs and planning new features.  Members of our team also monitor the forum so we do our best to make sure all questions there get answered.  Thanks!
