### ISSUE TITLE
3D Tiles position appears offset in Columbus view

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7915]
I _think_ this is generally a problem with any geo-referenced models/data in Cesium, but this case that's come up that's easy to see is in the NYC 3D buildings tileset. Here's what it looks like in columbus view:

![columbus_view](https://user-images.githubusercontent.com/1711126/59049552-418f8300-8856-11e9-8311-7d9f4f23c265.png)

Notice the buildings in the ocean. This is what it looks like in the 3D view:

![3D_view](https://user-images.githubusercontent.com/1711126/59049556-43f1dd00-8856-11e9-8a1c-75c3f7cc2dbe.png)

This came up in [this forum thread](https://groups.google.com/d/msg/cesium-dev/e3HaZ6r6ZoM/MqT81qmcBQAJ). All you really have to do is go to the NYC sandcastle and turn on columbus view. [Here's a Sandcastle](https://www.google.com/url?q=https%3A%2F%2Fcesiumjs.org%2FCesium%2FBuild%2FApps%2FSandcastle%2F%23c%3DbVNrT9swFP0rVr%2BQSsV5k4QVNFbQVokCooUKKdLkxpfWw7Er2yljiP8%2B59FS2PLF8fW5Pueee70hCm0YPINCJ0jAMxqBZlWJ75uYc1A025EUhjAB6mCAXnOB7GdAKRu6UXLDKKjjbWKhgBiYS8XprIU4%2FUGbogsQMJEUduDpNoJH15d3k29305%2F344t5hy%2FJ2l7%2FCwrDpDjeVzeHxQRUQYxU7winO7zgnK21ZBTPv0%2FTqJ%2BLt%2F6XXOSirRM3MvCSywVgCmuzmoE2Z0urVJtOsvXCqAqaLNdFUzDIrAAxwQwjHBWkBEUa35CRiEv5hIhBEyJWxBhSU1lbO%2FSN1KyWZ%2B%2FsBI6IMvaPiBA%2FKlmew1IBaOcwibDnp6kfekHqeUGUDlDk4aPM96MwDBM%2FSgN%2FgJI4rMvZY7hWDGx%2FOpI9m34AoUwsb5gpVreS8w90gY%2BDJE2yNEmDLEzDeIAObSyMwsyLYy9NgujI0nnYS%2FyjLPYzKy1LIz9u2PetbO3AGkw9NU43INS6ygRpe%2FfJi67B8l348X%2BK6VAg6EwRoR%2BlKneTMyFGsd8RHp9fXM3Gs4ddk227LiWhTb%2BuHkZoUTFem6CRYRysxta6bvPRr3YJz2ftofOKKsV3lGMpbkHLShXQGHmmLWZMnTiJ%2FD56%2B8eWtWKlLWkDGhNKnY6xVdkb9IbavHA4bWv8ysq1VKbmczB2DZRrbp%2BRdhdV8QQGF1rXiUN3mzSkbIMYPcl7n15o3kMFJ1rbk8eK8yn7A3nvdOha%2FIc0LpvZuN6A4uSlhqz808s2iDEeuna7zfoL&sa=D&sntz=1&usg=AFQjCNGxMarGTqyAaSIMLYFc5akpKAtr1A) that loads it in Columbus view.

@likangning93 mentioned this is because we don't project the position of every model, just the center of the tileset itself. So things further away from the center will be offset this way. 

I'm not sure what an easy fix for this would be - it sounds like you might want to handle this during the creation of the tileset? Or perhaps reprojecting things at run-time like with Gary's PR https://github.com/AnalyticalGraphicsInc/cesium/pull/6986 would help if you could do a projection that was local to NYC?

**Comment by likangning93** [comment]
> Or perhaps reprojecting things at run-time

To clarify, this would be projecting Columbus View itself into something more local to NYC when building an app around NYC that can't be on the 3D Globe.

It also isn't necessarily just each building's position that needs to be reprojected, it's not that much of a leap to imagine a model or sequence of models such that each vertex must be reprojected - imagine an elevated highway or maybe a bridge, perhaps as several models that must line up very perfectly.

We've kind of been ignoring 2D/2.5D for 3D Tiles because they're 3D Tiles, so in cases like this we've mostly been asking if users could adopt a globe view instead. But yeah for the case where users are working in a local projection, it may be sufficient to support that local projection.

**Comment by hpinkos** [comment]
duplicate #5955

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/e3HaZ6r6ZoM/MqT81qmcBQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7915 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
