### ISSUE TITLE
Crash when loading glTF's KHR_texture_transform without a sampler

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#7916]
Cesium's implementation of the `KHR_texture_transform` extension of glTF makes poor assumptions that the optional `sampler` will be defined.

https://github.com/AnalyticalGraphicsInc/cesium/blob/90b130edea858b7b6b6a1575422b0b2654f2ae97/Source/Scene/processPbrMaterials.js#L94

In the above, `gltf.samplers` need not be defined, and `gltf.textures[n].sampler` is likewise optional, leading to a rather fancy message:

> Cannot read property 'undefined' of undefined

Here's a sample model for testing.

[TexRotateTest.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3262897/TexRotateTest.zip)

**Comment by mramato** [comment]
So it looks like the behavior is to have repeatS/repeatT be false if there's no sampler?

**Comment by emackey** [comment]
No, the [default wrapping value](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplerwraps) in glTF is `REPEAT`, so when not specified, repeat should be true.
