### ISSUE TITLE
Extruded polygon disappear(clipped) at oblique camera view

### ISSUE THREAD

**Issue by dhdbtkd** [AnalyticalGraphicsInc/cesium#7918]
![bandicam 2019-06-07 19-43-59-311 mp4_000003816](https://user-images.githubusercontent.com/37060597/59099516-3c1d6000-895e-11e9-8296-75c6f67a0f69.gif)
![bandicam 2019-06-07 19-45-13-023 mp4_000000366](https://user-images.githubusercontent.com/37060597/59099521-3f185080-895e-11e9-9089-3c94b40443c5.gif)

I trying to simulate flood
i used entity for polygon and extruding this and material water
but Zoom in or oblique, extruded polygon disappear(clipped) partially
Both Chrome and Firefox are same 
Is there any reported bug about this??
and what's the solution for this problem

this is my code for polygon

polygon = viewer.entities.add({
            name : 'Water Polygon',
            polygon : {
                hierarchy : Cesium.Cartesian3.fromDegreesArray([129.114576532148, 35.180415714084134,
                                                                129.12028042633713, 35.180371289635005,
                                                                129.12198945638295, 35.17625045200848,
                                                                129.12508129548067, 35.17342526165849,
                                                              129.1253017622399,35.16468843450737,
                                                            129.11464306769273,35.16464005679386]),
                extrudedHeight: 1.2,
                material : new CustomMaterialProperty({
                   type : 'Water',
                    uniforms : {
                        normalMap: Cesium.buildModuleUrl('./Assets/Textures/waterNormals.jpg'),
                        frequency: 1000.0,
                        animationSpeed: 0.025,
                        amplitude: 10.0,
                        specularIntensity: 10,
                        baseWaterColor: new Cesium.Color(0.23, 0.46, 0.34),
                        blendColor: new Cesium.Color(0.23, 0.46, 0.34) 
                    }
                })
          }})

**Comment by OmarShehata** [comment]
I think this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/6573. Can you confirm if the following line solves the issue for you?

```
viewer.scene.logarithmicDepthBuffer = false;
```

**Comment by dhdbtkd** [comment]
It's working!! Thank you!

**Comment by MapsRus** [comment]
Hi Omar...did you happen to create an open repository for this project? It looks amazing.
