### ISSUE TITLE
Hide viewer until CSS is ready in Sandcastle standalone mode

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7919]
If you go to any [Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/), and then click "open in new window", you'll see this quick flicker of misplaced elements for a fraction of a second on first load:

![master](https://user-images.githubusercontent.com/1711126/59128944-6b6da600-8939-11e9-9bad-36eb4902dc6d.gif)

I _think_ this is only an issue in the standalone mode in Sandcastle, but if anyone has encountered this in their CesiumJS app please provide a sample here. 

I'm fairly certain this is happening because the HTML gets added, and in the HTML it has a `<style>` block to include the CSS, and then after that is included, things get correctly placed. To prove this theory, you can add a line [right after you add the HTML in standalone.html](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/standalone.html#L59) to hide the HTML:

```
htmlElement.querySelector("#cesiumContainer").style = 'display:none';
```

And then in [bucket.css](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/templates/bucketRaw.css) add this to force it to show again:

```
#cesiumContainer {
    display: block!important;
}
```

It looks much better:

![fixed](https://user-images.githubusercontent.com/1711126/59128947-6dd00000-8939-11e9-8fb6-d8ffa16ae312.gif)

I think some kind of mechanism like this might be the most elegant fix? Another question to investigate is why doesn't this issue happen in regular Sandcastle (or maybe it does and I just haven't noticed it?)

**Comment by emackey** [comment]
Opinion:  `!important` is never a good idea.  Don't use it.  Instead, always try to use the cascading nature of CSS.
