### ISSUE TITLE
An error occurred in "IonImageryProvider": Failed to obtain image tile X:  Y:   Level:   

### ISSUE THREAD

**Issue by chaogis** [AnalyticalGraphicsInc/cesium#7925]
Browser: Google Chrome 74.0.3729.169 (64bit)

Operating System: Windows 10 Professional

Hello, i am integrating CesiumJS with vue(webpack) under the direction of CesiumJS and webpack（https://cesium.com/docs/tutorials/cesium-and-webpack/）, but there is something not work perfect. you can see the errors and result in the pictures, and also, i provided the config files of webpacks and vue components.

I hope you can help me find out why this happens, and how can i fix it.

Thank you very much.
![error](https://user-images.githubusercontent.com/32628057/59177356-70776300-8b8e-11e9-9619-42097e314233.png)
![show result](https://user-images.githubusercontent.com/32628057/59177357-70776300-8b8e-11e9-9c38-c6a193a1abb2.png)
[webpack.base.js](https://github.com/AnalyticalGraphicsInc/cesium/files/3270887/webpack.base.js.txt)
[CesiumViewer.vue](https://github.com/AnalyticalGraphicsInc/cesium/files/3270888/CesiumViewer.vue.txt)

**Comment by chaogis** [comment]
@bagnell @pjcozzi @hpinkos @mramato @lilleyse @kring Thank you.

**Comment by OmarShehata** [comment]
@chaogis please open a thread on the forum (https://groups.google.com/forum/#!forum/cesium-dev) for questions like this, I'd be happy to take a look there!

GitHub is more for bug reports or specific feature requests.
