### ISSUE TITLE
Crash when 3D Tiles bounding region has 0 volume

### ISSUE THREAD

**Issue by verybigzhouhai** [AnalyticalGraphicsInc/cesium#7933]
Hi,
       Recently I loaded a lot of 3dtiles layers from different sources. During the browsing process, I sometimes get an error. 
![image](https://user-images.githubusercontent.com/37999729/59326945-b6f9c880-8d1a-11e9-8d55-4dc888f3df8a.png)
![image](https://user-images.githubusercontent.com/37999729/59327231-81091400-8d1b-11e9-9f3f-4f3da9565882.png)
I checked this in detail. I found that when a cesium3dtile bounding box has a volume of 0, for example, it is A face or a point in point cloud data, there is no height in a certain direction, which causes this error to be thrown when calculating the distance from the camera to the tile.

![image](https://user-images.githubusercontent.com/37999729/59326971-c416b780-8d1a-11e9-9c7d-4f7ed7ebc89a.png)
Should we add a validation to the program, when creating a cesium3dtile object, if I get a bounding box that will cause problems, initialize it to a fixed unit quantity, for example, when I create the box, I will detect it. The following is the case. 
![image](https://user-images.githubusercontent.com/37999729/59326983-cf69e300-8d1a-11e9-8483-d1eeb62eff9d.png)
    The correct operation of the program does not depend entirely on the legitimacy of the data.

**Comment by OmarShehata** [comment]
This seems like a good idea to me, to make the client more robust. The [specification doesn't say anything](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#bounding-volumes) about a 0 volume bounding volume being invalid.

I'm not sure if it's going to cause problems further down the chain if you fix this one, but if this really is a valid bounding volume, we should fix it, or if it's not, we should throw a more meaningful error.

@lilleyse thoughts?

**Comment by verybigzhouhai** [comment]
By resetting the new value for 0 volume, the program is running fine so far, and no effect has been found. Just because we modified it at the top of the chain, it should not cause other problems. Maybe I can set the value even more. Smaller, make it closer to 0 instead of unit_x , unit_y or unit_z

**Comment by verybigzhouhai** [comment]
@lilleyse haha，we have the same idea
