### ISSUE TITLE
Show only a portion of the terrain,Black square flashing

### ISSUE THREAD

**Issue by hemincan** [AnalyticalGraphicsInc/cesium#7935]
![image](https://user-images.githubusercontent.com/32860032/59338961-e407a480-8d35-11e9-9c6a-4405cbdcac68.png)

When zoomed in to a terrain area，then Back to the world view,There will be such a black square flashing

**Comment by hemincan** [comment]
![image](https://user-images.githubusercontent.com/32860032/59339660-2e3d5580-8d37-11e9-92e4-f84873e59f04.png)

**Comment by OmarShehata** [comment]
Can you please share a Sandcastle (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) code example of this issue? I'm unable to reproduce this. Is this using a custom terrain provider, or a different tiling scheme, or some other configuration?

**Comment by hemincan** [comment]
> Can you please share a Sandcastle (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) code example of this issue? I'm unable to reproduce this. Is this using a custom terrain provider, or a different tiling scheme, or some other configuration?

when I use Cesium Ion to publish the same terrain.There is not such problem. But I use nginx to publish my terrain,It will have such problem. 
it seem like that the layer.json is different.
cesium ion layer.json  "bounds": [-180, -90, 180, 90]
my terrain "bounds": [104.99942779541, 19.9995803833008, 109.999580383301, 24.9997329711914],

**Comment by OmarShehata** [comment]
@hemincan  How are you creating your terrain locally?

If you manually edit the layer.json bounds, does it fix the issue?

**Comment by hemincan** [comment]
> @hemincan How are you creating your terrain locally?
> 
> If you manually edit the layer.json bounds, does it fix the issue?

I replaced my entire layer.json with layer.json generated using cesium ion, but the problem remains.

But I used the terrain url generated by cesium ion (Cesium.IonResource.fromAssetId(30987)) in the same code, and there was no problem.

Can you recommend the official offline tool for processing terrain data?

**Comment by OmarShehata** [comment]
So I think this may be a case of incorrect tiles generated, but it's hard to narrow it down further without seeing the tiles or how you created these tiles.

There is an offline version of all of Cesium ion's tools available. You can read about it here: https://cesium.com/docs/on-premise/ , and you contact the email on there for a trial. If you have any follow up questions feel free to start a forum thread! https://groups.google.com/forum/#!forum/cesium-dev
