### ISSUE TITLE
Loading Vector tile ?

### ISSUE THREAD

**Issue by anujsinghwd** [AnalyticalGraphicsInc/cesium#7939]
- **I am unable to get PBF vector tiles working from an external http:// source. I don't see any documentation or examples of this.**
- Loading [Mapmyindia](https://maps.mapmyindia.com/) .pbf tiles and style
- how to load .pbf and style.json
- Still Map working well
```jsx
 const viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider: new Cesium.UrlTemplateImageryProvider({
       url : 'https://{s}.mapmyindia.com/advancedmaps/v1/your_key/still_map/{z}/{x}/{y}.png',
       subdomains: ['mt0', 'mt1', 'mt2', 'mt3', 'mt4'],
       minimumLevel: 4,
       maximumLevel: 19
    }),
    baseLayerPicker : false
  });
```
- like above still map , how to load .pbf url and style.json ?

**Comment by OmarShehata** [comment]
CesiumJS doesn't currently have support for PBF. You can check out the roadmap issue here: https://github.com/AnalyticalGraphicsInc/cesium/issues/2132

I bumped it with your request, feel free to continue any discussion there to keep it all in one place.
