### ISSUE TITLE
3DTiles透明度 导致LabelGraphics.disableDepthTestDistanc 禁用无效

### ISSUE THREAD

**Issue by gaoxiansheng1324** [AnalyticalGraphicsInc/cesium#7949]
如果3DTiles存在透明度，那么LabelGraphics.disableDepthTestDistance = Number.POSITIVE_INFINITY 将无效

**Comment by OmarShehata** [comment]
@gaoxiansheng1324 can you please provide a full Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) code example showing this issue?

**Comment by OmarShehata** [comment]
Closing for now, feel free to add more detail to the issue so we can reproduce it and we can take a look then.
