### ISSUE TITLE
addSample function of SampledProperty bug

### ISSUE THREAD

**Issue by shyoon87** [AnalyticalGraphicsInc/cesium#7954]
hi 

When adding a new position(sample property), there is a bug that does not work properly.

There is a bug that changes existing values instead of being added.

**Comment by OmarShehata** [comment]
Can you please provide a [Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) code example that recreates this issue?

**Comment by shyoon87** [comment]
I'm sorry..
my mistake..
not bug. thank you.

**Comment by OmarShehata** [comment]
No worries, thanks for confirming!
