### ISSUE TITLE
I want to kown what frame the cesium is importing, require.js?

### ISSUE THREAD

**Issue by caflulu** [AnalyticalGraphicsInc/cesium#7955]
i want to contribute to this project, but first i need to know what's the frame does cesium used?
who can introduce to me, thanks

**Comment by OmarShehata** [comment]
Hey @caflulu, excited to see to hear you want to contribute! We absolutely appreciate it.

The contributing guide is a good place to start: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md

Specifically, the build guide has instructions on the setup you need: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md#build-the-code

I'm going to close this as we use GitHub issues for bug reports or feature requests - but if you have any more questions feel free to post a thread in the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev
