### ISSUE TITLE
Wrong gamma on unlit "KHR_materials_unlit" Gltf model

### ISSUE THREAD

**Issue by TietoaPetter** [AnalyticalGraphicsInc/cesium#7957]
**GLTF** models with the **KHR_materials_unlit** extension _i.e._ unlit models, have an incorrect gamma profile in comparison to an html element with the same image as texture source. As you can plainly see, the GLTF background is grey, while the actual image background is white.

![gltf is considerably darker than html img](https://storage.googleapis.com/cesium-debug-folder/ColorGammaDebug/Capture.JPG)

[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVRtb5swEP4riC+hErFDkrZbXqpV6bR+WLWu3fYJqXLAgFe/yTZJuqn/fWcICclMpNjn5567e7gjlRtigg2jW2qCZSDpNlhRy2qBfjW2aJA1x5WSjjBJzeBinkr/YOw9hcop/2k4+A4QwoffrdYWPxOhOb0jjuAGZ3HLfcvMfvcCW1Ty9QBIz+jSsHJO2xnG1ilDSopKpUpOiWYWZUrgNrFhTtd1OSwUzymwKq7MFyIEufPm9ryqaPZKfRxXpOE+/cxQ4uiDjxelYdbg7htcGsZdGnEy6sotapk5pmTQd5RE0DioARhUlJWVuwj+pjKA1SqKqHTMMWqRoUJt6C3nUUvYYKBgrSxraJed7itiHOyInKDCKHFHS0OpjYbJeIJG19PpVfIxDqZTNLocTa5HV4fI8yNpRUnOZHnkfCCuQk49gZlIGyWTyz5cM5dVAB71bEZxfmaq9FmH3LdhHr37E+Cjfdy4ZYwbkn4gZRgIQk7r/WEgpUIZYVF1Rvi9BqWNBHjU6RT7NE4lbDR+A8JzzUmeR/vX4Zd/WcGs+YuP1sMLmB22vdt+xrP+qYdpmgVue6H8qg0Do++NU7tgkolaPLId5c/sj08pGX84B5GdBz1nhHvAeATriHhvt+8HbdvCnSHQv/nnTo9WGMC8ty18fMI4XFj3xulNS/CJCa2M89lGMLyOwtyC9Bava2B0KLPWx1rgzmmRs03A8iVMzunnIQ2DjBNr4aaoeVNgGt4sMOC9GxNlYE22PA53rbkiOdqyVyYotCdSpsT+pP0Jw6ALJS12VS3WeIqnRTvTL91Q67zAGr4OyTAZjad6N/zvGv3WJaRFuIOwzW2QVftJD5qCwL5luatml8lY7+btQM3Gl1dw6JpiRtZW8drROdTTF8CnD037bUMNJ2++2Cq5+doaEUILDMdD/QcvpxRfE9PT5h8)

Browser: Firefox latest, Chrome latest

Operating System: Windows 10

The .gltf model used here is very simple and is displayed below in its entirety.

The .gltf is also downloadable here:

 [gltf](https://storage.googleapis.com/cesium-debug-folder/ColorGammaDebug/ColorChecker.gltf)

 [bin](https://storage.googleapis.com/cesium-debug-folder/ColorGammaDebug/ColorChecker.bin)

 [image](https://storage.googleapis.com/cesium-debug-folder/ColorGammaDebug/page1-1024px-Color_Checker.pdf.jpg)

`{
    "asset" : {
        "generator" : "Khronos Blender glTF 2.0 I/O",
        "version" : "2.0"
    },
    "extensionsUsed" : [
        "KHR_materials_unlit"
    ],
    "extensionsRequired" : [
        "KHR_materials_unlit"
    ],
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                0
            ]
        }
    ],
    "nodes" : [
        {
            "mesh" : 0,
            "name" : "Plane"
        }
    ],
    "materials" : [
        {
            "extensions" : {},
            "name" : "Material",
            "pbrMetallicRoughness" : {
                "baseColorTexture" : {
                    "index" : 0,
                    "texCoord" : 0
                }
            }
        }
    ],
    "meshes" : [
        {
            "name" : "Plane",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "TEXCOORD_0" : 1
                    },
                    "indices" : 2,
                    "material" : 0
                }
            ]
        }
    ],
    "textures" : [
        {
            "sampler" : 0,
            "source" : 0
        }
    ],
    "images" : [
        {
            "mimeType" : "image/jpeg",
            "name" : "page1-1024px-Color_Checker.pdf.jpg",
            "uri" : "page1-1024px-Color_Checker.pdf.jpg"
        }
    ],
    "accessors" : [
        {
            "bufferView" : 0,
            "componentType" : 5126,
            "count" : 4,
            "max" : [
                1,
                0.42645999789237976,
                0.5
            ],
            "min" : [
                -1,
                0.42645999789237976,
                -0.5
            ],
            "type" : "VEC3"
        },
        {
            "bufferView" : 1,
            "componentType" : 5126,
            "count" : 4,
            "type" : "VEC2"
        },
        {
            "bufferView" : 2,
            "componentType" : 5123,
            "count" : 6,
            "type" : "SCALAR"
        }
    ],
    "bufferViews" : [
        {
            "buffer" : 0,
            "byteLength" : 48,
            "byteOffset" : 0
        },
        {
            "buffer" : 0,
            "byteLength" : 32,
            "byteOffset" : 48
        },
        {
            "buffer" : 0,
            "byteLength" : 12,
            "byteOffset" : 80
        }
    ],
    "samplers" : [
        {
            "magFilter" : 9729,
            "minFilter" : 9986,
            "wrapS" : 33071,
            "wrapT" : 33071
        }
    ],
    "buffers" : [
        {
            "byteLength" : 92,
            "uri" : "ColorChecker.bin"
        }
    ]
}`

**Comment by lilleyse** [comment]
This is due to Cesium's scene-wide high dynamic range. Here is a Sandcastle with high dynamic range disabled: [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVRtT9swEP4rUb40SKndlBa2UtBQO40PQ2Ow7VMk5CaXxMMvke20sIn/vnPSl7QzSPWdHz939/guqVozE6w5bMAE14GCTbAAyxtJfrW+aJC15kIrx7gCMzi7SlWHJzYDBaTiZbV8U0zy7JGpEpCmYMIC4lJFqeeXOgfx0wg8GhBC9/+3dW3pE5O1gCVzjLY4S7sMbrnZ7p5xS0qxGvjQx3RpWDlX2xml1mnDSiCl1qUAVnNLMi1pl/4wh1VTDgstckBWLbT5wqRkS+/u7EUF2Qv4OK5Iwzb5VGUGmIN7Hy9Kw6zF3bW4NIx3acTJ6GyLLxqVOa5V0L+I0kAcNAgMKkCx3FnwN1UBrq2OoBx3HCwxIPUaboWIOsIWgwXX2vKW9nr3OgtmHO6YOieF0XIJpQGw0TAZn5PR5WRykXyMg8mEjKaj88vRxT7y1YG0ApZzVR4475mriNOP6GbKRsn5tA+vucsqBI96PqOFOHFV9Ukf3XVhHvz1R8RH27hxxxi3JP1A2nAUhB3X+8NgSoU20pLqhPB7g0obhfBop1Ps0ziWsNX4DQlPNWd5Hm2fwy//WMGs/YkP3v0DzPbb3mk/41nf6mHaZsHTXii/GsPR6Xvj2C+54rKRD/wVxBP/41NKxh9OQezVg54yJjxgPMJ1QLx32/e9tl3hzjDs3/zzTo9OGMS8dy18+AvjcG7dm4CbjuATl7U2zmcb4fA6wLlF6S1dNcjoSGatjzWnu0vznK8Dnl/j5Bx/RNIwyASzFk+KRrQFpuHNnCLeX+OyDKzJrg/D3dRCs5xs+AuXgO1JtCmpt2pvURx0qZWlrmrkik7opOhm+nk31HVe0Bq/DskwGY0n9evwv2Pyuy4xLSYchm1Pg6zaTnrQFoT+Dc9dNZsm4/r1qhuo2Xh6gcauKWZsZbVoHH78wiMBfPrYtN/WYAR788VWyc3XzkkImVM09/XvbzmtxYqZnjb/AA)

![UNADJUSTEDNONRAW_thumb_1](https://user-images.githubusercontent.com/915398/60021865-c6550c00-9660-11e9-994f-28af04943037.jpg)

**Comment by TietoaPetter** [comment]
> This is due to Cesium's scene-wide high dynamic range. Here is a Sandcastle with high dynamic range disabled:
Sweet, problem solved. Thank you very much. 

What is the use case of having the tonemapping not in accordance to reality? Wouldn't it be simpler to compensate the lighting, and have correct tonemapping. Is ugly tonemapping for vectorized images somehow preferable to correct tonemapping of "emissive" or "unlit" surfaces? Is there a way to control the tonemapping?
