### ISSUE TITLE
Using SampledProperty to create pulsating point

### ISSUE THREAD

**Issue by jad4580** [AnalyticalGraphicsInc/cesium#7960]
Browser: Chrome

Operating System: Windows

So, I am currently trying to creating a pulsating effect on points plotted on the globe, similar to the solution provided here: https://stackoverflow.com/questions/42842607/cesiumjs-points-and-css-keyframe-animation

However, this only works on an older build of Cesium (1.31), but does not work on the most recent version (1.58). I looked over the code, and most of the code should work with the most current version. Can someone provide some insight on this and how to fix it so that it runs on version 1.58 as well?

Thanks!

**Comment by emackey** [comment]
I fixed it on StackOverflow.  In Cesium versions newer than this old example, Cesium doesn't run the clock by default, you just have to add one extra Viewer construction option to make it work.

```
    shouldAnimate : true
```

**Comment by jad4580** [comment]
> I fixed it on StackOverflow. In Cesium versions newer than this old example, Cesium doesn't run the clock by default, you just have to add one extra Viewer construction option to make it work.
> 
> ```
>     shouldAnimate : true
> ```

Thanks!! Do you also by any chance know if we're able to somehow use GIF images for billboards? I saw some posts relating to it, but the only solution I could find involved changing the build code. Has this functionality been implemented?
