### ISSUE TITLE
OSM ImageryLayer is dark in compare to prev versions

### ISSUE THREAD

**Issue by talattar1234** [AnalyticalGraphicsInc/cesium#7962]
While upgrading from 1.50 to 1.58 I have noticed that the OSM ImageryLayer is darker in 1.58
![DarknessCesium](https://user-images.githubusercontent.com/5999248/60091999-88ceac80-974e-11e9-8d0c-fccd3eaa7827.png)

Sandcastle example: 

Browser: chrome 64-bit

Operating System: windows 10 64-bit

**Comment by GatorScott** [comment]
You need to disable high dynamic range support.

`viewer.scene.highDynamicRange = false;`

Scott

**Comment by talattar1234** [comment]
> You need to disable high dynamic range support.
> 
> `viewer.scene.highDynamicRange = false;`
> 
> Scott

Thanks Scott! now it's works great!
