### ISSUE TITLE
Disable HDR

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7966]
There have been many issues related to HDR causing imagery to appear darker in Cesium:

* https://github.com/AnalyticalGraphicsInc/cesium/issues/7962
* https://github.com/AnalyticalGraphicsInc/cesium/issues/7957
* https://github.com/AnalyticalGraphicsInc/cesium/issues/7815
* https://github.com/AnalyticalGraphicsInc/cesium/issues/7417

Personally I do not think HDR provides enough (or any) of a visual quality improvement to justify being on by default. The problem is very little of the Cesium rendering engine outputs high dynamic range values so tone-mapping is ineffective and only darkens the scene.

We should consider disabling it on everything but PBR glTF 2.0 models, where the tonemapping would just be part of the PBR shader.

**Comment by GatorScott** [comment]
+1

**Comment by mramato** [comment]
I agree as well, I feel like HDR went in prematurely and it needs a lot more thought to be enabled by default.  It affects too many things in unintended ways.

**Comment by pjcozzi** [comment]
Agree to turn it off by default.  I would think this includes glTF PBR models but that is up to @lilleyse.

**Comment by ProjectBarks** [comment]
I made a quick [sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVZdT9swFP0rVl8apMxt+dgHFDRopzFpCEYRLwtCJrltrDp2ZDsFNvW/79pJ2jSMjZdGffDH8T3nHtvXXTBNFhweQZNjIuGRjMDwIqO3fizoxr47UtIyLkF3Q/I7kgQ/LqfqTD2RQzJlwkBYjhoQEFuu5DeZ8JhZpduAlCXq0eCo1cV6UBUiOZU8YxaqqUgud44iGclpIX1EEmvA6QuVgAgKLUKSAp+ldqdWVKZBQVpuORiqIVMLOBUiKAN5DKabK8N9wOM62RHTFltM7tGpVtkYZhrABO8Gu3u0/2F///3gU0j292n/oL/3of9+xXy0DpoCS7icrWNeMJtSq65xmEkTDPYOmvCc2zhFcL8xppUQraE0b23LeUlz5ZZfIz6oeMMyYuiDNImU5mgI28z3RqOkqdKZoWkr4I8CPdYS4UHtU+hkbFroPX7GgG3PWZIE1Xa4T7LM7afbrfXgyv/DVbMx2xR82Ow1MJk7AzjbYHJfofkLMg/neLKK7Io/gZjwX07RYPdjG8SeHGgSM+EAu3381ohl2VyurC3ztprFc0i+1HaUviBm6dzy/udOu8G5n5VaC08WCbqnXMeaTW23EoIof3nchamOfLDTTLF5/ruU9la/0zw3vQnLcgFjZlnP22N65WYjTdW6xyadiQe8wweYHO3XyaDY5epe1/K+alXIhNxCymMBWxNZ0lQsm71K679lnitLMC9yxoRQSm7ZzIpls1fpHPzf0wsu5uRGF/F8yzodkedp99/Ns/hNvk7mXEpIyChleMatq/zbVcxqV++x+SaJYxSmyEhluQZjUKvn3JpOT7dmazuLku20rfnuqK4DZcG4XFeDEtTQ49I6JFFnzA17wBp0Pr6OOs3C+DIhsplRozCZGCTQFF+p8TMWYR5fMzkD5PVv8dHLwha+queL3KIc99L/RU0k7yI5YTKJmbFYCfBZuVFKPDB9AbIINswsX6bXwWoN64SdobHPAk5Kns88y5W27skIcOMt4J7jmTC9B9xQsDQ2ftmwVy8aJnxBeHIcdVr/i6IOiQUzBmemhfCvTNQ5GfYQv7FMKP/cXi5AC/bsIOng5Hs5SCkd9rD7cpUt02lE/AM) to see the differences between HDR and non-HDR cesium.

It might be worthwhile to:
- Enable HDR on glTF models or
- Leave HDR enable but create a sand castle to show how to enable/disable


Here is a

**Comment by lilleyse** [comment]
Just seeing how washed out the milk truck looks with HDR disabled I think it will be a good idea to add tonemapping to the PBR shader when HDR is disabled.

**Comment by lilleyse** [comment]
And both the atmsophere and shadows can be tweaked when HDR is disabled.

**Comment by OmarShehata** [comment]
The reason it looks washed out is because of our PBR shader is trying to output HDR values right? These equations were created with HDR in mind for example: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/processPbrMaterials.js#L787-L790

**Comment by lilleyse** [comment]
HDR was disabled by default in https://github.com/AnalyticalGraphicsInc/cesium/pull/8055
