### ISSUE TITLE
Static background for skybox

### ISSUE THREAD

**Issue by jad4580** [AnalyticalGraphicsInc/cesium#7977]
Hi there!

Does anyone know if it's possible to use a static image as the skybox in the Cesium viewer? I noticed some other posts regarding changing the source images in the skybox, but I am curious as to whether I can use one simple static image for the background.

If anyone can provide some input, I'd greatly appreciate it!

**Comment by OmarShehata** [comment]
You could pass the same image 6 times to the skybox. If you mean you want to have a background that does not move with the camera, you could remove the skybox and set a background color like in this example https://github.com/AnalyticalGraphicsInc/cesium/issues/7732 (or make the background transparent and put an image behind the canvas).

In the future, for general questions like this, please use the forum: https://groups.google.com/forum/#!forum/cesium-dev. We try to use GitHub issues more for bugs or specific feature requests.
