### ISSUE TITLE
New Cesium.PostProcessStage draw the circular scan diagram, click click to select it, how to add event selection;New Cesium. ScreenSpaceEventHandler (viewer. Scene. Canvas);The selection is not valid through this API

### ISSUE THREAD

**Issue by yuchengxing** [AnalyticalGraphicsInc/cesium#7980]
function AddCircleScanPostStage(viewer, cartographicCenter, maxRadius, scanColor, duration) {
        var ScanSegmentShader =
            "uniform sampler2D colorTexture;\n" +
            "uniform sampler2D depthTexture;\n" +
            "varying vec2 v_textureCoordinates;\n" +
            "uniform vec4 u_scanCenterEC;\n" +
            "uniform vec3 u_scanPlaneNormalEC;\n" +
            "uniform float u_radius;\n" +
            "uniform vec4 u_scanColor;\n" +

            "vec4 toEye(in vec2 uv, in float depth)\n" +
            " {\n" +
              " vec2 xy = vec2((uv.x * 2.0 - 1.0),(uv.y * 2.0 - 1.0));\n" +
              " vec4 posInCamera =czm_inverseProjection * vec4(xy, depth, 1.0);\n" +
              " posInCamera =posInCamera / posInCamera.w;\n" +
              " return posInCamera;\n" +
            " }\n" +

            "vec3 pointProjectOnPlane(in vec3 planeNormal, in vec3 planeOrigin, in vec3 point)\n" +
            "{\n" +
                "vec3 v01 = point -planeOrigin;\n" +
                "float d = dot(planeNormal, v01) ;\n" +
                "return (point - planeNormal * d);\n" +
             "}\n" +

             "float getDepth(in vec4 depth)\n" +
             "{\n" +
                "float z_window = czm_unpackDepth(depth);\n" +
                "z_window = czm_reverseLogDepth(z_window);\n" +
                "float n_range = czm_depthRange.near;\n" +
                "float f_range = czm_depthRange.far;\n" +
                "return (2.0 * z_window - n_range - f_range) / (f_range - n_range);\n" +
             "}\n" +

             "void main()\n" +
             "{\n" +
                "gl_FragColor = texture2D(colorTexture, v_textureCoordinates);\n" +
                "float depth = getDepth( texture2D(depthTexture, v_textureCoordinates));\n" +
                "vec4 viewPos = toEye(v_textureCoordinates, depth);\n" +
                "vec3 prjOnPlane = pointProjectOnPlane(u_scanPlaneNormalEC.xyz, u_scanCenterEC.xyz, viewPos.xyz);\n" +
                "float dis = length(prjOnPlane.xyz - u_scanCenterEC.xyz);\n" +
                "if(dis < u_radius)\n" +
                    "{\n" +
                    "float f = 1.0 -abs(u_radius - dis) / u_radius;\n" +
                    "f = pow(f, 4.0);\n" +
                    "gl_FragColor = mix(gl_FragColor, u_scanColor, f);\n" +
                 "}\n" +
              "}\n";

        var _Cartesian3Center = Cesium.Cartographic.toCartesian(cartographicCenter);
        var _Cartesian4Center = new Cesium.Cartesian4(_Cartesian3Center.x, _Cartesian3Center.y, _Cartesian3Center.z, 1);

        var _CartographicCenter1 = new Cesium.Cartographic(cartographicCenter.longitude, cartographicCenter.latitude, cartographicCenter.height + 500);
        var _Cartesian3Center1 = Cesium.Cartographic.toCartesian(_CartographicCenter1);
        var _Cartesian4Center1 = new Cesium.Cartesian4(_Cartesian3Center1.x, _Cartesian3Center1.y, _Cartesian3Center1.z, 1);

        var _time = (new Date()).getTime();

        var _scratchCartesian4Center = new Cesium.Cartesian4();
        var _scratchCartesian4Center1 = new Cesium.Cartesian4();
        var _scratchCartesian3Normal = new Cesium.Cartesian3();

        var ScanPostStage = new Cesium.PostProcessStage({
            fragmentShader: ScanSegmentShader,
            id:'Shader',
            uniforms: {
                u_scanCenterEC: function () {
                    return Cesium.Matrix4.multiplyByVector(viewer.camera._viewMatrix, _Cartesian4Center, _scratchCartesian4Center);
                },
                u_scanPlaneNormalEC: function () {
                    var temp = Cesium.Matrix4.multiplyByVector(viewer.camera._viewMatrix, _Cartesian4Center, _scratchCartesian4Center);
                    var temp1 = Cesium.Matrix4.multiplyByVector(viewer.camera._viewMatrix, _Cartesian4Center1, _scratchCartesian4Center1);
                    _scratchCartesian3Normal.x = temp1.x - temp.x;
                    _scratchCartesian3Normal.y = temp1.y - temp.y;
                    _scratchCartesian3Normal.z = temp1.z - temp.z;

                    Cesium.Cartesian3.normalize(_scratchCartesian3Normal, _scratchCartesian3Normal);
                    return _scratchCartesian3Normal;
                },
                u_radius: function () {
                    return maxRadius * (((new Date()).getTime() - _time) % duration) / duration;
                },
                u_scanColor: scanColor
            }
        });

        viewer.scene.postProcessStages.add(ScanPostStage);
    }

    var lat = 149.4024201566827;
    var lon = -65.71296152309055;
    viewer.camera.setView({
        destination: Cesium.Cartesian3.fromDegrees(lon, lat, 30000)
    });
    var CartographicCenter = new Cesium.Cartographic(Cesium.Math.toRadians(lon), Cesium.Math.toRadians(lat), 0);
    var scanColor = new Cesium.Color(1.0, 0.0, 0.0, 1);
    AddCircleScanPostStage(viewer, CartographicCenter, 1500, scanColor, 4000);

**Comment by OmarShehata** [comment]
Can you please provide a full Sandcastle example, and post the error message you're getting? You can do this by going to (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html), putting your cod there and selecting "share" and pasting the link here.

**Comment by yuchengxing** [comment]
https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=xVhtb9s4DP4rQoBD5c1V4iTtbk073C7dgAN2t2Ed9ilAoNmKo82WA1lO4wz970fJjl/il6TDAecPiS2RDymSIiltqURbzh6ZRHdIsEc0ZzFPQvLVjOEL13zOI6EoF0xeWLOFQPCsEuEqHgn01vPmXLoBe3Cp+BTF6kFRn+EM00YulSryJd2suTtnQumxkO4+U48nsY1iYJpHQQSjXiKpRrTQz0yEfragngZ+YH4I3A9r6mlNSwL9LAaJ4KtIhiim4SZgcnyPXA36he1UItlssRCLAXp5mstjG7U+wQUqpVz4aMvcMdouVUY9jyLpcUEVi0+JA8YpSpZm6cYi7+ZnsExylk8BFewfGKTBab5VEFEFjNKY+zmKafOV9A0baEoVvUsZ5iKzRLK1EbxnEo0drQ5x4N+2CTNloHYpxKJ+wzjZkh16gcZkhC6RQ0aWrYfS2pA168Wbok0U/yXmNGSSojt3Hy652DIZs08y+s6yKH5hKPEutTPdbYPcA1zDrH4Mq1PksQdCMggcUSXvchB66vPEBCC4UPlqPmYRkvsF5sp4MQ4qBz9K7nNRGdQoXU7r8lmhw3bkgNcMBrqs4M96GPNgAT4vUrimKcBZqI83tx7OJVbXCd70uny3GHTZstDHZ+pex0BuwmlfNJ+wTAa4Xz5y4UWPsE4dfYnYUPdHJiKD7lvnEbNkJnQ/RH4GcJi2TttZQBoQPsuBjOTPeoAIRuVp9lUX+6qf++AovWFflLa4LPS5PEBbsHnwqhjN53/Jk9uIe1BnuMC/5Dc/WL6X1DdZEBac5/jxPa6WFbs1+5/hCGM7gC0CrSKgWoE6BPRKMAGriy+UYq25ydFtMHmiOwUGaUF+z3PKYX8fZZqWukR26d4+qnHZWK6a/jjHUlwvImDCByuVimhuCJAmfi8kX2GNd1vUQ6uT+FSE1PYFaOjoYkS/xfgADdqBLB3Q/cW3Amas+4hXNpr2lJ6OCA35DleH7Godt9GqD6+6kdpnZtUdpluy5RzaOugMqZhk5gcV8sZxXmn4iIoKQtzsBA+9ZBN1WqBWWtJyFjfkk53dVIqkbYMQhI7VvqK6ek5T/IGgZTEkiITPVeKxtqaXBNDbdk6uGffXCr1EV6NRt1EmpVqnbN22mpPWds43t9Nqb6fV4E6XxRUPdUrBWuY9pCRsWQRS4hcYxi3ksQvnA3d9dow01tsB4Pw6wiTvN9oBJi2rqB2S6nx6GDIrHLji7Aj1s74dV7C3yzPQTfNYZNfpBbSUNxfZ1MXRXN7xxzfoZzMh1NPqTXnUw1YbuX7yGp+v5G+qJN9NSZgEim+C9M/0K5SLSOaHQuJmvfFSf2a0djMa7U6HVd1yeJ7srnXU6tJZi9F+UizclPvsf1hQVRHnP9bE6VbF6dKlK/bheHaXKQlvl+aN7J6LkRYY6QEjfS7GvsDYHzD2s0ZnmD+NrUqEQeF7hrsk2J2yu2yW74outrPDOGsgnrMRixsW6Lgxbs+wYCWTgi30W+XuZVi8P2uXmT7jprzOqdM9lZ9PRzkxC9vYZdDVbY4yYEyo5+FayjyY+unoFso1V1BvBQ+N7rhxiQT1V/dp09dkOhpPxyPn6vr69/GrowwPNRyoLq+vyCtn/PrauRpPRq9HV1ezhsb5RouZ0jdlx7naY7HSbTaoctMSbCsZhffMl4zFGETaWjsbTUbwWEemqmrXLOo9HUqZMNbQGuhooMJIs2zUMUcVzDUakMKnR8L0EIbGF1iKn1r6OHEzOG+5GXSgAapdCk5HZUf0lP83fD0b2IPbWKUBe5NR/MHDTSQVSmSACRnqZBDoM8/wW+L+YIq4sT6midvhgenW41vEvbvF4Oi+E7piN6BxDDOrJAgeIEEsBm9uh0BfY4OTAJyr/I9wOA9oqknWzpsP2SAh5HYIn00uFUXBNyoriP8C


This is the address. How do I pick up the red circles?"var eventHandler = new Cesium. ScreenSpaceEventHandler (viewer. Scene. Canvas);
"Is not valid through this API method

**Comment by yuchengxing** [comment]
> 您能否提供完整的Sandcastle示例，并发布您收到的错误消息？您可以转到（https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html），将您的鳕鱼放在那里并选择“分享”并粘贴链接。
https://cesiumjs.org/Cesium/Apps/Sandcastle/index。HTML＃C = xVhtb9s4DP4rQoBD5c1V4iTtbk073C7dgAN2t2Ed9ilAoNmKo82WA1lO4wz970fJjl / il6TDAecPiS2RDymSIiltqURbzh6ZRHdIsEc0ZzFPQvLVjOEL13zOI6EoF0xeWLOFQPCsEuEqHgn01vPmXLoBe3Cp + BTF6kFRn + EM00YulSryJd2suTtnQumxkO4 + U48nsY1iYJpHQQSjXiKpRrTQz0yEfragngZ + YH4I3A9r6mlNSwL9LAaJ4KtIhiim4SZgcnyPXA36he1UItlssRCLAXp5mstjG7U + wQUqpVz4aMvcMdouVUY9jyLpcUEVi0 + JA8YpSpZm6cYi7 + ZnsExylk8BFewfGKTBab5VEFEFjNKY + zmKafOV9A0baEoVvUsZ5iKzRLK1EbxnEo0drQ5x4N + 2CTNloHYpxKJ + wzjZkh16gcZkhC6RQ0aWrYfS2pA168Wbok0U / yXmNGSSojt3Hy652DIZs08y + s6yKH5hKPEutTPdbYPcA1zDrH4Mq1PksQdCMggcUSXvchB66vPEBCC4UPlqPmYRkvsF5sp4MQ4qBz9K7nNRGdQoXU7r8lmhw3bkgNcMBrqs4M96GPNgAT4vUrimKcBZqI83tx7OJVbXCd70uny3GHTZstDHZ + pex0BuwmlfNJ + wTAa4Xz5y4UWPsE4dfYnYUPdHJiKD7lvnEbNkJnQ / RH4GcJi2TttZQBoQPsuBjOTPeoAIRuVp9lUX + 6QF ++ AovWFflLa4LPS5PEBbsHnwqhjN53 / Jk9uIe1BnuMC / 5DC / WL6X1DdZEBac5 / jxPa6WFbs1 + 5 / + hCGM7gC0CrSKgWoE6BPRKMAGriy UYq25ydFtMHmiOwUGaUF + z3PKYX8fZZqWukR26d4 + qnHZWK6a / jjHUlwvImDCByuVimhuCJAmfi8kX2GNd1vUQ6uT + FSE1PYFaOjoYkS / xfgADdqBLB3Q / cW3Amas + 4hXNpr2lJ6OCA35DleH7Godt9GqD6 + 6kdpnZtUdpluy5RzaOugMqZhk5gcV8sZxXmn4iIoKQtzsBA + 9ZBN1WqBWWtJyFjfkk53dVIqkbYMQhI7VvqK6ek5T / IGgZTEkiITPVeKxtqaXBNDbdk6uGffXCr1EV6NRt1EmpVqnbN22mpPWds43t9Nqb6fV4E6XxRUPdUrBWuY9pCRsWQRS4hcYxi3ksQvnA3d9dow01tsB4Pw6wiTvN9oBJi2rqB2S6nx6GDIrHLji7Aj1s74dV7C3yzPQTfNYZNfpBbSUNxfZ1MXRXN7xxzfoZzMh1NPqTXnUw1YbuX7yGp + V5G + qJN9NSZgEim + C9M / 0K5SLSOaHQuJmvfFSf2a0djMa7U6HVd1yeJ7srnXU6tJZi9F + UizclPvsf1hQVRHnP9bE6VbF6dKlK / bheHaXKQlvl + aN7J6LkRYY6QEjfS7GvsDYHzD2s0ZnmD + NrUqEQeF7hrsk2J2yu2yW74outrPDOGsgnrMRixsW6Lgxbs + wYCWTgi30W + XuZVi8P2uXmT7jprzOqdM9lZ9PRzkxC9vYZdDVbY4yYEyo5 + FayjyY + unoFso1V1BvBQ + N7rhxiQT1V / dp09dkOhpPxyPn6vr69 / GrowwPNRyoLq + vyCtn / PrauRpPRq9HV1ezhsb5RouZ0jdlx7naY7HSbTaoctMSbCsZhffMl4zFGETaWjsbTUbwWEemqmrXLOo9HUqZMNbQGuhooMJIs2zUMUcVzDUakMKnR8L0EIbGF1iKn1r6OHEzOG + 5GXSgAapdCk5HZUf0lP83fD0b2IPbWKUBe5NR / MHDTSQVSmSACRnqZBDoM8 / WW + L + YIq4sT6midvhgenW41vEvbvF4Oi + E7piN6BxDDOrJAgeIEEsBm9uh0BfY4OTAJyr / I9wOA9oqknWzpsP2SAh5HYIn00uFUXBNyoriP8C

这是地址。我如何选择红色圆圈？“var eventHandler = new Cesium.ScreenSpaceEventHandler（viewer.People.Canvas）; 
”通过此API方法无效

**Comment by OmarShehata** [comment]
I am able to add a click event with no errors by adding the code below:

```
var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
handler.setInputAction(function(result) {
    console.log(result.position);
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

It sounds like what you want is to be able to detect when the mouse is clicking over the circle and have it react to that click? I think the easiest way to do that would be to pass the mouse position, and whether it's clicked, as uniform(s) to the shader, and do this computation in your customer shader. In the future, for general questions like this, please use the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev
