### ISSUE TITLE
Cannot set property 'Autolinker' of undefined

### ISSUE THREAD

**Issue by wsw87201326** [AnalyticalGraphicsInc/cesium#7981]
when i use angular new version 8.1.0
new project with : ng new ngx-map -enableIvy=true --style=scss,
then npm cesium . edit angular.json to import the cesium,
then cesium error with : 
cesium.js:494 Uncaught TypeError: Cannot set property 'Autolinker' of undefined
    at cesium.js:494
    at c (cesium.js:444)
    at a (cesium.js:444)
    at c (cesium.js:444)
    at a (cesium.js:444)
    at c (cesium.js:444)
    at a (cesium.js:444)
    at c (cesium.js:444)
    at d (cesium.js:444)
    at cesium.js:535,
when i use angular version 7 is right.
so, what's the problem??

**Comment by shayb-datumate** [comment]
I'm having the same issue. How did you fix it?

**Comment by wsw87201326** [comment]
@shayb-datumate no,i still use angular7 with cesium
