### ISSUE TITLE
Label spacing

### ISSUE THREAD

**Issue by hulyayurtman** [AnalyticalGraphicsInc/cesium#7986]
Hi,
Is there a way that I can set the vertical label spacing size? Currently it automatically shows like this.
![image](https://user-images.githubusercontent.com/7858990/60861680-e4f00100-a223-11e9-9764-7695da6ac018.png)

**Comment by OmarShehata** [comment]
There's a number of ways you can tweak label positioning, including the `eyeOffset` and `pixelOffset` properties.

We try to keep general questions like this in the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) and use GitHub more for specific bug reports and feature requests. Feel free to post a follow up question there with a code sample and I'd be happy to take a look there!
