### ISSUE TITLE
How can I set clipping planes to primitive object?

### ISSUE THREAD

**Issue by TNMoOn** [AnalyticalGraphicsInc/cesium#7988]
Thanks a lot!

**Comment by OmarShehata** [comment]
There's a few code examples on Sandcastles showing this, here's one:

https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Clipping%20Planes.html

Please keep general questions like this on the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev. Feel free to post a follow up question there!
