### ISSUE TITLE
Firefox 68 cannot access layer.json on cesium home page

### ISSUE THREAD

**Issue by pedalpete** [AnalyticalGraphicsInc/cesium#7989]
Viewing cesium on https://cesiumjs.org tiles do not load and console shows error
`An error occurred in "x": An error occurred while accessing https://assets.cesium.com/1/layer.json.`

Sandcastle returned the error `An error occurred in "CesiumTerrainProvider": An error occurred while accessing https://assets.cesium.com/1/layer.json.`
Sandcastle example:  default & 3D tiles clipping planes. It seems to be somewhat random
Browser: FireFox 68

Operating System: Windows 10, our users (Ayvri) have experienced the issue on Mac and Linux Fedora

**Comment by pedalpete** [comment]
Looks like @OmarShehata is already on this with mozilla https://bugzilla.mozilla.org/show_bug.cgi?id=1559795#c18 

Closing this here.

**Comment by pedalpete** [comment]
The only way we can fix this issue is to create a proxy for the layers file and terrain data, which we would prefer not to do.  The issue alludes to Cesium fixing, so we'd like to be kept in the loop on how that is progressing and that something is being done.

**Comment by OmarShehata** [comment]
Yeah we are aware @pedalpete . We've had an issue open here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/184 where I believe Matt may be testing out a fix on the ion server side. Feel free to continue discussion/follow that issue.

**Comment by mramato** [comment]
Thanks @pedalpete we are actively looking into the issue.  While it is indeed a regression in Firefox, we believe we can work around it on our end.  Will hopefully follow up shortly with a fix.

**Comment by pedalpete** [comment]
Thanks guys, appreciate you keeping us up to date on this.

**Comment by mramato** [comment]
@pedalpete our workaround has been deployed and all versions of Firefox should be working again.  Thanks again for the heads up (I didn't realize they actually deployed 68 today with the regression still in place).

**Comment by pedalpete** [comment]
Great, thanks @mramato I've tested and it is working on our end. Thanks for the quick fix and congrats on the spin-out! Not the best day to have FF drop that change.

**Comment by mramato** [comment]
Thanks @pedalpete! If a browser regression is the biggest hurdle we face post spin-out, I'll take it :smile:
