### ISSUE TITLE
Cesium with Firefox 52 ESR doesn't show map

### ISSUE THREAD

**Issue by onderaltintas** [AnalyticalGraphicsInc/cesium#7995]
Sandcastle example: Any sandcastle example
Browser: Firefox ESR52
Operating System: Windows 10 / Linux

Hello there,

We have a compatibility problem with Cesium on Firefox 52ESR. It is no problem when it comes to windows since every program uses their own libraries so you can upgrade firefox version but on linux, firefox dependencies might require shared libraries that can affect other programs, so it is not possible to upgrade firefox for the sake of other installed programs. For every sandcastle example, the sphere is not visible. Also geometries are being added one by one so slowly. I can say "cesium doesn't support 52esr" but it is not written anywhere. 

On colsole, the examples give: 
"
Use of getAttributeNode() is deprecated. Use getAttribute() instead.  dom-attr.js:36:38
TypeError: widget is undefined[Learn More]  popup.js:252:5
	PopupManager<.open https://cesiumjs.org/Cesium/ThirdParty/dojo-release-1.10.4/dijit/popup.js:252:5
	openGalleryTooltip https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/CesiumSandcastle.js:331:13
Error: WebGL: texImage2D: Conversion requires pixel reformatting.  Cesium.js:87755:17
Error: WebGL: texImage2D: Conversion requires pixel reformatting. Cesium.js:87301:17
"

**Comment by OmarShehata** [comment]
Just to confirm, do you the same issue in Firefox ESR 52 in both Windows and Linux? Does the issue exist in the latest version of Firefox as well? Does it produce a similar issue in Chrome?

Can you paste the results of https://webglreport.com/ for you here?

**Comment by mramato** [comment]
FYI Mozilla states that Firefox 52 ESR is end of life and should not be used: https://www.mozilla.org/en-US/firefox/organizations/ What Linux OS are you on that you don't think upgrading is an option?  I've had successful installing FF directly from Mozilla on a variety of systems with little issue.

We can certainly look into this, but we tend to only support browsers that are in turn being supported themselves.

**Comment by onderaltintas** [comment]
1- WebGLreport console says that $ is not defined. It is normally defined in chrome browsers but not defined in firefox browsers. So the screen is all black with moon background. Could you change it to make it work with firefox as well?

2- Yeah I know that it is not the most recent browser. On the other hand, 60.8esr (which works perfectly with cesium) released 2-3 days ago. But on centos when you try to install gtk 3.4+ versions (which is dependency for latest esr) there is a risk that you can broke some programs that uses older gtk. You can understand that trying firefox versions one by one in an isolated area with linux is not an easy job.

**Comment by shunter** [comment]
In WebGLReport, $ comes from jQuery which is loaded from cdnjs.  Is your version of Firefox blocking that request to load jQuery?

**Comment by onderaltintas** [comment]
Okay I fixed the situation for webglreport at my side. The report says supported for both webgl1 and webgl2. Unfortunately I cannot upload images. It might be better to investigate the situation further when I hit back to home.

Webgl1 report:
Platform: 	Win64
Browser User Agent: 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
Context Name: 	webgl
GL Version: 	WebGL 1.0
Shading Language Version: 	WebGL GLSL ES 1.0
Vendor: 	Mozilla
Renderer: 	Mozilla
Antialiasing: 	Available
ANGLE: 	Yes, D3D11
Major Performance Caveat: 	No
Vertex Shader
Max Vertex Attributes: 	16
Max Vertex Uniform Vectors: 	4096
Max Vertex Texture Image Units: 	16
Max Varying Vectors: 	30
Best float precision: 	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range: 	[1, 1]
Aliased Point Size Range: 	[1, 1024]
Fragment Shader
Max Fragment Uniform Vectors: 	1024
Max Texture Image Units: 	16
float/int precision: 	highp/highp
Best float precision: 	[-2127, 2127] (23)
Framebuffer
Max Color Buffers: 	8
RGBA Bits: 	[8, 8, 8, 8]
Depth / Stencil Bits: 	[16, 8]
Max Render Buffer Size: 	16384
Max Viewport Dimensions: 	[32767, 32767]
Textures
Max Texture Size: 	16384
Max Cube Map Texture Size: 	16384
Max Combined Texture Image Units: 	32
Max Anisotropy: 	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
	ANGLE_instanced_arrays
	EXT_blend_minmax
	EXT_color_buffer_half_float
	EXT_frag_depth
	EXT_shader_texture_lod
	EXT_texture_filter_anisotropic
	EXT_disjoint_timer_query
	OES_element_index_uint
	OES_standard_derivatives
	OES_texture_float
	OES_texture_float_linear
	OES_texture_half_float
	OES_texture_half_float_linear
	OES_vertex_array_object
	WEBGL_color_buffer_float
	WEBGL_compressed_texture_etc1
	WEBGL_compressed_texture_s3tc
	WEBGL_depth_texture
	WEBGL_draw_buffers
	WEBGL_lose_context
	MOZ_WEBGL_lose_context
	MOZ_WEBGL_compressed_texture_s3tc
	MOZ_WEBGL_depth_texture...

webgl2 report:
Platform:	Win32
Browser User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Context Name:	webgl2
GL Version:	WebGL 2.0 (OpenGL ES 3.0 Chromium)
Shading Language Version:	WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc.
Unmasked Renderer:	ANGLE (NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0)
Antialiasing:	Available
ANGLE:	Yes, D3D11
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	4096
Max Vertex Texture Image Units:	16
Max Varying Vectors:	30
Best float precision:	[-2127, 2127] (23)
Max Vertex Uniform Components:	16384
Max Vertex Uniform Blocks:	12
Max Vertex Output Components:	120
Max Varying Components:	120
Transform Feedback
Max Interleaved Components:	120
Max Separate Attribs:	4
Max Separate Components:	30
Rasterizer
Aliased Line Width Range:	[1, 1]
Aliased Point Size Range:	[1, 1024]
Fragment Shader
Max Fragment Uniform Vectors:	1024
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Max Fragment Uniform Components:	4096
Max Fragment Uniform Blocks:	12
Max Fragment Input Components:	120
Min Program Texel Offset:	-8
Max Program Texel Offset:	7
Framebuffer
Max Draw Buffers:	8
Max Color Attachments:	8
Max Samples:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	16384
Max Viewport Dimensions:	[16384, 16384]
Textures
Max Texture Size:	16384
Max Cube Map Texture Size:	16384
Max Combined Texture Image Units:	32
Max Anisotropy:	16
Max 3D Texture Size:	2048
Max Array Texture Layers:	2048
Max Texture LOD Bias:	2
Uniform Buffers
Max Uniform Buffer Bindings:	24
Max Uniform Block Size:	65536
Uniform Buffer Offset Alignment:	256
Max Combined Uniform Blocks:	32
Max Combined Vertex Uniform Components:	212992
Max Combined Fragment Uniform Components:	200704
Supported Extensions:
EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context

To see draft extensions in Chrome, browse to about:flags, enable the "Enable WebGL Draft Extensions" option, and relaunch.

WebGL 2 Functions Implementation Status:
88 of 88 new functions implemented.

copyBufferSubData
getBufferSubData
blitFramebuffer
framebufferTextureLayer
getInternalformatParameter
invalidateFramebuffer
invalidateSubFramebuffer
readBuffer
renderbufferStorageMultisample
texStorage2D
texStorage3D
texImage3D
texSubImage3D...

**Comment by onderaltintas** [comment]
Greetings,

Sorry for taking your times, I just checked the same situation with same props @home. As it turns out security was blocking the tiles and I could not even got any network error messages. I'll close it here and next time will check it in more precisely.
