### ISSUE TITLE
How to display custom ellipsoid data in cesium current version(1.59)

### ISSUE THREAD

**Issue by wenjiangchun** [AnalyticalGraphicsInc/cesium#8000]
Hi, I want to show the image data of the moon.When I refer to the code [#4245](https://github.com/AnalyticalGraphicsInc/cesium/issues/4245)
```
var ellipsoid = Cesium.Ellipsoid.MOON;

    var imagery = new Cesium.SingleTileImageryProvider({
        ellipsoid: ellipsoid,
        url: Cesium.buildModuleUrl('Assets/Textures/moonSmall.jpg')
    });

    var viewer = new Cesium.Viewer('cesiumContainer', {
        mapProjection: new Cesium.GeographicProjection(ellipsoid),
        imageryProvider: imagery,
        selectionIndicator : false,
        infoBox : false,
        baseLayerPicker: false,
        geocoder: false,
        skyAtmosphere: false
    });
```
![1](https://user-images.githubusercontent.com/3843344/61203174-387ab700-a71c-11e9-9326-4ec175a6fe9d.gif)
3D can't be displayed. When I switch to 2D, the data can be displayed. But when I switch from 2D to 3D, the sphere display disappears. Does that happen when the ellipsoid definition value is too small? If the larger value in the defined Ellipsoid(Just like Jupiter's ellipsoid[ 'x': 71492000.0,'y':71492000.0, 'z': 66864000.0) can be displayed, how can I solve this problem?

（**Cesium current version 1.59, when I used version 1.48, it showed normal**.）

**Comment by OmarShehata** [comment]
I think you just need to turn off the groundAtmosphere:

```
viewer.scene.globe.showGroundAtmosphere = false;
```

I looked at this bug report for reference which also used a lunar ellipsoid: https://github.com/AnalyticalGraphicsInc/cesium/issues/7552.

I'll make a note in the issue you linked to about this. Thanks for reporting it!
