### ISSUE TITLE
SVG doesn't render in billboard when embedded image tag is used in SVG

### ISSUE THREAD

**Issue by bbehling-trimble** [AnalyticalGraphicsInc/cesium#8002]
I'm trying to use an SVG with an image tag in it. When I use the SVG as a billboard, the image is not rendered in the SVG.

The image is rendered in the SVG when not used in a billboard.

Some business requirements are mandating we have a dynamic image based on some conditions, so have to generate the SVG dynamically. Billboards have to be used for clustering.

```
Projects.createSvg(url).then(canvas => {
              debugger;
              //cluster.billboard.image = canvas;

              const billboardEntity = {
                position: Cartesian3.fromDegrees(
                  point.geometry.coordinates[0],
                  point.geometry.coordinates[1]
                ),
                id: point.properties.projectId,
                name: point.properties.projectName,
                billboard: {
                  image: canvas,
                  heightReference: HeightReference.CLAMP_TO_GROUND,
                  disableDepthTestDistance: Number.POSITIVE_INFINITY,
                  color: new Color(1.0, 1.0, 1.0, 1)
                }
              };
  
              this.dataSource.entities.add(billboardEntity);

            });
```

```
static async createSvg(value) {
     debugger;
    const canvas = document.createElement('canvas');
    canvas.width = 54;
    canvas.height = 54;

    const svgString = `<?xml version="1.0" encoding="UTF-8"?>
    <svg width="500" height="250">
        <defs>
            <clipPath id="circleView">
                <circle cx="250" cy="125" r="125" fill="#FFFFFF" />            
            </clipPath>
        </defs>
        <image width="500" height="250" xlink:href="/static/media/project-default-1.2abe131c.svg" clip-path="url(#circleView)" />
    
    </svg>`;

    const image = new Image();
    image.src = 'data:image/svg+xml;base64,' + window.btoa(svgString);
    await new Promise((resolve, reject) => {
      image.onload = () => resolve(canvas);
    });

    canvas.getContext('2d').drawImage(image, 0, 0);
    return canvas;
  }
```

**Comment by OmarShehata** [comment]
Are you able to replicate this issue in Sandcastle @bbehling-trimble ? I seem to be able to render an SVG to a billboard [in this code example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVJRb5swEP4rFn0IUVIDKasioFG17GXSpD1U2hMvBg6wamxkG0g25b/vDGnTbgaJu+/uuzs+38g0GTlMoMkTkTCRIxg+dPTXjPmrcnaPSlrGJejVOs1lLkdkmbFByipz34lXtn3KvXjfn3KPtMCb1t581+CrOiEQkpDEe3wdCtpwJRGNaIT+qRPSoNda2ydBME0TnR6o0k2wC8MwwD65d1hhf9dx41qXXJcCSOkq72IsUZ7fLO3KhmgYexaATs2FSO7qOoojSI3V6hXu57GTXX+6AskdlO5JkRd8buXaz8iCIVQxyxLesQZcbIPTpwUz8BhvV2SDishKTbSwivkYvsk2M65af3e2v8RmnCopFKswXA+ytKiOvyZ/cknwLLdEQVpuORjKqsq/hvD0ynCXT5K3GzwybdFi8oHWWnXfoNEAxr/ff9mSOFxv36kFKlMopiuS3Oq5s4yaLN/3yGWxLm7sy4fRjS5xbvzX1Nt62Sz7YUl95l2vtCWDFj6lgYWuFwxnC4qhfAVLS2NcMdT4SsoqPhJe4a39s37uigUzbkvqQYgX/htwJ7IA8z/RnIhcNj9xxQQ7u5Q2OvxYQEppFqD7P8sqJQqmP1T8Cw).

**Comment by bbehling-trimble** [comment]
Hi Omar.

The problem is rendering an SVG with an image tag inside it.

**Comment by OmarShehata** [comment]
@bbehling-trimble I don't this is a CesiumJS issue. A base64 encoded SVG with an embedded image used as a source for an image element does not seem to be something browsers consider valid. You can see that the image actually fails to load before it reaches any Cesium code by checking for the onerror event:

```
image.onerror = function() {
    console.log("Failed to load");
};
```

Does it work when you draw the SVG to a canvas and then use the canvas as the source for the billboard?

**Comment by OmarShehata** [comment]
> The SVG loads in the sandbox's index page displaying the embedded image, but the same SVG doesn't load in the billboard.

Notice that what you're testing in the HTML is the SVG directly:

```
 <svg width="500" height="250">
    <defs> <clipPath id="circleView"><circle cx="250" cy="125" r="125" fill="#FFFFFF" /> </clipPath></defs><image width="500" height="250" xlink:href="https://cdn4.vectorstock.com/i/1000x1000/28/23/map-point-icon-on-white-background-pin-sign-for-vector-22422823.jpg" clip-path="url(#circleView)" />
</svg>
```

But what you're trying to load is an image tag with that SVG as a base64 encoded source:

```
var svg = '<svg width="500" height="250">';
svg += '<defs> <clipPath id="circleView"><circle cx="250" cy="125" r="125" fill="#FFFFFF" /> </clipPath></defs><image width="500" height="250" xlink:href="https://cdn4.vectorstock.com/i/1000x1000/28/23/map-point-icon-on-white-background-pin-sign-for-vector-22422823.jpg" clip-path="url(#circleView)" />';
svg += '</svg>';
svg = 'data:image/svg+xml;base64,' + window.btoa(svg);

var image = new Image();
image.src = svg;
```

The browser fails to load this. If you try that directly in the HTML it fails too` <img src="...base64 encoded SVG with embedded image here.." />`.

**Comment by bbehling-trimble** [comment]
Sorry, typo.

Fixed the SVG so it should be the same string as in the HTML.

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=7VPdq9owFP9XgvdBZTbRqiDeXhk4BoPBBhf25EtM0/bMNClJrLrh/76Txo8rgw32vNOSnO/8zjlJyy1pQR6kJS9EywNZSwf7mn7rdIO+6MS10Z6DlrY/fN7o8LUY59oSg/pZ2A+Q++pl05uPx5seqSSUlUcxnaO46mNQcHoXvHNZuBXJhILmK/cVgRz9BFihZDgU3bMoEXG8ZiDihOwknSNrb1wBSqHw9LEjVDDMy66JVxnrjsqg5qX8I0ByVKB3y8rKAlWV941bMiZyPaOtFN5Y543YUWFqBmwyHo+PYWHpgqVTVvMmaQxon4AwOsH/UIGXyZaLXWnNXudJAzpxUOqkMDaJGZM0naXpIp3S700ZCkTUScM7iHurBk/3jgy7yh56yJDrNPdhxCrjDD8FfhBH1emp0crwHM3FXgsPRg+G5OdGE6Q4fSq1Bw/SUZ7ng4sJqTEOgj9ZXm/GmluPHNdTWlhTf5ClldINksV8RGbj4egWusXxbA23OVne8wWKUJdxv1nOkTsH2Oc30J0ViBsLfu6NepnzJyVX0fU91I2xnoR+Ucq8rBvFERvb7sVOeiqcC8mwW5egLIf2ct8er3U3AO4cWoq9Uq/wQ4Z7yND/ISw0EXT5pZVW8VNwqSarz1FJKc0Yir9HeWPUlts3GRH/31/NvWf/38y/vZnYwbjGN7PRvwA

**Comment by OmarShehata** [comment]
@bbehling-trimble this is still not a valid image element. Notice that `image.onload` never runs. You can see that it fails to load by creating an `image.onerror` callback. In the HTML, you have:

```
<svg width="500" height="250">
      <defs> <clipPath id="circleView"><circle cx="250" cy="125" r="125" fill="#FFFFFF" /> </clipPath></defs><image width="500" height="250" xlink:href="https://cdn4.vectorstock.com/i/1000x1000/28/23/map-point-icon-on-white-background-pin-sign-for-vector-22422823.jpg" clip-path="url(#circleView)" />
 </svg>
```

But what you're trying to load would be something like:

```
<img src="data:image/png;base64, PHN2ZyB2ZXJzaW9uPSIxLjEiDQogICAgIGJhc2VQcm9maWxlPSJmdWxsIg0KICAgICB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCINCiAgICAgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4NCiAgPGRlZnM+IDxjbGlwUGF0aCBpZD0iY2lyY2xlVmlldyI+PGNpcmNsZSBjeD0iMjUwIiBjeT0iMTI1IiByPSIxMjUiIGZpbGw9IiNGRkZGRkYiIC8+IDwvY2xpcFBhdGg+PC9kZWZzPjxpbWFnZSB3aWR0aD0iNTAwIiBoZWlnaHQ9IjI1MCIgaHJlZj0iaHR0cHM6Ly9jZG40LnZlY3RvcnN0b2NrLmNvbS9pLzEwMDB4MTAwMC8yOC8yMy9tYXAtcG9pbnQtaWNvbi1vbi13aGl0ZS1iYWNrZ3JvdW5kLXBpbi1zaWduLWZvci12ZWN0b3ItMjI0MjI4MjMuanBnIiBjbGlwLXBhdGg9InVybCgjY2lyY2xlVmlldykiIC8+DQo8L3N2Zz4=" />
```

Which is the base64 encoded version of the SVG. Notice that that fails to load in any HTML. So this is not a CesiumJS issue.

I would first try to get it working outside of CesiumJS to limit the scope of the issue (for example, you can try adding the image tag to the page directly, instead of adding it to an entity).
