### ISSUE TITLE
new Mapbox Style API

### ISSUE THREAD

**Issue by sunday60004** [AnalyticalGraphicsInc/cesium#8008]
I saw the 1.59 version update log: Added support for new Mapbox Style API.
Does this mean loading Mapbox Vector Tiles and configuring styles using mapbox style api?

**Comment by OmarShehata** [comment]
@sunday60004 yes! You should be able to create your Mapbox style and then load it in CesiumJS. Vector tiles still aren't directly supported but I believe they get rasterized on the server before they're sent (see my comment here: https://github.com/AnalyticalGraphicsInc/cesium/pull/7698#issuecomment-507276334).

In the future, for general questions like this please use the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev
