### ISSUE TITLE
Removing Cesium from ESLint

### ISSUE THREAD

**Issue by jad4580** [AnalyticalGraphicsInc/cesium#8013]
Hi, so I'm currently using Vue to create a project. Inside of the main HTML file, I simply added 
the CesiumJS library in the main HTML file's head section:

`<script src="https://cesiumjs.org/releases/1.59/Build/Cesium/Cesium.js"></script>`   
`<link href="https://cesiumjs.org/releases/1.59/Build/Cesium/Widgets/widgets.css" rel="stylesheet">`

When I run the application, it seems to work fine, but an abundance of errors pop up in the command line window, most of which saying "'Cesium' is not defined (no-undef)...". I'm guessing this is because I didn't install Cesium through npm and didn't import it into the files where Cesium is used. 

Is there anyway I can disable these errors?

**Comment by OmarShehata** [comment]
This sounds like the `eslint` in your setup is complaining about the use of the global `Cesium` not being explicitly defined. I think you should be able to add an exception for it or do something like `window.Cesium = Cesium`.  In any case, I don't think it's a bug in the library, so feel free to start a thread in the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) if you're still having issues and I'll be happy to take a look there!
