### ISSUE TITLE
How to increase the brightness of material in 2D mode as well as in 3d mode?

### ISSUE THREAD

**Issue by huochaimindy** [AnalyticalGraphicsInc/cesium#8014]
I want to load GeoJson file, when i load it in 3D mode, the brightness of material is ok. however, when i load it in 2D mode, the brightness of material is very low, how can i increase the brightness in 2D mode as well as in 3d mode?
following picture is in 2d mode, red color is very dark
![2d](https://user-images.githubusercontent.com/49577646/61507926-56952f80-aa1a-11e9-952b-fb0d8e205d2b.png)

following picture is in 2d mode, red color is ok
![3d](https://user-images.githubusercontent.com/49577646/61507927-585ef300-aa1a-11e9-9917-2d693ab2b5a5.png)

Here is my code in 3D:

<script> var viewer = new Cesium.Viewer('cesiumContainer', { sceneMode: 3 }); var promise = Cesium.GeoJsonDataSource.load('grid222.geojson', { clampToGround: true }); promise.then(function(dataSource) { viewer.dataSources.add(dataSource); var entities = dataSource.entities.values; for (var i = 0; i < entities.length; i++) { var entity = entities[i]; entity.polygon.height = 0.0; } }); viewer.flyTo(promise); </script>

Here is my code in 2D:

<script> var viewer = new Cesium.Viewer('cesiumContainer', { sceneMode: 2 }); var promise = Cesium.GeoJsonDataSource.load('grid222.geojson', { clampToGround: true }); promise.then(function(dataSource) { viewer.dataSources.add(dataSource); var entities = dataSource.entities.values; for (var i = 0; i < entities.length; i++) { var entity = entities[i]; entity.polygon.height = 0.0; } }); viewer.flyTo(promise); </script>
here is geoJson text:
{
	"type" : "FeatureCollection",	
	"features" : [{
			"type" : "Feature",
			"geometry" : {
				"coordinates" : [[[114.37999106868926, 36.0854368313549], [114.37999106868926, 36.087285894830124], [114.38214958987339, 36.087285894830124], [114.38214958987339, 36.0854368313549], [114.37999106868926, 36.0854368313549]]],
				"type" : "Polygon"
			},
			"properties" : {	 
                "fill" : "#FF0000",
				"fill-opacity" : 1,
				"stroke-width" : 1,
				"stroke" : "#FF0000",
				"stroke-opacity" : 1            
			}
		}		
	]
}

**Comment by OmarShehata** [comment]
I think you need to turn off HDR to get the expected color, see https://github.com/AnalyticalGraphicsInc/cesium/issues/7966. 

For general questions like this, please post a thread in the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev).

**Comment by huochaimindy** [comment]
@OmarShehata 
After I turn off HDR, like the following code 
viewer.scene.highDynamicRange = false,
The brightness of material color in 2D is also very dark, it looks no effect , Is there any other suggestions? thanks!

**Comment by OmarShehata** [comment]
Actually, it may be this issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/5730 which means you'd need to try changing the time of day to set the sun position overhead.

I also have other recommendations in this forum thread about how to control the sun position and other lighting factors @huochaimindy https://groups.google.com/d/msg/cesium-dev/XbeJ1fRlKAA/NhlUtL-CBAAJ

**Comment by huochaimindy** [comment]
It worked well by your suggestions.  Thanks! @OmarShehata

**Comment by hyman4hu** [comment]
> It worked well by your suggestions. Thanks! @OmarShehata

Can you tell me how you solved this problem? I have been troubled for several days and tried many methods.

**Comment by OmarShehata** [comment]
@hyman4hu have you tried the recommendations here https://github.com/CesiumGS/cesium/issues/8014#issuecomment-514204283 ?

If you're still having trouble please open a new topic in the Cesium community forum: https://community.cesium.com/
