### ISSUE TITLE
why it is so slow?

### ISSUE THREAD

**Issue by cpgood** [AnalyticalGraphicsInc/cesium#8015]
Hello! I am a Cesium beginner and I have a problem.
I copied the code here form (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Styling.html), but it didn't work smoothly, and he was very slow compared to the example. Is there anything I need to modify? Thank you!

my code is there (https://gist.github.com/cpgood/da181cfcfe12756716980540625a6b86)

**Comment by OmarShehata** [comment]
Do you mean slow to load, or slow runtime performance? What kind of dataset are loading in? You can set `viewer.scene.debugShowFramesPerSecond = true;` to see the frames per second. What number are you seeing?

In the future, please use the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) for general questions like this. We use GitHub for specific bugs or feature requests.

**Comment by mrbankim** [comment]
Hi.. in the web it is better but if I run the app on ios simulator then it is very slow. The number is showing for iOS simulator 900.00 MS and 0 FPS sometime 2 FPS. I am using IONIC framework for my project.
