### ISSUE TITLE
Clamped to ground arrow polyline renders a regular line between the first 2 positions

### ISSUE THREAD

**Issue by lpww** [AnalyticalGraphicsInc/cesium#8017]
Hey! 

I'm running into an issue with arrow polylines that are clamped to the ground. The first 2 points do not show an arrow between, just a regular line. This line is the expected width in pixels. The remaining positions do have an arrow but with an unexpectedly small line. 

A workaround could be to add heights to your Cartesians. It doesn't work well for my use case but could help others.

It seems related to https://github.com/AnalyticalGraphicsInc/cesium/issues/7645 but the weird thing is that the example they have shows an arrow even between 2 points! 

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZZLbjtMwEIZfxQoX7UrBdQ4+hW4FqhA3i6hg4YZw4TZma+HYkeO026767jgH2LL4KjPzf/94PDkIBw5KHqUDt8DII1jLVnU1/Dbk5rPdEK6t8UIZ6WY3b0pTmkOgms41Wr5zzh4DOnpAabzySrZQVNX8qTQgHCNqCQow2wwAaL0T6mHvgRhQ4cFe9vEsHuWN1ScdegVkMuhPaXZWW1eAMnqVELGVWRnFz+WdFnVzbz8425mqAN51MlRr4aVTQhfXk20m/+HmHyfFxtlGOn+aT6J13wxuvn7e3L2/CU6NbcNc1rQF+P70WIDXKUWIpgnMc5bSjHEeg1NI5ylBmDKYIUIpQwmOwbkAGQsCnkGGGUk5peQSg78uJEV9ATGWZ8mVS9BzjjFOw9fkwhEKLTmmKGRpfu2CeQIpIjnHeXLlQkgKGclRnmZ59nwXlkCcI0wQyvjlR5jvqCq/L0CKpje9lOYyrXpc7Nna+t7OX6y5l0RxtGz9ScvViL5VdWOdB53TcwgXXtaNDq/cLrbd7pf0cNcO2HLxB1pW6gBUdVtGL362Mur32rah8rPT+os6yzJaLRdB/w+mraiUefh0kE6LUy/ZJ6u7MQkhXC5C+D/lrdVb4a4cfwM

Browser: firefox, chrome

Operating System: linux

**Comment by likangning93** [comment]
Thanks @lpww! Here's what I'm seeing, also on Linux:

![Screenshot_20190722_065918](https://user-images.githubusercontent.com/5395255/61627706-6bf29f80-ac4e-11e9-8fa3-e326f532c476.png)

We actually just happened to run into this on another project too. It seems to be related to how some WebGL implementations handle floating-point vertex attributes with a value of infinity. A fix should be available shortly.

**Comment by lpww** [comment]
That's great news! Thanks @likangning93 :+1:
