### ISSUE TITLE
czm_materialInput  materialInput.positionToEyeEC  Does not work

### ISSUE THREAD

**Issue by ran125** [AnalyticalGraphicsInc/cesium#8018]
customShaderSource= `
    czm_material czm_getMaterial(czm_materialInput materialInput)
    {
    czm_material material = czm_getDefaultMaterial(materialInput);
    material.diffuse = normalize(materialInput.positionToEyeEC);
    material.alpha = 1.0; 
    return material;
    }`;
 var cartesian3 = new Cesium.Cartesian3( -2607902.520854573, -1386219.1804484087, 5634175.562991936);
    var ellipsoid = viewer.scene.globe.ellipsoid;
    var cartographic = ellipsoid.cartesianToCartographic(cartesian3);
    var minH = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, Number(viewModel.minHeight));
    //最高高度
    var maxH = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, Number(viewModel.maxHeight));
    var fabric = {
        type: 'MyNewMaterial',
        uniforms: {
            color: Cesium.Color.YELLOW,
            image: 'colors.png',
            maxHeight: viewModel.maxHeight,
            width:100,
            // u_NormalEC: {
            //     x:1.0,y:0.0,z:1.0
            // },
            // u_CenterEB: new Cesium.Cartesian3(1.0, 1.0, 1.0),
            // u_CenterEC: new Cesium.Cartesian3(1.0, 1.0, 1.0),
            u_point0: {
                x: -2607902.520854573,
                y: -1386219.1804484087,
                z: 5634175.562991936
            },
            u_point1: {
                x: -2564703.5701839165,
                y: -1401632.6195028438,
                z: 5650062.551804534
            },
            u_point2: {
                x: -2561563.503341591,
                y: -1385316.2495589675,
                z: 5655472.073867392
            },

        },
        source: customShaderSource
        //剩余JSON值
    };
    
    var material = new Cesium.Material({
        fabric: fabric,
        translucent: false
    });
   
    var globe = viewer.scene.globe;
    globe.depthTestAgainstTerrain = true;
    globe.material = material;

**Comment by ran125** [comment]
I want to get the vertex information in the shader of the custom material.  But materialInput.positionToEyeEC has no effect in the custom shader.

**Comment by OmarShehata** [comment]
Please post your question on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev). We use GitHub for bug reports and specific feature requests.

It would also help to put together a complete Sandcastle code example (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) that we can run.
