### ISSUE TITLE
How does the billboard in czml keep spinning?

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#8019]
var rotation = Cesium.Math.toRadians(1);

  function getRotationValue() {
        rotation += 0.05;
        return rotation;
  }
var billboard =  new Cesium.BillboardGraphics({
          image: "../../Sandcastle//images/facility.gif",
          rotation: new Cesium.CallbackProperty(getRotationValue, false),
          stRotation: new Cesium.CallbackProperty(getRotationValue, false),
          scale: 1
        });
var czml = [{
    "id" : "document",
    "name" : "Basic CZML billboard and label",
    "version" : "1.0"
}, {
    "id" : "some-unique-id",
    "name" : "AGI",
    "description" : "<p><a href='http://www.agi.com' target='_blank'>Analytical Graphics, Inc.</a> (AGI) founded Cesium.</p>",
    "billboard" :billboard,
    "position" : {
        "cartesian":[
            1216361.4096947117, -4736253.175342511, 4081267.4865667094
        ]
    }
}];

var viewer = new Cesium.Viewer('cesiumContainer');
viewer.dataSources.add(Cesium.CzmlDataSource.load(czml));

////////error////////////////
Error loading image for billboard: RangeError: Maximum call stack size exceeded

**Comment by OmarShehata** [comment]
It looks like you're creating a new billboard recursively here. If you're looking for an example on how to use a CallbackProperty, check out this code example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Callback%20Property.html

In the future please use the Cesium forum for general questions like this (https://groups.google.com/forum/#!forum/cesium-dev). We use GitHub for specific bug reports or feature requests.
