### ISSUE TITLE
Camera flight path in Columbus View ends at wrong destination

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#802]
In Columbus view, if the camera is zoomed out further than the default camera position it doesn't fly to the default camera position if it is given as the destination.  The position at the end of the flight remains further zoomed out than the default.

Sandcastle example:

<pre><code>require([
    'Cesium', 'dijit/form/Button'
], function(
    Cesium, Button) {
    "use strict";
    var ellipsoid = Cesium.Ellipsoid.WGS84;

    function fly() {
        //move camera to position further than default
        widget.scene.getCamera().position = new Cesium.Cartesian3(0, -38370635.91011722, 38404680.99332635);

        var maxRadii = ellipsoid.getMaximumRadius();
        //default position
        var position = new Cesium.Cartesian3(0.0, -1.0, 1.0).normalize().multiplyByScalar(5.0 * maxRadii);
        var direction = Cesium.Cartesian3.ZERO.subtract(position).normalize();
        var right = direction.cross(Cesium.Cartesian3.UNIT_Z);
        var up = right.cross(direction);
    
        var description = {
            destination: position,
            up: up,
            direction: direction
        };
    
        var flight = Cesium.CameraFlightPath.createAnimation(widget.scene.getFrameState(), description);
        widget.scene.getAnimations().add(flight);
    }
    
    function createButtons(scene) {
        new Button({
            label : "Zoom out, then fly to default position",
            onClick : function() {
                fly(scene);
            }
        }).placeAt('toolbar');
    }

    var widget = new Cesium.CesiumWidget('cesiumContainer');
    var transitioner = new Cesium.SceneTransitioner(widget.scene, ellipsoid);
    transitioner.morphToColumbusView();
    createButtons(widget.scene);
    Sandcastle.finishedLoading();
});</code></pre>

**Comment by bagnell** [comment]
Updated code sample:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', { sceneMode : Cesium.SceneMode.COLUMBUS_VIEW });
var scene = viewer.scene;

function fly() {
    var maxRadii = scene.globe.ellipsoid.maximumRadius;
    var position = new Cesium.Cartesian3(0.0, -1.0, 1.0);
    Cesium.Cartesian3.multiplyByScalar(Cesium.Cartesian3.normalize(position, position), 5.0 * maxRadii, position);
    var pitch = -Math.acos(Cesium.Cartesian3.normalize(position, new Cesium.Cartesian3()).z);

    scene.camera.flyTo({
        destination : position,
        orientation : {
            heading : 0.0,
            pitch : pitch,
            roll : 0.0
        },
        convert : false
    });
}

Sandcastle.addToolbarButton('Fly', function() {fly();});
```
Zoom out when loaded, then click the `Fly` button.
