### ISSUE TITLE
When Czml.DataSource.precess is called, the view will appear

### ISSUE THREAD

**Issue by JimmingSong** [AnalyticalGraphicsInc/cesium#8025]
初始加载2000个卫星,后续从websocket中持续读取数据通过Czml.DataSource.process方法往position属性中加入对应的坐标,这种情况下process方法 每调用一次,视图和currentTime会出现卡顿,卡顿的时长与播放速度有关

**Comment by OmarShehata** [comment]
@JimmingSong does the issue only appear if you have 2000 satellites loaded? 

Do you mean that the browser window itself freezes, or just that the timeline stops progressing? Are you able to reproduce this issue in Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) ? Can you provide a code example of what you're doing?
