### ISSUE TITLE
Create the same model in two different views on the same page

### ISSUE THREAD

**Issue by xiaobaogeit** [AnalyticalGraphicsInc/cesium#8030]
Create the same model in two different views on the same page, and only one will come out or none, or one will come out for a long time.

Browser: Google Chrome 版本 74.0.3729.131（正式版本） （32 位）
Cesium:1.57
Operating System: win10

**Comment by OmarShehata** [comment]
@xiaobaogeit can you share a Sandcastle code example that reproduces this issue?

Here's [one](https://cesiumjs.org/Cesium/Apps/Sandcastle/#c=zVjbcuI4EP0VFy/DVHmMMYSQa60wyWxmSchCkq2pOA/CFqCJsShZhmRT+fdt2TgYX7gku6n1k9V9unXULbUuM8yVGSVzwpUTxSNzxSQ+DSbaXSgrf7HDpsk8galH+BdVebE8BT7qDVmLPSmHyhC7PlEjqU9cYgvKvAvPoTYWjKcBY+ywuQ9SwYOlkAWugzw6wYIsVJb3+vXI8mZv/IytCBqfztDyhoEXelRsTkB9yRzilgPuqsqY0NFYqIsRfI2ZyUFNmU9Do5N4RCbmAv6wV9OGnE3aZMQJ8cvfqkZN0/fr9Ub1QFXqdU3f02v7eiP2LjnETscEO9QbLX1eYjHWBOuBGHt+uVrbS8KnVNhjAOsJGWeumxKNp6nJ8XvUzbU07wG+vOhXjTyqoZNkR4xTAglaHe8NB0pDxie+Nk45/DOAOHIP4OU4TqqkEcU79gouqXgGh1F4tbBNia9hxykvQi0/D09kzmRGlsK3+B++/Sa0ScKHyVYCM5F5Bm2iJ/kFnGY6C+EUZk8wuaZPxO3TvyWjqtFMg/CTBPVt7EqAocO3RLxGv69voY3GLTi2H4lzFocjigtgXmW0ZKQiqicxVauEfZ8Iq7RC3iqNCKwguSSkxiqZ3U4HtZHxvXNzbpXUJHJGuA/RiHCGplulBTU17sG3wZnU66siX8rul75S0bNKHnBNg+JPXxU9ZELz8NZZnptMX/aYug4nXkF31VR3atoeqgGnT0XWmq7mDOFTpd8+TuL/MAzgUJx5dU2CJ8Qfh5NwzUyRmM1TZcrpBKrErHBuvmRFi7UmYJIMAhFZFsAi6FW3d4k6ElZV1+Guu/2Lm4vulUQa+cBXtYgPlRtfREYvBMmKIRH1YoQs0RS7qfCmwly8dmRVjurHZZikNRnCNvD1Gd+YpEEwHBIujwZ5owP9syDd4XBR+7J6m02mzIP6efM8Dcntweabgwq80EGtkVMRisqBUdtYTai3Zd3LmIoFX6vUN1EH9VbCqW4dseq/ErFGccSM+g4Rq+5Qj7IVYofwFlTJNeLt83F3Ztb+o2wYzean5kPX9tQdpB/IR77PNeIP5COzHSzq2uYdYcAvicCuS+0eC0ZjONsUVXjIHPaJyVzGz7G9OGDd51dWXWvq4VetHhj6gXGgFuH0nTWZmZsXrXhXjIa25KunjV/X1PQecdZGeTnTtyzq2xT0vf1GLqJDvJEIzwH7RnZqYD6KzGv1g0Ztp5X6vl1mlVIR6T6cGqI9uLqJtLEx0JuDvMKpUc9WFrjXRKl1sMCHeDp15fUZLgEVZgsivvkCbr+TIznRG3UVJb8LVHlve9Rprqi2b5voep7U7Npe+Gs339k20Szlf7d2Mh5m5T3t0F8Uj7B9nWqH+nZK396Az/WX7s/cyt9Sbxb7W8NvlmffzuOTP95ZYX/mVvrrwvGG7ZacyGgOiUVnsnGO0E/UmqPvCN1K4Q+EGDLn6A+EHuGaja4QqqP2HHUR0sEC9VDrAp3NUR+1zqTxHWr9ROdz9Bdq3aK84goX/qP4xv/LD59afvS7VxqsTOqN6PC5HL4DxM9qA5cNFu86Lfgt30ubB1V5kZulXOjJNS51VuntSS7g8jlhDlcJNtduex0tevrqDn4RW0C7LJ1HrzWZR7E92Ntgh4ofxY42QgyJKamlY188u+Q0Gu1vFA46XEgmZU2rCDKZuuDErwwC+5EIzfZ9aXZciY2OHTpTqHMCp5/VJ0OrpCghCFTRk9phXdencAo6Pa6A0TpbA4y3tnVZ+MrVnRHu4mcJGVdPO5FQ07TjCjSzVoIxd4B5wuM/) that loads a simple model in two viewers that seems to work fine. You can replace this simple model with one of the more complex models from here: https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=3D%20Models.html or your own if you have it uploaded somewhere.

**Comment by OmarShehata** [comment]
I'm closing this now, but feel free to follow up here or on the [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev) and I'd be happy to help.
