### ISSUE TITLE
Error 3D Map - Type error : u is undefined.

### ISSUE THREAD

**Issue by PalluelLuis** [AnalyticalGraphicsInc/cesium#8038]
This error happens every time I zoom or move the map in 3D.

I have this error in Firefox :
![image](https://user-images.githubusercontent.com/28446415/62453536-cf162300-b772-11e9-8fc5-51d45ef3247b.png)

And this one in Chrome :
![image](https://user-images.githubusercontent.com/28446415/62453645-08e72980-b773-11e9-8550-33d087c6cf06.png)

I didn't find a solution on forums...  Have you an idea ?

Versions :
"@angular/core": "6.1.6"
"cesium": "^1.59.0"

**Comment by OmarShehata** [comment]
Have you tried running the unminified version of CesiumJS? That will give you a stacktrace with more details that could help us debug it.

Does this happen only in your application with Angular, or does it happen in Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) as well? Does it happen immediately after you move the map, or after a few seconds, or after a few minutes?

**Comment by PalluelLuis** [comment]
Thanks for your help.
I replaced the minified version by the unminified and it works, without any errors...

So thanks again, we can close this issue !
