### ISSUE TITLE
Camera flight path in 2D tries to fly through the map

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#804]
If the current camera position is closer to the globe than the destination, and the current position is not directly in front of destination (the path isn't a straight zoom-out, it is offset in some direction),  the camera flies through the map and generates an error of "right must be greater than left."

Sandcastle Example:  Click 'Vew Extent' then 'Fly To Extent'
<pre><code>require([
    'Cesium', 'dijit/form/Button'
], function(
    Cesium, Button)
{
    "use strict";
    var ellipsoid = Cesium.Ellipsoid.WGS84;
    function flyToExtent(scene) {
        var west = Cesium.Math.toRadians(-90.0);
        var south = Cesium.Math.toRadians(38.0);
        var east = Cesium.Math.toRadians(-87.0);
        var north = Cesium.Math.toRadians(40.0);

        var extent = new Cesium.Extent(west, south, east, north);

        var flight = Cesium.CameraFlightPath.createAnimationExtent(scene.getFrameState(), {
            destination : extent,
            onComplete : function() {
            }
        });
        scene.getAnimations().add(flight);
    }

    function viewAnExtent(scene) {
        var west = Cesium.Math.toRadians(-89.0);
        var south = Cesium.Math.toRadians(38.5);
        var east = Cesium.Math.toRadians(-88.0);
        var north = Cesium.Math.toRadians(39.5);

        var extent = new Cesium.Extent(west, south, east, north);
        scene.getCamera().controller.viewExtent(extent, ellipsoid);
    }

    function createButtons(scene) {
        new Button({
            label : "View Extent",
            onClick : function() {
                viewAnExtent(scene);
            }
        }).placeAt('toolbar');
        
        new Button({
            label : "Fly to Extent",
            onClick : function() {
                flyToExtent(scene);
            }
        }).placeAt('toolbar');
    }

    var widget = new Cesium.CesiumWidget('cesiumContainer');
    
    var transitioner = new Cesium.SceneTransitioner(widget.scene, ellipsoid);
    transitioner.morphTo2D();

    createButtons(widget.scene);

    Sandcastle.finishedLoading();
});
</code></pre>

**Comment by bagnell** [comment]
Updated code example:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', { sceneMode : Cesium.SceneMode.SCENE2D });
var scene = viewer.scene;
var ellipsoid = scene.globe.ellipsoid;

function flyToExtent() {
    var west = Cesium.Math.toRadians(-90.0);
    var south = Cesium.Math.toRadians(38.0);
    var east = Cesium.Math.toRadians(-87.0);
    var north = Cesium.Math.toRadians(40.0);

    var extent = new Cesium.Rectangle(west, south, east, north);
    
    scene.camera.flyTo({
        destination : extent
    });
}

function viewAnExtent() {
    var west = Cesium.Math.toRadians(-89.0);
    var south = Cesium.Math.toRadians(38.5);
    var east = Cesium.Math.toRadians(-88.0);
    var north = Cesium.Math.toRadians(39.5);

    var extent = new Cesium.Rectangle(west, south, east, north);
    scene.camera.viewRectangle(extent, ellipsoid);
}

Sandcastle.addToolbarButton('View Extent', function() {viewAnExtent();});
Sandcastle.addToolbarButton('Fly to Extent', function() {flyToExtent();});
```
