### ISSUE TITLE
Cannot read property 'scene' of undefined AFTER CLICK

### ISSUE THREAD

**Issue by erubeymtzs** [AnalyticalGraphicsInc/cesium#8040]
Hello, what happens is that I occupy the click event, and then to click on the Cesium balloon I get the error shown in the next image, I don't know why it is due.
![Captura de pantalla 2019-08-05 a la(s) 11 08 19](https://user-images.githubusercontent.com/26581749/62478947-ff10f680-b771-11e9-863d-165de4cee819.png)

**Comment by OmarShehata** [comment]
Can you put together a code example I can run on Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) to reproduce this issue?

**Comment by erubeymtzs** [comment]
Oh, sorry man, you were right, until I made the example in Sandcastle I realized my mistake.

**Comment by OmarShehata** [comment]
Thanks for confirming that @erubeymtzs ! In the future, for questions like this, please post in the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev

Once we've confirmed there's a specific bug we can open a GitHub issue documenting it.
