### ISSUE TITLE
 How to get latitude and longitude!!!!

### ISSUE THREAD

**Issue by erubeymtzs** [AnalyticalGraphicsInc/cesium#8047]
I want to know the value of all the intersection points of the gendered lines through a GridMaterialProperty, the image shows what points

This is the code:

var viewer = new Cesium.Viewer('cesiumContainer');

var entity = viewer.entities.add({
  position: Cesium.Cartesian3.fromDegrees(-103.0, 40.0),
  ellipse : {
    semiMinorAxis : 250000.0,
    semiMajorAxis : 400000.0,
    material : Cesium.Color.BLUE.withAlpha(0.5)
  }
});

entity.ellipse.material = new Cesium.GridMaterialProperty({
  color : Cesium.Color.YELLOW,
  cellAlpha : 0.2,
  lineCount : new Cesium.Cartesian2(8, 1),
  lineThickness : new Cesium.Cartesian2(2.0, 0.0)
});

viewer.zoomTo(viewer.entities);

var ellipse = entity.ellipse;
![Captura de pantalla 2019-08-06 a la(s) 13 46 18](https://user-images.githubusercontent.com/26581749/62721309-9031d880-b9d1-11e9-8bdd-cac24df7303e.png)

**Comment by OmarShehata** [comment]
I posted an answer for this on your forum thread here: https://groups.google.com/d/msg/cesium-dev/SbXp8dk1c4Y/bMXyFv7tBwAJ

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/SbXp8dk1c4Y/bMXyFv7tBwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8047 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
