### ISSUE TITLE
How to get latitude and longitude!!!!

### ISSUE THREAD

**Issue by erubeymtzs** [AnalyticalGraphicsInc/cesium#8048]
I want to know the value of all the intersection points of the gendered lines through a GridMaterialProperty, the image shows what points

This is the code:

var viewer = new Cesium.Viewer('cesiumContainer');

var entity = viewer.entities.add({
position: Cesium.Cartesian3.fromDegrees(-103.0, 40.0),
ellipse : {
semiMinorAxis : 250000.0,
semiMajorAxis : 400000.0,
material : Cesium.Color.BLUE.withAlpha(0.5)
}
});

entity.ellipse.material = new Cesium.GridMaterialProperty({
color : Cesium.Color.YELLOW,
cellAlpha : 0.2,
lineCount : new Cesium.Cartesian2(8, 1),
lineThickness : new Cesium.Cartesian2(2.0, 0.0)
});

viewer.zoomTo(viewer.entities);

var ellipse = entity.ellipse;
![Captura de pantalla 2019-08-06 a la(s) 13 46 18](https://user-images.githubusercontent.com/26581749/62721373-ab9ce380-b9d1-11e9-9280-494a63166d10.png)

**Comment by OmarShehata** [comment]
Closing as duplicate, see https://github.com/AnalyticalGraphicsInc/cesium/issues/8047#issuecomment-519609162
