### ISSUE TITLE
Unable to pull resources from cesiumjs.org due to CORS

### ISSUE THREAD

**Issue by ccopland94** [AnalyticalGraphicsInc/cesium#8050]
Hi - it appears that CORS is no longer working with the Cesiumjs.org domain. It was working before, but now it is blocking requests to get resources due to CORS issues, and failing altogether.

Browser: Chrome, Firefox

Operating System: Windows, iOS

**Comment by OmarShehata** [comment]
@ccopland94 are you embedding CesiumJS in your application like this?

```
<script src="https://cesiumjs.org/Cesium/Build/Cesium/Cesium.js"></script>
```

If so, try using an official release, like:

````
<script src="https://cesiumjs.org/releases/1.60/Build/Cesium/Cesium.js"></script>
````

Let me know if that works.

**Comment by ccopland94** [comment]
Thanks for your response.

I am already doing that, but with version 1.56. The issue isn't that the built cesium isn't loading into the frame, it's that it is failing to load resources cross origin. See the attached image:

![image](https://user-images.githubusercontent.com/22207133/62784254-1579c380-ba8c-11e9-9ef0-df4bb26c17bb.png)

**Comment by ccopland94** [comment]
It appears to me that something changed on the hosting side in that they are no longer sending the Access-Control-Allow-Origin header anymore.

**Comment by hpinkos** [comment]
Thanks @ccopland94.  @mramato is looking into this now and we'll have an update for you soon =)

**Comment by ccopland94** [comment]
Thanks @hpinkos 👍

**Comment by mramato** [comment]
Thanks for reporting this @ccopland94, we accidentally got a little over-aggressive with some housecleaning/security updates.  This should be fixed (but may take a few minutes to propagate globally). Please try it out on your end and let us know.

**Comment by ccopland94** [comment]
@mramato Thanks, that seems to have done the trick! Closing this issue out.

**Comment by Maarondesigns** [comment]
Our site is suddenly being blocked by CORS. Changing to a different build has no effect. This completely breaks our app (assuming the approximate terrain file). Can this please be fixed asap? This is breaking a production site for my company and if we can't rely on this framework we will have to move to a different product. I have a presentation of the app I've been building to the owner at the end of this week!! Please, thank you....
![cesiumscors](https://user-images.githubusercontent.com/40376601/66843470-da3bbb00-ef3a-11e9-911b-acb1997f9554.jpg)

**Comment by hpinkos** [comment]
Hello @Maarondesigns, we recently moved the releases from cesiumjs.org to cesium.com.

If you change your URL to `https://cesium.com/downloads/cesiumjs/releases/1.62/...` it should work, but please let me know if you are still experiencing problems as we just rolled this change out this morning.  Thanks!
