### ISSUE TITLE
Display X/Y tile labels on separate lines in Cesium Inspector

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8058]
[From this forum thread](https://groups.google.com/d/msg/cesium-dev/5WusaMbYNcs/qeXtXUMXDAAJ)

> I have been using the viewer CesiumInspectorMixin widget for development which is very handy. 
However the "Show tile coordinates" option becomes unreadable after level 19. Any change of having the Y coordinate displayed on the next line 

You can see how in earlier zoom levels, it looks OK:

<img width="319" alt="good_coordinate" src="https://user-images.githubusercontent.com/1711126/62979882-fd3ed700-bdf2-11e9-9966-7d72cadff608.png">

But as you zoom in more, you can't really read the labels anymore:

<img width="281" alt="bad_coordinate" src="https://user-images.githubusercontent.com/1711126/62979892-016af480-bdf3-11e9-90d7-0d4b385c5381.png">

Should be a straightforward fix, this is what you'd need to edit:

https://github.com/AnalyticalGraphicsInc/cesium/blob/54acd32f50c332605615a7b37b774c04690ef55c/Source/Scene/TileCoordinatesImageryProvider.js#L260-L266

Marking as good first issue to welcome external contributions!

**Comment by hpinkos** [comment]
Fixed in #8131

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/5WusaMbYNcs/qeXtXUMXDAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8058 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
