### ISSUE TITLE
Constantly creating and cancelling requests for 3D Tiles with requestRenderMode

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8074]
[Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=jVXbbuM2EP0Vwi+WWpfW1ZISJ2g3RdsAu2gQB33yCyONbaISqZKUs8rC/97RzZa97nb1YJkzZ2YOh4ej+Zw8yTdQ5ClnwpAMNN8KUsgMclIquecZZOS1Jh9AmBxqsqq1gUKvxZ4psufQhN4RAW/kAUOrgv7V2qxp2i4fpDCMC1DTGfmyFqR5FPxTgTbPIDJQn7DSDTGqglnvLthnXlRF537hBTzsmNgi6FFsuOCmXouDfdsR0CkIwPodEdou0dU5Dc9Bg0F3a6el4gU3fA+asiyzunIj5t3L//Wli7MGvvhUKr8ZYI9SPIOWlUqBbpQsftEIfsysMApcuws54NtuefQcqAKW1U+I5hqo2YGwNpVIDZfC6iH20J9+L+9SFi9y8M7GRP/AZFxsn7hJd89NbyyHhjPyk0O92bBr+ior0aBW5Q4UUIUhlSY/kIA6dsPtYFOJRNQbMjqRAaWkOlJJpdAyB5rLbe+57ZuPHR61fNxavZNv2PINy3VzFCsmspRp1E7T9Be53ebwoTIGa01XCEVdtFB8DRzSHaR/Q3bZkP+q1MNPzIZEZAvmgRWg2G95ja08JURxpK3jJJ1ufXsClFLzNstdj6WDZQTKuIL0HHU0jWBVefJX5e0li5VReFAImX5Z4wbWJ93hdTRcsLbCzZlWmTL4jwnfmpIfj2TpZ1xgS89s9RXbe2OzZxflpOJ4zYdyl2RaQscNf4vOETXmczLW14zXGbWXr/xmsaocV8FVfba6nvdwacgqNezbH7kO0/60FJhKibMDaxTX6O1S4jJ/ZWrQ+O84gDoRTkcSt69csEu1fn3XegVtWn+f4XsU4vp+4sY4I/zA9xwvcXFWBIvQxYdGruct4miBtsAN3SiMaeB6kefGiWf3I/lSFuL71YAzqSkTxn7kLdzQCyLHnxGHxkngOOFikUS+01Bpp1fgB04QO27gLYLEdYfy/6MBh/phGOPwxTjM7kVu1FQIAj9MkhB/Iy9axF1VzwsDZ+F6MW408f2hwqF/n4mgaf5kNllqU+dw3wF+5kUplWm+Bxalc/wSljlDIvPXCmeQoanWzYkt50PQMuN7wrO79eTie7iekDRnWqNnU+X5ir/DenK/nCP+LCyX7az/cw8qZ3UD2bn3HzsjpXQ5x+XXUaYT4Sjjvw). This is a bit tricky to reproduce but I can reliably reproduce it:

1. Open the network tab, filter for "b3dm"
2. Move the camera a little bit. 

After a bit of movement, you should start to see a seemingly endless stream of requests for b3dm tiles that keep getting cancelled and re-requested. This goes on for thousands of requests, for at least a full minute, even though it take seconds to actually load the given view if the tileset were not hidden. 

This only happens with `requestRenderMode: true`. Seems like a bit of a corner case in the request cancelling system? @loshjawrence do you have any idea off the top of your head, or where in the code someone might want to look to debug this?

**Comment by mramato** [comment]
Sounds similar to #7786 which @loshjawrence already fixed once.  requestRenderMode is important and this sounds like a major performance killer so we should fix this ASAP.

**Comment by mramato** [comment]
Preferably before the next release, but I would like to know more before tagging it that way.

**Comment by loshjawrence** [comment]
I'll have time tomorrow to look at this

**Comment by loshjawrence** [comment]
[Update Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=jVVdc+o2EP0rGl6wWyr8iU0gmfam0zYz904zIdMnXhx7AU1tyZVkcp07/Peu/AGG0PT6AaHds7tHqyNpOiWP4hUkecwTrkkGim05KUQGOSml2LMMMvJSk0/AdQ41WdVKQ6HWfJ9IsmdgQm8Jh1dyj6FVQf9qbNY4bab3guuEcZDjCfm25sR8Ev6pQOkn4BnIL1jphmhZwaRzF8lXVlRF635mBdzvEr5F0APfMM50veYHe9ESUClwwPotEdpM0dU6NctBgUZ3Y6elZAXTbA+KJllmteUGzNvB//W5jbN6vvhVMr/pYQ+CP4ESlUyBbqQoflEIfsisMApcuw054Gg3PDoOVEKS1Y+IZgqo3gG3NhVPNRPc6iB2359uLW9CFM+i906GRP/AZIxvH5lOd0+mN5ZDwwn5yaHepF81fREVN6hVuQMJVGJIpcgPJKCObbgdbCqQiHxFRicyIKWQRyqp4ErkQHOx7TyLrvnY4UHLh61VO/GKLd8kuTJbsUp4liYKtWOa/iy22xw+VVpjrfEKoaiLBopDzyHdQfo3ZJcN+a9KHXxxBXymNMtevF/V2OQjJtPNmPz4Yamr4b3Gjhn69vcRXbf6xZEt6PukAJn8lte4vadFomDTxnGScztfnAClUKzJctthaW8ZgDImIT1HHU0DWFWe/FW5uGSx0hLFg5DxtzUuYH06C3hFaMaTpsLN2flJpMZ/Cfct04meGv2KE9zmM1t9xfZmbPbkopyQDK+evtwlmYbQccEf0TmihnxOxvqa8Tqj5kIoPyxWlcMqOKvPZtfzHi4NWSX7dfsD12Hc7ZYEXUl+tmFGcUZvl8dO5C+J7M/d7yjYVoTjwbGzrxz6S7W+P/+dgjaNv8vwPQpxfX/uxnhv+YHvOd7cxfsrmIUufjRyPW8WRzO0BW7oRmFMA9eLPDeee3b3TFzKgn+/GvCeNGXC2I+8mRt6QeT4E+LQeB44TjibzSPfMVSaGzXwAyeIHTfwZsHcdfvy/6MBh/phGOODgHGY3YvcyFQIAj+cz0P8jbxoFrdVPS8MnJnrxbjQue/3FQ7deCYC0/zRZLRUus7hrgX8zIpSSG3eKIvSKb7OZZ4gkelLhfeipqlSZseW0z5ombE9YdntenTxRq9HJM0TpdCzqfJ8xd5gPbpbThF/FpaL5v35cw8yT2oD2bl3n1sjpXQ5xen7KN2KcJDxXw)

Looks like the tileset's show boolean isn't updated from the more global primitives.show

**Comment by loshjawrence** [comment]
Potential fix https://github.com/AnalyticalGraphicsInc/cesium/pull/8081

**Comment by dennisadams** [comment]
I don't think #8081 properly solves the issue.  
I have this issue also when I create a new tileset with `show : false`.  
I can't however make `scene.primitives.show = false`, because I have other tilesets and primitives that I do want to show.
I haven't dug deep into your optimizations @loshjawrence, but maybe here in [Cesium3dTileset.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Cesium3DTileset.js#L2280):
```
if ((pass === Cesium3DTilePass.PRELOAD && (!this.preloadWhenHidden || this.show)) ||
    (pass === Cesium3DTilePass.PRELOAD_FLIGHT && (!this.preloadFlightDestinations || (!this.show && !this.preloadWhenHidden))) ||
    (pass === Cesium3DTilePass.REQUEST_RENDER_MODE_DEFER_CHECK && !this.cullRequestsWhileMoving && this.foveatedTimeDelay <= 0)) {
    return;
}
```
you should have a check of `this.show` also in the third condition line.  
This worked for me:
```
(pass === Cesium3DTilePass.REQUEST_RENDER_MODE_DEFER_CHECK && ((!this.cullRequestsWhileMoving && this.foveatedTimeDelay <= 0) || !this.show))
```

but I don't know if it hurts any optimization.

**Comment by loshjawrence** [comment]
Thanks @dennisadams.

**Comment by OmarShehata** [comment]
This should now be fixed with https://github.com/AnalyticalGraphicsInc/cesium/pull/8081.
