### ISSUE TITLE
Draw polygons!

### ISSUE THREAD

**Issue by erubeymtzs** [AnalyticalGraphicsInc/cesium#8075]
Hello, the thing is that I am drawing a polygon according to the position in which the map is clicked in cesium, in CESIUM SANDCLASTLE my code works perfectly, but when I implement it in my application the polygon I draw it completely disproportionate.

In the following images I show as in SANDCASTLE if I draw the polygon perfectly and in my application no.

Does anyone know something.
![Captura de pantalla 2019-08-15 a la(s) 9 32 57](https://user-images.githubusercontent.com/26581749/63102492-e1e1e200-bf40-11e9-8140-85ff8589c93f.png)
![Captura de pantalla 2019-08-15 a la(s) 9 31 13](https://user-images.githubusercontent.com/26581749/63102502-e8705980-bf40-11e9-8efa-8c8875f8cab0.png)

**Comment by OmarShehata** [comment]
Please keep general questions like this on the forum. I see you've already posted a topic here: https://groups.google.com/forum/#!topic/cesium-dev/OILGKZK1a70

I'll make sure to respond there. We use GitHub issues specifically for bug reports and feature requests.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/OILGKZK1a70

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8075 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
