### ISSUE TITLE
Decouple SSE from Resolution & Resolution Scales With Device Pixel Ratio 

### ISSUE THREAD

**Issue by ProjectBarks** [AnalyticalGraphicsInc/cesium#8082]
When working to have Cesium render at the browsers native resolution (https://github.com/AnalyticalGraphicsInc/cesium/issues/7875) density it became apparent that there was a bigger design change required. Here are some the changes I plan to bring in a pull request soon (since they are highly related)

#### Problem
Currently, if the user sets the resolution scale to x2 the SSE will be effected as well. It is outside a users expectation for a change in resolution to also impact SSE. Here is an example:

`resolutionScale` used to be a constant 1 that could be changed by the user but now it's set to `window.devicePixelRatio` by default. 

| `resolutionScale = 1`  | `resolutionScale = 2` |  `resolutionScale = 2` <br> <br> `maximumScreenSpaceError * viewer.resolutionScale` |
|---|---|---|
| <img width="314" alt="image" src="https://user-images.githubusercontent.com/4194371/63177191-643bd600-c015-11e9-9cc4-341f65b53bfb.png">  |  <img width="271" alt="image" src="https://user-images.githubusercontent.com/4194371/63177083-3060b080-c015-11e9-8583-3c8530faf713.png"> |  <img width="315" alt="image" src="https://user-images.githubusercontent.com/4194371/63177445-eb894980-c015-11e9-8375-6d8381569627.png"> |

When the user sets the `resolutionScale` to `2` it nearly triples the amount of tiles loaded. The only thing `resolutionScale` should do is increase resolution instead of inadvertently impacting SSE.

#### Solution
The way to fix this is take the resolutions scaling factor and multiply SSE by that factor. When resolution changes SSE stays constant. _(Much like the example I provided in the third quadrant of the table)_  This would involve passing a `resolutionScale` to `FrameState` and making `resolutionScale` a part of the Scene.

### Resolution Scales With Device Pixel Ratio
Cesium should render at the same pixel ratio as the `window.devicePixelRatio` but as Ed pointed out:
> But this isn't resolutionScale, it's devicePixelRatio. The latter is affected by things such as CTRL + and CTRL - screen scaling, and Windows Desktop DPI scaling. Just for completeness, has someone tested the effects of those being set to non-default settings?

Me an @lilleyse agreed when talking privately most users would prefer to see an equally high resolution image of cesium when zooming in than degraded image. So instead of passing devixePixelRatio as the default resolution scale we create a resolution final resolution scale that is: `resolutionScale * devicePixelRatio`. 

Please feel free to provide feedback.

**Comment by lilleyse** [comment]
@ProjectBarks generally sounds good. I'm curious to set what the final code will look like.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/8083
