### ISSUE TITLE
2D & CV Clipping Planes

### ISSUE THREAD

**Issue by ProjectBarks** [AnalyticalGraphicsInc/cesium#8088]
The implementation of clipping planes does not work when viewed in 2D or Columbus View.

As @likangning93 mentioned:
> To be fair I think that they can be made to work in 2D/CV, it's just not automagic like our geometries are. And automagic clipping planes is a very hard problem! Robust support may require that some projected planes be curved.

Related information: [link](https://github.com/AnalyticalGraphicsInc/cesium/pull/8087)

**Comment by hpinkos** [comment]
duplicate #6871
