### ISSUE TITLE
cesium1.5.0~1.6 can not rotate the model

### ISSUE THREAD

**Issue by engineerhe** [AnalyticalGraphicsInc/cesium#8095]
Since cesium 1.5.0 ,it can not roate 3dtiles modle any more.When i rotate the model , the model suddenly disappears, and the code as follows:
let m = tileset.modelMatrix;
let mx = Cesium.Matrix3.fromRotationY(Cesium.Math.toRadians(-1));
let rotationX = Cesium.Matrix4.fromRotationTranslation(mx);
Cesium.Matrix4.multiply(m, rotationX, m);
tileset._root.transform = m;

**Comment by lilleyse** [comment]
This sounds like the same problem as https://github.com/AnalyticalGraphicsInc/cesium/pull/6755#issuecomment-425454485. That comment has a suggested fix if you are ok modifying CesiumJS locally.

You could also try upgrading the tileset, see https://github.com/AnalyticalGraphicsInc/cesium/issues/7036#issuecomment-425146294 for details.

**Comment by OmarShehata** [comment]
I'm fairly certain it's the same problem as linked above. I posted a link to a recent forum thread discussing the same issue (see https://github.com/AnalyticalGraphicsInc/cesium/issues/7036#issuecomment-523451339), and re-tiling your data with Cesium ion could be another easy way to fix it.

I'm closing this for now @engineerhe but feel free to follow up if these suggested fixes don't work.
