### ISSUE TITLE
DEM stair case effect

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium#8098]
When I am loading the custom DEM using geoserver terrain provider over cesium globe, it is showing stair case effect. please suggest how ow to rectify it
![step effect](https://user-images.githubusercontent.com/41281254/63521012-48539b00-c513-11e9-8977-1e42c7988b6a.JPG)

**Comment by OmarShehata** [comment]
It's hard to tell whether it's an issue with the data or the library without having a reproducible test case we can run. 

I would post a thread on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev), with some sample data if possible, and if we identify a specific bug with the library we can open a GitHub issue for it.
