### ISSUE TITLE
not allowed to load from local resource

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium#8099]
when i am loading the quantized mesh terrain tiles generated through cesium terrain builder. it is showing the "not allowed to load from local resource"
![load local resource](https://user-images.githubusercontent.com/41281254/63521316-d62f8600-c513-11e9-9443-4b9caea53e65.JPG)
.

**Comment by OmarShehata** [comment]
This is a JavaScript/browser error. The browser does not allow the application to read your local filesystem (for security reasons). You'll need to run a local web server. 

Please use the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) for questions like this. That way we can keep GitHub issues for specific bug reports in the library.
