### ISSUE TITLE
Use CSS pixel units everywhere

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#8113]
- [x] Point cloud size
- [x] Styled point cloud size
- [x] Point cloud eye dome lighting radius
- [x] Polyline arrow
- [x] Polyline dash
- [x] Polyline shadow volume
- [ ] GL line width
- [x] Model minimum pixel size
- [x] Star Burst demo
- [x] Frustum getPixelDimensions
- [ ] (More to come)

https://github.com/AnalyticalGraphicsInc/cesium/pull/8083 changed Cesium to render at device resolution rather than upscaling on high DPI displays. The problem now is there are some options in Cesium whose unit is pixels but it's unclear if that means "CSS pixel" or "device pixel".

Everything should be in CSS pixels so that a scene doesn't look different on different displays. We should sweep through everything that has pixel units and multiply by `frameState.pixelScale` like we're doing for SSE.

For example point cloud maximum attenuation is considered to be "device pixels" and because of that points are smaller than in 1.60.

**1.60** [Sandcastle](https://cesiumjs.org/releases/1.60/Apps/Sandcastle/index.html#c=dVNNc9MwEP0rmlzqzBj5S/5ISTtk0gOdKUMmLXDxRZE3zYIsZSQ5bejw35HtFggFX+xdvbfvaXcdRSuNypGl1F1DNkeyMnpLyQocGLKQElRIllp27QY5+aTwAMaiO5K13miHwpIbvqHkVnClUN33BRYSvnLVGE3ujBZCSyQ+JB+4AyRL1IIbiUBrdeCGHBAevNAFUfBAlmCxa+nnIReciSFcauU4KjBnIXmqFfGPt2Z8yjs9YOPZ5y9MYcCrfNFGNncjJpjW6sf0ba283FCWWgEK6A7vd1dHxVsUa67uwTvYcmlhRHpjDiVYcKfOxld2dTceBk+kM/KX+rVWa7C6MwLo1uh2YT3mugmSgqXJlAw2TkzsDbbofEst5U0TPEv+w63gLRhO/WHfm+C5DQ1Yh4o71Or8xCU3zn9xlQWMxUnJGC0YS1ieJSwkaZrHeUJZEpfVLEniPA0Jy2c5S2OalaysGMuyaThKaIPg2/9K4j3wxo97hU7s1lrKIPcSRZllVZzH2azMy5C8iWlaFkVcJnlWZbOqKkJS0LRKvGhV5iyO4yr/PZ7n29N9v47DNt7uBhHKnQPVDSb8OJzp+in9H97yR2y7dnHCyj1lEk7m1h0lXI6Xe4ftXhvXzzCgNHLQ7qVfHxttOvHNlxbW9tbm0Qtp3uCBYHNRT/5azXpChOTW+pNtJ+Utfod6cjmPPP6EJvVg8aP/iSQ/9pBdcnkzJiml88iHr1lOa7nh5o+KPwE)
![old](https://user-images.githubusercontent.com/915398/63780999-0e89e800-c8b7-11e9-8203-b528af447cf1.jpg)

**master** [Local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=dVPbctMwEP2VnbzUYYxsx/IlbdohEx7oTBkyaYGXvCjyli7IUkaSk4YO/44Sp9DQwS/2Xs6esxcnydyQ9jBTpmtgtYO5NfcM5ujRwlQp1DHMjOraFQn4rGmD1pHfwcKsjCfp4EasGNxKoTXpb/sCU4XfhW6sgTtrpDSKIJjwUXgkmJGRwipCttQbYWFDuA1El6BxCzN01LXsy8EXncmDOTPaC9Joz2J4WmoIT5Bmgyso3VAT0OfPSGkxsHw1VjV3fU40XOpfw4ul7uk8KXToT/n6V/7+rg9GT9BZ9afmtdELdKazEtm9Ne3UhZzrJspKPsqGcCjed8GcRI1sbaklHwblmGia6Eh51PAyUYoWrWAhuO84OjbXoPOkhSejz09UCuvDl9B5xHmaVZyzkvOMF3nGYxiNirTIGM/Sqh5nWVqMYuDFuOCjlOUVr2rO83wY9xTGEoahvqL4gKIJS5yTlw8Lo1RUBIqyyvM6LdJ8XBVVDG9TNqrKMq2yIq/zcV2XMZRsVGeBtK4KnqZpXfwd+rF7tt4f2eHGbh8OJEx4j7o7iAjr8LbDAEiS/wNa8Uht105PcAW8gS3pxmxZgxuSOKdHVIt9+GIQDybO7xRe9W2/o3ZtrN9vN2Is8diuVTgXl6w6+SNQSuf2oifJM2jS0AaouVwO/jnF5QCkEs6FyH2n1C39xOXgapKE/BOYMgfpn8JPo8Run/KQXd30TsbYJAnma5Q3Rq2EfVHxNw)
![new-unfixed](https://user-images.githubusercontent.com/915398/63780997-0df15180-c8b7-11e9-8494-68560151a8d3.jpg)

**master with `devicePixelRatio` correction** [Local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=fVNNb9NAEP0ro1zqILOx43XstGlFFA5UKiJKC1x82ayndGC9G+2uk4aK/846TqGhEr7Y8/HmvfnwaLQ0pD0slGlrWO9hac09gyV6tDBXCnUMC6PaZk0CPmvaonXk97Aya+NJOrgRawa3UmhN+ltXYK7wu9C1NXBnjZRGEQQTPgqPBAsyUlhFyCq9FRa2hLtAdAkad7BAR23Dvhx80Zk8mAujvSCN9iyGp0pDeII0G1xB6ZbqgD5/RkqLgeWrsaq+63OiYaV/DS8q3dN5UujQn/L1r+z9XR+MnqC16k/Na6NX6ExrJbJ7a5q5CznXdZRO+DgdwqF43wVzEjWyjaWGfBiUY6KuoyPlUcPLRCkatIKFYNdxdGyuRudJC09Gn5+oFNaHL6GziPMkLThnE85Tnmcpj2E8zpM8ZTxNinKapkk+joHn05yPE5YVvCg5z7Jh3FMYSxiG+oriA4o6LHFJXj6sjFJRHigmRZaVSZ5k0yIvYnibsHExmSRFmmdlNi3LSQwTNi7TQFoWOU+SpMz/Dv3YPdt0R3a4sduHAwkT3qNuDyLCOrxt8eJ/6Y14pKZt5ieoHN7AjnRtdqzGLUlc0iOqVRe+GMSDmfN7hVd90++o2Rjru91GjI08NhsVjsWN1q38ESilc53k2egZNKtpC1RfVoN/DrEagFTCuRC5b5W6pZ9YDa5mo5B/AlPmIP1T+GWU2HcpD+nVTe9kjM1GwXyN8saotbAvKv4G)

![new-fixed](https://user-images.githubusercontent.com/915398/63780998-0df15180-c8b7-11e9-8549-4127714bd681.jpg)

**Comment by lilleyse** [comment]
A workaround is to set `viewer.resolutionScale = 1.0 / window.devicePixelRatio`.

This will render the Cesium canvas in CSS pixels rather than device pixels and will apply upscaling for high dpi devices. This is the behavior in 1.60 and before.

**Comment by smills2929** [comment]
> A workaround is to set `viewer.resolutionScale = 1.0 / window.devicePixelRatio`.
> 
> This will render the Cesium canvas in CSS pixels rather than device pixels and will apply upscaling for high dpi devices. This is the behavior in 1.60 and before.

@lilleyse 
It isn't quite so simple. If you set the viewer resolutionscale and then drag your browser window (with a cesium viewer in it) from a high DPI screen to a low DPI screen with different scaling, it doesn't adjust it, so you get a horribly pixelated viewer.

**Comment by OmarShehata** [comment]
> drag your browser window (with a cesium viewer in it) from a high DPI screen to a low DPI screen with different scaling

You should be able to detect this in your application, and you can re-update the resolution scale then. See https://stackoverflow.com/a/31482424

**Comment by lilleyse** [comment]
@smills2929 also check out some of the solutions in https://github.com/AnalyticalGraphicsInc/cesium/pull/8083:

* https://github.com/AnalyticalGraphicsInc/cesium/pull/8083#issuecomment-531101645
* https://github.com/AnalyticalGraphicsInc/cesium/pull/8083#issuecomment-531105626

There was some discussion about making this a configurable option in cesium. I think there's enough demand now that it's worth doing. I opened an issue which we'll target for the coming release: https://github.com/AnalyticalGraphicsInc/cesium/issues/8215.

**Comment by lilleyse** [comment]
@smills2929 you can now replace any workaround code with `viewer.useBrowserRecommendedResolution = true`. It will ship with Cesium 1.62.

**Comment by smills2929** [comment]
That's great to hear. Thanks!

**Comment by lilleyse** [comment]
@IanLilleyT since just the GL line width problem is left can you open a separate issue? This one can be closed.

**Comment by IanLilleyT** [comment]
The separate GL lines issue can be found here: https://github.com/AnalyticalGraphicsInc/cesium/issues/8319
