### ISSUE TITLE
chrome crashes  when cesiumContainer width and height is 100% and the chrome's scroll bar is display

### ISSUE THREAD

**Issue by skylning** [AnalyticalGraphicsInc/cesium#8118]
i use cesiumContainer with  width and height for 100% as container for Cesium,when the real width or height out of the screen width or height and the chorme's scroll bar displayed,the chrome is  crashed.

**Comment by skylning** [comment]
sorry,maybe is my pc os problem,i change orther pc to test and it is work fine

**Comment by OmarShehata** [comment]
Thanks for confirming @skylning . If you're able to recreate this in an example you can share, feel free to open an issue for it. If you're unsure you can always ask on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev).
