### ISSUE TITLE
How to add the polyline between the entity and point using the entity added by addSample() , without using czml

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#8121]
How to add the polyline between the entity and point using the entity added by addSample() , without using czml？
![捕获](https://user-images.githubusercontent.com/33933148/64097602-48675c80-cd97-11e9-9efe-40ed7ec7be38.PNG)

**Comment by OmarShehata** [comment]
Did you figure it out?

Just in case someone else stumbled on this, you should just be able to grab the entity (whether by ID if added from a datasource, or by iterating through `viewer.entities` and finding it if you don't know its ID etc) and then getting its position `entity.position.getValue(viewer.clock.currentTime)` and then adding the polyline at that starting position (see code example https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polyline%20Dash.html).

You may need to have a callback property on the polygon positions property if the entities are moving.
