### ISSUE TITLE
Model rendering test failures in master

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8127]
I'm doing the 1.61 release, and the following 3 tests are failing in master:

* http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20loads%20a%20glTF%202.0%20model
* http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20renders%20with%20the%20KHR_materials_unlit%20extension
* http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20renders%20with%20lightColor

@lilleyse I know we made some changes to lighting in 1.61, like turning off HDR, but I wouldn't expect this to cause an unlit model to render darker than it should be. 

Although actually inspecting the color drawn for this unlit model in the specs, it seems to be exactly the same from 1.60 to 1.61 (it's slightly darker than the base color in both versions). 

Here's a [Sandcastle in 1.60](https://cesiumjs.org/releases/1.60/Apps/Sandcastle/index.html#c=tVVhb9owEP0rFl8IUpZAgXZrabWWTuukoXWl65cxTW5yIRaOjWyH0k38952dBEIqbZXWWgjZ5/O7d+98zooqsmLwAIqcEgEPZAya5Vlw52xeO3LLsRSGMgGq7ZPfM0FwMJHIC7kmxyShXINfWDVwiAyT4pOIWUSNVE2HlMbyQaPVqHxnlDmPzwXLqIFyayY2nZOZmIkkFw6RRApweyJj4F6uuE9SYPPUdCpGRRoBCMMMAx0oyOQKzjn3CiDng+kupWYO8LRKdkyVwRkV/SBRMruEuQLQ3pveQT/oHg0Gh713PhkMgu6w2z/qHm4jn+xAU6AxE/Md5oSaNDDyBs1UaK/XH9bdl8xEKTp3azYlOW+Y0mWjLFdFmGt7/Ab9vTKuXyD6DqQeSCqGgtD9fG8VUkqkynSQNgC/5qixEujuVTr5lsa+hE7jRwRsak7j2CvLYYegma2nrdbOuNX/eDut7dYJH9dXNZ/M3gHcrUWyI1fsSTDnzvBm5dk1WwOfsl+WUe/gbdOJrq3TNKLcOhx0cTRcwpDbso8ld9e6VpbdBfKGQdcn1V9nB7ApppttcQrljKLRAuIPlaCFsuizsXq7Ci5t9hr3vpf5GlgbjN8+ZypSNDHtkid6ufazLVc2jdepi1TvoHYQhMVvuoRIh5fU0NBt6fD64ibE3v4mODPbSTDnJsH+H6IwmFmZBtLcbN+EithHJXMRkztIWcThf+hNabbk4LhlBbcCu4TeXyHDeyT4d25X0hAUjlxQzqUUL0uuuA4l9P6qJNf7t3oTxhfkVuXR4jXIWXQH3ly/WWTRsxScLpgQEJNxSvHyGvtReAWatNLvJ06fxesS2UgyltlSgdZI0AV6WXIuxi5EU8OqR/aI/nBP55SKOKLa4DXFR/JWSn5P1QRE7pUNbo+0/NZIm0cOZ8Xx9yxbSmXsm+YhHwPIB0nq8B6DgQki7Y6NwurQKGYrwuLTWavx4Z61SMSp1riT5Nw9g7PW2ShE/71jXLrvwZcVKE4frUvaO/tcGIMgGIW4fHrKFOnUEP8A) if you use the browser's color picker you'll see renders as `#00d100` and not the expected `#00ff00` both in 1.60 and in master.

**Comment by mramato** [comment]
I actually get 4 failues:

```
1) renders with specular environment map
     Scene/Model
     Error: Expected not to render [0,0,0,255], but actually rendered [0,0,0,255].
    at <Jasmine>
    at verifyRender (Specs/Scene/ModelSpec.js:255:23)
    at Specs/Scene/ModelSpec.js:674:17
    at Promise.then (Source/ThirdParty/when.js:196:34)

2) loads a glTF 2.0 model
     Scene/Model
     Error: Expected Uint8Array [ 174, 6, 5, 255 ] to equal epsilon [ 193, 17, 16, 255 ], 5.
    at <Jasmine>
    at Specs/Scene/ModelSpec.js:1029:30
    at compare (Specs/addDefaultMatchers.js:271:29)
    at <Jasmine>

3) renders with the KHR_materials_unlit extension
     Scene/Model
     Error: Expected 209 to equal 255.
    at <Jasmine>
    at Specs/Scene/ModelSpec.js:2889:33
    at compare (Specs/addDefaultMatchers.js:271:29)
    at <Jasmine>

4) renders with lightColor
     Scene/Model
     Error: Expected not to render [0,0,0,255], but actually rendered [0,0,0,255].
    at <Jasmine>
    at Specs/Scene/ModelSpec.js:3108:35
    at compare (Specs/addDefaultMatchers.js:271:29)
    at <Jasmine>
```

2 and 3 are most likely related to #8055 and we just need to update the values.  Not sure about 1 and 4 (at least for me).  CC @lilleyse

**Comment by OmarShehata** [comment]
I did see test failure 1) above on Linux, but not when I switched to Windows to test the other browsers.

2/3 tests in the original post here are fixed in this PR https://github.com/AnalyticalGraphicsInc/cesium/pull/8128. I am convinced the `renders with lightColor` is not an actual bug. You can see in this [1.60 Sandcastle](https://cesiumjs.org/releases/1.60/Apps/Sandcastle/index.html#c=bVRdT9swFP0rVl8IUuakX7BBQRtl0yaBxsq0p7xcnJvGmmNXtlPopv73XSf9CGFWU9nX5557c46dNVi2lviMll0xjc9sjk7WFf/VxKIT0SznRnuQGu1JzP5mmtGQujA35oVdsAKUw7iNOlQovDT6m86lAG9sH1BCbp4dRb2tj0FTq/yTlhV43G1lent6melMJ0nbH3cCNfJSLsvbjYZKigXoJVLbAd5Ai1o3xZmwSEz3JkcV1VbFrERK86f75neMqL30Eh23WJk1flIqams2GFJmZZxsCK/2uszBepqBHvPCmuoWlxbRRe+GozFPzyeTs+GHmE0mPJ2m4/P07FD58khaIuRSL4+c9+BL7s2CwqBdNBxPu/CV9KIkcNqJWaNUL1Sueg5+bcs8hPQF4aNd3bhljBuSbiFjJQkCr9/3p6WWCmMrx8se4Y+aNLaa4NFepzi08VrCRuMNEfY1hzyPdnaEQY4G64Nbx+BB/4vDtLPbbfiiu+pgqnAGaLdTKYzayjfFGrikQ1hXD/IF1aP8Ezoajt73QfASQI8CVACMUho9CJ3kJd6Aw/wu2E+yfQHR3oaORYfDNIpSnsaM/k57RCqkz40y9v+Z40NmzKaUfszettPtweJWf29B/Mb8896W1h/CbINr3YtzwnnS/h5XKFxyCx6SZsslDzeLhG5/ePhS+YK+C1NSgRogpkE8mDm/UXjdVv4oq5WxPsgdEZvHaqWoikueamrFc+FcSJsl+6RZLtdM5lfZoPf5yQZMKHCOdopaNQ5lg+tZQvhXaco0R/X7Gq2CTYCUw+u7Nsg5nyW0fJvljVFPYDuM/wA) that setting the same parameters as the test gives the model a slight blue color. And I can see the same exact effect in 1.61. It almost seems like the test has the sun set in the wrong position (if you move the timeline, at some point the model will become all black). I tried changing or fixing the time in the unit test, but it didn't fix it. 

I would vote for `xit` this test for this release.

**Comment by mramato** [comment]
> I would vote for `xit` this test for this release.

There's no reason to `xit` it if it's a test only thing.  Since travis is passing we can just release as-is and investigate the failure later.

**Comment by hpinkos** [comment]
I see this one `Scene/Model renders with lightColor`
