### ISSUE TITLE
new CesiumSensors.RectangularSensorGraphics () 问题

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#8136]
如何 使用new CesiumSensors.RectangularSensorGraphics ()

entity.addProperty("rectangularSensor");

entity.rectangularSensor = new CesiumSensors.RectangularSensorGraphics(
   {
     xHalfAngle : Cesium.Math.toRadians(40.0),
      yHalfAngle : Cesium.Math.toRadians(20.0),   
      intersectionColor : Cesium.Color.GREEN.withAlpha(0.8),
      intersectionWidth : 10,
      showIntersection : true,
      radius : 1000000.0,
      show : true,     
      showThroughEllipsoid : false
 }
);
报错：
![捕获](https://user-images.githubusercontent.com/33933148/64316391-4a275f00-cfe7-11e9-83ac-0698923c4e1d.PNG)

**Comment by OmarShehata** [comment]
If you're using the ion SDK (https://cesium.com/ion-sdk/), shoot us an email at support@cesium.com and we can help you out there.
