### ISSUE TITLE
Valid glTF does not render 

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8148]
Came up [in the forum](https://groups.google.com/d/msg/cesium-dev/DZdiWyPFlTw/uQxEIuHeAQAJ). I've split the given glb into a glTF with separate bin and textures to make debugging easier:

[Test.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3600730/Test.zip)

It's valid according to [glTF validator](https://github.khronos.org/glTF-Validator/) and renders correctly in the [glTF viewer](https://gltf-viewer.donmccurdy.com/):

![Rock](https://user-images.githubusercontent.com/1711126/64696841-73277400-d46d-11e9-9ae3-6d44e1bc4689.png)

In CesiumJS, it loads with no errors, but nothing is displayed. Initially I thought maybe it was just rendering with a transparent material, but overriding the material in [processPbrMaterial](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/processPbrMaterials.js) still does not display it. It works fine when uploading it to Cesium ion and tiling it as 3D Tiles, so I'm wondering if there's some transform issue/if the geometry is actually pretty far from the origin etc.?

**Comment by DerouineauNicolas** [comment]
Hi Omar,
I just found out that if I scale the geometry by 1000 with meshlab, then the cesiumjs display is ok.

**Comment by OmarShehata** [comment]
Oh I can see it now. If you scale it by 1000 in CesiumJS it's also visible, but since the vertices don't seem centered around the origin, it also moves away when scaled, so it looks like the original mode was just too small.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/DZdiWyPFlTw/uQxEIuHeAQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8148 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by DerouineauNicolas** [comment]
I tried scaling directly with CesiumJS

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            uri : url,
            minimumPixelSize : 1,
            maximumScale : 20000,
            scale:1000,
        }
    });

But how are you sure it's correctly displayed in the scene ? I tried zooming in/out, nothing appears on the screen.

**Comment by OmarShehata** [comment]
I was able to see it briefly, it was nowhere near its original location, somewhere off in the atmosphere (and I may have had a higher scale there). I haven't been able to easily reproduce this again though.

**Comment by DerouineauNicolas** [comment]
Thanks for you answer. But why is not displayed when no scaling is applied ? Is there a minimum "bounding box" diagonal size required by CesiumJS ?

**Comment by OmarShehata** [comment]
Actually, the model isn't that small. The problem is more that the coordinates aren't centered around the origin. So when you zoom to in CesiumJS, it goes to the (0, 0, 0) but the geometry itself is very far. This would explain why it works in Cesium ion (the geometry gets re-normalized). I verified this with our model inspector (a beta debugging tool):

![ref_frame](https://user-images.githubusercontent.com/1711126/64702938-788abb80-d479-11e9-8b3b-0c7c5f18ab6b.png)

The axes are where the reference frame of the model is, which is what CesiumJS zooms to.

**Comment by DerouineauNicolas** [comment]
Awesome, thank you very much for the explanation !

**Comment by DerouineauNicolas** [comment]
This transformation operator at the root node looks promising ! I saw there is the same operator in the 3D Tiles, looks like the good solution. I'm very grateful for your help !

**Comment by jackbr0gm** [comment]
@OmarShehata @DerouineauNicolas I'm also facing same [issue](https://github.com/CesiumGS/cesium/issues/10165#issue-1161292585). Would you please tell me what steps I need to follow to repair my model in blender. It's very important to me.

- Thank you
