### ISSUE TITLE
filling complex polygon

### ISSUE THREAD

**Issue by alon6699** [AnalyticalGraphicsInc/cesium#8154]
There is a bad behavior of filling complex polygons. 
Complex polygon is any polygon that has few small areas:
for example when drawing a hourglass shape. When this kind of polygon is being drawn in cesium - the filling result is terrible.

I tried to find an open issue about this topic so sorry if this issue already exist.
It would be wonderful if you fix this.

**Comment by OmarShehata** [comment]
@alon6699 there is an old issue that's similar to this: https://github.com/AnalyticalGraphicsInc/cesium/issues/1209

Feel free to add your test case there, or if it's different enough, we can re-open this issue.

**Comment by alon6699** [comment]
This is a Sandcastle example in chrome :
https://cesiumjs.org/Cesium/Apps/Sandcastle/#c=pZLfS8MwEID/ldCXdlDTljp/zG4om2+CMsEX40PW3rZgmoxL2lFl/7tpu+HUJ/XIQ3J338eRhKmaI6kFbAHJmCjYkikYUZX0qcsFft4dp1pZLhSgP7hiinUUQvGgZbPSypG9goKywgowlBdF8M4UcaF4CWRE/DkUZLMH3DIVLnkOfth3HSojssfaWAtAjvm6cen9XFOO1u24SukSdTmDFQKYG0TeBM8nSRLT85AMY5pehp+e30bnOQvTUzr8nyaO6TAJ23HSv3t6TdqNcxG+DI5MJbeAgsuj+9FSI53fzvqmHVO7/sm80MuMbSRM+sq1KDcaLalQBpRGFsqNdDYTLar8FSzNjWnBLDpAWSFqIoox8779CeaRXHJjXGVZSfko3oB5kyxy/V8wqXkh1Oq+BpS8aVvWyeSuT1JKs8gdf1JWa7ngeGT8AA

There is no effect in changing to a different material. This is not a hardware problem.
