### ISSUE TITLE
Color.fromRgba & color.toRgba methods

### ISSUE THREAD

**Issue by alon6699** [AnalyticalGraphicsInc/cesium#8161]
Hey, Color.fromRgba method returns absolutely revers output. 

For example: it's known that 0xFF0000 is a red color but when using Color.fromRgba(0xFF0000) 
you get a blue cesium color (aka 0x0000FF).
In the console it looks like this: {red: 0 , green: 0, blue: 1, alpha: 0} 

Also the color.toRgba() works the same revers way. 
When it's a blue cesium color, you get a hex of red color.

Please fix this issue.

**Comment by mramato** [comment]
@alon6699 you're assumption that red is `0xFF0000` is incorrect. Since there is also an alpha component, the value is `0xFF0000FF`.
