### ISSUE TITLE
RequestScheduler double counts image fetches in Chrome (using createImageBitmap)

### ISSUE THREAD

**Issue by steve9164** [AnalyticalGraphicsInc/cesium#8162]
RequestScheduler counts requests when `startRequest` is called:
https://github.com/AnalyticalGraphicsInc/cesium/blob/d9e06b005ba93edf23aaf564dc66a8c0e7aa356c/Source/Core/RequestScheduler.js#L202-L211

But when ImageryProvider calls `Resource.fetchImage` and the browser supports `createImageBitmap`, `startRequest` can indirectly call itself (via `Resource.fetchBlob`).

See the following call stack:
![image](https://user-images.githubusercontent.com/13863530/64758462-fe8d2c00-d577-11e9-9437-c269532300ba.png)

**Comment by fredj** [comment]
@steve9164, @kring can this issue be closed?

**Comment by kring** [comment]
Yes, thank you @fredj!
