### ISSUE TITLE
a strange problem when using KHR_techniques_webgl extension

### ISSUE THREAD

**Issue by hanaimin** [AnalyticalGraphicsInc/cesium#8164]
Can not pick the feature when use the gltf2.0 KHR_techniques_webgl extension.

the FS like that.

```
precision highp float;
varying vec3 v_normal;
varying float v_batchId;
varying vec4 v_color;
uniform vec4 u_diffuse;
uniform vec4 u_ambient;
uniform bool u_hasDiffuse;
uniform bool u_hasColor;
uniform bool u_hasNormal;
uniform bool u_isLightOn;
uniform vec4 u_specular;
uniform float u_shininess;
uniform bool u_twoSideLightOn;
void main(void)
{
	vec4 ambient = vec4(0.2,0.2,0.2,1.0);
	vec4 diffuse = vec4(1., 1., 1., 1.);
	if(u_hasColor)
	{
		diffuse = diffuse * v_color;
	}
	if(u_hasDiffuse)
	{
		diffuse = diffuse * u_diffuse;
	}
	 ambient *= u_ambient;
	if(u_hasNormal && u_isLightOn)
	{
		vec3 normal = (v_normal);
		if(u_twoSideLightOn)
		{
			if(gl_FrontFacing) 
				diffuse.rgb *= max(dot(normal,vec3(0.,0.,1.)), 0.0) * 0.5 + 0.5; 
			else 
				diffuse.rgb *= max(0.0, dot(normal,vec3(0.,0.,-1.))) * 0.5 + 0.5; 
		}
		else
		{
			diffuse.rgb *= max(dot(normal,vec3(0.,0.,1.)), 0.) * 0.5 + 0.5; 
		}
	}
   gl_FragColor = diffuse + vec4(ambient.rgb,0.0);
}
```

but  if I modify the FS code like following, pick-feature is OK. note the last line code modified crazily.

```
precision highp float;
varying vec3 v_normal;
varying float v_batchId;
varying vec4 v_color;
uniform vec4 u_diffuse;
uniform vec4 u_ambient;
uniform bool u_hasDiffuse;
uniform bool u_hasColor;
uniform bool u_hasNormal;
uniform bool u_isLightOn;
uniform vec4 u_specular;
uniform float u_shininess;
uniform bool u_twoSideLightOn;
void main(void)
{
	vec4 ambient = vec4(0.2,0.2,0.2,1.0);
	vec4 diffuse = vec4(1., 1., 1., 1.);
	if(u_hasColor)
	{
		diffuse = diffuse * v_color;
	}
	if(u_hasDiffuse)
	{
		diffuse = diffuse * u_diffuse;
	}
	 ambient *= u_ambient;
	if(u_hasNormal && u_isLightOn)
	{
		vec3 normal = (v_normal);
		if(u_twoSideLightOn)
		{
			if(gl_FrontFacing) 
				diffuse.rgb *= max(dot(normal,vec3(0.,0.,1.)), 0.0) * 0.5 + 0.5; 
			else 
				diffuse.rgb *= max(0.0, dot(normal,vec3(0.,0.,-1.))) * 0.5 + 0.5; 
		}
		else
		{
			diffuse.rgb *= max(dot(normal,vec3(0.,0.,1.)), 0.) * 0.5 + 0.5; 
		}
	}
   **gl_FragColor = diffuse + vec4(ambient.rgb,v_batchId);**
}
```

So strange.

**Comment by OmarShehata** [comment]
@hanaimin can you provide a sample glTF file that shows this issue?

**Comment by hanaimin** [comment]
> @hanaimin can you provide a sample glTF file that shows this issue?
thanks, the sample glTF(glb) file :
[0.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3616954/0.zip)

**Comment by hanaimin** [comment]
and the tileset here:
[tileset.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3616973/tileset.zip)

**Comment by hanaimin** [comment]
and linked shaders:
[Shader.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3616995/Shader.zip)

**Comment by hanaimin** [comment]
@OmarShehata  hi, is there any solution for the issue?

**Comment by rainliang000** [comment]
in the glb file, the diffuse value alpha channel is 0.0, default it should be 1.0.  
                        "u_diffuse": [
                            0.866667,
                            0.721569,
                            0.133333,
                            0.0
                        ],
or you can just change the fs shader to ignore diffuse.alpha 
	if(u_hasDiffuse)
	{
		diffuse.rgb = diffuse.rgb * u_diffuse.rgb;
	}

**Comment by OmarShehata** [comment]
Thanks for the tip @rainliang000. @hanaimin can you confirm this by adding:

```
gl_FragColor = diffuse + vec4(ambient.rgb, 1.0);
```

As the last line of your shader?

**Comment by hanaimin** [comment]
@OmarShehata @rainliang000  Thank you very much. both solutions are OK.
