### ISSUE TITLE
How can convert KML(without model) to 3D Tiles

### ISSUE THREAD

**Issue by Minhom** [AnalyticalGraphicsInc/cesium#8166]
Sorry for asking questions by Issue for I can't use forum because of my network problems.
I got a InSAR data，and It has about ten million points tissue through CSV，covers a wide range of areas. I want to conversion it to 3D Tiles. 
I have try convert it to KML frist and user ICO,  but KML only support KML with model.
Can I convert to CityGML first and convert to 3D Tiles?  I'm trying to do that but I'm not sure if it's working or not. 
I really need some advice.
Thanks a lot !!!

**Comment by OmarShehata** [comment]
@Minhom this sounds like it might be a good use case for this proposed feature here, to allow Cesium ion to tile points defined in a CSV file:

https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/179

For now, you might need to either create a single model that can be attached to all your KML points, use a point cloud format like LAS/LAZ, or convert to something else that ion supports. You can see a list of currently supported formats here:

https://cesium.com/docs/tutorials/uploading/

I'm closing this but feel free to follow up if you're still having problems in the issue I linked above.

**Comment by Minhom** [comment]
Thank you so much,  It's useful for me!



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月17日(星期二) 凌晨1:16
收件人: "AnalyticalGraphicsInc/cesium"<cesium@noreply.github.com>; 
抄送: "何明宏"<1076307024@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AnalyticalGraphicsInc/cesium] How can convert KML(without model)to 3D Tiles (#8166)




@Minhom this sounds like it might be a good use case for this proposed feature here, to allow Cesium ion to tile points defined in a CSV file:
 
AnalyticalGraphicsInc/cesium-ion-community#179
 
For now, you might need to either create a single model that can be attached to all your KML points, use a point cloud format like LAS/LAZ, or convert to something else that ion supports. You can see a list of currently supported formats here:
 
https://cesium.com/docs/tutorials/uploading/
 
I'm closing this but feel free to follow up if you're still having problems in the issue I linked above.
 
&mdash;
