### ISSUE TITLE
Billboard color is darker than expected

### ISSUE THREAD

**Issue by WebHero0544** [AnalyticalGraphicsInc/cesium#8180]
为什么在使用billboard时，设置的颜色与渲染出来的颜色不一致，渲染出来的颜色偏暗

**Comment by vinstics** [comment]
cesium在1.61之前默认开启了HDR，会导致颜色有偏差，从1.61版开始HDR默认不开启，这个问题要好很多。

**Comment by OmarShehata** [comment]
@vinstics is correct. Although without seeing a code example or a screenshot it's hard to tell for sure. Please upgrade to the latest CesiumJS or disable HDR with `viewer.scene.highDynamicRange = false;`. If that doesn't fix it please post a [Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) example and/or a screenshot and we can re-open.
