### ISSUE TITLE
ClippingPlaneCollection bug

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/cesium#8181]
Sandcastle example: 
Why does the same data use ClippingPlaneCollection produce different results? I want to know the difference between two pieces of data that can be loaded successfully. Tell me whether it's the b3dm file or tileset. json.
test1：
![image](https://user-images.githubusercontent.com/42527845/65223648-39511000-daf4-11e9-8dbe-529bfb19f50f.png)
test2：
![image](https://user-images.githubusercontent.com/42527845/65223704-5685de80-daf4-11e9-9dcf-f0bb7083a767.png)

Browser:chrome

Operating System:windows 10

datas: 
[test1.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3630020/test1.zip)

[test2.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3630026/test2.zip)

**Comment by OmarShehata** [comment]
@simonasdmd thanks for uploading your sample data. Can you please provide a Sandcastle example we can run that has the clipping plane set up to reproduce this?

From the screenshots you posted it looks like the clipping plane is behaving the same way in both of them, but that the attached plane entity doesn't match up with that's being clipped in the first case, potentially due to https://github.com/AnalyticalGraphicsInc/cesium/issues/6573, which you can confirm by turning off the logarithmic depth buffer option on the scene.

**Comment by simonasdmd** [comment]
![image](https://user-images.githubusercontent.com/42527845/65295636-90a6bd00-db94-11e9-83ef-08441b6dbba7.png)

I replaced the data on the case. But the test2 data is normal. Tes1 data exception. Please help me see why. Also, what you said about using "scene. logarithmic DepthBuffer = false;" doesn't work. Is there any other way? Thank you very much

**Comment by OmarShehata** [comment]
Can you please provide a Sandcastle example we can run that has the clipping plane set up to reproduce this? You can click the "share" button in Sandcastle and paste the link here.

**Comment by simonasdmd** [comment]
Well. But maybe it's because of the network problem (I'm in China). Clicking "share" may not work. I clicked "save" to produce an HTML file.
I just changed here：
![image](https://user-images.githubusercontent.com/42527845/65398538-52a2d680-ddea-11e9-8f00-50930e94438f.png)


My directory structure：
![image](https://user-images.githubusercontent.com/42527845/65398491-1a02fd00-ddea-11e9-954c-5608a3c90aa6.png)


html file：
[3D Tiles Clipping Planes.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3640442/3D.Tiles.Clipping.Planes.zip)

share：
http://localhost:8080/Apps/Sandcastle/index.html#c=7Rn7U9s4+l/R9WY2ztUohEe3l0DvgLJTZrYLV9J2dkqno8Qi0WJbXkkOZHf43/fTw7LsOBSuvd+OacGWPn3vlz4PBugoSRBBs5QVBcvnqEhJTmNYMQ9oTnlGlVghxZFc8FukFhQJWggqaa6IYjxH/FqvXuWDgT+dJ2jGcyV4ag5kZJ4zVSbUwTrkCZOK5DOKbplaWEBeSoqv8qt8SQRaMnpLBTpEOb1FJ1SyMsMfzFrUm5nXEyBCWE5FL0Z/XuUIflh+zY/53Qhdk1TS2C5KmtKZZvYsT9iMKC6a+4oKAXguBF+yhMKmozYTlCj6kYs0mViQqH+V3/fHlkE5oyDGoWMUm9dxxb1W6fn0N6ArAeRT7/jsLXDZu+AsV+gk5WWiX89yqwPz8pYnNO19HtfimxU47oRL6LScH/MSpMjnH3haZlSe5mSa0gQ1JaLJnF6qVQpwNYASpd+/I1mR0smqoBJ2AmYdwKwUAkx8WsM1wT5tfwZNeGkVEXOqfgVWt/G2E8BY+TRXTDFqdFBJZs1BkwsNMK7VpT3QrEmDFxzq0kA6f7ld0Ny6CEr4rSOsn96Aw6VtT7kE49H8siAzeroESRxQFBoLzwggkdqeAR4sqTrLi1IdGZ+JrsvcPmR8STNA1a/sYaRksxuaWK0ABxavXvTguOCSaQSajvHRaxQ5LhN6Df6bRCGWPvrhBwtY/TwAjFnyVHhs1Nn3UtQR4kwCYnQeGW+AxxlEiWBEe6ojfcJTLvDHN2eTU6zD+ygtFiQC39jvb8TCSwX+Ss3RTkzhSaNmWdv4hGRUkBObdbQRqXF7Y0ftfCY4HIJ78Nx4k59oV8c/n/40+fL6/OMv/coT3wGrRFapi1eOWBbWDcviezihx7LRBb3ROnyooc0HzPsEcw2/k7Va3gUJzPJcG8Ql6qeaVae08ePM+f7CG/N9kYAK2rbU8WqtqZ++hz0DPI9PKk+zrMmBNFVE516fcaCoCHXh0g5eoa16i+ZJvRHYqMrgzw8dvkcHy9vz95enX96efzi1Cq5EQ7Z8Gqatxn+qhLYZqJJDUFWKHPlzUUNCA4t9s3BYcRrw7hCESUqXpntfnVgKDYsaB7ylnCQTuxyVIvUUm3Woaf2TcO9E+6OVps2srqifmhl5E5Yo3ACbwRPJd3WijJH5tTXE233z3K8xfo7rZ13pP7IEOqhR3TLgjvr/LwSoAAhQORVZcxnjW020ehlcCJaBpyypxCRJGryaP7uvKxUGKgBtAhX4HTDZ0uqotVDxs8YQNh3PJXSeza7HMWplfaArGjccrEIKbpmsoNnLGHSb0Hd25dcqtqYO72WxoMJ4n0PS3Bg3TwmSsFJ7TxMK23UvpQG3Cv+D82zCI4c9Dh3mDbCrVcXUbPGO5HMK7rEPnrGNd+KK0j/QHnhIv4FZJ5K/ORxviRLsbg/T30sohJHXBOcKK0Fyec1F5sO8gj57ffrL5GzyazPl6B9IohNo2Jv3BsQk9N/gMCRNV6jqesD1iDLtvaPak0jTRZ4uXsN9VBSAgeQI3M4ggWKVGab0TQR8EwqYQdliAAJbr1ZaR9JazR5okTGJoWLhxKI8bGsAEs1Ew6TmrrNRb91R3A+rZ0VyQdl8oYKK6eF9jotabMUbnA5budpUmrGFMx0kVp51+a4hCkIBv5aOLPcNwe5DnwOmUaTFZPoqMIY/B21+UprP1WKMnj9na27lrw1wunUMLBGxLoXW14xVnb+ou3aYvNUiYvK0c05IRZ06jTuOGL5GqAObuZsxKK8SUOr01qXGncjH6o6O3/CtH3cj9Z3a6Oud2gYUFdsNltJ0SmY3kAILKtQq+lqhjm37vImEawWbN8wNQLZf7BJn/dh9c+m+md68cNUVExelXESBO7S8tNUt1E2BRY45pA5xCzWhLgdw6eei4aUzMDBPKU753O2Og2p63+h/dI9hStT/OwwbqVXQdSU/nYle0zn0lzLaGu7s4u0f9/ZeDP8Zoz0obfvbuz9uv4jR7rbmc1zjXNji2MhsC6z4O1iGtBYNd/ebBwpdRv2cwhds0PXa4qJotf+NSgwnIkc9tlhjgyYkxgXzczLP4aTK7hIvWgj/U+qAz03kOWXFmo0QJ31kqsvh6rTWiAV5zxOod0N2R+FbAGPKyXoaLAVbI2ZvdCTVbLxsrWfQKGRldsHuaHrJ/tAgQ23b+KFatqFxDOI79DirHqilepThC4RVn4f6hoL1lGL1XxWqh431lZr0iHpkgqmKqY60/Y3V539ceb5adZ5YcYIK0ao0j6sy9y79Q/t6wfXgWkul4DIt2Tx3YVPYCXOCpit0DKZP6QpdrqSimdQHzYWDZe9FMJo54/k7KnkpZtTkyCOpJwlJ9HL/xV41iPZnehgP4B8YWA0HVdP4m+R5r5rJ6vGzmT4/isjwxd7OsKLCqll1g9alGRC/JooMGpfCgR9t10/ndUbp5M4oaRN2sykdkSMm3NMXeMTzdNozJguv9VYrfugz0YnAfpswTmdvCsz0ftLkAb2gw9Ly4UYHnIPH6jqQ8FlpJigQ3KepGaYcr0BHPQfS05ScPm9yPrsB/7PZJ/JVswuE6LvOseOjBo0r0laA9ilg4nwqqVjq0hue6q1P7nt9LMupnAk2DXobCMsPJC3DMYzWWu36+v5YAaHDw8PW+L+RC7v1bsICgdXow8iGm5E1HPYpOHc24wwdOUzSJnJdytW+4OH8fIRM+ZJWn4uC2Znz5eZVK8h7T7tuDfdNX7b/EkPHs7+NX+7s91uitySzXWYVPmFGeqr3PDBM6XajZcOHOoaXTjnNGcIj5jsa7zcIst6fPoZ/02D5ftdxETa2PjpaFT885J/Hnm9/J3BB5um1ugBB9aD2CFpL3/JtGMhZSK9dB935zS0c74Y9bj31Cwfypog9i58dSNAefWVB/82yggulG7zIFBjILZBD5WBaQnel8EzKioW/VykzMLeu+XOhTTxCYj4l0d4O9PXuPzh4GIWFnvnk8xHaK+6C5SkXCRVb9tYcbt63yDI9ZW/0adBpMGhDt0gKlXgErWeSpHSd4pbixQjtNKhWW1OuFM/C3TZZ08vThtTXPFdbt2ZioscMafC542BQafcgYUvEksOrZ61v2lfPwMeIlLBzXaamSb569upgAPCNYzr+gcVzEDMlKw2yGL762S5ijA8G8Lp+yrEN4JanA/uNAUEPRrZ0VQQYXmiXBWWHX4tjGxOjji/Ehj2Lp8JqjaFgUwu4oLObKb8DyQwOLZnu7uA9JGvAKHjKA7nIcWF7xhHqGTo9YADpZFIPAJfm1COZ0X3kJl7W08lmFiyAOYKkPaMtbk1wlf8F

**Comment by simonasdmd** [comment]
I came up with a way. You click here. 
![image](https://user-images.githubusercontent.com/42527845/65399353-bf1fd480-ddee-11e9-8ae4-4ea80b9141ca.png)

Then put test1 and test2 in the corresponding directory. Then replace the url. That's all right.
![image](https://user-images.githubusercontent.com/42527845/65399376-d8288580-ddee-11e9-8abb-ae1df6f97979.png)
![image](https://user-images.githubusercontent.com/42527845/65399406-07d78d80-ddef-11e9-9cf3-d59107b0b4ce.png)

Just in case. I copied the code of js. You can use it.
[jscode.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/3640486/jscode.txt)

**Comment by simonasdmd** [comment]
hi~
But I see that the bounding boxes are calculated correctly. Is there anything else at the center?
My data is generated with "obj23dtiles". Do you know this?

**Comment by simonasdmd** [comment]
@OmarShehata This question is very important to me. Can you help me?

**Comment by OmarShehata** [comment]
@simonasdmd can you try uploading your model to Cesium ion and convert to 3D Tiles that way? This will verify whether the issue is with the offset in the geometry coordinates.

**Comment by simonasdmd** [comment]
@OmarShehata @shunter 
Hello. It's normal for me to slice in the XY direction. But there is a part of the error in the Z direction. I tried many ways. Want to know what attributes the planer reads. Where can I see it? Maybe it's a calculation error (but there's no problem with the central point of the bounding box). I'm very troubled now.
![image](https://user-images.githubusercontent.com/42527845/65575795-372efb80-dfa3-11e9-8706-ae445c972312.png)
![image](https://user-images.githubusercontent.com/42527845/65575925-7eb58780-dfa3-11e9-9a11-23b319700504.png)


I will attach my obj file and my 3dtiles file.
objfile:
[test_99.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3650899/test_99.zip)
3dtilesfile:
[Batchedtest_99.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3650900/Batchedtest_99.zip)

**Comment by OmarShehata** [comment]
@simonasdmd is this a different version from the earlier tileset? What changed?

Have you tried uploading the source data on Cesium ion to see if the clipping planes work correctly for that?

**Comment by simonasdmd** [comment]
@OmarShehata 
Previous data is a bridge head. So there's an error in the XY direction. This time it's the center of the bridge, so the error from the XY direction is gone. The main error is Z direction. I don't know how cesium judges cutting. I downloaded the latest cesium-master. This problem still exists.

I am in China and I see you in France. We have six hours'jet lag, which makes it difficult for us to communicate synchronously. You can process data in your way. Is the problem still there?

Source data (objfile) has been provided.
Source data:
[test_99.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3655498/test_99.zip)
The data I converted:
[Batchedtest_99.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3655499/Batchedtest_99.zip)



In my opinion. The bounding box's scope and center point are correct and should not have this problem, because it has described the scope of a model.

I think there are several directions to confirm now:

1. Same obj data. Will you have the same problem after you deal with it? (Determine the computational problems in the transformation process and the attributes of the corresponding computations)

2. Can you fix this problem by setting the settings for cesium loading?

I hope we can work together to solve this problem. As far as I know, many people have encountered this problem.

Plant trees for the benefit of posterity.

Thank you again for your help, my international friend. Thank you.

**Comment by OmarShehata** [comment]
@simonasdmd I think I can reproduce what you're seeing with clipping on the Z axis [in this Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=5VZtb9s2EP4rRPZBMuDQdhp3rZMGa502U1DZbeIkTeqgoKSzzZgiNZLyS4b8953ebDntBgzop42ATR7v/bmjyFaLnGkmLemD4Wl8fklYGIIxxCqyVqkmXEnCjAFrxrKQoZ6SNIIJS4V9mwuP1BwkeUMcWJ/PgrOQD/m5d/XodQbcM5686IZ976U3T75c989fUxT6Izqbo5C3ur153x2ezmZ3lx3hP34+/Di64P5DaG8fBvHtZbtzGw/m/o3fHYwu5ncPHv/YP0/u0Jg/ul376yVnNx/a3oNaDUZe13/0D/yHz+vJZxp86XjX/NsQfhe/6pvXvN1py5UO37/yX/bPWTBcpGc3wafh3fLg0Dkay7FcME0WHJagMQ0JyxIOep3vuU6Yk30lLeMStNPYaFkuANFBtUKfmhAk0ETzmFu+AENZFLljSXDUDBfTi9NRoe7+WUhkI9WiR7ZQX4DBOoRAJ1rFb7NKeJF72D046DSaW6VWazTjZhNNpMBIx5IZWwBhRKiQWaxkkxhFluBoIKnhcoqsWEUgfGY1X2U1TwQLgXBLmCXtJmkTLo0FFhE1IZFmy1zJEjsDgnlaxAsZGQVM29k2nprZTTIjbDQzUTo2FJixA4UaV8lIfeAriD5oFoNboYPGcMXkizzrU5hqAONmATUahZMnnMsqFLg/KhWPlFsiUEpRhbHpJTfgTlIZZhgQF7RWukFqkIdKGiWACjUtuUeVl9zFtkH8LC8sdqkccWOZDKFH2mP5lMuWKcylCucqtdRqFs7djW6tc5QSAcsaLlJhGiOadAr2vYBs+W6NVXZKkbzdnttlSSLW77iMsCRma79Z2S0clXDQUPAkQclPgkkwu03er/P6SgjIgap6MilUeuTrFrC/03brjE0R3Q7NSlf+NYr/wtg99nAJ8vMEEYxhYEAvWCCgnqBToe40qEkDE2oebOvrVtzG8yJh1oM0DvA8b0TKMvMJcbkZsMGWs9MfGmyqZdUTxZSFnM0/Rph+K2D72r6nNf/V8miTddELKslCz+rytXRrYWURcyeDl3xxyqOOMpCVBzmbfHci3cBU99o+2gr8hIaoxo8a46c3SDXuax+7p8a2FE9N8iPEbv/riOVgdX4iYnf/C8Qq2P4dYvf5Ub1kMgrx4sKLAu/0UfGZ9UGmbnl8G0d7zb1jY9cCTgrl33ic4DWX3ekupS0LMSaEAbWCNJxnCBlT+fmlug9qCAR4dUy1SmXUI3oaMPfwoEmqX5u+atRATzAmRKBHDpNVbTtQOgK9r1nEU1NnPj1zy2WS2p0yg7Y8ZGKfCT6VPRLzKBLwvcd9q5IeOdjxWrECZa2K61x0e9yqIDqO+ILw6M1479kDa7xHQoHPTuRMUiEu+SOM906OWyi/oyYUy/wMMVbB1pnIrHPysdiklB63kPxeq0wZxYuYMs7JadnLlXjOKECx6wRQDZ8vUwwDgZBI7Xe62EEZyVZIHhYEPpYSpDq4jJhl+wFe0EgvmEjxkVCdlybJN64SlMFtJ3fjbOPZcZud0swyYoBU958t5zaqFP4C). Clipping on X or Y, distance = 0 cuts through the center of the model. On Z, it seems the 0 is at the bottom of the model, whereas I would expect it to be through the center. 

I will investigate a bit to see where this unexpected height difference may be coming from.

**Comment by simonasdmd** [comment]
@OmarShehata 
Thank you. I will try as many methods as I can. I hope we can solve this problem as soon as possible. Make cesium better.
My friend if you travel to China. I think I can invite you to eat some food with Chinese characteristics. (I am in Xi'an, China)

**Comment by simonasdmd** [comment]
@OmarShehata 
hi~
I tried some methods. But it did not solve the problem. Are you making progress?

**Comment by simonasdmd** [comment]
@OmarShehata 
hello~
Have you made any progress? Can you share it with me?

**Comment by simonasdmd** [comment]
@OmarShehata 
Have I been forgotten?....emm.....

**Comment by OmarShehata** [comment]
@simonasdmd I'm still planning on taking a look hopefully sometime this week.

**Comment by simonasdmd** [comment]
@OmarShehata  Hello, is there any progress?I still can't solve this problem

**Comment by simonasdmd** [comment]
@OmarShehata hi...

**Comment by simonasdmd** [comment]
@OmarShehata This problem is too difficult. You can't solve the problem？

**Comment by mramato** [comment]
@OmarShehata should this be re-opened or not, you mentioned you would look into it but never followed up.

**Comment by simonasdmd** [comment]
@mramato Hello, sir. Can you help me with this?I tried a lot and it didn't work out.

**Comment by OmarShehata** [comment]
Confirmed this is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/8053 and opened a fix here https://github.com/AnalyticalGraphicsInc/cesium/pull/8392
