### ISSUE TITLE
context_lost_webgl

### ISSUE THREAD

**Issue by caven-chen** [AnalyticalGraphicsInc/cesium#8198]
I used three Rita Invida p5000 graphics cards to output multi-screen and the resolution of viwer container is 5000 * 3000. When refreshing the page, the browser will prompt context_lost_webgl.

**Comment by OmarShehata** [comment]
Can you share a code example and steps to reproduce this? Have you tested Chrome, Firefox, other browsers etc? Does this only happen when the resolution is that size, or does it happen for smaller sizes as well?

**Comment by caven-chen** [comment]
Just test it in Chrome browser. The whole pixel of application is 15,000*3,000, and viewer container is only one part of it. When viewer container reaches more than 5,000 pixels,
The View. prototype. createPotentiallyVisibleSet method will show error,
But if add blow codes before
If (! Scene. isVisible (command, culling Volume, occluder)){
Continue;
}
added codes
If (isNAN (bounding Volume. radius){
Continue
}
No errors will be displayed, but it will still be webgl context lost

**Comment by OmarShehata** [comment]
There is a maximum texture size that your hardware can support (see these numbers here https://webglreport.com/). If you're just trying to render on a large screen, you should set the viewer `resolutionScale` to a number smaller than 1 so it draws to a smaller canvas and scales up. If you're trying to do something like generate a large render for print, a better strategy would be to render it over multiple frames and stitch it together. 

I'm not sure that there's a specific action we can take here.
