### ISSUE TITLE
Preferred Camera Orientation for Following Objects

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#821]
There needs to be some way to specify what the camera's reference frame is for following objects. The objects can have the type of reference frame and then compute it client-side or have the pre-computed orientation.

We also need velocity information for LVLH. See #818.

**Comment by mramato** [comment]
I'm closing this as OBE.  The Camera object gives user total control over the transform and the high-level Entity API now uses LVLH, NED, or @emackey's magic Geo view depending on the speed and altitude.
