### ISSUE TITLE
Broken link to "Cesium Sandcastle Clipping Planes Editor Demo"

### ISSUE THREAD

**Issue by Smoreley** [AnalyticalGraphicsInc/cesium#8217]
Broken link to "Cesium Sandcastle Clipping Planes Editor Demo" in the ClippingPlanesEditor documentation. http://help.agi.com/STKWebVisualizationLibrary/ClippingPlanesEditor.html

http://help.agi.com/Apps/Sandcastle/index.html?src=Clipping%20Planes%20Editor.html
redirects to 
http://help.agi.com/STKWebVisualizationLibrary/ClippingPlanesEditor.html

Which throws a 403 Forbidden.

**Comment by hpinkos** [comment]
@shunter

**Comment by shunter** [comment]
The Sandcastle examples are not deployed publicly for SWVL/ion SDK classes.  You can run the examples from the release zip using the local server.
