### ISSUE TITLE
Error in Clipping Plane Collection

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/cesium#8220]
Sandcastle example: 
Hello. It's normal for me to slice in the XY direction. But there is a part of the error in the Z direction. I tried many ways. Want to know what attributes the planer reads. Where can I see it? Maybe it's a calculation error (but there's no problem with the central point of the bounding box). I'm very troubled now.

![image](https://user-images.githubusercontent.com/42527845/65576142-f2f02b00-dfa3-11e9-999f-e95cab132441.png)
![image](https://user-images.githubusercontent.com/42527845/65576187-0c917280-dfa4-11e9-8fa7-b69d3d604c79.png)

I will attach my obj file and my 3dtiles file.
objfile:
[test_99.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3650916/test_99.zip)
3dtilesfile:
[Batchedtest_99.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3650918/Batchedtest_99.zip)

This problem has appeared in #8181 but has not been solved.

Operating System: win10 64

**Comment by simonasdmd** [comment]
The example is in 8181.

**Comment by simonasdmd** [comment]
The example is in [8181](https://github.com/AnalyticalGraphicsInc/cesium/issues/8181)

**Comment by OmarShehata** [comment]
Let's keep the discussion in https://github.com/AnalyticalGraphicsInc/cesium/issues/818 since it's the same issue.
