### ISSUE TITLE
IBL Sandcastle demo issues

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8230]
http://localhost:8080/Apps/Sandcastle/index.html?src=Image-Based%20Lighting.html&label=All

1. Under Safari/Mac, the `Use procedural image` check does nothing. If it's not supported on some systems, we should be indicating that.
2. On Chrome/Linux, everything works but the `Use procedural image` checkbox seems to be flipped, i.e. when it's off it uses an image and when it's on it doesn't:

![image](https://user-images.githubusercontent.com/1495196/65967448-98d1e880-e42f-11e9-84c4-055d7d120e99.png)

CC @lilleyse @IanLilleyT

**Comment by IanLilleyT** [comment]
I could not repro the second point on chrome/linux

**Comment by IanLilleyT** [comment]
On second thought, point 2 is expected behavior.

**Comment by lilleyse** [comment]
Maybe the wording should be clearer: `Use procedural image` -> `Use procedural skybox`

**Comment by lilleyse** [comment]
Or `Use procedural environment lighting` to not get mixed up with Cesium's actual skybox

**Comment by IanLilleyT** [comment]
@lilleyse I updated the wording
