### ISSUE TITLE
New Resolution Scaling demo is confusing.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8233]
1. The demo starts with 0.25 as the resolution scale and "Use Browser Recommended Resolution" is checked to off.
2. Checking "Use Browser Recommended Resolution"  has no affect on machines with `devicePixelRation === 1` but doesn't set the resolution scale back to 1.0 either/
3. On a machine with `devicePixelRation !== 1` it doesn't use the recommended resolution either, it mixes it with resolution scale.

@lilleyse @IanLilleyT we need to think of these demos from a user perspective.  What is this demo trying to accomplish?  If a user does not know what resolution scale means, would they be able to figure it out from this demo in its current form and make use of it in their application?

I know how these features work and the demo still confused me.  Even a comment at the top of the demo explaining the demo would go a long way to helping the user.

We need to do a much better job as a team when it comes to putting ourselves in the users mindset and writing demos that actually illustrate concepts and help them use Cesium.  Most of the newer demos fail miserably here.

**Comment by lilleyse** [comment]
`useBroserRecommendedResolution` and `resolutionScale` are separate concepts and can be changed independently of each other. I think the points you mentioned are expected behavior.

Maybe a comment in the demo will help explain this.
