### ISSUE TITLE
KML and clampToGround option

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#8239]
Similar KML to https://github.com/AnalyticalGraphicsInc/cesium/issues/8238 but with both `tessellate` and `altitudeMode` set so that the whole line should clamp to terrain. However it only clamps to terrain if `options.clampToGround` is `true`. Should it clamp to terrain automatically even if that option isn't passed in?

```xml
<?xml version="1.0" encoding="utf-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <Folder>
      <Placemark>
        <LineString>
          <tessellate>1</tessellate>
          <altitudeMode>clampToGround</altitudeMode>
          <coordinates>-94.2853118971204,34.0604044149558,200.0
            -95.2849440296246,34.0600224952286,200.0</coordinates>
        </LineString>
      </Placemark>
    </Folder>
  </Document>
</kml>
```

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVHBSgMxEP2VsJduoSTqSepaRAseFBQsetlLTKZuaJJZJrMrKv67aXerVnMJefPevHmTXpPoHbwCiXMR4VVcQXJdkI87rJyY3fMKI2sXgSYz8VFHkQ8DUYbuCXtngeZ7oSHQDE9I3q4GSjmt4+f0rI51HJxkMhBBenzR5LgJziyh5eayW693Y6y1TzDw83TYssOYMj46Gx2AtJiLg24DOttTsjT9p2zRkaKU8Tq0K7wm7KLNXKYO8qTfxlazfsCODGTvsdEPlqS2thxD3wS//K7kYNqWk4a5nSvl0WjfYOL56dHRiUqs2Rm1hLRhbNUmeGXRyHzn1Y5RpwfLekcMKyx/nKdnxayoEr95WAxZLlxokVh05EspFUNoff6EpJ47swGWJqVty0rtRZV1vXD2vC7+/G9diLyWlHJl3Xn/4N6hLhaVyvwD2Taiiy93PZDXb1tKc7y4HUApZaXy87+KEf2zpl8dvwA) (will need to replace url with a different url)

**Comment by mramato** [comment]
It is clamping to the ellipsoid or not clamping at all?



> Should it clamp to terrain automatically even if that option isn't passed in?

No, the entire reason `clampToGround` is optional is because ground primitives have caveats that need to be addressed before we basically just turn it on by default everywhere (i.e. terrain on by default)

**Comment by lilleyse** [comment]
> It is clamping to the ellipsoid or not clamping at all?

It's setting the height values to zero and not using ground polylines.

> No, the entire reason `clampToGround` is optional is because ground primitives have caveats that need to be addressed before we basically just turn it on by default everywhere (i.e. terrain on by default)

Ah, ok. I added a checkbox to https://github.com/AnalyticalGraphicsInc/cesium/issues/5942

**Comment by lilleyse** [comment]
Also - the original KML snippet I posted had 0.0 heights but I changed those to 200.0. Ultimately the heights are replaced with 0.0 but it's clearer that it happens if the source heights are not 0.0.
