### ISSUE TITLE
Cannot pass a Geocoder instance to Viewer?

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8250]
I want to pass a modified [Geocoder](https://cesiumjs.org/Cesium/Build/Documentation/Geocoder.html) instance to my viewer (in [this forum thread's](https://groups.google.com/d/msg/cesium-dev/RYzGH_8PGQo/hfIFyhGgAAAJ) case, the goal is to create a custom destinationFound function). But in order to create this `Geocoder` instance I must pass it a scene.

So I create the viewer first. But then I cannot set the `viewer.geocoder` because it's a read-only property! 

It would be possible to do this I guess by creating your own CesiumWidget manually and creating all the viewer options manually, but this seems like a lot of effort (and not obvious, there isn't an example on this etc.)

**Comment by shunter** [comment]
I think you would have better success by changing the `destinationFound` property on the geocoder's viewModel after construction.  Generally the view models are meant to be the programming interface from code rather than the views (e.g. Geocoder).

**Comment by OmarShehata** [comment]
Of course the other problem is that as a user creating the Geocoder instance myself also requires I set the "container" element, which is already created for me as part of the viewer, so I would need to know the element ID name, which I can only find from the source (and then my application would break if we ever change the element ID etc.)

So I think the best solution here is to just extend the `Viewer` construction options to allow me to pass in this property or allow me to edit it after creation.

**Comment by OmarShehata** [comment]
This works perfectly:

```
viewer.geocoder.viewModel.destinationFound = function(viewModel, destination) {
    viewer.camera.flyTo({
        destination: destination
    });
    console.log("Going to", viewModel.searchText);
};
```

Thanks again @shunter!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/RYzGH_8PGQo/hfIFyhGgAAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8250 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
