### ISSUE TITLE
Avoid importing Cesium3DTileset in Picking.js

### ISSUE THREAD

**Issue by puckey** [AnalyticalGraphicsInc/cesium#8261]
Since updating to the latest version of Cesium, I noticed my project's bundle size had grown 85% by over 850kb minified.

I tracked down a large chunk of it to a single `instanceof Cesium3DTileset` use here: https://github.com/AnalyticalGraphicsInc/cesium/blob/d26ccfea38dcf4623cf5da3faca141913c64cfe1/Source/Scene/Picking.js#L549 causing the bundle size to grow by 549 kB, while I do not use `Cesium3DTileset` in my project.

Perhaps instead of using `instanceof` we could have a static `type` enum property to check against? For example `if (primitive.type === Type.Cesium3DTileset)`

**Comment by hpinkos** [comment]
@lilleyse please make this a priority before the October release

**Comment by lilleyse** [comment]
@puckey All the code in `Picking.js` used to exist in `Scene.js`. Was `Scene.js` previously included in your project's bundle?

> Perhaps instead of using `instanceof` we could have a static `type` enum property to check against?

Yes, something like that might work.

**Comment by hpinkos** [comment]
Ahhh, I do see that `Cesium3DTileset` has been required by `Scene` for a few releases.  It probably shouldn't be though for apps not using combined Cesium.  I downgraded this to `priority - high`.

@puckey were you using the latest version of cesium before you upgraded to the 1.62 release?

**Comment by puckey** [comment]
I wasn't using the very latest version before – I must have been a few releases behind.

**Comment by puckey** [comment]
> @puckey All the code in `Picking.js` used to exist in `Scene.js`. Was `Scene.js` previously included in your project's bundle?
> 
> > Perhaps instead of using `instanceof` we could have a static `type` enum property to check against?
> 
> Yes, something like that might work.

Yes both of them were in my bundle, but  I guess I was runni
