### ISSUE TITLE
Cesium OpenStreetMapImageryProvider

### ISSUE THREAD

**Issue by hashirilyas** [AnalyticalGraphicsInc/cesium#8266]
The cesium documentation states that for including osm imagery you have to use the following code 
var osm = new Cesium.OpenStreetMapImageryProvider({
    url : 'https://a.tile.openstreetmap.org/'
});
which when used produces this error
"Uncaught TypeError: Cesium.OpenStreetMapImageryProvider is not a constructor"

But the code works fine when you use "createOpenStreetMapImageryProvider" instead of "OpenStreetMapImageryProvider"  as shown in the snippet below

var osm = new Cesium.createOpenStreetMapImageryProvider({
    url : 'https://a.tile.openstreetmap.org/'
});

Please edit the documentation to depict as such the link for official documentation
https://cesiumjs.org/Cesium/Build/Documentation/createOpenStreetMapImageryProvider.html?classFilter=ImageryProvider

P.S I am using cesium 1.61
Regards

**Comment by bampakoa** [comment]
hey @hashirilyas are you working a PR for this or should I take it?

**Comment by hashirilyas** [comment]
I think you should take it.
Regards

**Comment by bampakoa** [comment]
Thanks! Nevertheless, if you would like to do it but have difficulties on how I would definitely love to help you and get it merged by your own 😃 Community is all about helping and sharing after all ❤️

**Comment by hpinkos** [comment]
Hello @hashirilyas, `createOpenStreetMapImageryProvider` was deprecated in the 1.62 release and replaced by  `new OpenStreetMapProvider`.  You must have been looking at the 1.62 documentation.
