### ISSUE TITLE
Deprecated flag in docs is not obvious

### ISSUE THREAD

**Issue by bampakoa** [AnalyticalGraphicsInc/cesium#8267]
Having recently came across #8266 I think that the deprecated flag in API documentation may lead to confusion. Let me clarify that a bit.

The flag `Deprecated: true` in the docs that flags whether a feature is deprecated or not is not styled appropriately and may not be noticed straight away from the end user who is not comfortable with the API documentation. It would be great if it could be set like `flag` or `readonly` flags.

**Comment by OmarShehata** [comment]
Thanks for opening this @bampakoa ! I had actually run into that on the forum and advised them to open the issue because I didn't realize it was deprecated either!
