### ISSUE TITLE
Cesium behind firewall

### ISSUE THREAD

**Issue by bling683** [AnalyticalGraphicsInc/cesium#8272]
Is there a way to bypass the `api.cesium.com` api call? We are using cesium behind a firewall that cannot get to that site. Even configuring to a custom imageryProvider, it seems like cesium always tries to contact `api.cesium.com` and halts rendering of the globe until that call has been satisfied (returning 200 authentication).

**Comment by mramato** [comment]
Absolutely.  By default, Cesium uses ion for geocoding, imagery, and terrain (if you enable terrain).  If you turn these 3 features off or switch to a different provider for them, Cesium will work just fine in a completely offline setup (or online just not through cesium.com).

See this Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Offline.html

There is also some more information at https://github.com/AnalyticalGraphicsInc/cesium/wiki/Offline-Guide, but I'm not sure how up to date it is.

**Comment by OmarShehata** [comment]
Just to close the loop here, I believe this is the same question as on the forum here: https://groups.google.com/d/msg/cesium-dev/JdrKvSEaIRI/2AExANrADAAJ

If you're still having trouble feel free to follow up on the forum!
