### ISSUE TITLE
Look into why CesiumJS release zip grew significantly larger in the 1.50 release

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#8284]
![Screenshot_20191014-125239~2](https://user-images.githubusercontent.com/3451886/66768946-d5ff9700-ee81-11e9-9203-ae33c16c8fc0.png)

I noticed this recently, and I couldn't find anything in CHANGES.md that explains why the packages suddenly grew by almost 30MB. It would be a good idea to make sure this is expected and not something we need to fix in our release.

**Comment by shunter** [comment]
#7006 added new test models with 30MB of PNG textures.  Perhaps they can be reduced in size.

**Comment by OmarShehata** [comment]
My bad, thanks for pointing that out Scott! We can definitely put a much smaller/less detailed model for the tests.

**Comment by hpinkos** [comment]
@OmarShehata is this something you can do before the next release?

**Comment by hpinkos** [comment]
nevermind @OmarShehata, i got it #8294
