### ISSUE TITLE
Cesium3DTileset setting in Cesium does not work for luminanceAtZenith property

### ISSUE THREAD

**Issue by Ma-Wen** [AnalyticalGraphicsInc/cesium#8296]
![问题](https://user-images.githubusercontent.com/44662993/66895978-932af400-f026-11e9-87f2-fe04a2f43257.png)

Hello: When I added the 3DTileset model to Cesium, setting the luminanceAtZenith property does not take effect, the brightness of the model does not change.

Is this what is the reason？

Looking forward to your reply

**Comment by OmarShehata** [comment]
What kind of 3D Tileset are you using? Note that the [luminanceAtZenith](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html#luminanceAtZenith) is used only when the models are using the procedural environment map, which would apply to b3dm and i3dm tiles if they are not using the unlit extension (so photogrammetry tilesets will not be affected by the lighting for example). But you can see that the `luminanceAtZenith` does affect tilesets like this one:

https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Feature%20Picking.html

For general questions like this, please use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). Feel free to follow up in a new thread there if you're still having issues with this.

**Comment by ZhengWeiming233** [comment]
> ![问题](https://user-images.githubusercontent.com/44662993/66895978-932af400-f026-11e9-87f2-fe04a2f43257.png)
> 
> Hello: When I added the 3DTileset model to Cesium, setting the luminanceAtZenith property does not take effect, the brightness of the model does not change.
> 
> Is this what is the reason？
> 
> Looking forward to your reply

hello,I have encountered this problem now. Have you solved this problem now?

**Comment by Ma-Wen** [comment]
no,the problem has not been solved




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CesiumGS/cesium"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 上午9:14
收件人:&nbsp;"CesiumGS/cesium"<cesium@noreply.github.com&gt;;
抄送:&nbsp;"马文超"<460764680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CesiumGS/cesium] Cesium3DTileset setting in Cesium does not work for luminanceAtZenith property (#8296)





  

 
Hello: When I added the 3DTileset model to Cesium, setting the luminanceAtZenith property does not take effect, the brightness of the model does not change.
 
Is this what is the reason？
 
Looking forward to your reply
  
hello,I have encountered this problem now. Have you solved this problem now?
