### ISSUE TITLE
In Android Clipping plane 3dtiles work not properly

### ISSUE THREAD

**Issue by dhdbtkd** [AnalyticalGraphicsInc/cesium#8297]
Sandcastle example: https://sandcastle.cesium.com/?src=3D%20Tiles%20Clipping%20Planes.html
(standard example that Cesium provide)

Browser: 
IOS = Chrome ios(ver 77.0.3865.103)
Android = Chrome(ver 77.0.3865.116), FIrefox(ver 68.1.1)

Operating System:
ios = Ipad pro 10.5(chorme)
Android = Samsung Galaxytab S6(Chrome, Firefox), LG V40(Chrome)

The below image is work with Apple Ipad pro 10.5(chorme).
clipping plane photogrammetry 3dtiles work well.

![IMG_0035](https://user-images.githubusercontent.com/37060597/66897093-3c76e780-f031-11e9-9843-fe13918abe88.jpg)

But.
In Android
Below image is work with Samsung Galaxytab S6(Chrome, Firefox)
Clipping is not normal

![222](https://user-images.githubusercontent.com/37060597/66897183-67f9d200-f031-11e9-8192-8c425bb067cc.jpg)

One more in Android
Below image is work with LG V40(Chrome)
Open Sandcastle sample also work not properly.

![KakaoTalk_20191016_161539364](https://user-images.githubusercontent.com/37060597/66897273-98417080-f031-11e9-9a2a-4fb6baf19a1c.jpg)

**Comment by OmarShehata** [comment]
This is a known issue, see: https://github.com/AnalyticalGraphicsInc/cesium/issues/8061

Can you post the results of your WebGL Report (http://webglreport.com) on the devices you've tested to that issue?

**Comment by dhdbtkd** [comment]
This is Samsung GalaxyTab S6 WebGL report.

![Screenshot_20191018-105900_Chrome](https://user-images.githubusercontent.com/37060597/67060094-89c09980-f196-11e9-8d90-76ef383a78ae.jpg)

This is LG V40 WebGL report.
![KakaoTalk_20191018_110003978](https://user-images.githubusercontent.com/37060597/67060136-a3fa7780-f196-11e9-8c0c-185d4fff941b.jpg)
