### ISSUE TITLE
Cesium selectedEntity infobox won't open ?? Help me

### ISSUE THREAD

**Issue by ILHNYILDIRIM** [AnalyticalGraphicsInc/cesium#8300]
:exclamation: Please use the [forum](https://groups.google.com/forum/#!forum/cesium-dev) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

    this.handler.setInputAction(function(movement) {
      var pickedObject = viewer1.scene.pick(movement.position);
      var pickRay = viewer1.camera.getPickRay(movement.position);
      var fetaPromise = viewer1.imageryLayers.pickImageryLayerFeatures(pickRay, viewer1.scene);
      debugger;
      if(!Cesium.defined(fetaPromise)){
       
      }else{
        Cesium.when(fetaPromise,function(features1){
          var info = features1[0];
          debugger; 
          var selectedEntity = new Cesium.Entity();
          selectedEntity.name = info.properties.name;
          selectedEntity.description = 'Loading.. <div class ="cesium-infoBox-loading"></div>';
          this.viewer.selectedEntity = selectedEntity;
          selectedEntity.description = info.description;
        });
      }
    }, Cesium.ScreenSpaceEventType.LEFT_CLICK);

selectedEntity infobox won't open .?

**Comment by OmarShehata** [comment]
Can you ask this question in the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) ? We try to keep GitHub issues for specific bug reports and feature requests.

It would also help to include a Sandcastle example along with your question.
