### ISSUE TITLE
ES6 relative path is too deep

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#8301]
I still run a development build of Cesium out of a sub-folder of my local server, instead of at the root level as is customary with NodeJS.  Occasionally, this causes bad relative paths to break.

In [Apps/Sandcastle/load-cesium-es6.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/6361718743dba781d01bdf12118fa0458d9f3755/Apps/Sandcastle/load-cesium-es6.js#L3), there is a relative path that has one too many parent folders:

```
import * as Cesium from "../../../Source/Cesium.js";
```

This is only 2 levels deep, but tries to climb up 3 levels, and breaks Sandcastle when run as a development build from a subfolder.

Note there may be other configurations (such as running a built Sandcastle from a subfolder) where the 3rd level may be needed.

**Comment by mramato** [comment]
Thanks @emackey we'll get this fixed for next release.

**Comment by mramato** [comment]
@emackey it was just this one path (plus load-cesium-es6.js isn't used in the built version).

I pushed a fix directly to master after hosting cesium under a sub-dir and running all of the tests and build Sadncastle.
