### ISSUE TITLE
cesium 如何通过 heading， pitch，roll  获取新的坐标？

### ISSUE THREAD

**Issue by hanyingling** [AnalyticalGraphicsInc/cesium#8305]
![捕获](https://user-images.githubusercontent.com/33933148/67188194-66a81b00-f41e-11e9-8252-9c811e708254.PNG)
BC 垂直于地面，BC = AC ， 如何通过heading,pitch ,roll ,获取A的坐标。请问Cesium 如何确定A的坐标

**Comment by OmarShehata** [comment]
How are these labels placed in your scene? If you have a [Sandcastle example](https://sandcastle.cesium.com/index.html?) that shows this (you can click "share" and paste the link you get here) I can probably point out how the positions are computed.

If you're asking how to place them in these positions, given these line entities that already exist/are already rotated this way, I think the easiest way would be to extract the orientation from the entity as a direction vector, and use that to push your label position by the magnitude you need. This forum thread discusses how this can be done with some sample code:

https://groups.google.com/d/msg/cesium-dev/xPOMVgEbids/sZdw6GMCCAAJ

For general questions like this, please use the Cesium forum. We use GitHub issues for bug reports and feature requests.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/xPOMVgEbids/sZdw6GMCCAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8305 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
