### ISSUE TITLE
3D tiles spurious disappearing

### ISSUE THREAD

**Issue by DaniilSNikulin** [AnalyticalGraphicsInc/cesium#8306]
Good day.

I've tried to create 3d tileset from single mesh. When tileset have single tile, all visualization are good. However, if tileset have got children, on runtime tiles are spurious disappearing (Video of disappearing below).

![tiles_disappearing](https://user-images.githubusercontent.com/31708320/67191835-081d7580-f3fb-11e9-9c1b-484387655d0f.gif)

This behavior was confused me, because tiles, that disappearing, including leaf tiles with zero `geometricError`. Could you suggest, what reason of this behavior could be?

Tileset can be downloading from [here](https://yadi.sk/d/GM-saBxXMNm3ig).

**Comment by OmarShehata** [comment]
How was this tileset created? Do you see the same issue if you upload the source data to Cesium ion (https://cesium.com/ion) and create a 3D Tileset that way?

**Comment by DaniilSNikulin** [comment]
Thank you for the quick response @OmarShehata.

It turned out my error was similar as in this [issue](https://github.com/AnalyticalGraphicsInc/cesium/issues/4333): i did not correctly create min/max fields in gltf file.

I apologize for asking a question when I did not fully investigate the problem.

**Comment by OmarShehata** [comment]
No worries @DaniilSNikulin , glad you figured it out! If you're unsure if the issue is a bug or not you can always ask a question on the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).
