### ISSUE TITLE
SceneTransforms.wgs84ToWindowCoordinates made wrong calculation for popup

### ISSUE THREAD

**Issue by leation** [AnalyticalGraphicsInc/cesium#8308]
I want to show a popup that can follow the moving map for a Billbord.I try to use SceneTransforms.wgs84ToWindowCoordinates for transform WGS84 (world) coordinates to window coordinates,my code is as follows:
```
var c= Cesium.Cartesian3.fromDegrees(108.874997,32.359956,803.1);
var p = Cesium.SceneTransforms.wgs84ToWindowCoordinates(viewer.scene, c);
```
But its computed result is correct only under horizontal view angle or 2d view.Is there any other way for transform WGS84 (world) coordinates to window coordinates?
![Image text](https://github.com/leation/mydata/blob/master/popup1.png?raw=true)

**Comment by OmarShehata** [comment]
Can you please provide a [Sandcastle example](https://sandcastle.cesium.com/index.html?) (you can click "share" and paste the link you get here) that demonstrates when the coordinates are incorrectly computed, and steps to reproduce?

**Comment by leation** [comment]
@OmarShehata My code is as follows:
https://sandcastle.cesium.com/index.html#c=rVZtc+I2EP4rLl/itJxiQiAvzWWaA5I4DSZHTHJp6WSEJUAgS64sQ+Am/70r2xBDks5Np5nJWHr22RftrlbMsLIiGVufre99YcEfl+LEqjhH6Ojw4Pj4sJyjWJ9Y1X1UrR0f1+o5iDmAR04VVfri5de+mKW2oiR6YESPwWTFcYrwFWWjsQa8buAGjVkSIlcKROgQJ1yfBwGNY19OqQDSDl1cjweXAeuwa7e3dCsec2NXdGtBw6270+jbfeP6GAHpb3I5BZJb9SbdiXd5MfEWlYnXbFdv/K/Ltj/VneY9f7xzao/hRdjxz58fJ9Na+6HHbhrX0R9grL2E/d2cBfveLLi8X7qTaOCGF8tBAxzCN2DZlyzMl0xc7sCXj4nR9XvLjt+rdvzWvvfNQZ/2awnpLVte97peD4XbaP9+dDUM6s+ji6f728Pbg/hheneFe5PO1508NzNG51TBiQWdW3lW7lPM3gnSbUMKjZmgaqe8KpOmSgF0q+SMEapOVoqBoljTB6k48TOKvQvV2QVfmejWVKLFaUiFtg0cU33J5QAEMdNMihTEhDSAQFUbqykEYrABEyRltmYgusKC8FzSF8NEBEbZes/JKmZzWCEJhaMSGSRGmMe7ovZLhM36JWPTKBgyYgT4/VLaQU0jLQpjveAUzfN+KzTfL0bl+T3yeNWFxZ78mB7laUmDwINY8kTT94icDnVKqjjvW9Iy+lf5AAfTkZKJIA3JpUq5ajTA9n6tVjb/TtlBtd1NVU2ftWkPyF6qEOIoO9iaZrKOlSomfUR1nvH4y8LHIw+HFHI/kGTxmvz02npZuUD/T+evXJCCCEcRhUjHjBPbRGLUXjZa4U0PFfugkNZC2zew0rDCooqGSoZNOlKUxjaQEcylspUusM4WMH6sn61qMV5wx/QCbGZ3CqV7RoFLiJ17T4+Qez9Zr8pFIRMw2Ar0FGXPlN+xJYU56JQ3ZYGp1/oKptVD3VZzi5U1XpcOqaIioGv+1SaOGjfn7dsnv/N02e30vG0rhMV4wGmTRnrs01g3Waxxaq7mOK/Ul2z58rYsb+/7Rl3+34IE0FkKvxYkDqigKENzWrZBQ77wZbFGBA7HBM7LVMgCSVSO1gqoVAyqnQu+b2ceEyZG64y3sR7DdewCikVsO8jZLW9XWwfjj/ifjt/RUJLzEwsEP1KDD0ZpsRA/nrlQzmhLENPjqbkb6AjgKnvtzqa7xZQkEVnNaGgCe1Wvd+LcZhYDTAPaiq84Oqpmbv/HNtqYQa9m7owPX0ENhlKFMZqP4qMDXz5ANuW8IaUipmHAcBpM2cSwssSGlv1TtJEGRXWixOrwxdEEx/W23qnXkfll4RK7+B6tXKz1Nh+ECD1vPy/bzOxliNCiSHwplUunqfws0/qNhZFU2koUtxHa0zSMuDnt3iAJphSe0jg2oZzurZRO4TG1GPncL239jOiXrIDjOAbJMOHpVOuXzk73gL+hxmV6bzozqjheGMq4cnaTgQih0z3YvtXSUvIBVgWL/wA

**Comment by leation** [comment]
Sorry,Just I had test some points,the resean for my problem is the point's altitude is not right.If  the point's altitude is absolute above the terrain,the popup's position is correct under all views.
