### ISSUE TITLE
WMTS + Time Sandcastle is broken

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8310]
It seems like the URL for the imagery has changed here: https://sandcastle.cesium.com/index.html?src=Web%20Map%20Tile%20Service%20with%20Time.html

You can find the "Snow Water" imagery layer described on this page: https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+Available+Imagery+Products#expand-SnowWaterEquivalent3Products

And the NASA API described here: https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-OGCWebMapTileService(WMTS)

**Comment by mramato** [comment]
So we know the fix?  Why not just open a PR?

**Comment by OmarShehata** [comment]
I don't know what the fix is. I thought we'd need to get an API key but it looks like maybe it's just that the URL has changed. They list this as the URL:

```
https://gibs.earthdata.nasa.gov/wmts/epsg{EPSG:Code}/best/{ProductName}/default/{Time}/{TileMatrixSet}/{ZoomLevel}/{TileRow}/{TileCol}.png
```

And our Sandcastle example has:

```
https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/AMSR2_Snow_Water_Equivalent/default/{Time}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png
```

`ZoomLevel` doesn't seem to be a valid tag in our WMTS class. I didn't have time to dig more into this but I can see if I can see if it's just a matter of updating this URL to pass the correct parameters.
