### ISSUE TITLE
Create a lot of labels called GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8315]
```js
var viewer = new Cesium.Viewer('cesiumContainer');

for(var i = 0; i < 10000 ; i++){
    viewer.entities.add({
        position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
        label : {
            text : 'Philadelphia' + i
        }
    });
}
```

![image](https://user-images.githubusercontent.com/1495196/67537263-9b2f0780-f6a8-11e9-9378-503dbf12ee2a.png)

@jasonbeverage could this be related to recent SDF changes?

CC @lilleyse

**Comment by lilleyse** [comment]
It looks like this goes all the way back to 1.15 when billboards first became instanced. The Billboard Instancing dev sandcastle has the same error messages. I'll try to look into this when I have a chance.

**Comment by lilleyse** [comment]
Turns out this error doesn't show on windows/ANGLE which is why I didn't notice it happening during development. But it's a legit issue and fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/8325.
