### ISSUE TITLE
PolylineCollection update instanceIndex is out of range

### ISSUE THREAD

**Issue by tinco** [AnalyticalGraphicsInc/cesium#8321]
Browser: Chrome
Operating System: MacOS
Cesium version: 1.5.3

Hi, we have an app where we create and destroy a bunch of Polyline's. Basically the user cycles through different polylines, and every time they select a new one we delete the ones they were previously looking at and create the ones they're looking at now using. 

The polylines also have a `CallbackProperty` on the `positions` property that updates the positions every frame.

We get an error from Cesium originating on this line:

https://github.com/AnalyticalGraphicsInc/cesium/blob/d26ccfea38dcf4623cf5da3faca141913c64cfe1/Source/Scene/PolylineCollection.js#L471

Quite reliably when we delete a set of polylines and then immediately render frames. If we remove the `CallbackProperty` the error does not occur.

Are we hitting some race condition bug where callback properties are setting a dirty flag on polylines that already have been deleted?

We're creating the polylines with `viewer.entities.add` and destroying them with `viewer.entities.remove`.

<img width="1037" alt="Screen Shot 2019-10-25 at 4 53 17 PM" src="https://user-images.githubusercontent.com/22532/67583345-aedf7a00-f74b-11e9-9f21-8189c9cd5e89.png">

**Comment by hpinkos** [comment]
Hello @tinco, I believe we fixed this issue in a newer version of CesiumJS. Can you try updating to the latest release and see if you still experience the problem?

**Comment by tinco** [comment]
hi @hpinkos thanks for the quick reply! I just upgraded to Cesium 1.62, and the error definitely became less reproducible, it takes a couple tries before it breaks now.

<img width="1071" alt="Screen Shot 2019-10-25 at 5 43 04 PM" src="https://user-images.githubusercontent.com/22532/67584997-059a8300-f74f-11e9-932e-882989920da7.png">

**Comment by hpinkos** [comment]
Thanks for trying that out @tinco.  Could you put together a code example that reproduces the issue in [Sandcastle](https://sandcastle.cesium.com/)?  That would be a big help for us tracking down the problem.

**Comment by tinco** [comment]
Hi, thanks for the examples. We've been trying to reproduce in Sandcastle, but haven't had any luck so far. It seems that disabling the positions callback fixes our problem, but disabling requestRenderMode also does.

My colleague is working on a bigger Sandcastle right now to see what else we need from our app to reproduce the problem.

**Comment by tinco** [comment]
Ok we made some progress, this Sandcastle is huge, but if you leave this running for a couple minutes you'll eventually get the instanceIndex is out of range error:

https://sandcastle.cesium.com/#c=7Vt7c9s2Ev8qaP6oqakC8/2Q41xTx+3lmsSe2G2uY3s6NAlJTCiSR1BS1NTf/RYESAIk5Ti9pnM3c0mnFYHFvveHBchuwhJtErIlJTpGGdmiE0KT9Qr/XI9pB1H9eJJnVZhkpDyYoo/XGUIVKUsYOC/zTRKTctYsi0oSVuRtXqbxJSfRJlO2oCT/WhNavSEZkL/KYzJDVbkmMHc3ObrOrjOuBKYRyQiOye16cbHMt9+X4YrQc1JekCjPYtCRrarpQfEqSQkllao5/4/1/JJParW+6zKdoYNlVRV0dnhIq7wMFwQv8nyRkrBIKI7y1WFIypxGYfY4pLCQPo7J5jAOq/BX9nRoGo9//Hu5+cf60vyuKp89Szy3/OfFLyfkp4tDoQh+R/PsYNykokxWSZVsCMVhHGtiBSMUZL/l+eoylyeus/k6i6okz1CxTtPznCbs4TI/AaeUoVaIgQmPSUmqdamS0pb2qiG+mVzpN6DiXvZ0wJ/2BDTDeBUWmlZM0PFTToDQ4SFK5kj7CgY/oqIXmLCs4FeYWdoE3XF6CCqtUBi/W9OKxPvpZeo4KQlX+xgpLo5qtXE7zxcNuOGMLCBJtZZu2iow2bskL1dhmvxGtIb0AYtW67RKinT33e4iCtOwlNbqWHckDsxvTrQSAyuSVajKt2EZU8SN2ieCpVLHtRgoJULWjLLBu4mIfpRCnqNXJKTrktQy6yDWTi7XEdSIBr8r8qECtlmWVyF3VpEnWXWaVZAEhE5RCrjQPE2aPKiWUFMKIQTr6uZImpXXDSY7eTDVPcgkQjeYF7+O7hGtPN+jhfxYk9V5Spn0CHFwG3NKazfP0H2m8dm9bpGmz4q6wmBWMEYoX1eM70me5oC3Sp2k6W0YvQcwLkhZ7TRNrkj2h5VkpyymJIXEh3L7+mvJBgaBRZ5BHpxDfk3k9W0eNRKZDviX05cvz94edWR33U+SUrJP7ANYn/zy7PXDGX+u4q9On7/46dXF+ZsXr3/44c3p6X2iPsns+bM3P569efb6h9MxLndTNA+BD98EpTC+TeJqOUNmOx4N48pGNB3Agv+DjY5LkXwg6QXg0Qw5YvBOyJccwzYvvOIFfs7SiuJ5Xp6G0RJgmz2ricLzT6bvigsTkbA15EheAeRqNoQZz91pN9nNfDpf92xxTMuBExGXNFOKpZ2tt1+JrKk1XKzpUpPtawjbFWI/gs5l95Jki2qpwM+YQ9Oa7Khf/iMFHP2/cv+nK3cRFgJ8FTaXwOLi/Nmb09eXLWkc0iXPnxkydGX4PKygeYaKMJ1+5XbZ8wr2mTIJU7UhOs/THZt9DmwaijZ1pKSb/AEkmKIEOvMPav6l0FtnfI/NoDpbN7Eo1uToG2Sg4+NjuWIm9+RvrcaC5CtSlTtc7QpSrz5gli2gde6lgJCtf16UR6PZ/OgvEiJaa44GK7qoPAANCxGimaqYBJJ0hq6Ex++NzxXT7OZmKrOReHwenirngAfLHsNdhLb9nYv9WYl0nCnpK5HcjaGz3CdxcGYj3Xzjbd7eK0dIbQDdosSZY6Se9vNb2K7ti0Fame+0XnfXHpflNnRfT9mVGVFrS5xc2kQCdfMN0cjArmE/+5/zVI5NY369E2eE5i+3vEwWy+ot1Eq+ZYB9VpfER8QSSCR8U9vwiFh5z7raFimgJNqMq3P1EX2YIcsL3EC3sGHqhm6btudNETCyAt+yAxwYjuEbvucZU/QbdD16YJq+BccoT/cdNzDaDJN4Gdh2DTswDd2VWXkuDHm+57sSKx37pm8Htj/KSQdOtmMFpm0pSgWOa9mmbgWOxMrAjq27umcEwRgvExuuafiWbrSsHGjuPMtyXccMfE8x0LdMLzACw0R3N3JkRiNyuc3//IgY2DcM1zccx5YVNsEfnuXbnm9LCttYtx3f8mzDcsYdqQe2A7F0XEfmBqOuDosMQ3EkeNlydScY4eUHAdZBkG0CQ5kVuBEkWbYn62Vi1/B1D7xrjqvl26bjGl7gmTIvljym7fu+pdjI5mxdN4NPBaXp/6SAPCQk40HpF4rlQuLbbq9OdNMKbNtzLSWNIOVcyzMtU0JitVJsAywDnyuVYnkeCNEdU6kU1wwciIs9yswPfOYfzzRhteJL34SyNn3fVOLigOAg8PQ9mkFkoJR80zBMJcqOBUUHUQh0uYodrENhWVZXLlN+pyH1mWwHHiLZdKSWbiQUFG0AmX9pAHSxDn4yfNdR4mpAUA3bhwxWQcuHEnSgAsay2sYWlK1hWgBSMi/dcoLAcmwvkErE87FnuBYIBtFj3CDhLMOCFIIylbkBkBmW7fqWzCzAtmeCMYC/45oFgB0u1LaSbyyZIaK+r6KAx2rc9f3RalND8kUQ0MbgQMNmOCRr6ziA8Lqj+4arqBs4gesBWrrj6A+Ws70sUOPL4Me0dMhdxYue5TgWZL87vr/5sDEAqYyAwAu8DqoGsFDJFUd3TROssMajC9FwPNjiDCVXPD+wAgu2pcBTytYDOg8CZX8iKF8QAV1sei7sM5ahK+ZDFuuG7YCpllorYKFveN440NjYhpBBhgdSdvsYdgzfttlmrpSKDdGC/cK19+Ep+AfSAHYPJTCe67oWsHUUxWwP4NQGzBxnBqHxoAcA4DQVO+uGxYfyVwE1gPqFX4F7PwQOoGw6LKUGAOH8Mk8hlvkc5esShUVRjxkYHZC07rMP0DasoiX0xcukouzcxxpxMYkSigr2UiWGg1a90sSovcsoQBbSWtKs7ngR+RCuihQa3DCL6yXwp13SGiMW1/8erFyQqlvJbtTrU+wUxWW4PeXitJqK3bKnKeFyLCwTII09NMnIRuhAUCMkxChKSVhShbyZvcUozfOCImjJy9YzTHOVfnRxxPwFc9WSrBD062HKzAn7xzhEcyAJK8Qf6mt8YEXZ+SxaNsxisJDM4ZBCgUMkTo+oEMdHSSS/8KbcB3Qy1MzGaEtEWICXEskJeixmWDKBozX+1Hpe9pswDk46TYzZIhZ7dfSkCXyzlp2KGSV4oz6rglANXLI3RrdC1iLZkKyvMDBhI901W/O6sfMIjy+EQS0oNYKaICv6M1yNW3Dre9q9grmE09dFLfJEKdLh+xih6VQc4NTXLU1KHTfJNfqyhK+UphSH84uekVlFM4mshgcG6JV06KbdkRnMvWRxSFiuLVmeweEVco1s2Ck1W6Cf1wS/o2he5itWH+/ZGCRwHbz6Vonzqd8q1hr9qji0O/wOJ+t3K+Lkq9wRDEklU2R0aDND9nMdXNXao76STSx+/x19JX7jutQlhZXbKuV9aM+ImuPAw2Khwl261Bu72lfeqn28a+9Z+ihyjIr6R0twdvsOsgBz1GjvmeQblYMmUZovBMSdKalmSNxHtbk0dhUkm8yvgiRrxWcFmpzKyuu33gWHiORIoMYKZuC6+i5a9h6LqwIMyj1lHzJqHOpdI7KXrp8dYaUP4p5plVypGq5we1nVF6isT5uXGjqrzNpBahWL7z5aA0XFdKghSCVkZ/ZPURauyH+BewHcL5MVyddV/2UK2FvjD9s3N3kSszdxrKHhV7+kLAGXonBNGQDxr14YaVSGdCmETJHh6Horiqm9HyP7yDRKtMeuu0YE6LwKd7cEQWNF2FabEaAFtVgnoTQSVHQSbMeMuy2ZgfSD0XyPWfdZ8xAj6gCy9GCC4D/S6GCj3b8vMfrmLL7vLlbK386W3lZ5/+Wnipf824vuM5PmWwyVqlFU/pJiX0ljANC4qd4VHgDvMTe0fpp0gpgdI2KUOhE6ztPdZT5GjHuX3soLinw+pwyqlUEEaRfGUA8z4Qksnqf1tn72/Ix1j9E6BWzmGzavHtYd8Q9mRANHGk+K9VBztIKfqrAigR51hvSpOlyG2YIor9HU9wm8+lU4UBKpRrmT8yG2KlCmlISmNHc9cPsL6j7aR8yrZEiilJdkO2tm1KZSk7F58gBsUAS1sCQteVGRleqwSa+d6mmwv6saRqnfWO0BJb5NDdFT1LHaVrdvbuTR76EBbfXszJkOwUj5GG3AWtn1rvSbnhjFot5iaBbVkWa7foKMT9l6b1sxlvz9G4Fug44e0jvubx0j3juOEES9zJIh/8/pMaPRJvNP6jG7VkNumPq+lQ4+31b0cbIAJCSDM8zJ+Z5TzMiy5mijrhkebkaWKucddX2/T95nxx9IrL+sY5UuHLvD70feCamX/PLd1g26k6/0K1DjJKREfGux7zA+OHtzHrBrvoBcKTdhqoV0l0VIajsb1njsTMkIwm2YVNCvpeFOM/S6t5RWST12H1WgGOZJSfn90cGDeamb3CegShajXrh9KYHGTV3k9Zfef1TiiCCZbccMsmmUH9vcGpZ7W4cB0SjJLkfb5Q7FOaE8c9U62uble97Z38JRhN1abZckgyaqvielSdvHM5v+Buk+RY4uDiDXGc+29hNubkW8LsPhJ+EsrwFRVwklmlYSmqcb9r6LMMCVq1I6PLVULUfl2+Hh30fTR09otUvJU87r2wTiBzC/LlMN40PoEQrWJ9LD23X0ngDc0vpTiyeHzaIncbJBSXx8/aj3/xxcP0L1PRnMzOGcwr56vH709Mkh0CvL0rxuLs/gVASuYCRL4+lLPogxfnIIj8NVVZ6nt4ApHcd/Aw

It's a bit annoying that it takes a couple minutes, and that it's such a large slice of code, so we'll continue whittling away at it.

BTW the tileset used in that Sandcastle is property of my employer, please don't use it for any other purpose than researching this bug.

**Comment by hpinkos** [comment]
Thanks for taking the time to put this together @tinco 
I'll try to make some time next week to look into this issue.

**Comment by tinco** [comment]
I just noticed that it reliably happens when I switch away from the tab for a couple minutes and then switch back. I have no idea what that means. I guess maybe chrome buffers the intervals and then runs a bunch in quick sequence and that makes it more likely for the bug to happen?

**Comment by OmarShehata** [comment]
Thanks @tinco . I am able to reproduce this. Were you able to get the same issue using any of the tilesets already on Cesium ion (like this photogrammetry one https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Photogrammetry.html) ? That way you won't have to have a public link to your dataset if you can't share it.

**Comment by tinco** [comment]
No worries @OmarShehata, the data is not really secret or anything. Good to hear you were able to reproduce, did you also trigger it by switching tabs? In our real app there was some sequence of actions that would reliably trigger the exception without switching tabs. I think I'll spend some time this week or the week after improving the sandcastle or maybe digging through the source to find the source of the race condition.

**Comment by OmarShehata** [comment]
@tinco yes I was able to trigger it by switching tabs (didn't try leaving it long enough without switching).

I have run into a similar behavior where a CesiumJS app will crash if the tab is switched away for too long (although only on Linux, and I haven't been able to consistently reproduce), so creating and digging into a reproducible example here is definitely helpful!

**Comment by hpinkos** [comment]
@tinco sorry for the delay on this.  We've been able to reproduce the issue but haven't tracked down exactly what is causing the error yet.  We'll keep you posted when we have updates.  Thanks

**Comment by mramato** [comment]
@tinco I'm pretty positive that requestRenderMode combined with viewer.flyTo is the primary culprit here but haven't been able to track down exactly how. If I change your example to the below, the problem goes away:

```js
setInterval(async () => {
  testCase.drawElement(element)
  viewer.scene.requestRender();
  await delay(1000)
  testCase.selectPart(element.parts[0], 'first part')
  viewer.scene.requestRender();
  await delay(1000)
  testCase.selectComponentPart(element.parts[0].componentParts[0], 'first component part')
  viewer.scene.requestRender();
  await delay(1000)
  testCase.selectComponentPart(element.parts[0].componentParts[1], 'second component part')
  viewer.scene.requestRender();
  await delay(1000)
  testCase.selectPart(element.parts[1], 'second part')
  viewer.scene.requestRender();
}, 5000)
```

In fact, it seems only a single requestRender call may actually be needed.  The below change fixes your demo (as far as I cantell).

```js
    setInterval(async () => {
      testCase.drawElement(element)
      viewer.scene.requestRender();  
      await delay(1000)
      testCase.selectPart(element.parts[0], 'first part')
      await delay(1000)
      testCase.selectComponentPart(element.parts[0].componentParts[0], 'first component part')
      await delay(1000)
      testCase.selectComponentPart(element.parts[0].componentParts[1], 'second component part')
      await delay(1000)
      testCase.selectPart(element.parts[1], 'second part')
    }, 5000)
```

The intent of the above change is to continue to use requestRenderMode, but also inform Cesium after the scene changes so that it will render a single frame and performany bookeeping that the Entity API needs to do.

The general idea of requestRender mode is that you call scene.requestRender whenever you change anything about the scene manually.  Whileit works without calls to `scene.requestRender` most of the time, in this case the use of flyTo is triggering some code that I think is out of sync with the scene.  I'm going to continue to look into this and see if there's something we can do at the Cesium level that makes sense to fix it, but I recommend you add a scene.requrestRender call anytime to change the scene anyway.

Can you test this change to see if the problem goes away?  If so, can you then test that change in your real application and report back?

Thanks.

**Comment by tinco** [comment]
Thank you @mramato, so your fix is to reduce the amount of request renders, so the scene has some time to naturally go through the rendering? I get that might fix the problem in the test demo, but I don't think that's a feasible fix for us. I make the calls to requestRender because I can't be sure there is other movement going on that will eventually trigger the render. Sometimes the camera doesn't have the move, and cesium is done loading the highest quality, and all the `selectComponentPart` does is update a color or something (through a callbackproperty), and it won't show up unless we do the requestRender.

I get the code paths intermingling here are pretty complex, but why is calling requestRender different than just having cesium continuously render? If flyTo was able to go out of sync with render calls, would that problem not be even bigger if requestRenderMode was off?

By the way, I also get this error when flyTo is not active, I think it's purely an interaction between `viewer.entities.remove`, `callbackProperty` and `scene.requestRender`.

**Comment by OmarShehata** [comment]
[Here's a reduced test case](https://sandcastle.cesium.com/#c=lZJPb5wwEMW/yohLWGllkuyty64akUukSKnUP5eSgwOzWyvGRmPDilb73TtgWEKiHsrJ9rx583s2rSRoFZ6QYAcGT5ChU00lfgxn8VUxbDNrvFQG6Wq1zU1uWu4qrNZYeGXNsvOL1Z1mbXapx31TGCJcgQZFTapSXrXohCzLeLYK9kkCGaH0CPVo5oDw2GhJusuNQ/9gPFIrdVwMumnmGm6ug8WhMYFtKYhX8Cc3wF8fYXLnADPCQDSK+q+2TvXn7tOUMJPkeSXNRhzIVvd4JER3RyS7+Oc1M6zhdg2b51UwOQeifsnBvtdlCDa6gj14NDNTM9SnfEz2Nu0l1ZwjIIYcYnbd/TfsdqSd73AkvmNAAgleVXzBzts6QCpzBGlKfpnKthjkDPuNZbbx/2ItNEq6BFqmnRgG3fwgYUA8pVyQDqjn3ETrKHW+07gPxc+qqi15aEjHQiQeq1rzJJe8NMUrelE413emydSUlqoFVe7y6N0vn0fMLJ3jyqHR+qv6jXm0TxPWL9q0lSVfyVOLpGXXS37d7B/DoRAiTXj7sctbq18kvXH8Cw) I got over email. I'm able to pretty consistently reproduce this now, crashes almost immediately when switching out to another tab and back.
