### ISSUE TITLE
With Inspector-panel visible points and markers become partly obstructed by terrain

### ISSUE THREAD

**Issue by DoktorDrehAmRad** [AnalyticalGraphicsInc/cesium#8324]
Hello,
when adding the inspector panel the point-entities do get partly obscured.
<img width="338" alt="Screen Shot 2019-10-26 at 09 43 32" src="https://user-images.githubusercontent.com/53915337/67621582-94a2ac00-f7de-11e9-92e9-97c3be05a634.png">
See also:
https://sandcastle.cesium.com/#c=jVNha9swEP0rIl9qg5HZ9q1NwzovW0NTVkhYvxiGIl8SUVkS0tltVvrfK0t2kqUtzIHgu3vv3d2T3DJLWgGPYMklUfBICnCiqenvkEvOeAgLrZAJBfYsvShViZFB4QlBVUlPickYzJQzwFHbW/EkVCCp1rdyHBT4Tr1ACC9iyWih0PlaSFJjRS1QtOAoq6rkaLS7Dng3lAstpe8ktErStJfaMlXJ040W3AKohWEcpi0ovI6gJLbjzDNdJ9CTqQOcKdPgVRRfNyq+QIspeQ4u+FacWfT6TB2W4qwGy6gR/GEqpTBOi6pjUaOd6CSyfsWN1CugMGC65sQ/g6zeWGa2gnvlfoXiKEvXVtfF0D3ZzxEPiJDuP1oa/HuOWSKq817M28EQfjZ+uDTrq2QYkZwfNsvy/MjGfcsvYYLvsPG2uuEO3DLcUtRD9ngNKrXaCGwqSDPyP3CGEX2YjmuprR9tGKUL6f31bDndQ3SD0l/U4j3kt/lVcXOKvBcVbj3yc5d/ie4FwMFG/wsH85KR+PLBjVruDND59MfyTzGfFTcR+/YpwxmNstHY4U7CJOK+itpoi6SxMqE0R6iNdwBcvmr4AyDlLtzOcT6QxpVo/XFelqOTb7QcES6Zc76ybqRciL9Qjibj3OP/oUnNKqE2v1qwku06yPbTZB6TlNJx7sO3LNRarpg9UnwF

**Comment by OmarShehata** [comment]
This is because the inspector turns on depthTestAgainst terrain. All you have to do is set it back to false after creating the inspector:

```
viewer.scene.globe.depthTestAgainstTerrain = false;
```
