### ISSUE TITLE
how to do this "Overlapping points become brighter"

### ISSUE THREAD

**Issue by huashaoxu** [AnalyticalGraphicsInc/cesium#8332]
Referring to this example, it cannot be implemented in the new version.
Why does this code not work?
https://github.com/NYPL/pic-app/blob/master/app/assets/javascripts/PIC.ts#L412-L418
Demo
http://pic.nypl.org/map#

**Comment by OmarShehata** [comment]
For general questions like this, please [use the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).
