### ISSUE TITLE
eslint now failing in all branches

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8334]
eslint is now failing in all branches due to the below code:

https://github.com/AnalyticalGraphicsInc/cesium/blob/898cb379657bcc85a79b3bcd8cf4c893ee7e6a54/Source/Widgets/Cesium3DTilesInspector/Cesium3DTilesInspectorViewModel.js#L1116-L1131

@hpinkos git blame says you wrote this 3 years ago, ring any bells?  Why are we self-assigning or is it an actual bug?

I'm assuming they fixed or updated a rule in eslint which is why it popped up now.

**Comment by mramato** [comment]
I'm guessing it's supposed to be `tileset[setting] = this[setting];` and not `this[setting] = this[setting];`

**Comment by mramato** [comment]
Or perhaps the other way around?

**Comment by mramato** [comment]
So I figured out that the original code is "correct", by re-assigning already existing values it's updating the underlying tileset to the new values.  Another case of trying to be too clever.

I pushed a fix directly to master in c016b731f5bd33df9eada76c78a97e3e12263629

**Comment by hpinkos** [comment]
@mramato I think this was a workaround to force an update to all the setters to make sure everything was in sync after the tileset finished loading

**Comment by hpinkos** [comment]
Ah yeah, I see you already figured that out
