### ISSUE TITLE
Is there ways to render image on 3dtiles like texture on runtime

### ISSUE THREAD

**Issue by mct-Naserdin** [AnalyticalGraphicsInc/cesium#8342]
Is there ways to rander image on 3dtiles like texture on runtime

**Comment by OmarShehata** [comment]
Yes! See the textured material option in this code example:

https://sandcastle.cesium.com/index.html?src=Classification%20Types.html

For general questions like this please use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).
