### ISSUE TITLE
Odd outline on label

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8344]
In Firefox, using http://localhost:8080/Apps/Sandcastle/index.html?src=Callback%20Property.html&label=All

![image](https://user-images.githubusercontent.com/1495196/68046139-84447280-fcb1-11e9-8a5e-dd77fe80876b.png)

I thought this issue was resolved a long time ago, but maybe not.

**Comment by mramato** [comment]
Appears to be Firefox only (at least on my machine)

**Comment by hpinkos** [comment]
duplicate #4525

**Comment by mramato** [comment]
thanks, GitHub search is terrible, I couldn't find it to save my life.
