### ISSUE TITLE
WMS-T Sandcastle server is gone

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8347]
https://sandcastle.cesium.com/?src=Web%20Map%20Tile%20Service%20with%20Time.html no longer works because the layer appears to be done.

@tfili can you confirm and see if there is a server or layer we can still use?

**Comment by OmarShehata** [comment]
Duplicate https://github.com/AnalyticalGraphicsInc/cesium/issues/8310.
