### ISSUE TITLE
Sandbox: Add a stop/pause option?

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/cesium#8354]
Dear Cesium Team

Depending on the use case, the sandcastle generates quite a bit of load on CPU/GPU. I think it would be nice to have an option to stop/pause the heavy computational load at certain times. Have you considered that? Or are there good points against that feature request?

![sandbox_stop](https://user-images.githubusercontent.com/15689124/68107595-a6263b00-fee5-11e9-9a84-1b1d7603b35b.png)

Thx!

**Comment by OmarShehata** [comment]
Thanks for bringing this up @tkazik . Ideally resource consumption in the Cesium viewer would be optimized to avoid having to manually stop/resume program execution. 

With that said, there is an explicit rendering mode in CesiumJS, so it only re-renders a new frame when something has changed, so it would greatly reduce CPU/GPU load when idle. You can see how it works in this Sandcastle example: https://sandcastle.cesium.com/index.html?src=Scene%20Rendering%20Performance.html&label=All

Try it out, and if you have any questions feel free to search the [forum](https://groups.google.com/forum/#!forum/cesium-dev) or post a new thread there.
