### ISSUE TITLE
Label text jagged

### ISSUE THREAD

**Issue by easternmotors** [AnalyticalGraphicsInc/cesium#8355]
I am trying to upgrade to Cesium 1.63 to get some of the cool new features associated with it. I upgraded locally and got a weird jagged font behavior. I launched the official Sandcastle and saw the same thing in the examples.

Sandcastle example:
https://sandcastle.cesium.com/?src=Labels%20SDF.html&label=All
https://sandcastle.cesium.com/?src=Labels.html&label=All

Browser:
Chrome 78

Operating System:
OS X 10.14.6

**Comment by OmarShehata** [comment]
We are aware of this and have a fix for it in this PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/8351

**Comment by easternmotors** [comment]
Ah, sorry for the dupe! Thanks!
