### ISSUE TITLE
Billboard under Terrain Tiles

### ISSUE THREAD

**Issue by fironalia** [AnalyticalGraphicsInc/cesium#8357]
Dear Cesium Team,
billboard sometimes they go under my terrain tiles. And they change their place if i moved the globe.
any idea on whats happening here?

**Comment by OmarShehata** [comment]
For general questions like this [please use the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). If you have a specific bug to report please put together a Sandcastle example that can help us reproduce it.
