### ISSUE TITLE
resolutionScale related lighting issue

### ISSUE THREAD

**Issue by vinstics** [AnalyticalGraphicsInc/cesium#8358]
Sandcastle example: [sandcastle](https://sandcastle.cesium.com/#c=ZY5BawIxEIX/SshFCzKhZ+NS8Cr0UOgpl2x2XIfOJpJMVvTXG5VCq3N7b977eLPPaiY8YVYbFfGktlioTvB995aLcJfbFMVTxLx4W7v4yEMJGBFGTj0CRt8z7mg8CMWxoSRXXOuVtkXOjJ2Lqt0HTceURdXMSwAjOB3ZCxbT1/CDAqGUG9+a35IdaFY0bJx+2uG0CuxLaZ99Zf6iCzrdWdPy/2qc/NAGfc6Y2Z9vkcN7t3uYAGBNk68tSYl7n/8Qrw)

Browser: Chrome 78

Operating System: Windows 10 1903

Monitor: 14 inch 3200x1800 250% zoom

Browser Zoom: 100%

Set "viewer.scene.globe.enableLighting = true" can replicate the problem. Happens only when devicePixelRatio not equals 1.
And, images near the pole seem to be strange.

![image](https://user-images.githubusercontent.com/16721670/68180650-79e6e900-ffcf-11e9-9a02-155a274d9416.png)

![image](https://user-images.githubusercontent.com/16721670/68180673-88350500-ffcf-11e9-9ac3-a1f0e9c8ff65.png)

**Comment by OmarShehata** [comment]
@vinstics this is a known issue. We have a fix for it here: https://github.com/AnalyticalGraphicsInc/cesium/pull/8351

In the mean time you can fix it by setting:

```
viewer.resolutionScale = 1.0 / window.devicePixelRatio;
```

This brings the resolutionScale back to the old behavior as of 1.61 (see the explanation of this change here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#additions-tada-2).

**Comment by vinstics** [comment]
@OmarShehata Thanks a lot. I'll turn off lighting and wait for the fix since I have to render model at native device resolution. By the way how about the image near the pole, is it normal?

**Comment by OmarShehata** [comment]
@vinstics I believe the poles look like that when the imagery layer does not cover the poles, and so CesiumJS will stretch the pixels to fill the gap.
