### ISSUE TITLE
Significant polyline artifacts with log depth off

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8366]
I noticed a bad artifact on iOS and traced it back to all systems if you disable logDepth.

1. Run this Sandcastle on any system https://sandcastle.cesium.com/index.html#c=tVPJbtswEP0VQhfJgEvJDRygrmI0sQ89FOhBRU66TKiRRXREBlwUOIX/vaQkN07aAr10AEHkLG/eLBzAsEHiExp2wxQ+sR1a6Xt+P+qyVIzXnVYOpEKTLtmPWrEgttOemlsle3DINswZj7U6LT7WqlYTIrcCFXLSBzDSdb0Ue3x03Z1v2zFdC2Rx9K9ANQKsI+TQNHtswZP7pjU9gLnzzmmVpVXIQyQd2kCi9Uo4GdSLM585ZQMOKu1N4B2hsrmc3XNP+1+mQAmaLOU8r6B/JIyW3Mp45CJ4poupjAtcAT0a4C0dP+sesyI6zMW+Jv+G9T12UhD+H8oz+N84T+2fmVt0cabZnDtKg9ZJBZHUhp0HvwMTWixBXfHW6H6PB4Nos3er1TVfv1+yqzUvwu/DuiiKxfIFTBuJYUkmsIskUTqERqrDhl2/6E/T8fTnRhoMfOOK/EvTDPZ6wFuibAQLX7JMSuuOhNsp6FOYrTaOeUNZaKHD0MKwTjZ/8OI7Oi6sjaFlfg4qGzkw2dzUyZsHUCdMEFgbLK0nquQz1sm2zIP/q7A4rlDy1wENwTG6dKvtl0nJOS/zcP09yk3Lc4FYq58

2. Hit pause and manually zoom into agi

3. At some point, two orbit lines will appear on screen and be drawn as if they were statically on screen, they shouldn't be there and are no where near the view.

![image](https://user-images.githubusercontent.com/1495196/68300897-b9174780-006c-11ea-9af8-aa4c6c23f15a.png)

@lilleyse this affects all iOS devices and any device that doesn't use logDepth.  There seems to be a lot of regressions in this area lately.  What can we do to ensure devices without logDepth continue to work as expected?

**Comment by OmarShehata** [comment]
This looks like it's the same as https://github.com/AnalyticalGraphicsInc/cesium/issues/8356, where those polylines are actually showing through the globe. 

> The points on the opposite side of the globe are rendered in the last frustum which is past the depth plane. The same thing happened in 1.62 but the points would get overwritten by globe commands in closer frustums.

https://github.com/AnalyticalGraphicsInc/cesium/issues/8356#issuecomment-549629310

**Comment by lilleyse** [comment]
Yes it's the same as #8356. Since we're doing the patch release already I can revert back to the old behavior and fix it before the next release.
