### ISSUE TITLE
devicePixelRatio and particle system demo

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8369]
1. Run http://localhost:8080/Apps/Sandcastle/index.html?src=Particle%20System%20Weather.html&label=All
2. On a devicePixelRatio > 1 machine, the snowflakes are much bigger. You can see this in Chrome via the responsive debugger.

CC @lilleyse @IanLilleyT is this a particle-system wide issue, or specific to this demo? (I think it's the latter but want to confirm).

**Comment by IanLilleyT** [comment]
It's specific to the demo. The fix was pretty straightforward: just had to remove drawing buffer width from the size. See PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/8371
