### ISSUE TITLE
application run on sandcastle

### ISSUE THREAD

**Issue by worlddai** [AnalyticalGraphicsInc/cesium#8374]
Why does my application run so jammed locally, but so smoothly on sandcastle?I just set up an IIS server locally, using the latest Cesium1.62 code, and added an ImageLayer,of course,use the same browser。it seems that my fps Less than  30

**Comment by worlddai** [comment]
I just find the reason . when the application run on sandcastle,the window size is just 1135 * 547.but in my browser it was 1929 *1080.when I try to change my window to this size,it comes to smoothly .so  I think it's because the render area is getting bigger then caused the jammed. the reason was found.but I think it was a bug when i use big screen(3840*2160) application.

**Comment by OmarShehata** [comment]
Please use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) for general questions like this. 

Here's a [forum thread](https://groups.google.com/d/msg/cesium-dev/w0_X_GB4P6U/KkOX2aI2BwAJ) with some tips on improving performance, such as by lowering the canvas resolution to render to a smaller window and scale it up to the desired window size.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/w0_X_GB4P6U/KkOX2aI2BwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8374 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
