### ISSUE TITLE
Can the front-end project based on cesiumJS be fully localized？

### ISSUE THREAD

**Issue by wyan-all** [AnalyticalGraphicsInc/cesium#8380]
I want to develop a 3-D earth satellite project through cesiumJS. I know that token is necessary to display a 3-D earth, but can I display a earth locally? Moreover, whether the follow-up development can be fully localized, such as simulating the movement of satellites？

**Comment by OmarShehata** [comment]
Please use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) for general questions like this. I've answered [your forum question here](https://groups.google.com/forum/#!topic/cesium-dev/7Z5Kga2fcSY).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/7Z5Kga2fcSY

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8380 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
