### ISSUE TITLE
how to avoid the width of PathGraphics changing when the angle between 2 paths is small 

### ISSUE THREAD

**Issue by Noah-Gilga** [AnalyticalGraphicsInc/cesium#8382]
![image](https://user-images.githubusercontent.com/42824389/68571300-a69e7300-049d-11ea-9cd4-d19d8bdbae82.png)

in this view, i set the width is 10, but in this view ,it looks like its value<10,when i change the camera position to look at this path from another position, it looks like its value = 10,how to avoid changing its width when i look at it?plz
![image](https://user-images.githubusercontent.com/42824389/68571252-8969a480-049d-11ea-8184-1254cfca33c1.png)

**Comment by emackey** [comment]
Duplicate with #5231.
