### ISSUE TITLE
the translucent top of box doesn't disappeared

### ISSUE THREAD

**Issue by polluxll** [AnalyticalGraphicsInc/cesium#8393]
I use custom Primitive for drawing a cube on cesium,but the translucent top of box doesn't disappeared,but the three.js is correct in same code and setting.
Sandcastle example: 
//the box geometry height equal 40000
//Cesium.SceneMode.COLUMBUS_VIEW
var vertexShader = `attribute vec3 position2DHigh;
            attribute vec3 position2DLow;
            attribute vec2 compressedAttributes;
            attribute vec3 position3DHigh;
            attribute vec3 position3DLow;
            attribute float batchId;

            varying vec3 v_pos;
            void main(){
                vec3 position2D=position2DHigh+position2DLow;
                gl_Position = czm_modelViewProjection * vec4(position2D.zxy,1.0);
            }`;
var fragmentShader = `varying vec3 v_pos;
            void main(){
                vec4 color;
                if(v_pos.x>20000.0){
                    float alpha=(v_pos.x-20000.0)/20000.0;
                    color=vec4(1.0,1.0,1.0,alpha);
                }else{
                     color=vec4(1.0,0.0,0.0,1.0);
                }          
                gl_FragColor = color;
            }`;

var renderState = Cesium.RenderState.fromCache({
                depthTest: {
                    enabled: true
                },
                cull: {
                    enabled: false
                },
                depthMask: true,
                blending: Cesium.DISABLED //DISABLED  ALPHA_BLEND
            });
            return new Cesium.DrawCommand({
                owner: this,
                cull: false,
                occlude: false,
                boundingVolume: this.geometry.boundingSphere,
                vertexArray: vertexArray,
                modelMatrix: Cesium.Matrix4.IDENTITY,
                shaderProgram: shaderProgram,
                renderState: renderState,
                pass: Cesium.Pass.TRANSLUCENT //OPAQUE : 8, TRANSLUCENT : 9, OVERLAY : 10,
            });
https://sandcastle.cesium.com/#c=rVhtc9pIDP4rvnypaahJAnfTuiFzFHIJMyThAkmnk3TSxRawV7/N2iaQm/73067X9tostHc9ZjLxSnq0klYryXY8EsdGP53BmFGfJnQFxt+PgSF/ThjECUudJGRmGCUUlw2Vz3/JksbWAkIfErYxukaQet57jYgT+jMawIWUNB+kwgI7xL1I4MDnhhaONt4DS2A9WRIXGO70hSQJo7M0AWMFTtuIwphylSeDS7pY1pTslB2Fz/tETzAIfsQgjsHt5Yz4x5S3/4Uh7b2GzL2QJMaMJM5y6KJUVW5F2IYGi0zh6glV1hStQuoaPqGB2aidnuBW7ehWzT/cZ+EW/KSEn1ThJ7vg3N6uT9dmKWm9rDdNxSRrvXlpGs6L/+SHLFpOqQ8NjaqF9zSWGEyPTNwF757C85iFf4EjOK+5xR1T7Ns8to7qmr592ZV/fzCy8CFIygz8+ch3ML+8kGm8ofPMRmt9dnIkfmirRgn/ZflBvGhJujnqTYlqFY/v9XhhQ1fEBSPSzP+EQl2kv4EXww5b6sqO5J8m1EJV+ag9UR70PtfIj1QTqspxfVOvRr3iyEJDt2sYHqMRlRmCRQyejT7ENPWtjzC7AuYQrIFlEpmSee55NIrxjK2PF5O3nbp/XC+WjtRLUKeEFIV2TCPw0L6tyqiJK5W1MbaNwovmthjk5tiKO1ZB1SBKMRWiVQ089YeBC+s7incgjaIQyzFuhR0CNIjYgQDag5vA29jGnGDCNHU3gJf0PnGWcIP9wKcvsFs4r8S8D1ARjB1bi2t/RTBKazu7vgqllj7abqP0s+z8cgqF+OHosw5SFOtRiMnCO1sJ3ubpNCg2lumSrTuW44UBmFKfItncwjaq96EIHgOSAG/1/dD3SeCa2N0x9on2NmTn0mOMbEpb7kuiNWehvy9jpXI7f9CcUh5kuxpzjeR2/OxdQdegZ+l8DuwuJgvMLenKh5JmTaa96bD/NLjtfWx+Jzl4aGJR/bEWLBjxy+BMVLIIj8jq/xibn/N4pQxKkzBlDtj6KUqDnVea3Ba62gN/IFwMAq4nweQrg3VbEveHyoUoWU4hxmDtaDcQkJnHy5CoGpr+0tyh9YrEX/fUGhxj/9c9ERC4OCsUKdgbjS97Tx9G59cDo9UaDCc9fB4YhkL/TngZJCkL1GY1YOQ5v94a28PnAFh2mDtd3hWQ0HG81N1TnWdhKhy8D73Uh9qltnLuJFoC290JRHGx1cX3ynutTg4H59fT4fSTriGpN9SuLjXiSuLa6kLXRfEtqrBkjAtretu7nozu+mgMHu7NuPfn3blhG2+bhsqxjXdN4+b+/HbU+4SL46N99Uep5WnkoiEmXlUfhE1bNZzODfMXaZALcxwvXLO4wzJDGg1dftel8NJmpK3+UW5v5a2kPptVlxWA0DGicWJFabzcNm7bczHcieaEA72Yv5XMvxc085Ujln20B4duYK8a73OUT4ORGO6O8ylYUMlaUttvrfa7o3cnKhMhhM9u7RpCEH/tIKDT/q0KuAR86+Hs2i4FvZPN4go3CaMP/Hog8+GzQp+FiZYeJxD1kZEIZ1RNOCRMkIl0Uzr2RvrdMFolTiLmOFSbHEaFufjvtKsIGfTwEFME85ePqeVxyI0QI0N6iMjX+d7KueV+ZSeM/KYMnnq4UlNurV5THglVkzibhpIauW0uLBhAnA8vD5mVOUK5YgVDGJXR8zjXlKhLnu3Ye83cvYYGkhmaeVXY+uOqc3+z7C1di0Jvs6i/oYwzom4ak/KXFBhhzhIr6zauYJrV2yql+gRLcUxJ0BadeqBYa6qmN0p0Q4nxUqS9Xd4AhYcVg2FLcS+lzJE8zIaS0cokrndXFqbCe+lyTUf+cakauYvapyc1dOV0mj9prIuKr2ZSr/olTact38lWjVJCUiicbqJyWh2rVOwtw971xeh8UjdIlEBLvHdZhSIcGV3XLJZc+KB5cBonGw/OMuDv1OfvckbKPNOyWgn4kYchjVuz1PkKieXEMYedtnLQqUtXBnW7jwe1cvt4YDj8kyJy5jhNTPB17vHg7LSF8hWYFxI+DNxgn/fIhossj89GGdGyrNMWLrdRSRh6M8IUjf8A
Browser: chrome

Operating System: windpws10

![cesium](https://user-images.githubusercontent.com/5866132/68828650-5c0d3880-06e1-11ea-9c3a-98f777fa143c.png)
![three](https://user-images.githubusercontent.com/5866132/68828653-5f082900-06e1-11ea-8acb-4ce39ddb17a9.png)

**Comment by OmarShehata** [comment]
I'm closing because general questions like this should go on [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). 

It would also help to show a screenshot from the ThreeJS version showing what the effect you're trying to create is.
