### ISSUE TITLE
normalized result is  not a number

### ISSUE THREAD

**Issue by xianshangdeyu** [AnalyticalGraphicsInc/cesium#8399]
When i add  3dtile of a city, the 3D model includes the tilt photography model and the manual model。the error "normalized result is not a number" will appear when I load a large amount of data。This problem will not occur when only part of the data is displayed。

**Comment by xianshangdeyu** [comment]
![TIM图片20191115095437](https://user-images.githubusercontent.com/23569095/68910980-8cf77700-078e-11ea-8321-04cb6fc83998.jpg)

**Comment by OmarShehata** [comment]
Are you able to share a code example that reproduces this issue @xianshangdeyu ?

**Comment by xianshangdeyu** [comment]
I can't reproduce this  issue because our data can't be published on the Internet, but I have calculated that our total data is 30 square kilometers, including tilt photography data and manual model data, The data in osgb format is more than 100GB in total

**Comment by xianshangdeyu** [comment]
In the process of loading, I made some attempts. If only part of the data is loaded, this problem will not occur, but once all the data is loaded, this problem will occur. In the process of using cesium, it is found that after the model is loaded, the occupied memory keeps increasing. Even after the model is removed, the memory is still not released

**Comment by OmarShehata** [comment]
How large is the 3D Tileset you're loading into CesiumJS? How was the 3D Tileset produced? Does lowering the tileset's memory usage (see https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html#maximumMemoryUsage) prevent the crash?

**Comment by xianshangdeyu** [comment]
The size of the 3D tileset is 84.4 GB,The production of 3D tileset uses a program downloaded on the Internet。The maximummemoryusage parameter, which I try to set to 1024 or 2048, will not prevent the crash

**Comment by xianshangdeyu** [comment]
I guess it may not be the problem of data quantity, but the problem of manual model. If I try to load a manual model alone, this problem will also occur. What is the cause of this problem

**Comment by mramato** [comment]
Usually this problem is caused by bad data or a coding error at the application level, however in rare cases it is a Cesium bug.  It's such a generic error that it's not possible for us to debug it unless you can share an easily reproducible test case with us.

**Comment by xianshangdeyu** [comment]
Thank you. After I update cesium to the latest version, all models can be loaded
