### ISSUE TITLE
When I use particle system, the particle image is always displayed

### ISSUE THREAD

**Issue by Jonny0601** [AnalyticalGraphicsInc/cesium#8408]
when I use the particle system in my project like this 
![image](https://user-images.githubusercontent.com/18041735/69215074-a4c26700-0ba3-11ea-95e1-c27ed92fe58b.png)

the wind2.png will always display  in the current scene（The red arrow is the wind2.png）
![image](https://user-images.githubusercontent.com/18041735/69215542-fae3da00-0ba4-11ea-880a-826d8f747707.png)

I don't know how to fix this problem

**Comment by Crocsx** [comment]
Use the forum if you want help on how to use Cesium. 
Github should be used only for bug report or feature request...

Anyway, you have multiple way to hide your particles, and you would have found out if you read the [Documentation](https://cesium.com/docs/cesiumjs-ref-doc/ParticleSystem.html?classFilter=parti)

you can remove your particle system from the entity list 
```
var particleSystem = scene.primitives.add(new Cesium.ParticleSystem({
//...options
}));

 scene.primitives.remove(particleSystem);
```

you can just hide the particles using : 
```
particleSystem.show = false
```

**Comment by Crocsx** [comment]
I Think you are talking about this ?

**Comment by Jonny0601** [comment]
> 如果您需要有关如何使用铯的帮助，请使用论坛。
> Github应该仅用于错误报告或功能请求...
> 
> 无论如何，您有多种方法可以隐藏粒子，具体取决于要实现的目标。[文献资料](https://cesium.com/docs/cesiumjs-ref-doc/ParticleSystem.html?classFilter=parti)
> 
> 您可以从实体列表中删除粒子系统
> 
> ```
> var particleSystem = scene.primitives.add(new Cesium.ParticleSystem({
> //...options
> }));
> 
>  scene.primitives.remove(particleSystem);
> ```
> 
> 您可以使用以下方法隐藏粒子：
> 
> ```
> particleSystem.show = false
> ```



> I Think you are talking about this ?
> 
> #7511
> 
> It is a bug, and it has not been fix yet from what I see as it also appear in the [Sandcastle](https://sandcastle.cesium.com/?src=Particle%2520System.html) when zoom out



> 我认为您在谈论这个吗？
> 
> [＃7511](https://github.com/AnalyticalGraphicsInc/cesium/issues/7511)
> 
> 这是一个错误，根据我的观察，它尚未得到修复，因为缩小时它也出现在[沙堡中](https://sandcastle.cesium.com/?src=Particle%2520System.html)

yes！I am referring to the problem #7511，

**Comment by Jonny0601** [comment]
> I Think you are talking about this ?
> 
> #7511
> 
> It is a bug, and it has not been fix yet from what I see as it also appear in the [Sandcastle](https://sandcastle.cesium.com/?src=Particle%2520System.html) when zoom out



> I Think you are talking about this ?
> 
> #7511
> 
> It is a bug, and it has not been fix yet from what I see as it also appear in the [Sandcastle](https://sandcastle.cesium.com/?src=Particle%2520System.html) when zoom out

yes！I am referring to the problem #7511，

**Comment by OmarShehata** [comment]
Thanks for finding the relevant issue @Crocsx ! And thank you for confirming @Jonny0601. I'm going to close this as a duplicate and move the discussion into the above linked issue.
