### ISSUE TITLE
on the mobile phone，the label text spacing will increase

### ISSUE THREAD

**Issue by ElevenIjusee** [AnalyticalGraphicsInc/cesium#8409]
Sandcastle example: 

Browser:

Operating System:

**Comment by OmarShehata** [comment]
Are you referring to a similar effect as shown in this issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/7376 ?

If so, I'm closing this as a duplicate issue. If it isn't, please provide a Sandcastle example, which browser, and operating system you're testing on, and a screenshot of the issue.
