### ISSUE TITLE
Clamp to point cloud not working properly

### ISSUE THREAD

**Issue by cr8tpro** [AnalyticalGraphicsInc/cesium#8410]
![Screenshot at Nov 20 04-38-17](https://user-images.githubusercontent.com/46979515/69228474-a19e8b00-0b51-11ea-8d78-7cae0fc6952a.png)
I drew a line on point cloud and it works fine. I attached a screenshot.
As you can see at the screenshot clamping to point cloud is not working correctly. I used clampToGround property to draw line above point cloud.
To get all points of the polyline (blue line on screenshot), I calculated the length of line and divided line per 1 meter, so I could get all points between the start point and endpoint of the line.
And to calculate the height of each point, I used clampToHeight() function.
But there are holes(gaps) on the point cloud, so clamping to hole is clamping to CesiumGlobe.
But I want to draw a graph on chartView with same shape to line on point cloud.
Are there any features in Cesium to do it?

Or is there any way to get all points of line with height property?

Browser: Chrome
OS: Mac OS Catalina

Best

**Comment by OmarShehata** [comment]
For general questions like this, please use [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). I believe this clamping is a render process, so you will want to use [clampToHeightMostDetailed like in this code example](https://sandcastle.cesium.com/index.html?src=Sample%20Height%20from%203D%20Tiles.html) to make sure the highest level of detail is loaded, and you might also need to set the point attenuation to fill in any gaps.

**Comment by lilleyse** [comment]
In addition to using `clampToHeightMostDetailed` I recommend setting the `width` to create a larger sampling area. The default width is 0.1 meters, a larger value like 1.0 will make it less likely to go through a gap in the point cloud.

**Comment by cr8tpro** [comment]
Thanks for your help @lilleyse and @OmarShehata
