### ISSUE TITLE
 prevent the camera from going underground

### ISSUE THREAD

**Issue by Jonny0601** [AnalyticalGraphicsInc/cesium#8412]
Is there any way to prevent the camera from going underground?
I tried to do this：
![image](https://user-images.githubusercontent.com/18041735/69407910-a1b0ad80-0d40-11ea-99c2-c498c0cc913e.png)

But still can't completely prevent it。

Is there any better way?

**Comment by OmarShehata** [comment]
The camera already has collision detect to prevent it from going underground, which is enabled by default and can be toggled with:

https://cesium.com/docs/cesiumjs-ref-doc/ScreenSpaceCameraController.html?classFilter=screenspace#enableCollisionDetection

This is intentionally turned off while the terrain is still loading. You can read more about why this is and how to work around it in this issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/5837

**Comment by Jonny0601** [comment]
@OmarShehata I understand，  thank you!
