### ISSUE TITLE
SampleTerrainDetailed return an incorrect altitude 

### ISSUE THREAD

**Issue by popoleeMaster** [AnalyticalGraphicsInc/cesium#8414]
Hello,
I posted this issue on the forum, but even from the answer I got, I couldn't fix it cause it looks like an issue in cesium or in the documentation at least. 

PREREQUISITE : 

I am using cesium to making some drone fly:

-> My Backend require MSL altitude.
-> Cesium use WSG84 altitude.

I found on internet that converting WGS84 to MSL require GEOID **.

*: [source](https://cesium.com/blog/2015/10/26/cloudahoy-migration-to-cesium/)
*: [source](https://support.pix4d.com/hc/en-us/articles/202559869-Orthometric-vs-ellipsoidal-height)

I use my backend to do so, using a package to retrieve GEOID (EGM2008) I calculate the MSL using the WGS64 from cesium and the geoid from the package. 

In My app I use Cesium World Terrain `terrainProvider : Cesium.createWorldTerrain()`
On this terrain I use sampleTerrainMostDetailed to get the height of a point on the ground and return it.

`As is typical of the Cartographic type, the supplied height is a height above the reference ellipsoid (such as Ellipsoid.WGS84) `

So this altitude I get should be similar to what I get from a GPS* :

*: [source ](https://gis.stackexchange.com/questions/157005/meaning-of-elevation-above-surface-of-ellipsoid)

So from all the research I did, I have a lot of sources that say 

`MSL = WGS84 - GEOID`
which in my case would be 
`MSL = Cesium sampleTerrainMostDetailed wgs84 altitude - my package geoid altitude`

PROBLEM :

The problem I face is the following. I use external website to test this approach.
[to get GPS altitude](https://www.daftlogic.com/sandbox-google-maps-find-altitude.htm)
[to get geoid and MSL](https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height)

I use this code To get the elevation of the terrain at my point :
```
var terrainProvider = new Cesium.createWorldTerrain();


var promise = Cesium.sampleTerrainMostDetailed(terrainProvider, [new Cesium.Cartographic.fromDegrees(139.6072415, 35.7139224, 0)]);
Cesium.when(promise, (updatedPositions) => {
  console.log(updatedPositions)
});
```

Well, the height I get from sampleTerrainMostDetailed is not the same height i get from GPS, the height I get in cesium looks like to be the sum of (GPS + GEOID) already.

Using `Cesium` and `sampleTerrainMostDetailed`, I need to do the following 
`WSG84 - 2(Geoid) = MSL` 
for some reason, or it will not work.

For exemple at this point, where I know on the ground the MSL is 12meters :

If I do the normal procedure : ex [sandcastle](https://sandcastle.cesium.com/#c=tVRLi9swEP4rQy6RwSib7G6XkgeF7NLLli506YO6B8WaOKKyZCTZYVvy3zuOH3Gyh9JDfZJG8z3mgSvhoFK4RwdLMLiHNXpV5vzzMcbG6fG6tiYIZdCNo3liElMRKqBzFHtytlLyEp46FAG/WKflc5PHGmSDLZzNlUfCtPle5IXGNvWD9eEeSVCjZBcyMXwfyKyFCzZzotiplG+J9B4zh+jZ9Potf3N1N7uZ3sZwfcvvKDCb3cRwFf2ojbT4/Q4Na83EwMpCkmv5ZL0KyhofwXIFvxMDkNLNauTaZq+zEnPoizu2jaeCyvRcSPlQoQmPygc0x3Zqlf4cx7AtTVqDGUZHfoC6LbktPXa85w2tK6WTMDOGnFiI9WsM3fFbo9/xoNaq8FZJ4mgd+ZQM8EzbDfL+eX6CpB3/CZKKHJ3gBTl+6BDszGJ8UopaLrUF1nNF0BY3VOnmRUI9mveQZzuc6YBqfs70PzaIDe3RqE2mQilpMc7jIrThdpc6W/+6U933l93q0g6d1oH6RpUPOIRGF9j4fT1d2AsPxgao54Zy3KNoQQJtKu2eIHg0H8WjhQ8vGldNwjuVF9YFKJ1mnE8CUj/Ji59sSiIKPPW+5lpMOtBCqgqUXCaji59EMoJUC+/pZVtq/Un9wmS0Wkwo/wymrZDKZB8rdFq81Cm76eqxCXLOFxO6vkYFa/VGuAHjHw)

POINT => {longitude: 139.6072415,latitude: 35.7139224, height: 0}
MEASURE => SampleTerrainMostDetailed (with createWorldTerrain) => 86.8920731655 meter above the ellipsoid
CALCULATE => 87.39579997978265 - 37.29716 = 50.0986399798meters

But doing 2 times :
POINT => {longitude: 139.6072415,latitude: 35.7139224, height: 0}
MEASURE => SampleTerrainMostDetailed (with createWorldTerrain) => 86.8920731655 meter above the ellipsoid
CALCULATE => 86.8920731655 - 2*(37.29716) = 12.8014799798meters

It looks perfect with 2 times geoid.
And I tried this all around the world, 2 times works, one time is wrong.

So to me, it looks like there is a problem within Cesium somewhere in the altitude OR the documentation is incorrect/incomplete, and it should state that the altitude returned is a WGS altitude based on the ground + the GEOID

p.s : [Forum post](https://groups.google.com/forum/#!topic/cesium-dev/bnyGsqTKLLY)

**Comment by OmarShehata** [comment]
@popoleeMaster so to summarize the issue here, you're able to correctly convert the height returned from CesiumJS into Mean Sea Level by doing:

```
MSL = HeightFromCesium - EarthGravityModel2008 * 2
```

Whereas you'd expect it to work correctly without the need to multiply by 2, right?

**Comment by popoleeMaster** [comment]
Exactly, 

Since Cesium should return aWGS84 altitude  based on the surface of the ellipsoid, this altitude should be exactly like the GPS.

and it should not require a EarthGravityModel2008 * 2.

**Comment by GatorScott** [comment]
How do you know the MSL height at (139.6072415, 35.7139224) is 12 meters?

Google Earth inspection using cursor says 48.4632 meters MSL.
Cesium says 87.4751 meters WGS84 (or 50.2042) meters after conversion to MSL using EGM96 orthometric height of 37.2709 meters.  

Disagreement between Google Earth and Cesium World terrain values are expected given likely differences between source data and processing techniques.

**Comment by popoleeMaster** [comment]
sorry not 12 meters, but 35 (I was subtracting the height of my point that was 20 meters) I will edit. And the value come from measure I did on the spot

**Comment by OmarShehata** [comment]
Closing because it sounds like the issue here is not with CesiumJS. Feel free to continue any discussion in [the forum thread here](https://groups.google.com/forum/#!topic/cesium-dev/bnyGsqTKLLY).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/bnyGsqTKLLY

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8414 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
