### ISSUE TITLE
Polyline zOrdering problem

### ISSUE THREAD

**Issue by safa833** [AnalyticalGraphicsInc/cesium#8422]
In order to show a primitive above other primitives, that primitive needs to add above others in viewer.scene.primitives. Therefore I pass index number to primitives.add(xxxxx, index).
But Polyline don't comply with this rule.

[The Example in Sandcastle](https://sandcastle.cesium.com/#c=xVZtb9MwEP4rVr80lYLbvWkQuomSZWjSxqZ2TEgUITe5bhZOHNlOR5j637HTOnFaBgOkkQ+Vfefn3p47uwghtCACLSjcg0BHKIN7FIKkRYpvKpnXjattyDNFaAai66OHaYaqT8aQwQVPILCgiZXgSRi9j3ZPVkeXvdfTbLU07gQkIRUxg3fAU1CibHtu67zanbatQNS+QiKUXpFsD88FT0/gVgBI78XLAzzw0f4AH/R8CxUkoYUMtFR/Wm3lC9A2vp1ykRJVG74CcZZJRbIYQs64GOU5EGG2+CYaX0cfv5xeji9G17/OzZpo52azstomu9u1JtguTx0uUUrQWaHTDhoWdGFMlE1dzG7Tz8giq1pVRzz3PB5HJz1rcVk7pEmAulqFwrNxeB51Wyk3Sc9YAc/B6OB/MNok9/eUbhfoOTh9e/4heoxUo/spq04jXwmaUkUXGwnX4u1MbWgy2B6EJuO6+kHL7KMkeQ9I6YVkhWkYFKA5YRJ0wI/y9U+RbxP+XKHnnJVM37JyI+y1WNtmECvKM8/gDKpGYJIkTVY5l9Sck7+ZrZEQpPQ+NW3n3J6+K93H+z7aO8SvrPBzM4r3NFF3AdqtBXr0QFDCWjW6WAs9p8md0qwr4zidk5mgcWsoNKLMdem7VZW7vqspMjrXUy83APUkuddRNSo7JtHqZ7Be9VzgstnUyxZtFWnVI4mrhxDntrtWZLT68CkAd+J0UE+B1PTr+J1WWiFikoIgeM7Ka95UPQGpaEZMd/zBU+qjA3PROhdwUoi1kUFdlI7fGUpVMjheid7QNOdCoUIwD+O+gjRnug1kf1bEX0HhWEoT9bBvQcOELvT9dDTtbPztmHZQzIiUWjMvGJvQ7zDtHA/7+nwLxrh+F7LbS/0MMFKaI3c7x+crIcZ42NfbbZTinM2IcCz+AA)

![Polyline zOrdering Problem](https://user-images.githubusercontent.com/10292075/69781924-a7831480-11c0-11ea-8c23-a61c67ef0365.PNG)
```
    var viewer = new Cesium.Viewer('cesiumContainer', {
      sceneMode: Cesium.SceneMode.SCENE2D
    });

    var redCircleGeometry = new Cesium.CircleGeometry({
      center: Cesium.Cartesian3.fromDegrees(-85.0, 40.5),
      radius: 40000.0,
      vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT
    });

    var redCircleInstance = new Cesium.GeometryInstance({
      geometry: redCircleGeometry,
      attributes: {
        color: Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.RED)
      },
      id: 'RED CIRCLE'
    });


    var blueCircleGeometry = new Cesium.CircleGeometry({
      center: Cesium.Cartesian3.fromDegrees(-85.0, 40.0),
      radius: 40000.0,
      vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT
    });

    var blueCircleInstance = new Cesium.GeometryInstance({
      geometry: blueCircleGeometry,
      attributes: {
        color: Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.BLUE)
      },
      id: 'BLUE CIRCLE'
    });

    var redPrimitive = new Cesium.Primitive({
      geometryInstances: redCircleInstance,
      appearance: new Cesium.PerInstanceColorAppearance({ translucent : false })
    });

    var bluePrimitive = new Cesium.Primitive({
      geometryInstances: blueCircleInstance,
      appearance: new Cesium.PerInstanceColorAppearance({ translucent : false })
    });

    var polylines = new Cesium.PolylineCollection();
    polylines.add({
      positions: Cesium.Cartesian3.fromDegreesArray([
        -85.0, 40.5,
        -84.4, 37.9
      ]),
      width: 2,
      material: new Cesium.Material({
        translucent: false,
        fabric: {
          type: 'Color',
          uniforms: {
            color: new Cesium.Color(1.0, 1.0, 0.0, 1.0)
          }
        }
      })
    });
    viewer.scene.primitives.add(bluePrimitive);
    viewer.scene.primitives.add(redPrimitive, 0);
    viewer.scene.primitives.add(polylines, 1);
```

**Comment by OmarShehata** [comment]
I think this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/8302 since it only happens in 2D.
