### ISSUE TITLE
load 3dtiles the scene appear blink 

### ISSUE THREAD

**Issue by VINOlive** [AnalyticalGraphicsInc/cesium#8437]
when load 3dtiles the scene appear blink .
Is the computer setting problem and how to config?
The specific situation see the red box in screenshot.

any help thank you!

[offical url](https://sandcastle.cesium.com/?src=3D%20Tiles%20Feature%20Styling.html&label=3D%20Tiles)

![blink](https://user-images.githubusercontent.com/7323049/70213073-792ea780-1773-11ea-8ce9-edd5c350497d.png)

Cesium Version 1.64.

**Comment by OmarShehata** [comment]
This is a known issue, see https://github.com/AnalyticalGraphicsInc/cesium/issues/7189 for a discussion of the cause and a workaround.

**Comment by VINOlive** [comment]
> This is a known issue, see #7189 for a discussion of the cause and a workaround.

thank you, my problem solved.
