### ISSUE TITLE
perPositionHeight and material conflict in Entity.polygon

### ISSUE THREAD

**Issue by zhangwang9li** [AnalyticalGraphicsInc/cesium#8447]
Sandcastle example: 
Material cannot set transparency when positionheight = true
Run the following code in cesium 1.6.4：
var orangePolygon = viewer.entities.add({
    name : 'Orange polygon with per-position heights and outline',
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArrayHeights([-108.0, 25.0, 100000,
                                                               -100.0, 25.0, 100000,
                                                               -100.0, 30.0, 100000,
                                                               -108.0, 30.0, 300000]),
        perPositionHeight : true,
        material : Cesium.Color.ORANGE.withAlpha(0.5),
        outline : true,
        outlineColor : Cesium.Color.BLACK
    }
});

Browser: Google Chrome v 77.0.3865.90

Operating System: windows10

**Comment by OmarShehata** [comment]
@zhangwang9li do you mean CesiumJS 1.64? I'm not able to reproduce this, see [this Sandcastle](https://sandcastle.cesium.com/index.html#c=jVLdS8MwEP9XQl/WwUw7hyBah3OKguJEwRfrw9mebTBNyiXtqOL/bvohVkXwHkLy+8pdSA3EaoFbJHbEFG7ZGo2oCn7fYf4k6Y5rrSwIhTSZHsYqVrVzaQKV4Y2WTaaVM/cpHJUVVqDhkKb+W6yYKwUFsgM22XQWVg6erbA5K5F2Sm2cxyE5iiy3hoFKma6sdFdOZn3Gp+mADaFt5QIJKMkbBw+Nr4Gs24Fa8GfSxSlmhGhWRNBc9On+w8483OfhjO3utes8bGv2lero8B/0IvyL3v+iFx39OB0J3MQ3w8B9R655SxWOJAVYJAFyNJaWmvjmdnV9fsbbh1vJMgc/5Hvj6OHNfgcORJfyM/TkarW+7KXvsXqfHnozLzK2kbjs0WNRlJosq0j6nAcWi1K6Bk3wVCUvaHliTPstouDTFKWiZiI9ir0f3yf2WCLBGMc8V1LeiVeMvWUUOP03m9SQCpVtaiQJTSvJ58urHuScR4E7/nZZreUT0CjxAw).
