### ISSUE TITLE
model cannot display in 2D mode

### ISSUE THREAD

**Issue by Rokkregin** [AnalyticalGraphicsInc/cesium#8457]
The model of an entity with position of large height (above about 7600000) can't display, polyline and polygon have the same    problem.is this a bug?or we can heighten the height by changing some parameters?

**Comment by OmarShehata** [comment]
@Rokkregin can you please submit a full code example that reproduces the issue? You can create the example in [Sandcastle](https://sandcastle.cesium.com/index.html?) and click "share" and paste the link you get here.
