### ISSUE TITLE
How can I change the width of a groundPolylinePrimitive

### ISSUE THREAD

**Issue by LyjPeppers** [AnalyticalGraphicsInc/cesium#8462]
I have tried the method as below,but it does work! Please help me, thanks a million!
`const attributes = groundPolylinePrimitive.getGeometryInstanceAttributes(mid);
 const width = new Uint8Array(1);
 width[0] = style.width;
 attributes.width = width;
 attributes.color = Cesium.ColorGeometryInstanceAttribute.toValue(
   Cesium.Color.RED, attributes.color);`
Just as codes above, the method 'getGeometryInstanceAttributes' from class GroundPolylinePrimitive does work for setting color or   width.

**Comment by OmarShehata** [comment]
Please use the [Cesium forum]() for general questions like this. You can usually find the answer there (in this case, here's a forum thread [explaining what I think the issue you're seeing here is](https://groups.google.com/d/msg/cesium-dev/nX3bbKeoosc/9Jf06czSBAAJ)), and if not you can always open a new forum thread with your question.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/nX3bbKeoosc/9Jf06czSBAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8462 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
