### ISSUE TITLE
Point entity with disableDepthTestDistance set to infinity breaks zooming in with scroll

### ISSUE THREAD

**Issue by ttimmy** [AnalyticalGraphicsInc/cesium#8476]
See sandcastle example, try to zoom in and out on the point entities with scroll. Sometimes you need to play around with the map to get the bug. Here is a link to a video reproducing this bug, it will make it easier to understand (make sure to view at high quality): https://youtu.be/SM22fr207h8

Sandcastle example: 

[Link](https://sandcastle.cesium.com/#c=lZlrixvJFYb/ivCXHYMp1+VUnSqvbQK2A4bgDVmzEDIhyDPaWESWhpHGm03Y/57naNRd8uZLaWBAanWfrj6X91L9dXm/+Lpe/bK6X7xabFe/LN6s9uuHL+6n47Gr726OX9/stofleru6/+7p99fb6+1mdVistof1Yb3ac93f/n48erPb7g+Lu916ezgevd4uTn9ngd8s7w98Wm7TlUjyOUSXom+t+ZyeLZJvsUp16nNLOUrhUFKtKi5LTDGGpk+fjQXOLkSvPoYSToFzcTW1EFMj4ily4bSSq9dYaxkMncRxsno+6Sl0FRcDqybgvOgizhfu6qtPo6FDdSnVpMSKecpHcFI0+1bitGoNLtcaQrH/wdA+ulp88zHVOSE8fBJumpqcItfoQuA3qfGCRIeSJKVcpyXn5iRQW1YdpsgluZxbqzXz+2DsmJwluqQU2ym0VhdVVEop7RTZ6hq4UwxUZDQyTVZryon4vYYlR5/Jbp7WHKh0i9QgyuiafXZVUpBKx54iE4aa5drI0JQO5dEk1FBaLDIaurkiPhdhXk6hGyssNYmXGKZ0RFd88pw0mmdp6oRU0FLH9R3zLE5T81KTr9OSs1PhA7fSMl7BQkOF4nVqjupdklgyNegFJPPUg+EZTYV3hTbLLcy4UbMrzEgN1cfec9UAgJuH0QV7V2kBiW0ebrLjWW+IJU6NkYprzBFQEHU0x41eYjVcd1pxC975lLyGoiWdIkt0LfoQJJU6inVRXFBGtsZ5TIRpK0J3Jzq3Z4PRroHIYXROfOUakE5CkQ6jielmzbV1fFZahbbU0V4OzeVGzT2rnAKDanRXSQTSvmamRA2r2mBk8U5bMxDT2ps5Z5ucEqfW4P7cp2bIII6OdoogcWupBD2b7Ax8Gq9MFUwMEwejaJLhCkYe3avmWKYKMsagtbfZDlM2wNUkrXDAp3HMUMP1UGWOXJnJFAyeQycU1kvXM5XDEKqOygQ+t7M8h8gMxlxn3E+gRuHhCtHH+1mpjfiejVYNLgH+eVCgSpMESWH00aZLPCa9FDSFnM9hv3HPOGNzDI6u0JQb/6Ohs2tCcdo0Js07GgZs5rmn+qF2AgkGR9rwkm3aMsgYci8fnZxbSa3VnuTA4BQ63Ot4/aRYE0SdUYNcwEjcsEwqhrvFzMEMiOsFoFGhNdBR+qAwFKGhNUR605UCvSC+hkFUHAAWm9TW2QTdVTiqsfMU6UdRIpiGA8NT8LzNy8TaLTqAmHL5eUwKoIUeQYXmUQQVOhcIRgn5Wk64D3kJKa5eZKZAOCYx1TaXw0oDvGxZMgwXp8jqeHDNWbvEhQq8h3Sy1OHeCMUZ41EdlSk0JB1QS0y2zoPCoAYQlOkeDg2IKvqW9eikQyspSnR483VedVAIHjlSWxmNLCBNqxFeylMNU3Ix2ixGX3NnWL7gOSSMDmFE01VbdS4TWTGXiK+EwtfSvUTWYpgRhnVMCCBCs0zOnCLNkQnjgiS9o2ukW1SGTQqlQSeGYHXvjFLQ9QYdLXfpFTygAdTGCyqIGfFVi58VbmIuUb2+zVyVTAcrPg4pM451cpTfPk7JUEDKBMvccsHGiX6LSFwd13T0McorTdVD/mfhEXzOfjaZmBZajtuNj4m6BFSSiLnjstkcOoPpPveYiBhcjJfx0UbBHKFmCqzeEDRioGiRbiKSh3Ap6qiJMAhFtyKnyMI0f8W0GJDUwqzokDoB5UE719HAAe/KCDNcpbP2EeZ6vxVYW1uGTcRf4Fyxe3hHhMwERvQbtpCazV5NCjAHJ+JYhhVMObptBN1sTtD6eM1kJQ0diSDEZmp6ODLqsoGMwLmfIhsrNYYRLTQvOR+5izRnHc8FU4bbzjo3BlhNPpmzVnqWUdOsoA1vD4D4gsJifcSeMM68tpk9NO/UF+qwMJB4HFYw0cQ3tJYeo0zaVslxQyjKGQMC3yIUV8f1nCEcH9OsB/RI5Og3HFTXc/SbZPN1474VRqJvvcyszaJTQC/mGZdpjZBsWNq4HldXMWGis1drRx5XTAUj1DlKGmQDbQ3PtXcNWR9RtqHnwlSHMZJ2JgG1I30Zy/jmABNtQk21Y1Gz6StUa2pm25jBT4UwnotgmzDWA2GmVTWBB2QAfDNFBbMrDCpAcsH8RewdXR1nLEIGBZQK4mh2lxCOYaFhvuZxLQB/QthyrhThGC3waOstV9D9ntSXcfaLhu+M8pSNgofQ1CK0OpsTJA24og38HIVms5eCVUJa1MmqyVEkQ4Hd9hQxnkopoobLeDZsrwSikDNFnuhm/La0sx0e4SFaDP4CRd7U23ZD6xs8dDcUg2ApZwxoNgtILDpOVI3F0HSTcbURDDGZ9YnSWdsjgeVoZ8e1foK3ad8+3HQioqhKraEzlW0ee9t6vaCh1cCI0Zt2j7w4S3sE6tJkfVA6OAIBp9o4iIrNStHgZwnasjMmtw30GevM1NEZqLnhKRR1Sq8aLExTWOjE6o+SXM7g2dv+QOM5Rqcwm0BCkSPBSn9vYA1tnTjNd8SvaUNuGDBesH101K1p0s3JjlBI2y+eQcm7YlteokEuYKtiBq/1KcSDW21Vz/ac6XLkbQQ92jiOelPxatTaNwBxrxICWJ+64YbeQQPGapSuBL1WWGjqG1NqeQbX0tx2YD/KxIdx6masYNOCd406b8WobT9ghDJoKj00eIg5BHOHLTciKdOxMP68G2PYVo/bzv2NRHMMuCIk/fBWK0CB1qY+2Yc+h3SXmeA0W27TMkgbxucC9Ffa3wByxjsMCY+O9NRZf5mXAKmOW73jdg22Mid9pgvAYoOJotpfdVh2qm1NyQU7gNl2sOd3VXgozXZMk57tIGECeRAk4LBjszcmyE7bn+r6GXGP2tPZWGX6BVYAt1O4QHIABqbCz3R5zOaAU56WDJQgpNB1zKqMm4mc7Lkf32uczCsgii4AJVK3xdwdn2nE+3SK/PgG9fHz4xtU9/Pu/t3y5vPV3eLV68V/+xKmF6/u7mH/+erx5a2bDy5vb6/OTrZoe37ZbV8s7p59e5y7vFh8cy5H1/9ebX5c/2f1YpGfffvTzW6zu38xP719c3959/Z3Z92u98tPm9Xb1d3h88fV/vB2vT8stzfE+/Dw5RMr/fMPP77/+P6nd/94/+GP7z+8//jX8+t/619+e2rvmqfP3z959uTl/vDrZvX68eAf1l/udveHxcP95sq554fVl7vNkno8//Rw86/Vwd3s93b9y+fTRS9v118X69tX109+9077+sniZrPc7/nl54fN8eGvn7x++Zzzv7lss1verrf//OHr6n6z/NVO+Rxe/+nxoHPu5XO+/v9Vh91u82l5fxbxfw)

Browser:

Chrome latest

Operating System:

Mac OS Mojave

**Comment by OmarShehata** [comment]
Thanks for reporting this and for the Sandcastle and video @ttimmy. I believe this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/6840. There's some more discussion and potential workarounds there.
