### ISSUE TITLE
EllipsoidGraphics' outline width doesn't work

### ISSUE THREAD

**Issue by bbbbx** [AnalyticalGraphicsInc/cesium#8485]
Sandcastle example: [Here](https://sandcastle.cesium.com/index.html#c=7VNdT4MwFP0rDS+yZBaGPk22qNMHk5kZv/ZCsnRwN24sLWkLcxr/uwU290F889H7QHrPPee0PUDJFCkRVqDIgAhYkRFoLDL6WmPuSVy3IykMQwHqpHMRiUiUViULwy00xcSkVhv4F208sINeo6j9KAiDBkFTliTuZySIrVxqi0nR3+49YsrYFRNndKFkdgNLBaDd017gU79Lzu2z0220wDnmWmJC+mRjV5ViCaKF9i60M3UDv6rKqr3aGleVsXfM6ssD+TncPTMpfbibTV5vH2fP08kB34BCxnfkkeRS0evxyy1doUmveJ4y16dn+7ts8rIiowpoD5qA+wdtQ/qKxFfn79Lt/ae7+Wp/ifdDyuxZukdhVxSn64TarDkMG+klZrlUhhSKu5R6BrKc2+Nrb17Eb2BorGtZ6G1FYYIlwWQQOUc/XOSQmDOt7WRRcP6EHxA5w9Cz/AMZl/aliOWkBMXZuqKkveG4ASmloWfbtspIyedM7Tl+Aw) is the example, one entity's width is 20, and the others is 1, but they look like same, preview:

<img width="990" alt="Screen Shot 2019-12-20 at 20 30 41" src="https://user-images.githubusercontent.com/22176164/71254988-a0869680-2367-11ea-9940-bbeb8b59cbfa.png">

I paste the code on below for convenience:

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var outlineWidth = 20;
var outlineWidth2 = 1;

viewer.entities.add({
    position: Cesium.Cartesian3.fromDegrees(-120.0, 40.0),
    ellipsoid : {
        radii : new Cesium.Cartesian3(200000.0, 200000.0, 200000.0),
        maximumCone : Cesium.Math.PI_OVER_TWO,
        material : Cesium.Color.BLUE.withAlpha(0.3),
        outline : true,
        outlineWidth : outlineWidth
    }
});

viewer.entities.add({
    position: Cesium.Cartesian3.fromDegrees(-110.0, 40.0),
    ellipsoid : {
        radii : new Cesium.Cartesian3(200000.0, 200000.0, 200000.0),
        maximumCone : Cesium.Math.PI_OVER_TWO,
        material : Cesium.Color.BLUE.withAlpha(0.3),
        outline : true,
        outlineWidth : outlineWidth2
    }
});

viewer.zoomTo(viewer.entities);
```

Did I forget something?

Browser: Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)

Operating System: macOS 10.15

**Comment by OmarShehata** [comment]
This is a Windows issue, see https://github.com/AnalyticalGraphicsInc/cesium/issues/4223#issuecomment-241462146.

This will be fixed when we switch to using polylines for all lines in the engine, see https://github.com/AnalyticalGraphicsInc/cesium/issues/8319.
