### ISSUE TITLE
Point cloud bounding sphere gets cloned every frame

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#8486]
The `boundingSphere` setter in `PointCloud.js` always clones the bounding sphere into a new object.

https://github.com/AnalyticalGraphicsInc/cesium/blob/db26f0c79f42de0c97a22444bb6eec69f5d15c0d/Source/Scene/PointCloud.js#L192-L194

The second argument should be `this._boundingSphere` so it clones into the existing bounding sphere.

Good beginner issue for @Samulus

**Comment by Samulus** [comment]
Fixed, branch: https://github.com/AnalyticalGraphicsInc/cesium/tree/bugfix/bounding_sphere_clone
