### ISSUE TITLE
PrimitiveCollection remove function example code is wrong

### ISSUE THREAD

**Issue by craigp1231** [AnalyticalGraphicsInc/cesium#8496]
[https://cesium.com/docs/cesiumjs-ref-doc/PrimitiveCollection.html#remove](url)

The example given in the documentation for the remove function for PrimitiveCollection states

`var billboards = scene.primitives.add(new Cesium.BillboardCollection());
scene.primitives.remove(p);  // Returns true`

**p is not defined**. The code should be the following

`var billboards = scene.primitives.add(new Cesium.BillboardCollection());
scene.primitives.remove(billboards);  // Returns true`

**Comment by lilleyse** [comment]
Thanks for catching this @craigp1231. This may be a good starter issue for @sanjeetsuhag.
