### ISSUE TITLE
How can i avoid a white-content fill when adding a groundPrimitive with image material?

### ISSUE THREAD

**Issue by LyjPeppers** [AnalyticalGraphicsInc/cesium#8506]
I want to add dozens of groundPrimitives filled in image material which will be gonging to update in the coming renders. However, I found that the groundPrimitive was filled with a white color content before its image material being ready! 
          How can I avoid this? Can you give me some suggestions, I will be very grateful!
![sample_png](https://user-images.githubusercontent.com/20767375/71789953-e4b4af00-3068-11ea-8bb5-c5fae2046b38.png)
         My code is just like as follow:
          `primitive.add(new Cesium.GroundPrimitive({
                          geometryInstances: new Cesium.GeometryInstance({
                            geometry : new Cesium.RectangleGeometry({
                              rectangle : tileReactangle
                            })
                          }),
                          appearance: new Cesium.PolylineMaterialAppearance({
                            translucent: false,
                            closed: true,
                            material: new Cesium.Material({
                              fabric: {
                                type: 'Image',
                                uniforms: {
                                  image: imagePath,
                                  repeat: new Cesium.Cartesian2(1, 1)
                                }
                              }
                            })
                          }),
                          asynchronous: false,
                        }));`
 The 'primitive' of codes above is a PrimitiveCollection existed.

**Comment by OmarShehata** [comment]
For general questions like this please use the Cesium forum. You can find a similar question [asked here](https://groups.google.com/d/msg/cesium-dev/37cVssOUWtc/3D-X10TkAgAJ).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/37cVssOUWtc/3D-X10TkAgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8506 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
