### ISSUE TITLE
How to draw water flow direction？

### ISSUE THREAD

**Issue by hanyingling** [AnalyticalGraphicsInc/cesium#8520]
How to draw water flow direction？

![捕获](https://user-images.githubusercontent.com/33933148/72047924-9288bd80-32f6-11ea-9f57-e24d47be51f1.PNG)

**Comment by GatorScott** [comment]
Please ask questions like this on the [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev).  This list is exclusively for bugs and features.

You could do this:
`var viewer = new Cesium.Viewer('cesiumContainer');

var line = viewer.entities.add({
    name : 'Purple straight arrow at height',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights([
            -76.073545, 39.475197, 0.0,
            -76.325561, 39.130333, 0.0,
            -76.431673, 38.772206, 0.0,
            -76.385249, 38.487031, 0.0,
            -76.272505, 38.148799, 0.0,
            -76.192921, 37.883520, 0.0,
            -76.133233, 37.611609, 0.0,
            -76.126601, 37.352961, 0.0,
            -76.133233, 37.114210, 0.0,
            -75.867954, 36.941778, 0.0
        ]),
        width : 10,
        arcType : Cesium.ArcType.NONE,
        material : new Cesium.PolylineArrowMaterialProperty(Cesium.Color.PURPLE)
    }
});

viewer.zoomTo(line);
`
Resulting in:
![image](https://user-images.githubusercontent.com/4126790/72068211-87ac3980-32b2-11ea-9ae5-e1b357d01035.png)
