### ISSUE TITLE
PolylineGeometryUpdater crash when deleting and re-creating an object position

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#8521]
[Sandcastle example](https://sandcastle.cesium.com/index.html#c=vVRNj5swEP0rFj2ESNRAqlwSNqqaPVbqIVUvIQfHTLJujY1sk212xX+vjWGBRt1LVwsSYvze83x4xhei0IXBIyh0hwQ8oi1oVpf4R7sWzmhrbqUwhAlQs/k6F+69WB19KrlV7Z9zgeyTB6zIA7SyP4WkdQnC5EHUYxdQmknREVKc5EEumgjdiuXxJ1CTjrSV1Mz04k7gEUqUkWdFqgdG7+GsAHRL2n9M0wQnEVq23+TgRc1oS+bCs9s5g/0GvmNP4BYWCWpejWzxv5Elywh9Wr5ZVNwezCQkfvVLf4fUB6tbDwPiUQUnUCAotPB+CntKdzIfhqyjf9MWI9qUdRjMpquATe2w7jIYddfipr1Wr/fH6tk2H3AwrmhG1eBq++5d1mXj8yiIITtZKwrTCdva/O5fsNAN1kDFXJIidCXwA+dHFA8EjUlRhIPtaTsiCkq04eDg71LyI1FfamOkCGcGtJlF6FQL6tIM5y5JH/HIcaWk3V23vhfzdX8ijXcQREGmzZXDxgs/s7KSyqBa8RDj2EBZcWIdxcea/gKDqdZOmMW9KCvYBbHizhZ1erPYglJOtLbIqeZd32+y2PInMlcYJs7f7H3CydVRHtLNV7+IMc5ia96qjC/FaMc/)

(load then click the Test button)

This example creates a polyline via CZML, then processes a second document which deletes one of the endpoint positions, then immediately recreates it.

This crashes:
```
Sandcastle-client.js:20 TypeError: Cannot read property 'getValueInReferenceFrame' of undefined
    at ReferenceProperty.getValueInReferenceFrame (Cesium.js:128476)
    at PositionPropertyArray.getValueInReferenceFrame (Cesium.js:128013)
    at PositionPropertyArray.getValue (Cesium.js:127979)
    at PolylineGeometryUpdater._onEntityPropertyChanged (Cesium.js:155733)
    at Event.raiseEvent (Cesium.js:12972)
    at Entity.<anonymous> (Cesium.js:80710)
    at Event.raiseEvent (Cesium.js:12972)
    at PolylineGraphics.<anonymous> (Cesium.js:80710)
    at Event.raiseEvent (Cesium.js:12972)
    at PositionPropertyArray._raiseDefinitionChanged (Cesium.js:128063)
```

This is because `PolylineGeometryUpdater.prototype._onEntityPropertyChanged` responds to the property being deleted by immediately trying to get the value, and `ReferenceProperty` crashes when it is asked to get the value.

@mramato do you remember why we made `ReferenceProperty` crash rather than return undefined?  It's been so long that I don't know if there was a reason or not.

**Comment by mramato** [comment]
The only explanation I have is very early on, we assumed properties were never undefined and that we wanted to "fail fast" instead of letting bad/unexpected data in.  Obviously that's changed quite a bit (For the better).
