### ISSUE TITLE
Cesium can support any Coordinate System map  to show, not need to transform Coordinate System

### ISSUE THREAD

**Issue by small-lady** [AnalyticalGraphicsInc/cesium#8522]
I recently tried using cesium, and cesium only support EPSG:3857 and EPSG:4326; 
These problems i encountered
the first： a mistake occurred in "ArcGisMapServerImageryProvider": Tile spatial reference WKID 4490 is not supported.
second： error message An error occurred in "m": Failed to obtain image tile X: 1 Y: 0 Level: 0.
Following is my use case ：
the first : My use scene requires cesium to support superimposing a variety of different coordinate systems
-----------------------------------------------------------------------------------------------
 const acg4 = new Cesium.ArcGisMapServerImageryProvider({
      url:
        "http://61.175.211.102/arcgis/rest/services/wzmap/map/MapServer",
    });  // Spatial Reference: 4490

error message
a mistake occurred in "ArcGisMapServerImageryProvider": Tile spatial reference WKID 4490 is not supported.

------------------------------------------------------------------------------------------------------
    const acg3 = new Cesium.WebMapTileServiceImageryProvider({
      url: 'http://61.175.211.102/arcgis/rest/services/wzmap/map/MapServer/WMTS?',
      layer: 'wzmap_map',
      style: 'default',
      tileMatrixSetID: 'default028mm',
      format: 'image/png',
    }); // Spatial Reference: 4490;

error message An error occurred in "m": Failed to obtain image tile X: 1 Y: 0 Level: 0.

second：I have a map with a coordinate system of 4326, but it is not global but just a local area，error message An error occurred in "m": Failed to obtain image tile X: 1 Y: 0 Level: 0. i hope load map tile X: 1 Y: 0 Level: 0 can support user to setting not load from X: 1 Y: 0 Level: 0;

The above are my needs. I hope cesium can see and consider it. thank you very much

**Comment by OmarShehata** [comment]
Thanks for detailing your feature request here @small-lady ! We do have a feature request open for this here: https://github.com/AnalyticalGraphicsInc/cesium/issues/3877, which I will bump with your request.

In the meantime, I would recommend reprojecting your imagery before loading it into CesiumJS. One way you can do this is by uploading your source GeoTIFFs to [Cesium ion](https://cesium.com/ion) and they will be automatically reprojected.

**Comment by GatorScott** [comment]
Alternatively, you could try to configure that server to also provide the tiles in a Cesium compatible CRS.  Unfortunately, those compatible CRSs don't seem to be listed in the documentation.  EPSG:3857 appears to be one supported CRS.
