### ISSUE TITLE
the outlineWidth of ellipse can't work 

### ISSUE THREAD

**Issue by engineerhe** [AnalyticalGraphicsInc/cesium#8523]
![image](https://user-images.githubusercontent.com/39166385/72202033-bfbfa200-3495-11ea-8590-6e7e15229359.png)

**Comment by thw0rted** [comment]
Search this tracker for "outlineWidth" and you will find no fewer than a dozen reports of this problem.  The short version is that it's not Cesium's fault and there's nothing they can do to actually fix it.  I'm currently filing a new issue to talk about it on the docs.

**Comment by OmarShehata** [comment]
Thanks @thw0rted ! 

@engineerhe longer explanation here: https://github.com/AnalyticalGraphicsInc/cesium/issues/8577
