### ISSUE TITLE
glTF 2.0 models cause crash when skin does not explicitly point to a skeleton.

### ISSUE THREAD

**Issue by sanjeetsuhag** [AnalyticalGraphicsInc/cesium#8540]
glTF 2.0 allows for models with skins that don't directly refer to a skeleton. [Cesium_Man.glb](https://drive.google.com/open?id=1-4O_udJauSGHlIO3OY-woetd8EWMaQzZ) is validated by [glTF Validator](https://github.com/KhronosGroup/glTF-Validator/tree/2.0.0-dev.3.0) and is rendered in Babylon and Three.js, but causes an error in Cesium.

 The issue lies in [Source/Model.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/9082fc669034d7f71e206bee0d15afa39996d22d/Source/Scene/Model.js#L3632) where it's assumed that the skin will have a skeleton directly associated with it.

**Comment by emackey** [comment]
This is a fairly substantial discrepancy between Cesium and glTF's skinning specification.  The spec explicitly says that the skeleton is optional, but Cesium treats it as required.

I'm by no means a skinning expert, but it appears very difficult with the current glTF-Blender-IO project to export any kind of skinned mesh from Blender and get it to load correctly in Cesium, even if the model validates correctly and loads into Babylon and ThreeJS without issue.

All of the "working in Cesium" skinned models that I know of appear to have come through COLLADA2GLTF, not Blender.

**Comment by OmarShehata** [comment]
Is the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/8175 ?

**Comment by emackey** [comment]
Oh yeah, I had deja-vu but I couldn't find that one, thanks.
