### ISSUE TITLE
label background outline color and width don't  work

### ISSUE THREAD

**Issue by ShirlyNiego** [AnalyticalGraphicsInc/cesium#8552]
Sandcastle example: 
https://sandcastle.cesium.com/#c=bVFNT8JAEP0rm15akrq1IhCwEEP1RqKJUS+9LN2BbpjuNrvbIhr+u1sawoe+08yb914yMw3TpBGwBU2mRMKWpGBEXdKPAxf4+aFNlbRMSNB+7yGTmSQOnYuCtMIKMJRxHvx0oxaVMo5XkkyOkSnT1lVM9ulKq/IJ1hrABDejAY2H9/FwOApJf0zHg7sWvfCUhWwJ6ILO4ltY+LKO9V8LgYwDVoVgfnipMYXazlm+WWtVSz4hVtdwJVG1Rbfbp+C2mJD49v9xqlDp0y5tR+eL9+eTeN+V+/ZEXuglxu4QZh35KMpKaUtqjQGlkYWyQuauES3rfAOW5sa0tiQ6mhIuGiL4NPOuPpB5JEdmjJusasQ38Q2ZN0sip7+woWJcyPVLAxrZrpUU8WzRkZTSJHLtX5dVCpdMnyX+Ag

Browser:
chrome Version 79.0.3945.117 (Official Build) (64-bit)

Operating System:
windows 7

**Comment by OmarShehata** [comment]
You need to specify the style: `style : Cesium.LabelStyle.FILL_AND_OUTLINE,`. 

There's an example of this in the [Labels](https://sandcastle.cesium.com/index.html?src=Labels.html) Sandcastle.
