### ISSUE TITLE
Incorrect intersection with camera.pickEllipsoid on high DPI monitors

### ISSUE THREAD

**Issue by jrafidi** [AnalyticalGraphicsInc/cesium#8564]
Sandcastle example: 
https://sandcastle.cesium.com/#c=dVPfb5swEP5XPF4Ka2TaPk0KiTZFPEzK2qrtJk3ixcUXONXYyDZkaZX/fQckI2kZPJjz9+M+H3IrLGsRtmDZgmnYshU4bCr+q98LL/K+XBntBWqwF9E80y1pclGBFaQZxHyoD6DLQcOI9SVB3TvweGVaSLXkQsq0Be3X6DyRbLhpdO7R6DBibyzTrHuGpTPe1ucpV8J6+hL6JjztRWkoh+NblL6Mb/jVbAotAYvSd3B3KPaulRU76nWIW4C/x/zlQezCbX1k50Y7o4ArU4RZ8PDtdxZMQWTEjcUC9f9QiRb6Qx8Jk/7p48/109iiy/hn9zpmrClgqhTWzqCkmLPj+OG4GQ1K3LCwU35aLFijJWzox8qTcR/MlSrJ/GTQprCiLjHnG2uqf5PvrMb5nacmC1p1gb6RwD6z6y9XLGY/hC/5/Xd2ybJglgW09jzhJ2nRfJzInoFywN6mu5HV7d1tOo5oP/IyvY/mwSxInN8pWA7AV6xqYz1rrAo5jz1UNaUAFz83+Qt4njvXWSXxUZRIbBnKRRa8uxbUOlfCOUI2jVKP+ApZsExi4p/JlBESdXHXglVi11HK6+V62OScJzGVH1XeGPUs7InjXw

Browser:
Chrome 79.0.3945.117 

Operating System:
Mac OSX

On high DPI monitors (like Retina displays), the above sandcastle reports no intersection between a ray from the center of the screen to the earth, which is definitely incorrect.  On other monitors, there is an intersection.

**Comment by jrafidi** [comment]
User error: the correct width/height to use from the canvas is `clientWidth` and `clientHeight`.

**Comment by IanLilleyT** [comment]
Beat me to it! I'm going to update the `Ellipsoid.pickEllipsoid` documentation with an example so this doesn't cause confusion in the future.
