### ISSUE TITLE
Optimize tests

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#857]
We strive to keep our tests fast, so it is painless to run them often.  Our tests use to run in 30 seconds, but now take 45-50.

The time for each suite (group of tests) and spec (individual test) is listed when the tests are ran.  Find the hot spots and optimize them if possible - I'm talking about changing the test, not necessarily the engine code.  For example, the [PolygonCollection tests](http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FPolylineCollection) take 7-8 seconds alone. 

Sometimes we just need to change the amount of data used in a test, e.g., change 10,000 vertices to 10, or use a smaller image.  Be careful because sometimes a large amount of data is required to test certain code paths, for example, over 64K vertices.

Other times we need to reduce the granularity that we do something, e.g., create a context per suite, instead of per spec.  Again, be careful because we try to keep each test as isolated as possible.

Discuss ideas on the [forum](http://cesium.agi.com/forum.html) and open a small pull request before making big changes to get early feedback.

**Comment by mramato** [comment]
I vote we close this.  Since this issue was written over 2 years ago, overall test time has not increased (despite a large increase in code).  At some point we did a bunch of work on this, but given tests run in ~45 seconds on my 2 year old laptop I'm not sure it's worth keeping this issue open.

**Comment by pjcozzi** [comment]
I agree there is diminishing returns here.
