### ISSUE TITLE
OBB commit broke certain zoomTo's

### ISSUE THREAD

**Issue by loshjawrence** [AnalyticalGraphicsInc/cesium#8570]
@IanLilleyT 
This commit broke certain camera zoomTo's (throws a `normalized result is not a number`):

> 61bef7c016f5271318f0a530f1594c52470fb725 is the first bad commit
> commit 61bef7c016f5271318f0a530f1594c52470fb725
> Author: Ian Lilley
> Date:   Wed Dec 18 17:48:49 2019 -0500
> 
>     added large rectangle support to obb fromRectangle

[Example sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=rVbbbts4EP0VIi+WsSkl62LJThpsmmQBA226SIwUi7ooGImOuUuRKkk5cRb59x3qZtlxm5fVg8w5c+HMkHOsNVFozegjVeg9EvQRXVDNyhzfVZgzSCvxQgpDmKBqcIz+XQgEj+s+cHlPp0vCNT1uMUOVAsM/lVyzjKppGy5VlBj6RSqezWsTZ7gQL8OThViINeRwQZQBUyICyKNx2mKdmU6poGBRp4wr8aRWpSSnioCuAnEtgg6yaqzpk6Eic5roNVgLweWccapnQhc0NVJ9Yk9M2ORct03mhv4oqTa36YpmJYdoGb0vH25X8vHWEMO0YamGzY0q24QyMGcCdFL8UYrU/lqLr9+qag5pv3rfwGDZiM6waXVdCl7yzVw6DWafXgg0rQ+v65jzLoi82BslOIzjZOwHkyA6RqEXRcEkxtE48ZIoiEaABWEYJJGHEz+JJ0kwHvvD4+0eUjEqTLtHb/MqAaZoenh7D0eRH/pe5MdhMPHHx+idh8ewCmLfD70wCPxJWIFREMK2YRInwWQcT0b93e1TFoeiB3488uPATyYQPI78KlQIkcfeOLZhJiMfQCgrDMMkGY29IBnF/k70l3pZ3cKX6lAWom0+4pJk1aWgxpFFdTzDtn57uqbW7d1FXCiWM8PWVGOSZU5vonZuGgTt9bJUHHWjMpPihmpZqpTipZL5uQbrWdYmgUktD9vkbfZ2Vb+btDDMW7aBMcyZptisqHC216p/jK39dyWlwUYRoZdS5dsh/ESMYk8hnl1eXc9n879OXvvmMqO8tgO/Ns8u1kmvzXahqCmVaL1t723jYdKWJedVN+v5+b86DN2dosHKmGLqulymhK+kNtPE83xX26uduhkx5LK6zFJt3GZj7crSFKVpZfy3lmLQ3J9u+j/IUmRMPNxJXuZ0iioGsNRWc5vr/mTQHatvCnuWMofRbvZpHZEumEGQA9IypyiFLiMGfVvZtdCSU2QkAlaAt1kxjQqpmQ2/ELdEZCnRhlPbo7mU/J6oD6UxcPyDB+gpUApQ+esr0QTGXD44A1VTHs1QQRTJNYLTRGmpFDBCS7e2gkF7svbU2iTg2BreapGe0ZY4OqsO6pnB6Hf6sqja8irJBaCLX1d8N7v6slds7XSAXLeKNxl2gH7rqsVPIEBHd7DNAezZYkBCu/vss+yu9g2qtfE7dT+RLbg5BB5O5WeUa33Loh8epM2OdDjgyz6QlaqtFJb7Wko0TFM7KR0rXu3A+OPs+ur85vv15+urfgDLMVvJsJyec+50IKiru9p8d7wxJ97BCfnVOFdxj46PTrXZcHpWO/zO8kIqY2nIwRi+kPKCw7eQdu/L9B9glVRr63bqtk6nGVsjlr1fHO19fC2OUMqB/kFjqfKWPdPF0dmpC/Y7bvavC5r1eU0VJxtrshqdfaxBjPGpC+JrL1NX34v4Hw) 

I can provide the test tileset. The result should look like (a textureless single tile globe):
![image](https://user-images.githubusercontent.com/13598291/73281849-95bcee00-41be-11ea-90c4-dbbb4a3510d8.png)

**Comment by lilleyse** [comment]
@IanLilleyT it would be good to squeeze in this fix before the February release.
