### ISSUE TITLE
Assets not loading correctly

### ISSUE THREAD

**Issue by hijazikaram** [AnalyticalGraphicsInc/cesium#8586]
![image](https://user-images.githubusercontent.com/9812037/73662433-c6db6980-4669-11ea-9ac6-507549b3af9b.png)
 Running the latest cesium with my angular application. Was working, then suddenly assets started breaking. 
Angular.json file
`"assets": [
                            {
                                "glob": "**/*",
                                "input": "node_modules/cesium/Build/Cesium",
                                "output": "./assets/cesium"
                            }
                        ],
                        "styles": [
                            "client/styles.scss",
                            "node_modules/animate.css/animate.min.css"
                        ],
                        "scripts": [
                            "node_modules/cesium/Build/Cesium/Cesium.js"
                        ],`

**Comment by hijazikaram** [comment]
Could it be chrome version

**Comment by OmarShehata** [comment]
I believe you need to set the `CESIUM_BASE_URL` global variable, see https://github.com/AnalyticalGraphicsInc/cesium/issues/8327
