### ISSUE TITLE
Add ability to disable tracked entity behavior

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#8592]
When double clicking on an entity the viewer will automatically call `zoomTo` on the clicked entity. As far as I'm aware, the only way to disable this behavior is by listening to the trackedEntityChanged event and resetting that to undefined every time:

```
viewer.trackedEntityChanged.addEventListener(function(entity) {
    // Undo default behavior
    viewer.trackedEntity = undefined;
});
```

I think it would make sense to add a `trackEntitiesOnClick` boolean to the Viewer constructor in the same way that you can turn off `selectionIndicator` without having to listen for the event and turn it off in that same way. 

If we don't think this needs to be part of the library, I think it would be helpful to mention this as part of the doc, or as a doc code example, since it isn't obvious that this is how you'd disable this behavior.

**Comment by emackey** [comment]
I'm not claiming this is beautiful nor obvious API, but.......

```
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.dataSources.add(Cesium.CzmlDataSource.load('../../SampleData/simple.czml'));

// Remove double-click handler.
viewer.cesiumWidget.screenSpaceEventHandler.removeInputAction(
    Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
```

**Comment by mramato** [comment]
@emackey has the correct answer here.  You don't actually want to disable tracking, you want to disable the default double click behavior (which is what his code does).

**Comment by Jappan07** [comment]
When i use czml file for example to visualize satellites, it overides the current time in cesium js and shows the old time mentioned in czml file. I have tried using automaticallyTrackDataSourceClocks: false but it will also vanish the satellites. I want the current time to be shown with satellites moving just like here - http://www.orbitalpredictor.com/home/40697/
