### ISSUE TITLE
Sandcastle gists using deprecated API, angering the GitHubs

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#8593]
AGI is getting spammed with many of these messages a day, the last two days or so:

> Hi @ Cesium-Sandcastle,
>
> On February 5th, 2020 at 18:41 (UTC) your personal access token (getting gist) using Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.131 Safari/537.36 was used as part of a query parameter to access an endpoint through the GitHub API:
>
> [gist URI redacted]
>
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
>
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
>
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
>
> Thanks,
> The GitHub Team

**Comment by mramato** [comment]
As far as I can tell, this is the only spot that's using an access_token:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/CesiumSandcastle.js#L714

I assume you can add something like:
```
headers: {
"Authorization": "<access_token>"
}
```

to replace the query parameter, but I haven't tried it.
