### ISSUE TITLE
How to overlay terrain

### ISSUE THREAD

**Issue by chenguang1994** [AnalyticalGraphicsInc/cesium#8595]
cesium only support single terrain ,but i want to overlay terrain , now i have a world terrain( level 0-6),another Partial terrain(level 7-10),i want to load them together  as Imagery Layers.It seems impossible.I try to read sourcecode，there is a property ‘parentUrl’ in layer.json。 how to use it or modify sourcecode，I have no idea，can you help me. i use cesium 1.64

**Comment by OmarShehata** [comment]
Hey @chenguang1994, please use the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) for asking general questions and getting help. To keep things organized, we use GitHub issues for bug reports and feature requests.

For your case, I would try uploading your terrain to [Cesium ion](https://cesium.com/ion). This will let you combine multiple layers into one and load them into CesiumJS. If you're still having issues feel free to follow up in a new forum thread.
