### ISSUE TITLE
rotate 3dtile doesn't work in cesiumjs 1.66

### ISSUE THREAD

**Issue by peterchen2001** [AnalyticalGraphicsInc/cesium#8611]
Hi experts,

Below code snippet works in early cesium version, however the 3dtile disappear in cesiumjs 1.66, how to rotate 3dtile in new version?  thands in advance for any clues.

var m = tileset.modelMatrix;
    var m1 = Cesium.Matrix3.fromRotationX(Cesium.Math.toRadians(rotateXAngle));
    Cesium.Matrix4.multiplyByMatrix3(modelMatrix, m1, modelMatrix);
    tileset.modelMatrix = m;

**Comment by OmarShehata** [comment]
I believe this is an issue with older 3D Tilesets. There's a suggested source code fix here: https://github.com/AnalyticalGraphicsInc/cesium/pull/6755#issuecomment-425454485

Or you can upgrade your tileset as described here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7036#issuecomment-425146294
