### ISSUE TITLE
Create a small rectangle using one point

### ISSUE THREAD

**Issue by hijazikaram** [AnalyticalGraphicsInc/cesium#8617]
I have one point, whats the best way to draw a small rectangle with that point being the center point.

Camera Point

```
const cameraState = {
    x: -13734998.52033772
    y: -41230419.91157826
    z: 26215185.399910662
    heading: 6.283185307179586
    pitch: -1.568415825780305
    roll: 0
}

const destination = new Cesium.Cartesian3(
      cameraState.x,
      cameraState.y,
      cameraState.z
);
```

https://stackoverflow.com/questions/60266737/cesium-show-a-rectangle-from-1-point

**Comment by OmarShehata** [comment]
Please ask questions in the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). We use GitHub for tracking bug reports and feature requests.
