### ISSUE TITLE
Get rectangle of a current camera view

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#871]
From [this](https://groups.google.com/forum/?fromgroups#!topic/cesium-dev/jYlLEnyv7lM) thread (and other requests we've gotten), it would be convenient  to have a function on the camera that returns the currently rectangle being viewed.  In a perfect world we would be able to take terrain into account as well, but for now just the ellipsoid would be useful as well.

**Comment by danwild** [comment]
Any movement on this feature? The ol3-cesium project surely must be doing something similar under the hood for this.. http://openlayers.org/ol3-cesium/examples/sidebyside.html

**Comment by pjcozzi** [comment]
@danwild no update, we are focused on 3D Tiles right now.  In the meantime, perhaps @gberaudo can point you to the code in ol3-cesium.

**Comment by danwild** [comment]
Thanks @pjcozzi, might just have a bit more of a poke around ol3-cesium

**Comment by danwild** [comment]
Thanks @gberaudo, we ended up using a similar approach with canvas size and `Camera.pickEllipsoid` to get each of the corners. Just a side note/comment for anybody else taking this approach - make sure you take pixel ratio of the canvas.width/height into account (for retina screens etc.), that me tripped me up in testing ;)

**Comment by hpinkos** [comment]
This is definitely the most requested feature on the forum. Here are a few posts:

https://groups.google.com/forum/?hl=en#!topic/cesium-dev/2xmQ2ETqeyg
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/I8UcJ4_Hqj8
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/e2H7EefikAk
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/lZAr0L6Cq9s

**Comment by emackey** [comment]
[Another strategy](http://gis.stackexchange.com/questions/129903/cesium-3d-determining-the-map-scale-of-the-viewed-globe/144496#144496) is to dig into the currently loaded/requested tiles, the way Cesium Inspector does.  This is not as precise as the four-corner globe pick, and has other problems as well, but it does provide answer covering at least the whole visible surface even when space or sky is showing in the corners.

**Comment by hpinkos** [comment]
@mramato @pjcozzi can we close this issue now that we added the `Camera.computeViewRectangle` function in #3538?

**Comment by mramato** [comment]
Yes.  Since this is oft-requested (for right or wrong reasons) we should also add it to CHANGES for the next release (even though it went in 1.19.  I'll do that right in master.
