### ISSUE TITLE
Remove unnecessary DSFUN90 subtraction in reprojection code

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium#965]
I hacked it out to take a screenshot of what it looks like without it for a presentation, and found it doesn't make any difference at all.  That's probably because we're cutting off the reprojection before the limited precision available to the subtraction becomes a problem.

**Comment by mramato** [comment]
Is this still relevant?  Was it taken care of a part of #2277?

**Comment by pjcozzi** [comment]
Yes, this is still relevant.  See how the south argument is broken into `low` and `high` bits.  This is low-ish hanging fruit.

**Comment by ggetz** [comment]
@pjcozzi Should I also combine the low and high arguments and deprecate the old function?

**Comment by pjcozzi** [comment]
Yes, combine the low and high arguments.

Since this is all internal to Cesium (there's no public-facing API), it doesn't need to be deprecated; it is not a breaking change to our users.

**Comment by ggetz** [comment]
Ok, thanks.
